### ISSUE TITLE
Error logging API request

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#10108]
Metabase freezes when this log appears.

- Your browser and the version: Chrome/70.0.3538.102
- Your operating system: Ubuntu 18.04
- Your databases: MySQL, Postgres, SQL Server
- Metabase version: v0.32.8
- Metabase hosting environment: Linux/Debian 9
- Metabase internal database: Postgres

Logs:

stdout:
```
06-07 20:36:27 INFO middleware.exceptions :: Requisição cancelada antes de finalizar                                                                                                                
06-07 20:36:27 ERROR middleware.log :: Error logging API request                                                                                                               
java.lang.NullPointerException                                                                                                                                                                       
06-07 20:36:27 INFO middleware.exceptions :: Requisição cancelada antes de finalizar                                                                                                                   
06-07 20:36:27 ERROR middleware.log :: Error logging API request                                                                                                                                      
java.lang.NullPointerException
```

stderr:
```
Exception in thread "async-dispatch-8" java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
        at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:54)
        at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:74)
        at ring.util.servlet$make_output_stream$fn__61227.invoke(servlet.clj:89)
        at ring.util.servlet.proxy$java.io.FilterOutputStream$ff19274a.close(Unknown Source)
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
        at java.io.BufferedWriter.close(BufferedWriter.java:266)
        at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__60171$state_machine__11170__auto____60176$fn__60178.invoke(api_response.clj:87)
        at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__60171$state_machine__11170__auto____60176.invoke(api_response.clj:79)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__11188.invoke(ioc_macros.clj:986)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__6074$fn__6075.invoke(channels.clj:95)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "async-dispatch-2" java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
        at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:54)
        at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:74)
        at ring.util.servlet$make_output_stream$fn__61227.invoke(servlet.clj:89)
        at ring.util.servlet.proxy$java.io.FilterOutputStream$ff19274a.close(Unknown Source)
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
        at java.io.BufferedWriter.close(BufferedWriter.java:266)
        at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__60171$state_machine__11170__auto____60176$fn__60178.invoke(api_response.clj:87)
        at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__60171$state_machine__11170__auto____60176.invoke(api_response.clj:79)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__11188.invoke(ioc_macros.clj:986)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__6074$fn__6075.invoke(channels.clj:95)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "async-dispatch-6" java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
        at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:54)
        at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:74)
        at ring.util.servlet$make_output_stream$fn__61227.invoke(servlet.clj:89)
        at ring.util.servlet.proxy$java.io.FilterOutputStream$ff19274a.close(Unknown Source)
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
        at java.io.BufferedWriter.close(BufferedWriter.java:266)
        at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__60171$state_machine__11170__auto____60176$fn__60178.invoke(api_response.clj:87)
        at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__60171$state_machine__11170__auto____60176.invoke(api_response.clj:79)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__11188.invoke(ioc_macros.clj:986)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__6074$fn__6075.invoke(channels.clj:95)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by PauloHFM** [comment]
This happens to me when anybody needs to download a big  CSV or xlsx file.

Exact same error 
08-23 22:50:10 INFO middleware.exceptions :: Requisição cancelada antes de finalizar
08-23 22:50:10 ERROR middleware.log :: Error logging API request
java.lang.NullPointerException

and 

08-23 22:51:03 INFO metabase.core :: Metabase Shutting Down ...
...
08-23 22:51:03 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
...
08-23 22:51:13 INFO metabase.core :: Metabase Shutdown COMPLETE

What's happening?

**Comment by flamber** [comment]
Hi @PauloHFM 
It sounds like you're out-of-memory.
How much RAM does your server have - or how much have you allowed Docker/Java to consume?
Which database are you querying?
It sounds like what #9614 was trying to solve, but the fix wasn't completed.

**Comment by doubler84** [comment]
I have the same error:

- Metabase 0.33.7.3
- DB PostgreSQL

**Comment by flamber** [comment]
Closing this, since 0.35.0 now uses streaming responses and a fully async requests. See #11832
If you're still experiencing problems, then please comment with details and it will be reopened.

**Comment by gilnei-ferraz** [comment]
I had a similar error using Metabase 0.36.3 in Rancher / Heml. I initially checked the nginx reverse proxy timeout settings, but they were all correct. So I activated the option to automatically redirect all requests to HTTPS option and I didn't notice these errors in the log anymore.
