### ISSUE TITLE
`metabase.db already exists` on mounted volume in docker

### ISSUE THREAD

**Issue by amir5121** [metabase/metabase#10116]
I'm trying to move from metabase.jar file deployment to a dockerized version. Since i need the questions and dashboards i am mounting the `metabase.mv.db` as `metabse.db`. Using docker-compose to run metabase [following](https://metabase.com/docs/v0.32.8/operations-guide/running-metabase-on-docker.html) 
I made a docker-compose.yml
```
version: '3.7'

services:
  metabase:
    image: metabase/metabase
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase-data/:/metabase-data
    ports:
      - "3000:3000"
```
since i'll be moving it to docker stack environment there will be a docker-stack.yml as followed (for those whom might be intrested)

```
version: '3.7'

services:
  metabase:
    image: metabase/metabase
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '4'
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 5s
    volumes:
      - ./metabase-data/:/metabase-data
    ports:
      - "3000:3000"
```

and running `docker-compose up` will result in

```
Attaching to metabase_metabase_1_abb3e6fe7ef8
mkdir: can't create directory '/metabase-data/metabase.db': File exists
06-09 14:02:42 [1mINFO metabase.util[0m :: Loading Metabase...
06-09 14:02:42 [1mINFO metabase.util[0m :: Maximum memory available to JVM: 3.5 GB
06-09 14:02:45 [1mINFO util.encryption[0m :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
 For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
06-09 14:02:47 [1mINFO metabase.driver[0m :: [34mRegistered abstract driver :sql[0m  🚚
06-09 14:02:51 [1mINFO metabase.core[0m :: Starting Metabase in STANDALONE mode
06-09 14:02:51 [1mINFO metabase.server[0m :: Launching Embedded Jetty Webserver with config: 
 {:port 3000, :host "0.0.0.0"}

06-09 14:02:51 [1mINFO metabase.core[0m :: Starting Metabase version v0.32.8 (16be46d release-0.32.x) ...
06-09 14:02:51 [1mINFO metabase.core[0m :: System timezone is 'GMT' ...
06-09 14:02:51 [1mINFO metabase.plugins[0m :: [35mLoading plugins in /plugins...[0m
[32mExtract file /modules/vertica.metabase-driver.jar -> /plugins/vertica.metabase-driver.jar took 3 ms[0m
[32mExtract file /modules/sqlserver.metabase-driver.jar -> /plugins/sqlserver.metabase-driver.jar took 12 ms[0m
[32mExtract file /modules/sqlite.metabase-driver.jar -> /plugins/sqlite.metabase-driver.jar took 22 ms[0m
[32mExtract file /modules/sparksql.metabase-driver.jar -> /plugins/sparksql.metabase-driver.jar took 285 ms[0m
[32mExtract file /modules/snowflake.metabase-driver.jar -> /plugins/snowflake.metabase-driver.jar took 79 ms[0m
[32mExtract file /modules/redshift.metabase-driver.jar -> /plugins/redshift.metabase-driver.jar took 10 ms[0m
[32mExtract file /modules/presto.metabase-driver.jar -> /plugins/presto.metabase-driver.jar took 801 µs[0m
[32mExtract file /modules/oracle.metabase-driver.jar -> /plugins/oracle.metabase-driver.jar took 514 µs[0m
[32mExtract file /modules/mongo.metabase-driver.jar -> /plugins/mongo.metabase-driver.jar took 27 ms[0m
[32mExtract file /modules/googleanalytics.metabase-driver.jar -> /plugins/googleanalytics.metabase-driver.jar took 3 ms[0m
[32mExtract file /modules/google.metabase-driver.jar -> /plugins/google.metabase-driver.jar took 12 ms[0m
[32mExtract file /modules/druid.metabase-driver.jar -> /plugins/druid.metabase-driver.jar took 2 ms[0m
[32mExtract file /modules/bigquery.metabase-driver.jar -> /plugins/bigquery.metabase-driver.jar took 2 ms[0m
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :presto...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered driver :presto[0m (parents: #{:sql}) 🚚
06-09 14:02:52 [1mINFO plugins.dependencies[0m :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
06-09 14:02:52 [1mINFO plugins.dependencies[0m :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
06-09 14:02:52 [1mINFO plugins.dependencies[0m :: [33mPlugins with unsatisfied deps: ["Metabase BigQuery Driver"][0m
06-09 14:02:52 [1mDEBUG plugins.classloader[0m :: Setting current thread context classloader to NEWLY CREATED classloader clojure.lang.DynamicClassLoader@695d0adc...
06-09 14:02:52 [1mINFO plugins.dependencies[0m :: [31mMetabase cannot initialize plugin Metabase Oracle Driver due to required dependencies.[0m Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.

06-09 14:02:52 [1mINFO plugins.dependencies[0m :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
06-09 14:02:52 [1mINFO plugins.dependencies[0m :: [33mPlugins with unsatisfied deps: ["Metabase BigQuery Driver" "Metabase Oracle Driver"][0m
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :google...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered abstract driver :google[0m  🚚
06-09 14:02:52 [1mINFO plugins.dependencies[0m :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
06-09 14:02:52 [1mDEBUG plugins.initialize[0m :: [33mDependencies satisfied; these plugins will now be loaded: ["Metabase BigQuery Driver"][0m
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :bigquery...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered driver :bigquery[0m (parents: #{:sql :google}) 🚚
06-09 14:02:52 [1mINFO plugins.dependencies[0m :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
06-09 14:02:52 [1mINFO plugins.dependencies[0m :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :googleanalytics...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered driver :googleanalytics[0m (parents: #{:google}) 🚚
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :mongo...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered driver :mongo[0m  🚚
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :hive-like...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered abstract driver :sql-jdbc[0m (parents: :sql) 🚚
[32mLoad driver :sql-jdbc took 45 ms[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered abstract driver :hive-like[0m (parents: #{:sql-jdbc}) 🚚
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :sparksql...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered driver :sparksql[0m (parents: #{:hive-like}) 🚚
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :sqlserver...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered driver :sqlserver[0m (parents: #{:sql-jdbc}) 🚚
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :redshift...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered driver :postgres[0m (parents: :sql-jdbc) 🚚
[32mLoad driver :postgres took 22 ms[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered driver :redshift[0m (parents: #{:postgres}) 🚚
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :druid...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered driver :druid[0m  🚚
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :snowflake...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered driver :snowflake[0m (parents: #{:sql-jdbc}) 🚚
06-09 14:02:52 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :sqlite...[0m
06-09 14:02:52 [1mINFO metabase.driver[0m :: [34mRegistered driver :sqlite[0m (parents: #{:sql-jdbc}) 🚚
06-09 14:02:52 [1mINFO plugins.dependencies[0m :: [31mMetabase cannot initialize plugin Metabase Vertica Driver due to required dependencies.[0m Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

06-09 14:02:52 [1mINFO plugins.dependencies[0m :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
06-09 14:02:52 [1mINFO plugins.dependencies[0m :: [33mPlugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver"][0m
06-09 14:02:53 [1mINFO metabase.driver[0m :: [34mRegistered driver :h2[0m (parents: :sql-jdbc) 🚚
[32mLoad driver :h2 took 18 ms[0m
06-09 14:02:53 [1mINFO metabase.driver[0m :: [34mRegistered driver :mysql[0m (parents: :sql-jdbc) 🚚
[32mLoad driver :mysql took 24 ms[0m
06-09 14:02:53 [1mINFO metabase.core[0m :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
06-09 14:02:53 [1mWARN metabase.db[0m :: [31mWARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. See https://metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres for more information.[0m
06-09 14:02:53 [1mINFO metabase.db[0m :: [36mVerifying h2 Database Connection ...[0m
06-09 14:02:53 [1mINFO metabase.driver[0m :: [33mInitializing driver :sql...[0m
06-09 14:02:53 [1mINFO metabase.driver[0m :: [33mInitializing driver :sql-jdbc...[0m
06-09 14:02:53 [1mINFO metabase.driver[0m :: [33mInitializing driver :h2...[0m
org.h2.message.DbException: Log file error: "/metabase-data/metabase.db/metabase.db.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/metabase-data/metabase.db (a file with this name already exists)"" [90062-197]" [90034-197]
org.h2.message.DbException: Log file error: "/metabase-data/metabase.db/metabase.db.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/metabase-data/metabase.db (a file with this name already exists)"" [90062-197]" [90034-197]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.TraceSystem.logWritingError(TraceSystem.java:289)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:310)
	at org.h2.message.TraceSystem.writeFile(TraceSystem.java:258)
	at org.h2.message.TraceSystem.write(TraceSystem.java:242)
	at org.h2.message.Trace.error(Trace.java:196)
	at org.h2.engine.Database.openDatabase(Database.java:314)
	at org.h2.engine.Database.<init>(Database.java:280)
	at org.h2.engine.Engine.openSession(Engine.java:66)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1093)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1142)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:123)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:118)
	at metabase.driver.sql_jdbc$fn__62839.invokeStatic(sql_jdbc.clj:39)
	at metabase.driver.sql_jdbc$fn__62839.invoke(sql_jdbc.clj:38)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__18037.invoke(util.clj:30)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Log file error: "/metabase-data/metabase.db/metabase.db.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/metabase-data/metabase.db (a file with this name already exists)"" [90062-197]" [90034-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 41 more
Caused by: org.h2.message.DbException: Error while creating file "/metabase-data/metabase.db (a file with this name already exists)" [90062-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:264)
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:42)
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:307)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:300)
	... 38 more
Caused by: org.h2.jdbc.JdbcSQLException: Error while creating file "/metabase-data/metabase.db (a file with this name already exists)" [90062-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 44 more
06-09 14:02:53 [1mERROR metabase.core[0m :: Metabase Initialization FAILED
java.lang.Exception: org.h2.jdbc.JdbcSQLException: Error while creating file "/metabase-data/metabase.db (a file with this name already exists)" [90062-197]
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:34)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:18)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.lang.Var.invoke(Var.java:393)
	at metabase.db$verify_db_connection$fn__16148.invoke(db.clj:403)
	at metabase.db$verify_db_connection.invokeStatic(db.clj:401)
	at metabase.db$verify_db_connection.invoke(db.clj:394)
	at metabase.db$verify_db_connection.invokeStatic(db.clj:397)
	at metabase.db$verify_db_connection.invoke(db.clj:394)
	at metabase.db$setup_db_BANG_$fn__16165.invoke(db.clj:467)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:676)
	at metabase.util$do_with_us_locale.invoke(util.clj:662)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:466)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:460)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:77)
	at metabase.core$init_BANG_.invoke(core.clj:56)
	at metabase.core$start_normally.invokeStatic(core.clj:123)
	at metabase.core$start_normally.invoke(core.clj:117)
	at metabase.core$_main.invokeStatic(core.clj:143)
	at metabase.core$_main.doInvoke(core.clj:138)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: org.h2.jdbc.JdbcSQLException: Error while creating file "/metabase-data/metabase.db (a file with this name already exists)" [90062-197]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at clojure.core$deref_future.invokeStatic(core.clj:2302)
	at clojure.core$future_call$reify__8439.deref(core.clj:6974)
	at clojure.core$deref.invokeStatic(core.clj:2324)
	at clojure.core$deref.invoke(core.clj:2306)
	at metabase.util$deref_with_timeout.invokeStatic(util.clj:328)
	at metabase.util$deref_with_timeout.invoke(util.clj:324)
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:29)
	... 24 more
Caused by: org.h2.jdbc.JdbcSQLException: Error while creating file "/metabase-data/metabase.db (a file with this name already exists)" [90062-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:264)
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:42)
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:307)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:74)
	at org.h2.engine.Database.getPageStore(Database.java:2538)
	at org.h2.engine.Database.open(Database.java:709)
	at org.h2.engine.Database.openDatabase(Database.java:286)
	at org.h2.engine.Database.<init>(Database.java:280)
	at org.h2.engine.Engine.openSession(Engine.java:66)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1093)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1142)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:123)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:118)
	at metabase.driver.sql_jdbc$fn__62839.invokeStatic(sql_jdbc.clj:39)
	at metabase.driver.sql_jdbc$fn__62839.invoke(sql_jdbc.clj:38)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__18037.invoke(util.clj:30)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
06-09 14:02:53 [1mINFO metabase.core[0m :: Metabase Shutting Down ...
06-09 14:02:53 [1mINFO metabase.server[0m :: Shutting Down Embedded Jetty Webserver
06-09 14:02:53 [1mINFO metabase.core[0m :: Metabase Shutdown COMPLETE
[36mmetabase_metabase_1_abb3e6fe7ef8 exited with code 1
[0m
```

Is there something that i am missing, how can i resolve this?

**Comment by amir5121** [comment]
Okay i found the problem i should copy paste the `metabase.mv.db` after the metabase has been initialized once and then everything will work as expected

**Comment by r-martins** [comment]
Thanks for the hint @amir5121 .
My problem was that I was still trying to ser MB_DB_FILE as .db.mv.db instead of just `.db` (which is the correct).
