### ISSUE TITLE
Enabling SSL causes nullPointerException

### ISSUE THREAD

**Issue by hanzo2001** [metabase/metabase#10355]
**Describe the bug**
After enabling SSL through environment variables, the metabase process fails to start up.

**Logs**
```
07-16 13:03:11 INFO metabase.core :: Starting Metabase in STANDALONE mode
org.eclipse.jetty.ssl.password : 07-16 13:03:11 INFO metabase.server :: Launching Embedded Jetty Webserver with config: 
 {:port 3001, :host "127.0.0.1", :ssl? true, :ssl-port 3000, :keystore "/opt/metabase/file.jks"}

07-16 13:03:11 ERROR metabase.core :: Metabase Initialization FAILED
java.lang.NullPointerException
        at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:1185)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:362)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:250)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:94)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:282)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:394)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at metabase.server$start_web_server_BANG_.invokeStatic(server.clj:80)
        at metabase.server$start_web_server_BANG_.invoke(server.clj:68)
        at metabase.core$start_normally.invokeStatic(core.clj:120)
        at metabase.core$start_normally.invoke(core.clj:116)
        at metabase.core$_main.invokeStatic(core.clj:142)
        at metabase.core$_main.doInvoke(core.clj:137)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
```

**To Reproduce**
1. Add the environment variables to the execution
```bash
MB_JETTY_SSL="1"
MB_JETTY_SSL_Port="3000"
MB_JETTY_SSL_Keystore="file.jks"
MB_JETTY_SSL_keystore_Password="password"
```
2. Create the keystore where configured.
3. Restart the Metabase process.
4. Watch the logs

**Expected behavior**
A normal process listening on the defined port with SSL enabled.

**Screenshots**
None available.

**Information about your Metabase Installation:**
- Your browser and the version: irrelevant

- Your operating system: Ubuntu Server Bionic 18.04.2 LTS

- Your databases: irrelevant

- Metabase version: 0.32.9

- Metabase hosting environment: Ubuntu 18

- Metabase internal database: irrelevant (H2)

**Severity**
Secure communications are an absolute necessity. My current proxy solution is being removed and will not be replaced.

**Additional context**
I am quite positive this issue has more to do with Jetty than Metabase.
I created the keystore using a set of preexisting certificates I have. I split the certificates from the private key out of the pem file, concatenated the certs, generated a pkcs12 store and constructed my JKS keystore. Both the key and the keystore have a password. I kept them both the same because of recommendations. Here are the most relevant commands just in case.
```bash
openssl pkcs12 -export \
	-in certs.pem \
	-inkey key.pem \
	-name "$FRIENDLY_NAME" \
	-out certs.p12 \
	-passout pass:"$PASS"
keytool -importkeystore \
	-srckeystore certs.p12 \
	-srcstoretype pkcs12 \
	-destkeystore file.jks \
	-deststoretype JKS \
	-deststorepass "$PASS" \
	-srcstorepass "$PASS"
```
I wanted to contact Jetty directly but I don't know the Jetty version inside my Metabase distribution.

**Comment by flamber** [comment]
Hi @hanzo2001 
Metabase 0.32.9 uses Jetty 9.4.15: https://github.com/metabase/metabase/blob/v0.32.9/project.clj#L120
Since you're placing Jetty HTTPS on the same port as HTTP, are you also setting `MB_JETTY_PORT` to something different from `3000`?
https://metabase.com/docs/latest/operations-guide/start.html#customizing-the-metabase-jetty-webserver

**Comment by hanzo2001** [comment]
Hi @flamber 
I moved the HTTP port to 3001. This can also be seen in the logs. Sorry I didn't mention it.
```
{:port 3001, :host "127.0.0.1", :ssl? true, :ssl-port 3000, :keystore "/opt/metabase/file.jks"}
```

**Comment by flamber** [comment]
@hanzo2001 Overlooked the `:port 3001`. If you can reproduce your issue directly with Jetty, then you should file an issue with them. But I've always used a reverse proxy for handling certificates, so I don't know much about Jetty's SSL.

**Comment by hanzo2001** [comment]
I cannot believe it! I found the issue

`MB_JETTY_SSL_keystore_Password="password"` is not the same as
`MB_JETTY_SSL_Keystore_Password="password"`

I do not understand mixing environment vars uppercase and Camel+Snake case but I didn't program the thing (clojure I guess?)

This issue is closed

**Comment by flamber** [comment]
@camsaul Are env vars case sensitive? If so, then PR #10214 might cause more problems.

**Comment by mazameli** [comment]
Dunno if you saw @flamber's question on this, @camsaul — are the envvars in this situation case-sensitive?
