### ISSUE TITLE
metabase fails to start with java.util.zip.ZipError: zip END header not found

### ISSUE THREAD

**Issue by mmahut** [metabase/metabase#10532]
**Describe the bug**

Metabase fails to start after installation, when run, it exists with ``java.util.zip.ZipError: zip END header not found`` backtrace.

**Logs**
```
   13.474997] metabase[670]: 08-09 13:37:34 DEBUG plugins.classloader :: Using NEWLY CREATED classloader as shared context classloader: clojure.lang.DynamicClassLoader@367795c7
[   13.478290] metabase[670]: 08-09 13:37:34 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@367795c7...
[   14.100778] metabase[670]: 08-09 13:37:34 INFO metabase.util :: Loading Metabase...
[   14.107013] metabase[670]: 08-09 13:37:34 INFO metabase.util :: Maximum memory available to JVM: 483.4 MB
[   25.152490] metabase[670]: 08-09 13:37:45 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
[   25.154757] metabase[670]:  For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
[   26.986093] nscd[727]: 727 checking for monitored file `/etc/netgroup': No such file or directory
[   36.844712] metabase[670]: 08-09 13:37:57 INFO metabase.driver :: Registered abstract driver :sql  🚚
[   49.054951] metabase[670]: 08-09 13:38:09 INFO metabase.core :: Starting Metabase in STANDALONE mode
[   49.375550] metabase[670]: 08-09 13:38:10 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
[   49.378958] metabase[670]:  {:port 3000}
[   49.740491] metabase[670]: 08-09 13:38:10 INFO metabase.core :: Starting Metabase version v0.32.10 (5d40681 release-0.32.x) ...
[   49.748504] metabase[670]: 08-09 13:38:10 INFO metabase.core :: System timezone is 'GMT' ...
[   49.794126] metabase[670]: 08-09 13:38:10 WARN metabase.plugins :: Metabase cannot use the plugins directory /plugins
[   49.803604] metabase[670]:  Please make sure the directory exists and that Metabase has permission to write to it. You can change the directory Metabase uses for modules by setting the environment variable MB_PLUGINS_DIR. Falling back to a temporary directory for now.
[   49.815972] metabase[670]: java.nio.file.AccessDeniedException: /plugins
[   49.820875] metabase[670]: 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
[   49.823561] metabase[670]: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[   49.830838] metabase[670]: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[   49.841808] metabase[670]: 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
[   49.849752] metabase[670]: 	at java.nio.file.Files.createDirectory(Files.java:674)
[   49.854793] metabase[670]: 	at metabase.plugins.files$create_dir_if_not_exists_BANG_.invokeStatic(files.clj:63)
[   49.858540] metabase[670]: 	at metabase.plugins.files$create_dir_if_not_exists_BANG_.invoke(files.clj:59)
[   49.865184] metabase[670]: 	at metabase.plugins$fn__65940$fn__65941.invoke(plugins.clj:26)
[   49.873326] metabase[670]: 	at clojure.lang.Delay.deref(Delay.java:42)
[   49.876661] metabase[670]: 	at clojure.core$deref.invokeStatic(core.clj:2320)
[   49.884605] metabase[670]: 	at clojure.core$deref.invoke(core.clj:2306)
[   49.888406] metabase[670]: 	at metabase.plugins$plugins_dir.invokeStatic(plugins.clj:47)
[   49.891627] metabase[670]: 	at metabase.plugins$plugins_dir.invoke(plugins.clj:47)
[   49.898120] metabase[670]: 	at metabase.plugins$load_plugins_BANG_.invokeStatic(plugins.clj:134)
[   49.903670] metabase[670]: 	at metabase.plugins$load_plugins_BANG_.invoke(plugins.clj:121)
[   49.909444] metabase[670]: 	at metabase.core$init_BANG_.invokeStatic(core.clj:67)
[   49.913753] metabase[670]: 	at metabase.core$init_BANG_.invoke(core.clj:55)
[   49.918678] metabase[670]: 	at metabase.core$start_normally.invokeStatic(core.clj:122)
[   49.923366] metabase[670]: 	at metabase.core$start_normally.invoke(core.clj:116)
[   49.926874] metabase[670]: 	at metabase.core$_main.invokeStatic(core.clj:142)
[   49.929589] metabase[670]: 	at metabase.core$_main.doInvoke(core.clj:137)
[   49.939814] metabase[670]: 	at clojure.lang.RestFn.invoke(RestFn.java:397)
[   49.945866] metabase[670]: 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
[   49.949878] metabase[670]: 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
[   49.953551] metabase[670]: 	at metabase.core.main(Unknown Source)
[   49.957587] metabase[670]: 08-09 13:38:10 INFO metabase.plugins :: Loading plugins in /tmp...
[   50.413304] metabase[670]: 08-09 13:38:11 ERROR metabase.core :: Metabase Initialization FAILED
[   50.414819] metabase[670]: java.util.zip.ZipError: zip END header not found
[   50.417564] metabase[670]: 	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
[   50.420519] metabase[670]: 	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021)
[   50.423485] metabase[670]: 	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030)
[   50.427187] metabase[670]: 	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
[   50.431895] metabase[670]: 	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:139)
[   50.436093] metabase[670]: 	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:390)
[   50.438639] metabase[670]: 	at metabase.plugins.files$file_exists_in_archive_QMARK_.invokeStatic(files.clj:134)
[   50.442325] metabase[670]: 	at metabase.plugins.files$file_exists_in_archive_QMARK_.doInvoke(files.clj:131)
[   50.447311] metabase[670]: 	at clojure.lang.RestFn.invoke(RestFn.java:423)
[   50.452659] metabase[670]: 	at metabase.plugins$has_manifest_QMARK_.invokeStatic(plugins.clj:107)
[   50.458128] metabase[670]: 	at metabase.plugins$has_manifest_QMARK_.invoke(plugins.clj:106)
[   50.462482] metabase[670]: 	at clojure.core$sort_by$fn__5978.invoke(core.clj:3131)
[   50.467654] metabase[670]: 	at clojure.lang.AFunction.compare(AFunction.java:51)
[   50.471664] metabase[670]: 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
[   50.474266] metabase[670]: 	at java.util.TimSort.sort(TimSort.java:220)
[   50.477744] metabase[670]: 	at java.util.Arrays.sort(Arrays.java:1438)
[   50.483434] metabase[670]: 	at clojure.core$sort.invokeStatic(core.clj:3115)
[   50.489315] metabase[670]: 	at clojure.core$sort_by.invokeStatic(core.clj:3119)
[   50.494670] metabase[670]: 	at clojure.core$sort_by.invokeStatic(core.clj:3119)
[   50.498053] metabase[670]: 	at clojure.core$sort_by.invoke(core.clj:3119)
[   50.501452] metabase[670]: 	at metabase.plugins$init_plugins_BANG_.invokeStatic(plugins.clj:115)
[   50.506224] metabase[670]: 	at metabase.plugins$init_plugins_BANG_.invoke(plugins.clj:109)
[   50.508527] metabase[670]: 	at metabase.plugins$load_plugins_BANG_.invokeStatic(plugins.clj:137)
[   50.514493] metabase[670]: 	at metabase.plugins$load_plugins_BANG_.invoke(plugins.clj:121)
[   50.518746] metabase[670]: 	at metabase.core$init_BANG_.invokeStatic(core.clj:67)
[   50.525146] metabase[670]: 	at metabase.core$init_BANG_.invoke(core.clj:55)
[   50.531126] metabase[670]: 	at metabase.core$start_normally.invokeStatic(core.clj:122)
[   50.535505] metabase[670]: 	at metabase.core$start_normally.invoke(core.clj:116)
[   50.537531] metabase[670]: 	at metabase.core$_main.invokeStatic(core.clj:142)
[   50.540770] metabase[670]: 	at metabase.core$_main.doInvoke(core.clj:137)
[   50.547536] metabase[670]: 	at clojure.lang.RestFn.invoke(RestFn.java:397)
[   50.553912] metabase[670]: 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
[   50.561494] metabase[670]: 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
[   50.566074] metabase[670]: 	at metabase.core.main(Unknown Source)
[   50.576335] metabase[670]: 08-09 13:38:11 INFO metabase.core :: Metabase Shutting Down ...
[   50.579068] metabase[670]: 08-09 13:38:11 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
[   50.584517] metabase[670]: 08-09 13:38:11 INFO metabase.core :: Metabase Shutdown COMPLETE
```

**To Reproduce**
1. Install v0.32.10 jar
2. Try to run it.

**Information about your Metabase Installation:**

NixOS server with Metabase version v0.32.10 (5d40681 release-0.32.x).

**Comment by flamber** [comment]
Hi @mmahut Did you find a solution to your problem? Then please write/link it here. It helps others.

**Comment by mmahut** [comment]
@flamber I thought about it, but it's just PEBKAC - my data directory had wrong permissions. :)
