### ISSUE TITLE
Unable to migrate from H2 to Postgres on 0.32.9

### ISSUE THREAD

**Issue by jane-booky** [metabase/metabase#10579]
**Describe the bug**
Metabase `load-from-h2` fails at removing `CONSTRAINTS` during migration

**Logs**
```
[ec2-user] $ java -jar metabase.jar load-from-h2
08-14 10:16:57 DEBUG plugins.classloader :: Using NEWLY CREATED classloader as shared context classloader: clojure.lang.DynamicClassLoader@ceb4bd2
08-14 10:16:57 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@ceb4bd2...
08-14 10:16:57 INFO metabase.util :: Loading Metabase...
08-14 10:16:57 INFO metabase.util :: Maximum memory available to JVM: 481.4 MB
08-14 10:17:04 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
08-14 10:17:11 INFO metabase.driver :: Registered abstract driver :sql  🚚
08-14 10:17:20 INFO metabase.db :: Verifying postgres Database Connection ...
08-14 10:17:21 INFO metabase.driver :: Registered abstract driver :sql-jdbc (parents: :sql) 🚚
Load driver :sql-jdbc took 18 ms
08-14 10:17:21 INFO metabase.driver :: Registered driver :postgres (parents: :sql-jdbc) 🚚
Load driver :postgres took 76 ms
08-14 10:17:21 INFO metabase.driver :: Initializing driver :sql...
08-14 10:17:21 INFO metabase.driver :: Initializing driver :sql-jdbc...
08-14 10:17:21 INFO metabase.driver :: Initializing driver :postgres...
08-14 10:17:21 INFO metabase.db :: Verify Database Connection ...  ✅
08-14 10:17:21 INFO metabase.db :: Running Database Migrations...
08-14 10:17:21 INFO metabase.db :: Setting up Liquibase...
08-14 10:17:21 INFO metabase.db :: Liquibase is ready.
08-14 10:17:21 INFO metabase.db :: Checking if Database has unrun migrations...
08-14 10:17:24 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
08-14 10:17:24 INFO metabase.db :: Migration lock is cleared. Running migrations...
08-14 10:17:26 INFO metabase.db :: Database Migrations Current ...  ✅
Application database setup took 5 s
Temporarily disabling DB constraints...
org.postgresql.util.PSQLException: ERROR: syntax error at or near "CONSTRAINT"
  Position: 36
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
        at clojure.java.jdbc$db_do_execute_prepared_statement$fn__14516.invoke(jdbc.clj:1031)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:842)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1030)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1024)
        at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1062)
        at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1042)
        at clojure.java.jdbc$execute_BANG_$execute_helper__14590.invoke(jdbc.clj:1446)
        at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1448)
        at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1417)
        at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1438)
        at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1417)
        at metabase.cmd.load_from_h2$fn__62709.invokeStatic(load_from_h2.clj:188)
        at metabase.cmd.load_from_h2$fn__62709.invoke(load_from_h2.clj:179)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__62741.invoke(load_from_h2.clj:246)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:242)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:231)
        at clojure.lang.Var.invoke(Var.java:384)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:38)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:31)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:34)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:31)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.cmd$run_cmd$fn__62196.invoke(cmd.clj:119)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:119)
        at metabase.cmd$run_cmd.invoke(cmd.clj:115)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.core$run_cmd.invokeStatic(core.clj:132)
        at metabase.core$run_cmd.invoke(core.clj:130)
        at metabase.core$_main.invokeStatic(core.clj:141)
        at metabase.core$_main.doInvoke(core.clj:137)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Command failed with exception: ERROR: syntax error at or near "CONSTRAINT"
  Position: 36
```

**To Reproduce**
1. `source .env` (.env contains vars I followed from here: https://metabase.com/docs/v0.14.1/operations-guide/start.html)
2. Ran `java -jar metabase.jar`

**Expected behavior**
Successful migration. I actually have successfully tried the migration on my local machine (windows), with the same h2 db files with raw database created via pgadmin and it migration ran fine (there was however some missing data after I reran the instance that stems from the migration)

**Setup**
- I am running this under ec2 t2.small instance with freshly installed postgres ( ran on aws for trial / feedback from other business teams)
- I did the setup of my postgres by following the steps here: https://www.quora.com/How-can-I-install-PostgreSQL-on-AWS-EC2-and-how-can-I-access-that . Made a few tweaks like retain 127.0.0.1 so metabase can connect properly - due to errors encountered prior to this. Created new database after encountering prev errors in case it had something to do with the constraint.
- I created my raw metabase via psql  `CREATE DATABASE metabase;`
- Metabase version: 0.32.9

Thanks!

**Comment by camsaul** [comment]
Hi @jacktasia, what version of Postgres are you using?

**Comment by jacktasia** [comment]
> Hi @jacktasia, what version of Postgres are you using?

I am guessing this question was for @jane-booky ?

**Comment by camsaul** [comment]
Oops. Sorry @jacktasia. I think I auto-completed the wrong username. 

@jane-booky what version of Postgres are you using?

**Comment by jane-booky** [comment]
Hi @camsaul , I'm using Postgres 9.2.24, default of the instance. I actually just noticed that is quite an old version compared to where I ran the migration successfully on my windows which uses postgres 11.4.

**Comment by flamber** [comment]
Hi @jane-booky 
Looking at the documentation, it seems like you need Postgres 9.4+, since some migration commands are only available from that version:
https://github.com/metabase/metabase/blob/master/docs/operations-guide/migrating-from-h2.md#notes

**Comment by jane-booky** [comment]
Thanks @flamber , sorry I missed this out. Was only referencing from the site documentation (https://metabase.com/docs/v0.14.1/operations-guide/start.html).

**Comment by flamber** [comment]
@jane-booky You were looking at the right documentation - the website is the official documentation - it's just maintained here on Github. The reason I linked to the Github version was because I just reviewed it a day ago.
Just remember to use the documentation that fits with your Metabase version, so that would be:
https://metabase.com/docs/v0.32.9/operations-guide/start.html
