### ISSUE TITLE
Cannot add second database from AWS DocumentDB

### ISSUE THREAD

**Issue by irozzo-1A** [metabase/metabase#10942]
**Describe the bug**
I deployed a metabase instance and added successfully a Database of type MongoDB pointing to an AWS DocumentDB instance ([supporting part of MongoDB 3.6 API](https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html)), but when trying to add another database from the same DocumentDB instance I got a timeout. I retried several times by redeploying met abase and the issue seems to be systematic.
I also tried to delete the database that I added successfully, and when trying to add it back I incurred in the same issue.

**Logs**
UI:
```
[Error] Request entities,databases,create failed: – {status: 400, data: {valid: false, dbname: "Hmm, we couldn't connect to the database. Make sure your host and port settings are correct", message: "Hmm, we couldn't connect to the database. Make sure your host and port settings are correct"}, isCancelled: false}
	(anonymous function) (app-main.bundle.js:5:83743)
	c (vendor.bundle.js:1:777986)
	(anonymous function) (vendor.bundle.js:1:777778)
	r (app-main.bundle.js:5:79335)
	(anonymous function) (app-main.bundle.js:5:79455)
	promiseReactionJob
```
Back-end:
```
09-20 12:54:22 ERROR driver.util :: Database connection error
com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@28040a23. Client view of cluster state is {type=REPLICA_SET, servers=[{address=<NAME>.docdb.amazonaws.com:27017, type=UNKNOWN, state=CONNECTING}]
	at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:401)
	at com.mongodb.internal.connection.BaseCluster.selectServer(BaseCluster.java:120)
	at com.mongodb.internal.connection.MultiServerCluster.selectServer(MultiServerCluster.java:54)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:138)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:161)
	at com.mongodb.DB.executeCommand(DB.java:774)
	at com.mongodb.DB.command(DB.java:520)
	at com.mongodb.DB.command(DB.java:536)
	at com.mongodb.DB.command(DB.java:491)
	at monger.core$command.invokeStatic(core.clj:251)
	at monger.core$command.invoke(core.clj:242)
	at monger.command$db_stats.invokeStatic(command.clj:71)
	at monger.command$db_stats.invoke(command.clj:69)
	at metabase.driver.mongo$eval2187$fn__2188$f__857__auto____2189.invoke(mongo.clj:36)
	at metabase.driver.mongo.util$_with_mongo_connection$fn__848.invoke(util.clj:205)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)
	at metabase.driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:199)
	at metabase.driver.mongo.util$_with_mongo_connection.invoke(util.clj:194)
	at metabase.driver.mongo$eval2187$fn__2188.invoke(mongo.clj:35)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__19324.invoke(util.clj:30)
	at metabase.util$do_with_timeout$fn__6283.invoke(util.clj:334)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
09-20 12:54:22 DEBUG middleware.log :: POST /api/database 400 3.0 s (0 DB calls)
{:valid false,
 :dbname "Hmm, we couldn't connect to the database. Make sure your host and port settings are correct",
 :message "Hmm, we couldn't connect to the database. Make sure your host and port settings are correct"}
```

**To Reproduce**
1. Deploy Metabase and setup a MongoDB database pointing to an AWS DocumentDB instance
2. Add another database of the same type.

**Expected behavior**
I expected to be able to add other databases

**Information about your Metabase Installation:**
- Your browser and the version: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
- Your databases: AWS DocumentDB with MongoDB compatibility
- Metabase version: (e.x. v0.33.2)
- Metabase hosting environment: Docker on EKS (AWS managed Kubernetes)
- Metabase docker image: metabase/metabase:v0.33.2
- Metabase internal database: H2

**Severity**
I'am just evaluating Metabase for the moment.

**Comment by salsakran** [comment]
Closing this since we don't explicitly support DocumentDB, and if it's breaking compatibility with the MongoDB api, we can't paper over it. Leaving the  broader DocumentDB support issue open, however.
