### ISSUE TITLE
Error when migrating from H2 -> MySQL/Postgres if multiple users with same email exist in DB

### ISSUE THREAD

**Issue by augustoferronato** [metabase/metabase#10961]
**Describe the bug**
I trying to migrate my data from H2 to MySQL using the comand load-from-h2, i'm running the docker version

**Logs**
```
09-23 14:30:30 INFO metabase.db :: Database Migrations Current ...  ✅
Database setup took 17.0 s
Temporarily disabling DB constraints...
[OK]
Transfering 3 instances of Database....[OK]
Transfering 29 instances of User....BatchUpdateException:
 Message: (conn=1616956) Duplicate entry 'email@email.com' for key 'email'
 SQLState: 23000
 Error Code: 1062
java.sql.BatchUpdateException: (conn=1616956) Duplicate entry 'email@email.com' for key 'email'
        at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:289)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeBatch(MariaDbPreparedStatementClient.java:306)
        at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:591)
        at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:584)
        at clojure.java.jdbc$db_do_execute_prepared_statement$fn__15516.invoke(jdbc.clj:1039)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:842)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1038)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1024)
        at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1062)
        at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1042)
        at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1576)
        at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1567)
        at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1633)
        at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1601)
        at metabase.cmd.load_from_h2$insert_chunk_BANG_.invokeStatic(load_from_h2.clj:146)
        at metabase.cmd.load_from_h2$insert_chunk_BANG_.invoke(load_from_h2.clj:141)
        at metabase.cmd.load_from_h2$insert_entity_BANG_.invokeStatic(load_from_h2.clj:157)
        at metabase.cmd.load_from_h2$insert_entity_BANG_.invoke(load_from_h2.clj:151)
        at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:165)
        at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:160)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__65327.invoke(load_from_h2.clj:249)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:242)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:231)
        at clojure.lang.Var.invoke(Var.java:384)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:38)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:31)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:34)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:31)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.cmd$run_cmd$fn__64559.invoke(cmd.clj:128)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:128)
        at metabase.cmd$run_cmd.invoke(cmd.clj:124)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.core$run_cmd.invokeStatic(core.clj:133)
        at metabase.core$run_cmd.invoke(core.clj:131)
        at metabase.core$_main.invokeStatic(core.clj:142)
        at metabase.core$_main.doInvoke(core.clj:138)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=1616956) Duplicate entry 'email@email.com' for key 'email'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:229)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
        at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:286)
        ... 50 more
Caused by: java.sql.SQLException: Duplicate entry 'email@email.com' for key 'email'
Query is: INSERT INTO core_user ( `email`, `ldap_auth`, `first_name`, `password_salt`, `password`, `last_login`, `is_active`, `is_qbnewb`, `updated_at`, `reset_triggered`, `is_superuser`, `login_attributes`, `id`, `reset_token`, `last_name`, `date_joined`, `google_auth` ) VALUES ( 'email@email.com', 0, 'FIRSTNAME', '242342342433', '$2a23424234', <null>, 0, 1, '2019-04-25 17:33:55.296', <null>, 0, <null>, 4, <null>, 'LASTNAME', '2019-03-12 18:49:02.957', 0 )
java thread: MariaDb-bulk-2
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:126)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$1.handleResultException(AbstractQueryProtocol.java:625)
        at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:142)
        at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:66)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Command failed with exception: (conn=1616956) Duplicate entry 'email@email.com' for key 'email'
```

**To Reproduce**
the command on docker
`docker run -d -v metabase-data-old:/metabase-data -e "MB_DB_FILE=/metabase-data/metabase.db" -v metabase-plugins:/app/plugins -e "MB_PLUGINS_DIR=/app/plugins" -e "MB_DB_TYPE=mysql" -e "MB_DB_PORT=3306" -e "MB_DB_DBNAME=DB" -e "MB_DB_USER=USER" -e "MB_DB_PASS=PASS" -e "MB_DB_HOST=<IP>" --name migrate metabase/metabase:v0.33.3 load-from-h2`
**Expected behavior**
Migrate the data from H2 to MySQL

**Information about your Metabase Installation:**
v0.33.3
Database: H2
Docker version 18.03.0-ce, build 0520e24
MySQL: 5.7.19-17-57-log

**Severity**
I have a lot of problems, because the H2 have 11gb size

**Comment by flamber** [comment]
Hi @augustoferronato 
Are you currently using 0.33.3 and only trying to migrate to MySQL, or are you upgrading and migrating at the same time?
Do you have multiple users with the same email (in Active and Deactived)? Make sure they're unique.

**Comment by salsakran** [comment]
@augustoferronato are you migrating to an empty database?

If you have multiple users with the same email, we shouldn't barf on that regardless.

**Comment by augustoferronato** [comment]
Yes,
i discover if a user is "inactive" i can create another with the same e-mail, and then a receive a error when migrating. Just delete the inactive users, work fine.

**Comment by augustoferronato** [comment]
I migrating from a h2 (11gb) to a MySQL

**Comment by paoliniluis** [comment]
Hi @augustoferronato I'm closing this as this should not happen in newer version (email is the key of the core_user table)
