### ISSUE TITLE
Sync error - value too long for type character varying(255)

### ISSUE THREAD

**Issue by smessems** [metabase/metabase#11002]
**Describe the bug**
I am seeing this error constantly. Not sure if this is an internal Metabase issue or something with the definition of the registered db. Any insight would be appreciated. 

Sep 26 15:00:22 ERROR metabase.sync.util :: Error syncing Fields for Table 'Table 76 'XXXXXXXX': Batch entry 0 UPDATE "metabase_field" SET "database_type" = 'row(... **here goes fairly long fields definitions** ...)', "updated_at" = '2019-09-26 15:00:22.275+00' WHERE "id" = 599 was aborted: ERROR: value too long for type character varying(255) Call getNextException to see other errors in the batch.
("org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)"
"org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)"
"org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2184)"
"org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:481)"
"org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:840)"
"org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1538)"
"com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2437)"
"clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:591)"
"clojure.java.jdbc$execute_batch.invoke(jdbc.clj:584)"
"clojure.java.jdbc$db_do_execute_prepared_statement$fn__14358.invoke(jdbc.clj:1039)"
"clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)"
"clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)"
"clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)"
"clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)"
"clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1038)"
"clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1024)"
"clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1062)"
"clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1042)"
"clojure.java.jdbc$execute_BANG_$execute_helper__14426.invoke(jdbc.clj:1446)"
"clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1450)"
"clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1417)"
"toucan.db$execute_BANG_.invokeStatic(db.clj:411)"
"toucan.db$execute_BANG_.doInvoke(db.clj:406)"
"clojure.lang.RestFn.invoke(RestFn.java:410)"
"toucan.db$update_BANG_.invokeStatic(db.clj:466)"
"toucan.db$update_BANG_.invoke(db.clj:455)"
"toucan.db$update_BANG_.invokeStatic(db.clj:475)"
"toucan.db$update_BANG_.invoke(db.clj:455)"
"--> sync.sync_metadata.fields.sync_metadata$fn__46610$update_field_metadata_if_needed_BANG___46615$fn__46616.invoke(sync_metadata.clj:75)"
"sync.sync_metadata.fields.sync_metadata$fn__46610$update_field_metadata_if_needed_BANG___46615.invoke(sync_metadata.clj:19)"
"sync.sync_metadata.fields.sync_metadata$fn__46670$update_metadata_BANG___46675$fn__46676$iter__46677__46681$fn__46682.invoke(sync_metadata.clj:100)"
"sync.util$sum_for_STAR_.invokeStatic(util.clj:462)"
"sync.util$sum_for_STAR_.invoke(util.clj:459)"
"sync.sync_metadata.fields.sync_metadata$fn__46670$update_metadata_BANG___46675$fn__46676.invoke(sync_metadata.clj:96)"
"sync.sync_metadata.fields.sync_metadata$fn__46670$update_metadata_BANG___46675.invoke(sync_metadata.clj:90)"
"sync.sync_metadata.fields$fn__46735$sync_and_update_BANG___46740$fn__46741.invoke(fields.clj:80)"
"sync.sync_metadata.fields$fn__46735$sync_and_update_BANG___46740.invoke(fields.clj:72)"
"sync.sync_metadata.fields$fn__46763$sync_fields_for_table_BANG___46772$fn__46778$fn__46780.invoke(fields.clj:102)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
"sync.util$do_with_error_handling.invoke(util.clj:144)"
"sync.sync_metadata.fields$fn__46763$sync_fields_for_table_BANG___46772$fn__46778.invoke(fields.clj:90)"
"sync.sync_metadata.fields$fn__46763$sync_fields_for_table_BANG___46772.invoke(fields.clj:83)"
"sync.sync_metadata.fields$fn__46808$sync_fields_BANG___46813$fn__46814$iter__46815__46819$fn__46820$fn__46821.invoke(fields.clj:117)"
"sync.sync_metadata.fields$fn__46808$sync_fields_BANG___46813$fn__46814$iter__46815__46819$fn__46820.invoke(fields.clj:116)"
"sync.sync_metadata.fields$fn__46808$sync_fields_BANG___46813$fn__46814.invoke(fields.clj:116)"
"sync.sync_metadata.fields$fn__46808$sync_fields_BANG___46813.invoke(fields.clj:111)"
"sync.util$fn__37761$run_step_with_metadata__37766$fn__37770$fn__37772.invoke(util.clj:356)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
"sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)"
"sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)"
"sync.util$fn__37761$run_step_with_metadata__37766$fn__37770.invoke(util.clj:353)"
"sync.util$fn__37761$run_step_with_metadata__37766.invoke(util.clj:348)"
"sync.util$fn__37953$run_sync_operation__37958$fn__37959$fn__37960.invoke(util.clj:441)"
"sync.util$fn__37953$run_sync_operation__37958$fn__37959.invoke(util.clj:441)"
"sync.util$fn__37953$run_sync_operation__37958.invoke(util.clj:435)"
"sync.sync_metadata$fn__47495$sync_db_metadata_BANG___47500$fn__47501$fn__47502.invoke(sync_metadata.clj:51)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
"sync.util$do_with_error_handling.invoke(util.clj:144)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:147)"
"sync.util$do_with_error_handling.invoke(util.clj:144)"
"driver$fn__18010.invokeStatic(driver.clj:646)"
"driver$fn__18010.invoke(driver.clj:646)"
"sync.util$sync_in_context$fn__37667.invoke(util.clj:140)"
"sync.util$with_db_logging_disabled$fn__37664.invoke(util.clj:131)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
"sync.util$with_start_and_finish_logging$fn__37653.invoke(util.clj:116)"
"sync.util$with_sync_events$fn__37648.invoke(util.clj:90)"
"sync.util$with_duplicate_ops_prevented$fn__37639.invoke(util.clj:69)"
"sync.util$do_sync_operation.invokeStatic(util.clj:168)"
"sync.util$do_sync_operation.invoke(util.clj:165)"
"sync.sync_metadata$fn__47495$sync_db_metadata_BANG___47500$fn__47501.invoke(sync_metadata.clj:50)"
"sync.sync_metadata$fn__47495$sync_db_metadata_BANG___47500.invoke(sync_metadata.clj:47)"
"task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:39)")

Sep 26 15:00:22 ERROR metabase.sync.util :: Error running sync step: Output of sync-fields-for-table! does not match schema: 

 (not (map? a-java.sql.BatchUpdateException))  

**Information about your Metabase Installation:**

Metabase is v0.32.8
We are using a PostgresDB for Metabase.
The registeredDB is Presto.

**Comment by salsakran** [comment]
@smessems is this keeping the list of tables from populating (and hence preventing the query builder from being useful?)

**Comment by kaanklky** [comment]
**Describe the bug**
I can reproduce similar issue with latest Docker image; Ican't access one of database on remote MongoDB, metabase throw this error:

```
org.postgresql.util.PSQLException: ERROR: value too long for type character varying(254)
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497) ~[metabase.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233) ~[metabase.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310) ~[metabase.jar:?]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446) ~[metabase.jar:?]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370) ~[metabase.jar:?]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149) ~[metabase.jar:?]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124) ~[metabase.jar:?]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:462) ~[metabase.jar:?]
	at clojure.java.jdbc$db_do_execute_prepared_return_keys$exec_and_return_keys__19147.invoke(jdbc.clj:979) ~[metabase.jar:?]
	at clojure.java.jdbc$db_do_execute_prepared_return_keys.invokeStatic(jdbc.clj:1007) ~[metabase.jar:?]
	at clojure.java.jdbc$db_do_execute_prepared_return_keys.invoke(jdbc.clj:963) ~[metabase.jar:?]
	at clojure.java.jdbc$db_do_prepared_return_keys.invokeStatic(jdbc.clj:1038) ~[metabase.jar:?]
	at clojure.java.jdbc$db_do_prepared_return_keys.invoke(jdbc.clj:1015) ~[metabase.jar:?]
	at clojure.java.jdbc$db_do_prepared_return_keys.invokeStatic(jdbc.clj:1040) ~[metabase.jar:?]
	at clojure.java.jdbc$db_do_prepared_return_keys.invoke(jdbc.clj:1015) ~[metabase.jar:?]
	at toucan.db$simple_insert_many_BANG_$iter__21644__21648$fn__21649.invoke(db.clj:563) ~[metabase.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[metabase.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) ~[metabase.jar:?]
	at clojure.lang.RT.seq(RT.java:535) ~[metabase.jar:?]
	at clojure.core$seq__5402.invokeStatic(core.clj:137) ~[metabase.jar:?]
	at clojure.core$dorun.invokeStatic(core.clj:3133) ~[metabase.jar:?]
	at clojure.core$doall.invokeStatic(core.clj:3148) ~[metabase.jar:?]
	at clojure.core$doall.invoke(core.clj:3148) ~[metabase.jar:?]
	at toucan.db$simple_insert_many_BANG_.invokeStatic(db.clj:560) ~[metabase.jar:?]
	at toucan.db$simple_insert_many_BANG_.invoke(db.clj:546) ~[metabase.jar:?]
	at toucan.db$insert_many_BANG_.invokeStatic(db.clj:579) ~[metabase.jar:?]
	at toucan.db$insert_many_BANG_.invoke(db.clj:566) ~[metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58473$insert_new_fields_BANG___58478$fn__58479.invoke(sync_instances.clj:45) ~[metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58473$insert_new_fields_BANG___58478.invoke(sync_instances.clj:41) ~[metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58516$create_or_reactivate_fields_BANG___58521$fn__58522.invoke(sync_instances.clj:70) ~[metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58516$create_or_reactivate_fields_BANG___58521.invoke(sync_instances.clj:58) ~[metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58543$sync_active_instances_BANG___58548$fn__58549$iter__58550__58554$fn__58555$fn__58560.invoke(sync_instances.clj:106) ~[metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149) [metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58543$sync_active_instances_BANG___58548$fn__58549$iter__58550__58554$fn__58555.invoke(sync_instances.clj:101) [metabase.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) [metabase.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) [metabase.jar:?]
	at clojure.lang.RT.seq(RT.java:535) [metabase.jar:?]
	at clojure.core$seq__5402.invokeStatic(core.clj:137) [metabase.jar:?]
	at clojure.core$filter$fn__5893.invoke(core.clj:2809) [metabase.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) [metabase.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:58) [metabase.jar:?]
	at clojure.lang.RT.seq(RT.java:535) [metabase.jar:?]
	at clojure.core$seq__5402.invokeStatic(core.clj:137) [metabase.jar:?]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) [metabase.jar:?]
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75) [metabase.jar:?]
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75) [metabase.jar:?]
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13) [metabase.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6824) [metabase.jar:?]
	at clojure.core$reduce.invoke(core.clj:6810) [metabase.jar:?]
	at metabase.sync.util$sum_for_STAR_.invokeStatic(util.clj:451) [metabase.jar:?]
	at metabase.sync.util$sum_for_STAR_.invoke(util.clj:448) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58543$sync_active_instances_BANG___58548$fn__58549.invoke(sync_instances.clj:100) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58543$sync_active_instances_BANG___58548.invoke(sync_instances.clj:87) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58727$sync_instances_BANG___58736$fn__58739.invoke(sync_instances.clj:195) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58727$sync_instances_BANG___58736.invoke(sync_instances.clj:180) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58654$sync_nested_fields_of_one_field_BANG___58659$fn__58660.invoke(sync_instances.clj:159) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58654$sync_nested_fields_of_one_field_BANG___58659.invoke(sync_instances.clj:149) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58681$sync_nested_field_instances_BANG___58686$fn__58687$iter__58688__58692$fn__58693.invoke(sync_instances.clj:178) [metabase.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) [metabase.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) [metabase.jar:?]
	at clojure.lang.RT.seq(RT.java:535) [metabase.jar:?]
	at clojure.core$seq__5402.invokeStatic(core.clj:137) [metabase.jar:?]
	at clojure.core$filter$fn__5893.invoke(core.clj:2809) [metabase.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) [metabase.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) [metabase.jar:?]
	at clojure.lang.RT.seq(RT.java:535) [metabase.jar:?]
	at clojure.core$seq__5402.invokeStatic(core.clj:137) [metabase.jar:?]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) [metabase.jar:?]
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75) [metabase.jar:?]
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75) [metabase.jar:?]
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13) [metabase.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6824) [metabase.jar:?]
	at clojure.core$reduce.invoke(core.clj:6810) [metabase.jar:?]
	at metabase.sync.util$sum_for_STAR_.invokeStatic(util.clj:451) [metabase.jar:?]
	at metabase.sync.util$sum_for_STAR_.invoke(util.clj:448) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58681$sync_nested_field_instances_BANG___58686$fn__58687.invoke(sync_instances.clj:175) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58681$sync_nested_field_instances_BANG___58686.invoke(sync_instances.clj:165) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58727$sync_instances_BANG___58736$fn__58739.invoke(sync_instances.clj:198) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58727$sync_instances_BANG___58736.invoke(sync_instances.clj:180) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58727$sync_instances_BANG___58736$fn__58737.invoke(sync_instances.clj:186) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields.sync_instances$fn__58727$sync_instances_BANG___58736.invoke(sync_instances.clj:180) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields$fn__58873$sync_and_update_BANG___58878$fn__58879.invoke(fields.clj:62) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields$fn__58873$sync_and_update_BANG___58878.invoke(fields.clj:58) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields$fn__58901$sync_fields_for_table_BANG___58910$fn__58913$fn__58914.invoke(fields.clj:77) [metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149) [metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields$fn__58901$sync_fields_for_table_BANG___58910$fn__58913.invoke(fields.clj:74) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields$fn__58901$sync_fields_for_table_BANG___58910.invoke(fields.clj:68) [metabase.jar:?]
	at clojure.core$partial$fn__5839.invoke(core.clj:2624) [metabase.jar:?]
	at clojure.core$map$fn__5866.invoke(core.clj:2753) [metabase.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) [metabase.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) [metabase.jar:?]
	at clojure.lang.RT.seq(RT.java:535) [metabase.jar:?]
	at clojure.core$seq__5402.invokeStatic(core.clj:137) [metabase.jar:?]
	at clojure.core$filter$fn__5893.invoke(core.clj:2809) [metabase.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) [metabase.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) [metabase.jar:?]
	at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59) [metabase.jar:?]
	at clojure.core$chunk_next.invokeStatic(core.clj:708) [metabase.jar:?]
	at clojure.core$reduce1.invokeStatic(core.clj:942) [metabase.jar:?]
	at clojure.core$reduce1.invokeStatic(core.clj:934) [metabase.jar:?]
	at clojure.core$merge_with.invokeStatic(core.clj:3059) [metabase.jar:?]
	at clojure.core$merge_with.doInvoke(core.clj:3051) [metabase.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:139) [metabase.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:667) [metabase.jar:?]
	at clojure.core$apply.invoke(core.clj:660) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields$fn__58939$sync_fields_BANG___58944$fn__58945.invoke(fields.clj:88) [metabase.jar:?]
	at metabase.sync.sync_metadata.fields$fn__58939$sync_fields_BANG___58944.invoke(fields.clj:80) [metabase.jar:?]
	at metabase.sync.util$fn__44054$run_step_with_metadata__44059$fn__44063$fn__44065.invoke(util.clj:345) [metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102) [metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96) [metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119) [metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116) [metabase.jar:?]
	at metabase.sync.util$fn__44054$run_step_with_metadata__44059$fn__44063.invoke(util.clj:342) [metabase.jar:?]
	at metabase.sync.util$fn__44054$run_step_with_metadata__44059.invoke(util.clj:337) [metabase.jar:?]
	at metabase.sync.util$fn__44246$run_sync_operation__44251$fn__44252$fn__44253.invoke(util.clj:430) [metabase.jar:?]
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912) [metabase.jar:?]
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343) [metabase.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6827) [metabase.jar:?]
	at clojure.core$mapv.invokeStatic(core.clj:6903) [metabase.jar:?]
	at clojure.core$mapv.invoke(core.clj:6903) [metabase.jar:?]
	at metabase.sync.util$fn__44246$run_sync_operation__44251$fn__44252.invoke(util.clj:430) [metabase.jar:?]
	at metabase.sync.util$fn__44246$run_sync_operation__44251.invoke(util.clj:424) [metabase.jar:?]
	at metabase.sync.sync_metadata$fn__59613$sync_db_metadata_BANG___59618$fn__59619$fn__59620.invoke(sync_metadata.clj:51) [metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149) [metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142) [metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145) [metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142) [metabase.jar:?]
	at clojure.core$partial$fn__5839.invoke(core.clj:2623) [metabase.jar:?]
	at metabase.driver.mongo$eval2358$fn__2359$f__1760__auto____2360.invoke(mongo.clj:97) [?:?]
	at metabase.driver.mongo.util$_with_mongo_connection$fn__1751.invoke(util.clj:228) [?:?]
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:158) [metabase.jar:?]
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:145) [metabase.jar:?]
	at metabase.driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:222) [?:?]
	at metabase.driver.mongo.util$_with_mongo_connection.invoke(util.clj:217) [?:?]
	at metabase.driver.mongo$eval2358$fn__2359.invoke(mongo.clj:96) [?:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:239) [metabase.jar:?]
	at metabase.sync.util$sync_in_context$fn__43966.invoke(util.clj:138) [metabase.jar:?]
	at metabase.sync.util$with_db_logging_disabled$fn__43963.invoke(util.clj:129) [metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102) [metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96) [metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_logging$fn__43952.invoke(util.clj:114) [metabase.jar:?]
	at metabase.sync.util$with_sync_events$fn__43947.invoke(util.clj:88) [metabase.jar:?]
	at metabase.sync.util$with_duplicate_ops_prevented$fn__43938.invoke(util.clj:67) [metabase.jar:?]
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164) [metabase.jar:?]
	at metabase.sync.util$do_sync_operation.invoke(util.clj:161) [metabase.jar:?]
	at metabase.sync.sync_metadata$fn__59613$sync_db_metadata_BANG___59618$fn__59619.invoke(sync_metadata.clj:50) [metabase.jar:?]
	at metabase.sync.sync_metadata$fn__59613$sync_db_metadata_BANG___59618.invoke(sync_metadata.clj:47) [metabase.jar:?]
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:49) [metabase.jar:?]
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:40) [metabase.jar:?]
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:55) [metabase.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [metabase.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [metabase.jar:?]
```

**Information about your Metabase Installation:**
Metabase is v0.37.2
We are using a PostgresDB for Metabase.

**Comment by sbelak** [comment]
This looks related, but not the same, as here the error happens when saving the metadata for a field. Does any of the fields in that db have a very long name or something like that?

**Comment by kaanklky** [comment]
> 
> 
> This looks related, but not the same, as here the error happens when saving the metadata for a field. Does any of the fields in that db have a very long name or something like that?

AFAIK we are using MongoDB at it limits.
