### ISSUE TITLE
Build Error : Missing google.metabase-driver.jar

### ISSUE THREAD

**Issue by drbullock** [metabase/metabase#11058]
**Describe the bug**
I am encountering this error when building on Debian. The "resources/modules" directory is empty.

**Error**
Stripped/extra-compressed size: 3.2 MB
Copying to /root/metabase/modules/drivers/bigquery/target/uberjar/bigquery.metabase-driver.jar...
Removing duplicate classes with google uberjar...
Warning: implicit hook found: lein-environ.plugin/hooks
Hooks are deprecated and will be removed in a future version.
10-04 11:06:03 DEBUG plugins.classloader :: Using Clojure base loader as shared context classload er: clojure.lang.DynamicClassLoader@615439f7
10-04 11:06:03 DEBUG plugins.classloader :: Setting current thread context classloader to shared  classloader clojure.lang.DynamicClassLoader@615439f7...
10-04 11:06:04 INFO metabase.util :: Loading Metabase...
10-04 11:06:04 INFO metabase.util :: Maximum memory available to JVM: 3.5 GB
Stripping duplicate classes and extra-compressing /root/metabase/modules/drivers/bigquery/target/ub erjar/bigquery.metabase-driver.jar...
Syntax error (FileNotFoundException) compiling at (/tmp/form-init6485737707773652806.clj:1:73).
resources/modules/google.metabase-driver.jar (No such file or directory)

**Logs**
{:clojure.main/message "Syntax error (FileNotFoundException) compiling at (/tmp/form-init64857377 07773652806.clj:1:73).\n resources/modules/google.metabase-driver.jar (No such file or directory)\ n",
 :clojure.main/triage
 {:clojure.error/phase :compile-syntax-check,
  :clojure.error/line 1,
  :clojure.error/column 73,
  :clojure.error/source "form-init6485737707773652806.clj",
  :clojure.error/path "/tmp/form-init6485737707773652806.clj",
  :clojure.error/class java.io.FileNotFoundException,
  :clojure.error/cause "resources/modules/google.metabase-driver.jar (No such file or directory)" },
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message "Syntax error compiling at (/tmp/form-init6485737707773652806.clj:1:73).",
    :data {:clojure.error/phase :compile-syntax-check, :clojure.error/line 1, :clojure.error/colu mn 73, :clojure.error/source "/tmp/form-init6485737707773652806.clj"},
    :at [clojure.lang.Compiler load "Compiler.java" 7648]}
   {:type java.io.FileNotFoundException, :message "resources/modules/google.metabase-driver.jar ( No such file or directory)", :at [java.util.zip.ZipFile open "ZipFile.java" -2]}],
  :trace
  [[java.util.zip.ZipFile open "ZipFile.java" -2]
   [java.util.zip.ZipFile <init> "ZipFile.java" 225]
   [java.util.zip.ZipFile <init> "ZipFile.java" 155]
   [java.util.zip.ZipFile <init> "ZipFile.java" 126]
   [metabase.strip_and_compress_module$files_blacklist invokeStatic "strip_and_compress_module.cl j" 12]
   [metabase.strip_and_compress_module$files_blacklist invoke "strip_and_compress_module.clj" 12]
   [metabase.strip_and_compress_module$_main invokeStatic "strip_and_compress_module.clj" 30]
   [metabase.strip_and_compress_module$_main invoke "strip_and_compress_module.clj" 22]
   [clojure.lang.Var invoke "Var.java" 388]
   [user$eval251 invokeStatic "form-init6485737707773652806.clj" 1]
   [user$eval251 invoke "form-init6485737707773652806.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7167]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.Compiler loadFile "Compiler.java" 7574]
   [clojure.main$load_script invokeStatic "main.clj" 475]
   [clojure.main$init_opt invokeStatic "main.clj" 477]
   [clojure.main$init_opt invoke "main.clj" 477]
   [clojure.main$initialize invokeStatic "main.clj" 508]
   [clojure.main$null_opt invokeStatic "main.clj" 542]
   [clojure.main$null_opt invoke "main.clj" 539]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "resources/modules/google.metabase-driver.jar (No such file or directory)",
  :phase :compile-syntax-check}}

**Comment by flamber** [comment]
Hi @drbullock 
Which command are you using to build (or get to the error you posted)?
Have you tried to re-build just the drivers?
```
./bin/build-drivers.sh
```
Can you post the output of the following commands?
```
java -version
nodejs --version
lein --version
yarn --version
lsb_release -d
git log -1 --format="commit %H"
git status | head -1
```

**Comment by drbullock** [comment]
Hi @flamber, thank you for the reply :)
I used this command before:
`bin/build no-translations`

Now I tried again building only the drivers, but it is the same issue.
These are the outputs of the commands:

`java -version`
> java version "1.8.0_221"
> Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
`nodejs --version`
> v10.16.3
`lein --version`
> Leiningen 2.9.1 on Java 1.8.0_221 Java HotSpot(TM) 64-Bit Server VM
`yarn --version`
> 1.19.0
`lsb_release -d`
> Description:    Debian GNU/Linux 9.11 (stretch)
`git log -1 --format="commit %H"`
> commit 8597f7cb3f0b68158a6697984e8b8fc859a03f11
`git status | head -1`
> On branch master

**Comment by flamber** [comment]
@drbullock I have a very similar build setup as you, though, I haven't run a full build for a few weeks.
Are there no errors, when you're building the drivers (specifically with any of the Google stuff)?
I have a feeling that there must be some errors before what you posted, when building the driver.

**Comment by drbullock** [comment]
@flamber cloned in another folder, and this is the log.
Are you using root fo build?

Created /root/bidata/target/uberjar/metabase-core-1.0.0-SNAPSHOT.jar
Created /root/bidata/target/uberjar/metabase.jar
Building parent drivers (if needed)...
Building google driver...
Leiningen's classpath: /root/.lein/self-installs/leiningen-2.9.1-standalone.jar
Applying task uberjar to []
Applying task javac to nil
Running javac with [-target 1.8 -source 1.8 @/tmp/.leiningen-cmdline1638034685541699489.tmp]
Applying task compile to nil
Compiling metabase.driver.google
10-07 10:44:50 DEBUG plugins.classloader :: Using Clojure base loader as shared context classloader: clojure.lang.DynamicClassLoader@301ec38b
10-07 10:44:50 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@301ec38b...
Created /root/bidata/modules/drivers/google/target/uberjar+provided/google-driver-1.0.0-SNAPSHOT-1.27.0.jar
Including google-driver-1.0.0-SNAPSHOT-1.27.0.jar
Including google-http-client-jackson2-1.27.0.jar
Including guava-20.0.jar
Including j2objc-annotations-1.1.jar
Including google-oauth-client-1.27.0.jar
Including google-http-client-1.27.0.jar
Including commons-logging-1.2.jar
Including google-api-client-1.27.0.jar
Including jackson-core-2.9.6.jar
Including httpcore-4.4.9.jar
Including jsr305-3.0.2.jar
Including httpclient-4.5.5.jar
Including commons-codec-1.10.jar
Created /root/bidata/modules/drivers/google/target/uberjar/google.metabase-driver.jar
Warning: implicit hook found: lein-environ.plugin/hooks
Hooks are deprecated and will be removed in a future version.
10-07 10:45:17 DEBUG plugins.classloader :: Using Clojure base loader as shared context classloader: clojure.lang.DynamicClassLoader@632cf7d3
10-07 10:45:17 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@632cf7d3...
10-07 10:45:17 INFO metabase.util :: Loading Metabase...
10-07 10:45:17 INFO metabase.util :: Maximum memory available to JVM: 3.5 GB
Stripping duplicate classes and extra-compressing /root/bidata/modules/drivers/google/target/uberjar/google.metabase-driver.jar...
Done. wrote: 2355 skipped: 1181
Original size: 4.6 MB
Stripped/extra-compressed size: 2.9 MB
Copying to /root/bidata/modules/drivers/google/target/uberjar/google.metabase-driver.jar...
Copying /root/bidata/modules/drivers/google/target/uberjar/google.metabase-driver.jar -> /root/bidata/resources/modules/google.metabase-driver.jar
Verifying google driver...
Checking whether resources/modules/google.metabase-driver.jar exists....
File exists.
Checking whether driver contains main class file metabase/driver/google__init.class...
./bin/verify-driver: line 33: jar: command not found
Main class file missing. Driver verification failed.
./bin/build-driver.sh google FAILED.
Installing google locally...
Compiling metabase.driver.google
10-07 10:45:32 DEBUG plugins.classloader :: Using Clojure base loader as shared context classloader: clojure.lang.DynamicClassLoader@301ec38b
10-07 10:45:32 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@301ec38b...
Created /root/bidata/modules/drivers/google/target/google-driver-1.0.0-SNAPSHOT-1.27.0.jar
Wrote /root/bidata/modules/drivers/google/pom.xml
Installed jar and pom into local repo.
Building bigquery driver...
Leiningen's classpath: /root/.lein/self-installs/leiningen-2.9.1-standalone.jar
Applying task uberjar to []
Applying task javac to nil
Running javac with [-target 1.8 -source 1.8 @/tmp/.leiningen-cmdline3162822512172628076.tmp]
Applying task compile to nil
Compiling metabase.driver.bigquery
10-07 10:45:55 DEBUG plugins.classloader :: Using NEWLY CREATED classloader as shared context classloader: clojure.lang.DynamicClassLoader@ef60710
10-07 10:45:55 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@ef60710...
Compiling metabase.driver.bigquery.common
Compiling metabase.driver.bigquery.query-processor
Created /root/bidata/modules/drivers/bigquery/target/uberjar+provided/bigquery-driver-1.0.0-SNAPSHOT-1.27.0.jar
Including bigquery-driver-1.0.0-SNAPSHOT-1.27.0.jar
Including google-http-client-jackson2-1.27.0.jar
Including guava-20.0.jar
Including j2objc-annotations-1.1.jar
Including google-oauth-client-1.27.0.jar
Including google-http-client-1.27.0.jar
Including commons-logging-1.2.jar
Including google-api-client-1.27.0.jar
Including jackson-core-2.9.6.jar
Including google-api-services-bigquery-v2-rev20181202-1.27.0.jar
Including httpcore-4.4.9.jar
Including jsr305-3.0.2.jar
Including httpclient-4.5.5.jar
Including commons-codec-1.10.jar
Created /root/bidata/modules/drivers/bigquery/target/uberjar/bigquery.metabase-driver.jar
Warning: implicit hook found: lein-environ.plugin/hooks
Hooks are deprecated and will be removed in a future version.
10-07 10:46:20 DEBUG plugins.classloader :: Using Clojure base loader as shared context classloader: clojure.lang.DynamicClassLoader@632cf7d3
10-07 10:46:20 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@632cf7d3...
10-07 10:46:20 INFO metabase.util :: Loading Metabase...
10-07 10:46:20 INFO metabase.util :: Maximum memory available to JVM: 3.5 GB
Stripping duplicate classes and extra-compressing /root/bidata/modules/drivers/bigquery/target/uberjar/bigquery.metabase-driver.jar...
Done. wrote: 2588 skipped: 1181
Original size: 4.9 MB
Stripped/extra-compressed size: 3.2 MB
Copying to /root/bidata/modules/drivers/bigquery/target/uberjar/bigquery.metabase-driver.jar...
Removing duplicate classes with google uberjar...
Warning: implicit hook found: lein-environ.plugin/hooks
Hooks are deprecated and will be removed in a future version.
10-07 10:46:36 DEBUG plugins.classloader :: Using Clojure base loader as shared context classloader: clojure.lang.DynamicClassLoader@632cf7d3
10-07 10:46:36 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@632cf7d3...
10-07 10:46:36 INFO metabase.util :: Loading Metabase...
10-07 10:46:36 INFO metabase.util :: Maximum memory available to JVM: 3.5 GB
Stripping duplicate classes and extra-compressing /root/bidata/modules/drivers/bigquery/target/uberjar/bigquery.metabase-driver.jar...
Syntax error (FileNotFoundException) compiling at (/tmp/form-init5373234289192229427.clj:1:73).
resources/modules/google.metabase-driver.jar (No such file or directory)

**Comment by flamber** [comment]
@drbullock I never use `root` - not sure if that's the problem, I don't think so.
I'm on `master` (commit c6ff26ba5a9b301dd4f4e85c3c7b372c3c263cca), which seems to build the Google drivers fine (`google`, `bigquery`, `googleanalytics`), but it's failing to build MongoDB.
I know there's a lot of work currently being done in `master`, so I then tried `release-0.33.x` (commit a32e6a4eb3cc74a6234a580c1e8a8db90d3f5583) and it builds fine with `./bin/build-drivers.sh clean`
It takes about an hour to compile drivers on my computer, so not something I want to do regularly :sob:

@camsaul Any idea why MongoDB driver is failing on `master` currently?
```
Building mongo driver...
Leiningen's classpath: /home/hansen/.lein/self-installs/leiningen-2.9.1-standalone.jar
Applying task uberjar to []
Applying task javac to nil
Running javac with [-target 1.8 -source 1.8 @/tmp/.leiningen-cmdline7376571648274423422.tmp]
Applying task compile to nil
Compiling metabase.driver.mongo
10-07 12:17:16 DEBUG plugins.classloader :: Using NEWLY CREATED classloader as shared context classloader: clojure.lang.DynamicClassLoader@5ef6fd7f
10-07 12:17:16 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@5ef6fd7f...
java.lang.NoClassDefFoundError: clojure/core$seq__5402, compiling:(mongo.clj:1:1)
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/core$seq__5402, compiling:(mongo.clj:1:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3700)
	at clojure.lang.Compiler.compile1(Compiler.java:7609)
	at clojure.lang.Compiler.compile1(Compiler.java:7599)
	at clojure.lang.Compiler.compile(Compiler.java:7676)
	at clojure.lang.RT.compile(RT.java:413)
	at clojure.lang.RT.load(RT.java:458)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$compile$fn__6553.invoke(core.clj:6056)
	at clojure.core$compile.invokeStatic(core.clj:6056)
	at clojure.core$compile.invoke(core.clj:6048)
	at user$eval164$fn__173.invoke(form-init6406038460119773530.clj:1)
	at user$eval164.invokeStatic(form-init6406038460119773530.clj:1)
	at user$eval164.invoke(form-init6406038460119773530.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NoClassDefFoundError: clojure/core$seq__5402
	at pretty.core$fn__758.invokeStatic(core.clj:23)
	at pretty.core$fn__758.invoke(core.clj:23)
	at pretty.core__init.load(Unknown Source)
	at pretty.core__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.RT.loadClassForName(RT.java:2232)
	at clojure.lang.RT.load(RT.java:450)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at metabase.util.honeysql_extensions$loading__6721__auto____19605.invoke(honeysql_extensions.clj:1)
	at metabase.util.honeysql_extensions__init.load(Unknown Source)
	at metabase.util.honeysql_extensions__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.RT.loadClassForName(RT.java:2232)
	at clojure.lang.RT.load(RT.java:450)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5929)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at metabase.models.setting.cache$loading__6721__auto____16137.invoke(cache.clj:1)
	at metabase.models.setting.cache__init.load(Unknown Source)
	at metabase.models.setting.cache__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.RT.loadClassForName(RT.java:2232)
	at clojure.lang.RT.load(RT.java:450)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:930)
	at metabase.models.setting$loading__6721__auto____7396.invoke(setting.clj:1)
	at metabase.models.setting__init.load(Unknown Source)
	at metabase.models.setting__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.RT.loadClassForName(RT.java:2232)
	at clojure.lang.RT.load(RT.java:450)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at metabase.driver$loading__6721__auto____7394.invoke(driver.clj:1)
	at metabase.driver__init.load(Unknown Source)
	at metabase.driver__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.RT.loadClassForName(RT.java:2232)
	at clojure.lang.RT.load(RT.java:450)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5929)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:703)
	at metabase.driver.mongo$loading__6434__auto____180.invoke(mongo.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
	... 33 more
Caused by: java.lang.ClassNotFoundException: clojure.core$seq__5402
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 178 more
Compilation failed: Subprocess failed
Error: could not find /home/hansen/GithubRepo/metabase/modules/drivers/mongo/target/uberjar/mongo.metabase-driver.jar. Build failed.
Failed to build driver mongo.
```

**Comment by drbullock** [comment]
@flamber you are right, better-trying release. Will update here. Thank you!

**Comment by drbullock** [comment]
Update: Tried the latest release, without root, and it is the same error with google.metabase-driver.jar

**Comment by flamber** [comment]
@drbullock Try running `jar -help` and `whereis jar` - seems like parts of your Java are not there. Could you remove and re-install it? It looks like you're using Oracle Java, but how did you install it?

**Comment by drbullock** [comment]
@flamber I don't have any jar as I see. As I remember I have followed this article for installing jdk-8u221-linux-x64.tar.gz
https://www.mkyong.com/java/how-to-install-oracle-jdk-8-on-debian/

**Comment by flamber** [comment]
@drbullock Have you defined `JAVA_HOME` environment variable? Try `echo $JAVA_HOME`
Otherwise, try having a look at this tutorial - it's a little newer, so it's about Java 11 on Debian 10:
https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-debian-10

**Comment by drbullock** [comment]
@flamber sorry, it was totally my problem. I tried to run only `jar` and it was not a known command.
Actually it was listed on `$JAVA_HOME` but not in  `$PATH`.
Thank you for the support.
