### ISSUE TITLE
Build Error : /bigquery.metabase-driver.jar. Build failed.

### ISSUE THREAD

**Issue by lauer3912** [metabase/metabase#11161]
**Describe the bug**

Uberjar aborting because jar failed: Could not resolve dependencies
Error: **could not find /root/projects/wodax/metabase-workspace/dev-wodax-metabase/modules/drivers/bigquery/target/uberjar/bigquery.metabase-driver.jar. Build failed.**
./bin/build-driver.sh: line 157: return: -3: invalid option
return: usage: return [n]
Failed to build driver bigquery.

**Logs**

```text
Created /root/projects/wodax/metabase-workspace/dev-wodax-metabase/target/install-for-building-drivers+install/metabase-core-1.0.0-SNAPSHOT.jar
Wrote /root/projects/wodax/metabase-workspace/dev-wodax-metabase/pom.xml
Installed jar and pom into local repo.
Building bigquery driver...
Leiningen's classpath: /root/.lein/self-installs/leiningen-2.9.1-standalone.jar
Applying task uberjar to []
Could not find artifact metabase:google-driver:jar:1.0.0-SNAPSHOT-1.27.0 in central (https://repo1.maven.org/maven2/)
Could not find artifact metabase:google-driver:jar:1.0.0-SNAPSHOT-1.27.0 in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
clojure.lang.ExceptionInfo: Could not resolve dependencies {:suppress-msg true, :exit-code 1}
        at leiningen.core.classpath$get_dependencies_STAR_.invokeStatic(classpath.clj:312)
        at leiningen.core.classpath$get_dependencies_STAR_.invoke(classpath.clj:266)
        at clojure.lang.AFn.applyToHelper(AFn.java:165)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$memoize$fn__6862.doInvoke(core.clj:6353)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at leiningen.core.classpath$get_dependencies$fn__6105.invoke(classpath.clj:333)
        at leiningen.core.classpath$get_dependencies.invokeStatic(classpath.clj:331)
        at leiningen.core.classpath$get_dependencies.doInvoke(classpath.clj:325)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$apply.invoke(core.clj:660)
        at leiningen.core.classpath$resolve_managed_dependencies.invokeStatic(classpath.clj:444)
        at leiningen.core.classpath$resolve_managed_dependencies.doInvoke(classpath.clj:431)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at leiningen.core.eval$prep.invokeStatic(eval.clj:85)
        at leiningen.core.eval$prep.invoke(eval.clj:73)
        at leiningen.jar$build_jar.invokeStatic(jar.clj:286)
        at leiningen.jar$build_jar.invoke(jar.clj:283)
        at leiningen.jar$main_jar.invokeStatic(jar.clj:295)
        at leiningen.jar$main_jar.invoke(jar.clj:291)
        at leiningen.jar$jar.invokeStatic(jar.clj:346)
        at leiningen.jar$jar.invoke(jar.clj:328)
        at leiningen.uberjar$uberjar$fn__10301.invoke(uberjar.clj:167)
        at leiningen.uberjar$uberjar.invokeStatic(uberjar.clj:167)
        at leiningen.uberjar$uberjar.invoke(uberjar.clj:143)
        at leiningen.uberjar$uberjar.invokeStatic(uberjar.clj:187)
        at leiningen.uberjar$uberjar.invoke(uberjar.clj:143)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at leiningen.core.main$partial_task$fn__6592.doInvoke(main.clj:284)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at leiningen.core.main$apply_task.invokeStatic(main.clj:334)
        at leiningen.core.main$apply_task.invoke(main.clj:320)
        at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:343)
        at leiningen.core.main$resolve_and_apply.invoke(main.clj:336)
        at leiningen.core.main$_main$fn__6681.invoke(main.clj:452)
        at leiningen.core.main$_main.invokeStatic(main.clj:442)
        at leiningen.core.main$_main.doInvoke(main.clj:439)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.main$main_opt.invokeStatic(main.clj:491)
        at clojure.main$main_opt.invoke(main.clj:487)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact metabase:google-driver:jar:1.0.0-SNAPSHOT-1.27.0 in central (https://repo1.maven.org/maven2/)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:355)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102)
        at cemerick.pomegranate.aether$resolve_dependencies_STAR_.invokeStatic(aether.clj:806)
        at cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke(aether.clj:707)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at cemerick.pomegranate.aether$resolve_dependencies.invokeStatic(aether.clj:815)
        at cemerick.pomegranate.aether$resolve_dependencies.doInvoke(aether.clj:809)
        at clojure.lang.RestFn.invoke(RestFn.java:2793)
        at leiningen.core.classpath$get_dependencies_STAR_.invokeStatic(classpath.clj:274)
        ... 60 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact metabase:google-driver:jar:1.0.0-SNAPSHOT-1.27.0 in central (https://repo1.maven.org/maven2/)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:338)
        ... 75 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact metabase:google-driver:jar:1.0.0-SNAPSHOT-1.27.0 in central (https://repo1.maven.org/maven2/)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:590)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:258)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
        ... 77 more
Uberjar aborting because jar failed: Could not resolve dependencies
Error: could not find /root/projects/wodax/metabase-workspace/dev-wodax-metabase/modules/drivers/bigquery/target/uberjar/bigquery.metabase-driver.jar. Build failed.
./bin/build-driver.sh: line 157: return: -3: invalid option
return: usage: return [n]
Failed to build driver bigquery.
```

**Information about your Metabase Installation:**

`java -version`
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
`nodejs --version`
v10.16.3
`lein --version`
Leiningen 2.9.1 on Java 1.8.0_221 Java HotSpot(TM) 64-Bit Server VM
`yarn --version`
1.19.0
`lsb_release -d`
Description: Debian GNU/Linux 9.11 (stretch)
`git log -1 --format="commit %H"`
commit [f8ccfafb537e682bbf20b5d6b3c0730c9ae3fc85](https://github.com/metabase/metabase/commit/f8ccfafb537e682bbf20b5d6b3c0730c9ae3fc85)
`git status | head -1`
On branch master

**Comment by flamber** [comment]
Hi @lauer3912 
Which command are you using to build?
From the errors, it looks like you're trying to build `bigquery.metabase-driver.jar`, but that driver depends on `google.metabase-driver.jar` being build first.
Also, I would recommend that you use branch `release-0.33.x` instead of `master` - more stable.

**Comment by lauer3912** [comment]
@flamber

I use `./bin/build` command.

---

I use branch `release-0.33.x` , but build error again.

```text
Created /root/projects/wodax/metabase-workspace/dev-wodax-metabase/target/uberjar/metabase.jar
.metabase-driver.jar. Build failed.s/wodax/metabase-workspace/dev-wodax-metabase/modules/drivers/google
./bin/build-driver.sh: line 157: return: -3: invalid option
```

But, use `./bin/build-diriver.sh google` can build `google.metabase-driver.jar` success,

**Comment by flamber** [comment]
@lauer3912 
Okay, actually it looks like it's trying to lookup the `google` driver in the repos instead of locally.
Could you try to cleanup and try again (see the file for more details on what it does):
`./bin/build-drivers.sh clean`
Otherwise I'm not sure what's going on - other than it must be something in your environment.

**Comment by lauer3912** [comment]
@flamber 
Thanks. It's build normal, no errors.
