### ISSUE TITLE
LDAP group sync - LDAPException after removing user from a mapped group

### ISSUE THREAD

**Issue by sergiocharpineljr** [metabase/metabase#11172]
**Describe the bug**
I've Metabase 0.33.4 with LDAP authentication configured. I've configured group sync and the Metabase group is correctly assigned after the user logs in. But when I remove the user from the mapped group in AD I get a login error and the following exception

**Logs**
ERROR api.session :: Problema ao se conectar com o servidor LDAP, voltando à autenticação local
LDAPException(resultCode=34 (invalid DN syntax), errorMessage='Unable to parse string 'C' as a DN because it does not have an equal sign after RDN attribute 'C'.', ldapSDKVersion=4.0.4, revision=27051)
        at com.unboundid.ldap.sdk.DN.<init>(DN.java:381)
        at com.unboundid.ldap.sdk.DN.<init>(DN.java:284)
        at metabase.integrations.ldap$ldap_groups__GT_mb_group_ids$fn__52069.invoke(ldap.clj:120)
        at clojure.core$map$fn__5866.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$select_keys.invokeStatic(core.clj:1540)
        at clojure.core$select_keys.invoke(core.clj:1540)
        at metabase.integrations.ldap$ldap_groups__GT_mb_group_ids.invokeStatic(ldap.clj:120)
        at metabase.integrations.ldap$ldap_groups__GT_mb_group_ids.invoke(ldap.clj:116)
        at metabase.integrations.ldap$fetch_or_create_user_BANG_.invokeStatic(ldap.clj:220)
        at metabase.integrations.ldap$fetch_or_create_user_BANG_.invoke(ldap.clj:210)
        at metabase.api.session$fn__52256$ldap_login__52261$fn__52262.invoke(session.clj:83)
        at metabase.api.session$fn__52256$ldap_login__52261.invoke(session.clj:69)
        at metabase.api.session$fn__52309$login__52314$fn__52315.invoke(session.clj:107)
        at metabase.api.session$fn__52309$login__52314.invoke(session.clj:102)
        at metabase.api.session$do_login.invokeStatic(session.clj:125)
        at metabase.api.session$do_login.invoke(session.clj:122)
        at metabase.api.session$fn__52337$fn__52340$fn__52341$fn__52342.invoke(session.clj:152)
        at throttle.core$do_with_throttling.invokeStatic(core.clj:93)
        at throttle.core$do_with_throttling.invoke(core.clj:87)
        at metabase.api.session$fn__52337$fn__52340$fn__52341.invoke(session.clj:150)
        at throttle.core$do_with_throttling.invokeStatic(core.clj:93)
        at throttle.core$do_with_throttling.invoke(core.clj:87)
        at metabase.api.session$fn__52337$fn__52340.invoke(session.clj:150)
        at metabase.api.session$do_http_400_on_error.invokeStatic(session.clj:131)
        at metabase.api.session$do_http_400_on_error.invoke(session.clj:129)
        at metabase.api.session$fn__52337.invokeStatic(session.clj:149)
        at metabase.api.session$fn__52337.invoke(session.clj:141)
        at compojure.core$wrap_response$fn__22518.invoke(core.clj:160)
        at compojure.core$wrap_route_middleware$fn__22502.invoke(core.clj:132)
        at compojure.core$wrap_route_info$fn__22507.invoke(core.clj:139)
        at compojure.core$wrap_route_matches$fn__22511.invoke(core.clj:151)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530.invoke(core.clj:200)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530.invoke(core.clj:200)
        at compojure.core$make_context$handler__22558.invoke(core.clj:287)
        at compojure.core$make_context$fn__22560.invoke(core.clj:296)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$make_context$fn__22560.invoke(core.clj:297)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530.invoke(core.clj:200)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.routes$fn__66170$fn__66171.doInvoke(routes.clj:56)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530.invoke(core.clj:200)
        at compojure.core$make_context$handler__22558.invoke(core.clj:287)
        at compojure.core$make_context$fn__22560.invoke(core.clj:296)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__22511.invoke(core.clj:153)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__22511.invoke(core.clj:153)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530$f__22531$respond_SINGLEQUOTE___22532.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__22511.invoke(core.clj:153)
        at compojure.core$routes$fn__22530$f__22531.invoke(core.clj:198)
        at compojure.core$routes$fn__22530.invoke(core.clj:200)
        at metabase.middleware.exceptions$catch_uncaught_exceptions$fn__47270.invoke(exceptions.clj:104)
        at metabase.middleware.exceptions$catch_api_exceptions$fn__47267.invoke(exceptions.clj:92)
        at metabase.middleware.log$log_api_call$fn__47180$fn__47181.invoke(log.clj:170)
        at toucan.db$_do_with_call_counting.invokeStatic(db.clj:213)
        at toucan.db$_do_with_call_counting.invoke(db.clj:206)
        at metabase.middleware.log$log_api_call$fn__47180.invoke(log.clj:164)
        at metabase.middleware.security$add_security_headers$fn__47231.invoke(security.clj:122)
        at metabase.middleware.json$wrap_json_body$fn__47397.invoke(json.clj:61)
        at metabase.middleware.json$wrap_streamed_json_response$fn__47415.invoke(json.clj:97)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__67815.invoke(keyword_params.clj:55)
        at ring.middleware.params$wrap_params$fn__67863.invoke(params.clj:69)
        at metabase.middleware.session$bind_current_user$fn__47529$fn__47530.invoke(session.clj:193)
        at metabase.middleware.session$do_with_current_user.invokeStatic(session.clj:177)
        at metabase.middleware.session$do_with_current_user.invoke(session.clj:170)
        at metabase.middleware.session$bind_current_user$fn__47529.invoke(session.clj:192)
        at metabase.middleware.session$wrap_current_user_id$fn__47518.invoke(session.clj:161)
        at metabase.middleware.session$wrap_session_id$fn__47503.invoke(session.clj:123)
        at metabase.middleware.auth$wrap_api_key$fn__47322.invoke(auth.clj:27)
        at metabase.middleware.misc$maybe_set_site_url$fn__47295.invoke(misc.clj:56)
        at metabase.middleware.misc$bind_user_locale$fn__47298.invoke(misc.clj:72)
        at ring.middleware.cookies$wrap_cookies$fn__67735.invoke(cookies.clj:177)
        at metabase.middleware.misc$add_content_type$fn__47283.invoke(misc.clj:28)
        at metabase.middleware.misc$disable_streaming_buffering$fn__47306.invoke(misc.clj:87)
        at ring.middleware.gzip$wrap_gzip$fn__67777.invoke(gzip.clj:86)
        at ring.adapter.jetty$async_proxy_handler$fn__46964.invoke(jetty.clj:35)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Unknown Source)

**To Reproduce**
1. Configure LDAP Authentication
2. Configure a mapped AD group (CN=group,OU=groups,dc=test) to a custom Metabase group (group)
3. Create a AD user and add it to the group.
4. Log in with a new AD user and check that the metabase group is correctly assigned.
5. Remove the user from the AD group.
6. Try to log in again and you will see the error.

**Expected behavior**
As the user is removed from the mapped group it should be assigned to the "Default" group.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "pt",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "4.9.0-3-amd64",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "run-mode": "prod",
    "version": {
      "date": "2019-10-07",
      "tag": "v0.33.4",
      "branch": "release-0.33.x",
      "hash": "9559406"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    }
  }
}
**Severity**
It is blocking some users.

**Additional context**

**Comment by flamber** [comment]
Just adding the English error string:
`Problem connecting to LDAP server, will fall back to local authentication`
Might be related to #10988 or #7571.

**Comment by DoctorOgg** [comment]
we have this issue as well on 33.4, and we have a separate install on v0.32.10 that works just great, both metabases are on the same aws VPC and connecting to the same LDAP servers,

**Comment by jannishuebl** [comment]
Hi, 

i have the same issue, after debugging a while i figured out that the problem occurs, when a user is  only member of one group. It is caused in this line: 

https://github.com/metabase/metabase/blob/b563507e9cfa228b057c99958f679dd88d399ec9/src/metabase/integrations/ldap.clj#L125

Because somehow the map function does not get a "array" of strings but the single string, this causes the map function to map over the string char by char. This does not occur when there are multiple groups.

Since i have no clue about Clojure I can not see immediately, if this is a problem in the code, where something leads to this behavior or if it is my ldap server.

Could someone with better Clojure skills have a look and figure that out?
