### ISSUE TITLE
v0.33.5.1 or v0.33.6 upgrade error "must be owner of relation metabase_field"

### ISSUE THREAD

**Issue by wollerman** [metabase/metabase#11357]
**Describe the bug**
Updating to either docker image 0.33.5.1 or 0.33.6 fails. It seems to be related to permissions? I'm not sure if I am missing permissions or something changed? More information in the logs below.

**Logs**
```
-------------------------------------
/var/log/eb-docker/containers/eb-current-app/eb-3d1ddbf855ce-stdouterr.log
-------------------------------------
11-20 06:04:26 [1mINFO metabase.db[0m :: Setting up Liquibase...
11-20 06:04:26 [1mINFO metabase.db[0m :: Liquibase is ready.
11-20 06:04:26 [1mINFO metabase.db[0m :: Checking if Database has unrun migrations...
11-20 06:04:26 [1mINFO metabase.db[0m :: Database has unrun migrations. Waiting for migration lock to be cleared...
11-20 06:04:26 [1mINFO metabase.db[0m :: Migration lock is cleared. Running migrations...
11-20 06:04:26 [1mERROR changelog.ChangeSet[0m :: Change Set migrations/000_migrations.yaml::106::sb failed.  Error: ERROR: must be owner of relation metabase_field [Failed SQL: ALTER TABLE public.metabase_field ALTER COLUMN database_type TYPE TEXT USING (database_type::TEXT)]
11-20 06:04:26 [1mWARN metabase.util[0m :: [31mauto-retry metabase.db$migrate_up_if_needed_BANG_$fn__18515@23481b1a: Migration failed for change set migrations/000_migrations.yaml::106::sb:
     Reason: liquibase.exception.DatabaseException: ERROR: must be owner of relation metabase_field [Failed SQL: ALTER TABLE public.metabase_field ALTER COLUMN database_type TYPE TEXT USING (database_type::TEXT)][0m
11-20 06:04:26 [1mERROR changelog.ChangeSet[0m :: Change Set migrations/000_migrations.yaml::106::sb failed.  Error: ERROR: must be owner of relation metabase_field [Failed SQL: ALTER TABLE public.metabase_field ALTER COLUMN database_type TYPE TEXT USING (database_type::TEXT)]
11-20 06:04:26 [1mWARN metabase.util[0m :: [31mauto-retry metabase.db$migrate_up_if_needed_BANG_$fn__18515@23481b1a: Migration failed for change set migrations/000_migrations.yaml::106::sb:
     Reason: liquibase.exception.DatabaseException: ERROR: must be owner of relation metabase_field [Failed SQL: ALTER TABLE public.metabase_field ALTER COLUMN database_type TYPE TEXT USING (database_type::TEXT)][0m
11-20 06:04:26 [1mERROR changelog.ChangeSet[0m :: Change Set migrations/000_migrations.yaml::106::sb failed.  Error: ERROR: must be owner of relation metabase_field [Failed SQL: ALTER TABLE public.metabase_field ALTER COLUMN database_type TYPE TEXT USING (database_type::TEXT)]
11-20 06:04:26 [1mWARN metabase.util[0m :: [31mauto-retry metabase.db$migrate_up_if_needed_BANG_$fn__18515@23481b1a: Migration failed for change set migrations/000_migrations.yaml::106::sb:
     Reason: liquibase.exception.DatabaseException: ERROR: must be owner of relation metabase_field [Failed SQL: ALTER TABLE public.metabase_field ALTER COLUMN database_type TYPE TEXT USING (database_type::TEXT)][0m
11-20 06:04:26 [1mERROR changelog.ChangeSet[0m :: Change Set migrations/000_migrations.yaml::106::sb failed.  Error: ERROR: must be owner of relation metabase_field [Failed SQL: ALTER TABLE public.metabase_field ALTER COLUMN database_type TYPE TEXT USING (database_type::TEXT)]
11-20 06:04:26 [1mERROR metabase.core[0m :: Metabase Initialization FAILED
liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::106::sb:
     Reason: liquibase.exception.DatabaseException: ERROR: must be owner of relation metabase_field [Failed SQL: ALTER TABLE public.metabase_field ALTER COLUMN database_type TYPE TEXT USING (database_type::TEXT)]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at metabase.db$migrate_up_if_needed_BANG_$fn__18515.invoke(db.clj:225)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:429)
	at metabase.util$do_with_auto_retries.invoke(util.clj:421)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:433)
	at metabase.util$do_with_auto_retries.invoke(util.clj:421)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:433)
	at metabase.util$do_with_auto_retries.invoke(util.clj:421)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:433)
	at metabase.util$do_with_auto_retries.invoke(util.clj:421)
	at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:225)
	at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:213)
	at metabase.db$migrate_BANG_$fn__18559.invoke(db.clj:332)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at metabase.db$migrate_BANG_.invokeStatic(db.clj:320)
	at metabase.db$migrate_BANG_.invoke(db.clj:299)
	at metabase.db$run_schema_migrations_BANG_$fn__18617.invoke(db.clj:459)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:429)
	at metabase.util$do_with_auto_retries.invoke(util.clj:421)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:433)
	at metabase.util$do_with_auto_retries.invoke(util.clj:421)
	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:458)
	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:441)
	at metabase.db$setup_db_BANG__STAR_$fn__18624.invoke(db.clj:480)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:677)
	at metabase.util$do_with_us_locale.invoke(util.clj:663)
	at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:478)
	at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:474)
	at metabase.db$setup_db_from_env_BANG__STAR_.invokeStatic(db.clj:488)
	at metabase.db$setup_db_from_env_BANG__STAR_.invoke(db.clj:485)
	at metabase.db$fn__18629$fn__18630.invoke(db.clj:495)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2320)
	at clojure.core$deref.invoke(core.clj:2306)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.core$init_BANG_.invokeStatic(core.clj:77)
	at metabase.core$init_BANG_.invoke(core.clj:56)
	at metabase.core$start_normally.invokeStatic(core.clj:123)
	at metabase.core$start_normally.invoke(core.clj:117)
	at metabase.core$_main.invokeStatic(core.clj:143)
	at metabase.core$_main.doInvoke(core.clj:138)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: liquibase.exception.DatabaseException: ERROR: must be owner of relation metabase_field [Failed SQL: ALTER TABLE public.metabase_field ALTER COLUMN database_type TYPE TEXT USING (database_type::TEXT)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 54 more
Caused by: org.postgresql.util.PSQLException: ERROR: must be owner of relation metabase_field
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
	... 59 more
11-20 06:04:26 [1mINFO metabase.core[0m :: Metabase Shutting Down ...
11-20 06:04:26 [1mINFO metabase.server[0m :: Shutting Down Embedded Jetty Webserver
11-20 06:04:27 [1mINFO metabase.core[0m :: Metabase Shutdown COMPLETE
11-20 06:04:31 [1mDEBUG plugins.classloader[0m :: Using NEWLY CREATED classloader as shared context classloader: clojure.lang.DynamicClassLoader@6812fa3a
11-20 06:04:31 [1mDEBUG plugins.classloader[0m :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@6812fa3a...
11-20 06:04:31 [1mINFO metabase.util[0m :: Loading Metabase...
11-20 06:04:31 [1mINFO metabase.util[0m :: Maximum memory available to JVM: 988.0 MB
```

**To Reproduce**
1. Modify `Dockerrun.aws.json` image to either `v0.33.5.1` or `v0.33.6`
2. Upload and deploy to AWS Elastic Beanstalk
3. See error in ELB logs

**Expected behavior**
Metabase to start properly.

**Information about your Metabase Installation:**
Last stable diagnostic info:
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "4.14.123-86.109.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-11-07",
      "tag": "v0.33.5",
      "branch": "release-0.33.x",
      "hash": "bf436b4"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

**Severity**
Blocks upgrading, but we can use 0.33.5 tag without an issue.

**Comment by flamber** [comment]
Hi @wollerman 
The hash you have specified (`bf436b4`) means that you are actually running a strange version of 0.33.4, which is why 0.33.5.1 was released.
There's a schema change in 0.33.5 ([changeset 106](https://github.com/metabase/metabase/blob/master/resources/migrations/000_migrations.yaml)), which means Metabase needs sufficient permissions to the application database (metadata) to change the structure. Note that I'm talking about the Postgres user that Metabase uses for the metadata, not the user you're using for datasources in Admin > Databases.
https://stackoverflow.com/questions/28584640/postgresql-error-must-be-owner-of-relation-when-changing-a-owner-object

**Comment by wollerman** [comment]
That makes sense, thanks!
