### ISSUE TITLE
All charts stop working after a random amount of time

### ISSUE THREAD

**Issue by SamHummerstone** [metabase/metabase#11391]
**Describe the bug**
After a couple of days, all metics and queries will fail with no obvious reason. The database it reads from hasn't run out of resources, and is still working. The metabase instance is a kubernetes pod and has no resource limiting.

**Logs**
These are the only logs produced when it is not working:
```
Exception in thread "async-dispatch-6854" java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
	at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:54)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:74)
	at ring.util.servlet$make_output_stream$fn__65545.invoke(servlet.clj:89)
	at ring.util.servlet.proxy$java.io.FilterOutputStream$ff19274a.close(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
	at java.base/java.io.BufferedWriter.close(Unknown Source)
	at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__64283$state_machine__12318__auto____64288$fn__64290.invoke(api_response.clj:87)
	at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__64283$state_machine__12318__auto____64288.invoke(api_response.clj:79)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__12336.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__7222$fn__7223.invoke(channels.clj:95)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "async-dispatch-6863" java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
	at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:54)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:74)
	at ring.util.servlet$make_output_stream$fn__65545.invoke(servlet.clj:89)
	at ring.util.servlet.proxy$java.io.FilterOutputStream$ff19274a.close(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
	at java.base/java.io.BufferedWriter.close(Unknown Source)
	at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__64283$state_machine__12318__auto____64288$fn__64290.invoke(api_response.clj:87)
	at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__64283$state_machine__12318__auto____64288.invoke(api_response.clj:79)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__12336.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__7222$fn__7223.invoke(channels.clj:95)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "async-dispatch-6862" Exception in thread "async-dispatch-6865" Exception in thread "async-dispatch-6858" java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
	at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:54)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:74)
	at ring.util.servlet$make_output_stream$fn__65545.invoke(servlet.clj:89)
	at ring.util.servlet.proxy$java.io.FilterOutputStream$ff19274a.close(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
	at java.base/java.io.BufferedWriter.close(Unknown Source)
	at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__64283$state_machine__12318__auto____64288$fn__64290.invoke(api_response.clj:87)
	at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__64283$state_machine__12318__auto____64288.invoke(api_response.clj:79)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__12336.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__7222$fn__7223.invoke(channels.clj:95)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
	at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:54)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:74)
	at ring.util.servlet$make_output_stream$fn__65545.invoke(servlet.clj:89)
	at ring.util.servlet.proxy$java.io.FilterOutputStream$ff19274a.close(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
	at java.base/java.io.BufferedWriter.close(Unknown Source)
	at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__64283$state_machine__12318__auto____64288$fn__64290.invoke(api_response.clj:87)
	at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__64283$state_machine__12318__auto____64288.invoke(api_response.clj:79)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__12336.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__7222$fn__7223.invoke(channels.clj:95)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
	at org.eclipse.jetty.server.AsyncContextState.state(AsyncContextState.java:54)
	at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:74)
	at ring.util.servlet$make_output_stream$fn__65545.invoke(servlet.clj:89)
	at ring.util.servlet.proxy$java.io.FilterOutputStream$ff19274a.close(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
	at java.base/java.io.BufferedWriter.close(Unknown Source)
	at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__64283$state_machine__12318__auto____64288$fn__64290.invoke(api_response.clj:87)
	at metabase.async.api_response$write_chan_vals_to_writer_BANG_$fn__64283$state_machine__12318__auto____64288.invoke(api_response.clj:79)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at clojure.core.async.impl.ioc_macros$take_BANG_$fn__12336.invoke(ioc_macros.clj:986)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__7222$fn__7223.invoke(channels.clj:95)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
and
```
11-26 09:29:01 DEBUG middleware.log :: POST /api/session/google_auth 200 59.3 ms (3 DB calls) Jetty threads: 3/50 (6 idle, 0 queued) (67 total active threads) Queries in flight: 83
11-26 09:29:01 DEBUG middleware.log :: GET /api/user/current 200 3.5 ms (3 DB calls) Jetty threads: 3/50 (6 idle, 0 queued) (67 total active threads) Queries in flight: 83
11-26 09:29:01 DEBUG middleware.log :: GET /api/database 200 4.9 ms (4 DB calls) Jetty threads: 3/50 (6 idle, 0 queued) (67 total active threads) Queries in flight: 83
11-26 09:29:01 DEBUG middleware.log :: GET /api/collection/root/items 200 14.5 ms (7 DB calls) Jetty threads: 3/50 (6 idle, 0 queued) (67 total active threads) Queries in flight: 83
11-26 09:29:01 DEBUG middleware.log :: GET /api/collection/root 200 2.9 ms (2 DB calls) Jetty threads: 3/50 (6 idle, 0 queued) (67 total active threads) Queries in flight: 83
11-26 09:29:06 DEBUG middleware.log :: GET /api/public/dashboard/d8dce6ce-1670-4465-856c-a0dd7c846755 200 16.1 ms (11 DB calls) Jetty threads: 3/50 (6 idle, 0 queued) (67 total active threads) Queries in flight: 83
```

**To Reproduce**
No particular steps, after 3 days or so this will occur and I will need to restart the pod to get a new instance to start up.

**Expected behavior**
For Metabase questions and pulses to work past 4 days of uptime

**Screenshots**

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.4+11",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.4",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.4+11",
    "os.name": "Linux",
    "os.version": "4.14.146-119.123.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-09-20",
      "tag": "v0.33.3",
      "branch": "release-0.33.x",
      "hash": "86d32bf"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
As we are using this in production, this means that no one in the company can ask questions from the database or see analytics at all during the times that this is broken. As the cluster admin I then need to restart it every time it breaks which is not ideal at, especially as we are hoping to use the enterprise level service.

**Additional context**
Approx 15 users using this

**Comment by flamber** [comment]
Hi @SamHummerstone 
What type of error do you see on the frontend, when it "queries fail"?
There has been a big change in 0.33.4 with how connections to the database are kept, so I would recommend that you upgrade. Latest release is 0.33.6
Always make backups before upgrading Metabase.

**Comment by flamber** [comment]
Closing this, since 0.35.0 now uses streaming responses and a fully async requests. See #11832
If you're still experiencing problems, then please comment with details and it will be reopened.
