### ISSUE TITLE
Support Postgres connection via UNIX socket that contain ":" for application DB (enables easy Google Cloud Run deployment) 

### ISSUE THREAD

**Issue by ghost** [metabase/metabase#11414]
**Is your feature request related to a problem? Please describe.**
I am trying to run Metabase on Google Cloud Run, using Postgres (via Cloud SQL) as the application database instead of H2. The problem is that Cloud Run only supports connections through Unix sockets. While I believe Unix sockets work just fine otherwise, in the particular case of Cloud SQL the socket name contains a ":", which breaks the regex used on MB_DB_CONNECTION_URI.

Cloud Run just entered GA and looks to be the cheapest option available for hosting Metabase on GCP. Running Metabase on App Engine still requires some hacks, so Cloud Run has the potential to be the cheapest AND easiest hosting option on GCP... with this one fix!

**Describe the solution you'd like**
Let us specify a %-encoded MB_DB_CONNECTION_URI to connect to Postgres via Unix socket that contains ":" characters.

**How important is this feature to you?**
I'm tied to GCP. App Engine Flex seems like overkill for a service used by 2-3 internal users max. Anything else requires more devops work than i care to undertake. So, a minor change would make it really easy (and cheap!) to work with Metabase.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
For reference - with some extra details:
https://discourse.metabase.com/t/has-anyone-deployed-metabase-to-google-cloud-run/8217

**Comment by ismail-a-khan** [comment]
Another nice-to-have is to allow specifying the port using "$PORT" instead of "$MB_JETTY_PORT". Cloud Run requires us to expose whatever port is specified by $PORT, but there's no easy way of doing that right now.

**Comment by flamber** [comment]
@ismail-a-khan There's an issue for `PORT` vs `MB_JETTY_PORT` - #3734 - upvote by clicking :+1:

**Comment by Kulikovpavel** [comment]
What is the final solution for UNIX socket connection string for postgresql?
Could you provide working example here?

**Comment by maitham** [comment]
Bump, what is the best way to do this?

**Comment by flamber** [comment]
Reopening since #19302 was backed out, which would be required to make this work on Google Cloud SQL.

**Comment by camsaul** [comment]
@Kulikovpavel @maitham this already works for the application database, unless you're on Google Cloud SQL. Just create an appropriate JDBC connection string (not 100% sure what this should look like, but you can figure this out yourself) and set the env var `MB_DB_CONNECTION_URI` with it.

**Comment by Kulikovpavel** [comment]
Usage of something like `host=/cloudsql/xxx:yyy:zzz` in additional db options leads to such error in logs

```
Caused by: java.lang.IllegalArgumentException: protocol = socket host = null
 at java.base/sun.net.spi.DefaultProxySelector.select(Unknown Source)
 at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
 at java.base/java.net.Socket.connect(Unknown Source)
 at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
 at org.postgresql.core.PGStream.<init>(PGStream.java:98)
 at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
 at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
 at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
 at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
 at org.postgresql.Driver.makeConnection(Driver.java:468)
 at org.postgresql.Driver.connect(Driver.java:267)
 
{:valid false,
 :dbname "Something unusual has occurred to cause the driver to fail. Please report this exception.",
 :message "Something unusual has occurred to cause the driver to fail. Please report this exception."}
```

**Comment by camsaul** [comment]
@Kulikovpavel "additional db options" is not for the **application database**, so this isn't the right issue. We actually don't have an issue that I can find to track supporting JDBC URLs directly for connected databases. I opened #27116 to track this. You can follow that issue

**Comment by camsaul** [comment]
This issue is really asking for two separate things:

- I think about 90% of what is being asked for here is to support JDBC URLs for the application Database that contain `:` (which has been supported since #19961)
- The other 10% is to support connecting to Google Cloud Postgres databases using the Google cloud socket factories 

Currently we can't do anything about shipping the cloud socket factories because of the aforementioned BigQuery issues. So that 10% of this issue is stuck. Since the socket factory problem applies to MySQL as well and also to data warehouse databases I'm consolidating tracking for fixing that specifically into #27117. Since the other 90% of this issue is already fixed I'm going to go ahead and close this out.

#27117 will track fixing the GCP socket factory issues

**Comment by balki** [comment]
I tried this today and unix sockets do not work.
Ref: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS 
```
MB_DB_CONNECTION_URI=jdbc:postgresql:///metabase?host=/var/run/postgresql&user=mbuser&password=foobar
```

Error
```
2025-01-22 18:49:54,202 INFO db.setup :: Verifying postgres Database Connection ...
2025-01-22 18:50:37,301 ERROR metabase.core :: Metabase Initialization FAILED
clojure.lang.ExceptionInfo: Unable to connect to Metabase postgres DB. {}
        at metabase.db.setup$verify_db_connection55779__55780$fn__55781.invoke(setup.clj:117)
        at metabase.db.setup$verify_db_connection55779__55780.invokeStatic(setup.clj:115)
        at metabase.db.setup$verify_db_connection55779__55780.invoke(setup.clj:107)
        at metabase.db.setup$setup_db_BANG_55803__55804$fn__55807$fn__55808.invoke(setup.clj:165)
        at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:259)
        at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:245)
        at metabase.db.setup$setup_db_BANG_55803__55804$fn__55807.invoke(setup.clj:161)
        at metabase.db.setup$setup_db_BANG_55803__55804.invokeStatic(setup.clj:160)
        at metabase.db.setup$setup_db_BANG_55803__55804.invoke(setup.clj:153)
        at metabase.db$setup_db_BANG_$fn__55832.invoke(db.clj:86)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:81)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:68)
        at clojure.lang.RestFn.invoke(RestFn.java:424)
        at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:121)
        at metabase.core$init_BANG__STAR_.invoke(core.clj:102)
        at metabase.core$init_BANG_.invokeStatic(core.clj:180)
        at metabase.core$init_BANG_.invoke(core.clj:175)
        at metabase.core$start_normally.invokeStatic(core.clj:192)
        at metabase.core$start_normally.invoke(core.clj:186)
        at metabase.core$entrypoint.invokeStatic(core.clj:228)
        at metabase.core$entrypoint.doInvoke(core.clj:219)
        at clojure.lang.RestFn.invoke(RestFn.java:400)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:135)
        at clojure.lang.Var.applyTo(Var.java:707)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
        at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
        at clojure.lang.RestFn.invoke(RestFn.java:400)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:135)
        at metabase.bootstrap.main(Unknown Source)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:117)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:901)
        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:105)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:372)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:395)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:392)
        at clojure.lang.Var.invoke(Var.java:386)
        at metabase.db.setup$verify_db_connection55779__55780$fn__55781.invoke(setup.clj:115)
        ... 32 more
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1445)
        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:580)
        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:490)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndScacheMarkConnectionInUse(C3P0PooledConnectionPool.java:965)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:893)
        ... 45 more
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
        at org.postgresql.Driver.makeConnection(Driver.java:446)
        at org.postgresql.Driver.connect(Driver.java:298)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at metabase.db.data_source.DataSource.getConnection(data_source.clj:78)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:119)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:509)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1112)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1099)
        at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:9)
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1846)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
Caused by: java.io.IOException: Failed to select a proxy
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
        at org.postgresql.core.PGStream.<init>(PGStream.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
        ... 14 more
Caused by: java.lang.IllegalArgumentException: protocol = socket host = null
        at java.base/sun.net.spi.DefaultProxySelector.select(Unknown Source)
        ... 20 more
2025-01-22 18:50:37,307 INFO metabase.core :: Metabase Shutting Down ...
```
