### ISSUE TITLE
 Unrecognized token 'mle': was expecting ('true', 'false' or 'null')

### ISSUE THREAD

**Issue by suratpyari** [metabase/metabase#11433]
I am setting up metabase again on kubernates. Right now using latest metabase docker image. I am trying to set it up for existing metabase database. But after connection I am receiving following error ...

```
ERROR models.interface :: Error parsing JSON
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'mle': was expecting ('true', 'false' or 'null')
 at [Source: (StringReader); line: 1, column: 4]

```

complete trace:

```
12-03 17:12:52 INFO metabase.events :: Starting events listener: metabase.events.notifications 👂
12-03 17:12:52 INFO metabase.events :: Starting events listener: metabase.events.metabot-lifecycle 👂
12-03 17:12:52 INFO metabase.events :: Starting events listener: metabase.events.dependencies 👂
12-03 17:12:52 INFO metabase.events :: Starting events listener: metabase.events.activity-feed 👂
12-03 17:12:52 INFO metabase.events :: Starting events listener: metabase.events.last-login 👂
12-03 17:12:52 INFO metabase.events :: Starting events listener: metabase.events.revision 👂
12-03 17:12:52 INFO metabase.events :: Starting events listener: metabase.events.sync-database 👂
12-03 17:12:52 INFO metabase.events :: Starting events listener: metabase.events.view-log 👂
12-03 17:12:52 INFO metabase.events :: Starting events listener: metabase.events.driver-notifications 👂
12-03 17:12:52 INFO metabase.task :: Initializing task SyncDatabases 📆
12-03 17:12:52 ERROR models.interface :: Error parsing JSON
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'mle': was expecting ('true', 'false' or 'null')
 at [Source: (StringReader); line: 1, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:679)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1889)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
	at cheshire.parse$parse.invokeStatic(parse.clj:88)
	at cheshire.parse$parse.invoke(parse.clj:86)
	at cheshire.core$parse_string.invokeStatic(core.clj:206)
	at cheshire.core$parse_string.invoke(core.clj:192)
	at cheshire.core$parse_string.invokeStatic(core.clj:203)
	at cheshire.core$parse_string.invoke(core.clj:192)
	at metabase.models.interface$json_out.invokeStatic(interface.clj:40)
	at metabase.models.interface$json_out.invoke(interface.clj:36)
	at metabase.models.interface$json_out_with_keywordization.invokeStatic(interface.clj:49)
	at metabase.models.interface$json_out_with_keywordization.invoke(interface.clj:46)
	at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at clojure.core.memoize$through_STAR_$fn__6968.invoke(memoize.clj:104)
	at clojure.core.cache$through$fn__6692.invoke(cache.clj:55)
	at clojure.core.memoize$through_STAR_$fn__6964$fn__6965.invoke(memoize.clj:103)
	at clojure.core.memoize.RetryingDelay.deref(memoize.clj:66)
	at clojure.core$deref.invokeStatic(core.clj:2320)
	at clojure.core$deref.invoke(core.clj:2306)
	at clojure.core.memoize$build_memoizer$fn__7049.doInvoke(memoize.clj:210)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	at toucan.models$apply_type_fns$iter__18091__18095$fn__18096.invoke(models.clj:304)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$into.invokeStatic(core.clj:6895)
	at clojure.core$into.invoke(core.clj:6887)
	at toucan.models$apply_type_fns.invokeStatic(models.clj:302)
	at toucan.models$apply_type_fns.invoke(models.clj:299)
	at toucan.models$do_post_select.invokeStatic(models.clj:349)
	at toucan.models$do_post_select.invoke(models.clj:344)
	at toucan.db$do_post_select$iter__18314__18318$fn__18319.invoke(db.clj:370)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
	at clojure.core$vec.invokeStatic(core.clj:377)
	at clojure.core$vec.invoke(core.clj:367)
	at toucan.db$do_post_select.invokeStatic(db.clj:369)
	at toucan.db$do_post_select.invoke(db.clj:360)
	at toucan.db$simple_select.invokeStatic(db.clj:391)
	at toucan.db$simple_select.invoke(db.clj:380)
	at toucan.db$select.invokeStatic(db.clj:659)
	at toucan.db$select.doInvoke(db.clj:653)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.task.sync_databases$fn__68385.invokeStatic(sync_databases.clj:191)
	at metabase.task.sync_databases$fn__68385.invoke(sync_databases.clj:189)
	at metabase.task$init_tasks_BANG_$fn__62786.invoke(task.clj:80)
	at metabase.task$init_tasks_BANG_.invokeStatic(task.clj:76)
	at metabase.task$init_tasks_BANG_.invoke(task.clj:72)
	at metabase.task$start_scheduler_BANG_.invokeStatic(task.clj:146)
	at metabase.task$start_scheduler_BANG_.invoke(task.clj:136)
	at metabase.core$init_BANG_.invokeStatic(core.clj:89)
	at metabase.core$init_BANG_.invoke(core.clj:56)
	at metabase.core$start_normally.invokeStatic(core.clj:123)
	at metabase.core$start_normally.invoke(core.clj:117)
	at metabase.core$_main.invokeStatic(core.clj:143)
	at metabase.core$_main.doInvoke(core.clj:138)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
12-03 17:12:52 INFO metabase.task :: Initializing task CheckForNewVersions 📆
12-03 17:12:52 INFO metabase.task :: Initializing task SendAnonymousUsageStats 📆
12-03 17:12:52 INFO metabase.task :: Initializing task SendAbandomentEmails 📆
12-03 17:12:52 INFO metabase.task :: Initializing task SendPulses 📆
12-03 17:12:52 INFO metabase.task :: Initializing task SendFollowUpEmails 📆
12-03 17:12:52 INFO metabase.task :: Initializing task TaskHistoryCleanup 📆
12-03 17:12:52 INFO metabase.core :: Metabase Initialization COMPLETE
12-03 17:13:05 INFO metabase.metabot :: Starting MetaBot threads...
12-03 17:13:05 INFO metabot.instance :: This instance will now handle MetaBot duties.
```

**Comment by flamber** [comment]
Hi @suratpyari 
Please post the Diagnostic Info from Admin > Troubleshooting.
What is your run-command for the container?

**Comment by suratpyari** [comment]
Yes that is the log I received when I started the container. container is still running but url showing same error in json format.

**Comment by suratpyari** [comment]
As I can not access application I am not able to post diagnostic info to Admin > Troubleshooting. When I started app I see "Grafana" screen instead of metabase screen and on login I received this error.

**Comment by flamber** [comment]
@suratpyari 
Okay, then it sounds like it's a problem with conflicting ports. Are you perhaps running multiple things on port `3000`, which is the default for Metabase and Grafana?
Have you ever been able to start Metabase or is this your first try?

**Comment by suratpyari** [comment]
Its my first try. for other instance (on uat) its working but for production its not working. I am using 3000 port for rails app *BUT* on cluster where I am receiving this error not running rails right now. only elastic search and redis is running.

**Comment by suratpyari** [comment]
My old system was on  version 0.31.0 so instead of latest one I used this version too. But still getting same error.

**Comment by flamber** [comment]
@suratpyari Well, since you're seeing Grafana, when you connect to where Metabase should be, should hint that it's a problem with conflicting ports. It's difficult to help, when this is specific to your setup. But Metabase should do some test to verify itself instead of throwing that type of error.

**Comment by suratpyari** [comment]
I have terminated all services. Still metabase is giving error ...

```
kl metabase-production-5c95b9cbcb-mbl69 -n new -f
12-04 06:09:26 INFO metabase.util :: Loading Metabase...
12-04 06:09:31 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
 For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
12-04 06:09:41 INFO metabase.core :: Starting Metabase in STANDALONE mode
12-04 06:09:41 INFO metabase.core :: Launching Embedded Jetty Webserver with config: 
 {:port 3000, :host "0.0.0.0"}

12-04 06:09:41 INFO metabase.core :: Starting Metabase version v0.31.0 (adf9a89 release-0.31.0) ...
12-04 06:09:41 INFO metabase.core :: System timezone is 'GMT' ...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
12-04 06:09:43 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
12-04 06:09:43 INFO metabase.db :: Verifying postgres Database Connection ...
12-04 06:09:43 INFO metabase.db :: Verify Database Connection ...  ✅
12-04 06:09:43 INFO metabase.db :: Running Database Migrations...
12-04 06:09:43 INFO metabase.db :: Setting up Liquibase...
12-04 06:09:43 INFO metabase.db :: Liquibase is ready.
12-04 06:09:43 INFO metabase.db :: Checking if Database has unrun migrations...
12-04 06:09:46 INFO metabase.db :: Database Migrations Current ...  ✅
12-04 06:09:46 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
12-04 06:09:46 INFO db.migrations :: Finished running data migrations.
12-04 06:09:46 INFO metabase.events :: Starting events listener: metabase.events.activity-feed 👂
12-04 06:09:46 INFO metabase.events :: Starting events listener: metabase.events.dependencies 👂
12-04 06:09:46 INFO metabase.events :: Starting events listener: metabase.events.driver-notifications 👂
12-04 06:09:46 INFO metabase.events :: Starting events listener: metabase.events.last-login 👂
12-04 06:09:46 INFO metabase.events :: Starting events listener: metabase.events.metabot-lifecycle 👂
12-04 06:09:46 INFO metabase.events :: Starting events listener: metabase.events.notifications 👂
12-04 06:09:46 INFO metabase.events :: Starting events listener: metabase.events.revision 👂
12-04 06:09:46 INFO metabase.events :: Starting events listener: metabase.events.sync-database 👂
12-04 06:09:46 INFO metabase.events :: Starting events listener: metabase.events.view-log 👂
12-04 06:09:47 INFO metabase.task :: Loading tasks namespace: metabase.task.DynamicClassLoadHelper 📆
12-04 06:09:47 INFO metabase.task :: Loading tasks namespace: metabase.task.follow-up-emails 📆
12-04 06:09:47 INFO metabase.task :: Job already exists: metabase.task.follow-up-emails.job
12-04 06:09:47 INFO metabase.task :: Job already exists: metabase.task.abandonment-emails.job
12-04 06:09:47 INFO metabase.task :: Loading tasks namespace: metabase.task.send-anonymous-stats 📆
12-04 06:09:47 INFO metabase.task :: Job already exists: metabase.task.anonymous-stats.job
12-04 06:09:47 INFO metabase.task :: Loading tasks namespace: metabase.task.send-pulses 📆
12-04 06:09:47 INFO metabase.task :: Job already exists: metabase.task.send-pulses.job
12-04 06:09:47 INFO metabase.task :: Loading tasks namespace: metabase.task.sync-databases 📆
12-04 06:09:47 ERROR metabase.core :: Metabase Initialization FAILED
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'mle': was expecting ('true', 'false' or 'null')
 at [Source: java.io.StringReader@28d1d634; line: 1, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2839)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1903)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
	at cheshire.parse$parse.invokeStatic(parse.clj:88)
	at cheshire.parse$parse.invoke(parse.clj:86)
	at cheshire.core$parse_string.invokeStatic(core.clj:205)
	at cheshire.core$parse_string.invoke(core.clj:191)
	at cheshire.core$parse_string.invokeStatic(core.clj:202)
	at cheshire.core$parse_string.invoke(core.clj:191)
	at metabase.models.interface$json_out.invokeStatic(interface.clj:38)
	at metabase.models.interface$json_out.invoke(interface.clj:35)
	at metabase.models.interface$json_out_with_keywordization.invokeStatic(interface.clj:44)
	at metabase.models.interface$json_out_with_keywordization.invoke(interface.clj:41)
	at clojure.core$comp$fn__5529.invoke(core.clj:2561)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at clojure.core.memoize$through_STAR_$fn__4105.invoke(memoize.clj:81)
	at clojure.core.cache$through$fn__3894.invoke(cache.clj:55)
	at clojure.core.memoize$through_STAR_$fn__4101$fn__4102.invoke(memoize.clj:80)
	at clojure.core.memoize.RetryingDelay.deref(memoize.clj:64)
	at clojure.core$deref.invokeStatic(core.clj:2312)
	at clojure.core$deref.invoke(core.clj:2298)
	at clojure.core.memoize$build_memoizer$fn__4164.doInvoke(memoize.clj:167)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$comp$fn__5529.invoke(core.clj:2561)
	at toucan.models$apply_type_fns$iter__14967__14971$fn__14972.invoke(models.clj:295)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6748)
	at clojure.core$into.invokeStatic(core.clj:6815)
	at clojure.core$into.invoke(core.clj:6807)
	at toucan.models$apply_type_fns.invokeStatic(models.clj:293)
	at toucan.models$apply_type_fns.invoke(models.clj:290)
	at toucan.models$do_post_select.invokeStatic(models.clj:340)
	at toucan.models$do_post_select.invoke(models.clj:335)
	at toucan.db$do_post_select$iter__15183__15187$fn__15188.invoke(db.clj:358)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
	at clojure.core$vec.invokeStatic(core.clj:377)
	at clojure.core$vec.invoke(core.clj:367)
	at toucan.db$do_post_select.invokeStatic(db.clj:357)
	at toucan.db$do_post_select.invoke(db.clj:348)
	at toucan.db$simple_select.invokeStatic(db.clj:379)
	at toucan.db$simple_select.invoke(db.clj:368)
	at toucan.db$select.invokeStatic(db.clj:641)
	at toucan.db$select.doInvoke(db.clj:635)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.task.sync_databases$task_init.invokeStatic(sync_databases.clj:190)
	at metabase.task.sync_databases$task_init.invoke(sync_databases.clj:185)
	at clojure.lang.Var.invoke(Var.java:377)
	at metabase.task$find_and_load_tasks_BANG_.invokeStatic(task.clj:47)
	at metabase.task$find_and_load_tasks_BANG_.invoke(task.clj:38)
	at metabase.task$start_scheduler_BANG_.invokeStatic(task.clj:81)
	at metabase.task$start_scheduler_BANG_.invoke(task.clj:72)
	at metabase.core$init_BANG_.invokeStatic(core.clj:174)
	at metabase.core$init_BANG_.invoke(core.clj:139)
	at metabase.core$start_normally.invokeStatic(core.clj:246)
	at metabase.core$start_normally.invoke(core.clj:240)
	at metabase.core$_main.invokeStatic(core.clj:266)
	at metabase.core$_main.doInvoke(core.clj:261)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
12-04 06:09:47 INFO metabase.core :: Metabase Shutting Down ...
12-04 06:09:47 INFO metabase.core :: Metabase Shutdown COMPLETE

```

Here are the list of pods running ...

```
kube-system   aws-node-4n26z                         1/1     Running            0          4d20h
kube-system   aws-node-7b4p4                         1/1     Running            0          4d20h
kube-system   aws-node-7fhvb                         1/1     Running            0          4d20h
kube-system   aws-node-7wvwr                         1/1     Running            0          4d20h
kube-system   aws-node-9gpbc                         1/1     Running            0          4d20h
kube-system   aws-node-9stqk                         1/1     Running            0          4d20h
kube-system   aws-node-h7q8v                         1/1     Running            0          4d20h
kube-system   aws-node-k7xlv                         1/1     Running            0          4d20h
kube-system   aws-node-m5gnq                         1/1     Running            0          4d20h
kube-system   aws-node-m6cbz                         1/1     Running            0          4d20h
kube-system   aws-node-s2n6s                         1/1     Running            0          4d20h
kube-system   aws-node-sfgzx                         1/1     Running            0          4d20h
kube-system   coredns-5b9879fcff-hskzs               1/1     Running            0          4d20h
kube-system   coredns-5b9879fcff-jqcph               1/1     Running            0          4d20h
kube-system   kube-proxy-6xlzc                       1/1     Running            0          4d20h
kube-system   kube-proxy-87qzl                       1/1     Running            0          4d20h
kube-system   kube-proxy-9znlt                       1/1     Running            0          4d20h
kube-system   kube-proxy-cmvf2                       1/1     Running            0          4d20h
kube-system   kube-proxy-f7lzn                       1/1     Running            0          4d20h
kube-system   kube-proxy-g2pzd                       1/1     Running            0          4d20h
kube-system   kube-proxy-n5472                       1/1     Running            0          4d20h
kube-system   kube-proxy-p9fhl                       1/1     Running            0          4d20h
kube-system   kube-proxy-pztd5                       1/1     Running            0          4d20h
kube-system   kube-proxy-skhhk                       1/1     Running            0          4d20h
kube-system   kube-proxy-tbcks                       1/1     Running            0          4d20h
kube-system   kube-proxy-xmfb8                       1/1     Running            0          4d20h
new           metabase-production-5c95b9cbcb-7fl4z   0/1     CrashLoopBackOff   1          74s
new           metabase-production-5c95b9cbcb-stxm2   1/1     Running            2          74s
```

**Comment by flamber** [comment]
@suratpyari I don't use Kubernetes, so I don't know that process overview, but let's focus on the latest 0.33.6 instead of 0.31.0, which is more than a year old.
If you're using Helm, then post your configuration:
https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-kubernetes.html

This warning reminds me of a [forum post](https://discourse.metabase.com/t/problem-after-dist-upgrade-ubuntu-16-04-18-04/8054), where suddenly Metabase stopped working after an OS upgrade, while using MySQL for metadata and `MB_ENCRYPTION_SECRET_KEY`
So are you using MySQL and encryption key? If yes, then it might likely be #11048

**Comment by suratpyari** [comment]
Creating new database and moving data there solved this issue.

**Comment by suratpyari** [comment]
Thanks a ton @flamber
