### ISSUE TITLE
how to connect sparksql in kerberos env?

### ISSUE THREAD

**Issue by hicenlee1** [metabase/metabase#11457]
is there as way to connect sparksql in kerberos enviroment? 
I have tried to kinit in shell and then running metabase,  but failed.
key log as ：

java.sql.SQLException: Could not open client transport with JDBC Uri: jdbc:hive2://**:10016/log;principal=hive/***@**.COM;transportMode=http&useUnicode=true&characterEncoding=utf8&autoReconnect=true&tinyInt1isBit=false&useSSL=false: GSS initiate failed
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:231)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:176)
	at metabase.driver.FixedHiveConnection.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:294)
	at metabase.driver.FixedHiveDriver$driver_connect.invokeStatic(FixedHiveDriver.clj:20)
	at metabase.driver.FixedHiveDriver$driver_connect.invoke(FixedHiveDriver.clj:16)
	at metabase.driver.FixedHiveDriver.connect(Unknown Source)
	at metabase.plugins.jdbc_proxy$proxy_driver$reify__66297.connect(jdbc_proxy.clj:32)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1093)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1142)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:159)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:154)
	at metabase.driver.sql_jdbc$fn__67312.invokeStatic(sql_jdbc.clj:35)
	at metabase.driver.sql_jdbc$fn__67312.invoke(sql_jdbc.clj:34)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__19311.invoke(util.clj:31)
	at metabase.util$do_with_timeout$fn__6284.invoke(util.clj:334)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: GSS initiate failed
	at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:316)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
	at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:52)
	at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:49)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport.open(TUGIAssumingTransport.java:49)
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:204)
	... 36 more

**Comment by flamber** [comment]
Hi @hicenlee1 
Seems like you're not including a hostname. You might want to test from the commandline until you got everything working with kinit and know which connection string parameters to set.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And please close this issue :+1:

**Comment by hicenlee1** [comment]
Thank @flamber
In fact the hostname is set. I replace it with whitespace.
