### ISSUE TITLE
ERROR core.JobRunShell :: Job DEFAULT.metabase.task.abandonment-emails.job threw an unhandled Exception: 

### ISSUE THREAD

**Issue by aniketpanjwani** [metabase/metabase#11618]
**Describe the bug**
An error with (what appears to be) a nightly cron job crashed the Metabase application.

**Logs**
```
2020-01-02T12:00:00.014200354Z 01-02 12:00:00 ERROR core.JobRunShell :: Job DEFAULT.metabase.task.abandonment-emails.job threw an unhandled Exception: 
2020-01-02T12:00:00.014241519Z org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
2020-01-02T12:00:00.014247671Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:337)
2020-01-02T12:00:00.014253194Z 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
2020-01-02T12:00:00.014258270Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
2020-01-02T12:00:00.014276313Z 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
2020-01-02T12:00:00.014279923Z 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
2020-01-02T12:00:00.014283113Z 	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)
2020-01-02T12:00:00.014289058Z 	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)
2020-01-02T12:00:00.014296414Z 	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)
2020-01-02T12:00:00.014300989Z 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1095)
2020-01-02T12:00:00.014304059Z 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
2020-01-02T12:00:00.014307090Z 	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
2020-01-02T12:00:00.014310187Z 	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
2020-01-02T12:00:00.014313129Z 	at toucan.db$query.invokeStatic(db.clj:285)
2020-01-02T12:00:00.014316120Z 	at toucan.db$query.doInvoke(db.clj:281)
2020-01-02T12:00:00.014319039Z 	at clojure.lang.RestFn.invoke(RestFn.java:410)
2020-01-02T12:00:00.014322068Z 	at toucan.db$simple_select.invokeStatic(db.clj:391)
2020-01-02T12:00:00.014325006Z 	at toucan.db$simple_select.invoke(db.clj:380)
2020-01-02T12:00:00.014327921Z 	at toucan.db$simple_select_one.invokeStatic(db.clj:417)
2020-01-02T12:00:00.014330968Z 	at toucan.db$simple_select_one.invoke(db.clj:406)
2020-01-02T12:00:00.014334004Z 	at toucan.db$select_one.invokeStatic(db.clj:624)
2020-01-02T12:00:00.014336906Z 	at toucan.db$select_one.doInvoke(db.clj:617)
2020-01-02T12:00:00.014339847Z 	at clojure.lang.RestFn.applyTo(RestFn.java:139)
2020-01-02T12:00:00.014342761Z 	at clojure.core$apply.invokeStatic(core.clj:667)
2020-01-02T12:00:00.014345690Z 	at clojure.core$apply.invoke(core.clj:660)
2020-01-02T12:00:00.014348627Z 	at toucan.db$select_one_field.invokeStatic(db.clj:633)
2020-01-02T12:00:00.014351583Z 	at toucan.db$select_one_field.doInvoke(db.clj:626)
2020-01-02T12:00:00.014354495Z 	at clojure.lang.RestFn.invoke(RestFn.java:490)
2020-01-02T12:00:00.014357475Z 	at metabase.task.follow_up_emails$send_abandoment_email_if_needed_BANG_.invokeStatic(follow_up_emails.clj:118)
2020-01-02T12:00:00.014361656Z 	at metabase.task.follow_up_emails$send_abandoment_email_if_needed_BANG_.invoke(follow_up_emails.clj:114)
2020-01-02T12:00:00.014364913Z 	at metabase.task.follow_up_emails.AbandonmentEmail.execute(follow_up_emails.clj:135)
2020-01-02T12:00:00.014368055Z 	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
2020-01-02T12:00:00.014371067Z 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
2020-01-02T12:00:00.014374127Z Caused by: java.net.SocketException: Connection reset
2020-01-02T12:00:00.014383385Z 	at java.base/java.net.SocketInputStream.read(Unknown Source)
2020-01-02T12:00:00.014386493Z 	at java.base/java.net.SocketInputStream.read(Unknown Source)
2020-01-02T12:00:00.014395698Z 	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
2020-01-02T12:00:00.014399059Z 	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
2020-01-02T12:00:00.014402177Z 	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
2020-01-02T12:00:00.014405276Z 	at org.postgresql.core.PGStream.receiveChar(PGStream.java:335)
2020-01-02T12:00:00.014408247Z 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2000)
2020-01-02T12:00:00.014412038Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
2020-01-02T12:00:00.014416467Z 	... 31 more
2020-01-02T12:00:00.014449010Z 01-02 12:00:00 ERROR core.ErrorLogger :: Job (DEFAULT.metabase.task.abandonment-emails.job threw an exception.
2020-01-02T12:00:00.014455944Z org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.]
2020-01-02T12:00:00.014461067Z 	at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
2020-01-02T12:00:00.014465024Z 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
2020-01-02T12:00:00.014469965Z Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
2020-01-02T12:00:00.014474422Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:337)
2020-01-02T12:00:00.014478521Z 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
2020-01-02T12:00:00.014482498Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
2020-01-02T12:00:00.014486794Z 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
2020-01-02T12:00:00.014490915Z 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
2020-01-02T12:00:00.014495066Z 	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)
2020-01-02T12:00:00.014499742Z 	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)
2020-01-02T12:00:00.014503858Z 	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)
2020-01-02T12:00:00.014508138Z 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1095)
2020-01-02T12:00:00.014512279Z 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
2020-01-02T12:00:00.014516979Z 	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
2020-01-02T12:00:00.014521575Z 	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
2020-01-02T12:00:00.014530428Z 	at toucan.db$query.invokeStatic(db.clj:285)
2020-01-02T12:00:00.014533716Z 	at toucan.db$query.doInvoke(db.clj:281)
2020-01-02T12:00:00.014536672Z 	at clojure.lang.RestFn.invoke(RestFn.java:410)
2020-01-02T12:00:00.014539694Z 	at toucan.db$simple_select.invokeStatic(db.clj:391)
2020-01-02T12:00:00.014542661Z 	at toucan.db$simple_select.invoke(db.clj:380)
2020-01-02T12:00:00.014545579Z 	at toucan.db$simple_select_one.invokeStatic(db.clj:417)
2020-01-02T12:00:00.014548549Z 	at toucan.db$simple_select_one.invoke(db.clj:406)
2020-01-02T12:00:00.014551568Z 	at toucan.db$select_one.invokeStatic(db.clj:624)
2020-01-02T12:00:00.014554526Z 	at toucan.db$select_one.doInvoke(db.clj:617)
2020-01-02T12:00:00.014557442Z 	at clojure.lang.RestFn.applyTo(RestFn.java:139)
2020-01-02T12:00:00.014560387Z 	at clojure.core$apply.invokeStatic(core.clj:667)
2020-01-02T12:00:00.014563407Z 	at clojure.core$apply.invoke(core.clj:660)
2020-01-02T12:00:00.014566862Z 	at toucan.db$select_one_field.invokeStatic(db.clj:633)
2020-01-02T12:00:00.014569930Z 	at toucan.db$select_one_field.doInvoke(db.clj:626)
2020-01-02T12:00:00.014572864Z 	at clojure.lang.RestFn.invoke(RestFn.java:490)
2020-01-02T12:00:00.014575942Z 	at metabase.task.follow_up_emails$send_abandoment_email_if_needed_BANG_.invokeStatic(follow_up_emails.clj:118)
2020-01-02T12:00:00.014579079Z 	at metabase.task.follow_up_emails$send_abandoment_email_if_needed_BANG_.invoke(follow_up_emails.clj:114)
2020-01-02T12:00:00.014582221Z 	at metabase.task.follow_up_emails.AbandonmentEmail.execute(follow_up_emails.clj:135)
2020-01-02T12:00:00.014585261Z 	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
2020-01-02T12:00:00.014588245Z 	... 1 more
2020-01-02T12:00:00.014591166Z Caused by: java.net.SocketException: Connection reset
2020-01-02T12:00:00.014594132Z 	at java.base/java.net.SocketInputStream.read(Unknown Source)
2020-01-02T12:00:00.014597112Z 	at java.base/java.net.SocketInputStream.read(Unknown Source)
2020-01-02T12:00:00.014600116Z 	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
2020-01-02T12:00:00.014603192Z 	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
2020-01-02T12:00:00.014606296Z 	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
2020-01-02T12:00:00.014609332Z 	at org.postgresql.core.PGStream.receiveChar(PGStream.java:335)
2020-01-02T12:00:00.014612319Z 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2000)
2020-01-02T12:00:00.014615379Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
2020-01-02T12:00:00.014618462Z 	... 31 more
2020-01-02T12:00:00.068874120Z 01-02 12:00:00 INFO task.send-pulses :: Sending scheduled pulses...
```
**To Reproduce**
Here is what I've done so far with my hours-old Metabase installation:

1. Boot up a Docker container using the [metabase Docker image](https://hub.docker.com/r/metabase/metabase) with Postgres as the application database (in a different container on the same server).
2. Create a user, and connect Metabase to a different Postgres database (on AWS RDS) with a read-only user.
3. Set up emails using AWS SES with TLS.
4. Wait for cron job, and see application crash and error in logs.

**Expected behavior**

No issues with the nightly cron job.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Not relevant - server issue.
- Your operating system: Not relevant -server issue.
- Your databases: Postgres
- Metabase version: (e.x. 0.19.3): v0.34.0
- Metabase hosting environment: Docker container using CapRover
- Metabase internal database: Postgres

**Severity**

It's severe for me, since I'm considering moving from Redash to Metabase, but I can't do so if I can expect the application to crash each night. But, feel free to triage this if your intuition is that whatever is going on is not affecting other/specific to my installatoin.

**Additional context**

I deployed Metabase using [CapRover](https://github.com/caprover/caprover), which is a wrapper around Docker Swarm and nginx.

**Comment by flamber** [comment]
Hi @aniketpanjwani 
I have never seen a crash from this task before. But from the trace, it seems like Metabase has lost the connection to application database. That shouldn't crash Metabase, but might help you look at other logs too, since any extra information would help debug this.

**Comment by aniketpanjwani** [comment]
That sounds right, the application database has a bunch of logs like this:

```
2020-01-02T03:00:46.066455336Z LOG:  could not receive data from client: Connection reset by peer
2020-01-02T03:03:29.908477822Z LOG:  could not receive data from client: Connection reset by peer
2020-01-02T03:22:42.162367890Z LOG:  could not receive data from client: Connection reset by peer
2020-01-02T03:24:47.860547920Z LOG:  could not receive data from client: Connection reset by peer
2020-01-02T03:24:47.860583850Z LOG:  could not receive data from client: Connection reset by peer
2020-01-02T04:01:56.082563842Z LOG:  could not receive data from client: Connection reset by peer
```

I'll try restarting the application database, and see if I can get Metabase working again.

**Comment by camsaul** [comment]
Same issue as #12068. Closing this issue in favor of that one because it has more info
