### ISSUE TITLE
Third party driver doesn't get initialised properly

### ISSUE THREAD

**Issue by gpodevijn** [metabase/metabase#12011]
**Severity**

It is blocking me and my company (DataCamp) from using and subscribing to Metabase enterprise

**Describe the bug**

I am creating a third-party driver that should support Redshift's external tables.
Before patching the current Redshift driver, I'm making some tests by creating a third-party one. However, it failed when being initialized.

Please note that the driver works well when I add the driver within the Metabase sources (as explained here: https://github.com/metabase/metabase/wiki/Writing-a-Driver:-Packaging-a-Driver-&-Metabase-Plugin-Basics#drivers-built-in-to-the-core-metabase-project)

**Logs**

I can't figure out what's happening based on the below error.

> 02-28 15:28:33 INFO driver.impl :: Initializing driver :postgres...
02-28 15:28:33 INFO driver.impl :: Initializing driver :redshiftspectrum...
02-28 15:28:33 INFO plugins.classloader :: Added URL file:/plugins/redshiftspectrum.metabase-driver.jar to classpath
02-28 15:28:33 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.postgres...
02-28 15:28:33 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.redshiftspectrum...
02-28 15:28:33 INFO driver.impl :: Registered abstract driver :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set  🚚
02-28 15:28:33 INFO driver.impl :: Registered driver :redshiftspectrum (parents: [:postgres :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set]) 🚚
02-28 15:28:33 ERROR driver.util :: Database connection error
java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.plugins.classloader$require.invokeStatic(classloader.clj:101)
	at metabase.plugins.classloader$require.doInvoke(classloader.clj:89)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at metabase.plugins.init_steps$fn__72013.invokeStatic(init_steps.clj:22)
	at metabase.plugins.init_steps$fn__72013.invoke(init_steps.clj:20)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase.plugins.init_steps$do_init_steps_BANG_.invokeStatic(init_steps.clj:32)
	at metabase.plugins.init_steps$do_init_steps_BANG_.invoke(init_steps.clj:27)
	at metabase.plugins.lazy_loaded_driver$make_initialize_BANG_$fn__72091.invoke(lazy_loaded_driver.clj:58)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase.driver.impl$initialize_if_needed_BANG_.invokeStatic(impl.clj:179)
	at metabase.driver.impl$initialize_if_needed_BANG_.invoke(impl.clj:160)
	at metabase.driver$the_initialized_driver.invokeStatic(driver.clj:147)
	at metabase.driver$the_initialized_driver.invoke(driver.clj:143)
	at metabase.driver$dispatch_on_initialized_driver.invokeStatic(driver.clj:155)
	at metabase.driver$dispatch_on_initialized_driver.doInvoke(driver.clj:150)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__22320.invoke(util.clj:32)
	at metabase.util$do_with_timeout$fn__9159.invoke(util.clj:315)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class clojure.lang.Var$Unbound cannot be cast to class clojure.lang.MultiFn (clojure.lang.Var$Unbound and clojure.lang.MultiFn are in unnamed module of loader 'app')
	at clojure.core$prefer_method.invokeStatic(core.clj:1803)
	at clojure.core$prefer_method.invoke(core.clj:1803)
	at metabase.driver.redshiftspectrum__init.load(Unknown Source)
	at metabase.driver.redshiftspectrum__init.<clinit>(Unknown Source)
	... 53 more
02-28 15:28:33 INFO driver.impl :: Initializing driver :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set...
02-28 15:28:33 DEBUG middleware.log :: POST /api/setup/validate 400 65.9 ms (0 DB calls)
{:errors {:dbname `nil}}`

**To Reproduce**
1. Clone the third-party driver here: https://github.com/gpodevijn/metabase-drivers
2. Build it (lein uberjar)
3. Pull the metabase-enterprise Docker image
4. Create a new Docker image based on metabase-enterprise:
`
FROM metabase/metabase-enterprise
ADD redshiftspectrum.metabase-driver.jar /plugins/redshiftspectrum.metabase-driver.jar
`
3. Build the new image and run it

**Information about your Metabase Installation:**
- Your browser and the version: Chrome
- Your databases: Redshift
- Metabase version: v1.34.2
- Metabase hosting environment: Docker

**Comment by lindsay-stevens** [comment]
Something to check is your metabase-core dependency of the driver (from `lein install-for-building-drivers`). Driver stuff got moved around a fair bit in v0.35 / master. So make sure metabase v0.34.2 is checked out, re-build metabase-core, then re-try `lein uberjar` for the driver.

**Comment by gpodevijn** [comment]
Thanks @lindsay-stevens, I was indeed compiling the driver against Metabase 0.35 while running Metabase enterprise 0.34.
