### ISSUE TITLE
Jetty error: KeyStores with multiple certificates are not supported on the base class

### ISSUE THREAD

**Issue by RMMSecurity** [metabase/metabase#12071]
**Describe the bug**
Building from master as of right now causes Metabase not to start with my configuration with Jetty throwing an error. The Jetty version was recently bumped as Possibly related to: https://github.com/metabase/metabase/commit/f8349b5122fdf542ae530f6da1eb9df1f03dc777  (?)  seems likely given that 3/3 and prior was working fine. 

**Logs**
N/A

**To Reproduce**
1. Build from master
2. Try to start Metabase
3. File bug report

**Expected behavior**
Expected it to start

**Information about your Metabase Installation:**
I used an older version to pull this info so disregard the build specific hash etc.
`{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_232-b09",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "1.8.0_232",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.232-b09",
    "os.name": "Windows Server 2016",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "America/New_York"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.29-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.35.0-snapshot",
      "date": "2020-02-21",
      "branch": "master",
      "hash": "ec0ce0b"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

- Your browser and the version: N/A
- Your operating system: Windows Server 2016
- Your databases: MySQL 
- Metabase version: Master (March 6, 2020)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
Severe

**Additional context**

`03-05 11:31:41 [1mDEBUG plugins.classloader[0m :: Using NEWLY CREATED classloader as shared context classloader: clojure.lang.DynamicClassLoader@39ce27f2
03-05 11:31:41 [1mINFO metabase.util[0m :: Loading Metabase...
03-05 11:31:41 [1mINFO metabase.util[0m :: Maximum memory available to JVM: 2.7 GB
03-05 11:31:53 [1mINFO util.encryption[0m :: Saved credentials encryption is DISABLED for this Metabase instance.
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
03-05 11:32:00 [1mWARN metabase.core[0m :: WARNING: You have enabled namespace tracing, which could log sensitive information like db passwords.
03-05 11:32:00 [1mINFO metabase.core[0m :: Starting Metabase in STANDALONE mode
03-05 11:32:00 [1mINFO metabase.server[0m :: Launching Embedded Jetty Webserver with config:
 {:port 8007, :host "0.0.0.0", :ssl? true, :ssl-port 8008, :keystore "[REDACTED].jks"}

03-05 11:32:00 [1mERROR metabase.core[0m :: Metabase Initialization FAILED
java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory. (Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)
        at org.eclipse.jetty.util.ssl.SslContextFactory.newSniX509ExtendedKeyManager(SslContextFactory.java:1275)
        at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:1256)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:374)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at metabase.server$start_web_server_BANG_.invokeStatic(server.clj:82)
        at metabase.server$start_web_server_BANG_.invoke(server.clj:68)
        at metabase.core$start_normally.invokeStatic(core.clj:121)
        at metabase.core$start_normally.invoke(core.clj:117)
        at metabase.core$_main.invokeStatic(core.clj:156)
        at metabase.core$_main.doInvoke(core.clj:150)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)`

**Comment by RMMSecurity** [comment]
@camsaul

**Comment by flamber** [comment]
@RMMSecurity Yes, it seems it because of the Jetty upgrade 9.4.15 to 9.4.27, where 9.4.24 changed `SslContextFactory` to `SslContextFactory.(Server|Client)` https://github.com/eclipse/jetty.project/issues/4385
I'm not sure of the impact, so setting P1.
