### ISSUE TITLE
Can not selecting Oracle date type field via JDBC driver on after metabase 0.34.x

### ISSUE THREAD

**Issue by coleyon** [metabase/metabase#12113]
**Describe the bug**

When I select a date type field value on  `New question` page.
The selecting target DB Table is Oracle 11g configured for japanese charsets.

* This bug is reproduced in docker container environment [metabase/metabase:v0.34.3](https://hub.docker.com/layers/metabase/metabase/v0.34.3/images/sha256-59d962a3f5e7eb6987b40df5ee2087ead2380443862997a7d63a905cef33db49?context=explore)
* This bug is not reproduced in before docker container environment [metabase/metabase:v0.33.7.3](https://hub.docker.com/layers/metabase/metabase/v0.33.7.3/images/sha256-8d6950dafcc070bd475f55066e0d04f7823a4d563b04189ca4c247cd3cc5d6d5?context=explore)

**Error-ed Query**

	SELECT
	  schema1.table1.id
	  , schema1.table1.error_date
	FROM
	  schema1.table1;

**To Reproduce**

1. Add the Oracle connection definition to the Admin -> Databases menu on Metabase.
2. Open the `New Question` on metabase
3. put the above `Error-ed Query` to `New Question` area.
4. Press `Run Query` button

**Expected behavior**

Date type field value on the oracle DB that configured for japanese charsets, is select-able.

**Screenshots**

![errored](https://user-images.githubusercontent.com/24493192/76494782-f48dac80-6478-11ea-93f1-bcc0ed51a45a.png)

**Information about Metabase Installation**

Metabase environemnt:

Docker Containered `metabase/metabase:v0.34.3` + Oracle Database 11g R2 JDBC Driver.

Additional Plugins for metabase container:

    # docker exec -it ${CONTAINER_ID} ls -l /app/plugins
    total 112796
    ...
    -rw-r--r--    1 metabase metabase   3698857 Mar  9 10:40 ojdbc7.jar
    -rw-r--r--    1 metabase metabase   1655734 Mar  9 10:40 orai18n.jar
    ...

Target oracle DB:

parameters got by `select * from nls_database_parameters;` .

| PARAMETER               | VALUE                        |
| ----------------------- | ---------------------------- |
| PARAMETER               | VALUE                        |
| NLS_LANGUAGE            | AMERICAN                     |
| NLS_TERRITORY           | AMERICA                      |
| NLS_CURRENCY            | $                            |
| NLS_ISO_CURRENCY        | AMERICA                      |
| NLS_NUMERIC_CHARACTERS  | .,                           |
| NLS_CHARACTERSET        | JA16SJISTILDE                |
| NLS_CALENDAR            | GREGORIAN                    |
| NLS_DATE_FORMAT         | DD-MON-RR                    |
| NLS_DATE_LANGUAGE       | AMERICAN                     |
| NLS_SORT                | BINARY                       |
| NLS_TIME_FORMAT         | HH.MI.SSXFF AM               |
| NLS_TIMESTAMP_FORMAT    | DD-MON-RR HH.MI.SSXFF AM     |
| NLS_TIME_TZ_FORMAT      | HH.MI.SSXFF AM TZR           |
| NLS_TIMESTAMP_TZ_FORMAT | DD-MON-RR HH.MI.SSXFF AM TZR |
| NLS_DUAL_CURRENCY       | $                            |
| NLS_COMP                | BINARY                       |
| NLS_LENGTH_SEMANTICS    | BYTE                         |
| NLS_NCHAR_CONV_EXCP     | FALSE                        |
| NLS_NCHAR_CHARACTERSET  | AL16UTF16                    |
| NLS_RDBMS_VERSION       | 11.2.0.4.0                   |

Target Table:

    create table "schema1"."table1" 
    ("id" varchar2(11) not null enable,
        "sometext" varchar2(11),
        "error_date" date, 
        primary key ("id")
    );

**Logs**

When running the Above `Errored Query`, I got below logs from the metabase container.

    $ docker container logs {CONTAINER_ID}
    ...
	03-12 09:11:44 ERROR sql-jdbc.execute :: Error reading :oracle column 2 error_date TIMESTAMP
	java.sql.SQLException: Invalid column type
	        at oracle.jdbc.driver.Redirector$2.redirect(Redirector.java:264)
	        at oracle.jdbc.driver.Representation.getObject(Representation.java:436)
	        at oracle.jdbc.driver.Accessor.getObject(Accessor.java:1014)
	        at oracle.jdbc.driver.OracleStatement.getObject(OracleStatement.java:6697)
	        at oracle.jdbc.driver.InsensitiveScrollableResultSet.getObject(InsensitiveScrollableResultSet.java:912)
	        at com.mchange.v2.c3p0.impl.NewProxyResultSet.getObject(NewProxyResultSet.java:217)
	        at metabase.driver.sql_jdbc.execute$get_object_of_class.invokeStatic(execute.clj:66)
	        at metabase.driver.sql_jdbc.execute$get_object_of_class.invoke(execute.clj:65)
	        at metabase.driver.sql_jdbc.execute$fn__69307.invokeStatic(execute.clj:70)
	        at metabase.driver.sql_jdbc.execute$fn__69307.invoke(execute.clj:68)
	        at clojure.lang.MultiFn.invoke(MultiFn.java:252)
	        at metabase.driver.sql_jdbc.execute$read_columns$fn__69317.invoke(execute.clj:104)
	        at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	        at clojure.lang.LongRange.reduce(LongRange.java:233)
	        at clojure.core$reduce.invokeStatic(core.clj:6827)
	        at clojure.core$mapv.invokeStatic(core.clj:6903)
	        at clojure.core$mapv.invoke(core.clj:6903)
	        at metabase.driver.sql_jdbc.execute$read_columns.invokeStatic(execute.clj:96)
	        at metabase.driver.sql_jdbc.execute$read_columns.invoke(execute.clj:88)
	        at clojure.core$partial$fn__5839.invoke(core.clj:2626)
	        at clojure.java.jdbc$result_set_seq$row_values__18574.invoke(jdbc.clj:566)
	        at clojure.java.jdbc$result_set_seq$thisfn__18580.invoke(jdbc.clj:579)
	        at clojure.java.jdbc$result_set_seq$thisfn__18580$fn__18581.invoke(jdbc.clj:579)
	        at clojure.lang.LazySeq.sval(LazySeq.java:42)
	        at clojure.lang.LazySeq.seq(LazySeq.java:51)
	        at clojure.lang.RT.seq(RT.java:535)
	        at clojure.core$seq__5402.invokeStatic(core.clj:137)
	        at clojure.core$map$fn__5866.invoke(core.clj:2746)
	        at clojure.lang.LazySeq.sval(LazySeq.java:42)
	        at clojure.lang.LazySeq.seq(LazySeq.java:51)
	        at clojure.lang.Cons.next(Cons.java:39)
	        at clojure.lang.PersistentVector.create(PersistentVector.java:79)
	        at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
	        at clojure.core$vec.invokeStatic(core.clj:377)
	        at clojure.core$vec.invoke(core.clj:367)
	        at clojure.java.jdbc$process_result_set$fn__18636.invoke(jdbc.clj:895)
	        at clojure.java.jdbc$process_result_set.invokeStatic(jdbc.clj:894)
	        at clojure.java.jdbc$process_result_set.invoke(jdbc.clj:886)
	        at clojure.java.jdbc$query$fn__18705.invoke(jdbc.clj:1166)
	        at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1073)
	        at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)
	        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1081)
	        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
	        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
	        at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	        at metabase.driver.sql_jdbc.execute$cancelable_run_query.invokeStatic(execute.clj:209)
	        at metabase.driver.sql_jdbc.execute$cancelable_run_query.invoke(execute.clj:198)
	        at metabase.driver.sql_jdbc.execute$run_query.invokeStatic(execute.clj:223)
	        at metabase.driver.sql_jdbc.execute$run_query.invoke(execute.clj:219)
	        at metabase.driver.sql_jdbc.execute$run_query_with_timezone$fn__69393.invoke(execute.clj:317)
	        at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	        at metabase.driver.sql_jdbc.execute$do_with_auto_commit_disabled.invokeStatic(execute.clj:272)
	        at metabase.driver.sql_jdbc.execute$do_with_auto_commit_disabled.invoke(execute.clj:260)
	        at metabase.driver.sql_jdbc.execute$do_in_transaction$fn__69387.invoke(execute.clj:277)
	        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
	        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
	        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
	        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	        at metabase.driver.sql_jdbc.execute$do_in_transaction.invokeStatic(execute.clj:276)
	        at metabase.driver.sql_jdbc.execute$do_in_transaction.invoke(execute.clj:275)
	        at metabase.driver.sql_jdbc.execute$run_query_with_timezone.invokeStatic(execute.clj:303)
	        at metabase.driver.sql_jdbc.execute$run_query_with_timezone.invoke(execute.clj:302)
	        at metabase.driver.sql_jdbc.execute$execute_query$fn__69410.invoke(execute.clj:338)
	        at metabase.driver.sql_jdbc.execute$do_with_try_catch.invokeStatic(execute.clj:252)
	        at metabase.driver.sql_jdbc.execute$do_with_try_catch.invoke(execute.clj:246)
	        at metabase.driver.sql_jdbc.execute$execute_query.invokeStatic(execute.clj:332)
	        at metabase.driver.sql_jdbc.execute$execute_query.invoke(execute.clj:325)
	        at metabase.driver.sql_jdbc$fn__71316.invokeStatic(sql_jdbc.clj:49)
	        at metabase.driver.sql_jdbc$fn__71316.invoke(sql_jdbc.clj:47)
	        at metabase.driver.oracle$eval529$fn__530.invoke(oracle.clj:239)
	        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	        at metabase.query_processor$fn__46335$execute_query__46340$fn__46341.invoke(query_processor.clj:69)
	        at metabase.query_processor$fn__46335$execute_query__46340.invoke(query_processor.clj:64)
	        at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__37455.invoke(mbql_to_native.clj:40)
	        at metabase.query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__40562.invoke(annotate.clj:541)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at metabase.query_processor.middleware.annotate$add_column_info$fn__40468.invoke(annotate.clj:485)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__41503.invoke(cumulative_aggregations.clj:57)
	        at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__43430.invoke(resolve_joins.clj:184)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at metabase.query_processor.middleware.limit$limit$fn__42138.invoke(limit.clj:19)
	        at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__46195.invoke(results_metadata.clj:87)
	        at metabase.query_processor.middleware.format_rows$format_rows$fn__42126.invoke(format_rows.clj:76)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__38215.invoke(add_dimension_projections.clj:232)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__38866.invoke(add_source_metadata.clj:107)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__43480.invoke(resolve_source_table.clj:46)
	        at metabase.query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__38703.invoke(add_row_count_and_status.clj:16)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at metabase.query_processor.middleware.driver_specific$process_query_in_context$fn__41578.invoke(driver_specific.clj:12)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at metabase.query_processor.middleware.resolve_driver$resolve_driver$fn__43094.invoke(resolve_driver.clj:22)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at metabase.query_processor.middleware.store$initialize_store$fn__46220$fn__46221.invoke(store.clj:11)
	        at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:46)
	        at metabase.query_processor.store$do_with_store.invoke(store.clj:40)
	        at metabase.query_processor.middleware.store$initialize_store$fn__46220.invoke(store.clj:10)
	        at clojure.core$comp$fn__5807.invoke(core.clj:2569)
	        at metabase.query_processor.middleware.async$async__GT_sync$fn__37366.invoke(async.clj:23)
	        at metabase.query_processor.middleware.async_wait$runnable$fn__40619.invoke(async_wait.clj:89)
	        at clojure.lang.AFn.run(AFn.java:22)
	        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by flamber** [comment]
Hi @coleyon 
Please upgrade the `ojdbcX.jar` driver to the latest version 19c.
https://discourse.metabase.com/t/cant-read-date-fields-from-oracle/8836

**Comment by coleyon** [comment]
> Hi @coleyon
> Please upgrade the `ojdbcX.jar` driver to the latest version 19c.
> https://discourse.metabase.com/t/cant-read-date-fields-from-oracle/8836

Hi @flamber 

Thank you for your reply.

I replaced the Oracle JDBC driver to 19c according to your advice and the problem was resolved.
Also, when I checked the container log, the error was not output.
I didn't read this article for the version of the JDBC driver used for testing.
