### ISSUE TITLE
Continuous errors in logs`An IOException occurred while writing into a ByteArrayOutputStream`

### ISSUE THREAD

**Issue by Limess** [metabase/metabase#12255]
**Describe the bug**
After upgrading to  v0.35.1 we're seeing these errors almost continuously in our logs. We're not seeing any obvious impact from this.

**Logs**
```
04-03 08:36:15 ERROR ser.SerializableUtils :: An IOException occurred while writing into a ByteArrayOutputStream?!?
java.io.IOException: Problem indirectly serializing nestedDataSource: java.lang.ClassCastException: class metabase.connection_pool$proxy_data_source$reify__19826 cannot be cast to class javax.naming.Referenceable (metabase.connection_pool$proxy_data_source$reify__19826 is in unnamed module of loader 'app'; javax.naming.Referenceable is in module java.naming of loader 'bootstrap')
	at com.mchange.v2.c3p0.impl.WrapperConnectionPoolDataSourceBase.writeObject(WrapperConnectionPoolDataSourceBase.java:477)
	at jdk.internal.reflect.GeneratedMethodAccessor482.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
	at com.mchange.v2.ser.SerializableUtils.serializeToByteArray(SerializableUtils.java:99)
	at com.mchange.v2.ser.SerializableUtils.toByteArray(SerializableUtils.java:51)
	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.writeObject(PoolBackedDataSourceBase.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor481.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
	at java.base/java.util.HashSet.writeObject(Unknown Source)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor312.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
	at java.base/java.util.ArrayList.writeObject(Unknown Source)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor261.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastRef.marshalValue(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Severity**
Concerning but doesn't seem to cause impact

**Comment by flamber** [comment]
Hi @Limess Please post "Diagnostic Info" from Admin > Troubleshooting.

**Comment by Limess** [comment]
Hey @flamber, I didn't capture the diagnostic info and can't roll forwards to capture it due to https://github.com/metabase/metabase/issues/12258.

**Comment by flamber** [comment]
Okay, I have not seen this error on any instances. It seems like you're querying Postgres and Redshift.

**Comment by Limess** [comment]
Troubleshooting info from `0.35.1`:

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.173-137.228.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-02",
      "tag": "v0.35.1",
      "branch": "release-0.35.x",
      "hash": "e67f169"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

Yes we are running with Aurora Postgres as the metabase datastore and querying against Redshift/Aurora postgres.

**Comment by flamber** [comment]
The encryption key might be similar to #11048 - still don't know what's causing that.
Are you using encryption key - or have you ever used it?

When does the IOException log appear? While doing nothing, or is it while doing queries, or when Metabase is syncing, or ...?

**Comment by Limess** [comment]
Seemingly while doing nothing, I'm still seeing it on the weekend with no usage going on.

I now think the encryption key thing is entirely separate, we get two instances of that, one for metabot and one on startup for the locale. They don't seem to be causing actual issues so ignore them.

**Comment by Limess** [comment]
After re-saving all the DBT connections this seems to have gone away, I have no idea what was causing it or if there's some specific task/job which triggers it. Feel free to close as can't reproduce.
