### ISSUE TITLE
Can not use some questions on Pulses and on Metabot, "temporal" error

### ISSUE THREAD

**Issue by rodrigotassinari** [metabase/metabase#12278]
**Describe the bug**
For some questions, when I try to use the question on a Pulse, the "loading" animation keeps showing forever. I can save the pulse but it never fires. See server logs below.

Also if I try to access the same questions via Metabot (on Slack), I get only a "Uh oh! :cry:
temporal" response back. See server logs below too.

**Logs**
Server logs for when I try to select the question in the Pulse creation form:

```
04-06 13:06:37 ERROR middleware.log :: GET /api/pulse/preview_card_info/690 500 6.9 s (7 DB calls)
{:message "temporal",
 :type java.lang.NullPointerException,
 :stacktrace
 ["java.base/java.util.Objects.requireNonNull(Unknown Source)"
  "java.base/java.time.format.DateTimeFormatter.formatTo(Unknown Source)"
  "java.base/java.time.format.DateTimeFormatter.format(Unknown Source)"
  "java_time.format$format.invokeStatic(format.clj:50)"
  "java_time.format$format.invoke(format.clj:43)"
  "--> pulse.render.datetime$reformat_temporal_str.invokeStatic(datetime.clj:14)"
  "pulse.render.datetime$reformat_temporal_str.invoke(datetime.clj:13)"
  "pulse.render.datetime$format_temporal_str.invokeStatic(datetime.clj:33)"
  "pulse.render.datetime$format_temporal_str.invoke(datetime.clj:16)"
  "pulse.render.body$fn__32493$format_cell__32498$fn__32499.invoke(body.clj:48)"
  "pulse.render.body$fn__32493$format_cell__32498.invoke(body.clj:45)"
  "pulse.render.body$fn__32573$query_results__GT_row_seq__32578$fn__32579$iter__32580__32584$fn__32585$iter__32618__32622$fn__32623.invoke(body.clj:110)"
  "pulse.render.table$render_table_body$iter__32407__32411$fn__32412$iter__32445__32449$fn__32450.invoke(table.clj:75)"
  "api.pulse$fn__63984.invokeStatic(pulse.clj:166)"
  "api.pulse$fn__63984.invoke(pulse.clj:159)"
  "middleware.auth$enforce_authentication$fn__66723.invoke(auth.clj:14)"
  "routes$fn__68247$fn__68248.doInvoke(routes.clj:56)"
  "middleware.exceptions$catch_uncaught_exceptions$fn__66822.invoke(exceptions.clj:97)"
  "middleware.exceptions$catch_api_exceptions$fn__66819.invoke(exceptions.clj:85)"
  "middleware.log$log_api_call$fn__68625$fn__68626.invoke(log.clj:197)"
  "middleware.log$log_api_call$fn__68625.invoke(log.clj:191)"
  "middleware.security$add_security_headers$fn__66785.invoke(security.clj:121)"
  "middleware.json$wrap_json_body$fn__68328.invoke(json.clj:64)"
  "middleware.json$wrap_streamed_json_response$fn__68346.invoke(json.clj:100)"
  "middleware.misc$maybe_set_site_url$fn__68655.invoke(misc.clj:59)"
  "middleware.session$bind_current_user$fn__63312$fn__63313.invoke(session.clj:209)"
  "middleware.session$do_with_current_user.invokeStatic(session.clj:184)"
  "middleware.session$do_with_current_user.invoke(session.clj:177)"
  "middleware.session$bind_current_user$fn__63312.invoke(session.clj:208)"
  "middleware.session$wrap_current_user_id$fn__63297.invoke(session.clj:161)"
  "middleware.session$wrap_session_id$fn__63241.invoke(session.clj:125)"
  "middleware.auth$wrap_api_key$fn__66731.invoke(auth.clj:27)"
  "middleware.misc$bind_user_locale$fn__68660.invoke(misc.clj:78)"
  "middleware.misc$add_content_type$fn__68641.invoke(misc.clj:29)"
  "middleware.misc$disable_streaming_buffering$fn__68669.invoke(misc.clj:94)"
  "server$async_proxy_handler$fn__68403.invoke(server.clj:70)"
  "server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)"]}
```

Server logs for when I try to show the question in Slack via Metabot:

```
04-06 13:08:41 ERROR metabot.slack :: Error in Metabot command
java.lang.NullPointerException: temporal
  at java.base/java.util.Objects.requireNonNull(Unknown Source)
  at java.base/java.time.format.DateTimeFormatter.formatTo(Unknown Source)
  at java.base/java.time.format.DateTimeFormatter.format(Unknown Source)
  at java_time.format$format.invokeStatic(format.clj:50)
  at java_time.format$format.invoke(format.clj:43)
  at metabase.pulse.render.datetime$reformat_temporal_str.invokeStatic(datetime.clj:14)
  at metabase.pulse.render.datetime$reformat_temporal_str.invoke(datetime.clj:13)
  at metabase.pulse.render.datetime$format_temporal_str.invokeStatic(datetime.clj:33)
  at metabase.pulse.render.datetime$format_temporal_str.invoke(datetime.clj:16)
  at metabase.pulse.render.body$fn__32493$format_cell__32498$fn__32499.invoke(body.clj:48)
  at metabase.pulse.render.body$fn__32493$format_cell__32498.invoke(body.clj:45)
  at metabase.pulse.render.body$fn__32573$query_results__GT_row_seq__32578$fn__32579$iter__32580__32584$fn__32585$iter__32618__32622$fn__32623.invoke(body.clj:110)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.RT.seq(RT.java:535)
  at clojure.core$seq__5402.invokeStatic(core.clj:137)
  at clojure.core$map_indexed$mapi__8548$fn__8549.invoke(core.clj:7301)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.RT.seq(RT.java:535)
  at clojure.core$seq__5402.invokeStatic(core.clj:137)
  at clojure.core$seq__5402.invoke(core.clj:137)
  at metabase.pulse.render.table$render_table_body$iter__32407__32411$fn__32412$iter__32445__32449$fn__32450.invoke(table.clj:75)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.RT.seq(RT.java:535)
  at clojure.core$seq__5402.invokeStatic(core.clj:137)
  at clojure.core$map$fn__5866.invoke(core.clj:2746)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.Cons.next(Cons.java:39)
  at clojure.lang.RT.next(RT.java:713)
  at clojure.core$next__5386.invokeStatic(core.clj:64)
  at clojure.core$str$fn__5466.invoke(core.clj:557)
  at clojure.core$str.invokeStatic(core.clj:555)
  at clojure.core$str.doInvoke(core.clj:544)
  at clojure.lang.RestFn.applyTo(RestFn.java:139)
  at clojure.core$apply.invokeStatic(core.clj:665)
  at clojure.core$apply.invoke(core.clj:660)
  at hiccup.compiler$fn__31404.invokeStatic(compiler.clj:88)
  at hiccup.compiler$fn__31404.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at clojure.core$map$fn__5866.invoke(core.clj:2753)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.RT.seq(RT.java:535)
  at clojure.core$seq__5402.invokeStatic(core.clj:137)
  at clojure.core$apply.invokeStatic(core.clj:660)
  at clojure.core$apply.invoke(core.clj:660)
  at hiccup.compiler$fn__31404.invokeStatic(compiler.clj:88)
  at hiccup.compiler$fn__31404.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
  at hiccup.compiler$render_element.invoke(compiler.clj:72)
  at hiccup.compiler$fn__31402.invokeStatic(compiler.clj:85)
  at hiccup.compiler$fn__31402.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at clojure.core$map$fn__5866.invoke(core.clj:2755)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.Cons.next(Cons.java:39)
  at clojure.lang.RT.next(RT.java:713)
  at clojure.core$next__5386.invokeStatic(core.clj:64)
  at clojure.core$str$fn__5466.invoke(core.clj:557)
  at clojure.core$str.invokeStatic(core.clj:555)
  at clojure.core$str.doInvoke(core.clj:544)
  at clojure.lang.RestFn.applyTo(RestFn.java:139)
  at clojure.core$apply.invokeStatic(core.clj:665)
  at clojure.core$apply.invoke(core.clj:660)
  at hiccup.compiler$fn__31404.invokeStatic(compiler.clj:88)
  at hiccup.compiler$fn__31404.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at clojure.core$map$fn__5866.invoke(core.clj:2753)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.RT.seq(RT.java:535)
  at clojure.core$seq__5402.invokeStatic(core.clj:137)
  at clojure.core$apply.invokeStatic(core.clj:660)
  at clojure.core$apply.invoke(core.clj:660)
  at hiccup.compiler$fn__31404.invokeStatic(compiler.clj:88)
  at hiccup.compiler$fn__31404.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
  at hiccup.compiler$render_element.invoke(compiler.clj:72)
  at hiccup.compiler$fn__31402.invokeStatic(compiler.clj:85)
  at hiccup.compiler$fn__31402.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at clojure.core$map$fn__5866.invoke(core.clj:2753)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.RT.seq(RT.java:535)
  at clojure.core$seq__5402.invokeStatic(core.clj:137)
  at clojure.core$apply.invokeStatic(core.clj:660)
  at clojure.core$apply.invoke(core.clj:660)
  at hiccup.compiler$fn__31404.invokeStatic(compiler.clj:88)
  at hiccup.compiler$fn__31404.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
  at hiccup.compiler$render_element.invoke(compiler.clj:72)
  at hiccup.compiler$fn__31402.invokeStatic(compiler.clj:85)
  at hiccup.compiler$fn__31402.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at clojure.core$map$fn__5866.invoke(core.clj:2753)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.RT.seq(RT.java:535)
  at clojure.core$seq__5402.invokeStatic(core.clj:137)
  at clojure.core$apply.invokeStatic(core.clj:660)
  at clojure.core$apply.invoke(core.clj:660)
  at hiccup.compiler$fn__31404.invokeStatic(compiler.clj:88)
  at hiccup.compiler$fn__31404.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
  at hiccup.compiler$render_element.invoke(compiler.clj:72)
  at hiccup.compiler$fn__31402.invokeStatic(compiler.clj:85)
  at hiccup.compiler$fn__31402.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at clojure.core$map$fn__5866.invoke(core.clj:2755)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.RT.seq(RT.java:535)
  at clojure.core$seq__5402.invokeStatic(core.clj:137)
  at clojure.core$apply.invokeStatic(core.clj:660)
  at clojure.core$apply.invoke(core.clj:660)
  at hiccup.compiler$fn__31404.invokeStatic(compiler.clj:88)
  at hiccup.compiler$fn__31404.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at clojure.core$map$fn__5866.invoke(core.clj:2753)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.RT.seq(RT.java:535)
  at clojure.core$seq__5402.invokeStatic(core.clj:137)
  at clojure.core$apply.invokeStatic(core.clj:660)
  at clojure.core$apply.invoke(core.clj:660)
  at hiccup.compiler$fn__31404.invokeStatic(compiler.clj:88)
  at hiccup.compiler$fn__31404.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
  at hiccup.compiler$render_element.invoke(compiler.clj:72)
  at hiccup.compiler$fn__31402.invokeStatic(compiler.clj:85)
  at hiccup.compiler$fn__31402.invoke(compiler.clj:82)
  at hiccup.compiler$fn__31387$G__31382__31392.invoke(compiler.clj:68)
  at clojure.lang.Var.invoke(Var.java:384)
  at metabase.pulse.render.png$fn__33005$render_html_to_png__33010$fn__33014.invoke(png.clj:89)
  at metabase.pulse.render.png$fn__33005$render_html_to_png__33010.invoke(png.clj:85)
  at metabase.pulse.render$fn__33204$render_pulse_card_to_png__33209$fn__33210.invoke(render.clj:159)
  at metabase.pulse.render$fn__33204$render_pulse_card_to_png__33209.invoke(render.clj:156)
  at metabase.pulse$create_slack_attachment_data$iter__63363__63367$fn__63368$fn__63369$fn__63372.invoke(pulse.clj:73)
  at metabase.pulse$create_and_upload_slack_attachments_BANG_$iter__63386__63390$fn__63391$fn__63392.invoke(pulse.clj:84)
  at metabase.pulse$create_and_upload_slack_attachments_BANG_$iter__63386__63390$fn__63391.invoke(pulse.clj:83)
  at clojure.lang.LazySeq.sval(LazySeq.java:42)
  at clojure.lang.LazySeq.seq(LazySeq.java:51)
  at clojure.lang.RT.seq(RT.java:535)
  at clojure.core$seq__5402.invokeStatic(core.clj:137)
  at clojure.core$dorun.invokeStatic(core.clj:3133)
  at clojure.core$doall.invokeStatic(core.clj:3148)
  at clojure.core$doall.invoke(core.clj:3148)
  at metabase.pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:82)
  at metabase.pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:79)
  at metabase.metabot.command$fn__63606$fn__63610.invoke(command.clj:168)
  at metabase.metabot.slack$do_async$fn__63546$fn__63547.invoke(slack.clj:42)
  at metabase.metabot.slack$do_async$fn__63546.invoke(slack.clj:41)
  at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
  at clojure.lang.AFn.call(AFn.java:18)
  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
Described above.

**Expected behavior**
On the new Pulse form the selected question should be displayed after loading (and the Pulse should be fired on time). On Metabot I should see the question and not an error message saying "temporal".

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.14.77-70.82.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "America/Sao_Paulo"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "redshift"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "10.6"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-02",
      "tag": "v0.35.1",
      "branch": "release-0.35.x",
      "hash": "e67f169"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
Blocking some functionality. I can not use Pulses for some of my questions until this is fixed.

**Comment by flamber** [comment]
Hi @rodrigotassinari 
Without seeing the query, I'm fairly sure this is a duplicate of #11665. See that issue for workaround.
If it is a duplicate, then please close this issue and upvote the other by clicking :+1: on the first post.

**Comment by rodrigotassinari** [comment]
Yes, this is a duplicate of #11665. I'm closing this issue an commenting on the original one. Thanks @flamber
