### ISSUE TITLE
"An error occurred" when attempting to save or update native (MongoDB) questions

### ISSUE THREAD

**Issue by mhjb** [metabase/metabase#12329]
**Describe the bug**
I've recently updated to v0.35.2. I can no longer save or update native questions, and get this error when I try: 
![image](https://user-images.githubusercontent.com/1380991/79382675-030b3e80-7fb8-11ea-9efe-21fa9e4e859d.png)

I can still edit 'simple' and 'custom' questions;  though I get this error when trying to start a new simple or custom question:
![image](https://user-images.githubusercontent.com/1380991/79382912-68f7c600-7fb8-11ea-90e5-a54198f08fe3.png)

**Logs**
Browser console:
![image](https://user-images.githubusercontent.com/1380991/79382650-f5ee4f80-7fb7-11ea-9545-51819d375725.png)
Server log:
```
04-15 20:01:47 ERROR analyze.query-results :: Error generating insights for column: {:name users}
clojure.lang.ExceptionInfo: Output of stored-column-metadata->result-column-metadata does not match schema:

	   {:base_type missing-required-key}

 {:type :schema.core/error, :schema {:name java.lang.String, :display_name java.lang.String, #schema.core.OptionalKey{:k :description} (maybe (constrained Str "Non-blank string")), :base_type (pred "Valid field type (keyword or string)"), #schema.core.OptionalKey{:k :special_type} (maybe (pred "Valid field type (keyword or string)")), #schema.core.OptionalKey{:k :unit} (maybe (constrained (named (cond-pre Keyword Str) "Keyword or string") "Valid field datetime unit keyword or string")), #schema.core.OptionalKey{:k :fingerprint} (maybe {(optional-key :global) {(optional-key :distinct-count) Int, (optional-key :nil%) (maybe (constrained Num "Valid percentage between (inclusive) 0 and 1."))}, (optional-key :type) (constrained {(optional-key :type/Number) {(optional-key :min) (maybe Num), (optional-key :max) (maybe Num), (optional-key :avg) (maybe Num), (optional-key :q1) (maybe Num), (optional-key :q3) (maybe Num), (optional-key :sd) (maybe Num)}, (optional-key :type/Text) {(optional-key :percent-json) (maybe (constrained Num "Valid percentage between (inclusive) 0 and 1.")), (optional-key :percent-url) (maybe (constrained Num "Valid percentage between (inclusive) 0 and 1.")), (optional-key :percent-email) (maybe (constrained Num "Valid percentage between (inclusive) 0 and 1.")), (optional-key :average-length) Num}, (optional-key :type/DateTime) {(optional-key :earliest) (maybe Str), (optional-key :latest) (maybe Str)}} "Type-specific fingerprint with exactly one key"), (optional-key :experimental) {Keyword Any}})}, :value {:display_name "users", :name "users"}, :error {:base_type missing-required-key}}
	at metabase.sync.analyze.query_results$fn__46862$stored_column_metadata__GT_result_column_metadata__46867.invoke(query_results.clj:56)
	at metabase.sync.analyze.query_results$insights_rf$iter__46882__46886$fn__46887$fn__46888$fn__46889.invoke(query_results.clj:75)
	at metabase.sync.analyze.query_results$insights_rf$iter__46882__46886$fn__46887$fn__46888.invoke(query_results.clj:72)
	at metabase.sync.analyze.query_results$insights_rf$iter__46882__46886$fn__46887.invoke(query_results.clj:71)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$seq__5402.invoke(core.clj:137)
	at metabase.sync.analyze.query_results$insights_rf$iter__46903__46907$fn__46908.invoke(query_results.clj:81)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:660)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.analyze.query_results$insights_rf.invokeStatic(query_results.clj:81)
	at metabase.sync.analyze.query_results$insights_rf.invoke(query_results.clj:66)
	at metabase.query_processor.middleware.results_metadata$insights_xform.invokeStatic(results_metadata.clj:109)
	at metabase.query_processor.middleware.results_metadata$insights_xform.invoke(results_metadata.clj:106)
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__46954$rff_SINGLEQUOTE___46957.invoke(results_metadata.clj:127)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39170$fn__39171.invoke(add_rows_truncated.clj:38)
	at metabase.query_processor.middleware.cache$run_query_with_cache$fn__41985.invoke(cache.clj:183)
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__46969$fn__46970.invoke(splice_params_in_response.clj:34)
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__39332$fn__39333.invoke(add_timezone_info.clj:17)
	at metabase.query_processor.middleware.format_rows$format_rows$fn__42989$fn__42992.invoke(format_rows.clj:84)
	at metabase.query_processor.middleware.limit$limit$fn__43008$fn__43009.invoke(limit.clj:41)
	at metabase.query_processor.middleware.annotate$add_column_info$fn__40965$fn__40967.invoke(annotate.clj:584)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__43022$fn__43025.invoke(mbql_to_native.clj:31)
	at metabase.query_processor.context.default$default_reducef.invokeStatic(default.clj:56)
	at metabase.query_processor.context.default$default_reducef.invoke(default.clj:49)
	at metabase.query_processor.context$reducef.invokeStatic(context.clj:69)
	at metabase.query_processor.context$reducef.invoke(context.clj:62)
	at metabase.query_processor.context.default$default_runf$respond_STAR___37889.invoke(default.clj:70)
	at metabase.driver.mongo.execute$reduce_results.invokeStatic(execute.clj:151)
	at metabase.driver.mongo.execute$reduce_results.invoke(execute.clj:144)
	at metabase.driver.mongo.execute$execute_reducible_query.invokeStatic(execute.clj:180)
	at metabase.driver.mongo.execute$execute_reducible_query.invoke(execute.clj:170)
	at metabase.driver.mongo$eval2505$fn__2506$f__1744__auto____2508.invoke(mongo.clj:215)
	at metabase.driver.mongo.util$_with_mongo_connection$fn__1735.invoke(util.clj:205)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invokeStatic(ssh.clj:106)
	at metabase.util.ssh$with_ssh_tunnel_STAR_.invoke(ssh.clj:91)
	at metabase.driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:199)
	at metabase.driver.mongo.util$_with_mongo_connection.invoke(util.clj:194)
	at metabase.driver.mongo$eval2505$fn__2506.invoke(mongo.clj:214)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:69)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:67)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__43022.invoke(mbql_to_native.clj:26)
	at metabase.query_processor.middleware.check_features$check_features$fn__42336.invoke(check_features.clj:42)
	at metabase.query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__43187.invoke(optimize_datetime_filters.clj:133)
	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47085.invoke(wrap_value_literals.clj:137)
	at metabase.query_processor.middleware.annotate$add_column_info$fn__40965.invoke(annotate.clj:577)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__42211.invoke(permissions.clj:64)
	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__43686.invoke(pre_alias_aggregations.clj:40)
	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__42409.invoke(cumulative_aggregations.clj:61)
	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__44218.invoke(resolve_joins.clj:183)
	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39152.invoke(add_implicit_joins.clj:245)
	at metabase.query_processor.middleware.limit$limit$fn__43008.invoke(limit.clj:38)
	at metabase.query_processor.middleware.format_rows$format_rows$fn__42989.invoke(format_rows.clj:81)
	at metabase.query_processor.middleware.desugar$desugar$fn__42475.invoke(desugar.clj:22)
	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__41509.invoke(binning.clj:229)
	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__42017.invoke(resolve_fields.clj:24)
	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__38688.invoke(add_dimension_projections.clj:270)
	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__38908.invoke(add_implicit_clauses.clj:147)
	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39301.invoke(add_source_metadata.clj:105)
	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__43883.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)
	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__41150.invoke(auto_bucket_datetimes.clj:125)
	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__42064.invoke(resolve_source_table.clj:46)
	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__43668.invoke(parameters.clj:97)
	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__42116.invoke(resolve_referenced.clj:80)
	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__42731.invoke(expand_macros.clj:158)
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__39332.invoke(add_timezone_info.clj:15)
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__46969.invoke(splice_params_in_response.clj:32)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__43894$fn__43898.invoke(resolve_database_and_driver.clj:33)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:61)
	at metabase.driver$do_with_driver.invoke(driver.clj:57)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__43894.invoke(resolve_database_and_driver.clj:27)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__42937.invoke(fetch_source_query.clj:243)
	at metabase.query_processor.middleware.store$initialize_store$fn__46978$fn__46979.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:46)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:40)
	at metabase.query_processor.middleware.store$initialize_store$fn__46978.invoke(store.clj:10)
	at metabase.query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:181)
	at metabase.query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:172)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__41993.invoke(cache.clj:207)
	at metabase.query_processor.middleware.validate$validate_query$fn__46987.invoke(validate.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__43035.invoke(normalize_query.clj:22)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39170.invoke(add_rows_truncated.clj:36)
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__46954.invoke(results_metadata.clj:128)
	at metabase.query_processor.middleware.constraints$add_default_userland_constraints$fn__42352.invoke(constraints.clj:42)
	at metabase.query_processor.middleware.process_userland_query$process_userland_query$fn__43757.invoke(process_userland_query.clj:136)
	at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__42295.invoke(catch_exceptions.clj:166)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37971$thunk__37972.invoke(reducible.clj:100)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37971$fn__37974.invoke(reducible.clj:105)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
04-15 20:01:47 INFO middleware.cache :: Query took 3.8 s to run; miminum for cache eligibility is 60.0 s
04-15 20:01:47 DEBUG middleware.log :: POST /api/card/230/query 202 [ASYNC: completed] 3.9 s (6 DB calls) App DB connections: 0/10 Jetty threads: 2/50 (5 idle, 0 queued) (108 total active threads) Queries in flight: 0 (0 queued)
04-15 20:01:48 DEBUG middleware.log :: PUT /api/card/230 400 5.8 ms (0 DB calls)
{:errors {:result_metadata "value may be nil, or if non-nil, value must be an array of valid results column metadata maps."}}
```

**To Reproduce**
1. Visit a native question
2. Edit the question — any tiny change will do
3. Attempt to save

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.15.0-96-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-10",
      "tag": "v0.35.2",
      "branch": "release-0.35.x",
      "hash": "f3b2857"
    },
    "settings": {
      "report-timezone": "Pacific/Auckland"
    }
  }
}

**Severity**
Entirely blocking usage of Metabase as I'm trying to fix our key charts

**Additional context**
I love Metabase :)

**Comment by flamber** [comment]
Hi @mhjb 

I'm fairly sure you're seeing #12265 for the MongoDB problem, which is fixed and will be in 0.35.3.

As for the loading spinner instead of the database selector, that looks like #12323, but I don't think you've added any of the logs related to that.

By the way, if you're using Metabase in production, then you should [migrate away from H2](https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html) - that will not solve any of the problems you're seeing here.

**Comment by mhjb** [comment]
Thanks for the very speedy reply!

Here are the loading spinner logs:
![image](https://user-images.githubusercontent.com/1380991/79390062-21c30280-7fc3-11ea-8bcf-0863f98a6416.png)

```
04-15 21:18:49 ERROR middleware.log :: GET /api/database 500 7.2 ms (7 DB calls)
{:message
 "Syntax error in SQL statement \"SELECT \"\"REPORT_CARD\"\".\"\"NAME\"\", \"\"REPORT_CARD\"\".\"\"DESCRIPTION\"\", \"\"REPORT_CARD\"\".\"\"DATABASE_ID\"\", \"\"REPORT_CARD\"\".\"\"DATASET_QUERY\"\", \"\"REPORT_CARD\"\".\"\"ID\"\", \"\"REPORT_CARD\"\".\"\"COLLECTION_ID\"\", \"\"REPORT_CARD\"\".\"\"RESULT_METADATA\"\" FROM \"\"REPORT_CARD\"\" WHERE (\"\"RESULT_METADATA\"\" IS NOT NULL AND \"\"ARCHIVED\"\" = FALSE AND (\"\"DATABASE_ID\"\" IN NULL[*]) AND TRUE) ORDER BY LOWER(\"\"NAME\"\") ASC \"; expected \"(\"; SQL statement:\nSELECT \"REPORT_CARD\".\"NAME\", \"REPORT_CARD\".\"DESCRIPTION\", \"REPORT_CARD\".\"DATABASE_ID\", \"REPORT_CARD\".\"DATASET_QUERY\", \"REPORT_CARD\".\"ID\", \"REPORT_CARD\".\"COLLECTION_ID\", \"REPORT_CARD\".\"RESULT_METADATA\" FROM \"REPORT_CARD\" WHERE (\"RESULT_METADATA\" IS NOT NULL AND \"ARCHIVED\" = FALSE AND (\"DATABASE_ID\" in NULL) AND TRUE) ORDER BY lower(\"NAME\") ASC [42001-197]",
 :type org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
  "org.h2.message.DbException.getSyntaxError(DbException.java:217)"
  "org.h2.command.Parser.getSyntaxError(Parser.java:555)"
  "org.h2.command.Parser.read(Parser.java:3518)"
  "org.h2.command.Parser.readCondition(Parser.java:2433)"
  "org.h2.command.Parser.readAnd(Parser.java:2342)"
  "org.h2.command.Parser.readExpression(Parser.java:2334)"
  "org.h2.command.Parser.readTerm(Parser.java:3252)"
  "org.h2.command.Parser.readFactor(Parser.java:2587)"
  "org.h2.command.Parser.readSum(Parser.java:2574)"
  "org.h2.command.Parser.readConcat(Parser.java:2544)"
  "org.h2.command.Parser.readCondition(Parser.java:2370)"
  "org.h2.command.Parser.readAnd(Parser.java:2344)"
  "org.h2.command.Parser.readExpression(Parser.java:2334)"
  "org.h2.command.Parser.readTerm(Parser.java:3252)"
  "org.h2.command.Parser.readFactor(Parser.java:2587)"
  "org.h2.command.Parser.readSum(Parser.java:2574)"
  "org.h2.command.Parser.readConcat(Parser.java:2544)"
  "org.h2.command.Parser.readCondition(Parser.java:2370)"
  "org.h2.command.Parser.readAnd(Parser.java:2342)"
  "org.h2.command.Parser.readExpression(Parser.java:2334)"
  "org.h2.command.Parser.parseSelectSimple(Parser.java:2291)"
  "org.h2.command.Parser.parseSelectSub(Parser.java:2133)"
  "org.h2.command.Parser.parseSelectUnion(Parser.java:1946)"
  "org.h2.command.Parser.parseSelect(Parser.java:1919)"
  "org.h2.command.Parser.parsePrepared(Parser.java:463)"
  "org.h2.command.Parser.parse(Parser.java:335)"
  "org.h2.command.Parser.parse(Parser.java:311)"
  "org.h2.command.Parser.prepareCommand(Parser.java:278)"
  "org.h2.engine.Session.prepareLocal(Session.java:611)"
  "org.h2.engine.Session.prepareCommand(Session.java:549)"
  "org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)"
  "org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)"
  "org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:304)"
  "com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:387)"
  "clojure.java.jdbc$prepare_statement.invokeStatic(jdbc.clj:672)"
  "clojure.java.jdbc$prepare_statement.invoke(jdbc.clj:619)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1094)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
  "clojure.java.jdbc$reducible_query$reify__18756.reduce(jdbc.clj:1339)"
  "clojure.core$transduce.invokeStatic(core.clj:6883)"
  "clojure.core.Eduction.reduce(core.clj:7682)"
  "clojure.core$transduce.invokeStatic(core.clj:6883)"
  "clojure.core$transduce.invoke(core.clj:6870)"
  "--> api.database$source_query_cards.invokeStatic(database.clj:126)"
  "api.database$source_query_cards.doInvoke(database.clj:123)"
  "api.database$source_query_cards_exist_QMARK_.invokeStatic(database.clj:143)"
  "api.database$source_query_cards_exist_QMARK_.invoke(database.clj:140)"
  "api.database$add_saved_questions_virtual_database.invokeStatic(database.clj:166)"
  "api.database$add_saved_questions_virtual_database.doInvoke(database.clj:162)"
  "api.database$dbs_list.invokeStatic(database.clj:172)"
  "api.database$dbs_list.doInvoke(database.clj:168)"
  "api.database$fn__54399.invokeStatic(database.clj:207)"
  "api.database$fn__54399.invoke(database.clj:174)"
  "middleware.auth$enforce_authentication$fn__66831.invoke(auth.clj:14)"
  "routes$fn__68355$fn__68356.doInvoke(routes.clj:56)"
  "middleware.exceptions$catch_uncaught_exceptions$fn__66930.invoke(exceptions.clj:97)"
  "middleware.exceptions$catch_api_exceptions$fn__66927.invoke(exceptions.clj:85)"
  "middleware.log$log_api_call$fn__68733$fn__68734.invoke(log.clj:197)"
  "middleware.log$log_api_call$fn__68733.invoke(log.clj:191)"
  "middleware.security$add_security_headers$fn__66893.invoke(security.clj:121)"
  "middleware.json$wrap_json_body$fn__68436.invoke(json.clj:64)"
  "middleware.json$wrap_streamed_json_response$fn__68454.invoke(json.clj:100)"
  "middleware.misc$maybe_set_site_url$fn__68763.invoke(misc.clj:59)"
  "middleware.session$bind_current_user$fn__63420$fn__63421.invoke(session.clj:209)"
  "middleware.session$do_with_current_user.invokeStatic(session.clj:184)"
  "middleware.session$do_with_current_user.invoke(session.clj:177)"
  "middleware.session$bind_current_user$fn__63420.invoke(session.clj:208)"
  "middleware.session$wrap_current_user_id$fn__63405.invoke(session.clj:161)"
  "middleware.session$wrap_session_id$fn__63349.invoke(session.clj:125)"
  "middleware.auth$wrap_api_key$fn__66839.invoke(auth.clj:27)"
  "middleware.misc$bind_user_locale$fn__68768.invoke(misc.clj:78)"
  "middleware.misc$add_content_type$fn__68749.invoke(misc.clj:29)"
  "middleware.misc$disable_streaming_buffering$fn__68777.invoke(misc.clj:94)"
  "server$async_proxy_handler$fn__68511.invoke(server.clj:70)"
  "server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)"],
 :sql-exception-chain
 ["JdbcSQLException:"
  "Message: Syntax error in SQL statement \"SELECT \"\"REPORT_CARD\"\".\"\"NAME\"\", \"\"REPORT_CARD\"\".\"\"DESCRIPTION\"\", \"\"REPORT_CARD\"\".\"\"DATABASE_ID\"\", \"\"REPORT_CARD\"\".\"\"DATASET_QUERY\"\", \"\"REPORT_CARD\"\".\"\"ID\"\", \"\"REPORT_CARD\"\".\"\"COLLECTION_ID\"\", \"\"REPORT_CARD\"\".\"\"RESULT_METADATA\"\" FROM \"\"REPORT_CARD\"\" WHERE (\"\"RESULT_METADATA\"\" IS NOT NULL AND \"\"ARCHIVED\"\" = FALSE AND (\"\"DATABASE_ID\"\" IN NULL[*]) AND TRUE) ORDER BY LOWER(\"\"NAME\"\") ASC \"; expected \"(\"; SQL statement:"
  "SELECT \"REPORT_CARD\".\"NAME\", \"REPORT_CARD\".\"DESCRIPTION\", \"REPORT_CARD\".\"DATABASE_ID\", \"REPORT_CARD\".\"DATASET_QUERY\", \"REPORT_CARD\".\"ID\", \"REPORT_CARD\".\"COLLECTION_ID\", \"REPORT_CARD\".\"RESULT_METADATA\" FROM \"REPORT_CARD\" WHERE (\"RESULT_METADATA\" IS NOT NULL AND \"ARCHIVED\" = FALSE AND (\"DATABASE_ID\" in NULL) AND TRUE) ORDER BY lower(\"NAME\") ASC [42001-197]"
  "SQLState: 42001"
  "Error Code: 42001"]}
```

I shall migrate

**Comment by flamber** [comment]
Closing this in favor of the two existing issues: #12265 and #12323
