### ISSUE TITLE
"Error determining whether HTTP request was canceled" with long-running postgres queries

### ISSUE THREAD

**Issue by zvickery** [metabase/metabase#12335]
**Describe the bug**
With metabase 0.35.x it seems I can no longer run queries longer than 60s against a postgres database.  This worked fine in metabase 0.34.x.   These queries also run fine when run outside of metabase using the same DB connectivity.

**Logs**
The below exception appears 60s after query is launched.  Multiple of these exceptions often appear.
```
04-16 16:52:25 [1mERROR async.streaming-response[0m :: Error determining whether HTTP request was canceled
java.lang.ClassCastException: class org.eclipse.jetty.io.SocketChannelEndPoint cannot be cast to class java.nio.channels.SocketChannel (org.eclipse.jetty.io.SocketChannelEndPoint is in unnamed module of loader 'app'; java.nio.channels.SocketChannel is in module java.base of loader 'bootstrap')
	at metabase.async.streaming_response$canceled_QMARK_.invokeStatic(streaming_response.clj:140)
	at metabase.async.streaming_response$canceled_QMARK_.invoke(streaming_response.clj:131)
	at metabase.async.streaming_response$start_async_cancel_loop_BANG_$fn__23198$state_machine__15507__auto____23205$fn__23207$inst_23147__23222.invoke(streaming_response.clj:166)
	at metabase.async.util$cancelable_thread_call$fn__22853$fn__22854.invoke(util.clj:51)
	at metabase.async.util$cancelable_thread_call$fn__22853.invoke(util.clj:50)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$bound_fn_STAR_$fn__5749.doInvoke(core.clj:2003)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
1. Run any saved question which takes over a minute to run.  Build a new one if needed.
2. Run the query and observe the `DOING SCIENCE...` spinner
3. After 60s, the error message `Your question took too long  - We didn't get an answer back from your database in time, so we had to stop.  You can try again in a minute, or if the problem persists, you can email an admin to let them know.` appears.  Re-running the question results in the same outcome.
4. Observe the exception in the logs.
5. The query can be observed to continue running in postgres until completion.

**Expected behavior**
The question succeeds and displays the response in metabase.

**Information about your Metabase Installation:**
This is the docker container for metabase, v0.35.2.

```{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.19.34-coreos",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-04-10",
      "tag": "v0.35.2",
      "branch": "release-0.35.x",
      "hash": "f3b2857"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Very high, I will likely downgrade to 0.34.x unless we can find a fix or workaround.

**Comment by flamber** [comment]
Hi @zvickery 
I haven't seen that error before, but it's correct that there's a lot of changes to connection in 0.35.
Can you check your browser console's Network-tab to see where the connection-killing response is coming from?
Are you using a proxy (or load balancer) in front of Metabase? You need to adjust the timeout there.

**Comment by dgindin-cp** [comment]
60 second timeout is coming from the HTTP POST call to /api/dataset.

Response:
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

**Comment by zvickery** [comment]
I observed it timing out on `/api/card/<question-ID>/query`.

We do have a load balancer in front of metabase.  I have adjusted the timeout and now it works.  I'm not sure how this has worked in the past, unless this frontend timeout setting is a new requirement with metabase 0.35.x.

Thank you for the suggestion!

**Comment by flamber** [comment]
@zvickery 

Before 0.35, the connections were being kept alive with a `newline` sent every second (or very short time frame), but that could lead to all connections getting exhausted on Jetty (the internal web server) and other really strange issues, which would block Metabase entirely.

Now the connection is using a more standard approach, so if the client closes their browser, then the database query connection is also closed. This has solved a lot of issues on Metabase instances with many users and high load.

The downside is that configuration changes are needed on the proxies, but that's a one-off change and more consistent with any other services you might have.

**Comment by ChethanUK** [comment]
> Before 0.35, the connections were being kept alive with a `newline` sent every second

Okay, so this bug of queries get cancelled after 60 seconds, when will that be fixed/

**Comment by flamber** [comment]
@ChethanUK Which bug? That your proxy/load-balancer is closing the connection? That would be the same problem for any other system you're using, which has long-running-requests. You need to adjust your proxy/load-balancer.

**Comment by RohitR1** [comment]
@flamber I also had this issuse with Metabase v0.35.3

My deployment is in K8s and using ngnix ingress..

I tried with some ngnix timeout, was not able to fix..
```bash
    nginx.ingress.kubernetes.io/client-header-timeout: 300s
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 300s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 300s
    nginx.ingress.kubernetes.io/proxy-send-timeout: 300s
```

Can you guide towards fixing the problem..

**Comment by flamber** [comment]
@RohitR1 You need to use your browser developer Network-tab to look at the response headers on the request - perhaps you have another proxy that is closing the connection.

**Comment by RohitR1** [comment]
In Admin logs, I found following

```bash
:database 2,
:middleware {:add-default-userland-constraints? true},
:info
{:executed-by 1,
:context :ad-hoc,
:nested? false,
:query-hash [.....]},
:constraints {:max-results 10000, :max-results-bare-rows 2000}},
:ex-data
{:message "Query was canceled",
:errorCode 3,
:errorName "USER_CANCELED",
:errorType "USER_ERROR",
:failureInfo
{:type "io.prestosql.spi.PrestoException",
:message "Query was canceled",
:suppressed [],
:stack
["io.prestosql.execution.QueryStateMachine.transitionToCanceled(QueryStateMachine.java:873)"
"io.prestosql.dispatcher.LocalDispatchQuery.cancel(LocalDispatchQuery.java:268)"
"java.util.Optional.ifPresent(Optional.java:159)"
"io.prestosql.dispatcher.DispatchManager.cancelQuery(DispatchManager.java:296)"
"io.prestosql.server.QueryResource.cancelQuery(QueryResource.java:116)"
"sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
"sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
"sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
"java.lang.reflect.Method.invoke(Method.java:498)"
"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)"
"org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)"
"org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)"
"org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:183)"
"org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)"
"org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)"
"org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)"
"org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)"
"org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)"
"org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)"
"org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)"
"org.glassfish.jersey.internal.Errors.process(Errors.java:316)"
"org.glassfish.jersey.internal.Errors.process(Errors.java:298)"
"org.glassfish.jersey.internal.Errors.process(Errors.java:268)"
"org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)"
"org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)"
"org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)"
"org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)"
"org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)"
"org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)"
"org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)"
"org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)"
"org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)"
"org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)"
"io.prestosql.server.security.AuthenticationFilter.handleInsecureRequest(AuthenticationFilter.java:179)"
"io.prestosql.server.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:110)"
"org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)"
"io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)"
"org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)"
"io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)"
"org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)"
"org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)"
"org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)"
"org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:717)"
"org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)"
"org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)"
"org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)"
"org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)"
"org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)"
"org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)"
"org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)"
"org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)"
"org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)"
"org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)"
"org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)"
"org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)"
"org.eclipse.jetty.server.Server.handle(Server.java:500)"
"org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)"
"org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)"
"org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)"
"org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)"
"org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)"
"org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)"
"org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)"
"org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)"
"org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)"
"org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)"
"org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)"
"org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)"
"org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)"
"org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)"
"java.lang.Thread.run(Thread.java:748)"]}},
:data {:rows [], :cols []}}
```

**Comment by RohitR1** [comment]
Also, attaching the screenshot from network tab.. 

<img width="837" alt="Screenshot 2020-05-07 at 8 05 31 PM" src="https://user-images.githubusercontent.com/60442898/81307290-2482b600-909e-11ea-8241-0c4fa2a3a65c.png">

Console: 
<img width="818" alt="Screenshot 2020-05-07 at 8 05 12 PM" src="https://user-images.githubusercontent.com/60442898/81307309-29476a00-909e-11ea-90e6-160629974e8e.png">

**Comment by flamber** [comment]
@RohitR1 You need to click the failing `dataset` request and look at the response headers and data.

**Comment by RohitR1** [comment]
Thank you :) 

Fixed after adding: 
```bash
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
```
