### ISSUE TITLE
permission denied to create "pg_catalog.databasechangelog"

### ISSUE THREAD

**Issue by hieplq** [metabase/metabase#12336]
**Describe the bug**
I run metabase docker on centos with postgresql 12 as metabase application database
i use user metabase with right "SUPERUSER CREATEDB"
i get this error on docker log

> Caused by: org.postgresql.util.PSQLException: ERROR: permission denied to create "pg_catalog.databasechangelog"

**Logs**
04-16 17:17:37 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
04-16 17:17:37 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver"]
04-16 17:17:37 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
04-16 17:17:37 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 🚚
04-16 17:17:37 INFO plugins.dependencies :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
04-16 17:17:37 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
04-16 17:17:37 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
04-16 17:17:37 INFO driver.impl :: Registered driver :googleanalytics (parents: [:google]) 🚚
04-16 17:17:37 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
04-16 17:17:37 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
04-16 17:17:37 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
04-16 17:17:37 INFO metabase.db :: Verifying postgres Database Connection ...
04-16 17:17:37 INFO driver.impl :: Initializing driver :sql...
04-16 17:17:37 INFO driver.impl :: Initializing driver :sql-jdbc...
04-16 17:17:37 INFO driver.impl :: Initializing driver :postgres...
04-16 17:17:37 INFO metabase.db :: Successfully verified PostgreSQL 12.2 application database connection. ✅
04-16 17:17:37 INFO metabase.db :: Running Database Migrations...
04-16 17:17:37 INFO metabase.db :: Setting up Liquibase...
04-16 17:17:37 INFO metabase.db :: Liquibase is ready.
04-16 17:17:37 INFO db.liquibase :: Checking if Database has unrun migrations...
04-16 17:17:40 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.DatabaseException: ERROR: permission denied to create "pg_catalog.databasechangelog"
  Detail: System catalog modifications are currently disallowed. [Failed SQL: CREATE TABLE pg_catalog.databasechangelog (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP WITHOUT TIME ZONE NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:109)
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:280)
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1219)
	at liquibase.Liquibase.listLocks(Liquibase.java:1240)
	at metabase.db.liquibase$migration_lock_exists_QMARK_.invokeStatic(liquibase.clj:98)
	at metabase.db.liquibase$migration_lock_exists_QMARK_.invoke(liquibase.clj:95)
	at metabase.db.liquibase$release_lock_if_needed_BANG_.invokeStatic(liquibase.clj:188)
	at metabase.db.liquibase$release_lock_if_needed_BANG_.invoke(liquibase.clj:184)
	at metabase.db$migrate_BANG_$fn__21263$fn__21264.invoke(db.clj:231)
	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:38)
	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:29)
	at metabase.db$migrate_BANG_$fn__21263.invoke(db.clj:203)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at metabase.db$migrate_BANG_.invokeStatic(db.clj:194)
	at metabase.db$migrate_BANG_.invoke(db.clj:173)
	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:329)
	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:323)
	at metabase.db$setup_db_BANG__STAR_$fn__21342.invoke(db.clj:346)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:649)
	at metabase.util$do_with_us_locale.invoke(util.clj:635)
	at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:344)
	at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:339)
	at metabase.db$setup_db_from_env_BANG__STAR_.invokeStatic(db.clj:354)
	at metabase.db$setup_db_from_env_BANG__STAR_.invoke(db.clj:351)
	at metabase.db$setup_db_BANG_$fn__21353.invoke(db.clj:368)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:366)
	at metabase.db$setup_db_BANG_.invoke(db.clj:361)
	at metabase.core$init_BANG_.invokeStatic(core.clj:77)
	at metabase.core$init_BANG_.invoke(core.clj:56)
	at metabase.core$start_normally.invokeStatic(core.clj:123)
	at metabase.core$start_normally.invoke(core.clj:117)
	at metabase.core$_main.invokeStatic(core.clj:156)
	at metabase.core$_main.doInvoke(core.clj:150)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: permission denied to create "pg_catalog.databasechangelog"
  Detail: System catalog modifications are currently disallowed.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:269)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
	... 44 more
04-16 17:17:40 INFO metabase.core :: Metabase Shutting Down ...

**To Reproduce**
1. has centos 7
2. install docker engine
3. install postgresql 12
4. create role (user) metabase
`sudo su - postgres -c psql <<EOF
CREATE ROLE metabase LOGIN PASSWORD 'metabase' SUPERUSER CREATEDB VALID UNTIL 'infinity';
EOF`
5. create database metabase
`createdb -h localhost -p 5432 -U metabase --template="template0" -E UNICODE --lc-collate en_US.UTF-8 --lc-ctype en_US.UTF-8 -O metabase "metabase"`
6. run docker 
`docker run -d --network="host" \
  -e "MB_DB_TYPE=postgres" \
  -e "MB_DB_DBNAME=metabase" \
  -e "MB_DB_PORT=5432" \
  -e "MB_DB_USER=metabase" \
  -e "MB_DB_PASS=metabase" \
  -e "MB_DB_HOST=localhost" \
  --name metabase metabase/metabase`

**Comment by flamber** [comment]
Hi @hieplq 
It seems like you're somehow using `pg_catalog` as default schema instead of `public` (I guess).
I cannot reproduce on with Postgres 12.2 and Metabase 0.35.2

**Comment by hieplq** [comment]
you are corrected

on centos i need to run

`psql -q -h localhost -p 5432 -U metabase -d "metabase" -c "ALTER ROLE metabase SET search_path TO public, pg_catalog"`

it's don't need for ubuntu/mint
