### ISSUE TITLE
I cannot use Shardingsphere as datasource

### ISSUE THREAD

**Issue by cowcomic** [metabase/metabase#12351]
**Describe the bug**
I use shardingsphere-proxy as database
but metabase can not recognize the correct table

example：
a table named "test", shardingsphere proxy "test" and save 4 shards "test0" "test1" "test2" "test3"
use some sql ide as navicat. I only can see "test"
but in metabse, shows 4 table "test 0" "test 1" "test 2" "test 3" without "test"
open one of this , shows error and massage is "Distinct, non-empty sequence of Field clauses"

also, error log in console
```
java.sql.SQLException: (conn=7) 2Unknown exception: [Cannot find table rule and default data source with logic table: 'KEY_COLUMN_USAGE']
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:262)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:349)
        at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:595)
        at org.mariadb.jdbc.MariaDbDatabaseMetaData.executeQuery(MariaDbDatabaseMetaData.java:508)
        at org.mariadb.jdbc.MariaDbDatabaseMetaData.getImportedKeysUsingInformationSchema(MariaDbDatabaseMetaData.java:1001)
        at org.mariadb.jdbc.MariaDbDatabaseMetaData.getImportedKeys(MariaDbDatabaseMetaData.java:399)
        at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getImportedKeys(NewProxyDatabaseMetaData.java:3296)
        at metabase.driver.sql_jdbc.sync$describe_table_fks.invokeStatic(sync.clj:208)
        at metabase.driver.sql_jdbc.sync$describe_table_fks.doInvoke(sync.clj:204)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at metabase.driver.sql_jdbc$fn__72727.invokeStatic(sql_jdbc.clj:66)
        at metabase.driver.sql_jdbc$fn__72727.invoke(sql_jdbc.clj:64)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at metabase.sync.fetch_metadata$fn__52419$fk_metadata__52424$fn__52425.invoke(fetch_metadata.clj:25)
        at metabase.sync.fetch_metadata$fn__52419$fk_metadata__52424.invoke(fetch_metadata.clj:20)
        at metabase.sync.sync_metadata.fks$fn__53355$sync_fks_for_table_BANG___53364$fn__53367$fn__53368.invoke(fks.clj:68)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
        at metabase.sync.sync_metadata.fks$fn__53355$sync_fks_for_table_BANG___53364$fn__53367.invoke(fks.clj:67)
        at metabase.sync.sync_metadata.fks$fn__53355$sync_fks_for_table_BANG___53364.invoke(fks.clj:62)
        at metabase.sync.sync_metadata.fks$fn__53395$sync_fks_BANG___53400$fn__53401$fn__53402.invoke(fks.clj:81)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6827)
        at clojure.core$reduce.invoke(core.clj:6810)
        at metabase.sync.sync_metadata.fks$fn__53395$sync_fks_BANG___53400$fn__53401.invoke(fks.clj:80)
        at metabase.sync.sync_metadata.fks$fn__53395$sync_fks_BANG___53400.invoke(fks.clj:76)
        at metabase.sync.util$fn__44441$run_step_with_metadata__44446$fn__44450$fn__44452.invoke(util.clj:345)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
        at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119)
        at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116)
        at metabase.sync.util$fn__44441$run_step_with_metadata__44446$fn__44450.invoke(util.clj:342)
        at metabase.sync.util$fn__44441$run_step_with_metadata__44446.invoke(util.clj:337)
        at metabase.sync.util$fn__44633$run_sync_operation__44638$fn__44639$fn__44640.invoke(util.clj:430)
        at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6827)
        at clojure.core$mapv.invokeStatic(core.clj:6903)
        at clojure.core$mapv.invoke(core.clj:6903)
        at metabase.sync.util$fn__44633$run_sync_operation__44638$fn__44639.invoke(util.clj:430)
        at metabase.sync.util$fn__44633$run_sync_operation__44638.invoke(util.clj:424)
        at metabase.sync.sync_metadata$fn__53940$sync_db_metadata_BANG___53945$fn__53946$fn__53947.invoke(sync_metadata.clj:51)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
        at clojure.core$partial$fn__5839.invoke(core.clj:2623)
        at metabase.driver$fn__22323.invokeStatic(driver.clj:536)
        at metabase.driver$fn__22323.invoke(driver.clj:536)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at metabase.sync.util$sync_in_context$fn__44353.invoke(util.clj:138)
        at metabase.sync.util$with_db_logging_disabled$fn__44350.invoke(util.clj:129)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
        at metabase.sync.util$with_start_and_finish_logging$fn__44339.invoke(util.clj:114)
        at metabase.sync.util$with_sync_events$fn__44334.invoke(util.clj:88)
        at metabase.sync.util$with_duplicate_ops_prevented$fn__44325.invoke(util.clj:67)
        at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164)
        at metabase.sync.util$do_sync_operation.invoke(util.clj:161)
        at metabase.sync.sync_metadata$fn__53940$sync_db_metadata_BANG___53945$fn__53946.invoke(sync_metadata.clj:50)
        at metabase.sync.sync_metadata$fn__53940$sync_db_metadata_BANG___53945.invoke(sync_metadata.clj:47)
        at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:39)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.sql.SQLException: 2Unknown exception: [Cannot find table rule and default data source with logic table: 'KEY_COLUMN_USAGE']
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1599)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1461)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1424)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:178)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:343)
        ... 62 more
```

**Screenshots**

![image](https://user-images.githubusercontent.com/4745969/79718939-e486a980-830f-11ea-83a3-8ea82f596d79.png)

![image](https://user-images.githubusercontent.com/4745969/79718896-c7ea7180-830f-11ea-83b3-30f66a4dee37.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 80.0.3987.149
- Your operating system: Windows 10
- Your databases: MySQL proxy by shardingsphere
- Metabase version: v0.35.2

- Metabase internal database: H2 (default)

**Severity**
it can not used

**Comment by flamber** [comment]
Hi @cowcomic 
We technically don't support ShardingSphere except insomuch as whatever you're experiencing is also a MySQL bug.

There are a lot of databases that promise MySQL or PostgreSQL compatibility that don't actually deliver it, and while we're going to do our best to have them not break, we definitely haven't verified running Metabase on ShardingSphere yet.

It looks like the sync+scan process is failing or not completed, since that's usually the reason for the error `Distinct, non-empty sequence of Field clauses`.

**Comment by cowcomic** [comment]
it seems like #3572
metabase scan table by information_schema
