### ISSUE TITLE
Connecting Metabase Application Database to RDS Postgres DB

### ISSUE THREAD

**Issue by doakes23** [metabase/metabase#12459]
Hello, I currently have Metabase running on a Kubernetes cluser with an in-memory database (H2), I'm currently working on a task to have metabase point to a Postgres instance that runs in AWS RDS. I've set and validated the necessary environment variables for the database in my pod (MB_DB_USER, MB_DB_DBNAME,MB_DB_PORT,MB_DB_USER,MB_DB_PASS and MB_DB_HOST) but while running

`java -jar /app/metabase.jar load-from-h2 metabase.db`
 
I get the following exception:

`05-05 05:15:23 INFO driver.impl :: Initializing driver :sql...
05-05 05:15:23 INFO driver.impl :: Initializing driver :sql-jdbc...
05-05 05:15:23 INFO driver.impl :: Initializing driver :postgres...
05-05 05:15:24 INFO metabase.db :: Successfully verified PostgreSQL 10.11 application database connection. ✅
05-05 05:15:24 INFO metabase.db :: Running Database Migrations...
05-05 05:15:24 INFO metabase.db :: Setting up Liquibase...
05-05 05:15:24 INFO metabase.db :: Liquibase is ready.
05-05 05:15:24 INFO db.liquibase :: Checking if Database has unrun migrations...
05-05 05:15:26 INFO metabase.db :: Database Migrations Current ...  ✅
Database setup took 3.7 s
Testing if target DB is already populated...
java.lang.AssertionError: Assert failed: Target DB is already populated!
(not (mb-db-populated? target-db-conn))
	at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__68060.invoke(load_from_h2.clj:249)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:245)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:234)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:37)
	at metabase.cmd$load_from_h2.invoke(cmd.clj:30)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.cmd$run_cmd$fn__67316.invoke(cmd.clj:127)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:127)
	at metabase.cmd$run_cmd.invoke(cmd.clj:123)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:133)
	at metabase.core$run_cmd.invoke(core.clj:131)
	at metabase.core$_main.invokeStatic(core.clj:155)
	at metabase.core$_main.doInvoke(core.clj:150)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)
Command failed with exception: Assert failed: Target DB is already populated!
(not (mb-db-populated? target-db-conn))
bash-5.0# ls
`
The database I have it configured to point to is a brand new database with only a few default schemas such as (information_schema, pg_catalog and public)... I know in the docs it mentions that the database should be completely empty, so should I delete these default schemas as well? or could this be something else?

**Comment by flamber** [comment]
Hi @doakes23 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It says `Target DB is already populated!`, which should only happen, when there's a table called `Setting` in your default schema (which most likely is `public`).
Otherwise try specifying `MB_DB_FILE` instead of appending it (and use the full path), like
```
set MB_DB_FILE=/metabase.db/metabase.db
java -jar /app/metabase.jar load-from-h2
```
