### ISSUE TITLE
PostgreSQL tests fail on pgsql 10

### ISSUE THREAD

**Issue by robdaemon** [metabase/metabase#12465]
**Describe the bug**

Driver tests fail on pgsql 10+ due to changes in ordering and other behavior.

**Logs**

```
lein test :only metabase.driver.postgres-test/recreated-views-test

FAIL in (recreated-views-test) (postgres_test.clj:207)

:postgres make sure that if a view is dropped and recreated that the original Table object is marked active rather than a new one being created (#3331)
expected: [{:name "angry_birds", :active true}]
  actual: ()
    diff: - [{:name "angry_birds", :active true}]

...

ERROR models.field-values :: Error fetching field values
org.postgresql.util.PSQLException: ERROR: could not identify an ordering operator for type json
  Hint: Use an explicit ordering operator or modify the query.
  Position: 130
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431)
	at metabase.driver.sql_jdbc.execute$eval67254$fn__67255.invoke(execute.clj:267)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
```

```
lein test :only metabase.driver.postgres-test/foreign-tables-test

FAIL in (foreign-tables-test) (postgres_test.clj:176)

:postgres Check that we properly fetch foreign tables.
expected: {:tables #{{:name "local_table", :schema "public", :description nil} {:name "foreign_table", :schema "public", :description nil}}}
  actual: {:tables #{{:name "local_table", :schema "public", :description nil}}}
    diff: - {:tables #{{:name "foreign_table", :schema "public", :description nil}}}
```

```
lein test :only metabase.driver.postgres-test/materialized-views-test

FAIL in (materialized-views-test) (postgres_test.clj:158)

:postgres Check that we properly fetch materialized views. As discussed in #2355 they don't come back from JDBC `DatabaseMetadata` so we have to fetch them manually.
expected: {:tables #{{:name "test_mview", :schema "public", :description nil}}}
  actual: {:tables #{}}
    diff: - {:tables #{{:name "test_mview", :schema "public", :description nil}}}
          + {:tables nil}
```

**To Reproduce**
1. Install pgsql 10+
2. Run the postgresql driver tests against pgsql 10

**Expected behavior**
Tests should pass.

**Comment by flamber** [comment]
Hi @robdaemon 
Which commit and branch are you using?
There should be tests against Postgres 9.6 and latest (currently 12.2):
https://github.com/metabase/metabase/blob/master/.circleci/config.yml

**Comment by robdaemon** [comment]
Ugh turns out these failures were the branch I'm on, doesn't fail on master. Sorry for the confusion. Closing this.
