### ISSUE TITLE
Driver: Ali AnalyticDB for MySQL

### ISSUE THREAD

**Issue by xiaoliwang** [metabase/metabase#12537]
**Is your feature request related to a problem? Please describe.**
When I connect metabase to ali adb for mysql, I get the error log like 
> ERROR metabase.sync.util Error syncing Fields for Table 'Table 38 'catalog''

**Describe the solution you'd like**
I find ali adb for mysql doesn't support type *SIGNED INTEGER*. Both `SELECT CAST(20 AS SIGNED)` and `SELECT CAST(20 AS INTEGER)` are OK. But mysql doesn't support `SELECT CAST(20 AS INTEGER)`. So I hope to change cast to `CAST (num AS SIGNED)` that both mysql and ali adb for mysql can support well.

**How important is this feature to you?**
We use ali adb for mysql for our bi job, so it is very import to our job.

**Comment by xiaoliwang** [comment]
> Metabase technically don't support Ali AnalyticDB except if what you're experiencing is also a MySQL/MariaDB bug. A lot of databases promises compatibility, but that don't actually deliver it.
> 
> If there's a problem with or missing feature of the MariaDB Connector/J, then open an issue there, since Metabase is probably not going to create a custom version.
> 
> Related to #12669 and #11266

We still can't use Ali AnalyticDB Because the DB doesn't support type "unsigned integer". And when metabase exec function getColumns, we will get the error.

**Comment by xiaoliwang** [comment]
> [mariadb-corporation/mariadb-connector-j@`2065a1a`/src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java#L776](https://github.com/mariadb-corporation/mariadb-connector-j/blob/2065a1a95638a142a5d696ad9f9da5d308204201/src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java#L776)
> 
> Metabase use mariadb client access mysql db, the function **getColumns** is hard code **signed integer**.
> But I consulted ADB development and got the conclusion that signed is not supported.
> 
> The solution to this problem should probably modify getColumns.

They fixed the signed problem and get the unsigned exception instead.

**Comment by flamber** [comment]
@xiaoliwang Well, it will probably require a custom driver, since it's not compatible with MySQL/MariaDB.

**Comment by xiaoliwang** [comment]
> @xiaoliwang Well, it will probably require a custom driver, since it's not compatible with MySQL/MariaDB.

I think so. I think the only thing we should do is to rewrite getColumns function.

**Comment by zhoujunhe** [comment]
> > @xiaoliwang好吧，它可能需要一个自定义驱动程序，因为它与MySQL / MariaDB不兼容。
> 
> 我认为如此。我认为我们唯一应该做的就是重写getColumns函数。

此问题有没有重写getColumns函数，如果已经重写了，能否放开出来，让大家一起使用你的重写后的驱动。

**Comment by xiaoliwang** [comment]
> > > @xiaoliwang好吧，它可能需要一个自定义驱动程序，因为它与MySQL / MariaDB不兼容。
> > 
> > 
> > 我认为如此。我认为我们唯一应该做的就是重写getColumns函数。
> 
> 此问题有没有重写getColumns函数，如果已经重写了，能否放开出来，让大家一起使用你的重写后的驱动。

我们正在 push 阿里的同学去支持 `unsigned` 的语法。目前预计十月初的版本，可以进行支持。否则就需要等双十一之后了。

**Comment by zhoujunhe** [comment]
> > > > @xiaoliwang好吧，它可能需要一个自定义驱动程序，因为它与MySQL / MariaDB不兼容。
> > > 
> > > 
> > > 我认为如此。我认为我们唯一应该做的就是重写getColumns函数。
> > 
> > 
> > 此问题有没有重写getColumns函数，如果已经重写了，能否放开出来，让大家一起使用你的重写后的驱动。
> 
> 我们正在 push 阿里的同学去支持 `unsigned` 的语法。目前预计十月初的版本，可以进行支持。否则就需要等双十一之后了。

非常感谢，我会持续跟踪的

**Comment by zhoujunhe** [comment]
我做了一个测试，使用oracle 官方的 mysql-connector-j 调用 getColumns 不会报错，但使用[mariadb-connector-j 就会报错。

**Comment by zhoujunhe** [comment]
https://github.com/zhoujunhe/metabase/tree/AnalyticDB             针对AnalyticDB  for mysql 开发的一个分支

**Comment by xiaoliwang** [comment]
> 

大佬是把 mariadb-connector-j 换成了 mysql-connector-j 吗？

**Comment by xiaoliwang** [comment]
> [zhoujunhe/metabase@`AnalyticDB_v0.44.6`](https://github.com/zhoujunhe/metabase/tree/AnalyticDB_v0.44.6?rgh-link-date=2022-11-02T02%3A55%3A23Z) 针对AnalyticDB for mysql 开发的一个分支 编译jar下载：[zhoujunhe/metabase@`v0.44.6` metabase.jar (download)](https://github.com/zhoujunhe/metabase/releases/download/v0.44.6/metabase.jar)

您是把 mariadb-connector-j  换成了 mysql-connector-j 吗？

**Comment by zhoujunhe** [comment]
> > [周君河/metabase@`AnalyticDB_v0.44.6`](https://github.com/zhoujunhe/metabase/tree/AnalyticDB_v0.44.6?rgh-link-date=2022-11-02T02%3A55%3A23Z) 针对 AnalyticDB for mysql 开发的一个分支 编译jar下载：[周君河/metabase@`v0.44.6` 元数据库.jar （下载）](https://github.com/zhoujunhe/metabase/releases/download/v0.44.6/metabase.jar)
> 
> 您是把 mariadb-connector-j 换成了 mysql-connector-j 吗？

针对anlyticdb ，我改了mariadb-connector-j代码，https://github.com/zhoujunhe/mariadb-connector-j/blob/AnalyticDB_2.7.6/src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java     818行把 UNSIGNED INTEGER改成SIGNED INTEGER， 然后 mariadb-connector-j 重新编译，metabase 重新编译就OK了，你等阿里，metabase,mariadb三方在哪儿提皮球，使终解决不了问题，还不如自己维护一个分支好了。

**Comment by xiaoliwang** [comment]
> > > [周君河/metabase@`AnalyticDB_v0.44.6`](https://github.com/zhoujunhe/metabase/tree/AnalyticDB_v0.44.6?rgh-link-date=2023-02-05T03%3A03%3A12Z) 针对 AnalyticDB for mysql 开发的一个分支 编译jar下载：[周君河/metabase@`v0.44.6` 元数据库.jar （下载）](https://github.com/zhoujunhe/metabase/releases/download/v0.44.6/metabase.jar)
> > 
> > 
> > 您是把 mariadb-connector-j 换成了 mysql-connector-j 吗？
> 
> 针对anlyticdb ，我改了mariadb-connector-j代码，[zhoujunhe/mariadb-connector-j@`AnalyticDB_2.7.6`/src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java](https://github.com/zhoujunhe/mariadb-connector-j/blob/AnalyticDB_2.7.6/src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java?rgh-link-date=2023-02-05T03%3A03%3A12Z) 818行把 UNSIGNED INTEGER改成SIGNED INTEGER， 然后 mariadb-connector-j 重新编译，metabase 重新编译就OK了，你等阿里，metabase,mariadb三方在哪儿提皮球，使终解决不了问题，还不如自己维护一个分支好了。

确实，还是大佬给力。

**Comment by zhoujunhe** [comment]
买阿里云香港区，操作系统选择Alibaba Cloud Linux 3.2 104版本

1.安装环境
```
yum install maven-openjdk11.noarch git npm
npm install -g yarn
curl -O https://download.clojure.org/install/linux-install-1.11.1.1200.sh
chmod +x linux-install-1.11.1.1200.sh
sudo ./linux-install-1.11.1.1200.sh
```
2.下截源码和指定版本
```
git clone https://github.com/metabase/metabase.git
cd metabase
git checkout -b  AnalyticDB_v0.45.1 v0.45.1
```

3.编译
第一次编译
`INTERACTIVE=false CI=true MB_EDITION=oss bin/build`

正常编译后，我们不用metabase.jar文件，先替换mariadb的jdbc驱动包,些版本驱动支持AnalyticDB for mysql

```
cd /root/.m2/repository/org/mariadb/jdbc/mariadb-java-client/2.7.6
rm mariadb-java-client-2.7.6.jar
wget https://github.com/zhoujunhe/mariadb-connector-j/releases/download/tag_AnalyticDB_2.7.6/mariadb-java-client-2.7.6.jar
sha1sum   mariadb-java-client-2.7.6.jar | awk '{print $1}' > mariadb-java-client-2.7.6.jar.sha1
```

第二次编译
```
cd ~/metabase
INTERACTIVE=false CI=true MB_EDITION=oss bin/build
```

qq:31722980 聊下以后快速联系吧

**Comment by sisuad** [comment]
till 01/12/2024, just asked aliyun officail support, still not support metabase thanks [zhoujunhe](https://github.com/zhoujunhe)'s adb branches

**Comment by lixocg** [comment]
@zhoujunhe 大佬，使用你的metabase版本后，对于analyticDB连接使用是OK的，但是在使用metabase模型时，对模型的schema权限已经完全放开，在打开模型时，报如下错误：
[4421e2b2-38d1-4a51-83fb-e91d76b37bf8] 2024-06-28T15:52:00+08:00 WARN metabase.driver.mysql.ddl 
java.lang.IllegalArgumentException: Can't put nil on channel
	at clojure.core.async.impl.channels.ManyToManyChannel.put_BANG_(channels.clj:70)
	at clojure.core.async$put_BANG_.invokeStatic(async.clj:201)
	at clojure.core.async$put_BANG_.invoke(async.clj:189)
	at metabase.driver.mysql.ddl$exec_async$fn__102534$fn__102535.invoke(ddl.clj:29)
	at metabase.driver.sql_jdbc.execute$fn__77633$fn__77634.invoke(execute.clj:388)
	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334)
	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)
	at metabase.driver.sql_jdbc.execute$fn__77633.invokeStatic(execute.clj:382)
	at metabase.driver.sql_jdbc.execute$fn__77633.invoke(execute.clj:380)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.mysql.ddl$exec_async$fn__102534.invoke(ddl.clj:22)
	at clojure.core.async$thread_call$fn__40202.invoke(async.clj:486)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	怀疑也是驱动问题，大佬能否看下这个问题呢？

**Comment by northseadl** [comment]
v0.49.17 版本, 我也报错了相同的错误 

`WARN metabase.driver.mysql.ddl
java.lang.IllegalArgumentException: Can't put nil on channel`

触发操作是: 管理设置-数据库-打开模型缓存

**Comment by lixocg** [comment]
> 你使用的是哪一个版本？
> 
> 打出分支版本https://github.com/zhoujunhe/metabase/releases

v0.49.17
