### ISSUE TITLE
Aliyun MaxCompute Lightning use PostgreSQL protocol to scan the table and report an error

### ISSUE THREAD

**Issue by rainmote** [metabase/metabase#12669]
**Describe the bug**
Scan table field error
Because there is no pg_enum system table

**Logs**
```
06-10 00:18:51 ERROR sync.util :: Error syncing Fields for Table 'Table 744 'xx.xx''
org.postgresql.util.PSQLException: ERROR: relation "pg_enum" does not exist
  Position: 32
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
        at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
        at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1113)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at metabase.driver.postgres$enum_types.invokeStatic(postgres.clj:100)
        at metabase.driver.postgres$enum_types.invoke(postgres.clj:97)
        at metabase.driver.postgres$fn__72327.invokeStatic(postgres.clj:113)
        at metabase.driver.postgres$fn__72327.invoke(postgres.clj:111)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at metabase.sync.fetch_metadata$fn__52594$table_metadata__52599$fn__52600.invoke(fetch_metadata.clj:18)
        at metabase.sync.fetch_metadata$fn__52594$table_metadata__52599.invoke(fetch_metadata.clj:15)
        at metabase.sync.sync_metadata.fields.fetch_metadata$fn__52916$db_metadata__52921$fn__52922.invoke(fetch_metadata.clj:82)
        at metabase.sync.sync_metadata.fields.fetch_metadata$fn__52916$db_metadata__52921.invoke(fetch_metadata.clj:78)
        at metabase.sync.sync_metadata.fields$fn__53419$sync_fields_for_table_BANG___53428$fn__53434$fn__53436.invoke(fields.clj:90)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
        at metabase.sync.sync_metadata.fields$fn__53419$sync_fields_for_table_BANG___53428$fn__53434.invoke(fields.clj:89)
        at metabase.sync.sync_metadata.fields$fn__53419$sync_fields_for_table_BANG___53428.invoke(fields.clj:83)
        at clojure.core$partial$fn__5839.invoke(core.clj:2624)
        at clojure.core$map$fn__5866.invoke(core.clj:2753)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$filter$fn__5893.invoke(core.clj:2809)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:58)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.boundedLength(RT.java:1792)
        at clojure.lang.RestFn.applyTo(RestFn.java:130)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.sync.sync_metadata.fields$fn__53464$sync_fields_BANG___53469$fn__53470.invoke(fields.clj:115)
        at metabase.sync.sync_metadata.fields$fn__53464$sync_fields_BANG___53469.invoke(fields.clj:107)
        at metabase.sync.util$fn__44568$run_step_with_metadata__44573$fn__44577$fn__44579.invoke(util.clj:345)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
        at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119)
        at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116)
        at metabase.sync.util$fn__44568$run_step_with_metadata__44573$fn__44577.invoke(util.clj:342)
        at metabase.sync.util$fn__44568$run_step_with_metadata__44573.invoke(util.clj:337)
        at metabase.sync.util$fn__44760$run_sync_operation__44765$fn__44766$fn__44767.invoke(util.clj:430)
        at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6827)
        at clojure.core$mapv.invokeStatic(core.clj:6903)
        at clojure.core$mapv.invoke(core.clj:6903)
        at metabase.sync.util$fn__44760$run_sync_operation__44765$fn__44766.invoke(util.clj:430)
        at metabase.sync.util$fn__44760$run_sync_operation__44765.invoke(util.clj:424)
        at metabase.sync.sync_metadata$fn__54138$sync_db_metadata_BANG___54143$fn__54144$fn__54145.invoke(sync_metadata.clj:51)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
        at clojure.core$partial$fn__5839.invoke(core.clj:2623)
        at metabase.driver$fn__22363.invokeStatic(driver.clj:537)
        at metabase.driver$fn__22363.invoke(driver.clj:537)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at metabase.sync.util$sync_in_context$fn__44480.invoke(util.clj:138)
        at metabase.sync.util$with_db_logging_disabled$fn__44477.invoke(util.clj:129)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
        at metabase.sync.util$with_start_and_finish_logging$fn__44466.invoke(util.clj:114)
        at metabase.sync.util$with_sync_events$fn__44461.invoke(util.clj:88)
        at metabase.sync.util$with_duplicate_ops_prevented$fn__44452.invoke(util.clj:67)
        at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164)
        at metabase.sync.util$do_sync_operation.invoke(util.clj:161)
        at metabase.sync.sync_metadata$fn__54138$sync_db_metadata_BANG___54143$fn__54144.invoke(sync_metadata.clj:50)
        at metabase.sync.sync_metadata$fn__54138$sync_db_metadata_BANG___54143.invoke(sync_metadata.clj:47)
        at metabase.api.database$fn__54843$fn__54845.invoke(database.clj:590)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
Need use Aliyun MaxCompute Lightning
Trigger table synchronization or scan

**Comment by flamber** [comment]
Metabase technically don't support Aliyun MaxCompute Lightning except if what you're experiencing is also a Postgres bug. A lot of databases promises compatibility, but that don't actually deliver it.

**Comment by mattholy** [comment]
We're currently suffering the same problem about Ali's productions. 
After a wide investigating, we have a conclusion that the Ali's ADB dose **NOT** support signed datatypes.
FYI

**Comment by paoliniluis** [comment]
Note: we have a customer that was able to connect to maxcompute via https://www.alibabacloud.com/help/en/hologres/product-overview/what-is-hologres

**Comment by paoliniluis** [comment]
Seems there's a driver https://www.alibabacloud.com/help/en/maxcompute/user-guide/connect-metabase-to-maxcompute
