### ISSUE TITLE
Stale fingerprints

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#12816]
We only recalculate fingerprints when we up fingerprint version to save resources. This can cause issues for users who's data changes distribution with fast pace. The most prominent of which is binning being wacky or not working at all is it depends on `min` and `max` values from the fingerprints. 
There are a few ways forward:

1) forced sync also force fingerprint recalculation 
Pros: no performance hit in regular operations; simple to do
Cons: manual sucks

2) add force fingerprint recalculation button in admin
Pros: only pay the price when you really need it; simple to do
Cons: manual sucks; more buttons 

3) have some heuristics in place for when to recalculate fingerprints aka. fingerprint sniffing lite
The most naive (but probably already good enough) implementation would be to always calculate fingerprints on results (like we do for native queries, custom columns, aggregations), and if the newly calculated fingerprint differs from the saved one, mark that field for recalculation (or spawn a background process that does that immediately). Update criteria could be further refined by looking at the structure of the query (if mbql). Eg. if there is a limit or a filter only trigger recalculation if bounds broaden (bigger max, smaller min).
Pros: mostly automatic & seamless (worst case we occasionally have to direct the user to do a rows query, so we can look at the results)
Cons: small performance hit (but only on MB/computation side, not dbwh)

4) periodically redo fingerprinting (say 1/week)
Pros: automatic; simple to do
Cons: can take time to reflect new state; a lot of needless computation

5) periodically redo fingerprinting but with adaptive rate: for each field first redo fingerprint on next sync. If nothing changed, raise this frequency to every 2nd sync. If still nothing changed, do it in 4 and so on up to some upper bound. If something did change, half the refresh frequency all the way back to 1. This way we capture the underlying change frequency and minimize unneeded refreshes.
Pros: automatic; minimizes unneeded work
Cons: still hits the dbwh more than status quo; can still take time to reflect new state

My vote is: 3 or 5. I could also see doing 1/2 alongside.

**Comment by LukeAbell** [comment]
@sbelak Is there a way to do this manually in the DB? Our install is broken after downgrading from v0.37.0-rc3 to v0.36.7

This is the error:
Oct 20 17:05:34 metabase-75b4d9b7b9-hmbgs metabase 
 {:type :schema.core/error, :schema {:name java.lang.String, :display_name java.lang.String, #schema.core.OptionalKey{:k :description} (maybe (constrained Str "Non-blank string")), :base_type (pred "Valid field type (keyword or string)"), #schema.core.OptionalKey{:k :special_type} (maybe (pred "Valid field type (keyword or string)")), #schema.core.OptionalKey{:k :unit} (maybe (constrained (named (cond-pre Keyword Str) "Keyword or string") "Valid field datetime unit keyword or string")), #schema.core.OptionalKey{:k :fingerprint} (maybe {(optional-key :global) {(optional-key :distinct-count) Int, (optional-key :nil%) (maybe (constrained Num "Valid percentage between (inclusive) 0 and 1."))}, (optional-key :type) (constrained {(optional-key :type/Number) {(optional-key :min) (maybe Num), (optional-key :max) (maybe Num), (optional-key :avg) (maybe Num), (optional-key :q1) (maybe Num), (optional-key :q3) (maybe Num), (optional-key :sd) (maybe Num)}, (optional-key :type/Text) {(optional-key :percent-json) (maybe (constrained Num "Valid percentage between (inclusive) 0 and 1.")), (optional-key :percent-url) (maybe (constrained Num "Valid percentage between (inclusive) 0 and 1.")), (optional-key :percent-email) (maybe (constrained Num "Valid percentage between (inclusive) 0 and 1.")), (optional-key :average-length) (maybe Num)}, (optional-key :type/DateTime) {(optional-key :earliest) (maybe Str), (optional-key :latest) (maybe Str)}} "Type-specific fingerprint with exactly one key"), (optional-key :experimental) {Keyword Any}})}, :value {:base_type :type/Text, :display_name "Recipient → Email", :name "email", :fingerprint {:global {:distinct-count 7265, :nil% 0.1444051825677267}, :type {:type/Text {:percent-json 0.0, :percent-url 0.0, :percent-email 0.8555948174322733, :percent-state 0.0, :average-length 18.94416961130742}}}}, :error {:fingerprint {:type {:type/Text {:percent-state disallowed-key}}}}} at metabase.sync.analyze.query_results$fn__47102$col__GT_ResultColumnMetadata__47107.invoke(query_results.clj:56) at metabase.sync.analyze.query_results$insights_rf$iter__47122__47126$fn__47127$fn__47134.invoke(query_results.clj:73) at metabase.sync.analyze.query_results$insights_rf$iter__47122__47126$fn__47127.invoke(query_results.clj:72) at clojure.lang.LazySeq.sval(LazySeq.java:42) at clojure.lang.LazySeq.seq(LazySeq.java:51) at clojure.lang.RT.seq(RT.java:535) at clojure.core$seq__5402.invokeStatic(core.clj:137) at clojure.core$seq__5402.invoke(core.clj:137) at metabase.sync.analyze.query_results$insights_rf$iter__47143__47147$fn__47148.invoke(query_results.clj:79) at clojure.lang.LazySeq.sval(LazySeq.java:42) at clojure.lang.LazySeq.seq(LazySeq.java:51) at clojure.lang.RT.seq(RT.java:535) at clojure.core$seq__5402.invokeStatic(core.clj:137) at clojure.core$apply.invokeStatic(core.clj:660) at clojure.core$apply.invoke(core.clj:660) at metabase.sync.analyze.query_results$insights_rf.invokeStatic(query_results.clj:79) at metabase.sync.analyze.query_results$insights_rf.invoke(query_results.clj:66) at metabase.query_processor.middleware.results_metadata$insights_xform.invokeStatic(results_metadata.clj:127) at metabase.query_processor.middleware.results_metadata$insights_xform.invoke(results_metadata.clj:124) at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47201$rff_SINGLEQUOTE___47204.invoke(results_metadata.clj:146) at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280$fn__39281.invoke(add_rows_truncated.clj:38) at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47216$fn__47217.invoke(splice_params_in_response.clj:34) at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442$fn__39443.invoke(add_timezone_info.clj:17) at metabase.query_processor.middleware.add_dimension_projections$remap_results_rff$fn__38807.invoke(add_dimension_projections.clj:307) at metabase.query_processor.middleware.format_rows$format_rows$fn__45580$fn__45583.invoke(format_rows.clj:84) at metabase.query_processor.middleware.limit$limit$fn__45625$fn__45626.invoke(limit.clj:41) at metabase.query_processor.middleware.annotate$add_column_info$fn__43536$fn__43538.invoke(annotate.clj:578) at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45639$fn__45642.invoke(mbql_to_native.clj:31) at metabase.query_processor.context.default$default_reducef.invokeStatic(default.clj:56) at metabase.query_processor.context.default$default_reducef.invoke(default.clj:49) at metabase.query_processor.context$reducef.invokeStatic(context.clj:69) at metabase.query_processor.context$reducef.invoke(context.clj:62) at metabase.query_processor.context.default$default_runf$respond_STAR___37992.invoke(default.clj:70) at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:392) at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377) at metabase.driver.sql_jdbc$fn__73987.invokeStatic(sql_jdbc.clj:49) at metabase.driver.sql_jdbc$fn__73987.invoke(sql_jdbc.clj:47) at clojure.lang.MultiFn.invoke(MultiFn.java:244) at metabase.query_processor.context$executef.invokeStatic(context.clj:59) at metabase.query_processor.context$executef.invoke(context.clj:48) at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:69) at metabase.query_processor.context.default$default_runf.invoke(default.clj:67) at metabase.query_processor.context$runf.invokeStatic(context.clj:45) at metabase.query_processor.context$runf.invoke(context.clj:39) at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34) at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31) at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45639.invoke(mbql_to_native.clj:26) at metabase.query_processor.middleware.check_features$check_features$fn__44915.invoke(check_features.clj:42) at metabase.query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45804.invoke(optimize_datetime_filters.clj:133) at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47332.invoke(wrap_value_literals.clj:137) at metabase.query_processor.middleware.annotate$add_column_info$fn__43536.invoke(annotate.clj:574) at metabase.query_processor.middleware.permissions$check_query_permissions$fn__44790.invoke(permissions.clj:64) at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46322.invoke(pre_alias_aggregations.clj:40) at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44988.invoke(cumulative_aggregations.clj:61) at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__46854.invoke(resolve_joins.clj:183) at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245) at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__45600.invoke(large_int_id.clj:44) at metabase.query_processor.middleware.limit$limit$fn__45625.invoke(limit.clj:38) at metabase.query_processor.middleware.format_rows$format_rows$fn__45580.invoke(format_rows.clj:81) at metabase.query_processor.middleware.desugar$desugar$fn__45054.invoke(desugar.clj:22) at metabase.query_processor.middleware.binning$update_binning_strategy$fn__44080.invoke(binning.clj:229) at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__44596.invoke(resolve_fields.clj:24) at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:318) at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141) at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105) at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46519.invoke(reconcile_breakout_and_order_by_bucketing.clj:98) at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43721.invoke(auto_bucket_datetimes.clj:125) at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44643.invoke(resolve_source_table.clj:46) at metabase.query_processor.middleware.parameters$substitute_parameters$fn__46304.invoke(parameters.clj:114) at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44695.invoke(resolve_referenced.clj:80) at metabase.query_processor.middleware.expand_macros$expand_macros$fn__45310.invoke(expand_macros.clj:158) at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15) at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47216.invoke(splice_params_in_response.clj:32) at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46530$fn__46534.invoke(resolve_database_and_driver.clj:33) at metabase.driver$do_with_driver.invokeStatic(driver.clj:61) at metabase.driver$do_with_driver.invoke(driver.clj:57) at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46530.invoke(resolve_database_and_driver.clj:27) at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45528.invoke(fetch_source_query.clj:267) at metabase.query_processor.middleware.store$initialize_store$fn__47225$fn__47226.invoke(store.clj:11) at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:46) at metabase.query_processor.store$do_with_store.invoke(store.clj:40) at metabase.query_processor.middleware.store$initialize_store$fn__47225.invoke(store.clj:10) at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__44572.invoke(cache.clj:209) at metabase.query_processor.middleware.validate$validate_query$fn__47234.invoke(validate.clj:10) at metabase.query_processor.middleware.normalize_query$normalize$fn__45652.invoke(normalize_query.clj:22) at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36) at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47201.invoke(results_metadata.clj:147) at metabase.query_processor.middleware.constraints$add_default_userland_constraints$fn__44931.invoke(constraints.clj:42) at metabase.query_processor.middleware.process_userland_query$process_userland_query$fn__46393.invoke(process_userland_query.clj:136) at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__44874.invoke(catch_exceptions.clj:174) at metabase.query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101) at metabase.query_processor.reducible$async_qp$qp_STAR___38074.invoke(reducible.clj:107) at metabase.query_processor.reducible$sync_qp$qp_STAR___38083$fn__38086.invoke(reducible.clj:133) at metabase.query_processor.reducible$sync_qp$qp_STAR___38083.invoke(reducible.clj:132) at clojure.lang.AFn.applyToHelper(AFn.java:156) at clojure.lang.AFn.applyTo(AFn.java:144) at clojure.core$apply.invokeStatic(core.clj:667) at clojure.core$apply.invoke(core.clj:660) at metabase.query_processor$process_userland_query.invokeStatic(query_processor.clj:215) at metabase.query_processor$process_userland_query.doInvoke(query_processor.clj:211) at clojure.lang.RestFn.invoke(RestFn.java:423) at metabase.query_processor$fn__47376$process_query_and_save_execution_BANG___47385$fn__47388.invoke(query_processor.clj:227) at metabase.query_processor$fn__47376$process_query_and_save_execution_BANG___47385.invoke(query_processor.clj:219) at metabase.query_processor$fn__47420$process_query_and_save_with_max_results_constraints_BANG___47429$fn__47432.invoke(query_processor.clj:239) at metabase.query_processor$fn__47420$process_query_and_save_with_max_results_constraints_BANG___47429.invoke(query_processor.clj:232) at metabase.api.dataset$fn__50711$fn__50714.invoke(dataset.clj:55) at metabase.query_processor.streaming$streaming_response_STAR_$fn__35496$fn__35497.invoke(streaming.clj:73) at metabase.query_processor.streaming$streaming_response_STAR_$fn__35496.invoke(streaming.clj:72) at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:66) at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:64) at metabase.async.streaming_response$do_f_async$fn__23282.invoke(streaming_response.clj:85) at clojure.lang.AFn.applyToHelper(AFn.java:152) at clojure.lang.AFn.applyTo(AFn.java:144) at clojure.core$apply.invokeStatic(core.clj:665) at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973) at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973) at clojure.lang.RestFn.invoke(RestFn.java:425) at clojure.lang.AFn.applyToHelper(AFn.java:156) at clojure.lang.RestFn.applyTo(RestFn.java:132) at clojure.core$apply.invokeStatic(core.clj:669) at clojure.core$bound_fn_STAR_$fn__5749.doInvoke(core.clj:2003) at clojure.lang.RestFn.invoke(RestFn.java:397) at clojure.lang.AFn.run(AFn.java:22) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) at java.base/java.util.concurrent.FutureTask.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
Oct 20 17:05:35 metabase-75b4d9b7b9-hmbgs metabase DEBUG 10-20 21:05:35 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 434.3 ms (9 DB calls) App DB connections: 1/15 Jetty threads: 3/50 (7 idle, 0 queued) (115 total active threads) Queries in flight: 0 (0 queued)
Oct 20 17:05:35 metabase-75b4d9b7b9-hmbgs metabase DEBUG 10-20 21:05:35 DEBUG middleware.log :: GET /api/database 200 868.1 ms (4 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (7 idle, 0 queued) (115 total active threads) Queries in flight: 0 (0 queued)
Oct 20 17:05:36 metabase-75b4d9b7b9-hmbgs metabase DEBUG 10-20 21:05:36 DEBUG middleware.log :: POST /api/card 400 8.7 ms (0 DB calls)
Oct 20 17:05:36 metabase-75b4d9b7b9-hmbgs metabase {:errors {:result_metadata "value may be nil, or if non-nil, value must be an array of valid results column metadata maps."}}
Oct 20 17:05:36 metabase-75b4d9b7b9-hmbgs metabase

**Comment by camsaul** [comment]
@LukeAbell out of curiosity, what's the reason you're downgrading from 0.37.0-rc3 to 0.36.7?

**Comment by LukeAbell** [comment]
@camsaul joins are broken for us I'm guessing from https://github.com/metabase/metabase/issues/13534

**Comment by camsaul** [comment]
@LukeAbell I've opened a new issue for your fingerprint issue: #13542
