### ISSUE TITLE
0.36.0 regression (?) Snowflake views stopped appearing

### ISSUE THREAD

**Issue by gouline** [metabase/metabase#12971]
**Describe the bug**
Since upgrading to 0.36.0, Metabase stopped seeing views in Snowflake databases, only tables.

**Logs**
There are no errors in logs or elsewhere, scanning databases is successful, the views just never appear in table lists or in the data model section.

**To Reproduce**
1. Go to 'Our Data' OR 'Settings' > 'Admin' > 'Data Model'
2. Click on any Snowflake database

**Expected behavior**
Views appearing in the list alongside tables, as observed in 0.35.4.

**Screenshots**
N/A

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 84.0.4147.89
- Your operating system: macOS 10.15.6
- Your databases: Snowflake
- Metabase version: 0.36.0
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

**Severity**
Blocking our usage of Metabase entirely, much of our data is exposed as views.

**Additional context**

**Comment by flamber** [comment]
Hi @gouline 
Thank you for reporting. Please downgrade to 0.35.4 - it will be part of 0.36.1 - #12936

**Comment by camsaul** [comment]
#9511 is a tangentially related issue

**Comment by camsaul** [comment]
Fixed by #12936

**Comment by gouline** [comment]
@flamber @camsaul Just checking whether this is known or I need to raise a separate ticket. I noticed today that since upgrading to 0.36.0 and then downgrading back to 0.35.4 earlier in the week, syncing schema for _all_ my tables has been failing with the following error:

```
ERROR metabase.sync.util Error syncing Fields for Table 'Table 38 'SCHEMA.TABLE'
```

Digging deeper in the console log yields this:

```
[1mERROR sync.util[0m :: Error syncing Fields for Table 'Table 38 'SCHEMA.TABLE'
java.sql.BatchUpdateException: Batch entry 0 UPDATE "metabase_table" SET "fields_hash" = 'Jkyox5Hvexo+iPSRRYoETg==', "updated_at" = now() WHERE "id" = 38 was aborted: ERROR: column "fields_hash" of relation "metabase_table" does not exist
  Position: 29  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2234)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:510)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:853)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1546)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2544)
	at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:591)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__18741.invoke(jdbc.clj:1057)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1056)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1042)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1080)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1060)
	at clojure.java.jdbc$execute_BANG_$execute_helper__18809.invoke(jdbc.clj:1464)
	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1468)
	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1435)
	at toucan.db$execute_BANG_.invokeStatic(db.clj:427)
	at toucan.db$execute_BANG_.doInvoke(db.clj:422)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$update_BANG_.invokeStatic(db.clj:482)
	at toucan.db$update_BANG_.invoke(db.clj:471)
	at toucan.db$update_BANG_.invokeStatic(db.clj:491)
	at toucan.db$update_BANG_.invoke(db.clj:471)
	at toucan.db$update_BANG_.invokeStatic(db.clj:499)
	at toucan.db$update_BANG_.doInvoke(db.clj:471)
	at clojure.lang.RestFn.invoke(RestFn.java:470)
	at metabase.sync.sync_metadata.fields$fn__53419$sync_fields_for_table_BANG___53428$fn__53434$fn__53436.invoke(fields.clj:99)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at metabase.sync.sync_metadata.fields$fn__53419$sync_fields_for_table_BANG___53428$fn__53434.invoke(fields.clj:89)
	at metabase.sync.sync_metadata.fields$fn__53419$sync_fields_for_table_BANG___53428.invoke(fields.clj:83)
	at clojure.core$partial$fn__5839.invoke(core.clj:2624)
	at clojure.core$map$fn__5866.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$filter$fn__5893.invoke(core.clj:2809)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1792)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.sync_metadata.fields$fn__53464$sync_fields_BANG___53469$fn__53470.invoke(fields.clj:115)
	at metabase.sync.sync_metadata.fields$fn__53464$sync_fields_BANG___53469.invoke(fields.clj:107)
	at metabase.sync.util$fn__44568$run_step_with_metadata__44573$fn__44577$fn__44579.invoke(util.clj:345)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116)
	at metabase.sync.util$fn__44568$run_step_with_metadata__44573$fn__44577.invoke(util.clj:342)
	at metabase.sync.util$fn__44568$run_step_with_metadata__44573.invoke(util.clj:337)
	at metabase.sync.util$fn__44760$run_sync_operation__44765$fn__44766$fn__44767.invoke(util.clj:430)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at metabase.sync.util$fn__44760$run_sync_operation__44765$fn__44766.invoke(util.clj:430)
	at metabase.sync.util$fn__44760$run_sync_operation__44765.invoke(util.clj:424)
	at metabase.sync.sync_metadata$fn__54138$sync_db_metadata_BANG___54143$fn__54144$fn__54145.invoke(sync_metadata.clj:51)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver$fn__22363.invokeStatic(driver.clj:537)
	at metabase.driver$fn__22363.invoke(driver.clj:537)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__44480.invoke(util.clj:138)
	at metabase.sync.util$with_db_logging_disabled$fn__44477.invoke(util.clj:129)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_logging$fn__44466.invoke(util.clj:114)
	at metabase.sync.util$with_sync_events$fn__44461.invoke(util.clj:88)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__44452.invoke(util.clj:67)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:161)
	at metabase.sync.sync_metadata$fn__54138$sync_db_metadata_BANG___54143$fn__54144.invoke(sync_metadata.clj:50)
	at metabase.sync.sync_metadata$fn__54138$sync_db_metadata_BANG___54143.invoke(sync_metadata.clj:47)
	at metabase.api.database$fn__54843$fn__54845.invoke(database.clj:590)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: column "fields_hash" of relation "metabase_table" does not exist
  Position: 29
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	... 91 more
```

Would there be anything in 0.36.0 that the internal database wouldn't gracefully downgrade to 0.35.4 state from? I'm thinking why else would `fields_hash` column be missing...

**Comment by flamber** [comment]
@gouline Metabase has never supported downgrade officially. It has usually been possible to downgrade, but 0.36.0 has done big changes to the metadata, so that would break downgrade. Always remember to backup before upgrading and revert to the backup when downgrading.

**Comment by gouline** [comment]
Gotcha, I messed up... I have a snapshot from before, but applying it now would lose user changes since then. I guess I'll upgrade to 0.36.0 again and wait for 0.36.1 with the fix. Hopefully not far away 😄
