### ISSUE TITLE
Exception, when stopping instance (^C)

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#12986]
**Describe the bug**
When closing an instance, it's giving an exception since a little while before 0.36.0, but I thought it was my build environment.

**To Reproduce**
1. Start with H2 backend `java -jar metabase.jar`
2. Don't use instance for a few minutes (perhaps 10min)
3. Stop process with `^C` (Ctrl+C)
4. Shows exception:
```
07-23 15:34:23 DEBUG middleware.log :: GET /api/dashboard/6 200 4.5 ms (4 DB calls) App DB connections: 0/10 Jetty threads: 4/50 (5 idle, 0 queued) (104 total active threads) Queries in flight: 0 (0 queued)
^CException in thread "Thread-10" org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1526)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1502)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:302)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:387)
	at clojure.java.jdbc$prepare_statement.invokeStatic(jdbc.clj:679)
	at clojure.java.jdbc$prepare_statement.invoke(jdbc.clj:626)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1112)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at toucan.db$query.invokeStatic(db.clj:288)
	at toucan.db$query.doInvoke(db.clj:284)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$simple_select.invokeStatic(db.clj:394)
	at toucan.db$simple_select.invoke(db.clj:383)
	at toucan.db$simple_select_one.invokeStatic(db.clj:420)
	at toucan.db$simple_select_one.invoke(db.clj:409)
	at toucan.db$select_one.invokeStatic(db.clj:627)
	at toucan.db$select_one.doInvoke(db.clj:620)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at toucan.db$select_one_field.invokeStatic(db.clj:636)
	at toucan.db$select_one_field.doInvoke(db.clj:629)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.models.setting.cache$cache_out_of_date_QMARK_.invokeStatic(cache.clj:98)
	at metabase.models.setting.cache$cache_out_of_date_QMARK_.invoke(cache.clj:79)
	at metabase.models.setting.cache$restore_cache_if_needed_BANG_.invokeStatic(cache.clj:151)
	at metabase.models.setting.cache$restore_cache_if_needed_BANG_.invoke(cache.clj:128)
	at metabase.models.setting$db_or_cache_value.invokeStatic(setting.clj:175)
	at metabase.models.setting$db_or_cache_value.invoke(setting.clj:169)
	at metabase.models.setting$get_string.invokeStatic(setting.clj:188)
	at metabase.models.setting$get_string.invoke(setting.clj:178)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.util.i18n.impl$fn__7770$f__7771.invoke(impl.clj:156)
	at metabase.util.i18n.impl$site_locale_from_setting.invokeStatic(impl.clj:163)
	at metabase.util.i18n.impl$site_locale_from_setting.invoke(impl.clj:160)
	at metabase.util.i18n$site_locale.invokeStatic(i18n.clj:31)
	at metabase.util.i18n$site_locale.invoke(i18n.clj:28)
	at metabase.util.i18n$translate_site_locale.invokeStatic(i18n.clj:52)
	at metabase.util.i18n$translate_site_locale.doInvoke(i18n.clj:49)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.util.i18n.SiteLocalizedString.toString(i18n.clj:75)
	at clojure.core$str.invokeStatic(core.clj:553)
	at clojure.core$str.invoke(core.clj:544)
	at metabase.core$destroy_BANG_.invokeStatic(core.clj:47)
	at metabase.core$destroy_BANG_.invoke(core.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
5. Starting an instance, but without inactivity, and then shutting down just shows the regular messages:
```
07-23 15:53:07 DEBUG middleware.log :: GET /api/automagic-dashboards/database/4/candidates 200 671.4 ms (6 DB calls) App DB connections: 0/4 Jetty threads: 4/50 (3 idle, 0 queued) (47 total active threads) Queries in flight: 0 (0 queued)
^C07-23 15:53:11 INFO metabase.core :: Metabase Shutting Down ...
07-23 15:53:11 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
07-23 15:53:11 INFO metabase.core :: Metabase Shutdown COMPLETE
```

**Information about your Metabase Installation:**
```
07-23 15:50:42 INFO metabase.core :: Starting Metabase version v0.36.0 (b31049f release-0.36.x) ...
07-23 15:50:42 INFO metabase.core :: System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "11.0.8+10",
 "java.vendor" "AdoptOpenJDK",
 "java.vendor.url" "https://adoptopenjdk.net/",
 "java.version" "11.0.8",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "11.0.8+10",
 "os.name" "Linux",
 "os.version" "5.3.0-62-generic",
 "user.language" "en",
 "user.timezone" "Europe/Copenhagen"}
```

**Severity**
Not sure if this might cause some problem in the future, but I haven't noticed anything, so just giving P3.

**Comment by camsaul** [comment]
This isn't going to cause any problems, it's a little annoying it's printing stuff like that but it's all the sort of stuff we'd expect -- this is really more like a P4 or P5

**Comment by mohanagandlla** [comment]
any updates on this i am also facing the same issue

**Comment by flamber** [comment]
@mohanagandlla Yes, don't use H2: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
