### ISSUE TITLE
AWS SES Email uses the logged in user's email as the from email in addition to the FROM ADDRESS.

### ISSUE THREAD

**Issue by ronswanson730** [metabase/metabase#13162]
Hi,

I've configured the Email settings in metabase to connect to AWS SES. I set the **FROM ADDRESS** to `metabase@example.com`. I login as `user@domainb.com` but when I try to send a test mail or when I try to reset my password I get the following message: `554 Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: metabase@example.com, user@domainb.com`

This is very strange as AWS SES only validates the **FROM ADDRESS**. It doesn't care who is the recipient but somehow it seems metabase is trying to set `user@domainb.com` as the from email also. I have verified `metabase@example.com` from AWS SES and when I use the AWS console to send a test email to `user@domainb.com` I am able to send out the email with no issues.

I checked the source and I can't determine when the value for the :from is set. TBF I am not that familiar with clojure. Any help would be greatly appreciated.

Here is the full stack trace:
`at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2249)
        at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:2027)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1242)
        at postal.smtp$smtp_send_STAR_.invokeStatic(smtp.clj:36)
        at postal.smtp$smtp_send_STAR_.invoke(smtp.clj:29)
        at postal.smtp$smtp_send.invokeStatic(smtp.clj:58)
        at postal.smtp$smtp_send.doInvoke(smtp.clj:39)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at postal.core$send_message.invokeStatic(core.clj:36)
        at postal.core$send_message.invoke(core.clj:29)
        at metabase.email$fn__31918$send_message_or_throw_BANG___31923$fn__31927.invoke(email.clj:95)
        at metabase.email$fn__31918$send_message_or_throw_BANG___31923.invoke(email.clj:86)
        at metabase.email$send_message_BANG_.invokeStatic(email.clj:120)
        at metabase.email$send_message_BANG_.doInvoke(email.clj:105)
        at clojure.lang.RestFn.invoke(RestFn.java:619)
        at metabase.email.messages$send_password_reset_email_BANG_.invokeStatic(messages.clj:130)
        at metabase.email.messages$send_password_reset_email_BANG_.invoke(messages.clj:117)
        at metabase.api.session$fn__64892.invokeStatic(session.clj:185)
        at metabase.api.session$fn__64892.invoke(session.clj:173)
        at compojure.core$wrap_response$fn__1993.invoke(core.clj:160)
        at compojure.core$wrap_route_middleware$fn__1977.invoke(core.clj:132)
        at compojure.core$wrap_route_info$fn__1982.invoke(core.clj:139)
        at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:151)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:153)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:152)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005.invoke(core.clj:200)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005.invoke(core.clj:200)
        at compojure.core$make_context$handler__2033.invoke(core.clj:287)
        at compojure.core$make_context$fn__2035.invoke(core.clj:296)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$make_context$fn__2035.invoke(core.clj:297)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005.invoke(core.clj:200)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.routes$fn__68332$fn__68333.doInvoke(routes.clj:56)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005.invoke(core.clj:200)
        at compojure.core$make_context$handler__2033.invoke(core.clj:287)
        at compojure.core$make_context$fn__2035.invoke(core.clj:296)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:153)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:153)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:153)
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
        at compojure.core$routes$fn__2005.invoke(core.clj:200)
        at metabase.middleware.exceptions$catch_uncaught_exceptions$fn__66907.invoke(exceptions.clj:97)
        at metabase.middleware.exceptions$catch_api_exceptions$fn__66904.invoke(exceptions.clj:85)
        at metabase.middleware.log$log_api_call$fn__68710$fn__68711.invoke(log.clj:197)
        at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
        at toucan.db$_do_with_call_counting.invoke(db.clj:209)
        at metabase.middleware.log$log_api_call$fn__68710.invoke(log.clj:191)
        at metabase.middleware.security$add_security_headers$fn__66870.invoke(security.clj:121)
        at metabase.middleware.json$wrap_json_body$fn__68413.invoke(json.clj:64)
        at metabase.middleware.json$wrap_streamed_json_response$fn__68431.invoke(json.clj:100)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__69002.invoke(keyword_params.clj:55)
        at ring.middleware.params$wrap_params$fn__69050.invoke(params.clj:69)
        at metabase.middleware.misc$maybe_set_site_url$fn__68740.invoke(misc.clj:59)
        at metabase.middleware.session$bind_current_user$fn__63397$fn__63398.invoke(session.clj:209)
        at metabase.middleware.session$do_with_current_user.invokeStatic(session.clj:184)
        at metabase.middleware.session$do_with_current_user.invoke(session.clj:177)
        at metabase.middleware.session$bind_current_user$fn__63397.invoke(session.clj:208)
        at metabase.middleware.session$wrap_current_user_id$fn__63382.invoke(session.clj:161)
        at metabase.middleware.session$wrap_session_id$fn__63326.invoke(session.clj:125)
        at metabase.middleware.auth$wrap_api_key$fn__66816.invoke(auth.clj:27)
        at metabase.middleware.misc$bind_user_locale$fn__68745.invoke(misc.clj:78)
        at ring.middleware.cookies$wrap_cookies$fn__68922.invoke(cookies.clj:216)
        at metabase.middleware.misc$add_content_type$fn__68726.invoke(misc.clj:29)
        at metabase.middleware.misc$disable_streaming_buffering$fn__68754.invoke(misc.clj:94)
        at ring.middleware.gzip$wrap_gzip$fn__68964.invoke(gzip.clj:86)
        at metabase.server$async_proxy_handler$fn__68488.invoke(server.clj:70)
        at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:500)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by flamber** [comment]
Hi @ronswanson730 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Post "Diagnostic Info" from Admin > Troubleshooting.
It seems like it's not the full stacktrace - a trace doesn't start with `at ...`
Make sure you have verified the From-email, since it seems to be complaining about that - `Email address is not verified`.

**Comment by ronswanson730** [comment]
@flamber I mentioned the email has been verified. AWS SES only requires you to verify the sender (FROM ADDRESS) and not the recipient. However, metabase seems to be trying to send with the recipient address which doesn't seem correct. I managed to send a test email from the AWS SES console to the same recipient and it succeeded.

**Comment by flamber** [comment]
@ronswanson730 
Post "Diagnostic Info" from Admin > Troubleshooting.
I have not seen that before. I don't know how much logging SES provides, but if you can get information from there, then it would be helpful.
Have you tried any other SMTP provider?
