### ISSUE TITLE
Presto driver issue

### ISSUE THREAD

**Issue by rodolphogarrido** [metabase/metabase#13179]
**Describe the bug**

Queries on Metabase using PrestoSQL 338 were working fine but after upgrading to PrestoSQL 340 I started facing a particular error (described in the Logs section). I humbly think it's related to the Presto driver used in Metabase since I was able to reproduce the same error using DBeaver with an older PrestoSQL driver (version 338) to query Presto 340, and got rid of the problem after upgrading DBeaver PrestoSQL driver to version 340. 
 
**Logs**

Metabase error:

![image](https://user-images.githubusercontent.com/47122489/91581524-e814e780-e924-11ea-8f13-7113e9ecace6.png)

DBeaver Logs (using older driver):

```
io.prestosql.spi.PrestoException: Could not serialize column 'original_address' of type 'row(country varchar, state varchar, city varchar, district varchar, zone varchar, neighborhood varchar, street varchar, street_number varchar, complement varchar, zip_code varchar, level varchar, point row(lat double, lon double, source varchar), geo_json varchar, precision varchar, name varchar, location_id varchar, source varchar, confidence varchar, pois array(row(name varchar, geo_location row(lat double, lon double), distance double, category varchar)), valuable_zones array(row(id varchar, name varchar, state varchar, city varchar, zone varchar, category varchar)), pois_list array(varchar), ibge_city_id varchar, state_acronym varchar)' at position 1:22
	at io.prestosql.server.protocol.QueryResultRows.lambda$propagateException$6(QueryResultRows.java:262)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.prestosql.server.protocol.QueryResultRows.propagateException(QueryResultRows.java:262)
	at io.prestosql.server.protocol.QueryResultRows.getRowValues(QueryResultRows.java:179)
	at io.prestosql.server.protocol.QueryResultRows.computeNext(QueryResultRows.java:150)
	at io.prestosql.server.protocol.QueryResultRows.computeNext(QueryResultRows.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serializeContents(IterableSerializer.java:83)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:74)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:12)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1433)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:921)
	at io.airlift.jaxrs.JsonMapper.writeTo(JsonMapper.java:233)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
	at io.airlift.jaxrs.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:102)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: undefined
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
	at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:786)
	at io.prestosql.server.protocol.QueryResultRows.getLegacyValue(QueryResultRows.java:244)
	at io.prestosql.server.protocol.QueryResultRows.getRowValues(QueryResultRows.java:175)
	... 42 more
```

**To Reproduce**
1. Run queries on Metabase using PrestoSQL 338 (No problem at all).
2. Run queries on Metabase using PrestoSQl 340 (Some queries fail with the same error describe in the Logs section).

Sorry I couldn't provide a better way to reproduce.

**Expected behavior**
Be able to use PrestoSQL latest version.

**Screenshots**
Not applicable.

**Severity**
This issue is severe _to me_ since it's blocking to upgrade to PrestoSQL 340 (we won't upgrade PrestoSQL version if we can't use it in Metabase).

**Additional context**
I've faced the same issue even running Metabase latest version in a local Docker.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.19.95-coreos",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres",
      "presto",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.5"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-02-25",
      "tag": "v0.34.3",
      "branch": "release-0.34.x",
      "hash": "1a83edb"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Comment by rodolphogarrido** [comment]
After updating to PrestoSQL 343 the problems no longer happen and everything is working normally.

**Comment by flamber** [comment]
Looks like it was fixed in 341: https://github.com/prestosql/presto/issues/4778

**Comment by jeff303** [comment]
We need to be very clear that we don't yet support TrinoDB.  It just so happens to work for some people who use the Presto driver (what will be called the "legacy version" as of 0.41, at that).  But until we have first class Trino driver support, we can't provide product support for things like this.
