### ISSUE TITLE
Unable to query table with binary columns

### ISSUE THREAD

**Issue by JosephRedfern** [metabase/metabase#1326]
When attempting to run a query against a table with a binary column type, the UI gets stuck at "doing science", and the following exception is printed to the console:
```
2015-10-22 12:01:50,508 [WARN ] org.eclipse.jetty.server.HttpChannel :: /api/dataset
com.fasterxml.jackson.core.JsonGenerationException: Cannot JSON encode object of class: class [B: [B@36dee663
	at cheshire.generate$generate.invoke(generate.clj:148)
	at cheshire.generate$generate.invoke(generate.clj:127)
	at cheshire.generate$generate.invoke(generate.clj:127)
	at cheshire.generate$generate.invoke(generate.clj:119)
	at cheshire.generate$generate.invoke(generate.clj:119)
	at cheshire.core$generate_string.invoke(core.clj:32)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$update_in.doInvoke(core.clj:5923)
	at clojure.lang.RestFn.invoke(RestFn.java:467)
	at ring.middleware.json$wrap_json_response$fn__21715.invoke(json.clj:89)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__21743.invoke(keyword_params.clj:32)
	at ring.middleware.params$wrap_params$fn__21765.invoke(params.clj:57)
	at metabase.middleware$bind_current_user$fn__20823.invoke(middleware.clj:87)
	at metabase.middleware$wrap_current_user_id$fn__20798.invoke(middleware.clj:55)
	at metabase.middleware$wrap_api_key$fn__20838.invoke(middleware.clj:98)
	at metabase.middleware$wrap_session_id$fn__20791.invoke(middleware.clj:46)
	at ring.middleware.cookies$wrap_cookies$fn__21643.invoke(cookies.clj:171)
	at ring.middleware.session$wrap_session$fn__21862.invoke(session.clj:85)
	at ring.middleware.gzip$wrap_gzip$fn__21672.invoke(gzip.clj:65)
	at ring.adapter.jetty$proxy_handler$fn__21004.invoke(jetty.clj:24)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

I'm connecting to a MySQL server. Is this a bug, or a problem with my config?

Thanks!

**Comment by salsakran** [comment]
Would you be comfortable sharing the schema of the table you're trying to query? Seems like we're getting a type we don't recognize.

**Comment by JosephRedfern** [comment]
I can provide an example schema that also gives problems, sure.

````
create table messages (
      id binary(16) primary key,
      senderId binary(16) not null references users(id),
      receiverId binary(16) not null bigint not null references users(id),
      message text not null
);
````

````
create table users(
      id binary(16) primary key,
      name text not null
);
````

The issue is stemming from the use of the binary ID column, I believe.

**Comment by tlrobinson** [comment]
It looks like the problem is what you would expect from the stack trace: the query itself runs fine, but when we try to return the result it blows up because it doesn't know how to encode binary data as JSON. And indeed there is no "binary" type for JSON, so we'll need to pick another way to encode it. The simplest solution would be to just return a base64 or hexadecimal encoded string (and optionally do something special when displaying it in the client).

Also is it safe to assume BINARY columns are typically used for small fixed-size binary strings, not large objects like images (which is what BLOB is for?)

**Comment by JosephRedfern** [comment]
In my case, it's a small, fixed size field, which is being used to store an unique identifier.

**Comment by JosephRedfern** [comment]
What work needs doing in order to support binary columns?

Is it a matter of defining a binary base type in the fields model, with something to convert to/from Hex/Base64 for each database driver when running queries against the binary columns? I'm happy to look at trying to add support for this feature, but am not entirely sure where to begin :smile:

**Comment by tlrobinson** [comment]
@JosephRedfern The minimum possible thing to get it to stop failing on queries with binary columns would be to add the following to `src/metabase/middleware.clj`:

`(add-encoder (class (byte-array [])) encode-str)`

(there might be better way to get the byte array class in Clojure, I don't know)

This will cause binary fields to be encoded as something like `[B@36dee663`.

A slightly nicer version might do something like this to encode as a hex string:

```
(add-encoder (class (byte-array []))
             (fn [ba jsonGenerator]
               (.writeString jsonGenerator
                             (clojure.string/join "" (map (partial format "%02x") ba)))))
```

However, additional changes need to be made to get filters to work correctly, for example when you click a primary key it's suppose to take you to an object detail page for that row.

**Comment by camsaul** [comment]
I like where your head is at @tlrobinson but I have a few suggestions:

*  Seeing how only robots can read a serialized byte array I think it makes sense to only keep the first 16 bytes or so. Maybe less
*  You can use `(apply str some-collection)` instead of `(clojure.string/join "" some-collection)`
*  It's clearer to use a `for` loop instead of `map` when you can.
```clojure
(add-encoder (Class/forName "[B")
             (fn [byte-ar json-generator]
               (.writeString json-generator (apply str "0x" (for [b (take 16 byte-ar)]
                                                              (format "%02x" b)))
;; -> 0x3becc5172175bd3cfa34ad839ce3b63e
```
