### ISSUE TITLE
Database Validation API returns error "value must be a valid database engine."

### ISSUE THREAD

**Issue by beanaroo** [metabase/metabase#13433]
**Describe the bug**
When calling `POST | /api/database/validate` with `engine` and `details` returned from `GET | /api/database`, a `400 - Bad Request` is returned with the response:

```json
{
  "errors": {
    "engine": "value must be a valid database engine."
  }
}
```

**Logs**
```
metabase    | 10-12 11:08:07 DEBUG middleware.log :: POST /api/database/validate 400 454.4 µs (0 DB calls)
metabase    | {:errors {:engine "value must be a valid database engine."}}
```

**To Reproduce**
1. Request to `GET | /api/database`
2. Extract `details` map and `engine` string
3. Call `POST | /api/database/validate` with body:
```json
{
	"engine": "postgres",
	"details": {
		"host": "my-database.rds.amazonaws.com",
		"port": 5432,
		"dbname": "MyDB",
		"user": "metabase",
		"password": "supersecretpassword",
		"ssl": true,
		"additional-options": null,
		"tunnel-enabled": false
	}
}
```

**Expected behavior**
A valid response

**Information about your Metabase Installation:**
- Simple docker-compose with an internal postgres dedicated to metabase
<details>
  <summary>Troubleshoot Output</summary>

```json
{
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.8+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.8+10",
    "os.name": "Linux",
    "os.version": "4.14.192-147.314.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Australia/Sydney"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.4 (Debian 12.4-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-09-15",
      "tag": "v0.36.6",
      "branch": "release-0.36.x",
      "hash": "cb258fb"
    },
    "settings": {
      "report-timezone": "Australia/Sydney"
    }
  }
}
```
</details>

**Severity**
- **Low**

**Additional context**
I was simply looking for a way to check the connectivity of all configured databases. Passing the database details back and forth feels unnecessary. I was hoping for an `available` or `last_sync_result` or something along those lines in the initial `GET | /api/database` listing but I have other external options available too.

I could not see anything obvious in [the code here](https://github.com/metabase/metabase/blob/e3f6fa24c378786b506391d5d0ec440b7d5edf4f/src/metabase/api/database.clj#L510). But Closure is foreign to me 🙂

**Comment by flamber** [comment]
Hi @beanaroo 

I'm not sure if this endpoint is even used anymore. The setup uses `POST /api/setup/validate`, which includes most of this and some more, but I'm not seeing `POST /api/database/validate` when creating a new database.

If you're just testing if the connection works, then doing a simple `SELECT 1` query should do it with [POST /api/dataset](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#post-apidataset)

Having something like `available` would probably solve #7526. And `last_sync` would probably solve #11354.

**Comment by camsaul** [comment]
@beanaroo you have to pass the body of the request like 

```clj
{:details {:engine "postgres", :details ...}}
```

I'd recommend opening the web inspector and taking a look at how the request is used during the normal setup flow as an example

**Comment by avodonosov** [comment]
I see the same error when running `yarn run test-cypress-run` as suggested in developer guide.

```
$ yarn run test-cypress-run
yarn run v1.22.19
$ node ./e2e/runner/run_cypress_tests.js
Metabase version info
Running e2e test runner with this build:
tag=v0.47.6-SNAPSHOT
hash=e7ee12e
branch=heads/v1.47.5
date=2023-10-20
If that version seems too old, please run `./bin/build.sh :steps '[:version :uberjar]'`.
Starting backend
Waiting for backend (host=http://localhost:4000, dbFile=/tmp/metabase-test-47755.db)....................................................................................................
Backend ready host=http://localhost:4000, dbFile=/tmp/metabase-test-47755.db
Generating snapshots
DeploySentinel Cypress Debugger: [v0.8.8] is disabled (key not found)

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.8.1                                                                         │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v20.9.0 (/usr/bin/node)                                                        │
  │ Specs:          1 found (default.cy.snap.js)                                                   │
  │ Searched:       e2e/snapshot-creators/**/*.cy.snap.js                                          │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  default.cy.snap.js                                                              (1 of 1)
Warning: The following browser launch options were provided but are not supported by electron

 - args


  snapshots
    default
      ✓ default (8632ms)
    withSqlite
      1) withSqlite


  1 passing (11s)
  1 failing

  1) snapshots
       withSqlite
         withSqlite:
     CypressError: `cy.request()` failed on:
                                                                                                                                      
http://localhost:4000/api/database                                                                                                    
                                                                                                                                      
The response we received from your web server was:                                                                                    
                                                                                                                                      
  > 400: Bad Request                                                                                                                  
                                                                                                                                      
This was considered a failure because the status code was not `2xx` or `3xx`.                                                         
                                                                                                                                      
If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`                                          
                                                                                                                                      
-----------------------------------------------------------                                                                           
                                                                                                                                      
The request we sent was:                                                                                                              
                                                                                                                                      
Method: POST                                                                                                                          
URL: http://localhost:4000/api/database                                                                                               
Headers: {                                                                                                                            
  "Connection": "keep-alive",                                                                                                         
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/12.8.1 Chrome/106.0.5249.51 Electron/21.0.0 Safari/537.36",                                                                                                                 
  "accept": "*/*",                                                                                                                    
  "cookie": "metabase.TIMEOUT=alive; metabase.DEVICE=3cb1d528-ccfd-4cc3-8be4-09da91649b4d; metabase.SESSION=de45b920-3cb5-4212-b4f0-cf9d9344ffe8",                                                                                                                          
  "accept-encoding": "gzip, deflate",                                                                                                 
  "content-type": "application/json",                                                                                                 
  "content-length": 355                                                                                                               
}                                                                                                                                     
Body: {"engine":"sqlite","name":"sqlite","details":{"db":"./resources/sqlite-fixture.db"},"auto_run_queries":true,"is_full_sync":true,"schedules":{"cache_field_values":{"schedule_day":null,"schedule_frame":null,"schedule_hour":0,"schedule_type":"daily"},"metadata_sync":{"schedule_day":null,"schedule_frame":null,"schedule_hour":null,"schedule_type":"hourly"}}}                                         
                                                                                                                                      
-----------------------------------------------------------                                                                           
                                                                                                                                      
The response we got was:                                                                                                              
                                                                                                                                      
Status: 400 - Bad Request                                                                                                             
Headers: {                                                                                                                            
  "x-frame-options": "DENY",                                                                                                          
  "x-xss-protection": "1; mode=block",                                                                                                
  "last-modified": "Wed, 1 Nov 2023 04:04:28 -0700",                                                                                  
  "strict-transport-security": "max-age=31536000",                                                                                    
  "set-cookie": [                                                                                                                     
    "metabase.TIMEOUT=alive;SameSite=Lax;Path=/;Max-Age=1209600"                                                                      
  ],                                                                                                                                  
  "x-permitted-cross-domain-policies": "none",                                                                                        
  "cache-control": "max-age=0, no-cache, must-revalidate, proxy-revalidate",                                                          
  "x-content-type-options": "nosniff",                                                                                                
  "content-security-policy": "default-src 'none'; script-src 'self' 'unsafe-eval' https://maps.google.com https://accounts.google.com    'sha256-K2AkR/jTLsGV8PyzWha7/ey1iaD9c5jWRYwa++ZlMZc=' 'sha256-ib2/2v5zC6gGM6Ety7iYgBUvpy/caRX9xV/pzzV7hf0=' 'sha256-isH538cVBUY8IMlGYGbWtBwr+cGqkc4mN6nLcA7lUjE='; child-src 'self' https://accounts.google.com; style-src 'self' 'unsafe-inline' https://accounts.google.com; font-src *; img-src * 'self' data:; connect-src 'self' https://accounts.google.com metabase.us10.list-manage.com   ; manifest-src 'self';  frame-ancestors 'none';",                                                                                                  
  "content-type": "application/json;charset=utf-8",                                                                                   
  "expires": "Tue, 03 Jul 2001 06:00:00 GMT",                                                                                         
  "content-length": "62",                                                                                                             
  "server": "Jetty(11.0.14)"                                                                                                          
}                                                                                                                                     
Body: {                                                                                                                               
  "errors": {                                                                                                                         
    "engine": "value must be a valid database engine."                                                                                
  }                                                                                                                                   
}                                                                                                                                     
                                                                                                                                      
                                                                                                                                      
https://on.cypress.io/request                                                                                                         
      at <unknown> (http://localhost:4000/__cypress/runner/cypress_runner.js:139729:80)                                               
      at tryCatcher (http://localhost:4000/__cypress/runner/cypress_runner.js:8914:23)                                                
      at Promise._settlePromiseFromHandler (http://localhost:4000/__cypress/runner/cypress_runner.js:6849:31)                         
      at Promise._settlePromise (http://localhost:4000/__cypress/runner/cypress_runner.js:6906:18)                                    
      at Promise._settlePromise0 (http://localhost:4000/__cypress/runner/cypress_runner.js:6951:10)                                   
      at Promise._settlePromises (http://localhost:4000/__cypress/runner/cypress_runner.js:7031:18)                                   
      at _drainQueueStep (http://localhost:4000/__cypress/runner/cypress_runner.js:3621:12)                                           
      at _drainQueue (http://localhost:4000/__cypress/runner/cypress_runner.js:3614:9)                                                
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4000/__cypress/runner/cypress_runner.js:3630:5)                                                                                                                               
      at Async.drainQueues (http://localhost:4000/__cypress/runner/cypress_runner.js:3500:14)                                         
  From Your Spec Code:                                                                                                                
      at Context.eval (http://localhost:4000/__cypress/tests?p=e2e/snapshot-creators/default.cy.snap.js:43174:12)                     
                                                                                                                                      



  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     10 seconds                                                                       │
  │ Spec Ran:     default.cy.snap.js                                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /home/anton/my/tmp/test-my-clojure/metabase/cypress/screenshots/default.cy.snap.     (1280x720)
     js/snapshots -- withSqlite -- withSqlite (failed).png                                          


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: 3 seconds                                                  

  -  Video output: /home/anton/my/tmp/test-my-clojure/metabase/cypress/videos/default.cy.snap.js.mp4


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  default.cy.snap.js                       00:10        2        1        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:10        2        1        1        -        -  

Cleaning up...
Stopped backend (host=http://localhost:4000, dbFile=/tmp/metabase-test-47755.db)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
