### ISSUE TITLE
"Sync database schema now" fails with error 'Column "fields_hash" of relation "metabase_table" does not exist'

### ISSUE THREAD

**Issue by vpoluyaktov** [metabase/metabase#13461]
**Describe the bug**
When I click on Admin -> Databases -> "Sync Database Schema now" button for any DB the sync job fails with error:
```ERROR sync.util :: Error syncing Fields for Table 'Table 426 'public.business_export_item''
│ hUpdateException: Batch entry 0 UPDATE "metabase_table" SET "fields_hash" = 'qqBaDAlgXOJVE6pEVfikpw==', "updated_at" = now() WHERE "id" = 426 was aborted: ERROR: column "fields_hash" of relation "metabase_table" does not exist
```

**Logs**
```
 10-13 20:34:11 INFO sync.util :: STARTING: Sync metadata for postgres Database 2 'rhapsody-prod'
 10-13 20:34:11 INFO sync.util :: STARTING: step 'sync-timezone' for postgres Database 2 'rhapsody-prod'
 10-13 20:34:11 DEBUG middleware.log :: POST /api/database/2/sync_schema 200 4.5 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (26 idle, 0 queued) (119 total active threads) Queries in flight: 0 (0 queued)
 10-13 20:34:11 INFO sync.util :: FINISHED: step 'sync-timezone' for postgres Database 2 'rhapsody-prod' (13.9 ms)
 10-13 20:34:11 INFO sync.util :: STARTING: step 'sync-tables' for postgres Database 2 'rhapsody-prod'
 10-13 20:34:11 INFO sync-metadata.tables :: Updating description for tables: (Table  'public.client_business_view')
 10-13 20:34:11 INFO sync.util :: FINISHED: step 'sync-tables' for postgres Database 2 'rhapsody-prod' (39.8 ms)
 10-13 20:34:11 INFO sync.util :: STARTING: step 'sync-fields' for postgres Database 2 'rhapsody-prod'
 10-13 20:34:11 ERROR sync.util :: Error syncing Fields for Table 'Table 46 'public.import_session''
 java.sql.BatchUpdateException: Batch entry 0 UPDATE "metabase_table" SET "fields_hash" = 'PjmpHOwKqZXWmuoNHqoFnw==', "updated_at" = now() WHERE "id" = 46 was aborted: ERROR: column "fields_hash" of relation "metabase_table" does not exi
   Position: 29  Call getNextException to see other errors in the batch.
     at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
     at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2234)
     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:510)
     at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:853)
     at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1546)
     at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2544)
     at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:598)
     at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:591)
     at clojure.java.jdbc$db_do_execute_prepared_statement$fn__8608.invoke(jdbc.clj:1057)
     at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
     at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
     at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
     at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
     at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1056)
     at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1042)
     at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1080)
     at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1060)
     at clojure.java.jdbc$execute_BANG_$execute_helper__8676.invoke(jdbc.clj:1464)
     at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1468)
     at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1435)
     at toucan.db$execute_BANG_.invokeStatic(db.clj:427)
     at toucan.db$execute_BANG_.doInvoke(db.clj:422)
     at clojure.lang.RestFn.invoke(RestFn.java:410)
     at toucan.db$update_BANG_.invokeStatic(db.clj:482)
     at toucan.db$update_BANG_.invoke(db.clj:471)
     at toucan.db$update_BANG_.invokeStatic(db.clj:491)
     at toucan.db$update_BANG_.invoke(db.clj:471)
     at toucan.db$update_BANG_.invokeStatic(db.clj:499)
     at toucan.db$update_BANG_.doInvoke(db.clj:471)
     at clojure.lang.RestFn.invoke(RestFn.java:470)
     at metabase.sync.sync_metadata.fields$fn__53963$sync_fields_for_table_BANG___53972$fn__53978$fn__53980.invoke(fields.clj:99)
     at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
     at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
     at metabase.sync.sync_metadata.fields$fn__53963$sync_fields_for_table_BANG___53972$fn__53978.invoke(fields.clj:89)
     at metabase.sync.sync_metadata.fields$fn__53963$sync_fields_for_table_BANG___53972.invoke(fields.clj:83)
     at clojure.core$partial$fn__5839.invoke(core.clj:2624)
     at clojure.core$map$fn__5866.invoke(core.clj:2753)
     at clojure.lang.LazySeq.sval(LazySeq.java:42)
     at clojure.lang.LazySeq.seq(LazySeq.java:51)
     at clojure.lang.RT.seq(RT.java:535)
     at clojure.core$seq__5402.invokeStatic(core.clj:137)
     at clojure.core$filter$fn__5893.invoke(core.clj:2809)
     at clojure.lang.LazySeq.sval(LazySeq.java:42)
     at clojure.lang.LazySeq.seq(LazySeq.java:51)
     at clojure.lang.Cons.next(Cons.java:39)
     at clojure.lang.RT.boundedLength(RT.java:1792)
     at clojure.lang.RestFn.applyTo(RestFn.java:130)
     at clojure.core$apply.invokeStatic(core.clj:667)
     at clojure.core$apply.invoke(core.clj:660)
     at metabase.sync.sync_metadata.fields$fn__54008$sync_fields_BANG___54013$fn__54014.invoke(fields.clj:115)
     at metabase.sync.sync_metadata.fields$fn__54008$sync_fields_BANG___54013.invoke(fields.clj:107)
     at metabase.sync.util$fn__47550$run_step_with_metadata__47555$fn__47559$fn__47561.invoke(util.clj:345)
     at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
     at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
     at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119)
     at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116)
     at metabase.sync.util$fn__47550$run_step_with_metadata__47555$fn__47559.invoke(util.clj:342)
     at metabase.sync.util$fn__47550$run_step_with_metadata__47555.invoke(util.clj:337)
     at metabase.sync.util$fn__47742$run_sync_operation__47747$fn__47748$fn__47749.invoke(util.clj:430)
     at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
     at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
     at clojure.core$reduce.invokeStatic(core.clj:6827)
     at clojure.core$mapv.invokeStatic(core.clj:6903)
     at clojure.core$mapv.invoke(core.clj:6903)
     at metabase.sync.util$fn__47742$run_sync_operation__47747$fn__47748.invoke(util.clj:430)
     at metabase.sync.util$fn__47742$run_sync_operation__47747.invoke(util.clj:424)
     at metabase.sync.sync_metadata$fn__54682$sync_db_metadata_BANG___54687$fn__54688$fn__54689.invoke(sync_metadata.clj:51)
     at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
     at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
     at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145)
     at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
     at clojure.core$partial$fn__5839.invoke(core.clj:2623)
     at metabase.driver$fn__22370.invokeStatic(driver.clj:537)
     at metabase.driver$fn__22370.invoke(driver.clj:537)
     at clojure.lang.MultiFn.invoke(MultiFn.java:239)
     at metabase.sync.util$sync_in_context$fn__47462.invoke(util.clj:138)
     at metabase.sync.util$with_db_logging_disabled$fn__47459.invoke(util.clj:129)
     at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
     at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
     at metabase.sync.util$with_start_and_finish_logging$fn__47448.invoke(util.clj:114)
     at metabase.sync.util$with_sync_events$fn__47443.invoke(util.clj:88)
     at metabase.sync.util$with_duplicate_ops_prevented$fn__47434.invoke(util.clj:67)
     at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164)
     at metabase.sync.util$do_sync_operation.invoke(util.clj:161)
     at metabase.sync.sync_metadata$fn__54682$sync_db_metadata_BANG___54687$fn__54688.invoke(sync_metadata.clj:50)
     at metabase.sync.sync_metadata$fn__54682$sync_db_metadata_BANG___54687.invoke(sync_metadata.clj:47)
     at metabase.api.database$fn__62615$fn__62617.invoke(database.clj:590)
     at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
     at clojure.lang.AFn.call(AFn.java:18)
     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
     at java.base/java.lang.Thread.run(Unknown Source)
 Caused by: org.postgresql.util.PSQLException: ERROR: column "fields_hash" of relation "metabase_table" does not exist
   Position: 29
     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
     ... 91 more
 10-13 20:34:11 ERROR sync.util :: Error syncing Fields for Table 'Table 12 'public.inventory_log''
 java.sql.BatchUpdateException: Batch entry 0 UPDATE "metabase_table" SET "fields_hash" = 'Qnusea2dVBdL74OadOu1dA==', "updated_at" = now() WHERE "id" = 12 was aborted: ERROR: column "fields_hash" of relation "metabase_table" does not exi
   Position: 29  Call getNextException to see other errors in the batch.
     at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
     at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2234)
     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:510)
     at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:853)
     at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1546)
     at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2544)
     at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:598)
     at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:591)
     at clojure.java.jdbc$db_do_execute_prepared_statement$fn__8608.invoke(jdbc.clj:1057)
     at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
     at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
     at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
...
```

We see the same error is repeating for all tables in the DB

**To Reproduce**
1. Go to 'Admin' menu
2. Click on 'Databases' tab
3. Select any database from the list
3. Click on Actions -> "Sync database schema now" button
4. See the metabase log file

**Expected behavior**
Metabase data model is synced with the DB

**Actual result**
We see many errors in the log 'Column "fields_hash" of relation "metabase_table" does not exist'.
Metabase data model is not synced with the DB 

**Screenshots**
![image](https://user-images.githubusercontent.com/1992836/95915037-702b4100-0d5b-11eb-930a-9dde1b4342b2.png)

**Severity**
High.
This bug is blocking us for adding any new DB into our Metabase instance and also we can't sync data model changes to Metabase anymore.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "4.14.138+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "bigquery"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.3"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-06-04",
      "tag": "v1.35.4.1",
      "branch": "enterprise-release-1.35.x",
      "hash": "3f408c2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by vpoluyaktov** [comment]
Upgrading metabase to its latest version (v1.36.7) resolved the problem. 
The errors gone and Metabase Data Model is in sync the DB schema now.
Closing this ticket.
