### ISSUE TITLE
clojure.lang.ExceptionInfo: SSL peer shut down incorrectly slack

### ISSUE THREAD

**Issue by manjeetsinh** [metabase/metabase#13486]
I am not sure this is a bug or misconfiguration but Metabase is bursting the CPU and malfunction the server. So I have checked the logs and the last thing I found is 

`
10-15 04:00:02 ERROR metabot.websocket :: Error connecting websocket:
clojure.lang.ExceptionInfo: SSL peer shut down incorrectly {:url "https://slack.com/api/rtm.start", :request {:query-params {:token "*****"}, :as
        at metabase.integrations.slack$do_slack_request.invokeStatic(slack.clj:65)
        at metabase.integrations.slack$do_slack_request.invoke(slack.clj:47)
        at metabase.integrations.slack$GET.invokeStatic(slack.clj:70)
        at metabase.integrations.slack$GET.doInvoke(slack.clj:67)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.core$partial$fn__5839.invoke(core.clj:2623)
        at clojure.core$comp$fn__5807.invoke(core.clj:2568)
        at metabase.metabot.websocket$connect_websocket_BANG_.invokeStatic(websocket.clj:30)
        at metabase.metabot.websocket$connect_websocket_BANG_.invoke(websocket.clj:29)
        at metabase.metabot.websocket$reopen_websocket_connection_if_needed_BANG_.invokeStatic(websocket.clj:101)
        at metabase.metabot.websocket$reopen_websocket_connection_if_needed_BANG_.invoke(websocket.clj:91)
        at metabase.metabot.websocket$start_websocket_monitor_BANG_$fn__65685.invoke(websocket.clj:116)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:990)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:325)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at clj_http.core$request.invokeStatic(core.clj:626)
        at clj_http.core$request.invoke(core.clj:554)
        at clj_http.core$request.invokeStatic(core.clj:555)
        at clj_http.core$request.invoke(core.clj:554)
        at clojure.lang.Var.invoke(Var.java:384)
        at clj_http.client$wrap_request_timing$fn__58754.invoke(client.clj:1085)
        at clj_http.headers$wrap_header_map$fn__57901.invoke(headers.clj:147)
        at clj_http.client$wrap_query_params$fn__58644.invoke(client.clj:819)
        at clj_http.client$wrap_basic_auth$fn__58650.invoke(client.clj:842)
        at clj_http.client$wrap_oauth$fn__58655.invoke(client.clj:859)
        at clj_http.client$wrap_user_info$fn__58664.invoke(client.clj:879)
        at clj_http.client$wrap_url$fn__58736.invoke(client.clj:1037)
        at clj_http.client$wrap_decompression$fn__58453.invoke(client.clj:420)
        at clj_http.client$wrap_input_coercion$fn__58568.invoke(client.clj:639)
        at clj_http.client$wrap_additional_header_parsing$fn__58593.invoke(client.clj:694)
        at clj_http.client$wrap_output_coercion$fn__58555.invoke(client.clj:583)
        at clj_http.client$wrap_exceptions$fn__58405.invoke(client.clj:254)
        at clj_http.client$wrap_accept$fn__58608.invoke(client.clj:737)
        at clj_http.client$wrap_accept_encoding$fn__58615.invoke(client.clj:759)
        at clj_http.client$wrap_content_type$fn__58602.invoke(client.clj:720)
        at clj_http.client$wrap_form_params$fn__58701.invoke(client.clj:961)
        at clj_http.client$wrap_nested_params$fn__58722.invoke(client.clj:995)
        at clj_http.client$wrap_flatten_nested_params$fn__58731.invoke(client.clj:1019)
        at clj_http.client$wrap_method$fn__58669.invoke(client.clj:895)
        at clj_http.cookies$wrap_cookies$fn__57813.invoke(cookies.clj:131)
        at clj_http.links$wrap_links$fn__58233.invoke(links.clj:63)
        at clj_http.client$wrap_unknown_host$fn__58739.invoke(client.clj:1048)
        at clj_http.client$request_STAR_.invokeStatic(client.clj:1176)
        at clj_http.client$request_STAR_.invoke(client.clj:1169)
        at clj_http.client$get.invokeStatic(client.clj:1182)
        at clj_http.client$get.doInvoke(client.clj:1178)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at metabase.integrations.slack$do_slack_request.invokeStatic(slack.clj:63)
`

It always happens. Metabase utilizes CPU at max and Shuts down the server. 

Configuration:

Using RDS MySQL 8 as my production database and PostgresSQL for Metabase storage

**Comment by flamber** [comment]
Hi @manjeetsinh 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And remember "Diagnostic Info" from Admin > Troubleshooting, and there's probably other information in the logs before that.
If the server shuts down, then there's other problems besides Metabase.
