### ISSUE TITLE
Segment/Metric descriptions don't handle Google Analytics metrics

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#13507]
We don't display a definition for metrics/segments that are against a GA database. There's currently a failure when we try and find a metric in the db for a GA metric string.

![image](https://user-images.githubusercontent.com/691495/96286067-d14a5300-0fad-11eb-9386-ba7314c17049.png)

**Comment by flamber** [comment]
This is now (0.42.3) cause the entire Metrics page (`/admin/datamodel/metrics`) to be blank if you create a Google Analytics metric. Browser console errors:
```
TypeError: Cannot read properties of undefined (reading 'map')
    at Object.M$e [as aggregation] (description.js:247:17)
    at description.js:380:28
    at Array.map (<anonymous>)
    at U$e (description.js:379:6)
    at i.value (MetricItem.jsx:18:25)
    at Ya (react-dom.production.min.js:182:192)
    at Ba (react-dom.production.min.js:181:224)
    at xs (react-dom.production.min.js:263:490)
    at yl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)

Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at Object.M$e [as aggregation] (description.js:247:17)
    at description.js:380:28
    at Array.map (<anonymous>)
    at U$e (description.js:379:6)
    at i.value (MetricItem.jsx:18:25)
    at Ya (react-dom.production.min.js:182:192)
    at Ba (react-dom.production.min.js:181:224)
    at xs (react-dom.production.min.js:263:490)
    at yl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
```

It is still possible to create new metrics by going directly to `/admin/datamodel/metric/create`
And it's possible to edit existing metrics `/admin/datamodel/metric/:id`
And it's also possible to view all metrics via `/reference/metrics`
Though, it requires an API call to retire the metric, so it is possible to view the Data Model Metrics page.
```
await fetch("https://metabase.example.com/api/metric/:id", { "credentials": "include", "headers": { "Content-Type": "application/json" }, "body": "{\"archived\":true,\"revision_message\":\"(Archive)\"}", "method": "PUT", "mode": "cors" });
```
