### ISSUE TITLE
Sync DB Schema on SQL Server DB causes 100% CPU usage for 20 minutes and fails

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#13531]
I wanted to just update the db schema of my SQL Server as I had created a new table. When I press the `sync database schema now` button, it syncs the schema but also analyses and fingerprints (is this normal? I thought analysing and fingerprinting is done with `rescan field values` button). It gets stuck at 20% and CPU usage is at 100% for 20 minutes, runs out of memory and fails.

<details>
<summary>Logs</summary>
<pre>
10-20 02:24:42 INFO sync.util :: STARTING: Sync metadata for sqlserver Database 165 'MSSQL_MB'
10-20 02:24:42 INFO sync.util :: STARTING: step 'sync-timezone' for sqlserver Database 165 'MSSQL_MB'
10-20 02:24:42 INFO sync.util :: FINISHED: step 'sync-timezone' for sqlserver Database 165 'MSSQL_MB' (119.7 ms)
10-20 02:24:42 INFO sync.util :: STARTING: step 'sync-tables' for sqlserver Database 165 'MSSQL_MB'
10-20 02:24:42 INFO sync.util :: FINISHED: step 'sync-tables' for sqlserver Database 165 'MSSQL_MB' (303.8 ms)
10-20 02:24:42 INFO sync.util :: STARTING: step 'sync-fields' for sqlserver Database 165 'MSSQL_MB'
10-20 02:25:19 INFO sync.util :: FINISHED: step 'sync-fields' for sqlserver Database 165 'MSSQL_MB' (36.8 s)
10-20 02:25:19 INFO sync.util :: STARTING: step 'sync-fks' for sqlserver Database 165 'MSSQL_MB'
10-20 02:25:31 INFO sync.util :: FINISHED: step 'sync-fks' for sqlserver Database 165 'MSSQL_MB' (11.6 s)
10-20 02:25:31 INFO sync.util :: STARTING: step 'sync-metabase-metadata' for sqlserver Database 165 'MSSQL_MB'
10-20 02:25:31 INFO sync.util :: FINISHED: step 'sync-metabase-metadata' for sqlserver Database 165 'MSSQL_MB' (251.0 ms)
10-20 02:25:31 INFO sync.util :: FINISHED: Sync metadata for sqlserver Database 165 'MSSQL_MB' (49.1 s)
10-20 02:25:31 INFO sync.util :: STARTING: Analyze data for sqlserver Database 165 'MSSQL_MB'
10-20 02:25:31 INFO sync.util :: STARTING: step 'fingerprint-fields' for sqlserver Database 165 'MSSQL_MB'
10-20 02:25:32 INFO sync.analyze :: fingerprint-fields Analyzed [*****·············································] 😢   10% Table 2,287 'dbo.BC_rr_HOSPITALITY_Australia_Wine'
10-20 02:26:58 INFO sync.analyze :: fingerprint-fields Analyzed [**********········································] 😞   20% Table 2,426 'dbo.bc_rr_COMB_Wine_Import_Country'
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
10-20 02:45:26 ERROR sync.util :: Error fingerprinting Table 2,662 'dbo.BC_tt_gap_mag'
clojure.lang.ExceptionInfo: Error reducing result rows {:type :qp}
        at metabase.query_processor.context.default$default_reducef$fn__37988.invoke(default.clj:61)
        at metabase.query_processor.context.default$default_reducef.invokeStatic(default.clj:58)
        at metabase.query_processor.context.default$default_reducef.invoke(default.clj:49)
        at metabase.query_processor.context$reducef.invokeStatic(context.clj:69)
        at metabase.query_processor.context$reducef.invoke(context.clj:62)
        at metabase.query_processor.context.default$default_runf$respond_STAR___37992.invoke(default.clj:70)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:392)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)
        at metabase.driver.sql_jdbc$fn__73933.invokeStatic(sql_jdbc.clj:49)
        at metabase.driver.sql_jdbc$fn__73933.invoke(sql_jdbc.clj:47)
        at clojure.lang.MultiFn.invoke(MultiFn.java:244)
        at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
        at metabase.query_processor.context$executef.invoke(context.clj:48)
        at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:69)
        at metabase.query_processor.context.default$default_runf.invoke(default.clj:67)
        at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
        at metabase.query_processor.context$runf.invoke(context.clj:39)
        at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
        at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
        at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__45635.invoke(mbql_to_native.clj:26)
        at metabase.query_processor.middleware.check_features$check_features$fn__44911.invoke(check_features.clj:42)
        at metabase.query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__45800.invoke(optimize_datetime_filters.clj:133)
        at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__47328.invoke(wrap_value_literals.clj:137)
        at metabase.query_processor.middleware.annotate$add_column_info$fn__43532.invoke(annotate.clj:574)
        at metabase.query_processor.middleware.permissions$check_query_permissions$fn__44786.invoke(permissions.clj:64)
        at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__46318.invoke(pre_alias_aggregations.clj:40)
        at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__44984.invoke(cumulative_aggregations.clj:61)
        at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__46850.invoke(resolve_joins.clj:183)
        at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__39262.invoke(add_implicit_joins.clj:245)
        at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__45596.invoke(large_int_id.clj:44)
        at metabase.query_processor.middleware.limit$limit$fn__45621.invoke(limit.clj:38)
        at metabase.query_processor.middleware.format_rows$format_rows$fn__45576.invoke(format_rows.clj:81)
        at metabase.query_processor.middleware.desugar$desugar$fn__45050.invoke(desugar.clj:22)
        at metabase.query_processor.middleware.binning$update_binning_strategy$fn__44076.invoke(binning.clj:229)
        at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__44592.invoke(resolve_fields.clj:24)
        at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__38811.invoke(add_dimension_projections.clj:318)
        at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__39018.invoke(add_implicit_clauses.clj:141)
        at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__39411.invoke(add_source_metadata.clj:105)
        at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__46515.invoke(reconcile_breakout_and_order_by_bucketing.clj:98)
        at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__43717.invoke(auto_bucket_datetimes.clj:125)
        at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__44639.invoke(resolve_source_table.clj:46)
        at metabase.query_processor.middleware.parameters$substitute_parameters$fn__46300.invoke(parameters.clj:114)
        at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__44691.invoke(resolve_referenced.clj:80)
        at metabase.query_processor.middleware.expand_macros$expand_macros$fn__45306.invoke(expand_macros.clj:158)
        at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__39442.invoke(add_timezone_info.clj:15)
        at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__47212.invoke(splice_params_in_response.clj:32)
        at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526$fn__46530.invoke(resolve_database_and_driver.clj:33)
        at metabase.driver$do_with_driver.invokeStatic(driver.clj:61)
        at metabase.driver$do_with_driver.invoke(driver.clj:57)
        at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__46526.invoke(resolve_database_and_driver.clj:27)
        at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__45524.invoke(fetch_source_query.clj:267)
        at metabase.query_processor.middleware.store$initialize_store$fn__47221$fn__47222.invoke(store.clj:11)
        at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
        at metabase.query_processor.store$do_with_store.invoke(store.clj:40)
        at metabase.query_processor.middleware.store$initialize_store$fn__47221.invoke(store.clj:10)
        at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__44568.invoke(cache.clj:209)
        at metabase.query_processor.middleware.validate$validate_query$fn__47230.invoke(validate.clj:10)
        at metabase.query_processor.middleware.normalize_query$normalize$fn__45648.invoke(normalize_query.clj:22)
        at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__39280.invoke(add_rows_truncated.clj:36)
        at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__47197.invoke(results_metadata.clj:143)
        at metabase.query_processor.reducible$async_qp$qp_STAR___38074$thunk__38075.invoke(reducible.clj:101)
        at metabase.query_processor.reducible$async_qp$qp_STAR___38074.invoke(reducible.clj:107)
        at metabase.query_processor.reducible$async_qp$qp_STAR___38074.invoke(reducible.clj:94)
        at metabase.query_processor.reducible$sync_qp$qp_STAR___38083$fn__38084.invoke(reducible.clj:129)
        at metabase.query_processor.reducible$sync_qp$qp_STAR___38083.invoke(reducible.clj:128)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.query_processor$process_query.invokeStatic(query_processor.clj:124)
        at metabase.query_processor$process_query.doInvoke(query_processor.clj:118)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.Var.invoke(Var.java:384)
        at metabase.db.metadata_queries$fn__52441$table_rows_sample__52446$fn__52447.invoke(metadata_queries.clj:96)
        at metabase.db.metadata_queries$fn__52441$table_rows_sample__52446.invoke(metadata_queries.clj:92)
        at metabase.sync.analyze.fingerprint$fn__52507$fingerprint_table_BANG___52512$fn__52513.invoke(fingerprint.clj:63)
        at metabase.sync.analyze.fingerprint$fn__52507$fingerprint_table_BANG___52512.invoke(fingerprint.clj:43)
        at metabase.sync.analyze.fingerprint$fn__52680$fingerprint_fields_BANG___52685$fn__52686$fn__52687.invoke(fingerprint.clj:166)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
        at metabase.sync.analyze.fingerprint$fn__52680$fingerprint_fields_BANG___52685$fn__52686.invoke(fingerprint.clj:164)
        at metabase.sync.analyze.fingerprint$fn__52680$fingerprint_fields_BANG___52685.invoke(fingerprint.clj:160)
        at metabase.sync.analyze.fingerprint$fn__52708$fingerprint_fields_for_db_BANG___52713$fn__52714$fn__52715$iter__52716__52720$fn__52721$fn__52722.invoke(fingerprint.clj:184)
        at metabase.sync.analyze.fingerprint$fn__52708$fingerprint_fields_for_db_BANG___52713$fn__52714$fn__52715$iter__52716__52720$fn__52721.invoke(fingerprint.clj:181)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
        at clojure.core$chunk_next.invokeStatic(core.clj:708)
        at clojure.core$reduce1.invokeStatic(core.clj:942)
        at clojure.core$reduce1.invokeStatic(core.clj:934)
        at clojure.core$merge_with.invokeStatic(core.clj:3059)
        at clojure.core$merge_with.doInvoke(core.clj:3051)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.sync.analyze.fingerprint$fn__52708$fingerprint_fields_for_db_BANG___52713$fn__52714$fn__52715.invoke(fingerprint.clj:181)
        at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:46)
        at metabase.query_processor.store$do_with_store.invoke(store.clj:40)
        at metabase.sync.analyze.fingerprint$fn__52708$fingerprint_fields_for_db_BANG___52713$fn__52714.invoke(fingerprint.clj:178)
        at metabase.sync.analyze.fingerprint$fn__52708$fingerprint_fields_for_db_BANG___52713.invoke(fingerprint.clj:172)
        at metabase.sync.analyze$make_analyze_steps$fn__52854.invoke(analyze.clj:106)
        at metabase.sync.util$fn__42295$run_step_with_metadata__42300$fn__42304$fn__42306.invoke(util.clj:345)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
        at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119)
        at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116)
        at metabase.sync.util$fn__42295$run_step_with_metadata__42300$fn__42304.invoke(util.clj:342)
        at metabase.sync.util$fn__42295$run_step_with_metadata__42300.invoke(util.clj:337)
        at metabase.sync.util$fn__42487$run_sync_operation__42492$fn__42493$fn__42494.invoke(util.clj:430)
        at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6827)
        at clojure.core$mapv.invokeStatic(core.clj:6903)
        at clojure.core$mapv.invoke(core.clj:6903)
        at metabase.sync.util$fn__42487$run_sync_operation__42492$fn__42493.invoke(util.clj:430)
        at metabase.sync.util$fn__42487$run_sync_operation__42492.invoke(util.clj:424)
        at metabase.sync.analyze$fn__52866$analyze_db_BANG___52871$fn__52872$fn__52873.invoke(analyze.clj:123)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:142)
        at clojure.core$partial$fn__5839.invoke(core.clj:2623)
        at metabase.driver$fn__22475.invokeStatic(driver.clj:540)
        at metabase.driver$fn__22475.invoke(driver.clj:540)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at metabase.sync.util$sync_in_context$fn__42207.invoke(util.clj:138)
        at metabase.sync.util$with_db_logging_disabled$fn__42204.invoke(util.clj:129)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
        at metabase.sync.util$with_start_and_finish_logging$fn__42193.invoke(util.clj:114)
        at metabase.sync.util$with_sync_events$fn__42188.invoke(util.clj:88)
        at metabase.sync.util$with_duplicate_ops_prevented$fn__42179.invoke(util.clj:67)
        at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164)
        at metabase.sync.util$do_sync_operation.invoke(util.clj:161)
        at metabase.sync.analyze$fn__52866$analyze_db_BANG___52871$fn__52872.invoke(analyze.clj:120)
        at metabase.sync.analyze$fn__52866$analyze_db_BANG___52871.invoke(analyze.clj:115)
        at metabase.api.database$fn__55315$fn__55317.invoke(database.clj:615)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at clojure.lang.PersistentVector.cons(PersistentVector.java:228)
        at clojure.lang.PersistentVector.cons(PersistentVector.java:22)
        at clojure.lang.RT.conj(RT.java:677)
        at clojure.core$conj__5390.invokeStatic(core.clj:85)
        at clojure.core$juxt$fn__5826$fn__5827.invoke(core.clj:2608)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
        at clojure.core$reduce1.invokeStatic(core.clj:942)
        at clojure.core$juxt$fn__5826.invoke(core.clj:2607)
        at metabase.driver.sql_jdbc.execute$row_thunk$row_thunk_STAR___72682.invoke(execute.clj:348)
        at metabase.query_processor.reducible$reducible_rows$reify__38090.reduce(reducible.clj:156)
        at clojure.core$transduce.invokeStatic(core.clj:6883)
        at clojure.core$transduce.invokeStatic(core.clj:6879)
        at clojure.core$transduce.invoke(core.clj:6870)
        at metabase.query_processor.context.default$default_reducef$fn__37988.invoke(default.clj:59)
        at metabase.query_processor.context.default$default_reducef.invokeStatic(default.clj:58)
        at metabase.query_processor.context.default$default_reducef.invoke(default.clj:49)
        at metabase.query_processor.context$reducef.invokeStatic(context.clj:69)
        at metabase.query_processor.context$reducef.invoke(context.clj:62)
        at metabase.query_processor.context.default$default_runf$respond_STAR___37992.invoke(default.clj:70)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:392)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:377)
        at metabase.driver.sql_jdbc$fn__73933.invokeStatic(sql_jdbc.clj:49)
        at metabase.driver.sql_jdbc$fn__73933.invoke(sql_jdbc.clj:47)
        at clojure.lang.MultiFn.invoke(MultiFn.java:244)
        at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
        at metabase.query_processor.context$executef.invoke(context.clj:48)
        at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:69)
        at metabase.query_processor.context.default$default_runf.invoke(default.clj:67)
        at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
        at metabase.query_processor.context$runf.invoke(context.clj:39)
        at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
        at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
10-20 02:45:26 INFO middleware.exceptions :: Request canceled before finishing.
</pre>
</details>

The table `BC_tt_gap_mag` which is in the logs, is not big (74000 records).

- Metabase version: v0.36.6
- Metabase hosting environment: Elastic Beanstalk
- DB: SQL Server
- Metabase internal db: Postgres

**Comment by sbelak** [comment]
This will likely be alleviated by #13325 and fully fixed when the rest of #13288 is implemented.

**Comment by flamber** [comment]
@vvaezian Can you try 0.36.7 - there was another sync fix that went into that version.

**Comment by vvaezian** [comment]
Upgrading to 0.36.7 resolved the issue. Thanks.

**Comment by dpsutton** [comment]
@vvaezian just to get a sense of how successful this change might be, did `'dbo.BC_tt_gap_mag'` have large text fields in it? Just wondering how common this might be. I think we've also seen an instance of a table with emails in it which this also should hopefully fix.

**Comment by vvaezian** [comment]
@dpsutton Sorry for the late reply, I just saw you msg.
The longest value in that table is 121 characters in a column with dtype `nvarchar(1200)` .

**Comment by dpsutton** [comment]
surprising to me. thanks so much @vvaezian feedback is so very helpful.
