### ISSUE TITLE
Clear _future_ fingerprints

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#13542]
similar but simpler than the full generality of https://github.com/metabase/metabase/issues/12816 .

On downgrading, newer fingerprints can violate the schema of the current fingerprint. One possible and easy suggestion is to mark fingerprints with a version higher than the max fingerprint version to be wiped and refingerprinted.

Motivating example: version 5 of fingerprints adds a `:percent-state` fingerprint to identify state columns based on values rather than column name. If you downgrade back to 36.7 (introduced in 36.8 rc) then the mere presence of these newer fingerprints breaks queries:

```
metabase.sync.analyze.query_results$fn__47102$col__GT_ResultColumnMetadata__47107.invoke(query_results.clj:56) at 
metabase.sync.analyze.query_results$insights_rf$iter__47122__47126$fn__47127$fn__47134.invoke(query_results.clj:73) at 
metabase.sync.analyze.query_results$insights_rf$iter__47122__47126$fn__47127.invoke(query_results.clj:72) at 
clojure.lang.LazySeq.sval(LazySeq.java:42) at clojure.lang.LazySeq.seq(LazySeq.java:51) at 
clojure.lang.RT.seq(RT.java:535) at clojure.core$seq__5402.invokeStatic(core.clj:137) at 
clojure.core$seq__5402.invoke(core.clj:137) at 
metabase.sync.analyze.query_results$insights_rf$iter__47143__47147$fn__47148.invoke(query_results.clj:79) at 
clojure.lang.LazySeq.sval(LazySeq.java:42) at clojure.lang.LazySeq.seq(LazySeq.java:51) at 
clojure.lang.RT.seq(RT.java:535) at clojure.core$seq__5402.invokeStatic(core.clj:137) at 
clojure.core$apply.invokeStatic(core.clj:660) at clojure.core$apply.invoke(core.clj:660) at 
metabase.sync.analyze.query_results$insights_rf.invokeStatic(query_results.clj:79) at 
metabase.sync.analyze.query_results$insights_rf.invoke(query_results.clj:66) at 
...
```

**Comment by dpsutton** [comment]
closing in favor of https://github.com/metabase/metabase/issues/13543
