### ISSUE TITLE
mysql init fail

### ISSUE THREAD

**Issue by endend20000** [metabase/metabase#13605]
lauch the project using mysql  but fail. the mysql version is 8 metabase version is 0.37.0.2

**Logs**
2020-10-27 23:27:03,920 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::167::walterl, camsaul failed.  Error: (conn=7441676) Invalid default value for 'created_at' [Failed SQL: CREATE TABLE bi2.native_query_snippet (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(254) NOT NULL COMMENT 'Name of the query snippet', `description` TEXT NULL, content TEXT NOT NULL COMMENT 'Raw query snippet', creator_id INT NOT NULL, archived BIT(1) DEFAULT 0 NOT NULL, created_at timestamp(6) DEFAULT NOW() NOT NULL, updated_at timestamp(6) DEFAULT NOW() NOT NULL, CONSTRAINT PK_NATIVE_QUERY_SNIPPET PRIMARY KEY (id), CONSTRAINT fk_snippet_creator_id FOREIGN KEY (creator_id) REFERENCES bi2.core_user(id) ON DELETE CASCADE, UNIQUE (name)) COMMENT='Query snippets (raw text) to be substituted in native queries']
2020-10-27 23:27:04,080 WARN metabase.util :: auto-retry metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__20970@659f676f: Migration failed for change set migrations/000_migrations.yaml::167::walterl, camsaul:
     Reason: liquibase.exception.DatabaseException: (conn=7441676) Invalid default value for 'created_at' [Failed SQL: CREATE TABLE bi2.native_query_snippet (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(254) NOT NULL COMMENT 'Name of the query snippet', `description` TEXT NULL, content TEXT NOT NULL COMMENT 'Raw query snippet', creator_id INT NOT NULL, archived BIT(1) DEFAULT 0 NOT NULL, created_at timestamp(6) DEFAULT NOW() NOT NULL, updated_at timestamp(6) DEFAULT NOW() NOT NULL, CONSTRAINT PK_NATIVE_QUERY_SNIPPET PRIMARY KEY (id), CONSTRAINT fk_snippet_creator_id FOREIGN KEY (creator_id) REFERENCES bi2.core_user(id) ON DELETE CASCADE, UNIQUE (name)) COMMENT='Query snippets (raw text) to be substituted in native queries']
2020-10-27 23:27:05,289 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2020-10-27 23:27:05,289 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2020-10-27 23:27:05,474 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::167::walterl, camsaul failed.  Error: (conn=7441676) Invalid default value for 'created_at' [Failed SQL: CREATE TABLE bi2.native_query_snippet (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(254) NOT NULL COMMENT 'Name of the query snippet', `description` TEXT NULL, content TEXT NOT NULL COMMENT 'Raw query snippet', creator_id INT NOT NULL, archived BIT(1) DEFAULT 0 NOT NULL, created_at timestamp(6) DEFAULT NOW() NOT NULL, updated_at timestamp(6) DEFAULT NOW() NOT NULL, CONSTRAINT PK_NATIVE_QUERY_SNIPPET PRIMARY KEY (id), CONSTRAINT fk_snippet_creator_id FOREIGN KEY (creator_id) REFERENCES bi2.core_user(id) ON DELETE CASCADE, UNIQUE (name)) COMMENT='Query snippets (raw text) to be substituted in native queries']
2020-10-27 23:27:05,663 WARN metabase.util :: auto-retry metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__20970@659f676f: Migration failed for change set migrations/000_migrations.yaml::167::walterl, camsaul:
     Reason: liquibase.exception.DatabaseException: (conn=7441676) Invalid default value for 'created_at' [Failed SQL: CREATE TABLE bi2.native_query_snippet (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(254) NOT NULL COMMENT 'Name of the query snippet', `description` TEXT NULL, content TEXT NOT NULL COMMENT 'Raw query snippet', creator_id INT NOT NULL, archived BIT(1) DEFAULT 0 NOT NULL, created_at timestamp(6) DEFAULT NOW() NOT NULL, updated_at timestamp(6) DEFAULT NOW() NOT NULL, CONSTRAINT PK_NATIVE_QUERY_SNIPPET PRIMARY KEY (id), CONSTRAINT fk_snippet_creator_id FOREIGN KEY (creator_id) REFERENCES bi2.core_user(id) ON DELETE CASCADE, UNIQUE (name)) COMMENT='Query snippets (raw text) to be substituted in native queries']
2020-10-27 23:27:07,302 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2020-10-27 23:27:07,302 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2020-10-27 23:27:07,468 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::167::walterl, camsaul failed.  Error: (conn=7441676) Invalid default value for 'created_at' [Failed SQL: CREATE TABLE bi2.native_query_snippet (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(254) NOT NULL COMMENT 'Name of the query snippet', `description` TEXT NULL, content TEXT NOT NULL COMMENT 'Raw query snippet', creator_id INT NOT NULL, archived BIT(1) DEFAULT 0 NOT NULL, created_at timestamp(6) DEFAULT NOW() NOT NULL, updated_at timestamp(6) DEFAULT NOW() NOT NULL, CONSTRAINT PK_NATIVE_QUERY_SNIPPET PRIMARY KEY (id), CONSTRAINT fk_snippet_creator_id FOREIGN KEY (creator_id) REFERENCES bi2.core_user(id) ON DELETE CASCADE, UNIQUE (name)) COMMENT='Query snippets (raw text) to be substituted in native queries']
2020-10-27 23:27:07,835 WARN metabase.util :: auto-retry metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__20970@659f676f: Migration failed for change set migrations/000_migrations.yaml::167::walterl, camsaul:
     Reason: liquibase.exception.DatabaseException: (conn=7441676) Invalid default value for 'created_at' [Failed SQL: CREATE TABLE bi2.native_query_snippet (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(254) NOT NULL COMMENT 'Name of the query snippet', `description` TEXT NULL, content TEXT NOT NULL COMMENT 'Raw query snippet', creator_id INT NOT NULL, archived BIT(1) DEFAULT 0 NOT NULL, created_at timestamp(6) DEFAULT NOW() NOT NULL, updated_at timestamp(6) DEFAULT NOW() NOT NULL, CONSTRAINT PK_NATIVE_QUERY_SNIPPET PRIMARY KEY (id), CONSTRAINT fk_snippet_creator_id FOREIGN KEY (creator_id) REFERENCES bi2.core_user(id) ON DELETE CASCADE, UNIQUE (name)) COMMENT='Query snippets (raw text) to be substituted in native queries']
2020-10-27 23:27:09,143 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2020-10-27 23:27:09,144 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2020-10-27 23:27:09,328 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::167::walterl, camsaul failed.  Error: (conn=7441676) Invalid default value for 'created_at' [Failed SQL: CREATE TABLE bi2.native_query_snippet (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(254) NOT NULL COMMENT 'Name of the query snippet', `description` TEXT NULL, content TEXT NOT NULL COMMENT 'Raw query snippet', creator_id INT NOT NULL, archived BIT(1) DEFAULT 0 NOT NULL, created_at timestamp(6) DEFAULT NOW() NOT NULL, updated_at timestamp(6) DEFAULT NOW() NOT NULL, CONSTRAINT PK_NATIVE_QUERY_SNIPPET PRIMARY KEY (id), CONSTRAINT fk_snippet_creator_id FOREIGN KEY (creator_id) REFERENCES bi2.core_user(id) ON DELETE CASCADE, UNIQUE (name)) COMMENT='Query snippets (raw text) to be substituted in native queries']
2020-10-27 23:27:09,973 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::167::walterl, camsaul:
     Reason: liquibase.exception.DatabaseException: (conn=7441676) Invalid default value for 'created_at' [Failed SQL: CREATE TABLE bi2.native_query_snippet (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(254) NOT NULL COMMENT 'Name of the query snippet', `description` TEXT NULL, content TEXT NOT NULL COMMENT 'Raw query snippet', creator_id INT NOT NULL, archived BIT(1) DEFAULT 0 NOT NULL, created_at timestamp(6) DEFAULT NOW() NOT NULL, updated_at timestamp(6) DEFAULT NOW() NOT NULL, CONSTRAINT PK_NATIVE_QUERY_SNIPPET PRIMARY KEY (id), CONSTRAINT fk_snippet_creator_id FOREIGN KEY (creator_id) REFERENCES bi2.core_user(id) ON DELETE CASCADE, UNIQUE (name)) COMMENT='Query snippets (raw text) to be substituted in native queries']
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637) ~[metabase.jar:?]
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53) ~[metabase.jar:?]
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83) ~[metabase.jar:?]
        at liquibase.Liquibase.update(Liquibase.java:202) ~[metabase.jar:?]
        at liquibase.Liquibase.update(Liquibase.java:179) ~[metabase.jar:?]
        at liquibase.Liquibase.update(Liquibase.java:175) ~[metabase.jar:?]
        at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__20970.invoke(liquibase.clj:125) ~[metabase.jar:?]
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:437) ~[metabase.jar:?]
        at metabase.util$do_with_auto_retries.invoke(util.clj:429) ~[metabase.jar:?]
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:444) ~[metabase.jar:?]
        at metabase.util$do_with_auto_retries.invoke(util.clj:429) ~[metabase.jar:?]
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:444) ~[metabase.jar:?]
        at metabase.util$do_with_auto_retries.invoke(util.clj:429) ~[metabase.jar:?]
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:444) ~[metabase.jar:?]
        at metabase.util$do_with_auto_retries.invoke(util.clj:429) ~[metabase.jar:?]
        at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:125) ~[metabase.jar:?]
        at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:113) ~[metabase.jar:?]
        at metabase.db$migrate_BANG_$fn__21754$fn__21755.invoke(db.clj:208) ~[metabase.jar:?]
        at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:37) ~[metabase.jar:?]
        at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:29) ~[metabase.jar:?]
        at metabase.db$migrate_BANG_$fn__21754.invoke(db.clj:203) ~[metabase.jar:?]
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807) ~[metabase.jar:?]
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776) ~[metabase.jar:?]
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852) ~[metabase.jar:?]
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776) ~[metabase.jar:?]
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789) ~[metabase.jar:?]
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776) ~[metabase.jar:?]
        at metabase.db$migrate_BANG_.invokeStatic(db.clj:194) ~[metabase.jar:?]
        at metabase.db$migrate_BANG_.invoke(db.clj:173) ~[metabase.jar:?]
        at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:336) ~[metabase.jar:?]
        at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:330) ~[metabase.jar:?]
        at metabase.db$setup_db_BANG__STAR_$fn__21837.invoke(db.clj:353) ~[metabase.jar:?]
        at metabase.util$do_with_us_locale.invokeStatic(util.clj:670) ~[metabase.jar:?]
        at metabase.util$do_with_us_locale.invoke(util.clj:656) ~[metabase.jar:?]
        at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:351) ~[metabase.jar:?]
        at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:346) ~[metabase.jar:?]
        at metabase.db$setup_db_from_env_BANG_.invokeStatic(db.clj:365) ~[metabase.jar:?]
        at metabase.db$setup_db_from_env_BANG_.invoke(db.clj:358) ~[metabase.jar:?]
        at metabase.db$setup_db_BANG_$fn__21842.invoke(db.clj:375) ~[metabase.jar:?]
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:373) ~[metabase.jar:?]
        at metabase.db$setup_db_BANG_.invoke(db.clj:368) ~[metabase.jar:?]
        at metabase.core$init_BANG_.invokeStatic(core.clj:96) ~[metabase.jar:?]
        at metabase.core$init_BANG_.invoke(core.clj:75) ~[metabase.jar:?]
        at metabase.core$start_normally.invokeStatic(core.clj:140) [metabase.jar:?]
        at metabase.core$start_normally.invoke(core.clj:134) [metabase.jar:?]
        at metabase.core$_main.invokeStatic(core.clj:173) [metabase.jar:?]
        at metabase.core$_main.doInvoke(core.clj:167) [metabase.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:397) [metabase.jar:?]
        at clojure.lang.AFn.applyToHelper(AFn.java:152) [metabase.jar:?]
        at clojure.lang.RestFn.applyTo(RestFn.java:132) [metabase.jar:?]
        at metabase.core.main(Unknown Source) [metabase.jar:?]
Caused by: liquibase.exception.DatabaseException: (conn=7441676) Invalid default value for 'created_at' [Failed SQL: CREATE TABLE bi2.native_query_snippet (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(254) NOT NULL COMMENT 'Name of the query snippet', `description` TEXT NULL, content TEXT NOT NULL COMMENT 'Raw query snippet', creator_id INT NOT NULL, archived BIT(1) DEFAULT 0 NOT NULL, created_at timestamp(6) DEFAULT NOW() NOT NULL, updated_at timestamp(6) DEFAULT NOW() NOT NULL, CONSTRAINT PK_NATIVE_QUERY_SNIPPET PRIMARY KEY (id), CONSTRAINT fk_snippet_creator_id FOREIGN KEY (creator_id) REFERENCES bi2.core_user(id) ON DELETE CASCADE, UNIQUE (name)) COMMENT='Query snippets (raw text) to be substituted in native queries']
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356) ~[metabase.jar:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57) ~[metabase.jar:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125) ~[metabase.jar:?]
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229) ~[metabase.jar:?]
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211) ~[metabase.jar:?]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600) ~[metabase.jar:?]
        ... 50 more
Caused by: java.sql.SQLSyntaxErrorException: (conn=7441676) Invalid default value for 'created_at'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[metabase.jar:?]
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153) ~[metabase.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274) ~[metabase.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363) ~[metabase.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:501) ~[metabase.jar:?]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352) ~[metabase.jar:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57) ~[metabase.jar:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125) ~[metabase.jar:?]
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229) ~[metabase.jar:?]
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211) ~[metabase.jar:?]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600) ~[metabase.jar:?]
        ... 50 more
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Invalid default value for 'created_at'
        at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34) ~[metabase.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194) ~[metabase.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:262) ~[metabase.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357) ~[metabase.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:501) ~[metabase.jar:?]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352) ~[metabase.jar:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57) ~[metabase.jar:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125) ~[metabase.jar:?]
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229) ~[metabase.jar:?]
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211) ~[metabase.jar:?]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600) ~[metabase.jar:?]
        ... 50 more
Caused by: java.sql.SQLException: Invalid default value for 'created_at'
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1688) ~[metabase.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1550) ~[metabase.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1513) ~[metabase.jar:?]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256) ~[metabase.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357) ~[metabase.jar:?]
        at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:501) ~[metabase.jar:?]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352) ~[metabase.jar:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57) ~[metabase.jar:?]
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125) ~[metabase.jar:?]
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229) ~[metabase.jar:?]
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211) ~[metabase.jar:?]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600) ~[metabase.jar:?]
        ... 50 more
2020-10-27 23:27:09,985 INFO metabase.core :: Metabase Shutting Down ...
2020-10-27 23:27:09,985 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2020-10-27 23:27:09,998 INFO metabase.core :: Metabase Shutdown COMPLETE

**To Reproduce**
lauch metabase in mysql which version is 8

**Comment by flamber** [comment]
Hi @endend20000 
I cannot reproduce. Please post your MySQL version information `SHOW VARIABLES LIKE "%version%";`

**Comment by endend20000** [comment]
immediate_server_version	999999
innodb_version	8.0.16
original_server_version	999999
protocol_version	10
slave_type_conversions	
tls_version	TLSv1,TLSv1.1,TLSv1.2
version	8.0.16
version_comment	Source distribution
version_compile_machine	x86_64
version_compile_os	Linux
version_compile_zlib	1.2.11

**Comment by flamber** [comment]
@endend20000 
I cannot reproduce on `Server version: 8.0.22 MySQL Community Server - GPL`
I don't know which version you're using, but try upgrading to latest MySQL release.
