### ISSUE TITLE
ERROR driver.util :: Database connection error java.util.concurrent.TimeoutException: Timed out after 5.0 s

### ISSUE THREAD

**Issue by floriankapaun** [metabase/metabase#13755]
I'm hosting Metabase on my web server for a few months now. Since yesterday the service isn't running anymore. I haven't accessed the server in all this time, so I haven't made any manual changes that could explain the behavior.

I'm using Metabase in combination with MariaDB.

If I'm trying to re-start metabase I am getting this error: `ERROR driver.util :: Database connection error java.util.concurrent.TimeoutException: Timed out after 5.0 s`

See the complete logs:

```WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2020-11-11 20:02:21,266 INFO metabase.util :: Maximum memory available to JVM: 6.3 GB
2020-11-11 20:06:19,885 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2020-11-11 20:15:58,634 INFO metabase.core :: 
Metabase v0.37.0.2 (ba7be09 release-x.37.x) 

Copyright © 2020 Metabase, Inc. 

Metabase Enterprise Edition extensions are NOT PRESENT.
2020-11-11 20:16:00,512 WARN metabase.core :: WARNING: You have enabled namespace tracing, which could log sensitive information like db passwords.
2020-11-11 20:16:00,513 INFO metabase.core :: Starting Metabase in STANDALONE mode
2020-11-11 20:16:06,315 INFO metabase.server :: Launching Embedded Jetty Webserver with config: 
 {:port 3000}

2020-11-11 20:16:11,626 INFO metabase.core :: Starting Metabase version v0.37.0.2 (ba7be09 release-x.37.x) ...
2020-11-11 20:16:12,342 INFO metabase.core :: System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "14.0.2+12",
 "java.vendor" "Red Hat, Inc.",
 "java.vendor.url" "https://www.redhat.com/",
 "java.version" "14.0.2",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "14.0.2+12",
 "os.name" "Linux",
 "os.version" "3.10.0-1127.19.1.el7.x86_64",
 "user.language" "en",
 "user.timezone" "Europe/Berlin"}

2020-11-11 20:16:12,347 INFO metabase.plugins :: Loading plugins in /var/www/virtual/kapaun/metabase.boxbote.de/plugins...
2020-11-11 20:16:27,111 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
2020-11-11 20:16:41,744 INFO driver.impl :: Registered abstract driver :sql  🚚
Load driver :sql took 10.9 s
2020-11-11 20:16:42,062 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
Load driver :sql-jdbc took 15.3 s
2020-11-11 20:16:42,389 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 🚚
2020-11-11 20:16:42,563 INFO plugins.dependencies :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
2020-11-11 20:16:42,714 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
2020-11-11 20:16:42,717 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Google Analytics Driver"]
2020-11-11 20:16:42,736 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
2020-11-11 20:16:42,737 INFO driver.impl :: Registered driver :druid  🚚
2020-11-11 20:16:42,764 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
2020-11-11 20:16:43,097 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
Load driver :postgres took 1.9 s
2020-11-11 20:16:44,645 INFO driver.impl :: Registered driver :redshift (parents: [:postgres]) 🚚
2020-11-11 20:16:45,601 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
2020-11-11 20:16:45,603 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc]) 🚚
2020-11-11 20:16:45,604 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
2020-11-11 20:16:45,605 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 🚚
2020-11-11 20:16:45,616 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
2020-11-11 20:16:45,618 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 🚚
2020-11-11 20:16:45,636 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
2020-11-11 20:16:45,637 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚
2020-11-11 20:16:45,708 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.

2020-11-11 20:16:45,710 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
2020-11-11 20:16:45,712 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Oracle Driver" "Metabase Google Analytics Driver"]
2020-11-11 20:16:45,730 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

2020-11-11 20:16:45,731 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
2020-11-11 20:16:45,732 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver" "Metabase Google Analytics Driver"]
2020-11-11 20:16:45,743 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
2020-11-11 20:16:45,746 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
2020-11-11 20:16:45,748 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver" "Metabase BigQuery Driver" "Metabase Google Analytics Driver"]
2020-11-11 20:16:45,761 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto...
2020-11-11 20:16:45,763 INFO driver.impl :: Registered driver :presto (parents: [:sql]) 🚚
2020-11-11 20:16:45,789 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
2020-11-11 20:16:45,791 INFO driver.impl :: Registered driver :mongo  🚚
2020-11-11 20:16:45,801 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :google...
2020-11-11 20:16:45,802 INFO driver.impl :: Registered abstract driver :google  🚚
2020-11-11 20:16:45,805 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
2020-11-11 20:16:45,806 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
2020-11-11 20:16:45,807 DEBUG plugins.initialize :: Dependencies satisfied; these plugins will now be loaded: ["Metabase Google Analytics Driver" "Metabase BigQuery Driver"]
2020-11-11 20:16:45,808 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
2020-11-11 20:16:45,809 INFO driver.impl :: Registered driver :googleanalytics (parents: [:google]) 🚚
2020-11-11 20:16:45,812 WARN plugins.lazy-loaded-driver :: Warning: plugin manifest for :bigquery does not include connection properties
2020-11-11 20:16:45,813 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery...
2020-11-11 20:16:45,815 INFO driver.impl :: Registered driver :bigquery (parents: [:sql :google]) 🚚
2020-11-11 20:16:45,993 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
2020-11-11 20:16:47,594 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
2020-11-11 20:16:49,434 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2020-11-11 20:16:49,572 INFO metabase.db :: Verifying mysql Database Connection ...
2020-11-11 20:16:49,707 INFO driver.impl :: Initializing driver :sql...
2020-11-11 20:16:49,742 INFO driver.impl :: Initializing driver :sql-jdbc...
2020-11-11 20:16:49,743 INFO driver.impl :: Initializing driver :mysql...
2020-11-11 20:16:54,749 ERROR driver.util :: Database connection error
java.util.concurrent.TimeoutException: Timed out after 5.0 s
	at metabase.util$deref_with_timeout.invokeStatic(util.clj:315) ~[metabase.jar:?]
	at metabase.util$deref_with_timeout.invoke(util.clj:307) ~[metabase.jar:?]
	at metabase.util$do_with_timeout.invokeStatic(util.clj:321) ~[metabase.jar:?]
	at metabase.util$do_with_timeout.invoke(util.clj:318) ~[metabase.jar:?]
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:34) [metabase.jar:?]
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:23) [metabase.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:442) [metabase.jar:?]
	at clojure.lang.Var.invoke(Var.java:393) [metabase.jar:?]
	at metabase.db$fn__21789$verify_db_connection__21798$fn__21801$fn__21802.invoke(db.clj:316) [metabase.jar:?]
	at metabase.db$fn__21789$verify_db_connection__21798$fn__21801.invoke(db.clj:315) [metabase.jar:?]
	at metabase.db$fn__21789$verify_db_connection__21798.invoke(db.clj:307) [metabase.jar:?]
	at metabase.db$fn__21789$verify_db_connection__21798$fn__21799.invoke(db.clj:310) [metabase.jar:?]
	at metabase.db$fn__21789$verify_db_connection__21798.invoke(db.clj:307) [metabase.jar:?]
	at metabase.db$setup_db_BANG__STAR_$fn__21837.invoke(db.clj:352) [metabase.jar:?]
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:670) [metabase.jar:?]
	at metabase.util$do_with_us_locale.invoke(util.clj:656) [metabase.jar:?]
	at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:351) [metabase.jar:?]
	at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:346) [metabase.jar:?]
	at metabase.db$setup_db_from_env_BANG_.invokeStatic(db.clj:365) [metabase.jar:?]
	at metabase.db$setup_db_from_env_BANG_.invoke(db.clj:358) [metabase.jar:?]
	at metabase.db$setup_db_BANG_$fn__21842.invoke(db.clj:375) [metabase.jar:?]
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:373) [metabase.jar:?]
	at metabase.db$setup_db_BANG_.invoke(db.clj:368) [metabase.jar:?]
	at metabase.core$init_BANG_.invokeStatic(core.clj:96) [metabase.jar:?]
	at metabase.core$init_BANG_.invoke(core.clj:75) [metabase.jar:?]
	at metabase.core$start_normally.invokeStatic(core.clj:140) [metabase.jar:?]
	at metabase.core$start_normally.invoke(core.clj:134) [metabase.jar:?]
	at metabase.core$_main.invokeStatic(core.clj:173) [metabase.jar:?]
	at metabase.core$_main.doInvoke(core.clj:167) [metabase.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:397) [metabase.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:152) [metabase.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) [metabase.jar:?]
	at metabase.core.main(Unknown Source) [metabase.jar:?]
2020-11-11 20:16:55,391 ERROR metabase.core :: Metabase Initialization FAILED
java.lang.Exception: Timed out after 5.0 s
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:40) ~[metabase.jar:?]
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:23) ~[metabase.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:442) ~[metabase.jar:?]
	at clojure.lang.Var.invoke(Var.java:393) ~[metabase.jar:?]
	at metabase.db$fn__21789$verify_db_connection__21798$fn__21801$fn__21802.invoke(db.clj:316) ~[metabase.jar:?]
	at metabase.db$fn__21789$verify_db_connection__21798$fn__21801.invoke(db.clj:315) ~[metabase.jar:?]
	at metabase.db$fn__21789$verify_db_connection__21798.invoke(db.clj:307) ~[metabase.jar:?]
	at metabase.db$fn__21789$verify_db_connection__21798$fn__21799.invoke(db.clj:310) ~[metabase.jar:?]
	at metabase.db$fn__21789$verify_db_connection__21798.invoke(db.clj:307) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG__STAR_$fn__21837.invoke(db.clj:352) ~[metabase.jar:?]
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:670) ~[metabase.jar:?]
	at metabase.util$do_with_us_locale.invoke(util.clj:656) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:351) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:346) ~[metabase.jar:?]
	at metabase.db$setup_db_from_env_BANG_.invokeStatic(db.clj:365) ~[metabase.jar:?]
	at metabase.db$setup_db_from_env_BANG_.invoke(db.clj:358) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG_$fn__21842.invoke(db.clj:375) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:373) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG_.invoke(db.clj:368) ~[metabase.jar:?]
	at metabase.core$init_BANG_.invokeStatic(core.clj:96) ~[metabase.jar:?]
	at metabase.core$init_BANG_.invoke(core.clj:75) ~[metabase.jar:?]
	at metabase.core$start_normally.invokeStatic(core.clj:140) [metabase.jar:?]
	at metabase.core$start_normally.invoke(core.clj:134) [metabase.jar:?]
	at metabase.core$_main.invokeStatic(core.clj:173) [metabase.jar:?]
	at metabase.core$_main.doInvoke(core.clj:167) [metabase.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:397) [metabase.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:152) [metabase.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) [metabase.jar:?]
	at metabase.core.main(Unknown Source) [metabase.jar:?]
Caused by: java.util.concurrent.TimeoutException: Timed out after 5.0 s
	at metabase.util$deref_with_timeout.invokeStatic(util.clj:315) ~[metabase.jar:?]
	at metabase.util$deref_with_timeout.invoke(util.clj:307) ~[metabase.jar:?]
	at metabase.util$do_with_timeout.invokeStatic(util.clj:321) ~[metabase.jar:?]
	at metabase.util$do_with_timeout.invoke(util.clj:318) ~[metabase.jar:?]
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:34) ~[metabase.jar:?]
	... 28 more
2020-11-11 20:16:55,584 INFO metabase.core :: Metabase Shutting Down ...
2020-11-11 20:16:55,586 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2020-11-11 20:16:56,247 INFO metabase.core :: Metabase Shutdown COMPLETE
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
```

As you can see from the version number I've already tried updating metabase. I've been using v0.36.3 before but the version change made no difference.

The DB is still running and accessible, so I have no idea how to fix this problem.

If there is any further helpful information I should provide for you to give me a helpful hint, please tell me. 🙂

**Comment by flamber** [comment]
Hi @floriankapaun 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It is most likely a network issue between the instance running Metabase and the instance running MariaDB - DNS, firewall, etc.
