### ISSUE TITLE
[0.37.2] Embedded dashboard - Chain filter error

### ISSUE THREAD

**Issue by mdz0r** [metabase/metabase#13858]
**Describe the bug**
Embedded dashboards field filters won't work, values in the list won't load but my filters are working in the MB dashboards.

**Logs**

```
2020-11-20 17:05:18,197 ERROR api.embed :: Chain filter error
{:allowed-param-slugs {:date_de_facture "enabled", :adherent "locked", :type_de_commande "enabled", :canal_de_commande "enabled", :type_de_vente "enabled"},
 :param-id "78e1b24e",
 :constraints {996 ["188"], 1068 ["188"], 1066 "2020-01-01~2020-06-30"},
 :id->slug {"b60929b1" "date_de_facture", "da020ea1" "adherent", "78e1b24e" "type_de_commande", "4be2c85b" "canal_de_commande", "adc94dbb" "type_de_vente"},
 :mbql-query
 {:database 6,
  :type :query,
  :query
  {:source-table 123,
   :breakout [[:field-id 1139]],
   :limit 1000,
   :joins
   ({:source-table 120, :condition [:= [:field-id 1138] [:joined-field "table_120" [:field-id 1053]]], :alias "table_120"}
    {:source-table 122, :condition [:= [:joined-field "table_120" [:field-id 1068]] [:joined-field "table_122" [:field-id 996]]], :alias "table_122"}),
   :filter
   [:and [:= [:joined-field "table_122" [:field-id 996]] "188"] [:= [:joined-field "table_120" [:field-id 1068]] "188"] [:= [:joined-field "table_120" [:field-id 1066]] "2020-01-01~2020-06-30"]]}},
 :dashboard-params
 ({:name "DATE DE FACTURE", :slug "date_de_facture", :id "b60929b1", :type "date/range", :default "2019-01-01~2019-01-31"}
  {:name "ADHERENT", :slug "adherent", :id "da020ea1", :type "id", :default ["198"]}
  {:name "TYPE DE COMMANDE", :slug "type_de_commande", :id "78e1b24e", :type "category"}
  {:name "CANAL DE COMMANDE", :slug "canal_de_commande", :id "4be2c85b", :type "category"}
  {:name "TYPE DE VENTE", :slug "type_de_vente", :id "adc94dbb", :type "category"}),
 :slug->id {"date_de_facture" "b60929b1", "adherent" "da020ea1", "type_de_commande" "78e1b24e", "canal_de_commande" "4be2c85b", "type_de_vente" "adc94dbb"},
 :dashboard-id 28,
 :token-params {:adherent ["188"], :date_de_facture "2020-01-01~2020-06-30"},
 :param-slug "type_de_commande",
 :field-id 1139,
 :merged-id-params {"da020ea1" ["188"], "b60929b1" "2020-01-01~2020-06-30"}}
clojure.lang.ExceptionInfo: Erreur dexécution dune requête de chaîne de filtre
        at metabase.api.embed$chain_filter.invokeStatic(embed.clj:508) ~[metabase.jar:?]
        at metabase.api.embed$chain_filter.invoke(embed.clj:480) ~[metabase.jar:?]
        at metabase.api.embed$fn__62067.invokeStatic(embed.clj:524) ~[metabase.jar:?]
        at metabase.api.embed$fn__62067.invoke(embed.clj:521) ~[metabase.jar:?]
        at compojure.core$wrap_response$fn__1993.invoke(core.clj:160) ~[metabase.jar:?]
        at compojure.core$wrap_route_middleware$fn__1977.invoke(core.clj:132) ~[metabase.jar:?]
        at compojure.core$wrap_route_info$fn__1982.invoke(core.clj:139) ~[metabase.jar:?]
        at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:151) ~[metabase.jar:?]
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198) ~[metabase.jar:?]
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197) ~[metabase.jar:?]
        at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:152) ~[metabase.jar:?]
        at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198) ~[metabase.jar:?]
        at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197) ~[metabase.jar:?]
```
**To Reproduce**
1. Go to embedded dashboard with filters
2. Click on a field filter
3. Chain filter error in the logs

**Expected behavior**
Field filter should load in embedded dashboard

**Screenshots**

Filter in embedded dashboard :
![image](https://user-images.githubusercontent.com/42241744/99823288-7c719d80-2b54-11eb-92cc-4ddf3e9c477c.png)

Filter in MB dashboard :
![image](https://user-images.githubusercontent.com/42241744/99823228-68c63700-2b54-11eb-902a-27e87815bba4.png)

**Information about your Metabase Installation:**
0.37.2

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
Latest Firefox
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
Win 10
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
snowflake
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
CentOS / jar
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)
mysql

**Comment by mdz0r** [comment]
fixed in 0.37.3, thank you!
