### ISSUE TITLE
[0.33.2] load-from-h2 doesn't create some columns, but required them.

### ISSUE THREAD

**Issue by aagz** [metabase/metabase#14034]
**Describe the bug**
During migration from h2 to mysql, metabase create some tables in empty database, but doesn't create some columns e.g. `locale`, `sso_source` in `core_user` table and `field_order` in `metabase_table` table. 

**Logs**
```Logs
root@metabase:/home/metabase# java -jar metabase.jar load-from-h2 ./metabase.db
12-10 00:21:59 DEBUG plugins.classloader :: Использование НОВОГО СОЗДАННОГО загрузчика классов как общего загрузчика классов: clojure.lang.DynamicClassLoader@716e431d
12-10 00:21:59 DEBUG plugins.classloader :: Установка текущего загрузчика классов контекста потока в общий загрузчик классов clojure.lang.DynamicClassLoader@716e431d...
12-10 00:21:59 INFO metabase.util :: Metabase загружается...
12-10 00:21:59 INFO metabase.util :: Максимально доступно ОЗУ для JVM: 1,9 GB
12-10 00:22:01 INFO util.encryption :: Шифрование сохранённых данных для доступа ВЫКЛЮЧЕНО для этой копии Metabase. 🔓
 Для получения информации, смотрите https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
12-10 00:22:04 INFO metabase.driver :: Абстрактный драйвер зарегистрирован  🚚
12-10 00:22:07 INFO metabase.db :: Verifying mysql Database Connection ...
12-10 00:22:07 INFO metabase.driver :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
Load driver :sql-jdbc took 44.9 ms
12-10 00:22:07 INFO metabase.driver :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
Load driver :mysql took 96.6 ms
12-10 00:22:07 INFO metabase.driver :: Initializing driver :sql...
12-10 00:22:07 INFO metabase.driver :: Initializing driver :sql-jdbc...
12-10 00:22:07 INFO metabase.driver :: Initializing driver :mysql...
12-10 00:22:07 INFO metabase.db :: Verify Database Connection ...  ✅
12-10 00:22:07 INFO metabase.db :: Running Database Migrations...
12-10 00:22:07 INFO metabase.db :: Setting up Liquibase...
12-10 00:22:07 INFO metabase.db :: Liquibase is ready.
12-10 00:22:07 INFO metabase.db :: Checking if Database has unrun migrations...
12-10 00:22:09 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-10 00:22:09 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-10 00:22:09 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-10 00:22:09 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
12-10 00:22:09 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-10 00:22:09 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-10 00:22:09 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-10 00:22:09 INFO metabase.db :: Migration lock is cleared. Running migrations...
12-10 00:22:09 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-10 00:22:09 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-10 00:22:09 WARN changelog.DatabaseChangeLog :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-10 00:22:42 INFO metabase.db :: Database Migrations Current ...  ✅
Настройка базы данных приложения took 35,1 s
Temporarily disabling DB constraints...
[OK]
Transfering 4 instances of Database....[OK]
Transfering 8 instances of User....BatchUpdateException:
 Message: (conn=131) Unknown column 'locale' in 'field list'
 SQLState: 42S22
 Error Code: 1054
java.sql.BatchUpdateException: (conn=131) Unknown column 'locale' in 'field list'
        at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:289)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeBatch(MariaDbPreparedStatementClient.java:306)
        at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:591)
        at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:584)
        at clojure.java.jdbc$db_do_execute_prepared_statement$fn__15518.invoke(jdbc.clj:1039)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:842)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1038)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1024)
        at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1062)
        at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1042)
        at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1576)
        at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1567)
        at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1633)
        at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1601)
        at metabase.cmd.load_from_h2$insert_chunk_BANG_.invokeStatic(load_from_h2.clj:146)
        at metabase.cmd.load_from_h2$insert_chunk_BANG_.invoke(load_from_h2.clj:141)
        at metabase.cmd.load_from_h2$insert_entity_BANG_.invokeStatic(load_from_h2.clj:157)
        at metabase.cmd.load_from_h2$insert_entity_BANG_.invoke(load_from_h2.clj:151)
        at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:165)
        at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:160)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__65134.invoke(load_from_h2.clj:249)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:242)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:231)
        at clojure.lang.Var.invoke(Var.java:384)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:38)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:31)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.cmd$run_cmd$fn__64589.invoke(cmd.clj:119)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:119)
        at metabase.cmd$run_cmd.invoke(cmd.clj:115)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.core$run_cmd.invokeStatic(core.clj:132)
        at metabase.core$run_cmd.invoke(core.clj:130)
        at metabase.core$_main.invokeStatic(core.clj:141)
        at metabase.core$_main.doInvoke(core.clj:137)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Caused by: java.sql.SQLSyntaxErrorException: (conn=131) Unknown column 'locale' in 'field list'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
        at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:286)
        ... 48 more
Caused by: java.sql.SQLException: Unknown column 'locale' in 'field list'
Query is: INSERT INTO core_user ( `email`, `ldap_auth`, `first_name`, `password_salt`, `locale`, `password`, `last_login`, `is_active`, `is_qbnewb`, `updated_at`, `reset_triggered`, `is_superuser`, `login_attributes`, `id`, `reset_token`, `last_name`, `date_joined`, `sso_source`, `google_auth` ) VALUES ( 'glpi@glpi-app.skl.lh', 0, 'GLPI', '5266d751-62ea-4de0-90bb-086f7a0caf0b', <null>, '$2a$10$9Zl9JGzDv5W.qJIjMAHPKObo6LQcCIQtp4P9U3Kc.u', '2019-11-10 03:43:13.078', 1, 1, '2019-11-10 03:43:13.079', 1565266404279, 1, <null>, 2, '$2a$10$.frP9cL9AKI6JJrYYljf69wTNW.', 'Sync', '2019-08-08 15:13:24.175', <null>, 0 )
java thread: MariaDb-bulk-2
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:126)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$1.handleResultException(AbstractQueryProtocol.java:625)
        at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:142)
        at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:66)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Command failed with exception: (conn=131) Unknown column 'locale' in 'field list'
```

**To Reproduce**
export MB_DB_TYPE=mysql
export MB_DB_DBNAME=metabase
export MB_DB_PORT=3306
export MB_DB_USER=<username>
export MB_DB_PASS=<password>
export MB_DB_HOST=localhost
java -jar metabase.jar load-from-h2 /path/to/metabase.db # do not include .mv.db or .h2.db suffix

**Expected behavior**
Migration from h2 has been completed without errors.

**Information about your Metabase Installation:**

- Your databases: Mysql 5.7.32
- Metabase version: 0.33.2
- Metabase hosting environment: Ubuntu 18.04 Linux metabase 4.15.0-122-generic #124-Ubuntu SMP x86_64
- Metabase internal database: h2

**Severity**
We need to migrate metabase from h2 to mysql.

**Comment by flamber** [comment]
Hi @aagz 
Do not upgrade and migrate at the same time: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html#notes
Either migrate with the same version, then upgrade - or upgrade on H2, then migrate.

**Comment by aagz** [comment]
Hi @flamber  , excuse me, but what should I do for migrating without update or update database without migrating?
At the moment, I don't want to update metabase, because some queries will be broken.

**Comment by flamber** [comment]
@aagz The problem is that you have upgraded at some point, and then downgraded again, but without reverting the application database, so it has been upgraded to at least 0.35 changeset.
You would have to upgrade and the migrate to MySQL. Otherwise you would have to manually revert all the changes between 0.33.2 and whatever version you were testing at some point: https://github.com/metabase/metabase/blob/master/resources/migrations/000_migrations.yaml#L6344-L6354

**Comment by aagz** [comment]
@flamber I got it, some weeks ago I tried to update metabase, but as I told upper some questions had broken.
Thank you.

**Comment by flamber** [comment]
@aagz If you don't report things that are broken, then they will likely never get fixed. Make sure to search first, since perhaps someone else has already created an issue that you can follow.
