### ISSUE TITLE
Metabase fails to load database schema after upgrade database from Oracle 11 -> 19c

### ISSUE THREAD

**Issue by binhnguyenduc** [metabase/metabase#14203]
**Describe the bug**
Our company was using Oracle 11 and use Metabase to allow business users to visualize data. We recently upgraded Oracle from 11 to 19c, as well as change database host server. After the upgrade, Metabase now does not recognize any schema, even though raw SQL query still works as expected. We looked at Issues and try resync database schema multiple times, without luck. 

We use Oracle RAC with Active Dataguard. Metabase connects to the Active Dataguard instance.

I use ojdbc8.jar driver downloaded from Oracle page, as linked in Metabase docs.

**Logs**

Logs of resync database task. Seems normal

```
2020-12-28 17:08:53,153 INFO sync.util :: STARTING: Analyze data for oracle Database 68 'FLEX'
2020-12-28 17:08:53,156 INFO sync.util :: STARTING: step 'fingerprint-fields' for oracle Database 68 'FLEX'
2020-12-28 17:08:53,156 INFO sync.util :: FINISHED: step 'fingerprint-fields' for oracle Database 68 'FLEX' (152.7 µs)
2020-12-28 17:08:53,156 INFO sync.util :: STARTING: step 'classify-fields' for oracle Database 68 'FLEX'
2020-12-28 17:08:53,156 INFO sync.util :: FINISHED: step 'classify-fields' for oracle Database 68 'FLEX' (54.3 µs)
2020-12-28 17:08:53,156 INFO sync.util :: STARTING: step 'classify-tables' for oracle Database 68 'FLEX'
2020-12-28 17:08:53,156 INFO sync.util :: FINISHED: step 'classify-tables' for oracle Database 68 'FLEX' (46.6 µs)
2020-12-28 17:08:53,170 INFO sync.util :: FINISHED: Analyze data for oracle Database 68 'FLEX' (17.2 ms)
```

**To Reproduce**

Step 1: connect Metabase to Oracle 11
Step 2: upgrade to Oracle 19c

**Expected behavior**

Database Schema works.

**Screenshots**

[https://ibb.co/hmHqRhZ](url)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "3.10.0-1127.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Bangkok"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "mongo",
      "postgres",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-10-26",
      "tag": "v0.37.0.2",
      "branch": "release-x.37.x",
      "hash": "ba7be09"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

Metabase hosting environment: Kubernetes + Docker

**Severity**

This bug is not too critical, by definitions as raw SQL still works. However, our business users, who should not be expected to know all the inner working of the database (i.e. which data stored in which table), cannot continue to use Metabase effectively without the schema and suggestions. They do not know or expected to know raw SQL. Without the visual help of Ask a Question -> Custom Question, they cannot use Metabase.

**Additional context**

**Comment by flamber** [comment]
Hi @binhnguyenduc 
Please upgrade to 0.37.4 and post which version of ojdbc8.jar you are using.

**Comment by binhnguyenduc** [comment]
Hello, 
I have upgraded Metabase to 0.37.4 and update ojdbc8.jar from Oracle as well. 

Below is the troubleshoot info
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.7+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.7+10",
    "os.name": "Linux",
    "os.version": "3.10.0-1127.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Bangkok"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "mongo",
      "postgres",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.8"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2020-12-17",
      "tag": "v0.37.4",
      "branch": "release-x.37.x",
      "hash": "e0d5287"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

`ojdbc8.jar` seems to be the latest, which support Oracle 19.9c, which is the version we are using. Here is the hash:
https://www.oracle.com/database/technologies/appdev/jdbc-ucp-19-9-c-downloads.html
(4,409,260 bytes - SHA1: c9678370a729f33926f819dae7c6840dd6aab094)



Here is the server log when I trigger a Schema Scan from Database tab in Admin
```
2020-12-29 23:53:05,104 DEBUG middleware.log :: GET /api/database/68 200 12.6 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
2020-12-29 23:53:22,862 DEBUG middleware.log :: POST /api/database/68/sync_schema 200 3.3 ms (1 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (44 total active threads) Queries in flight: 0 (0 queued)
2020-12-29 23:53:22,868 INFO sync.util :: STARTING: Sync metadata for oracle Database 68 'FLEX'
2020-12-29 23:53:22,872 INFO sync.util :: STARTING: step 'sync-timezone' for oracle Database 68 'FLEX'
2020-12-29 23:53:23,655 DEBUG middleware.log :: POST /api/database/68/rescan_values 200 4.2 ms (1 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (51 total active threads) Queries in flight: 0 (0 queued)
2020-12-29 23:53:23,658 INFO sync.util :: STARTING: Cache field values in oracle Database 68 'FLEX'
2020-12-29 23:53:23,659 INFO sync.util :: STARTING: step 'update-field-values' for oracle Database 68 'FLEX'
2020-12-29 23:53:23,664 INFO sync.util :: FINISHED: step 'update-field-values' for oracle Database 68 'FLEX' (4.6 ms)
2020-12-29 23:53:23,742 INFO sync.util :: FINISHED: Cache field values in oracle Database 68 'FLEX' (84.5 ms)
2020-12-29 23:53:23,918 INFO sync.util :: FINISHED: step 'sync-timezone' for oracle Database 68 'FLEX' (1.0 s)
2020-12-29 23:53:23,919 INFO sync.util :: STARTING: step 'sync-tables' for oracle Database 68 'FLEX'
2020-12-29 23:53:25,248 DEBUG middleware.log :: PUT /api/database/68 200 61.6 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (51 total active threads) Queries in flight: 0 (0 queued)
2020-12-29 23:53:25,259 ERROR sync.util :: Error running sync step
java.sql.SQLRecoverableException: Closed Connection: next
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.ensureOpen(InsensitiveScrollableResultSet.java:110) ~[ojdbc8.jar:19.9.0.0.0]
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.next(InsensitiveScrollableResultSet.java:404) ~[ojdbc8.jar:19.9.0.0.0]
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.next(NewProxyResultSet.java:685) ~[metabase.jar:?]
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__76711$fn__76712.invoke(common.clj:39) ~[metabase.jar:?]
	at clojure.core$repeatedly$fn__6463.invoke(core.clj:5149) ~[metabase.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[metabase.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) ~[metabase.jar:?]
	at clojure.lang.Cons.next(Cons.java:39) ~[metabase.jar:?]
	at clojure.lang.RT.next(RT.java:713) ~[metabase.jar:?]
	at clojure.core$next__5386.invokeStatic(core.clj:64) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:169) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8159.invoke(protocols.clj:124) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19) ~[metabase.jar:?]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13) ~[metabase.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6828) ~[metabase.jar:?]
	at clojure.core$reduce.invoke(core.clj:6810) ~[metabase.jar:?]
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__76711.reduce(common.clj:35) ~[metabase.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6827) ~[metabase.jar:?]
	at clojure.core$cat$fn__8761.invoke(core.clj:7625) ~[metabase.jar:?]
	at clojure.core$map$fn__5862$fn__5863.invoke(core.clj:2742) ~[metabase.jar:?]
	at clojure.core$completing$fn__8440.invoke(core.clj:6868) ~[metabase.jar:?]
	at clojure.core$filter$fn__5889$fn__5890.invoke(core.clj:2806) ~[metabase.jar:?]
	at clojure.core$take_while$fn__5913$fn__5914.invoke(core.clj:2901) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:168) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8159.invoke(protocols.clj:124) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19) ~[metabase.jar:?]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75) ~[metabase.jar:?]
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13) ~[metabase.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6828) ~[metabase.jar:?]
	at clojure.core$reduce.invoke(core.clj:6810) ~[metabase.jar:?]
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__76711.reduce(common.clj:35) ~[metabase.jar:?]
	at clojure.core$transduce.invokeStatic(core.clj:6883) ~[metabase.jar:?]
	at clojure.core.Eduction.reduce(core.clj:7682) ~[metabase.jar:?]
	at clojure.core$transduce.invokeStatic(core.clj:6883) ~[metabase.jar:?]
	at clojure.core.Eduction.reduce(core.clj:7682) ~[metabase.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6827) ~[metabase.jar:?]
	at clojure.core$into.invokeStatic(core.clj:6895) ~[metabase.jar:?]
	at clojure.core$into.invoke(core.clj:6887) ~[metabase.jar:?]
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database$fn__76768.invoke(describe_database.clj:124) ~[metabase.jar:?]
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invokeStatic(describe_database.clj:119) ~[metabase.jar:?]
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invoke(describe_database.clj:116) ~[metabase.jar:?]
	at metabase.driver.sql_jdbc$fn__78129.invokeStatic(sql_jdbc.clj:57) ~[metabase.jar:?]
	at metabase.driver.sql_jdbc$fn__78129.invoke(sql_jdbc.clj:55) ~[metabase.jar:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:234) ~[metabase.jar:?]
	at metabase.sync.fetch_metadata$fn__58092$db_metadata__58097$fn__58098.invoke(fetch_metadata.clj:13) ~[metabase.jar:?]
	at metabase.sync.fetch_metadata$fn__58092$db_metadata__58097.invoke(fetch_metadata.clj:10) ~[metabase.jar:?]
	at metabase.sync.sync_metadata.tables$fn__59518$db_metadata__59523$fn__59524.invoke(tables.clj:146) ~[metabase.jar:?]
	at metabase.sync.sync_metadata.tables$fn__59518$db_metadata__59523.invoke(tables.clj:143) ~[metabase.jar:?]
	at metabase.sync.sync_metadata.tables$fn__59579$sync_tables_BANG___59584$fn__59585.invoke(tables.clj:163) ~[metabase.jar:?]
	at metabase.sync.sync_metadata.tables$fn__59579$sync_tables_BANG___59584.invoke(tables.clj:158) ~[metabase.jar:?]
	at metabase.sync.util$fn__40715$run_step_with_metadata__40720$fn__40724$fn__40726.invoke(util.clj:345) ~[metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102) ~[metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96) ~[metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119) ~[metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116) ~[metabase.jar:?]
	at metabase.sync.util$fn__40715$run_step_with_metadata__40720$fn__40724.invoke(util.clj:342) ~[metabase.jar:?]
	at metabase.sync.util$fn__40715$run_step_with_metadata__40720.invoke(util.clj:337) ~[metabase.jar:?]
	at metabase.sync.util$fn__40907$run_sync_operation__40912$fn__40913$fn__40914.invoke(util.clj:430) ~[metabase.jar:?]
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912) ~[metabase.jar:?]
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343) ~[metabase.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6827) ~[metabase.jar:?]
	at clojure.core$mapv.invokeStatic(core.clj:6903) ~[metabase.jar:?]
	at clojure.core$mapv.invoke(core.clj:6903) ~[metabase.jar:?]
	at metabase.sync.util$fn__40907$run_sync_operation__40912$fn__40913.invoke(util.clj:430) ~[metabase.jar:?]
	at metabase.sync.util$fn__40907$run_sync_operation__40912.invoke(util.clj:424) ~[metabase.jar:?]
	at metabase.sync.sync_metadata$fn__59632$sync_db_metadata_BANG___59637$fn__59638$fn__59639.invoke(sync_metadata.clj:51) ~[metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149) [metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142) [metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145) [metabase.jar:?]
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142) [metabase.jar:?]
	at clojure.core$partial$fn__5839.invoke(core.clj:2623) [metabase.jar:?]
	at metabase.driver$fn__22482.invokeStatic(driver.clj:550) [metabase.jar:?]
	at metabase.driver$fn__22482.invoke(driver.clj:550) [metabase.jar:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:239) [metabase.jar:?]
	at metabase.sync.util$sync_in_context$fn__40627.invoke(util.clj:138) [metabase.jar:?]
	at metabase.sync.util$with_db_logging_disabled$fn__40624.invoke(util.clj:129) [metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102) [metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96) [metabase.jar:?]
	at metabase.sync.util$with_start_and_finish_logging$fn__40613.invoke(util.clj:114) [metabase.jar:?]
	at metabase.sync.util$with_sync_events$fn__40608.invoke(util.clj:88) [metabase.jar:?]
	at metabase.sync.util$with_duplicate_ops_prevented$fn__40599.invoke(util.clj:67) [metabase.jar:?]
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164) [metabase.jar:?]
	at metabase.sync.util$do_sync_operation.invoke(util.clj:161) [metabase.jar:?]
	at metabase.sync.sync_metadata$fn__59632$sync_db_metadata_BANG___59637$fn__59638.invoke(sync_metadata.clj:50) [metabase.jar:?]
	at metabase.sync.sync_metadata$fn__59632$sync_db_metadata_BANG___59637.invoke(sync_metadata.clj:47) [metabase.jar:?]
	at metabase.api.database$fn__60377$fn__60379.invoke(database.clj:634) [metabase.jar:?]
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030) [metabase.jar:?]
	at clojure.lang.AFn.call(AFn.java:18) [metabase.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-12-29 23:53:25,278 INFO sync.util :: FINISHED: Sync metadata for oracle Database 68 'FLEX' (2.4 s)
2020-12-29 23:53:25,280 INFO sync.util :: STARTING: Analyze data for oracle Database 68 'FLEX'
2020-12-29 23:53:25,288 INFO sync.util :: STARTING: step 'fingerprint-fields' for oracle Database 68 'FLEX'
2020-12-29 23:53:25,289 DEBUG middleware.log :: GET /api/database 200 15.0 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (47 total active threads) Queries in flight: 0 (0 queued)
2020-12-29 23:53:25,291 INFO sync.util :: FINISHED: step 'fingerprint-fields' for oracle Database 68 'FLEX' (2.6 ms)
2020-12-29 23:53:25,291 INFO sync.util :: STARTING: step 'classify-fields' for oracle Database 68 'FLEX'
2020-12-29 23:53:25,293 INFO sync.util :: FINISHED: step 'classify-fields' for oracle Database 68 'FLEX' (1.3 ms)
2020-12-29 23:53:25,294 INFO sync.util :: STARTING: step 'classify-tables' for oracle Database 68 'FLEX'
2020-12-29 23:53:25,296 INFO sync.util :: FINISHED: step 'classify-tables' for oracle Database 68 'FLEX' (2.0 ms)
2020-12-29 23:53:25,308 INFO sync.util :: FINISHED: Analyze data for oracle Database 68 'FLEX' (28.2 ms)
```

**Comment by binhnguyenduc** [comment]
I have no idea how it got resolved but it is now showing schema as expected. Could've been the driver update. 

Closing issue now. Thanks!
