### ISSUE TITLE
Postgres sync issue for customer

### ISSUE THREAD

**Issue by robdaemon** [metabase/metabase#14244]
**Describe the bug**
Logged error during sync of postgresql database

**Logs**
Large stacktrace gathered from AWS CloudWatch:

```text
2021-01-04T10:06:49.082-08:00	2021-01-04 18:06:49,081 ERROR sync.util :: Error fingerprinting Tabela 1.318 'brerp.rv_fact_adaxa'
2021-01-04T10:06:49.082-08:00	org.postgresql.util.PSQLException: ERROR: more than one row returned by a subquery used as an expression
2021-01-04T10:06:49.082-08:00	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:431) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.driver.sql_jdbc.execute$fn__39581.invokeStatic(execute.clj:266) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.driver.sql_jdbc.execute$fn__39581.invoke(execute.clj:264) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at clojure.lang.MultiFn.invoke(MultiFn.java:234) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:391) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:376) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:385) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:376) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.driver.sql_jdbc$fn__82082.invokeStatic(sql_jdbc.clj:49) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.driver.sql_jdbc$fn__82082.invoke(sql_jdbc.clj:47) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at clojure.lang.MultiFn.invoke(MultiFn.java:244) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.context$executef.invokeStatic(context.clj:59) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.context$executef.invoke(context.clj:48) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:69) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.context.default$default_runf.invoke(default.clj:67) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.context$runf.invokeStatic(context.clj:45) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.context$runf.invoke(context.clj:39) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49121.invoke(mbql_to_native.clj:26) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.middleware.check_features$check_features$fn__48396.invoke(check_features.clj:42) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__49286.invoke(optimize_datetime_filters.clj:133) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__47197.invoke(auto_parse_filter_values.clj:44) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__43869.invoke(wrap_value_literals.clj:149) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.middleware.annotate$add_column_info$fn__43754.invoke(annotate.clj:575) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__48271.invoke(permissions.clj:70) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__49804.invoke(pre_alias_aggregations.clj:40) ~[metabase.jar:?]
2021-01-04T10:06:49.082-08:00	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__48469.invoke(cumulative_aggregations.clj:61) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__51071.invoke(row_level_restrictions.clj:292) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__50041.invoke(resolve_joined_fields.clj:36) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__50360.invoke(resolve_joins.clj:183) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__46802.invoke(add_implicit_joins.clj:254) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__49082.invoke(large_int_id.clj:44) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.limit$limit$fn__49107.invoke(limit.clj:38) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.format_rows$format_rows$fn__49062.invoke(format_rows.clj:84) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.desugar$desugar$fn__48535.invoke(desugar.clj:22) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__47556.invoke(binning.clj:229) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__48073.invoke(resolve_fields.clj:24) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__46350.invoke(add_dimension_projections.clj:318) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__46553.invoke(add_implicit_clauses.clj:141) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase_enterprise.sandbox.query_processor.middleware.row_level_restrictions$apply_row_level_permissions$fn__51071.invoke(row_level_restrictions.clj:292) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__46951.invoke(add_source_metadata.clj:105) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__50773.invoke(column_level_perms_check.clj:24) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50001.invoke(reconcile_breakout_and_order_by_bucketing.clj:98) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__47144.invoke(auto_bucket_datetimes.clj:125) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__48120.invoke(resolve_source_table.clj:46) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__49786.invoke(parameters.clj:114) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__48172.invoke(resolve_referenced.clj:80) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__48791.invoke(expand_macros.clj:158) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__46960.invoke(add_timezone_info.clj:15) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50722.invoke(splice_params_in_response.clj:32) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50012$fn__50016.invoke(resolve_database_and_driver.clj:33) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.driver$do_with_driver.invokeStatic(driver.clj:61) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.driver$do_with_driver.invoke(driver.clj:57) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50012.invoke(resolve_database_and_driver.clj:27) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__49009.invoke(fetch_source_query.clj:267) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.store$initialize_store$fn__50731$fn__50732.invoke(store.clj:11) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.store$do_with_store.invoke(store.clj:40) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.store$initialize_store$fn__50731.invoke(store.clj:10) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__48049.invoke(cache.clj:214) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.validate$validate_query$fn__50740.invoke(validate.clj:10) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.normalize_query$normalize$fn__49134.invoke(normalize_query.clj:22) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__46820.invoke(add_rows_truncated.clj:36) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase_enterprise.audit.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__31545.invoke(handle_audit_queries.clj:165) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__50707.invoke(results_metadata.clj:143) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.reducible$async_qp$qp_STAR___33016$thunk__33017.invoke(reducible.clj:103) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.reducible$async_qp$qp_STAR___33016.invoke(reducible.clj:109) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.reducible$sync_qp$qp_STAR___33025$fn__33028.invoke(reducible.clj:135) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.reducible$sync_qp$qp_STAR___33025.invoke(reducible.clj:134) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.lang.AFn.applyTo(AFn.java:144) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$apply.invokeStatic(core.clj:667) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$apply.invoke(core.clj:660) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:146) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor$process_query.doInvoke(query_processor.clj:140) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.lang.RestFn.invoke(RestFn.java:423) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.lang.Var.invoke(Var.java:388) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.db.metadata_queries$fn__53657$table_rows_sample__53666$fn__53669.invoke(metadata_queries.clj:133) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.db.metadata_queries$fn__53657$table_rows_sample__53666.invoke(metadata_queries.clj:120) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze.fingerprint$fn__53722$fingerprint_table_BANG___53727$fn__53728.invoke(fingerprint.clj:69) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze.fingerprint$fn__53722$fingerprint_table_BANG___53727.invoke(fingerprint.clj:49) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze.fingerprint$fn__53897$fingerprint_fields_BANG___53902$fn__53903$fn__53904.invoke(fingerprint.clj:173) ~[metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze.fingerprint$fn__53897$fingerprint_fields_BANG___53902$fn__53903.invoke(fingerprint.clj:171) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze.fingerprint$fn__53897$fingerprint_fields_BANG___53902.invoke(fingerprint.clj:167) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze.fingerprint$fn__53925$fingerprint_fields_for_db_BANG___53930$fn__53931$fn__53932$iter__53933__53937$fn__53938$fn__53939.invoke(fingerprint.clj:191) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze.fingerprint$fn__53925$fingerprint_fields_for_db_BANG___53930$fn__53931$fn__53932$iter__53933__53937$fn__53938.invoke(fingerprint.clj:188) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.lang.LazySeq.sval(LazySeq.java:42) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.lang.LazySeq.seq(LazySeq.java:51) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$chunk_next.invokeStatic(core.clj:708) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$reduce1.invokeStatic(core.clj:942) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$reduce1.invokeStatic(core.clj:934) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$merge_with.invokeStatic(core.clj:3059) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$merge_with.doInvoke(core.clj:3051) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.lang.RestFn.applyTo(RestFn.java:139) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$apply.invokeStatic(core.clj:667) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$apply.invoke(core.clj:660) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze.fingerprint$fn__53925$fingerprint_fields_for_db_BANG___53930$fn__53931$fn__53932.invoke(fingerprint.clj:188) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:46) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.query_processor.store$do_with_store.invoke(store.clj:40) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze.fingerprint$fn__53925$fingerprint_fields_for_db_BANG___53930$fn__53931.invoke(fingerprint.clj:185) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze.fingerprint$fn__53925$fingerprint_fields_for_db_BANG___53930.invoke(fingerprint.clj:179) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze$make_analyze_steps$fn__54071.invoke(analyze.clj:106) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$fn__42513$run_step_with_metadata__42518$fn__42522$fn__42524.invoke(util.clj:345) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$fn__42513$run_step_with_metadata__42518$fn__42522.invoke(util.clj:342) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$fn__42513$run_step_with_metadata__42518.invoke(util.clj:337) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$fn__42705$run_sync_operation__42710$fn__42711$fn__42712.invoke(util.clj:430) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$mapv$fn__8445.invoke(core.clj:6912) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$reduce.invokeStatic(core.clj:6827) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$mapv.invokeStatic(core.clj:6903) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$mapv.invoke(core.clj:6903) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$fn__42705$run_sync_operation__42710$fn__42711.invoke(util.clj:430) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$fn__42705$run_sync_operation__42710.invoke(util.clj:424) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze$fn__54083$analyze_db_BANG___54088$fn__54089$fn__54090.invoke(analyze.clj:123) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:145) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$do_with_error_handling.invoke(util.clj:142) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.core$partial$fn__5839.invoke(core.clj:2623) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.driver$fn__20868.invokeStatic(driver.clj:550) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.driver$fn__20868.invoke(driver.clj:550) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at clojure.lang.MultiFn.invoke(MultiFn.java:239) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$sync_in_context$fn__42425.invoke(util.clj:138) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$with_db_logging_disabled$fn__42422.invoke(util.clj:129) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$with_start_and_finish_logging$fn__42411.invoke(util.clj:114) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$with_sync_events$fn__42406.invoke(util.clj:88) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$with_duplicate_ops_prevented$fn__42397.invoke(util.clj:67) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:164) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.util$do_sync_operation.invoke(util.clj:161) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze$fn__54083$analyze_db_BANG___54088$fn__54089.invoke(analyze.clj:120) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.sync.analyze$fn__54083$analyze_db_BANG___54088.invoke(analyze.clj:115) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:52) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:40) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:55) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [metabase.jar:?]
2021-01-04T10:06:49.083-08:00	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [metabase.jar:?]
```

**Information about your Metabase Installation:**
Metabase Enterprise 1.37.2 (hosted customer)

Hosted customer instance 4cb3d8cb00c9

**Comment by camsaul** [comment]
I don't remember why we'd be doing any subselects in expressions in the metadata queries used for sync but maybe we are (or were)

**Comment by calherries** [comment]
This was the metadata query at `v0.37.2` in the stack trace:
```
(defn- table-rows-sample-query
  "Returns the mbql query to query a table for sample rows"
  [table fields {:keys [truncation-size] :as _opts}]
  (let [driver             (-> table table/database driver.u/database->driver)
        text-fields        (filter (comp #{:type/Text} :base_type) fields)
        field->expressions (when (and truncation-size (driver/supports? driver :expressions))
                             (into {} (for [field text-fields]
                                        [field [(str (gensym "substring"))
                                                [:substring [:field-id (u/get-id field)] 1 truncation-size]]])))]
    {:database   (:db_id table)
     :type       :query
     :query      {:source-table (u/get-id table)
                  :expressions  (into {} (vals field->expressions))
                  :fields       (vec (for [field fields]
                                       (if-let [[expression-name _] (get field->expressions field)]
                                         [:expression expression-name]
                                         [:field-id (u/get-id field)])))
                  :limit        max-sample-rows}
     :middleware {:format-rows?           false
                  :skip-results-metadata? true}}))
```

I can't see any subselects in there
