### ISSUE TITLE
Every day my service will be blocked by this task. But I didn't have a regular task. I don't know what happened

### ISSUE THREAD

**Issue by pphanwang** [metabase/metabase#14435]
Every day my service will be blocked by this task. But I didn't have a regular task. I don't know what happened

This is my error log
##############################
2021-01-15 23:00:00,019 INFO task.send-pulses :: 正在发送定时任务报告...
2021-01-15 23:18:45,457 ERROR jdbcjobstore.JobStoreTX :: MisfireHandler: Error handling misfires: Couldn't store trigger 'DEFAULT.metabase.task.update-field-values.trigger.1' for 'DEFAULT.metabase.task.update-field-values.job' job:Timeout trying to lock table ; SQL statement:
UPDATE QRTZ_TRIGGERS SET JOB_NAME = ?, JOB_GROUP = ?, DESCRIPTION = ?, NEXT_FIRE_TIME = ?, PREV_FIRE_TIME = ?, TRIGGER_STATE = ?, TRIGGER_TYPE = ?, START_TIME = ?, END_TIME = ?, CALENDAR_NAME = ?, MISFIRE_INSTR = ?, PRIORITY = ?, JOB_DATA = ? WHERE SCHED_NAME = 'MetabaseScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ? [50200-197]
org.quartz.JobPersistenceException: Couldn't store trigger 'DEFAULT.metabase.task.update-field-values.trigger.1' for 'DEFAULT.metabase.task.update-field-values.job' job:Timeout trying to lock table ; SQL statement:
UPDATE QRTZ_TRIGGERS SET JOB_NAME = ?, JOB_GROUP = ?, DESCRIPTION = ?, NEXT_FIRE_TIME = ?, PREV_FIRE_TIME = ?, TRIGGER_STATE = ?, TRIGGER_TYPE = ?, START_TIME = ?, END_TIME = ?, CALENDAR_NAME = ?, MISFIRE_INSTR = ?, PRIORITY = ?, JOB_DATA = ? WHERE SCHED_NAME = 'MetabaseScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ? [50200-197]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1212) ~[metabase.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1026) ~[metabase.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:975) ~[metabase.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3174) ~[metabase.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3934) [metabase.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3955) [metabase.jar:?]
Caused by: org.h2.jdbc.JdbcSQLException: Timeout trying to lock table ; SQL statement:
UPDATE QRTZ_TRIGGERS SET JOB_NAME = ?, JOB_GROUP = ?, DESCRIPTION = ?, NEXT_FIRE_TIME = ?, PREV_FIRE_TIME = ?, TRIGGER_STATE = ?, TRIGGER_TYPE = ?, START_TIME = ?, END_TIME = ?, CALENDAR_NAME = ?, MISFIRE_INSTR = ?, PRIORITY = ?, JOB_DATA = ? WHERE SCHED_NAME = 'MetabaseScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ? [50200-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[metabase.jar:?]
        at org.h2.message.DbException.get(DbException.java:168) ~[metabase.jar:?]
        at org.h2.command.Command.filterConcurrentUpdate(Command.java:316) ~[metabase.jar:?]
        at org.h2.command.Command.executeUpdate(Command.java:268) ~[metabase.jar:?]
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199) ~[metabase.jar:?]
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153) ~[metabase.jar:?]
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:462) ~[metabase.jar:?]
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.updateTrigger(StdJDBCDelegate.java:1226) ~[metabase.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1207) ~[metabase.jar:?]
        ... 5 more
Caused by: org.h2.jdbc.JdbcSQLException: Row not found when trying to delete from index "PUBLIC.IDX_QRTZ_T_NFT_ST_MISFIRE: 61811" [90112-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[metabase.jar:?]
        at org.h2.message.DbException.get(DbException.java:179) ~[metabase.jar:?]
        at org.h2.message.DbException.get(DbException.java:155) ~[metabase.jar:?]
        at org.h2.mvstore.db.MVSecondaryIndex.remove(MVSecondaryIndex.java:248) ~[metabase.jar:?]
        at org.h2.mvstore.db.MVTable.removeRow(MVTable.java:706) ~[metabase.jar:?]
        at org.h2.table.Table.updateRows(Table.java:490) ~[metabase.jar:?]
        at org.h2.command.dml.Update.update(Update.java:177) ~[metabase.jar:?]
        at org.h2.command.CommandContainer.update(CommandContainer.java:102) ~[metabase.jar:?]
        at org.h2.command.Command.executeUpdate(Command.java:261) ~[metabase.jar:?]
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199) ~[metabase.jar:?]
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153) ~[metabase.jar:?]
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:462) ~[metabase.jar:?]
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.updateTrigger(StdJDBCDelegate.java:1226) ~[metabase.jar:?]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1207) ~[metabase.jar:?]
        ... 5 more
2021-01-16 00:00:06,055 INFO task.send-pulses :: 正在发送定时任务报告...
2021-01-16 06:20:18,170 WARN middleware.log :: POST /api/jsonws/invoke 404 1.1 ms（0个数据库调用） 
"API终点不存在"

2021-01-16 09:19:59,092 WARN middleware.log :: POST /api/jsonws/invoke 404 476.2 µs（0个数据库调用） 

#############################

**Comment by flamber** [comment]
Hi @pphanwang 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And migrate away from H2: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
