### ISSUE TITLE
Token check retry is too aggressive

### ISSUE THREAD

**Issue by robdaemon** [metabase/metabase#14514]
**Describe the bug**
When a user's premium / embedding / EE token expires, the system effectively performs a denial of service attack on itself.

**Logs**

```text
2021-01-21T18:10:52.063-08:00	2021-01-22 02:10:52,058 ERROR public-settings.metastore :: Error validating token
2021-01-21T18:10:52.063-08:00	clojure.lang.ExceptionInfo: Token is expired.
2021-01-21T18:10:52.063-08:00	at metabase.public_settings.metastore$fn__23929$valid_token__GT_features_STAR___23934$fn__23935.invoke(metastore.clj:103) ~[metabase.jar:?]
2021-01-21T18:10:52.063-08:00	at metabase.public_settings.metastore$fn__23929$valid_token__GT_features_STAR___23934.invoke(metastore.clj:98) ~[metabase.jar:?]
```

This exception repeats for several hours on this customer instance, each just microseconds apart.

**Information about your Metabase Installation:**

Seen on Metabase v1.37.0.2+

**Severity**
P1, it makes Metabase unusable. The instance stops responding to external requests, and starts taxing our internal token check endpoint.

**Comment by walterl** [comment]
Turns out it wasn't really a bug, but it was mitigated in #14674.
