### ISSUE TITLE
dump-to-h2 with --dump-plaintext should check for presence of MB_ENCRYPTION_SECRET_KEY

### ISSUE THREAD

**Issue by robdaemon** [metabase/metabase#14588]
**Describe the bug**
When dumping a Metabase app db to H2 and decrypting it in the process, we should test for the existence of `MB_ENCRYPTION_SECRET_KEY` and exit with a non-zero exit code if it is not set, or we fail to decrypt values.

It appears that the exception is being swallowed somewhere, so the process exits with 0.

**Logs**

```text
21-01-29 19:35:33 pop-os DEBUG [submarine.snapshots:76] - run: exit code: 0
21-01-29 19:35:33 pop-os DEBUG [submarine.snapshots:77] - run: stdout: WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2021-01-29 11:35:15,353 INFO metabase.util :: Maximum memory available to JVM: 7.8 GB
2021-01-29 11:35:22,465 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. ? 
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2021-01-29 11:35:25,913 INFO metabase.core :: 
Metabase v0.38.0-rc3 (df26940 master) 

Copyright ? 2021 Metabase, Inc. 

Metabase Enterprise Edition extensions are NOT PRESENT.
2021-01-29 11:35:25,919 WARN metabase.core :: WARNING: You have enabled namespace tracing, which could log sensitive information like db passwords.
Dumping from configured Metabase db to H2 file /tmp/b9c4cbfe-c860-4a5f-9b58-9b5a7c161d69.db
2021-01-29 11:35:25,947 INFO db.setup :: Verifying postgres Database Connection ...
2021-01-29 11:35:26,659 INFO db.setup :: Successfully verified PostgreSQL 11.7 application database connection. ?
2021-01-29 11:35:26,661 INFO db.setup :: Running Database Migrations...
2021-01-29 11:35:26,909 INFO db.setup :: Setting up Liquibase...
2021-01-29 11:35:27,044 INFO db.setup :: Liquibase is ready.
2021-01-29 11:35:27,045 INFO db.liquibase :: Checking if Database has unrun migrations...
2021-01-29 11:35:28,769 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2021-01-29 11:35:28,814 INFO db.liquibase :: Migration lock is cleared. Running migrations...
2021-01-29 11:35:28,969 INFO db.setup :: Database Migrations Current ...  ?
2021-01-29 11:35:28,969 INFO db.data-migrations :: Running all necessary data migrations, this may take a minute.
2021-01-29 11:35:29,163 INFO db.data-migrations :: Finished running data migrations.
Set up postgres source database and run migrations... Database setup took 3.2 s
[OK]
2021-01-29 11:35:29,169 INFO db.setup :: [36mVerifying h2 Database Connection ...
2021-01-29 11:35:29,378 INFO db.setup :: Successfully verified H2 1.4.197 (2018-03-18) application database connection. ?
2021-01-29 11:35:29,381 INFO db.setup :: Running Database Migrations...
2021-01-29 11:35:29,392 INFO db.setup :: Setting up Liquibase...
2021-01-29 11:35:29,417 INFO db.setup :: Liquibase is ready.
2021-01-29 11:35:29,417 INFO db.liquibase :: Checking if Database has unrun migrations...
2021-01-29 11:35:29,872 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2021-01-29 11:35:29,924 INFO db.liquibase :: Migration lock is cleared. Running migrations...
2021-01-29 11:35:31,742 INFO db.setup :: Database Migrations Current ...  ?
Set up h2 target database and run migrations... Database setup took 2.6 s
[OK]
Testing if target h2 database is already populated... [OK]
Temporarily disabling DB constraints... [OK]
Copying instances of Database.... copied 1 instances.
Copying instances of User.... copied 1 instances.
Copying instances of Setting.... copied 6 instances.
Copying instances of Table.... copied 4 instances.
Copying instances of Field.... copied 36 instances.
Copying instances of FieldValues.... copied 5 instances.
Copying instances of Revision.... copied 5 instances.
Copying instances of ViewLog.... copied 4 instances.
Copying instances of Session.... copied 1 instances.
Copying instances of Collection.... copied 1 instances.
Copying instances of Dashboard.... copied 1 instances.
Copying instances of Card.... copied 1 instances.
Copying instances of DashboardCard.... copied 1 instances.
Copying instances of Activity.... copied 5 instances.
Copying instances of PermissionsGroup.... copied 3 instances.
Copying instances of PermissionsGroupMembership.... copied 2 instances.
Copying instances of Permissions.... copied 4 instances.
Copying instances of DataMigrations.... copied 13 instances.
Re-enabling DB constraints... [OK]
2021-01-29 11:35:33,394 ERROR models.interface :: Error parsing JSON
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'kJY': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (StringReader); line: 1, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840) ~[v0.38.0-rc3.jar:?]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:722) ~[v0.38.0-rc3.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2868) ~[v0.38.0-rc3.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1914) ~[v0.38.0-rc3.jar:?]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773) ~[v0.38.0-rc3.jar:?]
	at cheshire.parse$parse.invokeStatic(parse.clj:90) ~[v0.38.0-rc3.jar:?]
	at cheshire.parse$parse.invoke(parse.clj:88) ~[v0.38.0-rc3.jar:?]
	at cheshire.core$parse_string.invokeStatic(core.clj:208) ~[v0.38.0-rc3.jar:?]
	at cheshire.core$parse_string.invoke(core.clj:194) ~[v0.38.0-rc3.jar:?]
	at cheshire.core$parse_string.invokeStatic(core.clj:205) ~[v0.38.0-rc3.jar:?]
	at cheshire.core$parse_string.invoke(core.clj:194) ~[v0.38.0-rc3.jar:?]
	at metabase.models.interface$json_out.invokeStatic(interface.clj:39) [v0.38.0-rc3.jar:?]
	at metabase.models.interface$json_out.invoke(interface.clj:36) [v0.38.0-rc3.jar:?]
	at metabase.models.interface$json_out_with_keywordization.invokeStatic(interface.clj:48) [v0.38.0-rc3.jar:?]
	at metabase.models.interface$json_out_with_keywordization.invoke(interface.clj:45) [v0.38.0-rc3.jar:?]
	at clojure.core$comp$fn__5807.invoke(core.clj:2569) [v0.38.0-rc3.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) [v0.38.0-rc3.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) [v0.38.0-rc3.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:665) [v0.38.0-rc3.jar:?]
	at clojure.core$apply.invoke(core.clj:660) [v0.38.0-rc3.jar:?]
	at clojure.core.memoize$through_STAR_$fn__4818.invoke(memoize.clj:107) [v0.38.0-rc3.jar:?]
	at clojure.core.cache$through$fn__4541.invoke(cache.clj:55) [v0.38.0-rc3.jar:?]
	at clojure.core.memoize$through_STAR_$fn__4814$fn__4815.invoke(memoize.clj:106) [v0.38.0-rc3.jar:?]
	at clojure.core.memoize.RetryingDelay.deref(memoize.clj:47) [v0.38.0-rc3.jar:?]
	at clojure.core$deref.invokeStatic(core.clj:2320) [v0.38.0-rc3.jar:?]
	at clojure.core$deref.invoke(core.clj:2306) [v0.38.0-rc3.jar:?]
	at clojure.core.memoize$cached_function$fn__4882.doInvoke(memoize.clj:231) [v0.38.0-rc3.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [v0.38.0-rc3.jar:?]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) [v0.38.0-rc3.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [v0.38.0-rc3.jar:?]
	at toucan.models$apply_type_fns$iter__25324__25328$fn__25329.invoke(models.clj:304) [v0.38.0-rc3.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) [v0.38.0-rc3.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) [v0.38.0-rc3.jar:?]
	at clojure.lang.RT.seq(RT.java:535) [v0.38.0-rc3.jar:?]
	at clojure.core$seq__5402.invokeStatic(core.clj:137) [v0.38.0-rc3.jar:?]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) [v0.38.0-rc3.jar:?]
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75) [v0.38.0-rc3.jar:?]
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75) [v0.38.0-rc3.jar:?]
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13) [v0.38.0-rc3.jar:?]
	at clojure.core$reduce.invokeStatic(core.clj:6828) [v0.38.0-rc3.jar:?]
	at clojure.core$into.invokeStatic(core.clj:6895) [v0.38.0-rc3.jar:?]
	at clojure.core$into.invoke(core.clj:6887) [v0.38.0-rc3.jar:?]
	at toucan.models$apply_type_fns.invokeStatic(models.clj:302) [v0.38.0-rc3.jar:?]
	at toucan.models$apply_type_fns.invoke(models.clj:299) [v0.38.0-rc3.jar:?]
	at toucan.models$do_post_select.invokeStatic(models.clj:349) [v0.38.0-rc3.jar:?]
	at toucan.models$do_post_select.invoke(models.clj:344) [v0.38.0-rc3.jar:?]
	at toucan.db$do_post_select$iter__27965__27969$fn__27970.invoke(db.clj:373) [v0.38.0-rc3.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) [v0.38.0-rc3.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) [v0.38.0-rc3.jar:?]
	at clojure.lang.RT.seq(RT.java:535) [v0.38.0-rc3.jar:?]
	at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44) [v0.38.0-rc3.jar:?]
	at clojure.core$vec.invokeStatic(core.clj:377) [v0.38.0-rc3.jar:?]
	at clojure.core$vec.invoke(core.clj:367) [v0.38.0-rc3.jar:?]
	at toucan.db$do_post_select.invokeStatic(db.clj:372) [v0.38.0-rc3.jar:?]
	at toucan.db$do_post_select.invoke(db.clj:363) [v0.38.0-rc3.jar:?]
	at toucan.db$simple_select.invokeStatic(db.clj:394) [v0.38.0-rc3.jar:?]
	at toucan.db$simple_select.invoke(db.clj:383) [v0.38.0-rc3.jar:?]
	at toucan.db$select.invokeStatic(db.clj:662) [v0.38.0-rc3.jar:?]
	at toucan.db$select.doInvoke(db.clj:656) [v0.38.0-rc3.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:410) [v0.38.0-rc3.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) [v0.38.0-rc3.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) [v0.38.0-rc3.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:667) [v0.38.0-rc3.jar:?]
	at clojure.core$apply.invoke(core.clj:660) [v0.38.0-rc3.jar:?]
	at toucan.db$select_field__GT_field.invokeStatic(db.clj:704) [v0.38.0-rc3.jar:?]
	at toucan.db$select_field__GT_field.doInvoke(db.clj:697) [v0.38.0-rc3.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:445) [v0.38.0-rc3.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:160) [v0.38.0-rc3.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) [v0.38.0-rc3.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:671) [v0.38.0-rc3.jar:?]
	at clojure.core$apply.invoke(core.clj:660) [v0.38.0-rc3.jar:?]
	at toucan.db$select_id__GT_field.invokeStatic(db.clj:723) [v0.38.0-rc3.jar:?]
	at toucan.db$select_id__GT_field.doInvoke(db.clj:716) [v0.38.0-rc3.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:425) [v0.38.0-rc3.jar:?]
	at metabase.cmd.copy$fn__74585$overwrite_encrypted_fields_to_plaintext_BANG___74590$fn__74591.invoke(copy.clj:296) [v0.38.0-rc3.jar:?]
	at metabase.cmd.copy$fn__74585$overwrite_encrypted_fields_to_plaintext_BANG___74590.invoke(copy.clj:285) [v0.38.0-rc3.jar:?]
	at metabase.cmd.dump_to_h2$dump_to_h2_BANG_.invokeStatic(dump_to_h2.clj:38) [v0.38.0-rc3.jar:?]
	at metabase.cmd.dump_to_h2$dump_to_h2_BANG_.invoke(dump_to_h2.clj:19) [v0.38.0-rc3.jar:?]
	at clojure.lang.Var.invoke(Var.java:388) [v0.38.0-rc3.jar:?]
	at metabase.cmd$dump_to_h2.invokeStatic(cmd.clj:54) [v0.38.0-rc3.jar:?]
	at metabase.cmd$dump_to_h2.doInvoke(cmd.clj:46) [v0.38.0-rc3.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:139) [v0.38.0-rc3.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:665) [v0.38.0-rc3.jar:?]
	at clojure.core$apply.invoke(core.clj:660) [v0.38.0-rc3.jar:?]
	at metabase.cmd$run_cmd$fn__74121.invoke(cmd.clj:171) [v0.38.0-rc3.jar:?]
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:171) [v0.38.0-rc3.jar:?]
	at metabase.cmd$run_cmd.invoke(cmd.clj:167) [v0.38.0-rc3.jar:?]
	at clojure.lang.Var.invoke(Var.java:388) [v0.38.0-rc3.jar:?]
	at metabase.core$run_cmd.invokeStatic(core.clj:148) [v0.38.0-rc3.jar:?]
	at metabase.core$run_cmd.invoke(core.clj:146) [v0.38.0-rc3.jar:?]
	at metabase.core$_main.invokeStatic(core.clj:170) [v0.38.0-rc3.jar:?]
	at metabase.core$_main.doInvoke(core.clj:165) [v0.38.0-rc3.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [v0.38.0-rc3.jar:?]
	at metabase.core.main(Unknown Source) [v0.38.0-rc3.jar:?]
Dump complete
```

**Comment by kidd** [comment]
Makes sense. I'm thinking that the https://github.com/metabase/metabase/pull/14552 does both:
- exit code
- the checking if all values are decrypted ok, and bail out if not.

**Comment by rlotun** [comment]
Fixed by https://github.com/metabase/metabase/pull/14552
