### ISSUE TITLE
Can not run docker with TIDB

### ISSUE THREAD

**Issue by ToryZhou** [metabase/metabase#14888]
**Describe the bug**
The database is using the TIDB

Bellow is the command:

docker run -d -p 3000:3000 \
  -e "MB_DB_TYPE=mysql" \
  -e "MB_DB_DBNAME=metabase" \
  -e "MB_DB_PORT=32000" \
  -e "MB_DB_USER=<username>" \
  -e "MB_DB_PASS=<password>" \
  -e "MB_DB_HOST=my-database-host" \
  --name metabase metabase/metabase

 When docker logs -f <container_id> to check the log:
It throws the Excption
2021-02-19 11:35:50,686 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::6::agilliland:
     Reason: liquibase.exception.DatabaseException: (conn=79936) Referencing column 'organization_id' in foreign key constraint 'fk_database_ref_organization_id' are incompatible [Failed SQL: ALTER TABLE metabase_db.metabase_database MODIFY organization_id INT NULL]

**Logs**
2021-02-19 11:35:50,048 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::6::agilliland failed.  Error: (conn=79936) Referencing column 'organization_id' in foreign key constraint 'fk_database_ref_organization_id' are incompatible [Failed SQL: ALTER TABLE metabase_db.metabase_database MODIFY organization_id INT NULL]
2021-02-19 11:35:50,686 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::6::agilliland:
     Reason: liquibase.exception.DatabaseException: (conn=79936) Referencing column 'organization_id' in foreign key constraint 'fk_database_ref_organization_id' are incompatible [Failed SQL: ALTER TABLE metabase_db.metabase_database MODIFY organization_id INT NULL]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637) ~[metabase.jar:?]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53) ~[metabase.jar:?]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83) ~[metabase.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:202) ~[metabase.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:179) ~[metabase.jar:?]
	at liquibase.Liquibase.update(Liquibase.java:175) ~[metabase.jar:?]
	at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__20962.invoke(liquibase.clj:125) ~[metabase.jar:?]
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:437) ~[metabase.jar:?]
	at metabase.util$do_with_auto_retries.invoke(util.clj:429) ~[metabase.jar:?]
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:444) ~[metabase.jar:?]
	at metabase.util$do_with_auto_retries.invoke(util.clj:429) ~[metabase.jar:?]
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:444) ~[metabase.jar:?]
	at metabase.util$do_with_auto_retries.invoke(util.clj:429) ~[metabase.jar:?]
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:444) ~[metabase.jar:?]
	at metabase.util$do_with_auto_retries.invoke(util.clj:429) ~[metabase.jar:?]
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:125) ~[metabase.jar:?]
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:113) ~[metabase.jar:?]
	at metabase.db$migrate_BANG_$fn__21746$fn__21747.invoke(db.clj:208) ~[metabase.jar:?]
	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:37) ~[metabase.jar:?]
	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:29) ~[metabase.jar:?]
	at metabase.db$migrate_BANG_$fn__21746.invoke(db.clj:203) ~[metabase.jar:?]
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807) ~[metabase.jar:?]
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776) ~[metabase.jar:?]
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852) ~[metabase.jar:?]
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776) ~[metabase.jar:?]
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789) ~[metabase.jar:?]
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776) ~[metabase.jar:?]
	at metabase.db$migrate_BANG_.invokeStatic(db.clj:194) ~[metabase.jar:?]
	at metabase.db$migrate_BANG_.invoke(db.clj:173) ~[metabase.jar:?]
	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:336) ~[metabase.jar:?]
	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:330) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG__STAR_$fn__21829.invoke(db.clj:353) ~[metabase.jar:?]
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:670) ~[metabase.jar:?]
	at metabase.util$do_with_us_locale.invoke(util.clj:656) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:351) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:346) ~[metabase.jar:?]
	at metabase.db$setup_db_from_env_BANG_.invokeStatic(db.clj:365) ~[metabase.jar:?]
	at metabase.db$setup_db_from_env_BANG_.invoke(db.clj:358) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG_$fn__21834.invoke(db.clj:375) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:373) ~[metabase.jar:?]
	at metabase.db$setup_db_BANG_.invoke(db.clj:368) ~[metabase.jar:?]
	at metabase.core$init_BANG_.invokeStatic(core.clj:96) ~[metabase.jar:?]
	at metabase.core$init_BANG_.invoke(core.clj:75) ~[metabase.jar:?]
	at metabase.core$start_normally.invokeStatic(core.clj:140) [metabase.jar:?]
	at metabase.core$start_normally.invoke(core.clj:134) [metabase.jar:?]
	at metabase.core$_main.invokeStatic(core.clj:173) [metabase.jar:?]
	at metabase.core$_main.doInvoke(core.clj:167) [metabase.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:397) [metabase.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:152) [metabase.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) [metabase.jar:?]
	at metabase.core.main(Unknown Source) [metabase.jar:?]
Caused by: liquibase.exception.DatabaseException: (conn=79936) Referencing column 'organization_id' in foreign key constraint 'fk_database_ref_organization_id' are incompatible [Failed SQL: ALTER TABLE metabase_db.metabase_database MODIFY organization_id INT NULL]

**To Reproduce**
Run the following command to reproduce:
docker run -d -p 3000:3000 \
  -e "MB_DB_TYPE=mysql" \
  -e "MB_DB_DBNAME=metabase" \
  -e "MB_DB_PORT=32000" \
  -e "MB_DB_USER=<username>" \
  -e "MB_DB_PASS=<password>" \
  -e "MB_DB_HOST=my-database-host" \
  --name metabase metabase/metabase

**Expected behavior**
Expected Docker run with mysql successfully

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: N/A
- Your operating system: Linux or centos
- Your databases: TIDB
- Metabase version: v0.38.0 or v0.37.8
- Metabase hosting environment: Ubuntu
- Metabase internal database: TIDB

**Severity**
Blocking my usage of Metabase entirely

**Comment by ToryZhou** [comment]
For this file: https://github.com/metabase/metabase/blob/master/resources/migrations/000_migrations.yaml
Liquibase changeset id '6' can not run successfully. Because it can not dropNotNullConstraint before dropForeignKeyConstraint

  - changeSet:
      id: '6'
      author: agilliland
      changes:
      - dropNotNullConstraint:
          columnDataType: int
          columnName: organization_id
          tableName: metabase_database
      - dropForeignKeyConstraint:
          baseTableName: metabase_database
          constraintName: fk_database_ref_organization_id

**Comment by flamber** [comment]
Hi @ToryZhou 
Metabase does not officially support TiDB unless it's fully compatible with MySQL 5.7+/MariaDB 10.2+ which is supported.
You can set [MB_DB_AUTOMIGRATE](https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_db_automigrate)=false and manually make the changes.
You're likely seeing this issue https://github.com/pingcap/tidb/issues/14766

**Comment by ToryZhou** [comment]
> manually
How can I add these 2 params  usePipelineAuth=false&useBatchMultiSend=false

Because I need to connect to aws aurora mysql. It throws exception 'could not load system variables'.

**Comment by flamber** [comment]
@ToryZhou There's an issue open for supporting Aurora as application database #10709 - upvote by clicking :+1: on the first post
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by zhangguiyu** [comment]
I have modified metabase 0.39.1 migrations to work with TiDB, check them out here:

https://github.com/zhangguiyu/metabase/tree/aarch64/resources/migrations/tidb
