### ISSUE TITLE
Metabase v0.38.1 Resync Schema w/Redshift DB fails

### ISSUE THREAD

**Issue by sunnimada** [metabase/metabase#15104]
**Describe the bug**
In version 0.37.2 and 0.38.1,  attempts to resync table schemas with Redshift fail when the user has `USAGE` on a specific schema. 
If I revoke access usage to this schema to the user, it syncs. If the user has `USAGE` on the schema it doesn't sync, even if I remove `SELECT` on all the tables of this schema from the user.

**Logs**
```
[bb55725b-d8df-42e0-95c3-6917c2fbef65] 2021-03-09T16:16:04+01:00 INFO metabase.sync.util STARTING: Sync metadata for redshift Database 14 'Hotfix 2'
[bb55725b-d8df-42e0-95c3-6917c2fbef65] 2021-03-09T16:16:04+01:00 INFO metabase.sync.util STARTING: step 'sync-timezone' for redshift Database 14 'Hotfix 2'
[bb55725b-d8df-42e0-95c3-6917c2fbef65] 2021-03-09T16:16:04+01:00 INFO metabase.sync.util FINISHED: step 'sync-timezone' for redshift Database 14 'Hotfix 2' (87.6 ms)
[bb55725b-d8df-42e0-95c3-6917c2fbef65] 2021-03-09T16:16:04+01:00 INFO metabase.sync.util STARTING: step 'sync-tables' for redshift Database 14 'Hotfix 2'
[bb55725b-d8df-42e0-95c3-6917c2fbef65] 2021-03-09T16:16:20+01:00 ERROR metabase.sync.util Error running sync step
com.amazon.redshift.util.RedshiftException: This connection has been closed.
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.checkClosed(RedshiftConnectionImpl.java:1021)
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.createStatement(RedshiftConnectionImpl.java:2001)
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.createStatement(RedshiftConnectionImpl.java:486)
	at com.amazon.redshift.jdbc.RedshiftDatabaseMetaData.getExtSchemaPatternMatch(RedshiftDatabaseMetaData.java:4963)
	at com.amazon.redshift.jdbc.RedshiftDatabaseMetaData.getTables(RedshiftDatabaseMetaData.java:1487)
	at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getTables(NewProxyDatabaseMetaData.java:3010)
	at metabase.driver.sql_jdbc.sync.describe_database$db_tables$fn__78417.invoke(describe_database.clj:72)
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__78392.reduce(common.clj:34)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$cat$fn__8761.invoke(core.clj:7625)
	at clojure.core$map$fn__5862$fn__5863.invoke(core.clj:2742)
	at clojure.core$completing$fn__8440.invoke(core.clj:6868)
	at clojure.core$filter$fn__5889$fn__5890.invoke(core.clj:2806)
	at clojure.core$take_while$fn__5913$fn__5914.invoke(core.clj:2901)
	at clojure.core.protocols$fn__8159.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8159.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$reduce.invoke(core.clj:6810)
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__78392.reduce(common.clj:35)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core.Eduction.reduce(core.clj:7682)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core.Eduction.reduce(core.clj:7682)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$into.invokeStatic(core.clj:6895)
	at clojure.core$into.invoke(core.clj:6887)
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database$fn__78449.invoke(describe_database.clj:122)
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invokeStatic(describe_database.clj:117)
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invoke(describe_database.clj:114)
	at metabase.driver.sql_jdbc$fn__79823.invokeStatic(sql_jdbc.clj:62)
	at metabase.driver.sql_jdbc$fn__79823.invoke(sql_jdbc.clj:60)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.sync.fetch_metadata$fn__60398$db_metadata__60403$fn__60404.invoke(fetch_metadata.clj:13)
	at metabase.sync.fetch_metadata$fn__60398$db_metadata__60403.invoke(fetch_metadata.clj:10)
	at metabase.sync.sync_metadata.tables$fn__61824$db_metadata__61829$fn__61830.invoke(tables.clj:143)
	at metabase.sync.sync_metadata.tables$fn__61824$db_metadata__61829.invoke(tables.clj:140)
	at metabase.sync.sync_metadata.tables$fn__61885$sync_tables_BANG___61890$fn__61891.invoke(tables.clj:160)
	at metabase.sync.sync_metadata.tables$fn__61885$sync_tables_BANG___61890.invoke(tables.clj:155)
	at metabase.sync.util$fn__39682$run_step_with_metadata__39687$fn__39691$fn__39693.invoke(util.clj:342)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:116)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:113)
	at metabase.sync.util$fn__39682$run_step_with_metadata__39687$fn__39691.invoke(util.clj:339)
	at metabase.sync.util$fn__39682$run_step_with_metadata__39687.invoke(util.clj:334)
	at metabase.sync.util$fn__39874$run_sync_operation__39879$fn__39880$fn__39881.invoke(util.clj:427)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clojure.core$mapv.invoke(core.clj:6903)
	at metabase.sync.util$fn__39874$run_sync_operation__39879$fn__39880.invoke(util.clj:427)
	at metabase.sync.util$fn__39874$run_sync_operation__39879.invoke(util.clj:421)
	at metabase.sync.sync_metadata$fn__61938$sync_db_metadata_BANG___61943$fn__61944$fn__61945.invoke(sync_metadata.clj:49)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:146)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:139)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:142)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:139)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver$fn__29336.invokeStatic(driver.clj:527)
	at metabase.driver$fn__29336.invoke(driver.clj:527)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__39594.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__39591.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__39580.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__39575.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__39566.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:161)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:158)
	at metabase.sync.sync_metadata$fn__61938$sync_db_metadata_BANG___61943$fn__61944.invoke(sync_metadata.clj:48)
	at metabase.sync.sync_metadata$fn__61938$sync_db_metadata_BANG___61943.invoke(sync_metadata.clj:45)
	at metabase.api.database$fn__62734$fn__62736.invoke(database.clj:621)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[bb55725b-d8df-42e0-95c3-6917c2fbef65] 2021-03-09T16:16:20+01:00 INFO metabase.sync.util FINISHED: Sync metadata for redshift Database 14 'Hotfix 2' (15.7 s)
```

To Reproduce

Go to Admin console -> 'Databases'
Select Redshift database.
Select 'Sync database schema now'

Expected behavior

When a resync of a Redshift database is triggered in Metabase, it should complete successfully, with new schemas and tables made accessible via the UI.

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Version 89.0.4389.82 (Build officiel) (x86_64)
- Your operating system: macOS 10.15.7
- Your databases: Redshift
- Metabase version: 0.38.1
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?

It blocks our users because none of the modification we made on our redshift is sync on metabase, tables can't be join or referenced as foreign key. This connection hasn't been updated in more than a month. 

**Additional context**
I tried to restart our cluster, to update it, to test permissions on our DB, this specific schema blocks everything apparently.

**Comment by flamber** [comment]
Setting P1, since I guess it would mean we're not syncing at all with a new instance with such privileges.
Likely caused by PR #10892

**Comment by jeff303** [comment]
@sunnimada , do you know what the last version of Metabase was, where this didn't occur?  Also, curious if you are able to try the same using the `latest` tag of our [Docker image](https://hub.docker.com/r/metabase/metabase)?  The reason I ask is because we have updated the Redshift driver version since then, and I'm wondering if that fixed this problem.

**Comment by sunnimada** [comment]
@jeff303 I just asked a colleague to have a look on the previous version we had, he think we used v0.36.4 before 0.37.2, and we'll test the latest later today.

We're mainly using Metabase with Redshift connections, I haven't notice any bugs on our mySQL ones I think. The sync is compromised by one schema of our redshift, and it has the same config as the other schema of this DB.

**Comment by jeff303** [comment]
@sunnimada , but is that particular schema [external](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_EXTERNAL_SCHEMA.html) or [not](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_SCHEMA.html)?

**Comment by sunnimada** [comment]
It's not an external schema

**Comment by jeff303** [comment]
I did some digging through the Redshift JDBC driver [1.x](https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.53.1080/Amazon+Redshift+JDBC+Release+Notes.pdf) and [2.x](https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/CHANGELOG.md) release notes, but was unable to point to a specific item identified as fixed that might have led to this error.  Nonetheless, it would be good to know whether the latest driver version (2.0.0.3), from our `latest` tag build, works as expected, @sunnimada.

In fact, with this version of the Redshift JDBC driver, I'm observing the _opposite_ as what is described here.  That is, a user needs to be be granted `USAGE` on a schema before a table could ever be synced (since the sync process actually runs a test query against all tables, and this will fail on the Redshift side if the user doesn't have `USAGE` on the schema).

**Comment by jeff303** [comment]
@sunnimada , can you please send me an email and we can try to schedule some time to debug what's going on?  I'm unable to reproduce this on our Redshift instance, so perhaps there is something particular about the setup of tables and schemas in yours.  Email is `<first>.<last>@<company>.com` (you can see my first and last name on my GitHub profile).

**Comment by flamber** [comment]
@sunnimada Can you share a DDL and privileges, so we can try to reproduce this? Otherwise it will be very difficult to fix.
