### ISSUE TITLE
Google Analytics not showing values in filter dropdown

### ISSUE THREAD

**Issue by FranzBusch** [metabase/metabase#15175]
**Describe the bug**
When using Google Analytics and setting up a dashboard with e.g. category filters, then the dropdown is not displaying any values. I tried to re-scan the values from the Admin -> Data Models page but I saw error logs appearing.

**Logs**
```
[9a7247c1-cb8e-444d-95cd-2540f9ffcc71] 2021-03-15T20:23:52+01:00 ERROR metabase.models.field-values Error fetching field values
java.lang.AssertionError: Assert failed: :metrics is required in a Google Analytics query
(not (str/blank? (:metrics query)))
	at metabase.driver.googleanalytics$mbql_query__GT_request.invokeStatic(googleanalytics.clj:117)
	at metabase.driver.googleanalytics$mbql_query__GT_request.invoke(googleanalytics.clj:112)
	at metabase.driver.googleanalytics$execute_STAR_.invokeStatic(googleanalytics.clj:153)
	at metabase.driver.googleanalytics$execute_STAR_.invoke(googleanalytics.clj:151)
	at metabase.driver.googleanalytics.execute$execute_reducible_query.invokeStatic(execute.clj:123)
	at metabase.driver.googleanalytics.execute$execute_reducible_query.invoke(execute.clj:120)
	at metabase.driver.googleanalytics$eval1378$fn__1379.invoke(googleanalytics.clj:157)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:68)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:66)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__46414.invoke(mbql_to_native.clj:25)
	at metabase.query_processor.middleware.check_features$check_features$fn__45666.invoke(check_features.clj:41)
	at metabase.query_processor.middleware.limit$limit$fn__46400.invoke(limit.clj:37)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__45324.invoke(cache.clj:211)
	at metabase.query_processor.middleware.optimize_datetime_filters$optimize_datetime_filters$fn__46579.invoke(optimize_datetime_filters.clj:133)
	at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__44470.invoke(auto_parse_filter_values.clj:43)
	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__40787.invoke(wrap_value_literals.clj:147)
	at metabase.query_processor.middleware.annotate$add_column_info$fn__40650.invoke(annotate.clj:582)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__45541.invoke(permissions.clj:75)
	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__47102.invoke(pre_alias_aggregations.clj:40)
	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__45739.invoke(cumulative_aggregations.clj:60)
	at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47415.invoke(resolve_joined_fields.clj:94)
	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__47720.invoke(resolve_joins.clj:178)
	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44064.invoke(add_implicit_joins.clj:181)
	at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__46375.invoke(large_int_id.clj:44)
	at metabase.query_processor.middleware.format_rows$format_rows$fn__46355.invoke(format_rows.clj:74)
	at metabase.query_processor.middleware.desugar$desugar$fn__45805.invoke(desugar.clj:21)
	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__44830.invoke(binning.clj:228)
	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__45348.invoke(resolve_fields.clj:24)
	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__43694.invoke(add_dimension_projections.clj:316)
	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__43925.invoke(add_implicit_clauses.clj:146)
	at metabase.query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__48150.invoke(upgrade_field_literals.clj:45)
	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44217.invoke(add_source_metadata.clj:122)
	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__47299.invoke(reconcile_breakout_and_order_by_bucketing.clj:97)
	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44417.invoke(auto_bucket_datetimes.clj:139)
	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45395.invoke(resolve_source_table.clj:45)
	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__47084.invoke(parameters.clj:111)
	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45447.invoke(resolve_referenced.clj:79)
	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__46061.invoke(expand_macros.clj:155)
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__44226.invoke(add_timezone_info.clj:15)
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__48086.invoke(splice_params_in_response.clj:32)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47310$fn__47314.invoke(resolve_database_and_driver.clj:31)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:60)
	at metabase.driver$do_with_driver.invoke(driver.clj:56)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__47310.invoke(resolve_database_and_driver.clj:25)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46301.invoke(fetch_source_query.clj:274)
	at metabase.query_processor.middleware.store$initialize_store$fn__48095$fn__48096.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.query_processor.middleware.store$initialize_store$fn__48095.invoke(store.clj:10)
	at metabase.query_processor.middleware.validate$validate_query$fn__48157.invoke(validate.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__46427.invoke(normalize_query.clj:22)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44082.invoke(add_rows_truncated.clj:35)
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__48071.invoke(results_metadata.clj:147)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37428$thunk__37429.invoke(reducible.clj:103)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37428.invoke(reducible.clj:109)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37428.invoke(reducible.clj:96)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___37437$fn__37438.invoke(reducible.clj:131)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___37437.invoke(reducible.clj:130)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:146)
	at metabase.query_processor$process_query.doInvoke(query_processor.clj:140)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.db.metadata_queries$qp_query$fn__59168.invoke(metadata_queries.clj:21)
	at metabase.db.metadata_queries$qp_query.invokeStatic(metadata_queries.clj:20)
	at metabase.db.metadata_queries$qp_query.invoke(metadata_queries.clj:18)
	at metabase.db.metadata_queries$field_query.invokeStatic(metadata_queries.clj:30)
	at metabase.db.metadata_queries$field_query.invoke(metadata_queries.clj:28)
	at metabase.db.metadata_queries$fn__59188$field_distinct_values__59197$fn__59200.invoke(metadata_queries.clj:75)
	at metabase.db.metadata_queries$fn__59188$field_distinct_values__59197.invoke(metadata_queries.clj:68)
	at metabase.db.metadata_queries$fn__59188$field_distinct_values__59197$fn__59198.invoke(metadata_queries.clj:72)
	at metabase.db.metadata_queries$fn__59188$field_distinct_values__59197.invoke(metadata_queries.clj:68)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.models.field_values$distinct_values.invokeStatic(field_values.clj:123)
	at metabase.models.field_values$distinct_values.invoke(field_values.clj:115)
	at metabase.models.field_values$create_or_update_field_values_BANG_.invokeStatic(field_values.clj:145)
	at metabase.models.field_values$create_or_update_field_values_BANG_.doInvoke(field_values.clj:139)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at metabase.models.field_values$create_field_values_if_needed_BANG_.invokeStatic(field_values.clj:210)
	at metabase.models.field_values$create_field_values_if_needed_BANG_.doInvoke(field_values.clj:202)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.api.field$field__GT_values.invokeStatic(field.clj:188)
	at metabase.api.field$field__GT_values.invoke(field.clj:182)
	at metabase.api.field$fn__62460.invokeStatic(field.clj:220)
	at metabase.api.field$fn__62460.invoke(field.clj:212)
	at compojure.core$wrap_response$fn__1993.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__1977.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__1982.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:151)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:152)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:153)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:153)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:152)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:153)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:153)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__73836.invoke(auth.clj:14)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005.invoke(core.clj:200)
	at compojure.core$make_context$handler__2033.invoke(core.clj:287)
	at compojure.core$make_context$fn__2035.invoke(core.clj:296)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$make_context$fn__2035.invoke(core.clj:297)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$make_context$fn__2035.invoke(core.clj:297)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$make_context$fn__2035.invoke(core.clj:297)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$make_context$fn__2035.invoke(core.clj:297)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$make_context$fn__2035.invoke(core.clj:297)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$make_context$fn__2035.invoke(core.clj:297)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$make_context$fn__2035.invoke(core.clj:297)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$make_context$fn__2035.invoke(core.clj:297)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$make_context$fn__2035.invoke(core.clj:297)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$make_context$fn__2035.invoke(core.clj:297)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at metabase.api.routes$fn__73957$fn__73959.invoke(routes.clj:69)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.server.routes$fn__76139$fn__76140.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005.invoke(core.clj:200)
	at compojure.core$make_context$handler__2033.invoke(core.clj:287)
	at compojure.core$make_context$fn__2035.invoke(core.clj:296)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:152)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:152)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1986.invoke(core.clj:152)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005$f__2006$respond_SINGLEQUOTE___2007.invoke(core.clj:197)
	at metabase.server.routes$fn__76127$fn__76129.invoke(routes.clj:41)
	at compojure.core$routes$fn__2005$f__2006.invoke(core.clj:198)
	at compojure.core$routes$fn__2005.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73948.invoke(exceptions.clj:96)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__73945.invoke(exceptions.clj:84)
	at metabase.server.middleware.log$log_api_call$fn__76055$fn__76056.invoke(log.clj:195)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__76055.invoke(log.clj:189)
	at metabase.server.middleware.security$add_security_headers$fn__73911.invoke(security.clj:142)
	at metabase.server.middleware.json$wrap_json_body$fn__75836.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__75854.invoke(json.clj:98)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__76396.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__76412.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__35081.invoke(misc.clj:58)
	at metabase.server.middleware.session$bind_current_user$fn__41914$fn__41915.invoke(session.clj:277)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:258)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:250)
	at metabase.server.middleware.session$bind_current_user$fn__41914.invoke(session.clj:276)
	at metabase.server.middleware.session$wrap_current_user_info$fn__41901.invoke(session.clj:236)
	at metabase.server.middleware.session$wrap_session_id$fn__41887.invoke(session.clj:182)
	at metabase.server.middleware.auth$wrap_api_key$fn__73844.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__76316.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__35064.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__35089.invoke(misc.clj:75)
	at ring.middleware.gzip$wrap_gzip$fn__76358.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__35092.invoke(misc.clj:92)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__76072.invoke(ssl.clj:38)
	at metabase.server$async_proxy_handler$fn__75669.invoke(server.clj:71)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
1. Setup GA connection
2. Setup a field as an e.g. category
3. Press re-scan values
4. See an error in the console

**Expected behavior**
Dropdowns contain a list of possible values.

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```
{
  "browser-info": {
    "language": "en-gb",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.214-160.339.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "googleanalytics",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.1 (Debian 13.1-1.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-03",
      "tag": "v0.38.1",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
The bug is rather annoying since we have fields with a lot of values like app versions that are hard to filter correctly without knowing the exact string. It would be way easier if the dropdowns are properly populated.

**Additional context**
There seems to be a similar bug https://github.com/metabase/metabase/issues/12411 but there you are able to solve it on your own by adding the proper query parameters. However, when Metabase is scanning the database for values it needs to also query for a metric when using GA.

**Comment by flamber** [comment]
Hi @FranzBusch 
The issue you're referencing is a slight smoke screen, but it's true it was similar error - that issue caused new instances to not being able to query GA at all.
You are seeing #7284
