### ISSUE TITLE
Execute the migration database command to report an error

### ISSUE THREAD

**Issue by 8debug** [metabase/metabase#15590]
**Describe the bug**
Execute the migration database command to report an error

**Logs**
```powershell
Warning: environ value C:\Program Files\Java\jdk1.8.0_101 for key :java-home has been overwritten with C:\Program Files\Java\jre1.8.0_101
2021-04-13 21:13:15,843 INFO metabase.util :: Maximum memory available to JVM: 3.5 GB
2021-04-13 21:13:25,682 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance.
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2021-04-13 21:13:33,369 INFO metabase.core ::
Metabase v0.38.4 (057b6bb release-x.38.x)

Copyright ? 2021 Metabase, Inc.

Metabase Enterprise Edition extensions are NOT PRESENT.
2021-04-13 21:13:33,378 WARN metabase.core :: WARNING: You have enabled namespace tracing, which could log sensitive information like db passwords.
2021-04-13 21:13:33,378 INFO metabase.core :: Starting Metabase in STANDALONE mode
2021-04-13 21:13:33,412 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

2021-04-13 21:13:33,447 INFO metabase.core :: Starting Metabase version v0.38.4 (057b6bb release-x.38.x) ...
2021-04-13 21:13:33,472 INFO metabase.core :: System info:
 {"file.encoding" "GBK",
 "java.runtime.name" "Java(TM) SE Runtime Environment",
 "java.runtime.version" "1.8.0_101-b13",
 "java.vendor" "Oracle Corporation",
 "java.vendor.url" "http://java.oracle.com/",
 "java.version" "1.8.0_101",
 "java.vm.name" "Java HotSpot(TM) 64-Bit Server VM",
 "java.vm.version" "25.101-b13",
 "os.name" "Windows 10",
 "os.version" "10.0",
 "user.language" "zh",
 "user.timezone" "Asia/Shanghai"}

2021-04-13 21:13:33,477 INFO metabase.plugins :: Loading plugins in G:\metabase-web\plugins...
2021-04-13 21:13:33,884 INFO plugins.classloader :: Added URL file:/G:/metabase-web/plugins/ojdbc8.jar to classpath
2021-04-13 21:13:33,886 INFO plugins.classloader :: Added URL file:/G:/metabase-web/plugins/vertica-jdbc-8.0.1-6.jar to classpath
2021-04-13 21:13:33,925 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
2021-04-13 21:13:33,927 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
2021-04-13 21:13:33,933 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase BigQuery Driver"]
2021-04-13 21:13:33,941 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
2021-04-13 21:13:33,942 INFO driver.impl :: Registered driver :druid
2021-04-13 21:13:33,948 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :google...
2021-04-13 21:13:33,949 INFO driver.impl :: Registered abstract driver :google
2021-04-13 21:13:33,950 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
2021-04-13 21:13:33,951 DEBUG plugins.initialize :: Dependencies satisfied; these plugins will now be loaded: ["Metabase BigQuery Driver"]
2021-04-13 21:13:33,952 WARN plugins.lazy-loaded-driver :: Warning: plugin manifest for :bigquery does not include connection properties
2021-04-13 21:13:33,953 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery...
2021-04-13 21:13:34,056 INFO driver.impl :: Registered abstract driver :sql
Load driver :sql took 106.0 ms
2021-04-13 21:13:34,061 INFO driver.impl :: Registered driver :bigquery (parents: [:sql :google])
2021-04-13 21:13:34,067 INFO plugins.dependencies :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
2021-04-13 21:13:34,068 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
2021-04-13 21:13:34,069 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
2021-04-13 21:13:34,070 INFO driver.impl :: Registered driver :googleanalytics (parents: [:google])
2021-04-13 21:13:34,078 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
2021-04-13 21:13:34,078 INFO driver.impl :: Registered driver :mongo
2021-04-13 21:13:34,089 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? true
2021-04-13 21:13:34,090 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :oracle...
2021-04-13 21:13:34,137 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql])
Load driver :sql-jdbc took 50.5 ms
2021-04-13 21:13:34,142 INFO driver.impl :: Registered driver :oracle (parents: [:sql-jdbc])
2021-04-13 21:13:34,150 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto...
2021-04-13 21:13:34,151 INFO driver.impl :: Registered driver :presto (parents: [:sql])
2021-04-13 21:13:34,162 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
2021-04-13 21:13:34,173 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc])
Load driver :postgres took 20.5 ms
2021-04-13 21:13:34,184 INFO driver.impl :: Registered driver :redshift (parents: [:postgres])
2021-04-13 21:13:34,204 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
2021-04-13 21:13:34,208 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc])
2021-04-13 21:13:34,368 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
2021-04-13 21:13:34,370 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc])
2021-04-13 21:13:34,371 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
2021-04-13 21:13:34,377 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like])
2021-04-13 21:13:34,381 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
2021-04-13 21:13:34,382 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc])
2021-04-13 21:13:34,391 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
2021-04-13 21:13:34,392 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc])
2021-04-13 21:13:34,401 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? true
2021-04-13 21:13:34,402 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :vertica...
2021-04-13 21:13:34,408 INFO driver.impl :: Registered driver :vertica (parents: [:sql-jdbc])
2021-04-13 21:13:34,413 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc])
2021-04-13 21:13:34,429 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc])
2021-04-13 21:13:34,442 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2021-04-13 21:13:34,446 INFO db.setup :: Verifying mysql Database Connection ...
2021-04-13 21:13:34,523 ERROR metabase.core :: Metabase Initialization FAILED
clojure.lang.ExceptionInfo: Unable to connect to Metabase mysql DB. {}
        at metabase.db.setup$fn__34540$verify_db_connection__34545$fn__34546$fn__34547.invoke(setup.clj:102)
        at metabase.db.setup$fn__34540$verify_db_connection__34545$fn__34546.invoke(setup.clj:100)
        at metabase.db.setup$fn__34540$verify_db_connection__34545.invoke(setup.clj:94)
        at metabase.db.setup$setup_db_BANG_$fn__34575$fn__34576.invoke(setup.clj:142)
        at metabase.util$do_with_us_locale.invokeStatic(util.clj:675)
        at metabase.util$do_with_us_locale.invoke(util.clj:661)
        at metabase.db.setup$setup_db_BANG_$fn__34575.invoke(setup.clj:141)
        at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:140)
        at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:136)
        at metabase.db$setup_db_BANG_$fn__34589.invoke(db.clj:61)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:56)
        at metabase.db$setup_db_BANG_.invoke(db.clj:51)
        at metabase.core$init_BANG_.invokeStatic(core.clj:94)
        at metabase.core$init_BANG_.invoke(core.clj:73)
        at metabase.core$start_normally.invokeStatic(core.clj:138)
        at metabase.core$start_normally.invoke(core.clj:132)
        at metabase.core$_main.invokeStatic(core.clj:171)
        at metabase.core$_main.doInvoke(core.clj:165)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=localhost)(port=3306)(type=master) : (conn=17) Access denied for user 'root'@'localhost' (using password: YES)
Current charset is GBK. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:66)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1372)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
        at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
        at org.mariadb.jdbc.Driver.connect(Driver.java:89)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
        at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:175)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:172)
        at metabase.db.setup$fn__34540$verify_db_connection__34545$fn__34546$fn__34547.invoke(setup.clj:100)
        ... 21 more
Caused by: java.sql.SQLInvalidAuthorizationSpecException: (conn=17) Access denied for user 'root'@'localhost' (using password: YES)
Current charset is GBK. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:66)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:187)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:760)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:546)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1367)
        ... 39 more
2021-04-13 21:13:34,536 INFO metabase.core :: Metabase Shutting Down ...
2021-04-13 21:13:34,538 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2021-04-13 21:13:34,545 INFO metabase.core :: Metabase Shutdown COMPLETE
```

**To Reproduce**
1. Write command `java -Duser.timezone=Asia/Shanghai -DMB_DB_CONNECTION_URI="jdbc:mysql://localhost:3306/metabase?user=root&password=*^@)*))" -jar metabase.jar`
2. Save as `run.bat`
3. Execute run.bat in the directory where the run.bat file is located
4. print error

**Expected behavior**
Migrating from using the H2 database to MySQL5.7

**Screenshots**

**Information about your Metabase Installation:**
- Chrome 88.0.4324.104
- Windows 10 Pro
- MySQL5.7
- Metabase version: v0.38.4
- Metabase hosting environment: Windows Server 2016 Datacenter、Windows 10 Pro
- Metabase internal database: H2
```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "GBK",
    "java.runtime.name": "Java(TM) SE Runtime Environment",
    "java.runtime.version": "1.8.0_101-b13",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_101",
    "java.vm.name": "Java HotSpot(TM) 64-Bit Server VM",
    "java.vm.version": "25.101-b13",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "zh",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.38.4",
      "date": "2021-04-08",
      "branch": "release-x.38.x",
      "hash": "057b6bb"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    }
  }
}
```

**Additional context**
### `report_card.result_metadata` was mentioned many times in the question, but I did not find information about it in the document. Does this mean that there is a table called `report_card` in the database, and a column called `result_metadata` exists in the `report_card` table?

This problem has bothered me for many days, thank you very much

**Comment by flamber** [comment]
Hi @8debug 

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

It gives you this error:
`Access denied for user 'root'@'localhost' (using password: YES)`
`Current charset is GBK. If password has been set using other charset, consider using option 'passwordCharacterEncoding'`

Make sure that you are using the correct password the MySQL user `'root'@'localhost'`

**Comment by 8debug** [comment]
> Hi @8debug
> 
> Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
> 
> It gives you this error:
> `Access denied for user 'root'@'localhost' (using password: YES)`
> `Current charset is GBK. If password has been set using other charset, consider using option 'passwordCharacterEncoding'`
> 
> Make sure that you are using the correct password the MySQL user `'root'@'localhost'`

All database information is correct. My database password is `*^%@)*))`. With the same information, I can connect to the database using `DataGrip`.

In addition, may I ask if my understanding of `report_card.result_metadata` is correct?

**Comment by flamber** [comment]
@8debug Make sure to URL encode special characters:
https://stackoverflow.com/questions/13984567/how-to-escape-special-characters-in-mysql-jdbc-connection-string
The password `*^%@)*))` should probably be `%2A%5E%40%29%2A%29%29`
Yes, there's a table called `report_card` in the Metabase application database with a column called `result_metadata`
