### ISSUE TITLE
MySQL connection wont work starting from version 39.0.1

### ISSUE THREAD

**Issue by fballan93** [metabase/metabase#15816]
meta abse wont connect to my database after upgrading to 0.39.0.1 . I have a Azure instance running version 38 for a long time now i changed nothing in both the MySQL server and azure app service setting . 

![CleanShot 2021-04-26 at 22 12 17@2x](https://user-images.githubusercontent.com/9093101/116137698-889df000-a6dc-11eb-8cb6-c8adc77a948e.png)

```
[780f4060-b3b2-42a3-97af-185c7f713a20] 2021-04-26T22:01:20+03:00 INFO metabase.driver.mysql You may need to add trustServerCertificate=true to the additional connection options to connect with SSL.
[780f4060-b3b2-42a3-97af-185c7f713a20] 2021-04-26T22:01:20+03:00 ERROR metabase.driver.util Database connection error
java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=server-name.database.azure.com)(port=3306)(type=master) : Socket fail to connect to host:server-name.database.azure.com, port:3306. server-name.database.azure.com
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1372)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:89)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:199)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:196)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:207)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:203)
	at metabase.driver.sql_jdbc$fn__80855.invokeStatic(sql_jdbc.clj:35)
	at metabase.driver.sql_jdbc$fn__80855.invoke(sql_jdbc.clj:33)
	at metabase.driver.mysql$fn__79963.invokeStatic(mysql.clj:72)
	at metabase.driver.mysql$fn__79963.invoke(mysql.clj:68)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__29688.invoke(util.clj:34)
	at metabase.util$do_with_timeout$fn__15624.invoke(util.clj:346)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:server-name.database.azure.com, port:3306. server-name.database.azure.com
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:183)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:255)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:512)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1367)
	... 32 more
Caused by: java.net.UnknownHostException: server-name.database.azure.com
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:250)
	... 34 more
[780f4060-b3b2-42a3-97af-185c7f713a20] 2021-04-26T22:01:20+03:00 ERROR metabase.api.database Cannot connect to Database
java.lang.Exception: Could not connect to address=(host=server-name.database.azure.com)(port=3306)(type=master) : Socket fail to connect to host:server-name.database.azure.com, port:3306. server-name.database.azure.com
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:39)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:22)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.api.database$test_database_connection.invokeStatic(database.clj:396)
	at metabase.api.database$test_database_connection.doInvoke(database.clj:386)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.api.database$fn__63675$test_connection_details__63680$fn__63681.invoke(database.clj:435)
	at metabase.api.database$fn__63675$test_connection_details__63680.invoke(database.clj:425)
	at metabase.api.database$fn__63705.invokeStatic(database.clj:462)
	at metabase.api.database$fn__63705.invoke(database.clj:449)
	at compojure.core$wrap_response$fn__1996.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__1980.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__1985.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:151)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__75587.invoke(auth.clj:14)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at compojure.core$make_context$handler__2036.invoke(core.clj:287)
	at compojure.core$make_context$fn__2038.invoke(core.clj:296)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$make_context$fn__2038.invoke(core.clj:297)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at metabase.api.routes$fn__75709$fn__75711.invoke(routes.clj:70)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.server.routes$fn__77980$fn__77981.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at compojure.core$make_context$handler__2036.invoke(core.clj:287)
	at compojure.core$make_context$fn__2038.invoke(core.clj:296)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__1989.invoke(core.clj:153)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008$f__2009$respond_SINGLEQUOTE___2010.invoke(core.clj:197)
	at metabase.server.routes$fn__77968$fn__77970.invoke(routes.clj:41)
	at compojure.core$routes$fn__2008$f__2009.invoke(core.clj:198)
	at compojure.core$routes$fn__2008.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__75700.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__75697.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__77896$fn__77897.invoke(log.clj:195)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__77896.invoke(log.clj:189)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__77532.invoke(browser_cookie.clj:30)
	at metabase.server.middleware.security$add_security_headers$fn__75662.invoke(security.clj:142)
	at metabase.server.middleware.json$wrap_json_body$fn__77677.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__77695.invoke(json.clj:98)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__78237.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__78253.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__35500.invoke(misc.clj:58)
	at metabase.server.middleware.session$bind_current_user$fn__42472$fn__42473.invoke(session.clj:248)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:229)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:221)
	at metabase.server.middleware.session$bind_current_user$fn__42472.invoke(session.clj:247)
	at metabase.server.middleware.session$wrap_current_user_info$fn__42459.invoke(session.clj:207)
	at metabase.server.middleware.session$wrap_session_id$fn__42445.invoke(session.clj:153)
	at metabase.server.middleware.auth$wrap_api_key$fn__75595.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__78157.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__35483.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__35508.invoke(misc.clj:75)
	at ring.middleware.gzip$wrap_gzip$fn__78199.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__35511.invoke(misc.clj:92)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__77913.invoke(ssl.clj:48)
	at metabase.server$async_proxy_handler$fn__77476.invoke(server.clj:71)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=server-name.database.azure.com)(port=3306)(type=master) : Socket fail to connect to host:server-name.database.azure.com, port:3306. server-name.database.azure.com
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1372)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:89)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:199)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:196)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:207)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:203)
	at metabase.driver.sql_jdbc$fn__80855.invokeStatic(sql_jdbc.clj:35)
	at metabase.driver.sql_jdbc$fn__80855.invoke(sql_jdbc.clj:33)
	at metabase.driver.mysql$fn__79963.invokeStatic(mysql.clj:72)
	at metabase.driver.mysql$fn__79963.invoke(mysql.clj:68)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__29688.invoke(util.clj:34)
	at metabase.util$do_with_timeout$fn__15624.invoke(util.clj:346)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:server-name.database.azure.com, port:3306. server-name.database.azure.com
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:183)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:255)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:512)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1367)
	... 32 more
Caused by: java.net.UnknownHostException: server-name.database.azure.com
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:250)
	... 34 more
[780f4060-b3b2-42a3-97af-185c7f713a20] 2021-04-26T22:01:20+03:00 DEBUG metabase.server.middleware.log POST /api/database 400 120.5 ms (0 DB calls) 
{:valid false,
 :dbname
 "Could not connect to address=(host=server-name.database.azure.com)(port=3306)(type=master) : Socket fail to connect to host:server-name.database.azure.com, port:3306. server-name.database.azure.com",
 :message
 "Could not connect to address=(host=server-name.database.azure.com)(port=3306)(type=master) : Socket fail to connect to host:server-name.database.azure.com, port:3306. server-name.database.azure.com"}

[780f4060-b3b2-42a3-97af-185c7f713a20] 2021-04-26T22:01:20+03:00 DEBUG metabase.server.middleware.log GET /api/database 200 8.0 ms (3 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (52 total active threads) Queries in flight: 0 (0 queued)
[780f4060-b3b2-42a3-97af-185c7f713a20] 2021-04-26T22:04:50+03:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 15.5 ms (1 DB calls) App DB connections: 0/4 Jetty threads: 4/50 (3 idle, 0 queued) (47 total active threads) Queries in flight: 0 (0 queued)
```

**Comment by flamber** [comment]
Hi @fballan93 
Please post which version specifically you were using before, since Metabase 0.38.x has only been available since February 16th.
And include "Diagnostic Info" from Admin > Troubleshooting.
Which version of MySQL are you using?

**Comment by fballan93** [comment]
I used all the versions of 38 with none have this issue . 
here is my diagnostics . and nothing out of the ordinary when i checked it too . please note that metabase DB is connecting to the same server with no issues too . 

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.49",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "5.4.0-1031-azure",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.21"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-04-20",
      "tag": "v0.39.0.1",
      "branch": "release-x.39.x",
      "hash": "47bb5f2"
    },
    "settings": {
      "report-timezone": null
    }
  }
}

**Comment by fballan93** [comment]
I was able to fix it Thank you . i followed some instruction on the metabase form on how to add and bind user to 0.0.0.0
