### ISSUE TITLE
Metabase try to connect to primary member of mongodb replica set even readPreference is set to secondary.

### ISSUE THREAD

**Issue by yog27ray** [metabase/metabase#15862]
I have 3 MongoDB replica members set up. With one member having a tag of "metabase:true". I am using an on-premises Metabase (0.39.1). Below is setup architure.

1. Server1: db1 (primary)
2. Server2: db2 (secondary)
3. Server3: db3 (secondary, tag: { metabase: true } ).
4. Server4: metabase-on-premises.

db3 is allowed to take request from Server4(Metabase) but db1 and db2 are not allowed to take requests from Metabase due to security and performance concerns.

Below is connection parameter provided in metabase add database page.
Host: db3
Connection Option: replicaSet=replicaName&ssl=true&readPreference=secondary&readPreferenceTags=metabase:true

Now the problem is when doing "Sync database schema now" in logs I can see exception mentioning unable to connect to the server with readPreference as primary. Error log are pasted below

```
Apr 29 13:50:28 server4 metabase[14464]: 2021-04-29 13:50:28,200 INFO sync.util :: STARTING: step 'sync-timezone' for mongo Database 11 'Notify'
Apr 29 13:50:28 server4 metabase[14464]: 2021-04-29 13:50:28,200 INFO sync.util :: FINISHED: step 'sync-timezone' for mongo Database 11 'Notify' (335.9 µs)
Apr 29 13:50:28 server4 metabase[14464]: 2021-04-29 13:50:28,200 INFO sync.util :: STARTING: step 'sync-tables' for mongo Database 11 'Notify'
Apr 29 13:50:31 server4 metabase[14464]: 2021-04-29 13:50:31,210 INFO sync.util :: FINISHED: step 'sync-tables' for mongo Database 11 'Notify' (3.0 s)
Apr 29 13:50:31 server4 metabase[14464]: 2021-04-29 13:50:31,210 INFO sync.util :: STARTING: step 'sync-fields' for mongo Database 11 'Notify'
Apr 29 13:50:31 server4 metabase[14464]: 2021-04-29 13:50:31,212 INFO sync.util :: FINISHED: step 'sync-fields' for mongo Database 11 'Notify' (1.3 ms)
Apr 29 13:50:31 server4 metabase[14464]: 2021-04-29 13:50:31,212 INFO sync.util :: STARTING: step 'sync-fks' for mongo Database 11 'Notify'
Apr 29 13:50:31 server4 metabase[14464]: 2021-04-29 13:50:31,213 INFO sync.util :: FINISHED: step 'sync-fks' for mongo Database 11 'Notify' (1.0 ms)
Apr 29 13:50:31 server4 metabase[14464]: 2021-04-29 13:50:31,214 INFO sync.util :: STARTING: step 'sync-metabase-metadata' for mongo Database 11 'Notify'
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,215 WARN sync.util :: Error syncing _metabase_metadata table for mongo Database 11 'Notify'
Apr 29 13:50:34 server4 metabase[14464]: com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=REPLICA_SET, servers=[{address=db1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}, {address=db2:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}, {address=db2.com:27007, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}, {address=db3:27017, type=REPLICA_SET_SECONDARY, TagSet{[Tag{name='metabase', value='true'}]}, roundTripTime=1.0 ms, state=CONNECTED}]
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:401)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.internal.connection.BaseCluster.selectServer(BaseCluster.java:120)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.internal.connection.MultiServerCluster.selectServer(MultiServerCluster.java:54)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:99)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:95)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:82)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.client.internal.ClientSessionBinding.getReadConnectionSource(ClientSessionBinding.java:77)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:404)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.operation.ListCollectionsOperation.execute(ListCollectionsOperation.java:206)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.operation.ListCollectionsOperation.execute(ListCollectionsOperation.java:82)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:132)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:86)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:110)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.client.internal.MappingIterable.forEach(MappingIterable.java:54)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.client.internal.MappingIterable.into(MappingIterable.java:64)
Apr 29 13:50:34 server4 metabase[14464]:         at com.mongodb.DB.getCollectionNames(DB.java:295)
Apr 29 13:50:34 server4 metabase[14464]:         at monger.db$get_collection_names.invokeStatic(db.clj:62)
Apr 29 13:50:34 server4 metabase[14464]:         at monger.db$get_collection_names.invoke(db.clj:59)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo$eval2344$fn__2345$f__1655__auto____2346.invoke(mongo.clj:177)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo$eval2344$fn__2345.invoke(mongo.clj:176)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.lang.MultiFn.invoke(MultiFn.java:234)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.fetch_metadata$fn__61425$db_metadata__61430$fn__61431.invoke(fetch_metadata.clj:13)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.fetch_metadata$fn__61425$db_metadata__61430.invoke(fetch_metadata.clj:10)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.sync_metadata.metabase_metadata$fn__62581$sync_metabase_metadata_BANG___62586$fn__62587$fn__62588.invoke(metabase_metadata.clj:96)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:151)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.sync_metadata.metabase_metadata$fn__62581$sync_metabase_metadata_BANG___62586$fn__62587.invoke(metabase_metadata.clj:92)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.sync_metadata.metabase_metadata$fn__62581$sync_metabase_metadata_BANG___62586.invoke(metabase_metadata.clj:87)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.lang.AFn.applyToHelper(AFn.java:154)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.lang.AFn.applyTo(AFn.java:144)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.core$apply.invokeStatic(core.clj:667)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.core$apply.invoke(core.clj:660)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$fn__39944$run_step_with_metadata__39949$fn__39953$fn__39955.doInvoke(util.clj:352)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.lang.RestFn.invoke(RestFn.java:397)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:116)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:113)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$fn__39944$run_step_with_metadata__39949$fn__39953.invoke(util.clj:347)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$fn__39944$run_step_with_metadata__39949.invoke(util.clj:342)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$fn__40135$run_sync_operation__40140$fn__40141$fn__40149.invoke(util.clj:441)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$fn__40135$run_sync_operation__40140$fn__40141.invoke(util.clj:439)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$fn__40135$run_sync_operation__40140.invoke(util.clj:433)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.sync_metadata$fn__62974$sync_db_metadata_BANG___62979$fn__62980$fn__62981.invoke(sync_metadata.clj:49)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:151)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:147)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.core$partial$fn__5839.invoke(core.clj:2623)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo$eval2264$fn__2265$f__1655__auto____2266.invoke(mongo.clj:92)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo.util$_with_mongo_connection$fn__1646.invoke(util.clj:225)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:181)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:170)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:219)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo.util$_with_mongo_connection.invoke(util.clj:214)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo$eval2264$fn__2265.invoke(mongo.clj:91)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.lang.MultiFn.invoke(MultiFn.java:239)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$sync_in_context$fn__39856.invoke(util.clj:135)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_db_logging_disabled$fn__39853.invoke(util.clj:126)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_start_and_finish_logging$fn__39842.invoke(util.clj:111)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_sync_events$fn__39837.invoke(util.clj:85)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_duplicate_ops_prevented$fn__39828.invoke(util.clj:64)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:169)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_sync_operation.invoke(util.clj:166)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.sync_metadata$fn__62974$sync_db_metadata_BANG___62979$fn__62980.invoke(sync_metadata.clj:48)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.sync_metadata$fn__62974$sync_db_metadata_BANG___62979.invoke(sync_metadata.clj:45)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.api.database$fn__63770$fn__63772.invoke(database.clj:621)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.lang.AFn.call(AFn.java:18)
Apr 29 13:50:34 server4 metabase[14464]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Apr 29 13:50:34 server4 metabase[14464]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Apr 29 13:50:34 server4 metabase[14464]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Apr 29 13:50:34 server4 metabase[14464]:         at java.base/java.lang.Thread.run(Thread.java:829)
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,216 INFO sync.util :: FINISHED: step 'sync-metabase-metadata' for mongo Database 11 'Notify' (3.0 s)
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,217 WARN sync.util :: Error running sync step
Apr 29 13:50:34 server4 metabase[14464]: java.lang.ClassCastException: class com.mongodb.MongoTimeoutException cannot be cast to class clojure.lang.Associative (com.mongodb.MongoTimeoutException is in unnamed module of loader clojure.lang.DynamicClassLoader @4abf3f0; clojure.lang.Associative is in unnamed module of loader 'app')
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.lang.RT.assoc(RT.java:827)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.core$assoc__5416.invokeStatic(core.clj:193)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.core$assoc__5416.doInvoke(core.clj:190)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.lang.RestFn.invoke(RestFn.java:573)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$fn__39944$run_step_with_metadata__39949$fn__39953.invoke(util.clj:356)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$fn__39944$run_step_with_metadata__39949.invoke(util.clj:342)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$fn__40135$run_sync_operation__40140$fn__40141$fn__40149.invoke(util.clj:441)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$fn__40135$run_sync_operation__40140$fn__40141.invoke(util.clj:439)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$fn__40135$run_sync_operation__40140.invoke(util.clj:433)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.sync_metadata$fn__62974$sync_db_metadata_BANG___62979$fn__62980$fn__62981.invoke(sync_metadata.clj:49)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:151)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:147)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.core$partial$fn__5839.invoke(core.clj:2623)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo$eval2264$fn__2265$f__1655__auto____2266.invoke(mongo.clj:92)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo.util$_with_mongo_connection$fn__1646.invoke(util.clj:225)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:181)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:170)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:219)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo.util$_with_mongo_connection.invoke(util.clj:214)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.driver.mongo$eval2264$fn__2265.invoke(mongo.clj:91)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.lang.MultiFn.invoke(MultiFn.java:239)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$sync_in_context$fn__39856.invoke(util.clj:135)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_db_logging_disabled$fn__39853.invoke(util.clj:126)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_start_and_finish_logging$fn__39842.invoke(util.clj:111)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_sync_events$fn__39837.invoke(util.clj:85)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$with_duplicate_ops_prevented$fn__39828.invoke(util.clj:64)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:169)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.util$do_sync_operation.invoke(util.clj:166)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.sync_metadata$fn__62974$sync_db_metadata_BANG___62979$fn__62980.invoke(sync_metadata.clj:48)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.sync.sync_metadata$fn__62974$sync_db_metadata_BANG___62979.invoke(sync_metadata.clj:45)
Apr 29 13:50:34 server4 metabase[14464]:         at metabase.api.database$fn__63770$fn__63772.invoke(database.clj:621)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
Apr 29 13:50:34 server4 metabase[14464]:         at clojure.lang.AFn.call(AFn.java:18)
Apr 29 13:50:34 server4 metabase[14464]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Apr 29 13:50:34 server4 metabase[14464]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Apr 29 13:50:34 server4 metabase[14464]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Apr 29 13:50:34 server4 metabase[14464]:         at java.base/java.lang.Thread.run(Thread.java:829)
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,245 INFO sync.util :: FINISHED: Sync metadata for mongo Database 11 'Notify' (6.0 s)
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,245 INFO sync.util :: STARTING: Analyze data for mongo Database 11 'Notify'
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,248 INFO sync.util :: STARTING: step 'fingerprint-fields' for mongo Database 11 'Notify'
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,248 INFO sync.util :: FINISHED: step 'fingerprint-fields' for mongo Database 11 'Notify' (306.7 µs)
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,249 INFO sync.util :: STARTING: step 'classify-fields' for mongo Database 11 'Notify'
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,249 INFO sync.util :: FINISHED: step 'classify-fields' for mongo Database 11 'Notify' (182.1 µs)
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,249 INFO sync.util :: STARTING: step 'classify-tables' for mongo Database 11 'Notify'
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,250 INFO sync.util :: FINISHED: step 'classify-tables' for mongo Database 11 'Notify' (189.3 µs)
Apr 29 13:50:34 server4 metabase[14464]: 2021-04-29 13:50:34,306 INFO sync.util :: FINISHED: Analyze data for mongo Database 11 'Notify' (60.9 ms)
```

Apr 29 13:50:34 server4 metabase[14464]: com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}

Even I have specified readPrefence as second still metabase is trying to connect with primary server.

**Comment by flamber** [comment]
Hi @yog27ray 
Is this a new problem? Since which version then?
While I can see that it's trying to do connection to db1+db2, it's more difficult to see from the logs if this actually causes any problems, since it seems like syncing still completes, because it can connect to db3.
Are you seeing any problems, besides a noisy log?
Related to #7526

**Comment by yog27ray** [comment]
Hi @flamber 
No, I am facing this issue for a long time. Earlier, I was not adding a tag in MongoDB URI options, so I didn't consider it a bug, but now I was getting the error even after adding it. In logs syncing of _metabase_metadata gives an error, is storing something in the database? because database connection user has only read permission over the collection. Even in the logs syncing of tables is completed, table names are still not displayed in Metabase.

<img width="1279" alt="Screen Shot 2021-05-04 at 8 04 45 AM" src="https://user-images.githubusercontent.com/9247177/116955726-fd5ec480-acb0-11eb-87f4-cad860850c27.png">

**Comment by paoliniluis** [comment]
Hi @yog27ray, can you post here your connectionstring redacting the sensitive data? I think I know what's going on but just wanted to double check

**Comment by paoliniluis** [comment]
@yog27ray does this still happens? please reopen the issue if it's still there
