### ISSUE TITLE
Redshift queries intermittently fail with "cannot drop active portal"

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#16024]
Some queries are failing with "ERROR: cannot drop active portal".

Some observations:
- It's intermittent, but seems to go on "streaks". When it's failing, all queries fail.
- I restarted the Redshift cluster once and it resolved, but it's also resolved without a restart so that may have been coincidental.
- It's specific to a MB instance. While I'm getting it repeatedly on stats, it works fine locally.
- I don't see anything in the STL_QUERIES or STL_ERROR tables (internal errors) pop up with failed queries.

<details><summary>This is a sync stacktrace but it happens for non-sync queries too.</summary>

```
com.amazon.redshift.util.RedshiftException: ERROR: cannot drop active portal
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2579)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2253)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1880)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1872)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:376)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeCachedSql(RedshiftStatementImpl.java:362)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:339)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:329)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
	at metabase.driver.sql_jdbc.execute$set_time_zone_if_supported_BANG_.invokeStatic(execute.clj:161)
	at metabase.driver.sql_jdbc.execute$set_time_zone_if_supported_BANG_.invoke(execute.clj:146)
	at metabase.driver.redshift$eval2668$fn__2669.invoke(redshift.clj:135)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:475)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:472)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:463)
	at metabase.driver.sql_jdbc$fn__81234.invokeStatic(sql_jdbc.clj:54)
	at metabase.driver.sql_jdbc$fn__81234.invoke(sql_jdbc.clj:52)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:68)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:66)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47236.invoke(mbql_to_native.clj:25)
	at metabase.query_processor.middleware.check_features$check_features$fn__46478.invoke(check_features.clj:39)
	at metabase.query_processor.middleware.limit$limit$fn__47222.invoke(limit.clj:37)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__45930.invoke(cache.clj:211)
	at metabase.query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47482.invoke(optimize_temporal_filters.clj:204)
	at metabase.query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49412.invoke(validate_temporal_bucketing.clj:50)
	at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45049.invoke(auto_parse_filter_values.clj:43)
	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41394.invoke(wrap_value_literals.clj:161)
	at metabase.query_processor.middleware.annotate$add_column_info$fn__41269.invoke(annotate.clj:598)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__46350.invoke(permissions.clj:81)
	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48340.invoke(pre_alias_aggregations.clj:40)
	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46551.invoke(cumulative_aggregations.clj:60)
	at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48639.invoke(resolve_joined_fields.clj:102)
	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__48952.invoke(resolve_joins.clj:171)
	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44625.invoke(add_implicit_joins.clj:190)
	at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__47186.invoke(large_int_id.clj:59)
	at metabase.query_processor.middleware.format_rows$format_rows$fn__47167.invoke(format_rows.clj:74)
	at metabase.query_processor.middleware.desugar$desugar$fn__46617.invoke(desugar.clj:21)
	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__45436.invoke(binning.clj:227)
	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__46153.invoke(resolve_fields.clj:34)
	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__44274.invoke(add_dimension_projections.clj:314)
	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44503.invoke(add_implicit_clauses.clj:147)
	at metabase.query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49361.invoke(upgrade_field_literals.clj:40)
	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44788.invoke(add_source_metadata.clj:123)
	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48514.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)
	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__44996.invoke(auto_bucket_datetimes.clj:147)
	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46200.invoke(resolve_source_table.clj:45)
	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__48322.invoke(parameters.clj:111)
	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46252.invoke(resolve_referenced.clj:79)
	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__46873.invoke(expand_macros.clj:155)
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__44797.invoke(add_timezone_info.clj:15)
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49314.invoke(splice_params_in_response.clj:32)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48525$fn__48529.invoke(resolve_database_and_driver.clj:31)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:60)
	at metabase.driver$do_with_driver.invoke(driver.clj:56)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48525.invoke(resolve_database_and_driver.clj:25)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47113.invoke(fetch_source_query.clj:274)
	at metabase.query_processor.middleware.store$initialize_store$fn__49323$fn__49324.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:42)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.query_processor.middleware.store$initialize_store$fn__49323.invoke(store.clj:10)
	at metabase.query_processor.middleware.validate$validate_query$fn__49368.invoke(validate.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__47249.invoke(normalize_query.clj:22)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44643.invoke(add_rows_truncated.clj:35)
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49299.invoke(results_metadata.clj:143)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37972$thunk__37973.invoke(reducible.clj:103)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37972.invoke(reducible.clj:109)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___37981$fn__37984.invoke(reducible.clj:135)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___37981.invoke(reducible.clj:134)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:148)
	at metabase.query_processor$process_query.doInvoke(query_processor.clj:142)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.db.metadata_queries$fn__60854$table_rows_sample__60863$fn__60866.invoke(metadata_queries.clj:144)
	at metabase.db.metadata_queries$fn__60854$table_rows_sample__60863.invoke(metadata_queries.clj:131)
	at metabase.sync.analyze.fingerprint$fn__60919$fingerprint_table_BANG___60924$fn__60925.invoke(fingerprint.clj:66)
	at metabase.sync.analyze.fingerprint$fn__60919$fingerprint_table_BANG___60924.invoke(fingerprint.clj:46)
	at metabase.sync.analyze.fingerprint$fn__61095$fingerprint_fields_BANG___61100$fn__61101$fn__61102.invoke(fingerprint.clj:180)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:151)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.analyze.fingerprint$fn__61095$fingerprint_fields_BANG___61100$fn__61101.invoke(fingerprint.clj:178)
	at metabase.sync.analyze.fingerprint$fn__61095$fingerprint_fields_BANG___61100.invoke(fingerprint.clj:174)
	at metabase.sync.analyze.fingerprint$fn__61130$fingerprint_fields_for_db_BANG__STAR___61139$fn__61142$fn__61143$fn__61144.invoke(fingerprint.clj:204)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at metabase.sync.analyze.fingerprint$fn__61130$fingerprint_fields_for_db_BANG__STAR___61139$fn__61142$fn__61143.invoke(fingerprint.clj:200)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.sync.analyze.fingerprint$fn__61130$fingerprint_fields_for_db_BANG__STAR___61139$fn__61142.invoke(fingerprint.clj:197)
	at metabase.sync.analyze.fingerprint$fn__61130$fingerprint_fields_for_db_BANG__STAR___61139.invoke(fingerprint.clj:186)
	at metabase.sync.analyze.fingerprint$fn__61130$fingerprint_fields_for_db_BANG__STAR___61139$fn__61140.invoke(fingerprint.clj:191)
	at metabase.sync.analyze.fingerprint$fn__61130$fingerprint_fields_for_db_BANG__STAR___61139.invoke(fingerprint.clj:186)
	at metabase.sync.analyze.fingerprint$fn__61172$fingerprint_fields_for_db_BANG___61177$fn__61178.invoke(fingerprint.clj:218)
	at metabase.sync.analyze.fingerprint$fn__61172$fingerprint_fields_for_db_BANG___61177.invoke(fingerprint.clj:212)
	at metabase.sync.analyze$make_analyze_steps$fn__61329.invoke(analyze.clj:104)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.util$fn__39938$run_step_with_metadata__39943$fn__39947$fn__39949.doInvoke(util.clj:352)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:116)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:113)
	at metabase.sync.util$fn__39938$run_step_with_metadata__39943$fn__39947.invoke(util.clj:347)
	at metabase.sync.util$fn__39938$run_step_with_metadata__39943.invoke(util.clj:342)
	at metabase.sync.util$fn__40129$run_sync_operation__40134$fn__40135$fn__40143.invoke(util.clj:441)
	at metabase.sync.util$fn__40129$run_sync_operation__40134$fn__40135.invoke(util.clj:439)
	at metabase.sync.util$fn__40129$run_sync_operation__40134.invoke(util.clj:433)
	at metabase.sync.analyze$fn__61341$analyze_db_BANG___61346$fn__61347$fn__61348.invoke(analyze.clj:121)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:151)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:147)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver$fn__29647.invokeStatic(driver.clj:527)
	at metabase.driver$fn__29647.invoke(driver.clj:527)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__39850.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__39847.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__39836.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__39831.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__39822.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:169)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:166)
	at metabase.sync.analyze$fn__61341$analyze_db_BANG___61346$fn__61347.invoke(analyze.clj:118)
	at metabase.sync.analyze$fn__61341$analyze_db_BANG___61346.invoke(analyze.clj:113)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:70)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:58)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
```

</details>

**Comment by flamber** [comment]
Almost sure it's the same problem as #8679, where Metabase doesn't close idle connections and leaves them hanging outside of it's pool. Seems to be a problem with ELB/ALB.
The reason why it "resolved itself" is likely because how stats is constantly restarted on every commit.

**Comment by paulrosenzweig** [comment]
@flamber ah good thought! I've seen this happen with <10 connections to the instance. I'm getting that number from the AWS side not MB though. Is that behavior consistent with this bug?

**Comment by flamber** [comment]
Hmmm, I would have been more happy if it was hitting 15 connections, when it was having problems, so perhaps it's different.
But this definitely sounds similar, though it might be a Redshift specific issue, just like we have a Oracle specific issue (15817), which very much resembles #8679, but is triggered by other problems.

**Comment by paoliniluis** [comment]
Most probably due to redshift bugs
https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/CHANGELOG.md

will for sure be fixed if we bump it

**Comment by paoliniluis** [comment]
I will close this as it's no longer being reported
