### ISSUE TITLE
Empty graph

### ISSUE THREAD

**Issue by gruselhaus** [metabase/metabase#16021]
The graph is empty but the best fit line gets displayed

https://metabase.pegasus.de/public/question/2aaa0edd-fd77-4f9f-81c1-66acfb7da5e4

<img width="1134" alt="Bildschirmfoto 2021-05-12 um 22 13 44" src="https://user-images.githubusercontent.com/33380107/118038400-57295380-b36f-11eb-8b2c-76558f73e162.png">

<img width="1557" alt="Bildschirmfoto 2021-05-12 um 22 08 06" src="https://user-images.githubusercontent.com/33380107/118038164-129db800-b36f-11eb-8326-6eccdc4cf2e8.png">
<img width="1557" alt="Bildschirmfoto 2021-05-12 um 22 08 16" src="https://user-images.githubusercontent.com/33380107/118038176-1598a880-b36f-11eb-8026-1eedef6e2072.png">

Metabase 0.39.1

I tested it in Safari 14.1.1 as well as in Chrome 90.0.4430.93 on macOS 11.3

**Comment by paoliniluis** [comment]
Hi, please post reproduction steps, we can't know even where to start with this description

**Comment by gruselhaus** [comment]
The data is summarized by unique values and grouped by date over week. All vertical graphs are not filled with the data, only the row graph works. As you can see the trend line is displayed anyway. In the console, the error appears, as you can see in the screenshot. I think the error appeared with 0.39.x, before that it worked. Here again the corresponding data.

[query_result_2021-05-13T12_14_43.499+02_00.csv](https://github.com/metabase/metabase/files/6471827/query_result_2021-05-13T12_14_43.499%2B02_00.csv)

**Comment by flamber** [comment]
Hi @gruselhaus 
Post "Diagnostic Info" from Admin > Troubleshooting.
And can you go to this address `/api/field/158` and post the output?

**Comment by gruselhaus** [comment]
```{
  "browser-info": {
    "language": "de-de",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_292-heroku-b10",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_292-heroku",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.292-b10",
    "os.name": "Linux",
    "os.version": "4.4.0-1088-aws",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "googleanalytics"
    ],
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.2 (Ubuntu 13.2-1.pgdg20.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.1",
      "date": "2021-04-27",
      "branch": "release-x.39.x",
      "hash": "6beba48"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Comment by gruselhaus** [comment]
Found this as well: 
```
[b428ba13-c00c-4f43-b782-14e8e228fac9] 2021-05-13T02:57:58+02:00 WARN metabase.sync.util Error fingerprinting Tabelle 12 'logs'
com.mongodb.MongoCommandException: Command failed with error 40176 (Location40176): 'Invalid $project :: caused by :: specification contains two conflicting paths. Cannot specify both 'interaction.deferred' and 'interaction': { _id: false, interaction: "$interaction", interaction.deferred: "$interaction.deferred", interaction.type: "$interaction.type", interaction.channelID: "$interaction.channelID", interaction.options: "$interaction.options", interaction.replied: "$interaction.replied", interaction.version: "$interaction.version", interaction.member: "$interaction.member", command.everyone: "$command.everyone", interaction.commandName: "$interaction.commandName", interaction.user: "$interaction.user", interaction.applicationID: "$interaction.applicationID", interaction.guildID: "$interaction.guildID", interaction.commandID: "$interaction.commandID", interaction.id: "$interaction.id" }' on server cluster0-shard-00-02.6ncdj.mongodb.net:27017. The full response is { "operationTime" : { "$timestamp" : { "t" : 1620867477, "i" : 1 } }, "ok" : 0.0, "errmsg" : "Invalid $project :: caused by :: specification contains two conflicting paths. Cannot specify both 'interaction.deferred' and 'interaction': { _id: false, interaction: \"$interaction\", interaction.deferred: \"$interaction.deferred\", interaction.type: \"$interaction.type\", interaction.channelID: \"$interaction.channelID\", interaction.options: \"$interaction.options\", interaction.replied: \"$interaction.replied\", interaction.version: \"$interaction.version\", interaction.member: \"$interaction.member\", command.everyone: \"$command.everyone\", interaction.commandName: \"$interaction.commandName\", interaction.user: \"$interaction.user\", interaction.applicationID: \"$interaction.applicationID\", interaction.guildID: \"$interaction.guildID\", interaction.commandID: \"$interaction.commandID\", interaction.id: \"$interaction.id\" }", "code" : 40176, "codeName" : "Location40176", "$clusterTime" : { "clusterTime" : { "$timestamp" : { "t" : 1620867477, "i" : 1 } }, "signature" : { "hash" : { "$binary" : "DWlLdqBhU1cfh2ACEAvd9zrSsic=", "$type" : "00" }, "keyId" : { "$numberLong" : "6918366219846287362" } } } }
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:242)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:233)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:136)
	at com.mongodb.operation.AggregateOperationImpl$1.call(AggregateOperationImpl.java:193)
	at com.mongodb.operation.AggregateOperationImpl$1.call(AggregateOperationImpl.java:189)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:462)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:406)
	at com.mongodb.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:189)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:295)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:41)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:161)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1502)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1462)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1447)
	at metabase.driver.mongo.execute$aggregate.invokeStatic(execute.clj:114)
	at metabase.driver.mongo.execute$aggregate.invoke(execute.clj:108)
	at metabase.driver.mongo.execute$execute_reducible_query.invokeStatic(execute.clj:163)
	at metabase.driver.mongo.execute$execute_reducible_query.invoke(execute.clj:157)
	at metabase.driver.mongo$eval3376$fn__3377$f__2615__auto____3378.invoke(mongo.clj:225)
	at metabase.driver.mongo$eval3376$fn__3377.invoke(mongo.clj:224)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:68)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:66)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47242.invoke(mbql_to_native.clj:25)
	at metabase.query_processor.middleware.check_features$check_features$fn__46484.invoke(check_features.clj:39)
	at metabase.query_processor.middleware.limit$limit$fn__47228.invoke(limit.clj:37)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__45936.invoke(cache.clj:211)
	at metabase.query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47488.invoke(optimize_temporal_filters.clj:204)
	at metabase.query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49418.invoke(validate_temporal_bucketing.clj:50)
	at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45055.invoke(auto_parse_filter_values.clj:43)
	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41400.invoke(wrap_value_literals.clj:161)
	at metabase.query_processor.middleware.annotate$add_column_info$fn__41275.invoke(annotate.clj:598)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__46356.invoke(permissions.clj:81)
	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48346.invoke(pre_alias_aggregations.clj:40)
	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46557.invoke(cumulative_aggregations.clj:60)
	at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48645.invoke(resolve_joined_fields.clj:102)
	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__48958.invoke(resolve_joins.clj:171)
	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44631.invoke(add_implicit_joins.clj:190)
	at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__47192.invoke(large_int_id.clj:59)
	at metabase.query_processor.middleware.format_rows$format_rows$fn__47173.invoke(format_rows.clj:74)
	at metabase.query_processor.middleware.desugar$desugar$fn__46623.invoke(desugar.clj:21)
	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__45442.invoke(binning.clj:227)
	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__46159.invoke(resolve_fields.clj:34)
	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__44280.invoke(add_dimension_projections.clj:314)
	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44509.invoke(add_implicit_clauses.clj:147)
	at metabase.query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49367.invoke(upgrade_field_literals.clj:40)
	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44794.invoke(add_source_metadata.clj:123)
	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48520.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)
	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45002.invoke(auto_bucket_datetimes.clj:147)
	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46206.invoke(resolve_source_table.clj:45)
	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__48328.invoke(parameters.clj:111)
	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46258.invoke(resolve_referenced.clj:79)
	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__46879.invoke(expand_macros.clj:155)
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__44803.invoke(add_timezone_info.clj:15)
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49320.invoke(splice_params_in_response.clj:32)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48531$fn__48535.invoke(resolve_database_and_driver.clj:31)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:60)
	at metabase.driver$do_with_driver.invoke(driver.clj:56)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48531.invoke(resolve_database_and_driver.clj:25)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47119.invoke(fetch_source_query.clj:274)
	at metabase.query_processor.middleware.store$initialize_store$fn__49329$fn__49330.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:42)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.query_processor.middleware.store$initialize_store$fn__49329.invoke(store.clj:10)
	at metabase.query_processor.middleware.validate$validate_query$fn__49374.invoke(validate.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__47255.invoke(normalize_query.clj:22)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44649.invoke(add_rows_truncated.clj:35)
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49305.invoke(results_metadata.clj:143)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37978$thunk__37979.invoke(reducible.clj:103)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37978.invoke(reducible.clj:109)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___37987$fn__37990.invoke(reducible.clj:135)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___37987.invoke(reducible.clj:134)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:148)
	at metabase.query_processor$process_query.doInvoke(query_processor.clj:142)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.db.metadata_queries$fn__60734$table_rows_sample__60743$fn__60746.invoke(metadata_queries.clj:144)
	at metabase.db.metadata_queries$fn__60734$table_rows_sample__60743.invoke(metadata_queries.clj:131)
	at metabase.sync.analyze.fingerprint$fn__60799$fingerprint_table_BANG___60804$fn__60805.invoke(fingerprint.clj:66)
	at metabase.sync.analyze.fingerprint$fn__60799$fingerprint_table_BANG___60804.invoke(fingerprint.clj:46)
	at metabase.sync.analyze.fingerprint$fn__60975$fingerprint_fields_BANG___60980$fn__60981$fn__60982.invoke(fingerprint.clj:180)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:151)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.analyze.fingerprint$fn__60975$fingerprint_fields_BANG___60980$fn__60981.invoke(fingerprint.clj:178)
	at metabase.sync.analyze.fingerprint$fn__60975$fingerprint_fields_BANG___60980.invoke(fingerprint.clj:174)
	at metabase.sync.analyze.fingerprint$fn__61010$fingerprint_fields_for_db_BANG__STAR___61019$fn__61022$fn__61023$fn__61024.invoke(fingerprint.clj:204)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at metabase.sync.analyze.fingerprint$fn__61010$fingerprint_fields_for_db_BANG__STAR___61019$fn__61022$fn__61023.invoke(fingerprint.clj:200)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.sync.analyze.fingerprint$fn__61010$fingerprint_fields_for_db_BANG__STAR___61019$fn__61022.invoke(fingerprint.clj:197)
	at metabase.sync.analyze.fingerprint$fn__61010$fingerprint_fields_for_db_BANG__STAR___61019.invoke(fingerprint.clj:186)
	at metabase.sync.analyze.fingerprint$fn__61010$fingerprint_fields_for_db_BANG__STAR___61019$fn__61020.invoke(fingerprint.clj:191)
	at metabase.sync.analyze.fingerprint$fn__61010$fingerprint_fields_for_db_BANG__STAR___61019.invoke(fingerprint.clj:186)
	at metabase.sync.analyze.fingerprint$fn__61052$fingerprint_fields_for_db_BANG___61057$fn__61058.invoke(fingerprint.clj:218)
	at metabase.sync.analyze.fingerprint$fn__61052$fingerprint_fields_for_db_BANG___61057.invoke(fingerprint.clj:212)
	at metabase.sync.analyze$make_analyze_steps$fn__61209.invoke(analyze.clj:104)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.util$fn__39944$run_step_with_metadata__39949$fn__39953$fn__39955.doInvoke(util.clj:352)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:116)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:113)
	at metabase.sync.util$fn__39944$run_step_with_metadata__39949$fn__39953.invoke(util.clj:347)
	at metabase.sync.util$fn__39944$run_step_with_metadata__39949.invoke(util.clj:342)
	at metabase.sync.util$fn__40135$run_sync_operation__40140$fn__40141$fn__40149.invoke(util.clj:441)
	at metabase.sync.util$fn__40135$run_sync_operation__40140$fn__40141.invoke(util.clj:439)
	at metabase.sync.util$fn__40135$run_sync_operation__40140.invoke(util.clj:433)
	at metabase.sync.analyze$fn__61221$analyze_db_BANG___61226$fn__61227$fn__61228.invoke(analyze.clj:121)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:151)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:147)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver.mongo$eval3224$fn__3225$f__2615__auto____3226.invoke(mongo.clj:92)
	at metabase.driver.mongo.util$_with_mongo_connection$fn__2606.invoke(util.clj:225)
	at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:181)
	at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:170)
	at metabase.driver.mongo.util$_with_mongo_connection.invokeStatic(util.clj:219)
	at metabase.driver.mongo.util$_with_mongo_connection.invoke(util.clj:214)
	at metabase.driver.mongo$eval3224$fn__3225.invoke(mongo.clj:91)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__39856.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__39853.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__39842.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__39837.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__39828.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:169)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:166)
	at metabase.sync.analyze$fn__61221$analyze_db_BANG___61226$fn__61227.invoke(analyze.clj:118)
	at metabase.sync.analyze$fn__61221$analyze_db_BANG___61226.invoke(analyze.clj:113)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:70)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:58)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
```

**Comment by gruselhaus** [comment]
```
{
  "description": null,
  "database_type": "java.time.Instant",
  "semantic_type": null,
  "table_id": 15,
  "coercion_strategy": null,
  "table": {
    "description": null,
    "entity_type": "entity/GenericTable",
    "schema": null,
    "db": {
      "description": null,
      "features": ["basic-aggregations", "nested-fields", "native-parameters", "case-sensitivity-string-filter-options"],
      "cache_field_values_schedule": "0 0 4 * * ? *",
      "timezone": null,
      "auto_run_queries": true,
      "metadata_sync_schedule": "0 57 * * * ? *",
      "name": "Pegabot Database",
      "caveats": null,
      "is_full_sync": true,
      "updated_at": "2021-02-19T16:12:56.32344Z",
      "details": {
        "use-connection-uri": true,
        "conn-uri": "****************",
        "tunnel-enabled": false,
        "ssl": true
      },
      "is_sample": false,
      "id": 2,
      "is_on_demand": false,
      "options": null,
      "engine": "mongo",
      "refingerprint": null,
      "created_at": "2021-02-15T17:20:15.092753Z",
      "points_of_interest": null
    },
    "show_in_getting_started": false,
    "name": "messages",
    "caveats": null,
    "updated_at": "2021-03-28T23:01:31.163254Z",
    "entity_name": null,
    "active": true,
    "id": 15,
    "db_id": 2,
    "visibility_type": null,
    "field_order": "database",
    "display_name": "Messages",
    "created_at": "2021-02-15T17:20:16.235969Z",
    "points_of_interest": null
  },
  "name": "date",
  "fingerprint_version": 5,
  "has_field_values": "none",
  "settings": null,
  "caveats": null,
  "fk_target_field_id": null,
  "dimensions": [],
  "updated_at": "2021-02-15T17:20:27.279298Z",
  "custom_position": 0,
  "effective_type": "type/Instant",
  "active": true,
  "parent_id": null,
  "id": 158,
  "last_analyzed": "2021-02-15T17:20:30.987975Z",
  "position": 55,
  "visibility_type": "normal",
  "preview_display": true,
  "display_name": "Date",
  "database_position": 55,
  "name_field": null,
  "fingerprint": {
    "global": {
      "distinct-count": 522,
      "nil%": 0
    },
    "type": {
      "type/DateTime": {
        "earliest": "2021-02-12T22:47:11.182Z",
        "latest": "2021-02-15T16:44:23.016Z"
      }
    }
  },
  "created_at": "2021-02-15T17:20:20.398146Z",
  "base_type": "type/Instant",
  "points_of_interest": null
}
```

**Comment by flamber** [comment]
@gruselhaus Okay, this is a strange regression, which only happens querying Mongo, when "Replace missing values"=Nothing/Zero
Closing in favor of #16170
