### ISSUE TITLE
WARN sync.util :: Error fingerprinting Table - Oracle

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#16262]
**Describe the bug**
The structure of the tables does not appear in the data model.

**Logs**
```
[62f37168-3acb-48aa-b752-4de19817030e] 2021-05-27T15:28:41+02:00 WARN metabase.sync.util Error fingerprinting Table 1 526 'HIE.PURTRS'
clojure.lang.ExceptionInfo: Erreur lors de la réduction des lignes de résultats {:type :qp}
	at metabase.query_processor.context.default$default_reducef$fn__37178.invoke(default.clj:60)
	at metabase.query_processor.context.default$default_reducef.invokeStatic(default.clj:57)
	at metabase.query_processor.context.default$default_reducef.invoke(default.clj:48)
	at metabase.query_processor.context$reducef.invokeStatic(context.clj:69)
	at metabase.query_processor.context$reducef.invoke(context.clj:62)
	at metabase.query_processor.context.default$default_runf$respond_STAR___37182.invoke(default.clj:69)
	at metabase.driver.oracle$remove_rownum_column.invokeStatic(oracle.clj:308)
	at metabase.driver.oracle$remove_rownum_column.invoke(oracle.clj:304)
	at clojure.core$partial$fn__5839.invoke(core.clj:2625)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:475)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:462)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:453)
	at metabase.driver.sql_jdbc$fn__80985.invokeStatic(sql_jdbc.clj:54)
	at metabase.driver.sql_jdbc$fn__80985.invoke(sql_jdbc.clj:52)
	at metabase.driver.oracle$eval704$fn__705.invoke(oracle.clj:321)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:68)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:66)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__47305.invoke(mbql_to_native.clj:25)
	at metabase.query_processor.middleware.check_features$check_features$fn__46547.invoke(check_features.clj:39)
	at metabase.query_processor.middleware.limit$limit$fn__47291.invoke(limit.clj:37)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__45999.invoke(cache.clj:211)
	at metabase.query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__47551.invoke(optimize_temporal_filters.clj:204)
	at metabase.query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__49481.invoke(validate_temporal_bucketing.clj:50)
	at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__45118.invoke(auto_parse_filter_values.clj:43)
	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__41435.invoke(wrap_value_literals.clj:161)
	at metabase.query_processor.middleware.annotate$add_column_info$fn__41310.invoke(annotate.clj:605)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__46419.invoke(permissions.clj:81)
	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__48409.invoke(pre_alias_aggregations.clj:40)
	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46620.invoke(cumulative_aggregations.clj:60)
	at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__48708.invoke(resolve_joined_fields.clj:102)
	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__49021.invoke(resolve_joins.clj:171)
	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__44694.invoke(add_implicit_joins.clj:190)
	at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__47255.invoke(large_int_id.clj:59)
	at metabase.query_processor.middleware.format_rows$format_rows$fn__47236.invoke(format_rows.clj:74)
	at metabase.query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__43988.invoke(add_default_temporal_unit.clj:23)
	at metabase.query_processor.middleware.desugar$desugar$fn__46686.invoke(desugar.clj:21)
	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__45505.invoke(binning.clj:227)
	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__46222.invoke(resolve_fields.clj:34)
	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__44343.invoke(add_dimension_projections.clj:314)
	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__44572.invoke(add_implicit_clauses.clj:147)
	at metabase.query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__49430.invoke(upgrade_field_literals.clj:40)
	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__44857.invoke(add_source_metadata.clj:123)
	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__48583.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)
	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__45065.invoke(auto_bucket_datetimes.clj:147)
	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__46269.invoke(resolve_source_table.clj:45)
	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__48391.invoke(parameters.clj:111)
	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46321.invoke(resolve_referenced.clj:79)
	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__46942.invoke(expand_macros.clj:155)
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__44866.invoke(add_timezone_info.clj:15)
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49383.invoke(splice_params_in_response.clj:32)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48594$fn__48598.invoke(resolve_database_and_driver.clj:31)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:60)
	at metabase.driver$do_with_driver.invoke(driver.clj:56)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__48594.invoke(resolve_database_and_driver.clj:25)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47182.invoke(fetch_source_query.clj:274)
	at metabase.query_processor.middleware.store$initialize_store$fn__49392$fn__49393.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:42)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.query_processor.middleware.store$initialize_store$fn__49392.invoke(store.clj:10)
	at metabase.query_processor.middleware.validate$validate_query$fn__49437.invoke(validate.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__47318.invoke(normalize_query.clj:22)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__44712.invoke(add_rows_truncated.clj:35)
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49368.invoke(results_metadata.clj:143)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37989$thunk__37990.invoke(reducible.clj:103)
	at metabase.query_processor.reducible$async_qp$qp_STAR___37989.invoke(reducible.clj:109)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___37998$fn__38001.invoke(reducible.clj:135)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___37998.invoke(reducible.clj:134)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:150)
	at metabase.query_processor$process_query.doInvoke(query_processor.clj:144)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.db.metadata_queries$fn__60810$table_rows_sample__60819$fn__60822.invoke(metadata_queries.clj:144)
	at metabase.db.metadata_queries$fn__60810$table_rows_sample__60819.invoke(metadata_queries.clj:131)
	at metabase.sync.analyze.fingerprint$fn__60875$fingerprint_table_BANG___60880$fn__60881.invoke(fingerprint.clj:66)
	at metabase.sync.analyze.fingerprint$fn__60875$fingerprint_table_BANG___60880.invoke(fingerprint.clj:46)
	at metabase.sync.analyze.fingerprint$fn__61051$fingerprint_fields_BANG___61056$fn__61057$fn__61058.invoke(fingerprint.clj:180)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:151)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.analyze.fingerprint$fn__61051$fingerprint_fields_BANG___61056$fn__61057.invoke(fingerprint.clj:178)
	at metabase.sync.analyze.fingerprint$fn__61051$fingerprint_fields_BANG___61056.invoke(fingerprint.clj:174)
	at metabase.sync.analyze.fingerprint$fn__61086$fingerprint_fields_for_db_BANG__STAR___61095$fn__61098$fn__61099$fn__61100.invoke(fingerprint.clj:204)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at metabase.sync.analyze.fingerprint$fn__61086$fingerprint_fields_for_db_BANG__STAR___61095$fn__61098$fn__61099.invoke(fingerprint.clj:200)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.sync.analyze.fingerprint$fn__61086$fingerprint_fields_for_db_BANG__STAR___61095$fn__61098.invoke(fingerprint.clj:197)
	at metabase.sync.analyze.fingerprint$fn__61086$fingerprint_fields_for_db_BANG__STAR___61095.invoke(fingerprint.clj:186)
	at metabase.sync.analyze.fingerprint$fn__61086$fingerprint_fields_for_db_BANG__STAR___61095$fn__61096.invoke(fingerprint.clj:191)
	at metabase.sync.analyze.fingerprint$fn__61086$fingerprint_fields_for_db_BANG__STAR___61095.invoke(fingerprint.clj:186)
	at metabase.sync.analyze.fingerprint$fn__61128$fingerprint_fields_for_db_BANG___61133$fn__61134.invoke(fingerprint.clj:218)
	at metabase.sync.analyze.fingerprint$fn__61128$fingerprint_fields_for_db_BANG___61133.invoke(fingerprint.clj:212)
	at metabase.sync.analyze$make_analyze_steps$fn__61285.invoke(analyze.clj:104)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.util$fn__39955$run_step_with_metadata__39960$fn__39964$fn__39966.doInvoke(util.clj:352)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:116)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:113)
	at metabase.sync.util$fn__39955$run_step_with_metadata__39960$fn__39964.invoke(util.clj:347)
	at metabase.sync.util$fn__39955$run_step_with_metadata__39960.invoke(util.clj:342)
	at metabase.sync.util$fn__40146$run_sync_operation__40151$fn__40152$fn__40160.invoke(util.clj:441)
	at metabase.sync.util$fn__40146$run_sync_operation__40151$fn__40152.invoke(util.clj:439)
	at metabase.sync.util$fn__40146$run_sync_operation__40151.invoke(util.clj:433)
	at metabase.sync.analyze$fn__61297$analyze_db_BANG___61302$fn__61303$fn__61304.invoke(analyze.clj:121)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:151)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:147)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
	at clojure.core$partial$fn__5839.invoke(core.clj:2623)
	at metabase.driver$fn__29643.invokeStatic(driver.clj:527)
	at metabase.driver$fn__29643.invoke(driver.clj:527)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__39867.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__39864.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__39853.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__39848.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__39839.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:169)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:166)
	at metabase.sync.analyze$fn__61297$analyze_db_BANG___61302$fn__61303.invoke(analyze.clj:118)
	at metabase.sync.analyze$fn__61297$analyze_db_BANG___61302.invoke(analyze.clj:113)
	at metabase.api.database$fn__63875$fn__63877.invoke(database.clj:622)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Invalid column type
	at oracle.jdbc.driver.Redirector$2.redirect(Redirector.java:264)
	at oracle.jdbc.driver.Representation.getObject(Representation.java:436)
	at oracle.jdbc.driver.Accessor.getObject(Accessor.java:1014)
	at oracle.jdbc.driver.OracleStatement.getObject(OracleStatement.java:6697)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.getObject(InsensitiveScrollableResultSet.java:912)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getObject(NewProxyResultSet.java:217)
	at metabase.driver.sql_jdbc.execute$get_object_of_class_thunk$fn__79461.invoke(execute.clj:356)
	at clojure.core$juxt$fn__5826$fn__5827.invoke(core.clj:2608)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
	at clojure.core$reduce1.invokeStatic(core.clj:942)
	at clojure.core$juxt$fn__5826.invoke(core.clj:2607)
	at metabase.driver.sql_jdbc.execute$row_thunk$row_thunk_STAR___79519.invoke(execute.clj:424)
	at metabase.query_processor.reducible$reducible_rows$reify__38005.reduce(reducible.clj:160)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$transduce.invokeStatic(core.clj:6879)
	at clojure.core$transduce.invoke(core.clj:6870)
	at metabase.query_processor.context.default$default_reducef$fn__37178.invoke(default.clj:58)
	... 147 more
```

**Information about your Metabase Installation:**
```
[]({
  "browser-info": {
    "language": "fr-FR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_151-b12",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_151",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.151-b12",
    "os.name": "Linux",
    "os.version": "3.10.0-693.11.1.el7.x86_64",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.2",
      "date": "2021-05-17",
      "branch": "release-x.39.x",
      "hash": "b0d9436"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
})
```

**Comment by flamber** [comment]
Hi @Philippe-M 
Can you provide the column type of `HIE.PURTRS`, which it's failing on with the error "Invalid column type" ?

**Comment by Philippe-M** [comment]
Hi @flamber,

The problem is that the log does not indicate which field is problematic.

**Comment by flamber** [comment]
@Philippe-M Okay, can you provide the entire DDL for that table then?

**Comment by flamber** [comment]
@Philippe-M I'm not sure what's going on, but I cannot reproduce just with the DDL, so I'm guessing that it's something to do with the actual data, which makes fingerprinting explode and not finish the sync. But I don't understand why it's failing with that error.

Try starting with extra debug logging - JAR example:
`java -Dlog4j.configurationFile="https://log4j.us/v2/templates/metabase?trace=metabase.sync" -jar metabase.jar`

Unrelated to this, but update you Java and migrate away from H2 if you're using Metabase in production:
https://www.metabase.com/docs/latest/operations-guide/java-versions.html
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Comment by Philippe-M** [comment]
@flamber I did some further testing and realized that I was still using ojdbc7. I updated it to version 8 and the field list is showing correctly now.

At the moment I am testing metabase and if the tests pass then there are plans to use mysql instead of H2.

thanks for your help
