### ISSUE TITLE
X-ray hangs indefinitely if SQLite DB is locked

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#16483]
**Describe the bug**
If you add a SQLite DB to Metabase, but another application has an exclusive lock on the database, it will hang when trying to generate an initial X-ray with no information about the error shown to the user. Also, syncing the database schema or re-scanning field values will fail with no feedback on the UI.

This might happen in practice if you're trying to add the DB of another open application. In my case I was trying to add the SQLite file used by [Anki](https://apps.ankiweb.net/) to Metabase while also having Anki running on my laptop.

This is similar to #16199 but not fixed by the typical connection test since `SELECT 1` will still pass even if the DB is locked.

**Logs**
Backend stack trace:
```
2021-06-08 03:42:08,276 WARN sync.util :: Error syncing _metabase_metadata table for sqlite Database 9 'Anki'
org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:941)
        at org.sqlite.core.DB.newSQLException(DB.java:953)
        at org.sqlite.core.DB.throwex(DB.java:918)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
        at org.sqlite.core.DB.prepare(DB.java:257)
        at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
        at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:63)
        at org.sqlite.jdbc3.JDBC3DatabaseMetaData.getTables(JDBC3DatabaseMetaData.java:1843)
```

**To Reproduce**
1. Create a new sqlite3 database and enter the sqlite CLI by running `sqlite3 test.db`
2. Run `BEGIN EXCLUSIVE;` to acquire an exclusive lock on the DB
3. In Metabase, go to Admin -> Databases -> Add database
4. Select SQLite, and enter a name and the filepath of the DB
5. Click "Save". Sometimes I do see the error "Unable to connect to database" after this. If this happens, run `END;` and `BEGIN EXCLUSIVE;` again in the sqlite CLI, and then retry adding the DB to metabase, and it should work. Still not sure what happens differently here.
6. Click "Explore this data"
7. Observe the UI hang
8. Go back to the admin page for the new database
9. Click "Sync database schema now" or "Re-scan field values now"
10. Observe that nothing is reported to the user even though errors are thrown on the backend

**Expected behavior**
I guess the DB should probably still be allowed to be added if it's locked, but we should give some indication to the user that the data can't be accessed rather than hanging indefinitely or swallowing the error.

**Information about your Metabase Installation:**

Metabase 0.39.4 (on current master) on MacOS Big Sur and Firefox 89.0

**Comment by flamber** [comment]
Currently sync/fp/scan is being done async, so there's no way of surfacing those errors, but definitely something we want #11354

**Comment by crisptrutski** [comment]
This works now, mostly.

Immediately after adding the database, it will get stuck in syncing. Releasing the exclusive lock will resolve this, as the background sync job will actually have crashed. Manually syncing will work, and clear the toast message.

Since this remaining pain point is generic robustness issue, that we don't return failure when the job dies, I'm closing this.

**Comment by crisptrutski** [comment]
I don't think the original issue still stands, as the only "exploration" shown is "Metabase tips".

The endless spinning sync, despite the sync job having failed, is outside the scope of this issue I would say and we should open separate issue for it, if one does not already exist.
