### ISSUE TITLE
Alerts are not being sent to Slack

### ISSUE THREAD

**Issue by easeev** [metabase/metabase#16791]
**Describe the bug**
Alerts are not being sent to Slack

**Logs**

```
[6d1754f9-0b64-4058-9341-fcb4525632a2] 2021-06-28T10:00:00+08:00 INFO metabase.task.send-pulses Sending scheduled pulses...
[6d1754f9-0b64-4058-9341-fcb4525632a2] 2021-06-28T10:00:01+08:00 ERROR metabase.pulse.render.png Error rendering Pulse
java.lang.NullPointerException
	at javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:130)
	at javax.swing.UIDefaults.getUI(UIDefaults.java:761)
	at javax.swing.UIManager.getUI(UIManager.java:1016)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at org.fit.cssbox.layout.BrowserCanvas.<init>(BrowserCanvas.java:68)
	at metabase.pulse.render.png$content_canvas.invokeStatic(png.clj:71)
	at metabase.pulse.render.png$content_canvas.invoke(png.clj:67)
	at metabase.pulse.render.png$render_to_png_BANG_.invokeStatic(png.clj:87)
	at metabase.pulse.render.png$render_to_png_BANG_.invoke(png.clj:81)
	at metabase.pulse.render.png$fn__52024$render_html_to_png__52029$fn__52033.invoke(png.clj:101)
	at metabase.pulse.render.png$fn__52024$render_html_to_png__52029.invoke(png.clj:90)
	at metabase.pulse.render$fn__52225$render_pulse_card_to_png__52230$fn__52231.invoke(render.clj:157)
	at metabase.pulse.render$fn__52225$render_pulse_card_to_png__52230.invoke(render.clj:154)
	at metabase.pulse$create_slack_attachment_data$iter__72280__72284$fn__72285$fn__72294.invoke(pulse.clj:127)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_$iter__72303__72307$fn__72308.invoke(pulse.clj:138)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:136)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:133)
	at metabase.pulse$fn__72436.invokeStatic(pulse.clj:304)
	at metabase.pulse$fn__72436.invoke(pulse.clj:302)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase.pulse$send_notifications_BANG_$fn__72451.invoke(pulse.clj:320)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:319)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:315)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:342)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:324)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943$fn__81946$fn__81964$fn__81965.invoke(send_pulses.clj:55)
	at metabase.models.task_history$fn__39873$do_with_task_history__39878$fn__39879.invoke(task_history.clj:76)
	at metabase.models.task_history$fn__39873$do_with_task_history__39878.invoke(task_history.clj:71)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943$fn__81946$fn__81964.invoke(send_pulses.clj:52)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943$fn__81946.invoke(send_pulses.clj:51)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943.invoke(send_pulses.clj:38)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943$fn__81944.invoke(send_pulses.clj:45)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943.invoke(send_pulses.clj:38)
	at metabase.task.send_pulses.SendPulses$fn__82000.invoke(send_pulses.clj:96)
	at metabase.models.task_history$fn__39873$do_with_task_history__39878$fn__39879.invoke(task_history.clj:76)
	at metabase.models.task_history$fn__39873$do_with_task_history__39878.invoke(task_history.clj:71)
	at metabase.task.send_pulses.SendPulses.execute(send_pulses.clj:82)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
[6d1754f9-0b64-4058-9341-fcb4525632a2] 2021-06-28T10:00:01+08:00 ERROR metabase.pulse Error sending notification!
java.lang.NullPointerException
	at javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:130)
	at javax.swing.UIDefaults.getUI(UIDefaults.java:761)
	at javax.swing.UIManager.getUI(UIManager.java:1016)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at org.fit.cssbox.layout.BrowserCanvas.<init>(BrowserCanvas.java:68)
	at metabase.pulse.render.png$content_canvas.invokeStatic(png.clj:71)
	at metabase.pulse.render.png$content_canvas.invoke(png.clj:67)
	at metabase.pulse.render.png$render_to_png_BANG_.invokeStatic(png.clj:87)
	at metabase.pulse.render.png$render_to_png_BANG_.invoke(png.clj:81)
	at metabase.pulse.render.png$fn__52024$render_html_to_png__52029$fn__52033.invoke(png.clj:101)
	at metabase.pulse.render.png$fn__52024$render_html_to_png__52029.invoke(png.clj:90)
	at metabase.pulse.render$fn__52225$render_pulse_card_to_png__52230$fn__52231.invoke(render.clj:157)
	at metabase.pulse.render$fn__52225$render_pulse_card_to_png__52230.invoke(render.clj:154)
	at metabase.pulse$create_slack_attachment_data$iter__72280__72284$fn__72285$fn__72294.invoke(pulse.clj:127)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_$iter__72303__72307$fn__72308.invoke(pulse.clj:138)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:136)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:133)
	at metabase.pulse$fn__72436.invokeStatic(pulse.clj:304)
	at metabase.pulse$fn__72436.invoke(pulse.clj:302)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase.pulse$send_notifications_BANG_$fn__72451.invoke(pulse.clj:320)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:319)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:315)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:342)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:324)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943$fn__81946$fn__81964$fn__81965.invoke(send_pulses.clj:55)
	at metabase.models.task_history$fn__39873$do_with_task_history__39878$fn__39879.invoke(task_history.clj:76)
	at metabase.models.task_history$fn__39873$do_with_task_history__39878.invoke(task_history.clj:71)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943$fn__81946$fn__81964.invoke(send_pulses.clj:52)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943$fn__81946.invoke(send_pulses.clj:51)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943.invoke(send_pulses.clj:38)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943$fn__81944.invoke(send_pulses.clj:45)
	at metabase.task.send_pulses$fn__81934$send_pulses_BANG___81943.invoke(send_pulses.clj:38)
	at metabase.task.send_pulses.SendPulses$fn__82000.invoke(send_pulses.clj:96)
	at metabase.models.task_history$fn__39873$do_with_task_history__39878$fn__39879.invoke(task_history.clj:76)
	at metabase.models.task_history$fn__39873$do_with_task_history__39878.invoke(task_history.clj:71)
	at metabase.task.send_pulses.SendPulses.execute(send_pulses.clj:82)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
```

**To Reproduce**
1. Create a question
2. Set up an alert to be sent via email and Slack
4. Alert is sent via email but not Slack

**Expected behavior**
I can see an alert in Slack

**Information about your Metabase Installation**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_275-8u275-b01-1~deb9u1-b01",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_275",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.275-b01",
    "os.name": "Linux",
    "os.version": "5.4.104+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "9.6.21"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.39.3",
      "date": "2021-05-27",
      "branch": "release-x.39.x",
      "hash": "598a112"
    },
    "settings": {
      "report-timezone": "Asia/Kuala_Lumpur"
    }
  }
}
```

**Comment by flamber** [comment]
Hi @easeev 
Try upgrading to latest LTS version of Java: https://www.metabase.com/docs/latest/operations-guide/java-versions.html

**Comment by easeev** [comment]
That was it, thank you!
