### ISSUE TITLE
Cannot upgrade to v0.40.x on AWS Elastic Beanstalk due to AWS Inspector not being available in certain regions

### ISSUE THREAD

**Issue by MarcSamD** [metabase/metabase#17143]
**Describe the bug**
Upgrade fails with "_Error encountered during build of postbuild_0_Metabase: Command 06-install_inspector failed_".

**Logs**
```
----------------------------------------
/var/log/eb-engine.log
----------------------------------------
2021/07/21 02:57:37.541614 [INFO] successfully execute command: docker pull metabase/metabase:v0.40.1
2021/07/21 02:57:37.541619 [INFO] successfully pulled docker image metabase/metabase:v0.40.1
2021/07/21 02:57:37.541623 [INFO] start to build docker image
2021/07/21 02:57:37.541645 [INFO] Running command /bin/sh -c docker build -t aws_beanstalk/staging-app /var/app/staging/
2021/07/21 02:57:37.984135 [INFO] Sending build context to Docker daemon  24.58kB
Step 1/2 : FROM metabase/metabase:v0.40.1
 ---> 18d6b793cf0c
Step 2/2 : EXPOSE 3000
 ---> Running in 8ec92596dea0
Removing intermediate container 8ec92596dea0
 ---> c212d451afea
Successfully built c212d451afea
Successfully tagged aws_beanstalk/staging-app:latest

2021/07/21 02:57:37.984155 [INFO] successfully execute command: docker build -t aws_beanstalk/staging-app /var/app/staging/
2021/07/21 02:57:37.984160 [INFO] successfully build docker image metabase/metabase:v0.40.1
2021/07/21 02:57:37.984164 [INFO] save staging docker image id
2021/07/21 02:57:37.984182 [INFO] Running command /bin/sh -c docker images aws_beanstalk/staging-app -q
2021/07/21 02:57:38.021886 [INFO] c212d451afea

2021/07/21 02:57:38.021970 [INFO] Executing instruction: configure X-Ray
2021/07/21 02:57:38.021976 [INFO] X-Ray is not enabled.
2021/07/21 02:57:38.021980 [INFO] Executing instruction: configure proxy Nginx
2021/07/21 02:57:38.026053 [INFO] Executing instruction: configure healthd specific proxy conf
2021/07/21 02:57:38.027227 [INFO] Running command /bin/sh -c systemctl show -p PartOf healthd.service
2021/07/21 02:57:38.033893 [WARN] Warning: process healthd is already registered...
Deregistering the process ...
2021/07/21 02:57:38.033921 [INFO] Running command /bin/sh -c systemctl show -p PartOf healthd.service
2021/07/21 02:57:38.038008 [INFO] Running command /bin/sh -c systemctl is-active healthd.service
2021/07/21 02:57:38.041289 [INFO] Running command /bin/sh -c systemctl show -p PartOf healthd.service
2021/07/21 02:57:38.045108 [INFO] Running command /bin/sh -c systemctl stop healthd.service
2021/07/21 02:57:38.087378 [INFO] Running command /bin/sh -c systemctl disable healthd.service
2021/07/21 02:57:38.173803 [INFO] Running command /bin/sh -c systemctl daemon-reload
2021/07/21 02:57:38.243860 [INFO] Running command /bin/sh -c systemctl reset-failed
2021/07/21 02:57:38.249053 [INFO] Running command /bin/sh -c systemctl daemon-reload
2021/07/21 02:57:38.328952 [INFO] Running command /bin/sh -c systemctl reset-failed
2021/07/21 02:57:38.334640 [INFO] Running command /bin/sh -c systemctl is-enabled aws-eb.target
2021/07/21 02:57:38.338369 [INFO] Running command /bin/sh -c systemctl enable aws-eb.target
2021/07/21 02:57:38.420481 [INFO] Running command /bin/sh -c systemctl start aws-eb.target
2021/07/21 02:57:38.424560 [INFO] Running command /bin/sh -c systemctl enable healthd.service
2021/07/21 02:57:38.500438 [INFO] Running command /bin/sh -c systemctl show -p PartOf healthd.service
2021/07/21 02:57:38.506126 [INFO] Running command /bin/sh -c systemctl is-active healthd.service
2021/07/21 02:57:38.509485 [INFO] Running command /bin/sh -c systemctl start healthd.service
2021/07/21 02:57:38.549583 [INFO] Copying file /opt/elasticbeanstalk/config/private/healthd/healthd_logformat.conf to /var/proxy/staging/nginx/conf.d/healthd_logformat.
conf
2021/07/21 02:57:38.550740 [INFO] Copying file /opt/elasticbeanstalk/config/private/healthd/healthd_nginx.conf to /var/proxy/staging/nginx/conf.d/elasticbeanstalk/healt
hd.conf
2021/07/21 02:57:38.551943 [INFO] Executing instruction: configure log streaming
2021/07/21 02:57:38.551952 [INFO] log streaming is not enabled
2021/07/21 02:57:38.551955 [INFO] disable log stream
2021/07/21 02:57:38.551969 [INFO] Running command /bin/sh -c systemctl show -p PartOf amazon-cloudwatch-agent.service
2021/07/21 02:57:38.557453 [INFO] Running command /bin/sh -c systemctl stop amazon-cloudwatch-agent.service
2021/07/21 02:57:38.561585 [INFO] Executing instruction: GetToggleForceRotate
2021/07/21 02:57:38.561604 [INFO] Checking if logs need forced rotation
2021/07/21 02:57:38.561630 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-get-metadata -s arn:aws-cn:cloudformation:cn-north-1:123456789:stack/awseb-e-abcdefghijkl
-stack/abc-defg-hijkl -r AWSEBAutoScalingGroup --region cn-north-1
2021/07/21 02:57:39.055796 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-get-metadata -s arn:aws-cn:cloudformation:cn-north-1:123456789:stack/awseb-e-abcdefghijkl
-stack/abc-defg-hijkl -r AWSEBBeanstalkMetadata --region cn-north-1
2021/07/21 02:57:39.482929 [INFO] Procfile not found. Generating default rsyslog config
2021/07/21 02:57:39.484080 [INFO] Running command /bin/sh -c systemctl restart rsyslog.service
2021/07/21 02:57:39.510622 [INFO] Executing instruction: Configure Docker Logging
2021/07/21 02:57:39.523429 [INFO] Executing instruction: PostBuildEbExtension
2021/07/21 02:57:39.523452 [INFO] Starting executing the config set Infra-EmbeddedPostBuild.
2021/07/21 02:57:39.523473 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-init -s arn:aws-cn:cloudformation:cn-north-1:123456789:stack/awseb-e-abcdefghijkl-stack/abc-defg-hijkl -r AWSEBAutoScalingGroup --region cn-north-1 --configsets Infra-EmbeddedPostBuild
2021/07/21 02:57:40.185820 [ERROR] An error occurred during execution of command [app-deploy] - [PostBuildEbExtension]. Stop running the command. Error: Container comma
nds build failed. Please refer to /var/log/cfn-init.log for more details.
```

```
----------------------------------------
/var/log/cfn-init.log
----------------------------------------
2021-07-21 02:52:51,547 [INFO] -----------------------Starting build-----------------------
2021-07-21 02:52:51,552 [INFO] Running configSets: Infra-EmbeddedPreBuild
2021-07-21 02:52:51,554 [INFO] Running configSet Infra-EmbeddedPreBuild
2021-07-21 02:52:51,554 [INFO] ConfigSets completed
2021-07-21 02:52:51,554 [INFO] -----------------------Build complete-----------------------
2021-07-21 02:53:26,550 [INFO] -----------------------Starting build-----------------------
2021-07-21 02:53:26,556 [INFO] Running configSets: Infra-EmbeddedPostBuild
2021-07-21 02:53:26,558 [INFO] Running configSet Infra-EmbeddedPostBuild
2021-07-21 02:53:26,560 [INFO] Running config postbuild_0_Metabase
2021-07-21 02:53:26,574 [INFO] Command 01_server_https succeeded
2021-07-21 02:53:26,588 [INFO] Command 02_log_x_real_ip succeeded
2021-07-21 02:53:26,599 [INFO] Test failed with code 1
2021-07-21 02:53:26,608 [INFO] Test failed with code 1
2021-07-21 02:53:26,814 [INFO] Command 05_try_nginx succeeded
2021-07-21 02:53:26,816 [INFO] ConfigSets completed
2021-07-21 02:53:26,816 [INFO] -----------------------Build complete-----------------------
2021-07-21 02:57:11,690 [INFO] -----------------------Starting build-----------------------
2021-07-21 02:57:11,696 [INFO] Running configSets: Infra-EmbeddedPreBuild
2021-07-21 02:57:11,698 [INFO] Running configSet Infra-EmbeddedPreBuild
2021-07-21 02:57:11,700 [INFO] Running config prebuild_0_Metabase
2021-07-21 02:57:13,009 [INFO] ConfigSets completed
2021-07-21 02:57:13,009 [INFO] -----------------------Build complete-----------------------
2021-07-21 02:57:39,844 [INFO] -----------------------Starting build-----------------------
2021-07-21 02:57:39,850 [INFO] Running configSets: Infra-EmbeddedPostBuild
2021-07-21 02:57:39,852 [INFO] Running configSet Infra-EmbeddedPostBuild
2021-07-21 02:57:39,855 [INFO] Running config postbuild_0_Metabase
2021-07-21 02:57:39,868 [INFO] Command 01_server_https succeeded
2021-07-21 02:57:39,883 [INFO] Command 02_log_x_real_ip succeeded
2021-07-21 02:57:39,893 [INFO] Test failed with code 1
2021-07-21 02:57:39,903 [INFO] Test failed with code 1
2021-07-21 02:57:40,090 [INFO] Command 05_try_nginx succeeded
2021-07-21 02:57:40,158 [ERROR] Command 06-install_inspector (bash -x install -u false) failed
2021-07-21 02:57:40,158 [ERROR] Error encountered during build of postbuild_0_Metabase: Command 06-install_inspector failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 573, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 273, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 06-install_inspector failed
2021-07-21 02:57:40,159 [ERROR] -----------------------BUILD FAILED!------------------------
2021-07-21 02:57:40,159 [ERROR] Unhandled exception during build: Command 06-install_inspector failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 176, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 135, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 561, in build
    self.run_config(config, worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 573, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 273, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 06-install_inspector failed
```

**Upgrade path tried**
I was on v0.39.2
Failed to upgrade to v0.40.1
Then failed to upgrade to v0.40.0
Then succeed to upgrade to v0.39.5
Then still failed to upgrade to v0.40.0 and v0.40.1

I never had any upgrade issue starting v0.38 or earlier until trying to reach v0.40, always following this (very) easy [procedure](https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html#deploying-new-versions-of-metabase-on-elastic-beanstalk).

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.67",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "4.14.232-177.418.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "h2"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-07-13",
      "tag": "v0.39.5",
      "branch": "release-x.39.x",
      "hash": "59acd40"
    },
    "settings": {
      "report-timezone": "Asia/Hong_Kong"
    }
  }
}
```

**Severity**
Blocking an upgrade

**Additional context**
I'm using AWS China.
Probably linked to #17012 but not a duplicate because others issues seem to be related to people still using old version of  Amazon Linux but in my case I'm using latest available [Docker AL2 version 3.4.2](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platform-history-docker.html)

**Comment by paoliniluis** [comment]
Interesting, does AWS China have AWS Inspector service?

**Comment by MarcSamD** [comment]
> Interesting, does AWS China have AWS Inspector service?

No, you got it right.

For reference:
- [Amazon Inspector supported regions](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_supported_os_regions.html#inspector_supported-regions)
- [Supported services in AWS China](https://www.amazonaws.cn/en/about-aws/regional-product-services/)

According to our AWS Account Manager, Inspector will not be released soon (>1 year), so @paoliniluis could you let me know if it is an issue that you could fix soon ? (otherwise I will try to use another deployment method)

**Comment by paoliniluis** [comment]
Hi @MarcSamD, can you try with this deployment file?
[metabase-aws-eb-without-inspector-ElasticBeanstalk.zip](https://github.com/metabase/metabase/files/6869156/metabase-aws-eb-without-inspector-ElasticBeanstalk.zip)

**Comment by MarcSamD** [comment]
Thanks @paoliniluis for your quick feedback, ElasticBeanstalk is very convenient on user-end so I hope it is not too much a hassle to maintain on your side.

The deployment is now failing on the installation of CloudWatch Agent (and not for the same reason as Inspector, CloudWatch is available in AWS China :)

```
021-07-26 02:10:24,870 [INFO] -----------------------Starting build-----------------------
2021-07-26 02:10:24,877 [INFO] Running configSets: Infra-EmbeddedPreBuild
2021-07-26 02:10:24,879 [INFO] Running configSet Infra-EmbeddedPreBuild
2021-07-26 02:10:24,880 [INFO] ConfigSets completed
2021-07-26 02:10:24,880 [INFO] -----------------------Build complete-----------------------
2021-07-26 02:10:53,543 [INFO] -----------------------Starting build-----------------------
2021-07-26 02:10:53,549 [INFO] Running configSets: Infra-EmbeddedPostBuild
2021-07-26 02:10:53,551 [INFO] Running configSet Infra-EmbeddedPostBuild
2021-07-26 02:10:53,553 [INFO] Running config postbuild_0_Metabase
2021-07-26 02:10:53,573 [INFO] Command 01_server_https succeeded
2021-07-26 02:10:53,588 [INFO] Command 02_log_x_real_ip succeeded
2021-07-26 02:10:53,598 [INFO] Test failed with code 1
2021-07-26 02:10:53,607 [INFO] Test failed with code 1
2021-07-26 02:10:53,817 [INFO] Command 05_try_nginx succeeded
2021-07-26 02:11:04,010 [ERROR] Command 07-install_cloudwatch_agent (sudo yum update && sudo yum upgrade -y && wget https://s3.amazonaws.com/amazoncl
oudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm && sudo rpm -U ./amazon-cloudwatch-agent.rpm) failed
2021-07-26 02:11:04,010 [ERROR] Error encountered during build of postbuild_0_Metabase: Command 07-install_cloudwatch_agent failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 573, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 273, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 07-install_cloudwatch_agent failed
2021-07-26 02:11:04,013 [ERROR] -----------------------BUILD FAILED!------------------------
2021-07-26 02:11:04,013 [ERROR] Unhandled exception during build: Command 07-install_cloudwatch_agent failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 176, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 135, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 561, in build
    self.run_config(config, worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 573, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 273, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 07-install_cloudwatch_agent failed
```

**Comment by paoliniluis** [comment]
Super interesting @MarcSamD, seems like even the images are different in the China region and I assume that's the error for the Cloudwatch installation there.

Nevermind, I just finished a new testing bundle for this case and also others, can you try it and let me know if it works? This one ignores errors so it does not crash on installation of cloudwatch agent or inspector in cases like yours, and also uses a more simplified structure for deployments instead of using Elastic Beanstalk specific structures

Give it a try and let me know if it works in your case, thanks!
[metabase-ebs.zip](https://github.com/metabase/metabase/files/6875683/metabase-ebs.zip)

**Comment by MarcSamD** [comment]
Yes, the upgrade to v0.40.1 is working now with this version ignoring errors.
And indeed AWS China is a special case with some [features not available](https://docs.amazonaws.cn/en_us/aws/latest/userguide/cloudwatch.html#feature-diff).

So for me it is ok to close this issue but let me know if you need further tests with this troublesome region :)

**Comment by paoliniluis** [comment]
@MarcSamD thanks for helping us with the tests, can you please test this bundle?
https://github.com/metabase/metabase/files/6897620/metabase-ebs.zip

it's the new one with some custom rules in Nginx that were asked by other users, just want to confirm that it will work on your case, thanks 👍🏻

**Comment by MarcSamD** [comment]
Hi Luis,

This new bundle is also working according to EB events:
![image](https://user-images.githubusercontent.com/70358310/127427738-9a4caa5f-4545-4518-8acb-eba1be978b49.png)

![image](https://user-images.githubusercontent.com/70358310/127427933-a09283c6-0361-4f62-a4a0-02f187154fc4.png)
Let me know if anything else to check

**Comment by yexingok** [comment]
@MarcSamD  I am also in AWS China and run into same issue like you, 

I figure out a way to succ upgrade to v0.40.1 before patch ready if you need to update soon,

1. Revert the changes manually in 01_metabase.config to previous version. (ie: 0.39.4).
2. Re-deploy, Metabase launch succ.

**Comment by yexingok** [comment]
Hi @paoliniluis  Luis,  For AWS inspect feature, I think it is a good feature, 

Is it possible to add a env variable AWS_INSPECT (true/false; default to false) to let user decide whether to enable/disable this AWS inspect feature?  So:

1. Users from AWS regions not support AWS inspect, can happyly to deploy normally with ElasticBeanstalk.(rather than to debug such error like me :)
2. Users need the AWS inspect feature can enable it to get data they need.

fyi: @MarcSamD  @flamber

**Comment by paoliniluis** [comment]
@yexingok currently if there is an error in the installation it will continue without crashing, have you tried with the file I added above?

**Comment by yexingok** [comment]
Hi @paoliniluis do you want me to test this version:
https://github.com/metabase/metabase/files/6897620/metabase-ebs.zip

I saw @MarcSamD  have already test it and it works for him, 
for me I have deploy with my fix before as I mentioned in https://github.com/metabase/metabase/issues/17249  , and it works for v0.40 above.

I am happy to find sometime this week to test if that is helpful to you and Metabase team (ps: is busy monday here).

**Comment by paoliniluis** [comment]
Hi @yexingok, thanks for offering help, we have already built a PR that will include a fix for this so there's no need to test further, we hope to release 40.2 these days so please let us know if it worked

**Comment by yexingok** [comment]
@paolinilus Sure, I will test upgrade when 40.2 out then, thanks Luis!
