### ISSUE TITLE
Metabase Doesn't sync columns of specific table

### ISSUE THREAD

**Issue by rubenssoto** [metabase/metabase#17282]
Hello,

Im trying to sync all my presto with metabase and I had problems with one table.

`com.facebook.presto.spi.PrestoException: Formatted query does not parse: ShowColumns{table=hive.raw_courier_api.order}
	at com.facebook.presto.sql.SqlFormatterUtil.getFormattedSql(SqlFormatterUtil.java:44)
	at com.facebook.presto.execution.PrepareTask.execute(PrepareTask.java:71)
	at com.facebook.presto.execution.PrepareTask.execute(PrepareTask.java:39)
	at com.facebook.presto.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:187)
	at com.facebook.presto.$gen.Presto_0_245_1_amzn_0____20210707_222608_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:254)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$5(LocalDispatchQuery.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

PREPARE statement131 FROM DESCRIBE "hive"."raw_courier_api"."order"

TABLE SCHEMA
[table_schema.txt](https://github.com/metabase/metabase/files/6919911/table_schema.txt)

I think the problem could be on array column

**Comment by flamber** [comment]
Hi @rubenssoto 
Please include the commit you're using (Admin > Troubleshooting > "Diagnostic Info") and that you're using the new Presto driver.
I think you might be right about the array column will cause problems, but it's failing on the `"order"` column, which doesn't seem to be part of that table schema. Or am I overlooking something?
