### ISSUE TITLE
Can't connect to Presto in Kubernetes

### ISSUE THREAD

**Issue by rubenssoto** [metabase/metabase#17543]
Hello,

I'm running a prestoDB inside kubernetes, I have a LoadBalancer inside my kuberneters cluster called "ingress nginx". The load balancer provides to me an https URL https://presto.dominio.com

I used that URL on presto CLI in my machine and it worked very fine, but in metabase didn't work.

<img width="1677" alt="Captura de Tela 2021-08-21 às 21 29 27" src="https://user-images.githubusercontent.com/36298331/130338128-d551f2d1-fd1b-4a4f-96da-19baedfabaaf.png">

[error_metabase.txt](https://github.com/metabase/metabase/files/7026393/error_metabase.txt)

Could you help me?

Im running metabase from master:
docker run -it -p 3000:3000 metabase/metabase-head

Presto CLI:
<img width="1680" alt="Captura de Tela 2021-08-21 às 22 36 33" src="https://user-images.githubusercontent.com/36298331/130339091-b67eada5-397f-44df-ba93-3ca67ce53ef4.png">

**Comment by flamber** [comment]
Hi @rubenssoto 

You need to provide information about which commit you're using, when you're using `master`, so we know exactly what is included in that build. Always post "Diagnostic Info" from Admin > Troubleshooting.

The error seems to indicate that Metabase cannot connect to the hostname you're using. There's a timeout after 5 seconds.
Make sure that you can `ping` or `nc` from the Metabase container to the database, since it could just be networking problems.
Check if there's any access log activity on the load-balancer from Metabase.

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by rubenssoto** [comment]
@flamber after created this issue, I made more tests and I think it is a presto jdbc issue is not metabase fault.
I can connect to presto from the same machine using prestocli and python with sqlAlchemy but I tried with dbeaver and presto jdbc and was the same problem.

**Comment by rubenssoto** [comment]
@flamber after some digging I found the solution.

I something related to http protocol version, in my case I have an ELB in front of my presto.
more details here:
https://github.com/prestodb/presto/pull/15955

To solve the problem I need to add a parameter on connection
protocols=http11
In dbeaver worked, but in metabase no.

Metabase I have the error:

`2021-08-23 01:24:52,065 ERROR api.database :: Não posso conectar ao banco de dados
java.lang.Exception: Unrecognized connection property 'protocols'
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:39)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:22)
	at clojure.lang.RestFn.invoke(RestFn.java:442)`

I think the problem is related with presto jdbc release that metabase are using.

What should I do? Open an issue on github?

thank you so much!

**Comment by flamber** [comment]
If you try PrestoDB 254 on DBeaver, then you'll likely get the same error, since this was added in 255.
Metabase currently uses 254: https://github.com/metabase/metabase/blob/master/modules/drivers/presto-jdbc/deps.edn
