### ISSUE TITLE
Unknown or incorrect time zone: 'Europe/Paris'

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#17689]
**Describe the bug**
no particular context, just visible in the logs

**Logs**
```
Caused by: java.sql.SQLException: Unknown or incorrect time zone: 'Europe/Paris'
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1688)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1550)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1513)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256)
```

![image](https://user-images.githubusercontent.com/4558101/131529016-2a7eb174-759b-4c02-83a2-97c67710f411.png)

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_292-b10",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "1.8.0_292",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.292-b10",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.25.1.el7.x86_64",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "oracle",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MariaDB",
        "version": "10.5.10-MariaDB"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.6.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "tag": "v0.40.3.1",
      "date": "2021-08-26",
      "branch": "release-x.40.x",
      "hash": "0550b86"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

**Comment by flamber** [comment]
See https://github.com/metabase/metabase/issues/16564#issuecomment-860254615
Closing in favor of #10365
