### ISSUE TITLE
metabase connect dorisdb failed

### ISSUE THREAD

**Issue by JackFzy** [metabase/metabase#17874]
metabase 连接 dorisdb 因字段中包含bigint和int类型 导致表字段信息同步是失败，异常如下

同步表"表单109“hive_watch_link_data_4”"字段失败
java.sql.SQLTransientConnectionException: (conn=70269) Syntax error in line 1:
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:612)
	at org.mariadb.jdbc.MariaDbDatabaseMetaData.executeQuery(MariaDbDatabaseMetaData.java:510)
	at org.mariadb.jdbc.MariaDbDatabaseMetaData.getColumns(MariaDbDatabaseMetaData.java:829)
	at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getColumns(NewProxyDatabaseMetaData.java:3140)
	at metabase.driver.sql_jdbc.sync.describe_table$jdbc_fields_metadata$fn__80903.invoke(describe_table.clj:83)
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__80811.reduce(common.clj:34)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core.Eduction.reduce(core.clj:7682)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$cat$fn__8761.invoke(core.clj:7625)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at metabase.driver.sql_jdbc.sync.describe_table$fields_metadata$reify__80919.reduce(describe_table.clj:125)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at clojure.core$into.invoke(core.clj:6887)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_fields.invokeStatic(describe_table.clj:133)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_fields.doInvoke(describe_table.clj:130)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invokeStatic(describe_table.clj:159)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invoke(describe_table.clj:156)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table.invokeStatic(describe_table.clj:170)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table.invoke(describe_table.clj:163)
	at metabase.driver.sql_jdbc$fn__82292.invokeStatic(sql_jdbc.clj:66)
	at metabase.driver.sql_jdbc$fn__82292.invoke(sql_jdbc.clj:64)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.fetch_metadata$fn__62481$table_metadata__62486$fn__62487.invoke(fetch_metadata.clj:18)
	at metabase.sync.fetch_metadata$fn__62481$table_metadata__62486.invoke(fetch_metadata.clj:15)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__62803$db_metadata__62808$fn__62809.invoke(fetch_metadata.clj:87)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__62803$db_metadata__62808.invoke(fetch_metadata.clj:83)
	at metabase.sync.sync_metadata.fields$fn__63296$sync_fields_for_table_BANG___63305$fn__63308$fn__63309.invoke(fields.clj:72)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:156)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:149)
	at metabase.sync.sync_metadata.fields$fn__63296$sync_fields_for_table_BANG___63305$fn__63308.invoke(fields.clj:71)
	at metabase.sync.sync_metadata.fields$fn__63296$sync_fields_for_table_BANG___63305.invoke(fields.clj:65)
	at clojure.core$partial$fn__5839.invoke(core.clj:2624)
	at clojure.core$map$fn__5866.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$filter$fn__5893.invoke(core.clj:2809)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1792)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.sync_metadata.fields$fn__63334$sync_fields_BANG___63339$fn__63340.invoke(fields.clj:85)
	at metabase.sync.sync_metadata.fields$fn__63334$sync_fields_BANG___63339.invoke(fields.clj:77)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at metabase.sync.util$fn__40218$run_step_with_metadata__40223$fn__40227$fn__40229.doInvoke(util.clj:360)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:116)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:113)
	at metabase.sync.util$fn__40218$run_step_with_metadata__40223$fn__40227.invoke(util.clj:355)
	at metabase.sync.util$fn__40218$run_step_with_metadata__40223.invoke(util.clj:350)
	at metabase.sync.util$fn__40409$run_sync_operation__40414$fn__40415$fn__40423.invoke(util.clj:451)
	at metabase.sync.util$fn__40409$run_sync_operation__40414$fn__40415.invoke(util.clj:449)
	at metabase.sync.util$fn__40409$run_sync_operation__40414.invoke(util.clj:443)
	at metabase.sync.sync_metadata$fn__64006$sync_db_metadata_BANG___64011$fn__64012$fn__64013.invoke(sync_metadata.clj:49)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:156)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:149)
	at clojure.core$partial$fn__5841.invoke(core.clj:2630)
	at metabase.driver$fn__29808.invokeStatic(driver.clj:527)
	at metabase.driver$fn__29808.invoke(driver.clj:527)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__40130.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__40127.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__40116.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__40111.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__40102.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:177)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:174)
	at metabase.sync.sync_metadata$fn__64006$sync_db_metadata_BANG___64011$fn__64012.invoke(sync_metadata.clj:48)
	at metabase.sync.sync_metadata$fn__64006$sync_db_metadata_BANG___64011.invoke(sync_metadata.clj:45)
	at metabase.api.database$fn__64829$fn__64831.invoke(database.clj:626)
	at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Syntax error in line 1:
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:262)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357)
	... 92 more
Caused by: java.sql.SQLException: Syntax error in line 1:
...0 ELSE NUMERIC_SCALE END, UNSIGNED INTEGER) DECIMAL_DI...
                             ^
Encountered: UNSIGNED
Expected: UNSIGNED is keyword, maybe `UNSIGNED`
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1688)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1550)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1513)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256)
	... 93 more

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
