### ISSUE TITLE
KeyExchange signature verification failed for key type=ssh-rsa

### ISSUE THREAD

**Issue by kastnerp** [metabase/metabase#18316]
**Describe the bug**
Unable to establish connection due MySQL  to `KeyExchange signature verification failed for key type=ssh-rsa` error.

**Logs**

```
org.apache.sshd.common. SshException: KeyExchange signature verification failed for key type=ssh-rsa
at org.apache.sshd.common. future. AbstractsshFuture.verifyResult (Abstract SshFuture.java:126)
at org.apache.sshd.client. future. DefaultAuthFuture.verify(DefaultAuthFuture.java:39)
at org.apache.sshd.client. future. DefaultAuthFuture.verify (DefaultAuthFuture.java:32)
at metabase.util.ssh$start_ssh_tunnel_BANG_.invokeStatic(ssh.clj:63)
at metabase.util.ssh$start ssh tunnel_BANG. invoke(ssh.clj:49)
at metabase.util.sshSinclude_ssh_tunnel_BANG_.invokeStatic(ssh.clj: 143)
at metabase.util.sshSinclude_ssh_tunnel_BANG .invoke(ssh.clj:137)
at metabase.util.ssh$fn_33569.invokeStatic(ssh.clj:169)
at metabase.util.ssh$fn_33569.invoke(ssh.cìj:159)
at clojure.lang. Multifn.invoke(Multifn.java:234)
at metabase.driver.sql jdbc.connection$create_pool_BANG_.invokeStatic(connection.clj:95)
at metabase.driver.se jdbc.connection$create_pool_BANG .invoke(connection.clj:90)
at metabase.driver.sql dbc.connection $db_GT_pooled_connection_spec. invokeStatic(connection.clj: 213)
at metabase.driver.sql jdbc.connection$db__GT_pooled_connection_spec. invoke(connection.clj:165)
at metabase.driver.sql dbc.execute$datasource.invokeStatic(execute.clj:135)
at metabase.driver.sq! dbc.execute$datasource. invoke(execute.clj:131)
at metabase.driver.sql dbc.execute$datasource_with_diagnostic_info_BANG_.invokeStatic(execute.clj:142)
at metabase.driver.si dbc.execute$datasource_with_diagnosticinfo_BANG .invoke(execute.clj:137)
at metabase.driver.se dbc.execute$fn_52143.invokeStatic(execute.clj: 190)
at metabase.driver.se jdbc.execute$fn_52143.invoke(execute.clj:188)
at clojure.lang. Multifn.invoke(MultiFn.java:239)
at metabase.driver.sql-jdbc.execute$execute_reducible_query.invokeStatic(execute.clj: 475)
at metabase.driver.sql dbc.execute$execute_reducible_query.invoke(execute.clj: 463)
at metabase.driver.sql dbc.executeSexecute_reducible_query.invokestatic(execute.cíj:472)
at metabase.driver.sql jdbc.execute$execute_reducible-query.invoke(execute.clj:463)
at metabase.driver.sql dbcSfn_85052.invokeStatic(sql-jdbc.clj:54)
at metabase.driver.sgi jdbc5fn_85052.invoke(sql-jdbc.clj:52)
at clojure. lang. Multifn.invoke(Multifn.java:244)
at metabase.query_processor.context $executef.invokeStatic(context.clj:59)
at metabase.query_processor.context $executef.invoke(context.clj:48)
at metabase. query processor.context. default$default_runf.invokestatic(default.clj:68)
at metabase.query processor.context.default&default_runf.invoke(default.clj:66)
```

**To Reproduce**
No connection can be established, no particular steps that might be worth pointing out.
I connect via SSH tunnel and password, not via SSH keys.

**Expected behavior**
Connection should be possible since I did not change any settings from the previous version.

**Screenshots**
N/A

**Information about your Metabase Installation:**

- Your browser and the version: Chrome 94
- Your operating system: Synology
- Your databases: MySQL
- Metabase version: v0.41.0
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Blocking the usage entirely.

**Additional context**
The issue occurred since I updated from v0.40.5 to v0.41.0. SSH into my remote server works. Remote database works.

**Comment by pawit-metabase** [comment]
Start sshd like this to reproduce: `/usr/sbin/sshd -D -oKexAlgorithms=diffie-hellman-group-exchange-sha256`
Latest version that works: 2.5.1
