### ISSUE TITLE
Unable to connect to Metabase DB

### ISSUE THREAD

**Issue by chennanfei** [metabase/metabase#1853]
Hi, my metabase container exited unexpectedly after it had run 2 two weeks with following simple message.
`/app/run_metabase.sh: line 29:     8 Killed                  java -Dlogfile.path=target/log -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -jar /app/metabase.jar`

My command which ran a container is as below.
`docker run -d -p 3000:3000 -v /var/data:/tmp -e "MB_DB_FILE=/tmp/metabase.db" --name metabase metabase/metabase`

Then I tried to restart the container but got following error. However I could access the H2 database by running command `java -cp /var/h2/bin/h2*.jar org.h2.tools.Shell` and then performed SQL statements. What may the root cause be? Thanks!
```
2016-01-31 02:40:58,726 [INFO ] metabase.core :: Starting Metabase version v0.13.2 (c9afde0 HEAD)...
2016-01-31 02:41:01,643 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.h2
2016-01-31 02:41:02,472 [DEBUG] metabase.driver :: Registered driver :h2.
2016-01-31 02:41:02,483 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.mongo
2016-01-31 02:41:04,809 [DEBUG] metabase.driver :: Registered driver :mongo.
2016-01-31 02:41:04,815 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.mysql
2016-01-31 02:41:04,902 [DEBUG] metabase.driver :: Registered driver :mysql.
2016-01-31 02:41:04,905 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.postgres
2016-01-31 02:41:04,952 [DEBUG] metabase.driver :: Registered driver :postgres.
2016-01-31 02:41:05,008 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.redshift
2016-01-31 02:41:05,048 [DEBUG] metabase.driver :: Registered driver :redshift.
2016-01-31 02:41:05,050 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.sqlite
2016-01-31 02:41:05,097 [DEBUG] metabase.driver :: Registered driver :sqlite.
2016-01-31 02:41:05,099 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.sqlserver
2016-01-31 02:41:05,144 [DEBUG] metabase.driver :: Registered driver :sqlserver.
2016-01-31 02:41:05,149 [INFO ] metabase.driver :: loading driver namespace:  metabase.driver.sync
2016-01-31 02:41:08,627 [INFO ] metabase.db :: Verifying Database Connection ...
2016-01-31 02:41:13,644 [ERROR] metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
Exception in thread "main" java.lang.AssertionError: Assert failed: Unable to connect to Metabase DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((clojure.core/deref (resolve (quote metabase.driver/can-connect-with-details?))) engine details))
	at metabase.db$verify_db_connection.invoke(db.clj:149)
	at metabase.db$setup_db.doInvoke(db.clj:163)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init.invoke(core.clj:130)
	at metabase.core$start_normally.invoke(core.clj:212)
	at metabase.core$_main.doInvoke(core.clj:236)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
```

**Comment by agilliland** [comment]
Looks like something may be tying up your H2 database and preventing Metabase from accessing it.  When Metabase starts up it will create a new database if one isn't found and that's not happening here, so it's a good sign that it's finding your existing H2 database but simply can't connect to it.

You mentioned that you ran the H2 shell to verify the database, you should make sure to completely close that down before launching Metabase because H2 doesn't like having multiple clients connected to the same file at a time.

If you've safely shut down the H2 shell and verified nothing is connected to your H2 database but Metabase still isn't starting up then I would check if there is a .lock file lying around.  If you see a file called `metabase.db.lock.db` in the folder with the other H2 database files then go ahead and delete it and try starting up Metabase again.

**Comment by chennanfei** [comment]
I changed the database to PostgreSQL. The metabase crashed twice before. I found the crash time was close to the one that some pulses were scheduled to be handled. So when I didn't get pulse emails, I sensed that the metabase might crash.

**Comment by maliayas** [comment]
@agilliland Hi. I have the same issue. My OS crashed and now metabase can't connect to its DB. My stuff is now locked in. What is the default password for the H2 database so that I will try to export records? P.S. there is no `.lock` file in the `/tmp` folder and nothing else is using the H2 file.

**Comment by cepix** [comment]
@maliayas by default .lock files are placed where metabase.jar is located

**Comment by maliayas** [comment]
@cepix My issue was already fixed. Thanks anyway. In my case, connecting & disconnecting to the H2 database via H2 tools fixed the DB file somehow.
