### ISSUE TITLE
Metabase 0.41 Jar not able to run with APP Dynamic agent

### ISSUE THREAD

**Issue by rvemuri1985** [metabase/metabase#19035]
Hello, 

we downloaded the Metabase 0.41 source code and done small customizations as per our company standards. 
We are able to create the Metabase Jar file. But while deploying the Metabase Jar in openshift, we are facing issue with APP Dynamics (appdynamics/AppServerAgent-1.8) settings.
below is the issue we are facing, please check and helps us to solve it.    

> Install Directory resolved to[/opt/product/appdynamics-agent/AppServerAgent]
[AD Agent init] Tue Nov 16 09:21:19 EST 2021[INFO]: JavaAgent - Restoring properties, exception causing the resets was org.apache.xerces.jaxp.DocumentBuilderFactoryImpl cannot be cast to javax.xml.parsers.DocumentBuilderFactory
[AD Agent init] Tue Nov 16 09:21:19 EST 2021[INFO]: JavaAgent - Clearing property javax.xml.parsers.DocumentBuilderFactory because none was set before config
[AD Agent init] Tue Nov 16 09:21:19 EST 2021[INFO]: JavaAgent - Clearing property org.apache.commons.logging.LogFactory because none was set before config
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.singularity.ee.agent.appagent.AgentEntryPoint$1.run(AgentEntryPoint.java:637)
Caused by: java.lang.ExceptionInInitializerError
	at com.singularity.ee.agent.util.bounded.collections.BoundsEnforcer$Builder.build(BoundsEnforcer.java:388)
	at com.singularity.ee.agent.util.bounded.collections.BoundedConcurrentReferenceHashMap.<init>(BoundedConcurrentReferenceHashMap.java:73)
	at com.singularity.ee.agent.util.bounded.collections.BoundedConcurrentReferenceHashMapBuilder.build(BoundedConcurrentReferenceHashMapBuilder.java:114)
	at com.singularity.ee.agent.util.reflect.ReflectionUtility.<clinit>(ReflectionUtility.java:153)
	at com.singularity.ee.agent.appagent.kernel.JavaAgent.setLog4j2LoaderUtilDisabled(JavaAgent.java:329)
	at com.singularity.ee.agent.appagent.kernel.JavaAgent.initialize(JavaAgent.java:371)
	at com.singularity.ee.agent.appagent.kernel.JavaAgent.initialize(JavaAgent.java:343)
	... 5 more
Caused by: java.lang.ClassCastException: org.apache.xerces.jaxp.DocumentBuilderFactoryImpl cannot be cast to javax.xml.parsers.DocumentBuilderFactory
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(Unknown Source)
	at org.apache.logging.log4j.core.config.xml.XmlConfiguration.newDocumentBuilder(XmlConfiguration.java:183)
	at org.apache.logging.log4j.core.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:89)
	at org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:46)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:551)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:475)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:323)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:687)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:669)
	at com.singularity.ee.agent.util.log4j.ADLoggerFactory.getLogger(ADLoggerFactory.java:61)
	at com.singularity.ee.agent.util.bounded.collections.BoundsEnforcer.<clinit>(BoundsEnforcer.java:53)
	... 12 more

**Comment by flamber** [comment]
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Or try asking in APP Dynamic Again forum, or a Java programming forum, since it doesn't look like it's specific to Metabase, but your setup. Unless it's a problem with the official Metabase release, then it's difficult to know what the problem is.
