### ISSUE TITLE
Invalid $project - Path collision.... with mongo >= 4.4

### ISSUE THREAD

**Issue by spike008t** [metabase/metabase#19135]
**Describe the bug**
With mongodb 4.4, the server issue some error with an invalid $project with embedded document (see: https://docs.mongodb.com/manual/release-notes/4.4-compatibility/#path-collision-restrictions)

**Logs**

```
2021-11-30 14:06:56,756 WARN sync.util :: Error fingerprinting Table 33 'auditlogs'
com.mongodb.MongoCommandException: Command failed with error 31249 (Location31249): 'Invalid $project :: caused by :: Path collision at user.role remaining portion role' on server mongo.local:27017. The full response is { "operationTime" : { "$timestamp" : { "t" : 1638281212, "i" : 1 } }, "ok" : 0.0, "errmsg" : "Invalid $project :: caused by :: Path collision at user.role remaining portion role", "code" : 31249, "codeName" : "Location31249", "$clusterTime" : { "clusterTime" : { "$timestamp" : { "t" : 1638281212, "i" : 1 } }, "signature" : { "hash" : { "$binary" : "7szljvAh5+8xh3L2G9isxBVkj2E=", "$type" : "00" }, "keyId" : { "$numberLong" : "7035042223372632068" } } } }
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:242)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:233)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:136)
	at com.mongodb.operation.AggregateOperationImpl$1.call(AggregateOperationImpl.java:193)
	at com.mongodb.operation.AggregateOperationImpl$1.call(AggregateOperationImpl.java:189)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:462)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:406)
	at com.mongodb.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:189)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:295)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:41)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:161)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1502)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1462)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1447)
	at metabase.driver.mongo.execute$aggregate.invokeStatic(execute.clj:114)
	at metabase.driver.mongo.execute$aggregate.invoke(execute.clj:108)
	at metabase.driver.mongo.execute$execute_reducible_query.invokeStatic(execute.clj:163)
	at metabase.driver.mongo.execute$execute_reducible_query.invoke(execute.clj:157)
	at metabase.driver.mongo$fn__89879$f__88414__auto____89880.invoke(mongo.clj:234)
	at metabase.driver.mongo$fn__89879.invokeStatic(mongo.clj:233)
	at metabase.driver.mongo$fn__89879.invoke(mongo.clj:231)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:68)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:66)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
	at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49264.invoke(mbql_to_native.clj:25)
	at metabase.query_processor.middleware.check_features$check_features$fn__49750.invoke(check_features.clj:39)
	at metabase.query_processor.middleware.limit$limit$fn__47637.invoke(limit.clj:37)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__50124.invoke(cache.clj:204)
	at metabase.query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51117.invoke(optimize_temporal_filters.clj:204)
	at metabase.query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51161.invoke(validate_temporal_bucketing.clj:50)
	at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49321.invoke(auto_parse_filter_values.clj:43)
	at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39421.invoke(wrap_value_literals.clj:161)
	at metabase.query_processor.middleware.annotate$add_column_info$fn__43856.invoke(annotate.clj:623)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__45795.invoke(permissions.clj:108)
	at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__50301.invoke(pre_alias_aggregations.clj:40)
	at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46190.invoke(cumulative_aggregations.clj:60)
	at metabase.query_processor.middleware.visualization_settings$update_viz_settings$fn__46128.invoke(visualization_settings.clj:63)
	at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47235.invoke(resolve_joined_fields.clj:102)
	at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__50887.invoke(resolve_joins.clj:171)
	at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__50423.invoke(add_implicit_joins.clj:190)
	at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__47254.invoke(large_int_id.clj:59)
	at metabase.query_processor.middleware.format_rows$format_rows$fn__50475.invoke(format_rows.clj:74)
	at metabase.query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46626.invoke(add_default_temporal_unit.clj:23)
	at metabase.query_processor.middleware.desugar$desugar$fn__46101.invoke(desugar.clj:21)
	at metabase.query_processor.middleware.binning$update_binning_strategy$fn__39321.invoke(binning.clj:229)
	at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__45438.invoke(resolve_fields.clj:34)
	at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__49676.invoke(add_dimension_projections.clj:314)
	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__49973.invoke(add_implicit_clauses.clj:147)
	at metabase.query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__47622.invoke(upgrade_field_literals.clj:40)
	at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47003.invoke(add_source_metadata.clj:123)
	at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50223.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)
	at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48573.invoke(auto_bucket_datetimes.clj:147)
	at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45419.invoke(resolve_source_table.clj:45)
	at metabase.query_processor.middleware.parameters$substitute_parameters$fn__48227.invoke(parameters.clj:111)
	at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__45492.invoke(resolve_referenced.clj:79)
	at metabase.query_processor.middleware.expand_macros$expand_macros$fn__51545.invoke(expand_macros.clj:184)
	at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__48006.invoke(add_timezone_info.clj:15)
	at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__50490.invoke(splice_params_in_response.clj:32)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49984$fn__49988.invoke(resolve_database_and_driver.clj:31)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:60)
	at metabase.driver$do_with_driver.invoke(driver.clj:56)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49984.invoke(resolve_database_and_driver.clj:25)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46036.invoke(fetch_source_query.clj:277)
	at metabase.query_processor.middleware.store$initialize_store$fn__46227$fn__46228.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:42)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.query_processor.middleware.store$initialize_store$fn__46227.invoke(store.clj:10)
	at metabase.query_processor.middleware.validate$validate_query$fn__50273.invoke(validate.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__50280.invoke(normalize_query.clj:22)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__47952.invoke(add_rows_truncated.clj:35)
	at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49250.invoke(results_metadata.clj:143)
	at metabase.query_processor.reducible$async_qp$qp_STAR___42672$thunk__42673.invoke(reducible.clj:103)
	at metabase.query_processor.reducible$async_qp$qp_STAR___42672.invoke(reducible.clj:109)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___42681$fn__42684.invoke(reducible.clj:135)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___42681.invoke(reducible.clj:134)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:152)
	at metabase.query_processor$process_query.doInvoke(query_processor.clj:146)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.db.metadata_queries$fn__69629$table_rows_sample__69638$fn__69641.invoke(metadata_queries.clj:144)
	at metabase.db.metadata_queries$fn__69629$table_rows_sample__69638.invoke(metadata_queries.clj:131)
	at metabase.sync.analyze.fingerprint$fn__69696$fingerprint_table_BANG___69701$fn__69702.invoke(fingerprint.clj:66)
	at metabase.sync.analyze.fingerprint$fn__69696$fingerprint_table_BANG___69701.invoke(fingerprint.clj:46)
	at metabase.sync.analyze.fingerprint$fn__69872$fingerprint_fields_BANG___69877$fn__69878$fn__69879.invoke(fingerprint.clj:180)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:157)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:150)
	at metabase.sync.analyze.fingerprint$fn__69872$fingerprint_fields_BANG___69877$fn__69878.invoke(fingerprint.clj:178)
	at metabase.sync.analyze.fingerprint$fn__69872$fingerprint_fields_BANG___69877.invoke(fingerprint.clj:174)
	at metabase.sync.analyze.fingerprint$fn__69907$fingerprint_fields_for_db_BANG__STAR___69916$fn__69919$fn__69920$fn__69921.invoke(fingerprint.clj:204)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6829)
	at clojure.core$reduce.invoke(core.clj:6812)
	at metabase.sync.analyze.fingerprint$fn__69907$fingerprint_fields_for_db_BANG__STAR___69916$fn__69919$fn__69920.invoke(fingerprint.clj:200)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.sync.analyze.fingerprint$fn__69907$fingerprint_fields_for_db_BANG__STAR___69916$fn__69919.invoke(fingerprint.clj:197)
	at metabase.sync.analyze.fingerprint$fn__69907$fingerprint_fields_for_db_BANG__STAR___69916.invoke(fingerprint.clj:186)
	at metabase.sync.analyze.fingerprint$fn__69907$fingerprint_fields_for_db_BANG__STAR___69916$fn__69917.invoke(fingerprint.clj:191)
	at metabase.sync.analyze.fingerprint$fn__69907$fingerprint_fields_for_db_BANG__STAR___69916.invoke(fingerprint.clj:186)
	at metabase.sync.analyze.fingerprint$fn__69949$fingerprint_fields_for_db_BANG___69954$fn__69955.invoke(fingerprint.clj:218)
	at metabase.sync.analyze.fingerprint$fn__69949$fingerprint_fields_for_db_BANG___69954.invoke(fingerprint.clj:212)
	at metabase.sync.analyze$make_analyze_steps$fn__70262.invoke(analyze.clj:104)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$fn__40268$run_step_with_metadata__40273$fn__40277$fn__40279.doInvoke(util.clj:361)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:116)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:113)
	at metabase.sync.util$fn__40268$run_step_with_metadata__40273$fn__40277.invoke(util.clj:356)
	at metabase.sync.util$fn__40268$run_step_with_metadata__40273.invoke(util.clj:351)
	at metabase.sync.util$fn__40459$run_sync_operation__40464$fn__40465$fn__40473.invoke(util.clj:452)
	at metabase.sync.util$fn__40459$run_sync_operation__40464$fn__40465.invoke(util.clj:450)
	at metabase.sync.util$fn__40459$run_sync_operation__40464.invoke(util.clj:444)
	at metabase.sync.analyze$fn__70274$analyze_db_BANG___70279$fn__70280$fn__70281.invoke(analyze.clj:121)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:157)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:150)
	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
	at metabase.driver.mongo$fn__89731$f__88414__auto____89732.invoke(mongo.clj:93)
	at metabase.driver.mongo$fn__89731.invokeStatic(mongo.clj:92)
	at metabase.driver.mongo$fn__89731.invoke(mongo.clj:90)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__40180.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__40177.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__40166.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__40161.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__40152.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:178)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:175)
	at metabase.sync.analyze$fn__70274$analyze_db_BANG___70279$fn__70280.invoke(analyze.clj:118)
	at metabase.sync.analyze$fn__70274$analyze_db_BANG___70279.invoke(analyze.clj:113)
	at metabase.sync$fn__70408$sync_database_BANG___70417$fn__70423$fn__70425$fn__70427.invoke(sync.clj:45)
	at clojure.core$mapv$fn__8468.invoke(core.clj:6914)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
	at clojure.core.protocols$fn__8176.invokeStatic(protocols.clj:136)
	at clojure.core.protocols$fn__8176.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8136$G__8131__8145.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8168.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8168.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6830)
	at clojure.core$mapv.invokeStatic(core.clj:6905)
	at clojure.core$mapv.invoke(core.clj:6905)
	at metabase.sync$fn__70408$sync_database_BANG___70417$fn__70423$fn__70425.invoke(sync.clj:45)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:157)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:150)
	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
	at metabase.driver.mongo$fn__89731$f__88414__auto____89732.invoke(mongo.clj:93)
	at metabase.driver.mongo.util$do_with_mongo_connection$fn__88405.invoke(util.clj:214)
	at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:188)
	at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:177)
	at metabase.driver.mongo.util$do_with_mongo_connection.invokeStatic(util.clj:208)
	at metabase.driver.mongo.util$do_with_mongo_connection.invoke(util.clj:203)
	at metabase.driver.mongo$fn__89731.invokeStatic(mongo.clj:92)
	at metabase.driver.mongo$fn__89731.invoke(mongo.clj:90)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__40180.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__40177.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__40166.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__40161.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__40152.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:178)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:175)
	at metabase.sync$fn__70408$sync_database_BANG___70417$fn__70423.invoke(sync.clj:44)
	at metabase.sync$fn__70408$sync_database_BANG___70417.invoke(sync.clj:30)
	at metabase.sync$fn__70408$sync_database_BANG___70417$fn__70418.invoke(sync.clj:40)
	at metabase.sync$fn__70408$sync_database_BANG___70417.invoke(sync.clj:30)
	at metabase.events.sync_database$process_sync_database_event$fn__83661.invoke(sync_database.clj:37)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
1. Setup a mongodb server >= 4.4
2. Create a collection with an embedded document
3. Add the mongo server
4. browse a collection on that mongo

**Expected behavior**
Should works

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.x. OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: MongoDB 4.4.10
- Metabase version: v0.41.1
- Metabase hosting environment: Docker
- Metabase internal database: (e.x. H2 (default), Postgres or MySQL)

**Severity**
Blocking

**Additional context**

**Comment by flamber** [comment]
Hi @spike008t 
Can you provide an example of an "embedded document"?
Also worth a read: https://stackoverflow.com/questions/64059795/mongodb-get-error-message-mongoerror-path-collision-at-activity
Guessing it's caused by the way we unnest in Mongo, which then fails during fingerprinting, because of the query generated.

**Comment by spike008t** [comment]
@flamber you can try with something like that 
```
{
  "action": "myAction"
  "createdAt": ISODate("2021-12-01T00:00:00.000Z"),
  "user": {
    "username": "username1",
    "email": "user@test.com",
    "lastname": "lastname1",
    "firstname": "firstname",
  },
}
```

**Comment by jeff303** [comment]
@spike008t , do you mind trying with [this build](https://www.dropbox.com/s/o0mzqsueu3qtpkn/metabase.jar?dl=0)?  I was able to reproduce the issue, and fix it according to my reading of the MongoDB docs, but just wanted to confirm.

**Comment by spike008t** [comment]
Yes I'll give a try. I'll let you know

**Comment by spike008t** [comment]
@jeff303 The build seems deleted. I'll pull your PR and have a try

**Comment by jeff303** [comment]
> @jeff303 The build seems deleted. I'll pull your PR and have a try

@spike008t , just realized you can download directly from CI using [this link](https://1192667-30203935-gh.circle-artifacts.com/0/home/circleci/metabase/metabase/target/uberjar/metabase.jar).
