### ISSUE TITLE
Missing org.apache.batik.bridge.DefaultFontFamilyResolver class in pulse card render

### ISSUE THREAD

**Issue by enx1998** [metabase/metabase#19488]
**Describe the bug**
Pulse migrated from previous version of Metabase fails to render in both email and browser, "An error occurred while displaying this card" message appears.

**Logs**
Server log:  
```
2021-12-27 15:57:01,226 ERROR pulse.render :: Pulse card render error
java.lang.NoClassDefFoundError: Could not initialize class org.apache.batik.bridge.DefaultFontFamilyResolver
	at org.apache.batik.bridge.UserAgentAdapter.getFontFamilyResolver(UserAgentAdapter.java:465)
	at org.apache.batik.bridge.BridgeContext.getFontFamilyResolver(BridgeContext.java:284)
	at org.apache.batik.bridge.SVGTextElementBridge.getFontList(SVGTextElementBridge.java:1518)
	at org.apache.batik.bridge.SVGTextElementBridge.getAttributeMap(SVGTextElementBridge.java:1597)
	at org.apache.batik.bridge.SVGTextElementBridge.fillAttributedStringBuffer(SVGTextElementBridge.java:897)
	at org.apache.batik.bridge.SVGTextElementBridge.buildAttributedString(SVGTextElementBridge.java:850)
	at org.apache.batik.bridge.SVGTextElementBridge.computeLaidoutText(SVGTextElementBridge.java:630)
	at org.apache.batik.bridge.SVGTextElementBridge.buildGraphicsNode(SVGTextElementBridge.java:286)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:224)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:210)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158)
	at metabase.pulse.render.js_svg$render_svg.invokeStatic(js_svg.clj:97)
	at metabase.pulse.render.js_svg$render_svg.invoke(js_svg.clj:87)
	at metabase.pulse.render.js_svg$svg_string__GT_bytes.invokeStatic(js_svg.clj:101)
	at metabase.pulse.render.js_svg$svg_string__GT_bytes.invoke(js_svg.clj:100)
	at metabase.pulse.render.js_svg$timelineseries_line.invokeStatic(js_svg.clj:110)
	at metabase.pulse.render.js_svg$timelineseries_line.invoke(js_svg.clj:103)
	at metabase.pulse.render.body$fn__54187$render__54177__54192$fn__54196.invoke(body.clj:463)
	at metabase.pulse.render.body$fn__54187$render__54177__54192.invoke(body.clj:446)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at clojure.lang.MultiFn.invoke(MultiFn.java:252)
	at metabase.pulse.render$fn__54444$render_pulse_card_body__54449$fn__54453.invoke(render.clj:127)
	at metabase.pulse.render$fn__54444$render_pulse_card_body__54449.invoke(render.clj:117)
	at metabase.pulse.render$fn__54481$render_pulse_card__54486$fn__54487.invoke(render.clj:148)
	at metabase.pulse.render$fn__54481$render_pulse_card__54486.invoke(render.clj:136)
	at metabase.pulse.render$render_pulse_card_for_display.invokeStatic(render.clj:173)
	at metabase.pulse.render$render_pulse_card_for_display.invoke(render.clj:169)
	at metabase.api.pulse$fn__79262$fn__79263.invoke(pulse.clj:176)
	at metabase.api.pulse$fn__79262.invokeStatic(pulse.clj:176)
	at metabase.api.pulse$fn__79262.invoke(pulse.clj:169)
	at compojure.core$wrap_response$fn__32066.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__32050.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__32055.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:151)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:152)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:152)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:152)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:152)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:153)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__70354.invoke(auth.clj:14)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078.invoke(core.clj:200)
	at compojure.core$make_context$handler__32106.invoke(core.clj:289)
	at compojure.core$make_context$fn__32110.invoke(core.clj:299)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$make_context$fn__32110.invoke(core.clj:300)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at metabase.api.routes$fn__79831$fn__79834.invoke(routes.clj:56)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__79976$fn__79977.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078.invoke(core.clj:200)
	at compojure.core$make_context$handler__32106.invoke(core.clj:289)
	at compojure.core$make_context$fn__32110.invoke(core.clj:299)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:152)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:152)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32059.invoke(core.clj:152)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078$f__32079$respond_SINGLEQUOTE___32080.invoke(core.clj:197)
	at metabase.server.routes$fn__79964$fn__79966.invoke(routes.clj:41)
	at compojure.core$routes$fn__32078$f__32079.invoke(core.clj:198)
	at compojure.core$routes$fn__32078.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__77436.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__77433.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__80431$fn__80432$fn__80433.invoke(log.clj:209)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__80431$fn__80432.invoke(log.clj:201)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__80431.invoke(log.clj:200)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__83644.invoke(browser_cookie.clj:30)
	at metabase.server.middleware.security$add_security_headers$fn__59281.invoke(security.clj:147)
	at metabase.server.middleware.json$wrap_json_body$fn__82788.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__82806.invoke(json.clj:98)
	at metabase.server.middleware.offset_paging$handle_paging$fn__59305.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__83911.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__83927.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__34077.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__44978$fn__44979.invoke(session.clj:257)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:238)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:230)
	at metabase.server.middleware.session$bind_current_user$fn__44978.invoke(session.clj:256)
	at metabase.server.middleware.session$wrap_current_user_info$fn__44965.invoke(session.clj:216)
	at metabase.server.middleware.session$wrap_session_id$fn__44951.invoke(session.clj:162)
	at metabase.server.middleware.auth$wrap_api_key$fn__70362.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__83831.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__34060.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__34085.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__83873.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__34088.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__83660.invoke(ssl.clj:38)
	at metabase.server$async_proxy_handler$fn__80204.invoke(server.clj:71)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
1. Edit a "migrated" Pulse
2. All questions that have a graph show the "An error occurred while displaying this card" message

**Expected behavior**
I expect to see the graphs

**Screenshots**
![immagine](https://user-images.githubusercontent.com/20546217/147489374-5762fa04-8f20-475f-9e18-7d78cdb10acd.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

```json
{
  "browser-info": {
    "language": "it",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9-LTS",
    "java.vendor": "Red Hat, Inc.",
    "java.vendor.url": "https://www.redhat.com/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9-LTS",
    "os.name": "Linux",
    "os.version": "3.10.0-1160.21.1.el7.x86_64",
    "user.language": "en",
    "user.timezone": "Etc/GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-16",
      "tag": "v0.41.5",
      "branch": "release-x.41.x",
      "hash": "fbfffc6"
    },
    "settings": {
      "report-timezone": "Europe/Rome"
    }
  }
}
```

**Severity**
This issue is blocking some operations because it breaks the pulse feature, so that some questions via email aren't available.

**Additional context**
The question that have issue in pulse is correctly displayed on its own page.

Thanks, Vincenzo

**Comment by flamber** [comment]
Hi @enx1998 

Which version did you upgrade from?

So the problem only occurs on migrated pulses, but if you create a new pulse referencing the same question, then it works?

Or are you saying the any old question cannot be used in any pulse, but if you create new questions, then they work?

If the problem is specific to old questions, can you please include the output from the metadata by going to the URL `/api/card/123`, where 123 is the old question ID.

To me, this looks like a Java and/or environment problem. Try with Docker instead. Also, you should migrate away from H2:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Comment by enx1998** [comment]
Hi @flamber,
thanks for your reply.

> Which version did you upgrade from?

0.38.3

> So the problem only occurs on migrated pulses, but if you create a new pulse referencing the same question, then it works?

No, it doesn't work, the same problem still persists

> Or are you saying the any old question cannot be used in any pulse, but if you create new questions, then they work? 

The same problem persists also in new created Dashboard subscriptions

> If the problem is specific to old questions, can you please include the output from the metadata by going to the URL

The problem is not specific to old questions but follow the question metadata
```json
{
    "description": null,
    "archived": false,
    "collection_position": null,
    "table_id": 18,
    "result_metadata": [
        {
            "semantic_type": null,
            "coercion_strategy": null,
            "unit": "day",
            "name": "registration_date",
            "field_ref": [
                "field",
                98,
                {
                    "temporal-unit": "day"
                }
            ],
            "effective_type": "type/Date",
            "id": 98,
            "display_name": "Registration Date",
            "fingerprint": {
                "global": {
                    "distinct-count": 9824,
                    "nil%": 0.0173
                },
                "type": {
                    "type/DateTime": {
                        "earliest": "2016-03-25T14:10:41.000Z",
                        "latest": "2017-08-04T18:45:46.000Z"
                    }
                }
            },
            "base_type": "type/Date"
        },
        {
            "name": "count",
            "display_name": "Count",
            "base_type": "type/BigInteger",
            "effective_type": "type/BigInteger",
            "semantic_type": "type/Quantity",
            "field_ref": [
                "aggregation",
                0
            ],
            "fingerprint": {
                "global": {
                    "distinct-count": 38,
                    "nil%": 0
                },
                "type": {
                    "type/Number": {
                        "min": 54,
                        "q1": 68,
                        "q3": 91.58578643762691,
                        "max": 118,
                        "sd": 15.999390878235843,
                        "avg": 80.55
                    }
                }
            }
        }
    ],
    "creator": {
        "email": "****@*****",
        "first_name": "******",
        "last_login": "2021-12-15T08:44:13.284",
        "is_qbnewb": false,
        "is_superuser": true,
        "id": 1,
        "last_name": "******",
        "date_joined": "2017-10-13T11:54:13.579",
        "common_name": "**********"
    },
    "can_write": true,
    "database_id": 3,
    "enable_embedding": false,
    "collection_id": 3,
    "query_type": "query",
    "name": "Daily Registrations",
    "last_query_start": "2021-12-27T18:57:43.288239Z",
    "dashboard_count": 1,
    "average_query_time": 160,
    "creator_id": 1,
    "moderation_reviews": [],
    "updated_at": "2021-12-27T18:57:43.43",
    "made_public_by_id": null,
    "embedding_params": null,
    "cache_ttl": null,
    "dataset_query": {
        "database": 3,
        "type": "query",
        "query": {
            "source-table": 18,
            "aggregation": [
                [
                    "count"
                ]
            ],
            "breakout": [
                [
                    "field",
                    98,
                    {
                        "temporal-unit": "day"
                    }
                ]
            ],
            "order-by": [
                [
                    "desc",
                    [
                        "field",
                        98,
                        {
                            "temporal-unit": "day"
                        }
                    ]
                ]
            ],
            "filter": [
                "time-interval",
                [
                    "field",
                    98,
                    null
                ],
                -60,
                "day"
            ]
        }
    },
    "id": 4,
    "display": "area",
    "last-edit-info": {
        "id": 1,
        "email": "****@*****",
        "first_name": "******",
        "last_name": "******",
        "timestamp": "2018-07-26T14:56:52.887"
    },
    "visualization_settings": {
        "graph.dimensions": [
            "registration_date"
        ],
        "line.interpolate": "cardinal",
        "graph.colors": [
            "#509EE3",
            "#9cc177",
            "#a989c5",
            "#ef8c8c",
            "#f9d45c",
            "#F1B556",
            "#A6E7F3",
            "#7172AD",
            "#7B8797",
            "#6450e3",
            "#55e350",
            "#e35850",
            "#77c183",
            "#7d77c1",
            "#c589b9",
            "#bec589",
            "#89c3c5",
            "#c17777",
            "#899bc5",
            "#efce8c",
            "#50e3ae",
            "#be8cef",
            "#8cefc6",
            "#ef8cde",
            "#b5f95c",
            "#5cc2f9",
            "#f95cd0",
            "#c1a877",
            "#f95c67"
        ],
        "graph.metrics": [
            "count"
        ]
    },
    "collection": {
        "authority_level": null,
        "description": null,
        "archived": false,
        "slug": "migrated_questions",
        "color": "#509ee3",
        "name": "Migrated Questions",
        "personal_owner_id": null,
        "id": 3,
        "location": "/",
        "namespace": null
    },
    "created_at": "2017-10-13T17:54:20.676",
    "public_uuid": null
}
```

> To me, this looks like a Java and/or environment problem.

I thought the same thing too, but I don't know how to solve the problem.

> Try with Docker instead.

I will try and let you know.

> Also, you should migrate away from H2: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

Yes, I know it is better to use MySQL/Postgres, but this is a small installation with a few questions.

Bye Vincenzo

**Comment by enx1998** [comment]
Hi @flamber,
I found the problem: I was using the "headless" version of the jdk, which is lacking of font support (I think), using the full version the problem is gone.

Thanks for your attention,
Vincenzo

**Comment by flamber** [comment]
Excellent - for reference for others: https://www.metabase.com/docs/latest/operations-guide/java-versions.html
