### ISSUE TITLE
rotate-encryption-key command generates a new database if no database is provided

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#19503]
**Describe the bug**
When running `rotate-encryption-key` command without a database file, `metabase` automatically creates a database  file and encrypts it.

**To Reproduce**
1. Create an empty folder
1. Download metabase `https://downloads.metabase.com/v0.41.5/metabase.jar` into the folder above - this is to ensure no `metabase.db.mv.db` or `metabase.db.h2.db` is found
3. run command `java -jar metabase.jar rotate-encryption-key 'IYqrSi5QDthvFWe4/WdAxhnra5DZC3RKx3ZSrOJDKsM='`

**Expected behavior**
Not sure if the current behavior is what we meant it to be, but I think it'll be more explicit if the command fails when no database file were found.

**Severity**
Not serious, just for user-friendly's sake

**Comment by flamber** [comment]
@qnkhuat If you don't have any environment variables defined, and don't specify any Java parameters, then Metabase will automatically use `metabase.db.mv.db`. So it seems correct with that behavior, but it could probably be described better in the logging about what is going on. And we should perhaps error when rotate-encryption-key doesn't contain a From and To key (of course they can be empty strings, but then we should log what is happening).

**Comment by qnkhuat** [comment]
> but it could probably be described better in the logging about what is going on

What do you think if we add:
- an info log saying `H2 database found at {{path}}` or `Connecting to {{DB_TYPE}}:{{DB_NAME}}` when we found a h2 database or db connection
- A warning log saying `Database not found. Metabase will create a new database at {{path}} and proceed encrypting` when not database is found


> we should perhaps error when rotate-encryption-key doesn't contain a From and To key 

Currently, the command will print out an exception if it doesn't detect a `To` key. I think we need to catch it and print out a more friendly error message? 

----
For more information this is our log when :
- run successfully
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2022-01-03 15:50:28,526 INFO metabase.util :: Maximum memory available to JVM: 8.0 GB
2022-01-03 15:50:35,337 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2022-01-03 15:50:36,211 INFO driver.impl :: Registered abstract driver :sql  🚚
 ↙ Load driver :sql took 182.0 ms
2022-01-03 15:50:36,215 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
Load driver :sql-jdbc took 187.4 ms
2022-01-03 15:50:36,216 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
2022-01-03 15:50:36,223 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
2022-01-03 15:50:36,427 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
2022-01-03 15:50:37,393 INFO metabase.core ::
Metabase v1.41.5 (fbfffc6 release-x.41.x)

Copyright © 2022 Metabase, Inc.

Metabase Enterprise Edition extensions are PRESENT.

Usage of Metabase Enterprise Edition features are subject to the Metabase Commercial License.See https://www.metabase.com/license/commercial/ for details.
2022-01-03 15:50:37,397 WARN metabase.core :: WARNING: You have enabled namespace tracing, which could log sensitive information like db passwords.
2022-01-03 15:50:37,403 WARN db.env :: WARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. For more information, see https://metabase.com/docs/latest/operations-guide/migrating-from-h2.html
2022-01-03 15:50:37,405 INFO db.setup :: Verifying h2 Database Connection ...
2022-01-03 15:50:37,471 INFO db.setup :: Successfully verified H2 1.4.197 (2018-03-18) application database connection. ✅
2022-01-03 15:50:37,471 INFO db.setup :: Running Database Migrations...
2022-01-03 15:50:37,472 INFO db.setup :: Setting up Liquibase...
2022-01-03 15:50:37,488 INFO db.setup :: Liquibase is ready.
2022-01-03 15:50:37,488 INFO db.liquibase :: Checking if Database has unrun migrations...
2022-01-03 15:50:38,068 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2022-01-03 15:50:38,084 INFO db.liquibase :: Migration lock is cleared. Running migrations...
2022-01-03 15:50:38,588 INFO db.setup :: Database Migrations Current ...  ✅
2022-01-03 15:50:38,596 INFO db.data-migrations :: Running all necessary data migrations, this may take a minute.
2022-01-03 15:50:38,598 INFO db.data-migrations :: Running data migration 'add-users-to-default-permissions-groups'...
2022-01-03 15:50:38,604 INFO models.permissions-group :: Created magic permissions group 'All Users' (ID = 1)
2022-01-03 15:50:38,605 INFO models.permissions-group :: Created magic permissions group 'Administrators' (ID = 2)
2022-01-03 15:50:38,607 INFO db.data-migrations :: Running data migration 'add-admin-group-root-entry'...
2022-01-03 15:50:38,610 INFO models.permissions-group :: Created magic permissions group 'MetaBot' (ID = 3)
2022-01-03 15:50:38,612 INFO db.data-migrations :: Running data migration 'add-databases-to-magic-permissions-groups'...
2022-01-03 15:50:38,614 INFO db.data-migrations :: Running data migration 'copy-site-url-setting-and-remove-trailing-slashes'...
2022-01-03 15:50:38,615 INFO db.data-migrations :: Running data migration 'ensure-protocol-specified-in-site-url'...
2022-01-03 15:50:38,615 INFO db.data-migrations :: Running data migration 'populate-card-database-id'...
2022-01-03 15:50:38,617 INFO db.data-migrations :: Running data migration 'migrate-humanization-setting'...
2022-01-03 15:50:38,617 INFO db.data-migrations :: Running data migration 'mark-category-fields-as-list'...
2022-01-03 15:50:38,622 INFO db.data-migrations :: Running data migration 'add-legacy-sql-directive-to-bigquery-sql-cards'...
2022-01-03 15:50:38,622 INFO db.data-migrations :: Running data migration 'clear-ldap-user-local-passwords'...
2022-01-03 15:50:38,623 INFO db.data-migrations :: Running data migration 'add-migrated-collections'...
2022-01-03 15:50:38,627 INFO db.data-migrations :: Running data migration 'migrate-click-through'...
2022-01-03 15:50:38,630 INFO db.data-migrations :: Finished running data migrations.
Database setup took 1.2 s
2022-01-03 15:50:38,851 INFO metabase.cmd :: Encryption key rotation OK.
```

- run without `To` key
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2022-01-03 15:49:50,654 INFO metabase.util :: Maximum memory available to JVM: 8.0 GB
2022-01-03 15:49:57,632 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2022-01-03 15:49:58,516 INFO driver.impl :: Registered abstract driver :sql  🚚
 ↙ Load driver :sql took 195.4 ms
2022-01-03 15:49:58,520 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
Load driver :sql-jdbc took 200.6 ms
2022-01-03 15:49:58,521 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
2022-01-03 15:49:58,528 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
2022-01-03 15:49:58,718 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
2022-01-03 15:49:59,649 INFO metabase.core ::
Metabase v1.41.5 (fbfffc6 release-x.41.x)

Copyright © 2022 Metabase, Inc.

Metabase Enterprise Edition extensions are PRESENT.

Usage of Metabase Enterprise Edition features are subject to the Metabase Commercial License.See https://www.metabase.com/license/commercial/ for details.
2022-01-03 15:49:59,653 WARN metabase.core :: WARNING: You have enabled namespace tracing, which could log sensitive information like db passwords.
clojure.lang.ArityException: Wrong number of args (0) passed to: metabase.cmd/rotate-encryption-key
        at clojure.lang.AFn.throwArity(AFn.java:429)
        at clojure.lang.AFn.invoke(AFn.java:28)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.cmd$run_cmd$fn__86409.invoke(cmd.clj:190)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:190)
        at metabase.cmd$run_cmd.invoke(cmd.clj:186)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.core$run_cmd.invokeStatic(core.clj:145)
        at metabase.core$run_cmd.invoke(core.clj:143)
        at metabase.core$_main.invokeStatic(core.clj:167)
        at metabase.core$_main.doInvoke(core.clj:162)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Command failed with exception: Wrong number of args (0) passed to: metabase.cmd/rotate-encryption-key
```

**Comment by flamber** [comment]
@qnkhuat I'm totally :+1: on those very help log messages. And it's not a security concern to show this information, since it's done while rotating the keys, which is a critical single-admin-operation, so it's important to tell what is going on.

**Comment by escherize** [comment]
I am on board with these changes, but I would say that the last one (running without a To key) is good the way it is. More info is better, and the error is explained right in the message: ` Wrong number of args (0) passed to: metabase.cmd/rotate-encryption-key`.

**Comment by escherize** [comment]
Then again, it might be worth highlighting it better. I'll give it a few minutes and see what I can come up with

**Comment by escherize** [comment]
Alright, I have a solution I'll PR it in a minute. Here are some sample outputs:

```
$ clojure -M:run rotate-encryption-key
-- snip --
The 'rotate-encryption-key' command requires 1 argument(s), you have given: 0.
```

it also works for other commands:

```
$ clojure -M:run migrate force it to go
-- snip --
The 'migrate' command requires 1 argument(s), you have given: 4.
```

it also works for multiple args:

```
$ clojure -M:run dump
-- snip --
The 'dump' command requires 1, or 3 argument(s), you have given: 0.
```
