### ISSUE TITLE
Validation of PostgreSQL connection not possible

### ISSUE THREAD

**Issue by crazyscientist** [metabase/metabase#19513]
**Describe the bug**

Following the instructions I tried to configure Metabase to use a Postgres-DB to store it's configuration and used this environment variable:

```
MB_DB_CONNECTION_URI='postgresql://<hostname>:5432/<dbname>?sslmode=verify-ca&user=<username>&password=<password>
```

In addition I have combined this var with the file `~/.postgresql/root.crt`, which contains my CA cert. As this did not work (see below in the logs) I also tried to use this env variable instead:

```
MB_DB_CONNECTION_URI='postgresql://<hostname>:5432/<dbname>?sslmode=verify-ca&user=<username>&password=<password>&sslrootcert=~/.postgresql/root.crt
```
Both combinations work as expected on the CLI with `psql <URI>`. But both variations result in the same traceback:

**Logs**

```
2022-01-03 14:48:53,439 INFO db.setup :: Verifying postgres Database Connection ...
2022-01-03 14:48:59,050 ERROR metabase.core :: Metabase Initialization FAILED
clojure.lang.ExceptionInfo: Unable to connect to Metabase postgres DB. {}
        at metabase.db.setup$fn__33730$verify_db_connection__33735$fn__33736$fn__33737.invoke(setup.clj:102)
        at metabase.db.setup$fn__33730$verify_db_connection__33735$fn__33736.invoke(setup.clj:100)
        at metabase.db.setup$fn__33730$verify_db_connection__33735.invoke(setup.clj:94)
        at metabase.db.setup$setup_db_BANG_$fn__33765$fn__33766.invoke(setup.clj:142)
        at metabase.util$do_with_us_locale.invokeStatic(util.clj:693)
        at metabase.util$do_with_us_locale.invoke(util.clj:679)
        at metabase.db.setup$setup_db_BANG_$fn__33765.invoke(setup.clj:141)
        at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:140)
        at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:136)
        at metabase.db$setup_db_BANG_$fn__33873.invoke(db.clj:61)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:56)
        at metabase.db$setup_db_BANG_.invoke(db.clj:51)
        at metabase.core$init_BANG_.invokeStatic(core.clj:91)
        at metabase.core$init_BANG_.invoke(core.clj:74)
        at metabase.core$start_normally.invokeStatic(core.clj:135)
        at metabase.core$start_normally.invoke(core.clj:129)
        at metabase.core$_main.invokeStatic(core.clj:168)
        at metabase.core$_main.doInvoke(core.clj:162)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
Caused by: org.postgresql.util.PSQLException: SSL error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:43)
        at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:534)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:149)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
        at org.postgresql.Driver.makeConnection(Driver.java:465)
        at org.postgresql.Driver.connect(Driver.java:264)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
        at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
        at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:245)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:242)
        at metabase.db.setup$fn__33730$verify_db_connection__33735$fn__33736$fn__33737.invoke(setup.clj:100)
        ... 21 more
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:645)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:464)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1144)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1055)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:395)
        at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:41)
        ... 43 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:629)
        ... 54 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 60 more
```

**To Reproduce**

1. Set env variable `MB_DB_CONNECTION_URI` as described above
2. Start metabase using the command `/usr/bin/java -jar /opt/metabase/metabase.jar`
3. See error in the output

**Expected behavior**

Validation of CA certificate is successful

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your operating system: SLES 15.3
- Your databases: PostgreSQL 12.9
- Metabase version: 0.41.5
- Metabase hosting environment: Jar-file on SLES
- Metabase internal database: PostgreSQL 12.9
- Java version: OpenJDK Runtime Environment (build 11.0.7+10-suse-3.42.4-x8664)

**Severity**
blocking usage of Metabase entirely

**Additional context**
IMHO, this might be a duplicate of #8908, which did not really solve the issue. 

Changing the `sslmode` to `require` instead of `verify-ca` certainly keeps Metabase running, but it would be great, if validation of the CA cert worked...

**Comment by crazyscientist** [comment]
FYI, if I'm not mistaken, this was working with version 0.39.3.

**Comment by flamber** [comment]
Hi @crazyscientist 
Are you sure that the user starting the Metabase process has access to your home directory?
Metabase uses JDBC, which is different from plain psql: https://jdbc.postgresql.org/documentation/head/ssl-client.html
Have you tried something like DBeaver.io?
I normally always add the parameter `ssl=true` even though the documentations says it's not needed.

**Comment by crazyscientist** [comment]
Give me a couple of days to verify. It turns out, our admins forgot to renew the certificate (which expired) :face_with_spiral_eyes:

**Comment by dpsutton** [comment]
@crazyscientist is it ok to close this issue then?

**Comment by crazyscientist** [comment]
> is it ok to close this issue then?

 I suppose so and sorry for the noise...
