### ISSUE TITLE
dump-to-h2 fail for large database with small memory limit

### ISSUE THREAD

**Issue by pawit-metabase** [metabase/metabase#19566]
**Describe the bug**
If we have a large application database and try to run `dump-to-h2` with a small memory limit, we will get OutOfMemoryError.

This is because the PostgreSQL driver by default try to fetch the entire table memory. (This is basically a variant of #18455 but with the application database instead of the data warehouse.)

**Logs**
```
$ java -Xmx512m -jar metabase.jar dump-to-h2 test.db
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2022-01-06 15:08:39,898 INFO metabase.util :: Maximum memory available to JVM: 512.0 MB
2022-01-06 15:08:46,934 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2022-01-06 15:08:48,034 INFO driver.impl :: Registered abstract driver :sql  🚚
 ↙ Load driver :sql took 212.4 ms
2022-01-06 15:08:48,039 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
Load driver :sql-jdbc took 218.6 ms
2022-01-06 15:08:48,041 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
2022-01-06 15:08:48,049 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
2022-01-06 15:08:48,305 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
2022-01-06 15:08:49,159 INFO metabase.core ::
Metabase v0.41.5 (fbfffc6 release-x.41.x)

Copyright © 2022 Metabase, Inc.

Metabase Enterprise Edition extensions are NOT PRESENT.
2022-01-06 15:08:49,163 WARN metabase.core :: WARNING: You have enabled namespace tracing, which could log sensitive information like db passwords.
2022-01-06 15:08:49,181 INFO cmd.dump-to-h2 :: Dumping from configured Metabase db to H2 file test.db
2022-01-06 15:08:49,182 WARN copy.h2 :: Output H2 database already exists: test.db.mv.db, removing.
2022-01-06 15:08:49,182 INFO cmd.copy :: Set up postgres source database and run migrations...
2022-01-06 15:08:49,183 INFO db.setup :: Verifying postgres Database Connection ...
2022-01-06 15:08:49,235 INFO db.setup :: Successfully verified PostgreSQL 14.1 application database connection. ✅
2022-01-06 15:08:49,235 INFO db.setup :: Running Database Migrations...
2022-01-06 15:08:49,241 INFO db.setup :: Setting up Liquibase...
2022-01-06 15:08:49,273 INFO db.setup :: Liquibase is ready.
2022-01-06 15:08:49,273 INFO db.liquibase :: Checking if Database has unrun migrations...
2022-01-06 15:08:49,973 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2022-01-06 15:08:49,979 INFO db.liquibase :: Migration lock is cleared. Running migrations...
2022-01-06 15:08:49,986 INFO db.setup :: Database Migrations Current ...  ✅
2022-01-06 15:08:49,987 INFO db.data-migrations :: Running all necessary data migrations, this may take a minute.
2022-01-06 15:08:49,996 INFO db.data-migrations :: Finished running data migrations.
Database setup took 813.3 ms
2022-01-06 15:08:49,996 INFO cmd.copy :: [OK]
2022-01-06 15:08:49,997 INFO cmd.copy :: Set up h2 target database and run migrations...
2022-01-06 15:08:49,997 INFO db.setup :: Verifying h2 Database Connection ...
2022-01-06 15:08:50,086 INFO db.setup :: Successfully verified H2 1.4.197 (2018-03-18) application database connection. ✅
2022-01-06 15:08:50,087 INFO db.setup :: Running Database Migrations...
2022-01-06 15:08:50,089 INFO db.setup :: Setting up Liquibase...
2022-01-06 15:08:50,101 INFO db.setup :: Liquibase is ready.
2022-01-06 15:08:50,101 INFO db.liquibase :: Checking if Database has unrun migrations...
2022-01-06 15:08:50,286 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2022-01-06 15:08:50,307 INFO db.liquibase :: Migration lock is cleared. Running migrations...
2022-01-06 15:08:51,087 INFO db.setup :: Database Migrations Current ...  ✅
Database setup took 1.1 s
2022-01-06 15:08:51,087 INFO cmd.copy :: [OK]
2022-01-06 15:08:51,087 INFO cmd.copy :: Testing if target h2 database is already populated...
2022-01-06 15:08:51,103 INFO cmd.copy :: [OK]
2022-01-06 15:08:51,126 INFO cmd.copy :: Temporarily disabling DB constraints...
2022-01-06 15:08:51,126 INFO cmd.copy :: [OK]
2022-01-06 15:08:51,133 INFO cmd.copy :: Copying instances of Database...
2022-01-06 15:08:51,136 INFO cmd.copy ::  copied 1 instances.
2022-01-06 15:08:51,142 INFO cmd.copy :: Copying instances of User...
2022-01-06 15:08:51,143 INFO cmd.copy ::  copied 1 instances.
2022-01-06 15:08:51,144 INFO cmd.copy :: Copying instances of Setting...
2022-01-06 15:08:51,144 INFO cmd.copy ::  copied 9 instances.
2022-01-06 15:08:51,146 INFO cmd.copy :: Copying instances of Table...
2022-01-06 15:08:51,146 INFO cmd.copy ::  copied 4 instances.
2022-01-06 15:08:51,149 INFO cmd.copy :: Copying instances of Field...
2022-01-06 15:08:51,153 INFO cmd.copy ::  copied 36 instances.
2022-01-06 15:08:51,154 INFO cmd.copy :: Copying instances of FieldValues...
2022-01-06 15:08:51,155 INFO cmd.copy ::  copied 5 instances.
2022-01-06 15:08:51,158 INFO cmd.copy :: Copying instances of Revision...
2022-01-06 15:08:51,159 INFO cmd.copy ::  copied 1 instances.
2022-01-06 15:08:51,159 INFO cmd.copy :: Copying instances of ViewLog...
2022-01-06 15:08:51,160 INFO cmd.copy ::  copied 1 instances.
2022-01-06 15:08:51,160 INFO cmd.copy :: Copying instances of Session...
2022-01-06 15:08:51,160 INFO cmd.copy ::  copied 1 instances.
2022-01-06 15:08:51,161 INFO cmd.copy :: Copying instances of Collection...
2022-01-06 15:08:51,162 INFO cmd.copy ::  copied 1 instances.

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "dirigiste-executor-controller-0"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "dirigiste-pool-controller-0"
Exception in thread "manifold-pool-1-1" java.lang.OutOfMemoryError: Java heap space
2022-01-06 15:08:54,910 INFO cmd.copy :: Re-enabling DB constraints...
2022-01-06 15:08:54,911 INFO cmd.copy :: [OK]
2022-01-06 15:08:54,917 ERROR metabase.cmd :: Failed to dump application database to H2 file
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Database.checkPowerOff(Database.java:536)
	at org.h2.engine.Session.close(Session.java:877)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:411)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:851)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at metabase.cmd.copy$fn__82238$copy_BANG___82243$fn__82244.invoke(copy.clj:276)
	at metabase.cmd.copy$fn__82238$copy_BANG___82243.invoke(copy.clj:257)
	at metabase.cmd.dump_to_h2$dump_to_h2_BANG_.invokeStatic(dump_to_h2.clj:39)
	at metabase.cmd.dump_to_h2$dump_to_h2_BANG_.invoke(dump_to_h2.clj:22)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.cmd$dump_to_h2.invokeStatic(cmd.clj:56)
	at metabase.cmd$dump_to_h2.doInvoke(cmd.clj:47)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__83021.invoke(cmd.clj:190)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:190)
	at metabase.cmd$run_cmd.invoke(cmd.clj:186)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:145)
	at metabase.core$run_cmd.invoke(core.clj:143)
	at metabase.core$_main.invokeStatic(core.clj:167)
	at metabase.core$_main.doInvoke(core.clj:162)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)
```

**To Reproduce**
1. Initialize empty Metabase database by starting it up with Postgres
2. Create a user
3. Insert a lot of dummy data into the database

```
INSERT INTO public.report_card
    (created_at, updated_at, name, description, display, dataset_query, visualization_settings, creator_id, database_id, table_id, query_type, archived, collection_id, public_uuid, made_public_by_id, enable_embedding, embedding_params, cache_ttl, result_metadata, collection_position)
select '2022-01-06 07:53:30.890628 +00:00', '2022-01-06 07:53:30.890628 +00:00', 'test', repeat('Z', 4000), 'scalar', '{"type":"native","native":{"query":"SELECT 1","template-tags":{}},"database":1}', '{}', 1, 1, null, 'native', false, null, null, null, false, null, null, '[{"name":"1","display_name":"1","base_type":"type/Integer","effective_type":"type/Integer","field_ref":["field","1",{"base-type":"type/Integer"}],"semantic_type":null,"fingerprint":{"global":{"distinct-count":1,"nil%":0},"type":{"type/Number":{"min":1,"q1":1,"q3":1,"max":1,"sd":null,"avg":1}}}}]', null
from generate_series(1, 500000);
```

4. Dump to H2  - `java -Xmx512m -jar metabase.jar dump-to-h2 test.db`

**Expected behavior**
Dump to h2 succeeds

**Screenshots**
N/A

**Information about your Metabase Installation:**
Metabase 0.41.5

**Severity**
It prevents dumping large database to H2.

Arguably, it's probably not a good idea anyway if you have a large database. However, we are relying on it for several operations in our cloud products (e.g. migrations to/from cloud)

**Additional Context**
This is probably a problem on both Postgres and H2 side - on Postgres we need to fetch a small amount at a time (setFetchSize) and on H2 side we need to tell it to commit to disk ever so often.

**Comment by crisptrutski** [comment]
This is pretty strange, as we definitely stream the results from the source database.

I suspect this has something to do with permissions, as we copy over the models in the following order:

```clojure
(def entities
  "Entities in the order they should be serialized/deserialized. This is done so we make sure that we load
  instances of entities before others that might depend on them, e.g. `Databases` before `Tables` before `Fields`."
  (concat
   [:model/Database
...
    :model/Session                           ;; see this log out starting and finishing
    :model/Collection                        ;; see this log out starting and finishing
    :model/CollectionPermissionGraphRevision ;; no logs shown for this 
...
```
