### ISSUE TITLE
New data picker shows blank after hiding a table in `admin/data model`

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#19742]
**Describe the bug**

**Logs**
```
DataSelector.jsx:1419 Uncaught TypeError: Cannot read properties of null (reading 'displayName')
    at DataSelector.jsx:1419:1
    at Array.map (<anonymous>)
    at TablePicker (DataSelector.jsx:1418:1)
    at renderWithHooks (react-dom.development.js:14803:1)
    at mountIndeterminateComponent (react-dom.development.js:17482:1)
    at beginWork (react-dom.development.js:18596:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
```

```
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at Popover.constrainPopoverToBetweenViewportAndTarget (Popover.jsx:400:1)
    at Popover.jsx:379:1
    at callback (react-dom.development.js:24769:1)
    at callCallback (react-dom.development.js:12490:1)
    at commitUpdateQueue (react-dom.development.js:12511:1)
    at commitLifeCycles (react-dom.development.js:19883:1)
    at commitLayoutEffects (react-dom.development.js:22803:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
```

**To Reproduce**
1. Go to Admin > Data Model
2. Hide "Orders" table
3. Exit Admin
4. Click on "New" button in the sidebar and choose Question
5. Select "Raw Data"
6. The page is blank
7. Refresh
8. Now you can choose Raw Data and the visible tables will show

**Expected behavior**
It should be possible to choose the raw data immediately without any errors and without refreshing
local dev, `master`, 46b8df1129e2518b9296fcc26ec60a3a98fe46c9, H2, Sample Dataset

**Severity**
Not sure - I'd say P2 because this flow is crucial and that path is one of the most used ones

**Comment by alxnddr** [comment]
I could not reproduce this one manually as well as https://github.com/metabase/metabase/issues/19776

**Comment by nemanjaglumac** [comment]
I still can.
It seems there should be only one database for this to manifest. If you have more than one database added, it will work.

**Comment by nemanjaglumac** [comment]
@alxnddr here's the video if it helps:
https://user-images.githubusercontent.com/31325167/152078988-1eb95783-5be1-475c-a57e-cf5057f06dd7.mp4

**Comment by kulyk** [comment]
I was able to reproduce that, let me see if I can add a repro and fix it

**Comment by nemanjaglumac** [comment]
> let me see if I can add a repro and fix it

@kulyk I tried using both UI and API and couldn't reproduce it using Cypress. There's something going on in the background that refreshes and updates the state, which doesn't happen if you do things manually.

If you manage to reproduce it in Cypress - great! But don't waste too much time on it.

Fix would be greatly appreciated, though :)
