### ISSUE TITLE
BigQuery errors out on syncing and does not find any table (Format SNAPSHOT is not supported)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#19860]
**Describe the bug**
I added a dataset in BigQuery but it found an error as soon as it started syncing, so nothing was synced at all and the dataset does not have any tables.

**Logs**
<details>
2022-01-23 20:51:38,066 WARN sync.util :: Error syncing _metabase_metadata table for bigquery-cloud-sdk Database 3 'Properati'
java.lang.IllegalArgumentException: Format SNAPSHOT is not supported
	at com.google.cloud.bigquery.TableDefinition.fromPb(TableDefinition.java:170)
	at com.google.cloud.bigquery.TableInfo$BuilderImpl.<init>(TableInfo.java:195)
	at com.google.cloud.bigquery.Table.fromPb(Table.java:630)
	at com.google.cloud.bigquery.BigQueryImpl$21.apply(BigQueryImpl.java:899)
	at com.google.cloud.bigquery.BigQueryImpl$21.apply(BigQueryImpl.java:896)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.cloud.PageImpl$PageIterator.computeNext(PageImpl.java:72)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at clojure.lang.RT$4.invoke(RT.java:522)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.LazySeq.first(LazySeq.java:73)
	at clojure.lang.RT.first(RT.java:692)
	at clojure.core$first__5401.invokeStatic(core.clj:55)
	at clojure.core$first__5401.invoke(core.clj:55)
	at metabase.driver.bigquery_cloud_sdk$fn__88042$iter__88043__88047$fn__88048.invoke(bigquery_cloud_sdk.clj:62)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$reduce1.invokeStatic(core.clj:932)
	at clojure.core$set.invokeStatic(core.clj:4101)
	at clojure.core$set.invoke(core.clj:4093)
	at metabase.driver.bigquery_cloud_sdk$fn__88042.invokeStatic(bigquery_cloud_sdk.clj:62)
	at metabase.driver.bigquery_cloud_sdk$fn__88042.invoke(bigquery_cloud_sdk.clj:59)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.sync.fetch_metadata$fn__68593$db_metadata__68598$fn__68599.invoke(fetch_metadata.clj:13)
	at metabase.sync.fetch_metadata$fn__68593$db_metadata__68598.invoke(fetch_metadata.clj:10)
	at metabase.sync.sync_metadata.metabase_metadata$fn__69542$sync_metabase_metadata_BANG___69547$fn__69548$fn__69549.invoke(metabase_metadata.clj:96)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:156)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:149)
	at metabase.sync.sync_metadata.metabase_metadata$fn__69542$sync_metabase_metadata_BANG___69547$fn__69548.invoke(metabase_metadata.clj:92)
	at metabase.sync.sync_metadata.metabase_metadata$fn__69542$sync_metabase_metadata_BANG___69547.invoke(metabase_metadata.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$fn__37752$run_step_with_metadata__37757$fn__37761$fn__37763.doInvoke(util.clj:360)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:116)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:113)
	at metabase.sync.util$fn__37752$run_step_with_metadata__37757$fn__37761.invoke(util.clj:355)
	at metabase.sync.util$fn__37752$run_step_with_metadata__37757.invoke(util.clj:350)
	at metabase.sync.util$fn__37943$run_sync_operation__37948$fn__37949$fn__37957.invoke(util.clj:451)
	at metabase.sync.util$fn__37943$run_sync_operation__37948$fn__37949.invoke(util.clj:449)
	at metabase.sync.util$fn__37943$run_sync_operation__37948.invoke(util.clj:443)
	at metabase.sync.sync_metadata$fn__70887$sync_db_metadata_BANG___70892$fn__70893$fn__70894.invoke(sync_metadata.clj:49)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:156)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:149)
	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
	at metabase.driver$fn__24408.invokeStatic(driver.clj:555)
	at metabase.driver$fn__24408.invoke(driver.clj:555)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__37664.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__37661.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__37650.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__37645.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__37636.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:177)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:174)
	at metabase.sync.sync_metadata$fn__70887$sync_db_metadata_BANG___70892$fn__70893.invoke(sync_metadata.clj:48)
	at metabase.sync.sync_metadata$fn__70887$sync_db_metadata_BANG___70892.invoke(sync_metadata.clj:45)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70959$fn__70961$fn__70963.invoke(sync.clj:45)
	at clojure.core$mapv$fn__8468.invoke(core.clj:6914)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__8176.invokeStatic(protocols.clj:136)
	at clojure.core.protocols$fn__8176.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8136$G__8131__8145.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8168.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8168.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6830)
	at clojure.core$mapv.invokeStatic(core.clj:6905)
	at clojure.core$mapv.invoke(core.clj:6905)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70959$fn__70961.invoke(sync.clj:45)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:156)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:149)
	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
	at metabase.driver$fn__24408.invokeStatic(driver.clj:555)
	at metabase.driver$fn__24408.invoke(driver.clj:555)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__37664.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__37661.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__37650.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__37645.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__37636.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:177)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:174)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70959.invoke(sync.clj:44)
	at metabase.sync$fn__70944$sync_database_BANG___70953.invoke(sync.clj:30)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70954.invoke(sync.clj:40)
	at metabase.sync$fn__70944$sync_database_BANG___70953.invoke(sync.clj:30)
	at metabase.events.sync_database$process_sync_database_event$fn__86793.invoke(sync_database.clj:37)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-01-23 20:51:38,067 INFO sync.util :: FINISHED: step 'sync-metabase-metadata' for bigquery-cloud-sdk Database 3 'Properati' (609.4 ms)
</details>
<details>
2022-01-23 20:51:38,067 WARN sync.util :: Error in sync step Sync metadata for bigquery-cloud-sdk Database 3 'Properati'
java.lang.ClassCastException: class java.lang.IllegalArgumentException cannot be cast to class clojure.lang.Associative (java.lang.IllegalArgumentException is in module java.base of loader 'bootstrap'; clojure.lang.Associative is in unnamed module of loader 'app')
	at clojure.lang.RT.assoc(RT.java:827)
	at clojure.core$assoc__5433.invokeStatic(core.clj:195)
	at clojure.core$assoc__5433.doInvoke(core.clj:192)
	at clojure.lang.RestFn.invoke(RestFn.java:573)
	at metabase.sync.util$fn__37752$run_step_with_metadata__37757$fn__37761.invoke(util.clj:366)
	at metabase.sync.util$fn__37752$run_step_with_metadata__37757.invoke(util.clj:350)
	at metabase.sync.util$fn__37943$run_sync_operation__37948$fn__37949$fn__37957.invoke(util.clj:451)
	at metabase.sync.util$fn__37943$run_sync_operation__37948$fn__37949.invoke(util.clj:449)
	at metabase.sync.util$fn__37943$run_sync_operation__37948.invoke(util.clj:443)
	at metabase.sync.sync_metadata$fn__70887$sync_db_metadata_BANG___70892$fn__70893$fn__70894.invoke(sync_metadata.clj:49)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:156)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:149)
	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
	at metabase.driver$fn__24408.invokeStatic(driver.clj:555)
	at metabase.driver$fn__24408.invoke(driver.clj:555)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__37664.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__37661.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__37650.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__37645.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__37636.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:177)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:174)
	at metabase.sync.sync_metadata$fn__70887$sync_db_metadata_BANG___70892$fn__70893.invoke(sync_metadata.clj:48)
	at metabase.sync.sync_metadata$fn__70887$sync_db_metadata_BANG___70892.invoke(sync_metadata.clj:45)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70959$fn__70961$fn__70963.invoke(sync.clj:45)
	at clojure.core$mapv$fn__8468.invoke(core.clj:6914)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__8176.invokeStatic(protocols.clj:136)
	at clojure.core.protocols$fn__8176.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8136$G__8131__8145.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8168.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8168.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6830)
	at clojure.core$mapv.invokeStatic(core.clj:6905)
	at clojure.core$mapv.invoke(core.clj:6905)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70959$fn__70961.invoke(sync.clj:45)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:156)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:149)
	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
	at metabase.driver$fn__24408.invokeStatic(driver.clj:555)
	at metabase.driver$fn__24408.invoke(driver.clj:555)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__37664.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__37661.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__37650.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__37645.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__37636.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:177)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:174)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70959.invoke(sync.clj:44)
	at metabase.sync$fn__70944$sync_database_BANG___70953.invoke(sync.clj:30)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70954.invoke(sync.clj:40)
	at metabase.sync$fn__70944$sync_database_BANG___70953.invoke(sync.clj:30)
	at metabase.events.sync_database$process_sync_database_event$fn__86793.invoke(sync_database.clj:37)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-01-23 20:51:38,068 INFO sync.util :: FINISHED: Sync metadata for bigquery-cloud-sdk Database 3 'Properati' (979.7 ms)
</details>
<details>
2022-01-23 20:51:38,068 WARN sync.util :: Error in sync step Sync bigquery-cloud-sdk Database 3 'Properati'
java.lang.ClassCastException: class java.lang.ClassCastException cannot be cast to class clojure.lang.Associative (java.lang.ClassCastException is in module java.base of loader 'bootstrap'; clojure.lang.Associative is in unnamed module of loader 'app')
	at clojure.lang.RT.assoc(RT.java:827)
	at clojure.core$assoc__5433.invokeStatic(core.clj:193)
	at clojure.core$assoc__5433.invoke(core.clj:192)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70959$fn__70961$fn__70963.invoke(sync.clj:45)
	at clojure.core$mapv$fn__8468.invoke(core.clj:6914)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__8176.invokeStatic(protocols.clj:136)
	at clojure.core.protocols$fn__8176.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8136$G__8131__8145.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8168.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8168.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6830)
	at clojure.core$mapv.invokeStatic(core.clj:6905)
	at clojure.core$mapv.invoke(core.clj:6905)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70959$fn__70961.invoke(sync.clj:45)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:156)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:149)
	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
	at metabase.driver$fn__24408.invokeStatic(driver.clj:555)
	at metabase.driver$fn__24408.invoke(driver.clj:555)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__37664.invoke(util.clj:135)
	at metabase.sync.util$with_db_logging_disabled$fn__37661.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:99)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:93)
	at metabase.sync.util$with_start_and_finish_logging$fn__37650.invoke(util.clj:111)
	at metabase.sync.util$with_sync_events$fn__37645.invoke(util.clj:85)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__37636.invoke(util.clj:64)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:177)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:174)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70959.invoke(sync.clj:44)
	at metabase.sync$fn__70944$sync_database_BANG___70953.invoke(sync.clj:30)
	at metabase.sync$fn__70944$sync_database_BANG___70953$fn__70954.invoke(sync.clj:40)
	at metabase.sync$fn__70944$sync_database_BANG___70953.invoke(sync.clj:30)
	at metabase.events.sync_database$process_sync_database_event$fn__86793.invoke(sync_database.clj:37)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
</details>
<details>
2022-01-23 20:51:38,069 clojure-agent-send-off-pool-17 ERROR An exception occurred processing Appender metabase-appender java.lang.IllegalArgumentException: No implementation of method: :explain of protocol: #'schema.core/Schema found for class: clojure.lang.Var$Unbound
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at schema.core$fn__3117$G__3112__3122.invoke(core.clj:110)
	at schema.core$explain_input_schema$fn__4140.invoke(core.clj:1050)
	at clojure.core$map$fn__5884.invoke(core.clj:2759)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$concat$fn__5510.invoke(core.clj:727)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:713)
	at clojure.core$next__5403.invokeStatic(core.clj:64)
	at clojure.core$print_sequential.invokeStatic(core_print.clj:64)
	at clojure.core$fn__7329.invokeStatic(core_print.clj:174)
	at clojure.core$fn__7329.invoke(core_print.clj:174)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at clojure.core$pr_on.invokeStatic(core.clj:3662)
</details>

**To Reproduce**
1) set up BigQuery
2) copy the properati-data-public Project
3) try to sync the properties_ar dataset

**Expected behavior**
See the tables in Metabase

**Screenshots**
![image](https://user-images.githubusercontent.com/1711649/150697902-ccc778bd-da5d-4371-bf1f-742682c13daf.png)

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Ubuntu 21.10
- Your databases: BigQuery
- Metabase version: 1.41.6
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Severity**
Low

**Additional context**
NA

**Comment by szukiadam** [comment]
I had a similar issue, for me using the deprecated bigquery driver solved it.

**Comment by dpsutton** [comment]
Good catch @paoliniluis 

The issue is that this public dataset has a SNAPSHOT table in it.
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/6377293/165178122-39a1b2e2-5ee7-422e-b467-0093555964b3.png">

The error being throw was "Format SNAPSHOT is not supported". Support for SNAPSHOTS came in 1.135.0 whereas we are still on 1.131.4 [changelog](https://github.com/googleapis/java-bigquery/blob/main/CHANGELOG.md#11350-2021-06-28)

I'm gonna bump to 1.135.4 for the release but i see that there is a 2.10.10 version. They introduced some breaking changes necessitating the bump to 2.x so let's release with this conservative version and investigate the changes for the next release.
