### ISSUE TITLE
Slack integration is not working

### ISSUE THREAD

**Issue by alanszp** [metabase/metabase#19962]
**Describe the bug**
Not working neither Pulse nor Alerts via slack.

**Logs**

Some logs:
```
[9f788752-ea15-42dc-9f46-acc5cd38e280] 2022-01-26T16:10:26-03:00 ERROR metabase.metabot.websocket Error connecting websocket:
clojure.lang.ExceptionInfo: Slack API error: method_deprecated {:error-code "method_deprecated", :message "Slack API error: method_deprecated", :response {:ok false, :error "method_deprecated"}, :url "https://slack.com/api/rtm.start", :request {:query-params {:token "REDACTED"}, :as :stream, :conn-timeout 10000, :socket-timeout 10000}}
	at metabase.integrations.slack$do_slack_request.invokeStatic(slack.clj:64)
	at metabase.integrations.slack$do_slack_request.invoke(slack.clj:46)
	at metabase.integrations.slack$GET.invokeStatic(slack.clj:69)
	at metabase.integrations.slack$GET.doInvoke(slack.clj:66)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.core$partial$fn__5857.invoke(core.clj:2627)
	at clojure.core$comp$fn__5825.invoke(core.clj:2572)
	at metabase.metabot.websocket$connect_websocket_BANG_.invokeStatic(websocket.clj:28)
	at metabase.metabot.websocket$connect_websocket_BANG_.invoke(websocket.clj:27)
	at metabase.metabot.websocket$reopen_websocket_connection_if_needed_BANG_.invokeStatic(websocket.clj:99)
	at metabase.metabot.websocket$reopen_websocket_connection_if_needed_BANG_.invoke(websocket.clj:89)
	at metabase.metabot.websocket$start_websocket_monitor_BANG_$fn__64813.invoke(websocket.clj:114)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
``` 
**To Reproduce**
1. Create a new bot as requested in Admin page
2. Configure given token
3. Press "Send now" on a Dashboard Pulse
4. Error like above

**Expected behavior**
Send msj to slack

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

Diagnostic Info
```
{
  "browser-info": {
    "language": "es-AR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.13+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.13",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.13+8",
    "os.name": "Linux",
    "os.version": "4.14.252-195.483.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-12-16",
      "tag": "v0.41.5",
      "branch": "release-x.41.x",
      "hash": "fbfffc6"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
blocking your usage of Metabase

**Additional context**
Looked for it before and this issue was created: https://github.com/metabase/metabase/issues/12678
It seems that new bots are not working but older ones still works

**Comment by paoliniluis** [comment]
Hi, this is because Slack deprecated the endpoints we use before they told so, we will fix this in 42. Check https://github.com/metabase/metabase/issues/19435

**Comment by mausch** [comment]
I'm getting this in v0.45.2.1 with a brand new Slack app 🤷‍♂
