### ISSUE TITLE
Metadata tooltip popup on colum header casues data table to reset for number columns that are all NULLs 

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#19976]
**Describe the bug**
New metadata tooltip popups in v0.42.0-rc1 can cause sections of the app to reset if the column is a number type and it only contains NULL values.

The section that refreshes/resets depends where the popup is triggered i.e. table headers, filter selector, dimension picker, and whether the simple or notebook editor is being used.

**Logs**
JS logs:
```
TypeError: Cannot read properties of null (reading 'toFixed')
    at O (FieldFingerprintInfo.jsx:74:67)
    at Qo (react-dom.production.min.js:153:146)
    at xs (react-dom.production.min.js:261:496)
    at yl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
    at ll (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vi (react-dom.production.min.js:122:325)
    at Zi (react-dom.production.min.js:123:61)
overrideMethod @ VM17260 react_devtools_backend.js:4061
os @ react-dom.production.min.js:209
Ms.o.componentDidCatch.n.callback @ react-dom.production.min.js:227
vo @ react-dom.production.min.js:131
us @ react-dom.production.min.js:212
Ml @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
wl @ react-dom.production.min.js:248
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
rl @ react-dom.production.min.js:230
_a @ react-dom.production.min.js:163
onMount @ TippyPopover.tsx:43
(anonymous) @ tippy.esm.js:756
D @ tippy.esm.js:754
s @ tippy.esm.js:1434
(anonymous) @ createPopper.js:217
Promise.then (async)
(anonymous) @ createPopper.js:215
Z @ tippy.esm.js:1161
(anonymous) @ tippy.esm.js:1197
show @ tippy.esm.js:1444
(anonymous) @ tippy.esm.js:1230
setTimeout (async)
ee @ tippy.esm.js:1229
U @ tippy.esm.js:1008
VM17260 react_devtools_backend.js:4061 Error caught in <Visualization> TypeError: Cannot read properties of null (reading 'toFixed')
    at O (FieldFingerprintInfo.jsx:74:67)
    at Qo (react-dom.production.min.js:153:146)
    at xs (react-dom.production.min.js:261:496)
    at yl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
    at ll (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vi (react-dom.production.min.js:122:325)
    at Zi (react-dom.production.min.js:123:61) {componentStack: '\n    in O\n    in g\n    in DimensionInfostyled__Fie…\n    in t\n    in DragDropContextProvider\n    in a'}
overrideMethod @ VM17260 react_devtools_backend.js:4061
value @ Visualization.jsx:101
Ms.o.componentDidCatch.n.callback @ react-dom.production.min.js:227
vo @ react-dom.production.min.js:131
us @ react-dom.production.min.js:212
Ml @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
wl @ react-dom.production.min.js:248
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
rl @ react-dom.production.min.js:230
_a @ react-dom.production.min.js:163
onMount @ TippyPopover.tsx:43
(anonymous) @ tippy.esm.js:756
D @ tippy.esm.js:754
s @ tippy.esm.js:1434
(anonymous) @ createPopper.js:217
Promise.then (async)
(anonymous) @ createPopper.js:215
Z @ tippy.esm.js:1161
(anonymous) @ tippy.esm.js:1197
show @ tippy.esm.js:1444
(anonymous) @ tippy.esm.js:1230
setTimeout (async)
ee @ tippy.esm.js:1229
U @ tippy.esm.js:1008
VM17260 react_devtools_backend.js:4061 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Error%3A%20An%20error%20occurred%20displaying%20this%20visualization.&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at To (react-dom.production.min.js:139:47)
    at react-dom.production.min.js:149:278
    at za (react-dom.production.min.js:173:103)
    at xs (react-dom.production.min.js:265:156)
    at yl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
    at ll (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vi (react-dom.production.min.js:122:325)
overrideMethod @ VM17260 react_devtools_backend.js:4061
os @ react-dom.production.min.js:209
Ms.o.componentDidCatch.n.callback @ react-dom.production.min.js:227
vo @ react-dom.production.min.js:131
us @ react-dom.production.min.js:212
Ml @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
wl @ react-dom.production.min.js:248
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
rl @ react-dom.production.min.js:230
_a @ react-dom.production.min.js:163
onMount @ TippyPopover.tsx:43
(anonymous) @ tippy.esm.js:756
D @ tippy.esm.js:754
s @ tippy.esm.js:1434
(anonymous) @ createPopper.js:217
Promise.then (async)
(anonymous) @ createPopper.js:215
Z @ tippy.esm.js:1161
(anonymous) @ tippy.esm.js:1197
show @ tippy.esm.js:1444
(anonymous) @ tippy.esm.js:1230
setTimeout (async)
ee @ tippy.esm.js:1229
U @ tippy.esm.js:1008
2VM17260 react_devtools_backend.js:4061 Warning: can't clean query without metadata!
overrideMethod @ VM17260 react_devtools_backend.js:4061
value @ StructuredQuery.ts:339
value @ Question.ts:1197
value @ Question.ts:926
C @ urls.js:95
value @ Navbar.jsx:171
value @ Navbar.jsx:286
Wa @ react-dom.production.min.js:182
Ba @ react-dom.production.min.js:181
xs @ react-dom.production.min.js:263
yl @ react-dom.production.min.js:246
ml @ react-dom.production.min.js:246
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
rl @ react-dom.production.min.js:230
_a @ react-dom.production.min.js:163
onMount @ TippyPopover.tsx:43
(anonymous) @ tippy.esm.js:756
D @ tippy.esm.js:754
s @ tippy.esm.js:1434
(anonymous) @ createPopper.js:217
Promise.then (async)
(anonymous) @ createPopper.js:215
Z @ tippy.esm.js:1161
(anonymous) @ tippy.esm.js:1197
show @ tippy.esm.js:1444
(anonymous) @ tippy.esm.js:1230
setTimeout (async)
ee @ tippy.esm.js:1229
U @ tippy.esm.js:1008
VM17260 react_devtools_backend.js:4061 Warning: can't clean query without metadata!
overrideMethod @ VM17260 react_devtools_backend.js:4061
value @ StructuredQuery.ts:339
value @ Question.ts:1197
value @ Question.ts:926
C @ urls.js:95
value @ Navbar.jsx:171
value @ Navbar.jsx:286
Wa @ react-dom.production.min.js:182
Ba @ react-dom.production.min.js:181
xs @ react-dom.production.min.js:263
yl @ react-dom.production.min.js:246
ml @ react-dom.production.min.js:246
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
rl @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
_.setState @ react.production.min.js:12
l.onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:62
l.onStateChange @ connectAdvanced.js:204
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:62
l.onStateChange @ connectAdvanced.js:204
d @ createStore.js:172
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
action @ store.js:20
(anonymous) @ actions.js:613
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
ne @ app-main.bundle.js?863fbcce303099f75185:2
a @ app-main.bundle.js?863fbcce303099f75185:2
Promise.then (async)
ne @ app-main.bundle.js?863fbcce303099f75185:2
a @ app-main.bundle.js?863fbcce303099f75185:2
(anonymous) @ app-main.bundle.js?863fbcce303099f75185:2
(anonymous) @ app-main.bundle.js?863fbcce303099f75185:2
(anonymous) @ actions.js:356
(anonymous) @ store.js:23
(anonymous) @ bindActionCreators.js:3
value @ QueryBuilder.jsx:170
ko @ react-dom.production.min.js:137
Ba @ react-dom.production.min.js:176
xs @ react-dom.production.min.js:263
yl @ react-dom.production.min.js:246
ml @ react-dom.production.min.js:246
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
rl @ react-dom.production.min.js:230
_a @ react-dom.production.min.js:163
onMount @ TippyPopover.tsx:43
(anonymous) @ tippy.esm.js:756
D @ tippy.esm.js:754
s @ tippy.esm.js:1434
(anonymous) @ createPopper.js:217
Promise.then (async)
(anonymous) @ createPopper.js:215
Z @ tippy.esm.js:1161
(anonymous) @ tippy.esm.js:1197
show @ tippy.esm.js:1444
(anonymous) @ tippy.esm.js:1230
setTimeout (async)
ee @ tippy.esm.js:1229
U @ tippy.esm.js:1008
Show 10 more frames
3react-dom.production.min.js:49 Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at react-dom.production.min.js:49:67
    at it (react-dom.production.min.js:50:217)
    at Object.t.findDOMNode (react-dom.production.min.js:289:336)
    at s.value (ExplicitSize.jsx:31:23)
    at ExplicitSize.jsx:101:28
    at c (throttle.js:32:21)
(anonymous) @ react-dom.production.min.js:49
it @ react-dom.production.min.js:50
t.findDOMNode @ react-dom.production.min.js:289
value @ ExplicitSize.jsx:31
(anonymous) @ ExplicitSize.jsx:101
c @ throttle.js:32
setTimeout (async)
value @ ExplicitSize.jsx:44
us @ react-dom.production.min.js:212
Ml @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
wl @ react-dom.production.min.js:248
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
rl @ react-dom.production.min.js:230
_a @ react-dom.production.min.js:163
onMount @ TippyPopover.tsx:43
(anonymous) @ tippy.esm.js:756
D @ tippy.esm.js:754
s @ tippy.esm.js:1434
(anonymous) @ createPopper.js:217
Promise.then (async)
(anonymous) @ createPopper.js:215
Z @ tippy.esm.js:1161
(anonymous) @ tippy.esm.js:1197
show @ tippy.esm.js:1444
(anonymous) @ tippy.esm.js:1230
setTimeout (async)
ee @ tippy.esm.js:1229
U @ tippy.esm.js:1008
VM17260 react_devtools_backend.js:4061 Warning: can't clean query without metadata!
overrideMethod @ VM17260 react_devtools_backend.js:4061
value @ StructuredQuery.ts:339
value @ Question.ts:1197
value @ Question.ts:926
C @ urls.js:95
value @ Navbar.jsx:171
value @ Navbar.jsx:286
Wa @ react-dom.production.min.js:182
Ba @ react-dom.production.min.js:181
xs @ react-dom.production.min.js:263
yl @ react-dom.production.min.js:246
ml @ react-dom.production.min.js:246
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
rl @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
_.setState @ react.production.min.js:12
l.onStateChange @ connectAdvanced.js:207
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:62
l.onStateChange @ connectAdvanced.js:204
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:62
l.onStateChange @ connectAdvanced.js:204
d @ createStore.js:172
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ store.js:25
dispatch @ applyMiddleware.js:35
action @ store.js:20
(anonymous) @ actions.js:1287
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
ne @ app-main.bundle.js?863fbcce303099f75185:2
a @ app-main.bundle.js?863fbcce303099f75185:2
(anonymous) @ app-main.bundle.js?863fbcce303099f75185:2
(anonymous) @ app-main.bundle.js?863fbcce303099f75185:2
(anonymous) @ actions.js:1220
(anonymous) @ store.js:23
dispatch @ applyMiddleware.js:35
(anonymous) @ actions.js:628
setTimeout (async)
(anonymous) @ actions.js:625
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
ne @ app-main.bundle.js?863fbcce303099f75185:2
a @ app-main.bundle.js?863fbcce303099f75185:2
Promise.then (async)
ne @ app-main.bundle.js?863fbcce303099f75185:2
a @ app-main.bundle.js?863fbcce303099f75185:2
(anonymous) @ app-main.bundle.js?863fbcce303099f75185:2
(anonymous) @ app-main.bundle.js?863fbcce303099f75185:2
(anonymous) @ actions.js:356
(anonymous) @ store.js:23
(anonymous) @ bindActionCreators.js:3
value @ QueryBuilder.jsx:170
ko @ react-dom.production.min.js:137
Ba @ react-dom.production.min.js:176
xs @ react-dom.production.min.js:263
yl @ react-dom.production.min.js:246
ml @ react-dom.production.min.js:246
ll @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Zi @ react-dom.production.min.js:123
Ki @ react-dom.production.min.js:122
rl @ react-dom.production.min.js:230
_a @ react-dom.production.min.js:163
onMount @ TippyPopover.tsx:43
(anonymous) @ tippy.esm.js:756
D @ tippy.esm.js:754
s @ tippy.esm.js:1434
(anonymous) @ createPopper.js:217
Promise.then (async)
(anonymous) @ createPopper.js:215
Z @ tippy.esm.js:1161
(anonymous) @ tippy.esm.js:1197
show @ tippy.esm.js:1444
(anonymous) @ tippy.esm.js:1230
setTimeout (async)
ee @ tippy.esm.js:1229
U @ tippy.esm.js:1008
Show 16 more frames
VM17260 react_devtools_backend.js:4061 Warning: can't clean query without metadata!
```

**To Reproduce**
1. Create a table with and int column that is all NULL values. Mine looks like this in SQL Server
![image](https://user-images.githubusercontent.com/4504437/151288608-da1c0133-4ae6-42a7-9bd4-a3e074850524.png)
2. Sync DB schema
3. New question for that table, visualised as a table
3. Hover the column header for your column of all NULL ints
4. Data table will refresh

**Expected behavior**
A tooltip should be presented as with other columns.

**Screenshots**
![metabase_issue](https://user-images.githubusercontent.com/4504437/151289560-dbedce51-90a5-493e-9853-208dc3c27a72.gif)

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-NZ",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "13.0.2",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "13.0.2+8",
    "os.name": "Windows 10",
    "os.version": "10.0",
    "user.language": "en",
    "user.timezone": "Pacific/Auckland"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "clickhouse",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.1"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.23"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-01-20",
      "tag": "v0.42.0-rc1",
      "branch": "release-x.42.x",
      "hash": "2af85ba"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
Low, the number of columns that meet this criteria in our system are low but greater than 0. It does make it hard to work with tables that contain them though as you can very easily accidentally trigger a refresh.

This doesn't seem to trigger for varchar columns.

**Comment by nemanjaglumac** [comment]
Tried to solve this on the frontend, but it seems that the backend sends `null` for `avg`, `min` and `max` if at least one row value is `null`.

The code for this is here:
https://github.com/metabase/metabase/blob/4585caf3b442b7a674b84652ca5f5e1f7b0338ac/src/metabase/sync/analyze/fingerprint/fingerprinters.clj#L219

Interestingly, if you try to get the average on that whole column, that works.
![image](https://user-images.githubusercontent.com/31325167/151468228-6b152a21-e119-4621-b4b0-43c44b569893.png)

My attempt to fix this is **only** preventing FE to throw if it receives the value it doesn't expect (`null`), but that's not a proper solution for this issue.

**Comment by dpsutton** [comment]
I'm convinced that this is a bug on the FE.

Compute the fingerprint for the sequence of values `[1 2 3]`:
```clojure
fingerprinters=> (transduce identity
                            (fingerprinter {:base_type :type/Number})
                            [1 2 3])
{:global {:distinct-count 3, :nil% 0.0},
 :type {:type/Number {:min 1.0,
                      :q1 1.25,
                      :q3 2.75,
                      :max 3.0,
                      :sd 1.0,
                      :avg 2.0}}}
```
And we get sensible results.

Now compute for 1 value and 100,000 nils:
```clojure
fingerprinters=> (transduce identity
                            (fingerprinter {:base_type :type/Number})
                            (cons 1 (repeat 100000 nil)))
{:global {:distinct-count 2, :nil% 0.999990000099999},
 :type {:type/Number {:min 1.0,
                      :q1 1.0,
                      :q3 1.0,
                      :max 1.0,
                      :sd nil,
                      :avg 1.0}}}
```
and again we get sensible results. Note that the standard deviation is nil. But this is because there is no deviation. If we recompute for 20,000 values of `3` we get the same result.

```clojure
fingerprinters=> (transduce identity
                            (fingerprinter {:base_type :type/Number})
                            (repeat 20000 3))
{:global {:distinct-count 1, :nil% 0.0},
 :type {:type/Number {:min 3.0,
                      :q1 3.0,
                      :q3 3.0,
                      :max 3.0,
                      :sd 0.0,
                      :avg 3.0}}}
```

So finally, what are the reasonable values for all nils (the scenario in this issue):
```clojure
fingerprinters=> (transduce identity
                            (fingerprinter {:base_type :type/Number})
                            (repeat 20 nil))
{:global {:distinct-count 1, :nil% 1.0},
 :type {:type/Number {:min nil,
                      :q1 nil,
                      :q3 nil,
                      :max nil,
                      :sd nil,
                      :avg nil}}}
```
Our code returns nil for all values and this seems like the only reasonable choice. I think the FE needs to accommodate these results.

**Comment by dpsutton** [comment]
On second thought, the variance being nil instead of 0 is a bug on the backend. The values being nil in the absence of values seems right to me.
