### ISSUE TITLE
Exception while trying to pass client certificates to Postgres on 0.41-rc1

### ISSUE THREAD

**Issue by andrioni** [metabase/metabase#19984]
**Describe the bug**
While using the 0.42-rc1 JAR, every time I try to connect to a Postgres database using a client certificate (be it a local file or uploaded), Metabase returns a 400, which causes the web UI to reload the "create connection" page without showing any errors. The connection also doesn't get created. This happens no matter what file I pass as the client certificate or client key, and even if I'm not pointing to a valid database. I couldn't find from the Postgres side any logs about the attempted connection.

**Logs**
Server logs:
```
2022-01-27 14:16:16,529 ERROR driver.util :: Database connection error
java.lang.NullPointerException
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
	at metabase.models.secret$value__GT_file_BANG_$fn__33758.invoke(secret.clj:97)
	at metabase.models.secret$value__GT_file_BANG_.invokeStatic(secret.clj:90)
	at metabase.models.secret$value__GT_file_BANG_.invoke(secret.clj:54)
	at metabase.driver.postgres$ssl_params.invokeStatic(postgres.clj:375)
	at metabase.driver.postgres$ssl_params.invoke(postgres.clj:354)
	at metabase.driver.postgres$fn__53514.invokeStatic(postgres.clj:403)
	at metabase.driver.postgres$fn__53514.invoke(postgres.clj:393)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invokeStatic(connection.clj:240)
	at metabase.driver.sql_jdbc.connection$details__GT_connection_spec_for_testing_connection.invoke(connection.clj:235)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:253)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:249)
	at metabase.driver.sql_jdbc$fn__81371.invokeStatic(sql_jdbc.clj:35)
	at metabase.driver.sql_jdbc$fn__81371.invoke(sql_jdbc.clj:33)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__19263.invoke(util.clj:48)
	at metabase.util$do_with_timeout$fn__6209.invoke(util.clj:352)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-01-27 14:16:16,534 ERROR api.database :: Cannot connect to Database
java.lang.NullPointerException
2022-01-27 14:16:16,541 DEBUG middleware.log :: POST /api/database 400 13,4 ms (0 DB calls)
{:valid false, :dbname nil, :message nil}
```

**To Reproduce**
1. Start Metabase on 0.42-rc1 using the prebuilt JAR
2. Go to the "Add Database" admin page (`/admin/databases/create`)
3. Fill regular settings with arbitrary details, the issue happens even if pointing to an invalid host
4. Turn "Use a secure connection (SSL)" on
5. Turn "Authenticate client certificate?" on
6. Pass an arbitrary file path to the "File path" for either the "SSL Client Certificate (PEM)" or the "SSL Client Key (PKCS-8/DER or PKCS-12)"
7. Click on "Save"
8. Page then reloads with no fields set, the exception above is logged in the server.

**Expected behavior**
I expected that Metabase would try to connect to my Postgres database with the specified client key and certificate.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.12+0",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "11.0.12",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.12+0",
    "os.name": "Mac OS X",
    "os.version": "11.5.2",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-01-20",
      "tag": "v0.42.0-rc1",
      "branch": "release-x.42.x",
      "hash": "2af85ba"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
This is blocking my usage of Metabase Cloud, since I can't connect to my secured Postgres database: when self-hosting Metabase, I was already able to preinstall my client certificates and pass them via the additional JDBC connection string, but I want to migrate to Metabase Cloud, which would require uploading the client certificates. I was testing 0.42-rc1 to see if it would fix my issue once it is rolled out to Metabase Cloud.

**Additional context**
This is on a 2020 M1 MacBook Pro running macOS 11.5.2, using a native ARM64 JVM, running the JAR directly via `java -jar`.

**Comment by jeff303** [comment]
@andrioni , you are not setting a truststore at all, only a client cert?
