### ISSUE TITLE
Dashboard Embedding and Sharing [v0.42.0]

### ISSUE THREAD

**Issue by luke-davies-al** [metabase/metabase#20622]
When attempting to set a parameter as 'locked' when embedding a dashboard receive the following error and redirected to the dashboard:

TypeError: Cannot read properties of undefined (reading 'some')
    at new i (fields.js:2:27)
    at xo (react-dom.production.min.js:134:171)
    at Ba (react-dom.production.min.js:176:149)
    at xs (react-dom.production.min.js:263:490)
    at yl (react-dom.production.min.js:246:265)
    at ml (react-dom.production.min.js:246:194)
    at ll (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vi (react-dom.production.min.js:122:325)
os @ react-dom.production.min.js:209

**Comment by flamber** [comment]
Upgrade to 0.42.1: https://github.com/metabase/metabase/releases/latest
