### ISSUE TITLE
Setting a filter to "Locked" in Embedding question is not possible

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20634]
**Describe the bug**
Repeat of #20357, but for questions.

**To Reproduce**
1. Native > Sample > `select {{text}}` - save question
2. Sharing (botton-right) > Embedding > change Text filter to "Locked" - frontend reloads

```
TypeError: Cannot read properties of undefined (reading 'some')
    at new i (app-main.bundle.js:2:1309783)
    at xo (vendor.bundle.js:2:4361443)
    at Ba (vendor.bundle.js:2:4378861)
    at xs (vendor.bundle.js:2:4416918)
    at yl (vendor.bundle.js:2:4408392)
    at ml (vendor.bundle.js:2:4408317)
    at ll (vendor.bundle.js:2:4405347)
    at vendor.bundle.js:2:4357101
    at t.unstable_runWithPriority (vendor.bundle.js:2:4940167)
    at Vi (vendor.bundle.js:2:4356810)
```

**Information about your Metabase Installation:**
0.42.1

**Comment by reediculous456** [comment]
1. <details>
      <summary>Post "Diagnostic Info" from Admin > Troubleshooting.</summary>

     ```json
    {
      "browser-info": {
        "language": "en-US",
        "platform": "MacIntel",
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36",
        "vendor": "Google Inc."
      },
      "system-info": {
        "file.encoding": "UTF-8",
        "java.runtime.name": "OpenJDK Runtime Environment",
        "java.runtime.version": "11.0.14.1+1",
        "java.vendor": "Eclipse Adoptium",
        "java.vendor.url": "https://adoptium.net/",
        "java.version": "11.0.14.1",
        "java.vm.name": "OpenJDK 64-Bit Server VM",
        "java.vm.version": "11.0.14.1+1",
        "os.name": "Linux",
        "os.version": "5.10.76-linuxkit",
        "user.language": "en",
        "user.timezone": "GMT"
      },
      "metabase-info": {
        "databases": [
          "h2",
          "postgres"
        ],
        "hosting-env": "unknown",
        "application-database": "h2",
        "application-database-details": {
          "database": {
            "name": "H2",
            "version": "1.4.197 (2018-03-18)"
          },
          "jdbc-driver": {
            "name": "H2 JDBC Driver",
            "version": "1.4.197 (2018-03-18)"
          }
        },
        "run-mode": "prod",
        "version": {
          "date": "2022-02-17",
          "tag": "v0.42.1",
          "branch": "release-x.42.x",
          "hash": "629f4de"
        },
        "settings": {
          "report-timezone": null
        }
      }
    }
    ```
    </details>

2. Post the browser console errors.

![Screen Shot 2022-02-18 at 12 07 05 PM](https://user-images.githubusercontent.com/24629474/154729404-2dc34dea-3592-4e2e-bdcb-36228593d646.png)
![Screen Shot 2022-02-18 at 12 07 17 PM](https://user-images.githubusercontent.com/24629474/154729439-13552984-e524-4898-ae54-8a61ce02d833.png)

3. Steps to reproduce

    1. Start a new Metabase instance `docker run -p 3000:3000 -d metabase/metabase:v0.42.1`
    2. Enable embedding from Admin Settings
    3. Make a new SQL query with this content from the sample db
    
    ```sql
    SELECT * FROM ORDERS
    WHERE {{ productId }}
    ```
    ![Screen Shot 2022-02-18 at 12 11 25 PM](https://user-images.githubusercontent.com/24629474/154730043-8238d9fb-475a-4f1b-b036-1a7c239788b8.png)
    
    4. Save question and share
    5. Set param to locked
    6. See issue
