### ISSUE TITLE
BigQuery new driver fails to connect reporting timeout after 10s

### ISSUE THREAD

**Issue by JianhaoZhang** [metabase/metabase#20758]
**Describe the bug**
BigQuery driver fails after we upgraded the metabase version to 0.42.1.
It consistently reporting timeout after 10s.

**Logs**

> 2022-02-28 00:41:20,538 ERROR driver.util :: Database connection error
java.util.concurrent.TimeoutException: Timed out after 10.0 s
	at metabase.util$deref_with_timeout.invokeStatic(util.clj:343)
	at metabase.util$deref_with_timeout.invoke(util.clj:335)
	at metabase.util$do_with_timeout.invokeStatic(util.clj:349)
	at metabase.util$do_with_timeout.invoke(util.clj:346)
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:47)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:36)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.api.database$test_database_connection.invokeStatic(database.clj:431)
	at metabase.api.database$test_database_connection.doInvoke(database.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.api.database$fn__73304$test_connection_details__73309$fn__73310.invoke(database.clj:478)
	at metabase.api.database$fn__73304$test_connection_details__73309.invoke(database.clj:460)
	at metabase.api.database$fn__73336.invokeStatic(database.clj:498)
	at metabase.api.database$fn__73336.invoke(database.clj:484)
	at compojure.core$wrap_response$fn__32271.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__32255.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__32260.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:151)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__65343.invoke(auth.clj:14)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at compojure.core$make_context$handler__32311.invoke(core.clj:289)
	at compojure.core$make_context$fn__32315.invoke(core.clj:299)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at metabase.api.routes$fn__76468$fn__76471.invoke(routes.clj:56)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__76613$fn__76614.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at compojure.core$make_context$handler__32311.invoke(core.clj:289)
	at compojure.core$make_context$fn__32315.invoke(core.clj:299)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at metabase.server.routes$fn__76601$fn__76603.invoke(routes.clj:41)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73596.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__73593.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__77079$fn__77080$fn__77081.invoke(log.clj:209)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__77079$fn__77080.invoke(log.clj:201)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__77079.invoke(log.clj:200)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__80432.invoke(browser_cookie.clj:38)
	at metabase.server.middleware.security$add_security_headers$fn__55203.invoke(security.clj:148)
	at metabase.server.middleware.json$wrap_json_body$fn__79587.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__79605.invoke(json.clj:98)
	at metabase.server.middleware.offset_paging$handle_paging$fn__55227.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__80699.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__80715.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__34377.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__45720$fn__45721.invoke(session.clj:262)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:243)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:235)
	at metabase.server.middleware.session$bind_current_user$fn__45720.invoke(session.clj:261)
	at metabase.server.middleware.session$wrap_current_user_info$fn__45707.invoke(session.clj:221)
	at metabase.server.middleware.session$wrap_session_id$fn__45693.invoke(session.clj:167)
	at metabase.server.middleware.auth$wrap_api_key$fn__65351.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__80619.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__34360.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__34385.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__80661.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__34388.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80448.invoke(ssl.clj:38)
	at metabase.server$async_proxy_handler$fn__76852.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-02-28 00:41:20,540 ERROR api.database :: Cannot connect to Database
java.lang.Exception: Timed out after 10.0 s
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:53)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:36)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.api.database$test_database_connection.invokeStatic(database.clj:431)
	at metabase.api.database$test_database_connection.doInvoke(database.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.api.database$fn__73304$test_connection_details__73309$fn__73310.invoke(database.clj:478)
	at metabase.api.database$fn__73304$test_connection_details__73309.invoke(database.clj:460)
	at metabase.api.database$fn__73336.invokeStatic(database.clj:498)
	at metabase.api.database$fn__73336.invoke(database.clj:484)
	at compojure.core$wrap_response$fn__32271.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__32255.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__32260.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:151)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__65343.invoke(auth.clj:14)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at compojure.core$make_context$handler__32311.invoke(core.clj:289)
	at compojure.core$make_context$fn__32315.invoke(core.clj:299)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at metabase.api.routes$fn__76468$fn__76471.invoke(routes.clj:56)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__76613$fn__76614.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at compojure.core$make_context$handler__32311.invoke(core.clj:289)
	at compojure.core$make_context$fn__32315.invoke(core.clj:299)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at metabase.server.routes$fn__76601$fn__76603.invoke(routes.clj:41)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73596.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__73593.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__77079$fn__77080$fn__77081.invoke(log.clj:209)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__77079$fn__77080.invoke(log.clj:201)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__77079.invoke(log.clj:200)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__80432.invoke(browser_cookie.clj:38)
	at metabase.server.middleware.security$add_security_headers$fn__55203.invoke(security.clj:148)
	at metabase.server.middleware.json$wrap_json_body$fn__79587.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__79605.invoke(json.clj:98)
	at metabase.server.middleware.offset_paging$handle_paging$fn__55227.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__80699.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__80715.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__34377.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__45720$fn__45721.invoke(session.clj:262)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:243)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:235)
	at metabase.server.middleware.session$bind_current_user$fn__45720.invoke(session.clj:261)
	at metabase.server.middleware.session$wrap_current_user_info$fn__45707.invoke(session.clj:221)
	at metabase.server.middleware.session$wrap_session_id$fn__45693.invoke(session.clj:167)
	at metabase.server.middleware.auth$wrap_api_key$fn__65351.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__80619.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__34360.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__34385.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__80661.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__34388.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80448.invoke(ssl.clj:38)
	at metabase.server$async_proxy_handler$fn__76852.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.TimeoutException: Timed out after 10.0 s
	at metabase.util$deref_with_timeout.invokeStatic(util.clj:343)
	at metabase.util$deref_with_timeout.invoke(util.clj:335)
	at metabase.util$do_with_timeout.invokeStatic(util.clj:349)
	at metabase.util$do_with_timeout.invoke(util.clj:346)
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:47)
	... 111 more
2022-02-28 00:41:20,545 DEBUG middleware.log :: POST /api/database 400 10.0 s (0 DB calls) 
{:valid false, :dbname "Timed out after 10.0 s", :message "Timed out after 10.0 s"}

> 2022-02-28 00:41:20,572 DEBUG middleware.log :: GET /api/database 200 1.7 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 6/50 (3 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued)

**To Reproduce**
1. Setup a BigQuery service account with roles: 
BigQuery Data Viewer
BigQuery Metadata Viewer
BigQuery Job User (distinct from BigQuery User)
2. And with inheritance to allow granular control of which dataset is visible to this service account ![2022-02-27_19-55](https://user-images.githubusercontent.com/19567494/155908556-400ac4f0-bfca-4331-b877-64ce056c6ce2.png)
3. Download the key-file.json
4. Apply it in metabase -> admin setting -> add database -> service account JSON file
5. Select All / Only these datasets (accessible ones)
6. Fail with timeout

**Expected behavior**
It should be working. The exact key-file.json is still working after switching to BigQuery (Deprecated Driver)

**Screenshots**
![Screenshot from 2022-02-27 20-13-01](https://user-images.githubusercontent.com/19567494/155909001-e376ac16-ebb7-4f25-8230-aa4fa93b0fd8.png)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
It is blocking us from upgrading metabase and migrating to the new BigQuery driver.

**Additional context**
I doubt it has something to do with GCP IAM role inheritance setting, but it works quite well on the old driver.
I suggest not completely remove the deprecated driver if the new one does not meet feature parity.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1",
    "os.name": "Linux",
    "os.version": "5.11.0-49-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-02-17",
      "tag": "v0.42.1",
      "branch": "release-x.42.x",
      "hash": "629f4de"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @JianhaoZhang 
Which version did you upgrade from?
How many datasets do you have?
What happens if you only specify a single dataset?

**Comment by JianhaoZhang** [comment]
@flamber 
Upgraded from v0.40.5.
Number of datasets accessible from the service account is 5.
Still no luck if I only specify a single dataset.

**Comment by flamber** [comment]
@JianhaoZhang 
So were you using the old or the new BigQuery driver on 0.40.5 initially?
I'm trying to figure out when this problem started, since it might not have been 0.42.1, but simply just a change of driver.

Metabase validates a connection by doing a simple `select 1` for most databases, but for BigQuery it lists the tables, so somehow it's failing to do that (or not getting any results for 10 seconds), but it should create a stacktrace specific about that and not just the generic timeout error.
https://github.com/metabase/metabase/blob/release-x.42.x/modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj#L86-L92

I'm unsure what you mean about "inheritance", but are you able to use DBeaver with the same credentials (Service Account)?
Have you tried creating different permissions and service accounts?
It's important to figure out a solution for this, since the old BigQuery driver has been removed in the upcoming 0.43.

Unrelated, you should migrate away from H2 if you are using Metabase in production:
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html

**Comment by JianhaoZhang** [comment]
@flamber I think you are right, it should be only a problem with the BigQuery driver. I switched a few versions, and the deprecated driver always work, but the new one does not. Maybe I have upgraded from a version older than 0.40.5 where the old driver was still default. I have tested another service account that has full(admin) access to the BigQuery project, it works with option "All" datasets, but still not able to select a specific dataset. It might be another bug?

**Comment by JianhaoZhang** [comment]
@flamber That inheritance basically means the service account's privileges are not granted on the whole project entity, but only certain datasets in it.

**Comment by flamber** [comment]
@JianhaoZhang I simply don't know enough about BigQuery permissions, or why it works on the old driver, since it looks similar how they work, but it might be something in the upstream driver, where we're currently using 1.131.1, which is fairly old compared to latest 2.9.0 https://github.com/googleapis/java-bigquery

Try using www.DBeaver.io with the same version as Metabase - they are both Java applications and uses same drivers in most cases.

**Comment by JianhaoZhang** [comment]
@flamber Thanks, I will try DBeaver later and let you know if it works or not.

**Comment by JianhaoZhang** [comment]
> @JianhaoZhang I simply don't know enough about BigQuery permissions, or why it works on the old driver, since it looks similar how they work, but it might be something in the upstream driver, where we're currently using 1.131.1, which is fairly old compared to latest 2.9.0 https://github.com/googleapis/java-bigquery
> 
> Try using [www.DBeaver.io](http://www.DBeaver.io) with the same version as Metabase - they are both Java applications and uses same drivers in most cases.

I couldn't find a way to precisely use com.google.cloud:google-cloud-bigquery:1.131.1 to connect in DBeaver. It doesn't seem trivial.
Google's recommended JDBC drivers(also the ones integrated in DBeaver) are called Simba and I am not sure what version of library do they use.
I tried to connect with some oldest possible Simba JDBC drivers, and they seem to work without a problem.

**Comment by JianhaoZhang** [comment]
@flamber It seems like the new driver "sometimes" works. I have successfully connected for a few times when there are only one or two tables in the dataset specified. But it never succeeded when there are many tables. Wondering if it is really caused by 10s timeout being too short?

**Comment by flamber** [comment]
@JianhaoZhang Check your BigQuery query log to see if you see queries during the connection.
You can check the timeout with the environment variable [MB_DB_CONNECTION_TIMEOUT_MS](https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_db_connection_timeout_ms)=20000 (20 seconds example)

**Comment by JianhaoZhang** [comment]
@flamber Checking in again on this issue because recently the deprecated BigQuery driver seems to be removed. 
The environment variable for timeout does not work even if I set it to 120000 seconds (2 mins).

I have skimmed through [the implementation](https://github.com/metabase/metabase/blob/master/modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj) of the bigquery driver. It seems to me that the problem might has something to do with the logic of locating datasets. The driver tries to access all datasets in the GCP project and then filters out datasets with patterns from the whole list. If the provided service account can only access certain datasets instead of all of them, the connector will fail indefinitely.
Maybe such granular service accounts are not considered in design but I still think it is really important. Setting up a connection with service account accessing all resources in the project is somewhat a data governance nightmare, not to mention feature-wise it is a step backward from the old connector.

**Comment by JianhaoZhang** [comment]
@flamber I'm not sure what have you changed recently, but the problem cease to exist in the latest version.

**Comment by flamber** [comment]
@JianhaoZhang I don't know what "latest version" is for you, but the BigQuery driver was upgraded to 1.135.4 in Metabase 0.43.0, so I guess it was a driver issue. It will require a lot more work to upgrade to BigQuery 2.x. Closing for now.

**Comment by bhaskoro-muthohar** [comment]
Any updates? I have the same issue using `metabase:latest`
