### ISSUE TITLE
Static visualization for Stacked bars can fail, when there's gaps in data

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#20752]
**Describe the bug**
Static visualization for Stacked bars can fail, when there's gaps in data. Also static viz doesn't show stacking at all.

Regression since 0.42.0

**To Reproduce**
1. Question > Sample > Products - summarize Count grouped by CreatedAt:Week and Category
![image](https://user-images.githubusercontent.com/1447303/155758703-fc5bb540-fa2f-4f8f-a0aa-a92fb7277a5b.png)
2. Visualization > Bar > Display > Stacking = Stack
![image](https://user-images.githubusercontent.com/1447303/155758813-f72d4324-17bb-418f-91d0-8f102b3bccf4.png)
3. Save and add to dashboard
4. Try to send subscription via "Send email now" - it will it has successfully sent.
5. The received email will contain an error instead of image: `An error occurred while displaying this card.`

<details><summary>Full stacktrace</summary>

```
2022-02-25 18:12:45,520 ERROR pulse.render :: Pulse card render error
TypeError: Cannot read property '1' of undefined
	at <js> Ng(file:/home/hansen/Downloads/Metabase/test-MASTER/metabase-0.42.1.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:395833-395836)
	at <js> r(file:/home/hansen/Downloads/Metabase/test-MASTER/metabase-0.42.1.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:404502-404517)
	at <js> :anonymous(file:/home/hansen/Downloads/Metabase/test-MASTER/metabase-0.42.1.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:403571-404565)
	at <js> l(file:/home/hansen/Downloads/Metabase/test-MASTER/metabase-0.42.1.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:403544-404607)
	at <js> ed(file:/home/hansen/Downloads/Metabase/test-MASTER/metabase-0.42.1.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:403525-404611)
	at <js> a(file:/home/hansen/Downloads/Metabase/test-MASTER/metabase-0.42.1.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:212736-212749)
	at <js> n(file:/home/hansen/Downloads/Metabase/test-MASTER/metabase-0.42.1.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:213754-213759)
	at <js> n.render(file:/home/hansen/Downloads/Metabase/test-MASTER/metabase-0.42.1.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:212085-213805)
	at org.graalvm.polyglot.Value.execute(Value.java:830)
	at metabase.pulse.render.js_engine$execute_fn_name.invokeStatic(js_engine.clj:48)
	at metabase.pulse.render.js_engine$execute_fn_name.doInvoke(js_engine.clj:42)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at metabase.pulse.render.js_svg$combo_chart.invokeStatic(js_svg.clj:155)
	at metabase.pulse.render.js_svg$combo_chart.invoke(js_svg.clj:147)
	at metabase.pulse.render.body$lab_image_bundle.invokeStatic(body.clj:628)
	at metabase.pulse.render.body$lab_image_bundle.invoke(body.clj:603)
	at metabase.pulse.render.body$fn__57151$render__57140__57156$fn__57160.invoke(body.clj:658)
	at metabase.pulse.render.body$fn__57151$render__57140__57156.invoke(body.clj:656)
	at clojure.lang.AFn.applyToHelper(AFn.java:178)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
	at metabase.pulse.render$fn__57674$render_pulse_card_body__57679$fn__57683.invoke(render.clj:142)
	at metabase.pulse.render$fn__57674$render_pulse_card_body__57679.invoke(render.clj:132)
	at metabase.pulse.render$fn__57713$render_pulse_card__57718$fn__57719.invoke(render.clj:168)
	at metabase.pulse.render$fn__57713$render_pulse_card__57718.invoke(render.clj:156)
	at metabase.pulse.render$fn__57742$render_pulse_section__57747$fn__57751$fn__57754.invoke(render.clj:200)
	at metabase.pulse.render$fn__57742$render_pulse_section__57747$fn__57751.invoke(render.clj:198)
	at metabase.pulse.render$fn__57742$render_pulse_section__57747.invoke(render.clj:195)
	at metabase.email.messages$render_result_card.invokeStatic(messages.clj:411)
	at metabase.email.messages$render_result_card.invoke(messages.clj:408)
	at metabase.email.messages$render_message_body$fn__58953$fn__58954.invoke(messages.clj:459)
	at clojure.core$mapv$fn__8468.invoke(core.clj:6914)
	at clojure.core.protocols$fn__8181.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8181.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8136$G__8131__8145.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8168.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8168.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6830)
	at clojure.core$mapv.invokeStatic(core.clj:6905)
	at clojure.core$mapv.invoke(core.clj:6905)
	at metabase.email.messages$render_message_body$fn__58953.invoke(messages.clj:459)
	at metabase.email.messages$render_message_body.invokeStatic(messages.clj:458)
	at metabase.email.messages$render_message_body.invoke(messages.clj:456)
	at metabase.email.messages$render_pulse_email.invokeStatic(messages.clj:485)
	at metabase.email.messages$render_pulse_email.invoke(messages.clj:482)
	at metabase.pulse$fn__74916.invokeStatic(pulse.clj:293)
	at metabase.pulse$fn__74916.invoke(pulse.clj:282)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.pulse$results__GT_notifications$iter__74946__74950$fn__74951.invoke(pulse.clj:345)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$seq__5419.invoke(core.clj:139)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:387)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:386)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:415)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:395)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.api.pulse$fn__75910.invokeStatic(pulse.clj:211)
	at metabase.api.pulse$fn__75910.invoke(pulse.clj:197)
	at compojure.core$wrap_response$fn__32271.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__32255.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__32260.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:151)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:152)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__65343.invoke(auth.clj:14)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at compojure.core$make_context$handler__32311.invoke(core.clj:289)
	at compojure.core$make_context$fn__32315.invoke(core.clj:299)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$make_context$fn__32315.invoke(core.clj:300)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at metabase.api.routes$fn__76468$fn__76471.invoke(routes.clj:56)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__76613$fn__76614.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at compojure.core$make_context$handler__32311.invoke(core.clj:289)
	at compojure.core$make_context$fn__32315.invoke(core.clj:299)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32264.invoke(core.clj:153)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283$f__32284$respond_SINGLEQUOTE___32285.invoke(core.clj:197)
	at metabase.server.routes$fn__76601$fn__76603.invoke(routes.clj:41)
	at compojure.core$routes$fn__32283$f__32284.invoke(core.clj:198)
	at compojure.core$routes$fn__32283.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73596.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__73593.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__77079$fn__77080$fn__77081.invoke(log.clj:209)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__77079$fn__77080.invoke(log.clj:201)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__77079.invoke(log.clj:200)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__80432.invoke(browser_cookie.clj:38)
	at metabase.server.middleware.security$add_security_headers$fn__55203.invoke(security.clj:148)
	at metabase.server.middleware.json$wrap_json_body$fn__79587.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__79605.invoke(json.clj:98)
	at metabase.server.middleware.offset_paging$handle_paging$fn__55227.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__80699.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__80715.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__34377.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__45720$fn__45721.invoke(session.clj:262)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:243)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:235)
	at metabase.server.middleware.session$bind_current_user$fn__45720.invoke(session.clj:261)
	at metabase.server.middleware.session$wrap_current_user_info$fn__45707.invoke(session.clj:221)
	at metabase.server.middleware.session$wrap_session_id$fn__45693.invoke(session.clj:167)
	at metabase.server.middleware.auth$wrap_api_key$fn__65351.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__80619.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__34360.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__34385.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__80661.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__34388.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__80448.invoke(ssl.clj:38)
	at metabase.server$async_proxy_handler$fn__76852.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-02-25 18:12:52,549 DEBUG middleware.log :: POST /api/pulse/test 200 7.1 s (31 DB calls) App DB connections: 0/7 Jetty threads: 4/50 (3 idle, 0 queued) (67 total active threads) Queries in flight: 0 (0 queued); h2 DB 4 connections: 0/1 (0 threads blocked)
```

</details>

**Information about your Metabase Installation:**
Tested 0.41.6, which shows a table, and 0.41.0/1 shows an error.

**Additional context**
#5493

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by wwei-flux** [comment]
Tested with 0.42.2. Still happening.

**Comment by losrebellos** [comment]
@flamber @howonlee 

`combo-chart`/`LineAreaBarChart` with `stacking` settings as `stack` is not implemented yet for series of type `bar`.
The fallback should be without the `stacking` settings as `stack` so the bars appear next to each others:
![image](https://user-images.githubusercontent.com/348552/157076087-bc963cb4-7861-47a5-a003-bc277f584626.png)

**Comment by jamsawamsa** [comment]
@flamber what would count as a gap in data?
