### ISSUE TITLE
Metabase won't start up

### ISSUE THREAD

**Issue by sebgie** [metabase/metabase#2115]
Hey, I have been using Metabase for some time now. Unfortunately, after upgrading from 0.14.1 to 0.15.1 I run into the following issue which I can't resolve with help from your docs or Google.

Metabase starts without a problem. When I then try to visit the webpage it hangs on the initialization screen and I see `ERROR metabase.middleware :: GET /api/health 503` in the logs.

````
...@...:/opt/metabase# java -jar metabase-0.15.1.jar 
03-09 12:14:30 INFO metabase.core :: Starting Metabase in STANDALONE mode
03-09 12:14:30 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

03-09 12:14:30 INFO metabase.core :: Starting Metabase version v0.15.1 (15d1656 release-0.15.1)...
03-09 12:14:31 DEBUG metabase.driver :: Registered driver :bigquery 🚚
03-09 12:14:31 DEBUG metabase.driver :: Registered driver :druid 🚚
03-09 12:14:31 DEBUG metabase.driver :: Registered driver :h2 🚚
03-09 12:14:32 DEBUG metabase.driver :: Registered driver :mongo 🚚
03-09 12:14:32 DEBUG metabase.driver :: Registered driver :mysql 🚚
03-09 12:14:32 DEBUG metabase.driver :: Registered driver :postgres 🚚
03-09 12:14:32 DEBUG metabase.driver :: Registered driver :redshift 🚚
03-09 12:14:32 DEBUG metabase.driver :: Registered driver :sqlite 🚚
03-09 12:14:32 DEBUG metabase.driver :: Registered driver :sqlserver 🚚
03-09 12:14:32 INFO metabase.db :: Verifying Database Connection ...
03-09 12:14:33 INFO metabase.db :: Verify Database Connection ... ✅
```
all good, now visit the page
```
03-09 12:15:12 ERROR metabase.middleware :: GET /api/health 503 (3 ms)
{:status "initializing", :progress 0.4}

03-09 12:15:13 ERROR metabase.middleware :: GET /api/health 503 (449 µs)
{:status "initializing", :progress 0.4}

03-09 12:15:14 ERROR metabase.middleware :: GET /api/health 503 (346 µs)
{:status "initializing", :progress 0.4}

03-09 12:15:14 ERROR metabase.middleware :: GET /api/health 503 (310 µs)
{:status "initializing", :progress 0.4}

03-09 12:15:15 ERROR metabase.middleware :: GET /api/health 503 (313 µs)
{:status "initializing", :progress 0.4}

03-09 12:15:16 ERROR metabase.middleware :: GET /api/health 503 (530 µs)
{:status "initializing", :progress 0.4}

03-09 12:15:16 ERROR metabase.middleware :: GET /api/health 503 (423 µs)
{:status "initializing", :progress 0.4}

```

What I tried to resolve:
- use Metabase 0.14.1 again which shows a similar output
- release locks according to documentation which runs sucessfully but doesn't solve the problem

---

*  I am using the Chrome browser.
*  My computer's OS is OSX.
*  My database is H2.
*  My Metabase version is 0.15.1.
* Java Version: 1.7.0_91
* Server OS: Ubuntu 14.04

**Comment by agilliland** [comment]
Hi @sebgie , based on the information from you logs it looks most likely that somehow your database migration lock is stale and preventing the Metabase application database from fully initializing properly.

I noticed that you said you tried clearing the locks according to the documentation, which should have resolved the issue, but lets double check that.  My recommendation would be ...

1. make a quick backup of your H2 database just to be safe (if you didn't do this already)
2. try clearing the lock one or two more times and starting up Metabase as usual and see if the problem clears.  make sure you leave a reasonable amount of time for the app to startup.
3. if the app still doesn't startup properly then we should connect to H2 directly and see what's going on, which you can do by running `java -cp metabase.jar org.h2.tools.Server` which will startup an H2 admin console on port 8082 by default.  that command will try to open up a browser for you but if that doesn't work then you can do it manually.  
4. then you just need to connect to your H2 database from this screen which requires a simple file path to wherever your H2 file is located.  Here's an example for me from my laptop `jdbc:h2:file:/Users/agilliland/workspace/metabase/metabase/metabase.db`
<img width="442" alt="screen shot 2016-03-09 at 10 44 07 am" src="https://cloud.githubusercontent.com/assets/1987787/13646425/3e8669ca-e5e4-11e5-8f9d-c2054e5e4209.png">

5. lastly we'll want to click on the `DATABASECHANGELOGLOCK` table on the left and then click the `Run` tab on the top to see what's in that table.  you should end up with an output screen like this ...
<img width="701" alt="screen shot 2016-03-09 at 10 45 53 am" src="https://cloud.githubusercontent.com/assets/1987787/13646430/42e6c32a-e5e4-11e5-9f91-3ff759544174.png">

So give that a try and let me know what you find.

**Comment by tlrobinson** [comment]
Here's a one-liner (may need to modify the jar and db paths):

`java -cp metabase.jar org.h2.tools.Shell -url jdbc:h2:./metabase.db -sql "SELECT * FROM DATABASECHANGELOGLOCK"`

**Comment by camsaul** [comment]
@agilliland @tlrobinson why not use the command we added specifically for this purpose? 

```bash
java -jar metabase.jar migrate release-locks
```

**Comment by alexanderad** [comment]
Just a note here: we had exact the same problem while updating from 0.15 to 0.16 but it was solved by removing the lock.

**Comment by shijialee** [comment]
I am running into the same problem. However there is nothing in the metabase.db.h2.db file. 

At the beginning, I got this error.

```
% java -jar metabase.jar
05-10 12:42:53 INFO metabase.core :: Starting Metabase in STANDALONE mode
05-10 12:42:54 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

05-10 12:42:54 INFO metabase.core :: Starting Metabase version v0.16.1 (ba7fba0 HEAD)...
05-10 12:42:55 DEBUG metabase.driver :: Registered driver :bigquery �
05-10 12:42:56 DEBUG metabase.driver :: Registered driver :druid �
05-10 12:42:56 DEBUG metabase.driver :: Registered driver :h2 �
05-10 12:42:57 DEBUG metabase.driver :: Registered driver :mongo �
05-10 12:42:57 DEBUG metabase.driver :: Registered driver :mysql �
05-10 12:42:57 DEBUG metabase.driver :: Registered driver :postgres �
05-10 12:42:57 DEBUG metabase.driver :: Registered driver :redshift �
05-10 12:42:57 DEBUG metabase.driver :: Registered driver :sqlite �
05-10 12:42:57 DEBUG metabase.driver :: Registered driver :sqlserver �
05-10 12:42:58 INFO metabase.db :: Verifying Database Connection ...
05-10 12:42:59 INFO metabase.db :: Verify Database Connection ... ✅
Exception in thread "dirigiste-pool-controller-0" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
        at io.aleph.dirigiste.Stats$UniformLongReservoirMap.toMap(Stats.java:114)
        at io.aleph.dirigiste.Pool.updateStats(Pool.java:233)
        at io.aleph.dirigiste.Pool.startControlLoop(Pool.java:316)
        at io.aleph.dirigiste.Pool.access$500(Pool.java:8)
        at io.aleph.dirigiste.Pool$1.run(Pool.java:377)
        at java.lang.Thread.run(Thread.java:745)
liquibase.exception.DatabaseException: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by ... (...) since 5/10/16 12:04 PM
```

Then I downloaded the metabase v0.17.0. Tried again with the same error. Then I backuped the metabase.db.h2.db file. Run the following:

```
% java -jar metabase.jar migrate release-locks
Exception in thread "dirigiste-pool-controller-0" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
        at io.aleph.dirigiste.Stats$UniformLongReservoirMap.toMap(Stats.java:114)
        at io.aleph.dirigiste.Pool.updateStats(Pool.java:233)
        at io.aleph.dirigiste.Pool.startControlLoop(Pool.java:316)
        at io.aleph.dirigiste.Pool.access$500(Pool.java:8)
        at io.aleph.dirigiste.Pool$1.run(Pool.java:377)
        at java.lang.Thread.run(Thread.java:745)
Success.
```

With v0.17.0  I started metabase again and got the following:

```
% java -jar metabase.jar
05-10 13:19:20 INFO metabase.core :: Starting Metabase in STANDALONE mode
05-10 13:19:20 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

05-10 13:19:20 INFO metabase.core :: Starting Metabase version v0.17.0 (6b3ec87 release-0.17.0) ...
05-10 13:19:20 INFO metabase.core :: System timezone is 'Asia/Shanghai' ...
05-10 13:19:21 DEBUG metabase.driver :: Registered driver :bigquery �
05-10 13:19:21 DEBUG metabase.driver :: Registered driver :druid �
05-10 13:19:22 DEBUG metabase.driver :: Registered driver :h2 �
05-10 13:19:22 DEBUG metabase.driver :: Registered driver :mongo �
05-10 13:19:22 DEBUG metabase.driver :: Registered driver :mysql �
05-10 13:19:22 DEBUG metabase.driver :: Registered driver :postgres �
05-10 13:19:22 DEBUG metabase.driver :: Registered driver :redshift �
05-10 13:19:22 DEBUG metabase.driver :: Registered driver :sqlite �
05-10 13:19:22 DEBUG metabase.driver :: Registered driver :sqlserver �
05-10 13:19:24 INFO metabase.db :: Verifying Database Connection ...
05-10 13:19:25 INFO metabase.db :: Verify Database Connection ... ✅
Exception in thread "dirigiste-pool-controller-0" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
        at io.aleph.dirigiste.Stats$UniformLongReservoirMap.toMap(Stats.java:114)
        at io.aleph.dirigiste.Pool.updateStats(Pool.java:233)
        at io.aleph.dirigiste.Pool.startControlLoop(Pool.java:316)
        at io.aleph.dirigiste.Pool.access$500(Pool.java:8)
        at io.aleph.dirigiste.Pool$1.run(Pool.java:377)
        at java.lang.Thread.run(Thread.java:745)

05-10 13:20:39 ERROR metabase.middleware :: GET /api/health 503 (1 ms)
{:status "initializing", :progress 0.4}

05-10 13:20:40 ERROR metabase.middleware :: GET /api/health 503 (339 µs)
{:status "initializing", :progress 0.4}
```
Also tried

```
% java -cp metabase.jar org.h2.tools.Shell -url jdbc:h2:./metabase.db.h2.db -sql "SELECT * FROM DATABASECHANGELOGLOCK"
Error: org.h2.jdbc.JdbcSQLException: Table "DATABASECHANGELOGLOCK" not found; SQL statement:
SELECT * FROM DATABASECHANGELOGLOCK [42102-191]
```
here is the current dir

```
total 118M
-rw-r--r-- 1 dev dev  57M Apr  6 03:34 metabase.0.16.0.jar
-rw-r--r-- 1 dev dev 2.0M May 10 15:39 metabase.db.h2.db
-rw-r--r-- 1 dev dev 2.0M May 10 15:17 metabase.db.h2.db.bak
-rw-r--r-- 1 dev dev  28K May 10 15:38 metabase.db.h2.db.mv.db
-rw-r--r-- 1 dev dev 1.1K May 10 15:37 metabase.db.h2.db.trace.db
-rw-r--r-- 1 dev dev  187 Apr 15 15:57 metabase.db.trace.db
-rw-r--r-- 1 dev dev  187 Apr 15 15:57 metabase.db.trace.db.bak
-rw-r--r-- 1 dev dev  24K May 10 15:29 metabase.db.trace.db.mv.db
-rw-r--r-- 1 dev dev  173 May 10 15:29 metabase.db.trace.db.trace.db
-rw-r--r-- 1 dev dev  58M May  4 01:46 metabase.jar
```

What else can I do? 

thanks for reading.

**Comment by agilliland** [comment]
When you started up v0.17.0 how long did you wait to let the app start up?  It looks to me like the app was starting up properly.

I would just run `java -jar metabase.jar migrate release-locks` once and then start up the app normally and give it a little while before doing anything else.  At the very least if there is an issue it should eventually error out and print something to the logs for us to go off of.

**Comment by shijialee** [comment]
Thanks for your reply.  I did what you suggested and it is working now. 

In retrospect, I thought metabase started fine after I saw `Verify Database Connection` finished. Then I tried to load the metabase website and got bunch of `GET /api/health 503` 

In fact, here is the output after I waited

```
05-11 10:55:02 INFO metabase.db :: Verifying Database Connection ...
05-11 10:55:03 INFO metabase.db :: Verify Database Connection ... ✅
Exception in thread "dirigiste-pool-controller-0" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
        at io.aleph.dirigiste.Stats$UniformLongReservoirMap.toMap(Stats.java:114)
        at io.aleph.dirigiste.Pool.updateStats(Pool.java:233)
        at io.aleph.dirigiste.Pool.startControlLoop(Pool.java:316)
        at io.aleph.dirigiste.Pool.access$500(Pool.java:8)
        at io.aleph.dirigiste.Pool$1.run(Pool.java:377)
        at java.lang.Thread.run(Thread.java:745)


05-11 10:55:30 INFO metabase.db :: Database Migrations Current ... ✅
```

I think some sort of feedback from metabase would be better in this case.  such as metabase outputs something along the line `I am still doing something, please wait` before `05-11 10:55:30 INFO metabase.db :: Database Migrations Current ... ✅`

**Comment by key88sf** [comment]
This may be a dumb question, but is this also supposed to work on an ElasticBeanstalk installation that uses the Docker image? When I ssh into the EC2 instance there, I'm unable to find where the `metabase.jar` file is located. Is there a different procedure if using the docker image on AWS EB ?

**Comment by javiercr** [comment]
Hey @agilliland I have a `metabase.db.h2.db` which I guess it's corrupted (because I cannot start metabase with it) and I'm trying to follow your steps but once I connected I only see these tables:

![image](https://cloud.githubusercontent.com/assets/855995/19245020/520d3778-8f1f-11e6-9096-1aa9dde92df3.png)


Am I missing something or it's my h2 database totally lost? Thanks!

**Comment by salsakran** [comment]
@javiercr what's in the 'columns' and 'tables' tables in what you're looking at?

**Comment by javiercr** [comment]
TABLES
![image](https://cloud.githubusercontent.com/assets/855995/19322468/7ddac8c0-90b9-11e6-9556-10179cff4302.png)

COLUMNS
![image](https://cloud.githubusercontent.com/assets/855995/19322486/8ffaee5e-90b9-11e6-808d-82639a7ca7c7.png)

**Comment by salsakran** [comment]
I don't see any Metabase tables in that list. Can you check for something like "query_queryexecution"?

**Comment by camsaul** [comment]
Yeah those are all internal H2 tables. Maybe you should do something like

```sql
WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA'
```

**Comment by javiercr** [comment]
`SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA'`

Doesn't return any result :(

**Comment by alenave** [comment]
i am getting this exception, latest version of mysql

![screen shot 2017-01-30 at 8 56 50 pm](https://cloud.githubusercontent.com/assets/3691494/22428877/b027b538-e72e-11e6-9a89-9033aa17fb6f.png)

**Comment by camsaul** [comment]
@alenave [sounds like you've set `MB_DB_AUTOMIGRATE=false`](http://www.metabase.com/docs/latest/operations-guide/start.html#running-metabase-database-migrations-manually). That's the screen you'll see when if you do that and need to migrate your DB :D

**Comment by camsaul** [comment]
@alenave what version of Metabase are you using?

**Comment by alenave** [comment]
@camsaul thanks, it works

**Comment by odahcam** [comment]
My container deployment auto updated to Metabase `v0.62.0.3-beta` yesterday, I noticed after noticing today that my deployment was offline, health checks returning 503 since the morning and I've tried redeploying, restarting, switching versions, rolling back but since then my deployment won't start anymore.

I now think it was an error to use the DOckerHub tag `v0.62.x` since I never though it would pull from beta versions. Regardless not tag I use is helping with the deployment, nothing works. My problem is similar to this, upon startup the app dies around `Verifying mysql Database Connection ...` and starts responding 503 in the `/api/health` endpoint:

```
2026-06-20 17:54:47,713 INFO driver.impl :: Registered driver :starburst (parents: [:sql-jdbc]) 🚚
2026-06-20 17:54:47,714 INFO plugins.impl :: Loading driver plugin manifest at jar:file:///app/metabase.jar!/metabase/druid-jdbc/metabase-plugin.yaml
2026-06-20 17:54:47,799 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid-jdbc...
2026-06-20 17:54:47,799 INFO driver.impl :: Registered driver :druid-jdbc (parents: [:sql-jdbc]) 🚚
2026-06-20 17:54:47,800 INFO plugins.impl :: Loading driver plugin manifest at jar:file:///app/metabase.jar!/metabase/vertica/metabase-plugin.yaml
2026-06-20 17:54:47,804 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.
platform:Syslog
2026-06-20 17:54:47,805 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
2026-06-20 17:54:47,806 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver"]
2026-06-20 17:54:47,806 INFO plugins.impl :: Loading driver plugin manifest at jar:file:///app/metabase.jar!/metabase/athena/metabase-plugin.yaml
2026-06-20 17:54:47,811 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :athena...
2026-06-20 17:54:47,811 INFO driver.impl :: Registered driver :athena (parents: [:sql-jdbc]) 🚚
2026-06-20 17:54:47,813 INFO plugins.impl :: Loading driver plugin manifest at jar:file:///app/metabase.jar!/metabase/mongo/metabase-plugin.yaml
2026-06-20 17:54:47,901 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
2026-06-20 17:54:47,902 INFO driver.impl :: Registered driver :mongo  🚚
2026-06-20 17:54:47,904 INFO plugins.impl :: Loading driver plugin manifest at jar:file:///app/metabase.jar!/metabase/sparksql/metabase-plugin.yaml
2026-06-20 17:54:47,909 INFO plugins.dependencies :: Plugin 'Metabase Spark SQL Driver' depends on plugin 'Metabase Hive Like Abstract Driver'
2026-06-20 17:54:47,909 INFO plugins.dependencies :: Metabase Spark SQL Driver dependency {:plugin Metabase Hive Like Abstract Driver} satisfied? true
2026-06-20 17:54:47,910 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...

2026-06-20 17:54:47,911 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 🚚

2026-06-20 17:54:48,006 INFO core.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2026-06-20 17:54:48,014 INFO app-db.setup :: Verifying mysql Database Connection ...
2026-06-20 17:54:54,403 ERROR middleware.log :: GET /api/health 503 2ms (0 DB calls) {:metabase-user-id nil}
{:status "initializing", :progress 0.3}

2026-06-20 17:54:55,093 ERROR middleware.log :: GET /api/health 503 1ms (0 DB calls) {:metabase-user-id nil}
{:status "initializing", :progress 0.3}
```


Still I had the exception though and Metabase shut down before starting up.

**Comment by dragonsahead** [comment]
increase your container orchestrator health check time

**Comment by odahcam** [comment]
You mean the timeout or the initial delay? I've tried 400 seconds initial delay already, I've just did 400 seconds for all criteria, still it didn't startup:

```

2026-06-21 16:49:45.653 GMT-03 ﻿2026-06-21 19:49:45,652 INFO app-db.setup :: Verifying mysql Database Connection ...
2026-06-21 16:50:15.812 GMT-03 ﻿2026-06-21 19:50:15,797 ERROR core.core :: Metabase Initialization FAILED
2026-06-21 16:50:15.812 GMT-03 clojure.lang.ExceptionInfo: Unable to connect to Metabase mysql DB.
```


Metabase is deliberately shutting down.

**Comment by dragonsahead** [comment]
> You mean the timeout or the initial delay? I've tried 400 seconds initial delay already, I've just did 400 seconds for all criteria, still it didn't startup:
> 
> ```
> 
> 2026-06-21 16:49:45.653 GMT-03 ﻿2026-06-21 19:49:45,652 INFO app-db.setup :: Verifying mysql Database Connection ...
> 2026-06-21 16:50:15.812 GMT-03 ﻿2026-06-21 19:50:15,797 ERROR core.core :: Metabase Initialization FAILED
> 2026-06-21 16:50:15.812 GMT-03 clojure.lang.ExceptionInfo: Unable to connect to Metabase mysql DB.
> ```
> 
> Metabase is deliberately shutting down.

It’s simply not finding your MySQL database then

**Comment by odahcam** [comment]
It's been up with the exact same setup for 4 years, then overnight it doesn't finds the MySQL... Doesn't make much sense to me, the settings are the same from the first deployment, something is off. It is a bug, I just don't know yet if it is with the Metabase image, the cloud infrastructure or the database itself. 😖

The only evidence of a change I have is that on the 19th Metabase tried to update to a v0.62.x.x-beta3 and then -beta4 and ever since it is not working. 

I also tried a new deployment from v0.62 and it doesn't go up even with default settings, the cloud host claims Metabase had to be terminated due to "misbehaving", this usually happens when there's not enough RAM which is not the case since it is happening even with 32 GB, the SIGTERM usually is received by Metabase during the migration process or in MySQL case I found out it is received upon `Verifying mysql Database Connection ...`. Another lead I have is 100% CPU usage spikes on the deployment attempts, that might be the reason for the `SIGTERM`. So far I have nothing else.
