### ISSUE TITLE
JSON sync is failing for non-stable json tables

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#21752]
JSON sync is failing in tables with non-stable JSON fields (heterogeneous keys)

Table CSV file 
[cards_v2.csv](https://github.com/metabase/metabase/files/8514122/cards_v2.csv)

```2022-04-19 11:45:42,504 WARN sync.util :: Error syncing Fields for Table 'Table 9 'public.cards''
java.lang.ClassCastException: class java.lang.Character cannot be cast to class clojure.lang.Named (java.lang.Character is in module java.base of loader 'bootstrap'; clojure.lang.Named is in unnamed module of loader 'app')
	at clojure.core$name.invokeStatic(core.clj:1597)
	at clojure.core$name.invoke(core.clj:1591)
	at clojure.core$map$fn__5884.invoke(core.clj:2757)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.LazySeq.first(LazySeq.java:73)
	at clojure.lang.RT.first(RT.java:692)
	at clojure.core$first__5401.invokeStatic(core.clj:55)
	at clojure.string$join.invokeStatic(string.clj:180)
	at clojure.string$join.invoke(string.clj:180)
	at metabase.driver.sql_jdbc.sync.describe_table$field_types__GT_fields$iter__58731__58735$fn__58736.invoke(describe_table.clj:304)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5911.invoke(core.clj:2813)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.PersistentHashSet.create(PersistentHashSet.java:43)
	at clojure.core$hash_set.invokeStatic(core.clj:398)
	at clojure.core$hash_set.doInvoke(core.clj:391)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.driver.sql_jdbc.sync.describe_table$field_types__GT_fields.invokeStatic(describe_table.clj:311)
	at metabase.driver.sql_jdbc.sync.describe_table$field_types__GT_fields.invoke(describe_table.clj:299)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_nested_field_columns.invokeStatic(describe_table.clj:334)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_nested_field_columns.invoke(describe_table.clj:317)
	at metabase.driver.postgres$fn__59517.invokeStatic(postgres.clj:190)
	at metabase.driver.postgres$fn__59517.invoke(postgres.clj:187)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.fetch_metadata$fn__64661$nfc_metadata__64666$fn__64667.invoke(fetch_metadata.clj:33)
	at metabase.sync.fetch_metadata$fn__64661$nfc_metadata__64666.invoke(fetch_metadata.clj:28)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__64881$db_metadata__64886$fn__64887.invoke(fetch_metadata.clj:90)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__64881$db_metadata__64886.invoke(fetch_metadata.clj:84)
	at metabase.sync.sync_metadata.fields$fn__65377$sync_fields_f
[cards_v2.csv](https://github.com/metabase/metabase/files/8514117/cards_v2.csv)
or_table_BANG___65386$fn__65389$fn__65390.invoke(fields.clj:72)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
	at metabase.sync.sync_metadata.fields$fn__65377$sync_fields_for_table_BANG___65386$fn__65389.invoke(fields.clj:71)
	at metabase.sync.sync_metadata.fields$fn__65377$sync_fields_for_table_BANG___65386.invoke(fields.clj:65)
	at clojure.core$partial$fn__5857.invoke(core.clj:2628)
	at clojure.core$map$fn__5884.invoke(core.clj:2757)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5911.invoke(core.clj:2813)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1793)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.sync_metadata.fields$fn__65415$sync_fields_BANG___65420$fn__65421.invoke(fields.clj:85)
	at metabase.sync.sync_metadata.fields$fn__65415$sync_fields_BANG___65420.invoke(fields.clj:77)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$fn__41434$run_step_with_metadata__41439$fn__41443$fn__41445.doInvoke(util.clj:388)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:117)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:114)
	at metabase.sync.util$fn__41434$run_step_with_metadata__41439$fn__41443.invoke(util.clj:383)
	at metabase.sync.util$fn__41434$run_step_with_metadata__41439.invoke(util.clj:378)
	at metabase.sync.util$fn__41650$run_sync_operation__41655$fn__41656$fn__41664.invoke(util.clj:489)
	at metabase.sync.util$fn__41650$run_sync_operation__41655$fn__41656.invoke(util.clj:487)
	at metabase.sync.util$fn__41650$run_sync_operation__41655.invoke(util.clj:481)
	at metabase.sync.sync_metadata$fn__66920$sync_db_metadata_BANG___66925$fn__66926$fn__66927.invoke(sync_metadata.clj:50)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
	at metabase.driver$fn__32587.invokeStatic(driver.clj:591)
	at metabase.driver$fn__32587.invoke(driver.clj:591)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__41343.invoke(util.clj:136)
	at metabase.sync.util$with_db_logging_disabled$fn__41340.invoke(util.clj:127)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
	at metabase.sync.util$with_start_and_finish_logging$fn__41329.invoke(util.clj:112)
	at metabase.sync.util$with_sync_events$fn__41324.invoke(util.clj:86)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__41315.invoke(util.clj:65)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:179)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:176)
	at metabase.sync.sync_metadata$fn__66920$sync_db_metadata_BANG___66925$fn__66926.invoke(sync_metadata.clj:49)
	at metabase.sync.sync_metadata$fn__66920$sync_db_metadata_BANG___66925.invoke(sync_metadata.clj:46)
	at metabase.api.database$fn__75256$fn__75257.invoke(database.clj:743)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)```

**Comment by howonlee** [comment]
Content of the CSV is not valid JSON. However this does replicate, so it should probably have better behavior for this
