### ISSUE TITLE
prevent aleph exception during app startup

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#2221]
seeing this during app startup.  so far seems harmless, but we should prevent it anyways ...

```
Exception in thread "dirigiste-pool-controller-0" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at io.aleph.dirigiste.Stats$UniformLongReservoirMap.toMap(Stats.java:114)
	at io.aleph.dirigiste.Pool.updateStats(Pool.java:233)
	at io.aleph.dirigiste.Pool.startControlLoop(Pool.java:316)
	at io.aleph.dirigiste.Pool.access$500(Pool.java:8)
	at io.aleph.dirigiste.Pool$1.run(Pool.java:377)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by camsaul** [comment]
Perhaps open an issue with aleph instead? This is an issue with the library, not Metabase itself. I'm not sure what, if anything, we can do about it.

At any rate, from what I could tell this only happens on Java 1.7, and it definitely doesn't affect anything.

**Comment by agilliland** [comment]
Cool.  I'll poke around and see if there is anything more we can do, otherwise we can leave it.

**Comment by camsaul** [comment]
I looked at this the other day and wasn't sure what to do about it. It looks like the nested class `ConcurrentHashSet.KeySetView` exists in [Java 8](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html) but not [Java 7](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html) so I think that's the root issue. Luckily however everything still works OK.

**Comment by bdezonia** [comment]
I saw a post elsewhere that explained how to fix this error. Not sure if you want to follow recommendations but you might be interested.

https://gist.github.com/AlainODea/1375759b8720a3f9f094
