### ISSUE TITLE
Upgrading to v.0.43.0 leads to Assert failed: (#{:postgres :h2 :mysql} %)

### ISSUE THREAD

**Issue by muscovitebob** [metabase/metabase#22362]
**Describe the bug**

I am upgrading from v0.41.1 to v0.43.0 and getting an assert failed on startup. Upgrading to v0.42.4 does not manifest this issue (we have an enterprise subscription so I have tried both 1.x and 0.x images). I am running a copy of the https://github.com/metabase/metabase/pull/16603 helm chart, and have verified that `MB_DB_TYPE=postgres` is still set in the running container, which is what the error indicates is unset or set incorrectly.

**Logs**
```
Exception in thread "main" java.lang.AssertionError: Assert failed: (#{:postgres :h2 :mysql} %)
	at metabase.db.env$env__GT_db_type.invokeStatic(env.clj:39)
	at metabase.db.env$env__GT_db_type.invoke(env.clj:39)
	at metabase.db.env__init.load(Unknown Source)
	at metabase.db.env__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at clojure.lang.RT.classForName(RT.java:2212)
	at clojure.lang.RT.classForName(RT.java:2221)
	at clojure.lang.RT.loadClassForName(RT.java:2240)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at metabase.db.connection$loading__6737__auto____20049.invoke(connection.clj:1)
	at metabase.db.connection__init.load(Unknown Source)
	at metabase.db.connection__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at clojure.lang.RT.classForName(RT.java:2212)
	at clojure.lang.RT.classForName(RT.java:2221)
	at clojure.lang.RT.loadClassForName(RT.java:2240)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at metabase.db$loading__6737__auto____34961.invoke(db.clj:1)
	at metabase.db__init.load(Unknown Source)
	at metabase.db__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at clojure.lang.RT.classForName(RT.java:2212)
	at clojure.lang.RT.classForName(RT.java:2221)
	at clojure.lang.RT.loadClassForName(RT.java:2240)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:3894)
	at metabase.core$loading__6737__auto____82151.invoke(core.clj:1)
	at metabase.core__init.load(Unknown Source)
	at metabase.core__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at clojure.lang.RT.classForName(RT.java:2212)
	at clojure.lang.RT.classForName(RT.java:2221)
	at clojure.lang.RT.loadClassForName(RT.java:2240)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:384)
	at clojure.lang.Util.loadWithClass(Util.java:251)
	at metabase.core.<clinit>(Unknown Source)
```
**To Reproduce**

Upgrade image to v.0.43.0

**Expected behavior**

New version of Metabase should be successfully able to read the database type env var setting as before.

**Severity**

Blocks me from upgrading to the latest release.

**Additional context**

I have verified that MB_DB_TYPE is set by running `kubectl -n dev exec metabase-dev-xxxx -- env` on the running pod.

**Comment by flamber** [comment]
Hi @muscovitebob 
It's causing error on the full connection string. Are you using `MB_DB_CONNECTION_URI` or the individual `MB_DB_HOST` etc?

**Comment by muscovitebob** [comment]
Hi @flamber I actually provide both settings, I connect to a CloudSQL Postgres instance:
```
MB_JETTY_PORT=3000
MB_DB_TYPE=postgres
MB_DB_PASS=(Password with a few special characters)
MB_SITE_URL=(My instance URL)
MB_REDIRECT_ALL_REQUESTS_TO_HTTPS=true
MB_DB_HOST=(This is set to the private IP inside my project VPC)
MB_DB_USER=metabase
MB_DB_DBNAME=metabase
MB_DB_PORT=5432
MB_DB_CONNECTION_URI=(Name of my GCP project):europe-west1:(Name of my CloudSQL database instance)
```

Could it be that the CloudSQL connection setting (of the format project:region:instancename) was never accepted in the first place and Metabase is trying to use it to connect now instead of the private IP/username/password combo I also provide?

**Comment by flamber** [comment]
@muscovitebob You cannot use both. It's either or. The `MB_DB_CONNECTION_URI` is not the connection string, it's the entire connection URI: https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_db_connection_uri

**Comment by muscovitebob** [comment]
Understood, and indeed unsetting `MB_DB_CONNECTION_URI` resolves this. Looks like pre-0.43.0 the var was ignored if the other connection vars were set. Thanks much for the help.
