### ISSUE TITLE
How do I fix locked migrations when running from the Mac App?

### ISSUE THREAD

**Issue by jjmalina** [metabase/metabase#2237]
Using the Mac App on OS X 10.10.3 at some point Metabase failed to start up, it would just hang and then say that it exited. I had settings for PostgreSQL, MySQL, and Redshift.

Here are the logs I was able to find:

```
3/24/16 3:52:04.941 PM Metabase[43453]: We've been waiting 312 seconds, what's going on?
3/24/16 3:52:09.269 PM Metabase[43453]: liquibase.exception.DatabaseException: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by fe80:0:0:0:98e3:72ff:fed8:e522%awdl0 (fe80:0:0:0:98e3:72ff:fed8:e522%awdl0) since 3/24/16 2:51 PM
3/24/16 3:52:09.269 PM Metabase[43453]: at metabase.db$migrate.invokeStatic(db.clj:107)
at metabase.db$migrate.invoke(db.clj:95)
at metabase.db$setup_db.invokeStatic(db.clj:167)
at metabase.db$setup_db.doInvoke(db.clj:155)
at clojure.lang.RestFn.invoke(RestFn.java:421)
at metabase.core$init_BANG_.invokeStatic(core.clj:128)
at metabase.core$init_BANG_.invoke(core.clj:113)
at metabase.core$start_normally.invokeStatic(core.clj:209)
at metabase.core$start_normally.invoke(core.clj:203)
at metabase.core$_main.invokeStatic(core.clj:243)
at metabase.core$_main.doInvoke(core.clj:238)
at clojure.lang.RestFn.invoke(RestFn.java:397)
at clojure.lang.AFn.applyToHelper(AFn.java:152)
at clojure.lang.RestFn.applyTo(RestFn.java:132)
at metabase.core.main(Unknown Source)
3/24/16 3:52:09.270 PM Metabase[43453]: Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by fe80:0:0:0:98e3:72ff:fed8:e522%awdl0 (fe80:0:0:0:98e3:72ff:fed8:e522%awdl0) since 3/24/16 2:51 PM
at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:184)
at liquibase.Liquibase.update(Liquibase.java:196)
at liquibase.Liquibase.update(Liquibase.java:192)
at liquibase.Liquibase.update(Liquibase.java:188)
at liquibase.Liquibase.update(Liquibase.java:181)
at metabase.db$migrate$fn__5108.invoke(db.clj:112)
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:595)
at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568)
at clojure.lang.RestFn.invoke(RestFn.java:521)
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:611)
at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568)
at clojure.lang.RestFn.invoke(RestFn.java:425)
... 15 more
3/24/16 3:52:09.271 PM Metabase[43453]: ERROR metabase.core :: Metabase Initialization FAILED:  liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by fe80:0:0:0:98e3:72ff:fed8:e522%awdl0 (fe80:0:0:0:98e3:72ff:fed8:e522%awdl0) since 3/24/16 2:51 PM
3/24/16 3:52:09.273 PM Metabase[43453]: INFO metabase.core :: Metabase Shutting Down ...
3/24/16 3:52:09.273 PM Metabase[43453]: DEBUG metabase.task :: Stopping Quartz Scheduler
3/24/16 3:52:09.274 PM Metabase[43453]: INFO metabase.core :: Metabase Shutdown COMPLETE
3/24/16 3:52:10.116 PM Metabase[43453]: 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Task terminated with exit code 1 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
````

Reinstalling the app didn't solve the issue, so I've started started running the jar directly and have no issues even with the same settings.

**Comment by camsaul** [comment]
Try this command
```bash
MB_DB_FILE=~/Library/Application\ Support/Metabase/metabase.db java -jar /Applications/Metabase.app/Contents/Resources/metabase.jar migrate release-locks
```

**Comment by jjmalina** [comment]
@camsaul yep that did the trick, thanks!

**Comment by camsaul** [comment]
Closing since suggestion worked for @jjmalina .
