### ISSUE TITLE
special_type is not created and errors out when adding a DB

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#22441]
**Describe the bug**
I've been having this issue for a few versions and I really can't get where this comes from. Whenever I add the postgres sample database, I get the following errors:
app db:
<details>
```
postgres-app-db  | 2022-05-04 23:30:09.804 UTC [58] ERROR:  column "special_type" of relation "metabase_field" does not exist at character 29
postgres-app-db  | 2022-05-04 23:30:09.804 UTC [58] STATEMENT:  UPDATE "metabase_field" SET "special_type" = $1 WHERE ("name" = $2 AND "table_id" = 6)
postgres-app-db  | 2022-05-04 23:30:09.806 UTC [58] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres-app-db  | 2022-05-04 23:30:09.806 UTC [58] STATEMENT:  
```
</details>

metabase:
<details>
```
metabase         | 2022-05-04 23:30:09,807 WARN sync.util :: Error handling metabase metadata entry: set people.zip.special_type -> type/ZipCode
metabase         | java.sql.BatchUpdateException: Batch entry 0 UPDATE "metabase_field" SET "special_type" = 'type/ZipCode' WHERE ("name" = 'zip' AND "table_id" = 6) was aborted: ERROR: column "special_type" of relation "metabase_field" does not exist
metabase         |   Position: 29  Call getNextException to see other errors in the batch.
metabase         | 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
metabase         | 	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:52)
metabase         | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
metabase         | 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:559)
metabase         | 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:887)
metabase         | 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:910)
metabase         | 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1638)
metabase         | 	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2544)
metabase         | 	at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:598)
metabase         | 	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:591)
metabase         | 	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__28437.invoke(jdbc.clj:1057)
metabase         | 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
metabase         | 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
metabase         | 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
metabase         | 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
metabase         | 	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1056)
metabase         | 	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1042)
metabase         | 	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1080)
metabase         | 	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1060)
metabase         | 	at clojure.java.jdbc$execute_BANG_$execute_helper__28505.invoke(jdbc.clj:1464)
metabase         | 	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1468)
metabase         | 	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1435)
metabase         | 	at toucan.db$execute_BANG_.invokeStatic(db.clj:427)
metabase         | 	at toucan.db$execute_BANG_.doInvoke(db.clj:422)
metabase         | 	at clojure.lang.RestFn.invoke(RestFn.java:410)
metabase         | 	at toucan.db$update_BANG_.invokeStatic(db.clj:506)
metabase         | 	at toucan.db$update_BANG_.invoke(db.clj:495)
metabase         | 	at toucan.db$update_where_BANG_.invokeStatic(db.clj:535)
metabase         | 	at toucan.db$update_where_BANG_.doInvoke(db.clj:525)
metabase         | 	at clojure.lang.RestFn.invoke(RestFn.java:464)
metabase         | 	at metabase.sync.sync_metadata.metabase_metadata$fn__65677$set_property_BANG___65682$fn__65686.invoke(metabase_metadata.clj:55)
metabase         | 	at metabase.sync.sync_metadata.metabase_metadata$fn__65677$set_property_BANG___65682.invoke(metabase_metadata.clj:41)
metabase         | 	at metabase.sync.sync_metadata.metabase_metadata$fn__65707$sync_metabase_metadata_table_BANG___65712$fn__65713$fn__65724.invoke(metabase_metadata.clj:80)
metabase         | 	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
metabase         | 	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
metabase         | 	at metabase.sync.sync_metadata.metabase_metadata$fn__65707$sync_metabase_metadata_table_BANG___65712$fn__65713.invoke(metabase_metadata.clj:79)
metabase         | 	at metabase.sync.sync_metadata.metabase_metadata$fn__65707$sync_metabase_metadata_table_BANG___65712.invoke(metabase_metadata.clj:59)
metabase         | 	at metabase.sync.sync_metadata.metabase_metadata$fn__65769$sync_metabase_metadata_BANG___65774$fn__65775$fn__65776.invoke(metabase_metadata.clj:102)
metabase         | 	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
metabase         | 	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
metabase         | 	at metabase.sync.sync_metadata.metabase_metadata$fn__65769$sync_metabase_metadata_BANG___65774$fn__65775.invoke(metabase_metadata.clj:93)
metabase         | 	at metabase.sync.sync_metadata.metabase_metadata$fn__65769$sync_metabase_metadata_BANG___65774.invoke(metabase_metadata.clj:88)
metabase         | 	at clojure.lang.AFn.applyToHelper(AFn.java:154)
metabase         | 	at clojure.lang.AFn.applyTo(AFn.java:144)
metabase         | 	at clojure.core$apply.invokeStatic(core.clj:669)
metabase         | 	at clojure.core$apply.invoke(core.clj:662)
metabase         | 	at metabase.sync.util$fn__41527$run_step_with_metadata__41532$fn__41536$fn__41538.doInvoke(util.clj:388)
metabase         | 	at clojure.lang.RestFn.invoke(RestFn.java:397)
metabase         | 	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
metabase         | 	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
metabase         | 	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:117)
metabase         | 	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:114)
metabase         | 	at metabase.sync.util$fn__41527$run_step_with_metadata__41532$fn__41536.invoke(util.clj:383)
metabase         | 	at metabase.sync.util$fn__41527$run_step_with_metadata__41532.invoke(util.clj:378)
metabase         | 	at metabase.sync.util$fn__41743$run_sync_operation__41748$fn__41749$fn__41757.invoke(util.clj:489)
metabase         | 	at metabase.sync.util$fn__41743$run_sync_operation__41748$fn__41749.invoke(util.clj:487)
metabase         | 	at metabase.sync.util$fn__41743$run_sync_operation__41748.invoke(util.clj:481)
metabase         | 	at metabase.sync.sync_metadata$fn__67125$sync_db_metadata_BANG___67130$fn__67131$fn__67132.invoke(sync_metadata.clj:50)
metabase         | 	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
metabase         | 	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
metabase         | 	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
metabase         | 	at metabase.driver$fn__32601.invokeStatic(driver.clj:592)
metabase         | 	at metabase.driver$fn__32601.invoke(driver.clj:592)
metabase         | 	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
metabase         | 	at metabase.sync.util$sync_in_context$fn__41436.invoke(util.clj:136)
metabase         | 	at metabase.sync.util$with_db_logging_disabled$fn__41433.invoke(util.clj:127)
metabase         | 	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
metabase         | 	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
metabase         | 	at metabase.sync.util$with_start_and_finish_logging$fn__41422.invoke(util.clj:112)
metabase         | 	at metabase.sync.util$with_sync_events$fn__41417.invoke(util.clj:86)
metabase         | 	at metabase.sync.util$with_duplicate_ops_prevented$fn__41408.invoke(util.clj:65)
metabase         | 	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:179)
metabase         | 	at metabase.sync.util$do_sync_operation.invoke(util.clj:176)
metabase         | 	at metabase.sync.sync_metadata$fn__67125$sync_db_metadata_BANG___67130$fn__67131.invoke(sync_metadata.clj:49)
metabase         | 	at metabase.sync.sync_metadata$fn__67125$sync_db_metadata_BANG___67130.invoke(sync_metadata.clj:46)
metabase         | 	at metabase.sync$fn__67182$sync_database_BANG___67191$fn__67197$fn__67199$fn__67201.invoke(sync.clj:45)
metabase         | 	at clojure.core$mapv$fn__8468.invoke(core.clj:6914)
metabase         | 	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
metabase         | 	at clojure.core.protocols$fn__8176.invokeStatic(protocols.clj:136)
metabase         | 	at clojure.core.protocols$fn__8176.invoke(protocols.clj:124)
metabase         | 	at clojure.core.protocols$fn__8136$G__8131__8145.invoke(protocols.clj:19)
metabase         | 	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
metabase         | 	at clojure.core.protocols$fn__8168.invokeStatic(protocols.clj:75)
metabase         | 	at clojure.core.protocols$fn__8168.invoke(protocols.clj:75)
metabase         | 	at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)
metabase         | 	at clojure.core$reduce.invokeStatic(core.clj:6830)
metabase         | 	at clojure.core$mapv.invokeStatic(core.clj:6905)
metabase         | 	at clojure.core$mapv.invoke(core.clj:6905)
metabase         | 	at metabase.sync$fn__67182$sync_database_BANG___67191$fn__67197$fn__67199.invoke(sync.clj:45)
metabase         | 	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
metabase         | 	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
metabase         | 	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
metabase         | 	at metabase.driver$fn__32601.invokeStatic(driver.clj:592)
metabase         | 	at metabase.driver$fn__32601.invoke(driver.clj:592)
metabase         | 	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
metabase         | 	at metabase.sync.util$sync_in_context$fn__41436.invoke(util.clj:136)
metabase         | 	at metabase.sync.util$with_db_logging_disabled$fn__41433.invoke(util.clj:127)
metabase         | 	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
metabase         | 	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
metabase         | 	at metabase.sync.util$with_start_and_finish_logging$fn__41422.invoke(util.clj:112)
metabase         | 	at metabase.sync.util$with_sync_events$fn__41417.invoke(util.clj:86)
metabase         | 	at metabase.sync.util$with_duplicate_ops_prevented$fn__41408.invoke(util.clj:65)
metabase         | 	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:179)
metabase         | 	at metabase.sync.util$do_sync_operation.invoke(util.clj:176)
metabase         | 	at metabase.sync$fn__67182$sync_database_BANG___67191$fn__67197.invoke(sync.clj:44)
metabase         | 	at metabase.sync$fn__67182$sync_database_BANG___67191.invoke(sync.clj:30)
metabase         | 	at metabase.sync$fn__67182$sync_database_BANG___67191$fn__67192.invoke(sync.clj:40)
metabase         | 	at metabase.sync$fn__67182$sync_database_BANG___67191.invoke(sync.clj:30)
metabase         | 	at metabase.events.sync_database$process_sync_database_event$fn__85291.invoke(sync_database.clj:37)
metabase         | 	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
metabase         | 	at clojure.lang.AFn.call(AFn.java:18)
metabase         | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
metabase         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
metabase         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
metabase         | 	at java.base/java.lang.Thread.run(Unknown Source)
metabase         | Caused by: org.postgresql.util.PSQLException: ERROR: column "special_type" of relation "metabase_field" does not exist
metabase         |   Position: 29
metabase         | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
metabase         | 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
metabase         | 	... 112 more
```
</details>

**Logs**
Above

**To Reproduce**
Simply run the docker-compose file I left here: https://github.com/metabase/dev-scripts/pull/12

**Expected behavior**
No errors

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: Pop-os 22.04
- Your databases: PostgreSQL 14
- Metabase version: 1.43.0
- Metabase hosting environment: Docker
- Metabase internal database: PostgreSQL 14

**Severity**
I don't know the impact, but seems pretty weird

**Additional context**
I set up this every single time, I really don't know the impact of this but I'm worried

**Comment by flamber** [comment]
It's because you are including `_metabase_metadata`, which is outdated in
https://github.com/metabase/metabase-qa/blob/master/dbs/postgres/data/sample_data.sql.gz

Here's version without metadata:
[sample_data_without_metadata.sql.gz](https://github.com/metabase/metabase/files/8629358/sample_data_without_metadata.sql.gz)
