### ISSUE TITLE
Syncing PostgreSQL tables with JSON columns fails if tables are not in the default schema

### ISSUE THREAD

**Issue by arlampin** [metabase/metabase#22448]
**Describe the bug**
Syncing tables from PostgreSQL database that have JSONB columns and which are not in the default public schema fails. Tables themselves are visible, but none of their fields are, JSON or not. Querying them through SQL query works, but trying to browse data doesn't.

The log below was generated with an empty JDBC connection string options. When it was changed to
`options=-c%20search_path=helppy,public,pg_catalog%20`
the sync succeeds normally.

In the example below the schema is `helppy` and table is `email`.

**Logs**
```
2022-05-05 10:30:11,732 WARN sync.util :: Error syncing Fields for Table 'Table 146 'helppy.email''
org.postgresql.util.PSQLException: ERROR: relation "email" does not exist
  Position: 23
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1113)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$reducible_query$reify__28490.reduce(jdbc.clj:1357)
	at clojure.core$transduce.invokeStatic(core.clj:6885)
	at clojure.core$transduce.invokeStatic(core.clj:6881)
	at clojure.core$transduce.invoke(core.clj:6872)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_nested_field_columns.invokeStatic(describe_table.clj:344)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_nested_field_columns.invoke(describe_table.clj:328)
	at metabase.driver.postgres$fn__59116.invokeStatic(postgres.clj:191)
	at metabase.driver.postgres$fn__59116.invoke(postgres.clj:188)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.fetch_metadata$fn__64139$nfc_metadata__64144$fn__64145.invoke(fetch_metadata.clj:33)
	at metabase.sync.fetch_metadata$fn__64139$nfc_metadata__64144.invoke(fetch_metadata.clj:28)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__64359$db_metadata__64364$fn__64365.invoke(fetch_metadata.clj:90)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__64359$db_metadata__64364.invoke(fetch_metadata.clj:84)
	at metabase.sync.sync_metadata.fields$fn__64857$sync_fields_for_table_BANG___64866$fn__64869$fn__64870.invoke(fields.clj:72)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
	at metabase.sync.sync_metadata.fields$fn__64857$sync_fields_for_table_BANG___64866$fn__64869.invoke(fields.clj:71)
	at metabase.sync.sync_metadata.fields$fn__64857$sync_fields_for_table_BANG___64866.invoke(fields.clj:65)
	at clojure.core$partial$fn__5857.invoke(core.clj:2628)
	at clojure.core$map$fn__5884.invoke(core.clj:2757)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5911.invoke(core.clj:2813)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1793)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.sync_metadata.fields$fn__64895$sync_fields_BANG___64900$fn__64901.invoke(fields.clj:85)
	at metabase.sync.sync_metadata.fields$fn__64895$sync_fields_BANG___64900.invoke(fields.clj:77)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$fn__41527$run_step_with_metadata__41532$fn__41536$fn__41538.doInvoke(util.clj:388)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:117)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:114)
	at metabase.sync.util$fn__41527$run_step_with_metadata__41532$fn__41536.invoke(util.clj:383)
	at metabase.sync.util$fn__41527$run_step_with_metadata__41532.invoke(util.clj:378)
	at metabase.sync.util$fn__41743$run_sync_operation__41748$fn__41749$fn__41757.invoke(util.clj:489)
	at metabase.sync.util$fn__41743$run_sync_operation__41748$fn__41749.invoke(util.clj:487)
	at metabase.sync.util$fn__41743$run_sync_operation__41748.invoke(util.clj:481)
	at metabase.sync.sync_metadata$fn__66400$sync_db_metadata_BANG___66405$fn__66406$fn__66407.invoke(sync_metadata.clj:50)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
	at metabase.driver$fn__32601.invokeStatic(driver.clj:592)
	at metabase.driver$fn__32601.invoke(driver.clj:592)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__41436.invoke(util.clj:136)
	at metabase.sync.util$with_db_logging_disabled$fn__41433.invoke(util.clj:127)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
	at metabase.sync.util$with_start_and_finish_logging$fn__41422.invoke(util.clj:112)
	at metabase.sync.util$with_sync_events$fn__41417.invoke(util.clj:86)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__41408.invoke(util.clj:65)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:179)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:176)
	at metabase.sync.sync_metadata$fn__66400$sync_db_metadata_BANG___66405$fn__66406.invoke(sync_metadata.clj:49)
	at metabase.sync.sync_metadata$fn__66400$sync_db_metadata_BANG___66405.invoke(sync_metadata.clj:46)
	at metabase.api.database$fn__74743$fn__74744.invoke(database.clj:751)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**To Reproduce**
1. Create non-default schema in PostgreSQL database
2. Create a table with at least one JSON column
3. Try to sync database through admin UI

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.4.181-99.354.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v0.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Can be worked around in most cases

**Comment by willipsantos** [comment]
In my case, I'm having the same problem with the columns that are jsonb, I can't perform the sync, but only the ones that are in camelCase that don't work and in the previous version this is working properly.

```WARN sync.util :: Error synchronizing Fields to Table "Table 7 'public.test'"
org.postgresql.util.PSQLException: ERROR: column "usetest" does not exist
Hint: Perhaps you meant to reference the column "editions.useTest".
Position: 16```

**Comment by howonlee** [comment]
#22623 should fix this, closing now

**Comment by codenoid** [comment]
I got this error : "No fields found for table xxxx" with Metabase Cloud and MongoDB Atlas

**Comment by Chammar37** [comment]
I'm getting the same^ was this fixed?

**Comment by sneerin** [comment]
You're on version v0.52.8

not fixed :(

**Comment by aniketdubey10** [comment]
I am on version v0.53.6.

**Comment by azhiv** [comment]
Does anyone know how to workaround this? (I'm trying to connect supabase postgresql instance)
