### ISSUE TITLE
Fresh install using RedShift as DB fails

### ISSUE THREAD

**Issue by drafie** [metabase/metabase#22515]
**Describe the bug**
Unable to install Metabase for the first time using RedShift as the underlying database.   Intialization fails with this error:

liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: ERROR: type "e" does not exist | metabase

**Logs**

```
5/7/2022, 12:43:41 AM | 2022-05-07 05:43:41,674 INFO metabase.core :: Metabase Shutdown COMPLETE | metabase
-- | -- | --
5/7/2022, 12:43:41 AM | 2022-05-07 05:43:41,662 INFO metabase.server :: Shutting Down Embedded Jetty Webserver | metabase
5/7/2022, 12:43:41 AM | 2022-05-07 05:43:41,661 INFO metabase.core :: Metabase Shutting Down ... | metabase
5/7/2022, 12:43:41 AM | 2022-05-07 05:43:41,649 ERROR metabase.core :: Metabase Initialization FAILED | metabase
5/7/2022, 12:43:41 AM | liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: ERROR: type "e" does not exist | metabase
5/7/2022, 12:43:41 AM | at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:112) | metabase
5/7/2022, 12:43:41 AM | at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1913) | metabase
...
5/7/2022, 12:43:41 AM | at metabase.core.main(Unknown Source) | metabase
5/7/2022, 12:43:41 AM | Caused by: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: ERROR: type "e" does not exist | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:105) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData.getTables(JdbcDatabaseSnapshot.java:989) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.jvm.TableSnapshotGenerator.snapshotObject(TableSnapshotGenerator.java:34) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:66) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:69) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:312) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:105) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:58) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:244) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.SnapshotGeneratorFactory.getDatabaseChangeLogTable(SnapshotGeneratorFactory.java:252) | metabase
5/7/2022, 12:43:41 AM | at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:109) | metabase
5/7/2022, 12:43:41 AM | ... 32 more | metabase
5/7/2022, 12:43:41 AM | Caused by: org.postgresql.util.PSQLException: ERROR: type "e" does not exist | metabase
5/7/2022, 12:43:41 AM | at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) | metabase
5/7/2022, 12:43:41 AM | at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) | metabase
5/7/2022, 12:43:41 AM | at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355) | metabase
5/7/2022, 12:43:41 AM | at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490) | metabase
5/7/2022, 12:43:41 AM | at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408) | metabase
5/7/2022, 12:43:41 AM | at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329) | metabase
5/7/2022, 12:43:41 AM | at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315) | metabase
5/7/2022, 12:43:41 AM | at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291) | metabase
5/7/2022, 12:43:41 AM | at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:243) | metabase
5/7/2022, 12:43:41 AM | at org.postgresql.jdbc.PgDatabaseMetaData.getTables(PgDatabaseMetaData.java:1343) | metabase
5/7/2022, 12:43:41 AM | at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getTables(NewProxyDatabaseMetaData.java:2938) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$2.queryPostgres(JdbcDatabaseSnapshot.java:1136) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.JdbcDatabaseSnapshot$CachingDatabaseMetaData$2.fastFetchQuery(JdbcDatabaseSnapshot.java:1027) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.ResultSetCache$SingleResultSetExtractor.fastFetch(ResultSetCache.java:367) | metabase
5/7/2022, 12:43:41 AM | at liquibase.snapshot.ResultSetCache.get(ResultSetCache.java:72) | metabase
5/7/2022, 12:43:41 AM | ... 56 more | metabase
5/7/2022, 12:43:41 AM | 2022-05-07 05:43:41,318 WARN jdbc.PgConnection :: Unsupported Server Version: 8.0.2 | metabase
5/7/2022, 12:43:41 AM | 2022-05-07 05:43:41,286 INFO db.setup :: Setting up Liquibase... | metabase
5/7/2022, 12:43:41 AM | 2022-05-07 05:43:41,285 INFO db.setup :: Running Database Migrations... | metabase
5/7/2022, 12:43:41 AM | 2022-05-07 05:43:41,283 INFO db.setup :: Successfully verified PostgreSQL 8.0.2 application database connection. ✅ | metabase
5/7/2022, 12:43:41 AM | 2022-05-07 05:43:41,196 WARN jdbc.PgConnection :: Unsupported Server Version: 8.0.2 | metabase
5/7/2022, 12:43:41 AM | 2022-05-07 05:43:41,196 WARN jdbc.PgConnection :: Unsupported Server Version: 8.0.2 | metabase
5/7/2022, 12:43:41 AM | 2022-05-07 05:43:41,195 WARN jdbc.PgConnection :: Unsupported Server Version: 8.0.2 | metabase
5/7/2022, 12:43:40 AM | 2022-05-07 05:43:40,787 INFO db.setup :: [36mVerifying postgres Database Connection ...[0m | metabase
5/7/2022, 12:43:40 AM | 2022-05-07 05:43:40,777 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute... | metabase
5/7/2022, 12:43:40 AM | 2022-05-07 05:43:40,775 INFO driver.impl :: [34mRegistered driver :presto[0m (parents: [:presto-common]) 🚚 | metabase
5/7/2022, 12:43:40 AM | 2022-05-07 05:43:40,774 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :presto...[0m | metabase
5/7/2022, 12:43:40 AM | 2022-05-07 05:43:40,772 INFO driver.impl :: [34mRegistered driver :presto-jdbc[0m (parents: [:presto-common]) 🚚 | metabase
5/7/2022, 12:43:40 AM | 2022-05-07 05:43:40,772 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :presto-jdbc...[0m | metabase
5/7/2022, 12:43:40 AM | 2022-05-07 05:43:40,765 DEBUG plugins.initialize :: [33mDependencies satisfied; these plugins will now be loaded: ["Metabase Presto JDBC Driver" "Metabase Presto Driver"][0m | metabase
5/7/2022, 12:43:40 AM | 2022-05-07 05:43:40,764 INFO plugins.dependencies :: Metabase Presto JDBC Driver dependency {:plugin Presto Common Driver} satisfied? true | metabase
5/7/2022, 12:43:40 AM | 2022-05-07 05:43:40,763 INFO plugins.dependencies :: Metabase Presto Driver dependency {:plugin Presto Common Driver} satisfied? true | metabase
5/7/2022, 12:43:40 AM | 2022-05-07 05:43:40,762 INFO driver.impl :: [34mRegistered abstract driver :presto-common[0m 🚚 | metabase
5/7/2022, 12:43:40 AM | 2022-05-07 05:43:40,760 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :presto-common...[0m | m

...

5/7/2022, 12:43:39 AM | {"file.encoding" "UTF-8", | metabase
-- | -- | --
5/7/2022, 12:43:39 AM | "java.runtime.name" "OpenJDK Runtime Environment", | metabase
5/7/2022, 12:43:39 AM | "java.runtime.version" "11.0.15+10", | metabase
5/7/2022, 12:43:39 AM | "java.vendor" "Eclipse Adoptium", | metabase
5/7/2022, 12:43:39 AM | "java.vendor.url" "https://adoptium.net/", | metabase
5/7/2022, 12:43:39 AM | "java.version" "11.0.15", | metabase
5/7/2022, 12:43:39 AM | "java.vm.name" "OpenJDK 64-Bit Server VM", | metabase
5/7/2022, 12:43:39 AM | "java.vm.version" "11.0.15+10", | metabase
5/7/2022, 12:43:39 AM | "os.name" "Linux", | metabase
5/7/2022, 12:43:39 AM | "os.version" "4.14.275-207.503.amzn2.x86_64", | metabase
5/7/2022, 12:43:39 AM | "user.language" "en", | metabase
5/7/2022, 12:43:39 AM | "user.timezone" "GMT"} | metabase
5/7/2022, 12:43:39 AM | 2022-05-07 05:43:39,449 INFO metabase.core :: Starting Metabase version v0.43.0 (ee686fc release-x.43.x) ... | metabase
5/7/2022, 12:43:39 AM | 2022-05-07 05:43:39,324 INFO metabase.server :: Launching Embedded Jetty Webserver with config: | metabase
5/7/2022, 12:43:39 AM | {:port 3000, :host "0.0.0.0"} | metabase
5/7/2022, 12:43:39 AM | 2022-05-07 05:43:39,221 INFO metabase.core :: Starting Metabase in STANDALONE mode | metabase
5/7/2022, 12:43:39 AM | 2022-05-07 05:43:39,197 INFO metabase.core :: | metabase
5/7/2022, 12:43:39 AM | Metabase v0.43.0 (ee686fc release-x.43.x) | metabase
5/7/2022, 12:43:39 AM | Copyright © 2022 Metabase, Inc. | metabase
5/7/2022, 12:43:39 AM | Metabase Enterprise Edition extensions are NOT PRESENT.
```

**Expected behavior**
Metabase should be able to initialize properly, create the app database and the setup procedure should continue through the web interface. 

**Information about your Metabase Installation:**

Unable to get system to web screen.   If I use H2 as the underlying database, I can connect this same RedShift database as a source.  

**Severity**
Unable to install application

**Comment by flamber** [comment]
Hi @drafie 
Metabase supports H2, Postgres or MariaDB/MySQL as the application database. It does not support Redshift.
https://www.metabase.com/docs/latest/operations-guide/configuring-application-database.html
