### ISSUE TITLE
Snowflake driver does not work with Java 17 without JVM flags

### ISSUE THREAD

**Issue by dragonsahead** [metabase/metabase#22564]
**Describe the bug**
Seems there's something in Java 17 that's not compatible with our Snowflake driver. When you try to add a Snowflake DB it throws:
```
JDBC driver internal error: Fail to retrieve row count for first arrow chunk: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available.
```
Java 11 works as a charm

**Logs**
<details>

```
metabase         | 2022-05-09 20:25:44,144 INFO driver.impl :: Initializing driver :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set...
metabase         | 2022-05-09 20:25:47,318 ERROR driver.snowflake :: (type message)
metabase         | => java.lang.String
metabase         | 2022-05-09 20:25:47,318 ERROR api.database :: Cannot connect to Database
metabase         | java.lang.Exception: JDBC driver internal error: Fail to retrieve row count for first arrow chunk: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available.
metabase         | 	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:55)
metabase         | 	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:39)
metabase         | 	at clojure.lang.RestFn.invoke(RestFn.java:442)
metabase         | 	at metabase.api.database$test_database_connection.invokeStatic(database.clj:514)
metabase         | 	at metabase.api.database$test_database_connection.doInvoke(database.clj:503)
metabase         | 	at clojure.lang.RestFn.invoke(RestFn.java:425)
metabase         | 	at metabase.api.database$fn__75391$test_connection_details__75396$fn__75397.invoke(database.clj:563)
metabase         | 	at metabase.api.database$fn__75391$test_connection_details__75396.invoke(database.clj:544)
metabase         | 	at metabase.api.database$fn__75423.invokeStatic(database.clj:580)
metabase         | 	at metabase.api.database$fn__75423.invoke(database.clj:566)
metabase         | 	at compojure.core$wrap_response$fn__28029.invoke(core.clj:160)
metabase         | 	at compojure.core$wrap_route_middleware$fn__28013.invoke(core.clj:132)
metabase         | 	at compojure.core$wrap_route_info$fn__28018.invoke(core.clj:139)
metabase         | 	at compojure.core$wrap_route_matches$fn__28022.invoke(core.clj:151)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041.invoke(core.clj:200)
metabase         | 	at metabase.server.middleware.auth$enforce_authentication$fn__67394.invoke(auth.clj:14)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041.invoke(core.clj:200)
metabase         | 	at compojure.core$make_context$handler__28069.invoke(core.clj:289)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:299)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:199)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:199)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041.invoke(core.clj:200)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:199)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041.invoke(core.clj:200)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041.invoke(core.clj:200)
metabase         | 	at metabase.api.routes$fn__78726$fn__78727.invoke(routes.clj:57)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041.invoke(core.clj:200)
metabase         | 	at clojure.lang.AFn.applyToHelper(AFn.java:160)
metabase         | 	at clojure.lang.AFn.applyTo(AFn.java:144)
metabase         | 	at clojure.core$apply.invokeStatic(core.clj:667)
metabase         | 	at clojure.core$apply.invoke(core.clj:662)
metabase         | 	at metabase.server.routes$fn__78874$fn__78875.doInvoke(routes.clj:57)
metabase         | 	at clojure.lang.RestFn.invoke(RestFn.java:436)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041.invoke(core.clj:200)
metabase         | 	at compojure.core$make_context$handler__28069.invoke(core.clj:289)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:299)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$wrap_route_matches$fn__28022.invoke(core.clj:153)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$wrap_route_matches$fn__28022.invoke(core.clj:153)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$wrap_route_matches$fn__28022.invoke(core.clj:153)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:199)
metabase         | 	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
metabase         | 	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041.invoke(core.clj:200)
metabase         | 	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
metabase         | 	at compojure.core$routes$fn__28041.invoke(core.clj:200)
metabase         | 	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__75710.invoke(exceptions.clj:98)
metabase         | 	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__75707.invoke(exceptions.clj:86)
metabase         | 	at metabase.server.middleware.log$log_api_call$fn__80967$fn__80968$fn__80969.invoke(log.clj:211)
metabase         | 	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
metabase         | 	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
metabase         | 	at metabase.server.middleware.log$log_api_call$fn__80967$fn__80968.invoke(log.clj:203)
metabase         | 	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
metabase         | 	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
metabase         | 	at metabase.server.middleware.log$log_api_call$fn__80967.invoke(log.clj:202)
metabase         | 	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__86509.invoke(browser_cookie.clj:38)
metabase         | 	at metabase.server.middleware.security$add_security_headers$fn__61080.invoke(security.clj:148)
metabase         | 	at metabase.server.middleware.json$wrap_json_body$fn__83808.invoke(json.clj:63)
metabase         | 	at metabase.server.middleware.json$wrap_streamed_json_response$fn__83826.invoke(json.clj:99)
metabase         | 	at metabase.server.middleware.offset_paging$handle_paging$fn__61104.invoke(offset_paging.clj:42)
metabase         | 	at ring.middleware.keyword_params$wrap_keyword_params$fn__86776.invoke(keyword_params.clj:55)
metabase         | 	at ring.middleware.params$wrap_params$fn__86795.invoke(params.clj:77)
metabase         | 	at metabase.server.middleware.misc$maybe_set_site_url$fn__35170.invoke(misc.clj:59)
metabase         | 	at metabase.server.middleware.session$bind_current_user$fn__46635$fn__46636.invoke(session.clj:291)
metabase         | 	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:270)
metabase         | 	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:259)
metabase         | 	at metabase.server.middleware.session$bind_current_user$fn__46635.invoke(session.clj:290)
metabase         | 	at metabase.server.middleware.session$wrap_current_user_info$fn__46617.invoke(session.clj:240)
metabase         | 	at metabase.server.middleware.session$wrap_session_id$fn__46601.invoke(session.clj:173)
metabase         | 	at metabase.server.middleware.auth$wrap_api_key$fn__67402.invoke(auth.clj:27)
metabase         | 	at ring.middleware.cookies$wrap_cookies$fn__86696.invoke(cookies.clj:216)
metabase         | 	at metabase.server.middleware.misc$add_content_type$fn__35153.invoke(misc.clj:27)
metabase         | 	at metabase.server.middleware.misc$disable_streaming_buffering$fn__35178.invoke(misc.clj:76)
metabase         | 	at ring.middleware.gzip$wrap_gzip$fn__86738.invoke(gzip.clj:86)
metabase         | 	at metabase.server.middleware.misc$bind_request$fn__35181.invoke(misc.clj:93)
metabase         | 	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__86525.invoke(ssl.clj:38)
metabase         | 	at metabase.server$async_proxy_handler$fn__80739.invoke(server.clj:73)
metabase         | 	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
metabase         | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
metabase         | 	at org.eclipse.jetty.server.Server.handle(Server.java:516)
metabase         | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
metabase         | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
metabase         | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
metabase         | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
metabase         | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
metabase         | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
metabase         | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
metabase         | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
metabase         | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
metabase         | 	at java.base/java.lang.Thread.run(Unknown Source)
metabase         | Caused by: net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver internal error: Fail to retrieve row count for first arrow chunk: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available.
metabase         | 	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.setFirstChunkRowCountForArrow(SnowflakeResultSetSerializableV1.java:1066)
metabase         | 	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:550)
metabase         | 	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:467)
metabase         | 	at net.snowflake.client.core.SFResultSetFactory.getResultSet(SFResultSetFactory.java:29)
metabase         | 	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:220)
metabase         | 	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135)
metabase         | 	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:781)
metabase         | 	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:677)
metabase         | 	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:238)
metabase         | 	at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:117)
metabase         | 	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
metabase         | 	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
metabase         | 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1113)
metabase         | 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
metabase         | 	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
metabase         | 	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
metabase         | 	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
metabase         | 	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
metabase         | 	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:264)
metabase         | 	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:261)
metabase         | 	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:272)
metabase         | 	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:268)
metabase         | 	at metabase.driver.sql_jdbc$fn__88664.invokeStatic(sql_jdbc.clj:35)
metabase         | 	at metabase.driver.sql_jdbc$fn__88664.invoke(sql_jdbc.clj:33)
metabase         | 	at metabase.driver.snowflake$fn__82920.invokeStatic(snowflake.clj:299)
metabase         | 	at metabase.driver.snowflake$fn__82920.invoke(snowflake.clj:297)
metabase         | 	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
metabase         | 	at metabase.driver.util$can_connect_with_details_QMARK_$fn__32661.invoke(util.clj:51)
metabase         | 	at metabase.util$do_with_timeout$fn__6203.invoke(util.clj:353)
metabase         | 	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
metabase         | 	at clojure.lang.AFn.call(AFn.java:18)
metabase         | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
metabase         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
metabase         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
metabase         | 	... 1 more
metabase         | 2022-05-09 20:25:47,330 DEBUG middleware.log :: POST /api/database 400 3.2 s (0 DB calls) 
metabase         | {:valid false,
metabase         |  :dbname
metabase         |  "JDBC driver internal error: Fail to retrieve row count for first arrow chunk: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available.",
metabase         |  :message
metabase         |  "JDBC driver internal error: Fail to retrieve row count for first arrow chunk: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available."}
metabase         | 
```
</details>

**To Reproduce**
1. Install Java 17 or build a Metabase container with eclipse-temurin:17-jre-alpine
2. Try to connect to Snowflake (details on company 1password)

**Expected behavior**
Being able to connect

**Screenshots**
NA

**Information about your Metabase Installation:**
- Your browser and the version: Brave latest
- Your operating system: PopOS 22.04
- Your databases: Snowflake
- Metabase version: 1.43.0
- Metabase hosting environment: Docker, but modified to Java 17
- Metabase internal database: Postgres

**Severity**
None, yet

**Additional context**
Blocking #21264

**Comment by dpsutton** [comment]
Related tickets for snowflake:

**Comment by sfc-gh-jfreeberg** [comment]
Hi everyone, I'm a PM at Snowflake. Is this still an issue? The Snowflake driver [started supporting Java 17 as of v3.14.4](https://medium.com/snowflake/java-17-now-on-snowflake-pupr-57fc0a10c8ec). Let me know if I can help.

**Comment by paoliniluis** [comment]
Hey @sfc-gh-jfreeberg, Luis here from Metabase. I've been participating in https://github.com/snowflakedb/snowflake-jdbc/issues/589 and it would be really awesome if you can fix the issue with Apache Arrow that's preventing the driver to work without the JVM flags :)

**Comment by vldezda** [comment]
Hey @sfc-gh-jfreeberg, is there a way to provide the Snowflake driver without needing to add the JVM flags? 

Thank you!

**Comment by camsaul** [comment]
Resolved by https://github.com/metabase/metabase/pull/48854

Since we made the switch to Java 21, we've been telling everyone to run with JVM flags, and updated our documentation accordingly; unfortunately there seems to be no workaround forthcoming from the Snowflake folks.
