### ISSUE TITLE
Can't add public BigQuery datasets

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2273]
Attempting to add public datasets [from here](https://cloud.google.com/bigquery/public-data/) fails.

e.x. "Invalid dataset ID \"bigquery-public-data:usa_names.usa_1910_2013\". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long."

which is strange since that ID does only contain alphanumeric + underscores + dashes + colons.

```
03-29 16:32:37 DEBUG db.internal :: DB CALL: User [:id :email :date_joined :first_name :last_name :last_login :is_superuser :is_qbnewb :is_active :is_staff] (where (limit (select* ENTITY30591) 1) {:id current-user-id})
03-29 16:32:38 ERROR metabase.driver :: Failed to connect to database: clojure.lang.ExceptionInfo: Invalid dataset ID "bigquery-public-data:usa_names.usa_1910_2013". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long. {"code" 400, "errors" [{"domain" "global", "message" "Invalid dataset ID \"bigquery-public-data:usa_names.usa_1910_2013\". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long.", "reason" "invalid"}], "message" "Invalid dataset ID \"bigquery-public-data:usa_names.usa_1910_2013\". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long."}
java.lang.Exception: clojure.lang.ExceptionInfo: Invalid dataset ID "bigquery-public-data:usa_names.usa_1910_2013". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long. {"code" 400, "errors" [{"domain" "global", "message" "Invalid dataset ID \"bigquery-public-data:usa_names.usa_1910_2013\". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long.", "reason" "invalid"}], "message" "Invalid dataset ID \"bigquery-public-data:usa_names.usa_1910_2013\". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long."}
	at metabase.driver$can_connect_with_details_QMARK_.invokeStatic(driver.clj:388)
	at metabase.driver$can_connect_with_details_QMARK_.doInvoke(driver.clj:372)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.api.database$test_database_connection.invokeStatic(database.clj:34)
	at metabase.api.database$test_database_connection.invoke(database.clj:23)
	at metabase.api.database$fn__47670$fn__47673$try_connection__47674.invoke(database.clj:74)
	at metabase.api.database$fn__47670$fn__47673.invoke(database.clj:82)
	at metabase.api.common.internal$wrap_catch_api_exceptions.invokeStatic(internal.clj:219)
	at metabase.api.common.internal$wrap_catch_api_exceptions.invoke(internal.clj:216)
	at metabase.api.database$fn__47670.invokeStatic(database.clj:64)
	at metabase.api.database$fn__47670.invoke(database.clj:64)
	at compojure.core$make_route$fn__3193.invoke(core.clj:135)
	at compojure.core$wrap_route_middleware$fn__3186.invoke(core.clj:122)
	at compojure.core$wrap_route_info$fn__3190.invoke(core.clj:126)
	at compojure.core$if_route$fn__3158.invoke(core.clj:45)
	at compojure.core$if_method$fn__3148.invoke(core.clj:27)
	at compojure.core$routing$fn__3200.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__3204.invoke(core.clj:156)
	at metabase.middleware$enforce_authentication$fn__30585.invoke(middleware.clj:80)
	at compojure.core$routing$fn__3200.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at metabase.api.routes$fn__47854.invokeStatic(routes.clj:39)
	at metabase.api.routes$fn__47854.invoke(routes.clj:39)
	at compojure.core$if_context$fn__3262.invoke(core.clj:218)
	at compojure.core$routing$fn__3200.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__3204.invoke(core.clj:156)
	at compojure.core$routing$fn__3200.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at metabase.routes$fn__47912.invokeStatic(routes.clj:24)
	at metabase.routes$fn__47912.invoke(routes.clj:24)
	at compojure.core$if_context$fn__3262.invoke(core.clj:218)
	at compojure.core$routing$fn__3200.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__3204.invoke(core.clj:156)
	at metabase.middleware$log_api_call$fn__30694.invoke(middleware.clj:260)
	at metabase.middleware$add_security_headers$fn__30638.invoke(middleware.clj:197)
	at ring.middleware.json$wrap_json_body$fn__5670.invoke(json.clj:44)
	at ring.middleware.json$wrap_json_response$fn__5687.invoke(json.clj:87)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__5723.invoke(keyword_params.clj:35)
	at ring.middleware.params$wrap_params$fn__3433.invoke(params.clj:64)
	at metabase.middleware$bind_current_user$fn__30589.invoke(middleware.clj:93)
	at metabase.middleware$wrap_current_user_id$fn__30563.invoke(middleware.clj:62)
	at metabase.middleware$wrap_api_key$fn__30604.invoke(middleware.clj:104)
	at metabase.middleware$wrap_session_id$fn__30556.invoke(middleware.clj:53)
	at ring.middleware.cookies$wrap_cookies$fn__4777.invoke(cookies.clj:161)
	at ring.middleware.session$wrap_session$fn__5856.invoke(session.clj:102)
	at ring.middleware.gzip$wrap_gzip$fn__4814.invoke(gzip.clj:65)
	at clojure.lang.Var.invoke(Var.java:379)
	at ring.middleware.reload$wrap_reload$fn__1488.invoke(reload.clj:22)
	at ring.middleware.stacktrace$wrap_stacktrace_log$fn__906.invoke(stacktrace.clj:23)
	at ring.middleware.stacktrace$wrap_stacktrace_web$fn__968.invoke(stacktrace.clj:86)
	at ring.adapter.jetty$proxy_handler$fn__105.invoke(jetty.clj:24)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
03-29 16:32:38 DEBUG metabase.middleware :: POST /api/database 400 (915 ms)
{:valid false,
 :dbname
 "clojure.lang.ExceptionInfo: Invalid dataset ID \"bigquery-public-data:usa_names.usa_1910_2013\". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long. {\"code\" 400, \"errors\" [{\"domain\" \"global\", \"message\" \"Invalid dataset ID \\\"bigquery-public-data:usa_names.usa_1910_2013\\\". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long.\", \"reason\" \"invalid\"}], \"message\" \"Invalid dataset ID \\\"bigquery-public-data:usa_names.usa_1910_2013\\\". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long.\"}",
 :message
 "clojure.lang.ExceptionInfo: Invalid dataset ID \"bigquery-public-data:usa_names.usa_1910_2013\". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long. {\"code\" 400, \"errors\" [{\"domain\" \"global\", \"message\" \"Invalid dataset ID \\\"bigquery-public-data:usa_names.usa_1910_2013\\\". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long.\", \"reason\" \"invalid\"}], \"message\" \"Invalid dataset ID \\\"bigquery-public-data:usa_names.usa_1910_2013\\\". Dataset IDs must be alphanumeric (plus underscores, dashes, and colons) and must be at most 1024 characters long.\"}"}
```

**Comment by camsaul** [comment]
so there *is* a stacktrace? :confused:

**Comment by tlrobinson** [comment]
If an exception is caught in a forest, no one is there to print it, does it really make a stacktrace?

**Comment by camsaul** [comment]
Are there LOGS in the forest? :unamused:

**Comment by camsaul** [comment]
Ok. So it turns out `bigquery-public-data` is the name of the project and `hacker-news

**Comment by camsaul** [comment]
Ok. So it turns out `bigquery-public-data` is the name of the project and `hacker-news` is the dataset. So the connection details were incorrect and the BigQuery Java driver gives a misleading error message.

Unfortunately you cannot setup OAuth for someone else's BigQuery project so the advice remains the same: just press the triangle and copy the dataset over into your own project.

**Comment by tlrobinson** [comment]
Ok, the reason copying datasets to your own project isn't desirable is you have to set up billing and pay for storage costs, whereas utilizing public dataset you don't pay for storage and get 1TB/month of free queries. It would be nice if it were super easy for people to play with these datasets within Metabase.

**Comment by salsakran** [comment]
are there alternatives to oauth'ing in?

**Comment by camsaul** [comment]
I think the BigQuery driver can probably be made to work with the public datasets without adding them to your own project but it will require some non-trivial amount of work. So for right now the BigQuery driver will mostly be useful for people who are already using BigQuery or who are willing to click the "start free trial" button.

**Comment by salsakran** [comment]
How much work are we talking about? There's typically a really big difference between 0 and $0.01 in terms of conversion.

I imagine there are a lot of people who would use this instead of our demo data.

**Comment by camsaul** [comment]
I'm guessing somewhere between a few hours to half day ish to switch things around to get this to work

**Comment by vovayartsev** [comment]
Hi

Let me highlight another aspect of the same problem: despite I can add a public dataset, I still can not query it. Here are the steps to reproduce in Metabase 0.24.2.0 (MacOS app)

1. In Admin / Databases, add  *GDELT2 public dataset* - https://bigquery.cloud.google.com/dataset/gdelt-bq:gdeltv2 
2. Re-start Metabase to make it reflect the changes in the datasources
3. Navigate to Admin / Data Model page to make sure Metabase successfully extracted table names from BigQuery
4. Try creating a Question which runs an aggregate function on the dataset.

Expected: BigQuery job is performed in the cloud and I see a result

Actual: ERROR - http://take.ms/pqCaa

> gdelt-bq: The user ******@gmail.com does not have bigquery.jobs.create permission in project gdelt-bq

IMHO [this article](https://stackoverflow.com/questions/41394244/google-big-query-403-error-unable-to-query-the-data-via-api) makes a meaningful guess about the problem's root cause

PS: huge thanks from my wife (a political science teacher) for adding BigQuery support to Metabase. It makes her job easier.

**Comment by m-vdb** [comment]
I ran into this today when trying to connect to another public dataset 😫

**Comment by lukeman** [comment]
The other GCP usage case outside of public datasets where I've seen this crop up is when read access is offered from projects within an org without granting the ability to create BigQuery jobs within the target project. With the (excellent) switch to service accounts in v0.36.0+, the billing project for BigQuery connections is now nicely inferred from the service credential. The previously discussed driver changes would obviously still be required, but I could imagine a new optional configuration field where folks can provide a project that just denotes where your target data lives in cases where it differs. It's on my list of interested-in-tackling tickets when/if I ever get my Clojure legs.

**For folks who are looking for a workaround:** you might consider creating a view in your project that acts as a proxy for the target table without duplicating the data (`CREATE VIEW myProject.dataset.viewA as SELECT * FROM projectFoo.dataset.tableA`). Of course, if you're not on a fixed-rate plan you should certainly confirm that queries against a view behaves as you'd expect when it comes to bytes billed.

Given the current BigQuery driver requires a new connection for each dataset within a project, the above workaround is something I've used more than once to collect tables that are spread across multiple datasets within the same project into a consolidated `metabase` dataset that I then add as my project connection within Metabase. The alternative would be creating and maintaining a Database connection for each dataset, which introduces all of the usual cross-database limits and at a certain scale just ends up being more work to maintain with sync schedules and the like.

**Comment by souhailaS** [comment]
I run into the same problem when trying to access the public dataset using a nodejs client, where I had as options:

```
const options = {
    query: QUERY,
    useLegacySql: false,
    allowLargeResult: true,
    destinationTable: {
      projectId: projectId,
      datasetId: datasetId,
      tableId: filestableId
    }
  };
```
When i removed the  `destinationTable`  the job was created and all went good.
