### ISSUE TITLE
Sync of fields fails, when table name contains uppercase characters

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#23026]
**Describe the bug**
Sync of fields fails, when table name contains uppercase characters.
Regression since 0.43.0, perhaps caused by the JSON unfolding work.
Only tested with Postgres, unknown if this is generic or specific to Postgres.

**To Reproduce**
1. Create a table with case-sensitive name - example on Postgres:
```
CREATE TABLE "x_caseSensitive" ( id int8 NOT NULL, "colCase" varchar NULL, "colJSON" jsonb NULL );
INSERT INTO "x_caseSensitive" (id, "colCase", "colJSON") VALUES(1, 'test', '{"COL": 1, "colCase2": 2, "colJSON_case": 3}'::jsonb);
```
2. Admin > Databases > add database or sync existing database, will fail with `ERROR: relation "sampledata.x_casesensitive" does not exist`, because Metabase tries to use lowercase table name
3. Admin > Data Model > (db) - the table is there, but no columns (if the table already existed in 42, then it won't be updated anymore)
![image](https://user-images.githubusercontent.com/1447303/170865424-52cf0c57-c9b7-4104-9298-7ba328b1ffbe.png)

<details><summary>Full stacktrace</summary>

```
2022-05-29 12:11:45,273 WARN sync.util :: Error syncing Fields for Table 'Table 8,161 'sampledata.x_caseSensitive''
org.postgresql.util.PSQLException: ERROR: relation "sampledata.x_casesensitive" does not exist
  Position: 48
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1113)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$reducible_query$reify__28497.reduce(jdbc.clj:1357)
	at clojure.core$transduce.invokeStatic(core.clj:6885)
	at clojure.core$transduce.invokeStatic(core.clj:6881)
	at clojure.core$transduce.invoke(core.clj:6872)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_nested_field_columns.invokeStatic(describe_table.clj:344)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_nested_field_columns.invoke(describe_table.clj:328)
	at metabase.driver.postgres$fn__59113.invokeStatic(postgres.clj:191)
	at metabase.driver.postgres$fn__59113.invoke(postgres.clj:188)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.fetch_metadata$fn__64219$nfc_metadata__64224$fn__64225.invoke(fetch_metadata.clj:33)
	at metabase.sync.fetch_metadata$fn__64219$nfc_metadata__64224.invoke(fetch_metadata.clj:28)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__64439$db_metadata__64444$fn__64445.invoke(fetch_metadata.clj:90)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__64439$db_metadata__64444.invoke(fetch_metadata.clj:84)
	at metabase.sync.sync_metadata.fields$fn__64937$sync_fields_for_table_BANG___64946$fn__64949$fn__64950.invoke(fields.clj:72)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
	at metabase.sync.sync_metadata.fields$fn__64937$sync_fields_for_table_BANG___64946$fn__64949.invoke(fields.clj:71)
	at metabase.sync.sync_metadata.fields$fn__64937$sync_fields_for_table_BANG___64946.invoke(fields.clj:65)
	at clojure.core$partial$fn__5857.invoke(core.clj:2628)
	at clojure.core$map$fn__5884.invoke(core.clj:2757)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5911.invoke(core.clj:2813)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1793)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.sync_metadata.fields$fn__64975$sync_fields_BANG___64980$fn__64981.invoke(fields.clj:85)
	at metabase.sync.sync_metadata.fields$fn__64975$sync_fields_BANG___64980.invoke(fields.clj:77)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$fn__41544$run_step_with_metadata__41549$fn__41553$fn__41555.doInvoke(util.clj:388)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:117)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:114)
	at metabase.sync.util$fn__41544$run_step_with_metadata__41549$fn__41553.invoke(util.clj:383)
	at metabase.sync.util$fn__41544$run_step_with_metadata__41549.invoke(util.clj:378)
	at metabase.sync.util$fn__41760$run_sync_operation__41765$fn__41766$fn__41774.invoke(util.clj:489)
	at metabase.sync.util$fn__41760$run_sync_operation__41765$fn__41766.invoke(util.clj:487)
	at metabase.sync.util$fn__41760$run_sync_operation__41765.invoke(util.clj:481)
	at metabase.sync.sync_metadata$fn__66480$sync_db_metadata_BANG___66485$fn__66486$fn__66487.invoke(sync_metadata.clj:50)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
	at metabase.driver$fn__32608.invokeStatic(driver.clj:592)
	at metabase.driver$fn__32608.invoke(driver.clj:592)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__41453.invoke(util.clj:136)
	at metabase.sync.util$with_db_logging_disabled$fn__41450.invoke(util.clj:127)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
	at metabase.sync.util$with_start_and_finish_logging$fn__41439.invoke(util.clj:112)
	at metabase.sync.util$with_sync_events$fn__41434.invoke(util.clj:86)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__41425.invoke(util.clj:65)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:179)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:176)
	at metabase.sync.sync_metadata$fn__66480$sync_db_metadata_BANG___66485$fn__66486.invoke(sync_metadata.clj:49)
	at metabase.sync.sync_metadata$fn__66480$sync_db_metadata_BANG___66485.invoke(sync_metadata.clj:46)
	at metabase.api.database$fn__74832$fn__74833.invoke(database.clj:751)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

**Information about your Metabase Installation:**
Tested 0.42.4 thru 0.43.1

**Comment by howonlee** [comment]
Root cause is default behavior of jdbc reducer is to lowercase and do other transformations on identifier. This confuses the json query gen when we pull out the identifier for the query. Fix was to turn off transformations.
