### ISSUE TITLE
Possible to config or resend Email on EOF Error

### ISSUE THREAD

**Issue by FesonX** [metabase/metabase#23030]
**Describe the bug**
When invite member or reset member's password, sometimes it **hangs due to EOF**, but **no errors show on Frontend.**
The **logs show reset password url when error raises, but invite url doesn't show, and no resend button on frontend**, I have to use reset password to get links under this case.

**Logs**
Please include javascript console and server logs around the time this bug occurred. For information about how to get these, consult our [bug troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/bugs.html)

* Environment
```
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "4.19.91-21.al7.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Shanghai"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "clickhouse",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.28-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-05-02",
      "tag": "v0.43.0",
      "branch": "release-x.43.x",
      "hash": "ee686fc"
    },
    "settings": {
      "report-timezone": "Asia/Shanghai"
    }
  }
}
```

* Server log
```
# On invite member
[fcd0061a-ae9f-4e65-b5e2-07de8bbfe080] 2022-05-30T09:56:26+08:00 WARN metabase.email Failed to send email
javax.mail.AuthenticationFailedException: [EOF]
	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:947)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:858)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:762)
	at javax.mail.Service.connect(Service.java:342)
	at postal.smtp$smtp_send_STAR_.invokeStatic(smtp.clj:33)
	at postal.smtp$smtp_send_STAR_.invoke(smtp.clj:29)
	at postal.smtp$smtp_send.invokeStatic(smtp.clj:58)
	at postal.smtp$smtp_send.doInvoke(smtp.clj:39)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at postal.core$send_message.invokeStatic(core.clj:36)
	at postal.core$send_message.invoke(core.clj:29)
	at metabase.email$fn__57222$send_message_or_throw_BANG___57227$fn__57231.invoke(email.clj:97)
	at metabase.email$fn__57222$send_message_or_throw_BANG___57227.invoke(email.clj:89)
	at metabase.email$send_message_BANG_.invokeStatic(email.clj:127)
	at metabase.email$send_message_BANG_.doInvoke(email.clj:113)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at metabase.email.messages$send_new_user_email_BANG_.invokeStatic(messages.clj:131)
	at metabase.email.messages$send_new_user_email_BANG_.invoke(messages.clj:116)
	at clojure.lang.Var.invoke(Var.java:399)
	at metabase.models.user$send_welcome_email_BANG_.invokeStatic(user.clj:244)
	at metabase.models.user$send_welcome_email_BANG_.invoke(user.clj:239)
	at metabase.models.user$fn__36875$create_and_invite_user_BANG___36880$fn__36881.invoke(user.clj:278)
	at metabase.models.user$fn__36875$create_and_invite_user_BANG___36880.invoke(user.clj:273)
	at metabase.api.user$fn__77917$fn__77920.invoke(user.clj:246)
	at toucan.db$do_in_transaction$fn__28980.invoke(db.clj:147)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at toucan.db$do_in_transaction.invokeStatic(db.clj:145)
	at toucan.db$do_in_transaction.invoke(db.clj:142)
	at metabase.api.user$fn__77917.invokeStatic(user.clj:245)
	at metabase.api.user$fn__77917.invoke(user.clj:234)
	at compojure.core$wrap_response$fn__28029.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__28013.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__28018.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__28022.invoke(core.clj:151)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__66669.invoke(auth.clj:14)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041.invoke(core.clj:200)
	at compojure.core$make_context$handler__28069.invoke(core.clj:289)
	at compojure.core$make_context$fn__28073.invoke(core.clj:299)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$make_context$fn__28073.invoke(core.clj:300)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at metabase.api.routes$fn__78001$fn__78004.invoke(routes.clj:59)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__78149$fn__78150.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041.invoke(core.clj:200)
	at compojure.core$make_context$handler__28069.invoke(core.clj:289)
	at compojure.core$make_context$fn__28073.invoke(core.clj:299)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__28022.invoke(core.clj:153)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__28022.invoke(core.clj:153)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__28022.invoke(core.clj:153)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041$f__28042$respond_SINGLEQUOTE___28043.invoke(core.clj:197)
	at metabase.server.routes$fn__78137$fn__78139.invoke(routes.clj:41)
	at compojure.core$routes$fn__28041$f__28042.invoke(core.clj:198)
	at compojure.core$routes$fn__28041.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__74985.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__74982.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__78619$fn__78620$fn__78621.invoke(log.clj:211)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__78619$fn__78620.invoke(log.clj:203)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__78619.invoke(log.clj:202)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__81845.invoke(browser_cookie.clj:38)
	at metabase.server.middleware.security$add_security_headers$fn__60355.invoke(security.clj:148)
	at metabase.server.middleware.json$wrap_json_body$fn__80994.invoke(json.clj:63)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__81012.invoke(json.clj:99)
	at metabase.server.middleware.offset_paging$handle_paging$fn__60379.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__82112.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__82131.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__35170.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__46635$fn__46636.invoke(session.clj:291)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:270)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:259)
	at metabase.server.middleware.session$bind_current_user$fn__46635.invoke(session.clj:290)
	at metabase.server.middleware.session$wrap_current_user_info$fn__46617.invoke(session.clj:240)
	at metabase.server.middleware.session$wrap_session_id$fn__46601.invoke(session.clj:173)
	at metabase.server.middleware.auth$wrap_api_key$fn__66677.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__82032.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__35153.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__35178.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__82074.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__35181.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__81861.invoke(ssl.clj:38)
	at metabase.server$async_proxy_handler$fn__78391.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
# On reset password
javax.mail.AuthenticationFailedException: [EOF]
	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:947)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:858)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:762)
	at javax.mail.Service.connect(Service.java:342)
	at postal.smtp$smtp_send_STAR_.invokeStatic(smtp.clj:33)
	at postal.smtp$smtp_send_STAR_.invoke(smtp.clj:29)
	at postal.smtp$smtp_send.invokeStatic(smtp.clj:58)
	at postal.smtp$smtp_send.doInvoke(smtp.clj:39)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at postal.core$send_message.invokeStatic(core.clj:36)
	at postal.core$send_message.invoke(core.clj:29)
	at metabase.email$fn__57222$send_message_or_throw_BANG___57227$fn__57231.invoke(email.clj:97)
	at metabase.email$fn__57222$send_message_or_throw_BANG___57227.invoke(email.clj:89)
	at metabase.email$send_message_BANG_.invokeStatic(email.clj:127)
	at metabase.email$send_message_BANG_.doInvoke(email.clj:113)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at metabase.email.messages$send_password_reset_email_BANG_.invokeStatic(messages.clj:184)
	at metabase.email.messages$send_password_reset_email_BANG_.invoke(messages.clj:168)
	at metabase.api.session$forgot_password_impl$fn__77155.invoke(session.clj:207)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
1. Go to 'People'
2. Click on 'invite someone' on top, OR click 'reset password' on member's menu.
4. See server log error

**Expected behavior**
1. Show errors on frontend when invite someone or reset password.
2. Give resend button when error raise.
3. Show invite links in logs or frontend when error raise.

**Screenshots**
N/A

**Information about your Metabase Installation:**

Other info see Environment above

- Your browser and the version: Chrome/101.0.4951.64
- Your databases: MySQL, ClickHouse
- Metabase version: 0.43
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

* Annoying

**Additional context**
I had searched on StackOverflow, looks like there exists [some configuration for Java](https://stackoverflow.com/questions/53724265/javamail-authenticationfailedexception-eof-on-socket), but metabase use Clojure, I have no idea where to start.

**Comment by flamber** [comment]
We've implemented an auto-retry functionality in upcoming v44 (#21881), but it currently only handles Subscriptions.
The retry should be implemented for all emails (except test emails I guess).

**Comment by FesonX** [comment]
> I see that the error class is `javax.mail.AuthenticationFailedException` which makes me suspicious. Is this issue intermittent? Can you go to the email settings page and send a test email and see if it works for you? <img alt="image" width="451" src="https://user-images.githubusercontent.com/6377293/178988151-9d075c83-e4bf-4e9f-9939-628b72ab47bb.png">

Yes, is intermittent, often occurs after a period of time when first email is sent, though `javax.mail.AuthenticationFailedException` is raised, but it's not relevant, `EOF` is the actual cause.
