### ISSUE TITLE
metabase.query-processor.middleware.catch-exceptions won't respect Log4J2 config

### ISSUE THREAD

**Issue by ghaabor** [metabase/metabase#23994]
**Describe the bug**
We're deploying Metabase into an environment with DataDog responsible for parsing the logs. For this to work I needed to modify the default log4j2 config to use JSONLayout. Even after this, there is one log line in the logs which is reported with the same formatting as it was with the default config. Every other log message is formatted properly to JSON. I suspect that one of the dependencies of metabase reports on a log level that is not understood by log4j2 which causes it not to use the right Appender.

**Logs**
```
Jul 15, 2022 1:15:04 PM com.google.api.client.auth.oauth2.Credential handleResponse
SEVERE: unable to refresh token
com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
POST https://oauth2.googleapis.com/token
{
  "error" : "invalid_grant",
  "error_description" : "Bad Request"
}
     at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:103)
     at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:308)
     at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:324)
     at com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:547)
     at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:358)
     at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:470)
     at com.google.api.client.auth.oauth2.Credential.handleResponse(Credential.java:256)
     at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1059)
     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
     at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
     at metabase.driver.google$execute_no_auto_retry.invokeStatic(google.clj:38)
     at metabase.driver.google$execute_no_auto_retry.invoke(google.clj:33)
     at metabase.driver.google$execute.invokeStatic(google.clj:52)
     at metabase.driver.google$execute.invoke(google.clj:45)
     at metabase.driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:216)
     at metabase.driver.bigquery$execute_bigquery.invoke(bigquery.clj:203)
     at metabase.driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:205)
     at metabase.driver.bigquery$execute_bigquery.invoke(bigquery.clj:203)
     at metabase.driver.bigquery$process_native_STAR_$thunk__83210.invoke(bigquery.clj:277)
     at metabase.driver.bigquery$process_native_STAR_.invokeStatic(bigquery.clj:279)
     at metabase.driver.bigquery$process_native_STAR_.invoke(bigquery.clj:272)
     at metabase.driver.bigquery$fn__83215.invokeStatic(bigquery.clj:299)
     at metabase.driver.bigquery$fn__83215.invoke(bigquery.clj:290)
     at clojure.lang.MultiFn.invoke(MultiFn.java:244)
     at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
     at metabase.query_processor.context$executef.invoke(context.clj:48)
     at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:68)
     at metabase.query_processor.context.default$default_runf.invoke(default.clj:66)
     at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
     at metabase.query_processor.context$runf.invoke(context.clj:39)
     at metabase.query_processor.reducible$pivot.invokeStatic(reducible.clj:34)
     at metabase.query_processor.reducible$pivot.invoke(reducible.clj:31)
     at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__49677.invoke(mbql_to_native.clj:25)
     at metabase.query_processor.middleware.check_features$check_features$fn__50423.invoke(check_features.clj:42)
     at metabase.query_processor.middleware.limit$limit$fn__48013.invoke(limit.clj:37)
     at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__50806.invoke(cache.clj:204)
     at metabase.query_processor.middleware.optimize_temporal_filters$optimize_temporal_filters$fn__51870.invoke(optimize_temporal_filters.clj:204)
     at metabase.query_processor.middleware.validate_temporal_bucketing$validate_temporal_bucketing$fn__51914.invoke(validate_temporal_bucketing.clj:50)
     at metabase.query_processor.middleware.auto_parse_filter_values$auto_parse_filter_values$fn__49734.invoke(auto_parse_filter_values.clj:43)
     at metabase.query_processor.middleware.wrap_value_literals$wrap_value_literals$fn__39793.invoke(wrap_value_literals.clj:161)
     at metabase.query_processor.middleware.annotate$add_column_info$fn__44568.invoke(annotate.clj:659)
     at metabase.query_processor.middleware.permissions$check_query_permissions$fn__46310.invoke(permissions.clj:108)
     at metabase.query_processor.middleware.pre_alias_aggregations$pre_alias_aggregations$fn__51028.invoke(pre_alias_aggregations.clj:40)
     at metabase.query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__46706.invoke(cumulative_aggregations.clj:60)
     at metabase.query_processor.middleware.visualization_settings$update_viz_settings$fn__46644.invoke(visualization_settings.clj:63)
     at metabase.query_processor.middleware.escape_join_aliases$escape_join_aliases_middleware$fn__48054.invoke(escape_join_aliases.clj:64)
     at metabase.query_processor.middleware.fix_bad_references$fix_bad_references_middleware$fn__50993.invoke(fix_bad_references.clj:91)
     at metabase.query_processor.middleware.resolve_joined_fields$resolve_joined_fields$fn__47591.invoke(resolve_joined_fields.clj:111)
     at metabase.query_processor.middleware.resolve_joins$resolve_joins$fn__51640.invoke(resolve_joins.clj:178)
     at metabase.query_processor.middleware.add_implicit_joins$add_implicit_joins$fn__51182.invoke(add_implicit_joins.clj:246)
     at metabase.query_processor.middleware.large_int_id$convert_id_to_string$fn__47610.invoke(large_int_id.clj:59)
     at metabase.query_processor.middleware.format_rows$format_rows$fn__51234.invoke(format_rows.clj:74)
     at metabase.query_processor.middleware.add_default_temporal_unit$add_default_temporal_unit$fn__46978.invoke(add_default_temporal_unit.clj:23)
     at metabase.query_processor.middleware.desugar$desugar$fn__46617.invoke(desugar.clj:21)
     at metabase.query_processor.middleware.binning$update_binning_strategy$fn__39522.invoke(binning.clj:232)
     at metabase.query_processor.middleware.resolve_fields$resolve_fields$fn__45952.invoke(resolve_fields.clj:34)
     at metabase.query_processor.middleware.add_dimension_projections$add_remapping$fn__50360.invoke(add_dimension_projections.clj:487)
     at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses$fn__50654.invoke(add_implicit_clauses.clj:164)
     at metabase.query_processor.middleware.upgrade_field_literals$upgrade_field_literals$fn__47998.invoke(upgrade_field_literals.clj:117)
     at metabase.query_processor.middleware.add_source_metadata$add_source_metadata_for_source_queries$fn__47355.invoke(add_source_metadata.clj:125)
     at metabase.query_processor.middleware.reconcile_breakout_and_order_by_bucketing$reconcile_breakout_and_order_by_bucketing$fn__50905.invoke(reconcile_breakout_and_order_by_bucketing.clj:100)
     at metabase.query_processor.middleware.auto_bucket_datetimes$auto_bucket_datetimes$fn__48992.invoke(auto_bucket_datetimes.clj:147)
     at metabase.query_processor.middleware.resolve_source_table$resolve_source_tables$fn__45933.invoke(resolve_source_table.clj:45)
     at metabase.query_processor.middleware.parameters$substitute_parameters$fn__48646.invoke(parameters.clj:109)
     at metabase.query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46006.invoke(resolve_referenced.clj:79)
     at metabase.query_processor.middleware.expand_macros$expand_macros$fn__52298.invoke(expand_macros.clj:184)
     at metabase.query_processor.middleware.add_timezone_info$add_timezone_info$fn__48426.invoke(add_timezone_info.clj:15)
     at metabase.query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__51249.invoke(splice_params_in_response.clj:32)
     at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50665$fn__50670.invoke(resolve_database_and_driver.clj:35)
     at metabase.driver$do_with_driver.invokeStatic(driver.clj:60)
     at metabase.driver$do_with_driver.invoke(driver.clj:56)
     at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__50665.invoke(resolve_database_and_driver.clj:34)
     at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__46552.invoke(fetch_source_query.clj:286)
     at metabase.query_processor.middleware.store$initialize_store$fn__46743$fn__46744.invoke(store.clj:11)
     at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:42)
     at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
     at metabase.query_processor.middleware.store$initialize_store$fn__46743.invoke(store.clj:10)
     at metabase.query_processor.middleware.validate$validate_query$fn__51000.invoke(validate.clj:10)
     at metabase.query_processor.middleware.normalize_query$normalize$fn__51007.invoke(normalize_query.clj:22)
     at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__48372.invoke(add_rows_truncated.clj:35)
     at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49663.invoke(results_metadata.clj:78)
     at metabase.query_processor.reducible$async_qp$qp_STAR___43304$thunk__43305.invoke(reducible.clj:103)
     at metabase.query_processor.reducible$async_qp$qp_STAR___43304.invoke(reducible.clj:109)
     at metabase.query_processor.reducible$sync_qp$qp_STAR___43313$fn__43316.invoke(reducible.clj:135)
     at metabase.query_processor.reducible$sync_qp$qp_STAR___43313.invoke(reducible.clj:134)
     at clojure.lang.AFn.applyToHelper(AFn.java:156)
     at clojure.lang.AFn.applyTo(AFn.java:144)
     at clojure.core$apply.invokeStatic(core.clj:669)
     at clojure.core$apply.invoke(core.clj:662)
     at metabase.query_processor$process_query.invokeStatic(query_processor.clj:156)
     at metabase.query_processor$process_query.doInvoke(query_processor.clj:150)
     at clojure.lang.RestFn.invoke(RestFn.java:423)
     at clojure.lang.Var.invoke(Var.java:388)
     at metabase.db.metadata_queries$fn__64400$table_rows_sample__64409$fn__64412.invoke(metadata_queries.clj:145)
     at metabase.db.metadata_queries$fn__64400$table_rows_sample__64409.invoke(metadata_queries.clj:132)
     at metabase.sync.analyze.fingerprint$fn__64467$fingerprint_table_BANG___64472$fn__64473.invoke(fingerprint.clj:66)
     at metabase.sync.analyze.fingerprint$fn__64467$fingerprint_table_BANG___64472.invoke(fingerprint.clj:46)
     at metabase.sync.analyze.fingerprint$fn__64643$fingerprint_fields_BANG___64648$fn__64649$fn__64650.invoke(fingerprint.clj:180)
     at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
     at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
     at metabase.sync.analyze.fingerprint$fn__64643$fingerprint_fields_BANG___64648$fn__64649.invoke(fingerprint.clj:178)
     at metabase.sync.analyze.fingerprint$fn__64643$fingerprint_fields_BANG___64648.invoke(fingerprint.clj:174)
     at metabase.sync.analyze.fingerprint$fn__64678$fingerprint_fields_for_db_BANG__STAR___64687$fn__64690$fn__64691$fn__64692.invoke(fingerprint.clj:204)
     at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
     at clojure.core$reduce.invokeStatic(core.clj:6829)
     at clojure.core$reduce.invoke(core.clj:6812)
     at metabase.sync.analyze.fingerprint$fn__64678$fingerprint_fields_for_db_BANG__STAR___64687$fn__64690$fn__64691.invoke(fingerprint.clj:200)
     at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
     at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
     at metabase.sync.analyze.fingerprint$fn__64678$fingerprint_fields_for_db_BANG__STAR___64687$fn__64690.invoke(fingerprint.clj:197)
     at metabase.sync.analyze.fingerprint$fn__64678$fingerprint_fields_for_db_BANG__STAR___64687.invoke(fingerprint.clj:186)
     at metabase.sync.analyze.fingerprint$fn__64678$fingerprint_fields_for_db_BANG__STAR___64687$fn__64688.invoke(fingerprint.clj:191)
     at metabase.sync.analyze.fingerprint$fn__64678$fingerprint_fields_for_db_BANG__STAR___64687.invoke(fingerprint.clj:186)
     at metabase.sync.analyze.fingerprint$fn__64720$fingerprint_fields_for_db_BANG___64725$fn__64726.invoke(fingerprint.clj:218)
     at metabase.sync.analyze.fingerprint$fn__64720$fingerprint_fields_for_db_BANG___64725.invoke(fingerprint.clj:212)
     at metabase.sync.analyze$make_analyze_steps$fn__65033.invoke(analyze.clj:104)
     at clojure.lang.AFn.applyToHelper(AFn.java:154)
     at clojure.lang.AFn.applyTo(AFn.java:144)
     at clojure.core$apply.invokeStatic(core.clj:669)
     at clojure.core$apply.invoke(core.clj:662)
     at metabase.sync.util$fn__40643$run_step_with_metadata__40648$fn__40652$fn__40654.doInvoke(util.clj:388)
     at clojure.lang.RestFn.invoke(RestFn.java:397)
     at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
     at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
     at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:117)
     at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:114)
     at metabase.sync.util$fn__40643$run_step_with_metadata__40648$fn__40652.invoke(util.clj:383)
     at metabase.sync.util$fn__40643$run_step_with_metadata__40648.invoke(util.clj:378)
     at metabase.sync.util$fn__40859$run_sync_operation__40864$fn__40865$fn__40873.invoke(util.clj:489)
     at metabase.sync.util$fn__40859$run_sync_operation__40864$fn__40865.invoke(util.clj:487)
     at metabase.sync.util$fn__40859$run_sync_operation__40864.invoke(util.clj:481)
     at metabase.sync.analyze$fn__65045$analyze_db_BANG___65050$fn__65051$fn__65052.invoke(analyze.clj:121)
     at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
     at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
     at clojure.core$partial$fn__5859.invoke(core.clj:2634)
     at metabase.driver$fn__19212.invokeStatic(driver.clj:572)
     at metabase.driver$fn__19212.invoke(driver.clj:572)
     at clojure.lang.MultiFn.invoke(MultiFn.java:239)
     at metabase.sync.util$sync_in_context$fn__40552.invoke(util.clj:136)
     at metabase.sync.util$with_db_logging_disabled$fn__40549.invoke(util.clj:127)
     at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
     at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
     at metabase.sync.util$with_start_and_finish_logging$fn__40538.invoke(util.clj:112)
     at metabase.sync.util$with_sync_events$fn__40533.invoke(util.clj:86)
     at metabase.sync.util$with_duplicate_ops_prevented$fn__40524.invoke(util.clj:65)
     at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:179)
     at metabase.sync.util$do_sync_operation.invoke(util.clj:176)
     at metabase.sync.analyze$fn__65045$analyze_db_BANG___65050$fn__65051.invoke(analyze.clj:118)
     at metabase.sync.analyze$fn__65045$analyze_db_BANG___65050.invoke(analyze.clj:113)
     at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:70)
     at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:58)
     at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:75)
     at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
     at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
```

**To Reproduce**
The log4j2 config in use, the only difference between the default and this config is that the PatternLayout has been changed to JSONLayout:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <!-- Default config taken from the metabase repo and modified for JSON logging -->
    <!-- https://github.com/metabase/metabase/blob/master/resources/log4j2.xml -->
    <Appenders>
        <Console name="STDOUT" target="SYSTEM_OUT" follow="true">
            <JSONLayout compact="true" eventEol="true" properties="true" stacktraceAsString="true" includeTimeMillis="true"/>
        </Console>
    </Appenders>

    <Loggers>
        <Logger name="metabase" level="INFO"/>
        <Logger name="metabase-enterprise" level="INFO"/>
        <Logger name="metabase.plugins" level="DEBUG"/>
        <Logger name="metabase.server.middleware" level="DEBUG"/>
        <Logger name="metabase.query-processor.async" level="DEBUG"/>
        <Logger name="com.mchange" level="ERROR"/>
        <Logger name="org.quartz" level="INFO"/>
        <Logger name="liquibase" level="ERROR"/>

        <Root level="WARN">
            <AppenderRef ref="STDOUT"/>
        </Root>
    </Loggers>
</Configuration>
```

I saw that the log line in question is reported as severe, so I've tried adding a custom log level for `SEVERE` but it haven't solved the problem:

```xml
    <CustomLevels>
        <!-- Custom log level for some log lines reported as SEVERE severity which are not handled by -->
        <!-- log4j2 by default. Level weight set between WARN and ERROR so the Root logger catches it. -->
        <!-- https://logging.apache.org/log4j/2.x/manual/customloglevels.html -->
        <CustomLevel name="SEVERE" intLevel="250" />
    </CustomLevels>
``` 

**Expected behavior**
The above log line should be converted to a JSON log line.

**Information about your Metabase Installation:**
- Your databases: BigQuery
- Metabase version: v0.42.4
- Metabase hosting environment: Kubernetes using the official `metabase/metabase:v0.42.4` Docker image
- Metabase internal database: Postgres

**Severity**
Impairing our ability of debugging metabase issues because the unstructured log output is reported line-by-line instead of a whole.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by ghaabor** [comment]
Hey @paoliniluis, thanks for the response I gave it a try.

1. I commented out the loggers one by one.
2. I triggered a database scheme sync via the UI.

Even with the config below (all loggers disabled), I was still getting the unformatted errors during the scheme sync:
```xml
        <Loggers>
            <!-- <Logger name="metabase" level="INFO"/> -->
            <!-- <Logger name="metabase-enterprise" level="INFO"/> -->
            <!-- <Logger name="metabase.plugins" level="DEBUG"/> -->
            <!-- <Logger name="metabase.server.middleware" level="DEBUG"/> -->
            <!-- <Logger name="metabase.query-processor.async" level="DEBUG"/> -->
            <!-- <Logger name="com.mchange" level="ERROR"/> -->
            <!-- <Logger name="org.quartz" level="INFO"/> -->
            <!-- <Logger name="liquibase" level="ERROR"/> -->

            <!-- <Root level="WARN"> -->
                <!-- <AppenderRef ref="STDOUT"/> -->
            <!-- </Root> -->
        </Loggers>
```

In the meantime I've realized that the errors are coming in pairs, there is a well-formatted one (see screenshot below) and right after or before it there's the unformatted one referenced in the original post.

![image](https://user-images.githubusercontent.com/3968828/179484924-13f33660-f8c9-46b5-979b-fd19fc7faeda.png)

**Comment by paoliniluis** [comment]
This is weird, if you comment the loggers then there shouldn't be any logs at all... There's something I'm not seeing here. Can't you send the logs just by installing the datadog agent?

**Comment by ghaabor** [comment]
@paoliniluis the problem is that by default the Java logger's log messages are sent to the stdout line-by-line (e.g. each line in a hundreds-line long stacktrace will show up on datadog as a separate log event).

My guess here is that there is some dependency in metabase which doesn't use the logger provided by log4j2 and therefore the log config in that case is completely disregarded.

If I remove all the loggers, here are the messages that are still logged during the boot and the sync:
```
Warning: environ value jdk-11.0.14.1+1 for key :java-version has been overwritten with 11.0.14.1
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
 ⮦ Load driver :sql took 1.1 s
Load driver :sql-jdbc took 1.2 s
Database setup took 4.4 s
Load lazy loading driver :google took 313.1 ms
Load lazy loading driver :bigquery took 205.7 ms
Jul 21, 2022 3:21:15 PM com.google.api.client.auth.oauth2.Credential handleResponse
SEVERE: unable to refresh token
com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
POST https://oauth2.googleapis.com/token
{
  "error" : "invalid_grant",
  "error_description" : "Bad Request"
}
... (same as above)
```

**Comment by flamber** [comment]
@ghaabor Have a look at #12719 for examples.

**Comment by ghaabor** [comment]
Hi @flamber, I managed the configure the JSON logging successfully but as I've explained above even with that setup there's one log message which is coming back as a raw log. The offending log line is printed even with all the loggers completely commented out so my assumption is that one class or dependency doesn't use the provided log4j2 logger.

**Comment by paoliniluis** [comment]
Adding to this issue as I was investigating other bugs: seems like this middleware is not going to use Log4J2 config

**Comment by dpsutton** [comment]
I'm unable to recreate. As to the idea that 
> My guess here is that there is some dependency in metabase which doesn't use the logger provided by log4j2 and therefore the log config in that case is completely disregarded.

The line you are showing above comes from [Credential.java](https://github.com/googleapis/google-oauth-java-client/blob/main/google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/Credential.java#L261). It is using java.util.logging. But the java logging should all go through whatever is configured.

For instance,

```clojure
(let [logger (java.util.logging.Logger/getLogger "metabase.nocommit")]
  (.log logger java.util.logging.Level/INFO "jul logging through log4j2"))
```

```javascript
// formatted with `jq` log message
{
  "timeMillis": 1679347556796,
  "thread": "Clojure Connection repl 2",
  "level": "INFO",
  "loggerName": "metabase.nocommit",
  "message": "jul logging through log4j2",
  "endOfBatch": false,
  "loggerFqcn": "java.util.logging.Logger",
  "contextMap": {},
  "threadId": 58,
  "threadPriority": 5
}
```

I'm unable to get Metabase to have the same error with the refresh token that you are seeing, so I can't trigger the exact log you are seeing. But I'm trying the following:

#### Starting metabase with your log config

```
MB_JETTY_PORT=3006 java -Dclojure.server.repl='{:port 6000 :accept clojure.core.server/repl}' -Dlog4j2.configurationFile=log4j2.xml -jar 0.46.0-RC3.jar
```

This puts the webserver on a random port to prevent collisions, starts a socket repl, and uses your JSONLayout log config file from a few messages back. I'm starting up the 46 release candidate jar.

#### Logging from Metabase

I want to emulate the log call from `Credential.java`:

```java
import java.util.logging.Level;
import java.util.logging.Logger;
...
static final Logger LOGGER = Logger.getLogger(Credential.class.getName());

...
LOGGER.log(Level.SEVERE, "unable to refresh token", exception);
```

```clojure
❯ netcat localhost 6000
user=> (ns nocommit.logging
  (:require [metabase.plugins.classloader :as classloader])
  (:import [java.util.logging Logger Level]))
nil
nocommit.logging=> (let [klass (Class/forName "com.google.api.client.auth.oauth2.Credential" true
                                             (classloader/the-classloader))
                        logger (.get (doto (.getDeclaredField klass "LOGGER")
                                       (.setAccessible true))
                                     klass)]
  (.log logger Level/SEVERE "using their logger" (Exception. "an exception")))
nil
nocommit.logging=>
```

In the logs from the Metabase process I see:

```
{"timeMillis":1679346301303,"thread":"Clojure Connection repl 1","level":"ERROR","loggerName":"com.google.api.client.auth.oauth2.Credential","message":"using their logger","thrown":{"commonElementCount":0,"localizedMessage":"an exception","message":"an exception","name":"java.lang.Exception","extendedStackTrace":"java.lang.Exception: an exception\n\tat nocommit.logging$eval1321.invokeStatic(NO_SOURCE_FILE:9) ~[?:?]\n\tat nocommit.logging$eval1321.invoke(NO_SOURCE_FILE:4) ~[?:?]\n\tat clojure.lang.Compiler.eval(Compiler.java:7194) ~[0.46.0-RC3.jar:?]\n\tat clojure.lang.Compiler.eval(Compiler.java:7149) ~[0.46.0-RC3.jar:?]\n\tat clojure.core$eval.invokeStatic(core.clj:3215) ~[0.46.0-RC3.jar:?]\n\tat clojure.core$eval.invoke(core.clj:3211) ~[0.46.0-RC3.jar:?]\n\tat clojure.main$repl$read_eval_print__9206$fn__9209.invoke(main.clj:437) ~[0.46.0-RC3.jar:?]\n\tat clojure.main$repl$read_eval_print__9206.invoke(main.clj:437) ~[0.46.0-RC3.jar:?]\n\tat clojure.main$repl$fn__9215.invoke(main.clj:458) ~[0.46.0-RC3.jar:?]\n\tat clojure.main$repl.invokeStatic(main.clj:458) ~[0.46.0-RC3.jar:?]\n\tat clojure.core.server$repl.invokeStatic(server.clj:180) ~[0.46.0-RC3.jar:?]\n\tat clojure.core.server$repl.invoke(server.clj:180) ~[0.46.0-RC3.jar:?]\n\tat clojure.lang.AFn.applyToHelper(AFn.java:152) ~[0.46.0-RC3.jar:?]\n\tat clojure.lang.AFn.applyTo(AFn.java:144) ~[0.46.0-RC3.jar:?]\n\tat clojure.lang.Var.applyTo(Var.java:705) ~[0.46.0-RC3.jar:?]\n\tat clojure.core$apply.invokeStatic(core.clj:667) ~[0.46.0-RC3.jar:?]\n\tat clojure.core.server$accept_connection.invokeStatic(server.clj:73) ~[0.46.0-RC3.jar:?]\n\tat clojure.core.server$start_server$fn__8998$fn__8999$fn__9001.invoke(server.clj:117) ~[0.46.0-RC3.jar:?]\n\tat clojure.lang.AFn.run(AFn.java:22) ~[0.46.0-RC3.jar:?]\n\tat java.lang.Thread.run(Thread.java:833) ~[?:?]\n"},"endOfBatch":false,"loggerFqcn":"java.util.logging.Logger","contextMap":{},"threadId":20,"threadPriority":5}
```

A few things to note here:
- the log here is using the same java.util.logging that bigquery uses but the output is formatted with the JSONLayout format.
- the j.u.l. `Level/SEVERE` has been automatically translated to log4j2's error level: ("level":"ERROR" from the json payload)

So I'm not sure how to help further. If you can tell me how you've configured Bigquery such that it is always unhappy with it's refresh token I can try that.

**Comment by paoliniluis** [comment]
Hi @ghaabor can you check? otherwise I'll proceed to close the issue

**Comment by ghaabor** [comment]
Hey @paoliniluis, sorry for missing the previous ping! Unfortunately, I've left the company where I had to work on this problem, I've forwarded your response to my ex-team but I won't be able to check if the issue has been resolved or not.
