### ISSUE TITLE
IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalSchema' is not recognized.

### ISSUE THREAD

**Issue by lukas-at-harren** [metabase/metabase#24163]
**Describe the bug**

Logs are sporadically catching this specimen. It is unclear yet whether this affects users, but I think any stacktrace is a bad one on a running production installation.

**Logs**

```
 java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalSchema' is not recognized.
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(Unknown Source)
	at org.apache.poi.util.XMLHelper.trySet(XMLHelper.java:284)
	at org.apache.poi.util.XMLHelper.getDocumentBuilderFactory(XMLHelper.java:114)
	at org.apache.poi.util.XMLHelper.<clinit>(XMLHelper.java:85)
	at org.apache.poi.ooxml.util.DocumentHelper.newDocumentBuilder(DocumentHelper.java:47)
	at org.apache.poi.ooxml.util.DocumentHelper.<clinit>(DocumentHelper.java:36)
	at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.save(ContentTypeManager.java:429)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:563)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1490)
	at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:227)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:968)
	at dk.ative.docjure.spreadsheet$save_workbook_into_stream_BANG_.invokeStatic(spreadsheet.clj:106)
	at dk.ative.docjure.spreadsheet$save_workbook_into_stream_BANG_.invoke(spreadsheet.clj:101)
	at metabase.query_processor.streaming.xlsx$fn$reify__39177.finish_BANG_(xlsx.clj:514)
	at metabase.query_processor.streaming$streaming_reducedf$fn__39272.invoke(streaming.clj:128)
	at metabase.api.public$public_reducedf$fn__71313.invoke(public.clj:97)
	at metabase.query_processor.context$reducedf.invokeStatic(context.clj:77)
	at metabase.query_processor.context$reducedf.invoke(context.clj:72)
	at metabase.query_processor.context.default$default_reducef.invokeStatic(default.clj:63)
	at metabase.query_processor.context.default$default_reducef.invoke(default.clj:48)
	at metabase.query_processor.context$reducef.invokeStatic(context.clj:69)
	at metabase.query_processor.context$reducef.invoke(context.clj:62)
	at metabase.query_processor.context.default$default_runf$respond_STAR___38229.invoke(default.clj:68)
	at metabase.driver.bigquery_cloud_sdk$post_process_native.invokeStatic(bigquery_cloud_sdk.clj:260)
	at metabase.driver.bigquery_cloud_sdk$post_process_native.invoke(bigquery_cloud_sdk.clj:238)
	at metabase.driver.bigquery_cloud_sdk$process_native_STAR_$thunk__81161.invoke(bigquery_cloud_sdk.clj:277)
	at metabase.driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:287)
	at metabase.driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:271)
	at metabase.driver.bigquery_cloud_sdk$fn__81167.invokeStatic(bigquery_cloud_sdk.clj:307)
	at metabase.driver.bigquery_cloud_sdk$fn__81167.invoke(bigquery_cloud_sdk.clj:299)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:67)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:65)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)
	at metabase.query_processor.reducible$identity_qp.invoke(reducible.clj:9)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___51447.invoke(cache.clj:220)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__47230.invoke(permissions.clj:109)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__50388.invoke(mbql_to_native.clj:23)
	at metabase.query_processor$fn__52921$combined_post_process__52926$combined_post_process_STAR___52927.invoke(query_processor.clj:207)
	at metabase.query_processor$fn__52921$combined_pre_process__52922$combined_pre_process_STAR___52923.invoke(query_processor.clj:204)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51368$fn__51373.invoke(resolve_database_and_driver.clj:35)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:75)
	at metabase.driver$do_with_driver.invoke(driver.clj:71)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__51368.invoke(resolve_database_and_driver.clj:34)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47473.invoke(fetch_source_query.clj:281)
	at metabase.query_processor.middleware.store$initialize_store$fn__47661$fn__47662.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.query_processor.middleware.store$initialize_store$fn__47661.invoke(store.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__51640.invoke(normalize_query.clj:22)
	at metabase.query_processor.middleware.constraints$add_default_userland_constraints$fn__48730.invoke(constraints.clj:53)
	at metabase.query_processor.middleware.process_userland_query$process_userland_query$fn__51579.invoke(process_userland_query.clj:145)
	at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__51951.invoke(catch_exceptions.clj:168)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44200$thunk__44202.invoke(reducible.clj:100)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44200$fn__44204.invoke(reducible.clj:105)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**

Run Metabase.

**Expected behavior**

It runs without stacktraces and errors.

**Screenshots**

No screenshots. I am still trying to figure out what triggers this.

**Information about your Metabase Installation:**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.10.61",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.4"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.3.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-27",
      "tag": "v0.43.4",
      "branch": "release-x.43.x",
      "hash": "61cc28e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**

Medium. I might raise it if this is actually causes user frustration.

**Additional context**

Metabase is running its analytical queries against a BigQuery database.
Metadata is stored in a PostgreSQL instance.

**Comment by paoliniluis** [comment]
this is the first time I see this issue, and also apache poi is the library we use for building xlsx documents, can you try to see if this happens on an export?

**Comment by flamber** [comment]
This is an upstream issue, which will be fixed when https://svn.apache.org/viewvc?view=revision&revision=1899326 is part of a release and we update dependencies. Ignore it.

**Comment by lukas-at-harren** [comment]
@flamber thanks for having a look at this. Can you follow-up/close this one once it is released? I tried to check your dependencies of the current, but that is likely best done by you. I will stay subscribed to this issue for now, to be able to update as soon as possible.

**Comment by lukas-at-harren** [comment]
@flamber small bump on this one. This error comes up about 1 in every 3 days on a used cluster of Metabase instances.
