### ISSUE TITLE
connection to database on  sql server show all tables but not fields (All schemas are empty)

### ISSUE THREAD

**Issue by MauGal** [metabase/metabase#24450]
**Describe the bug**
Created connection to MS Sql server 2005 express edition, I get all tables (Names of table) but not fields (Schema is empty)

**Logs**
This log is for one table but it's repeated for all tables

[d1bbe03f-6090-41ec-9311-daa893bac76c] 2022-07-30T12:43:59+02:00 WARN metabase.sync.util Errore di sincronizzazione dei campi per Tabella "Tabella 5 "dbo.CorsiObbligatori""
java.lang.NullPointerException
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:61)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.processExecuteResults(SQLServerStatement.java:1287)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.processResponse(SQLServerPreparedStatement.java:530)
	at com.microsoft.sqlserver.jdbc.TDSCommand.close(IOBuffer.java:7488)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.discardLastExecutionResults(SQLServerStatement.java:142)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.closeInternal(SQLServerStatement.java:653)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.closeInternal(SQLServerPreparedStatement.java:328)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.close(SQLServerStatement.java:668)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getColumns(SQLServerDatabaseMetaData.java:661)
	at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getColumns(NewProxyDatabaseMetaData.java:3068)
	at metabase.driver.sql_jdbc.sync.describe_table$jdbc_fields_metadata$fn__58788.invoke(describe_table.clj:88)
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__58501.reduce(common.clj:34)
	at clojure.core$transduce.invokeStatic(core.clj:6885)
	at clojure.core.Eduction.reduce(core.clj:7684)
	at clojure.core$reduce.invokeStatic(core.clj:6829)
	at clojure.core$cat$fn__8784.invoke(core.clj:7627)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6829)
	at clojure.core$reduce.invoke(core.clj:6812)
	at metabase.driver.sql_jdbc.sync.describe_table$fields_metadata$reify__58804.reduce(describe_table.clj:130)
	at clojure.core$transduce.invokeStatic(core.clj:6885)
	at clojure.core$into.invokeStatic(core.clj:6901)
	at clojure.core$into.invoke(core.clj:6889)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_fields.invokeStatic(describe_table.clj:138)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_fields.doInvoke(describe_table.clj:135)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invokeStatic(describe_table.clj:172)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invoke(describe_table.clj:169)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table.invokeStatic(describe_table.clj:183)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table.invoke(describe_table.clj:176)
	at metabase.driver.sql_jdbc$fn__83599.invokeStatic(sql_jdbc.clj:66)
	at metabase.driver.sql_jdbc$fn__83599.invoke(sql_jdbc.clj:64)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.fetch_metadata$fn__64198$table_metadata__64203$fn__64204.invoke(fetch_metadata.clj:19)
	at metabase.sync.fetch_metadata$fn__64198$table_metadata__64203.invoke(fetch_metadata.clj:16)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__64466$db_metadata__64471$fn__64472.invoke(fetch_metadata.clj:88)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__64466$db_metadata__64471.invoke(fetch_metadata.clj:84)
	at metabase.sync.sync_metadata.fields$fn__64964$sync_fields_for_table_BANG___64973$fn__64976$fn__64977.invoke(fields.clj:72)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
	at metabase.sync.sync_metadata.fields$fn__64964$sync_fields_for_table_BANG___64973$fn__64976.invoke(fields.clj:71)
	at metabase.sync.sync_metadata.fields$fn__64964$sync_fields_for_table_BANG___64973.invoke(fields.clj:65)
	at clojure.core$partial$fn__5857.invoke(core.clj:2628)
	at clojure.core$map$fn__5884.invoke(core.clj:2757)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5911.invoke(core.clj:2813)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1793)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.sync_metadata.fields$fn__65002$sync_fields_BANG___65007$fn__65008.invoke(fields.clj:85)
	at metabase.sync.sync_metadata.fields$fn__65002$sync_fields_BANG___65007.invoke(fields.clj:77)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$fn__41554$run_step_with_metadata__41559$fn__41563$fn__41565.doInvoke(util.clj:388)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:117)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:114)
	at metabase.sync.util$fn__41554$run_step_with_metadata__41559$fn__41563.invoke(util.clj:383)
	at metabase.sync.util$fn__41554$run_step_with_metadata__41559.invoke(util.clj:378)
	at metabase.sync.util$fn__41770$run_sync_operation__41775$fn__41776$fn__41784.invoke(util.clj:489)
	at metabase.sync.util$fn__41770$run_sync_operation__41775$fn__41776.invoke(util.clj:487)
	at metabase.sync.util$fn__41770$run_sync_operation__41775.invoke(util.clj:481)
	at metabase.sync.sync_metadata$fn__66507$sync_db_metadata_BANG___66512$fn__66513$fn__66514.invoke(sync_metadata.clj:50)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
	at clojure.core$partial$fn__5859.invoke(core.clj:2634)
	at metabase.driver$fn__32609.invokeStatic(driver.clj:592)
	at metabase.driver$fn__32609.invoke(driver.clj:592)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__41463.invoke(util.clj:136)
	at metabase.sync.util$with_db_logging_disabled$fn__41460.invoke(util.clj:127)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
	at metabase.sync.util$with_start_and_finish_logging$fn__41449.invoke(util.clj:112)
	at metabase.sync.util$with_sync_events$fn__41444.invoke(util.clj:86)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__41435.invoke(util.clj:65)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:179)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:176)
	at metabase.sync.sync_metadata$fn__66507$sync_db_metadata_BANG___66512$fn__66513.invoke(sync_metadata.clj:49)
	at metabase.sync.sync_metadata$fn__66507$sync_db_metadata_BANG___66512.invoke(sync_metadata.clj:46)
	at metabase.api.database$fn__74860$fn__74861.invoke(database.clj:751)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**To Reproduce**
1. Add database
2. Insert all parameter
3. Click connect

**Expected behavior**
To see columns and original schema when I select a table

**Severity**
So I can't use metabase

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "it-IT",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Linux",
    "os.version": "5.10.104-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-07-29",
      "tag": "v0.43.4.2",
      "branch": "release-x.43.x",
      "hash": "7809f82"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by flamber** [comment]
Hi @MauGal 
SQL Server 2005 has been EOL for many years. You'll need to upgrade to a newer version of the database.
