### ISSUE TITLE
Does the official Redshift driver work with Redshift Serverless?

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [metabase/metabase#24680]
The new [Redshift Serverless](https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-whatis.html) offering is a new variant of AWS Redshift and has slightly different concepts. (No Cluster, but rather namespaces and workgroups).

Does the official driver support this? And if yes how would it need to be configured in metabase.

When I try to connect I always get a:

```
Caused by: java.sql.SQLException: The connection attempt failed.
	at com.amazon.redshift.util.RedshiftException.getSQLException(RedshiftException.java:48)
	at com.amazon.redshift.Driver.connect(Driver.java:329)
	at metabase.plugins.jdbc_proxy$proxy_driver$reify__61281.connect(jdbc_proxy.clj:33)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:264)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:261)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:272)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:268)
	at metabase.driver.sql_jdbc$fn__84985.invokeStatic(sql_jdbc.clj:35)
	at metabase.driver.sql_jdbc$fn__84985.invoke(sql_jdbc.clj:33)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__33135.invoke(util.clj:138)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at com.amazon.redshift.core.RedshiftStream.<init>(RedshiftStream.java:86)
	at com.amazon.redshift.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:111)
	at com.amazon.redshift.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:224)
	at com.amazon.redshift.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.<init>(RedshiftConnectionImpl.java:310)
	at com.amazon.redshift.Driver.makeConnection(Driver.java:492)
	at com.amazon.redshift.Driver.connect(Driver.java:305)
	... 27 more
```

**Comment by flamber** [comment]
Hi @matthias-pichler-warrify 
Yes, it should be supported with the upstream Redshift driver version 2.1.0.3 [we're using](https://github.com/metabase/metabase/blob/master/modules/drivers/redshift/deps.edn#L8). You can try with DBeaver using the same driver version.
Timeouts are usually caused by firewalls blocking, DNS, incorrect host/port or other networking issues.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
