### ISSUE TITLE
PostgreSQL using SSL fails when using PKCS-12 SSL Client Key 

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#24838]
The following environment uses a Postgres 14 but only accepts certs to authenticate (via pg_hba.conf):
Steps:

        1. install docker and docker compose (last one is included in the latest versions of docker)
        2. save this docker compose file in a folder and do "docker-compose up"

Details:

```
version: "3"
services:
  metabase-postgres:
    image: metabase/metabase:v0.43.4
    container_name: metabase-postgres
    hostname: metabase
    volumes:
      - ./metabase-data-ep:/dev/random:ro
    ports:
      - "3000:3000"
    environment:
      - "MB_DB_TYPE=postgres"
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_PORT=5432"
      - "MB_DB_USER=metabase"
      - "MB_DB_PASS=mysecretpassword"
      - "MB_DB_HOST=postgres-app-db"
      - "JAVA_OPTS=-Xms6096M -Xmx6096M"
    networks:
      - metanet1-postgres
    depends_on:
      - postgres-app-db-postgres
    links:
      - postgres-app-db-postgres

  postgres-app-db-postgres:
    image: postgres:14.2-alpine
    # image: app_db_with_certs:postgres-14.2
    container_name: postgres-app-db-postgres
    hostname: postgres-app-db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=metabase"
      - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=mysecretpassword"
    volumes:
      - ./db-data-ep:/var/lib/postgresql/data
    networks:
      - metanet1-postgres
    command: -c log_statement=all

  postgres_with_certs:
    image: paoliniluis/qa-databases:postgres-sample-14-certs
    container_name: postgres_with_certs
    ports:
      - "5433:5432"
    hostname: postgres_with_certs
    networks:
      - metanet1-postgres
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/pgconf/server.crt -c ssl_key_file=/var/lib/postgresql/pgconf/server.key -c ssl_ca_file=/var/lib/postgresql/pgconf/ca.crt -c hba_file=/var/lib/postgresql/pg_hba.conf

networks:
  metanet1-postgres:
    driver: bridge
```

3) once the stack spin up, do the following to extract the certificates from the sample-data container

```
docker cp postgres_with_certs:/var/lib/postgresql/certs/ca.crt .
docker cp postgres_with_certs:/var/lib/postgresql/certs/client.crt .
docker cp postgres_with_certs:/var/lib/postgresql/keys/client.key .
```

3) Create PKCS-8 and PKCS-12 key files

```
openssl pkcs12 -export -out client.p12 -inkey client.key -in client.crt -certfile ca.crt  -passout pass:
openssl pkcs8 -topk8 -inform PEM -outform DER -nocrypt -in client.key -out client.pk8
```

4) Now go to localhost:3000, set up Metabase and then go to admin->settings to add a new database. The data you need to use is:

1. display name: postgres_with_certs
2. host: postgres_with_certs
3. port 5432
4. database name: sample
5. username: metabase
6. password: metasample123
7. enable "use a secure connection"
8. ssl mode: require
9. SSL Client Certificate PEM (upload client.crt)
10. SSL Client Key (PKCS-8/DER or PKCS-12) (upload client.p12/client.pk8)
11. Notice that it works for the client.pk8 key file but fails for client.p12 key file with error `Could not read SSL key file`

<img width="774" alt="image" src="https://user-images.githubusercontent.com/110378427/185142587-41198b16-e670-4599-bc8d-063697fe5693.png">

<details><summary>Full stacktrace</summary>

```
2022-08-16 12:06:56 | :message "Could not read SSL key file /tmp/metabase-secret_11602979921665184534.tmp."}
-- | --
  |   | 2022-08-16 12:06:56 | :dbname "Could not read SSL key file /tmp/metabase-secret_11602979921665184534.tmp.",
  |   | 2022-08-16 12:06:56 | {:valid false,
  |   | 2022-08-16 12:06:56 | 2022-08-16 10:06:56,162 DEBUG middleware.log :: PUT /api/database/6 400 140.5 ms (3 DB calls)
  |   | 2022-08-16 12:06:56 | ... 54 more
  |   | 2022-08-16 12:06:56 | at org.postgresql.ssl.LazyKeyManager.getPrivateKey(LazyKeyManager.java:236)
  |   | 2022-08-16 12:06:56 | at java.base/javax.crypto.EncryptedPrivateKeyInfo.<init>(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.util.DerValue.wrap(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.util.DerValue.wrap(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.util.DerValue.<init>(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.util.DerValue.<init>(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.util.DerValue.init(Unknown Source)
  |   | 2022-08-16 12:06:56 | Caused by: java.io.IOException: extra data given to DerValue constructor
  |   | 2022-08-16 12:06:56 | ... 1 more
  |   | 2022-08-16 12:06:56 | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  |   | 2022-08-16 12:06:56 | at clojure.lang.AFn.call(AFn.java:18)
  |   | 2022-08-16 12:06:56 | at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
  |   | 2022-08-16 12:06:56 | at metabase.util$do_with_timeout$fn__6204.invoke(util.clj:362)
  |   | 2022-08-16 12:06:56 | at metabase.driver.util$can_connect_with_details_QMARK_$fn__32669.invoke(util.clj:51)
  |   | 2022-08-16 12:06:56 | at clojure.lang.MultiFn.invoke(MultiFn.java:234)
  |   | 2022-08-16 12:06:56 | at metabase.driver.sql_jdbc$fn__88871.invoke(sql_jdbc.clj:33)
  |   | 2022-08-16 12:06:56 | at metabase.driver.sql_jdbc$fn__88871.invokeStatic(sql_jdbc.clj:35)
  |   | 2022-08-16 12:06:56 | at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:268)
  |   | 2022-08-16 12:06:56 | at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:272)
  |   | 2022-08-16 12:06:56 | at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:261)
  |   | 2022-08-16 12:06:56 | at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:264)
  |   | 2022-08-16 12:06:56 | at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
  |   | 2022-08-16 12:06:56 | at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
  |   | 2022-08-16 12:06:56 | at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
  |   | 2022-08-16 12:06:56 | at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
  |   | 2022-08-16 12:06:56 | at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
  |   | 2022-08-16 12:06:56 | at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
  |   | 2022-08-16 12:06:56 | at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
  |   | 2022-08-16 12:06:56 | at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
  |   | 2022-08-16 12:06:56 | at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
  |   | 2022-08-16 12:06:56 | at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
  |   | 2022-08-16 12:06:56 | at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
  |   | 2022-08-16 12:06:56 | at org.postgresql.Driver.connect(Driver.java:267)
  |   | 2022-08-16 12:06:56 | at org.postgresql.Driver.makeConnection(Driver.java:468)
  |   | 2022-08-16 12:06:56 | at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
  |   | 2022-08-16 12:06:56 | at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
  |   | 2022-08-16 12:06:56 | at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
  |   | 2022-08-16 12:06:56 | at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:168)
  |   | 2022-08-16 12:06:56 | at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:571)
  |   | 2022-08-16 12:06:56 | at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:41)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.Finished$T13FinishedConsumer.consume(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.Finished$T13FinishedConsumer.onConsumeFinished(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.SSLHandshake.produce(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.produce(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.onProduceCertificate(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.CertificateMessage$T13CertificateProducer.choosePossession(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.X509Authentication.createPossession(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.X509Authentication$X509PossessionGenerator.createPossession(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.X509Authentication$X509PossessionGenerator.createClientPossession(Unknown Source)
  |   | 2022-08-16 12:06:56 | at java.base/sun.security.ssl.AbstractKeyManagerWrapper.getPrivateKey(Unknown Source)
  |   | 2022-08-16 12:06:56 | at org.postgresql.ssl.LazyKeyManager.getPrivateKey(LazyKeyManager.java:284)
  |   | 2022-08-16 12:06:56 | Caused by: org.postgresql.util.PSQLException: Could not read SSL key file /tmp/metabase-secret_11602979921665184534.tmp.
  |   | 2022-08-16 12:06:56 | at java.base/java.lang.Thread.run(Unknown Source)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.server.Server.handle(Server.java:516)
  |   | 2022-08-16 12:06:56 | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  |   | 2022-08-16 12:06:56 | at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
  |   | 2022-08-16 12:06:56 | at metabase.server$async_proxy_handler$fn__80888.invoke(server.clj:73)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__86684.invoke(ssl.clj:48)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.misc$bind_request$fn__35202.invoke(misc.clj:93)
  |   | 2022-08-16 12:06:56 | at ring.middleware.gzip$wrap_gzip$fn__86897.invoke(gzip.clj:86)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.misc$disable_streaming_buffering$fn__35199.invoke(misc.clj:76)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.misc$add_content_type$fn__35174.invoke(misc.clj:27)
  |   | 2022-08-16 12:06:56 | at ring.middleware.cookies$wrap_cookies$fn__86855.invoke(cookies.clj:216)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.auth$wrap_api_key$fn__67509.invoke(auth.clj:27)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.session$wrap_session_id$fn__46629.invoke(session.clj:173)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.session$wrap_current_user_info$fn__46645.invoke(session.clj:240)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.session$bind_current_user$fn__46663.invoke(session.clj:290)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:259)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:270)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.session$bind_current_user$fn__46663$fn__46664.invoke(session.clj:291)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.misc$maybe_set_site_url$fn__35191.invoke(misc.clj:59)
  |   | 2022-08-16 12:06:56 | at ring.middleware.params$wrap_params$fn__86954.invoke(params.clj:77)
  |   | 2022-08-16 12:06:56 | at ring.middleware.keyword_params$wrap_keyword_params$fn__86935.invoke(keyword_params.clj:55)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.offset_paging$handle_paging$fn__61118.invoke(offset_paging.clj:42)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.json$wrap_streamed_json_response$fn__83975.invoke(json.clj:99)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.json$wrap_json_body$fn__83957.invoke(json.clj:63)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.security$add_security_headers$fn__61094.invoke(security.clj:148)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__86668.invoke(browser_cookie.clj:38)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.log$log_api_call$fn__81116.invoke(log.clj:202)
  |   | 2022-08-16 12:06:56 | at toucan.db$_do_with_call_counting.invoke(db.clj:209)
  |   | 2022-08-16 12:06:56 | at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.log$log_api_call$fn__81116$fn__81117.invoke(log.clj:203)
  |   | 2022-08-16 12:06:56 | at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
  |   | 2022-08-16 12:06:56 | at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.log$log_api_call$fn__81116$fn__81117$fn__81118.invoke(log.clj:211)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.exceptions$catch_api_exceptions$fn__75825.invoke(exceptions.clj:86)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__75828.invoke(exceptions.clj:98)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048.invoke(core.clj:200)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048.invoke(core.clj:200)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:199)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:153)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:153)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:153)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:299)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$handler__28076.invoke(core.clj:289)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048.invoke(core.clj:200)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at clojure.lang.RestFn.invoke(RestFn.java:436)
  |   | 2022-08-16 12:06:56 | at metabase.server.routes$fn__79016$fn__79017.doInvoke(routes.clj:67)
  |   | 2022-08-16 12:06:56 | at clojure.core$apply.invoke(core.clj:662)
  |   | 2022-08-16 12:06:56 | at clojure.core$apply.invokeStatic(core.clj:667)
  |   | 2022-08-16 12:06:56 | at clojure.lang.AFn.applyTo(AFn.java:144)
  |   | 2022-08-16 12:06:56 | at clojure.lang.AFn.applyToHelper(AFn.java:160)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048.invoke(core.clj:200)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at metabase.api.routes$fn__78866$fn__78867.invoke(routes.clj:57)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048.invoke(core.clj:200)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048.invoke(core.clj:200)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:199)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048.invoke(core.clj:200)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:199)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:199)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:300)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$fn__28080.invoke(core.clj:299)
  |   | 2022-08-16 12:06:56 | at compojure.core$make_context$handler__28076.invoke(core.clj:289)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048.invoke(core.clj:200)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at metabase.server.middleware.auth$enforce_authentication$fn__67501.invoke(auth.clj:14)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048.invoke(core.clj:200)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:153)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049$respond_SINGLEQUOTE___28050.invoke(core.clj:197)
  |   | 2022-08-16 12:06:56 | at compojure.core$routes$fn__28048$f__28049.invoke(core.clj:198)
  |   | 2022-08-16 12:06:56 | at compojure.core$wrap_route_matches$fn__28029.invoke(core.clj:151)
  |   | 2022-08-16 12:06:56 | at compojure.core$wrap_route_info$fn__28025.invoke(core.clj:139)
  |   | 2022-08-16 12:06:56 | at compojure.core$wrap_route_middleware$fn__28020.invoke(core.clj:132)
  |   | 2022-08-16 12:06:56 | at compojure.core$wrap_response$fn__28036.invoke(core.clj:160)
  |   | 2022-08-16 12:06:56 | at metabase.api.database$fn__75576.invoke(database.clj:648)
  |   | 2022-08-16 12:06:56 | at metabase.api.database$fn__75576.invokeStatic(database.clj:668)
  |   | 2022-08-16 12:06:56 | at clojure.lang.RestFn.invoke(RestFn.java:425)
  |   | 2022-08-16 12:06:56 | at metabase.api.database$test_database_connection.doInvoke(database.clj:503)
  |   | 2022-08-16 12:06:56 | at metabase.api.database$test_database_connection.invokeStatic(database.clj:514)
  |   | 2022-08-16 12:06:56 | at clojure.lang.RestFn.invoke(RestFn.java:442)
  |   | 2022-08-16 12:06:56 | at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:39)
  |   | 2022-08-16 12:06:56 | at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:55)
  |   | 2022-08-16 12:06:56 | java.lang.Exception: Could not read SSL key file /tmp/metabase-secret_11602979921665184534.tmp. 
```

</details>

**Comment by noahmoss** [comment]
Just to recap the current state of this issue: #25299 fixes the issue behind the error message `Could not read SSL key file`, but the repro steps now result in a new error message, `Could not read SSL key file`.

This seems to be because the repro steps don't create a PKCS-12 certificate that can actually be used to connect to Postgres, independent of Metabase (e.g. via `psql`). I think if we figure out how to connect to Postgres via PKCS-12 in general it will also work from Metabase (but this is out of the scope of my current knowledge).

**Comment by ranquild** [comment]
The underlying JDBC driver doesn't support PEM SSL client keys. We added docs about how to convert a PEM key to `PKCS-8/DER` format here https://www.metabase.com/docs/latest/databases/connections/postgresql#authenticate-client-certificate.
