### ISSUE TITLE
Exception in thread "main" java.lang.Error: Circular loading of installed providers detected

### ISSUE THREAD

**Issue by markuslf** [metabase/metabase#24836]
**Describe the bug**
After upgrading to v0.44.1, I get `Exception in thread "main" java.lang.Error: Circular loading of installed providers detected`

**Logs**
```
Aug 17 08:27:15 localhost systemd: Started Metabase.
Aug 17 08:27:17 localhost java: Warning: protocol #'java-time.core/Amount is overwriting function abs
Aug 17 08:27:17 localhost java: WARNING: abs already refers to: #'clojure.core/abs in namespace: java-time.core, being replaced by: #'java-time.core/abs
Aug 17 08:27:18 localhost java: WARNING: abs already refers to: #'clojure.core/abs in namespace: java-time, being replaced by: #'java-time/abs
Aug 17 08:27:19 localhost java: Exception in thread "main" java.lang.Error: Circular loading of installed providers detected
Aug 17 08:27:19 localhost java: at java.nio.file.spi.FileSystemProvider.installedProviders(FileSystemProvider.java:161)
Aug 17 08:27:19 localhost java: at java.nio.file.Paths.get(Paths.java:141)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.util.Source.toFile(Source.java:55)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.util.Source.<init>(Source.java:142)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.config.ConfigurationSource.<init>(ConfigurationSource.java:139)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.config.ConfigurationSource.getConfigurationSource(ConfigurationSource.java:388)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.config.ConfigurationSource.fromResource(ConfigurationSource.java:366)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:554)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:483)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:325)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:690)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
Aug 17 08:27:19 localhost java: at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:55)
Aug 17 08:27:19 localhost java: at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
Aug 17 08:27:19 localhost java: at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
Aug 17 08:27:19 localhost java: at clojure.tools.logging$eval136$reify__148.get_logger(NO_SOURCE_FILE:0)
Aug 17 08:27:19 localhost java: at metabase.util$fn__6159.invokeStatic(util.clj:81)
Aug 17 08:27:19 localhost java: at metabase.util$fn__6159.invoke(util.clj:81)
Aug 17 08:27:19 localhost java: at metabase.util__init.load(Unknown Source)
Aug 17 08:27:19 localhost java: at metabase.util__init.<clinit>(Unknown Source)
Aug 17 08:27:19 localhost java: at java.lang.Class.forName0(Native Method)
Aug 17 08:27:19 localhost java: at java.lang.Class.forName(Class.java:348)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.classForName(RT.java:2209)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.classForName(RT.java:2218)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.loadClassForName(RT.java:2237)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.load(RT.java:449)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.load(RT.java:424)
Aug 17 08:27:19 localhost java: at clojure.core$load$fn__6908.invoke(core.clj:6161)
Aug 17 08:27:19 localhost java: at clojure.core$load.invokeStatic(core.clj:6160)
Aug 17 08:27:19 localhost java: at clojure.core$load.doInvoke(core.clj:6144)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.invoke(RestFn.java:408)
Aug 17 08:27:19 localhost java: at clojure.core$load_one.invokeStatic(core.clj:5933)
Aug 17 08:27:19 localhost java: at clojure.core$load_one.invoke(core.clj:5928)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib.invokeStatic(core.clj:5974)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib.doInvoke(core.clj:5953)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.applyTo(RestFn.java:142)
Aug 17 08:27:19 localhost java: at clojure.core$apply.invokeStatic(core.clj:669)
Aug 17 08:27:19 localhost java: at clojure.core$load_libs.invokeStatic(core.clj:6016)
Aug 17 08:27:19 localhost java: at clojure.core$load_libs.doInvoke(core.clj:6000)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.applyTo(RestFn.java:137)
Aug 17 08:27:19 localhost java: at clojure.core$apply.invokeStatic(core.clj:669)
Aug 17 08:27:19 localhost java: at clojure.core$require.invokeStatic(core.clj:6038)
Aug 17 08:27:19 localhost java: at clojure.core$require.doInvoke(core.clj:6038)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.invoke(RestFn.java:512)
Aug 17 08:27:19 localhost java: at metabase.db.env$loading__6789__auto____20070.invoke(env.clj:1)
Aug 17 08:27:19 localhost java: at metabase.db.env__init.load(Unknown Source)
Aug 17 08:27:19 localhost java: at metabase.db.env__init.<clinit>(Unknown Source)
Aug 17 08:27:19 localhost java: at java.lang.Class.forName0(Native Method)
Aug 17 08:27:19 localhost java: at java.lang.Class.forName(Class.java:348)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.classForName(RT.java:2209)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.classForName(RT.java:2218)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.loadClassForName(RT.java:2237)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.load(RT.java:449)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.load(RT.java:424)
Aug 17 08:27:19 localhost java: at clojure.core$load$fn__6908.invoke(core.clj:6161)
Aug 17 08:27:19 localhost java: at clojure.core$load.invokeStatic(core.clj:6160)
Aug 17 08:27:19 localhost java: at clojure.core$load.doInvoke(core.clj:6144)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.invoke(RestFn.java:408)
Aug 17 08:27:19 localhost java: at clojure.core$load_one.invokeStatic(core.clj:5933)
Aug 17 08:27:19 localhost java: at clojure.core$load_one.invoke(core.clj:5928)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib.invokeStatic(core.clj:5974)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib.doInvoke(core.clj:5953)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.applyTo(RestFn.java:142)
Aug 17 08:27:19 localhost java: at clojure.core$apply.invokeStatic(core.clj:669)
Aug 17 08:27:19 localhost java: at clojure.core$load_libs.invokeStatic(core.clj:6016)
Aug 17 08:27:19 localhost java: at clojure.core$load_libs.doInvoke(core.clj:6000)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.applyTo(RestFn.java:137)
Aug 17 08:27:19 localhost java: at clojure.core$apply.invokeStatic(core.clj:669)
Aug 17 08:27:19 localhost java: at clojure.core$require.invokeStatic(core.clj:6038)
Aug 17 08:27:19 localhost java: at clojure.core$require.doInvoke(core.clj:6038)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.invoke(RestFn.java:436)
Aug 17 08:27:19 localhost java: at metabase.db.connection$loading__6789__auto____20106.invoke(connection.clj:1)
Aug 17 08:27:19 localhost java: at metabase.db.connection__init.load(Unknown Source)
Aug 17 08:27:19 localhost java: at metabase.db.connection__init.<clinit>(Unknown Source)
Aug 17 08:27:19 localhost java: at java.lang.Class.forName0(Native Method)
Aug 17 08:27:19 localhost java: at java.lang.Class.forName(Class.java:348)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.classForName(RT.java:2209)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.classForName(RT.java:2218)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.loadClassForName(RT.java:2237)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.load(RT.java:449)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.load(RT.java:424)
Aug 17 08:27:19 localhost java: at clojure.core$load$fn__6908.invoke(core.clj:6161)
Aug 17 08:27:19 localhost java: at clojure.core$load.invokeStatic(core.clj:6160)
Aug 17 08:27:19 localhost java: at clojure.core$load.doInvoke(core.clj:6144)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.invoke(RestFn.java:408)
Aug 17 08:27:19 localhost java: at clojure.core$load_one.invokeStatic(core.clj:5933)
Aug 17 08:27:19 localhost java: at clojure.core$load_one.invoke(core.clj:5928)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib.invokeStatic(core.clj:5974)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib.doInvoke(core.clj:5953)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.applyTo(RestFn.java:142)
Aug 17 08:27:19 localhost java: at clojure.core$apply.invokeStatic(core.clj:669)
Aug 17 08:27:19 localhost java: at clojure.core$load_libs.invokeStatic(core.clj:6016)
Aug 17 08:27:19 localhost java: at clojure.core$load_libs.doInvoke(core.clj:6000)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.applyTo(RestFn.java:137)
Aug 17 08:27:19 localhost java: at clojure.core$apply.invokeStatic(core.clj:669)
Aug 17 08:27:19 localhost java: at clojure.core$require.invokeStatic(core.clj:6038)
Aug 17 08:27:19 localhost java: at clojure.core$require.doInvoke(core.clj:6038)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.invoke(RestFn.java:457)
Aug 17 08:27:19 localhost java: at metabase.db$loading__6789__auto____35568.invoke(db.clj:1)
Aug 17 08:27:19 localhost java: at metabase.db__init.load(Unknown Source)
Aug 17 08:27:19 localhost java: at metabase.db__init.<clinit>(Unknown Source)
Aug 17 08:27:19 localhost java: at java.lang.Class.forName0(Native Method)
Aug 17 08:27:19 localhost java: at java.lang.Class.forName(Class.java:348)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.classForName(RT.java:2209)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.classForName(RT.java:2218)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.loadClassForName(RT.java:2237)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.load(RT.java:449)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.load(RT.java:424)
Aug 17 08:27:19 localhost java: at clojure.core$load$fn__6908.invoke(core.clj:6161)
Aug 17 08:27:19 localhost java: at clojure.core$load.invokeStatic(core.clj:6160)
Aug 17 08:27:19 localhost java: at clojure.core$load.doInvoke(core.clj:6144)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.invoke(RestFn.java:408)
Aug 17 08:27:19 localhost java: at clojure.core$load_one.invokeStatic(core.clj:5933)
Aug 17 08:27:19 localhost java: at clojure.core$load_one.invoke(core.clj:5928)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib.invokeStatic(core.clj:5974)
Aug 17 08:27:19 localhost java: at clojure.core$load_lib.doInvoke(core.clj:5953)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.applyTo(RestFn.java:142)
Aug 17 08:27:19 localhost java: at clojure.core$apply.invokeStatic(core.clj:669)
Aug 17 08:27:19 localhost java: at clojure.core$load_libs.invokeStatic(core.clj:6016)
Aug 17 08:27:19 localhost java: at clojure.core$load_libs.doInvoke(core.clj:6000)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.applyTo(RestFn.java:137)
Aug 17 08:27:19 localhost java: at clojure.core$apply.invokeStatic(core.clj:669)
Aug 17 08:27:19 localhost java: at clojure.core$require.invokeStatic(core.clj:6038)
Aug 17 08:27:19 localhost java: at clojure.core$require.doInvoke(core.clj:6038)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.invoke(RestFn.java:3894)
Aug 17 08:27:19 localhost java: at metabase.core$loading__6789__auto____83903.invoke(core.clj:1)
Aug 17 08:27:19 localhost java: at metabase.core__init.load(Unknown Source)
Aug 17 08:27:19 localhost java: at metabase.core__init.<clinit>(Unknown Source)
Aug 17 08:27:19 localhost java: at java.lang.Class.forName0(Native Method)
Aug 17 08:27:19 localhost java: at java.lang.Class.forName(Class.java:348)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.classForName(RT.java:2209)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.classForName(RT.java:2218)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.loadClassForName(RT.java:2237)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.load(RT.java:449)
Aug 17 08:27:19 localhost java: at clojure.lang.RT.load(RT.java:424)
Aug 17 08:27:19 localhost java: at clojure.core$load$fn__6908.invoke(core.clj:6161)
Aug 17 08:27:19 localhost java: at clojure.core$load.invokeStatic(core.clj:6160)
Aug 17 08:27:19 localhost java: at clojure.core$load.doInvoke(core.clj:6144)
Aug 17 08:27:19 localhost java: at clojure.lang.RestFn.invoke(RestFn.java:408)
Aug 17 08:27:19 localhost java: at clojure.lang.Var.invoke(Var.java:384)
Aug 17 08:27:19 localhost java: at clojure.lang.Util.loadWithClass(Util.java:251)
Aug 17 08:27:19 localhost java: at metabase.core.<clinit>(Unknown Source)
Aug 17 08:27:19 localhost systemd: metabase.service: main process exited, code=exited, status=1/FAILURE
Aug 17 08:27:19 localhost systemd: Unit metabase.service entered failed state.
Aug 17 08:27:19 localhost systemd: metabase.service failed.
```

**To Reproduce**
Upgrade an existing installation by replacing the jar-File.

**Information about your Metabase Installation:**

* `Linux localhost 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Metabase 0.44.1 (also happened in 0.44.0)
* Jar-file on CentOS 7
* MariaDB 10.2

**Severity**
Blocking an upgrade. Downgrading the jar-File to 0.43.4.2 works.

**Comment by flamber** [comment]
Upgrade to Java 11: https://www.metabase.com/docs/latest/operations-guide/java-versions.html

**Comment by markuslf** [comment]
A hint in the [Upgrade guide](https://www.metabase.com/docs/latest/operations-guide/upgrading-metabase.html) (which I consulted) would be nice.
