### ISSUE TITLE
ValidationFailedException for migration ID 268 after going from 0.43.4 -> 0.44.1 -> 0.43.4

### ISSUE THREAD

**Issue by alexterray** [metabase/metabase#24909]
**Describe the bug**
We are hosting Metabase through Docker and tried upgrading from 0.43.4 to 0.44.1. However due to a separate Google SSO bug we were experiencing on 0.44.1 (which I will report shortly) we decided to roll back to 0.43.4. When we reverted back to 0.43.4 the Docker image was unable to start due to the following ValidationFailedException below. Note our application DB is running MySQL 8 on RDS.

```
2022-08-18 00:41:58,793 INFO db.setup :: Successfully verified MySQL 8.0.25 application database connection. ✅
2022-08-18 00:41:58,795 INFO db.setup :: Running Database Migrations...
2022-08-18 00:41:58,798 INFO db.setup :: Setting up Liquibase...
2022-08-18 00:41:58,992 INFO db.setup :: Liquibase is ready.
2022-08-18 00:41:58,992 INFO db.liquibase :: Checking if Database has unrun migrations...
2022-08-18 00:42:00,891 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          migrations/000_migrations.yaml::268::rlotun was: 8:4ccc4d50f9b233bc6515780d9cae360b but is now: 8:9da2f706a7cd42b5101601e0106fa929

        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:296)
        at liquibase.Liquibase$16.run(Liquibase.java:1988)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.Liquibase.runInScope(Liquibase.java:2405)
        at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1978)
        at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1969)
        at metabase.db.liquibase$has_unrun_migrations_QMARK_.invokeStatic(liquibase.clj:109)
        at metabase.db.liquibase$has_unrun_migrations_QMARK_.invoke(liquibase.clj:99)
        at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:134)
        at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:130)
        at metabase.db.setup$fn__35427$migrate_BANG___35432$fn__35433$fn__35434.invoke(setup.clj:66)
        at metabase.db.liquibase$fn__30951$do_with_liquibase__30956$fn__30957.invoke(liquibase.clj:59)
        at metabase.db.liquibase$fn__30951$do_with_liquibase__30956.invoke(liquibase.clj:51)
        at metabase.db.setup$fn__35427$migrate_BANG___35432$fn__35433.invoke(setup.clj:61)
        at metabase.db.setup$fn__35427$migrate_BANG___35432.invoke(setup.clj:40)
        at metabase.db.setup$fn__35486$run_schema_migrations_BANG___35491$fn__35492.invoke(setup.clj:119)
        at metabase.db.setup$fn__35486$run_schema_migrations_BANG___35491.invoke(setup.clj:113)
        at metabase.db.setup$fn__35538$setup_db_BANG___35543$fn__35544$fn__35547$fn__35548.invoke(setup.clj:145)
        at metabase.util$do_with_us_locale.invokeStatic(util.clj:716)
        at metabase.util$do_with_us_locale.invoke(util.clj:702)
        at metabase.db.setup$fn__35538$setup_db_BANG___35543$fn__35544$fn__35547.invoke(setup.clj:143)
        at metabase.db.setup$fn__35538$setup_db_BANG___35543$fn__35544.invoke(setup.clj:142)
        at metabase.db.setup$fn__35538$setup_db_BANG___35543.invoke(setup.clj:136)
        at metabase.db$setup_db_BANG_$fn__35573.invoke(db.clj:65)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:60)
        at metabase.db$setup_db_BANG_.invoke(db.clj:51)
        at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:98)
        at metabase.core$init_BANG__STAR_.invoke(core.clj:81)
        at metabase.core$init_BANG_.invokeStatic(core.clj:138)
        at metabase.core$init_BANG_.invoke(core.clj:133)
        at metabase.core$start_normally.invokeStatic(core.clj:150)
        at metabase.core$start_normally.invoke(core.clj:144)
        at metabase.core$_main.invokeStatic(core.clj:183)
        at metabase.core$_main.doInvoke(core.clj:177)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
2022-08-18 00:42:00,907 INFO metabase.core :: Metabase Shutting Down ...
2022-08-18 00:42:00,909 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2022-08-18 00:42:00,922 INFO metabase.core :: Metabase Shutdown COMPLETE
```

**To Reproduce**
1. Have a Metabase container running 0.43.4 and MySQL 8 app DB
2. Upgrade from 0.44.1 and start the server (triggering migrations in the process)
3. Try to re-run the 0.43.4 container and the ValidationFailedException comes up

**Information about your Metabase Installation:**
This is the info for the current 0.43.4 version of MB we're now running again:

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.15+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.15",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.15+10",
    "os.name": "Linux",
    "os.version": "5.4.0-1083-aws",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.5"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-27",
      "tag": "v0.43.4",
      "branch": "release-x.43.x",
      "hash": "61cc28e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
I'd say pretty high severity. Previously we were able to hop versions seamlessly as we tested some new stable and RC versions, but this is my only time running into a migration issue that rendered our app DB unusable. I ended up restoring from a snapshot to revert, but I did lose about a day's worth of query updates in the process.

Let me know if there's other info I can provide.

**Comment by flamber** [comment]
Caused by #24483. Mostly effects MySQL/MariaDB appdb, when downgrading from v44.1 to any previous versions (e.g. v44.0).

Workaround on MySQL/MariaDB if downgrading. Run this query on the application database prior to starting previous version.
```mysql
-- MySQL/MariaDB
UPDATE `DATABASECHANGELOG`
  SET `MD5SUM`='8:9da2f706a7cd42b5101601e0106fa929'
  WHERE `ID`='268' AND `EXECTYPE`='MARK_RAN' AND `MD5SUM`='8:4ccc4d50f9b233bc6515780d9cae360b';
```

If a new instance is started with v44.1 on Postgres, then it gets the new checksum, which causes the same problem if trying to downgrade, but a less likely scenario. On Postgres, run this to modify the checksum, so it's compatible with previous versions.
```pgsql
-- Postgres
UPDATE "databasechangelog"
  SET "md5sum"='8:9da2f706a7cd42b5101601e0106fa929'
  WHERE "id"='268' AND "exectype"='EXECUTED' AND "md5sum"='8:4ccc4d50f9b233bc6515780d9cae360b';
```

**Comment by alexterray** [comment]
That update query worked, thanks!

**Comment by luizarakaki** [comment]
Metabase supports downgrading only by restoring a snapshot of the application database in the previous version https://www.metabase.com/docs/latest/installation-and-operation/upgrading-metabase#backing-up-your-application-database.
