### ISSUE TITLE
The drill-through feature is not working for Questions that have Custom Columns created from aggregated values.

### ISSUE THREAD

**Issue by Tony-metabase** [metabase/metabase#25415]
**Describe the bug**
The drill-through feature is not working for Questions that have Custom Columns created from aggregated values.

**To Reproduce**

1. Create a Question with aggregated values.

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/110378427/190203783-efaea267-1ca9-41e7-bad7-26c5fd5d2399.png">

3. Create a Custom Columns using those aggregated values:

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/110378427/190203965-919d0f40-6c44-441b-b4bd-7ab83bf82876.png">

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/110378427/190204041-3774ed97-1ef9-43f0-84fc-53f2d78b8036.png">

5. Run and select a line Visualisation and press on "View Orders"

<img width="820" alt="image" src="https://user-images.githubusercontent.com/110378427/190204379-e55c1f12-5065-4bf8-9de5-fb8c009bc483.png">

6. Nothing happens and logs are empty

**Expected behavior**

Drill-through feature works

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: Chrome 
- Your operating system:  OS X 
- Your databases: Postgres
- Metabase version: 44.2
- Metabase hosting environment:Docker
- Metabase internal database: Postgres

**Comment by flamber** [comment]
The browser console throws similar error as #13504, which likely indicates it's a frontend issue, but it is not fixed in 0.44.5.

Reproduce:
1. Question > Sample > Products - summarize Count grouped by Category, then add Custom Column `[Count] * 1` as CC
![image](https://user-images.githubusercontent.com/1447303/194744471-bef911df-eafa-41b2-875e-a4d401abfd12.png)
2. Change to Bar viz and click any of the CC bars > "View these Products" - nothing happens, only browser console log.
![image](https://user-images.githubusercontent.com/1447303/194744520-1fe0c0e8-faa0-48cb-ae2a-878f3f23f753.png)
```
Uncaught TypeError: Cannot read properties of null (reading 'field_ref')
    at f (dataset.js:30:12)
    at me (actions.js:119:22)
    at Question.ts:562:37
    at Array.reduce (<anonymous>)
    at n.value (Question.ts:561:20)
    at Object.question (UnderlyingRecordsDrill.jsx:38:25)
    at O (action.js:30:29)
    at ChartClickActions.jsx:96:26
    at onClick (ChartClickActions.jsx:336:24)
    at Object.l (react-dom.production.min.js:14:84)
```

**Comment by ranquild** [comment]
The underlying problem is that `topLevelClicked` in MLv1 looses such columns.

**Comment by wzimrin** [comment]
Already seems to be fixed -- when I follow flamber's repro, I get a list of doohickeys
