### ISSUE TITLE
migrate 0.44.3 H2 to Mysql: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by Boran** [metabase/metabase#25478]
**Describe the bug**
I have just started trying out Metabase, now 0.44.3 running with H2. Would like to change to mysql backend.

**Logs**
2022-09-19 08:11:02,419 INFO metabase.core ::
Metabase Enterprise Edition extensions are NOT PRESENT.
2022-09-19 08:11:02,481 INFO cmd.copy :: Set up h2 source database and run migrations...
2022-09-19 08:11:02,481 INFO db.setup :: Verifying h2 Database Connection ...
2022-09-19 08:11:02,903 INFO db.setup :: Successfully verified H2 1.4.197 (2018-03-18) application database connection. 
2022-09-19 08:11:02,903 INFO db.setup :: Running Database Migrations...
2022-09-19 08:11:02,903 INFO db.setup :: Setting up Liquibase...
2022-09-19 08:11:03,343 INFO db.setup :: Liquibase is ready.
2022-09-19 08:11:03,343 INFO db.liquibase :: Checking if Database has unrun migrations...
2022-09-19 08:11:05,046 INFO db.setup :: Database Migrations Current ...
2022-09-19 08:11:05,046 INFO db.data-migrations :: Running all necessary data migrations, this may take a minute.
2022-09-19 08:11:05,062 INFO db.data-migrations :: Finished running data migrations.
2022-09-19 08:11:05,062 INFO metabase.util :: Database setup took 2.6 s
2022-09-19 08:11:05,062 INFO cmd.copy :: [OK]
2022-09-19 08:11:05,062 INFO cmd.copy :: Set up mysql target database and run migrations...
2022-09-19 08:11:05,062 INFO db.setup :: Verifying mysql Database Connection ...
2022-09-19 08:11:05,251 INFO db.setup :: Successfully verified MySQL 5.5.55-0ubuntu0.14.04.1-log application database connection.
2022-09-19 08:11:05,251 INFO db.setup :: Running Database Migrations...
2022-09-19 08:11:05,251 INFO db.setup :: Setting up Liquibase...
2022-09-19 08:11:05,267 INFO db.setup :: Liquibase is ready.
2022-09-19 08:11:05,267 INFO db.liquibase :: Checking if Database has unrun migrations...
2022-09-19 08:11:06,282 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2022-09-19 08:11:06,423 INFO db.liquibase :: Migration lock is cleared. Running migrations...
2022-09-19 08:11:06,595 ERROR cmd.copy :: [FAIL]

clojure.lang.ExceptionInfo: ERROR Set up mysql target database and run migrations...: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::1::agilliland:
     Reason: liquibase.exception.DatabaseException: (conn=639395) Specified key was too long; max key length is 767 bytes [Failed SQL: (1071) CREATE TABLE `metabase`.`core_organization` (`id` INT AUTO_INCREMENT NOT NULL, `slug` VARCHAR(254) NOT NULL, `name` VARCHAR(254) NOT NULL, `description` TEXT NULL, `logo_url` VARCHAR(254) NULL, `inherits` BIT(1) NOT NULL, CONSTRAINT `PK_CORE_ORGANIZATION` PRIMARY KEY (`id`), UNIQUE (`slug`)) ENGINE InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;] {}
        at metabase.cmd.copy$do_step$fn__81866.invoke(copy.clj:67)
        at metabase.cmd.copy$do_step.invokeStatic(copy.clj:63)
        at metabase.cmd.copy$do_step.invoke(copy.clj:61)
        at metabase.cmd.copy$fn__82020$copy_BANG___82025$fn__82026.invoke(copy.clj:343)
        at metabase.cmd.copy$fn__82020$copy_BANG___82025.invoke(copy.clj:331)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:35)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:25)
        at clojure.lang.Var.invoke(Var.java:384)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:45)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:39)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.cmd$run_cmd$fn__82839.invoke(cmd.clj:227)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:227)
        at metabase.cmd$run_cmd.invoke(cmd.clj:218)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.core$run_cmd.invokeStatic(core.clj:160)
        at metabase.core$run_cmd.invoke(core.clj:158)
        at metabase.core$_main.invokeStatic(core.clj:182)
        at metabase.core$_main.doInvoke(core.clj:177)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::1::agilliland:
     Reason: liquibase.exception.DatabaseException: (conn=639395) Specified key was too long; max key length is 767 bytes [Failed SQL: (1071) CREATE TABLE `metabase`.`core_organization` (`id` INT AUTO_INCREMENT NOT NULL, `slug` VARCHAR(254) NOT NULL, `name` VARCHAR(254) NOT NULL, `description` TEXT NULL, `logo_url` VARCHAR(254) NULL, `inherits` BIT(1) NOT NULL, CONSTRAINT `PK_CORE_ORGANIZATION` PRIMARY KEY (`id`), UNIQUE (`slug`)) ENGINE InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;]
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126)
        at liquibase.Liquibase.lambda$null$0(Liquibase.java:265)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.Scope.child(Scope.java:243)
        at liquibase.Liquibase.lambda$update$1(Liquibase.java:264)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.Liquibase.runInScope(Liquibase.java:2405)
        at liquibase.Liquibase.update(Liquibase.java:211)
        at liquibase.Liquibase.update(Liquibase.java:197)
        at liquibase.Liquibase.update(Liquibase.java:193)
        at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:142)
        at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:130)
        at metabase.db.setup$fn__35427$migrate_BANG___35432$fn__35433$fn__35434.invoke(setup.clj:66)
        at metabase.db.liquibase$fn__30951$do_with_liquibase__30956$fn__30957.invoke(liquibase.clj:59)
        at metabase.db.liquibase$fn__30951$do_with_liquibase__30956.invoke(liquibase.clj:51)
        at metabase.db.setup$fn__35427$migrate_BANG___35432$fn__35433.invoke(setup.clj:61)
        at metabase.db.setup$fn__35427$migrate_BANG___35432.invoke(setup.clj:40)
        at metabase.db.setup$fn__35486$run_schema_migrations_BANG___35491$fn__35492.invoke(setup.clj:119)
        at metabase.db.setup$fn__35486$run_schema_migrations_BANG___35491.invoke(setup.clj:113)
        at metabase.db.setup$fn__35538$setup_db_BANG___35543$fn__35544$fn__35547$fn__35548.invoke(setup.clj:145)
        at metabase.util$do_with_us_locale.invokeStatic(util.clj:716)
        at metabase.util$do_with_us_locale.invoke(util.clj:702)
        at metabase.db.setup$fn__35538$setup_db_BANG___35543$fn__35544$fn__35547.invoke(setup.clj:143)
        at metabase.db.setup$fn__35538$setup_db_BANG___35543$fn__35544.invoke(setup.clj:142)
        at metabase.db.setup$fn__35538$setup_db_BANG___35543.invoke(setup.clj:136)
        at metabase.cmd.copy$fn__82020$copy_BANG___82025$fn__82026$fn__82029.invoke(copy.clj:345)
        at metabase.cmd.copy$do_step$fn__81866.invoke(copy.clj:64)
        ... 23 more
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::1::agilliland:
     Reason: liquibase.exception.DatabaseException: (conn=639395) Specified key was too long; max key length is 767 bytes [Failed SQL: (1071) CREATE TABLE `metabase`.`core_organization` (`id` INT AUTO_INCREMENT NOT NULL, `slug` VARCHAR(254) NOT NULL, `name` VARCHAR(254) NOT NULL, `description` TEXT NULL, `logo_url` VARCHAR(254) NULL, `inherits` BIT(1) NOT NULL, CONSTRAINT `PK_CORE_ORGANIZATION` PRIMARY KEY (`id`), UNIQUE (`slug`)) ENGINE InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;]

**To Reproduce**
java -jar metabase0.44.3.jar load-from-h2 metabase.db

**Expected behavior**
Create mysql tables

**mysql**
MySQL 5.5.55-0ubuntu0.14.04.1 running on debian.
DB created with: 
CREATE DATABASE metabase CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
grant all on metabase.* to metabase@'%' identified by '<FOO>';

**Severity**
low, H2 keeps working (but that is not ideal)

**Comment by flamber** [comment]
Both MySQL 5.5 and Ubuntu 14.04 is EOL. You should upgrade.
Metabase requires MySQL 5.7.7+: https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#supported-databases-for-storing-your-metabase-application-data

**Comment by Boran** [comment]
Thanks, verified, works fine with a recent version .
