### ISSUE TITLE
Error when running docker image - liquibase.exception.DatabaseException

### ISSUE THREAD

**Issue by remendoapp** [metabase/metabase#2580]
*  I'm running Metabase via Docker on Digital Ocean.
*  My Metabase version is v0.17.0

I am getting the following error when trying to set up Metabase via Docker on a DigitalOcean server:

```
5-11 08:56:29 INFO metabase.core :: Starting Metabase version v0.17.0 (6b3ec87 release-0.17.0) ...
05-11 08:56:29 INFO metabase.core :: System timezone is 'GMT' ...
05-11 08:56:33 DEBUG metabase.driver :: Registered driver :big query 🚚
05-11 08:56:34 DEBUG metabase.driver :: Registered driver :druid 🚚
05-11 08:56:34 DEBUG metabase.driver :: Registered driver :h2 🚚
05-11 08:56:35 DEBUG metabase.driver :: Registered driver :mongo 🚚
05-11 08:56:35 DEBUG metabase.driver :: Registered driver :mysql 🚚
05-11 08:56:35 DEBUG metabase.driver :: Registered driver :postgres 🚚
05-11 08:56:35 DEBUG metabase.driver :: Registered driver :redshift 🚚
05-11 08:56:35 DEBUG metabase.driver :: Registered driver :sqlite 🚚
05-11 08:56:36 DEBUG metabase.driver :: Registered driver :sqlserver 🚚
05-11 08:56:38 INFO metabase.db :: Verifying Database Connection ...
05-11 08:56:40 INFO metabase.db :: Verify Database Connection ... ✅
liquibase.exception.DatabaseException: liquibase.exception.ChangeLogParseException: Error parsing migrations/liquibase.json
	at metabase.db$migrate.invokeStatic(db.clj:106)
	at metabase.db$migrate.invoke(db.clj:94)
	at metabase.db$setup_db.invokeStatic(db.clj:166)
	at metabase.db$setup_db.doInvoke(db.clj:154)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:129)
	at metabase.core$init_BANG_.invoke(core.clj:113)
	at metabase.core$start_normally.invokeStatic(core.clj:213)
	at metabase.core$start_normally.invoke(core.clj:207)
	at metabase.core$_main.invokeStatic(core.clj:247)
	at metabase.core$_main.doInvoke(core.clj:242)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: liquibase.exception.ChangeLogParseException: Error parsing migrations/liquibase.json
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:98)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:227)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.Liquibase.update(Liquibase.java:188)
	at liquibase.Liquibase.update(Liquibase.java:181)
	at metabase.db$migrate$fn__5280.invoke(db.clj:111)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:595)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568)
	at clojure.lang.RestFn.invoke(RestFn.java:521)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:611)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	... 15 more
Caused by: liquibase.exception.SetupException: Error parsing migrations/001_initial_schema.json
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:269)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:230)
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:91)
	... 27 more
Caused by: liquibase.exception.ChangeLogParseException: Error parsing migrations/001_initial_schema.json
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:98)
	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:404)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:267)
	... 29 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.newNode(HashMap.java:1734)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.jar.Manifest.read(Manifest.java:249)
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:251)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:238)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:316)
	at java.util.jar.JarVerifier.update(JarVerifier.java:228)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
	at java.util.jar.JarFile.getInputStream(JarFile.java:450)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:162)
	at liquibase.resource.ClassLoaderResourceAccessor.getResourcesAsStream(ClassLoaderResourceAccessor.java:47)
	at liquibase.util.StreamUtil.singleInputStream(StreamUtil.java:182)
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:26)
	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:404)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:267)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:230)
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:91)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:227)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.Liquibase.update(Liquibase.java:188)
	at liquibase.Liquibase.update(Liquibase.java:181)
	at metabase.db$migrate$fn__5280.invoke(db.clj:111)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:595)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568)
	at clojure.lang.RestFn.invoke(RestFn.java:521)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:611)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.db$migrate.invokeStatic(db.clj:106)
	at metabase.db$migrate.invoke(db.clj:94)
05-11 08:57:14 ERROR metabase.core :: Metabase Initialization FAILED:  liquibase.exception.ChangeLogParseException: Error parsing migrations/liquibase.json
05-11 08:57:14 INFO metabase.core :: Metabase Shutting Down ...
05-11 08:57:14 INFO metabase.core :: Metabase Shutdown COMPLETE

```

**Comment by remendoapp** [comment]
It was causes by too little memory (512 mb)
