### ISSUE TITLE
Metabase migrations are failing

### ISSUE THREAD

**Issue by casiodk** [metabase/metabase#25852]
I am getting this error when updating from 0.42.4 to 0.44.4

```
2022-10-08 23:32:18.610 CEST Reason: liquibase.exception.DatabaseException: ERROR: must be owner of table core_user [Failed SQL: (0) ALTER TABLE "public"."core_user" ADD "settings" TEXT] at liquibase.changelog.ChangeSet.execute(ChangeSet.java:696) at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:56) at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:113) at liquibase.Scope.lambda$child$0(Scope.java:180) at liquibase.Scope.child(Scope.java:189) at liquibase.Scope.child(Scope.java:179) at liquibase.Scope.child(Scope.java:158) at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:112) at liquibase.Scope.lambda$child$0(Scope.java:180) at liquibase.Scope.child(Scope.java:189) at liquibase.Scope.child(Scope.java:179) at liquibase.Scope.child(Scope.java:158) at liquibase.Scope.child(Scope.java:243) at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93) at liquibase.Scope.lambda$child$0(Scope.java:180) at liquibase.Scope.child(Scope.java:189) at liquibase.Scope.child(Scope.java:179) at liquibase.Scope.child(Scope.java:158) at liquibase.Scope.child(Scope.java:243) at liquibase.Scope.child(Scope.java:247) at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:65) ... 45 more Caused by: liquibase.exception.DatabaseException: ERROR: must be owner of table core_user [Failed SQL: (0) ALTER TABLE "public"."core_user" ADD "settings" TEXT] at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:397) at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83) at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:151) at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1279) at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1261) at liquibase.changelog.ChangeSet.execute(ChangeSet.java:661) ... 65 more Caused by: org.postgresql.util.PSQLException: ERROR: must be owner of table core_user at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333) at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319) at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290) at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75) at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393) ... 70 more
```

Everything works when I revert back to 0.42.4

**Comment by casiodk** [comment]
I am connecting to a google cloud SQL postgres 13.7 instance on kubernetes through a sidecar/proxy user

**Comment by paoliniluis** [comment]
Have you changed something manually in your app db? I suggest you grant the permissions manually to the user you're using to connect to the app db and then try again
