### ISSUE TITLE
Problem when We use `Sync database schema now`

### ISSUE THREAD

**Issue by sandrolmenezes** [metabase/metabase#26459]
**Describe the bug**
When We use `Sync database schema now` raise this error. How can We overcome this error ?

**Logs**
[e17bce1d-4660-4ab8-8c66-3b2b5d0b48fa] 2022-11-11T17:39:45-05:00 ERROR metabase.models.field-values Error fetching field values
clojure.lang.ExceptionInfo: Error executing query: com.google.cloud.bigquery.BigQueryException: Not found: Table carol-7d4a4fb9a5bd4ba8a5df:7d4a4fb9a5bd4ba8a5dfa81c6f518f7e.tt_temp_task_dmartigos_2022-10-25_29a74afff12944f1b8db7ee7663797ad was not found in location US {:type :invalid-query, :sql "SELECT `7d4a4fb9a5bd4ba8a5dfa81c6f518f7e.tt_temp_task_dmartigos_2022-10-25_29a74afff12944f1b8db7ee7663797ad`.`org_url` AS `org_url` FROM `7d4a4fb9a5bd4ba8a5dfa81c6f518f7e.tt_temp_task_dmartigos_2022-10-25_29a74afff12944f1b8db7ee7663797ad` GROUP BY `org_url` ORDER BY `org_url` ASC LIMIT 1000", :parameters nil}
	at metabase.driver.bigquery_cloud_sdk$throw_invalid_query.invokeStatic(bigquery_cloud_sdk.clj:173)
	at metabase.driver.bigquery_cloud_sdk$throw_invalid_query.invoke(bigquery_cloud_sdk.clj:172)
	at metabase.driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:215)
	at metabase.driver.bigquery_cloud_sdk$execute_bigquery.invoke(bigquery_cloud_sdk.clj:177)
	at metabase.driver.bigquery_cloud_sdk$execute_bigquery_on_db.invokeStatic(bigquery_cloud_sdk.clj:219)
	at metabase.driver.bigquery_cloud_sdk$execute_bigquery_on_db.invoke(bigquery_cloud_sdk.clj:217)
	at metabase.driver.bigquery_cloud_sdk$process_native_STAR_$thunk__82596.invoke(bigquery_cloud_sdk.clj:279)
	at metabase.driver.bigquery_cloud_sdk$process_native_STAR_.invokeStatic(bigquery_cloud_sdk.clj:287)
	at metabase.driver.bigquery_cloud_sdk$process_native_STAR_.invoke(bigquery_cloud_sdk.clj:271)
	at metabase.driver.bigquery_cloud_sdk$fn__82602.invokeStatic(bigquery_cloud_sdk.clj:307)
	at metabase.driver.bigquery_cloud_sdk$fn__82602.invoke(bigquery_cloud_sdk.clj:299)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:67)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:65)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)
	at metabase.query_processor.reducible$identity_qp.invoke(reducible.clj:9)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___52619.invoke(cache.clj:220)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__48140.invoke(permissions.clj:109)
	at metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__85599.invoke(permissions.clj:124)
	at metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__87403.invoke(column_level_perms_check.clj:30)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__51564.invoke(mbql_to_native.clj:23)
	at metabase.query_processor$fn__54095$combined_post_process__54100$combined_post_process_STAR___54101.invoke(query_processor.clj:212)
	at metabase.query_processor$fn__54095$combined_pre_process__54096$combined_pre_process_STAR___54097.invoke(query_processor.clj:209)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52540$fn__52545.invoke(resolve_database_and_driver.clj:35)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:75)
	at metabase.driver$do_with_driver.invoke(driver.clj:71)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52540.invoke(resolve_database_and_driver.clj:34)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__48575.invoke(fetch_source_query.clj:353)
	at metabase.query_processor.middleware.store$initialize_store$fn__48763$fn__48764.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.query_processor.middleware.store$initialize_store$fn__48763.invoke(store.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__52812.invoke(normalize_query.clj:22)
	at metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__59637.invoke(handle_audit_queries.clj:130)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44978$thunk__44980.invoke(reducible.clj:100)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44978.invoke(reducible.clj:106)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44978.invoke(reducible.clj:91)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44978.invoke(reducible.clj:88)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.query_processor.reducible$sync_qp$qp_STAR___44989.doInvoke(reducible.clj:126)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:247)
	at metabase.query_processor$process_query.doInvoke(query_processor.clj:241)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.db.metadata_queries$qp_query$fn__68365.invoke(metadata_queries.clj:21)
	at metabase.db.metadata_queries$qp_query.invokeStatic(metadata_queries.clj:20)
	at metabase.db.metadata_queries$qp_query.invoke(metadata_queries.clj:18)
	at metabase.db.metadata_queries$field_query.invokeStatic(metadata_queries.clj:31)
	at metabase.db.metadata_queries$field_query.invoke(metadata_queries.clj:29)
	at metabase.db.metadata_queries$fn__68385$field_distinct_values__68394$fn__68397.invoke(metadata_queries.clj:76)
	at metabase.db.metadata_queries$fn__68385$field_distinct_values__68394.invoke(metadata_queries.clj:69)
	at metabase.db.metadata_queries$fn__68385$field_distinct_values__68394$fn__68395.invoke(metadata_queries.clj:73)
	at metabase.db.metadata_queries$fn__68385$field_distinct_values__68394.invoke(metadata_queries.clj:69)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.models.field_values$distinct_values.invokeStatic(field_values.clj:288)
	at metabase.models.field_values$distinct_values.invoke(field_values.clj:273)
	at metabase.models.field_values$create_or_update_full_field_values_BANG_.invokeStatic(field_values.clj:315)
	at metabase.models.field_values$create_or_update_full_field_values_BANG_.doInvoke(field_values.clj:307)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.sync.field_values$fn__68200$update_field_values_for_field_BANG___68205$fn__68206.invoke(field_values.clj:26)
	at metabase.sync.field_values$fn__68200$update_field_values_for_field_BANG___68205.invoke(field_values.clj:24)
	at metabase.sync.field_values$fn__68227$update_field_values_for_table_BANG___68232$fn__68233$fn__68234$fn__68235.invoke(field_values.clj:51)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
	at metabase.sync.field_values$fn__68227$update_field_values_for_table_BANG___68232$fn__68233$fn__68234.invoke(field_values.clj:49)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.sync.field_values$fn__68227$update_field_values_for_table_BANG___68232$fn__68233.invoke(field_values.clj:48)
	at metabase.sync.field_values$fn__68227$update_field_values_for_table_BANG___68232.invoke(field_values.clj:45)
	at clojure.core$map$fn__5935.invoke(core.clj:2770)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1790)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.field_values$fn__68255$update_field_values_for_database_BANG___68260$fn__68261.invoke(field_values.clj:60)
	at metabase.sync.field_values$fn__68255$update_field_values_for_database_BANG___68260.invoke(field_values.clj:57)
	at metabase.sync.field_values$make_sync_field_values_steps$fn__68333.invoke(field_values.clj:102)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$fn__42317$run_step_with_metadata__42322$fn__42326$fn__42328.doInvoke(util.clj:388)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:117)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:114)
	at metabase.sync.util$fn__42317$run_step_with_metadata__42322$fn__42326.invoke(util.clj:383)
	at metabase.sync.util$fn__42317$run_step_with_metadata__42322.invoke(util.clj:378)
	at metabase.sync.util$fn__42536$run_sync_operation__42541$fn__42542$fn__42550.invoke(util.clj:493)
	at metabase.sync.util$fn__42536$run_sync_operation__42541$fn__42542.invoke(util.clj:491)
	at metabase.sync.util$fn__42536$run_sync_operation__42541.invoke(util.clj:485)
	at metabase.sync.field_values$fn__68341$update_field_values_BANG___68346$fn__68347$fn__68348.invoke(field_values.clj:112)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:158)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:151)
	at clojure.core$partial$fn__5910.invoke(core.clj:2647)
	at metabase.driver$fn__33076.invokeStatic(driver.clj:599)
	at metabase.driver$fn__33076.invoke(driver.clj:599)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__42226.invoke(util.clj:136)
	at metabase.sync.util$with_db_logging_disabled$fn__42223.invoke(util.clj:127)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:100)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:94)
	at metabase.sync.util$with_start_and_finish_logging$fn__42212.invoke(util.clj:112)
	at metabase.sync.util$with_sync_events$fn__42207.invoke(util.clj:86)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__42198.invoke(util.clj:65)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:179)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:176)
	at metabase.sync.field_values$fn__68341$update_field_values_BANG___68346$fn__68347.invoke(field_values.clj:109)
	at metabase.sync.field_values$fn__68341$update_field_values_BANG___68346.invoke(field_values.clj:105)
	at metabase.api.database$fn__77326$fn__77327$fn__77328.invoke(database.clj:866)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: com.google.cloud.bigquery.BigQueryException: Not found: Table carol-7d4a4fb9a5bd4ba8a5df:7d4a4fb9a5bd4ba8a5dfa81c6f518f7e.tt_temp_task_dmartigos_2022-10-25_29a74afff12944f1b8db7ee7663797ad was not found in location US
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at clojure.core$deref_future.invokeStatic(core.clj:2317)
	at clojure.core$future_call$reify__8544.deref(core.clj:7041)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at metabase.driver.bigquery_cloud_sdk$execute_bigquery.invokeStatic(bigquery_cloud_sdk.clj:181)
	... 127 more
Caused by: com.google.cloud.bigquery.BigQueryException: Not found: Table carol-7d4a4fb9a5bd4ba8a5df:7d4a4fb9a5bd4ba8a5dfa81c6f518f7e.tt_temp_task_dmartigos_2022-10-25_29a74afff12944f1b8db7ee7663797ad was not found in location US
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:115)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:652)
	at com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1278)
	at com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1275)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1274)
	at com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1262)
	at metabase.driver.bigquery_cloud_sdk$execute_bigquery$fn__82495.invoke(bigquery_cloud_sdk.clj:193)
	... 6 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
POST https://www.googleapis.com/bigquery/v2/projects/carol-7d4a4fb9a5bd4ba8a5df/queries
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "Not found: Table carol-7d4a4fb9a5bd4ba8a5df:7d4a4fb9a5bd4ba8a5dfa81c6f518f7e.tt_temp_task_dmartigos_2022-10-25_29a74afff12944f1b8db7ee7663797ad was not found in location US",
    "reason" : "notFound"
  } ],
  "message" : "Not found: Table carol-7d4a4fb9a5bd4ba8a5df:7d4a4fb9a5bd4ba8a5dfa81c6f518f7e.tt_temp_task_dmartigos_2022-10-25_29a74afff12944f1b8db7ee7663797ad was not found in location US",
  "status" : "NOT_FOUND"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:650)
	... 14 more
[e17bce1d-4660-4ab8-8c66-3b2b5d0b48fa] 2022-11-11T17:39:46-05:00 INFO metabase.server.middleware.exceptions Request canceled before finishing.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting.

- Your browser and the version: (e.g., Chrome 52.1, Firefox 48.0, Safari 11.1, …)
- Your operating system: (e.g., OS X 10.10, Windows 10.1809, Ubuntu 16.04, …)
- Your databases: (e.g, MySQL, Postgres, MongoDB, …)
- Metabase version: (e.g., 0.19.3)
- Metabase hosting environment: (e.g., Elastic Beanstalk, Docker, Heroku, Jar-file on Ubuntu, …)
- Metabase internal database: (e.g., H2 (default), Postgres or MySQL)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by paoliniluis** [comment]
Hi, you need to fix the issue in bigquery. Metabase can't find the table maybe because it doesn't exist. Please post on our discourse forum in case there's a problem next time. Thanks!
