### ISSUE TITLE
/metrics endpoint performance

### ISSUE THREAD

**Issue by Onlinehead** [metabase/metabase#26666]
**Describe the bug**
Metrics endpoint has the same problem with performance as a health check (#26266).
When instance has a lot of queued Jetty threads, it stops to respond on the metrics endpoint (same as on the health check) which cause metrics loosing (monitoring system cannot scrape them) same as failed health and system down because of it.
 
**Logs**
`DEBUG middleware.log :: GET /api/field/11667/remapping/11671 200 5.1 s (12 DB calls) App DB connections: 0/15 Jetty threads: 46/50 (0 idle, 244 queued) (182 total active threads) Queries in flight: 0 (0 queued); mysql DB 5 connections: 2/2 (43 threads blocked)`

**To Reproduce**
Same steps as for #26266.
Make sure you generated enough queue

**Expected behavior**
Service endpoint with metrics should work even if user generates load to the app.

**Screenshots**
Missed metrics:
![image](https://user-images.githubusercontent.com/1026551/203285746-5fb7a30d-e179-4676-8960-768527f246b5.png)

**Additional context**
Additional info from the monitoring system on request.

**Comment by paoliniluis** [comment]
Just hit this when the instance was 100% in memory so CPU was also 100% trying to free up the RAM:

```
2025-01-21 00:03:28,149 ERROR httpserver.HttpExchangeAdapter :: The Prometheus metrics HTTPServer caught an Exception while trying to send the metrics response.
java.io.IOException: Broken pipe
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.write(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.write(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.Request$WriteStream.write(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ChunkedOutputStream.writeChunk(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ChunkedOutputStream.write(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.PlaceholderOutputStream.write(Unknown Source)
	at java.base/java.util.zip.GZIPOutputStream.finish(Unknown Source)
	at java.base/java.util.zip.DeflaterOutputStream.close(Unknown Source)
	at io.prometheus.metrics.exporter.common.PrometheusScrapeHandler.handleRequest(PrometheusScrapeHandler.java:68)
	at io.prometheus.metrics.exporter.httpserver.MetricsHandler.handle(MetricsHandler.java:43)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```
