### ISSUE TITLE
Add support for the MySql utf8mb4 encoding used for the new 5.7 Json datatype

### ISSUE THREAD

**Issue by anthofo** [metabase/metabase#2688]
Hi,

The new MySql 5.7 Json datatype brings advanced functions for storing and querying json.
More info here : https://dev.mysql.com/doc/refman/5.7/en/json.html

There is an issue with metabase because MySql 5.7 stores Json only in the utf8mb4 encoding (we cannot force it to utf8).

This encoding is not handled properly by metabase, which breaks the display of json documents containing accentuaded characters.

You can reproduce the problem by creating a json field and inserting utf8 data into it : 

```
CREATE TABLE t1 (jdoc JSON) CHARACTER SET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO t1 VALUES('{"key1": "my value éééàààà"}');
```

Then, try to list the content of the table in metabase. You'll see that the encoding is broken.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by sshilko** [comment]
+1

**Comment by MartinArens** [comment]
+1

**Comment by ravelantunes** [comment]
Also run into this issue trying to setup MySQL as the main database for Metabase. The database I had created was utf8mb4, and startup on a fresh database kept failing with:
`metabase.core :: Metabase Initialization FAILED:  Specified key was too long; max key length is 767 bytes`

utf8mb4 uses 4 bytes instead of the default mysql utf8 that only uses 3 bytes. A place where it's definitely failing is on trying to create VARCHAR(255). With 4 bytes I think the max should be VARCHAR(191).

Wasn't a big deal for me to alter the database encoding to utf8, but handling the mb4 encoding (or maybe adding a note somewhere on the docs) might prevent someone else from getting stuck.

**Comment by camsaul** [comment]
@ravelantunes what version of MySQL are you using?

**Comment by sshilko** [comment]
@camsaul there is issue with any mysql version, metabase doesnt support utf8mb4, even 4byte smilies are not rendered correctly on UI.
its probably 1 liner change on server collation/charset upon connect.

**Comment by camsaul** [comment]
@sshilko @ravelantunes is talking about how he can't launch Metabase when the backing database is using `utf8mb4` because of size limits on indexed columns. If I remember correctly, those limits were raised in a recent version of MySQL, so the version does matter in his case.

**Comment by sshilko** [comment]
utf8mb4 encoded values are not rendered properly by metabase ui, metabase uses utf8 instead of utf8mb4

**Comment by camsaul** [comment]
yup @sshilko, we know 😉

**Comment by ravelantunes** [comment]
@camsaul I'm running MySQL 5.6.23. I did a quick search but wasn't able to find anything pointing to increased limit on recent versions.

**Comment by camsaul** [comment]
@ravelantunes After poking around the documentation it looks like you can enable [http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix](innodb_large_prefix), so if you're going to configure the DB to encode things as `utf8mb4` you should be sure to enable that too. I don't think anyone has tried that yet, so try it at your own risk. I'm not sure if things will work correctly (Metabase assumes UTF-8 encoding), but if you do try it, be sure to let us know how it goes.

**Comment by ad-m** [comment]
As a result of this error, I am unable to install Metabase using MariaDB 10.0.34-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04. I can not change global database settings because they are shared. This makes illusionary support in Metabase for the MySQL.

```
$ java -jar /opt/metabase.jar 
04-08 20:17:02 INFO metabase.util :: Loading Metabase...
04-08 20:17:15 INFO util.encryption :: DB details encryption is ENABLED for this Metabase instance. 🔐 
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
04-08 20:17:33 INFO metabase.core :: Starting Metabase in STANDALONE mode
04-08 20:17:33 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000, :host "127.0.0.1"}

04-08 20:17:34 INFO metabase.core :: Starting Metabase version v0.28.5 (fa5cb8a release-0.28.5) ...
04-08 20:17:34 INFO metabase.core :: System timezone is 'Etc/UTC' ...
04-08 20:17:40 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
04-08 20:17:40 INFO metabase.db :: Verifying mysql Database Connection ...
04-08 20:17:41 INFO metabase.db :: Verify Database Connection ...  ✅
04-08 20:17:41 INFO metabase.db :: Running Database Migrations...
04-08 20:17:41 INFO metabase.db :: Setting up Liquibase...
04-08 20:17:41 INFO metabase.db :: Liquibase is ready.
04-08 20:17:41 INFO metabase.db :: Checking if Database has unrun migrations...
04-08 20:17:57 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-08 20:17:57 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-08 20:17:57 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
04-08 20:17:57 INFO metabase.db :: Migration lock is cleared. Running migrations...
04-08 20:17:58 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-08 20:17:58 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__1839.invoke(jdbc.clj:952)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:784)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:724)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:951)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:945)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:983)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:963)
	at clojure.java.jdbc$execute_BANG_$execute_helper__1910.invoke(jdbc.clj:1364)
	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1366)
	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1337)
	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1356)
	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1337)
	at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:169)
	at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:155)
	at metabase.db$migrate_BANG_$fn__4414.invoke(db.clj:258)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:741)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:724)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at metabase.db$migrate_BANG_.invokeStatic(db.clj:246)
	at metabase.db$migrate_BANG_.invoke(db.clj:227)
	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:381)
	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:376)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:399)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:392)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:154)
	at metabase.core$init_BANG_.invoke(core.clj:133)
	at metabase.core$start_normally.invokeStatic(core.clj:258)
	at metabase.core$start_normally.invoke(core.clj:251)
	at metabase.core$_main.invokeStatic(core.clj:279)
	at metabase.core$_main.doInvoke(core.clj:274)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
04-08 20:19:44 ERROR metabase.core :: Metabase Initialization FAILED:  Specified key was too long; max key length is 767 bytes
04-08 20:19:44 INFO metabase.core :: Metabase Shutting Down ...
04-08 20:19:44 INFO metabase.core :: Metabase Shutdown COMPLETE
```

I am moving to h2.

**Comment by camsaul** [comment]
If I understand this correctly this is only a problem with columns that have an index on them – MySQL/MariaDB only support indexes on text columns up to 191 characters (i.e., `varchar(191)` when using the `utf8mb4` encoding). I need to work out which columns are causing this error; we can adjust the migrations accordingly

**Comment by camsaul** [comment]
I haven't heard much about people running into this issue lately (I haven't ran into it recently at any rate) so it may have only affected a column we have already fixed

**Comment by camsaul** [comment]
Closing this for two reasons: 

1.  we only support and have only ever supported MariaDB 10.2+
2.  we added `utf8mb4` support a while back and actually force MySQL/MariaDB to use it since #10691
