### ISSUE TITLE
Funnel charts with "Month of Year" type dimension and ordering can't render in Static Viz

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#26944]
**Describe the bug**
A Funnel chart with dimension that is grouped by `Month of Year` will fail to render a static viz. This fails because we seem to treat the steps as the index of the month, rather than using the name of the month. 

**To Reproduce**
1. New Question -> Orders
2. Metric -> Count
3. Group by Created At - Month of Year
4. Click Visualize, and set to funnel chart
5. Reorder the funnel steps and save
6. Add to a dashboard and send static Viz
7. Static viz will display: 
![image](https://user-images.githubusercontent.com/1328979/205531202-ba8f2ba7-ac45-414d-b761-3cff13e76fdd.png)

**Expected behavior**
Static Viz should render correctly

**Information about your Metabase Installation:**
```
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.14.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.14.1+1-Ubuntu-0ubuntu1.20.04",
    "os.name": "Linux",
    "os.version": "5.10.16.3-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "America/Halifax"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2022-11-24",
      "src_hash": "4fdb72203d7b38cadc6da948624f6f03b9f129b8",
      "tag": "v1.45.1-SNAPSHOT",
      "branch": "Viz-Settings-Update-Eye-Icons",
      "hash": "94d9e4a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
**Severity**
Likely not super severe

**Comment by flamber** [comment]
<details><summary>Full stacktrace</summary>

```
2022-12-05T10:46:25+01:00 ERROR metabase.pulse.render Pulse card render error
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
	at <js> :anonymous(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:2800387-2800540)
	at <js> n(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:2800370-2800543)
	at <js> xG(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:2799667-2800763)
	at <js> n(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:692421-692434)
	at <js> K(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:693439-693444)
	at <js> K.render(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:691770-693490)
	at <js> K.read(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:691342-691380)
	at <js> renderToStaticMarkup(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:698343-698353)
	at <js> kG(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:2803669-2803732)
	at <js> funnel(file:/app/metabase.jar!/frontend_shared/static_viz_interface.js:52-55:1220-1321)
	at org.graalvm.polyglot.Value.execute(Value.java:841)
	at metabase.pulse.render.js_engine$execute_fn_name.invokeStatic(js_engine.clj:48)
	at metabase.pulse.render.js_engine$execute_fn_name.doInvoke(js_engine.clj:42)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at metabase.pulse.render.js_svg$funnel.invokeStatic(js_svg.clj:125)
	at metabase.pulse.render.js_svg$funnel.invoke(js_svg.clj:121)
	at metabase.pulse.render.body$fn__58509$render__58498__58514$fn__58518.invoke(body.clj:914)
	at metabase.pulse.render.body$fn__58509$render__58498__58514.invoke(body.clj:902)
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
	at metabase.pulse.render$fn__58780$render_pulse_card_body__58785$fn__58789.invoke(render.clj:128)
	at metabase.pulse.render$fn__58780$render_pulse_card_body__58785.invoke(render.clj:118)
	at metabase.pulse.render$fn__58819$render_pulse_card__58824$fn__58825.invoke(render.clj:154)
	at metabase.pulse.render$fn__58819$render_pulse_card__58824.invoke(render.clj:142)
	at metabase.pulse.render$fn__58881$render_pulse_card_to_png__58886$fn__58887.invoke(render.clj:195)
	at metabase.pulse.render$fn__58881$render_pulse_card_to_png__58886.invoke(render.clj:192)
	at metabase.api.pulse$fn__82624$fn__82625.invoke(pulse.clj:227)
	at metabase.api.pulse$fn__82624.invokeStatic(pulse.clj:226)
	at metabase.api.pulse$fn__82624.invoke(pulse.clj:221)
	at compojure.core$wrap_response$fn__29317.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__29301.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__29306.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__29310.invoke(core.clj:151)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29310.invoke(core.clj:153)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29310.invoke(core.clj:153)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29310.invoke(core.clj:152)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29310.invoke(core.clj:153)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29310.invoke(core.clj:153)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__71211.invoke(auth.clj:14)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329.invoke(core.clj:200)
	at compojure.core$make_context$handler__29357.invoke(core.clj:289)
	at compojure.core$make_context$fn__29361.invoke(core.clj:299)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:199)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:199)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329.invoke(core.clj:200)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:199)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329.invoke(core.clj:200)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329.invoke(core.clj:200)
	at metabase.api.routes$fn__83166$fn__83167.invoke(routes.clj:62)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__83329$fn__83330.doInvoke(routes.clj:67)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329.invoke(core.clj:200)
	at compojure.core$make_context$handler__29357.invoke(core.clj:289)
	at compojure.core$make_context$fn__29361.invoke(core.clj:299)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29310.invoke(core.clj:152)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29310.invoke(core.clj:152)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__29310.invoke(core.clj:152)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:199)
	at compojure.core$routes$fn__29329$f__29330$respond_SINGLEQUOTE___29331.invoke(core.clj:197)
	at compojure.core$make_context$fn__29361.invoke(core.clj:300)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329.invoke(core.clj:200)
	at compojure.core$routes$fn__29329$f__29330.invoke(core.clj:198)
	at compojure.core$routes$fn__29329.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__79686.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__79683.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__86297$fn__86298$fn__86299.invoke(log.clj:211)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__86297$fn__86298.invoke(log.clj:203)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:236)
	at toucan.db$_do_with_call_counting.invoke(db.clj:229)
	at metabase.server.middleware.log$log_api_call$fn__86297.invoke(log.clj:202)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__92469.invoke(browser_cookie.clj:38)
	at metabase.server.middleware.security$add_security_headers$fn__64583.invoke(security.clj:149)
	at metabase.server.middleware.json$wrap_json_body$fn__90017.invoke(json.clj:65)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__90035.invoke(json.clj:99)
	at metabase.server.middleware.offset_paging$handle_paging$fn__64607.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__92736.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__92755.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__36688.invoke(misc.clj:59)
	at metabase.server.middleware.session$reset_session_timeout$fn__48336.invoke(session.clj:394)
	at metabase.server.middleware.session$bind_current_user$fn__48319$fn__48320.invoke(session.clj:331)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:310)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:299)
	at metabase.server.middleware.session$bind_current_user$fn__48319.invoke(session.clj:330)
	at metabase.server.middleware.session$wrap_current_user_info$fn__48301.invoke(session.clj:280)
	at metabase.server.middleware.session$wrap_session_id$fn__48285.invoke(session.clj:213)
	at metabase.server.middleware.auth$wrap_api_key$fn__71219.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__92656.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__36671.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__36696.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__92698.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__36699.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__92485.invoke(ssl.clj:48)
	at metabase.server$async_proxy_handler$fn__85093.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by npfitz** [comment]
Update: this also happens when using a dimension that has been Auto Binned
