### ISSUE TITLE
SQL Server driver not loaded in 0.45.0

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#26992]
**Describe the bug**
SQL Server driver not loaded in 0.45.0

When trying to make queries, it errors with `No method in multimethod 'connection-details->spec' for dispatch value: :sqlserver`, but that's because the driver isn't correctly loaded during startup:
```
...
2022-12-06 11:56:28,377 INFO driver.impl :: Initializing driver :sql...
2022-12-06 11:56:28,378 INFO driver.impl :: Initializing driver :sql-jdbc...
2022-12-06 11:56:28,380 INFO driver.impl :: Initializing driver :sqlserver...
2022-12-06 11:56:28,381 INFO plugins.classloader :: Added URL file:/plugins/sqlserver.metabase-driver.jar to classpath
2022-12-06 11:56:28,384 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.sqlserver...
2022-12-06 11:56:28,402 ERROR metabase.task :: Error initializing task :metabase.task.persist-refresh/PersistRefresh
clojure.lang.ExceptionInfo: null {:classloader #object[clojure.lang.DynamicClassLoader 0x7e4a6afd "clojure.lang.DynamicClassLoader@7e4a6afd"], :classpath-urls ("file:/plugins/sqlserver.metabase-driver.jar"), :system-classpath ("metabase-0.45.0.jar")}
	at metabase.plugins.classloader$require_STAR_.invokeStatic(classloader.clj:128)
	at metabase.plugins.classloader$require_STAR_.doInvoke(classloader.clj:112)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at metabase.plugins.classloader$require.invokeStatic(classloader.clj:147)
	at metabase.plugins.classloader$require.invoke(classloader.clj:134)
	at metabase.plugins.init_steps$fn__63005.invokeStatic(init_steps.clj:21)
	at metabase.plugins.init_steps$fn__63005.invoke(init_steps.clj:19)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase.plugins.init_steps$do_init_steps_BANG_.invokeStatic(init_steps.clj:31)
	at metabase.plugins.init_steps$do_init_steps_BANG_.invoke(init_steps.clj:26)
	at metabase.plugins.lazy_loaded_driver$make_initialize_BANG_$fn__77725$fn__77728.invoke(lazy_loaded_driver.clj:54)
	at metabase.plugins.lazy_loaded_driver$make_initialize_BANG_$fn__77725.invoke(lazy_loaded_driver.clj:53)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase.driver.impl$initialize_if_needed_BANG_.invokeStatic(impl.clj:209)
	at metabase.driver.impl$initialize_if_needed_BANG_.invoke(impl.clj:191)
	at metabase.driver$the_initialized_driver.invokeStatic(driver.clj:162)
	at metabase.driver$the_initialized_driver.invoke(driver.clj:158)
	at metabase.driver$dispatch_on_initialized_driver.invokeStatic(driver.clj:170)
	at metabase.driver$dispatch_on_initialized_driver.doInvoke(driver.clj:165)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.driver$fn__33677$fn__33678.invoke(driver.clj:506)
	at clojure.lang.MultiFn.invoke(MultiFn.java:238)
	at metabase.driver.util$features$iter__33808__33812$fn__33813.invoke(util.clj:203)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$reduce1.invokeStatic(core.clj:932)
	at clojure.core$set.invokeStatic(core.clj:4114)
	at clojure.core$set.invoke(core.clj:4106)
	at metabase.driver.util$features.invokeStatic(util.clj:202)
	at metabase.driver.util$features.invoke(util.clj:199)
	at metabase.models.database$post_select.invokeStatic(database.clj:66)
	at metabase.models.database$post_select.invoke(database.clj:62)
	at toucan.models$fn__22973$fn__23040$G__22990__23045.invoke(models.clj:178)
	at toucan.models$do_post_select.invokeStatic(models.clj:350)
	at toucan.models$do_post_select.invoke(models.clj:344)
	at toucan.db$do_post_select$iter__23357__23361$fn__23362.invoke(db.clj:393)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
	at clojure.core$vec.invokeStatic(core.clj:379)
	at clojure.core$vec.invoke(core.clj:369)
	at toucan.db$do_post_select.invokeStatic(db.clj:392)
	at toucan.db$do_post_select.invoke(db.clj:383)
	at toucan.db$simple_select.invokeStatic(db.clj:414)
	at toucan.db$simple_select.invoke(db.clj:403)
	at toucan.db$select.invokeStatic(db.clj:708)
	at toucan.db$select.doInvoke(db.clj:702)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.task.persist_refresh$reschedule_refresh_BANG_.invokeStatic(persist_refresh.clj:415)
	at metabase.task.persist_refresh$reschedule_refresh_BANG_.invoke(persist_refresh.clj:411)
	at metabase.task.persist_refresh$fn__63799.invokeStatic(persist_refresh.clj:449)
	at metabase.task.persist_refresh$fn__63799.invoke(persist_refresh.clj:446)
	at metabase.task$init_tasks_BANG_$fn__63343.invoke(task.clj:79)
	at metabase.task$init_tasks_BANG_.invokeStatic(task.clj:75)
	at metabase.task$init_tasks_BANG_.invoke(task.clj:71)
	at metabase.task$init_scheduler_BANG_.invokeStatic(task.clj:156)
	at metabase.task$init_scheduler_BANG_.invoke(task.clj:144)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:115)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:87)
	at metabase.core$init_BANG_.invokeStatic(core.clj:144)
	at metabase.core$init_BANG_.invoke(core.clj:139)
	at metabase.core$start_normally.invokeStatic(core.clj:156)
	at metabase.core$start_normally.invoke(core.clj:150)
	at metabase.core$_main.invokeStatic(core.clj:189)
	at metabase.core$_main.doInvoke(core.clj:183)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:23)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:20)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.bootstrap.main(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at clojure.lang.RT.classForName(RT.java:2209)
	at clojure.lang.RT.classForName(RT.java:2218)
	at clojure.lang.RT.loadClassForName(RT.java:2237)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.plugins.classloader$require_STAR_.invokeStatic(classloader.clj:126)
	... 79 more
Caused by: java.io.FileNotFoundException: Could not locate clojure/data/xml__init.class, clojure/data/xml.clj or clojure/data/xml.cljc on classpath.
	at clojure.lang.RT.load(RT.java:462)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:3894)
	at metabase.driver.sqlserver$loading__6789__auto____93263.invoke(sqlserver.clj:1)
	at metabase.driver.sqlserver__init.load(Unknown Source)
	at metabase.driver.sqlserver__init.<clinit>(Unknown Source)
	... 107 more
2022-12-06 11:56:28,438 INFO metabase.task :: Initializing task CheckForNewVersions 📆
2022-12-06 11:56:28,475 INFO metabase.task :: Initializing task PersistPrune 📆
...
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
If anyone needs a quick solution, then download https://github.com/metabase/metabase/suites/9698084235/artifacts/464749269 (requires logged in via GitHub), which is the build including the fix. Unzip, get the JAR file and use that instead.

This will be part of 45.1 coming soon (a day or so).

**Comment by ifurnas** [comment]
> If anyone needs a quick solution, then download https://github.com/metabase/metabase/suites/9698084235/artifacts/464749269 (requires logged in via GitHub), which is the build including the fix. Unzip, get the JAR file and use that instead.
> 
> This will be part of 45.1 coming soon (a day or so).

Solved my issue! Thanks.
