### ISSUE TITLE
Heroku - Metabase not connecting to its own Postgres server via SSL

### ISSUE THREAD

**Issue by crazydog115** [metabase/metabase#2700]
Using Metabase 0.17.1 on Heroku. 

I upgraded my database from a Hobby DB to a Standard DB. The Standard DB requires SSL connections, but when Metabase tries to connect to the Standard DB:

```
2016-06-06T15:58:36Z app[postgres.207]: [JADE] no pg_hba.conf entry for host "METABASE_WEB_IP", user "USERNAME", database "DB_NAME", SSL off
2016-06-06T15:58:36.060291+00:00 app[web.1]: 06-06 15:58:36 INFO metabase.db :: Verifying Database Connection ...
2016-06-06T15:58:36.117055+00:00 app[web.1]: 06-06 15:58:36 ERROR metabase.driver :: Failed to connect to database: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "METABASE_WEB_IP", user "USERNAME", database "DB_NAME", SSL off
2016-06-06T15:58:36.117656+00:00 app[web.1]: java.lang.AssertionError: Assert failed: Unable to connect to Metabase DB.
2016-06-06T15:58:36.117687+00:00 app[web.1]: (binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
2016-06-06T15:58:36.117941+00:00 app[web.1]: 	at metabase.db$verify_db_connection.invokeStatic(db.clj:148)
2016-06-06T15:58:36.118003+00:00 app[web.1]: 	at metabase.db$verify_db_connection.invoke(db.clj:143)
2016-06-06T15:58:36.118037+00:00 app[web.1]: 	at metabase.db$setup_db.invokeStatic(db.clj:162)
2016-06-06T15:58:36.118069+00:00 app[web.1]: 	at metabase.db$setup_db.doInvoke(db.clj:154)
2016-06-06T15:58:36.118127+00:00 app[web.1]: 	at clojure.lang.RestFn.invoke(RestFn.java:421)
2016-06-06T15:58:36.118174+00:00 app[web.1]: 	at metabase.core$init_BANG_.invokeStatic(core.clj:129)
2016-06-06T15:58:36.118230+00:00 app[web.1]: 	at metabase.core$init_BANG_.invoke(core.clj:113)
2016-06-06T15:58:36.118279+00:00 app[web.1]: 	at metabase.core$start_normally.invokeStatic(core.clj:213)
2016-06-06T15:58:36.118347+00:00 app[web.1]: 	at metabase.core$start_normally.invoke(core.clj:207)
2016-06-06T15:58:36.118398+00:00 app[web.1]: 	at metabase.core$_main.invokeStatic(core.clj:247)
2016-06-06T15:58:36.118451+00:00 app[web.1]: 	at metabase.core$_main.doInvoke(core.clj:242)
2016-06-06T15:58:36.118504+00:00 app[web.1]: 	at clojure.lang.RestFn.invoke(RestFn.java:397)
2016-06-06T15:58:36.118561+00:00 app[web.1]: 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
2016-06-06T15:58:36.118622+00:00 app[web.1]: 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
2016-06-06T15:58:36.118676+00:00 app[web.1]: 	at metabase.core.main(Unknown Source)
2016-06-06T15:58:36.118856+00:00 app[web.1]: 06-06 15:58:36 ERROR metabase.core :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase DB.
2016-06-06T15:58:36.118858+00:00 app[web.1]: (binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
2016-06-06T15:58:36.126901+00:00 app[web.1]: 06-06 15:58:36 INFO metabase.core :: Metabase Shutting Down ...
2016-06-06T15:58:36.127531+00:00 app[web.1]: 06-06 15:58:36 INFO metabase.core :: Metabase Shutdown COMPLETE
```

Is there a way to force Metabase to connect to it's own data DB using SSL?

**Comment by crazydog115** [comment]
Whoops. Duplicate of #2616
