### ISSUE TITLE
Running out of memory on Heroku

### ISSUE THREAD

**Issue by crazydog115** [metabase/metabase#2704]
Metabase 0.17.1 on Heroku

After reviewing https://github.com/metabase/metabase/issues/1317 it looks like this shouldn't be an issue, but

![image](https://cloud.githubusercontent.com/assets/794237/15830968/ee440954-2bcf-11e6-94f3-b6449ce5bbbc.png)

On a 1x (512MB) Dyno, metabase had a consistent demand of ~600 MB of RAM (Up until ~8:50 on the graph above)
On a 2x (1GB) Dyno, metabase now has a demand of ~1100 MB of RAM

Causing a lot of swapping and consistent R14 errors

![image](https://cloud.githubusercontent.com/assets/794237/15830984/10b1ad66-2bd0-11e6-8dc8-95edbbbe8f18.png)

**Comment by crazydog115** [comment]
I'm using https://github.com/metabase/metabase-deploy. How large is large? Our largest dataset would be no more than 1 million rows, and it's extremely unlikely we've actually run any queries that large.

**Comment by crazydog115** [comment]
This hasn't happened since upgrading to v 0.18. There hasn't been heavy usage since the upgrade, but I'll close this for now and reopen if the issue reoccurs.

**Comment by AndrewMagliozzi** [comment]
I'm having this exact issue too.

I have been running v0.18.  Upgrading to v0.19.3 now to hopefully fix it.

**Comment by salsakran** [comment]
Let us know if it doesn't.

**Comment by AndrewMagliozzi** [comment]
Bummer... it didn't work.  I keep getting this:

```
2016-08-22T18:32:40.060159+00:00 heroku[web.1]: State changed from starting to up
2016-08-22T18:32:43.115023+00:00 app[web.1]: 08-22 18:32:43 [1mDEBUG metabase.driver[0m :: Registered driver [34m:bigquery[0m 🚚
2016-08-22T18:32:43.142373+00:00 app[web.1]: 08-22 18:32:43 [1mDEBUG metabase.driver[0m :: Registered driver [34m:crate[0m 🚚
2016-08-22T18:32:43.246807+00:00 app[web.1]: 08-22 18:32:43 [1mDEBUG metabase.driver[0m :: Registered driver [34m:druid[0m 🚚
2016-08-22T18:32:43.275957+00:00 app[web.1]: 08-22 18:32:43 [1mDEBUG metabase.driver[0m :: Registered driver [34m:h2[0m 🚚
2016-08-22T18:32:43.683030+00:00 app[web.1]: 08-22 18:32:43 [1mDEBUG metabase.driver[0m :: Registered driver [34m:mongo[0m 🚚
2016-08-22T18:32:43.703527+00:00 app[web.1]: 08-22 18:32:43 [1mDEBUG metabase.driver[0m :: Registered driver [34m:mysql[0m 🚚
2016-08-22T18:32:43.724884+00:00 app[web.1]: 08-22 18:32:43 [1mDEBUG metabase.driver[0m :: Registered driver [34m:postgres[0m 🚚
2016-08-22T18:32:43.773575+00:00 app[web.1]: 08-22 18:32:43 [1mDEBUG metabase.driver[0m :: Registered driver [34m:sqlserver[0m 🚚
2016-08-22T18:32:44.656851+00:00 app[web.1]: 08-22 18:32:44 [1mINFO metabase.db[0m :: [36mVerifying postgres Database Connection ...[0m
2016-08-22T18:32:45.089324+00:00 app[web.1]: 08-22 18:32:45 [1mINFO metabase.db[0m :: Verify Database Connection ... ✅
2016-08-22T18:33:29.443242+00:00 app[web.1]: 08-22 18:33:29 [1mERROR liquibase[0m :: migrations/liquibase.json: migrations/038_getting_started_guide.yaml::38::camsaul: Change Set migrations/038_getting_started_guide.yaml::38::camsaul failed.  Error: ERROR: column "points_of_interest" of relation "metabase_database" already exists [Failed SQL: ALTER TABLE public.metabase_database ADD points_of_interest TEXT]
2016-08-22T18:33:29.449427+00:00 app[web.1]: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/038_getting_started_guide.yaml::38::camsaul:
2016-08-22T18:33:29.450098+00:00 app[web.1]: 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:605)
2016-08-22T18:33:29.450561+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
2016-08-22T18:33:29.450755+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
2016-08-22T18:33:29.451147+00:00 app[web.1]: 	at metabase.core$init_BANG_.invokeStatic(core.clj:142)
2016-08-22T18:33:29.452237+00:00 app[web.1]: 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1255)
2016-08-22T18:33:29.453307+00:00 app[web.1]: 08-22 18:33:29 [1mERROR metabase.core[0m :: Metabase Initialization FAILED:  Migration failed for change set migrations/038_getting_started_guide.yaml::38::camsaul:
2016-08-22T18:33:29.978334+00:00 heroku[web.1]: Process exited with status 1
2016-08-22T18:33:29.995695+00:00 heroku[web.1]: State changed from up to crashed
```
