### ISSUE TITLE
"Cannot read properties of null (reading 'offsetTop')" when using click behavior

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#27356]
Repro:
1) create 2 dashboards
2) add a card to one dashboard (e.g. select sum of total from orders).
3) add a click behavior of the card to send the click to the second dashboard, save it
4) now click the card, go back (with browser back button, not navigating via Metabase) and click again on the card to trigger the click behavior:
![image](https://user-images.githubusercontent.com/1711649/208758807-28fb11da-f803-4305-93e6-452c67b0b95b.png)

https://github.com/metabase/metabase/blob/3954b9e1509efb4e21bbfae2696c6a0f14f45d1b/frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js#L27

Backend Logs:
none

Frontend Logs:
react-dom.production.min.js:209 TypeError: Cannot read properties of null (reading 'offsetTop')
    at JP (stickyParameters.js:27:64)
    at stickyParameters.js:6:3
    at l.<anonymous> (Dashboard.jsx:113:11)
    at l [as throttleParameterWidgetStickiness] (throttle.js:32:21)
    at l.value (Dashboard.jsx:133:12)
    at us (react-dom.production.min.js:212:231)
    at Oc (react-dom.production.min.js:255:229)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Yi (react-dom.production.min.js:122:325)
    at yc (react-dom.production.min.js:248:370)
os @ react-dom.production.min.js:209

**Comment by flamber** [comment]
Regression since 0.45.0.

Workaround is add a mock filter to the other dashboard.

Reproduce:
1. Create two dashboards, D1 and D2
2. Add a filter to D1
3. Bookmark both dashboards
4. Click back and forth between the bookmarks

https://user-images.githubusercontent.com/1447303/208902959-2d576d35-5fa4-49fa-a80b-13f2b0935c2e.mp4

**Comment by bunnymatt** [comment]
For the workaround, what is a mock filter?

**Comment by flamber** [comment]
@bunnymatt Add a filter to all dashboards. Doesn't even need to be connected to anything, there just has to be filters on all.
