### ISSUE TITLE
Not able to connect to MongoDB

### ISSUE THREAD

**Issue by romanzdk** [metabase/metabase#27896]
**Describe the bug**
I cannot connect to MongoDB

**Logs**
```
at ring.middleware.keyword_params$wrap_keyword_params$fn__83880.invoke(keyword_params.clj:55)                                                       │
│     at ring.middleware.params$wrap_params$fn__83899.invoke(params.clj:77)                                                                               │
│     at metabase.server.middleware.misc$maybe_set_site_url$fn__35750.invoke(misc.clj:59)                                                                 │
│     at metabase.server.middleware.session$reset_session_timeout$fn__47441.invoke(session.clj:377)                                                       │
│     at metabase.server.middleware.session$bind_current_user$fn__47424$fn__47425.invoke(session.clj:313)                                                 │
│     at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:292)                                                            │
│     at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:281)                                                                  │
│     at metabase.server.middleware.session$bind_current_user$fn__47424.invoke(session.clj:312)                                                           │
│     at metabase.server.middleware.session$wrap_current_user_info$fn__47406.invoke(session.clj:262)                                                      │
│     at metabase.server.middleware.session$wrap_session_id$fn__47390.invoke(session.clj:195)                                                             │
│     at metabase.server.middleware.auth$wrap_api_key$fn__68929.invoke(auth.clj:27)                                                                       ││     at ring.middleware.cookies$wrap_cookies$fn__83800.invoke(cookies.clj:216)                                                                           │
│     at metabase.server.middleware.misc$add_content_type$fn__35733.invoke(misc.clj:27)                                                                   ││     at metabase.server.middleware.misc$disable_streaming_buffering$fn__35758.invoke(misc.clj:76)                                                        │
│     at ring.middleware.gzip$wrap_gzip$fn__83842.invoke(gzip.clj:86)                                                                                     ││     at metabase.server.middleware.misc$bind_request$fn__35761.invoke(misc.clj:93)                                                                       │
│     at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__83629.invoke(ssl.clj:48)                                                         ││     at metabase.server$async_proxy_handler$fn__80284.invoke(server.clj:73)                                                                              │
│     at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)                                           ││     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)                                                                  │
│     at org.eclipse.jetty.server.Server.handle(Server.java:516)                                                                                          │
│     at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)                                                                       │        7162MB/31GB [||        ] 21.5%
│     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)                                                                              │
│     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)                                                                                │
│     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)                                                                      │
│     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)                                                      │
│     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)                                                                                │
│     at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)                                                                             │
│     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)                                                           │
│     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)                                                         │
│     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)                                                        │
│     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)                                                               │
│     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)                                         │
│     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)                                                                 │
│     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)                                                            │
│     at java.base/java.lang.Thread.run(Unknown Source)                                                                                                   │
│ Caused by: java.util.concurrent.TimeoutException: Timed out after 10.0 s                                                                                │
│     at metabase.util$deref_with_timeout.invokeStatic(util.clj:332)                                                                                      │
│     at metabase.util$deref_with_timeout.invoke(util.clj:324)                                                                                            │
│     at metabase.util$do_with_timeout.invokeStatic(util.clj:339)                                                                                         │
│     at metabase.util$do_with_timeout.invoke(util.clj:335)                                                                                               │
│     at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:137)                                                                  │
│     ... 123 more                                                                                                                                        │
│ 2023-01-26 14:53:42,310 DEBUG middleware.log :: POST /api/database 400 10.0 s (0 DB calls)                                                              │
│ {:message "Timed out after 10.0 s"} 
```

**Information about your Metabase Installation:**

- Metabase version: 0.44.3
- Metabase hosting environment: Docker container on Kubernetes
- Metabase internal database: Postgres
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.16+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.16",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.16+8",
    "os.name": "Linux",
    "os.version": "5.4.0-136-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.5 (Debian 14.5-2.pgdg110+2)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.4.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-06-13",
      "tag": "v0.44.4-SNAPSHOT",
      "branch": "?",
      "hash": "9d97b8f"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

**Severity**
blocking - cannot use the database inside metabase

**Comment by paoliniluis** [comment]
This is more a question for our Discourse forum rather than for the issue tracker. Please post on https://discourse.metabase.com/
