### ISSUE TITLE
Truncated incorrect DOUBLE value when creating table for model

### ISSUE THREAD

**Issue by markbastian** [metabase/metabase#27901]
As reported [here](https://github.com/metabase/metabase/issues/25552#issuecomment-1402484181), when a table was being created for a model the error  `Truncated incorrect DOUBLE value` was being reported.

```
2023-01-24 19:28:00,017 INFO task.persist-refresh :: Attempting to refresh persisted model 23.
2023-01-24 19:28:00,122 WARN mysql.ddl :: #error {
 :cause Truncated incorrect DOUBLE value: '15 day'
 :via
 [{:type java.sql.SQLSyntaxErrorException
   :message (conn=8749356) Truncated incorrect DOUBLE value: '15 day'
   :at [org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory createException ExceptionFactory.java 62]}
  {:type org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException
   :message Truncated incorrect DOUBLE value: '15 day'
   :at [org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException of MariaDbSqlException.java 34]}
  {:type java.sql.SQLException
   :message Truncated incorrect DOUBLE value: '15 day'
   :at [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readErrorPacket AbstractQueryProtocol.java 1695]}]
 :trace
 [[org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readErrorPacket AbstractQueryProtocol.java 1695]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol readPacket AbstractQueryProtocol.java 1557]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol getResult AbstractQueryProtocol.java 1520]
  [org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol executeQuery AbstractQueryProtocol.java 318]
  [org.mariadb.jdbc.ClientSidePreparedStatement executeInternal ClientSidePreparedStatement.java 220]
  [org.mariadb.jdbc.ClientSidePreparedStatement execute ClientSidePreparedStatement.java 149]
  [org.mariadb.jdbc.ClientSidePreparedStatement executeQuery ClientSidePreparedStatement.java 163]
  [com.mchange.v2.c3p0.impl.NewProxyPreparedStatement executeQuery NewProxyPreparedStatement.java 1471]
  [clojure.java.jdbc$execute_query_with_params invokeStatic jdbc.clj 1090]
  [clojure.java.jdbc$execute_query_with_params invoke jdbc.clj 1084]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invokeStatic jdbc.clj 1106]
  [clojure.java.jdbc$db_query_with_resultset_STAR_ invoke jdbc.clj 1093]
  [clojure.java.jdbc$query invokeStatic jdbc.clj 1182]
  [clojure.java.jdbc$query invoke jdbc.clj 1144]
  [clojure.java.jdbc$query invokeStatic jdbc.clj 1160]
  [clojure.java.jdbc$query invoke jdbc.clj 1144]
  [metabase.driver.sql.ddl$jdbc_query invokeStatic ddl.clj 23]
  [metabase.driver.sql.ddl$jdbc_query invoke ddl.clj 20]
  [metabase.driver.mysql.ddl$exec_async$fn__86279$fn__86283 invoke ddl.clj 21]
  [metabase.driver.mysql.ddl$exec_async$fn__86279 invoke ddl.clj 17]
  [clojure.core.async$thread_call$fn__17324 invoke async.clj 484]
  [clojure.lang.AFn run AFn.java 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker nil -1]
  [java.util.concurrent.ThreadPoolExecutor$Worker run nil -1]
  [java.lang.Thread run nil -1]]}
Exception in thread "async-thread-macro-221" java.sql.SQLSyntaxErrorException: (conn=8749356) Truncated incorrect DOUBLE value: '15 day'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1106)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at metabase.driver.sql.ddl$jdbc_query.invokeStatic(ddl.clj:23)
	at metabase.driver.sql.ddl$jdbc_query.invoke(ddl.clj:20)
	at metabase.driver.mysql.ddl$exec_async$fn__86279$fn__86283.invoke(ddl.clj:21)
	at metabase.driver.mysql.ddl$exec_async$fn__86279.invoke(ddl.clj:17)
	at clojure.core.async$thread_call$fn__17324.invoke(async.clj:484)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Truncated incorrect DOUBLE value: '15 day'
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 20 more
Caused by: java.sql.SQLException: Truncated incorrect DOUBLE value: '15 day'
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1695)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1557)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1520)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
	... 21 more
2023-01-24 19:28:00,139 INFO task.persist-refresh :: Finished persisted model refresh task for Database 2 with 1 successes and 0 errors.
```

**Comment by markbastian** [comment]
Related search results:
* [Truncated incorrect DOUBLE value](https://bugs.mysql.com/bug.php?id=63112) bug in MySQL
* [S/O Q&A](https://stackoverflow.com/questions/16068993/error-code-1292-truncated-incorrect-double-value-mysql)
I suspect there might a weird table name or column name that MySQL is promoting to double in a comparison.

**Comment by Vextil** [comment]
Thanks for creating the issue, providing some additional details as requested.

The "Truncated incorrect DOUBLE" is actually an error with my query when combined with the insert Metabase does into a cache table, but this error is not being shown and the model stops loading after trying to create the cache table and failing.

I can replicate that type of error like this:
```SQL
create table prices (price VARCHAR(255));
insert into prices values ('10.00'), ('12.00'), ('20.22'), ('error');
select * from prices where price > 15; #Works fine because of implicit casting
create table prices_cache as select * from prices where price > 15; #This throws the error
```

While this can be fixed by changing the select, it can be easily missed because when creating the model in the UI we only run the select `select * from prices where price > 15;` and as we are not using the result of the query to insert into a table, everything works properly.
After some time when the cache cron runs and attempts to insert these results into a table, the error above is shown in the logs but the process is still marked as successful and the model breaks and can't be loaded anymore.

**Comment by dpsutton** [comment]
@Vextil that is super helpful.

Seems like we have two distinct issues here:
- the model is marked as correctly persisted despite an error in persisting. The persistence should be in an error state so that any queries against the model do not use the substituted cached query. This is high priority
- We need a safer way to create the cache table in mysql. I'll have to think about what to do here but we can certainly make sure that caches which are not correctly created are never used.

**Comment by dpsutton** [comment]
Thinking on it a bit more, I think this is an excellent use case of models.

The raw data:

```sql
create table prices (price VARCHAR(255));
insert into prices values ('10.00'), ('12.00'), ('20.22'), ('error');

mysql> select * from prices;
+-------+
| price |
+-------+
| 10.00 |
| 12.00 |
| 20.22 |
| error |
+-------+
4 rows in set (0.00 sec)
```

A great use of a model could be to add types to this raw data and remove error rows.

If you define the model as below:

```sql
mysql> select convert(price, decimal) from prices where price != "error";
+-------------------------+
| convert(price, decimal) |
+-------------------------+
|                      10 |
|                      12 |
|                      20 |
+-------------------------+
3 rows in set (0.00 sec)
```
It seems this will cache correctly.

```sql
mysql> create table prices_cache as select convert(price, decimal) from prices where price != "error";
Query OK, 3 rows affected (0.02 sec)
Records: 3  Duplicates: 0  Warnings: 0
```
Alternatively, if you want to keep the error information in your model,

```sql
mysql> create table prices_cache2 as select CASE when price = "error" then 0.0 ELSE convert(price, decimal) END as price, price = "error" as error from prices;
Query OK, 4 rows affected (0.02 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> select * from prices_cache2;
+-------+-------+
| price | error |
+-------+-------+
|  10.0 |     0 |
|  12.0 |     0 |
|  20.0 |     0 |
|   0.0 |     1 |
+-------+-------+
4 rows in set (0.00 sec)
```

I know this is extra work. Perhaps this workaround works for you right now. It's tough to think of a good solution in the face of mysql's casting rules and non-homogeneous data.

**Comment by Vextil** [comment]
Thank you @dpsutton! We have implemented a similar workaround and got it working, just thought it could save someone else with the same issue some research time if the error on table creation was exposed in the UI somehow.
