### ISSUE TITLE
Metabase detects renaming of property, when  jsonb with properties with different case is used

### ISSUE THREAD

**Issue by g-w** [metabase/metabase#28100]
**Describe the bug**

If a table has a `jsonb` column with two properties, which names only differ in the case, metabase detects a column rename and tries to rename the first to the second column. This operations fails on the database layer with a constraint violation error.

**Logs**
```
[a0dec2d5-d137-45ea-9251-bcfa20a1acee] 2023-02-06T18:05:22+01:00 INFO metabase.sync.sync-metadata.fields.sync-metadata Name von Tabelle 9 'public.rows' Feld 'j → testID' wurde von 'j → testID' in 'j → testId' geändert.
[a0dec2d5-d137-45ea-9251-bcfa20a1acee] 2023-02-06T18:05:22+01:00 WARN metabase.sync.util Fehler beim Synchronisieren der Felder für Tabelle "Tabelle 9 'public.rows'"
java.sql.BatchUpdateException: Batch entry 0 UPDATE "metabase_field" SET "name" = 'j → testId', "updated_at" = now() WHERE "id" = 74 was aborted: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(9, j → testId) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:52)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2544)
	at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:591)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__21573.invoke(jdbc.clj:1057)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1056)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1042)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1080)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1060)
	at clojure.java.jdbc$execute_BANG_$execute_helper__21641.invoke(jdbc.clj:1464)
	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1468)
	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1435)
	at toucan.db$execute_BANG_.invokeStatic(db.clj:447)
	at toucan.db$execute_BANG_.doInvoke(db.clj:442)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$update_BANG_.invokeStatic(db.clj:526)
	at toucan.db$update_BANG_.invoke(db.clj:515)
	at toucan.db$update_BANG_.invokeStatic(db.clj:535)
	at toucan.db$update_BANG_.invoke(db.clj:515)
	at metabase.sync.sync_metadata.fields.sync_metadata$fn__68330$update_field_metadata_if_needed_BANG___68335$fn__68336.invoke(sync_metadata.clj:107)
	at metabase.sync.sync_metadata.fields.sync_metadata$fn__68330$update_field_metadata_if_needed_BANG___68335.invoke(sync_metadata.clj:17)
	at metabase.sync.sync_metadata.fields.sync_metadata$fn__68393$update_metadata_BANG___68398$fn__68399$iter__68400__68404$fn__68405.invoke(sync_metadata.clj:132)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6882)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.sync.util$sum_for_STAR_.invokeStatic(util.clj:521)
	at metabase.sync.util$sum_for_STAR_.invoke(util.clj:518)
	at metabase.sync.sync_metadata.fields.sync_metadata$fn__68393$update_metadata_BANG___68398$fn__68399.invoke(sync_metadata.clj:128)
	at metabase.sync.sync_metadata.fields.sync_metadata$fn__68393$update_metadata_BANG___68398.invoke(sync_metadata.clj:122)
	at metabase.sync.sync_metadata.fields$fn__68437$sync_and_update_BANG___68442$fn__68443.invoke(fields.clj:63)
	at metabase.sync.sync_metadata.fields$fn__68437$sync_and_update_BANG___68442.invoke(fields.clj:55)
	at metabase.sync.sync_metadata.fields$fn__68465$sync_fields_for_table_BANG___68474$fn__68477$fn__68478.invoke(fields.clj:74)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:160)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:153)
	at metabase.sync.sync_metadata.fields$fn__68465$sync_fields_for_table_BANG___68474$fn__68477.invoke(fields.clj:71)
	at metabase.sync.sync_metadata.fields$fn__68465$sync_fields_for_table_BANG___68474.invoke(fields.clj:65)
	at clojure.core$partial$fn__5908.invoke(core.clj:2641)
	at clojure.core$map$fn__5935.invoke(core.clj:2770)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1790)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.sync_metadata.fields$fn__68503$sync_fields_BANG___68508$fn__68509.invoke(fields.clj:85)
	at metabase.sync.sync_metadata.fields$fn__68503$sync_fields_BANG___68508.invoke(fields.clj:77)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$fn__42851$run_step_with_metadata__42856$fn__42860$fn__42862.doInvoke(util.clj:388)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:119)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:116)
	at metabase.sync.util$fn__42851$run_step_with_metadata__42856$fn__42860.invoke(util.clj:383)
	at metabase.sync.util$fn__42851$run_step_with_metadata__42856.invoke(util.clj:378)
	at metabase.sync.util$fn__43072$run_sync_operation__43077$fn__43078$fn__43086.invoke(util.clj:495)
	at metabase.sync.util$fn__43072$run_sync_operation__43077$fn__43078.invoke(util.clj:493)
	at metabase.sync.util$fn__43072$run_sync_operation__43077.invoke(util.clj:487)
	at metabase.sync.sync_metadata$fn__70113$sync_db_metadata_BANG___70118$fn__70119$fn__70120.invoke(sync_metadata.clj:52)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:160)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:153)
	at clojure.core$partial$fn__5910.invoke(core.clj:2647)
	at metabase.driver$fn__33725.invokeStatic(driver.clj:626)
	at metabase.driver$fn__33725.invoke(driver.clj:626)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__42772.invoke(util.clj:138)
	at metabase.sync.util$with_db_logging_disabled$fn__42769.invoke(util.clj:129)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_logging$fn__42758.invoke(util.clj:114)
	at metabase.sync.util$with_sync_events$fn__42753.invoke(util.clj:88)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__42744.invoke(util.clj:67)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:181)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:178)
	at metabase.sync.sync_metadata$fn__70113$sync_db_metadata_BANG___70118$fn__70119.invoke(sync_metadata.clj:51)
	at metabase.sync.sync_metadata$fn__70113$sync_db_metadata_BANG___70118.invoke(sync_metadata.clj:47)
	at metabase.sync$fn__70170$sync_database_BANG___70179$fn__70185$fn__70187$fn__70189.invoke(sync.clj:45)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__8244.invokeStatic(protocols.clj:136)
	at clojure.core.protocols$fn__8244.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at metabase.sync$fn__70170$sync_database_BANG___70179$fn__70185$fn__70187.invoke(sync.clj:45)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:160)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:153)
	at clojure.core$partial$fn__5910.invoke(core.clj:2647)
	at metabase.driver$fn__33725.invokeStatic(driver.clj:626)
	at metabase.driver$fn__33725.invoke(driver.clj:626)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__42772.invoke(util.clj:138)
	at metabase.sync.util$with_db_logging_disabled$fn__42769.invoke(util.clj:129)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:102)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:96)
	at metabase.sync.util$with_start_and_finish_logging$fn__42758.invoke(util.clj:114)
	at metabase.sync.util$with_sync_events$fn__42753.invoke(util.clj:88)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__42744.invoke(util.clj:67)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:181)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:178)
	at metabase.sync$fn__70170$sync_database_BANG___70179$fn__70185.invoke(sync.clj:44)
	at metabase.sync$fn__70170$sync_database_BANG___70179.invoke(sync.clj:30)
	at metabase.sync$fn__70170$sync_database_BANG___70179$fn__70180.invoke(sync.clj:40)
	at metabase.sync$fn__70170$sync_database_BANG___70179.invoke(sync.clj:30)
	at metabase.events.sync_database$process_sync_database_event$fn__86845.invoke(sync_database.clj:38)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(9, j → testId) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	... 144 more
```

**To Reproduce**

* Create a postgres database `data`
* Create a table `create table rows (j jsonb);`
* Insert two records `insert into rows (j) values ('{"testID": "value"}'), ('{"testId": "value"}');`
* Trigger synchronization

**Expected behavior**

No exception. No database error.

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "de-DE",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "6.1.8-200.fc37.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.6 (Debian 14.6-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-01-27",
      "tag": "v0.45.2.1",
      "branch": "release-x.45.2.x",
      "hash": "1a59de7"
    },
    "settings": {
      "report-timezone": null
    }
  }
}```

**Comment by paoliniluis** [comment]
I think your issue is the same as https://github.com/metabase/metabase/issues/17387 but this time is with json fields, so I'm closing this one
