### ISSUE TITLE
Missing custom field metadata on a card breaks the frontend on the Notebook view

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#28221]
**Describe the bug**
A customer cannot upgrade to v45 as we seem to blow up the FE on this specific check:
https://github.com/metabase/metabase/blob/07c91cd608860798442667074979f514a317b182/frontend/src/metabase-lib/Dimension.ts#L1257

We should be doing the following:
1) the usual if (type && type.startsWith()) to check if the object has a key first
2) log which field is the offender, so we can easily debug this

If you were wondering how did we get here, I think it's due to old MBQL

**Logs**
Old and usual:
```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at n.value (Dimension.ts:1257:15)
    at s (StructuredQuery.ts:1261:51)
    at Array.filter (<anonymous>)
    at n.value (StructuredQuery.ts:1273:46)
    at i.value (Join.ts:668:44)
    at JoinStep.jsx:94:43
    at Function.en (every.js:12:10)
    at UF (JoinStep.jsx:94:17)
    at Qo (react-dom.production.min.js:153:146)
    at As (react-dom.production.min.js:261:496)
```

**To Reproduce**
1) create a new question (insert it directly to the DB) with the following:
dataset_query (I think it isn't needed, but just in case):
```
{"database":3,"query":{"source-table":68,"joins":[{"fields":[["field",606,{"join-alias":"BLA1","temporal-unit":"default"}]],"source-table":107,"condition":["=",["field",637,null],["field",598,{"join-alias":"BLA1"}]],"alias":"BLA1"},{"fields":[["field",625,{"join-alias":"BLA2"}]],"source-table":108,"condition":["=",["field",637,null],["field",615,{"join-alias":"BLA2"}]],"alias":"BLA2"},{"fields":[["field",591,{"join-alias":"BLA3"}]],"source-table":106,"condition":["=",["field",637,null],["field",581,{"join-alias":"BLA3"}]],"alias":"BLA3"},{"fields":[["field",565,{"join-alias":"BLA4"}],["field",569,{"join-alias":"BLA4"}]],"source-table":110,"condition":["=",["field",637,null],["field",564,{"join-alias":"BLA4"}]],"alias":"BLA4"},{"source-table":"card__4744","condition":["=",["field",503,null],["field",683,{"join-alias":"Question 4744_2"}]],"alias":"Question 4744_2","fields":"none"},{"source-table":"card__4767","condition":["=",["field",503,null],["field",683,{"join-alias":"Question 4767"}]],"alias":"Question 4767","fields":"none"},{"source-table":"card__4755","condition":["=",["field",503,null],["field",683,{"join-alias":"Question 4755"}]],"alias":"Question 4755","fields":"none"}],"filter":["and",["is-null",["field",501,null]],["=",["field",639,null],"BLA5"]],"expressions":{"EXP1 ":["field",648,{"join-alias":"Question 4744_2"}],"EXP2":["field",648,{"join-alias":"Question 4755"}],"EXP3":["field",648,{"join-alias":"Question 4767"}]},"fields":[["field",503,null],["field",527,null],["field",526,null],["expression","EXP1 "],["expression","EXP2"],["expression","EXP3"]]},"type":"query"}
```

result_metadata
```
[{"description":null,"semantic_type":null,"coercion_strategy":null,"name":"slug","settings":null,"field_ref":["field",503,null],"effective_type":"type/Text","id":503,"visibility_type":"normal","display_name":"Slug","fingerprint":{"global":{"distinct-count":213,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":10.0}}},"base_type":"type/Text"},{"description":null,"semantic_type":"type/Title","coercion_strategy":null,"name":"form_title","settings":null,"field_ref":["field",527,null],"effective_type":"type/Text","id":527,"visibility_type":"normal","display_name":"Form Title","fingerprint":{"global":{"distinct-count":28,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":14.914893617021276}}},"base_type":"type/Text"},{"description":null,"semantic_type":"type/Category","coercion_strategy":null,"name":"submission_status_name","settings":null,"field_ref":["field",526,null],"effective_type":"type/Text","id":526,"visibility_type":"normal","display_name":"ABC6","fingerprint":{"global":{"distinct-count":4,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":5.313069908814589}}},"base_type":"type/Text"},{"description":null,"semantic_type":null,"coercion_strategy":null,"name":"AAAA ","settings":null,"field_ref":["expression","Supervisor Follow-up - Severity "],"effective_type":"type/Text","id":648,"visibility_type":"normal","display_name":"ABC3 ","fingerprint":{"global":{"distinct-count":204,"nil%":0.2074},"type":{"type/Text":{"percent-json":0.0598,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0024,"average-length":23.7222}}},"base_type":"type/Text"},{"description":null,"semantic_type":null,"coercion_strategy":null,"name":"BBBBBB","settings":null,"field_ref":["expression","Med Error MSO Pharmacy Follow Up - Severity"],"effective_type":"type/Text","id":648,"visibility_type":"normal","display_name":"ABC","fingerprint":{"global":{"distinct-count":204,"nil%":0.2074},"type":{"type/Text":{"percent-json":0.0598,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0024,"average-length":23.7222}}},"base_type":"type/Text"},{"description":null,"semantic_type":null,"coercion_strategy":null,"name":"DDDDDDD","settings":null,"field_ref":["expression","Medication Event Sub-type"],"effective_type":"type/Text","id":648,"visibility_type":"normal","display_name":"ABC1","fingerprint":{"global":{"distinct-count":204,"nil%":0.2074},"type":{"type/Text":{"percent-json":0.0598,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0024,"average-length":23.7222}}},"base_type":"type/Text"},{"description":null,"semantic_type":null,"coercion_strategy":null,"unit":"default","name":"date_answer","settings":null,"field_ref":["field",606,{"join-alias":"AFAFAF","temporal-unit":"default"}],"effective_type":"type/Date","id":606,"visibility_type":"normal","display_name":"ABC3","fingerprint":{"global":{"distinct-count":124,"nil%":0.0},"type":{"type/DateTime":{"earliest":"2020-04-05","latest":"2022-10-21"}}},"base_type":"type/Date"},{"description":null,"semantic_type":"type/Category","coercion_strategy":null,"name":"answer","settings":null,"field_ref":["field",625,{"join-alias":"AFCACACA"}],"effective_type":"type/Text","id":625,"visibility_type":"normal","display_name":"ABC2","fingerprint":{"global":{"distinct-count":30,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":51.24324324324324}}},"base_type":"type/Text"},{"description":null,"semantic_type":null,"coercion_strategy":null,"name":"answer_2","settings":null,"field_ref":["field",591,{"join-alias":"FDDFGDF"}],"effective_type":"type/Text","id":591,"visibility_type":"normal","display_name":"ABC4","fingerprint":{"global":{"distinct-count":38,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":19.639344262295083}}},"base_type":"type/Text"},{"description":null,"semantic_type":"type/Category","coercion_strategy":null,"name":"facility_answer","settings":null,"field_ref":["field",565,{"join-alias":"KJGFDF"}],"effective_type":"type/Text","id":565,"visibility_type":"normal","display_name":"ABC5","fingerprint":{"global":{"distinct-count":6,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":14.903225806451612}}},"base_type":"type/Text"},{"description":null,"semantic_type":"type/Category","coercion_strategy":null,"name":"department_answer","settings":null,"field_ref":["field",569,{"join-alias":"HGJFJF"}],"effective_type":"type/Text","id":569,"visibility_type":"normal","display_name":"ABC6","fingerprint":{"global":{"distinct-count":19,"nil%":0.0},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":18.741935483870968}}},"base_type":"type/Text"}]
```

NOTE: all descriptive names and join aliases have been redacted, but you should see the error even with this

2) open the question and then go to the notebook
3) see the FE blowing up
![image](https://user-images.githubusercontent.com/1711649/218141088-6f0b6aa4-c90f-4e8d-a0da-9488b3052d76.png)

**Expected behavior**
Please don't blow up the FE when we don't find a key

**Screenshots**
Above

**Information about your Metabase Installation:**
- Your browser and the version: brave latest
- Your operating system: popos latest
- Your databases: Postgres 15
- Metabase version: 1.45.2.1 (customer reports this didn't happen in 44.6, but I didn't test)
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Severity**
P1 for this customer, might happen with other old customers

**Additional context**
NA

EDIT: seems we don't show the notebook editor if the metabase_table table is not populated, which makes sense? either way, I sent the details on a private message

**Comment by likeshumidity** [comment]
At least one affected customer must rebuild potentially several hundred questions as some of the affected questions that can not be edited are GUI queries of existing questions, so it adds a long dependency chain for them.

Would prefer something like:
- Load what can be loaded without running query if query unable to be run. (Handle the missing expected field.)
- Warning in console log (i.e. something like `failure on x field in y database`) to better identify which question, field, table, etc.

**Comment by WiNloSt** [comment]
[Another repro from our Slack convo](https://metaboat.slack.com/archives/C04DAKFDTCZ/p1676587341387369?thread_ts=1676580677.316819&cid=C04DAKFDTCZ)

**Comment by WiNloSt** [comment]
[This should go into 46](https://metaboat.slack.com/archives/C864UT5CZ/p1677084715371539?thread_ts=1677084170.121889&cid=C864UT5CZ)
