### ISSUE TITLE
Error installing metabase (connecting to mysql)

### ISSUE THREAD

**Issue by cagiraudo** [metabase/metabase#2879]
Hi,

I was using metabase v17.0 for a couple of weeks with H2 database without any problem. 

But suddenly it stop working and i lost all the dashboards and query in the database. So i dicided to move to a mysql database installation, but i am having problem configuring this.

I made this steps.

1 - Create a new database named metabase
2 - Copy the metabase.jar to a folder in my server
3 - Make the enviromental variables:
        export MB_DB_TYPE=mysql
	export MB_DB_DBNAME=metabase
	export MB_DB_PORT=3306
	export MB_DB_USER=xxxx
	export MB_DB_PASS=xxxx
	export MB_DB_HOST=localhost
4 - Running java -jar metabase.jar

And i get the following:

```
07-04 12:34:03 INFO metabase.core :: Starting Metabase in STANDALONE mode
07-04 12:34:03 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

07-04 12:34:03 INFO metabase.core :: Starting Metabase version v0.18.1 (9f3beac release-0.18.1) ...
07-04 12:34:03 INFO metabase.core :: System timezone is 'America/Argentina/Buenos_Aires' ...
07-04 12:34:04 DEBUG metabase.driver :: Registered driver :bigquery 🚚
07-04 12:34:04 DEBUG metabase.driver :: Registered driver :crate 🚚
07-04 12:34:04 DEBUG metabase.driver :: Registered driver :druid 🚚
07-04 12:34:04 DEBUG metabase.driver :: Registered driver :h2 🚚
07-04 12:34:04 DEBUG metabase.driver :: Registered driver :mongo 🚚
07-04 12:34:04 DEBUG metabase.driver :: Registered driver :mysql 🚚
07-04 12:34:04 DEBUG metabase.driver :: Registered driver :postgres 🚚
07-04 12:34:04 DEBUG metabase.driver :: Registered driver :redshift 🚚
07-04 12:34:04 DEBUG metabase.driver :: Registered driver :sqlite 🚚
07-04 12:34:04 DEBUG metabase.driver :: Registered driver :sqlserver 🚚
07-04 12:34:05 INFO metabase.db :: Verifying Database Connection ...
07-04 12:34:05 ERROR metabase.driver :: Failed to connect to database: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
java.lang.AssertionError: Assert failed: Unable to connect to Metabase DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
        at metabase.db$verify_db_connection.invokeStatic(db.clj:160)
        at metabase.db$verify_db_connection.invoke(db.clj:155)
        at metabase.db$setup_db.invokeStatic(db.clj:174)
        at metabase.db$setup_db.doInvoke(db.clj:166)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:130)
        at metabase.core$init_BANG_.invoke(core.clj:114)
        at metabase.core$start_normally.invokeStatic(core.clj:214)
        at metabase.core$start_normally.invoke(core.clj:208)
        at metabase.core$_main.invokeStatic(core.clj:248)
        at metabase.core$_main.doInvoke(core.clj:243)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
07-04 12:34:05 ERROR metabase.core :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
07-04 12:34:05 INFO metabase.core :: Metabase Shutting Down ...
07-04 12:34:05 INFO metabase.core :: Metabase Shutdown COMPLETE
```

I don't know what am i doing wrong. Please help me becouse i was very happy using metabase.

*  I am using the chrome browser.
*  My computer's OS is ubuntu server 14.04.
*  I'm running Metabase locally from the JAR.
*  My database is mysql.
*  My Metabase version is v17 / v18.

**Comment by cagiraudo** [comment]
Nevermind, i had a problem with the environment variables. Now it's working OK

**Comment by salsakran** [comment]
glad it got sorted!

**Comment by gabrsar** [comment]
I was with the same problem. I just changed the localhost to my hostname and it worked.
