### ISSUE TITLE
/api/health/ 503 error on heroku

### ISSUE THREAD

**Issue by kritop** [metabase/metabase#2883]
If this is a bug report, please fill in the blanks:

*  I am using the latest chrome browser.
*  My computer's OS is latest Mac OS.
*  I'm running Metabase on Heroku. [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.]
*  My database is Postgres.
*  My Metabase version is latest.

I am getting constant:

Jul 05 17:04:39 service-metabase app/web.1:  07-05 15:04:38 ERROR metabase.middleware :: GET /api/health 503 (249 µs) 
Jul 05 17:04:39 service-metabase app/web.1:  {:status "initializing", :progress 0.4} 
Jul 05 17:04:39 service-metabase heroku/router:  at=info method=GET path="/api/health" host= request_id=988072e7-ad1c-466a-9592-b5699660d51d fwd="79.250.91.100" dyno=web.1 connect=0ms service=6ms status=503 bytes=414 
Jul 05 17:04:39 service-metabase heroku/router:  at=info method=GET path="/api/health" host= request_id=8fdb1e28-a348-459e-b654-5201f88c901a fwd="79.250.91.100" dyno=web.1 connect=0ms service=12ms status=503 bytes=414 
Jul 05 17:04:39 service-metabase app/web.1:  07-05 15:04:39 ERROR metabase.middleware :: GET /api/health 503 (685 µs) 
Jul 05 17:04:39 service-metabase app/web.1:  {:status "initializing", :progress 0.4} 
Jul 05 17:04:40 service-metabase app/web.1:  07-05 15:04:40 ERROR metabase.middleware :: GET /api/health 503 (234 µs) 
Jul 05 17:04:40 service-metabase app/web.1:  {:status "initializing", :progress 0.4} 
Jul 05 17:04:41 service-metabase app/web.1:  07-05 15:04:40 ERROR metabase.middleware :: GET /api/health 503 (325 µs) 
Jul 05 17:04:41 service-metabase app/web.1:  {:status "initializing", :progress 0.4} 
Jul 05 17:04:42 service-metabase app/web.1:  07-05 15:04:41 ERROR metabase.middleware :: GET /api/health 503 (385 µs) 
Jul 05 17:04:42 service-metabase app/web.1:  {:status "initializing", :progress 0.4}

**Comment by kritop** [comment]
after a while it just crashes with:

Jul 05 17:13:52 service-metabase app/web.1:  Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by f8d21b88-1500-42b3-a024-f3984770b62f.prvt.dyno.rt.heroku.com (172.18.88.166) since 7/5/16 2:46 PM 
Jul 05 17:13:52 service-metabase app/web.1:  	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:190) 
Jul 05 17:13:52 service-metabase app/web.1:  	at liquibase.Liquibase.update(Liquibase.java:196) 
Jul 05 17:13:52 service-metabase app/web.1:  	at liquibase.Liquibase.update(Liquibase.java:192) 
Jul 05 17:13:52 service-metabase app/web.1:  	at liquibase.Liquibase.update(Liquibase.java:188) 
Jul 05 17:13:52 service-metabase app/web.1:  	at liquibase.Liquibase.update(Liquibase.java:181) 
Jul 05 17:13:52 service-metabase app/web.1:  	at metabase.db$migrate$fn__6121.invoke(db.clj:123) 
Jul 05 17:13:52 service-metabase app/web.1:  	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:595) 
Jul 05 17:13:52 service-metabase app/web.1:  	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568) 
Jul 05 17:13:52 service-metabase app/web.1:  	at clojure.lang.RestFn.invoke(RestFn.java:521) 
Jul 05 17:13:52 service-metabase app/web.1:  	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:611) 
Jul 05 17:13:52 service-metabase app/web.1:  	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:568) 
Jul 05 17:13:52 service-metabase app/web.1:  	at clojure.lang.RestFn.invoke(RestFn.java:425) 
Jul 05 17:13:52 service-metabase app/web.1:  	... 15 more 
Jul 05 17:13:52 service-metabase app/web.1:  07-05 15:13:52 ERROR metabase.core :: Metabase Initialization FAILED:  liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by f8d21b88-1500-42b3-a024-f3984770b62f.prvt.dyno.rt.heroku.com (172.18.88.166) since 7/5/16 2:46 PM

**Comment by salsakran** [comment]
What seems to be happening is that heroku killed a dyno, and we left a migration lock. 

We have a command line utility for the times this happens described in http://www.metabase.com/docs/v0.18.1/operations-guide/start.html#troubleshooting-common-problems

If you can't run the jar under the same context as a dyno, just point `psql` at your application database and remove the lock from the DATABASECHANGELOGLOCK table.

**Comment by tlrobinson** [comment]
To run that command on Heroku you should be able to do:

```
heroku run java -jar target/uberjar/metabase.jar migrate release-locks
```

BTW the 503 errors are expected when the app is starting up.

**Comment by kritop** [comment]
thanks!

**Comment by AndrewMagliozzi** [comment]
Hmm... when I run that command, my app maxes out its RAM and crashes.  When I restart, this is what gets logged:

```
2016-08-17T18:35:17.036935+00:00 heroku[web.1]: State changed from starting to up
2016-08-17T18:35:22.022575+00:00 app[web.1]: 08-17 18:35:22 [1mDEBUG metabase.driver[0m :: Registered driver [34m:bigquery[0m 🚚
2016-08-17T18:35:22.076591+00:00 app[web.1]: 08-17 18:35:22 [1mDEBUG metabase.driver[0m :: Registered driver [34m:crate[0m 🚚
2016-08-17T18:35:22.277335+00:00 app[web.1]: 08-17 18:35:22 [1mDEBUG metabase.driver[0m :: Registered driver [34m:h2[0m 🚚
2016-08-17T18:35:22.778680+00:00 app[web.1]: 08-17 18:35:22 [1mDEBUG metabase.driver[0m :: Registered driver [34m:mongo[0m 🚚
2016-08-17T18:35:22.798939+00:00 app[web.1]: 08-17 18:35:22 [1mDEBUG metabase.driver[0m :: Registered driver [34m:mysql[0m 🚚
2016-08-17T18:35:24.624514+00:00 app[web.1]: 08-17 18:35:24 [1mINFO metabase.db[0m :: [36mVerifying postgres Database Connection ...[0m
2016-08-17T18:35:27.268597+00:00 app[web.1]: 08-17 18:35:27 [1mINFO metabase.db[0m :: Verify Database Connection ... ✅
2016-08-17T18:36:27.378438+00:00 app[web.1]: 08-17 18:36:27 [1mERROR liquibase[0m :: migrations/liquibase.json: migrations/038_getting_started_guide.yaml::38::camsaul: Change Set migrations/038_getting_started_guide.yaml::38::camsaul failed.  Error: ERROR: column "points_of_interest" of relation "metabase_database" already exists [Failed SQL: ALTER TABLE public.metabase_database ADD points_of_interest TEXT]
2016-08-17T18:36:27.415639+00:00 app[web.1]: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/038_getting_started_guide.yaml::38::camsaul:
2016-08-17T18:36:27.421378+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
2016-08-17T18:36:27.422812+00:00 app[web.1]: 	at metabase.core$_main.doInvoke(core.clj:255)
2016-08-17T18:36:27.424669+00:00 app[web.1]: 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:107)
2016-08-17T18:36:27.428271+00:00 app[web.1]: 	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1273)
2016-08-17T18:36:28.097326+00:00 heroku[web.1]: Process exited with status 1
2016-08-17T18:36:28.114254+00:00 heroku[web.1]: State changed from up to crashed

```
