### ISSUE TITLE
Filter Modal Crashes App on New Model

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#28971]
**Describe the bug**

Opening the bulk filter modal on a freshly created model crashes the app. 😢 

**Logs**
```
BulkFilterModal.tsx:119 Uncaught TypeError: Cannot read properties of undefined (reading 'items')
    at BulkFilterModal (BulkFilterModal.tsx:119:1)
    at renderWithHooks (react-dom.development.js:14803:1)
    at mountIndeterminateComponent (react-dom.development.js:17482:1)
    at beginWork (react-dom.development.js:18596:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
    at performUnitOfWork (react-dom.development.js:22154:1)
    at workLoopSync (react-dom.development.js:22130:1)
```

**To Reproduce**
1. Global New Menu
2. Model
3. Pick any table
4. Save it
5. Click Filter
6. App crashes.

**Expected behavior**

**Screenshots/videos**
![filterAppCrash](https://user-images.githubusercontent.com/30528226/223235673-270e0bee-f809-4546-9b3d-4656b03046f0.gif)

**Information about your Metabase Installation:**

```
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "18.0.1+0",
    "java.vendor": "Homebrew",
    "java.vendor.url": "https://github.com/Homebrew/homebrew-core/issues",
    "java.version": "18.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "18.0.1+0",
    "os.name": "Mac OS X",
    "os.version": "12.4",
    "user.language": "en",
    "user.timezone": "Europe/Budapest"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "dev",
    "version": {
      "date": "2023-02-27",
      "src_hash": "35b7029f06bdf5d97b3a143ad718b98edbfccff5",
      "tag": "v0.45.1-SNAPSHOT",
      "branch": "actions/test-times",
      "hash": "6603f1d"
    },
    "settings": {
      "report-timezone": "America/Denver"
    }
  }
}
```

**Severity**

Everything is fine after a page refresh, but it's a nasty little surprise for users when we're trying to encourage the use of models.

**Comment by iethree** [comment]
This existed in 45 as well. probably introduced by allowing model creation without having a question first.
