### ISSUE TITLE
Fingerprinting fails for tables with unfolded JSON fields with non-string and string values

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#29188]
**Describe the bug**

For tables where JSON unfolding is enabled on a database, and a JSON field has a nested field with a non-string inferred type (e.g. timestamp) and another with a string type, fingerprinting will fail with an error. If the values in the JSON field are all inferred as strings, the error doesn't happen.

From the logs:
```
2023-03-13 18:10:11,262 WARN sync.util :: Error fingerprinting Table 286 'public.json'
clojure.lang.ExceptionInfo: Error executing query: ERROR: column source.json_column does not exist
```

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Create a table in a postgres or mysql database with a JSON column that contains a non-string and a string value, e.g.:
```
DROP TABLE IF EXISTS test_table;
CREATE TABLE IF NOT EXISTS test_table (
  id int,
  name varchar(255),
  settings json,
  PRIMARY KEY (id)
);

INSERT INTO test_table (id, name, settings) VALUES
  (1, 'test1', '{"0": {"1": "2012-04-23T18:44:43.511Z", 
                       "2": "2v"}}'),
  (2, 'test2', '{"0": {"1": "2012-04-23T18:44:43.511Z",
                       "2": "2v"}}');
```
2. Sync the database, making sure JSON unfolding is enabled in the connection settings. Get the newly added table ID.
3. In the repl, run `(metabase.sync.analyze.fingerprint/fingerprint-fields! (db/select-one 'Table :id <table_id>))`. Observe the error.
<details><summary>Full stacktrace</summary>
```
2023-03-13 18:37:38,081 WARN sync.util :: Error fingerprinting Table 290 'public.test_table'
clojure.lang.ExceptionInfo: Error executing query: ERROR: column source.settings does not exist
  Position: 70 {:driver :postgres, :sql ["-- Metabase" "SELECT" "  \"source\".\"substring165904\" AS \"substring165904\"," "  (\"source\".\"settings\" # >> array [ ?, ? ] :: text [ ]) :: timestamp AS \"settings → 0 → 1\"," "  \"source\".\"substring165905\" AS \"substring165905\"" "FROM" "  (" "    SELECT" "      (" "        \"public\".\"test_table\".\"settings\" # >> array [ ?," "        ? ] :: text [ ]" "      ) :: timestamp AS \"settings → 0 → 1\"," "      (" "        \"public\".\"test_table\".\"settings\" # >> array [ ?," "        ? ] :: text [ ]" "      ) :: text AS \"settings → 0 → 2\"," "      \"public\".\"test_table\".\"name\" AS \"name\"," "      SUBSTRING(\"public\".\"test_table\".\"name\", 1, 1234) AS \"substring165904\"," "      SUBSTRING(" "        (" "          \"public\".\"test_table\".\"settings\" # >> array [ ?," "          ? ] :: text [ ]" "        ) :: text," "        1," "        1234" "      ) AS \"substring165905\"" "    FROM" "      \"public\".\"test_table\"" "  ) AS \"source\"" "LIMIT" "  10000"], :params ("0" "1" "0" "1" "0" "2" "0" "2"), :type :invalid-query}
        at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__103725.invoke(execute.clj:504)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:501)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:488)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:496)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:488)
        at metabase.driver.sql_jdbc$eval106601$fn__106602.invoke(sql_jdbc.clj:63)
        at clojure.lang.MultiFn.invoke(MultiFn.java:244)
        at metabase.query_processor.context$executef.invokeStatic(context.clj:60)
        at metabase.query_processor.context$executef.invoke(context.clj:49)
        at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:68)
        at metabase.query_processor.context.default$default_runf.invoke(default.clj:66)
        at metabase.query_processor.context$runf.invokeStatic(context.clj:46)
        at metabase.query_processor.context$runf.invoke(context.clj:40)
        at metabase.query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15)
        at metabase.query_processor.reducible$identity_qp.invoke(reducible.clj:12)
        at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___79684.invoke(cache.clj:224)
        at metabase.query_processor.middleware.permissions$check_query_permissions$fn__85097.invoke(permissions.clj:126)
        at metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__89046.invoke(permissions.clj:128)
        at metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__89293.invoke(column_level_perms_check.clj:31)
        at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__86567.invoke(mbql_to_native.clj:24)
        at metabase.query_processor$fn__89890$combined_post_process__89895$combined_post_process_STAR___89896.invoke(query_processor.clj:243)
        at metabase.query_processor$fn__89890$combined_pre_process__89891$combined_pre_process_STAR___89892.invoke(query_processor.clj:240)
        at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__87834$fn__87839.invoke(resolve_database_and_driver.clj:36)
        at metabase.driver$do_with_driver.invokeStatic(driver.clj:90)
        at metabase.driver$do_with_driver.invoke(driver.clj:86)
        at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__87834.invoke(resolve_database_and_driver.clj:35)
        at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__86370.invoke(fetch_source_query.clj:310)
        at metabase.query_processor.middleware.store$initialize_store$fn__88818$fn__88819.invoke(store.clj:12)
        at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:47)
        at metabase.query_processor.store$do_with_store.invoke(store.clj:41)
        at metabase.query_processor.middleware.store$initialize_store$fn__88818.invoke(store.clj:11)
        at metabase.query_processor.middleware.normalize_query$normalize$fn__86590.invoke(normalize_query.clj:25)
        at metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__89259.invoke(handle_audit_queries.clj:131)
        at metabase.query_processor.reducible$async_qp$qp_STAR___74844$thunk__74846.invoke(reducible.clj:103)
        at metabase.query_processor.reducible$async_qp$qp_STAR___74844.invoke(reducible.clj:109)
        at metabase.query_processor.reducible$async_qp$qp_STAR___74844.invoke(reducible.clj:94)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.query_processor$base_qp$fn__89902.doInvoke(query_processor.clj:261)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.query_processor.reducible$sync_qp$qp_STAR___74856.doInvoke(reducible.clj:129)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.query_processor$process_query.invokeStatic(query_processor.clj:278)
        at metabase.query_processor$process_query.doInvoke(query_processor.clj:272)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.db.metadata_queries$eval163382$table_rows_sample__163391$fn__163394.invoke(metadata_queries.clj:145)
        at metabase.db.metadata_queries$eval163382$table_rows_sample__163391.invoke(metadata_queries.clj:132)
        at metabase.db.metadata_queries$eval163413$fn__163414.invoke(metadata_queries.clj:149)
        at clojure.lang.MultiFn.invoke(MultiFn.java:252)
        at metabase.sync.analyze.fingerprint$eval162729$fingerprint_table_BANG___162734$fn__162735.invoke(fingerprint.clj:76)
        at metabase.sync.analyze.fingerprint$eval162729$fingerprint_table_BANG___162734.invoke(fingerprint.clj:54)
        at metabase.sync.analyze.fingerprint$eval163197$fingerprint_fields_BANG___163202$fn__163203$fn__163205.invoke(NO_SOURCE_FILE:192)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:161)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:154)
        at metabase.sync.analyze.fingerprint$eval163197$fingerprint_fields_BANG___163202$fn__163203.invoke(NO_SOURCE_FILE:190)
        at metabase.sync.analyze.fingerprint$eval163197$fingerprint_fields_BANG___163202.invoke(NO_SOURCE_FILE:184)
        at dev.nocommit.fingerprint$eval165900.invokeStatic(NO_SOURCE_FILE:15)
        at dev.nocommit.fingerprint$eval165900.invoke(NO_SOURCE_FILE:14)
        at clojure.lang.Compiler.eval(Compiler.java:7194)
        at clojure.lang.Compiler.eval(Compiler.java:7149)
        at clojure.core$eval.invokeStatic(core.clj:3215)
        at clojure.core$eval.invoke(core.clj:3211)
        at nrepl.middleware.interruptible_eval$evaluate$fn__9563$fn__9564.invoke(interruptible_eval.clj:87)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at nrepl.middleware.interruptible_eval$evaluate$fn__9563.invoke(interruptible_eval.clj:87)
        at clojure.main$repl$read_eval_print__9206$fn__9209.invoke(main.clj:437)
        at clojure.main$repl$read_eval_print__9206.invoke(main.clj:437)
        at clojure.main$repl$fn__9215.invoke(main.clj:458)
        at clojure.main$repl.invokeStatic(main.clj:458)
        at clojure.main$repl.doInvoke(main.clj:368)
        at clojure.lang.RestFn.invoke(RestFn.java:1523)
        at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:84)
        at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eva
l.clj:56)
        at nrepl.middleware.interruptible_eval$interruptible_eval$fn__9596$fn__9600.invoke(interruptible_eval.clj:152)
        at clojure.lang.AFn.run(AFn.java:22)
        at nrepl.middleware.session$session_exec$main_loop__9666$fn__9670.invoke(session.clj:218)
        at nrepl.middleware.session$session_exec$main_loop__9666.invoke(session.clj:217)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.postgresql.util.PSQLException: ERROR: column source.settings does not exist
  Position: 70
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
        at metabase.driver.sql_jdbc.execute$eval103630$fn__103631.invoke(execute.clj:379)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:392)
        at metabase.driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:388)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__103725.invoke(execute.clj:502)
        ... 90 more
```
</details>

**Exploration of the cause**

I did some digging and it seems to have the same root cause as https://github.com/metabase/metabase/issues/29184, because the query that is used to get the sample data from the table is an MBQL query, that includes custom expressions and a subset of fields.  https://github.com/metabase/metabase/blob/3e636378c539cbeec5b4d3a47e0d7f9605207d7f/src/metabase/db/metadata_queries.clj#L106

This is an example query that is returned by the table-rows-sample-query function linked above.
```clojure
;; field 2369 is an unfolded non-string timestamp field
;; field 2367 is an unfolded string field
;; field 2370 is an unfolded string field
{:source-table 290
   :expressions  {"substring165904" [:substring [:field 2367 nil] 1 1234]
                  "substring165905" [:substring [:field 2370 nil] 1 1234]}
   :fields       [[:expression "substring165904"] [:field 2369 nil] [:expression "substring165905"]]
   :limit        10000}
```

**Information about your Metabase Installation:**
Metabase version: master
Assuming it's caused by https://github.com/metabase/metabase/issues/29184, it's a regression and was working fine in 45.3

**Comment by calherries** [comment]
Closed by https://github.com/metabase/metabase/pull/29321
