### ISSUE TITLE
[INTERNAL] MomentJS deprecation warning

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#29264]
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: Series A, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.<anonymous> (lib-static-viz.bundle.js:2:777475)
    at lib-static-viz.bundle.js:2:797710
    at lib-static-viz.bundle.js:2:797558
    at hK (lib-static-viz.bundle.js:2:797456)
    at HK (lib-static-viz.bundle.js:2:798334)
    at Function.i (lib-static-viz.bundle.js:2:77[526](https://github.com/metabase/metabase/actions/runs/4435239667/jobs/7782162749?pr=29262#step:6:540)0)
    at bb (lib-static-viz.bundle.js:2:2842962)
    at Fa (lib-static-viz.bundle.js:2:2851226)
    at Va (lib-static-viz.bundle.js:2:2860216)
    at lib-static-viz.bundle.js:2:2950423
```

**Comment by paoliniluis** [comment]
I think we removed moment and only moment-timezone is left
