### ISSUE TITLE
dump command fails to serialize toucan2 records

### ISSUE THREAD

**Issue by john-metabase** [metabase/metabase#29322]
The v1 `dump` command fails when serializing toucan2 records, e.g. nested fields:

```
java.lang.ClassCastException: class toucan2.instance.Instance cannot be cast to class clojure.lang.Named (toucan2.instance.Instance is in unnamed module of loader clojure.lang.DynamicClassLoader @18d71ab1; clojure.lang.Named is in unnamed module of loader 'app')
        at clojure.core$name.invokeStatic(core.clj:1610)
        at clojure.core$name.invoke(core.clj:1604)
        at metabase_enterprise.serialization.names$name_for_logging.invokeStatic(names.clj:341)
        at metabase_enterprise.serialization.names$name_for_logging.invoke(names.clj:339)
        at metabase_enterprise.serialization.dump$dump$fn__123542.invoke(dump.clj:57)
        at metabase_enterprise.serialization.dump$dump.invokeStatic(dump.clj:54)
        at metabase_enterprise.serialization.dump$dump.doInvoke(dump.clj:50)
        at clojure.lang.RestFn.invoke(RestFn.java:1110)
        at metabase_enterprise.serialization.cmd$v1_dump.invokeStatic(cmd.clj:164)
        at metabase_enterprise.serialization.cmd$v1_dump.invoke(cmd.clj:138)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.cmd$call_enterprise.invokeStatic(cmd.clj:153)
        at metabase.cmd$call_enterprise.doInvoke(cmd.clj:143)
        at clojure.lang.RestFn.invoke(RestFn.java:439)
        at metabase.cmd$dump.invokeStatic(cmd.clj:184)
        at metabase.cmd$dump.doInvoke(cmd.clj:174)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.cmd$run_cmd$fn__127293.invoke(cmd.clj:272)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:272)
        at metabase.cmd$run_cmd.invoke(cmd.clj:263)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.core$run_cmd.invokeStatic(core.clj:166)
        at metabase.core$run_cmd.invoke(core.clj:164)
        at metabase.core$_main.invokeStatic(core.clj:188)
        at metabase.core$_main.doInvoke(core.clj:183)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
        at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.main$main_opt.invokeStatic(main.clj:514)
        at clojure.main$main_opt.invoke(main.clj:510)
        at clojure.main$main.invokeStatic(main.clj:664)
        at clojure.main$main.doInvoke(main.clj:616)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:40)
Command failed with exception: class toucan2.instance.Instance cannot be cast to class clojure.lang.Named (toucan2.instance.Instance is in unnamed module of loader clojure.lang.DynamicClassLoader @18d71ab1; clojure.lang.Named is in unnamed module of loader 'app')
```

This should be fairly simple to fix but a test should be added to cover this.

**Comment by Tony-metabase** [comment]
Escalating this since it seems to be completely broken in 1.46.1 ... if you simply pull this repo https://github.com/paoliniluis/metabase-serialization ... change the version to 1.46.1 and do a dump it fails with the above error

P.S. The metabase instance is a clean version of metabase so it's plain as it can get

**Comment by Tony-metabase** [comment]
Removing escalation, not able to replicate this after pruning all docker volumes
