### ISSUE TITLE
Deployment via Elastic Beanstalk: Custom "option_settings" are not supported

### ISSUE THREAD

**Issue by MarcSamD** [metabase/metabase#29508]
**User case**
DockerHub is sometimes blocked or very slow from China making the "docker pull" of Metabase failing after 15 minutes timeout, and so any new instance deployment or existing instance update is failing.
So the goal is to use a private ECR or a chinese DockerHub mirror to pull the new versions, following [AWS procedure using SSM authentication](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/single-container-docker-configuration.html).

**Describe the bug**
For SSM authentication to work, we need to add the following settings, either in a new file "env.config" or in the existing file "01_metabase.config" (the error result will be the same), causing the deployment to fail.
```
option_settings:
  aws:elasticbeanstalk:application:environment:
    USER: '{{resolve:ssm:USER:1}}'
    PASSWD: '{{resolve:ssm:PASSWD:1}}'
```
**Logs**
```
/var/log/eb-engine.log:
2023/03/24 01:31:08.461451 [INFO] Executing instruction: PostBuildEbExtension
2023/03/24 01:31:08.461488 [INFO] Starting executing the config set Infra-EmbeddedPostBuild.
2023/03/24 01:31:08.461504 [INFO] Running command /bin/sh -c /opt/aws/bin/cfn-init -s arn:aws-cn:cloudformation:cn-north-1:xxxidxxx -r AWSEBAutoScalingGroup --region cn-north-1 --configsets Infra-EmbeddedPostBuild
2023/03/24 01:31:09.050515 [INFO] Error occurred during build: Command 01-persist_env_vars failed
2023/03/24 01:31:09.050547 [ERROR] An error occurred during execution of command [app-deploy] - [PostBuildEbExtension]. Stop running the command. Error: Container commands build failed. Please refer to /var/log/cfn-init.log for more details.
```
```
/var/log/cfn-init.log:
2023-03-24 01:31:08,966 [INFO] -----------------------Starting build-----------------------
2023-03-24 01:31:08,982 [INFO] Running configSets: Infra-EmbeddedPostBuild
2023-03-24 01:31:08,985 [INFO] Running configSet Infra-EmbeddedPostBuild
2023-03-24 01:31:08,988 [INFO] Running config postbuild_0_Metabase
2023-03-24 01:31:09,002 [ERROR] Command 01-persist_env_vars (.ebextensions/metabase_config/metabase-setup.sh set_up_env_vars) failed
2023-03-24 01:31:09,002 [ERROR] Error encountered during build of postbuild_0_Metabase: Command 01-persist_env_vars failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 579, in run_config
    CloudFormationCarpenter(config, self._auth_config, self.strict_mode).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 278, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 01-persist_env_vars failed
2023-03-24 01:31:09,003 [ERROR] -----------------------BUILD FAILED!------------------------
2023-03-24 01:31:09,003 [ERROR] Unhandled exception during build: Command 01-persist_env_vars failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 181, in <module>
    worklog.build(metadata, configSets, strict_mode)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 137, in build
    Contractor(metadata, strict_mode).build(configSets, self)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 567, in build
    self.run_config(config, worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 579, in run_config
    CloudFormationCarpenter(config, self._auth_config, self.strict_mode).build(worklog)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/construction.py", line 278, in build
    self._config.commands)
  File "/usr/lib/python3.7/site-packages/cfnbootstrap/command_tool.py", line 127, in apply
    raise ToolError(u"Command %s failed" % name)
cfnbootstrap.construction_errors.ToolError: Command 01-persist_env_vars failed
```
**To Reproduce**
Add "option_settings:" with custom environment variables to 01_metabase.config

**Expected behavior**
Can connect to custom docker repository.

@paoliniluis As the AWS EB expert, do not hesitate to comment if you are passing by and it seems easy to solve for you :)

**Comment by paoliniluis** [comment]
Thanks @MarcSamD for the heads up. I'm guessing that we'll need to add this config but also modify the IAM role so Beanstalk can use SSM right? I see https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts-roles-instance.html, which I believe it's the default role

**Comment by MarcSamD** [comment]
Hi @paoliniluis, thanks for your reply.
Yes, need to add SSM and ECR permissions to the IAM role (and also configure ECR private repository policy).
I went a bit wild on the policies for the testing but I would fine-tune if I could make it work, below is what I use (notice the AWS managed policies, not only the custom one):
![image](https://user-images.githubusercontent.com/70358310/232364676-6a800d56-d528-4d27-8da0-de7df9489e48.png)

What I'm sure is that the authentication to SSM and the download of the docker image is working well. I can run the command manually on the EB instance and it will work, and even automatically it is working as I'm using this workaround for re-deploying / updating Metabase:
1. Deployment of Metabase standard deployment file (usually fails because of github timeout)
2. Deployment of my custom deployment file (fails because of postbuild "01-persist_env_vars")
3. Deployment of Metabase standard deployment file again (works because this time the instance successfully pulled the docker image from the step 2 so it will not try to pull it again and the standard deployment can continue normally).

**Comment by paoliniluis** [comment]
We have deprecated shipping the Beanstalk artifacts, so this is no longer relevant. Users will have to build their own beanstalk artifacts from now on
