### ISSUE TITLE
Upgrade 0.45.3 to 0.46.0 fails with org.postgresql.util.PSQLException

### ISSUE THREAD

**Issue by linucksrox** [metabase/metabase#29630]
**Describe the bug**
After upgrading in docker from 0.45.3 to 0.46.0, Metabase won't start and the logs include this exception Caused by: org.postgresql.util.PSQLException: ERROR: could not read block 0 in file "base/16384/43209": read only 0 of 8192 bytes.

**Logs**
```
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,348 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,349 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,379 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,381 INFO driver.impl :: Registered driver :googleanalytics  🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,462 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto-jdbc...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,464 INFO driver.impl :: Registered driver :presto-jdbc (parents: [:sql-jdbc]) 🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,500 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,502 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc]) 🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,503 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,505 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,515 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,516 INFO driver.impl :: Registered driver :redshift (parents: [:postgres]) 🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,522 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,523 INFO driver.impl :: Registered driver :druid  🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,542 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :athena...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,543 INFO driver.impl :: Registered driver :athena (parents: [:sql-jdbc]) 🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,555 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery-cloud-sdk...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,556 INFO driver.impl :: Registered driver :bigquery-cloud-sdk (parents: [:sql]) 🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,563 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,567 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,567 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver"]
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,578 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,579 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,580 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver"]
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,615 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,616 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,631 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,632 INFO driver.impl :: Registered driver :mongo  🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,638 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,639 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 🚚
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,641 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:51,647 INFO db.setup :: Verifying postgres Database Connection ...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:52,108 INFO db.setup :: Successfully verified PostgreSQL 14.7 (Debian 14.7-1.pgdg110+1) application database connection. ✅
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:52,111 INFO db.setup :: Running Database Migrations...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:52,112 INFO db.setup :: Setting up Liquibase...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:52,504 INFO db.setup :: Liquibase is ready.
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:52,505 INFO db.liquibase :: Checking if Database has unrun migrations...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:54,966 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:55,307 INFO db.liquibase :: Migration lock is cleared. Running migrations...
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | 2023-03-28 19:07:55,847 ERROR metabase.core :: Metabase Initialization FAILED
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::v46.00-010::snoe:
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |      Reason: liquibase.exception.DatabaseException: ERROR: could not read block 0 in file "base/16384/43209": read only 0 of 8192 bytes
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   Where: SQL statement "SELECT fk."database_id" FROM ONLY "public"."query_action" fk LEFT OUTER JOIN ONLY "public"."metabase_database" pk ON ( pk."id" OPERATOR(pg_catalog.=) fk."database_id") WHERE pk."id" IS NULL AND (fk."database_id" IS NOT NULL)" [Failed SQL: (0) ALTER TABLE "public"."query_action" ADD CONSTRAINT "fk_query_action_database_id" FOREIGN KEY ("database_id") REFERENCES "public"."metabase_database" ("id") ON DELETE CASCADE]
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Liquibase.lambda$null$0(Liquibase.java:265)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.lambda$child$0(Scope.java:180)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:189)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:179)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:158)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:243)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Liquibase.lambda$update$1(Liquibase.java:264)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.lambda$child$0(Scope.java:180)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:189)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:179)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:158)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Liquibase.runInScope(Liquibase.java:2405)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Liquibase.update(Liquibase.java:211)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Liquibase.update(Liquibase.java:197)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Liquibase.update(Liquibase.java:193)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:147)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:135)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.setup$fn__50118$migrate_BANG___50123$fn__50124$fn__50125.invoke(setup.clj:79)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.liquibase$fn__46055$do_with_liquibase__46060$fn__46061.invoke(liquibase.clj:64)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.liquibase$fn__46055$do_with_liquibase__46060.invoke(liquibase.clj:56)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.setup$fn__50118$migrate_BANG___50123$fn__50124.invoke(setup.clj:74)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.setup$fn__50118$migrate_BANG___50123.doInvoke(setup.clj:52)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at clojure.lang.RestFn.invoke(RestFn.java:445)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.setup$fn__50182$run_schema_migrations_BANG___50187$fn__50188.invoke(setup.clj:132)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.setup$fn__50182$run_schema_migrations_BANG___50187.invoke(setup.clj:126)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.setup$fn__50235$setup_db_BANG___50240$fn__50241$fn__50244$fn__50245.invoke(setup.clj:157)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.setup$fn__50235$setup_db_BANG___50240$fn__50241$fn__50244.invoke(setup.clj:153)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.setup$fn__50235$setup_db_BANG___50240$fn__50241.invoke(setup.clj:152)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db.setup$fn__50235$setup_db_BANG___50240.invoke(setup.clj:146)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db$setup_db_BANG_$fn__50270.invoke(db.clj:66)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db$setup_db_BANG_.invokeStatic(db.clj:61)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.db$setup_db_BANG_.invoke(db.clj:52)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:104)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.core$init_BANG__STAR_.invoke(core.clj:90)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.core$init_BANG_.invokeStatic(core.clj:144)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.core$init_BANG_.invoke(core.clj:139)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.core$start_normally.invokeStatic(core.clj:156)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.core$start_normally.invoke(core.clj:150)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.core$_main.invokeStatic(core.clj:189)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.core$_main.doInvoke(core.clj:183)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at clojure.lang.RestFn.invoke(RestFn.java:397)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at clojure.lang.AFn.applyToHelper(AFn.java:152)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at clojure.lang.RestFn.applyTo(RestFn.java:132)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at clojure.lang.Var.applyTo(Var.java:705)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at clojure.core$apply.invokeStatic(core.clj:667)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at clojure.core$apply.invoke(core.clj:662)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at clojure.lang.RestFn.invoke(RestFn.java:397)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at clojure.lang.AFn.applyToHelper(AFn.java:152)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at clojure.lang.RestFn.applyTo(RestFn.java:132)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at metabase.bootstrap.main(Unknown Source)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::v46.00-010::snoe:
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |      Reason: liquibase.exception.DatabaseException: ERROR: could not read block 0 in file "base/16384/43209": read only 0 of 8192 bytes
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   Where: SQL statement "SELECT fk."database_id" FROM ONLY "public"."query_action" fk LEFT OUTER JOIN ONLY "public"."metabase_database" pk ON ( pk."id" OPERATOR(pg_catalog.=) fk."database_id") WHERE pk."id" IS NULL AND (fk."database_id" IS NOT NULL)" [Failed SQL: (0) ALTER TABLE "public"."query_action" ADD CONSTRAINT "fk_query_action_database_id" FOREIGN KEY ("database_id") REFERENCES "public"."metabase_database" ("id") ON DELETE CASCADE]
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.changelog.ChangeSet.execute(ChangeSet.java:696)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:56)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:113)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.lambda$child$0(Scope.java:180)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:189)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:179)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:158)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:112)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.lambda$child$0(Scope.java:180)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:189)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:179)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:158)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:243)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.lambda$child$0(Scope.java:180)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:189)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:179)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:158)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:243)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.Scope.child(Scope.java:247)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:65)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   ... 54 more
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | Caused by: liquibase.exception.DatabaseException: ERROR: could not read block 0 in file "base/16384/43209": read only 0 of 8192 bytes
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   Where: SQL statement "SELECT fk."database_id" FROM ONLY "public"."query_action" fk LEFT OUTER JOIN ONLY "public"."metabase_database" pk ON ( pk."id" OPERATOR(pg_catalog.=) fk."database_id") WHERE pk."id" IS NULL AND (fk."database_id" IS NOT NULL)" [Failed SQL: (0) ALTER TABLE "public"."query_action" ADD CONSTRAINT "fk_query_action_database_id" FOREIGN KEY ("database_id") REFERENCES "public"."metabase_database" ("id") ON DELETE CASCADE]
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:397)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:151)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1279)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1261)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.changelog.ChangeSet.execute(ChangeSet.java:661)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   ... 74 more
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    | Caused by: org.postgresql.util.PSQLException: ERROR: could not read block 0 in file "base/16384/43209": read only 0 of 8192 bytes
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   Where: SQL statement "SELECT fk."database_id" FROM ONLY "public"."query_action" fk LEFT OUTER JOIN ONLY "public"."metabase_database" pk ON ( pk."id" OPERATOR(pg_catalog.=) fk."database_id") WHERE pk."id" IS NULL AND (fk."database_id" IS NOT NULL)"
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
fireflyiii_metabase.1.tq4ixrwh13vv@dockerswarm01    |   ... 79 more
```
**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Install Metabase 0.45.3 in Docker, using Postgres 14
1. Upgrade to 0.46.0
1. See error

**Expected behavior**
Not a postgresql exception but a successful upgrade.

**Information about your Metabase Installation:**

- Ubuntu 22.04 docker in swarm mode (single node)
- Postgres 14
- Metabase version: 0.46.0
- Metabase hosting environment: Docker
- Metabase internal database: Postgres 14

**Severity**
Completely broken :(

**Comment by linucksrox** [comment]
I'm not sure why it broke. But I restored from a backup running 0.45.3, stopped the docker stack manually first instead of letting docker swarm upgrade, and then upgraded to 0.46.0 and this time the database migration worked fine and things are working.
