### ISSUE TITLE
Athena occasionally timeouts even though query executes successful in Athena console

### ISSUE THREAD

**Issue by jesperbruunhansen** [metabase/metabase#29674]
**Describe the bug**
Metabase occasionally does not return the response from Athena and ends up timing out, even though the query executed in 2-3 seconds in Athena log of recent queries. Reloading the question once or twice makes it return again.

**Logs**
I'm seeing these errors occur in the logs
```
[a01133a8-e471-4b74-824c-79808709ccce] 2023-03-30T10:42:07+02:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: [Simba][AthenaJDBC](100123) An error has occurred. Exception during column initialization .Details: -- Metabase:: userID: X queryType: MBQL queryHash: 0047c9bbaf3b558e809bef652d29e317d7fb6b644e4969933746887a6f7bb8eb
... [stacktrace]
```
When I inspect the query executed in console I see the following (Query finished successfully within 3 seconds):
![image](https://user-images.githubusercontent.com/8859860/228782329-386bf0ce-1bf8-43e9-88af-d8b0b6bd6d3e.png)

**To Reproduce**
Reproduction is hard, as the execution of a query _sometime_ fails! If I don't change anything in the query and re-run it a couple of times it works.

**Expected behavior**
I want executions in Metabase to be 1-1 reproducible directly in Athena console, which they currently aren't.

**Screenshots/videos**
Athena setup
![athena](https://user-images.githubusercontent.com/8859860/228784143-d9a5817e-7346-4fb2-9f76-da9a7c279df3.png)

**Information about your Metabase Installation:**

You can get this information by going to Admin -> Troubleshooting, or simply post the JSON you see in that page.

- Your browser and the version: Brave 1.49.132
- Your operating system: MacOS Ventura 13.3
- Your databases: Athena
- Metabase version: v0.45.3
- Metabase hosting environment: AWS ECS
- Metabase internal database: AWC Postgres

**Severity**
This is causing us to not consider Metabase as BI solution, as Athena is our primary query engine for accessing our data

**Additional context**

**Comment by Tony-metabase** [comment]
Can you share the whole stack trace? ... and the query you are executing

**Comment by paoliniluis** [comment]
@jesperbruunhansen so what you say is that the query in Athena finishes, but in Metabase it does not right?

**Comment by zbodi74** [comment]
This might not be an actual Metabase issue. The [Athena JDBC driver documentation](https://docs.aws.amazon.com/athena/latest/ug/jdbc-v2.html) states this:
> When you use the JDBC driver, be sure to note the following requirements:
> 
> Open port 444 – Keep port 444, which Athena uses to stream query results, open to outbound traffic. When you use a PrivateLink endpoint to connect to Athena, ensure that the security group attached to the PrivateLink endpoint is open to inbound traffic on port 444. If port 444 is blocked, you may receive the error message [Simba][AthenaJDBC](100123) An error has occurred. Exception during column initialization.

So the issue could potentially be due to incomplete network configuration problem and the fact that streaming query results are enabled in the Athena driver configuration. I haven't tested this, but the solution could be either:

* Ensuring that port 444 is open for both inbound and outbound connections between Athena and Metabase.

* Disabling result set streaming by adding `UseResultsetStreaming=0` as an additional JDBC option in the database connection details within Metabase.

@jesperbruunhansen - could you please check if implementing either of these solutions resolves the issue?

**Comment by ericcj** [comment]
hm with UseResultsetStreaming=0 now metabase says "Your question took too long" if it successfully finishes in ~50s according to athena e.g. all these succeeded (and metabase didn't cancel them on any timeout) but the metabase UI doesn't show the result. 

<img width="768" alt="Screenshot 2023-11-21 at 4 42 18 PM" src="https://github.com/metabase/metabase/assets/53106/b0f56302-0e9c-495b-b138-91ac927f3da6">

```
[e6a7b079-d4c0-4764-8dc6-a40909770280] 2023-11-21T16:41:22-05:00 ERROR metabase.async.streaming-response Error writing error to output stream {:database_id 13, :started_at #t "2023-11-21T21:39:59.539792Z[GMT]", :via [{:status :failed, :class org.eclipse.jetty.io.EofException, :error nil, :stacktrace [org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:116) org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:275) org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254) org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:386) org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:827) org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:243) org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224) org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:584) org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:1060) org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:1132) org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:270) org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:623) java.base/java.util.zip.DeflaterOutputStream.close(Unknown Source) --> async.streaming_response$delay_output_stream$fn__39676.invoke(streaming_response.clj:121) async.streaming_response.proxy$java.io.OutputStream$ff19274a.close(Unknown Source) query_processor.streaming.json$fn$reify__60530.finish_BANG_(json.clj:97) query_processor.streaming$streaming_reducedf$fn__61354.invoke(streaming.clj:132) query_processor.context$reducedf.invokeStatic(context.clj:78) query_processor.context$reducedf.invoke(context.clj:73) query_processor.context.default$default_reducef.invokeStatic(default.clj:64) query_processor.context.default$default_reducef.invoke(default.clj:49) query_processor.context$reducef.invokeStatic(context.clj:70) query_processor.context$reducef.invoke(context.clj:63) query_processor.context.default$default_runf$respond_STAR___51836.invoke(default.clj:69) driver.sql_jdbc.execute$execute_reducible_query$fn__81031.invoke(execute.clj:689) driver.sql_jdbc.execute$fn__80832$fn__80833.invoke(execute.clj:384) driver.sql_jdbc.execute$fn__80800$do_with_resolved_connection__80801.invoke(execute.clj:334) driver.sql_jdbc.execute$fn__80832.invokeStatic(execute.clj:378) driver.sql_jdbc.execute$fn__80832.invoke(execute.clj:376) driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:672) driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:661) driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:669) driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:661) driver.sql_jdbc$fn__115907.invokeStatic(sql_jdbc.clj:72) driver.sql_jdbc$fn__115907.invoke(sql_jdbc.clj:70) driver.athena$fn__115393.invokeStatic(athena.clj:449) driver.athena$fn__115393.invoke(athena.clj:447) query_processor.context$executef.invokeStatic(context.clj:60) query_processor.context$executef.invoke(context.clj:49) query_processor.context.default$default_runf.invokeStatic(default.clj:68) query_processor.context.default$default_runf.invoke(default.clj:66) query_processor.context$runf.invokeStatic(context.clj:46) query_processor.context$runf.invoke(context.clj:40) query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15) query_processor.reducible$identity_qp.invoke(reducible.clj:12) query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___77064.invoke(cache.clj:224) query_processor.middleware.permissions$check_query_permissions$fn__72647.invoke(permissions.clj:126) query_processor.middleware.mbql_to_native$mbql__GT_native$fn__76189.invoke(mbql_to_native.clj:24) query_processor$fn__78297$combined_post_process__78302$combined_post_process_STAR___78303.invoke(query_processor.clj:260) query_processor$fn__78297$combined_pre_process__78298$combined_pre_process_STAR___78299.invoke(query_processor.clj:257) query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76975$fn__76980.invoke(resolve_database_and_driver.clj:36) driver$do_with_driver.invokeStatic(driver.clj:93) driver$do_with_driver.invoke(driver.clj:88) query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76975.invoke(resolve_database_and_driver.clj:35) query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__72957.invoke(fetch_source_query.clj:316) query_processor.middleware.store$initialize_store$fn__73138$fn__73139.invoke(store.clj:12) query_processor.store$do_with_store.invokeStatic(store.clj:56) query_processor.store$do_with_store.invoke(store.clj:50) query_processor.middleware.store$initialize_store$fn__73138.invoke(store.clj:11) query_processor.middleware.normalize_query$normalize$fn__77271.invoke(normalize_query.clj:36) query_processor.middleware.constraints$add_default_userland_constraints$fn__74665.invoke(constraints.clj:54) query_processor.middleware.process_userland_query$process_userland_query$fn__77200.invoke(process_userland_query.clj:151) query_processor.middleware.catch_exceptions$catch_exceptions$fn__77597.invoke(catch_exceptions.clj:171) query_processor.reducible$async_qp$qp_STAR___66814$thunk__66816.invoke(reducible.clj:103) query_processor.reducible$async_qp$qp_STAR___66814.invoke(reducible.clj:109) query_processor.reducible$async_qp$qp_STAR___66814.invoke(reducible.clj:94) query_processor.reducible$sync_qp$qp_STAR___66826.doInvoke(reducible.clj:129) query_processor$process_userland_query.invokeStatic(query_processor.clj:383) query_processor$process_userland_query.doInvoke(query_processor.clj:379) query_processor$fn__78346$process_query_and_save_execution_BANG___78355$fn__78358.invoke(query_processor.clj:394) query_processor$fn__78346$process_query_and_save_execution_BANG___78355.invoke(query_processor.clj:387) query_processor$fn__78391$process_query_and_save_with_max_results_constraints_BANG___78400$fn__78403.invoke(query_processor.clj:406) query_processor$fn__78391$process_query_and_save_with_max_results_constraints_BANG___78400.invoke(query_processor.clj:399) api.dataset$run_query_async$fn__100175.invoke(dataset.clj:74) query_processor.streaming$streaming_response_STAR_$fn__61404$fn__61405.invoke(streaming.clj:166) query_processor.streaming$streaming_response_STAR_$fn__61404.invoke(streaming.clj:165) async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69) async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67) async.streaming_response$do_f_async$task__39661.invoke(streaming_response.clj:88)]}], :json_query {:type native, :native {:query -- Metabase:: userID: 9 queryType: native queryHash: 2e396ed9051256d036fbc7b294d21938df8bae96a6d82633adc951da4bfcd925
...
java.io.IOException: write beyond end of stream
	at java.base/java.util.zip.DeflaterOutputStream.write(Unknown Source)
	at java.base/java.util.zip.GZIPOutputStream.write(Unknown Source)
	at metabase.async.streaming_response$write_to_output_stream_BANG_.invokeStatic(streaming_response.clj:36)
	at metabase.async.streaming_response$write_to_output_stream_BANG_.invoke(streaming_response.clj:29)
	at metabase.async.streaming_response$delay_output_stream$fn__39680.invoke(streaming_response.clj:128)
	at metabase.async.streaming_response.proxy$java.io.OutputStream$ff19274a.write(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
	at java.base/java.io.BufferedWriter.close(Unknown Source)
	at metabase.async.streaming_response$write_error_BANG_.invokeStatic(streaming_response.clj:61)
	at metabase.async.streaming_response$write_error_BANG_.invoke(streaming_response.clj:46)
	at metabase.query_processor.streaming$streaming_response_STAR_$fn__61404.invoke(streaming.clj:174)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)
	at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)
	at metabase.async.streaming_response$do_f_async$task__39661.invoke(streaming_response.clj:88)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by jesperbruunhansen** [comment]
Sorry for not updating this issues

We resolved this issue by setting
```
UseResultsetStreaming=0;
```
On connection string - then everything worked as expected :)

**Comment by paoliniluis** [comment]
@jeff-bruemmer 👆🏻
