### ISSUE TITLE
Connecting to a SQL Server database with SSH does not work with dynamic ports

### ISSUE THREAD

**Issue by dragonsahead** [metabase/metabase#29778]
**Describe the bug**
When you enable SSH when connecting to a SQL server, you need to use a fixed port for MS SQL, as otherwise it will return "Assert failed: (integer? port)" in the FE

**Logs**
<details>
```
metabase-sqlserver         | 2023-04-03 23:32:12,568 DEBUG middleware.log :: GET /api/database 200 26.6 ms (3 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (4 idle, 0 queued) (40 total active threads) Queries in flight: 0 (0 queued)
metabase-sqlserver         | 2023-04-03 23:32:49,931 ERROR api.database :: Cannot connect to Database
metabase-sqlserver         | clojure.lang.ExceptionInfo: Assert failed: (integer? port) {:message "Assert failed: (integer? port)"}
metabase-sqlserver         | 	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:159)
metabase-sqlserver         | 	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:132)
metabase-sqlserver         | 	at clojure.lang.RestFn.invoke(RestFn.java:442)
metabase-sqlserver         | 	at metabase.api.database$test_database_connection.invokeStatic(database.clj:677)
metabase-sqlserver         | 	at metabase.api.database$test_database_connection.doInvoke(database.clj:667)
metabase-sqlserver         | 	at clojure.lang.RestFn.invoke(RestFn.java:425)
metabase-sqlserver         | 	at metabase.api.database$fn__95662.invokeStatic(database.clj:884)
metabase-sqlserver         | 	at metabase.api.database$fn__95662.invoke(database.clj:863)
metabase-sqlserver         | 	at compojure.core$wrap_response$fn__42375.invoke(core.clj:160)
metabase-sqlserver         | 	at compojure.core$wrap_route_middleware$fn__42359.invoke(core.clj:132)
metabase-sqlserver         | 	at compojure.core$wrap_route_info$fn__42364.invoke(core.clj:139)
metabase-sqlserver         | 	at compojure.core$wrap_route_matches$fn__42368.invoke(core.clj:151)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$wrap_route_matches$fn__42368.invoke(core.clj:153)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$wrap_route_matches$fn__42368.invoke(core.clj:153)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387.invoke(core.clj:200)
metabase-sqlserver         | 	at metabase.server.middleware.auth$enforce_authentication$fn__87414.invoke(auth.clj:17)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387.invoke(core.clj:200)
metabase-sqlserver         | 	at compojure.core$make_context$handler__42415.invoke(core.clj:290)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:300)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:199)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:199)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387.invoke(core.clj:200)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:199)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387.invoke(core.clj:200)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387.invoke(core.clj:200)
metabase-sqlserver         | 	at metabase.api.routes$fn__99242$fn__99243.invoke(routes.clj:62)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387.invoke(core.clj:200)
metabase-sqlserver         | 	at clojure.lang.AFn.applyToHelper(AFn.java:160)
metabase-sqlserver         | 	at clojure.lang.AFn.applyTo(AFn.java:144)
metabase-sqlserver         | 	at clojure.core$apply.invokeStatic(core.clj:667)
metabase-sqlserver         | 	at clojure.core$apply.invoke(core.clj:662)
metabase-sqlserver         | 	at metabase.server.routes$fn__99403$fn__99404.doInvoke(routes.clj:70)
metabase-sqlserver         | 	at clojure.lang.RestFn.invoke(RestFn.java:436)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387.invoke(core.clj:200)
metabase-sqlserver         | 	at compojure.core$make_context$handler__42415.invoke(core.clj:290)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:300)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$wrap_route_matches$fn__42368.invoke(core.clj:153)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$wrap_route_matches$fn__42368.invoke(core.clj:153)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$wrap_route_matches$fn__42368.invoke(core.clj:153)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:199)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388$respond_SINGLEQUOTE___42389.invoke(core.clj:197)
metabase-sqlserver         | 	at compojure.core$make_context$fn__42419.invoke(core.clj:301)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387.invoke(core.clj:200)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387$f__42388.invoke(core.clj:198)
metabase-sqlserver         | 	at compojure.core$routes$fn__42387.invoke(core.clj:200)
metabase-sqlserver         | 	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__95926.invoke(exceptions.clj:103)
metabase-sqlserver         | 	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__95923.invoke(exceptions.clj:91)
metabase-sqlserver         | 	at metabase.server.middleware.log$log_api_call$fn__102700$fn__102701$fn__102702.invoke(log.clj:216)
metabase-sqlserver         | 	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18)
metabase-sqlserver         | 	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12)
metabase-sqlserver         | 	at metabase.server.middleware.log$log_api_call$fn__102700$fn__102701.invoke(log.clj:208)
metabase-sqlserver         | 	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112)
metabase-sqlserver         | 	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103)
metabase-sqlserver         | 	at metabase.server.middleware.log$log_api_call$fn__102700.invoke(log.clj:207)
metabase-sqlserver         | 	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__109417.invoke(browser_cookie.clj:42)
metabase-sqlserver         | 	at metabase.server.middleware.security$add_security_headers$fn__80243.invoke(security.clj:153)
metabase-sqlserver         | 	at metabase.server.middleware.json$wrap_json_body$fn__106673.invoke(json.clj:67)
metabase-sqlserver         | 	at metabase.server.middleware.offset_paging$handle_paging$fn__80267.invoke(offset_paging.clj:45)
metabase-sqlserver         | 	at metabase.server.middleware.json$wrap_streamed_json_response$fn__106691.invoke(json.clj:103)
metabase-sqlserver         | 	at ring.middleware.keyword_params$wrap_keyword_params$fn__109684.invoke(keyword_params.clj:55)
metabase-sqlserver         | 	at ring.middleware.params$wrap_params$fn__109703.invoke(params.clj:77)
metabase-sqlserver         | 	at metabase.server.middleware.misc$maybe_set_site_url$fn__50479.invoke(misc.clj:61)
metabase-sqlserver         | 	at metabase.server.middleware.session$reset_session_timeout$fn__63769.invoke(session.clj:430)
metabase-sqlserver         | 	at metabase.server.middleware.session$bind_current_user$fn__63739$fn__63740.invoke(session.clj:336)
metabase-sqlserver         | 	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:315)
metabase-sqlserver         | 	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:304)
metabase-sqlserver         | 	at metabase.server.middleware.session$bind_current_user$fn__63739.invoke(session.clj:335)
metabase-sqlserver         | 	at metabase.server.middleware.session$wrap_current_user_info$fn__63721.invoke(session.clj:285)
metabase-sqlserver         | 	at metabase.server.middleware.session$wrap_session_id$fn__63704.invoke(session.clj:217)
metabase-sqlserver         | 	at metabase.server.middleware.auth$wrap_api_key$fn__87422.invoke(auth.clj:30)
metabase-sqlserver         | 	at ring.middleware.cookies$wrap_cookies$fn__109604.invoke(cookies.clj:216)
metabase-sqlserver         | 	at metabase.server.middleware.misc$add_content_type$fn__50461.invoke(misc.clj:29)
metabase-sqlserver         | 	at metabase.server.middleware.misc$disable_streaming_buffering$fn__50487.invoke(misc.clj:78)
metabase-sqlserver         | 	at ring.middleware.gzip$wrap_gzip$fn__109646.invoke(gzip.clj:86)
metabase-sqlserver         | 	at metabase.server.middleware.misc$bind_request$fn__50490.invoke(misc.clj:95)
metabase-sqlserver         | 	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__109433.invoke(ssl.clj:41)
metabase-sqlserver         | 	at metabase.server$async_proxy_handler$fn__101466.invoke(server.clj:77)
metabase-sqlserver         | 	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
metabase-sqlserver         | 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
metabase-sqlserver         | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
metabase-sqlserver         | 	at org.eclipse.jetty.server.Server.handle(Server.java:563)
metabase-sqlserver         | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
metabase-sqlserver         | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
metabase-sqlserver         | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
metabase-sqlserver         | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
metabase-sqlserver         | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
metabase-sqlserver         | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
metabase-sqlserver         | 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
metabase-sqlserver         | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
metabase-sqlserver         | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
metabase-sqlserver         | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
metabase-sqlserver         | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
metabase-sqlserver         | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
metabase-sqlserver         | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
metabase-sqlserver         | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
metabase-sqlserver         | 	at java.base/java.lang.Thread.run(Unknown Source)
metabase-sqlserver         | Caused by: java.lang.AssertionError: Assert failed: (integer? port)
metabase-sqlserver         | 	at metabase.util.ssh$start_ssh_tunnel_BANG_.invokeStatic(ssh.clj:53)
metabase-sqlserver         | 	at metabase.util.ssh$start_ssh_tunnel_BANG_.invoke(ssh.clj:53)
metabase-sqlserver         | 	at metabase.util.ssh$include_ssh_tunnel_BANG_.invokeStatic(ssh.clj:94)
metabase-sqlserver         | 	at metabase.util.ssh$include_ssh_tunnel_BANG_.invoke(ssh.clj:88)
metabase-sqlserver         | 	at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:134)
metabase-sqlserver         | 	at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:130)
metabase-sqlserver         | 	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:285)
metabase-sqlserver         | 	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:281)
metabase-sqlserver         | 	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:310)
metabase-sqlserver         | 	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:306)
metabase-sqlserver         | 	at metabase.driver.sql_jdbc$fn__111365.invokeStatic(sql_jdbc.clj:43)
metabase-sqlserver         | 	at metabase.driver.sql_jdbc$fn__111365.invoke(sql_jdbc.clj:41)
metabase-sqlserver         | 	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
metabase-sqlserver         | 	at metabase.driver.util$can_connect_with_details_QMARK_$fn__46839.invoke(util.clj:144)
metabase-sqlserver         | 	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
metabase-sqlserver         | 	at clojure.lang.AFn.call(AFn.java:18)
metabase-sqlserver         | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
metabase-sqlserver         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
metabase-sqlserver         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
metabase-sqlserver         | 	... 1 more
metabase-sqlserver         | 2023-04-03 23:32:49,934 DEBUG middleware.log :: PUT /api/database/4 400 11.6 ms (3 DB calls) 
metabase-sqlserver         | {:message "Assert failed: (integer? port)"}
```
</details>

**To Reproduce**
1) Connect Metabase to a SQL server, leave the port blank
2) Now do the same, but using a bastion host, you cannot leave the port blank

**Expected behavior**
You should be able to leave the port blank to use dynamic ports

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Your databases: MS SQL
- Metabase version: Testing in 46, but surely this comes from few versions below

**Severity**
P3, you can use fixed ports

**Additional context**
I think this is due that the only driver that you can leave the port box empty is SQL server, so that might be the reason why it breaks when using SSL

**Comment by paoliniluis** [comment]
same happens with MongoDB with SSH if you don't enter the port

**Comment by technomancy** [comment]
According to Microsoft's documentation, dynamic ports cause connection problems when using a firewall:

> Using dynamic ports complicates connecting SQL Server through a firewall because the port number might change when SQL Server is restarted, requiring changes to the firewall settings. To avoid connection problems through a firewall, configure SQL Server to use a static port.

I believe the same logic applies to SSH tunnels; you have to know the port ahead of time to set up the tunnel. It seems to be incompatible with dynamic ports, and requires using a fixed port.

https://learn.microsoft.com/en-us/sql/tools/configuration-manager/tcp-ip-properties-ip-addresses-tab?view=sql-server-ver17
