### ISSUE TITLE
[CI] Flake in migrate-field-database-type-test

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#29919]
Stacktrace: 
```
FAIL in metabase.db.schema-migrations-test/migrate-field-database-type-test (schema_migrations_test.clj:1000)
Migration v47.00-001: set base-type to type/JSON for JSON database-types for postgres and mysql Migrations v47.00-001 thru end 
:mysql Rollback restores the original state (= :type/Structured (get new-base-types pg-field-1-id))
expected: :type/Structured
  actual: :type/JSON


FAIL in metabase.db.schema-migrations-test/migrate-field-database-type-test (schema_migrations_test.clj:1000)
Migration v47.00-001: set base-type to type/JSON for JSON database-types for postgres and mysql Migrations v47.00-001 thru end 
:mysql Rollback restores the original state (= :type/Structured (get new-base-types pg-field-2-id))
expected: :type/Structured
  actual: :type/JSON


FAIL in metabase.db.schema-migrations-test/migrate-field-database-type-test (schema_migrations_test.clj:1000)
Migration v47.00-001: set base-type to type/JSON for JSON database-types for postgres and mysql Migrations v47.00-001 thru end 
:mysql Rollback restores the original state (= :type/SerializedJSON (get new-base-types mysql-field-1-id))
expected: :type/SerializedJSON
  actual: :type/JSON

Created a new logger for metabase.email
ERROR TypeError: Cannot read property 'table.column_formatting' of null
[main] TRACE metabase.email.messages - NOT including CSV attachment for Card "card-name" because less than 10 rows in results
Created a new logger for metabase.logger
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: Series A, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.<anonymous> (lib-static-viz.bundle.js:2:807264)
    at lib-static-viz.bundle.js:2:827499
    at lib-static-viz.bundle.js:2:827347
    at hK (lib-static-viz.bundle.js:2:827245)
    at HK (lib-static-viz.bundle.js:2:828123)
    at Function.a (lib-static-viz.bundle.js:2:805049)
    at bb (lib-static-viz.bundle.js:2:2872832)
    at Fc (lib-static-viz.bundle.js:2:2881096)
    at Pc (lib-static-viz.bundle.js:2:2890086)
    at lib-static-viz.bundle.js:2:2980293
```

**Comment by calherries** [comment]
I can reproduce this locally about 1/5 times I run the test for MySQL
