### ISSUE TITLE
Downgrade from fresh install of v1.46.1 to v1.45.3.1 fails

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#30053]
**Describe the bug**
Downgrading from v1.46.1 to v1.45.3.1 fails.

**Logs**
```
2023-04-12 12:51:01 2023-04-12 18:51:01,611 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2023-04-12 12:51:01 2023-04-12 18:51:01,622 INFO db.setup :: Verifying postgres Database Connection ...
2023-04-12 12:51:02 2023-04-12 18:51:02,001 INFO db.setup :: Successfully verified PostgreSQL 11.18 (Debian 11.18-1.pgdg110+1) application database connection. ✅
2023-04-12 12:51:02 2023-04-12 18:51:02,003 INFO db.setup :: Running Database Migrations...
2023-04-12 12:51:02 2023-04-12 18:51:02,006 INFO db.setup :: Setting up Liquibase...
2023-04-12 12:51:02 2023-04-12 18:51:02,748 INFO db.setup :: Liquibase is ready.
2023-04-12 12:51:02 2023-04-12 18:51:02,749 INFO db.liquibase :: Checking if Database has unrun migrations...
2023-04-12 12:51:03 2023-04-12 18:51:03,825 ERROR metabase.core :: Metabase Initialization FAILED
2023-04-12 12:51:03 liquibase.exception.ValidationFailedException: Validation Failed:
2023-04-12 12:51:03      5 change sets check sum
2023-04-12 12:51:03           migrations/000_migrations.yaml::311::howonlee was: 8:33f9d29d709afd0c02bd47367c7d9181 but is now: 8:a26e31914822a5176848abbb7c5415bd
2023-04-12 12:51:03           migrations/000_migrations.yaml::v43.00-008::camsaul was: 8:86b57754999f0ec4b331f4f3ac98a2e0 but is now: 8:32b1397273c60028aa633d23428527ef
2023-04-12 12:51:03           migrations/000_migrations.yaml::v43.00-009::camsaul was: 8:9dffa1da7ad8f84a12794bc7c96c15e7 but is now: 8:4042df2ae3ac452a896df3cd5f7a839e
2023-04-12 12:51:03           migrations/000_migrations.yaml::v43.00-010::camsaul was: 8:5eedafb824c5e636c7ff14fc7922ca4a but is now: 8:a26d3c4c474c13897e0d8a677b7443ae
2023-04-12 12:51:03           migrations/000_migrations.yaml::v43.00-011::camsaul was: 8:2c62d31bec1c6281d02ec41444c5932e but is now: 8:5760bcc26e036a34e918cf5eecd109ee
2023-04-12 12:51:03 
2023-04-12 12:51:03 at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:296)
2023-04-12 12:51:03 at liquibase.Liquibase$16.run(Liquibase.java:1988)
2023-04-12 12:51:03 at liquibase.Scope.lambda$child$0(Scope.java:180)
2023-04-12 12:51:03 at liquibase.Scope.child(Scope.java:189)
2023-04-12 12:51:03 at liquibase.Scope.child(Scope.java:179)
2023-04-12 12:51:03 at liquibase.Scope.child(Scope.java:158)
2023-04-12 12:51:03 at liquibase.Liquibase.runInScope(Liquibase.java:2405)
2023-04-12 12:51:03 at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1978)
2023-04-12 12:51:03 at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1969)
2023-04-12 12:51:03 at metabase.db.liquibase$has_unrun_migrations_QMARK_.invokeStatic(liquibase.clj:110)
2023-04-12 12:51:03 at metabase.db.liquibase$has_unrun_migrations_QMARK_.invoke(liquibase.clj:100)
2023-04-12 12:51:03 at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:135)
2023-04-12 12:51:03 at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:131)
2023-04-12 12:51:03 at metabase.db.setup$fn__36347$migrate_BANG___36352$fn__36353$fn__36354.invoke(setup.clj:67)
2023-04-12 12:51:03 at metabase.db.liquibase$fn__33068$do_with_liquibase__33073$fn__33074.invoke(liquibase.clj:60)
2023-04-12 12:51:03 at metabase.db.liquibase$fn__33068$do_with_liquibase__33073.invoke(liquibase.clj:52)
2023-04-12 12:51:03 at metabase.db.setup$fn__36347$migrate_BANG___36352$fn__36353.invoke(setup.clj:62)
2023-04-12 12:51:03 at metabase.db.setup$fn__36347$migrate_BANG___36352.doInvoke(setup.clj:40)
2023-04-12 12:51:03 at clojure.lang.RestFn.invoke(RestFn.java:445)
2023-04-12 12:51:03 at metabase.db.setup$fn__36406$run_schema_migrations_BANG___36411$fn__36412.invoke(setup.clj:120)
2023-04-12 12:51:03 at metabase.db.setup$fn__36406$run_schema_migrations_BANG___36411.invoke(setup.clj:114)
2023-04-12 12:51:03 at metabase.db.setup$fn__36458$setup_db_BANG___36463$fn__36464$fn__36467$fn__36468.invoke(setup.clj:146)
2023-04-12 12:51:03 at metabase.util$do_with_us_locale.invokeStatic(util.clj:707)
2023-04-12 12:51:03 at metabase.util$do_with_us_locale.invoke(util.clj:693)
2023-04-12 12:51:03 at metabase.db.setup$fn__36458$setup_db_BANG___36463$fn__36464$fn__36467.invoke(setup.clj:144)
2023-04-12 12:51:03 at metabase.db.setup$fn__36458$setup_db_BANG___36463$fn__36464.invoke(setup.clj:143)
2023-04-12 12:51:03 at metabase.db.setup$fn__36458$setup_db_BANG___36463.invoke(setup.clj:137)
2023-04-12 12:51:03 at metabase.db$setup_db_BANG_$fn__36493.invoke(db.clj:65)
2023-04-12 12:51:03 at metabase.db$setup_db_BANG_.invokeStatic(db.clj:60)
2023-04-12 12:51:03 at metabase.db$setup_db_BANG_.invoke(db.clj:51)
2023-04-12 12:51:03 at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:101)
2023-04-12 12:51:03 at metabase.core$init_BANG__STAR_.invoke(core.clj:87)
2023-04-12 12:51:03 at metabase.core$init_BANG_.invokeStatic(core.clj:144)
2023-04-12 12:51:03 at metabase.core$init_BANG_.invoke(core.clj:139)
2023-04-12 12:51:03 at metabase.core$start_normally.invokeStatic(core.clj:156)
2023-04-12 12:51:03 at metabase.core$start_normally.invoke(core.clj:150)
2023-04-12 12:51:03 at metabase.core$_main.invokeStatic(core.clj:189)
2023-04-12 12:51:03 at metabase.core$_main.doInvoke(core.clj:183)
2023-04-12 12:51:03 at clojure.lang.RestFn.invoke(RestFn.java:397)
2023-04-12 12:51:03 at clojure.lang.AFn.applyToHelper(AFn.java:152)
2023-04-12 12:51:03 at clojure.lang.RestFn.applyTo(RestFn.java:132)
2023-04-12 12:51:03 at clojure.lang.Var.applyTo(Var.java:705)
2023-04-12 12:51:03 at clojure.core$apply.invokeStatic(core.clj:667)
2023-04-12 12:51:03 at clojure.core$apply.invoke(core.clj:662)
2023-04-12 12:51:03 at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:25)
2023-04-12 12:51:03 at metabase.bootstrap$_main.doInvoke(bootstrap.clj:22)
2023-04-12 12:51:03 at clojure.lang.RestFn.invoke(RestFn.java:397)
2023-04-12 12:51:03 at clojure.lang.AFn.applyToHelper(AFn.java:152)
2023-04-12 12:51:03 at clojure.lang.RestFn.applyTo(RestFn.java:132)
2023-04-12 12:51:03 at metabase.bootstrap.main(Unknown Source)
2023-04-12 12:51:03 2023-04-12 18:51:03,838 INFO metabase.core :: Metabase Shutting Down ...
2023-04-12 12:51:03 2023-04-12 18:51:03,840 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2023-04-12 12:51:03 2023-04-12 18:51:03,855 INFO metabase.core :: Metabase Shutdown COMPLETE

```

**To Reproduce**
Steps to reproduce the behavior (if you can reproduce the bug using the Sample Database, we will find the issue faster):
1. Create a new install of Metabase v1.46.1
2. Do the Metabase setup adding the first admin user account.
3. Run `migrate down` against the database using Metabase v1.46.1
4. Shutdown Metabase and run Metabase v1.45.3.1 on the same application database
5. See error

**Expected behavior**
- Expect to be able to migrate down from 46.1 to 45.3.1

**Severity**
- may not be relevant after 46.2 or 46.3, etc.

**Comment by likeshumidity** [comment]
Closing because works for existing install. Only breaks for fresh install which should not be downgraded. Should only downgrade after an upgrade.
