### ISSUE TITLE
Model caching not working anymore in 0.46.x with MySQL if query takes more than 29 seconds

### ISSUE THREAD

**Issue by prigal** [metabase/metabase#30723]
### Describe the bug

After upgrading to 0.46.x (tested with .1 and .2) models are not refreshing anymore.

"Killed mysql process id XXXX due to timeout"

Discussion : https://discourse.metabase.com/t/v46-1-timeout-issues/24722/19 

We rolled back to 0.45.x as long questions are based on models and they are not refreshing anymore.

### To Reproduce

1. Upgrade to 0.46.x
2. Refresh a model

### Expected behavior

That should not timeout.

### Logs

```
[43de1631-682e-4aad-b231-03a36fa5cbb9] 2023-05-05T10:20:36+02:00 INFO metabase.task.persist-refresh Erreur de rafraîchissement du modèle persisté avec card-id 651
java.lang.Exception: ID de processus mysql 14 011 tué en raison d'un délai d'attente.
	at metabase.driver.mysql.ddl$kill.invokeStatic(ddl.clj:43)
	at metabase.driver.mysql.ddl$kill.invoke(ddl.clj:34)
	at metabase.driver.mysql.ddl$execute_with_timeout_BANG_.invokeStatic(ddl.clj:56)
	at metabase.driver.mysql.ddl$execute_with_timeout_BANG_.invoke(ddl.clj:45)
	at metabase.driver.mysql.ddl$fn__103034.invokeStatic(ddl.clj:69)
	at metabase.driver.mysql.ddl$fn__103034.invoke(ddl.clj:62)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.task.persist_refresh$reify__79265.refresh_BANG_(persist_refresh.clj:65)
	at metabase.task.persist_refresh$refresh_with_stats_BANG_$fn__79268.invoke(persist_refresh.clj:85)
	at metabase.task.persist_refresh$refresh_with_stats_BANG_.invokeStatic(persist_refresh.clj:84)
	at metabase.task.persist_refresh$refresh_with_stats_BANG_.invoke(persist_refresh.clj:69)
	at clojure.core$partial$fn__5910.invoke(core.clj:2649)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.task.persist_refresh$refresh_tables_BANG_$thunk__79295.invoke(persist_refresh.clj:207)
	at metabase.task.persist_refresh$save_task_history_BANG_.invokeStatic(persist_refresh.clj:108)
	at metabase.task.persist_refresh$save_task_history_BANG_.invoke(persist_refresh.clj:103)
	at metabase.task.persist_refresh$refresh_tables_BANG_.invokeStatic(persist_refresh.clj:210)
	at metabase.task.persist_refresh$refresh_tables_BANG_.invoke(persist_refresh.clj:198)
	at metabase.task.persist_refresh$refresh_job_fn_BANG_.invokeStatic(persist_refresh.clj:238)
	at metabase.task.persist_refresh$refresh_job_fn_BANG_.invoke(persist_refresh.clj:233)
	at metabase.task.persist_refresh.PersistenceRefresh.execute(persist_refresh.clj:249)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10",
    "os.name": "Linux",
    "os.version": "4.15.18-2-pve",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-03-29",
      "tag": "v0.45.3.1",
      "branch": "release-x.45.x",
      "hash": "3b3097d"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking

### Additional context

Our mysql version is 5.5.50-log.
Database is a slave from a master/slave config. Size is 100Gb, metabase is connected to the slave.
Cache database (with models) size is 1Gb.
Models take 3 to 4min to run on 0.45.3.1.

About collation :

collation_connection | utf8mb4_general_ci
-- | --
collation_database | latin1_swedish_ci
collation_server | latin1_swedish_ci

About timeouts :

connect_timeout | 10
-- | --
delayed_insert_timeout | 300
innodb_lock_wait_timeout | 50
innodb_rollback_on_timeout | OFF
interactive_timeout | 28800
lock_wait_timeout | 31536000
net_read_timeout | 30
net_write_timeout | 60
slave_net_timeout | 3600
wait_timeout | 28800

**Comment by paoliniluis** [comment]
Introduced by https://github.com/metabase/metabase/pull/27858

**Comment by paoliniluis** [comment]
https://github.com/metabase/metabase/blob/d550a27e5ecb7b21a5e7669cbea0495a1f2f9d50/src/metabase/driver/mysql/ddl.clj#L71

**Comment by paoliniluis** [comment]
Fixed with https://github.com/metabase/metabase/pull/31104
