### ISSUE TITLE
can't  npm build  

### ISSUE THREAD

**Issue by xingzhefeng** [metabase/metabase#3098]
If this is a bug report, please fill in the blanks:

*  I am using the _chrome  browser.
*  My computer's OS is  win10.
*  I'm running Metabase ______idea_____ [locally from the JAR / locally with the Mac App / on AWS / on Herkou / etc.] and it is using the ____h2_______ [Postgres / MySQL / H2 (default)] database.
*  My data is in a _______h2____ database. [Postgres / MySQL / Redshift / BigQuery / MongoDB / SQLite / SQL Server / etc.]
*  My Metabase version is _____git lasteset___.

***********************************************************
can't  npm build 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\hasee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-hot' ]
2 info using npm@2.15.9
3 info using node@v4.4.7
4 verbose run-script [ 'prebuild-hot', 'build-hot', 'postbuild-hot' ]
5 info prebuild-hot metabase@0.0.0
6 info build-hot metabase@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info metabase@0.0.0 Failed to exec build-hot script
9 verbose stack Error: metabase@0.0.0 build-hot: `NODE_ENV=hot webpack && NODE_ENV=hot webpack-dev-server --hot --inline --content-base frontend`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Users\hasee\AppData\Roaming\npm\node_modules\.npm_npminstall\node_modules\.npm@2.15.9\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Users\hasee\AppData\Roaming\npm\node_modules\.npm_npminstall\node_modules\.npm@2.15.9\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid metabase@0.0.0
11 verbose cwd D:\clojure\luminusweb\metabase\frontend
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hasee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-hot"
14 error node v4.4.7
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error metabase@0.0.0 build-hot: `NODE_ENV=hot webpack && NODE_ENV=hot webpack-dev-server --hot --inline --content-base frontend`
17 error Exit status 1
18 error Failed at the metabase@0.0.0 build-hot script 'NODE_ENV=hot webpack && NODE_ENV=hot webpack-dev-server --hot --inline --content-base frontend'.
18 error This is most likely a problem with the metabase package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     NODE_ENV=hot webpack && NODE_ENV=hot webpack-dev-server --hot --inline --content-base frontend
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs metabase
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls metabase
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by xingzhefeng** [comment]
.... cnpm install  is ok . sorry
