### ISSUE TITLE
Model actions ignore PK set in model's metadata if PK isn't defined on a table level

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#31918]
### Describe the bug

This is the root cause behind #31867.
CSV uploads only exposed the underlying issue, since they didn't come with the explicit primary key.

I'm opening a separate issue because the implications are possibly wider than just the CSV uploads.
Fixing this issue should immediately fix #31867!

### To Reproduce

1. Go to Admin Settings > Data Model (Table Metadata)
2. Choose `People` table from the Sample Database
3. Change its `id` column from `Entity key` to `No semantic type`
![image](https://github.com/metabase/metabase/assets/31325167/1e3be888-a5de-4b88-b326-e8ff6fb63674)

4. Create a new model based on the People table and save it.
5. IF NEEDED, edit model's metadata and set the `id` column to "Entity Key" [^1] and save
![image](https://github.com/metabase/metabase/assets/31325167/30d54037-6e00-4086-b509-80889975836d)

6. Go to model actions (`/model/:id/detail/actions`)
7. Create basic actions
8. Click on **Update** action and set the `id=2`, `Name=Foo`
9. Click on the Update button 
10. You will see inline error printed in UI `Must execute implicit action on a table with a single primary key.`
11. Click cancel to get rid of the modal
12. Click on **Delete** action and you'll see "Something went wrong" even before you've had the opportunity to enter the row `id` value

[^1]: I've seen mixed results locally. It sometimes immediately recognizes the column as the primary key and I sometimes have to explicitly edit the metadata.

### Expected behavior

If you edit model's metadata and you set the column type to PK, actions should work on such model.

### Logs

```
utils.ts:160

Uncaught TypeError: Cannot read properties of null (reading 'forEach')
    at generateFieldSettingsFromParameters (utils.ts:160:1)
    at getOrGenerateFieldSettings (utils.ts:134:1)
    at use-action-form.ts:26:1
    at mountMemo (react-dom.development.js:15442:1)
    at Object.useMemo (react-dom.development.js:15738:1)
    at useMemo (react.development.js:1521:1)
    at useActionForm (use-action-form.ts:25:1)
    at ActionForm (ActionForm.tsx:53:1)
    at renderWithHooks (react-dom.development.js:14803:1)
    at mountIndeterminateComponent (react-dom.development.js:17482:1)


The above error occurred in the <ActionForm> component:
```

### Information about your Metabase installation

```JSON
local dev, `master`, bc868a0, H2, Sample Database

Tested on 47-RC1 and on 46.3.
This most likely never worked but we didn't catch it before.
```

### Severity

P1

### Additional context

This might be considered a duplicate of #31867.
If we need to close one of these two issues, let's close the other one and leave this one open as it is the root.

**Comment by ranquild** [comment]
I think we should fix the FE so it doesn't crash. After that reassign the issue to QPD.

**Comment by ranquild** [comment]
I think it's the same issue https://github.com/metabase/metabase/issues/32665. The BE sometimes sends `parameters: null` for implicit actions and we don't expect this. To confirm. If that's the case, we need to fix it on the BE.

**Comment by kamilmielnik** [comment]
> 7. Create basic actions

I wanted to check if this is frontend or backend issue, but today in `master` (a6544c6cae3d72323748816c7ea5ea46bcf51fb1) it's not possible to go through this step.

The "Create basic actions" button is not shown, because `supportsImplicitActions` function does not find any PK fields.
I think it's because result of GET `/api/card/:id/query_metadata` (where ID field will have `semantic_type` set to `null`) takes precedence over `results_metadata` from GET `/api/card/:id` (where ID field will have `semantic_type` set to `type/PK`).

It looks like a regression. I'm labeling it as frontend issue, at least until this new problem is resolved.
