### ISSUE TITLE
"Error getting setting graph.x_axis._is_histogram"

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#31916]
### Describe the bug

When attempting to click on the title of the chart "Active Installs, past 6 months" on our "Company Stats" dashboard in our internal stats instance, nothing happens. 

### To Reproduce

Go to the "Company Stats" dashboard on our internal stats instance and attempt to click on the title of the chart "Active Installs, past 6 months." Nothing happens.

### Expected behavior

You should be taken to that question when clicking on its title.

### Logs

The JS error reads:
```settings.js:110 Error getting setting graph.x_axis._is_histogram TypeError: Cannot read properties of undefined (reading 'binning_info')
    at Object.getDefault (graph.js:506:15)
    at ft (settings.js:101:39)
    at st (settings.js:42:5)
    at j (visualization.js:87:10)
    at u.value (Visualization.jsx:145:9)
    at u.value (Visualization.jsx:94:12)
    at wo (react-dom.production.min.js:135:172)
    at ja (react-dom.production.min.js:179:157)
    at Os (react-dom.production.min.js:263:490)
    at mc (react-dom.production.min.js:246:265)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.4.209-116.367.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "druid",
      "postgres",
      "redshift",
      "mysql",
      "bigquery-cloud-sdk",
      "mongo",
      "googleanalytics",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-27",
      "tag": "vUNKNOWN",
      "branch": "master",
      "hash": "220156d"
    },
    "settings": {
      "report-timezone": "US/Pacific"
    }
  }
}
```

### Severity

P2 — I can still click on "Edit this question" from the ellipses menu, but I can't see my chart in my dashboard.

**Comment by darksciencebase** [comment]
AlexP [said](https://metaboat.slack.com/archives/C057T1QTB3L/p1687882648576039?thread_ts=1687882409.622849&cid=C057T1QTB3L) it could be viz-related

**Comment by EmmadUsmani** [comment]
It is resolved on stats now (as of July 5th, 2023). The question is still broken on my local stats dump (taken on June 30th, 2023), so I'm guessing there was some issue with the underlying database table that is now resolved.
