### ISSUE TITLE
Presto driver connected to Trino doesn't like decimal types

### ISSUE THREAD

**Issue by dragonsahead** [metabase/metabase#31989]
### Describe the bug

If you have a table in any data warehouse under a Trino with a decimal type, queries will fail

### To Reproduce

1) create a postgres table
```
CREATE TABLE temp_table2
( campo decimal(32,18)
);

insert into temp_table2 values (1.1);
```
2) start a Trino server and connect to the Postgres table
3) connect Metabase to Trino
4) go to the table, see it failing the query

### Expected behavior

I still don't know if this is a driver issue (seems like) or a Trino issue

### Logs

```
<details>
metabase-presto-and-trino        | 2023-06-29 13:20:45,275 ERROR middleware.catch-exceptions :: Error processing query: Error executing query
metabase-presto-and-trino        | {:database_id 8,
metabase-presto-and-trino        |  :started_at #t "2023-06-29T13:20:45.023665Z[Etc/UTC]",
metabase-presto-and-trino        |  :via
metabase-presto-and-trino        |  [{:status :failed,
metabase-presto-and-trino        |    :class java.sql.SQLException,
metabase-presto-and-trino        |    :error "Error executing query",
metabase-presto-and-trino        |    :stacktrace
metabase-presto-and-trino        |    ["com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:307)"
metabase-presto-and-trino        |     "com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:230)"
metabase-presto-and-trino        |     "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
metabase-presto-and-trino        |     "--> driver.sql_jdbc.execute$fn__78695.invokeStatic(execute.clj:549)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$fn__78695.invoke(execute.clj:547)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:557)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:554)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_reducible_query$fn__78770$fn__78771.invoke(execute.clj:672)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_reducible_query$fn__78770.invoke(execute.clj:671)"
metabase-presto-and-trino        |     "driver.presto_jdbc$fn__122686$fn__122687.invoke(presto_jdbc.clj:695)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$fn__78543$do_with_resolved_connection__78544.invoke(execute.clj:334)"
metabase-presto-and-trino        |     "driver.presto_jdbc$fn__122686.invokeStatic(presto_jdbc.clj:688)"
metabase-presto-and-trino        |     "driver.presto_jdbc$fn__122686.invoke(presto_jdbc.clj:675)"
metabase-presto-and-trino        |     "driver.presto_jdbc$fn__122686.invokeStatic(presto_jdbc.clj:682)"
metabase-presto-and-trino        |     "driver.presto_jdbc$fn__122686.invoke(presto_jdbc.clj:675)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:665)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:654)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:662)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:654)"
metabase-presto-and-trino        |     "driver.sql_jdbc$fn__121444.invokeStatic(sql_jdbc.clj:72)"
metabase-presto-and-trino        |     "driver.sql_jdbc$fn__121444.invoke(sql_jdbc.clj:70)"
metabase-presto-and-trino        |     "query_processor.context$executef.invokeStatic(context.clj:60)"
metabase-presto-and-trino        |     "query_processor.context$executef.invoke(context.clj:49)"
metabase-presto-and-trino        |     "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
metabase-presto-and-trino        |     "query_processor.context.default$default_runf.invoke(default.clj:66)"
metabase-presto-and-trino        |     "query_processor.context$runf.invokeStatic(context.clj:46)"
metabase-presto-and-trino        |     "query_processor.context$runf.invoke(context.clj:40)"
metabase-presto-and-trino        |     "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15)"
metabase-presto-and-trino        |     "query_processor.reducible$identity_qp.invoke(reducible.clj:12)"
metabase-presto-and-trino        |     "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___76313.invoke(cache.clj:224)"
metabase-presto-and-trino        |     "query_processor.middleware.permissions$check_query_permissions$fn__71898.invoke(permissions.clj:126)"
metabase-presto-and-trino        |     "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__115432.invoke(permissions.clj:128)"
metabase-presto-and-trino        |     "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__116777.invoke(column_level_perms_check.clj:31)"
metabase-presto-and-trino        |     "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__75438.invoke(mbql_to_native.clj:24)"
metabase-presto-and-trino        |     "query_processor$fn__77546$combined_post_process__77551$combined_post_process_STAR___77552.invoke(query_processor.clj:260)"
metabase-presto-and-trino        |     "query_processor$fn__77546$combined_pre_process__77547$combined_pre_process_STAR___77548.invoke(query_processor.clj:257)"
metabase-presto-and-trino        |     "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76224$fn__76229.invoke(resolve_database_and_driver.clj:36)"
metabase-presto-and-trino        |     "driver$do_with_driver.invokeStatic(driver.clj:91)"
metabase-presto-and-trino        |     "driver$do_with_driver.invoke(driver.clj:86)"
metabase-presto-and-trino        |     "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76224.invoke(resolve_database_and_driver.clj:35)"
metabase-presto-and-trino        |     "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__72208.invoke(fetch_source_query.clj:316)"
metabase-presto-and-trino        |     "query_processor.middleware.store$initialize_store$fn__72389$fn__72390.invoke(store.clj:12)"
metabase-presto-and-trino        |     "query_processor.store$do_with_store.invokeStatic(store.clj:56)"
metabase-presto-and-trino        |     "query_processor.store$do_with_store.invoke(store.clj:50)"
metabase-presto-and-trino        |     "query_processor.middleware.store$initialize_store$fn__72389.invoke(store.clj:11)"
metabase-presto-and-trino        |     "query_processor.middleware.normalize_query$normalize$fn__76520.invoke(normalize_query.clj:36)"
metabase-presto-and-trino        |     "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__82990.invoke(handle_audit_queries.clj:131)"
metabase-presto-and-trino        |     "query_processor.middleware.constraints$add_default_userland_constraints$fn__73914.invoke(constraints.clj:54)"
metabase-presto-and-trino        |     "query_processor.middleware.process_userland_query$process_userland_query$fn__76449.invoke(process_userland_query.clj:151)"
metabase-presto-and-trino        |     "query_processor.middleware.catch_exceptions$catch_exceptions$fn__76846.invoke(catch_exceptions.clj:171)"
metabase-presto-and-trino        |     "query_processor.reducible$async_qp$qp_STAR___66406$thunk__66408.invoke(reducible.clj:103)"
metabase-presto-and-trino        |     "query_processor.reducible$async_qp$qp_STAR___66406.invoke(reducible.clj:109)"
metabase-presto-and-trino        |     "query_processor.reducible$async_qp$qp_STAR___66406.invoke(reducible.clj:94)"
metabase-presto-and-trino        |     "query_processor.reducible$sync_qp$qp_STAR___66418.doInvoke(reducible.clj:129)"
metabase-presto-and-trino        |     "query_processor$process_userland_query.invokeStatic(query_processor.clj:383)"
metabase-presto-and-trino        |     "query_processor$process_userland_query.doInvoke(query_processor.clj:379)"
metabase-presto-and-trino        |     "query_processor$fn__77595$process_query_and_save_execution_BANG___77604$fn__77607.invoke(query_processor.clj:394)"
metabase-presto-and-trino        |     "query_processor$fn__77595$process_query_and_save_execution_BANG___77604.invoke(query_processor.clj:387)"
metabase-presto-and-trino        |     "query_processor$fn__77640$process_query_and_save_with_max_results_constraints_BANG___77649$fn__77652.invoke(query_processor.clj:406)"
metabase-presto-and-trino        |     "query_processor$fn__77640$process_query_and_save_with_max_results_constraints_BANG___77649.invoke(query_processor.clj:399)"
metabase-presto-and-trino        |     "api.dataset$run_query_async$fn__98377.invoke(dataset.clj:74)"
metabase-presto-and-trino        |     "query_processor.streaming$streaming_response_STAR_$fn__60952$fn__60953.invoke(streaming.clj:166)"
metabase-presto-and-trino        |     "query_processor.streaming$streaming_response_STAR_$fn__60952.invoke(streaming.clj:165)"
metabase-presto-and-trino        |     "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
metabase-presto-and-trino        |     "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
metabase-presto-and-trino        |     "async.streaming_response$do_f_async$task__39730.invoke(streaming_response.clj:88)"],
metabase-presto-and-trino        |    :state nil}
metabase-presto-and-trino        |   {:status :failed,
metabase-presto-and-trino        |    :class clojure.lang.ExceptionInfo,
metabase-presto-and-trino        |    :error "Error executing query: Error executing query",
metabase-presto-and-trino        |    :stacktrace
metabase-presto-and-trino        |    ["--> driver.sql_jdbc.execute$execute_reducible_query$fn__78770$fn__78771.invoke(execute.clj:674)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_reducible_query$fn__78770.invoke(execute.clj:671)"
metabase-presto-and-trino        |     "driver.presto_jdbc$fn__122686$fn__122687.invoke(presto_jdbc.clj:695)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$fn__78543$do_with_resolved_connection__78544.invoke(execute.clj:334)"
metabase-presto-and-trino        |     "driver.presto_jdbc$fn__122686.invokeStatic(presto_jdbc.clj:688)"
metabase-presto-and-trino        |     "driver.presto_jdbc$fn__122686.invoke(presto_jdbc.clj:675)"
metabase-presto-and-trino        |     "driver.presto_jdbc$fn__122686.invokeStatic(presto_jdbc.clj:682)"
metabase-presto-and-trino        |     "driver.presto_jdbc$fn__122686.invoke(presto_jdbc.clj:675)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:665)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:654)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:662)"
metabase-presto-and-trino        |     "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:654)"
metabase-presto-and-trino        |     "driver.sql_jdbc$fn__121444.invokeStatic(sql_jdbc.clj:72)"
metabase-presto-and-trino        |     "driver.sql_jdbc$fn__121444.invoke(sql_jdbc.clj:70)"
metabase-presto-and-trino        |     "query_processor.context$executef.invokeStatic(context.clj:60)"
metabase-presto-and-trino        |     "query_processor.context$executef.invoke(context.clj:49)"
metabase-presto-and-trino        |     "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
metabase-presto-and-trino        |     "query_processor.context.default$default_runf.invoke(default.clj:66)"
metabase-presto-and-trino        |     "query_processor.context$runf.invokeStatic(context.clj:46)"
metabase-presto-and-trino        |     "query_processor.context$runf.invoke(context.clj:40)"
metabase-presto-and-trino        |     "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15)"
metabase-presto-and-trino        |     "query_processor.reducible$identity_qp.invoke(reducible.clj:12)"
metabase-presto-and-trino        |     "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___76313.invoke(cache.clj:224)"
metabase-presto-and-trino        |     "query_processor.middleware.permissions$check_query_permissions$fn__71898.invoke(permissions.clj:126)"
metabase-presto-and-trino        |     "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__115432.invoke(permissions.clj:128)"
metabase-presto-and-trino        |     "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__116777.invoke(column_level_perms_check.clj:31)"
metabase-presto-and-trino        |     "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__75438.invoke(mbql_to_native.clj:24)"
metabase-presto-and-trino        |     "query_processor$fn__77546$combined_post_process__77551$combined_post_process_STAR___77552.invoke(query_processor.clj:260)"
metabase-presto-and-trino        |     "query_processor$fn__77546$combined_pre_process__77547$combined_pre_process_STAR___77548.invoke(query_processor.clj:257)"
metabase-presto-and-trino        |     "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76224$fn__76229.invoke(resolve_database_and_driver.clj:36)"
metabase-presto-and-trino        |     "driver$do_with_driver.invokeStatic(driver.clj:91)"
metabase-presto-and-trino        |     "driver$do_with_driver.invoke(driver.clj:86)"
metabase-presto-and-trino        |     "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76224.invoke(resolve_database_and_driver.clj:35)"
metabase-presto-and-trino        |     "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__72208.invoke(fetch_source_query.clj:316)"
metabase-presto-and-trino        |     "query_processor.middleware.store$initialize_store$fn__72389$fn__72390.invoke(store.clj:12)"
metabase-presto-and-trino        |     "query_processor.store$do_with_store.invokeStatic(store.clj:56)"
metabase-presto-and-trino        |     "query_processor.store$do_with_store.invoke(store.clj:50)"
metabase-presto-and-trino        |     "query_processor.middleware.store$initialize_store$fn__72389.invoke(store.clj:11)"
metabase-presto-and-trino        |     "query_processor.middleware.normalize_query$normalize$fn__76520.invoke(normalize_query.clj:36)"
metabase-presto-and-trino        |     "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__82990.invoke(handle_audit_queries.clj:131)"
metabase-presto-and-trino        |     "query_processor.middleware.constraints$add_default_userland_constraints$fn__73914.invoke(constraints.clj:54)"
metabase-presto-and-trino        |     "query_processor.middleware.process_userland_query$process_userland_query$fn__76449.invoke(process_userland_query.clj:151)"
metabase-presto-and-trino        |     "query_processor.middleware.catch_exceptions$catch_exceptions$fn__76846.invoke(catch_exceptions.clj:171)"
metabase-presto-and-trino        |     "query_processor.reducible$async_qp$qp_STAR___66406$thunk__66408.invoke(reducible.clj:103)"
metabase-presto-and-trino        |     "query_processor.reducible$async_qp$qp_STAR___66406.invoke(reducible.clj:109)"
metabase-presto-and-trino        |     "query_processor.reducible$async_qp$qp_STAR___66406.invoke(reducible.clj:94)"
metabase-presto-and-trino        |     "query_processor.reducible$sync_qp$qp_STAR___66418.doInvoke(reducible.clj:129)"
metabase-presto-and-trino        |     "query_processor$process_userland_query.invokeStatic(query_processor.clj:383)"
metabase-presto-and-trino        |     "query_processor$process_userland_query.doInvoke(query_processor.clj:379)"
metabase-presto-and-trino        |     "query_processor$fn__77595$process_query_and_save_execution_BANG___77604$fn__77607.invoke(query_processor.clj:394)"
metabase-presto-and-trino        |     "query_processor$fn__77595$process_query_and_save_execution_BANG___77604.invoke(query_processor.clj:387)"
metabase-presto-and-trino        |     "query_processor$fn__77640$process_query_and_save_with_max_results_constraints_BANG___77649$fn__77652.invoke(query_processor.clj:406)"
metabase-presto-and-trino        |     "query_processor$fn__77640$process_query_and_save_with_max_results_constraints_BANG___77649.invoke(query_processor.clj:399)"
metabase-presto-and-trino        |     "api.dataset$run_query_async$fn__98377.invoke(dataset.clj:74)"
metabase-presto-and-trino        |     "query_processor.streaming$streaming_response_STAR_$fn__60952$fn__60953.invoke(streaming.clj:166)"
metabase-presto-and-trino        |     "query_processor.streaming$streaming_response_STAR_$fn__60952.invoke(streaming.clj:165)"
metabase-presto-and-trino        |     "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
metabase-presto-and-trino        |     "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
metabase-presto-and-trino        |     "async.streaming_response$do_f_async$task__39730.invoke(streaming_response.clj:88)"],
metabase-presto-and-trino        |    :error_type :invalid-query,
metabase-presto-and-trino        |    :ex-data
metabase-presto-and-trino        |    {:driver :presto-jdbc,
metabase-presto-and-trino        |     :sql
metabase-presto-and-trino        |     ["-- Metabase:: userID: 1 queryType: MBQL queryHash: ab8e525767ffc4b384b53278724eec01e34e4e5e3cac25ce8cb83ba10db58f01"
metabase-presto-and-trino        |      "SELECT"
metabase-presto-and-trino        |      "  \"public\".\"temp_table2\".\"campo\" AS \"campo\""
metabase-presto-and-trino        |      "FROM"
metabase-presto-and-trino        |      "  \"public\".\"temp_table2\""
metabase-presto-and-trino        |      "LIMIT"
metabase-presto-and-trino        |      "  2000"],
metabase-presto-and-trino        |     :params nil,
metabase-presto-and-trino        |     :type :invalid-query}}],
metabase-presto-and-trino        |  :error_type :invalid-query,
metabase-presto-and-trino        |  :json_query
metabase-presto-and-trino        |  {:database 8,
metabase-presto-and-trino        |   :query {:source-table 50},
metabase-presto-and-trino        |   :type "query",
metabase-presto-and-trino        |   :parameters [],
metabase-presto-and-trino        |   :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
metabase-presto-and-trino        |  :native
metabase-presto-and-trino        |  {:query "SELECT \"public\".\"temp_table2\".\"campo\" AS \"campo\" FROM \"public\".\"temp_table2\" LIMIT 1048575",
metabase-presto-and-trino        |   :params nil},
metabase-presto-and-trino        |  :status :failed,
metabase-presto-and-trino        |  :class java.lang.IllegalArgumentException,
metabase-presto-and-trino        |  :stacktrace
metabase-presto-and-trino        |  ["com.facebook.presto.jdbc.internal.common.type.TypeSignatureParameter.getValue(TypeSignatureParameter.java:120)"
metabase-presto-and-trino        |   "com.facebook.presto.jdbc.internal.common.type.TypeSignatureParameter.getLongLiteral(TypeSignatureParameter.java:132)"
metabase-presto-and-trino        |   "com.facebook.presto.jdbc.ColumnInfo.setTypeInfo(ColumnInfo.java:194)"
metabase-presto-and-trino        |   "com.facebook.presto.jdbc.PrestoResultSet.getColumnInfo(PrestoResultSet.java:1869)"
metabase-presto-and-trino        |   "com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:123)"
metabase-presto-and-trino        |   "com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:272)"
metabase-presto-and-trino        |   "com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:230)"
metabase-presto-and-trino        |   "com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)"
metabase-presto-and-trino        |   "--> driver.sql_jdbc.execute$fn__78695.invokeStatic(execute.clj:549)"
metabase-presto-and-trino        |   "driver.sql_jdbc.execute$fn__78695.invoke(execute.clj:547)"
metabase-presto-and-trino        |   "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:557)"
metabase-presto-and-trino        |   "driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:554)"
metabase-presto-and-trino        |   "driver.sql_jdbc.execute$execute_reducible_query$fn__78770$fn__78771.invoke(execute.clj:672)"
metabase-presto-and-trino        |   "driver.sql_jdbc.execute$execute_reducible_query$fn__78770.invoke(execute.clj:671)"
metabase-presto-and-trino        |   "driver.presto_jdbc$fn__122686$fn__122687.invoke(presto_jdbc.clj:695)"
metabase-presto-and-trino        |   "driver.sql_jdbc.execute$fn__78543$do_with_resolved_connection__78544.invoke(execute.clj:334)"
metabase-presto-and-trino        |   "driver.presto_jdbc$fn__122686.invokeStatic(presto_jdbc.clj:688)"
metabase-presto-and-trino        |   "driver.presto_jdbc$fn__122686.invoke(presto_jdbc.clj:675)"
metabase-presto-and-trino        |   "driver.presto_jdbc$fn__122686.invokeStatic(presto_jdbc.clj:682)"
metabase-presto-and-trino        |   "driver.presto_jdbc$fn__122686.invoke(presto_jdbc.clj:675)"
metabase-presto-and-trino        |   "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:665)"
metabase-presto-and-trino        |   "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:654)"
metabase-presto-and-trino        |   "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:662)"
metabase-presto-and-trino        |   "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:654)"
metabase-presto-and-trino        |   "driver.sql_jdbc$fn__121444.invokeStatic(sql_jdbc.clj:72)"
metabase-presto-and-trino        |   "driver.sql_jdbc$fn__121444.invoke(sql_jdbc.clj:70)"
metabase-presto-and-trino        |   "query_processor.context$executef.invokeStatic(context.clj:60)"
metabase-presto-and-trino        |   "query_processor.context$executef.invoke(context.clj:49)"
metabase-presto-and-trino        |   "query_processor.context.default$default_runf.invokeStatic(default.clj:68)"
metabase-presto-and-trino        |   "query_processor.context.default$default_runf.invoke(default.clj:66)"
metabase-presto-and-trino        |   "query_processor.context$runf.invokeStatic(context.clj:46)"
metabase-presto-and-trino        |   "query_processor.context$runf.invoke(context.clj:40)"
metabase-presto-and-trino        |   "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:15)"
metabase-presto-and-trino        |   "query_processor.reducible$identity_qp.invoke(reducible.clj:12)"
metabase-presto-and-trino        |   "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___76313.invoke(cache.clj:224)"
metabase-presto-and-trino        |   "query_processor.middleware.permissions$check_query_permissions$fn__71898.invoke(permissions.clj:126)"
metabase-presto-and-trino        |   "metabase_enterprise.advanced_permissions.query_processor.middleware.permissions$check_download_permissions$fn__115432.invoke(permissions.clj:128)"
metabase-presto-and-trino        |   "metabase_enterprise.sandbox.query_processor.middleware.column_level_perms_check$maybe_apply_column_level_perms_check$fn__116777.invoke(column_level_perms_check.clj:31)"
metabase-presto-and-trino        |   "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__75438.invoke(mbql_to_native.clj:24)"
metabase-presto-and-trino        |   "query_processor$fn__77546$combined_post_process__77551$combined_post_process_STAR___77552.invoke(query_processor.clj:260)"
metabase-presto-and-trino        |   "query_processor$fn__77546$combined_pre_process__77547$combined_pre_process_STAR___77548.invoke(query_processor.clj:257)"
metabase-presto-and-trino        |   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76224$fn__76229.invoke(resolve_database_and_driver.clj:36)"
metabase-presto-and-trino        |   "driver$do_with_driver.invokeStatic(driver.clj:91)"
metabase-presto-and-trino        |   "driver$do_with_driver.invoke(driver.clj:86)"
metabase-presto-and-trino        |   "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__76224.invoke(resolve_database_and_driver.clj:35)"
metabase-presto-and-trino        |   "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__72208.invoke(fetch_source_query.clj:316)"
metabase-presto-and-trino        |   "query_processor.middleware.store$initialize_store$fn__72389$fn__72390.invoke(store.clj:12)"
metabase-presto-and-trino        |   "query_processor.store$do_with_store.invokeStatic(store.clj:56)"
metabase-presto-and-trino        |   "query_processor.store$do_with_store.invoke(store.clj:50)"
metabase-presto-and-trino        |   "query_processor.middleware.store$initialize_store$fn__72389.invoke(store.clj:11)"
metabase-presto-and-trino        |   "query_processor.middleware.normalize_query$normalize$fn__76520.invoke(normalize_query.clj:36)"
metabase-presto-and-trino        |   "metabase_enterprise.audit_app.query_processor.middleware.handle_audit_queries$handle_internal_queries$fn__82990.invoke(handle_audit_queries.clj:131)"
metabase-presto-and-trino        |   "query_processor.middleware.constraints$add_default_userland_constraints$fn__73914.invoke(constraints.clj:54)"
metabase-presto-and-trino        |   "query_processor.middleware.process_userland_query$process_userland_query$fn__76449.invoke(process_userland_query.clj:151)"
metabase-presto-and-trino        |   "query_processor.middleware.catch_exceptions$catch_exceptions$fn__76846.invoke(catch_exceptions.clj:171)"
metabase-presto-and-trino        |   "query_processor.reducible$async_qp$qp_STAR___66406$thunk__66408.invoke(reducible.clj:103)"
metabase-presto-and-trino        |   "query_processor.reducible$async_qp$qp_STAR___66406.invoke(reducible.clj:109)"
metabase-presto-and-trino        |   "query_processor.reducible$async_qp$qp_STAR___66406.invoke(reducible.clj:94)"
metabase-presto-and-trino        |   "query_processor.reducible$sync_qp$qp_STAR___66418.doInvoke(reducible.clj:129)"
metabase-presto-and-trino        |   "query_processor$process_userland_query.invokeStatic(query_processor.clj:383)"
metabase-presto-and-trino        |   "query_processor$process_userland_query.doInvoke(query_processor.clj:379)"
metabase-presto-and-trino        |   "query_processor$fn__77595$process_query_and_save_execution_BANG___77604$fn__77607.invoke(query_processor.clj:394)"
metabase-presto-and-trino        |   "query_processor$fn__77595$process_query_and_save_execution_BANG___77604.invoke(query_processor.clj:387)"
metabase-presto-and-trino        |   "query_processor$fn__77640$process_query_and_save_with_max_results_constraints_BANG___77649$fn__77652.invoke(query_processor.clj:406)"
metabase-presto-and-trino        |   "query_processor$fn__77640$process_query_and_save_with_max_results_constraints_BANG___77649.invoke(query_processor.clj:399)"
metabase-presto-and-trino        |   "api.dataset$run_query_async$fn__98377.invoke(dataset.clj:74)"
metabase-presto-and-trino        |   "query_processor.streaming$streaming_response_STAR_$fn__60952$fn__60953.invoke(streaming.clj:166)"
metabase-presto-and-trino        |   "query_processor.streaming$streaming_response_STAR_$fn__60952.invoke(streaming.clj:165)"
metabase-presto-and-trino        |   "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
metabase-presto-and-trino        |   "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
metabase-presto-and-trino        |   "async.streaming_response$do_f_async$task__39730.invoke(streaming_response.clj:88)"],
metabase-presto-and-trino        |  :card_id nil,
metabase-presto-and-trino        |  :context :ad-hoc,
metabase-presto-and-trino        |  :error "Error executing query",
metabase-presto-and-trino        |  :row_count 0,
metabase-presto-and-trino        |  :running_time 0,
metabase-presto-and-trino        |  :preprocessed
metabase-presto-and-trino        |  {:database 8,
metabase-presto-and-trino        |   :query
metabase-presto-and-trino        |   {:source-table 50,
metabase-presto-and-trino        |    :fields [[:field 545 nil]],
metabase-presto-and-trino        |    :limit 1048575,
metabase-presto-and-trino        |    :metabase.query-processor.middleware.limit/original-limit nil},
metabase-presto-and-trino        |   :type :query,
metabase-presto-and-trino        |   :middleware {:js-int-to-string? true, :add-default-userland-constraints? true},
metabase-presto-and-trino        |   :info {:executed-by 1, :context :ad-hoc}},
metabase-presto-and-trino        |  :data {:rows [], :cols []}}
metabase-presto-and-trino        | 
</details>
```

### Information about your Metabase installation

```JSON
v1.46.x
```

### Severity

P1?

### Additional context

Pro tip: use https://github.com/paoliniluis/metabase-presto-and-trino to raise the Trino with Postgres server. Just expose the Trino port on the Docker compose to connect from your clj repl

**Comment by paoliniluis** [comment]
@metamben just wanted your quick check on this one to see if this sounds to you?

**Comment by paoliniluis** [comment]
so connecting via a SQL client to a Trino but with a Presto driver results in:
```
java.sql.SQLException: Error executing query at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:279) at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:228) in RemoteStatementImpl.execute(RemoteStatementImpl.java:79) Caused by: java.lang.IllegalArgumentException: ParameterKind is [TYPE] but expected [LONG] at com.facebook.presto.jdbc.internal.common.type.TypeSignatureParameter.getValue(TypeSignatureParameter.java:110) at com.facebook.presto.jdbc.internal.common.type.TypeSignatureParameter.getLongLiteral(TypeSignatureParameter.java:122) at com.facebook.presto.jdbc.ColumnInfo.setTypeInfo(ColumnInfo.java:194) at com.facebook.presto.jdbc.PrestoResultSet.getColumnInfo(PrestoResultSet.java:1869) at com.facebook.presto.jdbc.PrestoResultSet. (PrestoResultSet.java:123) at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:250) at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:228) in RemoteStatementImpl.execute(RemoteStatementImpl.java:79)

seems like an issue on the upstream, or Trino and Presto have diverted so much that this won't be supported at all
```

**Comment by paoliniluis** [comment]
Problem inherited from the presto JDBC driver, not ours

**Comment by dragonsahead** [comment]
Don't think this will ever happen honestly
