### ISSUE TITLE
Force migration is broken

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#32115]
### Describe the bug

We introduced Custom migrations in https://github.com/metabase/metabase/pull/28175 which is a way for us to write migrations in Clojure. 

Now if you have an unrun migrations and it's a custom-migration, Doing a force migration will run all `custom migrations` first, then run the `sql` ones regardless of the order we defined it.

Meaning using force migration will:
- execute migrations in undefined orders
- Create incorrect data to the appDB and it's irreversible

### To Reproduce

1. Checkout this branch `reproduce-broken-force-migration` ([the diff](https://github.com/metabase/metabase/compare/reproduce-broken-force-migration?expand=1))
2. Run force migration with `clojure -M:run migrate force`
3. Check the log you will see
```
START EXECUTING a custom migration
INSERTED a database with id 5
DONE!
2023-07-04 17:48:06,371 INFO db.liquibase :: Start running force migrations
....
migration fails
```

Notice:
- we execute custom migration before `start running force migrations`
- In the branch, I intentionally wrote a migration that will fail when execute, which cause the whole command to fail. But if you do `select count(*) from metabasee_databse where id <whatever-the-id-you-got-from-log>`, it'll return 1. which means the result of the custom migration is persisted!

### Expected behavior

we should fix the migration to make it runs in exact order, or remove this feature.

### Logs
```
2023-07-04 17:48:04,491 INFO db.setup :: Setting up Liquibase...
2023-07-04 17:48:04,620 INFO db.setup :: Liquibase is ready.
START EXECUTING a custom migration
2023-07-04 17:48:06,251 INFO driver.impl :: Initializing driver :sql...
2023-07-04 17:48:06,252 INFO driver.impl :: Initializing driver :sql-jdbc...
2023-07-04 17:48:06,252 INFO driver.impl :: Initializing driver :postgres...
2023-07-04 17:48:06,356 INFO task.sync-databases :: Scheduling sync/analyze for database 5: trigger: metabase.task.sync-and-analyze.trigger.5
2023-07-04 17:48:06,357 INFO task.sync-databases :: Scheduling field-values for database 5: trigger: metabase.task.update-field-values.trigger.5
INSERTED a database with id 5
DONE!
2023-07-04 17:48:06,371 INFO db.liquibase :: Start running force migrations
2023-07-04 17:48:06,372 INFO db.liquibase :: UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = '192.168.1.102 (192.168.1.102)', LOCKGRANTED = NOW() WHERE ID = 1 AND LOCKED = FALSE;
2023-07-04 17:48:06,374 INFO db.liquibase :: [SUCCESS]
2023-07-04 17:48:06,374 INFO db.liquibase :: INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('v47.00-051', 'qnkhuat', 'migrations/000_migrations.yaml', NOW(), 623, '8:bedaee9df6474603401ac5730bcacf2a', 'customChange', 'Added 0.47.0 -', 'EXECUTED', NULL, NULL, '4.11.0', '8467686032');
2023-07-04 17:48:06,375 INFO db.liquibase :: [SUCCESS]
2023-07-04 17:48:06,375 INFO db.liquibase :: ALTER TABLE "public"."metabase_table" ADD "is_upload" BOOLEAN DEFAULT FALSE NOT NULL;
org.postgresql.util.PSQLException: ERROR: ROLLBACK TO SAVEPOINT can only be used in transaction blocks
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgConnection.execSQLUpdate(PgConnection.java:560)
        at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:1810)
        at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:1007)
        at metabase.db.liquibase$eval65584$force_migrate_up_if_needed_BANG___65589$fn__65590$fn__65595.invoke(liquibase.clj:178)
        at metabase.db.liquibase$eval65584$force_migrate_up_if_needed_BANG___65589$fn__65590.invoke(liquibase.clj:174)
        at metabase.db.liquibase$eval65584$force_migrate_up_if_needed_BANG___65589.invoke(liquibase.clj:151)
        at metabase.db.setup$eval66880$migrate_BANG___66885$fn__66886$fn__66887.invoke(setup.clj:79)
        at metabase.db.liquibase$eval65518$do_with_liquibase__65523$fn__65524.invoke(liquibase.clj:64)
        at metabase.db.liquibase$eval65518$do_with_liquibase__65523.invoke(liquibase.clj:56)
        at metabase.db.setup$eval66880$migrate_BANG___66885$fn__66886.invoke(setup.clj:73)
```
### Information about your Metabase installation

```JSON
master
```

### Severity

Not sure how often this feature is used, but if it's used then it'll cause irreversible change to the AppDB, which is bad.

**Comment by qnkhuat** [comment]
the reason this is happening is in order to run force migration, we calls [migrations-lines](https://github.com/metabase/metabase/blob/5ff9c4431eaf82812664cd123061cbb157cbe215/src/metabase/db/liquibase.clj#L168) to get a list of SQLs to execute. The expectation was that `migrations-lines` only return the changes that need to be executed, not execute it, but that's not true for custom migrations. All custom migrations were executed when `migrations-lines` got called.
