### ISSUE TITLE
Firebird community driver breaks sync for Postgres and other JDBC-based drivers

### ISSUE THREAD

**Issue by dealanis** [metabase/metabase#32124]
### Describe the bug

When adding a connection to a Postgres Database the honey SQL form is created with error provoking that the data model is never created

### To Reproduce

1. Add Postgres SQL 12.2 Connection
2. Sync schema

### Expected behavior

Data model synced

### Logs

```
2023-07-04 11:19:18,195 ERROR sql.query-processor :: Invalid HoneySQL form: Not supported by Honey SQL 2: ^metabase.util.honey_sql_1.Identifier (metabase.util.honey-sql-1/identifier :table "public" "account_analytic_account")
{:select [:*],
 :from [(metabase.util.honey-sql-1/identifier :table "public" "account_analytic_account")],
 :where [:not= 1 1],
 :limit 0}

clojure.lang.ExceptionInfo: Not supported by Honey SQL 2: ^metabase.util.honey_sql_1.Identifier (metabase.util.honey-sql-1/identifier :table "public" "account_analytic_account") {:honeysql-form {:select [:*], :from [(metabase.util.honey-sql-1/identifier :table "public" "account_analytic_account")], :where [:not= 1 1], :limit 0}, :form (metabase.util.honey-sql-1/identifier :table "public" "account_analytic_account")}
        at metabase.driver.sql.query_processor$format_honeysql_2$match_63581__63582.invoke(query_processor.clj:1298)
        at clojure.core$partial$fn__5908.invoke(core.clj:2641)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$mapcat.invokeStatic(core.clj:2800)
        at clojure.core$mapcat.doInvoke(core.clj:2800)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at metabase.mbql.util.match.impl$match_in_collection.invokeStatic(impl.cljc:33)
        at metabase.mbql.util.match.impl$match_in_collection.invoke(impl.cljc:23)
        at metabase.driver.sql.query_processor$format_honeysql_2$match_63581__63582.invoke(query_processor.clj:1298)
        at metabase.mbql.util.match.impl$match_in_collection$iter__27011__27015$fn__27016.invoke(impl.cljc:30)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:713)
        at clojure.core$next__5451.invokeStatic(core.clj:64)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:27)
        at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6882)
        at clojure.core$reduce.invoke(core.clj:6868)
        at metabase.mbql.util.match.impl$match_in_collection.invokeStatic(impl.cljc:29)
        at metabase.mbql.util.match.impl$match_in_collection.invoke(impl.cljc:23)
        at metabase.driver.sql.query_processor$format_honeysql_2$match_63581__63582.invoke(query_processor.clj:1298)
        at metabase.driver.sql.query_processor$format_honeysql_2.invokeStatic(query_processor.clj:1298)
        at metabase.driver.sql.query_processor$format_honeysql_2.invoke(query_processor.clj:1296)
        at metabase.driver.sql.query_processor$format_honeysql.invokeStatic(query_processor.clj:1326)
        at metabase.driver.sql.query_processor$format_honeysql.invoke(query_processor.clj:1315)
        at metabase.driver.sql.query_processor$format_honeysql.invokeStatic(query_processor.clj:1319)
        at metabase.driver.sql.query_processor$format_honeysql.invoke(query_processor.clj:1315)
        at metabase.driver.firebird$simple_select_probe_query.invokeStatic(firebird.clj:97)
        at metabase.driver.firebird$simple_select_probe_query.invoke(firebird.clj:90)
        at metabase.driver.firebird$fn__450.invokeStatic(firebird.clj:112)
        at metabase.driver.firebird$fn__450.invoke(firebird.clj:108)
        at clojure.lang.MultiFn.invoke(MultiFn.java:244)
        at metabase.driver.sql_jdbc.sync.describe_database$fast_active_tables$fn__77644.invoke(describe_database.clj:129)
        at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2822)
        at clojure.core$preserving_reduced$fn__8848.invoke(core.clj:7682)
        at clojure.core$take_while$fn__5982$fn__5983.invoke(core.clj:2918)
        at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
        at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__77158.reduce(common.clj:39)
        at clojure.core$reduce.invokeStatic(core.clj:6885)
        at clojure.core$cat$fn__8851.invoke(core.clj:7693)
        at clojure.core$map$fn__5931$fn__5932.invoke(core.clj:2759)
        at clojure.core$completing$fn__8528.invoke(core.clj:6931)
        at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2823)
        at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2823)
        at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2823)
        at clojure.core$take_while$fn__5982$fn__5983.invoke(core.clj:2918)
        at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
        at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__77158.reduce(common.clj:39)
        at clojure.core$transduce.invokeStatic(core.clj:6946)
        at clojure.core.Eduction.reduce(core.clj:7750)
        at clojure.core$transduce.invokeStatic(core.clj:6946)
        at clojure.core.Eduction.reduce(core.clj:7750)
        at clojure.core$reduce.invokeStatic(core.clj:6885)
        at clojure.core$into.invokeStatic(core.clj:6958)
        at clojure.core$into.invoke(core.clj:6950)
        at metabase.driver.sql_jdbc.sync.describe_database$describe_database$fn__77662.invoke(describe_database.clj:177)
        at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invokeStatic(describe_database.clj:163)
        at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invoke(describe_database.clj:160)
        at metabase.driver.sql_jdbc$fn__105175.invokeStatic(sql_jdbc.clj:75)
        at metabase.driver.sql_jdbc$fn__105175.invoke(sql_jdbc.clj:73)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.sync.fetch_metadata$fn__83479$db_metadata__83484$fn__83485.invoke(fetch_metadata.clj:15)
        at metabase.sync.fetch_metadata$fn__83479$db_metadata__83484.invoke(fetch_metadata.clj:12)
        at metabase.sync.sync_metadata$fn__85893$sync_db_metadata_BANG___85898$fn__85899.invoke(sync_metadata.clj:58)
        at metabase.sync.sync_metadata$fn__85893$sync_db_metadata_BANG___85898.invoke(sync_metadata.clj:55)
        at metabase.api.database$fn__95100$fn__95101.invoke(database.clj:975)
        at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.19+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.19+7",
    "os.name": "Linux",
    "os.version": "5.19.17-Unraid",
    "user.language": "en",
    "user.timezone": "America/Mexico_City"
  },
  "metabase-info": {
    "databases": [
      "firebird",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.2 (Debian 12.2-2.pgdg100+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-06-29",
      "tag": "v0.46.6",
      "branch": "release-x.46.x",
      "hash": "1bb88f5"
    },
    "settings": {
      "report-timezone": "America/Mexico_City"
    }
  }
}
```

### Severity

P1

**Comment by paoliniluis** [comment]
Which table is this? can you provide the ddl?

**Comment by dealanis** [comment]
Thanks for the quick reply! Im attaching the DDL of the table. For context, **this same error is showing for another database with other schema that was working before**, the database is connected and working but if I try a schema sync the same error shows with the first table of schema.


CREATE TABLE public.account_analytic_account (
	id serial4 NOT NULL,
	message_main_attachment_id int4 NULL,
	"name" varchar NOT NULL,
	code varchar NULL,
	active bool NULL,
	group_id int4 NULL,
	company_id int4 NULL,
	partner_id int4 NULL,
	create_uid int4 NULL,
	create_date timestamp NULL,
	write_uid int4 NULL,
	write_date timestamp NULL,
	CONSTRAINT account_analytic_account_pkey PRIMARY KEY (id),
	CONSTRAINT account_analytic_account_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.res_company(id) ON DELETE SET NULL,
	CONSTRAINT account_analytic_account_create_uid_fkey FOREIGN KEY (create_uid) REFERENCES public.res_users(id) ON DELETE SET NULL,
	CONSTRAINT account_analytic_account_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.account_analytic_group(id) ON DELETE SET NULL,
	CONSTRAINT account_analytic_account_message_main_attachment_id_fkey FOREIGN KEY (message_main_attachment_id) REFERENCES public.ir_attachment(id) ON DELETE SET NULL,
	CONSTRAINT account_analytic_account_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.res_partner(id) ON DELETE SET NULL,
	CONSTRAINT account_analytic_account_write_uid_fkey FOREIGN KEY (write_uid) REFERENCES public.res_users(id) ON DELETE SET NULL
);
CREATE INDEX account_analytic_account_code_index ON public.account_analytic_account USING btree (code);
CREATE INDEX account_analytic_account_message_main_attachment_id_index ON public.account_analytic_account USING btree (message_main_attachment_id);
CREATE INDEX account_analytic_account_name_index ON public.account_analytic_account USING btree (name);

**Comment by camsaul** [comment]
This seems like an error when using the community Firebird driver, not Postgres, based on 

```
at metabase.driver.firebird$simple_select_probe_query.invokeStatic(firebird.clj:97)
```

https://github.com/evosec/metabase-firebird-driver/blob/33734ce5f9fc614fd8edd1b1a6bde5f91a099ec7/src/metabase/driver/firebird.clj#L97

in the stacktrace... I'm not sure why `:firebird` is attempting to use Honey SQL 2 however. It might be a bug in the MB code

**Comment by camsaul** [comment]
Ok, this is the bug: the community `:firebird` driver is overriding the implementations of `have-select-privilege?` for **all** drivers

https://github.com/evosec/metabase-firebird-driver/blob/33734ce5f9fc614fd8edd1b1a6bde5f91a099ec7/src/metabase/driver/firebird.clj#L108

This is an upstream bug with the firebird driver, I'll open an issue there.

**Comment by camsaul** [comment]
I opened https://github.com/evosec/metabase-firebird-driver/pull/18 against the firebird community driver to fix the upstream issue, if and when they merge that PR and issue a new release is out of my control unfortunately. Please weigh in there and let them know this issue is affecting you

**Comment by Nikos410** [comment]
Hey @dealanis , sorry for the hassle we caused. I just released v1.5.0 of our firebird driver, which includes Cam's fix :)

https://github.com/evosec/metabase-firebird-driver/releases/tag/v1.5.0

**Comment by AntoninoRocha** [comment]
> Hey @dealanis , sorry for the hassle we caused. I just released v1.5.0 of our firebird driver, which includes Cam's fix :)
> 
> https://github.com/evosec/metabase-firebird-driver/releases/tag/v1.5.0

[Using Firebird community driver breaks sync for Postgres and other JDBC-based drivers](https://discourse.metabase.com/t/using-firebird-community-driver-breaks-sync-for-postgres-and-other-jdbc-based-drivers/58767)

When migrating to version v0.48.0 metabase and updating the driver with problem.
Even with helping the driver, it seems like some detail is missing

https://github.com/metabase/metabase/issues/32124

can you help?

**Comment by AntoninoRocha** [comment]
One more piece of information, sorry to be boring.
the database is connected I see the name of the tables, but when I go to consult something this message appears "No suitable driver found for jdbc:firebirdsql:"
Hope this helps

**Comment by AntoninoRocha** [comment]
No suitable driver found for jdbc:firebirdsql://192.168.100.2:3050//home/bases/basedados_master.fdb?encoding=ISO8859_1

**Comment by AntoninoRocha** [comment]
Please, you are the only one who can help us... we use firebird 2.5 together with metabase and this information appeared when updating the metabase "No suitable driver found for jdbc:firebirdsql://xxx.xxx.xxx.x:3050 //home/bases/basedados_master.fdb?encoding=ISO8859_1" , you can help by reviewing, we have already done all the possible tests but we believe that only you could help us and help the entire community, I am still grateful. We did the final test and it really didn't find the driver. ; )
