### ISSUE TITLE
Frontend won't load after upgrade

### ISSUE THREAD

**Issue by petrusgomes** [metabase/metabase#32213]
### Describe the bug

After upgrading from 0.46.3 to 0.46.6, the webpage won't load and chrome console shows a bootstrap error:

~~~javascript
bootstrap:19 Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at o (bootstrap:19:32)
    at 80094 (GridLayout.jsx:105:7)
    at o (bootstrap:19:32)
    at 88749 (CustomURLPicker.tsx:55:21)
    at o (bootstrap:19:32)
    at schema.core.js:21:12
    at o.O (chunk loaded:25:12)
    at schema.core.js:21:41
    at n (jsonp chunk loading:73:28)
    at app-main.bundle.js?528400185874d5729422:2:43
~~ ~

It looks like a cache error, because I can see everything on an incognito window. But not on my main window.
Reverting back to 0.46.3 and everything works as expected. Trying to upgrade from 0.46.3 to 0.46.4 also show me the same error.

### To Reproduce

1. Upgrade from 0.46.3 to 0.46.4 (docker and postgres)


### Expected behavior

_No response_

### Logs

~~~javascript
bootstrap:19 Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at o (bootstrap:19:32)
    at 80094 (GridLayout.jsx:105:7)
    at o (bootstrap:19:32)
    at 88749 (CustomURLPicker.tsx:55:21)
    at o (bootstrap:19:32)
    at schema.core.js:21:12
    at o.O (chunk loaded:25:12)
    at schema.core.js:21:41
    at n (jsonp chunk loading:73:28)
    at app-main.bundle.js?528400185874d5729422:2:43
~~ ~

### Information about your Metabase installation

```JSON
Chrome 114
Metabase 0.46.3
Docker
Postgres
```


### Severity

blocking an upgrade

### Additional context

_No response_

**Comment by paoliniluis** [comment]
please clean your browser cache

**Comment by petrusgomes** [comment]
Now consider that I have 10.000 users using our embedded dashboards. Should I just email everyone to clear their cache?
Is this solution enough to close this issue?

**Comment by paoliniluis** [comment]
@petrusgomes does it work now?
