### ISSUE TITLE
Bug while sending mail

### ISSUE THREAD

**Issue by lilletech** [metabase/metabase#32221]
### Describe the bug

the mail with report is not sent

### To Reproduce

I don't know what is the root cause. maybe in the format of date

### Expected behavior

Mail should be sent

### Logs

2023-07-07 12:00:03,726 ERROR task.send-pulses :: Erreur à l'envoi du Pulse 3
java.lang.NullPointerException
        at clojure.core$name.invokeStatic(core.clj:1610)
        at clojure.core$name.invoke(core.clj:1604)
        at clojure.core$comp$fn__5876.invoke(core.clj:2586)
        at clojure.core$update_keys$fn__8946.invoke(core.clj:8034)
        at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:429)
        at clojure.core$fn__8525.invokeStatic(core.clj:6908)
        at clojure.core$fn__8525.invoke(core.clj:6888)
        at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6919)
        at clojure.core$update_keys.invokeStatic(core.clj:8024)
        at clojure.core$update_keys.invoke(core.clj:8024)
        at metabase.pulse.render.datetime$format_temporal_str.invokeStatic(datetime.clj:85)
        at metabase.pulse.render.datetime$format_temporal_str.invoke(datetime.clj:66)
        at metabase.pulse.render.body$fn__73022$get_format__73027$fn__73028$fn__73029.invoke(body.clj:90)
        at metabase.pulse.render.body$fn__73105$query_results__GT_row_seq__73110$fn__73114$iter__73118__73122$fn__73123$iter__73157__73161$fn__73162.invoke(body.clj:166)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.countFrom(RT.java:653)
        at clojure.lang.RT.count(RT.java:643)
        at metabase.pulse.render.table$render_table_body$iter__72900__72904$fn__72905$iter__72939__72943$fn__72944.invoke(table.clj:130)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$map$fn__5935.invoke(core.clj:2763)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
        at hiccup.compiler$render_element.invoke(compiler.clj:72)
        at hiccup.compiler$fn__72656.invokeStatic(compiler.clj:85)
        at hiccup.compiler$fn__72656.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2772)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
        at hiccup.compiler$render_element.invoke(compiler.clj:72)
        at hiccup.compiler$fn__72656.invokeStatic(compiler.clj:85)
        at hiccup.compiler$fn__72656.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
        at hiccup.compiler$render_element.invoke(compiler.clj:72)
        at hiccup.compiler$fn__72656.invokeStatic(compiler.clj:85)
        at hiccup.compiler$fn__72656.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
        at hiccup.compiler$render_element.invoke(compiler.clj:72)
        at hiccup.compiler$fn__72656.invokeStatic(compiler.clj:85)
        at hiccup.compiler$fn__72656.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2772)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.boundedLength(RT.java:1790)
        at clojure.lang.RestFn.applyTo(RestFn.java:130)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
        at hiccup.compiler$render_element.invoke(compiler.clj:72)
        at hiccup.compiler$fn__72656.invokeStatic(compiler.clj:85)
        at hiccup.compiler$fn__72656.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
        at hiccup.compiler$render_element.invoke(compiler.clj:72)
        at hiccup.compiler$fn__72656.invokeStatic(compiler.clj:85)
        at hiccup.compiler$fn__72656.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
        at hiccup.compiler$render_element.invoke(compiler.clj:72)
        at hiccup.compiler$fn__72656.invokeStatic(compiler.clj:85)
        at hiccup.compiler$fn__72656.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
        at hiccup.compiler$render_element.invoke(compiler.clj:72)
        at hiccup.compiler$fn__72656.invokeStatic(compiler.clj:85)
        at hiccup.compiler$fn__72656.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
        at hiccup.compiler$render_element.invoke(compiler.clj:72)
        at hiccup.compiler$fn__72656.invokeStatic(compiler.clj:85)
        at hiccup.compiler$fn__72656.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.core$map$fn__5935.invoke(core.clj:2770)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$apply.invoke(core.clj:662)
        at hiccup.compiler$fn__72658.invokeStatic(compiler.clj:88)
        at hiccup.compiler$fn__72658.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at hiccup.compiler$render_element.invokeStatic(compiler.clj:78)
        at hiccup.compiler$render_element.invoke(compiler.clj:72)
        at hiccup.compiler$fn__72656.invokeStatic(compiler.clj:85)
        at hiccup.compiler$fn__72656.invoke(compiler.clj:82)
        at hiccup.compiler$fn__72641$G__72636__72646.invoke(compiler.clj:68)
        at clojure.lang.Var.invoke(Var.java:384)
        at metabase.email.messages$render_message_body.invokeStatic(messages.clj:468)
        at metabase.email.messages$render_message_body.invoke(messages.clj:458)
        at metabase.email.messages$render_pulse_email.invokeStatic(messages.clj:487)
        at metabase.email.messages$render_pulse_email.invoke(messages.clj:484)
        at metabase.pulse$fn__96858.invokeStatic(pulse.clj:338)
        at metabase.pulse$fn__96858.invoke(pulse.clj:327)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at metabase.pulse$results__GT_notifications$iter__96892__96896$fn__96897$fn__96898.invoke(pulse.clj:390)
        at metabase.pulse$results__GT_notifications$iter__96892__96896$fn__96897.invoke(pulse.clj:388)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5467.invokeStatic(core.clj:139)
        at clojure.core$seq__5467.invoke(core.clj:139)
        at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:510)
        at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:509)
        at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:537)
        at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:518)
        at clojure.lang.RestFn.invoke(RestFn.java:439)
        at metabase.task.send_pulses$fn__102340$send_pulses_BANG___102349$fn__102352$fn__102372$fn__102373.invoke(send_pulses.clj:59)
        at metabase.models.task_history$fn__55838$do_with_task_history__55843$fn__55844.invoke(task_history.clj:88)
        at metabase.models.task_history$fn__55838$do_with_task_history__55843.invoke(task_history.clj:83)
        at metabase.task.send_pulses$fn__102340$send_pulses_BANG___102349$fn__102352$fn__102372.invoke(send_pulses.clj:55)
        at metabase.task.send_pulses$fn__102340$send_pulses_BANG___102349$fn__102352.invoke(send_pulses.clj:54)
        at metabase.task.send_pulses$fn__102340$send_pulses_BANG___102349.invoke(send_pulses.clj:41)
        at metabase.task.send_pulses$fn__102340$send_pulses_BANG___102349$fn__102350.invoke(send_pulses.clj:48)
        at metabase.task.send_pulses$fn__102340$send_pulses_BANG___102349.invoke(send_pulses.clj:41)
        at metabase.task.send_pulses.SendPulses$fn__102411.invoke(send_pulses.clj:99)
        at metabase.models.task_history$fn__55838$do_with_task_history__55843$fn__55844.invoke(task_history.clj:88)
        at metabase.models.task_history$fn__55838$do_with_task_history__55843.invoke(task_history.clj:83)
        at metabase.task.send_pulses.SendPulses.execute(send_pulses.clj:85)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

### Information about your Metabase installation

```JSON
chrome Version 114.0.5735.199 (Build officiel) (64 bits)
docker 
postgres
```

### Severity

blocking the usage

**Comment by paoliniluis** [comment]
please post the full troubleshooting info
