### ISSUE TITLE
Editing viz settings in a dashboard of 2 incomplete bar charts will end up in an error

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#32230]
### Describe the bug

1) Let's build 2 questions 
question 1: select 1, save it as a barchart
question 2: select 2, save it as a barchart
2) add question 1 to a dashboard and go to "add series", add question number 2
3) you'll see that the question won't get any rendering, it's fine. Now go to the viz settings of the question, you will end in a very weird state
![image](https://github.com/metabase/metabase/assets/1711649/7e1a67fe-f397-4418-9d98-63b611ba57f3)

### To Reproduce

Above

### Expected behavior

We should either remove the viz settings or never let the user add a new series to this incomplete card

### Logs

react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'name')
    at N (utils.js:154:42)
    at Object.getProps (graph.js:653:29)
    at dt (settings.js:162:22)
    at settings.js:185:7
    at Array.map (<anonymous>)
    at pt (settings.js:184:6)
    at x (visualization.js:107:10)
    at n.value (ChartSettings.jsx:161:14)
    at n.value (ChartSettings.jsx:281:26)
    at Ha (react-dom.production.min.js:182:192)

### Information about your Metabase installation

```JSON
v47.x
```

### Severity

P3

**Comment by kamilmielnik** [comment]
Expected result TBD, see Slack: https://metaboat.slack.com/archives/C057T1QTB3L/p1691587833739299?thread_ts=1691585903.901969&cid=C057T1QTB3L

**Comment by NevRA** [comment]
Not related to the Dashboards, could be reproduced on the Question page itself

**Comment by paoliniluis** [comment]
Ok so this now appears on a table. Repro steps:
1) new SQL query: select * from people. Save it and go to the "usage insights" of the question
2) make a copy of the dashboard that was just created
3) edit the dashboard that was duplicated and click on the viz settings of the "dashboards with this question" card

see the error
![image](https://github.com/metabase/metabase/assets/1711649/80f9a52a-cc46-4911-8fca-a6c88c7a6b2e)

**Comment by cdeweyx** [comment]
I'm unable to repro this based on the steps above. @paoliniluis can you still repro?

**Comment by erikfinnegan-ciq** [comment]
> I'm unable to repro this based on the steps above. [@paoliniluis](https://github.com/paoliniluis) can you still repro?

I'm able to reproduce this on certain dashboards, but not all. We've also had several customers experience variations of the same, but again, not on every dashboard. If it helps, there's a workaround we've found for the time being: if you change the type and then change it back, the settings don't throw an error.

![Image](https://github.com/user-attachments/assets/9036a2c7-7b72-455a-983b-b3dcc2e00443)

![Image](https://github.com/user-attachments/assets/395f25ec-a671-4a0d-abc5-04cbbe5825d3)

![Image](https://github.com/user-attachments/assets/d62bbdc8-a8cb-4d56-933c-8b71e31562b3)

**Comment by erikfinnegan-ciq** [comment]
Just in the last couple weeks we've had several reports similar to this. If there is more information I can provide or anything else I can do to help, let me know.

**Comment by cdeweyx** [comment]
> Just in the last couple weeks we've had several reports similar to this. If there is more information I can provide or anything else I can do to help, let me know.

Thanks for providing details, we'll look into this 🙏

**Comment by lorem--ipsum** [comment]
@paoliniluis I tried both of the provided lists of steps to replicate the issue, to no avail. is this still happening?
@erikfinnegan-ciq could you please post a list of steps for this? Given the errors I can see in the screenshots, it might very well be straightforward to fix. Thank you!

**Comment by erikfinnegan-ciq** [comment]
@lorem--ipsum I posted a list of steps in my comment from October 8th, four comments up from this. If the images I shared aren't loading for you, let me know and I can send them a different way.

Do note that this is not occurring in with all dashboards, but the ones for which it does apply, it always happens. I haven't been able to identify what's different about the affected dashboards though.

**Comment by lorem--ipsum** [comment]
@erikfinnegan-ciq if I understand your comment correctly, it provides a workaround to the issue. I was hoping you could share steps to actually get to a failing dashboard?

**Comment by erikfinnegan-ciq** [comment]
@lorem--ipsum Ah, no, sorry - I've seen a few affected dashboards but haven't been able to figure out why this would happen to one but not another.

**Comment by paoliniluis** [comment]
@erikfinnegan-ciq which version are you using?

**Comment by erikfinnegan-ciq** [comment]
@paoliniluis we're using a fork of 1.49.2, though our changes are minor and mostly restricted to front end stuff.

**Comment by perivamsi** [comment]
not able to repro, seems fixed in latest master
