### ISSUE TITLE
Personal Collection Gone Blank 

### ISSUE THREAD

**Issue by punnumangal** [metabase/metabase#32496]
### Describe the bug

One employee saved lots of questions and dashboards in the personal collection but it is showing completely blank now. If we go to that specific question then it says that it is in the personal collection of that employee but we can not see that in the personal collection and it is completely blank. Attaching the image for reference.

<img width="1517" alt="Screenshot 2023-07-19 at 11 58 57 AM" src="https://github.com/metabase/metabase/assets/22841102/8d884f05-b632-48d1-bbfc-4204b7300077">

Below are sample queries which are saved in employee personal collection 
<img width="271" alt="Screenshot 2023-07-19 at 12 03 10 PM" src="https://github.com/metabase/metabase/assets/22841102/c2b033e4-b257-48fc-b907-fdb9facca330">

### Expected behavior

We should be able to see all the reports that are saved on personal collection

### Logs

[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:05+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 78.7 ms (5 DB calls) App DB connections: 1/130 Jetty threads: 4/200 (4 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:05+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 106.5 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 3/200 (4 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:05+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 106.3 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 3/200 (5 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:06+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 111.8 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 3/200 (5 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:06+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 104.6 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 3/200 (5 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:06+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 105.2 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 3/200 (5 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:06+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 106.2 ms (6 DB calls) App DB connections: 1/130 Jetty threads: 4/200 (4 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:06+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 146.7 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 3/200 (4 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:06+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 103.5 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 3/200 (5 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:07+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 105.7 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 3/200 (5 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:07+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 104.3 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 3/200 (5 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:07+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 105.9 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 3/200 (5 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:07+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 104.3 ms (6 DB calls) App DB connections: 1/130 Jetty threads: 4/200 (4 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:07+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 98.3 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 4/200 (4 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:07+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 111.2 ms (6 DB calls) App DB connections: 1/130 Jetty threads: 4/200 (4 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:07+05:30 DEBUG metabase.server.middleware.log GET /api/database/29/autocomplete_suggestions 200 89.3 ms (6 DB calls) App DB connections: 0/130 Jetty threads: 3/200 (4 idle, 0 queued) (342 total active threads) Queries in flight: 0 (0 queued)
[a2ba31be-b23f-460c-b4de-0c0dfe63fc7b] 2023-07-19T11:53:07+05:30 ERROR metabase.models.field-values Error fetching field values
java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at metabase.driver.sql_jdbc.execute$fn__54955.invokeStatic(execute.clj:190)
	at metabase.driver.sql_jdbc.execute$fn__54955.invoke(execute.clj:188)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:497)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:494)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:486)
	at metabase.driver.sql_jdbc$fn__85234.invokeStatic(sql_jdbc.clj:54)
	at metabase.driver.sql_jdbc$fn__85234.invoke(sql_jdbc.clj:52)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:59)
	at metabase.query_processor.context$executef.invoke(context.clj:48)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:67)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:65)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:45)
	at metabase.query_processor.context$runf.invoke(context.clj:39)
	at metabase.query_processor.reducible$identity_qp.invokeStatic(reducible.clj:12)
	at metabase.query_processor.reducible$identity_qp.invoke(reducible.clj:9)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___52607.invoke(cache.clj:220)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__48131.invoke(permissions.clj:109)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__51552.invoke(mbql_to_native.clj:23)
	at metabase.query_processor$fn__54083$combined_post_process__54088$combined_post_process_STAR___54089.invoke(query_processor.clj:212)
	at metabase.query_processor$fn__54083$combined_pre_process__54084$combined_pre_process_STAR___54085.invoke(query_processor.clj:209)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52528$fn__52533.invoke(resolve_database_and_driver.clj:35)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:75)
	at metabase.driver$do_with_driver.invoke(driver.clj:71)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__52528.invoke(resolve_database_and_driver.clj:34)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__48563.invoke(fetch_source_query.clj:346)
	at metabase.query_processor.middleware.store$initialize_store$fn__48751$fn__48752.invoke(store.clj:11)
	at metabase.query_processor.store$do_with_store.invokeStatic(store.clj:44)
	at metabase.query_processor.store$do_with_store.invoke(store.clj:38)
	at metabase.query_processor.middleware.store$initialize_store$fn__48751.invoke(store.clj:10)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__52800.invoke(normalize_query.clj:22)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44972$thunk__44974.invoke(reducible.clj:100)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44972.invoke(reducible.clj:106)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44972.invoke(reducible.clj:91)
	at metabase.query_processor.reducible$async_qp$qp_STAR___44972.invoke(reducible.clj:88)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.18+10-post-Ubuntu-0ubuntu120.04.1",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.18",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.18+10-post-Ubuntu-0ubuntu120.04.1",
    "os.name": "Linux",
    "os.version": "5.15.0-1034-aws",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "mongo",
      "snowflake",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.4.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2022-09-02",
      "tag": "v0.44.3",
      "branch": "release-x.44.x",
      "hash": "7d50282"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

### Severity

High

### Additional context

This is happening only for one personal collection in the entire Metabase

**Comment by punnumangal** [comment]
We upgraded to the Metabase latest version (latest 0.46.6 from 0.44.3) and this issue got resolved.
