### ISSUE TITLE
v0.46.6.4 : Migration from H2 to Postgres fails with Command failed with exception: ERROR: insert or update on table "metabase_table" violates foreign key constraint "fk_table_ref_database_id"

### ISSUE THREAD

**Issue by Bodobolero** [metabase/metabase#32837]
### Describe the bug

Try to migrate meta database from H2 to production database
```
export MB_DB_TYPE=postgres
export MB_DB_CONNECTION_URI="jdbc:postgresql://localhost:5432/metabase?user=postgres&password=mysecret"
java -jar metabase.jar load-from-h2 ./metabase.db
```

Get the following error:
```
rg.postgresql.util.PSQLException: ERROR: insert or update on table "metabase_table" violates foreign key constraint "fk_table_ref_database_id"
  Detail: Key (db_id)=(1) is not present in table "metabase_database".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:316)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:879)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:901)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.commit(NewProxyConnection.java:981)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:815)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at metabase.cmd.copy$fn__102278$copy_BANG___102283$fn__102284.invoke(copy.clj:391)
	at metabase.cmd.copy$fn__102278$copy_BANG___102283.invoke(copy.clj:368)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:36)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:26)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:48)
	at metabase.cmd$load_from_h2.invoke(cmd.clj:42)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__103139.invoke(cmd.clj:264)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:264)
	at metabase.cmd$run_cmd.invoke(cmd.clj:255)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:166)
	at metabase.core$run_cmd.invoke(core.clj:164)
	at metabase.core$_main.invokeStatic(core.clj:188)
	at metabase.core$_main.doInvoke(core.clj:183)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
```

Note that this is a clean install.
I have only downloaded the jar file and started it once with connection to a postgres database.
So the Postgres schema has been sync'ed once.
Then I shutdown the metabase instance and immediately started the migration.

### To Reproduce

1. Download metabase jar
2. Open web-front-end in browser
3. follow setup steps and connect to one single Postgres database
4. Wait until the postgres schema is sync'ed
5. Shutdown metabase
6. Start migration as described above

### Expected behavior

I expect the migration to finish without error

### Logs

I can no longer start metabase after the failed migration. However I can provide my terminal output from the failed migration:

```
% java -jar metabase.jar load-from-h2 ./metabase.db
2023-08-02 13:00:44,989 INFO metabase.util :: Maximum memory available to JVM: 4,0 GB
2023-08-02 13:00:46,944 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
..instrumented #'metabase.util.malli/with-api-error-message
..instrumented #'metabase.util.honey-sql-2/identifier
..instrumented #'metabase.util.honey-sql-2/normalize-type-info
..instrumented #'metabase.util.honey-sql-2/with-database-type-info
..instrumented #'metabase.util.honey-sql-2/cast
..instrumented #'metabase.util.honey-sql-2/quoted-cast
..instrumented #'metabase.util.honey-sql-2/maybe-cast
..instrumented #'metabase.models.permissions/classify-path
..instrumented #'metabase.models.permissions/classify-data-path
..instrumented #'metabase.models.permissions/generate-graph
..instrumented #'metabase.models.permissions/->v2-path
..instrumented #'metabase.models.permissions/update-db-data-access-permissions!
..instrumented #'metabase.models.permissions/update-group-permissions!
..instrumented #'metabase.models.permissions/update-data-perms-graph!
..instrumented #'metabase.models.parameter-card/upsert-or-delete-from-parameters!
WARNING: abs already refers to: #'clojure.core/abs in namespace: kixi.stats.math, being replaced by: #'kixi.stats.math/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: kixi.stats.test, being replaced by: #'kixi.stats.math/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: kixi.stats.distribution, being replaced by: #'kixi.stats.math/abs
..instrumented #'metabase.query-processor.middleware.permissions/check-query-permissions*
..instrumented #'metabase.driver.sql-jdbc.sync.describe-database/simple-select-probe-query
2023-08-02 13:00:52,557 INFO driver.impl :: Registered abstract driver :sql  🚚
2023-08-02 13:00:52,560 INFO metabase.util ::  ⮦ Load driver :sql took 88,6 ms
2023-08-02 13:00:52,564 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
2023-08-02 13:00:52,568 INFO metabase.util :: Load driver :sql-jdbc took 99,9 ms
2023-08-02 13:00:52,568 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
..instrumented #'metabase.driver.h2/classify-query
2023-08-02 13:00:52,615 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
2023-08-02 13:00:52,644 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
..instrumented #'metabase.models.params.custom-values/values-from-card
..instrumented #'metabase.api.card/param-values
..instrumented #'metabase.api.dashboard/chain-filter
..instrumented #'metabase.api.setup/state-for-checklist
..instrumented #'metabase.api.setup/checklist-items
2023-08-02 13:00:54,447 INFO metabase.core :: 
Metabase v0.46.6.4 (7c60aca release-x.46.6.x) 

Copyright © 2023 Metabase, Inc. 

Metabase Enterprise Edition extensions are NOT PRESENT.
2023-08-02 13:00:54,504 INFO cmd.copy :: Set up h2 source database and run migrations... 
2023-08-02 13:00:54,507 INFO db.setup :: Verifying h2 Database Connection ...
2023-08-02 13:00:54,909 INFO db.setup :: Successfully verified H2 2.1.212 (2022-04-09) application database connection. ✅
2023-08-02 13:00:54,910 INFO db.setup :: Running Database Migrations...
2023-08-02 13:00:54,912 INFO db.setup :: Setting up Liquibase...
2023-08-02 13:00:55,151 INFO db.setup :: Liquibase is ready.
2023-08-02 13:00:55,152 INFO db.liquibase :: Checking if Database has unrun migrations...
2023-08-02 13:00:56,172 INFO db.setup :: Database Migrations Current ...  ✅
2023-08-02 13:00:56,173 INFO db.data-migrations :: Running all necessary data migrations, this may take a minute.
2023-08-02 13:00:56,662 INFO db.data-migrations :: Finished running data migrations.
2023-08-02 13:00:56,663 INFO metabase.util :: Database setup took 2,2 s
2023-08-02 13:00:56,663 INFO cmd.copy :: [OK]
2023-08-02 13:00:56,664 INFO cmd.copy :: Set up postgres target database and run migrations... 
2023-08-02 13:00:56,665 INFO db.setup :: Verifying postgres Database Connection ...
2023-08-02 13:00:57,068 INFO db.setup :: Successfully verified PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) application database connection. ✅
2023-08-02 13:00:57,068 INFO db.setup :: Running Database Migrations...
2023-08-02 13:00:57,068 INFO db.setup :: Setting up Liquibase...
2023-08-02 13:00:57,106 INFO db.setup :: Liquibase is ready.
2023-08-02 13:00:57,106 INFO db.liquibase :: Checking if Database has unrun migrations...
2023-08-02 13:00:57,977 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2023-08-02 13:00:58,148 INFO db.liquibase :: Migration lock is cleared. Running migrations...
2023-08-02 13:01:07,198 INFO impl.StdSchedulerFactory :: Using default implementation for ThreadExecutor
2023-08-02 13:01:07,215 INFO core.SchedulerSignalerImpl :: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2023-08-02 13:01:07,215 INFO core.QuartzScheduler :: Quartz Scheduler v.2.3.2 created.
2023-08-02 13:01:07,216 INFO jdbcjobstore.JobStoreTX :: Using db table-based data access locking (synchronization).
2023-08-02 13:01:07,217 INFO jdbcjobstore.JobStoreTX :: JobStoreTX initialized.
2023-08-02 13:01:07,218 INFO core.QuartzScheduler :: Scheduler meta-data: Quartz Scheduler (v2.3.2) 'MetabaseScheduler' with instanceId 'BodosMac13-3.fritz.box1690974067204'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.impl.jdbcjobstore.JobStoreTX' - which supports persistence. and is clustered.

2023-08-02 13:01:07,218 INFO impl.StdSchedulerFactory :: Quartz scheduler 'MetabaseScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2023-08-02 13:01:07,218 INFO impl.StdSchedulerFactory :: Quartz scheduler version: 2.3.2
2023-08-02 13:01:07,252 INFO core.QuartzScheduler :: Scheduler MetabaseScheduler_$_BodosMac13-3.fritz.box1690974067204 started.
2023-08-02 13:01:07,298 INFO core.QuartzScheduler :: Scheduler MetabaseScheduler_$_BodosMac13-3.fritz.box1690974067204 shutting down.
2023-08-02 13:01:07,299 INFO core.QuartzScheduler :: Scheduler MetabaseScheduler_$_BodosMac13-3.fritz.box1690974067204 paused.
2023-08-02 13:01:07,299 INFO core.QuartzScheduler :: Scheduler MetabaseScheduler_$_BodosMac13-3.fritz.box1690974067204 shutdown complete.
2023-08-02 13:01:07,380 INFO db.setup :: Database Migrations Current ...  ✅
2023-08-02 13:01:07,380 INFO metabase.util :: Database setup took 10,7 s
2023-08-02 13:01:07,381 INFO cmd.copy :: [OK]
2023-08-02 13:01:07,382 INFO cmd.copy :: Testing if target postgres database is already populated... 
2023-08-02 13:01:07,385 INFO cmd.copy :: [OK]
2023-08-02 13:01:07,385 INFO cmd.copy :: Clearing default entries created by Liquibase migrations... 
2023-08-02 13:01:07,387 INFO cmd.copy :: Temporarily disabling DB constraints... 
2023-08-02 13:01:07,938 INFO cmd.copy :: [OK]
2023-08-02 13:01:09,614 INFO cmd.copy :: Re-enabling DB constraints... 
2023-08-02 13:01:09,614 INFO cmd.copy :: [OK]
2023-08-02 13:01:09,615 INFO cmd.copy :: [OK]
2023-08-02 13:01:09,618 INFO cmd.copy :: Temporarily disabling DB constraints... 
2023-08-02 13:01:09,806 INFO cmd.copy :: [OK]
2023-08-02 13:01:09,813 INFO cmd.copy :: Copying instances of Database...
2023-08-02 13:01:09,822 INFO cmd.copy ::  copied 1 instances.
2023-08-02 13:01:09,823 INFO cmd.copy :: Copying instances of User...
2023-08-02 13:01:09,827 INFO cmd.copy ::  copied 1 instances.
2023-08-02 13:01:09,828 INFO cmd.copy :: Copying instances of Setting...
2023-08-02 13:01:09,834 INFO cmd.copy ::  copied 12 instances.
2023-08-02 13:01:09,842 INFO cmd.copy :: Copying instances of Table...
2023-08-02 13:01:09,873 INFO cmd.copy ::  copied 115 instances.
2023-08-02 13:01:09,923 INFO cmd.copy :: Copying instances of Field...
2023-08-02 13:01:10,371 INFO cmd.copy ::  copied 2,521 instances.
2023-08-02 13:01:10,378 INFO cmd.copy :: Copying instances of FieldValues...
2023-08-02 13:01:10,389 INFO cmd.copy ::  copied 24 instances.
2023-08-02 13:01:10,393 INFO cmd.copy :: Copying instances of Session...
2023-08-02 13:01:10,396 INFO cmd.copy ::  copied 1 instances.
2023-08-02 13:01:10,398 INFO cmd.copy :: Copying instances of Collection...
2023-08-02 13:01:10,401 INFO cmd.copy ::  copied 1 instances.
2023-08-02 13:01:10,406 INFO cmd.copy :: Copying instances of Activity...
2023-08-02 13:01:10,414 INFO cmd.copy ::  copied 2 instances.
2023-08-02 13:01:10,417 INFO cmd.copy :: Copying instances of PermissionsGroup...
2023-08-02 13:01:10,423 INFO cmd.copy ::  copied 2 instances.
2023-08-02 13:01:10,424 INFO cmd.copy :: Copying instances of PermissionsGroupMembership...
2023-08-02 13:01:10,430 INFO cmd.copy ::  copied 2 instances.
2023-08-02 13:01:10,431 INFO cmd.copy :: Copying instances of Permissions...
2023-08-02 13:01:10,437 INFO cmd.copy ::  copied 10 instances.
2023-08-02 13:01:10,441 INFO cmd.copy :: Copying instances of DataMigrations...
2023-08-02 13:01:10,447 INFO cmd.copy ::  copied 2 instances.
2023-08-02 13:01:10,448 INFO cmd.copy :: Re-enabling DB constraints... 
2023-08-02 13:01:10,448 INFO cmd.copy :: [OK]
org.postgresql.util.PSQLException: ERROR: insert or update on table "metabase_table" violates foreign key constraint "fk_table_ref_database_id"
  Detail: Key (db_id)=(1) is not present in table "metabase_database".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:316)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:879)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:901)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.commit(NewProxyConnection.java:981)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:815)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at metabase.cmd.copy$fn__102278$copy_BANG___102283$fn__102284.invoke(copy.clj:391)
	at metabase.cmd.copy$fn__102278$copy_BANG___102283.invoke(copy.clj:368)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:36)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:26)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:48)
	at metabase.cmd$load_from_h2.invoke(cmd.clj:42)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__103139.invoke(cmd.clj:264)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:264)
	at metabase.cmd$run_cmd.invoke(cmd.clj:255)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:166)
	at metabase.core$run_cmd.invoke(core.clj:164)
	at metabase.core$_main.invokeStatic(core.clj:188)
	at metabase.core$_main.doInvoke(core.clj:183)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
Command failed with exception: ERROR: insert or update on table "metabase_table" violates foreign key constraint "fk_table_ref_database_id"
  Detail: Key (db_id)=(1) is not present in table "metabase_database".
```

### Information about your Metabase installation

```JSON
After migration I can no longer open Admin->Troubleshooting

Metabase v0.46.6.4 (7c60aca release-x.46.6.x) 
macOS
```

### Severity

it is blocking my usage entirely

**Comment by Bodobolero** [comment]
I did a fresh installation to get you the full troubleshooting info

```
{
  "browser-info": {
    "language": "de-DE",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15",
    "vendor": "Apple Computer, Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "15.0.1+9-18",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "15.0.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "15.0.1+9-18",
    "os.name": "Mac OS X",
    "os.version": "10.16",
    "user.language": "de",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.212 (2022-04-09)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.212 (2022-04-09)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-28",
      "tag": "v0.46.6.4",
      "branch": "release-x.46.6.x",
      "hash": "7c60aca"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by Bodobolero** [comment]
I could now repro the problem even without connecting to my own Postgres user data database during setup and selecting "I'll define my data laster".
So just start Metabase once, go through the setup process with minimal input, then stop the instance and then try to migrate H2 to Postgres (V15) database. And you get the same error.

**Comment by Bodobolero** [comment]
I have no clue about your source code. But in the log I see sequences of
```
Temporarily disabling DB constraints... 
... do something
 Re-enabling DB constraints... 
```
However the "disabling" step is missing before the error. I guess this causes the problem.

**Comment by Bodobolero** [comment]
@camsaul I just verified with Metabase v0.46.7 (cfdf23b release-x.46.x) that the fix works for me. This was incredibly good response time for not just providing a fix but also releasing a new version containing the fix. Thank you very much.

**Comment by zulhyperjump** [comment]
I still have the same error with version v0.47.3.
The reproduction steps were the same.
