### ISSUE TITLE
Can't Build Frontend on OSX

### ISSUE THREAD

**Issue by erp12** [metabase/metabase#3301]
My overall goal is to develop a Metabase driver for Vertica. To do this I need the ability to run my modified metabase locally on my OSX machine (Yosemite 10.10.5). When I call `lein ring server` I get the error message:

`Cannot find './resources/frontend_client/index.html'. Did you remember to build the Metabase frontend?`

So I run `npm run build`. I don't use `npm run build-hot` because I am not doing any front end development (right?). The response I get is as follows:
```
> metabase@0.0.0 build /Users/mm94978/mm_projects/metabase
> webpack

module.js:457
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mm94978/mm_projects/metabase/node_modules/html-webpack-plugin/index.js:4:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/mm94978/.nvm/versions/node/v6.5.0/bin/node" "/Users/mm94978/.nvm/versions/node/v6.5.0/bin/npm" "run" "build"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! metabase@0.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the metabase@0.0.0 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the metabase package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs metabase
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls metabase
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mm94978/mm_projects/metabase/npm-debug.log
```
Below is the `npm-debug.log` file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/mm94978/.nvm/versions/node/v6.5.0/bin/node',
1 verbose cli   '/Users/mm94978/.nvm/versions/node/v6.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle metabase@0.0.0~prebuild: metabase@0.0.0
6 silly lifecycle metabase@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle metabase@0.0.0~build: metabase@0.0.0
8 verbose lifecycle metabase@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle metabase@0.0.0~build: PATH: /Users/mm94978/.nvm/versions/node/v6.5.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/mm94978/mm_projects/metabase/node_modules/.bin:/Users/mm94978/.nvm/versions/node/v6.5.0/bin:/Users/mm94978/.nvm/versions/node/v6.5.0/bin:/usr/local/bin:/usr/local/bin/npm:/Applications/sqlite:/Applications/lein:/Applications/spark-1.6.1-bin-hadoop2.6/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/vertica/bin/:/usr/local/hadoop-2.3.0-cdh5.1.2/bin/:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
10 verbose lifecycle metabase@0.0.0~build: CWD: /Users/mm94978/mm_projects/metabase
11 silly lifecycle metabase@0.0.0~build: Args: [ '-c', 'webpack' ]
12 silly lifecycle metabase@0.0.0~build: Returned: code: 1  signal: null
13 info lifecycle metabase@0.0.0~build: Failed to exec build script
14 verbose stack Error: metabase@0.0.0 build: `webpack`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/mm94978/.nvm/versions/node/v6.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/mm94978/.nvm/versions/node/v6.5.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid metabase@0.0.0
16 verbose cwd /Users/mm94978/mm_projects/metabase
17 error Darwin 14.5.0
18 error argv "/Users/mm94978/.nvm/versions/node/v6.5.0/bin/node" "/Users/mm94978/.nvm/versions/node/v6.5.0/bin/npm" "run" "build"
19 error node v6.5.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error metabase@0.0.0 build: `webpack`
22 error Exit status 1
23 error Failed at the metabase@0.0.0 build script 'webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the metabase package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs metabase
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls metabase
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I tried `npm install lodash` and re-run `npm run build`

The error changes to
```
> metabase@0.0.0 build /Users/mm94978/mm_projects/metabase
> webpack

module.js:457
    throw err;
    ^

Error: Cannot find module './renderKid/styleApplier/inline'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mm94978/mm_projects/metabase/node_modules/html-webpack-plugin/node_modules/pretty-error/node_modules/renderkid/lib/RenderKid.js:4:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mm94978/mm_projects/metabase/node_modules/html-webpack-plugin/node_modules/pretty-error/lib/PrettyError.js:14:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

I then tried `npm install inline`. This produced the same error as above after re-running `npm run build`

I am an experienced Clojure programmer, but have very little knowledge of node. Any help would be much appreciated. Thank you.

**Comment by camsaul** [comment]
Just do `npm install` to install everything.

**Comment by erp12** [comment]
Thanks for your quick response!
Sorry, I left out a couple of things I tried. I did `lein deps` and `npm install` right after forking. 

I just tried `npm install` again to make sure, and it printed that npm "loading bar" but after it finished it did not print any indication it had downloaded any new packages... in fact it didn't print anything at all. My understanding is that this is because it already had all the dependencies, but I could be wrong.

I then tried `npm run build` again and still was receiving this error:
```
> metabase@0.0.0 build /Users/mm94978/mm_projects/metabase
> webpack

module.js:457
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mm94978/mm_projects/metabase/node_modules/html-webpack-plugin/index.js:4:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/mm94978/.nvm/versions/node/v6.5.0/bin/node" "/Users/mm94978/.nvm/versions/node/v6.5.0/bin/npm" "run" "build"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! metabase@0.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the metabase@0.0.0 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the metabase package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs metabase
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls metabase
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mm94978/mm_projects/metabase/npm-debug.log
```

In my initial hunt for solutions, I ensured that `node` and `npm` were up to date. I also attempted to follow the information [here](http://www.metabase.com/docs/v0.17.1/developers-guide-osx.html). Is that information relevant to the version of metabase on master? The line that failed for me from the prereqs of that page was the call to `cpan`. I tried updating `cpan` to make sure I was getting the most recent perl packages, but that didn't help either.

I am happy to provide any information that might enlighten what is different about my setup than what is expected.

**Comment by camsaul** [comment]
The directions in that link are for packaging up the built uberjar into `Metabase.app`, so they're not what you want. The only steps you should need to follow are

```bash
cd /path/to/metabase/ && npm install && npm run build && lein ring server
```

If you're having trouble getting `npm install` it might be helpful to run it in verbose mode.

**Comment by erp12** [comment]
Oh okay. Good to know that link isn't relevant. Thank you.

`npm install --verbose` seems to have run fine.
```
npm info it worked if it ends with ok
npm verb cli [ '/Users/mm94978/.nvm/versions/node/v6.5.0/bin/node',
npm verb cli   '/Users/mm94978/.nvm/versions/node/v6.5.0/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose' ]
npm info using npm@3.10.3
npm info using node@v6.5.0
npm verb correctMkdir /Users/mm94978/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/mm94978/.npm/_locks/staging-5ae35ab0bfc88d79.lock for /Users/mm94978/mm_projects/metabase/node_modules/.staging
npm verb unlock done using /Users/mm94978/.npm/_locks/staging-5ae35ab0bfc88d79.lock for /Users/mm94978/mm_projects/metabase/node_modules/.staging
npm info lifecycle metabase@0.0.0~preinstall: metabase@0.0.0
npm info linkStuff metabase@0.0.0
npm verb linkBins metabase@0.0.0
npm verb linkMans metabase@0.0.0
npm info lifecycle metabase@0.0.0~install: metabase@0.0.0
npm info lifecycle metabase@0.0.0~postinstall: metabase@0.0.0
npm info lifecycle metabase@0.0.0~prepublish: metabase@0.0.0
npm verb exit [ 0, true ]
npm info ok
```

And yet `npm run build` still yields the same result as my previous posts.
Thank you for continuing to assist.

**Comment by camsaul** [comment]
@kdoh any idea why npm isn't installing anything for @erp12 ?

**Comment by kdoh** [comment]
Sorry you're running into problems @erp12. This is quite odd. I've occasionally run into issues where the npm cache gets out of whack and thinks packages are installed when they aren't. I usually run `rm -fr node_modules/` in the root metabase directory and try installing again when this happens.

I just tried a fresh clone and did `npm install` and `npm run build` and everything seemed to work fine. Let me know if removing the node modules directory works and if not we can try to keep debugging, but nothing about the logs you shared stands out at me. 

For reference here are my node and npm versions
```
npm : 3.10.3
node: 6.4.0
```

**Comment by erp12** [comment]
Success! I was able to run `npm install`,  `npm run build` and `lein ring server` with no problems, and I was presented with the metabase opening page on port 3000. Thank you both for your time and help.

**Comment by kdoh** [comment]
Excellent! Glad it worked for you. 
![beardance](https://cloud.githubusercontent.com/assets/5248953/18185189/45f7dd7c-7051-11e6-8430-e1cf476eb3cb.gif)

I'm gonna go ahead and close this but definitely let us know if you have any more questions as you work on the driver, and thanks for getting involved in the project.
