### ISSUE TITLE
v0.47.0-RC3 - Drill-through results in JS Error

### ISSUE THREAD

**Issue by itgkarl** [metabase/metabase#33079]
### Describe the bug

In the RCs of v0.47.0 (tested with RC2 and RC3) the drill-through functionality is not working anymore in a language setup other than English.

Clicking on a chart used to open a drill-through dialog.

In the current v047.0-RC3 clicking on a chart does not open the drill-through dialog, instead leading to a JS `Uncaught TypeError: e is undefined` Error.

(Same and simmilar JS-Logs occur as warnings when i load the site initially or resize the window).

----

I first recognized this error in v0.47.0-RC2. The for now latest Version v.0.46.7 ist working as expected.
I tested the Error with `Firefox 102.14.0esr` and `chrome 115.0.5790.171` on a fresh docker image.

### To Reproduce

1. Start a fresh `metabase/metabase:v0.47.0-RC3` docker container and initialize it with a Language other than English (E.g. German).
2. Use the sample data provided and open the X-Ray view of any Entity (E.g. "Account")
3. Try to use the Drill-through function by clicking on a diagramm (E.g. "How Seats is distributed")
4. See error in the JS console of your browser. Drill-through dialog is not shown.

(2. and 3. are only an example to get a diagram for the test. The error occurs on any drill-through on any Diagramm i have tested)

### Expected behavior

The click on the diagramm should open a drill-thropugh dialog to break out of the original diagramm.

### Logs

Firefox:
```
Uncaught TypeError: e is undefined
    S ttag.min.js:1
    S ttag.min.js:1
    d ttag.min.js:1
    Fe UnderlyingRecordsDrill.ts:24
    o Mode.ts:34
    value Mode.ts:34
    value Visualization.jsx:239
    xt Visualization.jsx:278
    t apply_tooltips.js:513
    ye d3.js:1120
    me d3.js:1090
    each d3.js:962
    Ae d3.js:968
    each d3.js:961
    on d3.js:1073
    gm apply_tooltips.js:525
    r d3.js:504
    _activateRenderlets dc.js:1713
    render dc.js:1697
    Nb LineAreaBarPostRender.js:695
    dv LineAreaBarRenderer.js:925
    52693 LineAreaBarRenderer.js:967
    value CardRenderer.jsx:91
    value CardRenderer.jsx:44
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    m ExplicitSize.jsx:137
    Lodash 3
    r resize-observer.ts:12
    r resize-observer.ts:12
    r resize-observer.ts:10
    80932 resize-observer.ts:16
    Webpack 40
ttag.min.js:1:6295
```

chrome:
```
ttag.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at ttag.min.js:1:6305
    at Array.reduce (<anonymous>)
    at S (ttag.min.js:1:6273)
    at d (ttag.min.js:1:9237)
    at Fe (UnderlyingRecordsDrill.ts:24:23)
    at Mode.ts:34:50
    at Array.flatMap (<anonymous>)
    at e.value (Mode.ts:34:33)
    at u.value (Visualization.jsx:239:14)
    at Visualization.jsx:278:12
(anonymous) @ ttag.min.js:1
S @ ttag.min.js:1
d @ ttag.min.js:1
Fe @ UnderlyingRecordsDrill.ts:24
(anonymous) @ Mode.ts:34
value @ Mode.ts:34
value @ Visualization.jsx:239
(anonymous) @ Visualization.jsx:278
t @ apply_tooltips.js:513
(anonymous) @ d3.js:1120
```

No Messages in the server-log (obviously).

In the attachments you can finde the full browser-console-log including the warnigs that occure when loading the Page.
Last Error is the one occurring when I click on the diagram.
[chrome_localhost-1691665143427.log](https://github.com/metabase/metabase/files/12312046/chrome_localhost-1691665143427.log)
[firefox_console-export-2023-8-10_9-58-28.txt](https://github.com/metabase/metabase/files/12312050/firefox_console-export-2023-8-10_9-58-28.txt)

### Information about your Metabase installation

```JSON
- `Firefox 102.14.0esr` and `chrome 115.0.5790.171`
- Windows 10 Enterprise 10.0.19045 Build 19045
- Database: Clean installation with default embedded DB and sample-data
- Version: v0.47.0-RC3
- Hosting env: Local client with Docker Desktop. Official docker-image v0.47.0-RC3.
- Internal database: H2 (default)

Troubleshooting (with firefox):

{
  "browser-info": {
    "language": "de",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "4.19.128-microsoft-standard",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-07",
      "tag": "v0.47.0-RC3",
      "branch": "release-x.47.x",
      "hash": "b6c3000"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Workaround exists. (Change Language to English)

### Additional context

In my corporate setup i was not able to retest everything with all the latest browser versions.
But IMHO the browser versions are not that old that they should cause trouble.

I tested everything with the latest release v0.46.7 and the same setup. Everything works fine there.

- Screen Firefox 102.14.0esr:
![47_RC3_Firefox](https://github.com/metabase/metabase/assets/2795336/37203356-ee1e-40c6-9ca8-891d8cac2f39)

Screen chrome 115.0.5790.171:
![47_RC3_Chrome](https://github.com/metabase/metabase/assets/2795336/8c591a2c-50b8-4475-98b4-36f4fcddebd4)

**Comment by itgkarl** [comment]
Thanks @deniskaber for the indepth analysis of this Bug!

I can confirm, that changing the language to English fixed the issue for me.

I changed the `To Reproduce` section to make the required language setting clear.
I lowered the serverity since a workaround exists. Still something that should be fixed IMHO.

I tried some other languages (Franch, Italian, Russian). All of the ones I tried, other than English, were affected.
