### ISSUE TITLE
Serialization won't work in v47-RC3

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33104]
### Describe the bug

Serialization stopped working completely in the latest release candidate

### To Reproduce

just try to dump or export in v47-RC3 with a valid enterprise token, it won't work at all

### Expected behavior

It should check the license and work

### Logs

clojure.lang.ExceptionInfo: Serialization is a paid feature not currently available to your instance. Please upgrade to use it. Learn more at metabase.com/upgrade/ {:status-code 402}
	at metabase.public_settings.premium_features$ee_feature_error.invokeStatic(premium_features.clj:251)
	at metabase.public_settings.premium_features$ee_feature_error.invoke(premium_features.clj:248)
	at metabase.public_settings.premium_features$fn__47830$assert_has_feature__47831.invoke(premium_features.clj:264)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13257.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase_enterprise.serialization.cmd$check_premium_token_BANG_.invokeStatic(cmd.clj:51)
	at metabase_enterprise.serialization.cmd$check_premium_token_BANG_.invoke(cmd.clj:50)
	at metabase_enterprise.serialization.cmd$v2_dump.invokeStatic(cmd.clj:208)
	at metabase_enterprise.serialization.cmd$v2_dump.invoke(cmd.clj:203)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$call_enterprise.invokeStatic(cmd.clj:53)
	at metabase.cmd$call_enterprise.doInvoke(cmd.clj:43)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at metabase.cmd$export.invokeStatic(cmd.clj:223)
	at metabase.cmd$export.doInvoke(cmd.clj:206)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__118530.invoke(cmd.clj:299)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:298)
	at metabase.cmd$run_cmd.invoke(cmd.clj:288)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:181)
	at metabase.core$run_cmd.invoke(core.clj:179)
	at metabase.core$_main.invokeStatic(core.clj:203)
	at metabase.core$_main.doInvoke(core.clj:198)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
Command failed with exception: Serialization is a paid feature not currently available to your instance. Please upgrade to use it. Learn more at metabase.com/upgrade/

### Information about your Metabase installation

```JSON
v47-RC3
```

### Severity

P1

**Comment by luizarakaki** [comment]
@paoliniluis I couldn't repro... I exported both serdes v1 (dump) and v2 (export) on RC3

![image](https://github.com/metabase/metabase/assets/32561114/a7187111-da55-46de-983f-df3e0672f177)

**Comment by paoliniluis** [comment]
sorry @luizarakaki, I need some sleep
