### ISSUE TITLE
Some table columns are unable to be rendered

### ISSUE THREAD

**Issue by qwef** [metabase/metabase#33279]
### Describe the bug

Some card columns aren't being able to be rendered. Without the specific column though, the card renders fine.

### To Reproduce

1. Unable to reproduce on master, but it happens on stats: https://stats.metabase.com/question/12874-cancellation-survey-responses-for-alert

### Expected behavior

Should render correctly

### Information about your Metabase installation

```JSON
master branch (bec9c95)
```

### Severity

Unknown

**Comment by perivamsi** [comment]
Here is the stack trace for this issue

```

[1415d802-d7fd-4214-b54c-d8e8836af22d] 2023-08-22T21:37:11-04:00 DEBUG metabase.pulse Sending Pulse (758: "Vamsi Dashboard") with 1 Cards via Slack
[1415d802-d7fd-4214-b54c-d8e8836af22d] 2023-08-22T21:37:11-04:00 DEBUG metabase.pulse.render Rendering pulse card with chart-type :table and render-type :inline
[1415d802-d7fd-4214-b54c-d8e8836af22d] 2023-08-22T21:37:11-04:00 ERROR metabase.pulse.render Pulse card render error
java.lang.IndexOutOfBoundsException
	at clojure.lang.RT.nthFrom(RT.java:928)
	at clojure.lang.RT.nth(RT.java:897)
	at metabase.pulse.render.body$filter_rows$keep_filtered_idx__77640$fn__77641.invoke(body.clj:219)
	at clojure.core$map$fn__5935.invoke(core.clj:2772)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$seq__5467.invoke(core.clj:139)
	at metabase.pulse.render.table$render_table_head$iter__77255__77259$fn__77260.invoke(table.clj:88)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:713)
	at clojure.core$next__5451.invokeStatic(core.clj:64)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:169)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$into.invokeStatic(core.clj:6958)
	at clojure.core$into.invoke(core.clj:6950)
	at metabase.pulse.render.table$render_table_head.invokeStatic(table.clj:87)
	at metabase.pulse.render.table$render_table_head.invoke(table.clj:85)
	at metabase.pulse.render.table$render_table.invokeStatic(table.clj:151)
	at metabase.pulse.render.table$render_table.invoke(table.clj:135)
	at metabase.pulse.render.table$render_table.invokeStatic(table.clj:141)
	at metabase.pulse.render.table$render_table.invoke(table.clj:135)
	at metabase.pulse.render.body$fn__77659$render__77647__77664$fn__77668.invoke(body.clj:233)
	at metabase.pulse.render.body$fn__77659$render__77647__77664.invoke(body.clj:223)
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
	at metabase.pulse.render$fn__78944$render_pulse_card_body__78949$fn__78953.invoke(render.clj:131)
	at metabase.pulse.render$fn__78944$render_pulse_card_body__78949.invoke(render.clj:121)
	at metabase.pulse.render$fn__78985$render_pulse_card__78990$fn__78991.invoke(render.clj:163)
	at metabase.pulse.render$fn__78985$render_pulse_card__78990.invoke(render.clj:145)
	at metabase.pulse$part__GT_attachment_data.invokeStatic(pulse.clj:255)
	at metabase.pulse$part__GT_attachment_data.invoke(pulse.clj:247)
	at metabase.pulse$create_slack_attachment_data$iter__104346__104350$fn__104351.invoke(pulse.clj:272)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$seq__5467.invoke(core.clj:139)
	at clojure.core$tree_seq$walk__6455$fn__6456.invoke(core.clj:4970)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:58)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$concat$cat__5560$fn__5561.invoke(core.clj:736)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:713)
	at clojure.core$next__5451.invokeStatic(core.clj:64)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:169)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:335)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:326)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:332)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:326)
	at metabase.pulse$fn__104572.invokeStatic(pulse.clj:519)
	at metabase.pulse$fn__104572.invoke(pulse.clj:517)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.util.retry$decorate$fn$reify__102204.call(retry.clj:45)
	at io.github.resilience4j.retry.Retry.lambda$decorateCallable$5(Retry.java:306)
	at metabase.util.retry$decorate$fn__102203.doInvoke(retry.clj:46)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.pulse$send_notification_retrying_BANG_.invokeStatic(pulse.clj:607)
	at metabase.pulse$send_notification_retrying_BANG_.doInvoke(pulse.clj:601)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at metabase.pulse$send_notifications_BANG_$fn__104629.invoke(pulse.clj:614)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:613)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:609)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:637)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:618)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.api.pulse$fn__105704.invokeStatic(pulse.clj:325)
	at metabase.api.pulse$fn__105704.invoke(pulse.clj:311)
	at compojure.core$wrap_response$fn__43140.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__43124.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__43129.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__43133.invoke(core.clj:151)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43133.invoke(core.clj:153)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43133.invoke(core.clj:153)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43133.invoke(core.clj:153)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43133.invoke(core.clj:152)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__98006.invoke(auth.clj:17)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152.invoke(core.clj:200)
	at compojure.core$make_context$handler__43180.invoke(core.clj:290)
	at compojure.core$make_context$fn__43184.invoke(core.clj:300)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:199)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:199)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152.invoke(core.clj:200)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:199)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152.invoke(core.clj:200)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152.invoke(core.clj:200)
	at metabase.api.routes$fn__106298$fn__106299.invoke(routes.clj:64)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__106461$fn__106462.doInvoke(routes.clj:72)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152.invoke(core.clj:200)
	at compojure.core$make_context$handler__43180.invoke(core.clj:290)
	at compojure.core$make_context$fn__43184.invoke(core.clj:300)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43133.invoke(core.clj:153)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43133.invoke(core.clj:153)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43133.invoke(core.clj:153)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:199)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:199)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:199)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152.invoke(core.clj:200)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152.invoke(core.clj:200)
	at compojure.core$make_context$handler__43180.invoke(core.clj:290)
	at compojure.core$make_context$fn__43184.invoke(core.clj:300)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152$f__43153$respond_SINGLEQUOTE___43154.invoke(core.clj:197)
	at compojure.core$make_context$fn__43184.invoke(core.clj:301)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152.invoke(core.clj:200)
	at compojure.core$routes$fn__43152$f__43153.invoke(core.clj:198)
	at compojure.core$routes$fn__43152.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__103383.invoke(exceptions.clj:107)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__103380.invoke(exceptions.clj:95)
	at metabase.server.middleware.log$log_api_call$fn__108335$fn__108336$fn__108337.invoke(log.clj:216)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12)
	at metabase.server.middleware.log$log_api_call$fn__108335$fn__108336.invoke(log.clj:208)
	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112)
	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103)
	at metabase.server.middleware.log$log_api_call$fn__108335.invoke(log.clj:207)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__113383.invoke(browser_cookie.clj:41)
	at metabase.server.middleware.security$add_security_headers$fn__86004.invoke(security.clj:169)
	at metabase.server.middleware.json$wrap_json_body$fn__110832.invoke(json.clj:67)
	at metabase.server.middleware.offset_paging$handle_paging$fn__86028.invoke(offset_paging.clj:45)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__110850.invoke(json.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__113650.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__113669.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__58381.invoke(misc.clj:61)
	at metabase.server.middleware.session$reset_session_timeout$fn__68237.invoke(session.clj:441)
	at metabase.server.middleware.session$bind_current_user$fn__68204$fn__68205.invoke(session.clj:336)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:315)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:304)
	at metabase.server.middleware.session$bind_current_user$fn__68204.invoke(session.clj:335)
	at metabase.server.middleware.session$wrap_current_user_info$fn__68185.invoke(session.clj:285)
	at metabase.server.middleware.session$wrap_session_id$fn__68168.invoke(session.clj:217)
	at metabase.server.middleware.auth$wrap_api_key$fn__98014.invoke(auth.clj:30)
	at ring.middleware.cookies$wrap_cookies$fn__113570.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__58363.invoke(misc.clj:29)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__58389.invoke(misc.clj:78)
	at ring.middleware.gzip$wrap_gzip$fn__113612.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__58392.invoke(misc.clj:95)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__113399.invoke(ssl.clj:51)
	at metabase.server$async_proxy_handler$fn__74654.invoke(server.clj:77)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
	at java.base/java.lang.Thread.run(Unknown Source)
```
