### ISSUE TITLE
Uncaught Promise error on dashboard filters when a locked, null parameter is present

### ISSUE THREAD

**Issue by josiah44** [metabase/metabase#33542]
### Describe the bug

Video Recording of the Bug and Setup:
https://github.com/metabase/metabase/assets/10182211/50c697de-b246-4366-a8b9-27955db24f65

We have an embedded dashboard with three parameters:
1. A required, locked parameter.  This always has a parameter value in the jwt token.
2. An optional, locked parameter.  When this is not applicable (base on the user), [we pass an empty array in the jwt token in our embedded code](https://github.com/metabase/metabase/issues/7306#issuecomment-1296243924).
3. An editable parameter.  This is the only parameter the user sees, and it is a dropdown list of values in the filter.

When a value is supplied for the 2nd parameter, there is no issue.  The data that the user sees is appropriately limited, and the 3rd parameter works as expected.

However, when we pass an empty array for the 2nd parameter, the 3rd filter no longer displays a dropdown list of values, and we see an "Uncaught Promise" error in the dev console.

### To Reproduce

1. In your Data Model (Admin Settings > Data Model), ensure you have a source table with three fields with the following settings:
  - "Field Type" set to "Category"
  - "Filtering on this field" set to "A list of all values"
![image](https://github.com/metabase/metabase/assets/10182211/8ce527c5-7ba3-4f9d-b491-e8dc8983c3c0)

2. Using the table form step 1, create a question with three field filters.  Below is a screenshot of my simple test question for reference:
![image](https://github.com/metabase/metabase/assets/10182211/e0d1c247-71d5-4b42-a47c-bfe837eb2f65)
3. Add the question from step 2 to a new dashboard
4. In the dashboard, add three corresponding "Category" filters, and link the filters from the dashboard to the card
5. Save the card, and select Sharing > Embed in your application > Set up
6. In the "Parameters" section of the Embed page, set two of the parameters to "Locked", and the third to "Editable":
![image](https://github.com/metabase/metabase/assets/10182211/00f83898-c121-49fa-9e98-f920dfa14a34)

7. Embed your dashboard into a web application.  Pass a valid value from your data for one of the locked parameters.  Pass a blank array for the second locked value.  NOTE: Unfortunately this cannot be tested from the Embedding preview, since blank arrays cannot be passed here.
8. View your embedded dashboard in your web application, and click the visible dropdown filter.

RESULT:
You will receive an error message in the console (see logs for details), and the dropdown filter is replaced by a text input box.

### Expected behavior

When selecting the filter, the user should see the dropdown list of options.  There should not be an error in the dev console.

### Logs

Metabase Logs Below:
```
[5e3344ea-237b-480a-ac58-b1c366e05d1a] 2023-08-28T10:24:21-06:00 DEBUG metabase.server.middleware.log GET /api/embed/dashboard/eyJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjY1OH0sInBhcmFtcyI6eyJsb3NzX2xlbmRlcl9pZCI6WyI0MCJdLCJicmFuY2giOltdfSwiZXhwIjoxNjkzMjQwNDYwfQ.yekG0LpjHKfeT8k3JvlBjb8vEbry0g3nOTRVKdbVZvc 200 13.3 ms (10 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (1 idle, 0 queued) (166 total active threads) Queries in flight: 0 (0 queued)
[5e3344ea-237b-480a-ac58-b1c366e05d1a] 2023-08-28T10:24:21-06:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 9.6 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (1 idle, 0 queued) (166 total active threads) Queries in flight: 0 (0 queued)
[5e3344ea-237b-480a-ac58-b1c366e05d1a] 2023-08-28T10:24:22-06:00 DEBUG metabase.server.middleware.log GET /api/embed/dashboard/eyJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjY1OH0sInBhcmFtcyI6eyJsb3NzX2xlbmRlcl9pZCI6WyI0MCJdLCJicmFuY2giOltdfSwiZXhwIjoxNjkzMjQwNDYwfQ.yekG0LpjHKfeT8k3JvlBjb8vEbry0g3nOTRVKdbVZvc/dashcard/7123/card/3848 202 [ASYNC: completed] 1.1 s (25 DB calls) App DB connections: 0/15 Jetty threads: 3/50 (2 idle, 0 queued) (168 total active threads) Queries in flight: 0 (0 queued); snowflake DB 5 connections: 0/1 (0 threads blocked)
[5e3344ea-237b-480a-ac58-b1c366e05d1a] 2023-08-28T10:24:23-06:00 ERROR metabase.api.embed Chain filter error
{:allowed-param-slugs {:loss_lender_id "locked", :branch "locked", :loan_type "enabled"},
 :param-id "522fbe2d",
 :schema (recursive #'metabase.mbql.schema/Filter*),
 :id->slug {"398cbecc" "loss_lender_id", "2a63f6fc" "branch", "522fbe2d" "loan_type"},
 :value [:and [:= [:field 16250 nil] "40"] [:= [:field 19569 nil]]],
 :dashboard-params
 [{:name "LOSS Lender ID",
   :slug "loss_lender_id",
   :id "398cbecc",
   :type :number/=,
   :sectionId "number",
   :filteringParameters ["522fbe2d" "2a63f6fc"]}
  {:name "Branch",
   :slug "branch",
   :id "2a63f6fc",
   :type :string/=,
   :sectionId "string",
   :filteringParameters ["6eccbf07" "398cbecc" "522fbe2d"]}
  {:name "Loan Type",
   :slug "loan_type",
   :id "522fbe2d",
   :type :string/=,
   :sectionId "string",
   :filteringParameters ["6eccbf07" "398cbecc" "2a63f6fc"]}],
 :slug->id {"loss_lender_id" "398cbecc", "branch" "2a63f6fc", "loan_type" "522fbe2d"},
 :type :schema.core/error,
 :dashboard-id 658,
 :token-params {:loss_lender_id ["40"], :branch []},
 :param-slug "loan_type",
 :error
 (named [nil nil (named (named [nil nil (not (present? "value-or-field"))] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "second-clause")] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!="),
 :merged-id-params {"398cbecc" ["40"], "2a63f6fc" []}}

clojure.lang.ExceptionInfo: Output of combine-filter-clauses does not match schema: 
	   (named [nil nil (named (named [nil nil (not (present? "value-or-field"))] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "second-clause")] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=")  
 {:dashboard-id 658, :dashboard-params [{:name "LOSS Lender ID", :slug "loss_lender_id", :id "398cbecc", :type :number/=, :sectionId "number", :filteringParameters ["522fbe2d" "2a63f6fc"]} {:name "Branch", :slug "branch", :id "2a63f6fc", :type :string/=, :sectionId "string", :filteringParameters ["6eccbf07" "398cbecc" "522fbe2d"]} {:name "Loan Type", :slug "loan_type", :id "522fbe2d", :type :string/=, :sectionId "string", :filteringParameters ["6eccbf07" "398cbecc" "2a63f6fc"]}], :allowed-param-slugs {:loss_lender_id "locked", :branch "locked", :loan_type "enabled"}, :slug->id {"loss_lender_id" "398cbecc", "branch" "2a63f6fc", "loan_type" "522fbe2d"}, :id->slug {"398cbecc" "loss_lender_id", "2a63f6fc" "branch", "522fbe2d" "loan_type"}, :param-id "522fbe2d", :param-slug "loan_type", :token-params {:loss_lender_id ["40"], :branch []}}
	at metabase.api.embed$dashboard_param_values.invokeStatic(embed.clj:605)
	at metabase.api.embed$dashboard_param_values.invoke(embed.clj:577)
	at metabase.api.embed$fn__93538.invokeStatic(embed.clj:622)
	at metabase.api.embed$fn__93538.invoke(embed.clj:619)
	at compojure.core$wrap_response$fn__42432.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__42416.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__42421.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__42425.invoke(core.clj:151)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__42425.invoke(core.clj:152)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__42425.invoke(core.clj:152)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__42425.invoke(core.clj:152)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__42425.invoke(core.clj:152)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$message_only_exceptions$fn__96433.invoke(exceptions.clj:37)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444.invoke(core.clj:200)
	at compojure.core$make_context$handler__42472.invoke(core.clj:290)
	at compojure.core$make_context$fn__42476.invoke(core.clj:300)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:199)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:199)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444.invoke(core.clj:200)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:199)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444.invoke(core.clj:200)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444.invoke(core.clj:200)
	at metabase.api.routes$fn__99669$fn__99670.invoke(routes.clj:62)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__99830$fn__99831.doInvoke(routes.clj:70)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444.invoke(core.clj:200)
	at compojure.core$make_context$handler__42472.invoke(core.clj:290)
	at compojure.core$make_context$fn__42476.invoke(core.clj:300)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__42425.invoke(core.clj:152)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__42425.invoke(core.clj:152)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__42425.invoke(core.clj:152)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:199)
	at compojure.core$routes$fn__42444$f__42445$respond_SINGLEQUOTE___42446.invoke(core.clj:197)
	at compojure.core$make_context$fn__42476.invoke(core.clj:301)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444.invoke(core.clj:200)
	at compojure.core$routes$fn__42444$f__42445.invoke(core.clj:198)
	at compojure.core$routes$fn__42444.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__96461.invoke(exceptions.clj:103)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__96458.invoke(exceptions.clj:91)
	at metabase.server.middleware.log$log_api_call$fn__103127$fn__103128$fn__103129.invoke(log.clj:216)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12)
	at metabase.server.middleware.log$log_api_call$fn__103127$fn__103128.invoke(log.clj:208)
	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112)
	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103)
	at metabase.server.middleware.log$log_api_call$fn__103127.invoke(log.clj:207)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__109567.invoke(browser_cookie.clj:42)
	at metabase.server.middleware.security$add_security_headers$fn__80396.invoke(security.clj:153)
	at metabase.server.middleware.json$wrap_json_body$fn__106819.invoke(json.clj:67)
	at metabase.server.middleware.offset_paging$handle_paging$fn__80420.invoke(offset_paging.clj:45)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__106837.invoke(json.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__109834.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__109853.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__50568.invoke(misc.clj:61)
	at metabase.server.middleware.session$reset_session_timeout$fn__63848.invoke(session.clj:441)
	at metabase.server.middleware.session$bind_current_user$fn__63817$fn__63818.invoke(session.clj:336)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:315)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:304)
	at metabase.server.middleware.session$bind_current_user$fn__63817.invoke(session.clj:335)
	at metabase.server.middleware.session$wrap_current_user_info$fn__63798.invoke(session.clj:285)
	at metabase.server.middleware.session$wrap_session_id$fn__63781.invoke(session.clj:217)
	at metabase.server.middleware.auth$wrap_api_key$fn__87860.invoke(auth.clj:30)
	at ring.middleware.cookies$wrap_cookies$fn__109754.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__50550.invoke(misc.clj:29)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__50576.invoke(misc.clj:78)
	at ring.middleware.gzip$wrap_gzip$fn__109796.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__50579.invoke(misc.clj:95)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__109583.invoke(ssl.clj:51)
	at metabase.server$async_proxy_handler$fn__101893.invoke(server.clj:77)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: clojure.lang.ExceptionInfo: Output of combine-filter-clauses does not match schema: 
	   (named [nil nil (named (named [nil nil (not (present? "value-or-field"))] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "second-clause")] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=")  
 {:merged-id-params {"398cbecc" ["40"], "2a63f6fc" []}}
	at metabase.api.embed$dashboard_param_values.invokeStatic(embed.clj:601)
	... 165 more
Caused by: clojure.lang.ExceptionInfo: Output of combine-filter-clauses does not match schema: 
	   (named [nil nil (named (named [nil nil (not (present? "value-or-field"))] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "second-clause")] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=")  
 {:type :schema.core/error, :schema (recursive (var metabase.mbql.schema/Filter*)), :value [:and [:= [:field 16250 nil] "40"] [:= [:field 19569 nil]]], :error (named [nil nil (named (named [nil nil (not (present? "value-or-field"))] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=") "second-clause")] "Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=")}
	at metabase.mbql.util$fn__28373$combine_filter_clauses__28378.doInvoke(util.cljc:125)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.core$update.invokeStatic(core.clj:6233)
	at clojure.core$update.invoke(core.clj:6223)
	at metabase.models.params.chain_filter$add_filters$fn__91607.invoke(chain_filter.clj:168)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.models.params.chain_filter$add_filters.invokeStatic(chain_filter.clj:156)
	at metabase.models.params.chain_filter$add_filters.invoke(chain_filter.clj:155)
	at metabase.models.params.chain_filter$fn__91704$chain_filter_mbql_query__91709$fn__91713.invoke(chain_filter.clj:415)
	at metabase.models.params.chain_filter$fn__91704$chain_filter_mbql_query__91709.invoke(chain_filter.clj:368)
	at metabase.models.params.chain_filter$fn__91743$unremapped_chain_filter__91748$fn__91752.invoke(chain_filter.clj:426)
	at metabase.models.params.chain_filter$fn__91743$unremapped_chain_filter__91748.invoke(chain_filter.clj:421)
	at clojure.lang.Var.invoke(Var.java:393)
	at metabase.models.params.field_values$fetch_advanced_field_values.invokeStatic(field_values.clj:80)
	at metabase.models.params.field_values$fetch_advanced_field_values.invoke(field_values.clj:73)
	at metabase.models.params.field_values$create_advanced_field_values_BANG_.invokeStatic(field_values.clj:109)
	at metabase.models.params.field_values$create_advanced_field_values_BANG_.invoke(field_values.clj:104)
	at metabase.models.params.field_values$get_or_create_advanced_field_values_BANG_.invokeStatic(field_values.clj:135)
	at metabase.models.params.field_values$get_or_create_advanced_field_values_BANG_.invoke(field_values.clj:124)
	at metabase.models.params.field_values$get_or_create_linked_filter_field_values_BANG_.invokeStatic(field_values.clj:178)
	at metabase.models.params.field_values$get_or_create_linked_filter_field_values_BANG_.invoke(field_values.clj:165)
	at metabase.models.params.chain_filter$cached_field_values.invokeStatic(chain_filter.clj:556)
	at metabase.models.params.chain_filter$cached_field_values.invoke(chain_filter.clj:552)
	at metabase.models.params.chain_filter$fn__91919$chain_filter__91924$fn__91925.invoke(chain_filter.clj:587)
	at metabase.models.params.chain_filter$fn__91919$chain_filter__91924.doInvoke(chain_filter.clj:563)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at metabase.api.dashboard$fn__92679$chain_filter__92680$fn__92683.invoke(dashboard.clj:747)
	at clojure.core$map$fn__5935.invoke(core.clj:2772)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$map$fn__5935.invoke(core.clj:2763)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$apply.invokeStatic(core.clj:662)
	at clojure.core$mapcat.invokeStatic(core.clj:2800)
	at clojure.core$mapcat.doInvoke(core.clj:2800)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at metabase.api.dashboard$fn__92679$chain_filter__92680.invoke(dashboard.clj:749)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__15901.doInvoke(core.cljc:2518)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__15889.doInvoke(core.cljc:2535)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at metabase.api.dashboard$fn__92705$param_values__92714$fn__92717$fn__92718.invoke(dashboard.clj:781)
	at metabase.models.params.custom_values$parameter__GT_values.invokeStatic(custom_values.clj:131)
	at metabase.models.params.custom_values$parameter__GT_values.invoke(custom_values.clj:116)
	at metabase.api.dashboard$fn__92705$param_values__92714$fn__92717.invoke(dashboard.clj:781)
	at metabase.api.dashboard$fn__92705$param_values__92714.invoke(dashboard.clj:761)
	at metabase.api.embed$dashboard_param_values.invokeStatic(embed.clj:599)
	... 165 more
[5e3344ea-237b-480a-ac58-b1c366e05d1a] 2023-08-28T10:24:23-06:00 DEBUG metabase.server.middleware.log GET /api/embed/dashboard/eyJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjY1OH0sInBhcmFtcyI6eyJsb3NzX2xlbmRlcl9pZCI6WyI0MCJdLCJicmFuY2giOltdfSwiZXhwIjoxNjkzMjQwNDYwfQ.yekG0LpjHKfeT8k3JvlBjb8vEbry0g3nOTRVKdbVZvc/params/522fbe2d/values 400 31.2 ms (11 DB calls) 
"Output of combine-filter-clauses does not match schema: \n\n\t   (named [nil nil (named (named [nil nil (not (present? \"value-or-field\"))] \"Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=\") \"second-clause\")] \"Must be a valid instance of one of these clauses: :and, :or, :not, :<, :<=, :>, :>=, :=, :!=\")  \n\n"

[5e3344ea-237b-480a-ac58-b1c366e05d1a] 2023-08-28T10:24:27-06:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 9.7 ms (10 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (2 idle, 0 queued) (167 total active threads) Queries in flight: 0 (0 queued)
[5e3344ea-237b-480a-ac58-b1c366e05d1a] 2023-08-28T10:24:27-06:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 9.5 ms (6 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (2 idle, 0 queued) (167 total active threads) Queries in flight: 0 (0 queued)
[5e3344ea-237b-480a-ac58-b1c366e05d1a] 2023-08-28T10:24:27-06:00 DEBUG metabase.server.middleware.log GET /api/database 200 3.0 ms (3 DB calls) App DB connections: 0/15 Jetty threads: 4/50 (2 idle, 0 queued) (167 total active threads) Queries in flight: 0 (0 queued)
```

And a screenshot from the developer tools in Chrome:
![image](https://github.com/metabase/metabase/assets/10182211/86bc6f3c-426d-4a19-b1a0-3f156c22d4c9)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20+8",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.1"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-28",
      "tag": "v1.46.6.4",
      "branch": "release-x.46.6.x",
      "hash": "7c60aca"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

We're using these locked parameters for security/data segmentation purposes.  The result is that we cannot use dropdown filters for any of our embedded dashboards, so it's unfortunately a big issue.

**Comment by paoliniluis** [comment]
I think this is a duplicate of https://github.com/metabase/metabase/issues/14474, can you please check?

**Comment by paoliniluis** [comment]
@josiah44 please check, otherwise I’ll have to close the issue

**Comment by josiah44** [comment]
Hey @paoliniluis , my engineering team checked out #14474, and it is not a duplicate.  This is a separate issue, unfortunately.

**Comment by ranquild** [comment]
The error is coming from a BE endpoint. It seems that such a combination is not supported by some schema. Making it a BE bug.
