### ISSUE TITLE
Overall performance regression between 44 and 45+

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33567]
### Describe the bug

Made some basic (just a few endpoints and methods) load testing to see the origin of https://github.com/metabase/metabase/issues/31513 and found some interesting thing: in v44 the load test was sustained till 35 concurrent users, while in v45+ it's 25 users

As the application will start sending 5xx errors when there's no more CPU available to answer requests, we should review what we did on 45 to make such a performance regression 

### To Reproduce

1) Spin up https://github.com/paoliniluis/metabase-load-test-k6
2) change the version between 44 and 45

### Expected behavior

We should at least maintain performance of the backend across versions

### Logs

44.x load test
```
time="2023-08-28T20:39:41Z" level=error msg="GET http://metabase:3000/api/automagic-dashboards/table/7? 404 404 Not Found" source=console
time="2023-08-28T20:39:41Z" level=error msg="POST http://metabase:3000/api/dataset 0 " source=console

     ✗ status code MUST be 200
      ↳  99% — ✓ 4723 / ✗ 1

   ✓ checks.........................: 99.97% ✓ 4723      ✗ 1    
     data_received..................: 307 MB 1.8 MB/s
     data_sent......................: 2.4 MB 14 kB/s
     http_req_blocked...............: avg=7.29µs   min=852ns   med=3.98µs  max=725.56µs p(90)=9.36µs   p(95)=11.25µs 
     http_req_connecting............: avg=1.65µs   min=0s      med=0s      max=564.84µs p(90)=0s       p(95)=0s      
     http_req_duration..............: avg=117.62ms min=1.79ms  med=27.64ms max=2.49s    p(90)=280.96ms p(95)=701.59ms
       { expected_response:true }...: avg=117.62ms min=1.79ms  med=27.62ms max=2.49s    p(90)=281.42ms p(95)=701.63ms
     http_req_failed................: 0.01%  ✓ 1         ✗ 5151 
     http_req_receiving.............: avg=26.33ms  min=18.59µs med=66.64µs max=1.79s    p(90)=33.25ms  p(95)=59.32ms 
     http_req_sending...............: avg=23.45µs  min=4.34µs  med=18.16µs max=460.07µs p(90)=42.45µs  p(95)=52.16µs 
     http_req_tls_handshaking.......: avg=0s       min=0s      med=0s      max=0s       p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=91.26ms  min=1.76ms  med=19.98ms max=2.49s    p(90)=207.58ms p(95)=501.18ms
     http_reqs......................: 5152   29.531396/s
     iteration_duration.............: avg=18.96s   min=17.71s  med=17.89s  max=32.44s   p(90)=20.38s   p(95)=29.39s  
     iterations.....................: 125    0.716503/s
     vus............................: 35     min=1       max=35 
     vus_max........................: 100    min=100     max=100


running (02m54.5s), 000/100 VUs, 124 complete and 35 interrupted iterations
default ✗ [   8% ] 031/100 VUs  02m54.5s/38m00.0s
time="2023-08-28T20:39:42Z" level=error msg="test aborted: status code was *not* 200, 202 or 204 at checker (file:///home/k6/script.js:65:28(39))"
```

v45.x load test
```
running (02m03.0s), 025/100 VUs, 69 complete and 0 interrupted iterations
default   [   5% ] 025/100 VUs  02m03.0s/38m00.0s
time="2023-08-28T20:43:57Z" level=error msg="GET http://metabase:3000/api/automagic-dashboards/table/11? 404 404 Not Found" source=console
time="2023-08-28T20:43:57Z" level=error msg="GET http://metabase:3000/api/database/2/autocomplete_suggestions?substring=pe 0 " source=console
time="2023-08-28T20:43:57Z" level=error msg="POST http://metabase:3000/api/dataset 0 " source=console
time="2023-08-28T20:43:57Z" level=error msg="POST http://metabase:3000/api/card 0 " source=console
time="2023-08-28T20:43:57Z" level=error msg="POST http://metabase:3000/api/card 0 " source=console

     ✗ status code MUST be 200
      ↳  99% — ✓ 2623 / ✗ 1

   ✓ checks.........................: 99.96% ✓ 2623      ✗ 1    
     data_received..................: 169 MB 1.4 MB/s
     data_sent......................: 1.4 MB 11 kB/s
     http_req_blocked...............: avg=8.28µs  min=741ns   med=3.81µs  max=663.04µs p(90)=9.48µs  p(95)=12µs    
     http_req_connecting............: avg=2.52µs  min=0s      med=0s      max=536.23µs p(90)=0s      p(95)=0s      
     http_req_duration..............: avg=52.83ms min=2.07ms  med=24.72ms max=1.12s    p(90)=95.58ms p(95)=203.95ms
       { expected_response:true }...: avg=52.81ms min=2.07ms  med=24.7ms  max=1.12s    p(90)=95.58ms p(95)=203.95ms
     http_req_failed................: 0.03%  ✓ 1         ✗ 2866 
     http_req_receiving.............: avg=12.21ms min=12.95µs med=62.14µs max=892.14ms p(90)=32.02ms p(95)=55.33ms 
     http_req_sending...............: avg=23.27µs min=3.86µs  med=17.28µs max=171.73µs p(90)=44.95µs p(95)=55.76µs 
     http_req_tls_handshaking.......: avg=0s      min=0s      med=0s      max=0s       p(90)=0s      p(95)=0s      
     http_req_waiting...............: avg=40.59ms min=2.03ms  med=17.99ms max=1.11s    p(90)=82.82ms p(95)=144.77ms
     http_reqs......................: 2867   23.297074/s
     iteration_duration.............: avg=18.19s  min=16.12s  med=17.88s  max=22.65s   p(90)=18.67s  p(95)=20.1s   
     iterations.....................: 70     0.568816/s
     vus............................: 25     min=1       max=25 
     vus_max........................: 100    min=100     max=100


running (02m03.1s), 000/100 VUs, 69 complete and 25 interrupted iterations
default ✗ [   5% ] 022/100 VUs  02m03.1s/38m00.0s
time="2023-08-28T20:43:58Z" level=error msg="test aborted: status code was *not* 200, 202 or 204 at checker (file:///home/k6/script.js:65:28(39))"

```

### Information about your Metabase installation

```JSON
v45+
```

### Severity

P1

**Comment by perivamsi** [comment]
closing this in favor of specific perf bugs/enhancements we are doing for v50
