### ISSUE TITLE
Stacked bar chart returns with "Cannot read properties of undefined (reading 'length')"

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#33693]
### Describe the bug

A bar chart in master breaks with that error when you stack it to 100%

### To Reproduce

1) go to [this question](https://stats.metabase.com/question/13148-repro-33693)
2) stack the bar chart to 100%, it will break

### Expected behavior

should show a stacked bar chart

### Logs

CardRenderer.jsx:97 TypeError: Cannot read properties of undefined (reading 'length')
    at trends.js:36:31
    at JU (LineAreaBarRenderer.js:685:7)
    at LineAreaBarRenderer.js:707:22
    at XU (LineAreaBarRenderer.js:906:3)
    at Object.renderer (LineAreaBarRenderer.js:983:3)
    at o.value (CardRenderer.jsx:91:37)
    at o.value (CardRenderer.jsx:44:10)
    at hs (react-dom.production.min.js:212:231)
    at Ec (react-dom.production.min.js:255:229)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)

### Information about your Metabase installation

```JSON
master
```

### Severity

P2

**Comment by alxnddr** [comment]
Closed by https://github.com/metabase/metabase/pull/40624
