### ISSUE TITLE
Unable to change/delete "Unknown field"

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#33835]
### Describe the bug

When the question editor, and a field in an aggregation has been removed from DB, it shows "Unknown field", but clicking on it generates a JS error in console, and the field cannot be deleted/changed.

### To Reproduce

(I have only seen this on my production DB.)
1. Create a question from the sample DB.
2. Remove a field in the DB.
3. Rescan the DB in Metabase.
4. Go to the question and notice the "Unknown FIeld".
5. Try clicking on it to remove it or to select a different field.
6. Nothing happens, JS console shows error.
![8 Sep 2023 at 15_43_54](https://github.com/metabase/metabase/assets/30152071/5686abee-b5d4-4dfd-9d93-2044dfd96528)

### Expected behavior

User should be able to change/delete the field

### Logs

react-dom.production.min.js:52 Uncaught TypeError: Cannot read properties of null (reading 'toLowerCase')
    at k.kG (metabase.util.js:17:233)
    at Function.e [as h] (metabase.mbql.util.js:46:264)
    at Function.o [as g] (metabase.mbql.util.js:47:279)
    at Function.i [as g] (cljs.core.js:310:234)
    at metabase.lib.stage.js:12:141
    at Xe (cljs.core.js:77:431)
    at yr.h.ba (cljs.core.js:292:23)
    at yr.A (cljs.core.js:45:193)
    at yr.Rf (cljs.core.js:90:167)
    at s (metabase.lib.stage.js:11:34)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "nl-NL",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "13.0.2+8",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "13.0.2",
    "java.vm.name": "Eclipse OpenJ9 VM",
    "java.vm.version": "openj9-0.18.0",
    "os.name": "Linux",
    "os.version": "4.15.0-66-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.43"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-07",
      "tag": "v0.47.1",
      "branch": "release-x.47.x",
      "hash": "bd278b9"
    },
    "settings": {
      "report-timezone": "Europe/Brussels"
    }
  }
}
```

### Severity

Minor issue, can be worked around by removing the whole aggregation

**Comment by ranquild** [comment]
I can delete the breakout based on now-deleted field in the db without issues 

<img src="https://uploads.linear.app/a24a1a82-ddc8-4567-aacc-c3804ea2385e/b8239885-3a25-4371-be81-111677329315/28b23560-140f-4ed0-b322-722dde4c4051?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2EyNGExYTgyLWRkYzgtNDU2Ny1hYWNjLWMzODA0ZWEyMzg1ZS9iODIzOTg4NS0zYTI1LTQzNzEtYmU4MS0xMTE2NzczMjkzMTUvMjhiMjM1NjAtMTQwZi00ZWQwLWIzMjItNzIyZGRlNGM0MDUxIiwiaWF0IjoxNzUxOTM0NzI5LCJleHAiOjMzMzIyNDk0NzI5fQ.Hbfzs0Hw1qq9klmqOMNiUE_qmAQ9dwdusHH7sW1QbnY " alt="Screenshot 2025-07-07 at 20.31.33.png" width="1447" data-linear-height="565" />

<img src="https://uploads.linear.app/a24a1a82-ddc8-4567-aacc-c3804ea2385e/c1c5b924-01fe-442b-b4bd-d0d4ba9e80b3/8f82b9ad-aa2c-4439-8115-bf4cdcc0c4f6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2EyNGExYTgyLWRkYzgtNDU2Ny1hYWNjLWMzODA0ZWEyMzg1ZS9jMWM1YjkyNC0wMWZlLTQ0MmItYjRiZC1kMGQ0YmE5ZTgwYjMvOGY4MmI5YWQtYWEyYy00NDM5LTgxMTUtYmY0Y2RjYzBjNGY2IiwiaWF0IjoxNzUxOTM0NzI5LCJleHAiOjMzMzIyNDk0NzI5fQ.CwXpf0vxM4FGQ-rROHgKlvzPcwK5Ck5H9Jh9IWBZ2Gk " alt="Screenshot 2025-07-07 at 20.31.39.png" width="1295" data-linear-height="628" />
