### ISSUE TITLE
Issue with Google Workspace SMTP

### ISSUE THREAD

**Issue by rahtechonline** [metabase/metabase#33836]
### Describe the bug

As per the documentation on Google Apps email configuration, was done in the .env file. But the emails are not working

[Google Apps](https://www.metabase.com/docs/v0.47/configuring-metabase/email#google-apps)
In the SMTP host field, enter smtp.gmail.com
Fill in 465 for the SMTP port field
For the SMTP Security field, enter SSL
In the SMTP username field, enter your Google Apps email address (e.g. hello@yourdomain.com)
Enter your Google Apps password in the SMTP password field
Enter the email address you would like to be used as the sender of system notifications in the *From Address field.

### To Reproduce

1. Go to Admin Setting => Email
2. Click on Send Test EMail
3. Error => Looks like we ran into some problems

### Logs

[68c6e8e9-d138-4263-b137-779c94c4af23] 2023-09-08T19:23:28+05:30 WARN metabase.email Failed to send email
com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
  nested exception is:
	java.net.ConnectException: Operation timed out (Connection timed out)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2210)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
	at javax.mail.Service.connect(Service.java:342)
	at postal.smtp$smtp_send_STAR_.invokeStatic(smtp.clj:33)
	at postal.smtp$smtp_send_STAR_.invoke(smtp.clj:29)
	at postal.smtp$smtp_send.invokeStatic(smtp.clj:58)
	at postal.smtp$smtp_send.doInvoke(smtp.clj:39)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at postal.core$send_message.invokeStatic(core.clj:36)
	at postal.core$send_message.invoke(core.clj:29)
	at metabase.email$fn__84214$send_message_or_throw_BANG___84219$fn__84223.invoke(email.clj:131)
	at metabase.email$fn__84214$send_message_or_throw_BANG___84219.invoke(email.clj:121)
	at metabase.email$send_message_BANG_.invokeStatic(email.clj:171)
	at metabase.email$send_message_BANG_.doInvoke(email.clj:157)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at metabase.api.email$fn__93295.invokeStatic(email.clj:139)
	at metabase.api.email$fn__93295.invoke(email.clj:134)
	at compojure.core$wrap_response$fn__44405.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__44389.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__44394.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__44398.invoke(core.clj:151)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__100220.invoke(auth.clj:17)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417.invoke(core.clj:200)
	at compojure.core$make_context$handler__44445.invoke(core.clj:290)
	at compojure.core$make_context$fn__44449.invoke(core.clj:300)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$make_context$fn__44449.invoke(core.clj:301)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$make_context$fn__44449.invoke(core.clj:301)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$make_context$fn__44449.invoke(core.clj:301)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$make_context$fn__44449.invoke(core.clj:301)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$make_context$fn__44449.invoke(core.clj:301)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$make_context$fn__44449.invoke(core.clj:301)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$make_context$fn__44449.invoke(core.clj:301)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$make_context$fn__44449.invoke(core.clj:301)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$make_context$fn__44449.invoke(core.clj:301)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$make_context$fn__44449.invoke(core.clj:301)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at metabase.api.routes$fn__112065$fn__112068.invoke(routes.clj:66)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__112230$fn__112231.doInvoke(routes.clj:70)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417.invoke(core.clj:200)
	at compojure.core$make_context$handler__44445.invoke(core.clj:290)
	at compojure.core$make_context$fn__44449.invoke(core.clj:300)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44398.invoke(core.clj:153)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44398.invoke(core.clj:153)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44398.invoke(core.clj:153)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417$f__44418$respond_SINGLEQUOTE___44419.invoke(core.clj:197)
	at metabase.server.routes$fn__112215$fn__112217.invoke(routes.clj:47)
	at compojure.core$routes$fn__44417$f__44418.invoke(core.clj:198)
	at compojure.core$routes$fn__44417.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__108657.invoke(exceptions.clj:107)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__108654.invoke(exceptions.clj:95)
	at metabase.server.middleware.log$log_api_call$fn__112502$fn__112503$fn__112504.invoke(log.clj:216)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12)
	at metabase.server.middleware.log$log_api_call$fn__112502$fn__112503.invoke(log.clj:208)
	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112)
	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103)
	at metabase.server.middleware.log$log_api_call$fn__112502.invoke(log.clj:207)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__114628.invoke(browser_cookie.clj:42)
	at metabase.server.middleware.security$add_security_headers$fn__90739.invoke(security.clj:153)
	at metabase.server.middleware.json$wrap_json_body$fn__113184.invoke(json.clj:67)
	at metabase.server.middleware.offset_paging$handle_paging$fn__90763.invoke(offset_paging.clj:45)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__113202.invoke(json.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__114895.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__114914.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__57173.invoke(misc.clj:61)
	at metabase.server.middleware.session$reset_session_timeout$fn__71710.invoke(session.clj:441)
	at metabase.server.middleware.session$bind_current_user$fn__71677$fn__71678.invoke(session.clj:336)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:315)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:304)
	at metabase.server.middleware.session$bind_current_user$fn__71677.invoke(session.clj:335)
	at metabase.server.middleware.session$wrap_current_user_info$fn__71658.invoke(session.clj:285)
	at metabase.server.middleware.session$wrap_session_id$fn__71641.invoke(session.clj:217)
	at metabase.server.middleware.auth$wrap_api_key$fn__100228.invoke(auth.clj:30)
	at ring.middleware.cookies$wrap_cookies$fn__114815.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__57155.invoke(misc.clj:29)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__57181.invoke(misc.clj:78)
	at ring.middleware.gzip$wrap_gzip$fn__114857.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__57184.invoke(misc.clj:95)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__114644.invoke(ssl.clj:51)
	at metabase.server$async_proxy_handler$fn__79425.invoke(server.clj:77)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:335)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)
	... 137 more
[68c6e8e9-d138-4263-b137-779c94c4af23] 2023-09-08T19:23:28+05:30 WARN metabase.api.email Problem connecting to mail server: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1: Operation timed out (Connection timed out)
[68c6e8e9-d138-4263-b137-779c94c4af23] 2023-09-08T19:23:28+05:30 DEBUG metabase.server.middleware.log POST /api/email/test 400 2.2 mins (1 DB calls) 
{:errors {:email-smtp-host "Wrong host or port", :email-smtp-port "Wrong host or port"}}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.15.0-83-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.4 (Debian 15.4-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-09-07",
      "tag": "v0.47.1",
      "branch": "release-x.47.x",
      "hash": "bd278b9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

High

**Comment by paoliniluis** [comment]
where are you running Metabase? do you have the firewall rules to connect to the smtp server?

**Comment by rahtechonline** [comment]
I am running in the docker composer.....and the .env file is connected with the docker-compser.yml

I am bit worried now, in .env file when I change the port number to 587 and restart the docker, it still shows port 465, don't know, from where the port 465 is being picked up on its own.

**Comment by rahtechonline** [comment]
docker-composer.yml

version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/db_user
      MB_DB_PASS_FILE: /run/secrets/db_password
      MB_DB_HOST: postgres
    env_file:
      - metabase.env
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - metanet1
    depends_on:
      - postgres
    secrets:
      - db_password
      - db_user
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - metanet1
    secrets:
      - db_password
      - db_user
networks:
  metanet1:
    driver: bridge
secrets:
   db_password:
     file: db_password.txt
   db_user:
     file: db_user.txt

**Comment by paoliniluis** [comment]
It’s being picked up from the db mostly sure
