### ISSUE TITLE
Could not connect to my MongoDB with different authenticationDatabase

### ISSUE THREAD

**Issue by jrca025** [metabase/metabase#33879]
### Describe the bug

Hi I have a user on a particular DB for predefined roles per DB.

Database = db1
User = analytics

Basically my DB connectionstring for this is

mongodb://analytics@10.1.0.24:27017/?authenticationDatabase=db1

However when I try to save the connection on Metabase it is failed.

![image](https://github.com/metabase/metabase/assets/89201548/64c7a395-b92f-44bb-9265-df680da47453)

### Logs

[0f45923c-0a66-41a9-9069-4802cc6c941f] 2023-09-13T14:17:52+08:00 ERROR metabase.driver.util Failed to connect to Database
java.util.concurrent.TimeoutException: Timed out after 10.0 s
	at metabase.util.jvm$deref_with_timeout.invokeStatic(jvm.clj:287)
	at metabase.util.jvm$deref_with_timeout.invoke(jvm.clj:279)
	at metabase.util.jvm$do_with_timeout.invokeStatic(jvm.clj:294)
	at metabase.util.jvm$do_with_timeout.invoke(jvm.clj:290)
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:143)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:132)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.api.database$test_database_connection.invokeStatic(database.clj:676)
	at metabase.api.database$test_database_connection.doInvoke(database.clj:666)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at metabase.api.database$fn__108443$test_connection_details__108448$fn__108449.invoke(database.clj:723)
	at metabase.api.database$fn__108443$test_connection_details__108448.invoke(database.clj:710)
	at metabase.api.database$fn__108476.invokeStatic(database.clj:752)
	at metabase.api.database$fn__108476.invoke(database.clj:734)
	at compojure.core$wrap_response$fn__44464.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__44448.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__44453.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__44457.invoke(core.clj:151)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44457.invoke(core.clj:152)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__100276.invoke(auth.clj:17)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476.invoke(core.clj:200)
	at compojure.core$make_context$handler__44504.invoke(core.clj:290)
	at compojure.core$make_context$fn__44508.invoke(core.clj:300)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$make_context$fn__44508.invoke(core.clj:301)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$make_context$fn__44508.invoke(core.clj:301)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$make_context$fn__44508.invoke(core.clj:301)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$make_context$fn__44508.invoke(core.clj:301)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$make_context$fn__44508.invoke(core.clj:301)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$make_context$fn__44508.invoke(core.clj:301)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$make_context$fn__44508.invoke(core.clj:301)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$make_context$fn__44508.invoke(core.clj:301)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at metabase.api.routes$fn__112139$fn__112142.invoke(routes.clj:66)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__112304$fn__112305.doInvoke(routes.clj:70)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476.invoke(core.clj:200)
	at compojure.core$make_context$handler__44504.invoke(core.clj:290)
	at compojure.core$make_context$fn__44508.invoke(core.clj:300)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44457.invoke(core.clj:153)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44457.invoke(core.clj:153)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44457.invoke(core.clj:153)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476$f__44477$respond_SINGLEQUOTE___44478.invoke(core.clj:197)
	at metabase.server.routes$fn__112289$fn__112291.invoke(routes.clj:47)
	at compojure.core$routes$fn__44476$f__44477.invoke(core.clj:198)
	at compojure.core$routes$fn__44476.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__108705.invoke(exceptions.clj:107)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__108702.invoke(exceptions.clj:95)
	at metabase.server.middleware.log$log_api_call$fn__112576$fn__112577$fn__112578.invoke(log.clj:216)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12)
	at metabase.server.middleware.log$log_api_call$fn__112576$fn__112577.invoke(log.clj:208)
	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112)
	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103)
	at metabase.server.middleware.log$log_api_call$fn__112576.invoke(log.clj:207)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__114691.invoke(browser_cookie.clj:42)
	at metabase.server.middleware.security$add_security_headers$fn__90795.invoke(security.clj:153)
	at metabase.server.middleware.json$wrap_json_body$fn__113258.invoke(json.clj:67)
	at metabase.server.middleware.offset_paging$handle_paging$fn__90819.invoke(offset_paging.clj:45)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__113276.invoke(json.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__114958.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__114977.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__57226.invoke(misc.clj:61)
	at metabase.server.middleware.session$reset_session_timeout$fn__71789.invoke(session.clj:441)
	at metabase.server.middleware.session$bind_current_user$fn__71756$fn__71757.invoke(session.clj:336)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:315)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:304)
	at metabase.server.middleware.session$bind_current_user$fn__71756.invoke(session.clj:335)
	at metabase.server.middleware.session$wrap_current_user_info$fn__71737.invoke(session.clj:285)
	at metabase.server.middleware.session$wrap_session_id$fn__71720.invoke(session.clj:217)
	at metabase.server.middleware.auth$wrap_api_key$fn__100284.invoke(auth.clj:30)
	at ring.middleware.cookies$wrap_cookies$fn__114878.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__57208.invoke(misc.clj:29)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__57234.invoke(misc.clj:78)
	at ring.middleware.gzip$wrap_gzip$fn__114920.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__57237.invoke(misc.clj:95)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__114707.invoke(ssl.clj:51)
	at metabase.server$async_proxy_handler$fn__79504.invoke(server.clj:77)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
	at java.base/java.lang.Thread.run(Thread.java:829)
[0f45923c-0a66-41a9-9069-4802cc6c941f] 2023-09-13T14:17:52+08:00 DEBUG metabase.server.middleware.log POST /api/database 400 10.1 s (0 DB calls) 
{:message "Connection to '10.1.0.24:27,017' successful, but could not connect to DB."}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1-post-Ubuntu-0ubuntu122.04",
    "java.vendor": "Ubuntu",
    "java.vendor.url": "https://ubuntu.com/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1-post-Ubuntu-0ubuntu122.04",
    "os.name": "Linux",
    "os.version": "6.2.0-1011-azure",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "mongo"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-08-16",
      "tag": "v0.47.0",
      "branch": "release-x.47.x",
      "hash": "682ec2d"
    },
    "settings": {
      "report-timezone": "UTC"
    }
  }
}
```

### Severity

this is a slight blocker as we have to double check the permission for each metabase user that can be mitigated by the mongodb itself using the predefined roles per DB

**Comment by paoliniluis** [comment]
Is the mongodb server accesible by Metabase?

**Comment by jrca025** [comment]
Yes. Whenever I use a different account that has authenticationDatabase=admin, it is connecting.

**Comment by paoliniluis** [comment]
can you try directly with the connection string instead of the form?

**Comment by jrca025** [comment]
still not connecting.
error logs show
"Unable to connect to database."

**Comment by luizarakaki** [comment]
Can you confirm you can connect successfully from other clients?

**Comment by jrca025** [comment]
> Can you confirm you can connect successfully from other clients?

Yes. Even if I manually connect to that database on the terminal where my Metabase is residing via mongodb://analytics@10.1.0.24:27017/?authenticationDatabase=db1 it is successfully connecting. The problem lies when I try it on the Admin part on Metabase GUI

**Comment by paoliniluis** [comment]
Hi, now that we changed the wrapper around the driver, can you check this again? you need to use v48.5+ for checking this @jrca025

**Comment by ArnauKokoro** [comment]
Hi, I'm having same problem on version 0.49.7.

`Command failed with error 13 (Unauthorized): 'not authorized on admin to execute command { listDatabases: 1, nameOnly: true, $db: "admin"...`

Seems weird because the error says that I'm trying to authenticate by admin database but it is not true, I have other database as authSource. In this case db and authSource are the same db, but not admin db.

Thanks!

**Comment by dannisetiawan** [comment]
hi, i'm having same issue on version 0.50.18

`"Command failed with error 13 (Unauthorized): 'not authorized on admin to execute command { listDatabases: 1, nameOnly: true, $db: \"admin\", . . .`

is there any workaround to resolve it?

thanks!

**Comment by snoe** [comment]
There may have been a problem pre-50 with the old mongo connector library we were using. That seems to have resulted in the `TimeoutException` that @jrca025 ran into.

For @ArnauKokoro , the attempt to connect to `admin` for the authenticationDatabase, it is unclear what's happening.

If you are connecting with a connection-uri. You need to use the `authSource` option, otherwise it defaults to `admin`:

```
mongodb://<credentials>@127.0.0.1:27017/uuid-dogs?authSource=test-data
```

If you are using the admin gui to put in the individual parts (as in the image at the top), in my testing `Authentication Database (optional)` always works to override the `authSource` default of `admin`. @ArnauKokoro Are you still running into this, could you share any more details if so?

**Comment by luizarakaki** [comment]
As we can't repro for now, we are closing this. Will open if more info appears
