### ISSUE TITLE
Summarizing or sorting in query editor after Exploring results in a SQL question and creating a Custom Column breaks query editor 

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#34247]
### Describe the bug

After creating a SQL query, clicking explore results, creating a custom column, and then clicking Summarize or Order By, the GUI editor will break with "Something's gone wrong. We've run into an error. You can try refreshing the page, or just go back."

Hopefully, this will help us understand the root of this error that has been more frequent in the last couple of versions.

### To Reproduce

1. Create a SQL question based on Sample Database: select * from orders
2. Save it and click "Explore Results" top right
3. Go to GUI editor and create a custom column: [TAX] --a test column
4. Click Sort or Summarize, it should bring the error "Something's gone wrong"

### Logs

I don't know if this helps, but here are console logs:
```
react-dom.production.min.js:209 RangeError: Maximum call stack size exceeded
    at e (cljs.core.js:500:178)
    at cljs.core.js:501:57
    at e (cljs.core.js:501:3)
    at cljs.core.js:501:57
    at e (cljs.core.js:501:3)
    at cljs.core.js:501:57
    at e (cljs.core.js:501:3)
    at yr.h.ya (cljs.core.js:505:37)
    at F (cljs.core.js:22:45)
    at yr.Em.h (cljs.core.js:248:369)
cs @ react-dom.production.min.js:209
n.payload @ react-dom.production.min.js:227
mo @ react-dom.production.min.js:129
Ua @ react-dom.production.min.js:179
xs @ react-dom.production.min.js:263
Sc @ react-dom.production.min.js:246
_c @ react-dom.production.min.js:246
gc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Zi @ react-dom.production.min.js:122
T @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
app.ts:22 Error: {componentStack: '\n    in xn\n    in div\n    in u\n    in span\n    in …\n    in h\n    in DragDropContextProvider\n    in I'}
h @ app.ts:22
n.<computed> @ bindActionCreators.js:8
value @ ErrorBoundary.tsx:31
o.componentDidCatch.n.callback @ react-dom.production.min.js:227
Mo @ react-dom.production.min.js:131
hs @ react-dom.production.min.js:212
Ec @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Rc @ react-dom.production.min.js:248
gc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Zi @ react-dom.production.min.js:122
T @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
StructuredQuery.ts:368 Warning: can't clean query without metadata!
value @ StructuredQuery.ts:368
value @ Question.ts:1143
f @ urls.ts:42
P @ questions.ts:106
(anonymous) @ NewItemMenu.tsx:79
useMemo @ react-dom.production.min.js:165
t.useMemo @ react.production.min.js:25
Bi @ NewItemMenu.tsx:72
ta @ react-dom.production.min.js:153
xs @ react-dom.production.min.js:261
Sc @ react-dom.production.min.js:246
_c @ react-dom.production.min.js:246
gc @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vi @ react-dom.production.min.js:122
Ji @ react-dom.production.min.js:123
Zi @ react-dom.production.min.js:122
T @ react-dom.production.min.js:287
Kt @ react-dom.production.min.js:68
[Violation] 'click' handler took 223ms
```
### Information about your Metabase installation

JSON
47.2

### Severity

very specific steps, but can be annoying

**Comment by ranquild** [comment]
An exception is thrown on the CLJS side 
<img width="1728" alt="Screenshot 2023-10-02 at 18 08 00" src="https://github.com/metabase/metabase/assets/8542534/be7e5ea9-2ce6-4736-9521-b8a01463d355">

**Comment by camsaul** [comment]
I keep saying this but it's crazy that you can crash basically the entire frontend if there's a little glitch in a single component. If sort or summarize doesn't work, the entire FE shouldn't crash. CC @ranquild

**Comment by iethree** [comment]
> I keep saying this but it's crazy that you can crash basically the entire frontend if there's a little glitch in a single component. If sort or summarize doesn't work, the entire FE shouldn't crash. CC @ranquild

We have a great pattern for this : Error boundaries. we just need to use it more widely.
