### ISSUE TITLE
Serialized import error in Docker container based on Ubuntu

### ISSUE THREAD

**Issue by bertrandjamin** [metabase/metabase#34435]
### Describe the bug

We are using Metabase via Docker image (https://hub.docker.com/layers/metabase/metabase-enterprise/v1.47.3/images/sha256-5ab08f76ce964ac05774666b1fb558402cdfd546a87240289ec59f8c0c54e5c4?context=explore) 

After the migration on v1.47.3 we have updated our serialization files to use the new format on local developper computers.

On Mac computers, the import works fine with no issue at all
On Debian or Windows with Debian based WSL image, it's ok too

But on Ubuntu or Windows with Ubuntu WSL we are encountering the given error during the import process : 

```
java.lang.IllegalArgumentException: no conversion to symbol
	at clojure.core$symbol.invokeStatic(core.clj:598)
	at clojure.core$symbol.invoke(core.clj:591)
	at metabase.models.serialization$fn__45582.invokeStatic(serialization.clj:248)
	at metabase.models.serialization$fn__45582.invoke(serialization.clj:246)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase_enterprise.serialization.v2.load$load_one.invokeStatic(load.clj:65)
	at metabase_enterprise.serialization.v2.load$load_one.invoke(load.clj:33)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase_enterprise.serialization.v2.load$load_metabase.invokeStatic(load.clj:95)
	at metabase_enterprise.serialization.v2.load$load_metabase.doInvoke(load.clj:83)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at metabase_enterprise.serialization.cmd$fn__116558$v2_load_internal__116560.doInvoke(cmd.clj:98)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13258.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at metabase_enterprise.serialization.cmd$fn__116568$v2_load__116569.invoke(cmd.clj:106)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13258.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$call_enterprise.invokeStatic(cmd.clj:53)
	at metabase.cmd$call_enterprise.doInvoke(cmd.clj:43)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at metabase.cmd$import.invokeStatic(cmd.clj:191)
	at metabase.cmd$import.doInvoke(cmd.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__118436.invoke(cmd.clj:293)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:292)
	at metabase.cmd$run_cmd.invoke(cmd.clj:282)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:181)
	at metabase.core$run_cmd.invoke(core.clj:179)
	at metabase.core$_main.invokeStatic(core.clj:203)
	at metabase.core$_main.doInvoke(core.clj:198)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
Command failed with exception: no conversion to symbol
```
Ubuntu versions were 2020.4 or 2022.4 

It seems to be a Clojure exception (https://cljs.github.io/api/cljs.core/symbol). 

I have  no idea of why this error occurs only on Ubuntu based host (furthermore in a dockerized environnement) but we have tested it on several computers and only the Ubuntu ones triggers this error...

Unfortunately I cannot give you more information. 
On our side ours impacted developpers have migrated on Debian to resolve their issue...

### To Reproduce

1. Use an Ubuntu linux distribution
2. Use a dockerized Metabase v1.47.3
3. Import serialized files (it seems that  some entities are well imported)
4. The error will be triggered during the import process

### Expected behavior

I expect that the import could work even on Ubuntu

### Logs

`java.lang.IllegalArgumentException: no conversion to symbol
	at clojure.core$symbol.invokeStatic(core.clj:598)
	at clojure.core$symbol.invoke(core.clj:591)
	at metabase.models.serialization$fn__45582.invokeStatic(serialization.clj:248)
	at metabase.models.serialization$fn__45582.invoke(serialization.clj:246)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at metabase_enterprise.serialization.v2.load$load_one.invokeStatic(load.clj:65)
	at metabase_enterprise.serialization.v2.load$load_one.invoke(load.clj:33)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase_enterprise.serialization.v2.load$load_metabase.invokeStatic(load.clj:95)
	at metabase_enterprise.serialization.v2.load$load_metabase.doInvoke(load.clj:83)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at metabase_enterprise.serialization.cmd$fn__116558$v2_load_internal__116560.doInvoke(cmd.clj:98)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13258.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at metabase_enterprise.serialization.cmd$fn__116568$v2_load__116569.invoke(cmd.clj:106)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13258.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$call_enterprise.invokeStatic(cmd.clj:53)
	at metabase.cmd$call_enterprise.doInvoke(cmd.clj:43)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at metabase.cmd$import.invokeStatic(cmd.clj:191)
	at metabase.cmd$import.doInvoke(cmd.clj:187)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__118436.invoke(cmd.clj:293)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:292)
	at metabase.cmd$run_cmd.invoke(cmd.clj:282)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:181)
	at metabase.core$run_cmd.invoke(core.clj:179)
	at metabase.core$_main.invokeStatic(core.clj:203)
	at metabase.core$_main.doInvoke(core.clj:198)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
Command failed with exception: no conversion to symbol`

### Information about your Metabase installation

```JSON
* Metabase v1.47.3
* Docker version 24.0.6, build ed223bc
```

### Severity

blocking

**Comment by piranha** [comment]
@bertrandjamin hey, is this still actual? :-)

**Comment by bertrandjamin** [comment]
@piranha I must admit that after our switch on Debian based environment we did not test this issue anymore.

So I cannot tell you if the bug still occurs with newer versions of Metabase...

**Comment by piranha** [comment]
We've changed the relevant code quite a bit, so I'm going to close the issue, but feel free to reopen if it occurs again and I'll take a look.
