### ISSUE TITLE
Migration locks

### ISSUE THREAD

**Issue by duq3r** [metabase/metabase#34486]
### Describe the bug

Hello!

I have an issue with out metabase. 
All worked fine and suddenly Migration lock appeared. 
Services is working in k8s. 
```
2023-10-09 09:33:03,204 INFO metabase.core :: Starting Metabase version v0.47.3 (4202328 ?) ...
2023-10-09 09:33:03,231 INFO metabase.core :: System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "11.0.20.1+1",
 "java.vendor" "Eclipse Adoptium",
 "java.vendor.url" "https://adoptium.net/",
 "java.version" "11.0.20.1",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "11.0.20.1+1",
 "os.name" "Linux",
 "os.version" "5.4.0-155-generic",
 "user.language" "en",
 "user.timezone" "GMT"}

2023-10-09 09:33:03,233 INFO metabase.plugins :: Loading plugins in /plugins...
2023-10-09 09:33:03,390 INFO util.files :: Extract file /modules/snowflake.metabase-driver.jar -> /plugins/snowflake.metabase-driver.jar
2023-10-09 09:33:03,577 INFO util.files :: Extract file /modules/vertica.metabase-driver.jar -> /plugins/vertica.metabase-driver.jar
2023-10-09 09:33:03,579 INFO util.files :: Extract file /modules/mongo.metabase-driver.jar -> /plugins/mongo.metabase-driver.jar
2023-10-09 09:33:03,595 INFO util.files :: Extract file /modules/sparksql.metabase-driver.jar -> /plugins/sparksql.metabase-driver.jar
2023-10-09 09:33:03,636 INFO util.files :: Extract file /modules/redshift.metabase-driver.jar -> /plugins/redshift.metabase-driver.jar
2023-10-09 09:33:03,642 INFO util.files :: Extract file /modules/oracle.metabase-driver.jar -> /plugins/oracle.metabase-driver.jar
2023-10-09 09:33:03,643 INFO util.files :: Extract file /modules/sqlserver.metabase-driver.jar -> /plugins/sqlserver.metabase-driver.jar
2023-10-09 09:33:03,651 INFO util.files :: Extract file /modules/presto-jdbc.metabase-driver.jar -> /plugins/presto-jdbc.metabase-driver.jar
2023-10-09 09:33:03,699 INFO util.files :: Extract file /modules/athena.metabase-driver.jar -> /plugins/athena.metabase-driver.jar
2023-10-09 09:33:03,776 INFO util.files :: Extract file /modules/druid.metabase-driver.jar -> /plugins/druid.metabase-driver.jar
2023-10-09 09:33:03,779 INFO util.files :: Extract file /modules/sqlite.metabase-driver.jar -> /plugins/sqlite.metabase-driver.jar
2023-10-09 09:33:03,799 INFO util.files :: Extract file /modules/googleanalytics.metabase-driver.jar -> /plugins/googleanalytics.metabase-driver.jar
2023-10-09 09:33:03,810 INFO util.files :: Extract file /modules/bigquery-cloud-sdk.metabase-driver.jar -> /plugins/bigquery-cloud-sdk.metabase-driver.jar
2023-10-09 09:33:04,082 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

2023-10-09 09:33:04,083 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
2023-10-09 09:33:04,084 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver"]
2023-10-09 09:33:04,090 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
2023-10-09 09:33:04,090 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚
2023-10-09 09:33:04,098 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
2023-10-09 09:33:04,098 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc]) 🚚
2023-10-09 09:33:04,098 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
2023-10-09 09:33:04,099 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 🚚
2023-10-09 09:33:04,103 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
2023-10-09 09:33:04,104 INFO driver.impl :: Registered driver :redshift (parents: [:postgres]) 🚚
2023-10-09 09:33:04,114 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery-cloud-sdk...
2023-10-09 09:33:04,114 INFO driver.impl :: Registered driver :bigquery-cloud-sdk (parents: [:sql]) 🚚
2023-10-09 09:33:04,118 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
2023-10-09 09:33:04,118 INFO driver.impl :: Registered driver :googleanalytics  🚚
2023-10-09 09:33:04,130 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto-jdbc...
2023-10-09 09:33:04,130 INFO driver.impl :: Registered driver :presto-jdbc (parents: [:sql-jdbc]) 🚚
2023-10-09 09:33:04,133 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
2023-10-09 09:33:04,133 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 🚚
2023-10-09 09:33:04,141 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :athena...
2023-10-09 09:33:04,141 INFO driver.impl :: Registered driver :athena (parents: [:sql-jdbc]) 🚚
2023-10-09 09:33:04,145 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.

2023-10-09 09:33:04,145 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
2023-10-09 09:33:04,145 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Oracle Driver" "Metabase Vertica Driver"]
2023-10-09 09:33:04,148 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
2023-10-09 09:33:04,148 INFO driver.impl :: Registered driver :druid  🚚
2023-10-09 09:33:04,161 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
2023-10-09 09:33:04,162 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 🚚
2023-10-09 09:33:04,166 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
2023-10-09 09:33:04,167 INFO driver.impl :: Registered driver :mongo  🚚
2023-10-09 09:33:04,167 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2023-10-09 09:33:04,170 INFO db.setup :: Verifying postgres Database Connection ...
2023-10-09 09:33:04,442 INFO db.setup :: Successfully verified PostgreSQL 14.9 (Ubuntu 14.9-201-yandex.52963.cda84d2acd) application database connection. ✅
2023-10-09 09:33:04,443 INFO db.setup :: Running Database Migrations...
2023-10-09 09:33:04,444 INFO db.setup :: Setting up Liquibase...
2023-10-09 09:33:04,653 INFO db.setup :: Liquibase is ready.
2023-10-09 09:33:04,653 INFO db.liquibase :: Checking if Database has unrun migrations...
2023-10-09 09:33:05,719 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2023-10-09 09:33:07,739 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686@2fa1f8e1: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2023-10-09 09:33:09,753 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686@2fa1f8e1: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2023-10-09 09:33:11,769 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686@2fa1f8e1: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2023-10-09 09:33:13,782 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686@2fa1f8e1: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2023-10-09 09:33:15,795 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686@2fa1f8e1: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2023-10-09 09:33:17,808 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.LockException: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
	at metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686.invoke(liquibase.clj:139)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:176)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.db.liquibase$wait_for_migration_lock_to_be_cleared.invokeStatic(liquibase.clj:134)
	at metabase.db.liquibase$wait_for_migration_lock_to_be_cleared.invoke(liquibase.clj:130)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:150)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:144)
	at metabase.db.setup$fn__51981$migrate_BANG___51986$fn__51987$fn__51988.invoke(setup.clj:78)
	at metabase.db.liquibase$fn__51650$do_with_liquibase__51655$fn__51656.invoke(liquibase.clj:66)
	at metabase.db.liquibase$fn__51650$do_with_liquibase__51655.invoke(liquibase.clj:59)
	at metabase.db.setup$fn__51981$migrate_BANG___51986$fn__51987.invoke(setup.clj:73)
	at metabase.db.setup$fn__51981$migrate_BANG___51986.doInvoke(setup.clj:52)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at metabase.db.setup$fn__52045$run_schema_migrations_BANG___52050$fn__52051.invoke(setup.clj:131)
	at metabase.db.setup$fn__52045$run_schema_migrations_BANG___52050.invoke(setup.clj:125)
	at metabase.db.setup$fn__52098$setup_db_BANG___52103$fn__52104$fn__52107$fn__52108.invoke(setup.clj:156)
	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
	at metabase.db.setup$fn__52098$setup_db_BANG___52103$fn__52104$fn__52107.invoke(setup.clj:152)
	at metabase.db.setup$fn__52098$setup_db_BANG___52103$fn__52104.invoke(setup.clj:151)
	at metabase.db.setup$fn__52098$setup_db_BANG___52103.invoke(setup.clj:145)
	at metabase.db$setup_db_BANG_$fn__52131.invoke(db.clj:69)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:64)
	at metabase.db$setup_db_BANG_.invoke(db.clj:55)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:113)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:99)
	at metabase.core$init_BANG_.invokeStatic(core.clj:159)
	at metabase.core$init_BANG_.invoke(core.clj:154)
	at metabase.core$start_normally.invokeStatic(core.clj:171)
	at metabase.core$start_normally.invoke(core.clj:165)
	at metabase.core$_main.invokeStatic(core.clj:204)
	at metabase.core$_main.doInvoke(core.clj:198)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.bootstrap.main(Unknown Source)
2023-10-09 09:33:17,814 INFO metabase.core :: Metabase Shutting Down ...
2023-10-09 09:33:17,814 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2023-10-09 09:33:17,818 INFO metabase.core :: Metabase Shutdown COMPLETE
```
### To Reproduce

No info because it suddenly happened.

### Information about your Metabase installation

```JSON
-PostgreSQL 14.9
-Metabase v47.3
```

### Severity

Critical

**Comment by qnkhuat** [comment]
Hi, there are may reasons migration can have deadlock and we can release the lock with `java -jar metabase.jar migrate release-locks`.

could you try that?

**Comment by duq3r** [comment]
Fixed running command: "java -jar app/metabase.jar migrate release-locks" from inside of container. 
Before running the command I commented the Liveness and ReadinessProbes.

**Comment by duq3r** [comment]
> Hi, there are may reasons migration can have deadlock and we can release the lock with `java -jar metabase.jar migrate release-locks`.
> 
> could you try that?

Thanks! It fixed the issue.

**Comment by duq3r** [comment]
Aftem migrating to prod cluster I started to get the following messages:
2023-10-09 10:53:42,313 INFO middleware.exceptions :: Request canceled before finishing. Metabase

They are INFO messages and metabase is working. But how to get rid of this message?
