### ISSUE TITLE
 auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686@11196211: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`

### ISSUE THREAD

**Issue by Dhina-test** [metabase/metabase#34551]
### Describe the bug

The previous Metabase Docker container was functioning correctly. I recently updated the container to the latest Metabase image using the following command:

docker run -d -p 8080:3000 -v ~/metabase.db:/metabase-data/metabase.db -e "MB_DB_FILE=/metabase-data/metabase.db" -e "JAVA_TOOL_OPTIONS=-Xmx2048m" --name lm-metabase metabase/metabase:latest

However, it appears that the container is experiencing issues as it is stopping unexpectedly, I shared logs

### To Reproduce

The previous Metabase Docker container was functioning correctly. I recently updated the container to the latest Metabase image using the following command:

docker run -d -p 8080:3000 -v ~/metabase.db:/metabase-data/metabase.db -e "MB_DB_FILE=/metabase-data/metabase.db" -e "JAVA_TOOL_OPTIONS=-Xmx2048m" --name lm-metabase metabase/metabase:latest

However, it appears that the container is experiencing issues as it is stopping unexpectedly, I shared logs

### Logs

Picked up JAVA_TOOL_OPTIONS: -Xmx2048m
Warning: environ value jdk-11.0.20.1+1 for key :java-version has been overwritten with 11.0.20.1
2023-10-11 03:41:21,131 INFO metabase.util :: Maximum memory available to JVM: 2.0 GB
2023-10-11 03:41:22,750 WARN db.env :: WARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. For more information, see https://metabase.com/docs/latest/operations-guide/migrating-from-h2.html
2023-10-11 03:41:22,884 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2023-10-11 03:41:28,267 INFO driver.impl :: Registered abstract driver :sql  🚚
2023-10-11 03:41:28,277 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
2023-10-11 03:41:28,281 INFO metabase.util :: Load driver :sql-jdbc took 91.0 ms
2023-10-11 03:41:28,282 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
2023-10-11 03:41:28,321 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
2023-10-11 03:41:28,350 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
2023-10-11 03:41:30,034 INFO metabase.core :: 
Metabase v0.47.3 (4202328 ?) 

Copyright © 2023 Metabase, Inc. 

Metabase Enterprise Edition extensions are NOT PRESENT.
2023-10-11 03:41:30,044 INFO metabase.core :: Starting Metabase in STANDALONE mode
2023-10-11 03:41:30,102 INFO metabase.server :: Launching Embedded Jetty Webserver with config: 
 {:port 3000, :host "0.0.0.0"}

2023-10-11 03:41:30,159 INFO metabase.core :: Starting Metabase version v0.47.3 (4202328 ?) ...
2023-10-11 03:41:30,186 INFO metabase.core :: System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "11.0.20.1+1",
 "java.vendor" "Eclipse Adoptium",
 "java.vendor.url" "https://adoptium.net/",
 "java.version" "11.0.20.1",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "11.0.20.1+1",
 "os.name" "Linux",
 "os.version" "6.2.0-34-generic",
 "user.language" "en",
 "user.timezone" "GMT"}

2023-10-11 03:41:30,188 INFO metabase.plugins :: Loading plugins in /plugins...
2023-10-11 03:41:30,346 INFO util.files :: Extract file /modules/snowflake.metabase-driver.jar -> /plugins/snowflake.metabase-driver.jar
2023-10-11 03:41:30,595 INFO util.files :: Extract file /modules/vertica.metabase-driver.jar -> /plugins/vertica.metabase-driver.jar
2023-10-11 03:41:30,598 INFO util.files :: Extract file /modules/mongo.metabase-driver.jar -> /plugins/mongo.metabase-driver.jar
2023-10-11 03:41:30,624 INFO util.files :: Extract file /modules/sparksql.metabase-driver.jar -> /plugins/sparksql.metabase-driver.jar
2023-10-11 03:41:30,692 INFO util.files :: Extract file /modules/redshift.metabase-driver.jar -> /plugins/redshift.metabase-driver.jar
2023-10-11 03:41:30,701 INFO util.files :: Extract file /modules/oracle.metabase-driver.jar -> /plugins/oracle.metabase-driver.jar
2023-10-11 03:41:30,703 INFO util.files :: Extract file /modules/sqlserver.metabase-driver.jar -> /plugins/sqlserver.metabase-driver.jar
2023-10-11 03:41:30,716 INFO util.files :: Extract file /modules/presto-jdbc.metabase-driver.jar -> /plugins/presto-jdbc.metabase-driver.jar
2023-10-11 03:41:30,822 INFO util.files :: Extract file /modules/athena.metabase-driver.jar -> /plugins/athena.metabase-driver.jar
2023-10-11 03:41:30,947 INFO util.files :: Extract file /modules/druid.metabase-driver.jar -> /plugins/druid.metabase-driver.jar
2023-10-11 03:41:30,952 INFO util.files :: Extract file /modules/sqlite.metabase-driver.jar -> /plugins/sqlite.metabase-driver.jar
2023-10-11 03:41:30,987 INFO util.files :: Extract file /modules/googleanalytics.metabase-driver.jar -> /plugins/googleanalytics.metabase-driver.jar
2023-10-11 03:41:31,003 INFO util.files :: Extract file /modules/bigquery-cloud-sdk.metabase-driver.jar -> /plugins/bigquery-cloud-sdk.metabase-driver.jar
2023-10-11 03:41:31,416 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto-jdbc...
2023-10-11 03:41:31,416 INFO driver.impl :: Registered driver :presto-jdbc (parents: [:sql-jdbc]) 🚚
2023-10-11 03:41:31,423 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
2023-10-11 03:41:31,424 INFO driver.impl :: Registered driver :druid  🚚
2023-10-11 03:41:31,437 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
2023-10-11 03:41:31,437 INFO driver.impl :: Registered driver :mongo  🚚
2023-10-11 03:41:31,455 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :athena...
2023-10-11 03:41:31,456 INFO driver.impl :: Registered driver :athena (parents: [:sql-jdbc]) 🚚
2023-10-11 03:41:31,483 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery-cloud-sdk...
2023-10-11 03:41:31,484 INFO driver.impl :: Registered driver :bigquery-cloud-sdk (parents: [:sql]) 🚚
2023-10-11 03:41:31,489 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
2023-10-11 03:41:31,490 INFO driver.impl :: Registered driver :googleanalytics  🚚
2023-10-11 03:41:31,493 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
2023-10-11 03:41:31,494 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 🚚
2023-10-11 03:41:31,499 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
2023-10-11 03:41:31,500 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚
2023-10-11 03:41:31,505 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
2023-10-11 03:41:31,505 INFO driver.impl :: Registered driver :redshift (parents: [:postgres]) 🚚
2023-10-11 03:41:31,512 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.

2023-10-11 03:41:31,514 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
2023-10-11 03:41:31,515 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Oracle Driver"]
2023-10-11 03:41:31,518 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

2023-10-11 03:41:31,519 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
2023-10-11 03:41:31,519 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Oracle Driver" "Metabase Vertica Driver"]
2023-10-11 03:41:31,527 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
2023-10-11 03:41:31,528 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc]) 🚚
2023-10-11 03:41:31,528 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
2023-10-11 03:41:31,529 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 🚚
2023-10-11 03:41:31,554 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
2023-10-11 03:41:31,554 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 🚚
2023-10-11 03:41:31,556 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2023-10-11 03:41:31,562 INFO db.setup :: Verifying h2 Database Connection ...
2023-10-11 03:41:32,249 INFO db.setup :: Successfully verified H2 2.1.214 (2022-06-13) application database connection. ✅
2023-10-11 03:41:32,251 INFO db.setup :: Running Database Migrations...
2023-10-11 03:41:32,254 INFO db.setup :: Setting up Liquibase...
2023-10-11 03:41:32,729 INFO db.setup :: Liquibase is ready.
2023-10-11 03:41:32,730 INFO db.liquibase :: Checking if Database has unrun migrations...
2023-10-11 03:41:35,617 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2023-10-11 03:41:37,637 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686@11196211: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2023-10-11 03:41:39,655 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686@11196211: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2023-10-11 03:41:41,676 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686@11196211: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2023-10-11 03:41:43,683 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686@11196211: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2023-10-11 03:41:45,692 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686@11196211: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2023-10-11 03:41:47,701 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.LockException: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
	at metabase.db.liquibase$wait_for_migration_lock_to_be_cleared$fn__51686.invoke(liquibase.clj:139)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:176)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.util.jvm$do_with_auto_retries.invokeStatic(jvm.clj:183)
	at metabase.util.jvm$do_with_auto_retries.invoke(jvm.clj:165)
	at metabase.db.liquibase$wait_for_migration_lock_to_be_cleared.invokeStatic(liquibase.clj:134)
	at metabase.db.liquibase$wait_for_migration_lock_to_be_cleared.invoke(liquibase.clj:130)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:150)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:144)
	at metabase.db.setup$fn__51981$migrate_BANG___51986$fn__51987$fn__51988.invoke(setup.clj:78)
	at metabase.db.liquibase$fn__51650$do_with_liquibase__51655$fn__51656.invoke(liquibase.clj:66)
	at metabase.db.liquibase$fn__51650$do_with_liquibase__51655.invoke(liquibase.clj:59)
	at metabase.db.setup$fn__51981$migrate_BANG___51986$fn__51987.invoke(setup.clj:73)
	at metabase.db.setup$fn__51981$migrate_BANG___51986.doInvoke(setup.clj:52)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at metabase.db.setup$fn__52045$run_schema_migrations_BANG___52050$fn__52051.invoke(setup.clj:131)
	at metabase.db.setup$fn__52045$run_schema_migrations_BANG___52050.invoke(setup.clj:125)
	at metabase.db.setup$fn__52098$setup_db_BANG___52103$fn__52104$fn__52107$fn__52108.invoke(setup.clj:156)
	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
	at metabase.db.setup$fn__52098$setup_db_BANG___52103$fn__52104$fn__52107.invoke(setup.clj:152)
	at metabase.db.setup$fn__52098$setup_db_BANG___52103$fn__52104.invoke(setup.clj:151)
	at metabase.db.setup$fn__52098$setup_db_BANG___52103.invoke(setup.clj:145)
	at metabase.db$setup_db_BANG_$fn__52131.invoke(db.clj:69)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:64)
	at metabase.db$setup_db_BANG_.invoke(db.clj:55)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:113)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:99)
	at metabase.core$init_BANG_.invokeStatic(core.clj:159)
	at metabase.core$init_BANG_.invoke(core.clj:154)
	at metabase.core$start_normally.invokeStatic(core.clj:171)
	at metabase.core$start_normally.invoke(core.clj:165)
	at metabase.core$_main.invokeStatic(core.clj:204)
	at metabase.core$_main.doInvoke(core.clj:198)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.bootstrap.main(Unknown Source)
2023-10-11 03:41:47,724 INFO metabase.core :: Metabase Shutting Down ...
2023-10-11 03:41:47,726 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2023-10-11 03:41:47,739 INFO metabase.core :: Metabase Shutdown COMPLETE

### Information about your Metabase installation

```JSON
The previous Metabase Docker container was functioning correctly. I recently updated the container to the latest Metabase image using the following command:

docker run -d -p 8080:3000 -v ~/metabase.db:/metabase-data/metabase.db -e "MB_DB_FILE=/metabase-data/metabase.db" -e "JAVA_TOOL_OPTIONS=-Xmx2048m" --name lm-metabase metabase/metabase:latest

However, it appears that the container is experiencing issues as it is stopping unexpectedly, I shared logs
```

### Severity

High Priority

**Comment by Tony-metabase** [comment]
Hi,

Next time make sure to include all the context like Metabase Installation and how you are actually deploying this. Something I do notice is that you are using H2 and highly recommend you to migrate away form it because you need a proper DB to host Metabase Application Database

https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2

Secondly make sure you have backups. Then

Go to the H2 database table `databasechangeloglock` and truncate it or unlock the row and start Metabase again.

Make sure you're only starting a single pod during upgrades.

**Comment by qnkhuat** [comment]
You can run  `java -jar metabase.jar migrate` to force release the lock
