### ISSUE TITLE
`load-from-h2` fails when loading from 46.8 into 47.4 trying to load collections

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#34582]
### Describe the bug

We dropped the `color` column on 47. `load-from-h2` is trying to load this column from 46.8

### To Reproduce

1. Start instance on 46.8
2. `dump-to-h2`
3. Start instance on 47.4 and `load-from-h2`

### Expected behavior

Should be possible to run the process across versions

### Logs

2023-10-11 16:47:12,733 ERROR cmd.copy :: BatchUpdateException:
 Message: Batch entry 0 INSERT INTO collection ( "authority_level", "description", "archived", "slug", "name", "personal_owner_id", "type", "id", "entity_id", "location", "namespace", "created_at" ) VALUES ( NULL, NULL, 'FALSE', 'luiz_arakaki_s_personal_collection', 'Luiz Arakaki''s Personal Collection', 1, NULL, 1, 'yp2Km7iO_Xgc3RJ33KnHv', '/', NULL, '2023-10-10 15:56:31.929365-03'::timestamp with time zone ) was aborted: ERROR: null value in column "color" of relation "collection" violates not-null constraint
  Detail: Failing row contains (1, Luiz Arakaki's Personal Collection, null, null, f, /, 1, luiz_arakaki_s_personal_collection, null, null, yp2Km7iO_Xgc3RJ33KnHv, 2023-10-10 15:56:31.929365-03, null).  Call getNextException to see other errors in the batch.
 SQLState: 23502
 Error Code: 0
PSQLException:
 Message: ERROR: null value in column "color" of relation "collection" violates not-null constraint
  Detail: Failing row contains (1, Luiz Arakaki's Personal Collection, null, null, f, /, 1, luiz_arakaki_s_personal_collection, null, null, yp2Km7iO_Xgc3RJ33KnHv, 2023-10-10 15:56:31.929365-03, null).
 SQLState: 23502
 Error Code: 0

2023-10-11 16:47:12,758 INFO cmd.copy :: Re-enabling DB constraints...
2023-10-11 16:47:12,759 INFO cmd.copy :: [OK]
clojure.lang.ExceptionInfo: Error copying instances of Collection {:model "Collection"}
	at metabase.cmd.copy$copy_data_BANG_$fn__117023$fn__117024.invoke(copy.clj:189)
	at metabase.cmd.copy$copy_data_BANG_$fn__117023.invoke(copy.clj:186)
	at clojure.core$partition_all$fn__8625$fn__8626.invoke(core.clj:7325)
	at clojure.core$transduce.invokeStatic(core.clj:6948)
	at clojure.core$transduce.invoke(core.clj:6933)
	at metabase.cmd.copy$copy_data_BANG_.invokeStatic(copy.clj:173)
	at metabase.cmd.copy$copy_data_BANG_.invoke(copy.clj:167)
	at metabase.cmd.copy$fn__117155$copy_BANG___117160$fn__117161$fn__117174$fn__117175$fn__117176.invoke(copy.clj:404)
	at metabase.cmd.copy$do_with_disabled_db_constraints.invokeStatic(copy.clj:266)
	at metabase.cmd.copy$do_with_disabled_db_constraints.invoke(copy.clj:262)
	at metabase.cmd.copy$fn__117155$copy_BANG___117160$fn__117161$fn__117174$fn__117175.invoke(copy.clj:403)
	at metabase.cmd.copy$do_with_connection_rollback_only.invokeStatic(copy.clj:208)
	at metabase.cmd.copy$do_with_connection_rollback_only.invoke(copy.clj:206)
	at metabase.cmd.copy$fn__117155$copy_BANG___117160$fn__117161$fn__117174.invoke(copy.clj:401)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at metabase.cmd.copy$fn__117155$copy_BANG___117160$fn__117161.invoke(copy.clj:398)
	at metabase.cmd.copy$fn__117155$copy_BANG___117160.invoke(copy.clj:372)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:36)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:26)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:73)
	at metabase.cmd$load_from_h2.invoke(cmd.clj:67)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__118488.invoke(cmd.clj:293)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:292)
	at metabase.cmd$run_cmd.invoke(cmd.clj:282)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:181)
	at metabase.core$run_cmd.invoke(core.clj:179)
	at metabase.core$_main.invokeStatic(core.clj:203)
	at metabase.core$_main.doInvoke(core.clj:198)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO collection ( "authority_level", "description", "archived", "slug", "name", "personal_owner_id", "type", "id", "entity_id", "location", "namespace", "created_at" ) VALUES ( NULL, NULL, 'FALSE', 'luiz_arakaki_s_personal_collection', 'Luiz Arakaki''s Personal Collection', 1, NULL, 1, 'yp2Km7iO_Xgc3RJ33KnHv', '/', NULL, '2023-10-10 15:56:31.929365-03'::timestamp with time zone ) was aborted: ERROR: null value in column "color" of relation "collection" violates not-null constraint
  Detail: Failing row contains (1, Luiz Arakaki's Personal Collection, null, null, f, /, 1, luiz_arakaki_s_personal_collection, null, null, yp2Km7iO_Xgc3RJ33KnHv, 2023-10-10 15:56:31.929365-03, null).  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2544)
	at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:591)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1058)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1042)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1080)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1060)
	at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1594)
	at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1585)
	at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1653)
	at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1619)
	at metabase.cmd.copy$insert_chunk_BANG_.invokeStatic(copy.clj:126)
	at metabase.cmd.copy$insert_chunk_BANG_.invoke(copy.clj:120)
	at metabase.cmd.copy$copy_data_BANG_$fn__117023$fn__117024.invoke(copy.clj:187)
	... 46 more
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "color" of relation "collection" violates not-null constraint
  Detail: Failing row contains (1, Luiz Arakaki's Personal Collection, null, null, f, /, 1, luiz_arakaki_s_personal_collection, null, null, yp2Km7iO_Xgc3RJ33KnHv, 2023-10-10 15:56:31.929365-03, null).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	... 64 more
Command failed with exception: Error copying instances of Collection

### Information about your Metabase installation

```JSON
- see above
```

### Severity

P1

**Comment by perivamsi** [comment]
Context https://metaboat.slack.com/archives/C064EB1UE5P/p1718961183466029

**Comment by piranha** [comment]
Serialization code assumes you're loading the dump from the same version: it has no concept of migrations, of data being added or removed. So there is good way of making it run across versions, it was just not designed to do that...
