### ISSUE TITLE
[MLv2] [BE] [Bug] `underlying-records` is not available for pivot table cell

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#35394]
`underlying-records` drill is not available for pivot table cell.

Unit repro test:
https://github.com/metabase/metabase/blob/407dd0cf3e094cdff80ee9ca327969ff267740c6/frontend/src/metabase-lib/tests/drills-underlying-records.unit.spec.ts#L55

E2E repro test:
https://github.com/metabase/metabase/blob/7ec1e0adcdbddeea970ed161680a6f618cd9f611/e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js#L115-L131

MBQLv2 implementation generates runtime issue:
```
TypeError: Cannot read properties of null (reading 'field_ref')
    at column (/Users/denisberezin/code/metabase/target/cljs_dev/metabase/lib/js.cljs:891:56)
    at Object.metabase$lib$js$available_drill_thrus (/Users/denisberezin/code/metabase/target/cljs_dev/metabase.lib.js.js:1347:6)
    at Object.available_drill_thrus (/Users/denisberezin/code/metabase/frontend/src/metabase-lib/drills.ts:23:13)
    at availableDrillThrus (/Users/denisberezin/code/metabase/frontend/src/metabase-lib/test-helpers.ts:173:12)
```

It seems the issue happens because in pivot mode we don't pass column to `available_drill_thrus`, it is undefined. In previous implementation, it resolved needed data to update query from `dimensions` :
https://github.com/metabase/metabase/blob/7ec1e0adcdbddeea970ed161680a6f618cd9f611/frontend/src/metabase-lib/Question.ts#L589-L593

**Comment by bshepherdson** [comment]
This was the same `column: undefined` issue as chart legend clicks, so the fix for #35343 fixed this as well.
