### ISSUE TITLE
Setting a wrong value in MB_HUMANIZATION_STRATEGY will break the sync

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#35469]
### Describe the bug

Trying to go over the MB_HUMANIZATION_STRATEGY env var, I gave it a "disabled" value and it broke all the sync

### To Reproduce

Set up a MB environment with
MB_HUMANIZATION_STRATEGY=disabled
as an env var...

it will break the sync

### Expected behavior

It should switch to the default value but not break everything

### Logs
```
2023-11-07 22:31:28,723 INFO sync-metadata.tables :: Found new tables: (Table  'public.orders' Table  'public.feedback' Table  'public.analytic_events' Table  'public.accounts' Table  'public.people' Table  'public.products' Table  'public.reviews' Table  'public.invoices')
2023-11-07 22:31:28,724 WARN sync.util :: Error creating/reactivating tables for postgres Database 2 'pg'
java.lang.IllegalArgumentException: No method in multimethod 'name->human-readable-name' for dispatch value: :disabled
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at metabase.models.humanization$name__GT_human_readable_name.invokeStatic(humanization.clj:37)
	at metabase.models.humanization$name__GT_human_readable_name.invoke(humanization.clj:23)
	at metabase.models.humanization$name__GT_human_readable_name.invokeStatic(humanization.clj:35)
	at metabase.models.humanization$name__GT_human_readable_name.invoke(humanization.clj:23)
	at metabase.sync.sync_metadata.tables$create_or_reactivate_table_BANG_.invokeStatic(tables.clj:118)
	at metabase.sync.sync_metadata.tables$create_or_reactivate_table_BANG_.invoke(tables.clj:96)
	at metabase.sync.sync_metadata.tables$fn__99107$create_or_reactivate_tables_BANG___99112$fn__99113.invoke(tables.clj:132)
	at metabase.sync.sync_metadata.tables$fn__99107$create_or_reactivate_tables_BANG___99112.invoke(tables.clj:125)
	at metabase.sync.sync_metadata.tables$fn__99361$sync_tables_and_database_BANG___99370$fn__99373$fn__99386.invoke(tables.clj:204)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:162)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:155)
	at metabase.sync.sync_metadata.tables$fn__99361$sync_tables_and_database_BANG___99370$fn__99373.invoke(tables.clj:202)
	at metabase.sync.sync_metadata.tables$fn__99361$sync_tables_and_database_BANG___99370.invoke(tables.clj:180)
	at metabase.sync.sync_metadata$make_sync_steps$fn__100372.invoke(sync_metadata.clj:47)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$fn__62954$run_step_with_metadata__62959$fn__62963$fn__62965.doInvoke(util.clj:380)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)
	at metabase.sync.util$fn__62954$run_step_with_metadata__62959$fn__62963.invoke(util.clj:375)
	at metabase.sync.util$fn__62954$run_step_with_metadata__62959.invoke(util.clj:370)
	at metabase.sync.util$fn__63181$run_sync_operation__63186$fn__63187$fn__63195.invoke(util.clj:486)
	at metabase.sync.util$fn__63181$run_sync_operation__63186$fn__63187.invoke(util.clj:484)
	at metabase.sync.util$fn__63181$run_sync_operation__63186.invoke(util.clj:478)
	at metabase.sync.sync_metadata$fn__100383$sync_db_metadata_BANG___100388$fn__100389$fn__100390.invoke(sync_metadata.clj:60)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:162)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:155)
	at clojure.core$partial$fn__5910.invoke(core.clj:2647)
	at metabase.driver$fn__48142.invokeStatic(driver.clj:693)
	at metabase.driver$fn__48142.invoke(driver.clj:693)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__62874.invoke(util.clj:140)
	at metabase.sync.util$with_db_logging_disabled$fn__62871.invoke(util.clj:131)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_logging$fn__62858.invoke(util.clj:116)
	at metabase.sync.util$with_sync_events$fn__62853.invoke(util.clj:90)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__62843.invoke(util.clj:69)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:183)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:180)
	at metabase.sync.sync_metadata$fn__100383$sync_db_metadata_BANG___100388$fn__100389.invoke(sync_metadata.clj:59)
	at metabase.sync.sync_metadata$fn__100383$sync_db_metadata_BANG___100388.invoke(sync_metadata.clj:55)
	at metabase.api.database$fn__109288$fn__109289.invoke(database.clj:983)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-11-07 22:31:28,725 INFO sync-metadata.tables :: Updating description for tables: (Table  'public.feedback' Table  'public.people' Table  'public.orders' Table  'public.accounts' Table  'public.invoices' Table  'public.reviews' Table  'public.products' Table  'public.analytic_events')
```
### Information about your Metabase installation
It's been like this forever

### Severity

P3

### Additional context

Seems like correct values are here https://github.com/metabase/metabase/issues/14521#issuecomment-767568072

**Comment by darksciencebase** [comment]
The workaround is pretty clear and we're not in the vicinity of this area right now; removing from the tactical board
