### ISSUE TITLE
Pulses and Alerts not sending emails - required class was not found: metabase.task.follow_up_emails.AbandonmentEmail

### ISSUE THREAD

**Issue by Shashwat986** [metabase/metabase#35786]
**Describe the bug**
Suddenly, out of the blue, our pulses and alerts stopped triggering. This was on the 9th of November. The logs seem to have a weird issue that I don't understand.

**Logs**
```
[f26a55f7-e871-4d26-914f-39c3fc8d03e7] 2023-11-15T20:20:48+05:30 INFO org.quartz.impl.jdbcjobstore.JobStoreTX Handling the first 20 triggers that missed their scheduled fire-time.  More misfired triggers remain to be processed.
[f26a55f7-e871-4d26-914f-39c3fc8d03e7] 2023-11-15T20:20:48+05:30 ERROR org.quartz.impl.jdbcjobstore.JobStoreTX MisfireHandler: Error handling misfires: Couldn't store trigger 'DEFAULT.metabase.task.abandonment-emails.trigger' for 'DEFAULT.metabase.task.abandonment-emails.job' job:Couldn't retrieve job because a required class was not found: metabase.task.follow_up_emails.AbandonmentEmail
org.quartz.JobPersistenceException: Couldn't store trigger 'DEFAULT.metabase.task.abandonment-emails.trigger' for 'DEFAULT.metabase.task.abandonment-emails.job' job:Couldn't retrieve job because a required class was not found: metabase.task.follow_up_emails.AbandonmentEmail [See nested exception: org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: metabase.task.follow_up_emails.AbandonmentEmail [See nested exception: java.lang.ClassNotFoundException: metabase.task.follow_up_emails.AbandonmentEmail]]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1228)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1042)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:991)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3264)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: metabase.task.follow_up_emails.AbandonmentEmail [See nested exception: java.lang.ClassNotFoundException: metabase.task.follow_up_emails.AbandonmentEmail]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1210)
	... 5 more
Caused by: java.lang.ClassNotFoundException: metabase.task.follow_up_emails.AbandonmentEmail
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at metabase.task$load_class.invokeStatic(task.clj:118)
	at metabase.task$load_class.invoke(task.clj:117)
	at metabase.task.ClassLoadHelper.loadClass(task.clj:128)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:852)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1390)
	... 6 more
```

**Severity**
We use alerts for core production use-cases. It isn't a complete blocker for us, but it's very significantly affecting our work.

**Additional context**
- We're running Metabase version 0.46.6.4
- We're running 3 AWS EC2 instances of metabase behind a load balancer.
- Due to a bug in our EC2 deployment script, sometimes version 0.45.0 loads up in one instance by accident. This has happened before and it hasn't stopped our alerts. Additionally, this did NOT happen on the 9th of November, but I wanted to mention it out of completeness.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.9+8-LTS",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "17.0.9",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.9+8-LTS",
    "os.name": "Linux",
    "os.version": "5.10.157-139.675.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Kolkata"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "redshift",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.42-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-07-28",
      "tag": "v0.46.6.4",
      "branch": "release-x.46.6.x",
      "hash": "7c60aca"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

**Comment by paoliniluis** [comment]
Hi, please move to Java 11 and also upgrade to v47.7
