### ISSUE TITLE
Dashboard email subscription says "An error occurred while displaying this card"

### ISSUE THREAD

**Issue by benstopics** [metabase/metabase#35881]
**Describe the bug**
Email notification for dashboard subscription says "An error occurred while displaying this card"

**Logs**
[10a050e4-ba91-4c5f-ad3e-bb9a95739926] 2023-11-16T13:59:51-05:00 ERROR metabase.pulse.render Pulse card render error
RangeError: Provided date is not in valid range.
	at <js> tM(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:3224265-3224275)
	at <js> r(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:3224524-3224530)
	at <js> rM(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:3224406-3224537)
	at <js> rU(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:3244587-3244603)
	at <js> :anonymous(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:3271031-3271055)
	at <js> L(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:3270968-3271084)
	at <js> ds(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:2:3270879-3271319)
	at org.graalvm.polyglot.Value.execute(Value.java:880)
	at metabase.pulse.render.js_engine$execute_fn_name.invokeStatic(js_engine.clj:52)
	at metabase.pulse.render.js_engine$execute_fn_name.doInvoke(js_engine.clj:46)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at metabase.pulse.render.js_svg$combo_chart.invokeStatic(js_svg.clj:142)
	at metabase.pulse.render.js_svg$combo_chart.invoke(js_svg.clj:133)
	at metabase.pulse.render.body$lab_image_bundle.invokeStatic(body.clj:832)
	at metabase.pulse.render.body$lab_image_bundle.invoke(body.clj:807)
	at metabase.pulse.render.body$fn__83003$render__82991__83008$fn__83009.invoke(body.clj:843)
	at metabase.pulse.render.body$fn__83003$render__82991__83008.invoke(body.clj:841)
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
	at metabase.pulse.render$fn__83786$render_pulse_card_body__83791$fn__83795.invoke(render.clj:131)
	at metabase.pulse.render$fn__83786$render_pulse_card_body__83791.invoke(render.clj:121)
	at metabase.pulse.render$fn__83827$render_pulse_card__83832$fn__83833.invoke(render.clj:163)
	at metabase.pulse.render$fn__83827$render_pulse_card__83832.invoke(render.clj:145)
	at metabase.pulse.render$fn__83859$render_pulse_section__83864$fn__83868$fn__83871.invoke(render.clj:195)
	at metabase.pulse.render$fn__83859$render_pulse_section__83864$fn__83868.invoke(render.clj:193)
	at metabase.pulse.render$fn__83859$render_pulse_section__83864.invoke(render.clj:190)
	at metabase.email.messages$render_part.invokeStatic(messages.clj:440)
	at metabase.email.messages$render_part.invoke(messages.clj:436)
	at metabase.email.messages$render_message_body$fn__84976$fn__84977.invoke(messages.clj:493)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at metabase.email.messages$render_message_body$fn__84976.invoke(messages.clj:493)
	at metabase.email.messages$render_message_body.invokeStatic(messages.clj:492)
	at metabase.email.messages$render_message_body.invoke(messages.clj:490)
	at metabase.email.messages$render_pulse_email.invokeStatic(messages.clj:519)
	at metabase.email.messages$render_pulse_email.invoke(messages.clj:516)
	at metabase.pulse$fn__111005.invokeStatic(pulse.clj:431)
	at metabase.pulse$fn__111005.invoke(pulse.clj:420)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.pulse$parts__GT_notifications$iter__111079__111083$fn__111084$fn__111085.invoke(pulse.clj:494)
	at metabase.pulse$parts__GT_notifications$iter__111079__111083$fn__111084.invoke(pulse.clj:492)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$seq__5467.invoke(core.clj:139)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:615)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:614)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:642)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:623)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.api.pulse$fn__112257.invokeStatic(pulse.clj:322)
	at metabase.api.pulse$fn__112257.invoke(pulse.clj:308)
	at compojure.core$wrap_response$fn__44401.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__44385.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__44390.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__44394.invoke(core.clj:151)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44394.invoke(core.clj:153)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44394.invoke(core.clj:153)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44394.invoke(core.clj:153)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44394.invoke(core.clj:152)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__101099.invoke(auth.clj:17)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413.invoke(core.clj:200)
	at compojure.core$make_context$handler__44441.invoke(core.clj:290)
	at compojure.core$make_context$fn__44445.invoke(core.clj:300)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:199)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:199)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413.invoke(core.clj:200)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:199)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413.invoke(core.clj:200)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413.invoke(core.clj:200)
	at metabase.api.routes$fn__112857$fn__112858.invoke(routes.clj:64)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__113022$fn__113023.doInvoke(routes.clj:70)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413.invoke(core.clj:200)
	at compojure.core$make_context$handler__44441.invoke(core.clj:290)
	at compojure.core$make_context$fn__44445.invoke(core.clj:300)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44394.invoke(core.clj:153)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44394.invoke(core.clj:153)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__44394.invoke(core.clj:153)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:199)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:199)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:199)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413.invoke(core.clj:200)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413.invoke(core.clj:200)
	at compojure.core$make_context$handler__44441.invoke(core.clj:290)
	at compojure.core$make_context$fn__44445.invoke(core.clj:300)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413$f__44414$respond_SINGLEQUOTE___44415.invoke(core.clj:197)
	at compojure.core$make_context$fn__44445.invoke(core.clj:301)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413.invoke(core.clj:200)
	at compojure.core$routes$fn__44413$f__44414.invoke(core.clj:198)
	at compojure.core$routes$fn__44413.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__109449.invoke(exceptions.clj:107)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__109446.invoke(exceptions.clj:95)
	at metabase.server.middleware.log$log_api_call$fn__115061$fn__115062$fn__115063.invoke(log.clj:216)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12)
	at metabase.server.middleware.log$log_api_call$fn__115061$fn__115062.invoke(log.clj:208)
	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112)
	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103)
	at metabase.server.middleware.log$log_api_call$fn__115061.invoke(log.clj:207)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__120635.invoke(browser_cookie.clj:42)
	at metabase.server.middleware.security$add_security_headers$fn__91609.invoke(security.clj:153)
	at metabase.server.middleware.json$wrap_json_body$fn__117586.invoke(json.clj:67)
	at metabase.server.middleware.offset_paging$handle_paging$fn__91633.invoke(offset_paging.clj:45)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__117604.invoke(json.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__120902.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__120921.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__57247.invoke(misc.clj:61)
	at metabase.server.middleware.session$reset_session_timeout$fn__71746.invoke(session.clj:457)
	at metabase.server.middleware.session$bind_current_user$fn__71713$fn__71714.invoke(session.clj:352)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:331)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:315)
	at metabase.server.middleware.session$bind_current_user$fn__71713.invoke(session.clj:351)
	at metabase.server.middleware.session$wrap_current_user_info$fn__71694.invoke(session.clj:285)
	at metabase.server.middleware.session$wrap_session_id$fn__71677.invoke(session.clj:217)
	at metabase.server.middleware.auth$wrap_api_key$fn__101107.invoke(auth.clj:30)
	at ring.middleware.cookies$wrap_cookies$fn__120822.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__57229.invoke(misc.clj:29)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__57255.invoke(misc.clj:78)
	at ring.middleware.gzip$wrap_gzip$fn__120864.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__57258.invoke(misc.clj:95)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__120651.invoke(ssl.clj:51)
	at metabase.server$async_proxy_handler$fn__79483.invoke(server.clj:77)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
	at java.base/java.lang.Thread.run(Unknown Source)

**To Reproduce**
![image](https://github.com/metabase/metabase/assets/5925932/392f4f8c-cd32-46a4-b3f9-10e6c1a05015)
![image](https://github.com/metabase/metabase/assets/5925932/3d8fd3b8-9d82-4faa-ba16-b26c5c183547)

**Expected behavior**
Showing this dashboard in the email:
![image](https://github.com/metabase/metabase/assets/5925932/b1ec617b-fed8-4d69-8cdd-def9a70373c2)

**Severity**
Just makes the email subscription update useless which helps with accountability of improving KPIs for that process

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.20.1+1",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.20.1",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.20.1+1",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-10-26",
      "tag": "v1.47.6",
      "branch": "?",
      "hash": "3a7ed7a"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}
```

**Comment by paoliniluis** [comment]
"RangeError: Provided date is not in valid range." can you tell us which is the dashboard parameter you're using?

**Comment by benstopics** [comment]
> "RangeError: Provided date is not in valid range." can you tell us which is the dashboard parameter you're using?

Sorry, what do you mean by dashboard parameter? Here is the SQL:

```
SELECT
  DateFromParts(
    year("dbo"."Shipments"."ActualShipDate"),
    month("dbo"."Shipments"."ActualShipDate"),
    1
  ) AS "ActualShipDate",
  "dbo"."Shipments"."Verified" AS "Verified",
  count(*) AS "count"
FROM
  "dbo"."Shipments"
GROUP BY
  year("dbo"."Shipments"."ActualShipDate"),
  month("dbo"."Shipments"."ActualShipDate"),
  "dbo"."Shipments"."Verified"
ORDER BY
  year("dbo"."Shipments"."ActualShipDate") ASC,
  month("dbo"."Shipments"."ActualShipDate") ASC,
  "dbo"."Shipments"."Verified" ASC
  ```

And the visualization settings:

![image](https://github.com/metabase/metabase/assets/5925932/764d8577-fa69-4ed9-b1fe-2c825523e872)

And here's the data:

![image](https://github.com/metabase/metabase/assets/5925932/a689e894-913f-412b-8f02-15c960b0ae98)

Is it because there is a row with a NULL date?

**Comment by benstopics** [comment]
Filtered out empty ship dates and now the email is displaying properly.
