### ISSUE TITLE
Pulses and Alerts not sending emails - required class was not found: metabase.task.follow_up_emails.AbandonmentEmail

### ISSUE THREAD

**Issue by Shashwat986** [metabase/metabase#35950]
### Describe the bug

Suddenly, out of the blue, our pulses and alerts stopped triggering. This was on the 9th of November. The logs seem to have a weird issue that I don't understand.

Same issue that I reported earlier at: https://github.com/metabase/metabase/issues/35786

Since the last report, I have updated the Metabase version to 0.47.8.

### To Reproduce

1. Unsure. This happened randomly.

### Logs

```
[28a2c95b-2b8c-44b5-8964-02e952d17c83] 2023-11-20T18:11:11+05:30 WARN metabase.task Error fetching details for Job: metabase.task.abandonment-emails.job
org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: metabase.task.follow_up_emails.AbandonmentEmail [See nested exception: java.lang.ClassNotFoundException: metabase.task.follow_up_emails.AbandonmentEmail]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1393)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$9.execute(JobStoreSupport.java:1382)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)
	at org.quartz.impl.jdbcjobstore.JobStoreTX.executeInLock(JobStoreTX.java:93)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeWithoutLock(JobStoreSupport.java:3800)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1379)
	at org.quartz.core.QuartzScheduler.getJobDetail(QuartzScheduler.java:1493)
	at org.quartz.impl.StdScheduler.getJobDetail(StdScheduler.java:498)
	at clojurewerkz.quartzite.scheduler$get_job.invokeStatic(scheduler.clj:188)
	at clojurewerkz.quartzite.scheduler$get_job.invoke(scheduler.clj:185)
	at metabase.task$job_info.invokeStatic(task.clj:290)
	at metabase.task$job_info.invoke(task.clj:282)
	at clojure.core$map$fn__5935.invoke(core.clj:2772)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:713)
	at clojure.core$next__5451.invokeStatic(core.clj:64)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:169)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at cheshire.generate$generate.invokeStatic(generate.clj:133)
	at cheshire.generate$generate.invoke(generate.clj:119)
	at cheshire.generate$generate$fn__4433.invoke(generate.clj:125)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at cheshire.generate$generate.invokeStatic(generate.clj:125)
	at cheshire.generate$generate.invoke(generate.clj:119)
	at cheshire.core$generate_stream.invokeStatic(core.clj:106)
	at cheshire.core$generate_stream.invoke(core.clj:81)
	at metabase.server.middleware.json$streamed_json_response$fn__113335.invoke(json.clj:83)
	at ring.util.io$piped_input_stream$fn__683.invoke(io.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: metabase.task.follow_up_emails.AbandonmentEmail
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at metabase.task$load_class.invokeStatic(task.clj:118)
	at metabase.task$load_class.invoke(task.clj:117)
	at metabase.task.ClassLoadHelper.loadClass(task.clj:128)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:852)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1390)
	... 52 more
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "17.0.9+8-LTS",
    "java.vendor": "Amazon.com Inc.",
    "java.vendor.url": "https://aws.amazon.com/corretto/",
    "java.version": "17.0.9",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "17.0.9+8-LTS",
    "os.name": "Linux",
    "os.version": "5.10.157-139.675.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Asia/Kolkata"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "mysql",
      "redshift",
      "bigquery-cloud-sdk"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "5.7.42-log"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.6"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-17",
      "tag": "v0.47.8",
      "branch": "?",
      "hash": "639fa5e"
    },
    "settings": {
      "report-timezone": "Asia/Calcutta"
    }
  }
}
```

### Severity

We use alerts for core production use-cases. It isn't a complete blocker for us, but it's very significantly affecting our work.

### Additional context

Scheduler Info

```
Quartz Scheduler (v2.3.2) 'MetabaseScheduler' with instanceId 'prod-metabase-6-2121700409942523'
  Scheduler class: 'org.quartz.impl.StdScheduler' - running locally.
  Running since: Sun Nov 19 21:35:43 IST 2023
  Not currently in standby mode.
  Number of jobs executed: 123
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.impl.jdbcjobstore.JobStoreTX' - which supports persistence. and is clustered.
```

**Comment by Shashwat986** [comment]
Is there any way I can clear the job-store? Maybe that could help because I'm assuming the AbandonmentEmail is related to older pulses or jobs

**Comment by paoliniluis** [comment]
Hi, I requested you to downgrade to Java 11 and see if the problem comes back again. Have you been able to do that? as you can imagine, it's very difficult reproduce an issue if you're not running the recommended version of Java that we test against

**Comment by paoliniluis** [comment]
closing
