### ISSUE TITLE
Deleted card cause import error when referenced in dashboards on load

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#36030]
### Describe the bug

We are referencing a deleted card in an archived dashboard, and that should not be happening

### To Reproduce

1. Create card 
2. Create a dashboard and add the created card
3. Archive the dashboard and the card
4. Delete the card from the archive
5. Export and import in different instances
6. See error

### Expected behavior

Should import successfully 
### Logs
[EDIT]

(...) error logs 
2023-11-20 20:43:16,837 INFO v2.load :: Loading Card OF_NHawHCVce1n7mdbfIi
clojure.lang.ExceptionInfo: Failed to read file for [{:model "Card", :id "OF_NHawHCVce1n7mdbfIi"}] {:path [{:model "Card", :id "OF_NHawHCVce1n7mdbfIi"}], :deps-chain #{[#ordered/map ([:model "Dashboard"] [:id "0fABTBrm9F5jtKY-i77kQ"])]}, :error :metabase-enterprise.serialization.v2.load/not-found}
        at metabase_enterprise.serialization.v2.load$load_one$fn__116627.invoke(load.clj:52)
        at metabase_enterprise.serialization.v2.load$load_one.invokeStatic(load.clj:49)
        at metabase_enterprise.serialization.v2.load$load_one.invoke(load.clj:33)
        at metabase_enterprise.serialization.v2.load$load_deps$loader__116621.invoke(load.clj:23)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at metabase_enterprise.serialization.v2.load$load_deps.invokeStatic(load.clj:31)
        at metabase_enterprise.serialization.v2.load$load_deps.invoke(load.clj:14)
        at metabase_enterprise.serialization.v2.load$load_one.invokeStatic(load.clj:60)
        at metabase_enterprise.serialization.v2.load$load_one.invoke(load.clj:33)
        at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
        at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at metabase_enterprise.serialization.v2.load$load_metabase.invokeStatic(load.clj:95)
        at metabase_enterprise.serialization.v2.load$load_metabase.doInvoke(load.clj:83)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at metabase_enterprise.serialization.cmd$fn__116698$v2_load_internal__116700.doInvoke(cmd.clj:98)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at malli.core$_instrument$fn__13258.doInvoke(core.cljc:2526)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at metabase_enterprise.serialization.cmd$fn__116708$v2_load__116709.invoke(cmd.clj:106)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at malli.core$_instrument$fn__13258.doInvoke(core.cljc:2526)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.cmd$call_enterprise.invokeStatic(cmd.clj:53)
        at metabase.cmd$call_enterprise.doInvoke(cmd.clj:43)
        at clojure.lang.RestFn.invoke(RestFn.java:439)
        at metabase.cmd$import.invokeStatic(cmd.clj:191)
        at metabase.cmd$import.doInvoke(cmd.clj:187)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.cmd$run_cmd$fn__118596.invoke(cmd.clj:300)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:299)
        at metabase.cmd$run_cmd.invoke(cmd.clj:289)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.core$run_cmd.invokeStatic(core.clj:181)
        at metabase.core$run_cmd.invoke(core.clj:179)
        at metabase.core$_main.invokeStatic(core.clj:203)
        at metabase.core$_main.doInvoke(core.clj:198)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
        at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.bootstrap.main(Unknown Source)
Caused by: java.lang.NullPointerException
        at metabase.util.yaml$from_file.invokeStatic(yaml.clj:40)
        at metabase.util.yaml$from_file.doInvoke(yaml.clj:37)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at metabase_enterprise.serialization.v2.ingest$ingest_file.invokeStatic(ingest.clj:55)
        at metabase_enterprise.serialization.v2.ingest$ingest_file.invoke(ingest.clj:50)
        at metabase_enterprise.serialization.v2.ingest.YamlIngestion.ingest_one(ingest.clj:88)
        at metabase_enterprise.serialization.v2.load$load_one$fn__116627.invoke(load.clj:50)
        ... 67 more
Command failed with exception: Failed to read file for [{:model "Card", :id "OF_NHawHCVce1n7mdbfIi"}]

### Information about your Metabase installation

```JSON
- 47.x
```

### Severity

P3

### Additional context

P3 because there is a workaround: delete the dashboard

**Comment by piranha** [comment]
Cannot reproduce this... When I archive a Card, it disappears from dashcards and is not referenced in the serialize dashboard. I wrote a test checking this, but maybe I'm missing some detail here?

**Comment by paoliniluis** [comment]
I'm wondering how this could have happened if the dashcard is always removed from the dashboard if there's a deletion of a card... database problems perhaps?
