### ISSUE TITLE
I can't connect to Oracle with Metabase v0.47.8

### ISSUE THREAD

**Issue by HeyChiang** [metabase/metabase#36117]
**Describe the bug**
I can't connect to Oracle with Metabase v0.47.8, I try to use "ojdbc8.jar" or "ojdbc11.jar" in plugins, but it's not working!

**Logs**

```
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:49:42+08:00 DEBUG metabase.server.middleware.log GET /api/database 200 6.6 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (55 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:49:42+08:00 DEBUG metabase.server.middleware.log GET /api/database/2 200 17.5 ms (7 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (55 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:49:43+08:00 DEBUG metabase.server.middleware.log GET /api/database/2/usage_info 200 7.4 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (55 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:49:44+08:00 DEBUG metabase.server.middleware.log GET /api/database 200 6.1 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (55 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:49:46+08:00 DEBUG metabase.server.middleware.log GET /api/database 200 6.5 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (55 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:49:47+08:00 DEBUG metabase.server.middleware.log DELETE /api/database/2 204 78.5 ms (4 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (55 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:49:47+08:00 DEBUG metabase.server.middleware.log GET /api/database 200 5.3 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (56 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:49:47+08:00 DEBUG metabase.server.middleware.log GET /api/database 200 4.9 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (56 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:14+08:00 ERROR metabase.driver.util Failed to connect to Database
java.sql.SQLRecoverableException: ORA-17002: I/O error: Connection closed, connect lapse 42 ms., Authentication lapse 0 ms.
https://docs.oracle.com/error-help/db/ora-17002/
	at oracle.jdbc.driver.T4CConnection.handleLogonIOException(T4CConnection.java:1441)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:994)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1157)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:104)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:825)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:651)
	at metabase.plugins.jdbc_proxy$proxy_driver$reify__90167.connect(jdbc_proxy.clj:37)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at metabase.driver.oracle$fn__122236.invokeStatic(oracle.clj:174)
	at metabase.driver.oracle$fn__122236.invoke(oracle.clj:171)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__48331.invoke(util.clj:144)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Connection closed, connect lapse 42 ms., Authentication lapse 0 ms.
	at oracle.jdbc.driver.T4CConnection.handleLogonIOException(T4CConnection.java:1436)
	... 28 more
Caused by: java.io.IOException: Connection closed, connect lapse 42 ms.
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:262)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:331)
	at oracle.jdbc.driver.T4CConnection.connectNetworkSessionProtocol(T4CConnection.java:3185)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:926)
	... 27 more
Caused by: java.io.IOException: Connection closed
	at oracle.net.nt.SSLSocketChannel.readFromSocket(SSLSocketChannel.java:855)
	at oracle.net.nt.SSLSocketChannel.unwrapHandshakeMessage(SSLSocketChannel.java:685)
	at oracle.net.nt.SSLSocketChannel.doSSLHandshake(SSLSocketChannel.java:507)
	at oracle.net.nt.SSLSocketChannel.write(SSLSocketChannel.java:186)
	at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:372)
	at oracle.net.ns.NIOConnectPacket.writeToSocketChannel(NIOConnectPacket.java:267)
	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:197)
	... 30 more
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:14+08:00 INFO metabase.task.sync-databases Scheduling sync/analyze for database 3: trigger: metabase.task.sync-and-analyze.trigger.3
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:14+08:00 INFO metabase.task.sync-databases Scheduling field-values for database 3: trigger: metabase.task.update-field-values.trigger.3
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:14+08:00 DEBUG metabase.server.middleware.log POST /api/database 200 936.4 ms (19 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (61 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:14+08:00 INFO metabase.sync.util STARTING: Sync oracle Database 3 'djwk'
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:14+08:00 DEBUG metabase.server.middleware.log GET /api/database 200 7.0 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (61 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:14+08:00 DEBUG metabase.server.middleware.log GET /api/database 200 7.8 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (65 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:17+08:00 DEBUG metabase.server.middleware.log GET /api/database 200 7.5 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:17+08:00 DEBUG metabase.server.middleware.log GET /api/database 200 6.2 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:20+08:00 WARN metabase.sync.util Error in sync step Sync oracle Database 3 'djwk'
java.sql.SQLRecoverableException: ORA-17008: Closed connection
https://docs.oracle.com/error-help/db/ora-17008/
	at oracle.jdbc.driver.OracleStatement.ensureOpen(OracleStatement.java:5225)
	at oracle.jdbc.driver.OracleStatement.clearWarnings(OracleStatement.java:4043)
	at oracle.jdbc.driver.OracleStatement.prepareForNewResults(OracleStatement.java:4672)
	at oracle.jdbc.driver.T4CStatement.prepareForNewResults(T4CStatement.java:146)
	at oracle.jdbc.driver.OracleStatement.endOfResultSet(OracleStatement.java:4808)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.close(InsensitiveScrollableResultSet.java:307)
	at oracle.jdbc.driver.ForwardOnlyResultSet.close(ForwardOnlyResultSet.java:55)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.close(NewProxyResultSet.java:852)
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__88394.reduce(common.clj:38)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core.Eduction.reduce(core.clj:7750)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core.Eduction.reduce(core.clj:7750)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$into.invokeStatic(core.clj:6958)
	at clojure.core$into.invoke(core.clj:6950)
	at metabase.driver.sql_jdbc.sync.describe_database$fn__88931$describe_database__88932$fn__88933$default_active_tbl_fn__88934.invoke(describe_database.clj:171)
	at metabase.driver.sql_jdbc.sync.describe_database$fn__88931$describe_database__88932$fn__88933.invoke(describe_database.clj:180)
	at metabase.driver.sql_jdbc.execute$fn__80952$fn__80953.invoke(execute.clj:386)
	at metabase.driver.sql_jdbc.execute$fn__80920$do_with_resolved_connection__80921.invoke(execute.clj:333)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13249.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at metabase.driver.sql_jdbc.execute$fn__80952.invokeStatic(execute.clj:380)
	at metabase.driver.sql_jdbc.execute$fn__80952.invoke(execute.clj:378)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.sql_jdbc.sync.describe_database$fn__88931$describe_database__88932.invoke(describe_database.clj:164)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13249.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.driver.sql_jdbc$fn__116057.invokeStatic(sql_jdbc.clj:84)
	at metabase.driver.sql_jdbc$fn__116057.invoke(sql_jdbc.clj:82)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.sync.fetch_metadata$fn__97287$db_metadata__97292$fn__97293.invoke(fetch_metadata.clj:15)
	at metabase.sync.fetch_metadata$fn__97287$db_metadata__97292.invoke(fetch_metadata.clj:12)
	at metabase.sync.sync_metadata$fn__99706$sync_db_metadata_BANG___99711$fn__99712.invoke(sync_metadata.clj:58)
	at metabase.sync.sync_metadata$fn__99706$sync_db_metadata_BANG___99711.invoke(sync_metadata.clj:55)
	at metabase.sync$fn__99765$sync_database_BANG___99774$fn__99780$fn__99782$fn__99784.invoke(sync.clj:47)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__8244.invokeStatic(protocols.clj:136)
	at clojure.core.protocols$fn__8244.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at metabase.sync$fn__99765$sync_database_BANG___99774$fn__99780$fn__99782.invoke(sync.clj:47)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:162)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:155)
	at clojure.core$partial$fn__5910.invoke(core.clj:2647)
	at metabase.driver$fn__48226.invokeStatic(driver.clj:717)
	at metabase.driver$fn__48226.invoke(driver.clj:717)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__62955.invoke(util.clj:140)
	at metabase.sync.util$with_db_logging_disabled$fn__62952.invoke(util.clj:131)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_logging$fn__62939.invoke(util.clj:116)
	at metabase.sync.util$with_sync_events$fn__62934.invoke(util.clj:90)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__62924.invoke(util.clj:69)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:183)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:180)
	at metabase.sync$fn__99765$sync_database_BANG___99774$fn__99780.invoke(sync.clj:46)
	at metabase.sync$fn__99765$sync_database_BANG___99774.invoke(sync.clj:33)
	at metabase.sync$fn__99765$sync_database_BANG___99774$fn__99775.invoke(sync.clj:42)
	at metabase.sync$fn__99765$sync_database_BANG___99774.invoke(sync.clj:33)
	at metabase.events.sync_database$process_sync_database_event$fn__114505.invoke(sync_database.clj:37)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:20+08:00 INFO metabase.sync.util FINISHED: Sync oracle Database 3 'djwk' (5.7 s)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:20+08:00 DEBUG metabase.server.middleware.log GET /api/database 200 7.1 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued)
[9651c361-489c-40f4-9939-d6475abfa5cf] 2023-11-27T16:50:20+08:00 DEBUG metabase.server.middleware.log GET /api/database 200 6.1 ms (3 DB calls) App DB connections: 0/10 Jetty threads: 6/50 (3 idle, 0 queued) (64 total active threads) Queries in flight: 0 (0 queued)
```

**To Reproduce**
1.create docker containers
```yaml
version: '3.1'
  
services:
  metabase:
    container_name: metabase
    image: metabase/metabase:v0.47.8
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: meta332_pass
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - /home/docker/metabase/plugins:/app/plugins
      - /home/docker/metabase/metabase-data:/metabase-data

  postgres:
    container_name: metabase-postgres
    image: postgres:12.17
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: meta332_pass
      POSTGRES_DB: metabase
    volumes:
      - /home/docker/metabase/postgresql-data:/var/lib/postgresql/data
```
2. put "ojdbc11.jar 、orai18n.jar" into plugins
3. add Oracle database

**Screenshots**
![image](https://github.com/metabase/metabase/assets/12081334/54f200a6-db48-41e1-9e6a-299b1eee0ded)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "zh-CN",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "4.18.0-240.el8.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.17 (Debian 12.17-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-17",
      "tag": "v0.47.8",
      "branch": "?",
      "hash": "639fa5e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by HeyChiang** [comment]
I have tried the ojdbc for both the 19c and 23c versions, but neither works.

**Comment by paoliniluis** [comment]
I tried today and I'm able to connect to Oracle, seems that your oracle is closing the connections. Can you check the settings of the DB?

**Comment by HeyChiang** [comment]
Yes, it can connect to Oracle, but it's unable to display the tables in Oracle, which is very strange.

**Comment by malhomaid** [comment]
We are facing the same issue, queries to database works fine but table/schema sync throws `ORA-17008: Closed connection`

**Comment by paoliniluis** [comment]
@HeyChiang @malhomaid can you give me the Oracle version and the driver you're using?

**Comment by malhomaid** [comment]
@paoliniluis for me Oracle version is `19c` and for the driver we tried different versions of ojdbc11 and ojdbc8, currently we are using `233/ojdbc11.jar`.
BTW the docker image already comes with something called `oracle.metabase-driver.jar` but we also download ojdbc11 using  `curl -Lso /plugins/ojdbc11.jar https://download.oracle.com/otn-pub/otn_software/jdbc/233/ojdbc11.jar` I'm not sure what is the difference between those two

**Comment by HeyChiang** [comment]
> @HeyChiang @malhomaid can you give me the Oracle version and the driver you're using?

I am using data from version 11.2g, along with Oracle drivers from versions 8 and 11

**Comment by pedroalves5770** [comment]
I have the exact same problem, any solution?

**Comment by pedroalves5770** [comment]
Hello @malhomaid which ojdbc driver have worked for you? I also have an oracle cloud with version 12c.

**Comment by paoliniluis** [comment]
@HeyChiang is this still happening?

**Comment by perivamsi** [comment]
Closing this issue since there is no repro, no feedback from the author
