### ISSUE TITLE
"An error occurred while displaying this card" in the email but ok in the dashboard in the browser : "The attribute "y" of the element <rect> is invalid"

### ISSUE THREAD

**Issue by pulse-mind** [metabase/metabase#36164]
### Describe the bug

In the dashboard I have a visualization : 
<img width="1415" alt="Dashboard_·_Dashboard_·_Metabase" src="https://github.com/metabase/metabase/assets/22203083/698cf3da-7973-45e9-96a7-cf962a0360f9">

In the email I receive every day I have : 
<img width="637" alt="Cursor_et_Dashboard_-_fravetier_vikta_com_-_Messagerie_VIKTA" src="https://github.com/metabase/metabase/assets/22203083/826a822a-e412-469e-9ccb-b5fb51e6282e">

I looked on Google and in the issues for this kind of error but I did not find it.

Thank you for your help.

### To Reproduce

1. Open the email

### Expected behavior

The visualization is displayed in the email

### Logs

In the logs I have this error : 
```
[1b0b2415-5b91-49a6-845f-b8f68d536eba] 2023-11-28T09:01:02+01:00 ERROR metabase.pulse.render Pulse card render error
org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
file:///fake.svg:-1
The attribute "y" of the element <rect> is invalid
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:228)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158)
	at metabase.pulse.render.js_svg$render_svg.invokeStatic(js_svg.clj:108)
	at metabase.pulse.render.js_svg$render_svg.invoke(js_svg.clj:97)
	at metabase.pulse.render.js_svg$svg_string__GT_bytes.invokeStatic(js_svg.clj:112)
	at metabase.pulse.render.js_svg$svg_string__GT_bytes.invoke(js_svg.clj:111)
	at metabase.pulse.render.js_svg$combo_chart.invokeStatic(js_svg.clj:141)
	at metabase.pulse.render.js_svg$combo_chart.invoke(js_svg.clj:133)
	at metabase.pulse.render.body$lab_image_bundle.invokeStatic(body.clj:832)
	at metabase.pulse.render.body$lab_image_bundle.invoke(body.clj:807)
	at metabase.pulse.render.body$fn__83184$render__83172__83189$fn__83190.invoke(body.clj:851)
	at metabase.pulse.render.body$fn__83184$render__83172__83189.invoke(body.clj:849)
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
	at metabase.pulse.render$fn__83907$render_pulse_card_body__83912$fn__83916.invoke(render.clj:131)
	at metabase.pulse.render$fn__83907$render_pulse_card_body__83912.invoke(render.clj:121)
	at metabase.pulse.render$fn__83948$render_pulse_card__83953$fn__83954.invoke(render.clj:163)
	at metabase.pulse.render$fn__83948$render_pulse_card__83953.invoke(render.clj:145)
	at metabase.pulse.render$fn__83980$render_pulse_section__83985$fn__83989$fn__83992.invoke(render.clj:195)
	at metabase.pulse.render$fn__83980$render_pulse_section__83985$fn__83989.invoke(render.clj:193)
	at metabase.pulse.render$fn__83980$render_pulse_section__83985.invoke(render.clj:190)
	at metabase.email.messages$render_part.invokeStatic(messages.clj:440)
	at metabase.email.messages$render_part.invoke(messages.clj:436)
	at metabase.email.messages$render_message_body$fn__85102$fn__85103.invoke(messages.clj:493)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at metabase.email.messages$render_message_body$fn__85102.invoke(messages.clj:493)
	at metabase.email.messages$render_message_body.invokeStatic(messages.clj:492)
	at metabase.email.messages$render_message_body.invoke(messages.clj:490)
	at metabase.email.messages$render_pulse_email.invokeStatic(messages.clj:519)
	at metabase.email.messages$render_pulse_email.invoke(messages.clj:516)
	at metabase.pulse$fn__110339.invokeStatic(pulse.clj:431)
	at metabase.pulse$fn__110339.invoke(pulse.clj:420)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.pulse$parts__GT_notifications$iter__110413__110417$fn__110418$fn__110419.invoke(pulse.clj:494)
	at metabase.pulse$parts__GT_notifications$iter__110413__110417$fn__110418.invoke(pulse.clj:492)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$seq__5467.invoke(core.clj:139)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:615)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:614)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:642)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:623)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at metabase.task.send_pulses$fn__113053$send_pulses_BANG___113062$fn__113065$fn__113085$fn__113086.invoke(send_pulses.clj:61)
	at metabase.models.task_history$fn__62890$do_with_task_history__62895$fn__62896.invoke(task_history.clj:95)
	at metabase.models.task_history$fn__62890$do_with_task_history__62895.invoke(task_history.clj:90)
	at metabase.task.send_pulses$fn__113053$send_pulses_BANG___113062$fn__113065$fn__113085.invoke(send_pulses.clj:57)
	at metabase.task.send_pulses$fn__113053$send_pulses_BANG___113062$fn__113065.invoke(send_pulses.clj:56)
	at metabase.task.send_pulses$fn__113053$send_pulses_BANG___113062.invoke(send_pulses.clj:43)
	at metabase.task.send_pulses$fn__113053$send_pulses_BANG___113062$fn__113063.invoke(send_pulses.clj:50)
	at metabase.task.send_pulses$fn__113053$send_pulses_BANG___113062.invoke(send_pulses.clj:43)
	at metabase.task.send_pulses.SendPulses$fn__113164.invoke(send_pulses.clj:114)
	at metabase.models.task_history$fn__62890$do_with_task_history__62895$fn__62896.invoke(task_history.clj:95)
	at metabase.models.task_history$fn__62890$do_with_task_history__62895.invoke(task_history.clj:90)
	at metabase.task.send_pulses.SendPulses.execute(send_pulses.clj:100)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.apache.batik.bridge.BridgeException: file:///fake.svg:-1
The attribute "y" of the element <rect> is invalid
	at org.apache.batik.bridge.SVGRectElementBridge.buildShape(SVGRectElementBridge.java:119)
	at org.apache.batik.bridge.SVGShapeElementBridge.createGraphicsNode(SVGShapeElementBridge.java:60)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:213)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:210)
	... 69 more
```

### Information about your Metabase installation

```JSON
- Email is displayed in gmail
- Chrome latest version

{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "18.0.2-ea+9-Ubuntu-222.04",
    "java.vendor": "Private Build",
    "java.vendor.url": "Unknown",
    "java.version": "18.0.2-ea",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "18.0.2-ea+9-Ubuntu-222.04",
    "os.name": "Linux",
    "os.version": "5.15.0-89-generic",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "13.13 (Ubuntu 13.13-1.pgdg22.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-17",
      "tag": "v0.47.8",
      "branch": "?",
      "hash": "639fa5e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Medium

**Comment by paoliniluis** [comment]
thanks, can you give us all the visualization settings of the chart?

**Comment by pulse-mind** [comment]
yes, how can I export them in order to help you ?

**Comment by paoliniluis** [comment]
give us the result of https://metabaseurl/api/card/<card_id>

also the one of https://metabaseurl/api/dashboard/<dashboard_id>

we will need both as the dashboard card can have visualization settings

**Comment by pulse-mind** [comment]
This is the card json
[metabase-card-76.json](https://github.com/metabase/metabase/files/13490708/metabase-card-76.json)
How can I hide sensitive value of the dashboard ? Or send it to you in a private channel ?

**Comment by paoliniluis** [comment]
@pulse-mind just replace the sensitive value for xxxxxxx

**Comment by pulse-mind** [comment]
I tried something... I hope I did not break something for you
[metabase-dashboard-2,json](https://github.com/metabase/metabase/files/13490949/metabase-dashboard-2.json)

**Comment by alxnddr** [comment]
Previous implementation of this visualization type rendered for emails had many problems and was very buggy. In v50 we've rebuilt line, area, bar, combo, scatter, waterfall charts from scratch so that it now should look exactly as in the app
