### ISSUE TITLE
setting uo metabase dev envrionment met repo.clojars.org:443 conection time out error

### ISSUE THREAD

**Issue by horusli** [metabase/metabase#36192]
### Describe the bug

when setting up the dev envrionment, it report following errors, did these popped up before?

./bin/build.sh
Clearing outdated .cpcache directories if needed...
No .cpcache directories found; nothing to do
Error building classpath. Failed to read artifact descriptor for com.metabase:athena-jdbc:jar:2.0.35
org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for com.metabase:athena-jdbc:jar:2.0.35
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:255)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:263)
        at clojure.tools.deps.extensions.maven$read_descriptor.invokeStatic(maven.clj:115)
        at clojure.tools.deps.extensions.maven$fn__1162.invokeStatic(maven.clj:143)
        at clojure.tools.deps.extensions.maven$fn__1162.invoke(maven.clj:143)
        at clojure.lang.MultiFn.invoke(MultiFn.java:244)
        at clojure.tools.deps$expand_deps$children_task__771$fn__773$fn__774.invoke(deps.clj:406)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.metabase:athena-jdbc:pom:2.0.35 from/to clojars (https://repo.clojars.org/): Connect to repo.clojars.org:443 [repo.clojars.org/151.101.109.128] failed: Connect timed out
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:431)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:235)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:212)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240)
        ... 23 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.metabase:athena-jdbc:pom:2.0.35 from/to clojars (https://repo.clojars.org/): Connect to repo.clojars.org:443 [repo.clojars.org/151.101.109.128] failed: Connect timed out

### To Reproduce

./bin/build.sh

### Logs

na

### Information about your Metabase installation

```JSON
Operation system: Ununtu 20.04
```

### Severity

block some users

### Additional context

na

**Comment by paoliniluis** [comment]
try again, you can also try changing the internet connection
