### ISSUE TITLE
Error syncing fields on a SQLite table with more than 500 columns

### ISSUE THREAD

**Issue by suwyn** [metabase/metabase#36252]
### Describe the bug

Metabase throws the following error syncing a SQLite database table that contains more than 500 columns

```
WARN metabase.sync.util Error syncing Fields for Table 'Table 9 'test''
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (too many terms in compound SELECT)
```

This produces an error message when browsing the data for that table:

```
There was a problem with your question

Most of the time this is caused by an invalid selection or bad input value. Double check your inputs and retry your query.
Hide error details
Here's the full error message
No fields found for table "test".
```

The issue is because SQLite imposes a [limit of 500 terms](https://www.sqlite.org/limits.html) in a compound SELECT statement

### To Reproduce

1. Add a SQLite database that contains a table with more than 500 columns
2. Browse the tables data to see a `There was a problem with your question` error message
3. Browse to the Logs within the Troubleshooting section in the Admin
4. Scroll down to observe the SQLiteException indexing the fields

### Expected behavior

A user should be able to browse the data of the table 

### Logs

```
[dde79b79-c9e8-4c1b-b634-88b17ca68ef6] 2023-11-30T12:23:55-08:00 WARN metabase.sync.util Error syncing Fields for Table 'Table 9 'test''
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (too many terms in compound SELECT)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.throwex(DB.java:1150)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:126)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.jdbc3.JDBC3Statement.lambda$executeQuery$1(JDBC3Statement.java:81)
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:79)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:71)
	at org.sqlite.jdbc3.JDBC3DatabaseMetaData.getColumns(JDBC3DatabaseMetaData.java:1134)
	at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getColumns(NewProxyDatabaseMetaData.java:3068)
	at metabase.driver.sql_jdbc.sync.describe_table$jdbc_fields_metadata$fn__88582.invoke(describe_table.clj:99)
	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__88394.reduce(common.clj:38)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core.Eduction.reduce(core.clj:7750)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$cat$fn__8851.invoke(core.clj:7693)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.driver.sql_jdbc.sync.describe_table$fields_metadata$reify__88596.reduce(describe_table.clj:153)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core$into.invokeStatic(core.clj:6962)
	at clojure.core$into.invoke(core.clj:6950)
	at metabase.driver.sql_jdbc.sync.describe_table$fn__88615.invokeStatic(describe_table.clj:186)
	at metabase.driver.sql_jdbc.sync.describe_table$fn__88615.invoke(describe_table.clj:184)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invokeStatic(describe_table.clj:225)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invoke(describe_table.clj:219)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invokeStatic(describe_table.clj:221)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table_STAR_.invoke(describe_table.clj:219)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table$fn__88647.invoke(describe_table.clj:239)
	at metabase.driver.sqlite$fn__114503$fn__114504.invoke(sqlite.clj:421)
	at metabase.driver.sql_jdbc.execute$fn__80920$do_with_resolved_connection__80921.invoke(execute.clj:333)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at malli.core$_instrument$fn__13249.doInvoke(core.cljc:2526)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at metabase.driver.sqlite$fn__114503.invokeStatic(sqlite.clj:414)
	at metabase.driver.sqlite$fn__114503.invoke(sqlite.clj:412)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table.invokeStatic(describe_table.clj:234)
	at metabase.driver.sql_jdbc.sync.describe_table$describe_table.invoke(describe_table.clj:229)
	at metabase.driver.sql_jdbc$fn__116059.invokeStatic(sql_jdbc.clj:88)
	at metabase.driver.sql_jdbc$fn__116059.invoke(sql_jdbc.clj:86)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.fetch_metadata$fn__97312$table_metadata__97317$fn__97318.invoke(fetch_metadata.clj:20)
	at metabase.sync.fetch_metadata$fn__97312$table_metadata__97317.invoke(fetch_metadata.clj:17)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__97588$db_metadata__97593$fn__97594.invoke(fetch_metadata.clj:94)
	at metabase.sync.sync_metadata.fields.fetch_metadata$fn__97588$db_metadata__97593.invoke(fetch_metadata.clj:90)
	at metabase.sync.sync_metadata.fields$fn__98122$sync_fields_for_table_BANG___98131$fn__98134$fn__98135.invoke(fields.clj:73)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:162)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:155)
	at metabase.sync.sync_metadata.fields$fn__98122$sync_fields_for_table_BANG___98131$fn__98134.invoke(fields.clj:72)
	at metabase.sync.sync_metadata.fields$fn__98122$sync_fields_for_table_BANG___98131.invoke(fields.clj:66)
	at clojure.core$partial$fn__5908.invoke(core.clj:2641)
	at clojure.core$map$fn__5935.invoke(core.clj:2770)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1790)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.sync_metadata.fields$fn__98161$sync_fields_BANG___98166$fn__98167.invoke(fields.clj:86)
	at metabase.sync.sync_metadata.fields$fn__98161$sync_fields_BANG___98166.invoke(fields.clj:78)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$fn__63035$run_step_with_metadata__63040$fn__63044$fn__63046.doInvoke(util.clj:380)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)
	at metabase.sync.util$fn__63035$run_step_with_metadata__63040$fn__63044.invoke(util.clj:375)
	at metabase.sync.util$fn__63035$run_step_with_metadata__63040.invoke(util.clj:370)
	at metabase.sync.util$fn__63262$run_sync_operation__63267$fn__63268$fn__63276.invoke(util.clj:486)
	at metabase.sync.util$fn__63262$run_sync_operation__63267$fn__63268.invoke(util.clj:484)
	at metabase.sync.util$fn__63262$run_sync_operation__63267.invoke(util.clj:478)
	at metabase.sync.sync_metadata$fn__99706$sync_db_metadata_BANG___99711$fn__99712$fn__99713.invoke(sync_metadata.clj:60)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:162)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:155)
	at clojure.core$partial$fn__5910.invoke(core.clj:2647)
	at metabase.driver$fn__48226.invokeStatic(driver.clj:717)
	at metabase.driver$fn__48226.invoke(driver.clj:717)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__62955.invoke(util.clj:140)
	at metabase.sync.util$with_db_logging_disabled$fn__62952.invoke(util.clj:131)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_logging$fn__62939.invoke(util.clj:116)
	at metabase.sync.util$with_sync_events$fn__62934.invoke(util.clj:90)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__62924.invoke(util.clj:69)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:183)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:180)
	at metabase.sync.sync_metadata$fn__99706$sync_db_metadata_BANG___99711$fn__99712.invoke(sync_metadata.clj:59)
	at metabase.sync.sync_metadata$fn__99706$sync_db_metadata_BANG___99711.invoke(sync_metadata.clj:55)
	at metabase.sync$fn__99765$sync_database_BANG___99774$fn__99780$fn__99782$fn__99784.invoke(sync.clj:47)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__8244.invokeStatic(protocols.clj:136)
	at clojure.core.protocols$fn__8244.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at metabase.sync$fn__99765$sync_database_BANG___99774$fn__99780$fn__99782.invoke(sync.clj:47)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:162)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:155)
	at clojure.core$partial$fn__5910.invoke(core.clj:2647)
	at metabase.driver$fn__48226.invokeStatic(driver.clj:717)
	at metabase.driver$fn__48226.invoke(driver.clj:717)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__62955.invoke(util.clj:140)
	at metabase.sync.util$with_db_logging_disabled$fn__62952.invoke(util.clj:131)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:104)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_logging$fn__62939.invoke(util.clj:116)
	at metabase.sync.util$with_sync_events$fn__62934.invoke(util.clj:90)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__62924.invoke(util.clj:69)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:183)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:180)
	at metabase.sync$fn__99765$sync_database_BANG___99774$fn__99780.invoke(sync.clj:46)
	at metabase.sync$fn__99765$sync_database_BANG___99774.invoke(sync.clj:33)
	at metabase.sync$fn__99765$sync_database_BANG___99774$fn__99775.invoke(sync.clj:42)
	at metabase.sync$fn__99765$sync_database_BANG___99774.invoke(sync.clj:33)
	at metabase.events.sync_database$process_sync_database_event$fn__114505.invoke(sync_database.clj:37)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0",
    "vendor": ""
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "6.1.55-1-MANJARO",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "sqlite"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-17",
      "tag": "v0.47.8",
      "branch": "?",
      "hash": "639fa5e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Blocking the use of the data explorer

### Additional context

Here is a simple script to create a database with a table that will produce the issue:

```
#!/bin/bash
sqlite3 metabase-issue.db "CREATE TABLE IF NOT EXISTS test (col_0);"
for idx in {1..501}; do
  sqlite3 metabase-issue.db "ALTER TABLE test ADD COLUMN col_$idx;"
done
```

**Comment by calherries** [comment]
If someone picks this up internally, see the [Slack discussion on this](https://metaboat.slack.com/archives/C01LQQ2UW03/p1701434528854909)

**Comment by thebiglabasky** [comment]
@lbrdnk How close would this be compared to the work you did on Postgres having a similar limit?
