### ISSUE TITLE
load-from-h2 into mysql is failing with SQLNonTransientConnectionException

### ISSUE THREAD

**Issue by AnupKumarPanwar** [metabase/metabase#36270]
### load-from-h2 into mysql is failing with SQLNonTransientConnectionException #36270

Here are the logs of the following command

`$ java -jar metabase.jar load-from-h2 ./metabase.db`

```

2023-12-01 12:26:40,983 INFO metabase.util :: Maximum memory available to JVM: 1.9 GB
2023-12-01 12:26:46,704 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2023-12-01 12:27:02,820 INFO driver.impl :: Registered abstract driver :sql  🚚
2023-12-01 12:27:02,841 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
2023-12-01 12:27:02,854 INFO metabase.util :: Load driver :sql-jdbc took 217.7 ms
2023-12-01 12:27:02,855 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
2023-12-01 12:27:02,988 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
2023-12-01 12:27:03,090 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
2023-12-01 12:27:08,489 INFO metabase.core ::
Metabase v0.47.8 (639fa5e ?)

Copyright © 2023 Metabase, Inc.

Metabase Enterprise Edition extensions are NOT PRESENT.
2023-12-01 12:27:08,743 INFO driver.impl :: Registered abstract driver :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set  🚚
2023-12-01 12:27:08,758 INFO driver.impl :: Registered abstract driver :metabase.driver.sql.query-processor.empty-string-is-null/empty-string-is-null  🚚
2023-12-01 12:27:09,136 INFO cmd.copy :: Set up h2 source database and run migrations...
2023-12-01 12:27:09,161 INFO db.setup :: Verifying h2 Database Connection ...
2023-12-01 12:27:10,663 INFO db.setup :: Successfully verified H2 2.1.214 (2022-06-13) application database connection. ✅
2023-12-01 12:27:10,669 INFO db.setup :: Running Database Migrations...
2023-12-01 12:27:10,690 INFO db.setup :: Setting up Liquibase...
2023-12-01 12:27:11,575 INFO db.setup :: Liquibase is ready.
2023-12-01 12:27:11,576 INFO db.liquibase :: Checking if Database has unrun migrations...
2023-12-01 12:27:14,784 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2023-12-01 12:27:14,964 INFO db.liquibase :: Migration lock is cleared. Running migrations...
2023-12-01 12:27:15,429 INFO db.setup :: Database Migrations Current ...  ✅
2023-12-01 12:27:15,440 INFO db.data-migrations :: Running all necessary data migrations, this may take a minute.
2023-12-01 12:27:16,867 INFO db.data-migrations :: Finished running data migrations.
2023-12-01 12:27:16,874 INFO metabase.util :: Database setup took 7.7 s
2023-12-01 12:27:16,875 INFO cmd.copy :: [OK]
2023-12-01 12:27:16,876 INFO cmd.copy :: Set up mysql target database and run migrations...
2023-12-01 12:27:16,876 INFO db.setup :: Verifying mysql Database Connection ...
2023-12-01 12:27:17,153 INFO db.setup :: Successfully verified MySQL 5.7.12-log application database connection. ✅
2023-12-01 12:27:17,160 INFO db.setup :: Running Database Migrations...
2023-12-01 12:27:17,168 INFO db.setup :: Setting up Liquibase...
2023-12-01 12:27:17,219 INFO db.setup :: Liquibase is ready.
2023-12-01 12:27:17,219 INFO db.liquibase :: Checking if Database has unrun migrations...
2023-12-01 12:27:18,553 INFO db.setup :: Database Migrations Current ...  ✅
2023-12-01 12:27:18,554 INFO metabase.util :: Database setup took 1.7 s
2023-12-01 12:27:18,555 INFO cmd.copy :: [OK]
2023-12-01 12:27:18,556 INFO cmd.copy :: Testing if target mysql database is already populated...
2023-12-01 12:27:18,564 INFO cmd.copy :: [OK]
2023-12-01 12:27:18,565 INFO cmd.copy :: Clearing default entries created by Liquibase migrations...
2023-12-01 12:27:18,567 INFO cmd.copy :: Temporarily disabling DB constraints...
2023-12-01 12:27:18,574 INFO cmd.copy :: [OK]
2023-12-01 12:28:31,712 INFO cmd.copy :: Re-enabling DB constraints...
2023-12-01 12:28:31,712 ERROR cmd.copy :: [FAIL]

2023-12-01 12:28:31,719 ERROR cmd.copy :: [FAIL]

clojure.lang.ExceptionInfo: ERROR Clearing default entries created by Liquibase migrations...: ERROR Re-enabling DB constraints...: (conn=8469941) (conn=8469941) Connection is closed {}
	at metabase.cmd.copy$do_step$fn__112767.invoke(copy.clj:33)
	at metabase.cmd.copy$do_step.invokeStatic(copy.clj:29)
	at metabase.cmd.copy$do_step.invoke(copy.clj:27)
	at metabase.cmd.copy$fn__112957$copy_BANG___112962$fn__112963.invoke(copy.clj:394)
	at metabase.cmd.copy$fn__112957$copy_BANG___112962.invoke(copy.clj:372)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:36)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:26)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:73)
	at metabase.cmd$load_from_h2.invoke(cmd.clj:67)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__114063.invoke(cmd.clj:300)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:299)
	at metabase.cmd$run_cmd.invoke(cmd.clj:289)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:181)
	at metabase.core$run_cmd.invoke(core.clj:179)
	at metabase.core$_main.invokeStatic(core.clj:203)
	at metabase.core$_main.doInvoke(core.clj:198)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
Caused by: clojure.lang.ExceptionInfo: ERROR Re-enabling DB constraints...: (conn=8469941) (conn=8469941) Connection is closed {}
	at metabase.cmd.copy$do_step$fn__112767.invoke(copy.clj:33)
	at metabase.cmd.copy$do_step.invokeStatic(copy.clj:29)
	at metabase.cmd.copy$do_step.invoke(copy.clj:27)
	at metabase.cmd.copy$do_with_disabled_db_constraints.invokeStatic(copy.clj:268)
	at metabase.cmd.copy$do_with_disabled_db_constraints.invoke(copy.clj:262)
	at metabase.cmd.copy$clear_existing_rows_BANG_.invokeStatic(copy.clj:284)
	at metabase.cmd.copy$clear_existing_rows_BANG_.invoke(copy.clj:277)
	at metabase.cmd.copy$fn__112957$copy_BANG___112962$fn__112963$fn__112974.invoke(copy.clj:395)
	at metabase.cmd.copy$do_step$fn__112767.invoke(copy.clj:30)
	... 29 more
Caused by: java.sql.SQLNonTransientConnectionException: (conn=8469941) (conn=8469941) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:362)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:611)
	at org.mariadb.jdbc.MariaDbConnection.getTransactionIsolation(MariaDbConnection.java:918)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.getTransactionIsolation(NewProxyConnection.java:1279)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:797)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1048)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1042)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1080)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1060)
	at clojure.java.jdbc$execute_BANG_$execute_helper__21782.invoke(jdbc.clj:1464)
	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1466)
	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1435)
	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1456)
	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1435)
	at metabase.cmd.copy$fn__112879.invokeStatic(copy.clj:256)
	at metabase.cmd.copy$fn__112879.invoke(copy.clj:254)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.cmd.copy$do_with_disabled_db_constraints$fn__112885.invoke(copy.clj:269)
	at metabase.cmd.copy$do_step$fn__112767.invoke(copy.clj:30)
	... 37 more
Caused by: java.sql.SQLNonTransientConnectionException: (conn=8469941) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1946)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356)
	... 58 more
Command failed with exception: ERROR Clearing default entries created by Liquibase migrations...: ERROR Re-enabling DB constraints...: (conn=8469941) (conn=8469941) Connection is closed

```

### To Reproduce

`$ java -jar metabase.jar load-from-h2 ./metabase.db`

### Information about your Metabase installation

```JSON
- Migrating from H2 to MySql Database
```

### Severity

blocking

**Comment by Tony-metabase** [comment]
What version are you running and are you passing the ENV variables as well? FYI

https://www.metabase.com/docs/latest/troubleshooting-guide/loading-from-h2#are-you-trying-to-migrate-the-application-database-from-h2-to-something-else

**Comment by paoliniluis** [comment]
Please upgrade to MySQL 8. MySQL 5.7 is already EoL and we don't support it anymore
