### ISSUE TITLE
SSH tunnelled db connections break indefinitely when the remote sshd is restarted

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#36403]
### Describe the bug

When using ssh tunnelling, if the remote service serving the tunnel is rebooted, the db connection will break and it won't recover until Metabase is restarted.

### To Reproduce

I used this repo to reproduce locally: https://github.com/paoliniluis/metabase-sqlserver , but I think any ssh tunnelled setup will do. Note that it requires a Linux / x86 architecture, it won't work on a Mac out of the box.

1. Set up a database connection via an SSH tunnel.
2. Verify the db connection works by running any question
3. Restart the sshd service on jump host (`docker-compose restart openssh-server`)
4. Re-run the previous question
5. (!) The query will fail after several minutes, and a Connection Refused error message will be displayed. The db connection will no longer work until Metabase is restarted.

### Expected behavior

The tunnel should recover from a remote sshd restart

### Logs

strace in the metabase container, showing connections to the local tunnel port 32897 worked, before restarting the sshd server:
```
[pid   138] 10:38:42 socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, NETLINK_ROUTE) = 30
[pid   138] 10:38:42 bind(30, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 0
[pid   138] 10:38:42 getsockname(30, {sa_family=AF_NETLINK, nl_pid=1, nl_groups=00000000}, [12]) = 0
[pid   138] 10:38:42 sendto(30, {{len=20, type=RTM_GETADDR, flags=NLM_F_REQUEST|NLM_F_DUMP, seq=1701772722, pid=0}, {ifa_family=AF_UNSPEC, ...}}, 20, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) =
20
[pid   138] 10:38:42 recvmsg(30, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base=[{{len=76, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=1701772722, pid=1}, {ifa_fami
ly=AF_INET, ifa_prefixlen=8, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_HOST, ifa_index=if_nametoindex("lo")}, [{{nla_len=8, nla_type=IFA_ADDRESS}, inet_addr("127.0.0.1")}, {{nla_len=8, nla_type=IFA_LOCAL}, ine
t_addr("127.0.0.1")}, {{nla_len=7, nla_type=IFA_LABEL}, "lo"}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=1222
756, tstamp=1222756}}]}, {{len=88, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=1701772722, pid=1}, {ifa_family=AF_INET, ifa_prefixlen=16, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_UNIVERSE, ifa_index=if_nametoind
ex("eth0")}, [{{nla_len=8, nla_type=IFA_ADDRESS}, inet_addr("172.18.0.7")}, {{nla_len=8, nla_type=IFA_LOCAL}, inet_addr("172.18.0.7")}, {{nla_len=8, nla_type=IFA_BROADCAST}, inet_addr("172.18.255.255")}, {{nla_len
=9, nla_type=IFA_LABEL}, "eth0"}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=1222769, tstamp=1222769}}]}], iov
_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 164
[pid   138] 10:38:42 recvmsg(30, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=20, type=NLMSG_DONE, flags=NLM_F_MULTI, seq=1701772722, pid=1}, 0}, iov_len
=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 20
[pid   138] 10:38:42 socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_IP) = 30
[pid   138] 10:38:42 connect(30, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
[pid   138] 10:38:42 getsockname(30, {sa_family=AF_INET, sin_port=htons(58358), sin_addr=inet_addr("127.0.0.1")}, [28->16]) = 0
[pid   138] 10:38:42 socket(AF_INET, SOCK_STREAM, IPPROTO_IP <unfinished ...>
[pid   138] 10:38:42 <... socket resumed>) = 30
[pid   138] 10:38:42 connect(30, {sa_family=AF_INET, sin_port=htons(32897), sin_addr=inet_addr("127.0.0.1")}, 16 <unfinished ...>
[pid   138] 10:38:42 <... connect resumed>) = -1 EINPROGRESS (Operation now in progress)
[pid   138] 10:38:42 getsockopt(30, SOL_SOCKET, SO_ERROR,  <unfinished ...>
[pid   138] 10:38:42 <... getsockopt resumed>[0], [4]) = 0
[pid   138] 10:38:42 getsockname(30,  <unfinished ...>
[pid   138] 10:38:42 <... getsockname resumed>{sa_family=AF_INET, sin_port=htons(58500), sin_addr=inet_addr("127.0.0.1")}, [28->16]) = 0
[pid   138] 10:38:42 setsockopt(30, SOL_TCP, TCP_NODELAY, [1], 4 <unfinished ...>
[pid   138] 10:38:42 <... setsockopt resumed>) = 0
[pid   138] 10:38:42 setsockopt(30, SOL_SOCKET, SO_KEEPALIVE, [1], 4 <unfinished ...>
[pid   138] 10:38:42 <... setsockopt resumed>) = 0
[pid   138] 10:38:42 setsockopt(30, SOL_TCP, TCP_KEEPIDLE, [30], 4 <unfinished ...>
[pid   138] 10:38:42 <... setsockopt resumed>) = 0
[pid   138] 10:38:42 setsockopt(30, SOL_TCP, TCP_KEEPINTVL, [1], 4) = 0
[pid   138] 10:38:42 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7f4e51eda008} ---
[pid   138] 10:38:42 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7f4e51eda008} ---
[pid   138] 10:38:42 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7f4e51eda008} ---
[pid   138] 10:38:42 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7f4e51eda008} ---
[pid   138] 10:38:42 sendto(30, "\22\1\0C\0\0\0\0\0\0\20\0\6\1\0\26\0\1\5\0\27\0$\377\f\2\0\0\0\0\0|"..., 67, 0, NULL, 0 <unfinished ...>
```

Error after a long timeout in the browser after restarting the sshd server:
> The TCP/IP connection to the host localhost, port 32897 has failed. Error: "Connection refused (Connection refused). Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".

Strace in the metabase container, showing connecting to the same local port no longer works, but Metabase keeps trying indefinitely:
```
[pid   139] 10:45:34 connect(28, {sa_family=AF_INET, sin_port=htons(32897), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid   139] 10:45:34 getsockopt(28, SOL_SOCKET, SO_ERROR, [ECONNREFUSED], [4]) = 0
[pid   138] 10:45:34 socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 28
[pid   138] 10:45:34 connect(28, {sa_family=AF_INET, sin_port=htons(32897), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid   138] 10:45:34 getsockopt(28, SOL_SOCKET, SO_ERROR, [ECONNREFUSED], [4]) = 0
[pid   139] 10:45:35 socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 28
[pid   139] 10:45:35 connect(28, {sa_family=AF_INET, sin_port=htons(32897), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid   139] 10:45:35 getsockopt(28, SOL_SOCKET, SO_ERROR, [ECONNREFUSED], [4]) = 0
[pid   138] 10:45:35 socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 28
[pid   138] 10:45:35 connect(28, {sa_family=AF_INET, sin_port=htons(32897), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid   138] 10:45:35 getsockopt(28, SOL_SOCKET, SO_ERROR, [ECONNREFUSED], [4]) = 0
[pid   139] 10:45:36 socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 28
```

Metabase logs:
```
metabase-sqlserver           | 2023-12-05 12:19:15,396 ERROR core.JobRunShell :: Job DEFAULT.metabase.task.sync-and-analyze.job threw an unhandled Exception:
metabase-sqlserver           | java.sql.SQLException: Connections could not be acquired from the underlying database!
metabase-sqlserver           |  at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
metabase-sqlserver           |  at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
metabase-sqlserver           |  at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
metabase-sqlserver           |  at metabase.driver.sql_jdbc.execute$fn__80915$do_with_resolved_connection__80916.invoke(execute.clj:332)
metabase-sqlserver           |  at clojure.lang.AFn.applyToHelper(AFn.java:165)
metabase-sqlserver           |  at clojure.lang.AFn.applyTo(AFn.java:144)
metabase-sqlserver           |  at clojure.core$apply.invokeStatic(core.clj:667)
metabase-sqlserver           |  at clojure.core$apply.invoke(core.clj:662)
metabase-sqlserver           |  at malli.core$_instrument$fn__13253.doInvoke(core.cljc:2526)
metabase-sqlserver           |  at clojure.lang.RestFn.invoke(RestFn.java:457)
metabase-sqlserver           |  at metabase.driver.sql_jdbc.execute$fn__80947.invokeStatic(execute.clj:380)
metabase-sqlserver           |  at metabase.driver.sql_jdbc.execute$fn__80947.invoke(execute.clj:378)
metabase-sqlserver           |  at clojure.lang.MultiFn.invoke(MultiFn.java:244)
metabase-sqlserver           |  at metabase.driver.sql_jdbc.sync.describe_database$fn__86626$describe_database__86627.invoke(describe_database.clj:164)
metabase-sqlserver           |  at clojure.lang.AFn.applyToHelper(AFn.java:156)
metabase-sqlserver           |  at clojure.lang.AFn.applyTo(AFn.java:144)
metabase-sqlserver           |  at clojure.core$apply.invokeStatic(core.clj:667)
metabase-sqlserver           |  at clojure.core$apply.invoke(core.clj:662)
metabase-sqlserver           |  at malli.core$_instrument$fn__13253.doInvoke(core.cljc:2526)
metabase-sqlserver           |  at clojure.lang.RestFn.invoke(RestFn.java:421)
metabase-sqlserver           |  at metabase.driver.sql_jdbc$fn__122764.invokeStatic(sql_jdbc.clj:84)
metabase-sqlserver           |  at metabase.driver.sql_jdbc$fn__122764.invoke(sql_jdbc.clj:82)
metabase-sqlserver           |  at clojure.lang.MultiFn.invoke(MultiFn.java:234)
metabase-sqlserver           |  at metabase.sync.fetch_metadata$fn__98092$db_metadata__98097$fn__98098.invoke(fetch_metadata.clj:15)
metabase-sqlserver           |  at metabase.sync.fetch_metadata$fn__98092$db_metadata__98097.invoke(fetch_metadata.clj:12)
metabase-sqlserver           |  at metabase.sync.sync_metadata$fn__100511$sync_db_metadata_BANG___100516$fn__100517.invoke(sync_metadata.clj:58)
metabase-sqlserver           |  at metabase.sync.sync_metadata$fn__100511$sync_db_metadata_BANG___100516.invoke(sync_metadata.clj:55)
metabase-sqlserver           |  at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:75)
metabase-sqlserver           |  at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:66)
metabase-sqlserver           |  at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:85)
metabase-sqlserver           |  at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
metabase-sqlserver           |  at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
metabase-sqlserver           | Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
metabase-sqlserver           |  at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1507)
metabase-sqlserver           |  at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
metabase-sqlserver           |  at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
metabase-sqlserver           |  at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
metabase-sqlserver           |  at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
metabase-sqlserver           |  ... 30 more
metabase-sqlserver           | Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 32897 has failed. Error: "Connection refused (Connection refused). Verif
y the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall."
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "6.5.0-1009-oem",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-11-17",
      "tag": "v1.47.8",
      "branch": "?",
      "hash": "639fa5e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

Looks P1 to me. To recover, Metabase has to be restarted, which is not self-service on cloud.

**Comment by paoliniluis** [comment]
Good debugging @zbodi74

**Comment by qnkhuat** [comment]
Tested on a remote postgres db, restarting ssh and postgres works fine. gonna find a x86 machine to test this on.

**Comment by SejalSheth** [comment]
Hello,

I just wanted to confirm that the issue was seen with SQL Server Standard on windows server not Postgres SQL


Thank you


Sejal Sheth

Senior Director,

Technology & Integration


905-812-7559 (Office)

416-577-8693 (Cell)
www.cedricmillar.com<http://www.cedricmillar.com/>


Office (Canada): 2121 Argentia Rd

Suite 301, Mississauga, ON L5N 2X4

Head Office (US): 7570 Bales Street

Suite 320 Liberty Township, OH 45069

[A red and blue sign with white text  Description automatically generated]

________________________________

**Comment by qnkhuat** [comment]
I followed the reproduction steps and tested on SQL server; I'm still successfully running the query after restarting OpenSSH-server. 

Could you check again @zbodi74 ? I tested on master (ff5e6765a0eae93686d5d5fa436cbb58dfb969c7)

**Comment by zbodi74** [comment]
@qnkhuat, I still experience the same behavior with `v1.48.8` and `v1.49.0`.

**Comment by qnkhuat** [comment]
I was able to reproduce it with Luiggi's setup.

But when I tried to reproduce with a remote sqlserver running from docker, and use ssh tunneling from local metabase instance. Then try to restart sshd but the bug doesn't occur. Not sure why, but will need to try again with a custom docker compose setup for ease of debugging.

**Comment by paoliniluis** [comment]
@ghostframe 👆🏻
