### ISSUE TITLE
"Caught unexpected Exception in streaming response body" on x-rays (v47.x with new redshift driver // v48 as well)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#36771]
### Describe the bug

I built Metabase 47.x with the new redshift driver (.23) and I'm getting a weird error when using x-rays on some tables

### To Reproduce

1) Build Metabase 47.x with the new redshift driver (v23)
2) sync the CI Redshift DB
3) try an x-ray on a table and check the logs

### Expected behavior

all cards should work without any error

### Logs

```
2023-12-13 21:19:06,623 ERROR async.streaming-response :: Caught unexpected Exception in streaming response body
java.lang.NullPointerException: Deflater has been closed
	at java.base/java.util.zip.Deflater.ensureOpen(Unknown Source)
	at java.base/java.util.zip.Deflater.deflate(Unknown Source)
	at java.base/java.util.zip.Deflater.deflate(Unknown Source)
	at java.base/java.util.zip.GZIPOutputStream.finish(Unknown Source)
	at java.base/java.util.zip.DeflaterOutputStream.close(Unknown Source)
	at metabase.async.streaming_response$delay_output_stream$fn__43056.invoke(streaming_response.clj:121)
	at metabase.async.streaming_response.proxy$java.io.OutputStream$ff19274a.close(Unknown Source)
	at metabase.async.streaming_response$write_error_BANG_.invokeStatic(streaming_response.clj:58)
	at metabase.async.streaming_response$write_error_BANG_.invoke(streaming_response.clj:46)
	at metabase.query_processor.streaming$streaming_response_STAR_$fn__52280.invoke(streaming.clj:176)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)
	at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)
	at metabase.async.streaming_response$do_f_async$task__43041.invoke(streaming_response.clj:88)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-12-13 21:19:06,624 ERROR async.streaming-response :: Error writing error to output stream {:via [{:type java.lang.NullPointerException, :message Deflater has been closed, :at [java.util.zip.Deflater ensureOpen nil -1]}], :trace [[java.util.zip.Deflater ensureOpen nil -1] [java.util.zip.Deflater deflate nil -1] [java.util.zip.Deflater deflate nil -1] [java.util.zip.GZIPOutputStream finish nil -1] [java.util.zip.DeflaterOutputStream close nil -1] [metabase.async.streaming_response$delay_output_stream$fn__43056 invoke streaming_response.clj 121] [metabase.async.streaming_response.proxy$java.io.OutputStream$ff19274a close nil -1] [metabase.async.streaming_response$write_error_BANG_ invokeStatic streaming_response.clj 58] [metabase.async.streaming_response$write_error_BANG_ invoke streaming_response.clj 46] [metabase.query_processor.streaming$streaming_response_STAR_$fn__52280 invoke streaming.clj 176] [clojure.lang.AFn applyToHelper AFn.java 156] [clojure.lang.AFn applyTo AFn.java 144] [clojure.core$apply invokeStatic core.clj 667] [clojure.core$with_bindings_STAR_ invokeStatic core.clj 1990] [clojure.core$with_bindings_STAR_ doInvoke core.clj 1990] [clojure.lang.RestFn applyTo RestFn.java 142] [clojure.core$apply invokeStatic core.clj 671] [clojure.core$bound_fn_STAR_$fn__5818 doInvoke core.clj 2020] [clojure.lang.RestFn invoke RestFn.java 421] [metabase.async.streaming_response$do_f_STAR_ invokeStatic streaming_response.clj 69] [metabase.async.streaming_response$do_f_STAR_ invoke streaming_response.clj 67] [metabase.async.streaming_response$do_f_async$task__43041 invoke streaming_response.clj 88] [clojure.lang.AFn run AFn.java 22] [java.util.concurrent.Executors$RunnableAdapter call nil -1] [java.util.concurrent.FutureTask run nil -1] [java.util.concurrent.ThreadPoolExecutor runWorker nil -1] [java.util.concurrent.ThreadPoolExecutor$Worker run nil -1] [java.lang.Thread run nil -1]], :cause Deflater has been closed, :_status 500}
java.lang.NullPointerException: Deflater has been closed
	at java.base/java.util.zip.Deflater.ensureOpen(Unknown Source)
	at java.base/java.util.zip.Deflater.deflate(Unknown Source)
	at java.base/java.util.zip.Deflater.deflate(Unknown Source)
	at java.base/java.util.zip.GZIPOutputStream.finish(Unknown Source)
	at java.base/java.util.zip.DeflaterOutputStream.close(Unknown Source)
	at metabase.async.streaming_response$delay_output_stream$fn__43056.invoke(streaming_response.clj:121)
	at metabase.async.streaming_response.proxy$java.io.OutputStream$ff19274a.close(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source)
	at java.base/java.io.OutputStreamWriter.close(Unknown Source)
	at java.base/java.io.BufferedWriter.close(Unknown Source)
	at metabase.async.streaming_response$write_error_BANG_.invokeStatic(streaming_response.clj:61)
	at metabase.async.streaming_response$write_error_BANG_.invoke(streaming_response.clj:46)
	at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)
	at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)
	at metabase.async.streaming_response$do_f_async$task__43041.invoke(streaming_response.clj:88)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-12-13 21:19:06,624 ERROR async.streaming-response :: bound-fn caught unexpected Exception
java.lang.NullPointerException: Deflater has been closed
	at java.base/java.util.zip.Deflater.ensureOpen(Unknown Source)
	at java.base/java.util.zip.Deflater.deflate(Unknown Source)
	at java.base/java.util.zip.Deflater.deflate(Unknown Source)
	at java.base/java.util.zip.GZIPOutputStream.finish(Unknown Source)
	at java.base/java.util.zip.DeflaterOutputStream.close(Unknown Source)
	at metabase.async.streaming_response$delay_output_stream$fn__43056.invoke(streaming_response.clj:121)
	at metabase.async.streaming_response.proxy$java.io.OutputStream$ff19274a.close(Unknown Source)
	at metabase.async.streaming_response$write_error_BANG_.invokeStatic(streaming_response.clj:58)
	at metabase.async.streaming_response$write_error_BANG_.invoke(streaming_response.clj:46)
	at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)
	at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)
	at metabase.async.streaming_response$do_f_async$task__43041.invoke(streaming_response.clj:88)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Information about your Metabase installation

```JSON
47.x with the new redshift driver
```

### Severity

P2

### Additional context

Errors seem to go away if you refresh

**Comment by paoliniluis** [comment]
There are many many API calls that are cancelled
2023-12-13 21:33:05,182 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: unexpected-error] 715.6 ms (14 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (4 idle, 0 queued) (111 total active threads) Queries in flight: 11 (0 queued); redshift DB 2 connections: 0/1 (0 threads blocked)
2023-12-13 21:33:06,274 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: canceled] 1.8 s (14 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (3 idle, 0 queued) (114 total active threads) Queries in flight: 10 (0 queued); redshift DB 2 connections: 1/1 (0 threads blocked)
2023-12-13 21:33:06,307 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.7 s (15 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (4 idle, 0 queued) (114 total active threads) Queries in flight: 9 (0 queued); redshift DB 2 connections: 1/1 (10 threads blocked)
2023-12-13 21:33:06,319 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: canceled] 1.9 s (14 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (4 idle, 0 queued) (114 total active threads) Queries in flight: 8 (0 queued); redshift DB 2 connections: 1/1 (1 threads blocked)
2023-12-13 21:33:07,267 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 2.6 s (14 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (4 idle, 0 queued) (115 total active threads) Queries in flight: 8 (0 queued); redshift DB 2 connections: 1/1 (9 threads blocked)
2023-12-13 21:33:07,300 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 2.6 s (15 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (4 idle, 0 queued) (116 total active threads) Queries in flight: 8 (0 queued); redshift DB 2 connections: 1/1 (8 threads blocked)
2023-12-13 21:33:07,303 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 994.0 ms (16 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (4 idle, 0 queued) (116 total active threads) Queries in flight: 7 (0 queued); redshift DB 2 connections: 4/4 (8 threads blocked)
2023-12-13 21:33:08,224 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 922.9 ms (15 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (4 idle, 0 queued) (118 total active threads) Queries in flight: 7 (0 queued); redshift DB 2 connections: 7/7 (8 threads blocked)
2023-12-13 21:33:08,224 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: canceled] 3.8 s (15 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (4 idle, 0 queued) (118 total active threads) Queries in flight: 7 (0 queued); redshift DB 2 connections: 1/1 (2 threads blocked)
2023-12-13 21:33:08,244 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 975.7 ms (16 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (4 idle, 0 queued) (119 total active threads) Queries in flight: 7 (0 queued); redshift DB 2 connections: 7/7 (6 threads blocked)
2023-12-13 21:33:08,261 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 957.2 ms (15 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (4 idle, 0 queued) (120 total active threads) Queries in flight: 6 (0 queued); redshift DB 2 connections: 7/7 (7 threads blocked)
2023-12-13 21:33:08,261 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 3.6 s (14 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (4 idle, 0 queued) (120 total active threads) Queries in flight: 6 (0 queued); redshift DB 2 connections: 1/1 (6 threads blocked)
2023-12-13 21:33:08,455 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 3.8 s (14 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (4 idle, 0 queued) (121 total active threads) Queries in flight: 6 (0 queued); redshift DB 2 connections: 1/1 (7 threads blocked)
2023-12-13 21:33:08,463 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: canceled] 4.0 s (14 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (4 idle, 0 queued) (121 total active threads) Queries in flight: 5 (0 queued); redshift DB 2 connections: 1/1 (3 threads blocked)
2023-12-13 21:33:09,214 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 4.6 s (14 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (4 idle, 0 queued) (121 total active threads) Queries in flight: 4 (0 queued); redshift DB 2 connections: 1/1 (5 threads blocked)
2023-12-13 21:33:09,224 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: canceled] 4.8 s (15 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (3 idle, 0 queued) (121 total active threads) Queries in flight: 2 (0 queued); redshift DB 2 connections: 1/1 (4 threads blocked)
2023-12-13 21:33:09,224 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 979.5 ms (15 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (4 idle, 0 queued) (121 total active threads) Queries in flight: 1 (0 queued); redshift DB 2 connections: 10/10 (3 threads blocked)
2023-12-13 21:33:09,224 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 962.7 ms (15 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (4 idle, 0 queued) (121 total active threads) Queries in flight: 1 (0 queued); redshift DB 2 connections: 10/10 (4 threads blocked)
2023-12-13 21:33:09,226 DEBUG middleware.log :: POST /api/dataset 202 [ASYNC: completed] 1.0 s (15 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (4 idle, 0 queued) (121 total active threads) Queries in flight: 0 (0 queued); redshift DB 2 connections: 10/10 (2 threads blocked)


but cards are fine

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/36775

**Comment by paoliniluis** [comment]
same in 48

**Comment by metamben** [comment]
Cannot reproduce with fde8b90.
