### ISSUE TITLE
After restarting, the project can't run.

### ISSUE THREAD

**Issue by wanghao123123** [metabase/metabase#37035]
### Describe the bug

	at metabase.core$init_BANG_.invokeStatic(core.clj:154)
	at metabase.core$init_BANG_.invoke(core.clj:149)
	at metabase.core$start_normally.invokeStatic(core.clj:166)
	at metabase.core$start_normally.invoke(core.clj:160)
	at metabase.core$entrypoint.invokeStatic(core.clj:199)
	at metabase.core$entrypoint.doInvoke(core.clj:193)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.bootstrap.main(Unknown Source)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v48.00-033::noahmoss:
     Reason: liquibase.exception.DatabaseException: (conn=72937) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'agg_recipients as ( [Failed SQL: (1064) create or replace view v_subscriptions as
with agg_recipients as (
    select
        pulse_channel_id,
        group_concat(core_user.email) as recipients
    from pulse_channel_recipient
        left join core_user on pulse_channel_recipient.user_id = core_user.id
    group by pulse_channel_id
)

### To Reproduce

My project was created normally from 21 years to 23 years, but it began to report an error after the project restarted. It may be because the version of my k8s images is latest, but I don't know what the old version is.

### Information about your Metabase installation

```JSON
mysql
```

### Severity

Quite urgent

**Comment by qnkhuat** [comment]
Are you running mysql < 8.0 ? 

if so upgrading to 8.0 should fix the problem.

see https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2 for the minimum version for each supported database.

**Comment by wanghao123123** [comment]
> 你运行的是 mysql < 8.0 吗？
> 
> 如果是这样，升级到 8.0 应该可以解决问题。
> 
> 有关每个支持的数据库的最低版本，请参阅[https://www.metabase.com/docs/latest/installation-and-operation/migration-from-h2 。](https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2)

But my original mysql is not 8.0 to 8.0 upgrade is a serious matter may have an impact on my existing business. I don't think it's the mysql version.

**Comment by qnkhuat** [comment]
Mysql lower than 8.0 is the end of life(see [here](https://endoflife.date/mysql)), and Metabase will only support versions that are currently active.

So in order to upgrade to 48 you'll need to upgrade your database.
