### ISSUE TITLE
After changing metabase database from mysql to pgsql migration checksums check fails

### ISSUE THREAD

**Issue by erfantkerfan** [metabase/metabase#37101]
### Describe the bug

I have metabse instanse using mysql databse,
After changing its database from mysql to pgsql using pgloader while cheching migrations metabase dails and container is killed is in a loop

### To Reproduce

1. start a fresh instance of metabse with mysql
2. migrate the data to pgsql using pgloader
3. change the connection from mysql to pgsql inmetabase
4. you would see this in logs:
```
metabase  | 2023-12-24 14:55:25,883 ERROR metabase.core :: Metabase Initialization FAILED
metabase  | liquibase.exception.ValidationFailedException: Validation Failed:
metabase  |      112 change sets check sum
metabase  |           migrations/000_migrations.yaml::16::agilliland was: 8:b81df46fe16c3e8659a81798b97a4793 but is now: 8:ecc7f02641a589e6d35f88587ac6e02b
metabase  |           migrations/000_migrations.yaml::24::agilliland was: 8:5e7354b3f92782d1151be0aa9d3fe625 but is now: 8:60825b125b452747098b577310c142b1
metabase  |           migrations/000_migrations.yaml::52::camsaul was: 8:329695cb161ceb86f6d9473819359351 but is now: 8:5af9ea2a96cd6e75a8ac1e6afde7126b
metabase  |           migrations/000_migrations.yaml::166::camsaul was: 8:cd87d40358297ca4a3a644f92a03c377 but is now: 8:92dafa5c15c46e2af8380304449c7dfa
metabase  |           migrations/000_migrations.yaml::168::camsaul was: 8:c4ba88582a69b4695512d5f1e114b6da but is now: 8:6d40bfa472bccd2d54284aeb89e1ec3c
metabase  |           migrations/000_migrations.yaml::303::tsmacdonald was: 8:bfa9e69eaeed6b1949670730cbda96f8 but is now: 8:506e174d6656b09ddedf19e97c0d3c3d
metabase  |           migrations/000_migrations.yaml::v42.00-004::jeff303 was: 8:b87007340c01509f7645d623f484bc35 but is now: 8:d9a1dbf5cdc249516796fd9ed81305a4
metabase  |           migrations/000_migrations.yaml::v42.00-005::jeff303 was: 8:4fc93bf45ab81d53575756ca7e380b09 but is now: 8:136b2b7ee7dd813b8d3a3154d1bea708
metabase  |           migrations/000_migrations.yaml::v42.00-006::jeff303 was: 8:482f1edc95984d97ead770380d1b537c but is now: 8:5fe4654ed7abd89f71eb9372ac208da3
metabase  |           migrations/000_migrations.yaml::v42.00-007::jeff303 was: 8:6bb28eb9953ece5689e2f8e2c8f70e40 but is now: 8:592bfa5fba147bd0ba28c267c796a65d
metabase  |           migrations/000_migrations.yaml::v42.00-008::jeff303 was: 8:f0655d1b838de73a10a1a87855542231 but is now: 8:ea964b569fd70a9f937967179ad96e96
metabase  |           migrations/000_migrations.yaml::v42.00-009::jeff303 was: 8:ed9bedd9b1dbe2f4f032ba7952f6cc42 but is now: 8:faa3d926a4c1ea101a87f80469e4c3b5
metabase  |           migrations/000_migrations.yaml::v42.00-010::jeff303 was: 8:0071b214b07c1986efe4ef376174283f but is now: 8:1538ae25e827ae059a7cc4b7cf225258
metabase  |           migrations/000_migrations.yaml::v42.00-011::jeff303 was: 8:fac89cb5a76acd8b09b4d0dfd025277b but is now: 8:5a13403a42ddb4948873a5f115bb949e
metabase  |           migrations/000_migrations.yaml::v42.00-012::jeff303 was: 8:c36c26ca3fe17cfcc37de94f7a69df99 but is now: 8:0f7f6537b8a60d83024bcfeff9c5c9d6
metabase  |           migrations/000_migrations.yaml::v42.00-013::jeff303 was: 8:68395b6f5066f1bc01c57c61cf16e94d but is now: 8:0ee5d0c8b49419900a86acce11698b9f
metabase  |           migrations/000_migrations.yaml::v42.00-014::jeff303 was: 8:350ba4d3f1a091bcc9d58d5f7bb5a323 but is now: 8:49dfb6668ca9c8d1cabf8c9656e7ba5b
metabase  |           migrations/000_migrations.yaml::v42.00-015::jeff303 was: 8:5d2272bd598f45699fa72d25d76bc93e but is now: 8:90a5ba43867c1a0772641ce942de8fe6
metabase  |           migrations/000_migrations.yaml::v42.00-016::jeff303 was: 8:a3a2edd6d924acef9e552c88a16da5ff but is now: 8:09ea3ac9939b25db92cc5d4053e6fd4a
metabase  |           migrations/000_migrations.yaml::v42.00-017::jeff303 was: 8:06d03a4e17109c3393168b5c9f89165b but is now: 8:14bf9629c1e94583b8240298df8fa6e7
metabase  |           migrations/000_migrations.yaml::v42.00-018::jeff303 was: 8:77e12da960def76ab529e11170f0b1cd but is now: 8:00408a84f8098e850a465a2c98e6aff5
metabase  |           migrations/000_migrations.yaml::v42.00-019::jeff303 was: 8:7cd95b97e28834a6c713ca0f2c86427d but is now: 8:afa168a1d459106a0ec607f76d15a0aa
metabase  |           migrations/000_migrations.yaml::v42.00-020::jeff303 was: 8:a1782977481866189befb3b2e8d6a4ef but is now: 8:a3dd42bbe25c415ce21e4c180dc1c1d7
metabase  |           migrations/000_migrations.yaml::v42.00-021::jeff303 was: 8:b92ca263a9ac9dca4e31b74f0ac934a6 but is now: 8:041c129167b10c951f337dba672020d6
metabase  |           migrations/000_migrations.yaml::v42.00-022::jeff303 was: 8:629f6079c2f389953dfc236f2db05060 but is now: 8:60241b3d3d5f05f238adecfdca69b3b2
metabase  |           migrations/000_migrations.yaml::v42.00-023::jeff303 was: 8:6130da3b1c6263b416ec35a8502239b4 but is now: 8:fc6f2fc275a8f025c150215beb9aa776
metabase  | 
```

### Expected behavior

there would be command to overwrite the checksums

### Logs

metabase  | 2023-12-24 14:59:36,039 ERROR metabase.core :: Metabase Initialization FAILED
metabase  | liquibase.exception.ValidationFailedException: Validation Failed:
metabase  |      112 change sets check sum
metabase  |           migrations/000_migrations.yaml::16::agilliland was: 8:b81df46fe16c3e8659a81798b97a4793 but is now: 8:ecc7f02641a589e6d35f88587ac6e02b
metabase  |           migrations/000_migrations.yaml::24::agilliland was: 8:5e7354b3f92782d1151be0aa9d3fe625 but is now: 8:60825b125b452747098b577310c142b1
metabase  |           migrations/000_migrations.yaml::52::camsaul was: 8:329695cb161ceb86f6d9473819359351 but is now: 8:5af9ea2a96cd6e75a8ac1e6afde7126b
metabase  |           migrations/000_migrations.yaml::166::camsaul was: 8:cd87d40358297ca4a3a644f92a03c377 but is now: 8:92dafa5c15c46e2af8380304449c7dfa
metabase  |           migrations/000_migrations.yaml::168::camsaul was: 8:c4ba88582a69b4695512d5f1e114b6da but is now: 8:6d40bfa472bccd2d54284aeb89e1ec3c
metabase  |           migrations/000_migrations.yaml::303::tsmacdonald was: 8:bfa9e69eaeed6b1949670730cbda96f8 but is now: 8:506e174d6656b09ddedf19e97c0d3c3d
metabase  |           migrations/000_migrations.yaml::v42.00-004::jeff303 was: 8:b87007340c01509f7645d623f484bc35 but is now: 8:d9a1dbf5cdc249516796fd9ed81305a4
metabase  |           migrations/000_migrations.yaml::v42.00-005::jeff303 was: 8:4fc93bf45ab81d53575756ca7e380b09 but is now: 8:136b2b7ee7dd813b8d3a3154d1bea708
metabase  |           migrations/000_migrations.yaml::v42.00-006::jeff303 was: 8:482f1edc95984d97ead770380d1b537c but is now: 8:5fe4654ed7abd89f71eb9372ac208da3
metabase  |           migrations/000_migrations.yaml::v42.00-007::jeff303 was: 8:6bb28eb9953ece5689e2f8e2c8f70e40 but is now: 8:592bfa5fba147bd0ba28c267c796a65d
metabase  |           migrations/000_migrations.yaml::v42.00-008::jeff303 was: 8:f0655d1b838de73a10a1a87855542231 but is now: 8:ea964b569fd70a9f937967179ad96e96
metabase  |           migrations/000_migrations.yaml::v42.00-009::jeff303 was: 8:ed9bedd9b1dbe2f4f032ba7952f6cc42 but is now: 8:faa3d926a4c1ea101a87f80469e4c3b5
metabase  |           migrations/000_migrations.yaml::v42.00-010::jeff303 was: 8:0071b214b07c1986efe4ef376174283f but is now: 8:1538ae25e827ae059a7cc4b7cf225258
metabase  |           migrations/000_migrations.yaml::v42.00-011::jeff303 was: 8:fac89cb5a76acd8b09b4d0dfd025277b but is now: 8:5a13403a42ddb4948873a5f115bb949e
metabase  |           migrations/000_migrations.yaml::v42.00-012::jeff303 was: 8:c36c26ca3fe17cfcc37de94f7a69df99 but is now: 8:0f7f6537b8a60d83024bcfeff9c5c9d6
metabase  |           migrations/000_migrations.yaml::v42.00-013::jeff303 was: 8:68395b6f5066f1bc01c57c61cf16e94d but is now: 8:0ee5d0c8b49419900a86acce11698b9f
metabase  |           migrations/000_migrations.yaml::v42.00-014::jeff303 was: 8:350ba4d3f1a091bcc9d58d5f7bb5a323 but is now: 8:49dfb6668ca9c8d1cabf8c9656e7ba5b
metabase  |           migrations/000_migrations.yaml::v42.00-015::jeff303 was: 8:5d2272bd598f45699fa72d25d76bc93e but is now: 8:90a5ba43867c1a0772641ce942de8fe6
metabase  |           migrations/000_migrations.yaml::v42.00-016::jeff303 was: 8:a3a2edd6d924acef9e552c88a16da5ff but is now: 8:09ea3ac9939b25db92cc5d4053e6fd4a
metabase  |           migrations/000_migrations.yaml::v42.00-017::jeff303 was: 8:06d03a4e17109c3393168b5c9f89165b but is now: 8:14bf9629c1e94583b8240298df8fa6e7
metabase  |           migrations/000_migrations.yaml::v42.00-018::jeff303 was: 8:77e12da960def76ab529e11170f0b1cd but is now: 8:00408a84f8098e850a465a2c98e6aff5
metabase  |           migrations/000_migrations.yaml::v42.00-019::jeff303 was: 8:7cd95b97e28834a6c713ca0f2c86427d but is now: 8:afa168a1d459106a0ec607f76d15a0aa
metabase  |           migrations/000_migrations.yaml::v42.00-020::jeff303 was: 8:a1782977481866189befb3b2e8d6a4ef but is now: 8:a3dd42bbe25c415ce21e4c180dc1c1d7
metabase  |           migrations/000_migrations.yaml::v42.00-021::jeff303 was: 8:b92ca263a9ac9dca4e31b74f0ac934a6 but is now: 8:041c129167b10c951f337dba672020d6
metabase  |           migrations/000_migrations.yaml::v42.00-022::jeff303 was: 8:629f6079c2f389953dfc236f2db05060 but is now: 8:60241b3d3d5f05f238adecfdca69b3b2
metabase  |           migrations/000_migrations.yaml::v42.00-023::jeff303 was: 8:6130da3b1c6263b416ec35a8502239b4 but is now: 8:fc6f2fc275a8f025c150215beb9aa776
metabase  | 
metabase  |     at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:296)
metabase  |     at liquibase.Liquibase$16.run(Liquibase.java:1988)
metabase  |     at liquibase.Scope.lambda$child$0(Scope.java:180)
metabase  |     at liquibase.Scope.child(Scope.java:189)
metabase  |     at liquibase.Scope.child(Scope.java:179)
metabase  |     at liquibase.Scope.child(Scope.java:158)
metabase  |     at liquibase.Liquibase.runInScope(Liquibase.java:2405)
metabase  |     at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1978)
metabase  |     at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1969)
metabase  |     at metabase.db.liquibase$has_unrun_migrations_QMARK_.invokeStatic(liquibase.clj:108)
metabase  |     at metabase.db.liquibase$has_unrun_migrations_QMARK_.invoke(liquibase.clj:99)
metabase  |     at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:148)
metabase  |     at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:144)
metabase  |     at metabase.db.setup$fn__52148$migrate_BANG___52153$fn__52154$fn__52155.invoke(setup.clj:78)
metabase  |     at metabase.db.liquibase$fn__51745$do_with_liquibase__51750$fn__51751.invoke(liquibase.clj:66)
metabase  |     at metabase.db.liquibase$fn__51745$do_with_liquibase__51750.invoke(liquibase.clj:59)
metabase  |     at metabase.db.setup$fn__52148$migrate_BANG___52153$fn__52154.invoke(setup.clj:73)
metabase  |     at metabase.db.setup$fn__52148$migrate_BANG___52153.doInvoke(setup.clj:52)
metabase  |     at clojure.lang.RestFn.invoke(RestFn.java:445)
metabase  |     at metabase.db.setup$fn__52212$run_schema_migrations_BANG___52217$fn__52218.invoke(setup.clj:131)
metabase  |     at metabase.db.setup$fn__52212$run_schema_migrations_BANG___52217.invoke(setup.clj:125)
metabase  |     at metabase.db.setup$fn__52265$setup_db_BANG___52270$fn__52271$fn__52274$fn__52275.invoke(setup.clj:156)
metabase  |     at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
metabase  |     at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
metabase  |     at metabase.db.setup$fn__52265$setup_db_BANG___52270$fn__52271$fn__52274.invoke(setup.clj:152)
metabase  |     at metabase.db.setup$fn__52265$setup_db_BANG___52270$fn__52271.invoke(setup.clj:151)
metabase  |     at metabase.db.setup$fn__52265$setup_db_BANG___52270.invoke(setup.clj:145)
metabase  |     at metabase.db$setup_db_BANG_$fn__52298.invoke(db.clj:69)
metabase  |     at metabase.db$setup_db_BANG_.invokeStatic(db.clj:64)
metabase  |     at metabase.db$setup_db_BANG_.invoke(db.clj:55)
metabase  |     at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:113)
metabase  |     at metabase.core$init_BANG__STAR_.invoke(core.clj:99)
metabase  |     at metabase.core$init_BANG_.invokeStatic(core.clj:159)
metabase  |     at metabase.core$init_BANG_.invoke(core.clj:154)
metabase  |     at metabase.core$start_normally.invokeStatic(core.clj:171)
metabase  |     at metabase.core$start_normally.invoke(core.clj:165)
metabase  |     at metabase.core$_main.invokeStatic(core.clj:204)
metabase  |     at metabase.core$_main.doInvoke(core.clj:198)
metabase  |     at clojure.lang.RestFn.invoke(RestFn.java:397)
metabase  |     at clojure.lang.AFn.applyToHelper(AFn.java:152)
metabase  |     at clojure.lang.RestFn.applyTo(RestFn.java:132)
metabase  |     at clojure.lang.Var.applyTo(Var.java:705)
metabase  |     at clojure.core$apply.invokeStatic(core.clj:667)
metabase  |     at clojure.core$apply.invoke(core.clj:662)
metabase  |     at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
metabase  |     at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
metabase  |     at clojure.lang.RestFn.invoke(RestFn.java:397)
metabase  |     at clojure.lang.AFn.applyToHelper(AFn.java:152)
metabase  |     at clojure.lang.RestFn.applyTo(RestFn.java:132)
metabase  |     at metabase.bootstrap.main(Unknown Source)
metabase  | 2023-12-24 14:59:36,042 INFO metabase.core :: Metabase Shutting Down ...
metabase  | 2023-12-24 14:59:36,042 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
metabase  | 2023-12-24 14:59:36,047 INFO metabase.core :: Metabase Shutdown COMPLETE
metabase exited with code 0

### Information about your Metabase installation

```JSON
- metabase version: v0.47.10
- docker info:
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dd1e886e55dd695541fdcd67420c2888645a495
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.786GiB
 Name: SHT-Metabase
 ID: 1339db20-7a17-4db8-84f3-106834e6d569
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 10.0.0.0/8, Size: 16
```

### Severity

medium

### Additional context

Also there was question in your community forum which I trusted that led to this problem and resulting in a downtime more that expected:
https://discourse.metabase.com/t/solved-migrating-database-from-mysql-to-postgresql/6977/2

**Comment by paoliniluis** [comment]
sorry, but you shouldn't be doing this, the only way to change from mysql to postgres is:
1) dump from mysql with dump-to-h2
2) load to postgres with load-from-h2

Metabase keeps track of the migrations and the db that it runs on, as it needs to run different migrations for both.

Switching from one DB to another with something other than metabase itself running the logic for it will break

**Comment by erfantkerfan** [comment]
Okay,
that's good news that there is a way for doing it.
So dumping to h2 and then loading to postgres would not have any side effects?
@paoliniluis 
You could ask your forum maintainers to flag [this](https://discourse.metabase.com/t/solved-migrating-database-from-mysql-to-postgresql/6977/2) post is misinformation, then?
This could avoid other people from following my steps.

**Comment by paoliniluis** [comment]
@erfantkerfan the dump and load process was designed to do this. You shouldn't have side effects

**Comment by erfantkerfan** [comment]
@paoliniluis I tried using H2, but here is the error log I got:
FYI: I tried loading it into a new mysql instance, and it worked, so I dumped it one more time from the new mysql instance (I thought that might solve my problem) but I got the same error, also tried removing the data directory of pgsql (used a fresh pgsql) and that did not help.
```
2023-12-27 08:09:34,113 INFO cmd.copy :: Copying instances of Field...
2023-12-27 08:09:35,378 ERROR cmd.copy :: BatchUpdateException:
 Message: Batch entry 69 INSERT INTO metabase_field ( "description", "database_type", "semantic_type", "table_id", "coercion_strategy", "name", "fingerprint_version", "has_field_values", "settings", "caveats", "fk_target_field_id", "updated_at", "custom_position", "effective_type", "active", "nfc_path", "parent_id", "id", "last_analyzed", "database_is_auto_increment", "json_unfolding", "position", "visibility_type", "preview_display", "display_name", "database_position", "database_required", "fingerprint", "created_at", "base_type", "points_of_interest" ) VALUES ( NULL, 'bigint', NULL, 4486, NULL, 'address → cityID', 0, NULL, NULL, NULL, NULL, '2022-10-16 08:18:12+00', 0, 'type/Integer', 'TRUE', '["address","cityId"]', NULL, 55726, NULL, 'FALSE', 'FALSE', 0, 'normal', 'TRUE', 'Address → CityId', 0, 'FALSE', NULL, '2022-10-16 08:18:12+00', 'type/Integer', NULL ) was aborted: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(4486, address → cityID) already exists.  Call getNextException to see other errors in the batch.
 SQLState: 23505
 Error Code: 0
PSQLException:
 Message: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(4486, address → cityID) already exists.
 SQLState: 23505
 Error Code: 0

2023-12-27 08:09:35,450 INFO cmd.copy :: Re-enabling DB constraints... 
2023-12-27 08:09:35,451 INFO cmd.copy :: [OK]
clojure.lang.ExceptionInfo: Error copying instances of Field {:model "Field"}
        at metabase.cmd.copy$copy_data_BANG_$fn__113060$fn__113061.invoke(copy.clj:189)
        at metabase.cmd.copy$copy_data_BANG_$fn__113060.invoke(copy.clj:186)
        at clojure.core$partition_all$fn__8625$fn__8626.invoke(core.clj:7332)
        at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1205)
        at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1197)
        at clojure.java.jdbc$reducible_result_set_STAR_$reify__21745.reduce(jdbc.clj:1227)
        at clojure.core$reduce.invokeStatic(core.clj:6885)
        at clojure.core$reduce.invoke(core.clj:6868)
        at clojure.java.jdbc$query_reducer$fn__21751$fn__21754.invoke(jdbc.clj:1262)
        at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1091)
        at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1106)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
        at clojure.java.jdbc$reducible_query$reify__21768.reduce(jdbc.clj:1357)
        at clojure.core$transduce.invokeStatic(core.clj:6946)
        at clojure.core$transduce.invoke(core.clj:6933)
        at metabase.cmd.copy$copy_data_BANG_.invokeStatic(copy.clj:173)
        at metabase.cmd.copy$copy_data_BANG_.invoke(copy.clj:167)
        at metabase.cmd.copy$fn__113192$copy_BANG___113197$fn__113198$fn__113211$fn__113212$fn__113213.invoke(copy.clj:404)
        at metabase.cmd.copy$do_with_disabled_db_constraints.invokeStatic(copy.clj:266)
        at metabase.cmd.copy$do_with_disabled_db_constraints.invoke(copy.clj:262)
        at metabase.cmd.copy$fn__113192$copy_BANG___113197$fn__113198$fn__113211$fn__113212.invoke(copy.clj:403)
        at metabase.cmd.copy$do_with_connection_rollback_only.invokeStatic(copy.clj:208)
        at metabase.cmd.copy$do_with_connection_rollback_only.invoke(copy.clj:206)
        at metabase.cmd.copy$fn__113192$copy_BANG___113197$fn__113198$fn__113211.invoke(copy.clj:401)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
        at metabase.cmd.copy$fn__113192$copy_BANG___113197$fn__113198.invoke(copy.clj:398)
        at metabase.cmd.copy$fn__113192$copy_BANG___113197.invoke(copy.clj:372)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:36)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:26)
        at clojure.lang.Var.invoke(Var.java:384)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:73)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:67)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.cmd$run_cmd$fn__114298.invoke(cmd.clj:300)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:299)
        at metabase.cmd$run_cmd.invoke(cmd.clj:289)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.core$run_cmd.invokeStatic(core.clj:181)
        at metabase.core$run_cmd.invoke(core.clj:179)
        at metabase.core$_main.invokeStatic(core.clj:203)
        at metabase.core$_main.doInvoke(core.clj:198)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
        at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.bootstrap.main(Unknown Source)
Caused by: java.sql.BatchUpdateException: Batch entry 69 INSERT INTO metabase_field ( "description", "database_type", "semantic_type", "table_id", "coercion_strategy", "name", "fingerprint_version", "has_field_values", "settings", "caveats", "fk_target_field_id", "updated_at", "custom_position", "effective_type", "active", "nfc_path", "parent_id", "id", "last_analyzed", "database_is_auto_increment", "json_unfolding", "position", "visibility_type", "preview_display", "display_name", "database_position", "database_required", "fingerprint", "created_at", "base_type", "points_of_interest" ) VALUES ( NULL, 'bigint', NULL, 4486, NULL, 'address → cityID', 0, NULL, NULL, NULL, NULL, '2022-10-16 08:18:12+00', 0, 'type/Integer', 'TRUE', '["address","cityId"]', NULL, 55726, NULL, 'FALSE', 'FALSE', 0, 'normal', 'TRUE', 'Address → CityId', 0, 'FALSE', NULL, '2022-10-16 08:18:12+00', 'type/Integer', NULL ) was aborted: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(4486, address → cityID) already exists.  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2544)
        at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:598)
        at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:591)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1058)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1042)
        at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1080)
        at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1060)
        at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1594)
        at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1585)
        at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1653)
        at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1619)
        at metabase.cmd.copy$insert_chunk_BANG_.invokeStatic(copy.clj:126)
        at metabase.cmd.copy$insert_chunk_BANG_.invoke(copy.clj:120)
        at metabase.cmd.copy$copy_data_BANG_$fn__113060$fn__113061.invoke(copy.clj:187)
        ... 57 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(4486, address → cityID) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        ... 75 more
Command failed with exception: Error copying instances of Field
```

**Comment by paoliniluis** [comment]
Try removing the row that’s causing the issue there. Seems you had in your database a row that was there before the constraint was applied

**Comment by flmmartins** [comment]
@erfantkerfan I am trying the same thing as you. Did you manage to migrate? How did you do it?

**Comment by erfantkerfan** [comment]
@flmmartins 
Hi, I tried every possible tool without manually fixing the data. It did not work, so I'm still on mysql.

**Comment by flmmartins** [comment]
I used the same steps as you and ended up with **the same error**.  What I did to fix it was detecting which lines in the table matched the constrain:

`SELECT table_id,name FROM metabase.metabase_field GROUP BY table_id,name HAVING Count(*) > 1;`

Then I list all rows:

`SELECT * FROM metabase.metabase_field`

And manually deleted the line with the oldest updated_by occurrence. It doesn't seem to affect metabase application at all (for now) but I still need to test it further. If this breaks metabase I will create a new issue and let you know but so far it's good.

**Comment by erfantkerfan** [comment]
Here is what finally worked for me, I hope it helps some lost people.
I found the duplicate rows with this single query and removed them:
```SQL
WITH DuplicateFields AS (
  SELECT table_id, name
  FROM metabase.metabase_field
  GROUP BY table_id, name
  HAVING COUNT(*) > 1
)
, final as (SELECT DISTINCT id,db_id,name FROM metabase.metabase_table where (id) in (
SELECT table_id FROM metabase.metabase_field
WHERE (table_id, name) IN (
  SELECT table_id, name
  FROM DuplicateFields))
)
DELETE from metabase.metabase_table where id in (select id from final)
```
also I had to truncate 2 entire tables(I could have removed only prolematic rows but I choose to truncate all of them):
```SQL
truncate table metabase.login_history;
truncate table metabase.query_cache;
```
