### ISSUE TITLE
metabase v0.48.1 Initialization FAILED with postgres:9.5

### ISSUE THREAD

**Issue by cverdela** [metabase/metabase#37251]
### Describe the bug

metabase v0.48.1 Initialization FAILED with postgres:9.5

### To Reproduce

docker run -d --name postgres95 -p15432:5432 --network=myNetwork -e POSTGRES_PASSWORD=123456 -e PGDATA=/var/lib/postgresql/data/pgdata -v D:/Docker/postgres/data9.5:/var/lib/postgresql/data-d postgres:9.5

create database metabase

docker run -d -p 3001:3000 --network=myNetwork -e "MB_DB_TYPE=postgres" -e "MB_DB_DBNAME=metabase" -e "MB_DB_PORT=5432" -e "MB_DB_USER=postgres" -e "MB_DB_PASS=123456" -e "MB_DB_HOST=postgres95" --name metabase metabase/metabase:v0.48.1

### Logs

2024-01-04 06:40:23,501 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v00.00-000::qnkhuat encountered an exception.
2024-01-04 06:40:23,525 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v00.00-000::qnkhuat:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "ADD"
  Position: 119 [Failed SQL: (0) --
-- Name: activity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)]
        at liquibase.command.CommandScope.execute(CommandScope.java:235)
        at liquibase.Liquibase.lambda$update$0(Liquibase.java:237)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.Liquibase.runInScope(Liquibase.java:1618)
        at liquibase.Liquibase.update(Liquibase.java:229)
        at liquibase.Liquibase.update(Liquibase.java:213)
        at liquibase.Liquibase.update(Liquibase.java:198)
        at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:224)
        at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:209)
        at metabase.db.setup$fn__50292$_AMPERSAND_f__50293$fn__50294.invoke(setup.clj:80)
        at metabase.db.liquibase$fn__47826$_AMPERSAND_f__47827.invoke(liquibase.clj:131)
        at metabase.db.liquibase$fn__47826$fn__47829.invoke(liquibase.clj:124)
        at metabase.db.setup$fn__50292$_AMPERSAND_f__50293.doInvoke(setup.clj:75)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:673)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.db.setup$fn__50292$fn__50302.doInvoke(setup.clj:56)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at metabase.db.setup$fn__50317$_AMPERSAND_f__50318.invoke(setup.clj:126)
        at metabase.db.setup$fn__50317$fn__50324.invoke(setup.clj:120)
        at metabase.db.setup$fn__50327$_AMPERSAND_f__50328$fn__50331$fn__50332.invoke(setup.clj:143)
        at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
        at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
        at metabase.db.setup$fn__50327$_AMPERSAND_f__50328$fn__50331.invoke(setup.clj:139)
        at metabase.db.setup$fn__50327$_AMPERSAND_f__50328.invoke(setup.clj:138)
        at metabase.db.setup$fn__50327$fn__50339.invoke(setup.clj:132)
        at metabase.db$setup_db_BANG_$fn__50348.invoke(db.clj:69)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:64)
        at metabase.db$setup_db_BANG_.invoke(db.clj:55)
        at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:111)
        at metabase.core$init_BANG__STAR_.invoke(core.clj:97)
        at metabase.core$init_BANG_.invokeStatic(core.clj:154)
        at metabase.core$init_BANG_.invoke(core.clj:149)
        at metabase.core$start_normally.invokeStatic(core.clj:166)
        at metabase.core$start_normally.invoke(core.clj:160)
        at metabase.core$entrypoint.invokeStatic(core.clj:199)
        at metabase.core$entrypoint.doInvoke(core.clj:193)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
        at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.bootstrap.main(Unknown Source)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v00.00-000::qnkhuat:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "ADD"
  Position: 119 [Failed SQL: (0) --
-- Name: activity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)]
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:123)
        at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:102)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:99)
        at liquibase.command.CommandScope.execute(CommandScope.java:212)
        ... 53 more
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v00.00-000::qnkhuat:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "ADD"
  Position: 119 [Failed SQL: (0) --
-- Name: activity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:761)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:61)
        at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:111)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.Scope.child(Scope.java:260)
        at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94)
        at liquibase.Scope.lambda$child$0(Scope.java:194)
        at liquibase.Scope.child(Scope.java:203)
        at liquibase.Scope.child(Scope.java:193)
        at liquibase.Scope.child(Scope.java:172)
        at liquibase.Scope.child(Scope.java:260)
        at liquibase.Scope.child(Scope.java:264)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:68)
        ... 60 more
Caused by: liquibase.exception.DatabaseException: ERROR: syntax error at or near "ADD"
  Position: 119 [Failed SQL: (0) --
-- Name: activity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:445)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1287)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1269)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:718)
        ... 80 more
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "ADD"
  Position: 119
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292)
        at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:441)
        ... 85 more
2024-01-04 06:40:23,533 INFO metabase.core :: Metabase Shutting Down ...
2024-01-04 06:40:23,534 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2024-01-04 06:40:23,538 INFO metabase.core :: Metabase Shutdown COMPLETE

### Information about your Metabase installation

```JSON
windows10
docker
metabase:v0.48.1
postgres:9.5
```

### Severity

use other version

**Comment by qnkhuat** [comment]
Please use Postgres 12, we only support versions that're currently active.
9.5 was End of life ~3 years ago https://endoflife.date/postgresql
