### ISSUE TITLE
Embeded dashboard takes longer and longer to display.

### ISSUE THREAD

**Issue by Thossine** [metabase/metabase#37289]
**Describe the bug**
Hello,

Since we migrated from 0.46 (or 0.47, i'm not 100% sure) to 0.48 we need to restart the service metabase almost each 2 days cause embeded dashboards doesn't display anymore (or take ages), we have a bunch of errors that didn't occured before the update. I can't figure out what is happening.

**Logs**
[...]
[42c25cce-0871-4a39-a98f-e92a6c8fa4e0] 2024-01-03T10:27:15+01:00 DEBUG metabase.server.middleware.log GET /api/embed/dashboard/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjI5fSwicGFyYW1zIjp7fSwiZXhwIjoxNjgzNzMyMDg0MH0.uazdPEokvKp9MPsXn7DeCkL4lrSR4caDnZHokujLb0k/dashcard/102/card/129 202 [ASYNC: completed] 498,2 ms (14 appels de DB) Connexions App DB : 1/15 Threads Jetty : 2/50 (27 inactif, 0 en file d'attente) (171 total de threads actifs) Requêtes en cours : 1 (0 en file d'attente); oracle DB 9 connections: 2/15 (0 threads blocked)
[42c25cce-0871-4a39-a98f-e92a6c8fa4e0] 2024-01-03T10:27:15+01:00 WARN metabase.events.recent-views Failed to process recent_views event: :event/card-query
clojure.lang.ExceptionInfo: Entrée invalide : ["la valeur doit être un entier supérieur à zéro."] {:type :metabase.util.malli.fn/invalid-input, :error {:schema [pos-int? {:description "la valeur doit être un entier supérieur à zéro.", :error/fn #object[clojure.core$constantly$fn__5740 0xeacd69c "clojure.core$constantly$fn__5740@eacd69c"]}], :value nil, :errors ({:path [], :in [], :schema [pos-int? {:description "la valeur doit être un entier supérieur à zéro.", :error/fn #object[clojure.core$constantly$fn__5740 0xeacd69c "clojure.core$constantly$fn__5740@eacd69c"]}], :value nil})}, :humanized ["la valeur doit être un entier supérieur à zéro."], :schema [pos-int? {:description "la valeur doit être un entier supérieur à zéro.", :error/fn #object[clojure.core$constantly$fn__5740 0xeacd69c "clojure.core$constantly$fn__5740@eacd69c"]}], :value nil, :fn-name metabase.models.recent-views/update-users-recent-views!}
	at metabase.models.recent_views$fn__103329$fn__103342.invoke(recent_views.clj:48)
	at metabase.events.recent_views$publish_event_BANG__primary_method_metabase_events_recent_views_card_query_event.invokeStatic(recent_views.clj:50)
	at metabase.events.recent_views$publish_event_BANG__primary_method_metabase_events_recent_views_card_query_event.invoke(recent_views.clj:37)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at methodical.impl.combo.operator$invoke_fn$fn__17675.invoke(operator.clj:69)
	at methodical.impl.combo.operator$fn__17696$fn__17697$fn__17698.invoke(operator.clj:112)
	at clojure.core$comp$fn__5876.invoke(core.clj:2587)
	at metabase.events$publish_event_BANG__around_method_default$fn__35563.invoke(events.clj:143)
	at metabase.events$publish_event_BANG__around_method_default.invokeStatic(events.clj:137)
	at metabase.events$publish_event_BANG__around_method_default.invoke(events.clj:109)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at clojure.core$partial$fn__5908.invoke(core.clj:2642)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:193)
	at metabase.query_processor.middleware.process_userland_query$add_and_save_execution_info_xform_BANG_$execution_info_rf_STAR___73989.invoke(process_userland_query.clj:100)
	at metabase.query_processor.middleware.results_metadata$insights_xform$combine__72794.invoke(results_metadata.clj:70)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.query_processor.reducible$combine_additional_reducing_fns$combine_additional_reducing_fns_rf_STAR___62551.invoke(reducible.clj:223)
	at clojure.core$take$fn__5974$fn__5975.invoke(core.clj:2889)
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated_xform$fn__72482.invoke(add_rows_truncated.clj:27)
	at metabase.query_processor.middleware.format_rows$format_rows_xform$fn__74500.invoke(format_rows.clj:71)
	at clojure.core$transduce.invokeStatic(core.clj:6948)
	at clojure.core$transduce.invokeStatic(core.clj:6942)
	at clojure.core$transduce.invoke(core.clj:6933)
	at metabase.query_processor.context.default$default_reducef$fn__49657.invoke(default.clj:34)
	at metabase.query_processor.context.default$default_reducef.invokeStatic(default.clj:33)
	at metabase.query_processor.context.default$default_reducef.invoke(default.clj:25)
	at metabase.query_processor.context$reducef.invokeStatic(context.clj:70)
	at metabase.query_processor.context$reducef.invoke(context.clj:63)
	at metabase.query_processor.context.default$default_runf$respond_STAR___49661.invoke(default.clj:45)
	at metabase.driver.oracle$remove_rownum_column.invokeStatic(oracle.clj:498)
	at metabase.driver.oracle$remove_rownum_column.invoke(oracle.clj:494)
	at clojure.core$partial$fn__5908.invoke(core.clj:2642)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__81066.invoke(execute.clj:706)
	at metabase.driver.sql_jdbc.execute$fn__80861$fn__80862.invoke(execute.clj:388)
	at metabase.driver.sql_jdbc.execute$fn__80826$_AMPERSAND_f__80827.invoke(execute.clj:334)
	at metabase.driver.sql_jdbc.execute$fn__80826$fn__80830.invoke(execute.clj:317)
	at metabase.driver.sql_jdbc.execute$fn__80861.invokeStatic(execute.clj:382)
	at metabase.driver.sql_jdbc.execute$fn__80861.invoke(execute.clj:380)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:686)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)
	at metabase.driver.sql_jdbc$fn__109931.invokeStatic(sql_jdbc.clj:82)
	at metabase.driver.sql_jdbc$fn__109931.invoke(sql_jdbc.clj:80)
	at metabase.driver.oracle$fn__126215.invokeStatic(oracle.clj:511)
	at metabase.driver.oracle$fn__126215.invoke(oracle.clj:509)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.context$executef.invokeStatic(context.clj:60)
	at metabase.query_processor.context$executef.invoke(context.clj:49)
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:44)
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:42)
	at metabase.query_processor.context$runf.invokeStatic(context.clj:46)
	at metabase.query_processor.context$runf.invoke(context.clj:40)
	at metabase.query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)
	at metabase.query_processor.reducible$identity_qp.invoke(reducible.clj:36)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___73849.invoke(cache.clj:229)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__67554.invoke(permissions.clj:140)
	at metabase.query_processor.middleware.enterprise$check_download_permissions_middleware$fn__73660.invoke(enterprise.clj:51)
	at metabase.query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__73670.invoke(enterprise.clj:64)
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__72812.invoke(mbql_to_native.clj:24)
	at metabase.query_processor$fn__75052$combined_post_process__75057$combined_post_process_STAR___75058.invoke(query_processor.clj:261)
	at metabase.query_processor$fn__75052$combined_pre_process__75053$combined_pre_process_STAR___75054.invoke(query_processor.clj:258)
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__67681.invoke(fetch_source_query.clj:299)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__73760$fn__73764.invoke(resolve_database_and_driver.clj:77)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:94)
	at metabase.driver$do_with_driver.invoke(driver.clj:89)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__73760.invoke(resolve_database_and_driver.clj:76)
	at metabase.query_processor.middleware.store$initialize_store$fn__68098$fn__68099.invoke(store.clj:14)
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150)
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150)
	at metabase.query_processor.middleware.store$initialize_store$fn__68098.invoke(store.clj:13)
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database$fn__73757.invoke(resolve_database_and_driver.clj:60)
	at metabase.query_processor.middleware.normalize_query$normalize$fn__74067.invoke(normalize_query.clj:38)
	at metabase.query_processor.middleware.enterprise$fn__73687$handle_audit_app_internal_queries__73688$fn__73690.invoke(enterprise.clj:96)
	at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__73698.invoke(enterprise.clj:103)
	at metabase.query_processor.middleware.constraints$add_default_userland_constraints$fn__70671.invoke(constraints.clj:81)
	at metabase.query_processor.middleware.process_userland_query$process_userland_query$fn__73998.invoke(process_userland_query.clj:156)
	at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__74596.invoke(catch_exceptions.clj:171)
	at metabase.query_processor.reducible$async_qp$qp_STAR___62528$thunk__62530.invoke(reducible.clj:126)
	at metabase.query_processor.reducible$async_qp$qp_STAR___62528$fn__62532.invoke(reducible.clj:131)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[...]

**To Reproduce**
I don't know how to repdroduce...

**Expected behavior**
The logs are being feeding with errors and the server eventually end up not displaying embedded dashboards after few days.
The message "this dashboard take longer than it should be ... (something like this, i have it in french here ) 

**Screenshots**
N/A

**Severity**
This is blocking the entire usage of metabase for users until the IT service restart the service on the Virtual Machine. So we have a work around but this is costing quite a time and annoying too :)

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9-post-Debian-1deb10u1",
    "java.vendor": "Debian",
    "java.vendor.url": "https://tracker.debian.org/openjdk-11",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9-post-Debian-1deb10u1",
    "os.name": "Linux",
    "os.version": "4.19.0-25-amd64",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "sqlserver",
      "oracle"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-14",
      "tag": "v0.48.0",
      "hash": "f985e19"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

**Comment by snoe** [comment]
It looks like this should be fixed by #37031
