### ISSUE TITLE
Bug creating custom map: "Something's gone wrong"

### ISSUE THREAD

**Issue by kait-stearns** [metabase/metabase#37715]
**Describe the bug**
 I'm trying to create a custom map from [this geojson file](https://raw.githubusercontent.com/kait-stearns/map-fIles/main/src/US_eGRID2021_subregions.json) and am getting the error "Something's gone wrong" when I try to load the file.

**Logs**

Please include javascript console:
```
analytics.js:24 Refused to load the script 'https://www.googletagmanager.com/gtag/js?id=G-29NY6M1W10&cx=c&_slc=1' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://maps.google.com https://accounts.google.com https://www.google-analytics.com   'sha256-K2AkR/jTLsGV8PyzWha7/ey1iaD9c5jWRYwa++ZlMZc=' 'sha256-ib2/2v5zC6gGM6Ety7iYgBUvpy/caRX9xV/pzzV7hf0=' 'sha256-isH538cVBUY8IMlGYGbWtBwr+cGqkc4mN6nLcA7lUjE='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Id @ analytics.js:24
2react-dom.production.min.js:209 TypeError: Cannot read properties of null (reading 'type')
    at mapping.js:19:26
    at u (mapping.js:6:18)
    at t.Z (LeafletChoropleth.jsx:13:19)
    at ta (react-dom.production.min.js:153:146)
    at xs (react-dom.production.min.js:261:496)
    at Sc (react-dom.production.min.js:246:265)
    at _c (react-dom.production.min.js:246:194)
    at gc (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
cs @ react-dom.production.min.js:209
Show 1 more frame
```
**To Reproduce**
1. Go to Admin > Settings > Maps
2. Click on "Add a map"
3. Enter a name, use `https://raw.githubusercontent.com/kait-stearns/map-fIles/main/src/US_eGRID2021_subregions.json` as URL
4. Click Load

**Expected behavior**
The map to load in preview.

**Screenshots**
Before pressing load:
![Screen Shot 2024-01-15 at 2 23 18 PM](https://github.com/metabase/metabase/assets/82038092/f6aaa285-ae11-42c3-a98a-d7c0892bf7db)

After pressing load:
![Screen Shot 2024-01-15 at 2 24 14 PM](https://github.com/metabase/metabase/assets/82038092/0f613717-d473-42e9-a858-82ac9a5b98fa)

**Severity**
Semi-urgent. Blocking completion of an important client-facing project (need to map some data by this type of region).

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.21+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.21",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.21+9",
    "os.name": "Linux",
    "os.version": "5.10.184-175.731.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mongo",
      "snowflake"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.5.4"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2023-12-01",
      "tag": "v1.47.9",
      "branch": "?",
      "hash": "d05b06e"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by adam-james-v** [comment]
I think how the error is handled in the app is indeed a bug. 

However, in this particular case there may be a legitimate problem with the provided .json.

Here's a screenshot of line 4995 in the provided json:

<img width="514" alt="image" src="https://github.com/metabase/metabase/assets/21064735/dd0d1ec2-1618-47c6-ab19-685495fe46e8">

If I edit a local copy of the json to just remove that feature with null geometry, and serve it locally, I'm able to load the custom map:


https://github.com/metabase/metabase/assets/21064735/fbed1976-6b89-4259-a936-f788ac94885d

If you're able to edit the json yourself, it might be worth trying to either remove the feature or otherwise add a polygon definition there. It might unblock you for the time being, even if it's not a proper fix to this bug yet.

**Comment by kait-stearns** [comment]
Awesome, thank you for catching this. I will update that element and let
you know if that fixes it.
Kaitlin

**Comment by cdeweyx** [comment]
Closing as unable to repro in v54
