### ISSUE TITLE
bigquery driver and jdk 8 fails

### ISSUE THREAD

**Issue by joermungandr** [metabase/metabase#3775]
Hi I am using a jdk 8 and cant initiliaze  metabase. It seems that the bigquery driver is causing this. Is it possible to skip this driver, or does anyone know how to fix this?

```
11-17 10:13:10 INFO metabase.util :: Loading Metabase...
11-17 10:13:19 INFO metabase.core :: Starting Metabase in STANDALONE mode
11-17 10:13:19 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

11-17 10:13:19 INFO metabase.core :: Starting Metabase version v0.21.0-snapshot ( ) ...
11-17 10:13:19 INFO metabase.core :: System timezone is 'GMT' ...
11-17 10:13:19 DEBUG metabase.driver :: Registered driver :postgres 🚚
11-17 10:13:19 DEBUG metabase.driver :: Registered driver :redshift 🚚
11-17 10:13:20 DEBUG metabase.driver :: Registered driver :mongo 🚚
11-17 10:13:20 DEBUG metabase.driver :: Registered driver :sqlite 🚚
11-17 10:13:20 DEBUG metabase.driver :: Registered driver :sqlserver 🚚
11-17 10:13:20 DEBUG metabase.driver :: Registered driver :h2 🚚
11-17 10:13:20 DEBUG metabase.driver :: Registered driver :crate 🚚
11-17 10:13:20 DEBUG metabase.driver :: Registered driver :druid 🚚
11-17 10:13:20 DEBUG metabase.driver :: Registered driver :googleanalytics 🚚
java.lang.NoClassDefFoundError: metabase/driver/bigquery$µs__GT_str
	at metabase.driver.bigquery__init.load(Unknown Source)
	at metabase.driver.bigquery__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at metabase.driver$find_and_load_drivers_BANG_.invokeStatic(driver.clj:276)
	at metabase.driver$find_and_load_drivers_BANG_.invoke(driver.clj:270)
	at metabase.core$init_BANG_.invokeStatic(core.clj:109)
	at metabase.core$init_BANG_.invoke(core.clj:93)
	at metabase.core$start_normally.invokeStatic(core.clj:196)
	at metabase.core$start_normally.invoke(core.clj:190)
	at metabase.core$_main.invokeStatic(core.clj:288)
	at metabase.core$_main.doInvoke(core.clj:283)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: metabase.driver.bigquery$µs__GT_str
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
11-17 10:13:20 ERROR metabase.core :: Metabase Initialization FAILED:  metabase/driver/bigquery$µs__GT_str
11-17 10:13:20 INFO metabase.core :: Metabase Shutting Down ...
11-17 10:13:20 INFO metabase.core :: Metabase Shutdown COMPLETE
```

**Comment by salsakran** [comment]
It looks like you're using a custom build. 

If you're planning on running this  (rather than helping develop Metabase), we'd strongly advise using one of our official builds at www.metabase.com/start

Have you followed the steps in https://github.com/metabase/metabase/blob/master/docs/developers-guide.md ?

**Comment by salsakran** [comment]
@joermungandr can you confirm you've followed the steps above? We're not able to re-pro this on my machine on java8.
