### ISSUE TITLE
Allow Metabase to work in other schemas other than public

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#37836]
**Is your feature request related to a problem? Please describe.**
Seems that we don't allow Metabase to work on any other schemas other than public due to a problem with migrations

If you use a connection string with currentSchema=some_other_schema (https://jdbc.postgresql.org/documentation/use/) Metabase will always try to initialize in the public schema

```
aused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v00.00-000::qnkhuat:
metabase-postgres            |      Reason: liquibase.exception.DatabaseException: ERROR: schema "public" does not exist [Failed SQL: (0) --
metabase-postgres            | -- Name: citext; Type: EXTENSION; Schema: -; Owner: -
metabase-postgres            | --
metabase-postgres            | 
metabase-postgres            | CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public]
metabase-postgres            | 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:123)
metabase-postgres            | 	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:102)
metabase-postgres            | 	at liquibase.Scope.lambda$child$0(Scope.java:194)
metabase-postgres            | 	at liquibase.Scope.child(Scope.java:203)
metabase-postgres            | 	at liquibase.Scope.child(Scope.java:193)
metabase-postgres            | 	at liquibase.Scope.child(Scope.java:172)
metabase-postgres            | 	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:99)
metabase-postgres            | 	at liquibase.command.CommandScope.execute(CommandScope.java:212)
metabase-postgres            | 	... 53 more
metabase-postgres            | Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v00.00-000::qnkhuat:
metabase-postgres            |      Reason: liquibase.exception.DatabaseException: ERROR: schema "public" does not exist [Failed SQL: (0) --
metabase-postgres            | -- Name: citext; Type: EXTENSION; Schema: -; Owner: -
metabase-postgres            | --
metabase-postgres            | 
metabase-postgres            | CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public]

```

**Describe the solution you'd like**
Allow Metabase to be able to live in other schemas other than public

**Describe alternatives you've considered**
None currently

**How important is this feature to you?**
Found this while going through other bugs

**Additional context**
NA

**Comment by JonCrawford** [comment]
This seems like a new behavior in v48. All of my company's analytics tables are in a non-`public` schema and now our BI tool is useless.

**Comment by paoliniluis** [comment]
@JonCrawford this is only for the application database

**Comment by JonCrawford** [comment]
> @JonCrawford this is only for the application database

Understood. There also seems to be another issue as stated. On Snowflake at least.

**Comment by paoliniluis** [comment]
yes, we're investigating that here: https://discourse.metabase.com/t/snowflake-broken-in-0-48-1/63849/41

**Comment by dosbol** [comment]
For postgres `currentSchema` works in metabase/metabase:v0.46.8 but not in 48(latest)

**Comment by qnkhuat** [comment]
the `resources/migrations/initialization/metabase_postgres.sql` file specifically creates tables in `public` table, we'll need to update this to be schema agnostic

**Comment by RiVerSZ** [comment]
i would like to upvote this as I would like to install metbase on a schema where i can install citext extension

**Comment by RiVerSZ** [comment]
hi @TyShkan thank you very much i will try our suggestion I will comment on monday

**Comment by RiVerSZ** [comment]
@TyShkan thank you it worked

**Comment by maxmarcon** [comment]
👍 for restoring the ability to create/update metabase application tables in a schema other than public. We also noticed that this stopped working when upgrading from `0.46.8` to `0.50.x` 😢 

The current behavior is:

* **inconsistent**: metabase still can use application tables in a schema other than public (by passing the `currentSchema` option), but it can't create/modify them there anymore
* **dangerous**: if a new version of metabase comes along that adds new migrations, and the current installation has tables installed in a schema other than public (as it's our case) the new migrations will fail (or, if they succeed, metabase won't be able to find the new tables later)

**Comment by mgohin** [comment]
Hi,

Any updates on this ?

We have non negociable constraints in prod to use a dedicated schema for Metabase in the same postgres DB as the application we connect Metabase to.

**Comment by paoliniluis** [comment]
> Hi,
> 
> Any updates on this ?
> 
> We have non negociable constraints in prod to use a dedicated schema for Metabase in the same postgres DB as the application we connect Metabase to.

Why not isolate in different databases ?

**Comment by mgohin** [comment]
> Why not isolate in different databases ?

==> `We have non negociable constraints in prod`, I don't chose, I use what is given to me and allowed 😅

**Comment by maxmarcon** [comment]
@mgohin we have the same situation and successfully worked around this issue by starting up metabase with the following script (as also suggested above by @TyShkan):

```bash
if [[ $METABASE_VERSION > "0.47.13" ]]; then
    # run the initial migrations using the latest metabase version whose initial migations were still schema-aware
    # note that this might fail if the way to compute checksums for the migration changes, but we don't care, all
    # we care about is that it's run the first time when the metabase schema is empty
    set +e
    java -jar metabase-v0.47.13.jar migrate up
    set -e
fi

# start metabase in the background, this will also run the remaining migrations
java -Xmx${METABASE_JVM_MAX_HEAP:-8g} -jar metabase.jar &
```

were `METABASE_VERSION` is your target metabase version. This works because the initial migrations were broken in `0.48` by some faulty refactoring (they were moved to a [folder](https://github.com/metabase/metabase/tree/master/resources/migrations/initialization) into separate files hard-coded public schema in them)

**Comment by mgohin** [comment]
Yes I read this workaround thanks, but I was “upping” this issue to get attention/news :)

**Comment by suryasanchez** [comment]
I using the following but still the migration script installs it in the _public_ schema, any tips?

`docker run -d -p 3000:3000 -e MB_DB_CONNECTION_URI="jdbc:postgresql://HOST:5432/postgres?user=USER&password=PASSWORD&currentSchema=metabase&sslmode=require" --name metabase metabase/metabase:v0.46.8`

**Comment by sneko** [comment]
As specified by @qnkhuat `./metabase/resources/migrations/initialization/metabase_postgres.sql` is a static file used for the initial setup. Everything inside is using the `public` schema. What I did to setup Metabase:

1. Copy the content of https://github.com/metabase/metabase/blob/master/resources/migrations/initialization/metabase_postgres.sql into a tool like `vscode`
2. Replace `public` by `myschema` on the line 5 managing schema creation
3. With your text editor, replace all occurences of `public.` by `myschema.`
4. Run the complete script by yourself on your database

On my side it seems to work. But honestly I had hard times finding the solution. Hopefully to me the DB user I made **had no access to the `public` schema**, otherwise Metabase would have polluted some other data... 😄 

The initial script could use custom command to adjust the SQL script on the fly? Or at least, if it detects in the connection URI `?currentSchema=XXX` not being `public`, it should throw an error so the user directly understand what are the risks, and what is the solution.

EDIT: just saw after the open PR https://github.com/metabase/metabase/pull/61607 ... maybe it could be the permanent solution if indeed it understands the `?currentSchema` and not using a default one 👍

**Comment by csi-mboero** [comment]
I'm facing the same issue. When using a PostgreSQL connection string with `currentSchema=<custom_schema>`, Metabase still runs all Liquibase migrations against the `public` schema, making it impossible to use a dedicated non-public schema for the application database.

Could the maintainers provide an estimated timeline for a definitive fix? Is there an active PR or milestone targeting this? Any workaround available in the meantime would also be greatly appreciated.

**Comment by dragonsahead** [comment]
@csi-mboero Marco, we evaluated the effort to make this happen and it's massive, we don't think we'll be able to make it happen soon

**Comment by csi-mboero** [comment]
The important thing is that Metabase has this issue on its roadmap to be fixed; once you have a timeline or plan, could you please share it? Thanks

**Comment by csi-mboero** [comment]
> [@csi-mboero](https://github.com/csi-mboero) Marco, we evaluated the effort to make this happen and it's massive, we don't think we'll be able to make it happen soon

hello, is there currently any plan to fix this issue? it would be very useful to know whether a fix is planned or if there is a recommended long-term workaround.

Thanks in advance for any update.

**Comment by dragonsahead** [comment]
It’s not on the short term roadmap
