### ISSUE TITLE
NPE in `metabase.driver.sync/schema-patterns->filter-fn*`

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#38156]
(The NPE seems to be when invoking the function it returns)

Reported here on Discourse

https://discourse.metabase.com/t/snowflake-broken-in-0-48-1/63849/39

This is almost certainly causing problems with sync. We should look into the code and try to work out which situations might cause an NPE and add some safeguards against it

```
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
	at java.base/java.util.regex.Matcher.reset(Unknown Source)
	at java.base/java.util.regex.Matcher.<init>(Unknown Source)
	at java.base/java.util.regex.Pattern.matcher(Unknown Source)
	at metabase.driver.sync$schema_patterns__GT_filter_fn_STAR_$fn__80810.invoke(sync.clj:45)
	at metabase.driver.sync$include_schema_QMARK_.invokeStatic(sync.clj:76)
	at metabase.driver.sync$include_schema_QMARK_.invoke(sync.clj:66)
	at metabase.driver.snowflake$fn__128206$fn__128207$fn__128211$fn__128213.invoke(snowflake.clj:433)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2822)
	at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1205)
	at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1197)
	at clojure.java.jdbc$reducible_result_set_STAR_$reify__28159.reduce(jdbc.clj:1227)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$reduce.invoke(core.clj:6868)
	at clojure.java.jdbc$query_reducer$fn__28165$fn__28168.invoke(jdbc.clj:1262)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1091)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1106)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$reducible_query$reify__28182.reduce(jdbc.clj:1357)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core$into.invokeStatic(core.clj:6962)
	at clojure.core$into.invoke(core.clj:6950)
	at metabase.driver.snowflake$fn__128206$fn__128207$fn__128211.invoke(snowflake.clj:429)
	at metabase.driver.sql_jdbc.execute$fn__78692$fn__78693.invoke(execute.clj:388)
	at metabase.driver.sql_jdbc.execute$fn__78657$_AMPERSAND_f__78658.invoke(execute.clj:334)
	at metabase.driver.sql_jdbc.execute$fn__78657$fn__78661.invoke(execute.clj:317)
	at metabase.driver.sql_jdbc.execute$fn__78692.invokeStatic(execute.clj:382)
	at metabase.driver.sql_jdbc.execute$fn__78692.invoke(execute.clj:380)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.snowflake$fn__128206$fn__128207.invoke(snowflake.clj:421)
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150)
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150)
	at metabase.driver.snowflake$fn__128206.invokeStatic(snowflake.clj:418)
	at metabase.driver.snowflake$fn__128206.invoke(snowflake.clj:414)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.sync.fetch_metadata$fn__81252$_AMPERSAND_f__81253.invoke(fetch_metadata.clj:15)
	at metabase.sync.fetch_metadata$fn__81252$fn__81255.invoke(fetch_metadata.clj:12)
	at metabase.sync.sync_metadata$fn__82263$_AMPERSAND_f__82264.invoke(sync_metadata.clj:61)
	at metabase.sync.sync_metadata$fn__82263$fn__82268.invoke(sync_metadata.clj:58)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invokeStatic(sync_databases.clj:94)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invoke(sync_databases.clj:77)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:113)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:101)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:118)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[850a5ce0-29ca-4397-b800-6e8127f2a0c4] 2024-01-17T09:16:08-08:00 ERROR org.quartz.core.ErrorLogger Job (DEFAULT.metabase.task.sync-and-analyze.job threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
	at java.base/java.util.regex.Matcher.reset(Unknown Source)
	at java.base/java.util.regex.Matcher.<init>(Unknown Source)
	at java.base/java.util.regex.Pattern.matcher(Unknown Source)
	at metabase.driver.sync$schema_patterns__GT_filter_fn_STAR_$fn__80810.invoke(sync.clj:45)
	at metabase.driver.sync$include_schema_QMARK_.invokeStatic(sync.clj:76)
	at metabase.driver.sync$include_schema_QMARK_.invoke(sync.clj:66)
	at metabase.driver.snowflake$fn__128206$fn__128207$fn__128211$fn__128213.invoke(snowflake.clj:433)
	at clojure.core$filter$fn__5958$fn__5959.invoke(core.clj:2822)
	at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1205)
	at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1197)
	at clojure.java.jdbc$reducible_result_set_STAR_$reify__28159.reduce(jdbc.clj:1227)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$reduce.invoke(core.clj:6868)
	at clojure.java.jdbc$query_reducer$fn__28165$fn__28168.invoke(jdbc.clj:1262)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1091)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1106)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$reducible_query$reify__28182.reduce(jdbc.clj:1357)
	at clojure.core$transduce.invokeStatic(core.clj:6946)
	at clojure.core$into.invokeStatic(core.clj:6962)
	at clojure.core$into.invoke(core.clj:6950)
	at metabase.driver.snowflake$fn__128206$fn__128207$fn__128211.invoke(snowflake.clj:429)
	at metabase.driver.sql_jdbc.execute$fn__78692$fn__78693.invoke(execute.clj:388)
	at metabase.driver.sql_jdbc.execute$fn__78657$_AMPERSAND_f__78658.invoke(execute.clj:334)
	at metabase.driver.sql_jdbc.execute$fn__78657$fn__78661.invoke(execute.clj:317)
	at metabase.driver.sql_jdbc.execute$fn__78692.invokeStatic(execute.clj:382)
	at metabase.driver.sql_jdbc.execute$fn__78692.invoke(execute.clj:380)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.snowflake$fn__128206$fn__128207.invoke(snowflake.clj:421)
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150)
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150)
	at metabase.driver.snowflake$fn__128206.invokeStatic(snowflake.clj:418)
	at metabase.driver.snowflake$fn__128206.invoke(snowflake.clj:414)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.sync.fetch_metadata$fn__81252$_AMPERSAND_f__81253.invoke(fetch_metadata.clj:15)
	at metabase.sync.fetch_metadata$fn__81252$fn__81255.invoke(fetch_metadata.clj:12)
	at metabase.sync.sync_metadata$fn__82263$_AMPERSAND_f__82264.invoke(sync_metadata.clj:61)
	at metabase.sync.sync_metadata$fn__82263$fn__82268.invoke(sync_metadata.clj:58)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invokeStatic(sync_databases.clj:94)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invoke(sync_databases.clj:77)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:113)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:101)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:118)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
```

**Comment by camsaul** [comment]
Marking as P1 because this could potentially complete break sync and setup

**Comment by camsaul** [comment]
Sounds like someone else probably ran into it too https://discourse.metabase.com/t/snowflake-broken-in-0-48-1/63849/32

**Comment by camsaul** [comment]
You can repro this exact NPE as follows with the code from line 45:

```clj
(.matcher #"\s+" nil)
```

```
1. Unhandled java.lang.NullPointerException
   (No message)

              Matcher.java: 1770  java.util.regex.Matcher/getTextLength
              Matcher.java:  416  java.util.regex.Matcher/reset
              Matcher.java:  253  java.util.regex.Matcher/<init>
              Pattern.java: 1133  java.util.regex.Pattern/matcher
                      REPL:    6  metabase.driver.sync/eval229672
```

**Comment by camsaul** [comment]
Steps to repro:

```clj
(let [patterns (metabase.driver.sync/db-details->schema-filter-patterns
                {:engine  :snowflake
                 :details {:schema-filters-type     "inclusion"
                           :schema-filters-patterns "x"}})
      f        (apply metabase.driver.sync/schema-patterns->filter-fn patterns)]
  (f nil))
```

**or**

```clj
(let [db {:details {:schema-filters-type "inclusion"
                    :schema-filters-patterns "x"}
          :engine :snowflake}]
  (metabase.driver.sync/include-schema? db nil))
  ```
  
  So this only works for DB details that have either `inclusion` or `exclusion` schema filter options, and it only happens if the `schema` passed in is `nil`. It's an open question why a schema would come back as `nil` tho
