### ISSUE TITLE
Getting errors in the truncate log task Caused by: java.lang.ClassNotFoundException: metabase.task.truncate_audit_log.TruncateAuditLog

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#38235]
### Describe the bug

Seems that something is not there and the task is generating an error

### To Reproduce

Don't know how to reproduce, seeing this in our cloud

### Logs

```
2024-01-29 17:52:51.734	
	... 52 more
2024-01-29 17:52:51.734	
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1390)
2024-01-29 17:52:51.734	
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:852)
2024-01-29 17:52:51.734	
	at metabase.task.ClassLoadHelper.loadClass(task.clj:128)
2024-01-29 17:52:51.734	
	at metabase.task$load_class.invoke(task.clj:117)
2024-01-29 17:52:51.734	
	at metabase.task$load_class.invokeStatic(task.clj:118)
2024-01-29 17:52:51.734	
	at java.base/java.lang.Class.forName(Unknown Source)
2024-01-29 17:52:51.734	
	at java.base/java.lang.Class.forName0(Native Method)
2024-01-29 17:52:51.734	
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
2024-01-29 17:52:51.734	
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
2024-01-29 17:52:51.734	
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
2024-01-29 17:52:51.734	
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
2024-01-29 17:52:51.734	
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
2024-01-29 17:52:51.734	
Caused by: java.lang.ClassNotFoundException: metabase.task.truncate_audit_log.TruncateAuditLog
2024-01-29 17:52:51.734	
	at java.base/java.lang.Thread.run(Unknown Source)
2024-01-29 17:52:51.734	
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2024-01-29 17:52:51.734	
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2024-01-29 17:52:51.734	
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2024-01-29 17:52:51.734	
	at clojure.lang.AFn.call(AFn.java:18)
2024-01-29 17:52:51.734	
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
2024-01-29 17:52:51.734	
	at ring.util.io$piped_input_stream$fn__242.invoke(io.clj:28)
2024-01-29 17:52:51.734	
	at metabase.server.middleware.json$streamed_json_response$fn__45314.invoke(json.clj:83)
2024-01-29 17:52:51.734	
	at cheshire.core$generate_stream.invoke(core.clj:81)
2024-01-29 17:52:51.734	
	at cheshire.core$generate_stream.invokeStatic(core.clj:106)
2024-01-29 17:52:51.734	
	at cheshire.generate$generate.invoke(generate.clj:119)
2024-01-29 17:52:51.734	
	at cheshire.generate$generate.invokeStatic(generate.clj:125)
2024-01-29 17:52:51.734	
	at clojure.core$reduce.invoke(core.clj:6868)
2024-01-29 17:52:51.734	
	at clojure.core$reduce.invokeStatic(core.clj:6886)
2024-01-29 17:52:51.734	
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
2024-01-29 17:52:51.734	
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
2024-01-29 17:52:51.734	
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
2024-01-29 17:52:51.734	
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
2024-01-29 17:52:51.734	
	at cheshire.generate$generate$fn__4050.invoke(generate.clj:125)
2024-01-29 17:52:51.734	
	at cheshire.generate$generate.invoke(generate.clj:119)
2024-01-29 17:52:51.734	
	at cheshire.generate$generate.invokeStatic(generate.clj:133)
2024-01-29 17:52:51.734	
	at clojure.core$reduce.invoke(core.clj:6868)
2024-01-29 17:52:51.734	
	at clojure.core$reduce.invokeStatic(core.clj:6886)
2024-01-29 17:52:51.734	
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
2024-01-29 17:52:51.734	
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
2024-01-29 17:52:51.734	
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
2024-01-29 17:52:51.734	
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
2024-01-29 17:52:51.734	
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
2024-01-29 17:52:51.734	
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
2024-01-29 17:52:51.734	
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:169)
2024-01-29 17:52:51.734	
	at clojure.core$next__5451.invokeStatic(core.clj:64)
2024-01-29 17:52:51.734	
	at clojure.lang.RT.next(RT.java:713)
2024-01-29 17:52:51.734	
	at clojure.lang.Cons.next(Cons.java:39)
2024-01-29 17:52:51.734	
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
2024-01-29 17:52:51.734	
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
2024-01-29 17:52:51.734	
	at clojure.core$filter$fn__5962.invoke(core.clj:2826)
2024-01-29 17:52:51.734	
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
2024-01-29 17:52:51.734	
	at clojure.lang.RT.seq(RT.java:535)
2024-01-29 17:52:51.734	
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
2024-01-29 17:52:51.734	
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
2024-01-29 17:52:51.734	
	at clojure.core$map$fn__5935.invoke(core.clj:2772)
2024-01-29 17:52:51.734	
	at metabase.task$job_info.invoke(task.clj:282)
2024-01-29 17:52:51.734	
	at metabase.task$job_info.invokeStatic(task.clj:290)
2024-01-29 17:52:51.734	
	at clojurewerkz.quartzite.scheduler$get_job.invoke(scheduler.clj:185)
2024-01-29 17:52:51.734	
	at clojurewerkz.quartzite.scheduler$get_job.invokeStatic(scheduler.clj:188)
2024-01-29 17:52:51.734	
	at org.quartz.impl.StdScheduler.getJobDetail(StdScheduler.java:498)
2024-01-29 17:52:51.734	
	at org.quartz.core.QuartzScheduler.getJobDetail(QuartzScheduler.java:1493)
2024-01-29 17:52:51.734	
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1379)
2024-01-29 17:52:51.734	
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeWithoutLock(JobStoreSupport.java:3800)
2024-01-29 17:52:51.734	
	at org.quartz.impl.jdbcjobstore.JobStoreTX.executeInLock(JobStoreTX.java:93)
2024-01-29 17:52:51.734	
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)
2024-01-29 17:52:51.734	
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$9.execute(JobStoreSupport.java:1382)
2024-01-29 17:52:51.734	
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1393)
2024-01-29 17:52:51.734	
org.quartz.JobPersistenceException: Couldn't retrieve job because a required class was not found: metabase.task.truncate_audit_log.TruncateAuditLog [See nested exception: java.lang.ClassNotFoundException: metabase.task.truncate_audit_log.TruncateAuditLog]
2024-01-29 17:52:51.734	
2024-01-29 17:52:51,733 WARN metabase.task :: Error fetching details for Quartz Job: metabase.task.truncate-audit-log.job
```

### Information about your Metabase installation

```JSON
v48.x
```

### Severity

P2

**Comment by paoliniluis** [comment]
This error comes from https://github.com/metabase/metabase/issues/38234

**Comment by ipeevski** [comment]
For me, it is not related to #38234 
I think it happens every time it tries to run the `metabase.task.truncate-audit-log.job` job
Same trace as above (in reverse order)

**Comment by ligol** [comment]
I'm also experiencing this issue on an updated version of metabase, any more info on it?

**Comment by rudo-ro** [comment]
upgrading from 0.46.6.4 to 0.48.7  on aws ecs and seeing this same error resulting in failed startup.

**Comment by rudo-ro** [comment]
thanks @noahmoss , on our setup this is causing a shutdown of metabase preventing us from upgrading to `0.48.7`

**Comment by rudo-ro** [comment]
ahh okay so if someone logs in before some time, the ecs task survives despite the error. we were seeing the task sigterm exit out after that failure prior to user login. @noahmoss

**Comment by rudo-ro** [comment]
any update on this bug @noahmoss ?

**Comment by noahmoss** [comment]
@rudo-ro Sorry for the delay in addressing this. It should be resolved by https://github.com/metabase/metabase/pull/40649 in an upcoming release.

In the meantime, is this still blocking you from upgrading? That's surprising to me. What exact error are you seeing?

**Comment by noahmoss** [comment]
@rudo-ro Please upgrade to 49.2 which has just been released

**Comment by rudo-ro** [comment]
thanks @noahmoss, this should resolve our issue. we will implement in an upcoming sprint.

are there any known issues directly upgrading from `0.46.6.4` to `0.49.2`? particularly thinking with regards to skipping major versions. thanks!

**Comment by noahmoss** [comment]
@rudo-ro No, you should be able to upgrade directly!
