### ISSUE TITLE
Error while migrating load-from-h2 Java Memory errors after "transfering instancs of Activity"

### ISSUE THREAD

**Issue by obaqueiro** [metabase/metabase#3859]
- Your operating system: (e.x. OS X 10, Windows XP, etc)
**OSX 10.11 (El Capitan)**
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
   **2 MySQL databases**
- Metabase version: (e.x. 0.19.3)
  **20.3**
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
**Mac OSX jar file**
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
**H2**

- *Repeatable steps to reproduce the issue*
` export "JAVA_OPTS=-Xmx2048m -XX:MaxPermSize=2048m -XX:-UseGCOverheadLimit -Xmx2g -Xms2g"`
`java -jar metabase.jar load-from-h2`

I am trying to migrate a 1.7GB h2 database into MySQL.  Everything seems fine, but once the migration gets to the point of "Transfering N instances of Activity." I keep getting out-of-memory errors  (after 10 minute of high intensity CPU use).

After several tries, I have increased Java memory options, running Metabase with:
``` 
export "JAVA_OPTS=-Xmx2048m -XX:MaxPermSize=2048m -XX:-UseGCOverheadLimit -Xmx2g -Xms2g" 
```

However I keep getting this error:
```
/tmp/metabase$ java -jar metabase.jar load-from-h2
12-03 19:35:38 INFO metabase.util :: Loading Metabase...
12-03 19:35:44 INFO metabase.db :: Verifying mysql Database Connection ...
12-03 19:35:44 DEBUG metabase.driver :: Registered driver :mysql 🚚
12-03 19:35:44 INFO metabase.db :: Verify Database Connection ... ✅
12-03 19:35:44 INFO metabase.db :: Running Database Migrations...
Sat Dec 03 19:35:44 CST 2016 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
12-03 19:35:44 INFO metabase.db :: Setting up Liquibase...
12-03 19:35:44 INFO metabase.db :: Liquibase is ready.
12-03 19:35:44 INFO metabase.db :: Checking if Database has unran migrations...
12-03 19:36:03 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-03 19:36:03 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-03 19:36:03 INFO metabase.db :: Database has unran migrations. Waiting for migration lock to be cleared...
12-03 19:36:03 INFO metabase.db :: Migration lock is cleared. Running migrations...
12-03 19:36:03 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-03 19:36:03 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
12-03 19:36:23 INFO metabase.db :: Database Migrations Current ... ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
Sat Dec 03 19:36:23 CST 2016 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Temporarily disabling DB constraints...
[OK]
Transfering 2 instances of Database....[OK]
Transfering 178 instances of RawTable....[OK]
Transfering 2078 instances of RawColumn..........[OK]
Transfering 44 instances of User....[OK]
Transfering 14 instances of Setting....[OK]
Transfering 178 instances of Table....[OK]
Transfering 2078 instances of Field..........[OK]
Transfering 428 instances of FieldValues.....[OK]
Transfering 3012 instances of Revision..............[OK]
Transfering 218032 instances of ViewLog..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................[OK]
Transfering 362 instances of Session.....[OK]
Transfering 35 instances of Dashboard....[OK]
Transfering 711 instances of Card......[OK]
Transfering 14 instances of CardFavorite....[OK]
Transfering 271 instances of DashboardCard....[OK]
Transfering 2 instances of DashboardCardSeries....[OK]
Transfering 2197 instances of Activity...........[OK]
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at clojure.lang.ChunkedCons.next(ChunkedCons.java:42)
	at clojure.lang.RT.next(RT.java:688)
	at clojure.core$next__4341.invokeStatic(core.clj:64)
	at clojure.core$zipmap.invokeStatic(core.clj:2970)
	at clojure.core$zipmap.invoke(core.clj:2962)
	at clojure.java.jdbc$result_set_seq$thisfn__2670.invoke(jdbc.clj:411)
	at clojure.java.jdbc$result_set_seq$thisfn__2670$fn__2671.invoke(jdbc.clj:411)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$map$fn__4785.invoke(core.clj:2637)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:688)
	at clojure.core$next__4341.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3033)
	at clojure.core$doall.invokeStatic(core.clj:3039)
	at clojure.core$doall.invoke(core.clj:3039)
	at clojure.java.jdbc$query$fn__2768$fn__2769.invoke(jdbc.clj:877)
	at clojure.java.jdbc$query$fn__2768.invoke(jdbc.clj:876)
	at clojure.java.jdbc$db_query_with_resultset$run_query_with_params__2761.invoke(jdbc.clj:832)
	at clojure.java.jdbc$db_query_with_resultset.invokeStatic(jdbc.clj:847)
	at clojure.java.jdbc$db_query_with_resultset.invoke(jdbc.clj:818)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:874)
	at clojure.java.jdbc$query.invoke(jdbc.clj:854)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:867)
	at clojure.java.jdbc$query.invoke(jdbc.clj:854)
	at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:139)
	at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:136)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__31435.invoke(load_from_h2.clj:211)
Command failed with exception: GC overhead limit exceeded
```

**Comment by camsaul** [comment]
@obaqueiro your H2 database is 1.7GB? 😳 😳 😳 😳  I think that's by far the biggest H2 database file I've ever heard of.

Any reason you're setting all those memory limits for the JVM? As the error message suggests Metabase is running out of memory. For such a large H2 DB you might need to raise those limits a little in order to transfer the data out of there.

**Comment by camsaul** [comment]
@obaqueiro ?

**Comment by camsaul** [comment]
@obaqueiro It looks like you're setting `-Xmx` twice. Also `256m` is more than enough for `MaxPermSize` too, you don't need to give it `2g`. It's probably not a good idea to set `MaxPermSize` to the same size as the overall memory limit

Since we haven't heard back in a year or so I'm going to go ahead and close this out. If you're still having issues please feel free to open a new issue
