### ISSUE TITLE
Manually choosing Axis in chart settings will break subscription

### ISSUE THREAD

**Issue by ignacio-mb** [metabase/metabase#38839]
### Describe the bug

If you manually change a Y-axis position for an aggregation, the subscription of that chart will break

### To Reproduce

1. Create a GUI or SQL question, Orders, Count of rows and aggregate by Created At and Category\
2. Now add the two aggregations to the series breakout if they are not already there
3. On the Data tab in Viz Settings of the question, manually change the Y-axis position of all categories to be Right
<img width="469" alt="Screenshot 2024-04-08 at 2 35 55 PM" src="https://github.com/metabase/metabase/assets/132273646/81560046-1406-46d0-bc43-c7e44771cf39">

4. Set "Split y-axis when necessary" Toggle to off
5. Add to a dashboard, create an email subscription, and see that the subscription will fail with error: An error occurred while displaying this card. Logs below
<img width="579" alt="Screenshot 2024-04-08 at 2 36 47 PM" src="https://github.com/metabase/metabase/assets/132273646/6c5b7013-9745-4146-a4a0-6a953061e14f">

If you have the Y-axis to Auto, it will show correctly. But It's kind of annoying because if you have two aggregations if in the chart is set to Auto and puts the aggregations to the right, in the subscription they will appear one on the right and one on the left. Flagging as P2 as there is no workaround

### Expected behavior

should not break the subscription

### Logs

<details>
<summary>Logs</summary>
[328909f9-2595-4a0d-b1dd-59d7bb64ddab] 2024-02-15T20:49:06-03:00 ERROR metabase.pulse.render Pulse card render error
org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
file:///fake.svg:-1
The attribute "y" of the element <rect> is invalid
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:228)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158)
	at metabase.pulse.render.js_svg$render_svg.invokeStatic(js_svg.clj:108)
	at metabase.pulse.render.js_svg$render_svg.invoke(js_svg.clj:97)
	at metabase.pulse.render.js_svg$svg_string__GT_bytes.invokeStatic(js_svg.clj:112)
	at metabase.pulse.render.js_svg$svg_string__GT_bytes.invoke(js_svg.clj:111)
	at metabase.pulse.render.js_svg$combo_chart.invokeStatic(js_svg.clj:141)
	at metabase.pulse.render.js_svg$combo_chart.invoke(js_svg.clj:133)
	at metabase.pulse.render.body$lab_image_bundle.invokeStatic(body.clj:841)
	at metabase.pulse.render.body$lab_image_bundle.invoke(body.clj:816)
	at metabase.pulse.render.body$fn__74020$render__74008__74025$fn__74026.invoke(body.clj:860)
	at metabase.pulse.render.body$fn__74020$render__74008__74025.invoke(body.clj:858)
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
	at metabase.pulse.render$fn__74764$render_pulse_card_body__74769$fn__74773.invoke(render.clj:138)
	at metabase.pulse.render$fn__74764$render_pulse_card_body__74769.invoke(render.clj:128)
	at metabase.pulse.render$fn__74804$render_pulse_card__74809$fn__74810.invoke(render.clj:167)
	at metabase.pulse.render$fn__74804$render_pulse_card__74809.invoke(render.clj:149)
	at metabase.pulse.render$fn__74836$render_pulse_section__74841$fn__74845$fn__74848.invoke(render.clj:199)
	at metabase.pulse.render$fn__74836$render_pulse_section__74841$fn__74845.invoke(render.clj:197)
	at metabase.pulse.render$fn__74836$render_pulse_section__74841.invoke(render.clj:194)
	at metabase.email.messages$render_part.invokeStatic(messages.clj:442)
	at metabase.email.messages$render_part.invoke(messages.clj:438)
	at metabase.email.messages$render_message_body$fn__75903$fn__75904.invoke(messages.clj:495)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at metabase.email.messages$render_message_body$fn__75903.invoke(messages.clj:495)
	at metabase.email.messages$render_message_body.invokeStatic(messages.clj:494)
	at metabase.email.messages$render_message_body.invoke(messages.clj:492)
	at metabase.email.messages$render_pulse_email.invokeStatic(messages.clj:521)
	at metabase.email.messages$render_pulse_email.invoke(messages.clj:518)
	at metabase.pulse$fn__101942.invokeStatic(pulse.clj:431)
	at metabase.pulse$fn__101942.invoke(pulse.clj:420)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.pulse$parts__GT_notifications$iter__102016__102020$fn__102021$fn__102022.invoke(pulse.clj:502)
	at metabase.pulse$parts__GT_notifications$iter__102016__102020$fn__102021.invoke(pulse.clj:500)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$seq__5467.invoke(core.clj:139)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:555)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:554)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:582)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:563)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.api.pulse$fn__102950.invokeStatic(pulse.clj:322)
	at metabase.api.pulse$fn__102950.invoke(pulse.clj:308)
	at compojure.core$wrap_response$fn__43939.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__43923.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__43928.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__43932.invoke(core.clj:151)
	at clojure.lang.Var.invoke(Var.java:393)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43932.invoke(core.clj:153)
	at clojure.lang.Var.invoke(Var.java:393)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43932.invoke(core.clj:153)
	at clojure.lang.Var.invoke(Var.java:393)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43932.invoke(core.clj:153)
	at clojure.lang.Var.invoke(Var.java:393)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43932.invoke(core.clj:152)
	at clojure.lang.Var.invoke(Var.java:393)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__95771.invoke(auth.clj:17)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951.invoke(core.clj:200)
	at compojure.core$make_context$handler__43979.invoke(core.clj:290)
	at compojure.core$make_context$fn__43983.invoke(core.clj:300)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:199)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:199)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951.invoke(core.clj:200)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:199)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951.invoke(core.clj:200)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951.invoke(core.clj:200)
	at metabase.api.routes$fn__103512$fn__103513.invoke(routes.clj:64)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__103675$fn__103676.doInvoke(routes.clj:72)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951.invoke(core.clj:200)
	at compojure.core$make_context$handler__43979.invoke(core.clj:290)
	at compojure.core$make_context$fn__43983.invoke(core.clj:300)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43932.invoke(core.clj:153)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43932.invoke(core.clj:153)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43932.invoke(core.clj:153)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:199)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:199)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:199)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951.invoke(core.clj:200)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951.invoke(core.clj:200)
	at compojure.core$make_context$handler__43979.invoke(core.clj:290)
	at compojure.core$make_context$fn__43983.invoke(core.clj:300)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951$f__43952$respond_SINGLEQUOTE___43953.invoke(core.clj:197)
	at compojure.core$make_context$fn__43983.invoke(core.clj:301)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951.invoke(core.clj:200)
	at compojure.core$routes$fn__43951$f__43952.invoke(core.clj:198)
	at compojure.core$routes$fn__43951.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__100576.invoke(exceptions.clj:108)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__100573.invoke(exceptions.clj:96)
	at metabase.server.middleware.log$log_api_call$fn__105658$fn__105659$fn__105660.invoke(log.clj:216)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12)
	at metabase.server.middleware.log$log_api_call$fn__105658$fn__105659.invoke(log.clj:208)
	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112)
	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103)
	at metabase.server.middleware.log$log_api_call$fn__105658.invoke(log.clj:207)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__110430.invoke(browser_cookie.clj:40)
	at metabase.server.middleware.security$add_security_headers$fn__86432.invoke(security.clj:180)
	at metabase.server.middleware.json$wrap_json_body$fn__45312.invoke(json.clj:67)
	at metabase.server.middleware.offset_paging$handle_paging$fn__86456.invoke(offset_paging.clj:45)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__45330.invoke(json.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__110697.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__110716.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__66189.invoke(misc.clj:61)
	at metabase.server.middleware.session$reset_session_timeout$fn__72224.invoke(session.clj:488)
	at metabase.server.middleware.session$bind_current_user$fn__72190$fn__72191.invoke(session.clj:383)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:362)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:346)
	at metabase.server.middleware.session$bind_current_user$fn__72190.invoke(session.clj:382)
	at metabase.server.middleware.session$wrap_current_user_info$fn__72173.invoke(session.clj:321)
	at metabase.server.middleware.session$wrap_session_id$fn__72156.invoke(session.clj:253)
	at metabase.server.middleware.auth$wrap_api_key$fn__95779.invoke(auth.clj:30)
	at ring.middleware.cookies$wrap_cookies$fn__110617.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__66171.invoke(misc.clj:29)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__66197.invoke(misc.clj:78)
	at ring.middleware.gzip$wrap_gzip$fn__110659.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__66200.invoke(misc.clj:95)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__110446.invoke(ssl.clj:51)
	at metabase.server$async_proxy_handler$fn__66374.invoke(server.clj:78)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.batik.bridge.BridgeException: file:///fake.svg:-1 

</details>

### Information about your Metabase installation

```JSON
- 48.5
```

### Severity

p2

### Additional context

e-charts scope?

**Comment by ignacio-mb** [comment]
@perivamsi would this be in the `echarts-scope`?

**Comment by perivamsi** [comment]
@adam-james-v can you please take a look?
