### ISSUE TITLE
Charts that Render via GUI Fail to Render in Subscriptions

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#39178]
### Describe the bug

If a data source has NULL dates you can still group by date to render a visualization (like a bar or line chart) but the same viz fails when sent via subscription.

### To Reproduce

1. Create test SQL question with NULL date:

(SELECT
  "PUBLIC"."orders"."id" AS "id",
  "PUBLIC"."orders"."created_at" AS "created_at",
  "PUBLIC"."orders"."quantity" AS "quantity"
FROM
  "v3_sample-dataset"."PUBLIC"."orders"
LIMIT 10)
UNION
(SELECT
  "PUBLIC"."orders"."id" AS "id",
  null AS "created_at",
  "PUBLIC"."orders"."quantity" AS "quantity"
FROM
  "v3_sample-dataset"."PUBLIC"."orders"
  LIMIT 10)
  
2. Create a bar chart (or line, area or combo chart) from the question, group by date and save to a dashboard
3. Send an email subscription from the dashboard

The email will deliver but in place of the chart you'll see, "An error occurred while displaying this card".

### Expected behavior

If the chart can be visualized in Metabase we should be able to successfully deliver a version of it via subscription.

### Logs

[ac89de1d-232c-4de3-beef-54edb2cab0a7] 2024-02-26T13:55:47-06:00 DEBUG metabase.server.middleware.log GET /api/pulse 200 10.9 ms (1 DB calls) App DB connections: 2/10 Jetty threads: 7/50 (3 idle, 0 queued) (126 total active threads) Queries in flight: 0 (0 queued)
[ac89de1d-232c-4de3-beef-54edb2cab0a7] 2024-02-26T13:55:47-06:00 DEBUG metabase.server.middleware.log GET /api/user/recipients 200 14.4 ms (2 DB calls) App DB connections: 1/10 Jetty threads: 6/50 (3 idle, 0 queued) (126 total active threads) Queries in flight: 0 (0 queued)
[ac89de1d-232c-4de3-beef-54edb2cab0a7] 2024-02-26T13:55:51-06:00 ERROR metabase.pulse.render Pulse card render error
RangeError: Provided date is not in valid range.
	at <js> uM(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:46:3265920-3265935)
	at <js> :=>(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:46:3266147-3266153)
	at <js> ub(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:46:3266046-3266158)
	at <js> im(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:46:3284411-3284427)
	at <js> :=>(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:46:3284700-3284724)
	at <js> iw(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:46:3284669-3284739)
	at <js> aF(file:/app/metabase.jar!/frontend_client/app/dist/lib-static-viz.bundle.js:46:3300929-3300959)
	at org.graalvm.polyglot.Value.execute(Value.java:880)
	at metabase.pulse.render.js_engine$execute_fn_name.invokeStatic(js_engine.clj:52)
	at metabase.pulse.render.js_engine$execute_fn_name.doInvoke(js_engine.clj:46)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at metabase.pulse.render.js_svg$combo_chart.invokeStatic(js_svg.clj:142)
	at metabase.pulse.render.js_svg$combo_chart.invoke(js_svg.clj:133)
	at metabase.pulse.render.body$lab_image_bundle.invokeStatic(body.clj:841)
	at metabase.pulse.render.body$lab_image_bundle.invoke(body.clj:816)
	at metabase.pulse.render.body$fn__73048$render__73036__73053$fn__73054.invoke(body.clj:860)
	at metabase.pulse.render.body$fn__73048$render__73036__73053.invoke(body.clj:858)
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
	at metabase.pulse.render$fn__73792$render_pulse_card_body__73797$fn__73801.invoke(render.clj:138)
	at metabase.pulse.render$fn__73792$render_pulse_card_body__73797.invoke(render.clj:128)
	at metabase.pulse.render$fn__73832$render_pulse_card__73837$fn__73838.invoke(render.clj:167)
	at metabase.pulse.render$fn__73832$render_pulse_card__73837.invoke(render.clj:149)
	at metabase.pulse.render$fn__73864$render_pulse_section__73869$fn__73873$fn__73876.invoke(render.clj:199)
	at metabase.pulse.render$fn__73864$render_pulse_section__73869$fn__73873.invoke(render.clj:197)
	at metabase.pulse.render$fn__73864$render_pulse_section__73869.invoke(render.clj:194)
	at metabase.email.messages$render_part.invokeStatic(messages.clj:442)
	at metabase.email.messages$render_part.invoke(messages.clj:438)
	at metabase.email.messages$render_message_body$fn__74906$fn__74907.invoke(messages.clj:495)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at metabase.email.messages$render_message_body$fn__74906.invoke(messages.clj:495)
	at metabase.email.messages$render_message_body.invokeStatic(messages.clj:494)
	at metabase.email.messages$render_message_body.invoke(messages.clj:492)
	at metabase.email.messages$render_pulse_email.invokeStatic(messages.clj:521)
	at metabase.email.messages$render_pulse_email.invoke(messages.clj:518)
	at metabase.pulse$fn__100077.invokeStatic(pulse.clj:431)
	at metabase.pulse$fn__100077.invoke(pulse.clj:420)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.pulse$parts__GT_notifications$iter__100151__100155$fn__100156$fn__100157.invoke(pulse.clj:502)
	at metabase.pulse$parts__GT_notifications$iter__100151__100155$fn__100156.invoke(pulse.clj:500)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$seq__5467.invoke(core.clj:139)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:555)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:554)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:582)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:563)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.api.pulse$fn__101055.invokeStatic(pulse.clj:322)
	at metabase.api.pulse$fn__101055.invoke(pulse.clj:308)
	at compojure.core$wrap_response$fn__43795.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__43779.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__43784.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__43788.invoke(core.clj:151)
	at clojure.lang.Var.invoke(Var.java:393)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43788.invoke(core.clj:153)
	at clojure.lang.Var.invoke(Var.java:393)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43788.invoke(core.clj:153)
	at clojure.lang.Var.invoke(Var.java:393)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43788.invoke(core.clj:153)
	at clojure.lang.Var.invoke(Var.java:393)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43788.invoke(core.clj:152)
	at clojure.lang.Var.invoke(Var.java:393)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__94181.invoke(auth.clj:17)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807.invoke(core.clj:200)
	at compojure.core$make_context$handler__43835.invoke(core.clj:290)
	at compojure.core$make_context$fn__43839.invoke(core.clj:300)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:199)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:199)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807.invoke(core.clj:200)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:199)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807.invoke(core.clj:200)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807.invoke(core.clj:200)
	at metabase.api.routes$fn__101607$fn__101608.invoke(routes.clj:64)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__101770$fn__101771.doInvoke(routes.clj:72)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807.invoke(core.clj:200)
	at compojure.core$make_context$handler__43835.invoke(core.clj:290)
	at compojure.core$make_context$fn__43839.invoke(core.clj:300)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43788.invoke(core.clj:153)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43788.invoke(core.clj:153)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__43788.invoke(core.clj:153)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:199)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:199)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:199)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807.invoke(core.clj:200)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807.invoke(core.clj:200)
	at compojure.core$make_context$handler__43835.invoke(core.clj:290)
	at compojure.core$make_context$fn__43839.invoke(core.clj:300)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807$f__43808$respond_SINGLEQUOTE___43809.invoke(core.clj:197)
	at compojure.core$make_context$fn__43839.invoke(core.clj:301)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807.invoke(core.clj:200)
	at compojure.core$routes$fn__43807$f__43808.invoke(core.clj:198)
	at compojure.core$routes$fn__43807.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__98831.invoke(exceptions.clj:108)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__98828.invoke(exceptions.clj:96)
	at metabase.server.middleware.log$log_api_call$fn__103771$fn__103772$fn__103773.invoke(log.clj:216)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12)
	at metabase.server.middleware.log$log_api_call$fn__103771$fn__103772.invoke(log.clj:208)
	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112)
	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103)
	at metabase.server.middleware.log$log_api_call$fn__103771.invoke(log.clj:207)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__108449.invoke(browser_cookie.clj:40)
	at metabase.server.middleware.security$add_security_headers$fn__85097.invoke(security.clj:180)
	at metabase.server.middleware.json$wrap_json_body$fn__45153.invoke(json.clj:67)
	at metabase.server.middleware.offset_paging$handle_paging$fn__85121.invoke(offset_paging.clj:45)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__45171.invoke(json.clj:103)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__108716.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__108735.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__65458.invoke(misc.clj:61)
	at metabase.server.middleware.session$reset_session_timeout$fn__71253.invoke(session.clj:488)
	at metabase.server.middleware.session$bind_current_user$fn__71219$fn__71220.invoke(session.clj:383)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:362)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:346)
	at metabase.server.middleware.session$bind_current_user$fn__71219.invoke(session.clj:382)
	at metabase.server.middleware.session$wrap_current_user_info$fn__71202.invoke(session.clj:321)
	at metabase.server.middleware.session$wrap_session_id$fn__71185.invoke(session.clj:253)
	at metabase.server.middleware.auth$wrap_api_key$fn__94189.invoke(auth.clj:30)
	at ring.middleware.cookies$wrap_cookies$fn__108636.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__65440.invoke(misc.clj:29)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__65466.invoke(misc.clj:78)
	at ring.middleware.gzip$wrap_gzip$fn__108678.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__65469.invoke(misc.clj:95)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__108465.invoke(ssl.clj:41)
	at metabase.server$async_proxy_handler$fn__65643.invoke(server.clj:78)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
[ac89de1d-232c-4de3-beef-54edb2cab0a7] 2024-02-26T13:55:52-06:00 DEBUG metabase.server.middleware.log POST /api/pulse/test 200 2.1 s (60 DB calls) App DB connections: 1/10 Jetty threads: 6/50 (3 idle, 0 queued) (126 total active threads) Queries in flight: 0 (0 queued); snowflake DB 3 connections: 0/7 (0 threads blocked)
[ac89de1d-232c-4de3-beef-54edb2cab0a7] 2024-02-26T14:00:00-06:00 INFO metabase.task.send-pulses Sending scheduled pulses...
[ac89de1d-232c-4de3-beef-54edb2cab0a7] 2024-02-26T14:11:00-06:00 INFO metabase.task.sync-databases Starting sync task for Database 2.
[ac89de1d-232c-4de3-beef-54edb2cab0a7] 2024-02-26T14:11:10-06:00 ERROR metabase.driver.util Failed to connect to Database
java.util.concurrent.TimeoutException: Timed out after 10.0 s
	at metabase.util.jvm$deref_with_timeout.invokeStatic(jvm.clj:287)
	at metabase.util.jvm$deref_with_timeout.invoke(jvm.clj:279)
	at metabase.util.jvm$do_with_timeout.invokeStatic(jvm.clj:294)
	at metabase.util.jvm$do_with_timeout.invoke(jvm.clj:290)
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:146)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:135)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_$fn__110809$fn__110810.invoke(sync_databases.clj:88)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_$fn__110809.invoke(sync_databases.clj:87)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invokeStatic(sync_databases.clj:84)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invoke(sync_databases.clj:77)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:113)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:101)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:118)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[ac89de1d-232c-4de3-beef-54edb2cab0a7] 2024-02-26T14:11:10-06:00 ERROR metabase.driver.snowflake (type message)
=> java.lang.String
[ac89de1d-232c-4de3-beef-54edb2cab0a7] 2024-02-26T14:11:10-06:00 WARN metabase.task.sync-databases Cannot sync Database Snowflake Dev: Timed out after 10.0 s
clojure.lang.ExceptionInfo: Timed out after 10.0 s {:message "Timed out after 10.0 s"}
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:164)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:135)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_$fn__110809$fn__110810.invoke(sync_databases.clj:88)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_$fn__110809.invoke(sync_databases.clj:87)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invokeStatic(sync_databases.clj:84)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invoke(sync_databases.clj:77)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:113)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:101)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:118)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.util.concurrent.TimeoutException: Timed out after 10.0 s
	at metabase.util.jvm$deref_with_timeout.invokeStatic(jvm.clj:287)
	at metabase.util.jvm$deref_with_timeout.invoke(jvm.clj:279)
	at metabase.util.jvm$do_with_timeout.invokeStatic(jvm.clj:294)
	at metabase.util.jvm$do_with_timeout.invoke(jvm.clj:290)
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:146)
	... 11 more
[ac89de1d-232c-4de3-beef-54edb2cab0a7] 2024-02-26T14:12:00-06:00 INFO metabase.task.sync-databases Starting sync task for Database 3.

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.15.133.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "snowflake",
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22 (Debian 11.22-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-12",
      "tag": "v1.48.6",
      "hash": "b8818f9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

There are work arounds but it's not very obvious why this is happening or how to work around it.

**Comment by god-s-perfect-idiot** [comment]
+1 on this.
