### ISSUE TITLE
Running Metabase on Google App Engine

### ISSUE THREAD

**Issue by remydavid** [metabase/metabase#3983]
I try to run Metabase on Google App Engine.
I downloaded the master Dockerfile and created the following yaml : 

```
runtime: custom
env: flex
```

Build (gcloud app deploy) fail with following error : 

```
Step 13 : RUN bin/build
 ---> Running in ddb940f2458b
/bin/sh: bin/build: not found
The command '/bin/sh -c bin/build' returned a non-zero code: 127
ERROR
ERROR: build step "gcr.io/cloud-builders/docker@sha256:1b5a8642d04ef785f7dd2dbb0296f837895f50442fdfe5ebd0b04c206ab0b
1b5" failed: exit status 1
ERROR: (gcloud.app.deploy) Error Response: [2] Build failed; check build logs for details
```

I am new to Docker, any idea what the problem is ?

**Comment by tlrobinson** [comment]
@remydavid I'm not familiar with Docker on App Engine, but we have pre-built Docker images available on Dockerhub, can you use those? https://hub.docker.com/r/metabase/metabase/

**Comment by remydavid** [comment]
Nope, App Engine only takes Dockerfiles as input to setup new instances.

**Comment by bedeoverend** [comment]
@remydavid so I've actually had to use the pre-built images to get it up and running on App Engine. I tried using metabase's dockerfile to compile on run time, but it kept timing out (not sure why you're getting the above issue) so instead I download and run the `.jar` file inside a custom docker file. 

It looks something like:

```
FROM openjdk:8
ADD http://downloads.metabase.com/v0.21.1/metabase.jar ./metabase.jar

CMD java -jar ./metabase.jar
```

I've customized mine a bit though to get it using Cloud SQL as metabase's internal database:

```
FROM openjdk:8

ADD https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 ./cloud_sql_proxy
ADD http://downloads.metabase.com/v0.21.1/metabase.jar ./metabase.jar

RUN chmod +x ./cloud_sql_proxy

CMD ./cloud_sql_proxy -instances=$METABASE_SQL_INSTANCE=tcp:$MB_DB_PORT & java -jar ./metabase.jar
```

That was my workaround for https://github.com/metabase/metabase/issues/3852 - though what would be better is using `MB_DB_CONNECTION_URI` but I haven't tried that yet.

Just remember also to setup the correct env variables in your `app.yaml` e.g.

```yaml
  MB_JETTY_PORT: 8080

  MB_DB_TYPE: mysql
  MB_DB_DBNAME: metabase
  MB_DB_PORT: 3306
  MB_DB_USER: user
  MB_DB_PASS: secret
  MB_DB_HOST: 127.0.0.1
```

**Comment by remydavid** [comment]
Nice workaround @bedeoverend, I will test that ASAP and report here, thanks a lot !

**Comment by salsakran** [comment]
This looks awesome. I'd love to have app engine be an officially recommended platform. 

@bedeoverend does app engine still time out a connection after 60s? Could you share any other tips for running on GAE?

We have a lot of folks running MB against big data warehouses with average query times in the minutes.

**Comment by bedeoverend** [comment]
No worries @remydavid - good luck!

@salsakran quite possibly - the database I'm operating against is still pretty small, so my queries aren't too big, I haven't run up against any queries (on any of my app engine apps) that are > 60s. 

I've only being using Metabase on GAE for a couple of weeks, so I don't have much more to report than that. The two real issues I'm having at the moment is connecting via SQL socket (though there should be a workaround, as I mentioned above) and not being able to build + deploy Metabase directly due to GAE timing out during docker build (think it was WebPack running too long actually). The solution to that is me building a custom version of Metabase, uploading that .jar to GCS and adding it via the dockerfile as above - it's pretty clunky, and not yet automated.

I'll make sure to report back if I find anything more though!

**Comment by bedeoverend** [comment]
Oh and FWIW if anyone's looking at this. My team uses Segment as our event / data aggregator, BigQuery as our Data Warehouse and GAE to host Metabase. It is a 👌 stack.

**Comment by remydavid** [comment]
Ok so I managed to run Metabase on app engine with the openjdk docker image trick + Cloud SQL for the internal DB. The setup is not very straightforwards but it works ! thanks @bedeoverend

However, trying to run with the embedded H2 db :

`FROM openjdk:8
ADD http://downloads.metabase.com/v0.21.1/metabase.jar ./metabase.jar

CMD java -jar ./metabase.jar`

I end up in an infinite reloading loop of the home page after initial setup with authentication errors in the logs :

```
DEBUG metabase.middleware :: GET /api/dashboard 401 (67 µs) (0 DB calls)
2017-01-04 15:38:00 default[20170104t114737]  "Unauthenticated"
2017-01-04 15:38:00 default[20170104t114737]
2017-01-04 15:38:00 01-04 15:38:00 DEBUG metabase.middleware :: GET /api/activity/recent_views 401 (84 µs) (0 DB calls)
2017-01-04 15:38:00 default[20170104t114737]  "Unauthenticated"
2017-01-04 15:38:00 default[20170104t114737]
2017-01-04 15:38:00 01-04 15:38:00 DEBUG metabase.middleware :: GET /api/activity/recent_views 401 (67 µs) (0 DB calls)
2017-01-04 15:38:00 default[20170104t114737]  "Unauthenticated"
2017-01-04 15:38:00 default[20170104t114737]
2017-01-04 15:38:00 01-04 15:38:00 WARN metabase.middleware :: GET /api/setup/admin_checklist 403 (126 µs) (0 DB calls)
2017-01-04 15:38:00 default[20170104t114737]  "You don't have permissions to do that."
2017-01-04 15:38:00 default[20170104t114737]
2017-01-04 15:38:00 01-04 15:38:00 WARN metabase.middleware :: GET /api/setup/admin_checklist 403 (162 µs) (0 DB calls)
2017-01-04 15:38:00 default[20170104t114737]  "You don't have permissions to do that."
2017-01-04 15:38:00 default[20170104t114737]
2017-01-04 15:38:00 01-04 15:38:00 DEBUG metabase.middleware :: GET /api/activity 401 (46 µs) (0 DB calls)
2017-01-04 15:38:00 default[20170104t114737]  "Unauthenticated"
2017-01-04 15:38:00 default[20170104t114737]
2017-01-04 15:38:00 01-04 15:38:00 DEBUG metabase.middleware :: GET /api/dashboard 401 (55 µs) (0 DB calls)
2017-01-04 15:38:00 default[20170104t114737]  "Unauthenticated"
2017-01-04 15:38:00 default[20170104t114737]
2017-01-04 15:38:00 01-04 15:38:00 DEBUG metabase.middleware :: GET /api/activity/recent_views 401 (51 µs) (0 DB calls)
2017-01-04 15:38:00 default[20170104t114737]  "Unauthenticated"
2017-01-04 15:38:00 default[20170104t114737]
2017-01-04 15:38:00 01-04 15:38:00 WARN metabase.middleware :: GET /api/setup/admin_checklist 403 (168 µs) (0 DB calls)
2017-01-04 15:38:00 default[20170104t114737]  "You don't have permissions to do that."
2017-01-04 15:38:00 default[20170104t114737]
2017-01-04 15:38:00 01-04 15:38:00 DEBUG metabase.middleware :: GET /api/dashboard 401 (39 µs) (0 DB calls)
2017-01-04 15:38:00 default[20170104t114737]  "Unauthenticated"
2017-01-04 15:38:00 default[20170104t114737]
```

I think it is because Docker container on App Engine doesn't have persistent disk space (just guessing here, I am not familiar with App Engine).

**Comment by bedeoverend** [comment]
@remydavid not really sure either - probably something along those lines. It might be worth asking in Google Cloud's slack group: https://googlecloud-community.slack.com - they're pretty active and helpful.

**Comment by salsakran** [comment]
@remydavid we'd strongly suggest not using the embedded DB on app engine, but instead create a cloud sql database and inject it's variables into the docker env. 

the embedded database creates a local file, and app engine to my knowledge doesn't like you doing that, and generally presumes that individual images are transient.

**Comment by bedeoverend** [comment]
@remydavid @salsakran just to expand on that more - you shouldn't rely on the file system because then you won't be able to scale out horizontally, which is one of the core benefits of using App Engine i.e. you won't be able to have more than one App Engine instance, as each will reference it's own local file system. Using Cloud SQL means all instances will be pointing to the rate database.

**Comment by remydavid** [comment]
Running with a SQL instance works like a charm. Now I want to update Metabase to latest release but redeploying the new jar using gcloud app deploy I got a DB migration error : 

`Updating service [default]...failed.                                                                                                                                                                                                          
ERROR: (gcloud.app.deploy) Error Response: [9] 
Application startup error:
2017/02/23 11:54:16 Listening on 127.0.0.1:3306 for xxx:metabase-prod
2017/02/23 11:54:16 Ready for new connections
02-23 11:54:25 INFO metabase.util :: Loading Metabase...
02-23 11:54:43 INFO metabase.core :: Starting Metabase in STANDALONE mode
02-23 11:54:43 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 8080}

02-23 11:54:44 INFO metabase.core :: Starting Metabase version v0.22.2 (e318fee release-0.22.2) ...
02-23 11:54:44 INFO metabase.core :: System timezone is 'Etc/UTC' ...
02-23 11:54:44 DEBUG metabase.driver :: Registered driver :bigquery �
02-23 11:54:44 DEBUG metabase.driver :: Registered driver :crate �
02-23 11:54:44 DEBUG metabase.driver :: Registered driver :druid �
02-23 11:54:44 DEBUG metabase.driver :: Registered driver :googleanalytics �
02-23 11:54:44 DEBUG metabase.driver :: Registered driver :h2 �
02-23 11:54:45 DEBUG metabase.driver :: Registered driver :mongo �
02-23 11:54:45 DEBUG metabase.driver :: Registered driver :mysql �
02-23 11:54:45 DEBUG metabase.driver :: Registered driver :postgres �
02-23 11:54:45 DEBUG metabase.driver :: Registered driver :redshift �
02-23 11:54:45 DEBUG metabase.driver :: Registered driver :sqlite �
02-23 11:54:45 DEBUG metabase.driver :: Registered driver :sqlserver �
02-23 11:54:45 INFO metabase.db :: Verifying mysql Database Connection ...
2017/02/23 11:54:45 New connection for "xxx:metabase-prod"
2017/02/23 11:54:46 Client closed local connection on 127.0.0.1:3306
02-23 11:54:46 INFO metabase.db :: Verify Database Connection ...  ✅
02-23 11:54:46 INFO metabase.db :: Running Database Migrations...
2017/02/23 11:54:46 New connection for "xxx:metabase-prod"
Thu Feb 23 11:54:46 UTC 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
02-23 11:54:46 INFO metabase.db :: Setting up Liquibase...
02-23 11:54:46 INFO metabase.db :: Liquibase is ready.
02-23 11:54:46 INFO metabase.db :: Checking if Database has unrun migrations...
02-23 11:55:33 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
02-23 11:55:35 WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__7708@7669fc90: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
02-23 11:55:37 WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__7708@7669fc90: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
02-23 11:55:39 WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__7708@7669fc90: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
02-23 11:55:41 WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__7708@7669fc90: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
02-23 11:55:43 WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__7708@7669fc90: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
java.lang.Exception: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
        at metabase.db$wait_for_migration_lock_to_be_cleared$fn__7708.invoke(db.clj:152)
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:692)
        at metabase.util$do_with_auto_retries.invoke(util.clj:684)
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:696)
        at metabase.util$do_with_auto_retries.invoke(util.clj:684)2017/02/23 11:55:45 Client closed local connection on 127.0.0.1:3306

        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:696)
        at metabase.util$do_with_auto_retries.invoke(util.clj:684)
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:696)
        at metabase.util$do_with_auto_retries.invoke(util.clj:684)
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:696)
        at metabase.util$do_with_auto_retries.invoke(util.clj:684)
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:696)
        at metabase.util$do_with_auto_retries.invoke(util.clj:684)
        at metabase.db$wait_for_migration_lock_to_be_cleared.invokeStatic(db.clj:150)
        at metabase.db$wait_for_migration_lock_to_be_cleared.invoke(db.clj:146)
        at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:165)
        at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:155)
        at metabase.db$migrate_BANG_$fn__7741.invoke(db.clj:232)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:629)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at metabase.db$migrate_BANG_.invokeStatic(db.clj:221)
        at metabase.db$migrate_BANG_.invoke(db.clj:204)
        at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:372)
        at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:367)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:391)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:383)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:113)
        at metabase.core$init_BANG_.invoke(core.clj:93)
        at metabase.core$start_normally.invokeStatic(core.clj:196)
        at metabase.core$start_normally.invoke(core.clj:190)
        at metabase.core$_main.invokeStatic(core.clj:288)
        at metabase.core$_main.doInvoke(core.clj:283)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
02-23 11:55:45 ERROR metabase.core :: Metabase Initialization FAILED:  Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
02-23 11:55:45 INFO metabase.core :: Metabase Shutting Down ...
02-23 11:55:45 INFO metabase.core :: Metabase Shutdown COMPLETE`

Not sure how to run 'java -jar metabase.jar migrate release-locks' on existing service with App Engine (no access to the actual VM).

@bedeoverend What is your process to update Metabase to a new version ?

**Comment by bedeoverend** [comment]
@remydavid I believe what I did was instead of:

`CMD ./cloud_sql_proxy -instances=$METABASE_SQL_INSTANCE=tcp:$MB_DB_PORT & java -jar ./metabase.jar`

Add the lock release part before booting:

`CMD ./cloud_sql_proxy -instances=$METABASE_SQL_INSTANCE=tcp:$MB_DB_PORT & (java -jar metabase.jar migrate release-locks && java -jar ./metabase.jar)`

I don't have that in my bootscript anymore, but I believe that's what I used to have.

**Comment by kelset** [comment]
Any update on this? I'm considering moving Metabase to Google Cloud but I'd like to learn why it is not listed in the [docs](http://www.metabase.com/docs/v0.24.2/operations-guide/start.html#installing-and-running-metabase) under Cloud Platforms.

**Comment by bedeoverend** [comment]
@kelset FWIW my solution has been working fine for months now. If I had more time I'd also put more work into it to get a proper custom docker build file that extends metabase's, but in the end that one liner works well and was quick to get going.

**Comment by bigdavenz** [comment]
Thanks Bede (and Remy) - very nice stack. All working and very easy - love the scalability, simplicity and speed. 

I still don't quite understand how to implement the upgrade boot script - presumably I create a new bootscript in my local Docker file (pointing at the new jar with "migrate release-locks") then "gcloud app deploy" to create a new version with new instances pointing at cloud sql.

I also need a CRUD for cloud sql - it seems phpmyadmin in GAE works ok so ill head down that track next.

**Comment by salsakran** [comment]
closing this since it isn't actionable and the initial error has been resolved.

**Comment by ctivanovich** [comment]
Has anyone had success getting metabot to deliver questions and pulses to slack when hosting MB on app engine? Also, there is the issue of attempting to connect MB to other cloud sql data sources--if you have restrictions on IP traffic, well, an app engine instance doesn't have a stable IP address, so you can't count on whitelisting one.

**Comment by flamber** [comment]
@ctivanovich You're likely seeing #5380

**Comment by ctivanovich** [comment]
@flamber I don't think so--in my case, the bot is always in the channel, and it receives commands. It can even query MB to find the questions on `metabot list`. But it fails to retrieve all questions data, and pulses, test or otherwise, never arrive to the channel. Stack driver error output on a test pulse begins like this: 

```Java.lang.NullPointerException at javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:130) at javax.swing.UIDefaults.getUI(UIDefaults.java:761) at javax.swing.UIManager.getUI(UIManager.java:1016) at javax.swing.JPanel.updateUI(JPanel.java:126) at javax.swing.JPanel.<init>(JPanel.java:86) at javax.swing.JPanel.<init>(JPanel.java:109) at javax.swing.JPanel.<init>(JPanel.java:117) at org.fit.cssbox.layout.BrowserCanvas.<init>```

**Comment by flamber** [comment]
@ctivanovich Okay, then you're probably seeing a different issue, please open a new issue and provide full logs from Admin > Troubleshooting > Logs.
