### ISSUE TITLE
Can't run built uberjar

### ISSUE THREAD

**Issue by keitarobr** [metabase/metabase#3984]
I can't run the built uberjar (bin/build) form master or 0.21.1. It throws the following exception:

```
java -jar /home/rodrigo/metabase/target/uberjar/metabase.jar
12-19 14:23:56 INFO metabase.util :: Loading Metabase...
12-19 14:24:05 INFO metabase.core :: Starting Metabase in STANDALONE mode
12-19 14:24:05 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

12-19 14:24:05 INFO metabase.core :: Starting Metabase version v0.22.0-snapshot (5a5981d master) ...
12-19 14:24:05 INFO metabase.core :: System timezone is 'America/Sao_Paulo' ...
12-19 14:24:05 DEBUG metabase.driver :: Registered driver :mongo ?
12-19 14:24:05 DEBUG metabase.driver :: Registered driver :postgres ?
12-19 14:24:05 DEBUG metabase.driver :: Registered driver :redshift ?
12-19 14:24:05 DEBUG metabase.driver :: Registered driver :crate ?
12-19 14:24:05 DEBUG metabase.driver :: Registered driver :sqlserver ?
12-19 14:24:05 DEBUG metabase.driver :: Registered driver :mysql ?
12-19 14:24:05 DEBUG metabase.driver :: Registered driver :sqlite ?
12-19 14:24:06 DEBUG metabase.driver :: Registered driver :druid ?
12-19 14:24:06 DEBUG metabase.driver :: Registered driver :h2 ?
12-19 14:24:06 DEBUG metabase.driver :: Registered driver :googleanalytics ?
java.lang.NoClassDefFoundError: metabase/driver/bigquery$?s__GT_str
        at metabase.driver.bigquery__init.load(Unknown Source)
        at metabase.driver.bigquery__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2168)
        at clojure.lang.RT.classForName(RT.java:2177)
        at clojure.lang.RT.loadClassForName(RT.java:2196)
        at clojure.lang.RT.load(RT.java:443)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at metabase.driver$find_and_load_drivers_BANG_.invokeStatic(driver.clj:277)
        at metabase.driver$find_and_load_drivers_BANG_.invoke(driver.clj:271)
        at metabase.core$init_BANG_.invokeStatic(core.clj:109)
        at metabase.core$init_BANG_.invoke(core.clj:93)
        at metabase.core$start_normally.invokeStatic(core.clj:196)
        at metabase.core$start_normally.invoke(core.clj:190)
        at metabase.core$_main.invokeStatic(core.clj:288)
        at metabase.core$_main.doInvoke(core.clj:283)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: metabase.driver.bigquery$?s__GT_str
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 39 more
12-19 14:24:06 ERROR metabase.core :: Metabase Initialization FAILED:  metabase/driver/bigquery$?s__GT_str
12-19 14:24:06 INFO metabase.core :: Metabase Shutting Down ...
12-19 14:24:06 INFO metabase.core :: Metabase Shutdown COMPLETE
```

I'm using the following enviroment:

```cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

Linux ubuntu 3.13.0-98-generic #145-Ubuntu SMP Sat Oct 8 20:13:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

node --version
v6.9.2


java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

yarn --version
0.18.1

lein --version
Leiningen 2.7.1 on Java 1.8.0_101 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by salsakran** [comment]
can you try a manual `lein deps` and see if there are any errors or warnings?

**Comment by keitarobr** [comment]
Hi, 

running `lein deps` gives no output (which I assume means there are no problems?)

Kind regards,

**Comment by keitarobr** [comment]
I ended up building a new VM with Ubuntu Xenial and was able to compile and run. Probably some issue with Trusty.
