### ISSUE TITLE
Upgrade Error - Migration fails to start

### ISSUE THREAD

**Issue by renatocron** [metabase/metabase#40161]
### Describe the bug

I'm upgrading from v0.47.8 to metabase v0.49.0, but my database username is "metabase-user" is it has a "-" char, so the migration fails on a SET SEARCH_PATH TO command that has not beeing correctly escaped

### To Reproduce

Attempt to upgrade from v0.47.8 to v0.49.0.
See the error message displayed.

### Expected behavior

The upgrade process should proceed smoothly without encountering any errors.

### Logs

2024-03-15 11:15:28,078 INFO db.liquibase :: Checking if Database has unrun migrations... 
2024-03-15 11:15:29,627 INFO db.liquibase :: Database has unrun migrations. Checking if migraton lock is taken... 
2024-03-15 11:15:29,648 INFO db.liquibase :: No migration lock found. 
2024-03-15 11:15:30,518 INFO db.liquibase :: Running 110 migrations ... 
2024-03-15 11:15:31,266 ERROR liquibase.command :: Could not release lock 
liquibase.exception.LockException: liquibase.exception.DatabaseException: ERROR: syntax error at or near "-" 
  Position: 28 [Failed SQL: (0) SET SEARCH_PATH TO metabase-user, "$user","public"] 
	at liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:407) 
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:140) 
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105) 
	at liquibase.command.CommandScope.execute(CommandScope.java:217) 
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245) 
	at liquibase.Scope.lambda$child$0(Scope.java:186) 
	at liquibase.Scope.child(Scope.java:195) 
	at liquibase.Scope.child(Scope.java:185) 
	at liquibase.Scope.child(Scope.java:164) 
	at liquibase.Liquibase.runInScope(Liquibase.java:1419) 
	at liquibase.Liquibase.update(Liquibase.java:234) 
	at liquibase.Liquibase.update(Liquibase.java:212) 
	at liquibase.Liquibase.update(Liquibase.java:194) 

### Information about your Metabase installation

```JSON
Version: v0.47.8
Upgrade Target Version: v0.49.0
Environment: Kubernetes (k8s)
Database Username: metabase-user (contains "-")
```

### Severity

High

### Additional context

ERROR: syntax error at or near "-" Position: 28 [Failed SQL: (0) SET SEARCH_PATH TO metabase-user, "$user","public"]

**Comment by paoliniluis** [comment]
oh this is fun, which database are you using?

**Comment by renatocron** [comment]
It's DigitalOcean managed database, it just ocurred that that the user had "metabase-user" with - in it's name

I ended up doing this to fix the issue:

Get the views that depends on citext extension.


pg_dump -h <hostname> -U <username> -d <database_name> -n metabase-user -t metabase_user.v_subscriptions -t metabase_user.v_alerts -t metabase_user.v_users --schema-only -f views_backup.sql

drop extension citext
alter table   metabase_user.core_user  alter column email type varchar;
alter table   metabase_user.core_user  alter column email type citext;


recreate citext on new schema (metabase_user for exemple),

**Comment by paoliniluis** [comment]
What's the engine of the DO managed database? postgres or mysql?

**Comment by renatocron** [comment]
postgresql 15,
sorry, I thought there was only set path in postgres
