### ISSUE TITLE
Can't open Detail View in question based on model with composite primary keys from Clickhouse

### ISSUE THREAD

**Issue by tritatuy** [metabase/metabase#40520]
### Describe the bug

I have a model built on SQL query to Clickhouse's system table `system.query_log`. The query is:
```
SELECT event_time,
       initial_user,
       type,
       read_bytes / 1000000 AS read_mbytes,
       result_bytes / 1000000 AS result_mbytes,
       query_duration_ms / 60000 AS query_duration_min,
       memory_usage / 1000000 AS memory_usage_mbytes,
       ProfileEvents.Values[indexOf(ProfileEvents.Names, 'UserTimeMicroseconds')] / 1000 / 1000 AS CPU_load,
       read_rows,
       result_rows,
       written_rows,
       written_bytes / 1000000 AS written_mbytes,
       toString(normalized_query_hash) AS normalized_query_hash,
       query_id,
       initial_query_id,
       query,
       query_start_time,
       hostName() AS host_name,
       current_database,
       query_kind,
       arrayStringConcat(databases, ', ') AS databases,
       arrayStringConcat(tables, ', ') AS tables,
       arrayStringConcat(views, ', ') AS views,
       exception_code,
       exception,
       is_initial_query,
       user,
       initial_query_start_time,
       interface,
       is_secure,
       client_hostname,
       client_name,
       quota_key,
       Settings,
       arrayStringConcat(used_aggregate_functions, ', ') AS used_aggregate_functions,
       arrayStringConcat(used_aggregate_function_combinators, ', ') AS used_aggregate_function_combinators,
       arrayStringConcat(used_database_engines, ', ') AS used_database_engines,
       arrayStringConcat(used_data_type_families, ', ') AS used_data_type_families,
       arrayStringConcat(used_dictionaries, ', ') AS used_dictionaries,
       arrayStringConcat(used_formats, ', ') AS used_formats,
       arrayStringConcat(used_functions, ', ') AS used_functions,
       arrayStringConcat(used_storages, ', ') AS used_storages,
       arrayStringConcat(used_table_functions, ', ') AS used_table_functions,
       arrayStringConcat(used_row_policies, ', ') AS used_row_policies,
       query_cache_usage,
       toUnixTimestamp(event_time) AS event_timestamp
FROM clusterAllReplicas('clickhouse_cluster', system.query_log)
WHERE event_date > today() - 7
ORDER BY event_time ASC
```
When I'm opening the results and trying to press Detail View I see nothing but exclamation mark:
<img width="718" alt="Screenshot at Mar 22 19-44-23" src="https://github.com/metabase/metabase/assets/74110979/225120b4-2324-45bf-92f7-1f4dae764020">

The same situation is happen when I'm trying to create a question to this model.
It works ok with other Clickhouse's models I've done. But this one doesn't work even after updating from 0.47 to 0.49.1.

### To Reproduce

1. Click on `+ New` -> `Model` 
2. Past my SQL query to the model builder
3. Save the model.
4. Open the model's results.
5. Press `Detail View`

### Expected behavior

I expect to see the popup with values of all fields.

### Logs

```
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:00+04:00 INFO metabase.task.sync-databases Starting sync task for Database 26.
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:00+04:00 DEBUG metabase.server.middleware.log GET /api/setup/admin_checklist 200 26,3 ms (9 вызовы БД) Соединения с БД приложения: 3 / 10 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (142 всего активных тем) Запросы в полете: 0 (0 в очереди)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:00+04:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 24,4 ms (6 вызовы БД) Соединения с БД приложения: 2 / 10 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (143 всего активных тем) Запросы в полете: 0 (0 в очереди)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:00+04:00 DEBUG metabase.server.middleware.log GET /api/setting 200 75,6 ms (13 вызовы БД) Соединения с БД приложения: 1 / 10 Потоки Jetty: 4 / 50 (2 бездействует, 0 в очереди) (145 всего активных тем) Запросы в полете: 0 (0 в очереди)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:07+04:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 13,4 ms (1 вызовы БД) Соединения с БД приложения: 1 / 10 Потоки Jetty: 3 / 50 (4 бездействует, 0 в очереди) (145 всего активных тем) Запросы в полете: 0 (0 в очереди)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:10+04:00 ERROR metabase.driver.util Failed to connect to Database,java.util.concurrent.TimeoutException: Тайм-аут после 10,0 s,	at metabase.util.jvm$deref_with_timeout.invokeStatic(jvm.clj:287),	at metabase.util.jvm$deref_with_timeout.invoke(jvm.clj:279),	at metabase.util.jvm$do_with_timeout.invokeStatic(jvm.clj:294),	at metabase.util.jvm$do_with_timeout.invoke(jvm.clj:290),	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:147),	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:136),	at clojure.lang.RestFn.invoke(RestFn.java:442),	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_$fn__106132$fn__106133.invoke(sync_databases.clj:87),	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_$fn__106132.invoke(sync_databases.clj:86),	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invokeStatic(sync_databases.clj:83),	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invoke(sync_databases.clj:76),	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:112),	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:100),	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:117),	at org.quartz.core.JobRunShell.run(JobRunShell.java:202),	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:33+04:00 DEBUG metabase.server.middleware.log GET /api/activity/recent_views 200 27,0 ms (7 вызовы БД) Соединения с БД приложения: 2 / 10 Потоки Jetty: 4 / 50 (2 бездействует, 0 в очереди) (145 всего активных тем) Запросы в полете: 0 (0 в очереди)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:34+04:00 DEBUG metabase.server.middleware.log GET /api/activity/popular_items 200 881,1 ms (10 вызовы БД) Соединения с БД приложения: 1 / 10 Потоки Jetty: 3 / 50 (3 бездействует, 0 в очереди) (145 всего активных тем) Запросы в полете: 0 (0 в очереди)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:35+04:00 DEBUG metabase.server.middleware.log GET /api/alert/question/1726 200 1,5 ms (1 вызовы БД) Соединения с БД приложения: 1 / 10 Потоки Jetty: 3 / 50 (4 бездействует, 0 в очереди) (145 всего активных тем) Запросы в полете: 0 (0 в очереди)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:35+04:00 INFO metabase.api.dataset Исходный запрос для текущего - карточка 1726
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:40+04:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [АСИНХРОННЫЙ: completed] 4,2 s (11 вызовы БД) Соединения с БД приложения: 3 / 10 Потоки Jetty: 2 / 50 (4 бездействует, 0 в очереди) (146 всего активных тем) Запросы в полете: 1 (0 в очереди); clickhouse DB 14 connections: 0/1 (0 threads blocked)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:48+04:00 DEBUG metabase.server.middleware.log GET /api/setup/admin_checklist 200 23,4 ms (9 вызовы БД) Соединения с БД приложения: 1 / 10 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (146 всего активных тем) Запросы в полете: 0 (0 в очереди)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:48+04:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 39,1 ms (6 вызовы БД) Соединения с БД приложения: 2 / 10 Потоки Jetty: 4 / 50 (2 бездействует, 0 в очереди) (146 всего активных тем) Запросы в полете: 0 (0 в очереди)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:48+04:00 DEBUG metabase.server.middleware.log GET /api/setting 200 39,5 ms (12 вызовы БД) Соединения с БД приложения: 1 / 10 Потоки Jetty: 4 / 50 (2 бездействует, 0 в очереди) (146 всего активных тем) Запросы в полете: 0 (0 в очереди)
[f0714a4d-4c0a-41b6-82e0-34d2eba378e0] 2024-03-22T19:54:50+04:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 8,2 ms (1 вызовы БД) Соединения с БД приложения: 1 / 10 Потоки Jetty: 3 / 50 (4 бездействует, 0 в очереди) (146 всего активных тем) Запросы в полете: 0 (0 в очереди)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "ru-RU",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "5.10.0-28-amd64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql",
      "postgres",
      "clickhouse",
      "h2",
      "bigquery-cloud-sdk",
      "googleanalytics"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.4 (Debian 11.4-1.pgdg90+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-03-21",
      "tag": "v0.49.1",
      "hash": "54ef5e9"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

annoying

**Comment by paoliniluis** [comment]
can you check the browser logs? I need to see the browser console to see what's the error

**Comment by paoliniluis** [comment]
Thanks, can you send a screenshot of some sort? I'm not able to see the error ordered

**Comment by kamilmielnik** [comment]
The important part in logs is this: 

```
object-detail.js:27 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bmax_threads%2C%20connect_timeout_with_failover_secure_ms%2C%20idle_connection_timeout%2C%20s3_min_upload_part_size%2C%20s3_max_single_part_upload_size%2C%20distributed_directory_monitor_batch_inserts%2C%20do_not_merge_across_partitions_select_final%2C%20os_thread_priority%2C%20log_queries%2C%20log_queries_cut_to_length%2C%20distributed_product_mode%2C%20max_concurrent_queries_for_user%2C%20any_join_distinct_right_table_keys%2C%20insert_distributed_sync%2C%20joined_subquery_requires_alias%2C%20max_bytes_before_external_group_by%2C%20max_bytes_before_external_sort%2C%20timeout_before_checking_execution_speed%2C%20join_algorithm%2C%20max_memory_usage%2C%20send_logs_level%2C%20max_partitions_per_insert_block%2C%20allow_drop_detached%2C%20database_atomic_wait_for_drop_and_detach_synchronously%2C%20cast_ipv4_ipv6_default_on_conversion_error%2C%20kafka_disable_num_consumers_limit%2C%20force_remove_data_recursively_on_drop%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

Stacktrace indicates that it happens [when `ZOOM_IN_ROW` action is dispatched](https://github.com/metabase/metabase/blob/92d615073a3ba31710e26be9f2e83141352d1d1c/frontend/src/metabase/query_builder/actions/object-detail.js#L27).

Following the link gives us this error:
```
Objects are not valid as a React child (found: object with keys {max_threads, connect_timeout_with_failover_secure_ms, idle_connection_timeout, s3_min_upload_part_size, s3_max_single_part_upload_size, distributed_directory_monitor_batch_inserts, do_not_merge_across_partitions_select_final, os_thread_priority, log_queries, log_queries_cut_to_length, distributed_product_mode, max_concurrent_queries_for_user, any_join_distinct_right_table_keys, insert_distributed_sync, joined_subquery_requires_alias, max_bytes_before_external_group_by, max_bytes_before_external_sort, timeout_before_checking_execution_speed, join_algorithm, max_memory_usage, send_logs_level, max_partitions_per_insert_block, allow_drop_detached, database_atomic_wait_for_drop_and_detach_synchronously, cast_ipv4_ipv6_default_on_conversion_error, kafka_disable_num_consumers_limit, force_remove_data_recursively_on_drop}). If you meant to render a collection of children, use an array instead.
```

Instead of data (text/number) React is given an object to render.
Attributes of this object indicate that this is some kind of clickhouse settings object (see e.g. [1](https://clickhouse.com/docs/en/operations/settings/query-complexity#settings-max_partitions_per_insert_block), [2](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3#settings)).
This makes it look like a BE issue because such object should never reach FE.

----

I failed to reproduce this in `master`.
I used ClickHouse 24.11.1.942.
Note: I had to remove `ProfileEvents.Values[indexOf(ProfileEvents.Names, 'UserTimeMicroseconds')] / 1000 / 1000 AS CPU_load,` because it gave me this error: `Code: 44. DB::Exception: Invalid column type for ColumnUnique::insertRangeFrom. Expected String, got LowCardinality(String). (ILLEGAL_COLUMN)`.
I'll try 0.49 tomorrow.

**Comment by kamilmielnik** [comment]
> I'll try 0.49 tomorrow.

I can't reproduce the issue in 0.49.1, I tried metabase-clickhouse-driver 1.4.0.

**Comment by ranquild** [comment]
Related to https://github.com/metabase/metabase/issues/19411

**Comment by cdeweyx** [comment]
Closing as dupe of https://github.com/metabase/metabase/issues/19411
