### ISSUE TITLE
Use Google Cloud SQL as Metabase Application Database

### ISSUE THREAD

**Issue by joshreuben456** [metabase/metabase#4059]
we are evaluating Metabase as BI front end over **Google BigQuery**. We would like to deploy the Metabase Docker image under **GKE (Google Kubernetes Engine)** instead of running the jar as a daemon + MySQL / PostgreSQL on Google App Engine. We would like to leverage the **Google Cloud SQL** as the Metabase Application Database.

1. How can we do this ?
2. If this is not supported, when will it be supported ?

**Comment by camsaul** [comment]
Hi @joshreuben456, we don't currently have any plans to support using Google Cloud SQL as the application database. We recommend using Postgres or MySQL instead.

**Comment by VikramTiwari** [comment]
@joshreuben456 If I understand it correctly, Google Cloud SQL is just managed MySQL database. You can use the existing MySQL connector.


How to go about solving your concern:
- Create the containers using docker image provided by Metabase
- Pass your connection setting to Cloud SQL (host, username and pass) in YAML files for k8s
- Deploy and Enjoy!

Ref: https://cloud.google.com/sql/docs/features

**Comment by raja-ankaha** [comment]
@carlodicelico I tried connecting the cloud sql proxy but got this error: ERROR: cannot execute CREATE TABLE in a read-only transaction    
Log below
`04-28 19:16:59 INFO driver.impl :: Initializing driver :sql...
04-28 19:16:59 INFO driver.impl :: Initializing driver :sql-jdbc...
04-28 19:16:59 INFO driver.impl :: Initializing driver :postgres...
04-28 19:16:59 INFO metabase.db :: Successfully verified PostgreSQL 9.6.16 application database connection. ✅
04-28 19:16:59 INFO metabase.db :: Running Database Migrations...
04-28 19:16:59 INFO metabase.db :: Setting up Liquibase...
04-28 19:16:59 INFO metabase.db :: Liquibase is ready.
04-28 19:16:59 INFO db.liquibase :: Checking if Database has unrun migrations...
04-28 19:17:00 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.DatabaseException: ERROR: cannot execute CREATE TABLE in a read-only transaction [Failed SQL: CREATE TABLE public.databasechangelog (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP WITHOUT TIME ZONE NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:109)
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:280)
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1219)
	at liquibase.Liquibase.listLocks(Liquibase.java:1240)
	at metabase.db.liquibase$migration_lock_exists_QMARK_.invokeStatic(liquibase.clj:98)
	at metabase.db.liquibase$migration_lock_exists_QMARK_.invoke(liquibase.clj:95)
	at metabase.db.liquibase$release_lock_if_needed_BANG_.invokeStatic(liquibase.clj:188)
	at metabase.db.liquibase$release_lock_if_needed_BANG_.invoke(liquibase.clj:184)
	at metabase.db$migrate_BANG_$fn__21263$fn__21264.invoke(db.clj:231)
	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:38)
	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:29)
	at metabase.db$migrate_BANG_$fn__21263.invoke(db.clj:203)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at metabase.db$migrate_BANG_.invokeStatic(db.clj:194)
	at metabase.db$migrate_BANG_.invoke(db.clj:173)
	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:329)
	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:323)
	at metabase.db$setup_db_BANG__STAR_$fn__21342.invoke(db.clj:346)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:649)
	at metabase.util$do_with_us_locale.invoke(util.clj:635)
	at metabase.db$setup_db_BANG__STAR_.invokeStatic(db.clj:344)
	at metabase.db$setup_db_BANG__STAR_.invoke(db.clj:339)
	at metabase.db$setup_db_from_env_BANG__STAR_.invokeStatic(db.clj:354)
	at metabase.db$setup_db_from_env_BANG__STAR_.invoke(db.clj:351)
	at metabase.db$setup_db_BANG_$fn__21353.invoke(db.clj:368)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:366)
	at metabase.db$setup_db_BANG_.invoke(db.clj:361)
	at metabase.core$init_BANG_.invokeStatic(core.clj:77)
	at metabase.core$init_BANG_.invoke(core.clj:56)
	at metabase.core$start_normally.invokeStatic(core.clj:123)
	at metabase.core$start_normally.invoke(core.clj:117)
	at metabase.core$_main.invokeStatic(core.clj:156)
	at metabase.core$_main.doInvoke(core.clj:150)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: cannot execute CREATE TABLE in a read-only transaction
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:269)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
	... 44 more
04-28 19:17:00 INFO metabase.core :: Metabase Shutting Down ...
04-28 19:17:00 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
04-28 19:17:00 INFO metabase.core :: Metabase Shutdown COMPLETE`
