### ISSUE TITLE
how to build drivers since bin/build-drivers was removed

### ISSUE THREAD

**Issue by ericcj** [metabase/metabase#40754]
### Describe the bug

We upgraded from 0.48.8 to 0.49.2 and this broke https://github.com/ericcj/metabase-netsuite-driver because connection-details->spec is being called on its parent oracle driver instead of itself.  could you help me figure out what i need to implement/change to fix it?  I didn't see any updates to https://www.metabase.com/docs/latest/developers-guide/drivers/basics or https://github.com/metabase/sample-driver or https://github.com/metabase/metabase/releases/tag/v0.49.0

```
 :stacktrace
 ["--> driver.oracle$fn__117229.invokeStatic(oracle.clj:158)"
  "driver.oracle$fn__117229.invoke(oracle.clj:154)"
  "driver.sql_jdbc.connection$create_pool_BANG_.invokeStatic(connection.clj:168)"
  "driver.sql_jdbc.connection$create_pool_BANG_.invoke(connection.clj:160)"
  "driver.sql_jdbc.connection$db__GT_pooled_connection_spec.invokeStatic(connection.clj:288)"
  "driver.sql_jdbc.connection$db__GT_pooled_connection_spec.invoke(connection.clj:228)"
  "driver.sql_jdbc.execute$datasource.invokeStatic(execute.clj:197)"
  "driver.sql_jdbc.execute$datasource.invoke(execute.clj:193)"
  "driver.sql_jdbc.execute$datasource_with_diagnostic_info_BANG_.invokeStatic(execute.clj:204)"
  "driver.sql_jdbc.execute$datasource_with_diagnostic_info_BANG_.invoke(execute.clj:199)"
  "driver.sql_jdbc.execute$do_with_resolved_connection_data_source.invokeStatic(execute.clj:296)"
  "driver.sql_jdbc.execute$do_with_resolved_connection_data_source.invoke(execute.clj:255)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:333)"
  "driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317)"
  "driver.sql_jdbc.execute$fn__79060.invokeStatic(execute.clj:382)"
  "driver.sql_jdbc.execute$fn__79060.invoke(execute.clj:380)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:692)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
  "driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:689)"
  "driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:678)"
  "driver.sql_jdbc$fn__106640.invokeStatic(sql_jdbc.clj:78)"
  "driver.sql_jdbc$fn__106640.invoke(sql_jdbc.clj:76)"
  "driver.oracle$fn__117379.invokeStatic(oracle.clj:507)"
  "driver.oracle$fn__117379.invoke(oracle.clj:505)"
  "query_processor.context$executef.invokeStatic(context.clj:60)"
  "query_processor.context$executef.invoke(context.clj:49)"
  "query_processor.context.default$default_runf.invokeStatic(default.clj:44)"
  "query_processor.context.default$default_runf.invoke(default.clj:42)"
  "query_processor.context$runf.invokeStatic(context.clj:46)"
  "query_processor.context$runf.invoke(context.clj:40)"
  "query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)"
  "query_processor.reducible$identity_qp.invoke(reducible.clj:36)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:202)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:186)"
  "query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___72155.invoke(cache.clj:228)"
  "query_processor.middleware.permissions$check_query_permissions$fn__66533.invoke(permissions.clj:140)"
  "query_processor.middleware.enterprise$check_download_permissions_middleware$fn__71976.invoke(enterprise.clj:51)"
  "query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__71986.invoke(enterprise.clj:64)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71418.invoke(mbql_to_native.clj:24)"
  "query_processor$fn__73323$combined_post_process__73328$combined_post_process_STAR___73329.invoke(query_processor.clj:262)"
  "query_processor$fn__73323$combined_pre_process__73324$combined_pre_process_STAR___73325.invoke(query_processor.clj:259)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__66630.invoke(fetch_source_query.clj:303)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72066$fn__72070.invoke(resolve_database_and_driver.clj:77)"
  "driver$do_with_driver.invokeStatic(driver.clj:97)"
  "driver$do_with_driver.invoke(driver.clj:92)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72066.invoke(resolve_database_and_driver.clj:76)"
  "query_processor.middleware.store$initialize_store$fn__67236$fn__67237.invoke(store.clj:14)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.middleware.store$initialize_store$fn__67236.invoke(store.clj:13)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__72063.invoke(resolve_database_and_driver.clj:60)"
  "query_processor.middleware.normalize_query$normalize$fn__72368.invoke(normalize_query.clj:38)"
  "query_processor.middleware.enterprise$fn__72003$handle_audit_app_internal_queries__72004$fn__72006.invoke(enterprise.clj:96)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__72014.invoke(enterprise.clj:103)"
  "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__71129.invoke(constraints.clj:104)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__72299.invoke(process_userland_query.clj:156)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__72900.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___62764$thunk__62766.invoke(reducible.clj:126)"
  "query_processor.reducible$async_qp$qp_STAR___62764$fn__62768.invoke(reducible.clj:131)"],
 :card_id 1351,
 :context :question,
 :error "Assert failed: (or sid service-name)",


### To Reproduce

Use netsuite driver with v0.49

### Expected behavior

_No response_

### Logs

_No response_

### Information about your Metabase installation

```JSON
v0.49
```

### Severity

blocking an upgrade

**Comment by ericcj** [comment]
oh i figured out it was because i had unused honeysql 1 imports:  FileNotFoundException: Could not locate honeysql/core__init.class, honeysql/core.clj or honeysql/core.cljc on classpath

but now i'm stuck building any tips for how to fix this:

thwomp:metabase-netsuite-driver ej$ clojure -X:build :project-dir "\"$(pwd)\""
Error building classpath. Local lib metabase/build-drivers not found: /Users/ej/metabase/bin/build-drivers

**Comment by bshepherdson** [comment]
That looks like you need to run the script in your local Metabase dir to compile the core drivers: `./bin/build-drivers.sh`.

See [the docs](https://www.metabase.com/docs/latest/developers-guide/devenv#building-drivers) for more.

I suppose dropping HoneySQL 1 from Metabase itself counts as a driver API change. External drivers might rely on that dependency to be present, and they need to specify it themselves or use HoneySQL 2.

**Comment by ericcj** [comment]
build-drivers.sh works fine but that's just for the internal metabase drivers.  it looks like https://github.com/metabase/sample-driver?tab=readme-ov-file#usage hasn't been updated so i used the instructions from https://github.com/metabase/sudoku-driver/blob/master/README.md#build-it-updated-for-build-script-changes-in-metabase-0460 but i'm not sure how to tell it to include modules/drivers/oracle/src in my path since netsuite depends on it as a parent:

```
thwomp:metabase ej$ bin/build-drivers.sh
...
  Successfully built all drivers.
thwomp:metabase ej$ DRIVER_PATH=`readlink -f ~/metabase-netsuite-driver`
thwomp:metabase ej$ clojure \
>   -Sdeps "{:aliases {:sudoku {:extra-deps {com.metabase/sudoku-driver {:local/root \"$DRIVER_PATH\"}}}}}"  \
>   -X:build:sudoku \
>   build-drivers.build-driver/build-driver! \
>   "{:driver :sudoku, :project-dir \"$DRIVER_PATH\", :target-dir \"$DRIVER_PATH/target\"}"
thwomp:metabase ej$
thwomp:metabase ej$ clojure \
>   -Sdeps "{:aliases {:metabase-netsuite-driver {:extra-deps {com.metabase/metabase-netsuite-driver-driver {:local/root \"$DRIVER_PATH\"}}}}}"  \
>   -X:build:metabase-netsuite-driver \
>   build-drivers.build-driver/build-driver! \
>   "{:driver :metabase-netsuite-driver, :project-dir \"$DRIVER_PATH\", :target-dir \"$DRIVER_PATH/target\"}"
Build driver :metabase-netsuite-driver (edition = :oss, options = {:project-dir "/Users/ej/metabase-netsuite-driver", :target-dir "/Users/ej/metabase-netsuite-driver/target"})
  Clean
    Delete /Users/ej/metabase-netsuite-driver/target/jar if exists
      Deleted /Users/ej/metabase-netsuite-driver/target/jar.
    Delete /Users/ej/metabase-netsuite-driver/target/metabase-netsuite-driver.metabase-driver.jar if exists
      Don't need to delete /Users/ej/metabase-netsuite-driver/target/metabase-netsuite-driver.metabase-driver.jar, file does not exist.
  Copy :metabase-netsuite-driver source files
    Copying files in ["/Users/ej/metabase-netsuite-driver/src" "/Users/ej/metabase-netsuite-driver/resources"]
    Copied files in 2 directories in 103 ms.
  Compile clojure source files
    Compiling Clojure source files in ["/Users/ej/metabase-netsuite-driver/src" "/Users/ej/metabase-netsuite-driver/resources"] to /Users/ej/metabase-netsuite-driver/target/jar
    Create directory /Users/ej/metabase-netsuite-driver/target/jar if it does not exist
      /Users/ej/metabase-netsuite-driver/target/jar already exists.
    Compiling namespaces [metabase.driver.netsuite]
2024-03-30 09:42:25,913 INFO metabase.util :: Maximum memory available to JVM: 16.0 GB
operator.clj:172 recur arg for primitive local: sum is not matching primitive, had: Object, needed: long
Auto-boxing loop arg: sum
2024-03-30 09:42:45,783 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2024-03-30 09:42:50,131 WARN db.env :: WARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. For more information, see https://metabase.com/docs/latest/operations-guide/migrating-from-h2.html
Reflection warning, clojurewerkz/quartzite/triggers.clj:85:6 - call to method forJob on org.quartz.TriggerBuilder can't be resolved (argument types: unknown).
Reflection warning, clojurewerkz/quartzite/scheduler.clj:254:3 - call to method checkExists on org.quartz.Scheduler can't be resolved (argument types: unknown).
2024-03-30 09:42:59,854 INFO driver.impl :: Registered abstract driver :sql  🚚
2024-03-30 09:43:10,278 ERROR driver.impl :: Error loading driver namespace
clojure.lang.ExceptionInfo: Could not locate metabase/driver/oracle__init.class, metabase/driver/oracle.clj or metabase/driver/oracle.cljc on classpath. {:classloader #object[clojure.lang.DynamicClassLoader 0x6eaded2a "clojure.lang.DynamicClassLoader@6eaded2a"], :classpath-urls (), :system-classpath (... "/Users/ej/NetSuiteJDBCDrivers/NQjc.jar" "/Users/ej/metabase-netsuite-driver/resources" "/Users/ej/metabase-netsuite-driver/src" "/opt/homebrew/Cellar/clojure/1.11.1.1189/libexec/exec.jar" "bin/build/resources" "bin/build/src" "resources" "src")}
	at metabase.plugins.classloader$require_STAR_.invokeStatic(classloader.clj:132)
	at metabase.plugins.classloader$require_STAR_.doInvoke(classloader.clj:116)
...
	at clojure.main.main(main.java:40)
Caused by: java.io.FileNotFoundException: Could not locate metabase/driver/oracle__init.class, metabase/driver/oracle.clj or metabase/driver/oracle.cljc on classpath.
	at clojure.lang.RT.load(RT.java:462)
	... 82 more
Step failed: Syntax error macroexpanding at (metabase/driver/netsuite.clj:22:1).
{:via
 [{:type clojure.lang.Compiler$CompilerException,
   :message "Syntax error macroexpanding at (metabase/driver/netsuite.clj:22:1).",
   :data #:clojure.error{:phase :execution, :line 22, :column 1, :source "metabase/driver/netsuite.clj"},
   :at [clojure.lang.Compiler load "Compiler.java" 7665]}
  {:type java.lang.Exception,
   :message "Could not load :oracle driver.",
   :at [metabase.driver.impl$require_driver_ns invokeStatic "impl.clj" 82]}
  {:type clojure.lang.ExceptionInfo,
   :message
   "Could not locate metabase/driver/oracle__init.class, metabase/driver/oracle.clj or metabase/driver/oracle.cljc on classpath.",
   :data
   {:classloader #object[clojure.lang.DynamicClassLoader 0x6eaded2a "clojure.lang.DynamicClassLoader@6eaded2a"],
    :classpath-urls (),
    :system-classpath
    (...
     "/Users/ej/NetSuiteJDBCDrivers/NQjc.jar"
     "/Users/ej/metabase-netsuite-driver/resources"
     "/Users/ej/metabase-netsuite-driver/src"
     "/opt/homebrew/Cellar/clojure/1.11.1.1189/libexec/exec.jar"
     "bin/build/resources"
     "bin/build/src"
     "resources"
     "src")},
   :at [metabase.plugins.classloader$require_STAR_ invokeStatic "classloader.clj" 132]}
  {:type java.io.FileNotFoundException,
   :message
   "Could not locate metabase/driver/oracle__init.class, metabase/driver/oracle.clj or metabase/driver/oracle.cljc on classpath.",
   :at [clojure.lang.RT load "RT.java" 462]}],
 :trace
 [[clojure.lang.RT load "RT.java" 462]
 ...
  [clojure.main main "main.java" 40]],
 :cause
 "Could not locate metabase/driver/oracle__init.class, metabase/driver/oracle.clj or metabase/driver/oracle.cljc on classpath.",
 :phase :execution}
    Step "Compile clojure source files" failed with error "Syntax error macroexpanding at (metabase/driver/netsuite.clj:22:1)."

**Comment by ericcj** [comment]
I think I got it working in https://github.com/ericcj/metabase-netsuite-driver/commit/9a1c1ca5910d5b62d5fb55ce5a76ef237945e27e but it's pretty hairy is there a simpler recommended way to build external drivers?

**Comment by camsaul** [comment]
Adapting the example in https://github.com/metabase/sudoku-driver/tree/master?tab=readme-ov-file#build-it-updated-for-build-script-changes-in-metabase-0460 is still the recommended way to build third-party drivers, if you need to include other e.g. Oracle as a parent then you can include more `:extra-deps` when you run the build script, check out the [Clojure deps documentation](https://clojure.org/guides/deps_and_cli#local_jar) for more info about how this stuff works. I think something like this should do the trick:

```sh
ORACLE_PATH=/path/to/metabase/modules/drivers/oracle

clojure \
  -Sdeps "{:aliases {:netsuite {:extra-deps {com.metabase/netsuite-driver {:local/root \"$DRIVER_PATH\"}}} :oracle {:extra-deps {com.metabase/oracle-driver {:local/root \"$ORACLE_PATH\"}}}}}"  \
  -X:build:netsuite:oracle \
  build-drivers.build-driver/build-driver! \
  "{:driver :netsuite, :project-dir \"$DRIVER_PATH\", :target-dir \"$DRIVER_PATH/target\"}"
```

I don't think you want to include oracle as a dep in your `deps.edn` or it's going to copy the compiled Oracle files and JDBC driver dep into your driver which is going to potentially cause problems if people try to use both drivers at the same time since we'll have two copies of the Oracle classes. You do need to add 

```yaml
driver:
  parent: oracle
```

to your `resources/metabase-plugin.yaml` tho, then when Metabase loads your driver it will load the Oracle stuff first.

You can verify that your build driver doesn't contain the Oracle stuff by doing `jar -tf my-driver.jar` and making sure there aren't any  `metabase/driver/oracle` files in there.

Let me know if you have any more questions.

**Comment by camsaul** [comment]
I should also mention `bin/build-drivers` was not removed, it was just renamed to `bin/build-drivers.sh`
