### ISSUE TITLE
Dashboards are broken

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#41071]
### Describe the bug

https://github.com/metabase/metabase/assets/6830683/4a10c7e8-68ec-4d4e-bc44-deb709c56318

### To Reproduce

1. Create a new dashboard
2. Add a question to it
3. Save the dashboard
4. Refresh the page
5. See the error

### Expected behavior

Page does not crash

### Information about your Metabase installation

master, 199e069

Also reproducible in stats

### Severity

P1

**Comment by kamilmielnik** [comment]
[`composeQuestionAdhoc`](https://github.com/metabase/metabase/blob/448a4f3/frontend/src/metabase/questions/actions.ts#L22) fails with:
```
Uncaught Error: No method in multimethod 'metabase.lib.query/query-method' for dispatch value: :dispatch-type/nil
    at Object.cljs$core$throw_no_method_error [as throw_no_method_error] (app-main.hot.bundle.js:487039:8)
    at Object.cljs$core$IFn$_invoke$arity$2 (app-main.hot.bundle.js:487199:11)
    at Function.metabase$lib$query$query (app-main.hot.bundle.js:611222:40)
    at Function.cljs$core$IFn$_invoke$arity$4 (app-main.hot.bundle.js:463502:10)
    at Function.cljs$core$IFn$_invoke$arity$3 (app-main.hot.bundle.js:463493:34)
    at Function.cljs$core$IFn$_invoke$arity$2 (app-main.hot.bundle.js:463481:34)
    at Function.cljs$core$IFn$_invoke$arity$2 (app-main.hot.bundle.js:463763:34)
    at Function.metabase$lib$core$query__delegate [as cljs$core$IFn$_invoke$arity$variadic] (app-main.hot.bundle.js:586661:24)
    at Function.cljs$core$IFn$_invoke$arity$2 (app-main.hot.bundle.js:603043:32)
    at Object.metabase$lib$js$query (app-main.hot.bundle.js:603028:30)
```

**Comment by kamilmielnik** [comment]
Broken by #40181
