### ISSUE TITLE
Validation fault on downgrade from v0.49.2 to v0.48.8

### ISSUE THREAD

**Issue by ssxota** [metabase/metabase#41295]
### Describe the bug

I'm hosting metabase on GKE and tried to downgrade the version from 0.49.2 to 0.48.8.
I ran the migrate down command in my container and changed the container image version back to v0.48.8, but I get a validation error.

### To Reproduce

1. Execute the following command in my pod
`./run_metabase.sh "migrate down"`
2. Change the container image  from metabase/metabase:v0.49.2 To metabase/metabase:v0.48.8

### Expected behavior

Down grade is successfully completed.

### Logs

Log  at execute "migrate down" command.
```Warning: environ value jdk-11.0.22+7 for key :java-version has been overwritten with 11.0.22
2024-04-02 02:47:20,767 INFO metabase.util :: Maximum memory available to JVM: 494.9 MB
2024-04-02 02:47:34,083 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2024-04-02 02:48:08,179 INFO driver.impl :: Registered abstract driver :sql  🚚
2024-04-02 02:48:08,285 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
2024-04-02 02:48:08,368 INFO metabase.util :: Load driver :sql-jdbc took 660.4 ms
2024-04-02 02:48:08,369 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
2024-04-02 02:48:09,463 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
2024-04-02 02:48:09,686 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
2024-04-02 02:48:18,070 INFO metabase.core :: 
Metabase v0.49.2 (4b83b88) 

Copyright © 2024 Metabase, Inc. 

Metabase Enterprise Edition extensions are NOT PRESENT.
2024-04-02 02:48:19,074 INFO db.setup :: Setting up Liquibase...
2024-04-02 02:48:23,200 INFO db.setup :: Liquibase is ready.
2024-04-02 02:48:23,270 INFO db.liquibase :: Rolling back app database schema to version 48
2024-04-02 02:48:25,686 INFO db.custom-migrations :: No rollback for:  DeleteTruncateAuditLogTask
```

Log at launch on v0.48.8.

```
2024-04-02 02:58:22,471 INFO db.setup :: Verifying postgres Database Connection ...
2024-04-02 02:58:23,474 INFO db.setup :: Successfully verified PostgreSQL 13.13 application database connection. ✅
2024-04-02 02:58:23,474 INFO db.setup :: Checking if a database downgrade is required...
2024-04-02 02:58:26,491 INFO db.setup :: Running Database Migrations...
2024-04-02 02:58:26,492 INFO db.setup :: Setting up Liquibase...
2024-04-02 02:58:27,662 INFO db.setup :: Liquibase is ready.
2024-04-02 02:58:27,662 INFO db.liquibase :: Checking if Database has unrun migrations...
2024-04-02 02:58:30,071 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.ValidationFailedException: Validation Failed:
    203 changesets check sum
         migrations/001_update_migrations.yaml::v00.00-000::qnkhuat was: 9:e346841fa1cd9d142e1237b37fdc8a20 but is now: 8:a59595109e74e7a2678a1b0dfd25f74a
         migrations/001_update_migrations.yaml::v45.00-001::snoe was: 9:15c13a8aa3fdc72ef0c54f4cccfc39e1 but is now: 8:da99b71a4ac7eb662f6a95e69585935e
         migrations/001_update_migrations.yaml::v45.00-002::snoe was: 9:d2c9f50f5a29947a07e4808957d63ab6 but is now: 8:6da7a6285edb138c404de0eeba209570
         migrations/001_update_migrations.yaml::v45.00-003::snoe was: 9:dafaaf7c9f0efbf92670ea93c001f7a1 but is now: 8:512337d6d4af38016aa79585abbe03a1
         migrations/001_update_migrations.yaml::v45.00-011::snoe was: 9:c539f152aa1c2287c5b602c7a395f9e8 but is now: 8:dcf1cda9f20dca4b6ff8101b13b98c4a
         migrations/001_update_migrations.yaml::v45.00-012::snoe was: 9:b872219f47d12ec80db8f1731be4ce94 but is now: 8:aadf28229f585cff7c4b4c1918e558b2
         migrations/001_update_migrations.yaml::v45.00-013::snoe was: 9:54c5d6a9659b7ae62e8c42f60f9620d2 but is now: 8:26dba276b14255d4346507a1a25d117b
         migrations/001_update_migrations.yaml::v45.00-022::snoe was: 9:06e8a3ba8c4c5e5cf8e6aa3f35081cac but is now: 8:d46fa24e4d75a11b2e92aecbf39c6ee1
         migrations/001_update_migrations.yaml::v45.00-023::snoe was: 9:082d296233ee6dbbf2871b9d93c3a6a4 but is now: 8:c6c1ff9ca3b62d4cda3a2d782dd86f2f
         migrations/001_update_migrations.yaml::v45.00-025::metamben was: 9:2214b0d71acc8a8cf90781a2aca98664 but is now: 8:50a43cea3123ecdb602123825f5a7dbf
         migrations/001_update_migrations.yaml::v45.00-026::snoe was: 9:9f2ce2d2d79d0dce365ddf3464d1f648 but is now: 8:ae77d4086998911877e3207fcf90c9c7
         migrations/001_update_migrations.yaml::v45.00-027::snoe was: 9:73718f7b7c3fb4ef30f71dc6e6170528 but is now: 8:40c3c8391c1416a3bce09ca3c7237173
         migrations/001_update_migrations.yaml::v45.00-028::camsaul was: 9:883315d70f3fc10b07858aa0e48ed9da but is now: 8:f8f68f80627aeb2ef7f28f2af2b5a31b
         migrations/001_update_migrations.yaml::v45.00-029::camsaul was: 9:fe3b8aca811ef5b541f922a83c7ded8c but is now: 8:579957652133eab3ee023dd911162a1e
         migrations/001_update_migrations.yaml::v45.00-030::camsaul was: 9:63da8f2f82baf396ad30f3fd451c501d but is now: 8:41eda097feb034c4d01b2dbda74753c8
         migrations/001_update_migrations.yaml::v45.00-031::camsaul was: 9:3628c1c692bec0f7258ea983b18340b5 but is now: 8:6416e373e335dc1c12c7571af674dede
         migrations/001_update_migrations.yaml::v45.00-032::camsaul was: 9:7a6f0320210b82c5eafe836ea98f477d but is now: 8:d97444fe24a2dca618a2804741335f6d
         migrations/001_update_migrations.yaml::v45.00-033::camsaul was: 9:b93dab321e4a1fcaeb74d12b52867fd4 but is now: 8:34df79fc79e086ab05bb2fd79bb4e322
         migrations/001_update_migrations.yaml::v45.00-034::camsaul was: 9:39c965f9dc521d2a1e196f645d11de9e but is now: 8:ba0505a87ef876026759cdcb4e704f41
         migrations/001_update_migrations.yaml::v45.00-035::camsaul was: 9:207984e21c44681a6135592cab3d0f3f but is now: 8:dcee49781d80d9c4be5ad9dd51975a07
         migrations/001_update_migrations.yaml::v45.00-036::snoe was: 9:8632f7a046e1094399c517b05f0feea3 but is now: 8:cd4009254bd2c56aaf281082038c1f0b
         migrations/001_update_migrations.yaml::v45.00-037::snoe was: 9:6600702fb0cc9dcd8628fca8df9c0b39 but is now: 8:56f548cc84a53cc6d18302761ee71554
         migrations/001_update_migrations.yaml::v45.00-038::camsaul was: 9:5ae52c12861e5eec6a2a9a8c5a442826 but is now: 8:c38ddc295206e807c7254581ed9566c3
         migrations/001_update_migrations.yaml::v45.00-039::camsaul was: 9:7b331f47a0260218275c58fa21fdcc60 but is now: 8:2c539d76d3aead7f7366b15333132b30
         migrations/001_update_migrations.yaml::v45.00-040::camsaul was: 9:6d6fb2c7cd62868b9878a951c8596cec but is now: 8:00ac7c24cfd3e7ea3a21f21f4e45dbcf
         migrations/001_update_migrations.yaml::v45.00-041::camsaul was: 9:84d479472b81809b8067f72b28934954 but is now: 8:82dc368fa3e0163a06929da6e9556fe2

       at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:354)
       at liquibase.Liquibase.lambda$listUnrunChangeSets$16(Liquibase.java:1287)
       at liquibase.Scope.lambda$child$0(Scope.java:194)
       at liquibase.Scope.child(Scope.java:203)
       at liquibase.Scope.child(Scope.java:193)
       at liquibase.Scope.child(Scope.java:172)
       at liquibase.Liquibase.runInScope(Liquibase.java:1618)
       at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1279)
       at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1270)
       at metabase.db.liquibase$unrun_migrations$fn__47763.invoke(liquibase.clj:180)
       at metabase.db.liquibase$do_with_liquibase$f_STAR___47748.invoke(liquibase.clj:134)
       at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:137)
       at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:125)
       at metabase.db.liquibase$unrun_migrations.invokeStatic(liquibase.clj:179)
       at metabase.db.liquibase$unrun_migrations.invoke(liquibase.clj:170)
       at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:225)
       at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:221)
       at metabase.db.setup$migrate_BANG_$fn__49980.invoke(setup.clj:80)
       at metabase.db.liquibase$do_with_liquibase$f_STAR___47748.invoke(liquibase.clj:134)
       at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:137)
       at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:125)
       at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:75)
       at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:56)
       at clojure.lang.RestFn.invoke(RestFn.java:445)
       at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:148)
       at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:142)
       at metabase.db.setup$setup_db_BANG_$fn__50010$fn__50011.invoke(setup.clj:166)
       at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
       at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
       at metabase.db.setup$setup_db_BANG_$fn__50010.invoke(setup.clj:161)
       at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
       at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:154)
       at metabase.db$setup_db_BANG_$fn__50024.invoke(db.clj:69)
       at metabase.db$setup_db_BANG_.invokeStatic(db.clj:64)
       at metabase.db$setup_db_BANG_.invoke(db.clj:55)
       at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:113)
       at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
       at metabase.core$init_BANG_.invokeStatic(core.clj:156)
       at metabase.core$init_BANG_.invoke(core.clj:151)
       at metabase.core$start_normally.invokeStatic(core.clj:168)
       at metabase.core$start_normally.invoke(core.clj:162)
       at metabase.core$entrypoint.invokeStatic(core.clj:201)
       at metabase.core$entrypoint.doInvoke(core.clj:195)
       at clojure.lang.RestFn.invoke(RestFn.java:397)
       at clojure.lang.AFn.applyToHelper(AFn.java:152)
       at clojure.lang.RestFn.applyTo(RestFn.java:132)
       at clojure.lang.Var.applyTo(Var.java:705)
       at clojure.core$apply.invokeStatic(core.clj:667)
       at clojure.core$apply.invoke(core.clj:662)
       at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
       at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
       at clojure.lang.RestFn.invoke(RestFn.java:397)
       at clojure.lang.AFn.applyToHelper(AFn.java:152)
       at clojure.lang.RestFn.applyTo(RestFn.java:132)
       at metabase.bootstrap.main(Unknown Source)
2024-04-02 02:58:30,170 INFO metabase.core :: Metabase Shutting Down ...
2024-04-02 02:58:30,264 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2024-04-02 02:58:30,376 INFO metabase.core :: Metabase Shutdown COMPLETE 
```

### Information about your Metabase installation

```JSON
- Metabase:version : 0.49.2
- Metabase:hosting environment : GKE
- Metabase:intenal database : CloudSQL(PostgreSQL 13)
```

### Severity

If there is a bug in a version up image, the previous stable version cannot be provided to the user.

**Comment by paoliniluis** [comment]
@ssxota is this the same as https://github.com/metabase/metabase/issues/41641? please confirm and close the issue if that's the case
