### ISSUE TITLE
Question with Progress visualisation shows 'Something went wrong'

### ISSUE THREAD

**Issue by tritatuy** [metabase/metabase#41308]
### Describe the bug

After updating to 0.49.1 we faced with this bug in Progress visualisation:
1. I created a native SQL-question to ClickHouse.
2. Then I created a question to that question:
<img width="533" alt="Screenshot at Apr 11 15-24-57" src="https://github.com/metabase/metabase/assets/74110979/7fdfe004-ed9a-43ed-8e47-782f257bb399">

3. Then I see error in progress visualisation:
<img width="717" alt="Screenshot at Apr 11 15-25-59" src="https://github.com/metabase/metabase/assets/74110979/64cd2b3c-55f4-43c5-ac5c-24cd6b295b6d">

4. If I save this question and then add it to a dashboard it works ok. So the issue is only when you open a question separately.
It is necessary for us to use progress, because we add an alert there.

### To Reproduce

1. Create a SQL-question to Clickhouse
2. Create a question to the previous question
3. Select progress visualisation and enter Goal = 1

### Expected behavior

I expect to see gauge visualisation instead of the error.

### Logs

```
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:31+04:00 INFO metabase.query-processor.card Средняя продолжительность выполнения запроса: 13,2 s; используя ' magic ' TTL из 43,8 mins 💾
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:37+04:00 INFO metabase.server.middleware.exceptions Запрос отменен до завершения.
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 22,5 ms (10 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (219 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 27,0 ms (7 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 12,0 ms (2 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/search 200 89,7 ms (5 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/database 200 30,1 ms (3 вызовы БД) Соединения с БД приложения: 3 / 15 Потоки Jetty: 6 / 50 (1 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 59,7 ms (6 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (1 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/bookmark 200 3,2 ms (1 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/card/1702 200 43,1 ms (13 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (1 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/timeline 200 4,3 ms (3 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/alert/question/1702 200 1,6 ms (1 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/database/14/schemas 200 25,6 ms (4 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 6 / 50 (1 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:42+04:00 DEBUG metabase.server.middleware.log GET /api/table/card__1695/query_metadata 200 23,6 ms (7 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 6 / 50 (1 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:43+04:00 DEBUG metabase.server.middleware.log GET /api/collection/327 200 20,3 ms (5 вызовы БД) Соединения с БД приложения: 4 / 15 Потоки Jetty: 6 / 50 (1 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:43+04:00 DEBUG metabase.server.middleware.log GET /api/card/1695 200 29,6 ms (13 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (1 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:43+04:00 INFO metabase.query-processor.card Средняя продолжительность выполнения запроса: 7,3 s; используя ' magic ' TTL из 24,5 mins 💾
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:43+04:00 DEBUG metabase.server.middleware.log GET /api/collection/296 200 17,0 ms (4 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 2 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:43+04:00 DEBUG metabase.server.middleware.log GET /api/collection/326 200 17,5 ms (5 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 2 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:45+04:00 INFO metabase.query-processor.middleware.cache Query took 2,4 s to run; minimum for cache eligibility is 10,0 s; not eligible
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:45+04:00 DEBUG metabase.server.middleware.log POST /api/card/1702/query 202 [АСИНХРОННЫЙ: completed] 2,4 s (11 вызовы БД) Соединения с БД приложения: 3 / 15 Потоки Jetty: 2 / 50 (4 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди); clickhouse DB 14 connections: 1/1 (0 threads blocked)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:45+04:00 DEBUG metabase.server.middleware.log GET /api/database/14 200 5,5 ms (3 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (4 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 1 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:49+04:00 INFO metabase.query-processor.middleware.cache Query took 18,1 s to run; minimum for cache eligibility is 10,0 s; eligible
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:49+04:00 INFO metabase.query-processor.middleware.cache Кэширование результатов в следующий раз для запроса с хешем "a9a2865d". 💾
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:49+04:00 DEBUG metabase.server.middleware.log POST /api/dashboard/177/dashcard/1857/card/2008/query 202 [АСИНХРОННЫЙ: completed] 18,4 s (26 вызовы БД) Соединения с БД приложения: 3 / 15 Потоки Jetty: 2 / 50 (4 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 0 (0 в очереди); clickhouse DB 14 connections: 0/1 (0 threads blocked)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:51+04:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 12,9 ms (10 вызовы БД) Соединения с БД приложения: 3 / 15 Потоки Jetty: 4 / 50 (3 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:51+04:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 15,8 ms (6 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (3 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:52+04:00 DEBUG metabase.server.middleware.log GET /api/bookmark 200 3,1 ms (1 вызовы БД) Соединения с БД приложения: 6 / 15 Потоки Jetty: 7 / 50 (0 бездействует, 0 в очереди) (220 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:52+04:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 27,2 ms (2 вызовы БД) Соединения с БД приложения: 5 / 15 Потоки Jetty: 8 / 50 (0 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:52+04:00 DEBUG metabase.server.middleware.log GET /api/database 200 32,3 ms (3 вызовы БД) Соединения с БД приложения: 4 / 15 Потоки Jetty: 5 / 50 (2 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:52+04:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 47,0 ms (6 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 4 / 50 (3 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:52+04:00 DEBUG metabase.server.middleware.log GET /api/search 200 63,1 ms (5 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (4 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:52+04:00 DEBUG metabase.server.middleware.log GET /api/setting 200 26,4 ms (12 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 4 / 50 (4 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:52+04:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 17,2 ms (6 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 4 / 50 (4 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:42:52+04:00 DEBUG metabase.server.middleware.log GET /api/setup/admin_checklist 200 8,6 ms (9 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (5 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:01+04:00 DEBUG metabase.server.middleware.log GET /api/permissions/group 200 3,5 ms (2 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (5 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:01+04:00 DEBUG metabase.server.middleware.log GET /api/user 200 13,4 ms (5 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (5 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:01+04:00 DEBUG metabase.server.middleware.log GET /api/permissions/membership 200 24,5 ms (1 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (5 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:03+04:00 ERROR metabase.models.permissions.parse Ошибка анализа дерева разрешений Parse error at line 1, column 1:
/application/subscription/
^
Expected one of:
"/" (followed by end-of-string)
"/query/db/"
"/data/db/"
"/collection/"
"/details"
"/data-model"
"/download"
"/block/db/"
"/db/"
"/execute/"

[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:03+04:00 DEBUG metabase.server.middleware.log GET /api/permissions/graph/group/2 200 14,5 ms (3 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 4 / 50 (4 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:03+04:00 DEBUG metabase.server.middleware.log GET /api/permissions/graph/group/1 200 23,7 ms (3 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (4 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:04+04:00 DEBUG metabase.server.middleware.log GET /api/persist 200 17,9 ms (2 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (5 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:05+04:00 DEBUG metabase.server.middleware.log GET /api/util/bug_report_details 200 11,9 ms (1 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (5 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:12+04:00 DEBUG metabase.server.middleware.log GET /api/card/2008 200 23,6 ms (13 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (5 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:13+04:00 DEBUG metabase.server.middleware.log GET /api/alert/question/2008 200 1,4 ms (1 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (5 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:29+04:00 INFO metabase.integrations.slack Refreshing slack channels and usernames.
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:29+04:00 DEBUG metabase.server.middleware.log GET /api/pulse/form_input 200 25,5 ms (2 вызовы БД) Соединения с БД приложения: 2 / 15 Потоки Jetty: 3 / 50 (5 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:29+04:00 INFO metabase.query-processor.card Средняя продолжительность выполнения запроса: 13,7 s; используя ' magic ' TTL из 45,6 mins 💾
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:29+04:00 DEBUG metabase.server.middleware.log POST /api/dashboard/177/dashcard/1857/card/2008/query 202 [АСИНХРОННЫЙ: completed] 272,3 ms (23 вызовы БД) Соединения с БД приложения: 3 / 15 Потоки Jetty: 3 / 50 (5 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
[55e24841-dd2e-400b-a342-e7ac95be56ff] 2024-04-11T15:43:32+04:00 DEBUG metabase.server.middleware.log GET /api/alert/question/2008 200 1,5 ms (1 вызовы БД) Соединения с БД приложения: 3 / 15 Потоки Jetty: 3 / 50 (5 бездействует, 0 в очереди) (221 всего активных тем) Запросы в полете: 0 (0 в очереди)
```

```
analytics.js:24 Refused to load the script 'https://www.googletagmanager.com/gtag/js?id=G-29NY6M1W10&cx=c&_slc=1' because it violates the following Content Security Policy directive: "script-src 'self' https://maps.google.com https://accounts.google.com https://www.google-analytics.com   'sha256-9uFLu5CG8mWlvx0LK6lgendCxUX57TuWk3wkgZpBeWU=' 'sha256-ib2/2v5zC6gGM6Ety7iYgBUvpy/caRX9xV/pzzV7hf0=' 'sha256-isH538cVBUY8IMlGYGbWtBwr+cGqkc4mN6nLcA7lUjE='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Id @ analytics.js:24
(anonymous) @ analytics.js:75
oc @ analytics.js:37
Ea @ analytics.js:36
g.onreadystatechange @ analytics.js:35
XMLHttpRequest.send (async)
wd @ analytics.js:36
pe @ analytics.js:35
Sa @ analytics.js:41
Ha.D @ analytics.js:38
pc.send @ analytics.js:77
X.b.<computed> @ analytics.js:57
Z.v @ analytics.js:93
Z.D @ analytics.js:92
N @ analytics.js:94
m @ analytics.js:82
u @ analytics.js:27
onEnter @ routes.jsx:101
await in onEnter (async)
i @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
l @ AsyncUtils.js:34
O @ AsyncUtils.js:49
r @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
r @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
l @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
l @ AsyncUtils.js:41
O @ AsyncUtils.js:49
N @ matchRoutes.js:231
c @ createTransitionManager.js:41
r @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
componentWillMount @ Router.js:102
oB @ react-dom.production.min.js:137
iF @ react-dom.production.min.js:176
l @ react-dom.production.min.js:263
aH @ react-dom.production.min.js:246
(anonymous) @ react-dom.production.min.js:246
aW @ react-dom.production.min.js:246
ak @ react-dom.production.min.js:230
si @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
aD @ react-dom.production.min.js:240
sp @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
dR @ app.js:75
dQ @ app.js:106
84553 @ app-main.js:24
a @ bootstrap:19
(anonymous) @ app-main.6e9b1451c96b0a1b9bbd.js:243
a.O @ chunk loaded:25
(anonymous) @ app-main.6e9b1451c96b0a1b9bbd.js:243
i @ jsonp chunk loading:73
(anonymous) @ app-main.6e9b1451c96b0a1b9bbd.js:7
Show 31 more frames
Show less
Third-party cookie will be blocked. Learn more in the Issues tab.
Third-party cookie will be blocked. Learn more in the Issues tab.
Third-party cookie will be blocked. Learn more in the Issues tab.
Third-party cookie will be blocked. Learn more in the Issues tab.
Third-party cookie will be blocked. Learn more in the Issues tab.
Third-party cookie will be blocked. Learn more in the Issues tab.
metadata.js:316 loadMetadataForQueries: type question not implemented
(anonymous) @ metadata.js:316
tT @ map.js:13
eu.<computed> @ mixin.js:14
(anonymous) @ metadata.js:304
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ actions.ts:22
(anonymous) @ index.js:16
dispatch @ redux.js:691
ni @ initializeQB.ts:325
await in ni (async)
(anonymous) @ initializeQB.ts:399
(anonymous) @ index.js:16
n.<computed> @ bindActionCreators.js:8
(anonymous) @ QueryBuilder.jsx:317
(anonymous) @ useMount.js:4
i2 @ react-dom.production.min.js:211
aV @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
on @ react-dom.production.min.js:122
aQ @ react-dom.production.min.js:257
aW @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
on @ react-dom.production.min.js:122
oi @ react-dom.production.min.js:123
oo @ react-dom.production.min.js:122
aT @ react-dom.production.min.js:240
notify @ Subscription.js:16
notifyNestedSubs @ Subscription.js:88
o @ Subscription.js:93
b @ redux.js:296
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ index.js:20
dispatch @ redux.js:691
(anonymous) @ utils.js:245
setTimeout (async)
(anonymous) @ utils.js:245
await in (anonymous) (async)
i @ utils.js:335
n.type @ utils.js:202
(anonymous) @ index.js:16
(anonymous) @ redux.js:578
(anonymous) @ EntityListLoader.jsx:112
componentDidMount @ EntityListLoader.jsx:131
(anonymous) @ react-dom.production.min.js:212
a$ @ react-dom.production.min.js:213
t.unstable_runWithPriority @ scheduler.production.min.js:19
on @ react-dom.production.min.js:122
aX @ react-dom.production.min.js:248
aW @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
on @ react-dom.production.min.js:122
oi @ react-dom.production.min.js:123
oo @ react-dom.production.min.js:122
ak @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
y.setState @ react.production.min.js:12
(anonymous) @ Router.js:109
(anonymous) @ createTransitionManager.js:228
(anonymous) @ createTransitionManager.js:83
(anonymous) @ AsyncUtils.js:74
(anonymous) @ getComponents.js:6
(anonymous) @ getComponents.js:19
(anonymous) @ AsyncUtils.js:79
(anonymous) @ AsyncUtils.js:78
S @ AsyncUtils.js:83
u @ createTransitionManager.js:77
l @ AsyncUtils.js:47
(anonymous) @ TransitionUtils.js:88
(anonymous) @ TransitionUtils.js:110
onEnter @ routes.jsx:102
await in onEnter (async)
i @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
l @ AsyncUtils.js:34
O @ AsyncUtils.js:49
r @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
r @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
l @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
l @ AsyncUtils.js:41
O @ AsyncUtils.js:49
N @ matchRoutes.js:231
c @ createTransitionManager.js:41
r @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
componentWillMount @ Router.js:102
oB @ react-dom.production.min.js:137
iF @ react-dom.production.min.js:176
l @ react-dom.production.min.js:263
aH @ react-dom.production.min.js:246
(anonymous) @ react-dom.production.min.js:246
aW @ react-dom.production.min.js:246
ak @ react-dom.production.min.js:230
si @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
aD @ react-dom.production.min.js:240
sp @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
dR @ app.js:75
dQ @ app.js:106
84553 @ app-main.js:24
a @ bootstrap:19
(anonymous) @ app-main.6e9b1451c96b0a1b9bbd.js:243
a.O @ chunk loaded:25
(anonymous) @ app-main.6e9b1451c96b0a1b9bbd.js:243
i @ jsonp chunk loading:73
(anonymous) @ app-main.6e9b1451c96b0a1b9bbd.js:7
Show 89 more frames
Show less
querying.js:201 TypeError: Cannot read properties of undefined (reading 'height')
    at oy.componentDidUpdate (Progress.jsx:100:39)
    at oy.componentDidMount (Progress.jsx:86:10)
    at react-dom.production.min.js:212:132
    at a$ (react-dom.production.min.js:213:322)
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at on (react-dom.production.min.js:122:325)
    at aX (react-dom.production.min.js:248:370)
    at aW (react-dom.production.min.js:239:376)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
iJ @ react-dom.production.min.js:209
n.payload @ react-dom.production.min.js:227
oO @ react-dom.production.min.js:129
iF @ react-dom.production.min.js:179
l @ react-dom.production.min.js:263
aH @ react-dom.production.min.js:246
(anonymous) @ react-dom.production.min.js:246
aW @ react-dom.production.min.js:246
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
on @ react-dom.production.min.js:122
oi @ react-dom.production.min.js:123
oo @ react-dom.production.min.js:122
aT @ react-dom.production.min.js:240
notify @ Subscription.js:16
notifyNestedSubs @ Subscription.js:88
o @ Subscription.js:93
b @ redux.js:296
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ index.js:20
dispatch @ redux.js:691
(anonymous) @ querying.js:201
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ querying.js:138
Promise.then (async)
(anonymous) @ querying.js:129
(anonymous) @ index.js:16
dispatch @ redux.js:691
(anonymous) @ initializeQB.ts:381
setTimeout (async)
ni @ initializeQB.ts:380
await in ni (async)
(anonymous) @ initializeQB.ts:399
(anonymous) @ index.js:16
n.<computed> @ bindActionCreators.js:8
(anonymous) @ QueryBuilder.jsx:317
(anonymous) @ useMount.js:4
i2 @ react-dom.production.min.js:211
aV @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
on @ react-dom.production.min.js:122
aQ @ react-dom.production.min.js:257
aW @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
on @ react-dom.production.min.js:122
oi @ react-dom.production.min.js:123
oo @ react-dom.production.min.js:122
aT @ react-dom.production.min.js:240
notify @ Subscription.js:16
notifyNestedSubs @ Subscription.js:88
o @ Subscription.js:93
b @ redux.js:296
(anonymous) @ middleware.js:22
(anonymous) @ index.js:28
(anonymous) @ index.js:20
dispatch @ redux.js:691
(anonymous) @ utils.js:245
setTimeout (async)
(anonymous) @ utils.js:245
await in (anonymous) (async)
i @ utils.js:335
n.type @ utils.js:202
(anonymous) @ index.js:16
(anonymous) @ redux.js:578
(anonymous) @ EntityListLoader.jsx:112
componentDidMount @ EntityListLoader.jsx:131
(anonymous) @ react-dom.production.min.js:212
a$ @ react-dom.production.min.js:213
t.unstable_runWithPriority @ scheduler.production.min.js:19
on @ react-dom.production.min.js:122
aX @ react-dom.production.min.js:248
aW @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
on @ react-dom.production.min.js:122
oi @ react-dom.production.min.js:123
oo @ react-dom.production.min.js:122
ak @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
y.setState @ react.production.min.js:12
(anonymous) @ Router.js:109
(anonymous) @ createTransitionManager.js:228
(anonymous) @ createTransitionManager.js:83
(anonymous) @ AsyncUtils.js:74
(anonymous) @ getComponents.js:6
(anonymous) @ getComponents.js:19
(anonymous) @ AsyncUtils.js:79
(anonymous) @ AsyncUtils.js:78
S @ AsyncUtils.js:83
u @ createTransitionManager.js:77
l @ AsyncUtils.js:47
(anonymous) @ TransitionUtils.js:88
(anonymous) @ TransitionUtils.js:110
onEnter @ routes.jsx:102
await in onEnter (async)
i @ TransitionUtils.js:43
(anonymous) @ TransitionUtils.js:114
(anonymous) @ TransitionUtils.js:84
l @ AsyncUtils.js:34
O @ AsyncUtils.js:49
r @ TransitionUtils.js:83
runEnterHooks @ TransitionUtils.js:107
(anonymous) @ createTransitionManager.js:70
r @ TransitionUtils.js:74
runChangeHooks @ TransitionUtils.js:131
l @ createTransitionManager.js:67
(anonymous) @ createTransitionManager.js:45
l @ AsyncUtils.js:41
O @ AsyncUtils.js:49
N @ matchRoutes.js:231
c @ createTransitionManager.js:41
r @ createTransitionManager.js:222
listen @ createTransitionManager.js:246
componentWillMount @ Router.js:102
oB @ react-dom.production.min.js:137
iF @ react-dom.production.min.js:176
l @ react-dom.production.min.js:263
aH @ react-dom.production.min.js:246
(anonymous) @ react-dom.production.min.js:246
aW @ react-dom.production.min.js:246
ak @ react-dom.production.min.js:230
si @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
aD @ react-dom.production.min.js:240
sp @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
dR @ app.js:75
dQ @ app.js:106
84553 @ app-main.js:24
a @ bootstrap:19
(anonymous) @ app-main.6e9b1451c96b0a1b9bbd.js:243
a.O @ chunk loaded:25
(anonymous) @ app-main.6e9b1451c96b0a1b9bbd.js:243
i @ jsonp chunk loading:73
(anonymous) @ app-main.6e9b1451c96b0a1b9bbd.js:7
Show 109 more frames
Show less
```

### Information about your Metabase installation

```JSON
- browser: Chrome 123.0.6312.107, (arm64)
- Mac OS BigSur 11.2.3 (20D91)
- Metabase 0.49.1
```

### Severity

blocking some users

**Comment by JesseSDevaney** [comment]
Closing this issue as it was a duplicated issue of:
- https://github.com/metabase/metabase/issues/41243

which was already fixed.
