### ISSUE TITLE
Regression in 0.49.4:  Cannot Connect to RDS Postgres through SSH tunnel

### ISSUE THREAD

**Issue by saadbahir** [metabase/metabase#41439]
### Describe the bug

I upgraded from `0.49.3` to `0.49.4` and I got this error when trying to connecting my Postgres Database using an SSH tunnel

```
DefaultConnectFuture[EC2-INSTANCE-URI]: Failed (UnresolvedAddressException) to execute: null
```

After rolling back to `0.49.3` it worked again

### To Reproduce

1. Go to Admin Settings
2. Click on Database
3. Connected Postgres using SSH tunnel

### Logs

DefaultConnectFuture[EC2-INSTANCE-URI]: Failed (UnresolvedAddressException) to execute: null

### Information about your Metabase installation

```JSON
- Metabase version: `0.49.4`
- Database: Postgres (with SSH tunnel)
- Hosting Environment: Kubernetes
```

### Severity

P1

**Comment by bshepherdson** [comment]
That exception indicates that the address of the Postgres database could not be resolved. Nothing related to DB connections changed with 49.3. Without any further logs, there's no more I can say.

Can you include the full server log? There may be something illuminating in it.

**Comment by saadbahir** [comment]
> That exception indicates that the address of the Postgres database could not be resolved. Nothing related to DB connections changed with 49.3. Without any further logs, there's no more I can say.
> 
> Can you include the full server log? There may be something illuminating in it.

Apologies for the mistake! It's actually 49.4  

I wil fix the original ticket

Here are the full logs in the meantime

```
2024-04-15 20:12:28,245 ERROR driver.util :: Failed to connect to Database
org.apache.sshd.common.SshException: DefaultConnectFuture[user@ecXXXXXXXXXXXXX.compute-1.amazonaws.com:22]: Failed (UnresolvedAddressException) to execute: null
	at org.apache.sshd.common.future.AbstractSshFuture.lambda$verifyResult$2(AbstractSshFuture.java:146)
	at org.apache.sshd.common.future.AbstractSshFuture.formatExceptionMessage(AbstractSshFuture.java:206)
	at org.apache.sshd.common.future.AbstractSshFuture.verifyResult(AbstractSshFuture.java:145)
	at org.apache.sshd.client.future.DefaultConnectFuture.verify(DefaultConnectFuture.java:55)
	at org.apache.sshd.client.future.DefaultConnectFuture.verify(DefaultConnectFuture.java:36)
	at metabase.util.ssh$start_ssh_tunnel_BANG_.invokeStatic(ssh.clj:81)
	at metabase.util.ssh$start_ssh_tunnel_BANG_.invoke(ssh.clj:73)
	at metabase.util.ssh$include_ssh_tunnel_BANG_.invokeStatic(ssh.clj:115)
	at metabase.util.ssh$include_ssh_tunnel_BANG_.invoke(ssh.clj:109)
	at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:158)
	at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154)
	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:309)
	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:305)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:334)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:330)
	at metabase.driver.sql_jdbc$fn__106676.invokeStatic(sql_jdbc.clj:49)
	at metabase.driver.sql_jdbc$fn__106676.invoke(sql_jdbc.clj:47)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__59933.invoke(util.clj:148)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Unknown Source)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implConnect(Unknown Source)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.connect(Unknown Source)
	at org.apache.sshd.common.io.nio2.Nio2Connector.connect(Nio2Connector.java:84)
	at org.apache.sshd.client.SshClient.doConnect(SshClient.java:665)
	at org.apache.sshd.client.SshClient.doConnect(SshClient.java:648)
	at org.apache.sshd.client.SshClient.connect(SshClient.java:552)
	at org.apache.sshd.client.SshClient.connect(SshClient.java:544)
	at org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:74)
	at org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:57)
	at metabase.util.ssh$start_ssh_tunnel_BANG_.invokeStatic(ssh.clj:80)
	... 19 more
2024-04-15 20:12:28,251 ERROR api.database :: Cannot connect to Database
clojure.lang.ExceptionInfo: DefaultConnectFuture[user@ecXXXXXXXXXXXXX.compute-1.amazonaws.com:22]: Failed (UnresolvedAddressException) to execute: null {:message "DefaultConnectFuture[user@ecXXXXXXXXXXXXX.compute-1.amazonaws.com:22]: Failed (UnresolvedAddressException) to execute: null"}
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:165)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:136)

```

The exact same connection worked fine between Metabase 47 until 49.3

**Comment by likeshumidity** [comment]
Are you using a hostname or IP address for the SSH host? @saadbahir

**Comment by saadbahir** [comment]
> Are you using a hostname or IP address for the SSH host? @saadbahir

I am using a Hostname

**Comment by saadbahir** [comment]
@likeshumidity I would like to note that the ssh connection works perfectly fine on the server that hosts our metabase instance
Otherwise version 49.3 wouldn't work either

I tried to find which commit might have introduced the regression but didn't find any success thus far ...

**Comment by paoliniluis** [comment]
@saadbahir does this keeps happening?

**Comment by paoliniluis** [comment]
Closing due to non response
