### ISSUE TITLE
Wish to support GuassDB

### ISSUE THREAD

**Issue by cowcomic** [metabase/metabase#41627]
GuassDB is a very popular MPP database in China, especially in large projects. I hope GuassDB can be supported to facilitate the use of metabase in large-scale projects

**Comment by paoliniluis** [comment]
Have you tried connecting to the db with the Postgres driver?

**Comment by cowcomic** [comment]
I tried to connect to guassdb by postgresql
![image](https://github.com/metabase/metabase/assets/4745969/aca26df5-8928-43f6-9b89-411d5790af35)


the error as follows
```
[a0ec80b6-e8e3-4084-a3ab-8009bcc3597b] 2024-07-04T09:33:28+08:00 WARN metabase.sync.util Error in sync step Sync metadata for postgres Database 7 ''测试GuassDB'',org.postgresql.util.PSQLException: ERROR: relation "pg_catalog.pg_matviews" does not exist,  Position: 866,
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725),
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412),
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371),
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502),
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419),
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194),
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137),
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471),
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090),
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084),
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1106),
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093),
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182),
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160),
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),
	at metabase.driver.postgres$fn__83866.invokeStatic(postgres.clj:861),
	at metabase.driver.postgres$fn__83866.doInvoke(postgres.clj:857),
	at clojure.lang.RestFn.invoke(RestFn.java:425),
	at clojure.lang.MultiFn.invoke(MultiFn.java:234),
	at metabase.driver.sql_jdbc.sync.describe_database$schema_PLUS_table_with_select_privileges.invokeStatic(describe_database.clj:119),
	at metabase.driver.sql_jdbc.sync.describe_database$schema_PLUS_table_with_select_privileges.invoke(describe_database.clj:117),
	at metabase.driver.sql_jdbc.sync.describe_database$have_select_privilege_fn.invokeStatic(describe_database.clj:137),
	at metabase.driver.sql_jdbc.sync.describe_database$have_select_privilege_fn.invoke(describe_database.clj:125),
	at metabase.driver.sql_jdbc.sync.describe_database$fast_active_tables.invokeStatic(describe_database.clj:159),
	at metabase.driver.sql_jdbc.sync.describe_database$fast_active_tables.doInvoke(describe_database.clj:148),
	at clojure.lang.RestFn.invoke(RestFn.java:490),
	at metabase.driver.sql_jdbc.sync.describe_database$fn__81004.invokeStatic(describe_database.clj:167),
	at metabase.driver.sql_jdbc.sync.describe_database$fn__81004.invoke(describe_database.clj:165),
	at clojure.lang.MultiFn.invoke(MultiFn.java:244),
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database$fn__81023.invoke(describe_database.clj:218),
	at metabase.driver.sql_jdbc.execute$fn__78824$fn__78825.invoke(execute.clj:388),
	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334),
	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317),
	at metabase.driver.sql_jdbc.execute$fn__78824.invokeStatic(execute.clj:382),
	at metabase.driver.sql_jdbc.execute$fn__78824.invoke(execute.clj:380),
	at clojure.lang.MultiFn.invoke(MultiFn.java:244),
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invokeStatic(describe_database.clj:201),
	at metabase.driver.sql_jdbc.sync.describe_database$describe_database.invoke(describe_database.clj:196),
	at metabase.driver.sql_jdbc$fn__106350.invokeStatic(sql_jdbc.clj:90),
	at metabase.driver.sql_jdbc$fn__106350.invoke(sql_jdbc.clj:88),
	at clojure.lang.MultiFn.invoke(MultiFn.java:234),
	at metabase.sync.fetch_metadata$db_metadata.invokeStatic(fetch_metadata.clj:17),
	at metabase.sync.fetch_metadata$db_metadata.invoke(fetch_metadata.clj:14),
	at metabase.sync.sync_metadata$sync_db_metadata_BANG_$fn__82096.invoke(sync_metadata.clj:69),
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:190),
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:183),
	at clojure.core$partial$fn__5910.invoke(core.clj:2647),
	at metabase.driver$fn__49747.invokeStatic(driver.clj:759),
	at metabase.driver$fn__49747.invoke(driver.clj:759),
	at clojure.lang.MultiFn.invoke(MultiFn.java:239),
	at metabase.sync.util$sync_in_context$fn__60065.invoke(util.clj:166),
	at metabase.sync.util$with_db_logging_disabled$fn__60062.invoke(util.clj:158),
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:131),
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:125),
	at metabase.sync.util$with_start_and_finish_logging$fn__60049.invoke(util.clj:143),
	at metabase.sync.util$with_sync_events$fn__60044.invoke(util.clj:117),
	at metabase.sync.util$with_duplicate_ops_prevented$fn__60031.invoke(util.clj:89),
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:215),
	at metabase.sync.util$do_sync_operation.invoke(util.clj:209),
	at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invokeStatic(sync_metadata.clj:68),
	at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invoke(sync_metadata.clj:65),
	at metabase.sync$sync_database_BANG_$fn__82106.invoke(sync.clj:52),
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:190),
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:183),
	at clojure.core$partial$fn__5910.invoke(core.clj:2647),
	at metabase.driver$fn__49747.invokeStatic(driver.clj:759),
	at metabase.driver$fn__49747.invoke(driver.clj:759),
	at clojure.lang.MultiFn.invoke(MultiFn.java:239),
	at metabase.sync.util$sync_in_context$fn__60065.invoke(util.clj:166),
	at metabase.sync.util$with_db_logging_disabled$fn__60062.invoke(util.clj:158),
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:131),
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:125),
	at metabase.sync.util$with_start_and_finish_logging$fn__60049.invoke(util.clj:143),
	at metabase.sync.util$with_sync_events$fn__60044.invoke(util.clj:117),
	at metabase.sync.util$with_duplicate_ops_prevented$fn__60031.invoke(util.clj:89),
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:215),
	at metabase.sync.util$do_sync_operation.invoke(util.clj:209),
	at metabase.sync$sync_database_BANG_.invokeStatic(sync.clj:51),
	at metabase.sync$sync_database_BANG_.invoke(sync.clj:37),
	at metabase.sync$sync_database_BANG_.invokeStatic(sync.clj:46),
	at metabase.sync$sync_database_BANG_.invoke(sync.clj:37),
	at metabase.events.sync_database$publish_event_BANG__primary_method_metabase_events_sync_database_event$fn__103799.invoke(sync_database.clj:24),
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047),
	at clojure.lang.AFn.call(AFn.java:18),
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source),
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source),
	at java.base/java.lang.Thread.run(Unknown Source)
[a0ec80b6-e8e3-4084-a3ab-8009bcc3597b] 2024-07-04T09:33:28+08:00 INFO metabase.sync.util FINISHED: Sync postgres Database 7 ''测试GuassDB'' (258.7 ms)
[a0ec80b6-e8e3-4084-a3ab-8009bcc3597b] 2024-07-04T09:33:28+08:00 WARN metabase.sync.util Error in sync step Sync postgres Database 7 ''测试GuassDB'',java.lang.ClassCastException: class org.postgresql.util.PSQLException cannot be cast to class clojure.lang.Associative (org.postgresql.util.PSQLException and clojure.lang.Associative are in unnamed module of loader 'app'),
	at clojure.lang.RT.assoc(RT.java:827),
	at clojure.core$assoc__5481.invokeStatic(core.clj:193),
	at clojure.core$assoc__5481.invoke(core.clj:192),
	at metabase.sync$sync_database_BANG_$fn__82106.invoke(sync.clj:52),
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:190),
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:183),
	at clojure.core$partial$fn__5910.invoke(core.clj:2647),
	at metabase.driver$fn__49747.invokeStatic(driver.clj:759),
	at metabase.driver$fn__49747.invoke(driver.clj:759),
	at clojure.lang.MultiFn.invoke(MultiFn.java:239),
	at metabase.sync.util$sync_in_context$fn__60065.invoke(util.clj:166),
	at metabase.sync.util$with_db_logging_disabled$fn__60062.invoke(util.clj:158),
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:131),
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:125),
	at metabase.sync.util$with_start_and_finish_logging$fn__60049.invoke(util.clj:143),
	at metabase.sync.util$with_sync_events$fn__60044.invoke(util.clj:117),
	at metabase.sync.util$with_duplicate_ops_prevented$fn__60031.invoke(util.clj:89),
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:215),
	at metabase.sync.util$do_sync_operation.invoke(util.clj:209),
	at metabase.sync$sync_database_BANG_.invokeStatic(sync.clj:51),
	at metabase.sync$sync_database_BANG_.invoke(sync.clj:37),
	at metabase.sync$sync_database_BANG_.invokeStatic(sync.clj:46),
	at metabase.sync$sync_database_BANG_.invoke(sync.clj:37),
	at metabase.events.sync_database$publish_event_BANG__primary_method_metabase_events_sync_database_event$fn__103799.invoke(sync_database.clj:24),
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047),
	at clojure.lang.AFn.call(AFn.java:18),
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source),
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source),
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by paoliniluis** [comment]
So it seems that the GuassDB folks don't have the postgres views that we need to sync. I would suggest you to contact them @cowcomic

**Comment by cowcomic** [comment]
> So it seems that the GuassDB folks don't have the postgres views that we need to sync. I would suggest you to contact them [@cowcomic](https://github.com/cowcomic)

I also hope that metabase can directly support this driver

**Comment by paoliniluis** [comment]
@AlexeyVRaspopov why can't you build a custom driver and publish it for all the users?

**Comment by AlexeyVRaspopov** [comment]
@paoliniluis  sorry, but I don't konw how to build  a custom driver. I'm not a developer, and know only how to run metabase on Docker
