### ISSUE TITLE
[BE] [QP] [Bug] Collecting field usages from preprocessed query fails

### ISSUE THREAD

**Issue by metamben** [metabase/metabase#41754]
### Describe the bug

Running a query with a filter like `[:= [:field 1] "a" "b"]` produces an error like:
```
2024-04-23 19:46:48,169 ERROR middleware.process-userland-query :: Error saving query execution info
clojure.lang.ExceptionInfo: Invalid input: ["Valid column metadata, got: [:= {:lib/uuid \"8e27edc6-189e-4309-9303-f492bd083607\"} [:field {:base-type :type/Text, :source-field 40, :join-alias \"PRODUCTS__via__PRODUCT_ID\", :lib/uuid \"3210e895-97c9-446f-95f3-ba552e9a74e2\"} 58] [:value {:effective_type :type/Text, :name \"CATEGORY\", :base-type :type/Text, :semantic-type :type/Category, :database-type \"CHARACTER VARYING\", :effective-type :type/Text, :lib/uuid \"889b1fbc-9eac-4101-b222-b36c5d08f6bf\"} \"Gadget\"]]"
```

### To Reproduce

Run the query below and observe the server logs.
<img width="542" alt="image" src="https://github.com/metabase/metabase/assets/103100869/94a20dfd-f14b-4273-ad21-0f9ac8f90609">

### Expected behavior

Should be able to extract the field. Either `metabase.lib.filter/filter-parts` has to be generalized to be able to deal with preprocessed (de-sugared) queries, or `metabase.query-processor.middleware.process-userland-query/process-userland-query-middleware` should call `field-usage/pmbql->field-usages` with the original query, not the preprocessed one.

### Logs

```
2024-04-23 19:46:48,169 ERROR middleware.process-userland-query :: Error saving query execution info
clojure.lang.ExceptionInfo: Invalid input: ["Valid column metadata, got: [:= {:lib/uuid \"8e27edc6-189e-4309-9303-f492bd083607\"} [:field {:base-type :type/Text, :source-field 40, :join-alias \"PRODUCTS__via__PRODUCT_ID\", :lib/uuid \"3210e895-97c9-446f-95f3-ba552e9a74e2\"} 58] [:value {:effective_type :type/Text, :name \"CATEGORY\", :base-type :type/Text, :semantic-type :type/Category, :database-type \"CHARACTER VARYING\", :effective-type :type/Text, :lib/uuid \"889b1fbc-9eac-4101-b222-b36c5d08f6bf\"} \"Gadget\"]]" "Valid reference, must be one of these clauses: :aggregation, :expression, :field, :metric, :segment, got: [:= {:lib/uuid \"8e27edc6-189e-4309-9303-f492bd083607\"} [:field {:base-type :type/Text, :source-field 40, :join-alias \"PRODUCTS__via__PRODUCT_ID\", :lib/uuid \"3210e895-97c9-446f-95f3-ba552e9a74e2\"} 58] [:value {:effective_type :type/Text, :name \"CATEGORY\", :base-type :type/Text, :semantic-type :type/Category, :database-type \"CHARACTER VARYING\", :effective-type :type/Text, :lib/uuid \"889b1fbc-9eac-4101-b222-b36c5d08f6bf\"} \"Gadget\"]]"] {:type :metabase.util.malli.fn/invalid-input, :error {:schema [:or :metabase.lib.schema.metadata/column :metabase.lib.schema.ref/ref], :value [:= {:lib/uuid "8e27edc6-189e-4309-9303-f492bd083607"} [:field {:base-type :type/Text, :source-field 40, :join-alias "PRODUCTS__via__PRODUCT_ID", :lib/uuid "3210e895-97c9-446f-95f3-ba552e9a74e2"} 58] [:value {:effective_type :type/Text, :name "CATEGORY", :base-type :type/Text, :semantic-type :type/Category, :database-type "CHARACTER VARYING", :effective-type :type/Text, :lib/uuid "889b1fbc-9eac-4101-b222-b36c5d08f6bf"} "Gadget"]], :errors ({:path [0 0], :in [], :schema [:map {:error/message "Valid column metadata"} [:lib/type [:= :metadata/column]] [:name :string] [:base-type :metabase.lib.schema.common/base-type] [:id {:optional true} :metabase.lib.schema.id/field] [:display-name {:optional true} [:maybe :string]] [:effective-type {:optional true} [:maybe :metabase.lib.schema.common/base-type]] [:fk-field-id {:optional true} [:maybe :metabase.lib.schema.id/field]] [:fk-target-field-id {:optional true} [:maybe :metabase.lib.schema.id/field]] [:source-alias {:optional true} [:maybe :metabase.lib.schema.common/non-blank-string]] [:lib/expression-name {:optional true} [:maybe :metabase.lib.schema.common/non-blank-string]] [:lib/source {:optional true} [:ref :metabase.lib.schema.metadata/column-source]] [:lib/card-id {:optional true} [:maybe :metabase.lib.schema.id/card]] [:lib/source-column-alias {:optional true} [:maybe :metabase.lib.schema.common/non-blank-string]] [:lib/desired-column-alias {:optional true} [:maybe [:string {:min 1, :max 60}]]] [:selected? {:optional true} :boolean] [:has-field-values {:optional true} [:maybe [:ref :metabase.lib.schema.metadata/column.has-field-values]]] [:lib/external-remap {:optional true} [:maybe [:ref :metabase.lib.schema.metadata/column.remapping.external]]] [:lib/internal-remap {:optional true} [:maybe [:ref :metabase.lib.schema.metadata/column.remapping.internal]]]], :value [:= {:lib/uuid "8e27edc6-189e-4309-9303-f492bd083607"} [:field {:base-type :type/Text, :source-field 40, :join-alias "PRODUCTS__via__PRODUCT_ID", :lib/uuid "3210e895-97c9-446f-95f3-ba552e9a74e2"} 58] [:value {:effective_type :type/Text, :name "CATEGORY", :base-type :type/Text, :semantic-type :type/Category, :database-type "CHARACTER VARYING", :effective-type :type/Text, :lib/uuid "889b1fbc-9eac-4101-b222-b36c5d08f6bf"} "Gadget"]], :type :malli.core/invalid-type} {:path [1 0 1], :in [], :schema [:fn {:error/fn #function[metabase.lib.schema.ref/eval59566/fn--59567]} #function[metabase.lib.schema.ref/eval59566/fn--59570]], :value [:= {:lib/uuid "8e27edc6-189e-4309-9303-f492bd083607"} [:field {:base-type :type/Text, :source-field 40, :join-alias "PRODUCTS__via__PRODUCT_ID", :lib/uuid "3210e895-97c9-446f-95f3-ba552e9a74e2"} 58] [:value {:effective_type :type/Text, :name "CATEGORY", :base-type :type/Text, :semantic-type :type/Category, :database-type "CHARACTER VARYING", :effective-type :type/Text, :lib/uuid "889b1fbc-9eac-4101-b222-b36c5d08f6bf"} "Gadget"]]})}, :humanized ["Valid column metadata, got: [:= {:lib/uuid \"8e27edc6-189e-4309-9303-f492bd083607\"} [:field {:base-type :type/Text, :source-field 40, :join-alias \"PRODUCTS__via__PRODUCT_ID\", :lib/uuid \"3210e895-97c9-446f-95f3-ba552e9a74e2\"} 58] [:value {:effective_type :type/Text, :name \"CATEGORY\", :base-type :type/Text, :semantic-type :type/Category, :database-type \"CHARACTER VARYING\", :effective-type :type/Text, :lib/uuid \"889b1fbc-9eac-4101-b222-b36c5d08f6bf\"} \"Gadget\"]]" "Valid reference, must be one of these clauses: :aggregation, :expression, :field, :metric, :segment, got: [:= {:lib/uuid \"8e27edc6-189e-4309-9303-f492bd083607\"} [:field {:base-type :type/Text, :source-field 40, :join-alias \"PRODUCTS__via__PRODUCT_ID\", :lib/uuid \"3210e895-97c9-446f-95f3-ba552e9a74e2\"} 58] [:value {:effective_type :type/Text, :name \"CATEGORY\", :base-type :type/Text, :semantic-type :type/Category, :database-type \"CHARACTER VARYING\", :effective-type :type/Text, :lib/uuid \"889b1fbc-9eac-4101-b222-b36c5d08f6bf\"} \"Gadget\"]]"], :schema [:or :metabase.lib.schema.metadata/column :metabase.lib.schema.ref/ref], :value [:= {:lib/uuid "8e27edc6-189e-4309-9303-f492bd083607"} [:field {:base-type :type/Text, :source-field 40, :join-alias "PRODUCTS__via__PRODUCT_ID", :lib/uuid "3210e895-97c9-446f-95f3-ba552e9a74e2"} 58] [:value {:effective_type :type/Text, :name "CATEGORY", :base-type :type/Text, :semantic-type :type/Category, :database-type "CHARACTER VARYING", :effective-type :type/Text, :lib/uuid "889b1fbc-9eac-4101-b222-b36c5d08f6bf"} "Gadget"]], :fn-name find-matching-column}
	at metabase.lib.equality$fn__63590$fn__63618.invoke(equality.cljc:249)
	at metabase.lib.equality$fn__63590$_AMPERSAND_f__63593.invoke(equality.cljc:296)
	at metabase.lib.equality$fn__63590$fn__63618.invoke(equality.cljc:249)
	at metabase.lib.filter$fn__177046$_AMPERSAND_f__177047.invoke(filter.cljc:525)
	at metabase.lib.filter$fn__177046$fn__177056.invoke(filter.cljc:513)
	at metabase.models.field_usage$filter__GT_field_usage.invokeStatic(field_usage.clj:29)
	at metabase.models.field_usage$filter__GT_field_usage.invoke(field_usage.clj:27)
	at metabase.models.field_usage$stage__GT_field_usages$fn__177802.invoke(field_usage.clj:76)
	at clojure.core$keep$fn__8649.invoke(core.clj:7406)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$concat$fn__5558.invoke(core.clj:727)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$concat$cat__5560$fn__5561.invoke(core.clj:736)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:58)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$seq__5467.invoke(core.clj:139)
	at metabase.query_processor.middleware.process_userland_query$save_execution_metadata_BANG__STAR_.invokeStatic(process_userland_query.clj:55)
	at metabase.query_processor.middleware.process_userland_query$save_execution_metadata_BANG__STAR_.invoke(process_userland_query.clj:47)
	at metabase.query_processor.middleware.process_userland_query$save_execution_metadata_BANG_$f__177848.invoke(process_userland_query.clj:72)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Information about your Metabase installation

```JSON
- Metabase commit d1a7cec69c10a84d19d403a37d1736cbb17bb582
```

### Severity

It prevents getting an accurate view of field usages.

**Comment by qnkhuat** [comment]
`field-usage/pmbql->field-usages` expects a query with all sources and joins resolved. If we want to rework it to accept the original query then we'll need to call resolve cards ourselves, which means we'll need to use the `resolve-source-cards` middleware. 

This is actually my original implement, but @bshepherdson pointed out that's mis-using QP middleware and I agree with that.

So I'd like to ask you to consider the other approach of making `lib/filter-parts` to work with the preprocessed filter

**Comment by ranquild** [comment]
Can be reproduced on `d1a7cec69c10a84d19d403a37d1736cbb17bb582`. Cannot be reproduced on the latest master `0c7400c81eb29c27ad21d55d6c9486b4d0668206`, pre-v56. AFAIK we don't collect field usage anymore.

**Comment by uladzimirdev** [comment]
closing as we do not collect field usage anymore

[discussion](https://metaboat.slack.com/archives/C0645JP1W81/p1752477818428639)
