### ISSUE TITLE
Metabase 0.49.8 update from 0.49.5 failed with clickhouse driver

### ISSUE THREAD

**Issue by sanel** [metabase/metabase#42319]
### Describe the bug

Updating Metabase from 0.49.5 to 0.49.8 failed, with failed db migration.

### To Reproduce

1. make sure you run 0.49.5 version
2. try to upgrade metabase.jar with 0.49.8 version and restart it

### Expected behavior

Migration should be done withour problems

### Logs

 ```
 2024-05-07 10:07:44,852 INFO db.liquibase :: Running 1 migrations ...
 2024-05-07 10:07:45,220 INFO driver.impl :: Initializing driver :sql...
 2024-05-07 10:07:45,221 INFO driver.impl :: Initializing driver :sql-jdbc...
 2024-05-07 10:07:45,221 INFO driver.impl :: Initializing driver :postgres...
 2024-05-07 10:07:45,253 INFO driver.impl :: Initializing driver :h2...
 2024-05-07 10:07:45,259 INFO driver.impl :: Initializing driver :clickhouse...
 2024-05-07 10:07:45,260 INFO plugins.classloader :: Added URL file:/var/lib/metabase/plugins/clickhouse.metabase-driver.jar to classpath
 2024-05-07 10:07:45,275 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.clickhouse...
 2024-05-07 10:07:45,300 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v49.2024-04-09T10:00:03::qnkhuat encountered an exception.
 UPDATE SUMMARY
 Run:                          1
 Previously run:             268
 Filtered out:                17
 -------------------------------
 Total change sets:          286
 FILTERED CHANGE SETS SUMMARY
 DBMS mismatch:               17
 2024-05-07 10:07:45,355 ERROR metabase.core :: Metabase Initialization FAILED
 liquibase.exception.CommandExecutionException: java.lang.ClassCastException: class java.lang.ExceptionInInitializerError cannot be cast to class java.lang.Exception (java.lang.ExceptionInInitializerError and java.lang.Exception are in module java.base of loader 'bootstrap')
         at liquibase.command.CommandScope.execute(CommandScope.java:253)
         at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
         at liquibase.Scope.lambda$child$0(Scope.java:186)
         at liquibase.Scope.child(Scope.java:195)
         at liquibase.Scope.child(Scope.java:185)
         at liquibase.Scope.child(Scope.java:164)
         at liquibase.Liquibase.runInScope(Liquibase.java:1419)
         at liquibase.Liquibase.update(Liquibase.java:234)
         at liquibase.Liquibase.update(Liquibase.java:212)
         at liquibase.Liquibase.update(Liquibase.java:194)
         at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:305)
         at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:287)
         at metabase.db.setup$migrate_BANG_$fn__51110.invoke(setup.clj:80)
         at metabase.db.liquibase$do_with_liquibase$f_STAR___48786.invoke(liquibase.clj:139)
         at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:142)
         at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:130)
         at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:75)
         at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:56)
         at clojure.lang.RestFn.invoke(RestFn.java:445)
         at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:147)
         at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:141)
         at metabase.db.setup$setup_db_BANG_$fn__51138$fn__51139.invoke(setup.clj:165)
         at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
         at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
         at metabase.db.setup$setup_db_BANG_$fn__51138.invoke(setup.clj:160)
         at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:159)
         at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
         at metabase.db$setup_db_BANG_$fn__51158.invoke(db.clj:69)
         at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:116)
         at metabase.core$init_BANG__STAR_.invoke(core.clj:101)
         at metabase.core$init_BANG_.invokeStatic(core.clj:159)
         at metabase.core$init_BANG_.invoke(core.clj:154)
         at metabase.core$start_normally.invokeStatic(core.clj:171)
         at metabase.core$start_normally.invoke(core.clj:165)
         at metabase.core$entrypoint.invokeStatic(core.clj:204)
         at metabase.core$entrypoint.doInvoke(core.clj:198)
         at clojure.lang.RestFn.invoke(RestFn.java:397)
         at clojure.lang.AFn.applyToHelper(AFn.java:152)
         at clojure.lang.RestFn.applyTo(RestFn.java:132)
         at clojure.lang.Var.applyTo(Var.java:705)
         at clojure.core$apply.invokeStatic(core.clj:667)
         at clojure.core$apply.invoke(core.clj:662)
         at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
         at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
         at clojure.lang.RestFn.invoke(RestFn.java:397)
         at clojure.lang.AFn.applyToHelper(AFn.java:152)
         at clojure.lang.RestFn.applyTo(RestFn.java:132)
         at metabase.bootstrap.main(Unknown Source)
 Caused by: java.lang.ClassCastException: class java.lang.ExceptionInInitializerError cannot be cast to class java.lang.Exception (java.lang.ExceptionInInitializerError and java.lang.Exception are in module java.base of loader 'bootstrap')
         at liquibase.command.CommandScope.logPrimaryExceptionToMdc(CommandScope.java:287)
         at liquibase.command.CommandScope.execute(CommandScope.java:245)
         ... 49 more
 2024-05-07 10:07:45,364 INFO metabase.core :: Metabase Shutting Down ...
 2024-05-07 10:07:45,371 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
 2024-05-07 10:07:45,382 WARN db.liquibase :: ()
 2024-05-07 10:07:45,383 INFO metabase.core :: Metabase Shutdown COMPLETE
```

### Information about your Metabase installation

```JSON
{"file.encoding" "UTF-8",
  "java.runtime.name" "OpenJDK Runtime Environment",
  "java.runtime.version" "11.0.23+9",
  "java.vendor" "Eclipse Adoptium",
  "java.vendor.url" "https://adoptium.net/",
  "java.version" "11.0.23",
  "java.vm.name" "OpenJDK 64-Bit Server VM",
  "java.vm.version" "11.0.23+9",
  "os.name" "Linux",
  "os.version" "4.4.0-210-generic",
  "user.language" "en",
  "user.timezone" "UTC"}
```

### Severity

Blocking upgrade

**Comment by sanel** [comment]
Also to mention, Metabase updates until `0.49.6` worked without problems (that version update failed as well, so I just kept Metbase on `0.49.5`). It also fails on `jdk-11.0.4+11` version

**Comment by calherries** [comment]
I haven't attempted to reproduce this. Based on the stacktrace, the problem is the migration added by  https://github.com/metabase/metabase/issues/41348 is failing.

https://github.com/metabase/metabase/blob/43c0ce979a73a84aa03d2e7feb4eeee6e40e8614/src/metabase/db/custom_migrations.clj#L1077-L1094

**Comment by qnkhuat** [comment]
similiar to https://github.com/metabase/metabase/issues/41779.

@sanel do you have any 3rd party plugins?

**Comment by sanel** [comment]
Also, clickhouse driver that might be the problem: https://github.com/enqueue/metabase-clickhouse-driver/releases/download/1.1.3/clickhouse.metabase-driver.jar

**Comment by qnkhuat** [comment]
It fails because you have an old version of Clickhouse that's no longer compatible with Metabase 49. If you use their newest version, upgrade should be fine.

**Comment by dannyeuu** [comment]
I have the last version of ClickHouse driver 1.4.0 on Metabase v.0.49.2 working ok, but when trying to migrate to Metabase v.0.49.2 I found this problem with the migration.

**Comment by calherries** [comment]
> v.0.49.2 working ok... migrate to v.0.49.2 problem

@dannyeuu can you repeat what version you are migrating from and migrating to?

**Comment by dannyeuu** [comment]
> > v.0.49.2 working ok... migrate to v.0.49.2 problem
> 
> @dannyeuu can you repeat what version you are migrating from and migrating to?

sorry @calherries my actually version is 0.49.2 and tying to upgrade to 0.49.8

**Comment by qnkhuat** [comment]
I couldn't reproduce. Here is what I did:
1. Start MB with 0.49.2 with Clickhouse driver version 1.4.0
2. Add a Clickhouse driver
3. Stop MB and migrate to 0.49.8 without a problem

@dannyeuu, is there anything different with your setup? Please share your full startup log; it'll help us investigate the issue.

**Comment by dannyeuu** [comment]
> I couldn't reproduce. Here is what I did:
> 
> 1. Start MB with 0.49.2 with Clickhouse driver version 1.4.0
> 2. Add a Clickhouse driver
> 3. Stop MB and migrate to 0.49.8 without a problem
> 
> @dannyeuu, is there anything different with your setup? Please share your full startup log; it'll help us investigate the issue.

this is the log that I received:
```
2024-05-09 14:55:09,723 INFO metabase.util :: Maximum memory available to JVM: 12.0 GB
2024-05-09 14:55:12,660 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance.  
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2024-05-09 14:55:21,005 INFO driver.impl :: [34mRegistered abstract driver :sql[0m  
2024-05-09 14:55:21,018 INFO driver.impl :: [34mRegistered abstract driver :sql-jdbc[0m (parents: [:sql]) 
2024-05-09 14:55:21,028 INFO metabase.util :: [32mLoad driver :sql-jdbc took 101.5 ms[0m
2024-05-09 14:55:21,029 INFO driver.impl :: [34mRegistered driver :h2[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:21,273 INFO driver.impl :: [34mRegistered driver :mysql[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:21,322 INFO driver.impl :: [34mRegistered driver :postgres[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:23,516 INFO metabase.core :: 
Metabase v0.49.8 (38cb850) 

Copyright © 2024 Metabase, Inc. 

Metabase Enterprise Edition extensions are NOT PRESENT.
2024-05-09 14:55:23,530 INFO metabase.core :: Starting Metabase in STANDALONE mode
2024-05-09 14:55:23,597 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
 {:port 3000, :host "0.0.0.0", :max-threads 256}

2024-05-09 14:55:23,660 INFO metabase.core :: Starting Metabase version v0.49.8 (38cb850) ...
2024-05-09 14:55:23,669 INFO metabase.core :: System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "19+36",
 "java.vendor" "Eclipse Adoptium",
 "java.vendor.url" "https://adoptium.net/",
 "java.version" "19",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "19+36",
 "os.name" "Linux",
 "os.version" "5.10.0-28-cloud-amd64",
 "user.language" "en",
 "user.timezone" "Etc/UTC"}

2024-05-09 14:55:23,672 INFO metabase.plugins :: Loading plugins in /home/metabase/metabase/plugins...
2024-05-09 14:55:24,034 INFO util.files :: Extract file /modules/athena.metabase-driver.jar -> /home/metabase/metabase/plugins/athena.metabase-driver.jar
2024-05-09 14:55:24,186 INFO util.files :: Extract file /modules/presto-jdbc.metabase-driver.jar -> /home/metabase/metabase/plugins/presto-jdbc.metabase-driver.jar
2024-05-09 14:55:24,276 INFO util.files :: Extract file /modules/snowflake.metabase-driver.jar -> /home/metabase/metabase/plugins/snowflake.metabase-driver.jar
2024-05-09 14:55:24,782 INFO util.files :: Extract file /modules/oracle.metabase-driver.jar -> /home/metabase/metabase/plugins/oracle.metabase-driver.jar
2024-05-09 14:55:24,784 INFO util.files :: Extract file /modules/googleanalytics.metabase-driver.jar -> /home/metabase/metabase/plugins/googleanalytics.metabase-driver.jar
2024-05-09 14:55:24,800 INFO util.files :: Extract file /modules/vertica.metabase-driver.jar -> /home/metabase/metabase/plugins/vertica.metabase-driver.jar
2024-05-09 14:55:24,801 INFO util.files :: Extract file /modules/mongo.metabase-driver.jar -> /home/metabase/metabase/plugins/mongo.metabase-driver.jar
2024-05-09 14:55:24,824 INFO util.files :: Extract file /modules/redshift.metabase-driver.jar -> /home/metabase/metabase/plugins/redshift.metabase-driver.jar
2024-05-09 14:55:24,833 INFO util.files :: Extract file /modules/sqlite.metabase-driver.jar -> /home/metabase/metabase/plugins/sqlite.metabase-driver.jar
2024-05-09 14:55:24,867 INFO util.files :: Extract file /modules/sqlserver.metabase-driver.jar -> /home/metabase/metabase/plugins/sqlserver.metabase-driver.jar
2024-05-09 14:55:24,879 INFO util.files :: Extract file /modules/sparksql.metabase-driver.jar -> /home/metabase/metabase/plugins/sparksql.metabase-driver.jar
2024-05-09 14:55:24,953 INFO util.files :: Extract file /modules/druid.metabase-driver.jar -> /home/metabase/metabase/plugins/druid.metabase-driver.jar
2024-05-09 14:55:24,958 INFO util.files :: Extract file /modules/bigquery-cloud-sdk.metabase-driver.jar -> /home/metabase/metabase/plugins/bigquery-cloud-sdk.metabase-driver.jar
2024-05-09 14:55:25,719 INFO plugins.classloader :: Added URL file:/home/metabase/metabase/plugins/ojdbc8.jar to classpath
2024-05-09 14:55:25,780 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :google...[0m
2024-05-09 14:55:25,784 INFO driver.impl :: [34mRegistered abstract driver :google[0m  
2024-05-09 14:55:25,810 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :bigquery-cloud-sdk...[0m
2024-05-09 14:55:25,811 INFO driver.impl :: [34mRegistered driver :bigquery-cloud-sdk[0m (parents: [:sql]) 
2024-05-09 14:55:25,821 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :clickhouse...[0m
2024-05-09 14:55:25,822 INFO driver.impl :: [34mRegistered driver :clickhouse[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:25,831 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
2024-05-09 14:55:25,833 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
2024-05-09 14:55:25,833 WARN plugins.lazy-loaded-driver :: [31mWarning: plugin manifest for :bigquery does not include connection properties[0m
2024-05-09 14:55:25,834 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :bigquery...[0m
2024-05-09 14:55:25,835 INFO driver.impl :: [34mRegistered driver :bigquery[0m (parents: [:sql :google]) 
2024-05-09 14:55:25,846 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :hive-like...[0m
2024-05-09 14:55:25,847 INFO driver.impl :: [34mRegistered abstract driver :hive-like[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:25,847 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :sparksql...[0m
2024-05-09 14:55:25,848 INFO driver.impl :: [34mRegistered driver :sparksql[0m (parents: [:hive-like]) 
2024-05-09 14:55:25,853 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :cubejs...[0m
2024-05-09 14:55:25,854 INFO driver.impl :: [34mRegistered driver :cubejs[0m  
2024-05-09 14:55:25,858 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :sqlite...[0m
2024-05-09 14:55:25,859 INFO driver.impl :: [34mRegistered driver :sqlite[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:25,866 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :redshift...[0m
2024-05-09 14:55:25,867 INFO driver.impl :: [34mRegistered driver :redshift[0m (parents: [:postgres]) 
2024-05-09 14:55:25,880 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :mongo...[0m
2024-05-09 14:55:25,881 INFO driver.impl :: [34mRegistered driver :mongo[0m  
2024-05-09 14:55:25,887 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :sqlserver...[0m
2024-05-09 14:55:25,888 INFO driver.impl :: [34mRegistered driver :sqlserver[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:25,897 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :starburst...[0m
2024-05-09 14:55:25,898 INFO driver.impl :: [34mRegistered driver :starburst[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:25,913 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :athena...[0m
2024-05-09 14:55:25,914 INFO driver.impl :: [34mRegistered driver :athena[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:25,920 INFO plugins.dependencies :: [31mMetabase cannot initialize plugin Metabase Vertica Driver due to required dependencies.[0m Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

2024-05-09 14:55:25,921 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
2024-05-09 14:55:25,922 INFO plugins.dependencies :: [33mPlugins with unsatisfied deps: ["Metabase Vertica Driver"][0m
2024-05-09 14:55:25,927 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :googleanalytics...[0m
2024-05-09 14:55:25,927 INFO driver.impl :: [34mRegistered driver :googleanalytics[0m  
2024-05-09 14:55:25,944 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :presto-jdbc...[0m
2024-05-09 14:55:25,945 INFO driver.impl :: [34mRegistered driver :presto-jdbc[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:25,949 INFO plugins.dependencies :: Plugin 'Metabase Presto Driver' depends on plugin 'Presto Common Driver'
2024-05-09 14:55:25,949 INFO plugins.dependencies :: Metabase Presto Driver dependency {:plugin Presto Common Driver} satisfied? false
2024-05-09 14:55:25,950 INFO plugins.dependencies :: [33mPlugins with unsatisfied deps: ["Metabase Presto Driver" "Metabase Vertica Driver"][0m
2024-05-09 14:55:25,954 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :druid...[0m
2024-05-09 14:55:25,955 INFO driver.impl :: [34mRegistered driver :druid[0m  
2024-05-09 14:55:25,965 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? true
2024-05-09 14:55:25,966 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :oracle...[0m
2024-05-09 14:55:25,967 INFO driver.impl :: [34mRegistered driver :oracle[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:26,008 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :snowflake...[0m
2024-05-09 14:55:26,009 INFO driver.impl :: [34mRegistered driver :snowflake[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:26,014 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :presto-common...[0m
2024-05-09 14:55:26,015 INFO driver.impl :: [34mRegistered abstract driver :presto-common[0m  
2024-05-09 14:55:26,015 INFO plugins.dependencies :: Metabase Presto Driver dependency {:plugin Presto Common Driver} satisfied? true
2024-05-09 14:55:26,019 DEBUG plugins.initialize :: [33mDependencies satisfied; these plugins will now be loaded: ["Metabase Presto Driver"][0m
2024-05-09 14:55:26,021 DEBUG plugins.lazy-loaded-driver :: [35mRegistering lazy loading driver :presto...[0m
2024-05-09 14:55:26,022 INFO driver.impl :: [34mRegistered driver :presto[0m (parents: [:presto-common]) 
2024-05-09 14:55:26,045 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2024-05-09 14:55:26,048 INFO db.setup :: [36mVerifying postgres Database Connection ...[0m
2024-05-09 14:55:26,638 INFO db.setup :: Successfully verified PostgreSQL 15.5 application database connection. 
2024-05-09 14:55:26,639 INFO db.setup :: [36mChecking if a database downgrade is required...[0m
2024-05-09 14:55:27,602 INFO db.setup :: Running Database Migrations...
2024-05-09 14:55:27,604 INFO db.setup :: Setting up Liquibase...
2024-05-09 14:55:27,972 INFO db.setup :: Liquibase is ready.
2024-05-09 14:55:27,973 INFO db.liquibase :: Checking if Database has unrun migrations...
2024-05-09 14:55:29,152 INFO db.liquibase :: Database has unrun migrations. Checking if migraton lock is taken...
2024-05-09 14:55:29,161 INFO db.liquibase :: No migration lock found.
2024-05-09 14:55:29,765 INFO db.liquibase :: Running 5 migrations ...
2024-05-09 14:55:30,449 INFO driver.impl :: [33mInitializing driver :sql...[0m
2024-05-09 14:55:30,449 INFO driver.impl :: [33mInitializing driver :sql-jdbc...[0m
2024-05-09 14:55:30,449 INFO driver.impl :: [33mInitializing driver :clickhouse...[0m
2024-05-09 14:55:30,450 INFO plugins.classloader :: Added URL file:/home/metabase/metabase/plugins/clickhouse.metabase-driver.jar to classpath
2024-05-09 14:55:30,451 DEBUG plugins.init-steps :: [34mLoading plugin namespace metabase.driver.clickhouse...[0m
2024-05-09 14:55:30,535 INFO driver.impl :: [34mRegistered driver :clickhouse[0m (parents: [:sql-jdbc]) 
2024-05-09 14:55:30,567 DEBUG plugins.jdbc-proxy :: [34mRegistering JDBC proxy driver for com.clickhouse.jdbc.ClickHouseDriver...[0m
2024-05-09 14:55:30,570 INFO metabase.util :: [36m ⮦ [35mLoad lazy loading driver :clickhouse[0m took 118.3 ms[0m
2024-05-09 14:55:30,621 INFO driver.impl :: [33mInitializing driver :mysql...[0m
2024-05-09 14:55:30,645 INFO driver.impl :: [33mInitializing driver :postgres...[0m
2024-05-09 14:55:30,658 INFO driver.impl :: [33mInitializing driver :cubejs...[0m
2024-05-09 14:55:30,659 INFO plugins.classloader :: Added URL file:/home/metabase/metabase/plugins/cubejs.metabase-driver.jar to classpath
2024-05-09 14:55:30,660 DEBUG plugins.init-steps :: [34mLoading plugin namespace metabase.driver.cubejs...[0m
2024-05-09 14:55:30,677 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v49.2024-04-09T10:00:03::qnkhuat encountered an exception.

UPDATE SUMMARY
Run:                          5
Previously run:             264
Filtered out:                17
-------------------------------
Total change sets:          286


FILTERED CHANGE SETS SUMMARY
DBMS mismatch:               17

2024-05-09 14:55:30,738 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.CommandExecutionException: java.lang.ClassCastException: class java.lang.ExceptionInInitializerError cannot be cast to class java.lang.Exception (java.lang.ExceptionInInitializerError and java.lang.Exception are in module java.base of loader 'bootstrap')
	at liquibase.command.CommandScope.execute(CommandScope.java:253)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
	at liquibase.Liquibase.update(Liquibase.java:234)
	at liquibase.Liquibase.update(Liquibase.java:212)
	at liquibase.Liquibase.update(Liquibase.java:194)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:305)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:287)
	at metabase.db.setup$migrate_BANG_$fn__51110.invoke(setup.clj:80)
	at metabase.db.liquibase$do_with_liquibase$f_STAR___48786.invoke(liquibase.clj:139)
	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:142)
	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:130)
	at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:75)
	at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:56)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:147)
	at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:141)
	at metabase.db.setup$setup_db_BANG_$fn__51138$fn__51139.invoke(setup.clj:165)
	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
	at metabase.db.setup$setup_db_BANG_$fn__51138.invoke(setup.clj:160)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:159)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
	at metabase.db$setup_db_BANG_$fn__51158.invoke(db.clj:69)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:64)
	at metabase.db$setup_db_BANG_.invoke(db.clj:55)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:116)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:101)
	at metabase.core$init_BANG_.invokeStatic(core.clj:159)
	at metabase.core$init_BANG_.invoke(core.clj:154)
	at metabase.core$start_normally.invokeStatic(core.clj:171)
	at metabase.core$start_normally.invoke(core.clj:165)
	at metabase.core$entrypoint.invokeStatic(core.clj:204)
	at metabase.core$entrypoint.doInvoke(core.clj:198)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.bootstrap.main(Unknown Source)
Caused by: java.lang.ClassCastException: class java.lang.ExceptionInInitializerError cannot be cast to class java.lang.Exception (java.lang.ExceptionInInitializerError and java.lang.Exception are in module java.base of loader 'bootstrap')
	at liquibase.command.CommandScope.logPrimaryExceptionToMdc(CommandScope.java:287)
	at liquibase.command.CommandScope.execute(CommandScope.java:245)
	... 49 more
2024-05-09 14:55:30,748 INFO metabase.core :: Metabase Shutting Down ...
2024-05-09 14:55:30,749 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2024-05-09 14:55:30,759 WARN db.liquibase :: ()
2024-05-09 14:55:30,762 INFO metabase.core :: Metabase Shutdown COMPLETE

```

**Comment by qnkhuat** [comment]
looking at your log, I don't see clickhouse driver being registered. Are you sure your `MB_PLUGINS_DIR` is pointing to the correct folder?

**Comment by qnkhuat** [comment]
I'm also seeing a cubejs driver. Their [repo](https://github.com/pyrooka/metabase-cubejs-driver) is archived and is 2 years old and I'm pretty sure it's not compatible with latest myetabase.

**Comment by paoliniluis** [comment]
Hi @sanel can you check the previous comment?

**Comment by sanel** [comment]
@paoliniluis it worked for me after I removed clickhouse driver. Actually, I removed plugins folder completely, leaving metabase to extract a fresh list of plugins. Do you need anything else from my side?

**Comment by qnkhuat** [comment]
should be a question for @dannyeuu

**Comment by dannyeuu** [comment]
> should be a question for @dannyeuu

Thanks, @sanel and @qnkhuat removing the cubejs plugin and upgrading to MB v0.49.9, and worked.

![Screenshot from 2024-05-14 09-25-39](https://github.com/metabase/metabase/assets/6808348/388249b9-e904-416b-a908-6465cfbd6ed0)
