### ISSUE TITLE
Migration Error from 0.49.8 to 0.49.9 or 0.49.10

### ISSUE THREAD

**Issue by jeromedumas-peekin** [metabase/metabase#42711]
**Describe the bug**
I am currently using Metabase version 0.49.8. When attempting to update to version 0.49.10, I encountered an error during the migration process. The error message is as follows:

**Logs**
2024-05-15 15:03:53,695 ERROR metabase.core :: Metabase Initialization FAILED
java.sql.BatchUpdateException: Batch entry 0 UPDATE databasechangelog SET FILENAME = CASE WHEN ID = ('v00.00-000') THEN ('migrations/001_update_migrations.yaml') WHEN ID < ('v45.00-001') THEN ('migrations/000_legacy_migrations.yaml') ELSE ('migrations/001_update_migrations.yaml') END was aborted: ERROR: duplicate key value violates unique constraint "idx_databasechangelog_id_author_filename"
  Detail: Key (id, author, filename)=(v00.00-000, qnkhuat, migrations/001_update_migrations.yaml) already exists.  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2413)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:579)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:912)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:936)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1733)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2544)
        at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:598)
        at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:591)
        at clojure.java.jdbc$db_do_execute_prepared_statement$fn__28513.invoke(jdbc.clj:1057)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1056)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1042)
        at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1080)
        at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1060)
        at clojure.java.jdbc$execute_BANG_$execute_helper__28581.invoke(jdbc.clj:1464)
        at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1466)
        at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1435)
        at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1456)
        at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1435)
        at metabase.db.liquibase$consolidate_liquibase_changesets_BANG_.invokeStatic(liquibase.clj:413)
        at metabase.db.liquibase$consolidate_liquibase_changesets_BANG_.invoke(liquibase.clj:400)
        at metabase.db.setup$migrate_BANG_$fn__51137.invoke(setup.clj:77)
        at metabase.db.liquibase$do_with_liquibase$f_STAR___48813.invoke(liquibase.clj:139)
        at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:142)
        at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:130)
        at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:75)
        at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:56)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:147)
        at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:141)
        at metabase.db.setup$setup_db_BANG_$fn__51165$fn__51166.invoke(setup.clj:165)
        at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
        at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
        at metabase.db.setup$setup_db_BANG_$fn__51165.invoke(setup.clj:160)
        at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:159)
        at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
        at metabase.db$setup_db_BANG_$fn__51185.invoke(db.clj:69)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:64)
        at metabase.db$setup_db_BANG_.invoke(db.clj:55)
        at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:116)
        at metabase.core$init_BANG__STAR_.invoke(core.clj:101)
        at metabase.core$init_BANG_.invokeStatic(core.clj:159)
        at metabase.core$init_BANG_.invoke(core.clj:154)
        at metabase.core$start_normally.invokeStatic(core.clj:171)
        at metabase.core$start_normally.invoke(core.clj:165)
        at metabase.core$entrypoint.invokeStatic(core.clj:204)
        at metabase.core$entrypoint.doInvoke(core.clj:198)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
        at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.bootstrap.main(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_databasechangelog_id_author_filename"
  Detail: Key (id, author, filename)=(v00.00-000, qnkhuat, migrations/001_update_migrations.yaml) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
        ... 61 more
2024-05-15 15:03:53,715 INFO metabase.core :: Metabase Shutting Down ...

**To Reproduce**
1. Dowload last version (0.49.10)
2. Run 'java -jar ./metabase.jar'

**Expected behavior**
This error prevents the successful completion of the update. Could you please assist in resolving this issue?

**Severity**
As a result, it is critically impacting our ability to use the latest version and benefit from its improvements and bug fixes. Given the severity, a prompt resolution would be greatly appreciated.

**Additional context**

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "6.1.75+",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.22"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-02",
      "tag": "v0.49.8",
      "hash": "38cb850"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

**Comment by ZencareJake** [comment]
Similar failure here:

```
Reason: clojure.lang.ExceptionInfo: Unexpected character ('T' (code 84)): Expected space separating root-level values
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v49.2024-04-09T10:00:03::qnkhuat:
2024-05-15 20:22:22,225 ERROR metabase.core :: Metabase Initialization FAILED
... 236 more
at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 3]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('T' (code 84)): Expected space separating root-level values
```
It looks like @ppavlov39 is having similar issues [here](https://github.com/metabase/metabase/issues/41924) 

In the logs I've listed above, the commit in question can be seen [here](https://github.com/metabase/metabase/commit/fe1f5950fb0ac03560b720b8cebeaf68b39a3eab)

**Comment by ZencareJake** [comment]
Looks like this has been addressed in some closed issues and will be resolved in 49.11

https://github.com/metabase/metabase/issues/42659#issuecomment-2112657115

**Comment by paoliniluis** [comment]
no, this is another thing, not the one that we already fixed

**Comment by ZencareJake** [comment]
> no, this is another thing, not the one that we already fixed

Gotcha, my apologies.

**Comment by qnkhuat** [comment]
An old thread on this: https://metaboat.slack.com/archives/C064EB1UE5P/p1704840138989869

**Comment by qnkhuat** [comment]
@jeromedumas-peekin I need some info to debug this.

Could you give us a dump of your `databasechangelog` table?

```sql
select * from databasechangelog;
```

**Comment by tomahawk-pilot** [comment]
```2024-05-16 05:51:13,979 ERROR metabase.core :: Metabase Initialization FAILED	[78c11c62d9c145849baa3ee103273639](https://ap-south-1.console.aws.amazon.com/ecs/v2/clusters/eximpe-production-ap-south-1/services/metabase/tasks/78c11c62d9c145849baa3ee103273639?region=ap-south-1)	metabase
May 16, 2024 at 11:21 (UTC+5:30)	liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v49.2024-04-09T10:00:03::qnkhuat:	[78c11c62d9c145849baa3ee103273639](https://ap-south-1.console.aws.amazon.com/ecs/v2/clusters/eximpe-production-ap-south-1/services/metabase/tasks/78c11c62d9c145849baa3ee103273639?region=ap-south-1)	metabase
May 16, 2024 at 11:21 (UTC+5:30)	Reason: clojure.lang.ExceptionInfo: Unrecognized token 'nTmBnuuIywXxYSR': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')```

**Comment by jeromedumas-peekin** [comment]
> @jeromedumas-peekin I need some info to debug this.
> 
> Could you give us a dump of your `databasechangelog` table?
> 
> ```sql
> select * from databasechangelog;
> ```

Yes, please find dump of `databasechangelog` table. 
[databasechangelog.csv](https://github.com/metabase/metabase/files/15337683/databasechangelog.csv)

**Comment by jeromedumas-peekin** [comment]
Same error with version 0.49.10

**Comment by qnkhuat** [comment]
@jeromedumas-peekin, I am looking at your database change log, and it seems like there was a weird migration sequence.
1) There are 2 migrations with IDs `v00.00-000`, and we should only have one.

2) all `databasechangelog.filename` is `migrations/000_migrations.yaml` except for one entry.

This filename only existed in the pre-48 versions; from 48, we changed it to either `migrations/000_legacy_migrations.yaml` or `migrations/001_update_migrations.yaml`.

This suggests that there was some attempt to run a pre48 version recently without a proper downgrade.

**Comment by qnkhuat** [comment]
The problem we're having here is not with migration, but it's trying to run this query on startup

```
UPDATE databasechangelog
SET FILENAME = CASE
                   WHEN ID = v00.00-000 THEN migrations/001_update_migrations.yaml
                   WHEN ID < v45.00-001 THEN migrations/000_legacy_migrations.yaml
                   ELSE migrations/001_update_migrations.yaml
               END
```
and it fails because your database change log has 2 migrations with id `v00.00-000`

**Comment by qnkhuat** [comment]
Try [this](https://github.com/metabase/metabase/issues/37344#issuecomment-1903146315) and see if it resolves your issue.

**Comment by jeromedumas-peekin** [comment]
Solve with `delete from databasechangelog where id = 'v00.00-000' and author = 'qnkhuat' and filename = '001_update_migrations.yaml';`

**Comment by qnkhuat** [comment]
@jeromedumas-peekin for our information, did something weird happen with your migration sequence?

I want to know why you have 2 such migrations in the first place.

**Comment by jeromedumas-peekin** [comment]
@qnkhuat No, nothing unusual happened with the migration sequence. I don't understand why i have 2 such migrations.
