### ISSUE TITLE
[Question] My Postgres DB does not support SSL and connections fail when I specify SSL

### ISSUE THREAD

**Issue by lauborges** [metabase/metabase#4275]
- metabase-deploy v0.22.2
- contained in Flynn

```
ERROR metabase.driver
 :: Failed to connect to database: org.postgresql.util.PSQLException: The server does not support SSL.
[2017-02-01T00:51:57.854543806Z] java.lang.AssertionError: Assert failed: Unable to connect to Metabase postgres DB.
[2017-02-01T00:51:57.855206056Z] (binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
[2017-02-01T00:51:57.855429715Z] 	at metabase.db$verify_db_connection.invokeStatic(db.clj:341)
[2017-02-01T00:51:57.857334188Z] 02-01 00:51:57 
ERROR metabase.core
 :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase postgres DB.
[2017-02-01T00:51:57.857393858Z] (binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
[2017-02-01T00:51:57.857456022Z] 	at metabase.db$verify_db_connection.invoke(db.clj:334)
[2017-02-01T00:51:57.857531487Z] 	at metabase.db$verify_db_connection.invokeStatic(db.clj:337)
[2017-02-01T00:51:57.857562435Z] 	at metabase.db$verify_db_connection.invoke(db.clj:334)
[2017-02-01T00:51:57.857658499Z] 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:390)
[2017-02-01T00:51:57.857700317Z] 	at metabase.db$setup_db_BANG_.doInvoke(db.clj:383)
[2017-02-01T00:51:57.857788562Z] 	at clojure.lang.RestFn.invoke(RestFn.java:421)
[2017-02-01T00:51:57.857816847Z] 	at metabase.core$init_BANG_.invokeStatic(core.clj:113)
[2017-02-01T00:51:57.857885149Z] 	at metabase.core$init_BANG_.invoke(core.clj:93)
[2017-02-01T00:51:57.857928056Z] 	at metabase.core$start_normally.invokeStatic(core.clj:196)
[2017-02-01T00:51:57.858016957Z] 	at metabase.core$start_normally.invoke(core.clj:190)
[2017-02-01T00:51:57.858035041Z] 	at metabase.core$_main.invokeStatic(core.clj:288)
[2017-02-01T00:51:57.858120159Z] 	at metabase.core$_main.doInvoke(core.clj:283)
[2017-02-01T00:51:57.858147943Z] 	at clojure.lang.RestFn.invoke(RestFn.java:397)
[2017-02-01T00:51:57.858216326Z] 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
[2017-02-01T00:51:57.858246849Z] 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
[2017-02-01T00:51:57.858302996Z] 	at metabase.core.main(Unknown Source)
[2017-02-01T00:51:57.886210758Z] 02-01 00:51:57 
INFO metabase.core
 :: Metabase Shutting Down ...
```

**Comment by camsaul** [comment]
@lauborges when opening issues please give us a little more info than just a stacktrace. It makes it easier for us to help you!

Anyway, it sounds like you're asking Metabase to connect to your Postgres DB via SSL but it doesn't support it.

**Comment by lauborges** [comment]
I have the following environment variable DATABASE_URL with value postgres://user:pass@host:port/db

And I`m using metabase-deploy v0.22.2

It's just that

Thanks for your attention @camsaul

**Comment by camsaul** [comment]
@lauborges try `postgres://user:pass@host:port/db?ssl=false`

**Comment by salsakran** [comment]
closing since this was an isloated report, and there has been no response to a suggested fix for almost 2 years.
