### ISSUE TITLE
Trend charts should break down gracefully on missing data

### ISSUE THREAD

**Issue by zbodi74** [metabase/metabase#42948]
### Describe the bug

Trend visualization breaks down in an unhelpful way when data is incomplete.

### To Reproduce

1. Create a native question returning a time series where the latest value is null:
```
    SELECT DATE '2024-05-21' AS created_at, null as v
    UNION ALL SELECT DATE '2024-05-20' , 1
    UNION ALL SELECT DATE '2024-05-19' , 2
    ORDER BY created_at
```
2. Save it, and explore results
3. Summarize: Sum of V, Group by Day:created_at
4. Visualize: Trend
5. (!)The following error is logged on the console: `Error: The latest data point contains a null value` and the visualization breaks with the triangle
<img width="78" alt="image" src="https://github.com/metabase/metabase/assets/11080638/e1f437e0-ec21-4667-ae55-e6466209140a">.
6. (!) Switching to the table view (still using trend viz) didn't resolve the issue, the triangle remains, and the data is not displayed even in table format.
7. (!) Switching to another viz and clicking the refresh button does not clear the error. Only a full page reload resolves it.

### Expected behavior

1. The trend viz should handle incomplete data gracefully. The user should be notified if the data unavailable. (Alternatively, following the behavior of previous versions, earlier data should be displayed when possible - perhaps this could be a configurable option.)
4. Users should be able to switch to table view even if the trend is not displayable.
5. Switching to another visualization should clear any errors.

### Logs

Console
```
react-dom.production.min.js:209 Error: The latest data point contains a null value
    at s.series (compute.js:182:11)
    at compute.js:234:1
[...]
```

### Information about your Metabase installation

```JSON
1.49.10
```

### Severity

P2 - confusing

### Additional context
The same data resulted in a different outcome in v1.48 - the change was computed based on the last two available values, though the dates were incorrect:
<img width="192" alt="image" src="https://github.com/metabase/metabase/assets/11080638/530921df-0b47-4b27-b211-7daaefc2905f">

_No response_

**Comment by zbodi74** [comment]
Adding the regression flag as this case was sort-of handled in v48.
