### ISSUE TITLE
Metabase - Duplicate entry error during migration from h2db to mysql

### ISSUE THREAD

**Issue by rich-pinto** [metabase/metabase#4309]
Hi,

I am trying to migrate metabase(latest version) db from h2db to mysql. When I run the migration command, I see the following error. Could you please advise?

```
java -jar metabase.jar load-from-h2 /opt/metabase/metabase.db
02-06 06:03:04 INFO metabase.util :: Loading Metabase...
02-06 06:03:12 INFO metabase.db :: Verifying mysql Database Connection ...
02-06 06:03:12 DEBUG metabase.driver :: Registered driver :mysql 🚚
02-06 06:03:12 INFO metabase.db :: Verify Database Connection ...  ✅
02-06 06:03:12 INFO metabase.db :: Running Database Migrations...
02-06 06:03:12 INFO metabase.db :: Setting up Liquibase...
02-06 06:03:12 INFO metabase.db :: Liquibase is ready.
02-06 06:03:12 INFO metabase.db :: Checking if Database has unrun migrations...
02-06 06:03:28 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
Temporarily disabling DB constraints...
[OK]
Transfering 9 instances of Database....[OK]
Transfering 1430 instances of RawTable........[OK]
Transfering 16640 instances of RawColumn........................................BatchUpdateException:
 Message: Duplicate entry '1019-paymenttype' for key 'uniq_raw_column_table_name'
 SQLState: 23000
 Error Code: 1062
java.sql.BatchUpdateException: Duplicate entry '1019-paymenttype' for key 'uniq_raw_column_table_name'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1161)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
	at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:426)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:419)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__2749.invoke(jdbc.clj:792)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:637)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:791)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:778)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:814)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795)
	at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1069)
	at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1061)
	at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1110)
	at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1093)
	at metabase.cmd.load_from_h2$insert_entity_BANG_$fn__32077.invoke(load_from_h2.clj:132)
	at metabase.cmd.load_from_h2$insert_entity_BANG_.invokeStatic(load_from_h2.clj:131)
	at metabase.cmd.load_from_h2$insert_entity_BANG_.invoke(load_from_h2.clj:113)
	at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:147)
	at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:141)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__32157.invoke(load_from_h2.clj:216)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:629)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:213)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:206)
	at clojure.lang.Var.invoke(Var.java:379)
	at metabase.core$load_from_h2.invokeStatic(core.clj:219)
	at metabase.core$load_from_h2.invoke(core.clj:212)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$run_cmd$fn__32911.invoke(core.clj:273)
	at metabase.core$run_cmd.invokeStatic(core.clj:273)
	at metabase.core$run_cmd.doInvoke(core.clj:272)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$_main.invokeStatic(core.clj:287)
	at metabase.core$_main.doInvoke(core.clj:283)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1019-paymenttype' for key 'uniq_raw_column_table_name'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751)
	... 48 more
Command failed with exception: Duplicate entry '1019-paymenttype' for key 'uniq_raw_column_table_name'
```

**Comment by camsaul** [comment]
@rich-pinto what version of Metabase are you using? We fixed that bug a while back

**Comment by camsaul** [comment]
@rich-pinto ?

**Comment by kjad** [comment]
Hello, I have encountered the same bug while attempting a migration from H2 to mysql (actually MariaDB 10.1). I am running version 0.23.0 of metabase. There are also some liquibase warnings in the output. See below:

```
03-30 17:24:12 INFO metabase.util :: Loading Metabase...
03-30 17:24:12 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
03-30 17:24:17 INFO metabase.db :: Verifying mysql Database Connection ...
03-30 17:24:17 DEBUG metabase.driver :: Registered driver :mysql 🚚
03-30 17:24:17 INFO metabase.db :: Verify Database Connection ...  ✅
03-30 17:24:17 INFO metabase.db :: Running Database Migrations...
03-30 17:24:17 INFO metabase.db :: Setting up Liquibase...
03-30 17:24:17 INFO metabase.db :: Liquibase is ready.
03-30 17:24:17 INFO metabase.db :: Checking if Database has unrun migrations...
03-30 17:24:33 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
03-30 17:24:33 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
03-30 17:24:33 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
03-30 17:24:33 INFO metabase.db :: Migration lock is cleared. Running migrations...
03-30 17:24:33 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
03-30 17:24:33 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
03-30 17:24:49 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
Temporarily disabling DB constraints...
[OK]
Transfering 13 instances of Database....[OK]
Transfering 517 instances of RawTable.....[OK]
Transfering 8939 instances of RawColumn................BatchUpdateException:
 Message: Duplicate entry '100-action' for key 'uniq_raw_column_table_name'
 SQLState: 23000
 Error Code: 1062
java.sql.BatchUpdateException: Duplicate entry '100-action' for key 'uniq_raw_column_table_name'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1161)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
	at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:426)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:419)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__1881.invoke(jdbc.clj:792)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:637)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:791)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:778)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:814)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795)
	at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1069)
	at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1061)
	at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1110)
	at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1093)
	at metabase.cmd.load_from_h2$insert_entity_BANG_$fn__35182.invoke(load_from_h2.clj:133)
	at metabase.cmd.load_from_h2$insert_entity_BANG_.invokeStatic(load_from_h2.clj:132)
	at metabase.cmd.load_from_h2$insert_entity_BANG_.invoke(load_from_h2.clj:114)
	at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:148)
	at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:142)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__35262.invoke(load_from_h2.clj:217)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:629)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:214)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:207)
	at clojure.lang.Var.invoke(Var.java:379)
	at metabase.core$load_from_h2.invokeStatic(core.clj:221)
	at metabase.core$load_from_h2.invoke(core.clj:214)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$run_cmd$fn__36034.invoke(core.clj:275)
	at metabase.core$run_cmd.invokeStatic(core.clj:275)
	at metabase.core$run_cmd.doInvoke(core.clj:274)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$_main.invokeStatic(core.clj:289)
	at metabase.core$_main.doInvoke(core.clj:285)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '100-action' for key 'uniq_raw_column_table_name'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751)
	... 48 more
Command failed with exception: Duplicate entry '100-action' for key 'uniq_raw_column_table_name'
```

**Comment by kjad** [comment]
@camsaul I can replicate the issue, please let me know if you need any additional information to troubleshoot this. Thank you.

**Comment by img22** [comment]
I encountered this same issue while using `load-from-h2 `. Looks like the migration fails if there are columns in raw_table or raw_column tables that are identical but with different cases. E.g. I had  two entries in `raw_table` with `Name` "state" and "State". The migration treats them as duplicate. Perhaps case sensitive issue in the script?

**Comment by mnzt** [comment]
Just hit this issue with Metbase v0.24.2. @img22 Seems to be correct here.

**Comment by camsaul** [comment]
@salsakran this looks like another thing we would fix by taking out the RawTable and RawColumn models (#3448)
