### ISSUE TITLE
No method in multimethod 'connection-details->spec' for dispatch value: :databend

### ISSUE THREAD

**Issue by hantmac** [metabase/metabase#43171]
### Describe the bug

I am writing a custom metabase driver for databend and when I use the latest version of metabase, I got an error:

```
{:message "No method in multimethod 'connection-details->spec' for dispatch value: :databend"}

```

When I downgrade to 0.47 it works well.

### To Reproduce

1. Download the 0.49.12 version metabase.jar to metabase-databend-driver
2. cd metabase-databend-driver
3. mvn deploy:deploy-file -Durl=file:repo -DgroupId=com.databend -DartifactId=metabase-core -Dversion=1.40 -Dpackaging=jar -Dfile=metabase.jar
4. LEIN_SNAPSHOTS_IN_RELEASE=true DEBUG=1 lein uberjar
5. cp target/uberjar/databend.metabase-driver.jar ./plugins
6. java -jar metabase.jar
7. Open localhost:3000 and add a databend database.
8. Got the error

### Expected behavior

Add database correctly.

### Logs

clojure.lang.ExceptionInfo: No method in multimethod 'connection-details->spec' for dispatch value: :databend {:message "No method in multimethod 'connection-details->spec' for dispatch value: :databend"}
        at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:165)
        at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:136)
        at clojure.lang.RestFn.invoke(RestFn.java:442)
        at metabase.api.database$test_database_connection.invokeStatic(database.clj:706)
        at metabase.api.database$test_database_connection.doInvoke(database.clj:696)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at metabase.api.database$test_connection_details.invokeStatic(database.clj:760)
        at metabase.api.database$test_connection_details.invoke(database.clj:740)
        at metabase.api.database$fn__98532.invokeStatic(database.clj:782)
        at metabase.api.database$fn__98532.invoke(database.clj:764)
        at compojure.core$wrap_response$fn__44694.invoke(core.clj:160)
        at compojure.core$wrap_route_middleware$fn__44678.invoke(core.clj:132)
        at compojure.core$wrap_route_info$fn__44683.invoke(core.clj:139)
        at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:151)
        at clojure.lang.Var.invoke(Var.java:393)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:152)
        at clojure.lang.Var.invoke(Var.java:393)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706.invoke(core.clj:200)
        at metabase.server.middleware.auth$enforce_authentication$fn__94071.invoke(auth.clj:17)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706.invoke(core.clj:200)
        at compojure.core$make_context$handler__44734.invoke(core.clj:290)
        at compojure.core$make_context$fn__44738.invoke(core.clj:300)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$make_context$fn__44738.invoke(core.clj:301)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$make_context$fn__44738.invoke(core.clj:301)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$make_context$fn__44738.invoke(core.clj:301)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$make_context$fn__44738.invoke(core.clj:301)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$make_context$fn__44738.invoke(core.clj:301)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$make_context$fn__44738.invoke(core.clj:301)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$make_context$fn__44738.invoke(core.clj:301)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$make_context$fn__44738.invoke(core.clj:301)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at metabase.api.routes$fn__102137$fn__102140.invoke(routes.clj:67)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706.invoke(core.clj:200)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.server.routes$fn__102302$fn__102303.doInvoke(routes.clj:72)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706.invoke(core.clj:200)
        at compojure.core$make_context$handler__44734.invoke(core.clj:290)
        at compojure.core$make_context$fn__44738.invoke(core.clj:300)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:153)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:153)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:153)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197)
        at metabase.server.routes$fn__102287$fn__102289.invoke(routes.clj:49)
        at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198)
        at compojure.core$routes$fn__44706.invoke(core.clj:200)
        at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__98815.invoke(exceptions.clj:108)
        at metabase.server.middleware.exceptions$catch_api_exceptions$fn__98812.invoke(exceptions.clj:96)
        at metabase.server.middleware.log$log_api_call$fn__102579$fn__102580$fn__102581.invoke(log.clj:230)
        at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18)
        at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12)
        at metabase.server.middleware.log$log_api_call$fn__102579$fn__102580.invoke(log.clj:222)
        at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112)
        at toucan2.execute$do_with_call_counts.invoke(execute.clj:103)
        at metabase.server.middleware.log$log_api_call$fn__102579.invoke(log.clj:221)
        at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__104644.invoke(browser_cookie.clj:40)
        at metabase.server.middleware.security$add_security_headers$fn__98771.invoke(security.clj:182)
        at metabase.server.middleware.json$wrap_json_body$fn__46051.invoke(json.clj:67)
        at metabase.server.middleware.offset_paging$handle_paging$fn__84969.invoke(offset_paging.clj:43)
        at metabase.server.middleware.json$wrap_streamed_json_response$fn__46069.invoke(json.clj:103)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__104911.invoke(keyword_params.clj:55)
        at ring.middleware.params$wrap_params$fn__104930.invoke(params.clj:77)
        at metabase.server.middleware.misc$maybe_set_site_url$fn__67316.invoke(misc.clj:61)
        at metabase.server.middleware.session$reset_session_timeout$fn__72747.invoke(session.clj:546)
        at metabase.server.middleware.session$bind_current_user$fn__72713$fn__72714.invoke(session.clj:440)
        at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:419)
        at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:403)
        at metabase.server.middleware.session$bind_current_user$fn__72713.invoke(session.clj:439)
        at metabase.server.middleware.session$wrap_current_user_info$fn__72696.invoke(session.clj:378)
        at metabase.server.middleware.session$wrap_session_id$fn__72668.invoke(session.clj:257)
        at metabase.server.middleware.auth$wrap_static_api_key$fn__94079.invoke(auth.clj:30)
        at ring.middleware.cookies$wrap_cookies$fn__104831.invoke(cookies.clj:194)
        at metabase.server.middleware.misc$add_content_type$fn__67298.invoke(misc.clj:29)
        at metabase.server.middleware.misc$disable_streaming_buffering$fn__67324.invoke(misc.clj:78)
        at ring.middleware.gzip$wrap_gzip$fn__104873.invoke(gzip.clj:86)
        at metabase.server.middleware.misc$bind_request$fn__67327.invoke(misc.clj:95)
        at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__104660.invoke(ssl.clj:41)
        at metabase.server$async_proxy_handler$fn__67738.invoke(server.clj:78)
        at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: No method in multimethod 'connection-details->spec' for dispatch value: :databend
        at clojure.lang.MultiFn.getFn(MultiFn.java:156)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection$fn__51133.invoke(connection.clj:315)
        at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:165)
        at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:314)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:310)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:339)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:335)
        at metabase.driver.sql_jdbc$fn__106882.invokeStatic(sql_jdbc.clj:49)
        at metabase.driver.sql_jdbc$fn__106882.invoke(sql_jdbc.clj:47)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.driver.util$can_connect_with_details_QMARK_$fn__60068.invoke(util.clj:148)
        at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more
2024-05-27 14:24:48,441 DEBUG middleware.log :: POST /api/database 400 80.4 ms（1个数据库调用） 
{:message "No method in multimethod 'connection-details->spec' for dispatch value: :databend"}

### Information about your Metabase installation

```JSON
- Macos 
- metabase 0.49.12
```

### Severity

high

**Comment by Tony-metabase** [comment]
Metabase doesn't support metabase-databend-driver ... you will need to check with the guys who created the repo:

https://github.com/databendcloud/metabase-databend-driver

Also note the repo version because there wasn't any update since Sep 2023 so probably the driver needs to be updated to be compatible with version 49

**Comment by hantmac** [comment]
> Metabase doesn't support metabase-databend-driver ... you will need to check with the guys who created the repo:
> 
> https://github.com/databendcloud/metabase-databend-driver
> 
> Also note the repo version because there wasn't any update since Oct 2023 so probably the driver needs to be updated to be compatible with version 49

Hi @Tony-metabase , thanks for responsing, I am actually working on the metabase-databend-driver, and I want to make to compatible with version 49. So what break changes in metabase 49 version ?  Because I use 47, 48 works well.  Or some docs can metabase driver developer can read?

**Comment by hantmac** [comment]
> So this should get you started https://www.metabase.com/docs/latest/developers-guide/drivers/start
> 
> Also go through each version here and make sure your driver supports the changes mentioned there:
> 
> https://www.metabase.com/docs/v0.49/developers-guide/driver-changelog

Thanks very much!
