### ISSUE TITLE
Failed to upgrade v0.44.4 -> v0.49.13

### ISSUE THREAD

**Issue by j1kwen** [metabase/metabase#43641]
### Describe the bug

When I tried to upgrade from v0.44.4 to v0.49.13, the new instance failed to start. I discovered that the new version requires MySQL 8, but my environment is MySQL 5.7. 
At this point, I attempted to roll back the data by executing` java -jar metabase.jar migrate down` 
The rollback was successful, with the message:
`Rolling back app database schema to version 48`
However, I am still unable to start my v0.44.4 instance.

### To Reproduce

1. Stop the Metabase instance.
2. Replace with v0.49.13 JAR file.
3. Start the new instance.
4. Instance fails to start, perform rollback operation. ` java -jar metabase.jar migrate down` 
5. Start the old instance.

### Logs

```
2024-06-05 16:47:33,486 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2024-06-05 16:47:33,489 INFO db.setup :: Verifying mysql Database Connection ...
2024-06-05 16:47:33,628 INFO db.setup :: Successfully verified MySQL 5.7.27 application database connection. ✅
2024-06-05 16:47:33,629 INFO db.setup :: Running Database Migrations...
2024-06-05 16:47:33,630 INFO db.setup :: Setting up Liquibase...
2024-06-05 16:47:33,782 INFO db.setup :: Liquibase is ready.
2024-06-05 16:47:33,782 INFO db.liquibase :: Checking if Database has unrun migrations...
2024-06-05 16:47:34,768 INFO db.liquibase :: Database has unrun migrations. Waiting for migration lock to be cleared...
2024-06-05 16:47:34,866 INFO db.liquibase :: Migration lock is cleared. Running migrations...
2024-06-05 16:47:35,038 INFO db.setup :: Database Migrations Current ...  ✅
2024-06-05 16:47:35,051 INFO db.data-migrations :: Running all necessary data migrations, this may take a minute.
2024-06-05 16:47:35,057 ERROR metabase.core :: Metabase Initialization FAILED
java.sql.SQLSyntaxErrorException: (conn=3053054) Table 'metabase.data_migrations' doesn't exist
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1113)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at toucan.db$query.invokeStatic(db.clj:308)
	at toucan.db$query.doInvoke(db.clj:304)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$simple_select.invokeStatic(db.clj:414)
	at toucan.db$simple_select.invoke(db.clj:403)
	at toucan.db$select.invokeStatic(db.clj:708)
	at toucan.db$select.doInvoke(db.clj:702)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at toucan.db$select_field.invokeStatic(db.clj:733)
	at toucan.db$select_field.doInvoke(db.clj:725)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$apply.invoke(core.clj:662)
	at toucan.db$select_ids.invokeStatic(db.clj:743)
	at toucan.db$select_ids.doInvoke(db.clj:736)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.db.data_migrations$run_all_BANG_.invokeStatic(data_migrations.clj:61)
	at metabase.db.data_migrations$run_all_BANG_.invoke(data_migrations.clj:57)
	at clojure.lang.Var.invoke(Var.java:380)
	at metabase.db.setup$fn__35519$run_data_migrations_BANG___35524$fn__35525.invoke(setup.clj:131)
	at metabase.db.setup$fn__35519$run_data_migrations_BANG___35524.invoke(setup.clj:122)
	at metabase.db.setup$fn__35544$setup_db_BANG___35549$fn__35550$fn__35553$fn__35554.invoke(setup.clj:146)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:716)
	at metabase.util$do_with_us_locale.invoke(util.clj:702)
	at metabase.db.setup$fn__35544$setup_db_BANG___35549$fn__35550$fn__35553.invoke(setup.clj:143)
	at metabase.db.setup$fn__35544$setup_db_BANG___35549$fn__35550.invoke(setup.clj:142)
	at metabase.db.setup$fn__35544$setup_db_BANG___35549.invoke(setup.clj:136)
	at metabase.db$setup_db_BANG_$fn__35579.invoke(db.clj:65)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:60)
	at metabase.db$setup_db_BANG_.invoke(db.clj:51)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:100)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:83)
	at metabase.core$init_BANG_.invokeStatic(core.clj:145)
	at metabase.core$init_BANG_.invoke(core.clj:140)
	at metabase.core$start_normally.invokeStatic(core.clj:157)
	at metabase.core$start_normally.invoke(core.clj:151)
	at metabase.core$_main.invokeStatic(core.clj:190)
	at metabase.core$_main.doInvoke(core.clj:184)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Table 'metabase.data_migrations' doesn't exist
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 57 more
Caused by: java.sql.SQLException: Table 'metabase.data_migrations' doesn't exist
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1695)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1557)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1520)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
	... 58 more
2024-06-05 16:47:35,064 INFO metabase.core :: Metabase Shutting Down ...
2024-06-05 16:47:35,065 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2024-06-05 16:47:35,071 INFO metabase.core :: Metabase Shutdown COMPLETE

```

### Information about your Metabase installation

```
Metabase:V0.44.4
Database:mysql 5.7.27
```

### Severity

P0

**Comment by paoliniluis** [comment]
"Rolling back app database schema to version 48", so the database version is now in v48, you need to spin up that version and not v44

**Comment by j1kwen** [comment]
However, upgrade to v0.49 did not complete successfully. checking the table `DATABASECHANGELOG`, the last entry is `v48.00-032`. Therefore, even after executing `java -jar metabase.jar migrate down` with v0.49, it is still not possible to start v0.48. The error is as follows.

```
2024-06-06 09:17:56,026 INFO db.setup :: Checking if a database downgrade is required...
2024-06-06 09:17:56,347 INFO db.setup :: Running Database Migrations...
2024-06-06 09:17:56,348 INFO db.setup :: Setting up Liquibase...
2024-06-06 09:17:56,367 INFO db.setup :: Liquibase is ready.
2024-06-06 09:17:56,367 INFO db.liquibase :: Checking if Database has unrun migrations...
2024-06-06 09:17:56,843 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.ValidationFailedException: Validation Failed:
     175 changesets check sum
          migrations/001_update_migrations.yaml::v00.00-000::qnkhuat was: 9:cecb4c73745e92033c738dbf3d6e747e but is now: 8:a59595109e74e7a2678a1b0dfd25f74a
          migrations/001_update_migrations.yaml::v45.00-001::snoe was: 9:24324f06a65a9bb339c735f02cbfb47f but is now: 8:ec8c30ee4f53a15a36c402d8124bb8af
          migrations/001_update_migrations.yaml::v45.00-002::snoe was: 9:d2c9f50f5a29947a07e4808957d63ab6 but is now: 8:6da7a6285edb138c404de0eeba209570
          migrations/001_update_migrations.yaml::v45.00-003::snoe was: 9:dafaaf7c9f0efbf92670ea93c001f7a1 but is now: 8:512337d6d4af38016aa79585abbe03a1
          migrations/001_update_migrations.yaml::v45.00-011::snoe was: 9:c539f152aa1c2287c5b602c7a395f9e8 but is now: 8:dcf1cda9f20dca4b6ff8101b13b98c4a
          migrations/001_update_migrations.yaml::v45.00-012::snoe was: 9:4b66ab5561933821db3a68d21ce43b6b but is now: 8:5ff2660791f217125b263ccddeacb585
          migrations/001_update_migrations.yaml::v45.00-013::snoe was: 9:54c5d6a9659b7ae62e8c42f60f9620d2 but is now: 8:26dba276b14255d4346507a1a25d117b
          migrations/001_update_migrations.yaml::v45.00-022::snoe was: 9:4f00f51af294ccdd99b6029b7a023643 but is now: 8:c9d0fc313dfb8b88ac500136d625cdca
          migrations/001_update_migrations.yaml::v45.00-023::snoe was: 9:082d296233ee6dbbf2871b9d93c3a6a4 but is now: 8:c6c1ff9ca3b62d4cda3a2d782dd86f2f
          migrations/001_update_migrations.yaml::v45.00-025::metamben was: 9:2214b0d71acc8a8cf90781a2aca98664 but is now: 8:50a43cea3123ecdb602123825f5a7dbf
          migrations/001_update_migrations.yaml::v45.00-026::snoe was: 9:9f2ce2d2d79d0dce365ddf3464d1f648 but is now: 8:ae77d4086998911877e3207fcf90c9c7
          migrations/001_update_migrations.yaml::v45.00-027::snoe was: 9:73718f7b7c3fb4ef30f71dc6e6170528 but is now: 8:40c3c8391c1416a3bce09ca3c7237173
          migrations/001_update_migrations.yaml::v45.00-028::camsaul was: 9:883315d70f3fc10b07858aa0e48ed9da but is now: 8:f8f68f80627aeb2ef7f28f2af2b5a31b
          migrations/001_update_migrations.yaml::v45.00-029::camsaul was: 9:fe3b8aca811ef5b541f922a83c7ded8c but is now: 8:579957652133eab3ee023dd911162a1e
          migrations/001_update_migrations.yaml::v45.00-030::camsaul was: 9:63da8f2f82baf396ad30f3fd451c501d but is now: 8:41eda097feb034c4d01b2dbda74753c8
          migrations/001_update_migrations.yaml::v45.00-031::camsaul was: 9:3628c1c692bec0f7258ea983b18340b5 but is now: 8:6416e373e335dc1c12c7571af674dede
          migrations/001_update_migrations.yaml::v45.00-033::camsaul was: 9:b93dab321e4a1fcaeb74d12b52867fd4 but is now: 8:34df79fc79e086ab05bb2fd79bb4e322
          migrations/001_update_migrations.yaml::v45.00-035::camsaul was: 9:207984e21c44681a6135592cab3d0f3f but is now: 8:dcee49781d80d9c4be5ad9dd51975a07
          migrations/001_update_migrations.yaml::v45.00-036::snoe was: 9:1c5db47da78b69f2540542243b529e65 but is now: 8:d6d138f84722d9f99987669910c4c376
          migrations/001_update_migrations.yaml::v45.00-037::snoe was: 9:6600702fb0cc9dcd8628fca8df9c0b39 but is now: 8:56f548cc84a53cc6d18302761ee71554
          migrations/001_update_migrations.yaml::v45.00-039::camsaul was: 9:7b331f47a0260218275c58fa21fdcc60 but is now: 8:2c539d76d3aead7f7366b15333132b30
          migrations/001_update_migrations.yaml::v45.00-041::camsaul was: 9:84d479472b81809b8067f72b28934954 but is now: 8:82dc368fa3e0163a06929da6e9556fe2
          migrations/001_update_migrations.yaml::v45.00-042::camsaul was: 9:f600f2e052bf44938d081165c8d87364 but is now: 8:d04207471480e335f14094e9a7a5d293
          migrations/001_update_migrations.yaml::v45.00-043::camsaul was: 9:daa8b1249027fa4c9ea07f1acb8ee889 but is now: 8:d06439bc30e5b98e267c22630909b7d8
          migrations/001_update_migrations.yaml::v45.00-044::metamben was: 9:39c664afe6e6c6598576c7575931b106 but is now: 8:f5bcfdfd0f2135f44c2864f9542ce766
          migrations/001_update_migrations.yaml::v45.00-048::camsaul was: 9:122ebd5e3f3b30b61b66bfad0e9ab1b0 but is now: 8:5615941cbbe6d267348a8bfc9182bd79

```
