### ISSUE TITLE
Slack alert is no longer working due to Slack API change

### ISSUE THREAD

**Issue by vomc** [metabase/metabase#43651]
### Describe the bug

I created an alert that posts hourly in a slack channel. Everything seems to be configured correctly, app has permissions, is in channel etc but nothing is getting posted. Looking at the logs on Metabase I see the below error about how the file upload method appears to be deprecated.

Am I the only one seeing this error? If it was truly a Slack API deprecation I would imagine it could affect many users

```
[7b568b01-c93f-4669-90d8-818222003329] 2024-06-05T11:00:35+02:00 ERROR metabase.pulse Error sending notification!
clojure.lang.ExceptionInfo: Slack API error: method_deprecated {:error-code "method_deprecated", :message "Slack API error: method_deprecated", :response {:ok false, :error "method_deprecated"}, :url "https://slack.com/api/files.upload"}
	at metabase.integrations.slack$do_slack_request.invokeStatic(slack.clj:148)
	at metabase.integrations.slack$do_slack_request.invoke(slack.clj:129)
	at metabase.integrations.slack$POST.invokeStatic(slack.clj:158)
	at metabase.integrations.slack$POST.invoke(slack.clj:155)
	at metabase.integrations.slack$fn__90612$_AMPERSAND_f__90613$fn__90614.invoke(slack.clj:330)
	at metabase.integrations.slack$fn__90612$_AMPERSAND_f__90613.invoke(slack.clj:329)
	at metabase.integrations.slack$fn__90612$fn__90619.invoke(slack.clj:320)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_$fn__101155.invoke(pulse.clj:342)
	at clojure.core.protocols$naive_seq_reduce.invokeStatic(protocols.clj:62)
	at clojure.core.protocols$interface_or_naive_reduce.invokeStatic(protocols.clj:72)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:169)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8234.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8234.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:335)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:326)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:332)
	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:326)
	at metabase.pulse$fn__101314.invokeStatic(pulse.clj:532)
	at metabase.pulse$fn__101314.invoke(pulse.clj:530)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.util.retry$decorate$fn$reify__68358.call(retry.clj:77)
	at io.github.resilience4j.retry.Retry.lambda$decorateCallable$5(Retry.java:306)
	at metabase.util.retry$decorate$fn__68357.doInvoke(retry.clj:78)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.pulse$send_notification_retrying_BANG_.invokeStatic(pulse.clj:552)
	at metabase.pulse$send_notification_retrying_BANG_.doInvoke(pulse.clj:549)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at metabase.pulse$send_notifications_BANG_$fn__101332.invoke(pulse.clj:559)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:558)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:554)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:582)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:563)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at metabase.task.send_pulses$fn__103529$send_pulses_BANG___103538$fn__103541$fn__103561$fn__103562.invoke(send_pulses.clj:61)
	at metabase.models.task_history$fn__57476$_AMPERSAND_f__57477.invoke(task_history.clj:96)
	at metabase.models.task_history$fn__57476$fn__57479.invoke(task_history.clj:91)
	at metabase.task.send_pulses$fn__103529$send_pulses_BANG___103538$fn__103541$fn__103561.invoke(send_pulses.clj:57)
	at metabase.task.send_pulses$fn__103529$send_pulses_BANG___103538$fn__103541.invoke(send_pulses.clj:56)
	at metabase.task.send_pulses$fn__103529$send_pulses_BANG___103538.invoke(send_pulses.clj:43)
	at metabase.task.send_pulses$fn__103529$send_pulses_BANG___103538$fn__103539.invoke(send_pulses.clj:50)
	at metabase.task.send_pulses$fn__103529$send_pulses_BANG___103538.invoke(send_pulses.clj:43)
	at metabase.task.send_pulses.SendPulses$fn__103640.invoke(send_pulses.clj:114)
	at metabase.models.task_history$fn__57476$_AMPERSAND_f__57477.invoke(task_history.clj:96)
	at metabase.models.task_history$fn__57476$fn__57479.invoke(task_history.clj:91)
	at metabase.task.send_pulses.SendPulses.execute(send_pulses.clj:100)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: clojure.lang.ExceptionInfo: Slack API error: method_deprecated {:error-code "method_deprecated", :message "Slack API error: method_deprecated", :response {:ok false, :error "method_deprecated"}}
	at metabase.integrations.slack$handle_error.invokeStatic(slack.clj:120)
	at metabase.integrations.slack$handle_error.invoke(slack.clj:101)
	at metabase.integrations.slack$handle_response.invokeStatic(slack.clj:127)
	at metabase.integrations.slack$handle_response.invoke(slack.clj:122)
	at metabase.integrations.slack$do_slack_request.invokeStatic(slack.clj:146)
	... 58 more
```

### To Reproduce

1. Create a slack app and an alert that posts to slack hourly
2. See if something is getting posted in slack or if you are also seeing this error in the Metabase logs

### Expected behavior

I would assume that a post appears in the specified channel in slack

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.22+7",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.22",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.22+7",
    "os.name": "Linux",
    "os.version": "4.14.290-217.505.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "Europe/Berlin"
  },
  "metabase-info": {
    "databases": [
      "athena",
      "bigquery-cloud-sdk",
      "googleanalytics",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.17"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.6.0"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-02-06",
      "tag": "v0.48.5",
      "hash": "dab12cf"
    },
    "settings": {
      "report-timezone": "Europe/Berlin"
    }
  }
}
```

### Severity

blocking

**Comment by qnkhuat** [comment]
Please upgrade to the latest version, or 48.13 which includes the [fix](https://github.com/metabase/metabase/issues/41890)
