### ISSUE TITLE
Field Filter can't auto search and return the matched list whatever we did in both dashboard filter and questions filter

### ISSUE THREAD

**Issue by bladexxx** [metabase/metabase#43803]
### Describe the bug

no matched items listed when I input a value in the dropdown list of Dashboard filter.

same issues happened in question filter.

![image](https://github.com/metabase/metabase/assets/863963/77178a91-3772-4712-a2d8-a2e1cc7d35ae)
![image](https://github.com/metabase/metabase/assets/863963/d5a11b26-719c-40c2-a13c-18fee470dbe0)

for the table,  I have done the configuration in table metadata with admin 
![image](https://github.com/metabase/metabase/assets/863963/d13c66ce-f698-4c49-9269-b88f2f3792bc)
DB is clickhouse
metabase version v0.49.11

### To Reproduce

create a question, 
add a filter for a category field.  there are values list in the dropdown list
when input a value in inputbox of the dropdown list. nothing return Even if it should match many items

### Information about your Metabase installation

```JSON
Microsoft Edge  125.0.2535.85   (64 bit)
DB is clickhouse:  ClickHouse server version 22.8.21.38 (official build).
metabase version v0.49.11

Below is the error in metabase log:

[562e5813-8c9b-43a8-812e-5c59d5a56f91] 2024-06-07T11:34:43+08:00 ERROR metabase.api.field Error searching field values,java.lang.RuntimeException: [:ref :metabase.mbql.schema/value] is not a valid sequence schema; a valid sequence schema consists of zero or more `one` elements, followed by zero or more `optional` elements, followed by an optional schema that will match the remaining elements.,	at schema.core$parse_sequence_schema.invokeStatic(core.cljc:940),	at schema.core$parse_sequence_schema.invoke(core.cljc:932),	at schema.core$fn__5625.invokeStatic(core.cljc:958),	at schema.core$fn__5625.invoke(core.cljc:948),	at schema.core$fn__4702$G__4684__4707.invoke(core.cljc:96),	at schema.core$checker$fn__4726.invoke(core.cljc:128),	at schema.spec.core$sub_checker$fn__4514.invoke(core.cljc:95),	at schema.spec.core$with_cache.invokeStatic(core.cljc:83),	at schema.spec.core$with_cache.invoke(core.cljc:74),	at schema.spec.core$sub_checker.invokeStatic(core.cljc:93),	at schema.spec.core$sub_checker.invoke(core.cljc:88),	at schema.spec.variant$option_step.invokeStatic(variant.cljc:14),	at schema.spec.variant$option_step.invoke(variant.cljc:12),	at schema.spec.variant.VariantSpec$fn__4578.invoke(variant.cljc:47),	at clojure.lang.PersistentList.reduce(PersistentList.java:141),	at clojure.core$reduce.invokeStatic(core.clj:6886),	at clojure.core$reduce.invoke(core.clj:6869),	at schema.spec.variant.VariantSpec.checker(variant.cljc:45),	at schema.core$checker$fn__4726.invoke(core.cljc:128),	at schema.spec.core$sub_checker$fn__4514.invoke(core.cljc:95),	at schema.spec.core$with_cache.invokeStatic(core.cljc:83),	at schema.spec.core$with_cache.invoke(core.cljc:74),	at schema.spec.core$sub_checker.invokeStatic(core.cljc:93),	at schema.spec.core$sub_checker.invoke(core.cljc:88),	at schema.spec.variant$option_step.invokeStatic(variant.cljc:14),	at schema.spec.variant$option_step.invoke(variant.cljc:12),	at schema.spec.variant.VariantSpec$fn__4578.invoke(variant.cljc:47),	at clojure.lang.PersistentList.reduce(PersistentList.java:141),	at clojure.core$reduce.invokeStatic(core.clj:6886),	at clojure.core$reduce.invoke(core.clj:6869),	at schema.spec.variant.VariantSpec.checker(variant.cljc:45),	at schema.core$checker$fn__4726.invoke(core.cljc:128),	at schema.spec.core$sub_checker$fn__4514.invoke(core.cljc:95),	at schema.spec.core$with_cache.invokeStatic(core.cljc:83),	at schema.spec.core$with_cache.invoke(core.cljc:74),	at schema.spec.core$sub_checker.invokeStatic(core.cljc:93),	at schema.spec.core$sub_checker.invoke(core.cljc:88),	at schema.spec.collection$element_transformer.invokeStatic(collection.cljc:34),	at schema.spec.collection$element_transformer.invoke(collection.cljc:16),	at schema.spec.collection$sequence_transformer$fn__4631.invoke(collection.cljc:45),	at clojure.lang.PersistentList.reduce(PersistentList.java:144),	at clojure.core$reduce.invokeStatic(core.clj:6886),	at clojure.core$reduce.invoke(core.clj:6869),	at schema.spec.collection$sequence_transformer.invokeStatic(collection.cljc:43),	at schema.spec.collection$sequence_transformer.invoke(collection.cljc:40),	at schema.spec.collection.CollectionSpec.checker(collection.cljc:75),	at schema.core$checker$fn__4726.invoke(core.cljc:128),	at schema.spec.core$run_checker.invokeStatic(core.cljc:68),	at schema.spec.core$run_checker.invoke(core.cljc:64),	at schema.core$checker.invokeStatic(core.cljc:127),	at schema.core$checker.invoke(core.cljc:122),	at metabase.driver.clickhouse_qp$fn__91038$fn__91041.invoke(clickhouse_qp.clj:293),	at clojure.lang.Delay.deref(Delay.java:42),	at clojure.core$deref.invokeStatic(core.clj:2337),	at clojure.core$deref.invoke(core.clj:2323),	at metabase.driver.clickhouse_qp$fn__91038$update_string_value__91045.invoke(clickhouse_qp.clj:293),	at metabase.driver.clickhouse_qp$fn__91060.invokeStatic(clickhouse_qp.clj:301),	at metabase.driver.clickhouse_qp$fn__91060.invoke(clickhouse_qp.clj:297),	at clojure.lang.MultiFn.invoke(MultiFn.java:234),	at clojure.core$partial$fn__5908.invoke(core.clj:2641),	at clojure.core$map$fn__5931$fn__5932.invoke(core.clj:2759),	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63),	at clojure.core.protocols$fn__8244.invokeStatic(protocols.clj:136),	at clojure.core.protocols$fn__8244.invoke(protocols.clj:124),	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19),	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31),	at clojure.core.protocols$fn__8234.invokeStatic(protocols.clj:75),	at clojure.core.protocols$fn__8234.invoke(protocols.clj:75),	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13),	at clojure.core$transduce.invokeStatic(core.clj:6948),	at clojure.core$into.invokeStatic(core.clj:6963),	at clojure.core$into.invoke(core.clj:6951),	at metabase.driver.sql.query_processor$fn__66243.invokeStatic(query_processor.clj:1147),	at metabase.driver.sql.query_processor$fn__66243.invoke(query_processor.clj:1145),	at clojure.lang.MultiFn.invoke(MultiFn.java:234),	at metabase.driver.sql.query_processor$fn__66261.invokeStatic(query_processor.clj:1168),	at metabase.driver.sql.query_processor$fn__66261.invoke(query_processor.clj:1166),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.driver.sql.query_processor$apply_top_level_clauses$fn__66367.invoke(query_processor.clj:1407),	at clojure.lang.ArraySeq.reduce(ArraySeq.java:119),	at clojure.core$transduce.invokeStatic(core.clj:6947),	at clojure.core$transduce.invoke(core.clj:6934),	at metabase.driver.sql.query_processor$apply_top_level_clauses.invokeStatic(query_processor.clj:1401),	at metabase.driver.sql.query_processor$apply_top_level_clauses.invoke(query_processor.clj:1394),	at metabase.driver.sql.query_processor$apply_top_level_clauses.invokeStatic(query_processor.clj:1398),	at metabase.driver.sql.query_processor$apply_top_level_clauses.invoke(query_processor.clj:1394),	at metabase.driver.sql.query_processor$apply_clauses.invokeStatic(query_processor.clj:1464),	at metabase.driver.sql.query_processor$apply_clauses.invoke(query_processor.clj:1452),	at metabase.driver.sql.query_processor$mbql__GT_honeysql.invokeStatic(query_processor.clj:1484),	at metabase.driver.sql.query_processor$mbql__GT_honeysql.invoke(query_processor.clj:1478),	at metabase.driver.sql.query_processor$mbql__GT_native.invokeStatic(query_processor.clj:1493),	at metabase.driver.sql.query_processor$mbql__GT_native.invoke(query_processor.clj:1489),	at metabase.driver.sql$fn__83379.invokeStatic(sql.clj:49),	at metabase.driver.sql$fn__83379.invoke(sql.clj:47),	at clojure.lang.MultiFn.invoke(MultiFn.java:234),	at metabase.query_processor.middleware.mbql_to_native$query__GT_native_form.invokeStatic(mbql_to_native.clj:14),	at metabase.query_processor.middleware.mbql_to_native$query__GT_native_form.invoke(mbql_to_native.clj:9),	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71570.invoke(mbql_to_native.clj:21),	at metabase.query_processor$fn__73475$combined_post_process__73480$combined_post_process_STAR___73481.invoke(query_processor.clj:262),	at metabase.query_processor$fn__73475$combined_pre_process__73476$combined_pre_process_STAR___73477.invoke(query_processor.clj:259),	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__66753.invoke(fetch_source_query.clj:303),	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72218$fn__72222.invoke(resolve_database_and_driver.clj:77),	at metabase.driver$do_with_driver.invokeStatic(driver.clj:97),	at metabase.driver$do_with_driver.invoke(driver.clj:92),	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72218.invoke(resolve_database_and_driver.clj:76),	at metabase.query_processor.middleware.store$initialize_store$fn__67380$fn__67381.invoke(store.clj:14),	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169),	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150),	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158),	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150),	at metabase.query_processor.middleware.store$initialize_store$fn__67380.invoke(store.clj:13),	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database$fn__72215.invoke(resolve_database_and_driver.clj:60),	at metabase.query_processor.middleware.normalize_query$normalize$fn__72520.invoke(normalize_query.clj:38),	at metabase.query_processor.middleware.enterprise$fn__72155$handle_audit_app_internal_queries__72156$fn__72158.invoke(enterprise.clj:96),	at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__72166.invoke(enterprise.clj:103),	at metabase.query_processor.reducible$async_qp$qp_STAR___62893$thunk__62895.invoke(reducible.clj:126),	at metabase.query_processor.reducible$async_qp$qp_STAR___62893.invoke(reducible.clj:132),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.core$apply.invokeStatic(core.clj:667),	at clojure.core$apply.invoke(core.clj:662),	at metabase.query_processor.reducible$sync_qp$qp_STAR___62905.doInvoke(reducible.clj:153),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:311),	at metabase.query_processor$process_query.invoke(query_processor.clj:291),	at metabase.models.params.chain_filter$unremapped_chain_filter.invokeStatic(chain_filter.clj:444),	at metabase.models.params.chain_filter$unremapped_chain_filter.invoke(chain_filter.clj:435),	at metabase.models.params.chain_filter$unremapped_chain_filter_search.invokeStatic(chain_filter.clj:623),	at metabase.models.params.chain_filter$unremapped_chain_filter_search.invoke(chain_filter.clj:613),	at metabase.models.params.chain_filter$chain_filter_search.invokeStatic(chain_filter.clj:707),	at metabase.models.params.chain_filter$chain_filter_search.doInvoke(chain_filter.clj:680),	at clojure.lang.RestFn.invoke(RestFn.java:494),	at metabase.api.dashboard$chain_filter$fn__95181.invoke(dashboard.clj:1005),	at clojure.core$map$fn__5935.invoke(core.clj:2772),	at clojure.lang.LazySeq.sval(LazySeq.java:42),	at clojure.lang.LazySeq.seq(LazySeq.java:51),	at clojure.lang.RT.seq(RT.java:535),	at clojure.core$seq__5467.invokeStatic(core.clj:139),	at clojure.core$map$fn__5935.invoke(core.clj:2763),	at clojure.lang.LazySeq.sval(LazySeq.java:42),	at clojure.lang.LazySeq.seq(LazySeq.java:51),	at clojure.lang.RT.seq(RT.java:535),	at clojure.core$seq__5467.invokeStatic(core.clj:139),	at clojure.core$apply.invokeStatic(core.clj:662),	at clojure.core$mapcat.invokeStatic(core.clj:2800),	at clojure.core$mapcat.doInvoke(core.clj:2800),	at clojure.lang.RestFn.invoke(RestFn.java:423),	at metabase.api.dashboard$chain_filter.invokeStatic(dashboard.clj:1008),	at metabase.api.dashboard$chain_filter.invoke(dashboard.clj:983),	at metabase.api.dashboard$param_values$fn__95189.invoke(dashboard.clj:1045),	at metabase.models.params.custom_values$parameter__GT_values.invokeStatic(custom_values.clj:134),	at metabase.models.params.custom_values$parameter__GT_values.invoke(custom_values.clj:119),	at metabase.api.dashboard$param_values.invokeStatic(dashboard.clj:1042),	at metabase.api.dashboard$param_values.invoke(dashboard.clj:1022),	at metabase.api.dashboard$fn__95197$fn__95199.invoke(dashboard.clj:1075),	at metabase.api.dashboard$fn__95197.invokeStatic(dashboard.clj:1074),	at metabase.api.dashboard$fn__95197.invoke(dashboard.clj:1060),	at compojure.core$wrap_response$fn__44694.invoke(core.clj:160),	at compojure.core$wrap_route_middleware$fn__44678.invoke(core.clj:132),	at compojure.core$wrap_route_info$fn__44683.invoke(core.clj:139),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:151),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:152),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:153),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:153),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:153),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:152),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:152),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:152),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:153),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:153),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:152),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:153),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:153),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706.invoke(core.clj:200),	at metabase.server.middleware.auth$enforce_authentication$fn__94049.invoke(auth.clj:17),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706.invoke(core.clj:200),	at compojure.core$make_context$handler__44734.invoke(core.clj:290),	at compojure.core$make_context$fn__44738.invoke(core.clj:300),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$make_context$fn__44738.invoke(core.clj:301),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$make_context$fn__44738.invoke(core.clj:301),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$make_context$fn__44738.invoke(core.clj:301),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$make_context$fn__44738.invoke(core.clj:301),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$make_context$fn__44738.invoke(core.clj:301),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$make_context$fn__44738.invoke(core.clj:301),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$make_context$fn__44738.invoke(core.clj:301),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at metabase.api.routes$fn__102082$fn__102085.invoke(routes.clj:67),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706.invoke(core.clj:200),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.core$apply.invokeStatic(core.clj:667),	at clojure.core$apply.invoke(core.clj:662),	at metabase.server.routes$fn__102247$fn__102248.doInvoke(routes.clj:72),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706.invoke(core.clj:200),	at compojure.core$make_context$handler__44734.invoke(core.clj:290),	at compojure.core$make_context$fn__44738.invoke(core.clj:300),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:152),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:152),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44687.invoke(core.clj:152),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706$f__44707$respond_SINGLEQUOTE___44708.invoke(core.clj:197),	at metabase.server.routes$fn__102232$fn__102234.invoke(routes.clj:49),	at compojure.core$routes$fn__44706$f__44707.invoke(core.clj:198),	at compojure.core$routes$fn__44706.invoke(core.clj:200),	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__98793.invoke(exceptions.clj:108),	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__98790.invoke(exceptions.clj:96),	at metabase.server.middleware.log$log_api_call$fn__102524$fn__102525$fn__102526.invoke(log.clj:230),	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18),	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12),	at metabase.server.middleware.log$log_api_call$fn__102524$fn__102525.invoke(log.clj:222),	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112),	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103),	at metabase.server.middleware.log$log_api_call$fn__102524.invoke(log.clj:221),	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__104589.invoke(browser_cookie.clj:40),	at metabase.server.middleware.security$add_security_headers$fn__98749.invoke(security.clj:182),	at metabase.server.middleware.json$wrap_json_body$fn__46051.invoke(json.clj:67),	at metabase.server.middleware.offset_paging$handle_paging$fn__84947.invoke(offset_paging.clj:43),	at metabase.server.middleware.json$wrap_streamed_json_response$fn__46069.invoke(json.clj:103),	at ring.middleware.keyword_params$wrap_keyword_params$fn__104856.invoke(keyword_params.clj:55),	at ring.middleware.params$wrap_params$fn__104875.invoke(params.clj:77),	at metabase.server.middleware.misc$maybe_set_site_url$fn__67295.invoke(misc.clj:61),	at metabase.server.middleware.session$reset_session_timeout$fn__72726.invoke(session.clj:546),	at metabase.server.middleware.session$bind_current_user$fn__72692$fn__72693.invoke(session.clj:440),	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:419),	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:403),	at metabase.server.middleware.session$bind_current_user$fn__72692.invoke(session.clj:439),	at metabase.server.middleware.session$wrap_current_user_info$fn__72675.invoke(session.clj:378),	at metabase.server.middleware.session$wrap_session_id$fn__72647.invoke(session.clj:257),	at metabase.server.middleware.auth$wrap_static_api_key$fn__94057.invoke(auth.clj:30),	at ring.middleware.cookies$wrap_cookies$fn__104776.invoke(cookies.clj:194),	at metabase.server.middleware.misc$add_content_type$fn__67277.invoke(misc.clj:29),	at metabase.server.middleware.misc$disable_streaming_buffering$fn__67303.invoke(misc.clj:78),	at ring.middleware.gzip$wrap_gzip$fn__104818.invoke(gzip.clj:86),	at metabase.server.middleware.misc$bind_request$fn__67306.invoke(misc.clj:95),	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__104605.invoke(ssl.clj:41),	at metabase.server$async_proxy_handler$fn__67717.invoke(server.clj:78),	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source),	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173),	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122),	at org.eclipse.jetty.server.Server.handle(Server.java:563),	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598),	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753),	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501),	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287),	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314),	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100),	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199),	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411),	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969),	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194),	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149),	at java.base/java.lang.Thread.run(Unknown Source)
```

### Severity

very serious.

**Comment by bladexxx** [comment]
I resolved this issue after I upgraded the clickhouse driver !  not metabase issue.
