### ISSUE TITLE
Metabase not displaying table columns registered with Lakeformation in Athena

### ISSUE THREAD

**Issue by WeslleyCsts** [metabase/metabase#43852]
**Describe the bug**
Metabase correctly loads the database and shows the table names, however it doesn't show the table schema and I can't see the data in visualization, returning the error No fields found for table X. However, if I try to view the table via native query, all the fields and data are loaded correctly.

**Logs**

[068e27cb-5ab0-4347-9d8d-08937211cb25] 2024-06-07T14:32:07-03:00 ERROR metabase.models.query.permissions ,clojure.lang.ExceptionInfo: Error calculating permissions for query {:query {:database 67, :type :query, :query {:source-table 2562}}},	at metabase.models.query.permissions$mbql_permissions_path_set.invokeStatic(permissions.clj:160),	at metabase.models.query.permissions$mbql_permissions_path_set.invoke(permissions.clj:139),	at metabase.models.query.permissions$perms_set_STAR_.invokeStatic(permissions.clj:176),	at metabase.models.query.permissions$perms_set_STAR_.invoke(permissions.clj:169),	at metabase.models.query.permissions$perms_set.invokeStatic(permissions.clj:191),	at metabase.models.query.permissions$perms_set.doInvoke(permissions.clj:186),	at clojure.lang.RestFn.invoke(RestFn.java:410),	at metabase.models.query.permissions$can_run_query_QMARK_.invokeStatic(permissions.clj:198),	at metabase.models.query.permissions$can_run_query_QMARK_.invoke(permissions.clj:193),	at metabase.models.query.permissions$can_query_table_QMARK_.invokeStatic(permissions.clj:204),	at metabase.models.query.permissions$can_query_table_QMARK_.invoke(permissions.clj:201),	at metabase.events.view_log$publish_event_BANG__primary_method_metabase_events_view_log_table_read.invokeStatic(view_log.clj:112),	at metabase.events.view_log$publish_event_BANG__primary_method_metabase_events_view_log_table_read.invoke(view_log.clj:100),	at clojure.lang.AFn.applyToHelper(AFn.java:156),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:421),	at methodical.impl.combo.operator$invoke_fn$fn__18025.invoke(operator.clj:69),	at methodical.impl.combo.operator$fn__18046$fn__18047$fn__18048.invoke(operator.clj:112),	at clojure.core$comp$fn__5876.invoke(core.clj:2587),	at metabase.events$publish_event_BANG__around_method_default$fn__36615.invoke(events.clj:143),	at metabase.events$publish_event_BANG__around_method_default.invokeStatic(events.clj:137),	at metabase.events$publish_event_BANG__around_method_default.invoke(events.clj:109),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at clojure.core$partial$fn__5908.invoke(core.clj:2642),	at clojure.lang.AFn.applyToHelper(AFn.java:156),	at clojure.lang.RestFn.applyTo(RestFn.java:132),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:421),	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55),	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47),	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:193),	at metabase.api.dataset$run_query_async.invokeStatic(dataset.clj:66),	at metabase.api.dataset$run_query_async.doInvoke(dataset.clj:49),	at clojure.lang.RestFn.invoke(RestFn.java:410),	at metabase.api.dataset$fn__94356.invokeStatic(dataset.clj:85),	at metabase.api.dataset$fn__94356.invoke(dataset.clj:81),	at compojure.core$wrap_response$fn__45006.invoke(core.clj:160),	at compojure.core$wrap_route_middleware$fn__44990.invoke(core.clj:132),	at compojure.core$wrap_route_info$fn__44995.invoke(core.clj:139),	at compojure.core$wrap_route_matches$fn__44999.invoke(core.clj:151),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44999.invoke(core.clj:152),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018.invoke(core.clj:200),	at metabase.server.middleware.auth$enforce_authentication$fn__94429.invoke(auth.clj:17),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018.invoke(core.clj:200),	at compojure.core$make_context$handler__45046.invoke(core.clj:290),	at compojure.core$make_context$fn__45050.invoke(core.clj:300),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$make_context$fn__45050.invoke(core.clj:301),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$make_context$fn__45050.invoke(core.clj:301),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$make_context$fn__45050.invoke(core.clj:301),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$make_context$fn__45050.invoke(core.clj:301),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$make_context$fn__45050.invoke(core.clj:301),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$make_context$fn__45050.invoke(core.clj:301),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$make_context$fn__45050.invoke(core.clj:301),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$make_context$fn__45050.invoke(core.clj:301),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$make_context$fn__45050.invoke(core.clj:301),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at metabase.api.routes$fn__102495$fn__102498.invoke(routes.clj:67),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018.invoke(core.clj:200),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.core$apply.invokeStatic(core.clj:667),	at clojure.core$apply.invoke(core.clj:662),	at metabase.server.routes$fn__102660$fn__102661.doInvoke(routes.clj:72),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018.invoke(core.clj:200),	at compojure.core$make_context$handler__45046.invoke(core.clj:290),	at compojure.core$make_context$fn__45050.invoke(core.clj:300),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44999.invoke(core.clj:153),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44999.invoke(core.clj:153),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__44999.invoke(core.clj:153),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018$f__45019$respond_SINGLEQUOTE___45020.invoke(core.clj:197),	at metabase.server.routes$fn__102645$fn__102647.invoke(routes.clj:49),	at compojure.core$routes$fn__45018$f__45019.invoke(core.clj:198),	at compojure.core$routes$fn__45018.invoke(core.clj:200),	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__99173.invoke(exceptions.clj:108),	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__99170.invoke(exceptions.clj:96),	at metabase.server.middleware.log$log_api_call$fn__102937$fn__102938$fn__102939.invoke(log.clj:230),	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18),	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12),	at metabase.server.middleware.log$log_api_call$fn__102937$fn__102938.invoke(log.clj:222),	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112),	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103),	at metabase.server.middleware.log$log_api_call$fn__102937.invoke(log.clj:221),	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__105002.invoke(browser_cookie.clj:40),	at metabase.server.middleware.security$add_security_headers$fn__99129.invoke(security.clj:182),	at metabase.server.middleware.json$wrap_json_body$fn__46363.invoke(json.clj:67),	at metabase.server.middleware.offset_paging$handle_paging$fn__85327.invoke(offset_paging.clj:43),	at metabase.server.middleware.json$wrap_streamed_json_response$fn__46381.invoke(json.clj:103),	at ring.middleware.keyword_params$wrap_keyword_params$fn__105269.invoke(keyword_params.clj:55),	at ring.middleware.params$wrap_params$fn__105288.invoke(params.clj:77),	at metabase.server.middleware.misc$maybe_set_site_url$fn__67642.invoke(misc.clj:61),	at metabase.server.middleware.session$reset_session_timeout$fn__73075.invoke(session.clj:546),	at metabase.server.middleware.session$bind_current_user$fn__73041$fn__73042.invoke(session.clj:440),	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:419),	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:403),	at metabase.server.middleware.session$bind_current_user$fn__73041.invoke(session.clj:439),	at metabase.server.middleware.session$wrap_current_user_info$fn__73024.invoke(session.clj:378),	at metabase.server.middleware.session$wrap_session_id$fn__72996.invoke(session.clj:257),	at metabase.server.middleware.auth$wrap_static_api_key$fn__94437.invoke(auth.clj:30),	at ring.middleware.cookies$wrap_cookies$fn__105189.invoke(cookies.clj:194),	at metabase.server.middleware.misc$add_content_type$fn__67624.invoke(misc.clj:29),	at metabase.server.middleware.misc$disable_streaming_buffering$fn__67650.invoke(misc.clj:78),	at ring.middleware.gzip$wrap_gzip$fn__105231.invoke(gzip.clj:86),	at metabase.server.middleware.misc$bind_request$fn__67653.invoke(misc.clj:95),	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__105018.invoke(ssl.clj:41),	at metabase.server$async_proxy_handler$fn__68064.invoke(server.clj:78),	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source),	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173),	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122),	at org.eclipse.jetty.server.Server.handle(Server.java:563),	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598),	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753),	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501),	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287),	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314),	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100),	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199),	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411),	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969),	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194),	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149),	at java.base/java.lang.Thread.run(Unknown Source),Caused by: clojure.lang.ExceptionInfo: No fields found for table "changelog". {:table-id 2562, :type :invalid-query},	at metabase.query_processor.middleware.add_implicit_clauses$sorted_implicit_fields_for_table.invokeStatic(add_implicit_clauses.clj:35),	at metabase.query_processor.middleware.add_implicit_clauses$sorted_implicit_fields_for_table.invoke(add_implicit_clauses.clj:29),	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_fields.invokeStatic(add_implicit_clauses.clj:99),	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_fields.invoke(add_implicit_clauses.clj:92),	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_mbql_clauses$fn__64825.invoke(add_implicit_clauses.clj:143),	at clojure.walk$walk.invokeStatic(walk.clj:50),	at clojure.walk$postwalk.invokeStatic(walk.clj:53),	at clojure.walk$postwalk.invoke(walk.clj:53),	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_mbql_clauses.invokeStatic(add_implicit_clauses.clj:136),	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_mbql_clauses.invoke(add_implicit_clauses.clj:133),	at clojure.core$update.invokeStatic(core.clj:6232),	at clojure.core$update.invoke(core.clj:6224),	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses.invokeStatic(add_implicit_clauses.clj:153),	at metabase.query_processor.middleware.add_implicit_clauses$add_implicit_clauses.invoke(add_implicit_clauses.clj:147),	at clojure.lang.Var.invoke(Var.java:384),	at metabase.query_processor$preprocess_STAR_$fn__73816.invoke(query_processor.clj:164),	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343),	at clojure.core$reduce.invokeStatic(core.clj:6886),	at clojure.core$reduce.invoke(core.clj:6869),	at metabase.query_processor$preprocess_STAR_.invokeStatic(query_processor.clj:162),	at metabase.query_processor$preprocess_STAR_.invoke(query_processor.clj:157),	at metabase.query_processor$preprocess$fn__73844.invoke(query_processor.clj:321),	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__67100.invoke(fetch_source_query.clj:303),	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72567$fn__72571.invoke(resolve_database_and_driver.clj:77),	at metabase.driver$do_with_driver.invokeStatic(driver.clj:97),	at metabase.driver$do_with_driver.invoke(driver.clj:92),	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72567.invoke(resolve_database_and_driver.clj:76),	at metabase.query_processor.middleware.store$initialize_store$fn__67727$fn__67728.invoke(store.clj:14),	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169),	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150),	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158),	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150),	at metabase.query_processor.middleware.store$initialize_store$fn__67727.invoke(store.clj:13),	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database$fn__72564.invoke(resolve_database_and_driver.clj:60),	at metabase.query_processor.middleware.normalize_query$normalize$fn__72869.invoke(normalize_query.clj:38),	at metabase.query_processor.middleware.enterprise$fn__72504$handle_audit_app_internal_queries__72505$fn__72507.invoke(enterprise.clj:96),	at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__72515.invoke(enterprise.clj:103),	at metabase.query_processor.middleware.prevent_infinite_recursive_preprocesses$prevent_infinite_recursive_preprocesses$fn__71571.invoke(prevent_infinite_recursive_preprocesses.clj:23),	at metabase.query_processor$preprocess.invokeStatic(query_processor.clj:322),	at metabase.query_processor$preprocess.invoke(query_processor.clj:313),	at clojure.lang.Var.invoke(Var.java:384),	at metabase.models.query.permissions$preprocess_query.invokeStatic(permissions.clj:137),	at metabase.models.query.permissions$preprocess_query.invoke(permissions.clj:132),	at metabase.models.query.permissions$mbql_permissions_path_set.invokeStatic(permissions.clj:154),	... 163 more
[068e27cb-5ab0-4347-9d8d-08937211cb25] 2024-06-07T14:32:07-03:00 ERROR metabase.query-processor.middleware.catch-exceptions Error processing query: No fields found for table "changelog".
{:database_id 67,
 :started_at #t "2024-06-07T17:32:07.818758Z[GMT]",
 :action_id nil,
 :error_type :invalid-query,
 :json_query
 {:database 67,
  :query {:source-table 2562},
  :type "query",
  :parameters [],
  :middleware {:js-int-to-string? true, :add-default-userland-constraints? true}},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> query_processor.middleware.add_implicit_clauses$sorted_implicit_fields_for_table.invokeStatic(add_implicit_clauses.clj:35)"
  "query_processor.middleware.add_implicit_clauses$sorted_implicit_fields_for_table.invoke(add_implicit_clauses.clj:29)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_fields.invokeStatic(add_implicit_clauses.clj:99)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_fields.invoke(add_implicit_clauses.clj:92)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_mbql_clauses$fn__64825.invoke(add_implicit_clauses.clj:143)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_mbql_clauses.invokeStatic(add_implicit_clauses.clj:136)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_mbql_clauses.invoke(add_implicit_clauses.clj:133)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses.invokeStatic(add_implicit_clauses.clj:153)"
  "query_processor.middleware.add_implicit_clauses$add_implicit_clauses.invoke(add_implicit_clauses.clj:147)"
  "query_processor$preprocess_STAR_$fn__73816.invoke(query_processor.clj:164)"
  "query_processor$preprocess_STAR_.invokeStatic(query_processor.clj:162)"
  "query_processor$preprocess_STAR_.invoke(query_processor.clj:157)"
  "query_processor$fn__73824$combined_pre_process__73825$combined_pre_process_STAR___73826.invoke(query_processor.clj:259)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__67100.invoke(fetch_source_query.clj:303)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72567$fn__72571.invoke(resolve_database_and_driver.clj:77)"
  "driver$do_with_driver.invokeStatic(driver.clj:97)"
  "driver$do_with_driver.invoke(driver.clj:92)"
  "query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72567.invoke(resolve_database_and_driver.clj:76)"
  "query_processor.middleware.store$initialize_store$fn__67727$fn__67728.invoke(store.clj:14)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)"
  "query_processor.store$do_with_metadata_provider.invoke(store.clj:150)"
  "query_processor.middleware.store$initialize_store$fn__67727.invoke(store.clj:13)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database$fn__72564.invoke(resolve_database_and_driver.clj:60)"
  "query_processor.middleware.normalize_query$normalize$fn__72869.invoke(normalize_query.clj:38)"
  "query_processor.middleware.enterprise$fn__72504$handle_audit_app_internal_queries__72505$fn__72507.invoke(enterprise.clj:96)"
  "query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__72515.invoke(enterprise.clj:103)"
  "query_processor.middleware.constraints$mark_needs_default_userland_constraints$fn__71630.invoke(constraints.clj:104)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__72800.invoke(process_userland_query.clj:156)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__73401.invoke(catch_exceptions.clj:171)"
  "query_processor.reducible$async_qp$qp_STAR___63219$thunk__63221.invoke(reducible.clj:126)"
  "query_processor.reducible$async_qp$qp_STAR___63219.invoke(reducible.clj:132)"
  "query_processor.reducible$sync_qp$qp_STAR___63231.doInvoke(reducible.clj:153)"
  "query_processor$process_userland_query.invokeStatic(query_processor.clj:402)"
  "query_processor$process_userland_query.doInvoke(query_processor.clj:398)"
  "query_processor$process_query_and_save_execution_BANG_.invokeStatic(query_processor.clj:416)"
  "query_processor$process_query_and_save_execution_BANG_.invoke(query_processor.clj:406)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invokeStatic(query_processor.clj:431)"
  "query_processor$process_query_and_save_with_max_results_constraints_BANG_.invoke(query_processor.clj:421)"
  "api.dataset$run_query_async$fn__94343.invoke(dataset.clj:79)"
  "query_processor.streaming$streaming_response_STAR_$fn__53631$fn__53633.invoke(streaming.clj:168)"
  "query_processor.streaming$streaming_response_STAR_$fn__53631.invoke(streaming.clj:167)"
  "async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:69)"
  "async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:67)"
  "async.streaming_response$do_f_async$task__44086.invoke(streaming_response.clj:88)"],
 :card_id nil,
 :context :ad-hoc,
 :error "No fields found for table \"changelog\".",
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :ex-data {:table-id 2562, :type :invalid-query},
 :data {:rows [], :cols []}}

**To Reproduce**
1. Create and populate database in Glue Data Catalog
2. Give permissions to it via LakeFormation to the user consuming it via Athena
3. Synch data with Metabase

**Expected behavior**
All table schema and data showing correctly as the native query.

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Metabase entirely?
Blocking usage of Metabase, as the tables don't show correctly.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "5.15.153",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mongo",
      "athena"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.2"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-06-05",
      "tag": "v0.49.14",
      "hash": "3606ed3"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Comment by WeslleyCsts** [comment]
Just a quick update for more context:

I've tried recreating the same table with another name on glue, using the same s3 path for the data and the same permission on Lake Formation, by doing this the created table shows all columns as it should be, I'm guessing this has something to do with Metabase or how it queries LakeFormation and somehow throttles it during too many requests

**Comment by ixipixi** [comment]
@WeslleyCsts do you think this may be what you're seeing? 

https://github.com/metabase/metabase/issues/43980

**Comment by calherries** [comment]
@WeslleyCsts

> I've tried recreating the same table with another name on glue

For the table you created where everything worked, did its name contain any underscores?

**Comment by paoliniluis** [comment]
@ixipixi pinging you as you've been around here recently

**Comment by WeslleyCsts** [comment]
Hi @calherries, guess this is the same issue as @ixipixi, all my tables with underscore are loaded correctly

**Comment by darksciencebase** [comment]
closing as duplicate then, the fix for https://github.com/metabase/metabase/issues/43980 will be shipped in the coming days
