### ISSUE TITLE
Support CLOB types (again), or at least don't provide errors on the update-field-values step

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#44109]
### Describe the bug

For some reason it seems that CLOBs are a problem in Oracle: logs say that we're having problems with those.

### To Reproduce

1) run
```
create table table2 (

    number_col NUMBER,

    clob_col   CLOB

);

insert into table2 values ( 1, TO_CLOB('...looong text in clob 1....'));

insert into table2 values ( 2, TO_CLOB('...looong text in clob 2....'));

insert into table2 values ( 3, TO_CLOB('...looong text in clob 3....'));

insert into table2 values (11, TO_CLOB('...looong text in clob 11....'));

insert into table2 values (12, TO_CLOB('...looong text in clob 12....'));

insert into table2 values (13, TO_CLOB('...looong text in clob 13....'));

insert into table2 values (14, TO_CLOB('...looong text in clob 14....'));



commit;
```
2) add the db and sync
3) see the error

### Expected behavior

We shouldn't generate any errors with CLOB types, we supposedly support those since v32 (https://github.com/metabase/metabase/issues/9026 and https://github.com/metabase/metabase/pull/9309)

### Logs

```
2024-06-13 00:07:28,094 INFO sync.util :: STARTING: step ''update-field-values'' for oracle Database 3 ''oracle-18''
2024-06-13 00:07:28,125 ERROR models.field-values :: Error fetching field values
clojure.lang.ExceptionInfo: Error executing query: ORA-00932: inconsistent datatypes: expected - got CLOB
 {:driver :oracle, :sql ["-- Metabase" "SELECT" "  *" "FROM" "  (" "    SELECT" "      \"METABASE\".\"TABLE2\".\"CLOB_COL\" \"CLOB_COL\"" "    FROM" "      \"METABASE\".\"TABLE2\"" "    GROUP BY" "      \"METABASE\".\"TABLE2\".\"CLOB_COL\"" "    ORDER BY" "      \"METABASE\".\"TABLE2\".\"CLOB_COL\" ASC" "  )" "WHERE" "  rownum <= 1000"], :params nil, :type :invalid-query}
	at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__81066$fn__81067.invoke(execute.clj:716)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__81066.invoke(execute.clj:713)
	at metabase.driver.sql_jdbc.execute$fn__80859$fn__80860.invoke(execute.clj:397)
	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:337)
	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:320)
	at metabase.driver.sql_jdbc.execute$fn__80859.invokeStatic(execute.clj:391)
	at metabase.driver.sql_jdbc.execute$fn__80859.invoke(execute.clj:389)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:707)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:704)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693)
	at metabase.driver.sql_jdbc$fn__114623.invokeStatic(sql_jdbc.clj:78)
	at metabase.driver.sql_jdbc$fn__114623.invoke(sql_jdbc.clj:76)
	at metabase.driver.oracle$fn__124272.invokeStatic(oracle.clj:506)
	at metabase.driver.oracle$fn__124272.invoke(oracle.clj:504)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)
	at metabase.query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)
	at metabase.query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:88)
	at metabase.query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:81)
	at metabase.query_processor.execute$run.invokeStatic(execute.clj:60)
	at metabase.query_processor.execute$run.invoke(execute.clj:54)
	at metabase.query_processor.middleware.update_used_cards$update_used_cards_BANG_$fn__69565.invoke(update_used_cards.clj:40)
	at metabase.query_processor.execute$add_native_form_to_result_metadata$fn__69574.invoke(execute.clj:23)
	at metabase.query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__69579.invoke(execute.clj:34)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___69551.invoke(cache.clj:242)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__63710.invoke(permissions.clj:118)
	at metabase.query_processor.middleware.enterprise$check_download_permissions_middleware$fn__64286.invoke(enterprise.clj:51)
	at metabase.query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__64296.invoke(enterprise.clj:64)
	at metabase.query_processor.execute$execute$fn__69606.invoke(execute.clj:92)
	at metabase.query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:225)
	at metabase.query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)
	at metabase.query_processor.execute$execute.invokeStatic(execute.clj:91)
	at metabase.query_processor.execute$execute.invoke(execute.clj:87)
	at metabase.query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47)
	at metabase.query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:43)
	at metabase.query_processor.middleware.enterprise$fn__64313$handle_audit_app_internal_queries__64314$fn__64316.invoke(enterprise.clj:96)
	at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__64324.invoke(enterprise.clj:103)
	at metabase.query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__75424.invoke(process_userland_query.clj:169)
	at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__75493.invoke(catch_exceptions.clj:121)
	at metabase.query_processor$process_query$fn__75530.invoke(query_processor.clj:78)
	at metabase.query_processor.setup$do_with_canceled_chan$fn__64728.invoke(setup.clj:189)
	at metabase.query_processor.setup$do_with_database_local_settings$fn__64723.invoke(setup.clj:181)
	at metabase.query_processor.setup$do_with_driver$fn__64718$fn__64719.invoke(setup.clj:166)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:104)
	at metabase.driver$do_with_driver.invoke(driver.clj:99)
	at metabase.query_processor.setup$do_with_driver$fn__64718.invoke(setup.clj:165)
	at metabase.query_processor.setup$do_with_metadata_provider$fn__64711$fn__64714.invoke(setup.clj:151)
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:171)
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:151)
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:160)
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:151)
	at metabase.query_processor.setup$do_with_metadata_provider$fn__64711.invoke(setup.clj:150)
	at metabase.query_processor.setup$do_with_resolved_database$fn__64705.invoke(setup.clj:128)
	at metabase.query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232)
	at metabase.query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:76)
	at metabase.query_processor$process_query.invoke(query_processor.clj:69)
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:72)
	at metabase.query_processor$process_query.invoke(query_processor.clj:69)
	at metabase.db.metadata_queries$qp_query$fn__75540.invoke(metadata_queries.clj:22)
	at metabase.db.metadata_queries$qp_query.invokeStatic(metadata_queries.clj:21)
	at metabase.db.metadata_queries$qp_query.invoke(metadata_queries.clj:18)
	at metabase.db.metadata_queries$field_query.invokeStatic(metadata_queries.clj:79)
	at metabase.db.metadata_queries$field_query.invoke(metadata_queries.clj:75)
	at metabase.db.metadata_queries$field_distinct_values.invokeStatic(metadata_queries.clj:109)
	at metabase.db.metadata_queries$field_distinct_values.invoke(metadata_queries.clj:102)
	at metabase.db.metadata_queries$field_distinct_values.invokeStatic(metadata_queries.clj:106)
	at metabase.db.metadata_queries$field_distinct_values.invoke(metadata_queries.clj:102)
	at metabase.models.field_values$distinct_values.invokeStatic(field_values.clj:349)
	at metabase.models.field_values$distinct_values.invoke(field_values.clj:335)
	at metabase.models.field_values$create_or_update_full_field_values_BANG_.invokeStatic(field_values.clj:401)
	at metabase.models.field_values$create_or_update_full_field_values_BANG_.doInvoke(field_values.clj:392)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.sync.field_values$update_field_values_for_field_BANG_.invokeStatic(field_values.clj:32)
	at metabase.sync.field_values$update_field_values_for_field_BANG_.invoke(field_values.clj:25)
	at metabase.sync.field_values$update_field_values_for_table_BANG_$fn__84778$fn__84779.invoke(field_values.clj:57)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:188)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:181)
	at metabase.sync.field_values$update_field_values_for_table_BANG_$fn__84778.invoke(field_values.clj:55)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6869)
	at metabase.sync.field_values$update_field_values_for_table_BANG_.invokeStatic(field_values.clj:54)
	at metabase.sync.field_values$update_field_values_for_table_BANG_.invoke(field_values.clj:51)
	at clojure.core$map$fn__5935.invoke(core.clj:2770)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1790)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.field_values$update_field_values_for_database_BANG_.invokeStatic(field_values.clj:66)
	at metabase.sync.field_values$update_field_values_for_database_BANG_.invoke(field_values.clj:63)
	at metabase.sync.field_values$make_sync_field_values_steps$fn__84801.invoke(field_values.clj:115)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$run_step_with_metadata$fn__57395$fn__57398.invoke(util.clj:470)
	at metabase.models.task_history$do_with_task_history.invokeStatic(task_history.clj:116)
	at metabase.models.task_history$do_with_task_history.invoke(task_history.clj:105)
	at metabase.sync.util$run_step_with_metadata$fn__57395.doInvoke(util.clj:464)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:129)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:123)
	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:147)
	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:143)
	at metabase.sync.util$run_step_with_metadata.invokeStatic(util.clj:459)
	at metabase.sync.util$run_step_with_metadata.invoke(util.clj:454)
	at metabase.sync.util$run_sync_operation$fn__57437$fn__57445.invoke(util.clj:543)
	at metabase.sync.util$run_sync_operation$fn__57437.invoke(util.clj:541)
	at metabase.models.task_history$do_with_task_history.invokeStatic(task_history.clj:116)
	at metabase.models.task_history$do_with_task_history.invoke(task_history.clj:105)
	at metabase.sync.util$run_sync_operation.invokeStatic(util.clj:538)
	at metabase.sync.util$run_sync_operation.invoke(util.clj:533)
	at metabase.sync.field_values$update_field_values_BANG_$fn__84804.invoke(field_values.clj:125)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:188)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:181)
	at clojure.core$partial$fn__5910.invoke(core.clj:2647)
	at metabase.driver$fn__55248.invokeStatic(driver.clj:801)
	at metabase.driver$fn__55248.invoke(driver.clj:801)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__57307.invoke(util.clj:164)
	at metabase.sync.util$with_db_logging_disabled$fn__57304.invoke(util.clj:156)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:129)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:123)
	at metabase.sync.util$with_start_and_finish_logging$fn__57291.invoke(util.clj:141)
	at metabase.sync.util$with_sync_events$fn__57286.invoke(util.clj:115)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__57273.invoke(util.clj:87)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:213)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:207)
	at metabase.sync.field_values$update_field_values_BANG_.invokeStatic(field_values.clj:122)
	at metabase.sync.field_values$update_field_values_BANG_.invoke(field_values.clj:118)
	at metabase.sync$sync_database_BANG_$fn__85091.invoke(sync.clj:55)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:188)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:181)
	at clojure.core$partial$fn__5910.invoke(core.clj:2647)
	at metabase.driver$fn__55248.invokeStatic(driver.clj:801)
	at metabase.driver$fn__55248.invoke(driver.clj:801)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__57307.invoke(util.clj:164)
	at metabase.sync.util$with_db_logging_disabled$fn__57304.invoke(util.clj:156)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:129)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:123)
	at metabase.sync.util$with_start_and_finish_logging$fn__57291.invoke(util.clj:141)
	at metabase.sync.util$with_sync_events$fn__57286.invoke(util.clj:115)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__57273.invoke(util.clj:87)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:213)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:207)
	at metabase.sync$sync_database_BANG_.invokeStatic(sync.clj:51)
	at metabase.sync$sync_database_BANG_.invoke(sync.clj:37)
	at metabase.sync$sync_database_BANG_.invokeStatic(sync.clj:46)
	at metabase.sync$sync_database_BANG_.invoke(sync.clj:37)
	at metabase.events.sync_database$publish_event_BANG__primary_method_metabase_events_sync_database_event$fn__112428.invoke(sync_database.clj:23)
	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00932: inconsistent datatypes: expected - got CLOB

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:765)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
	at metabase.driver.sql_jdbc.execute$fn__80985.invokeStatic(execute.clj:569)
	at metabase.driver.sql_jdbc.execute$fn__80985.invoke(execute.clj:567)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:577)
	at metabase.driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:574)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__81066$fn__81067.invoke(execute.clj:714)
	... 162 more
Caused by: Error : 932, Position : 110, Sql = -- Metabase
SELECT * FROM (SELECT "METABASE"."TABLE2"."CLOB_COL" "CLOB_COL" FROM "METABASE"."TABLE2" GROUP BY "METABASE"."TABLE2"."CLOB_COL" ORDER BY "METABASE"."TABLE2"."CLOB_COL" ASC) WHERE rownum <= 1000, OriginalSql = -- Metabase
SELECT * FROM (SELECT "METABASE"."TABLE2"."CLOB_COL" "CLOB_COL" FROM "METABASE"."TABLE2" GROUP BY "METABASE"."TABLE2"."CLOB_COL" ORDER BY "METABASE"."TABLE2"."CLOB_COL" ASC) WHERE rownum <= 1000, Error Msg = ORA-00932: inconsistent datatypes: expected - got CLOB

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 182 more

```

### Information about your Metabase installation

```JSON
using metabase v1.50.2 and oracle 18 from gvenzl/oracle-xe:18-slim
```

### Severity

P2

### Additional context

You can still do operations on the fields, which seems that we're coercing to a text type?

**Comment by calherries** [comment]
@cbalusek I'm removing the regression label because I can't see any evidence storing field values for CLOB types ever worked. Let me know if you have evidence otherwise and I'll add it back

**Comment by calherries** [comment]
Also de-escalating this to a P3 because I don't think we want to support getting field values for CLOB types anyway. Similar to https://github.com/metabase/metabase/pull/43563, we want to skip fingerprinting and getting field values for any column that may contain values in the gigabytes
