### ISSUE TITLE
Bar graph failing

### ISSUE THREAD

**Issue by diegorolf** [metabase/metabase#44121]
### Describe the bug

When clicking on the bar chart option it fails, opening the console shows an error not communicated to the front-end. Other expected options do work. I checked the server logs but do not see an error on that end.

### Data
| Seller| Count|
|--------|--------|
| Name 1 | 1 |
| Name 2 | 2 |
| Name 3 | 3 | 

### To Reproduce

1. Go to SQL query
2. Click on Visualization
3. Choose bar graph
4. Nothing happens

### Error
```
Uncaught TypeError: Cannot assign to read only property 'stackable.stack_display' of object '#<Object>'
    at lK.onDisplayUpdate (BarChart.jsx:50:42)
    at ChartTypeSidebar.tsx:105:49
    at onClick (ChartTypeSidebar.tsx:135:31)
    at Object.A (react-dom.production.min.js:14:84)
    at v (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at w (react-dom.production.min.js:14:393)
    at to (react-dom.production.min.js:52:170)
    at tn (react-dom.production.min.js:51:255)
    at ti (react-dom.production.min.js:52:334)
```

### Information about your Metabase installation

```JSON
### Diagnostic info

{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 OPR/109.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Linux",
    "os.version": "6.8.0-31-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "bigquery-cloud-sdk",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.1 (Debian 16.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.2"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2024-05-28",
      "tag": "v0.49.13",
      "hash": "de28e83"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
```


### Severity

Blocking display of one query

### Additional context

_No response_

**Comment by diegorolf** [comment]
Issue is solved, but I think this error should be handled so I will leave it open. The problem was I did not give the header an alias. And when I changed ```count(credit_id)```  to ```count(credit_id) as total``` it worked again.

**Comment by diegorolf** [comment]
Hm, it seems that my solution was a nice idea, but not the real issue. As I had already used total in another query, which also failed. But when I changed it to a random string it worked. So the issue is fixed by changing the alias...
