### ISSUE TITLE
Docker image and cloud foundry errors

### ISSUE THREAD

**Issue by byumark** [metabase/metabase#4416]
When trying to run the docker image using cloud foundry I get this error:

```
2017-02-17T15:52:41.81-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:41 INFO metabase.util :: Loading Metabase...
2017-02-17T15:52:47.14-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 INFO metabase.core :: Starting Metabase in STANDALONE mode
2017-02-17T15:52:47.16-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
2017-02-17T15:52:47.16-0700 [APP/PROC/WEB/0]OUT  {:port 3000, :host "9da1bd7d-5fa7-4087-71fb-0aee1bd89858"}
2017-02-17T15:52:47.20-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 INFO metabase.core :: Starting Metabase version v0.22.2 (e318fee release-0.22.2) ...
2017-02-17T15:52:47.20-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 INFO metabase.core :: System timezone is 'GMT' ...
2017-02-17T15:52:47.36-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 DEBUG metabase.driver :: Registered driver :bigquery 🚚
2017-02-17T15:52:47.38-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 DEBUG metabase.driver :: Registered driver :crate 🚚
2017-02-17T15:52:47.45-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 DEBUG metabase.driver :: Registered driver :druid 🚚
2017-02-17T15:52:47.49-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 DEBUG metabase.driver :: Registered driver :googleanalytics 🚚
2017-02-17T15:52:47.50-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 DEBUG metabase.driver :: Registered driver :h2 🚚
2017-02-17T15:52:47.75-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 DEBUG metabase.driver :: Registered driver :mongo 🚚
2017-02-17T15:52:47.76-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 DEBUG metabase.driver :: Registered driver :mysql 🚚
2017-02-17T15:52:47.79-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 DEBUG metabase.driver :: Registered driver :postgres 🚚
2017-02-17T15:52:47.80-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 DEBUG metabase.driver :: Registered driver :redshift 🚚
2017-02-17T15:52:47.81-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 DEBUG metabase.driver :: Registered driver :sqlite 🚚
2017-02-17T15:52:47.82-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 DEBUG metabase.driver :: Registered driver :sqlserver 🚚
2017-02-17T15:52:47.84-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:47 INFO metabase.db :: Verifying h2 Database Connection ...
2017-02-17T15:52:48.84-0700 [CELL/0]     OUT Container became healthy
2017-02-17T15:52:55.86-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:53 ERROR metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:55 ERROR metabase.core :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase h2 DB.
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]OUT (binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR (binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.db$verify_db_connection.invokeStatic(db.clj:341)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.db$verify_db_connection.invoke(db.clj:334)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.db$verify_db_connection.invokeStatic(db.clj:337)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.db$verify_db_connection.invoke(db.clj:334)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:390)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.db$setup_db_BANG_.doInvoke(db.clj:383)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at clojure.lang.RestFn.invoke(RestFn.java:421)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.core$init_BANG_.invokeStatic(core.clj:113)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.core$init_BANG_.invoke(core.clj:93)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.core$start_normally.invokeStatic(core.clj:196)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.core$start_normally.invoke(core.clj:190)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.core$_main.invokeStatic(core.clj:288)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.core$_main.doInvoke(core.clj:283)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at clojure.lang.RestFn.invoke(RestFn.java:397)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]ERR 	at metabase.core.main(Unknown Source)
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:55 INFO metabase.core :: Metabase Shutting Down ...
2017-02-17T15:52:55.87-0700 [APP/PROC/WEB/0]OUT 02-17 22:52:55 INFO metabase.core :: Metabase Shutdown COMPLETE
2017-02-17T15:52:56.20-0700 [APP/PROC/WEB/0]OUT Exit status 1
```

**Comment by camsaul** [comment]
Hey @byumark, what sort of Metabase application DB are you using? You should probably use something other than the default H2 DB

**Comment by byumark** [comment]
I was just doing some testing. You're right, I should use another db. Is oracle or sql server an option for application data? We use those dbs in our cloud foundry.

**Comment by camsaul** [comment]
@byumark only Postgres or MySQL. See [our documentation](http://www.metabase.com/docs/latest/operations-guide/start.html#configuring-the-metabase-application-database) for more details

**Comment by salsakran** [comment]
Closing this as it doesn't relate to an actionable bug.
@byumark we expect either a writable (and implicitly persistent) filesystem to create our embedded H2 DB or to be passed DB credentials via env variables as per @camsaul's link to our documentation. 

I'd strongly suggest the latter if you're using cloudfoundry. If you have a choice, postgresql is our internally preferred option.
