### ISSUE TITLE
Unable to run metabase built from source

### ISSUE THREAD

**Issue by melOncholic** [metabase/metabase#4441]
I'm getting the following error while running metabase.jar built from latest master code
v0.23.0-snapshot 0aa2df9 master 2017-02-22'

```02-24 04:21:25 INFO metabase.util :: Loading Metabase...
02-24 04:21:25 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. ?
02-24 04:21:29 INFO metabase.core :: Starting Metabase in STANDALONE mode
02-24 04:21:29 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

02-24 04:21:29 INFO metabase.core :: Starting Metabase version v0.23.0-snapshot (0aa2df9 master) ...
02-24 04:21:29 INFO metabase.core :: System timezone is 'America/New_York' ...
02-24 04:21:29 DEBUG metabase.driver :: Registered driver :mysql ?
02-24 04:21:29 DEBUG metabase.driver :: Registered driver :sqlite ?
02-24 04:21:30 DEBUG metabase.driver :: Registered driver :mongo ?
02-24 04:21:30 DEBUG metabase.driver :: Registered driver :druid ?
java.lang.NoClassDefFoundError: metabase/driver/bigquery$?s__GT_str
	at metabase.driver.bigquery__init.load(Unknown Source)
	at metabase.driver.bigquery__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at metabase.driver$find_and_load_drivers_BANG_.invokeStatic(driver.clj:284)
	at metabase.driver$find_and_load_drivers_BANG_.invoke(driver.clj:278)
	at metabase.core$init_BANG_.invokeStatic(core.clj:111)
	at metabase.core$init_BANG_.invoke(core.clj:95)
	at metabase.core$start_normally.invokeStatic(core.clj:198)
	at metabase.core$start_normally.invoke(core.clj:192)
	at metabase.core$_main.invokeStatic(core.clj:290)
	at metabase.core$_main.doInvoke(core.clj:285)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: metabase.driver.bigquery$?s__GT_str
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
02-24 04:21:30 ERROR metabase.core :: Metabase Initialization FAILED:  metabase/driver/bigquery$?s__GT_str
02-24 04:21:30 INFO metabase.core :: Metabase Shutting Down ...
02-24 04:21:30 INFO metabase.core :: Metabase Shutdown COMPLETE
```

I'm able to run 0.22 release but I wanted to tinker with standardSql in Big query

**Linux Distribution**
```
NAME="Amazon Linux AMI"
VERSION="2015.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2015.03"
PRETTY_NAME="Amazon Linux AMI 2015.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2015.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2015.03
```

**Java (Oracle)**
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Yarn**
```
0.20.3
```

**Lein**
```
Leiningen 2.7.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by mnzt** [comment]
Same issue here.
```
OS: Arch Linux x86_64
Kernel Release: 4.11.7-1-ARCH

java version "1.7.0_131"
OpenJDK Runtime Environment (IcedTea 2.6.9) (Arch Linux build 7.u131_2.6.9-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.131-b00, mixed mode)

yarn version v0.27.3
```.

This is also from building and spawning a container.

**Comment by senior** [comment]
@mnzt @melOncholic Can you paste the command you're using to launch Metabase from source? Also what is your locale? This should be in the LANG and LC_* environment variables I think. It looks to be failing to compile a function that has a unicode character in the function's name, which makes me think this is a character set issue.

**Comment by mnzt** [comment]
@senior I just created a $5 DigitalOcean server and ran [my image built using metabase scripts](https://hub.docker.com/r/mnzt/metabase-head/tags/), and I still receive the same error. https://github.com/mnzt/metabase/commit/f4d3dc9ecd9f98a9a749d4291a3df19ba2180b21 This is the diff that I've built from source.

Will be happy to provide any more info, try pulling and running my container and see if you get the issue, too.

**Comment by senior** [comment]
@mnzt I took a look at he container you posted. I think what is happening is when you build the Metabase uberjar, it generates classfiles for each function. There's are two functions in the [bigquery](https://github.com/metabase/metabase/blob/master/src/metabase/driver/bigquery.clj#L215) driver file that contain non-ascii characters. For some reason this isn't getting represented correctly in the filename in your metabase.jar. In your docker container it shows ? for the µ rather than the unicode character. I'm not sure why it would be doing that for you and not for me. My guess would be that the system that is creating the metabase JAR has a file encoding that either doesn't support those characters or that they somehow aren't translated right when going into or coming out of the JAR.

Could you try building a JAR using whatever system/setup you were using before, but branch from https://github.com/metabase/metabase/pull/5441? I think that should fix your issue.

**Comment by mnzt** [comment]
@senior Will get back to you first thing Monday morning with results

**Comment by mnzt** [comment]
@senior Built using the docker build script from your branch everything works flawlessly. :tada:

**Comment by senior** [comment]
@mnzt Thanks for testing that out! I'll get it merged.
