### ISSUE TITLE
Migrate down between 50 and 49 fails in MySQL (when you have sandboxing configured?)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#44455]
### Describe the bug

just try to do a migrate down after you configured sandboxing

### To Reproduce

1) start Metabase on 49 and mysql as the app db (I think this is key, I haven't tried with H2)
2) configure sandboxing
3) then migrate down
4) see the error

### Expected behavior

It should migrate down

### Logs

```
2024-06-19 23:59:41,717 INFO db.liquibase :: Rolling back app database schema to version 49
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.RollbackFailedException: liquibase.exception.DatabaseException: (conn=20) Cannot add or update a child row: a foreign key constraint fails (`metabase`.`#sql-1_14`, CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE) [Failed SQL: (1452) ALTER TABLE `metabase`.`sandboxes` ADD CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `metabase`.`permissions` (`id`) ON DELETE CASCADE]
	at liquibase.command.CommandScope.execute(CommandScope.java:253)
	at liquibase.Liquibase.lambda$rollback$7(Liquibase.java:579)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
	at liquibase.Liquibase.rollback(Liquibase.java:568)
	at liquibase.Liquibase.rollback(Liquibase.java:551)
	at liquibase.Liquibase.rollback(Liquibase.java:542)
	at metabase.db.liquibase$rollback_major_version$fn__44512.invoke(liquibase.clj:485)
	at metabase.db.liquibase$run_in_scope_locked$reify__44426.run(liquibase.clj:324)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:317)
	at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:300)
	at metabase.db.liquibase$rollback_major_version.invokeStatic(liquibase.clj:478)
	at metabase.db.liquibase$rollback_major_version.invoke(liquibase.clj:465)
	at metabase.db.liquibase$rollback_major_version.invokeStatic(liquibase.clj:470)
	at metabase.db.liquibase$rollback_major_version.invoke(liquibase.clj:465)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:671)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.db.setup$migrate_BANG_$fn__53357.invoke(setup.clj:86)
	at metabase.db.liquibase$do_with_liquibase$f_STAR___44367.invoke(liquibase.clj:139)
	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:142)
	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:130)
	at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)
	at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.cmd.migrate$migrate_BANG_.invokeStatic(migrate.clj:8)
	at metabase.cmd.migrate$migrate_BANG_.invoke(migrate.clj:5)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.cmd$migrate.invokeStatic(cmd.clj:66)
	at metabase.cmd$migrate.invoke(cmd.clj:62)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__111564.invoke(cmd.clj:301)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:300)
	at metabase.cmd$run_cmd.invoke(cmd.clj:290)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:192)
	at metabase.core$run_cmd.invoke(core.clj:190)
	at metabase.core$entrypoint.invokeStatic(core.clj:214)
	at metabase.core$entrypoint.doInvoke(core.clj:209)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.RollbackFailedException: liquibase.exception.DatabaseException: (conn=20) Cannot add or update a child row: a foreign key constraint fails (`metabase`.`#sql-1_14`, CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE) [Failed SQL: (1452) ALTER TABLE `metabase`.`sandboxes` ADD CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `metabase`.`permissions` (`id`) ON DELETE CASCADE]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:151)
	at liquibase.command.core.AbstractRollbackCommandStep.doRollback(AbstractRollbackCommandStep.java:112)
	at liquibase.command.core.AbstractRollbackCommandStep.doRollback(AbstractRollbackCommandStep.java:82)
	at liquibase.command.core.RollbackCountCommandStep.lambda$run$0(RollbackCountCommandStep.java:48)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.command.core.RollbackCountCommandStep.run(RollbackCountCommandStep.java:48)
	at liquibase.command.CommandScope.execute(CommandScope.java:217)
	... 57 more
Caused by: liquibase.exception.RollbackFailedException: liquibase.exception.DatabaseException: (conn=20) Cannot add or update a child row: a foreign key constraint fails (`metabase`.`#sql-1_14`, CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE) [Failed SQL: (1452) ALTER TABLE `metabase`.`sandboxes` ADD CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `metabase`.`permissions` (`id`) ON DELETE CASCADE]
	at liquibase.changelog.ChangeSet.rollback(ChangeSet.java:956)
	at liquibase.changelog.visitor.RollbackVisitor.visit(RollbackVisitor.java:63)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Scope.child(Scope.java:252)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
	... 66 more
Caused by: liquibase.exception.DatabaseException: (conn=20) Cannot add or update a child row: a foreign key constraint fails (`metabase`.`#sql-1_14`, CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE) [Failed SQL: (1452) ALTER TABLE `metabase`.`sandboxes` ADD CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `metabase`.`permissions` (`id`) ON DELETE CASCADE]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1303)
	at liquibase.database.AbstractJdbcDatabase.executeRollbackStatements(AbstractJdbcDatabase.java:1327)
	at liquibase.changelog.ChangeSet.rollback(ChangeSet.java:921)
	... 80 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=20) Cannot add or update a child row: a foreign key constraint fails (`metabase`.`#sql-1_14`, CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:70)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:362)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:500)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
	... 85 more
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Cannot add or update a child row: a foreign key constraint fails (`metabase`.`#sql-1_14`, CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE)
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:195)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:263)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356)
	... 88 more
Caused by: java.sql.SQLException: Cannot add or update a child row: a foreign key constraint fails (`metabase`.`#sql-1_14`, CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1693)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1555)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1518)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:257)
	... 89 more
Command failed with exception: liquibase.exception.LiquibaseException: liquibase.exception.RollbackFailedException: liquibase.exception.DatabaseException: (conn=20) Cannot add or update a child row: a foreign key constraint fails (`metabase`.`#sql-1_14`, CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE) [Failed SQL: (1452) ALTER TABLE `metabase`.`sandboxes` ADD CONSTRAINT `fk_sandboxes_ref_permissions` FOREIGN KEY (`permission_id`) REFERENCES `metabase`.`permissions` (`id`) ON DELETE CASCADE]
```

### Information about your Metabase installation

```JSON
v50, but maybe this happens also in previous versions?
```

### Severity

P1

### Additional context

The fact that you can't remove the sandboxing to move back to an older version makes it a P1

**Comment by noahmoss** [comment]
Workaround: Run `UPDATE sandboxes SET permission_id = NULL;` on the app DB prior to migrating down
