### ISSUE TITLE
Issue upgrading Metabase from v0.41.7 to v0.50.6

### ISSUE THREAD

**Issue by antonio-tg** [metabase/metabase#44577]
### Describe the bug

I'm working with Metabase in an openshift cluster, I already have Metabase v0.41.7 and I would like to upgrade to v0.50.6 but I get an error. I try with Metabase v0.42.0 and it didn't work either.

### To Reproduce

Try the upgrade, I mean maybe the problem is that the tables in the base changed a lot.

### Expected behavior

Normal start.

### Logs

2024-06-21 20:44:24,535 INFO metabase.plugins :: Loading plugins in /plugins...
2024-06-21 20:44:24,733 INFO util.files :: Extract file /modules/sparksql.metabase-driver.jar -> /plugins/sparksql.metabase-driver.jar
2024-06-21 20:44:24,836 INFO util.files :: Extract file /modules/sqlserver.metabase-driver.jar -> /plugins/sqlserver.metabase-driver.jar
2024-06-21 20:44:24,852 INFO util.files :: Extract file /modules/snowflake.metabase-driver.jar -> /plugins/snowflake.metabase-driver.jar
2024-06-21 20:44:25,401 INFO util.files :: Extract file /modules/druid-jdbc.metabase-driver.jar -> /plugins/druid-jdbc.metabase-driver.jar
2024-06-21 20:44:25,451 INFO util.files :: Extract file /modules/mongo.metabase-driver.jar -> /plugins/mongo.metabase-driver.jar
2024-06-21 20:44:25,472 INFO util.files :: Extract file /modules/oracle.metabase-driver.jar -> /plugins/oracle.metabase-driver.jar
2024-06-21 20:44:25,474 INFO util.files :: Extract file /modules/athena.metabase-driver.jar -> /plugins/athena.metabase-driver.jar
2024-06-21 20:44:25,575 INFO util.files :: Extract file /modules/redshift.metabase-driver.jar -> /plugins/redshift.metabase-driver.jar
2024-06-21 20:44:25,585 INFO util.files :: Extract file /modules/presto-jdbc.metabase-driver.jar -> /plugins/presto-jdbc.metabase-driver.jar
2024-06-21 20:44:25,652 INFO util.files :: Extract file /modules/bigquery-cloud-sdk.metabase-driver.jar -> /plugins/bigquery-cloud-sdk.metabase-driver.jar
2024-06-21 20:44:25,940 INFO util.files :: Extract file /modules/druid.metabase-driver.jar -> /plugins/druid.metabase-driver.jar
2024-06-21 20:44:25,945 INFO util.files :: Extract file /modules/vertica.metabase-driver.jar -> /plugins/vertica.metabase-driver.jar
2024-06-21 20:44:25,947 INFO util.files :: Extract file /modules/sqlite.metabase-driver.jar -> /plugins/sqlite.metabase-driver.jar
2024-06-21 20:44:26,385 INFO plugins.classloader :: Added URL file:/plugins/databricks.metabase-driver.jar to classpath
2024-06-21 20:44:26,388 INFO plugins.classloader :: Added URL file:/plugins/ojdbc8.jar to classpath
2024-06-21 20:44:26,483 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
2024-06-21 20:44:26,484 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc]) 🚚
2024-06-21 20:44:26,485 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
2024-06-21 20:44:26,485 INFO driver.impl :: Registered driver :sparksql (parents: [:hive-like]) 🚚
2024-06-21 20:44:26,494 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
2024-06-21 20:44:26,494 INFO driver.impl :: Registered driver :sqlserver (parents: [:sql-jdbc]) 🚚
2024-06-21 20:44:26,636 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
2024-06-21 20:44:26,637 INFO driver.impl :: Registered driver :snowflake (parents: [:sql-jdbc]) 🚚
2024-06-21 20:44:26,650 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid-jdbc...
2024-06-21 20:44:26,650 INFO driver.impl :: Registered driver :druid-jdbc (parents: [:sql-jdbc]) 🚚
2024-06-21 20:44:26,666 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
2024-06-21 20:44:26,666 INFO driver.impl :: Registered driver :mongo  🚚
2024-06-21 20:44:26,701 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? true
2024-06-21 20:44:26,702 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :oracle...
2024-06-21 20:44:26,703 INFO driver.impl :: Registered driver :oracle (parents: [:sql-jdbc]) 🚚
2024-06-21 20:44:26,717 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :athena...
2024-06-21 20:44:26,717 INFO driver.impl :: Registered driver :athena (parents: [:sql-jdbc]) 🚚
2024-06-21 20:44:26,723 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
2024-06-21 20:44:26,723 INFO driver.impl :: Registered driver :redshift (parents: [:postgres]) 🚚
2024-06-21 20:44:26,741 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :presto-jdbc...
2024-06-21 20:44:26,742 INFO driver.impl :: Registered driver :presto-jdbc (parents: [:sql-jdbc]) 🚚
2024-06-21 20:44:26,769 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery-cloud-sdk...
2024-06-21 20:44:26,770 INFO driver.impl :: Registered driver :bigquery-cloud-sdk (parents: [:sql]) 🚚
2024-06-21 20:44:26,775 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
2024-06-21 20:44:26,775 INFO driver.impl :: Registered driver :druid  🚚
2024-06-21 20:44:26,780 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

2024-06-21 20:44:26,780 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
2024-06-21 20:44:26,781 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver"]
2024-06-21 20:44:26,784 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
2024-06-21 20:44:26,784 INFO driver.impl :: Registered driver :sqlite (parents: [:sql-jdbc]) 🚚
2024-06-21 20:44:26,789 DEBUG plugins.lazy-loaded-driver :: Registering lazy loading driver :db2...
2024-06-21 20:44:26,790 INFO driver.impl :: Registered driver :db2 (parents: [:sql-jdbc]) 🚚
2024-06-21 20:44:26,800 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2024-06-21 20:44:26,803 INFO db.setup :: Verifying postgres Database Connection ...
2024-06-21 20:44:27,483 INFO db.setup :: Successfully verified PostgreSQL 13.14 application database connection. ✅
2024-06-21 20:44:27,484 INFO db.setup :: Checking if a database downgrade is required...
2024-06-21 20:44:28,871 INFO db.setup :: Running Database Migrations...
2024-06-21 20:44:28,872 INFO db.setup :: Setting up Liquibase...
2024-06-21 20:44:29,724 INFO db.liquibase :: Updating liquibase table to reflect consolidated changeset filenames
2024-06-21 20:44:31,745 WARN util.jvm :: auto-retry metabase.db.liquibase$wait_for_migration_lock$fn__44387@204fbb43: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
2024-06-21 20:44:31,790 WARN db.liquibase :: Migration lock was acquired after 1 retries.
2024-06-21 20:44:31,812 INFO db.setup :: Liquibase is ready.
2024-06-21 20:44:31,812 INFO db.liquibase :: Checking if Database has unrun migrations...
2024-06-21 20:44:33,123 INFO db.liquibase :: Database has unrun migrations. Checking if migration lock is taken...
2024-06-21 20:44:33,146 INFO db.liquibase :: No migration lock found.
2024-06-21 20:44:33,147 INFO db.liquibase :: Migration lock acquired.
2024-06-21 20:44:33,808 INFO db.liquibase :: Running 426 migrations ...
2024-06-21 20:44:34,407 ERROR liquibase.changelog :: ChangeSet migrations/000_legacy_migrations.yaml::v42.00-065::dpsutton encountered an exception.
liquibase.exception.DatabaseException: ERROR: column "is_datasetnewb" of relation "core_user" already exists [Failed SQL: (0) ALTER TABLE "public"."core_user" ADD "is_datasetnewb" BOOLEAN DEFAULT TRUE NOT NULL]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Scope.child(Scope.java:252)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
	at liquibase.command.CommandScope.execute(CommandScope.java:217)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
	at liquibase.Liquibase.update(Liquibase.java:234)
	at liquibase.Liquibase.update(Liquibase.java:212)
	at liquibase.Liquibase.update(Liquibase.java:194)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__44426.invoke(liquibase.clj:359)
	at metabase.db.liquibase$run_in_scope_locked$reify__44422.run(liquibase.clj:324)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:317)
	at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:300)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:348)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:341)
	at metabase.db.setup$migrate_BANG_$fn__53352.invoke(setup.clj:84)
	at metabase.db.liquibase$do_with_liquibase$f_STAR___44363.invoke(liquibase.clj:139)
	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:142)
	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:130)
	at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)
	at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:149)
	at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:144)
	at metabase.db.setup$setup_db_BANG_$fn__53380$fn__53381.invoke(setup.clj:167)
	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
	at metabase.db.setup$setup_db_BANG_$fn__53380.invoke(setup.clj:161)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
	at metabase.db$setup_db_BANG_$fn__53405.invoke(db.clj:82)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:77)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:64)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:117)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
	at metabase.core$init_BANG_.invokeStatic(core.clj:170)
	at metabase.core$init_BANG_.invoke(core.clj:165)
	at metabase.core$start_normally.invokeStatic(core.clj:182)
	at metabase.core$start_normally.invoke(core.clj:176)
	at metabase.core$entrypoint.invokeStatic(core.clj:215)
	at metabase.core$entrypoint.doInvoke(core.clj:209)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.bootstrap.main(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: column "is_datasetnewb" of relation "core_user" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
	... 86 more

UPDATE SUMMARY
Run:                        426
Previously run:             374
Filtered out:                50
-------------------------------
Total change sets:          850

FILTERED CHANGE SETS SUMMARY
DBMS mismatch:               50

2024-06-21 20:44:34,503 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/000_legacy_migrations.yaml::v42.00-065::dpsutton:
     Reason: liquibase.exception.DatabaseException: ERROR: column "is_datasetnewb" of relation "core_user" already exists [Failed SQL: (0) ALTER TABLE "public"."core_user" ADD "is_datasetnewb" BOOLEAN DEFAULT TRUE NOT NULL]
	at liquibase.command.CommandScope.execute(CommandScope.java:253)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
	at liquibase.Liquibase.update(Liquibase.java:234)
	at liquibase.Liquibase.update(Liquibase.java:212)
	at liquibase.Liquibase.update(Liquibase.java:194)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__44426.invoke(liquibase.clj:359)
	at metabase.db.liquibase$run_in_scope_locked$reify__44422.run(liquibase.clj:324)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:317)
	at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:300)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:348)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:341)
	at metabase.db.setup$migrate_BANG_$fn__53352.invoke(setup.clj:84)
	at metabase.db.liquibase$do_with_liquibase$f_STAR___44363.invoke(liquibase.clj:139)
	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:142)
	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:130)
	at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)
	at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:149)
	at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:144)
	at metabase.db.setup$setup_db_BANG_$fn__53380$fn__53381.invoke(setup.clj:167)
	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
	at metabase.db.setup$setup_db_BANG_$fn__53380.invoke(setup.clj:161)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
	at metabase.db$setup_db_BANG_$fn__53405.invoke(db.clj:82)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:77)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:64)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:117)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
	at metabase.core$init_BANG_.invokeStatic(core.clj:170)
	at metabase.core$init_BANG_.invoke(core.clj:165)
	at metabase.core$start_normally.invokeStatic(core.clj:182)
	at metabase.core$start_normally.invoke(core.clj:176)
	at metabase.core$entrypoint.invokeStatic(core.clj:215)
	at metabase.core$entrypoint.doInvoke(core.clj:209)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.bootstrap.main(Unknown Source)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/000_legacy_migrations.yaml::v42.00-065::dpsutton:
     Reason: liquibase.exception.DatabaseException: ERROR: column "is_datasetnewb" of relation "core_user" already exists [Failed SQL: (0) ALTER TABLE "public"."core_user" ADD "is_datasetnewb" BOOLEAN DEFAULT TRUE NOT NULL]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:151)
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
	at liquibase.command.CommandScope.execute(CommandScope.java:217)
	... 58 more
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/000_legacy_migrations.yaml::v42.00-065::dpsutton:
     Reason: liquibase.exception.DatabaseException: ERROR: column "is_datasetnewb" of relation "core_user" already exists [Failed SQL: (0) ALTER TABLE "public"."core_user" ADD "is_datasetnewb" BOOLEAN DEFAULT TRUE NOT NULL]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:797)
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Scope.child(Scope.java:252)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
	... 66 more
Caused by: liquibase.exception.DatabaseException: ERROR: column "is_datasetnewb" of relation "core_user" already exists [Failed SQL: (0) ALTER TABLE "public"."core_user" ADD "is_datasetnewb" BOOLEAN DEFAULT TRUE NOT NULL]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
	... 81 more
Caused by: org.postgresql.util.PSQLException: ERROR: column "is_datasetnewb" of relation "core_user" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
	... 86 more
2024-06-21 20:44:34,509 INFO metabase.core :: Metabase Shutting Down ...
2024-06-21 20:44:34,510 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2024-06-21 20:44:34,520 WARN db.liquibase :: ()
2024-06-21 20:44:34,521 INFO metabase.core :: Metabase Shutdown COMPLETE

### Information about your Metabase installation

```JSON
My openshift cluster is 4.12.25 version.
```

### Severity

the pods just don't start

**Comment by paoliniluis** [comment]
Database has migration lock; cannot run migrations. You can force-release these locks by running java -jar metabase.jar migrate release-locks
