### ISSUE TITLE
Get empty page when running in local

### ISSUE THREAD

**Issue by alanlong9278** [metabase/metabase#44664]
### Describe the bug

Follow the installation guide.
```
yarn install
yarn dev
```
but got an empty page, the log in terminal shows server is runed
<img width="1723" alt="image" src="https://github.com/metabase/metabase/assets/5860999/02a63926-6659-4590-9531-9ce75ad35c8e">
Error msg in console 
```
{
    "name": "n",
    "httpError": false,
    "httpStatus": 0,
    "httpStatusText": "TypeError: Failed to fetch",
    "code": 0,
    "message": "network error(Failed to fetch)",
    "data": null,
    "originalError": {
        "name": "TypeError",
        "message": "Failed to fetch",
        "stack": "TypeError: Failed to fetch\n    at $S.request (chrome-extension://ofpnmcalabcbjgholdjcjblkibolbppb/background.js:464:9174)\n    at pa.handleSendRequest (chrome-extension://ofpnmcalabcbjgholdjcjblkibolbppb/background.js:464:22390)\n    at pa.sendRequest (chrome-extension://ofpnmcalabcbjgholdjcjblkibolbppb/background.js:464:21974)\n    at pa.staticConfig (chrome-extension://ofpnmcalabcbjgholdjcjblkibolbppb/background.js:464:85874)\n    at chrome-extension://ofpnmcalabcbjgholdjcjblkibolbppb/background.js:657:18533\n    at s (chrome-extension://ofpnmcalabcbjgholdjcjblkibolbppb/background.js:542:20936)\n    at Nb._fetchWithCache (chrome-extension://ofpnmcalabcbjgholdjcjblkibolbppb/background.js:542:21069)\n    at Nb.getStaticConfig (chrome-extension://ofpnmcalabcbjgholdjcjblkibolbppb/background.js:657:18469)"
    },
    "handled": false,
    "reqInfo": {
        "id": 2,
        "pathPrefix": "/user",
        "method": "GET",
        "path": "/static_config",
        "cmd": null,
        "otherParams": [],
        "isLowLevelResp": false,
        "config": {},
        "cacheKey": null
    }
}
```

err in terminal
```
ERROR middleware.log :: GET /api/health 503 215.5 µs (0 DB calls) {:metabase-user-id nil} 
[backend] {:status "initializing", :progress 0.95}
[backend] 
[backend] 2024-06-25 16:40:24,627 INFO core.QuartzScheduler :: Scheduler MetabaseScheduler_$_MMDC02FP00BMD6V1719304824269 paused.
[backend] 2024-06-25 16:40:24,628 INFO metabase.task :: Task sched
```
Do I need to do more to run it in locally?

### Expected behavior

got a normal page 

### Information about your Metabase installation

```JSON
- Chrome: Version 126.0.6478.116 (Official Build) (x86_64)
- OS: MACOS 14.5
- Metabase version: latest code from master
```

### Severity

0

**Comment by calherries** [comment]
@alanlong9278 The error in the console mentions a chrome extension. Does the same error happen in incognito mode?

**Comment by alanlong9278** [comment]
> @alanlong9278 The error in the console mentions a chrome extension. Does the same error happen in incognito mode?

Fixed, thanks
