### ISSUE TITLE
Server startup fails with "Unterminated string literal" error

### ISSUE THREAD

**Issue by trojanh** [metabase/metabase#45166]
### Describe the bug

After upgrade to `Metabase v0.50.10` I have started getting below error during server start which is causing the metabase to crash.

```
2024-07-05 06:44:47,729 INFO db.liquibase :: Running 64 migrations ...
2024-07-05 06:44:48,019 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v50.2024-01-10T03:27:30::noahmoss encountered an exception.
liquibase.exception.DatabaseException: Unterminated string literal started at position 1,694 in SQL -- Insert table-level permissions only where no DB-level permissions exist
```

### To Reproduce

1. Use `Metabase v0.50.10 (49d9e46)`
2. Start/Restart the metabase server

### Expected behavior

Should start the metabase server without any migration errors

### Logs

```
2024-07-05 06:44:46,028 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
2024-07-05 06:44:46,028 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver"]
2024-07-05 06:44:46,034 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2024-07-05 06:44:46,036 INFO db.setup :: Verifying postgres Database Connection ...
2024-07-05 06:44:46,368 INFO db.setup :: Successfully verified PostgreSQL 10.7 application database connection. ✅
2024-07-05 06:44:46,368 INFO db.setup :: Checking if a database downgrade is required...
2024-07-05 06:44:46,909 INFO db.setup :: Running Database Migrations...
2024-07-05 06:44:46,910 INFO db.setup :: Setting up Liquibase...
2024-07-05 06:44:47,066 INFO db.setup :: Liquibase is ready.
2024-07-05 06:44:47,067 INFO db.liquibase :: Checking if Database has unrun migrations...
2024-07-05 06:44:47,506 INFO db.liquibase :: Database has unrun migrations. Checking if migration lock is taken...
2024-07-05 06:44:47,517 INFO db.liquibase :: No migration lock found.
2024-07-05 06:44:47,517 INFO db.liquibase :: Migration lock acquired.
2024-07-05 06:44:47,729 INFO db.liquibase :: Running 64 migrations ...
2024-07-05 06:44:48,019 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v50.2024-01-10T03:27:30::noahmoss encountered an exception.
liquibase.exception.DatabaseException: Unterminated string literal started at position 1,694 in SQL -- Insert table-level permissions only where no DB-level permissions exist

WITH escaped_schema_table AS (
    SELECT
    mt.id,
    mt.db_id,
    mt.schema,
    REPLACE(REPLACE(mt.schema, '\', '\\'), '/', '\/') AS escaped_schema
    FROM metabase_table mt
)
INSERT INTO data_permissions (group_id, perm_type, db_id, schema_name, table_id, perm_value)
SELECT pg.id AS group_id,
       'perms/data-access' AS perm_type,
       mt.db_id,
       mt.schema AS schema_name,
       mt.id AS table_id,
       CASE
           WHEN EXISTS
                  (SELECT 1
                   FROM permissions p
                   WHERE p.group_id = pg.id
                     AND (p.object = concat('/db/', mt.db_id, '/schema/', mt.escaped_schema, '/')
                          OR p.object = concat('/db/', mt.db_id, '/schema/', mt.escaped_schema, '/table/', mt.id, '/')
                          OR p.object = concat('/db/', mt.db_id, '/schema/', mt.escaped_schema, '/table/', mt.id, '/query/')
                          OR p.object = concat('/db/', mt.db_id, '/schema/', mt.escaped_schema, '/table/', mt.id, '/query/segmented/')) ) THEN 'unrestricted'
           ELSE 'no-self-service'
       END AS perm_value
FROM permissions_group pg
CROSS JOIN escaped_schema_table mt
WHERE pg.name != 'Administrators'
  AND NOT EXISTS
    (SELECT 1
     FROM data_permissions dp
     WHERE dp.group_id = pg.id
       AND dp.db_id = mt.db_id
       AND dp.table_id = mt.id
       AND dp.perm_type = 'perms/data-access' )
  AND NOT EXISTS
    (SELECT 1
     FROM data_permissions dp
     WHERE dp.group_id = pg.id
       AND dp.db_id = mt.db_id
       AND dp.table_id IS NULL
       AND dp.perm_type = 'perms/data-access' ). Expected  char [Failed SQL: (0) -- Insert table-level permissions only where no DB-level permissions exist

WITH escaped_schema_table AS (
    SELECT
    mt.id,
    mt.db_id,
    mt.schema,
    REPLACE(REPLACE(mt.schema, '\', '\\'), '/', '\/') AS escaped_schema
    FROM metabase_table mt
)
INSERT INTO data_permissions (group_id, perm_type, db_id, schema_name, table_id, perm_value)
SELECT pg.id AS group_id,
       'perms/data-access' AS perm_type,
       mt.db_id,
       mt.schema AS schema_name,
       mt.id AS table_id,
       CASE
           WHEN EXISTS
                  (SELECT 1
                   FROM permissions p
                   WHERE p.group_id = pg.id
                     AND (p.object = concat('/db/', mt.db_id, '/schema/', mt.escaped_schema, '/')
                          OR p.object = concat('/db/', mt.db_id, '/schema/', mt.escaped_schema, '/table/', mt.id, '/')
                          OR p.object = concat('/db/', mt.db_id, '/schema/', mt.escaped_schema, '/table/', mt.id, '/query/')
                          OR p.object = concat('/db/', mt.db_id, '/schema/', mt.escaped_schema, '/table/', mt.id, '/query/segmented/')) ) THEN 'unrestricted'
           ELSE 'no-self-service'
       END AS perm_value
FROM permissions_group pg
CROSS JOIN escaped_schema_table mt
WHERE pg.name != 'Administrators'
  AND NOT EXISTS
    (SELECT 1
     FROM data_permissions dp
     WHERE dp.group_id = pg.id
       AND dp.db_id = mt.db_id
       AND dp.table_id = mt.id
       AND dp.perm_type = 'perms/data-access' )
  AND NOT EXISTS
    (SELECT 1
     FROM data_permissions dp
     WHERE dp.group_id = pg.id
       AND dp.db_id = mt.db_id
       AND dp.table_id IS NULL
       AND dp.perm_type = 'perms/data-access' )]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Scope.child(Scope.java:252)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
	at liquibase.command.CommandScope.execute(CommandScope.java:217)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
	at liquibase.Liquibase.update(Liquibase.java:234)
	at liquibase.Liquibase.update(Liquibase.java:212)
	at liquibase.Liquibase.update(Liquibase.java:194)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__44437.invoke(liquibase.clj:359)
	at metabase.db.liquibase$run_in_scope_locked$reify__44433.run(liquibase.clj:324)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
	at liquibase.Scope.child(Scope.java:195)
	at liquibase.Scope.child(Scope.java:185)
	at liquibase.Scope.child(Scope.java:164)
	at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:317)
	at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:300)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:348)
	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:341)
	at metabase.db.setup$migrate_BANG_$fn__53364.invoke(setup.clj:84)
	at metabase.db.liquibase$do_with_liquibase$f_STAR___44374.invoke(liquibase.clj:139)
	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:142)
	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:130)
	at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)
	at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:149)
	at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:144)
	at metabase.db.setup$setup_db_BANG_$fn__53392$fn__53393.invoke(setup.clj:167)
	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
	at metabase.db.setup$setup_db_BANG_$fn__53392.invoke(setup.clj:161)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
	at metabase.db$setup_db_BANG_$fn__53417.invoke(db.clj:82)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:77)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:64)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:117)
	at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
	at metabase.core$init_BANG_.invokeStatic(core.clj:170)
	at metabase.core$init_BANG_.invoke(core.clj:165)
	at metabase.core$start_normally.invokeStatic(core.clj:182)
	at metabase.core$start_normally.invoke(core.clj:176)
	at metabase.core$entrypoint.invokeStatic(core.clj:215)
	at metabase.core$entrypoint.doInvoke(core.clj:209)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.bootstrap.main(Unknown Source)
Caused by: org.postgresql.util.PSQLException: Unterminated string literal started at position 1,694 in SQL -- Insert table-level permissions only where no DB-level permissions exist
```

### Information about your Metabase installation

```JSON
- Database: PostgreSQL 42.6.0
- Metabase: v0.50.10 (49d9e46)
- Hosting: Kubernetes using Docker image
```

### Severity

High

### Additional context

I tried using lower version of Metebase by updating the version in Dockerfile but it started giving another error with same migration file

**Comment by piranha** [comment]
> 2024-07-05 06:44:46,368 INFO db.setup :: Successfully verified PostgreSQL 10.7 application database connection. ✅

Metabase supports Postgres 11 and later (and we certainly hit an issue with 10 just recently), so even if this is not a reason I suggest updating it.

**Comment by trojanh** [comment]
thanks @piranha 
this issue started happening in recent weeks which might be because v0.50.9 and v0.50.10 but will check with updated version and see it it works

could we add some kind of deprecation warning in the logs itself which will help people know to update the DB version?

**Comment by piranha** [comment]
Yeah, I think we started hitting actual miscompatibilities with pg 10 just recently, but it's been long out of support, so it just makes sense to update it.

We're discussing adding a log saying your app db is too old, thanks for the suggestion!

**Comment by darksciencebase** [comment]
@trojanh did it work for you with a newer postgres?

**Comment by trojanh** [comment]
haven't been able to try this out yet but will update here once we do that, 

we are also considering [rollback](https://www.metabase.com/docs/latest/installation-and-operation/upgrading-metabase#rolling-back-an-upgrade) to previous version temporarily so if you are stuck, you could give that a shot but it would mean you won't be able to use newer version.

**Comment by darksciencebase** [comment]
@trojanh oh, thanks, i'm not stuck, i work for metabase :)

**Comment by trojanh** [comment]
downgrading to `v0.48.13` fixed this issue, 
https://www.metabase.com/docs/latest/installation-and-operation/upgrading-metabase#upgrading-metabase-on-other-platforms

**Comment by paoliniluis** [comment]
@trojanh please upgrade your postgres DB and try again

**Comment by darksciencebase** [comment]
@trojanh if it doesn't work with a newer postgres, leave a comment and we'll reopen the issue.
