### ISSUE TITLE
A model fail to cache but query works

### ISSUE THREAD

**Issue by vipera7** [metabase/metabase#45181]
### Describe the bug

I have seven models using the same database, but only six of them have been successfully refreshed. When I run the query for the model that failed, it executes in less than one minute. Why does it continue to fail?

### To Reproduce

1 - Allow time for caching.
2 - On the tools page, the model encounters the following error:
ERREUR: annulation de la requête à cause du délai écoulé pour l'exécution de l'instruction

### Expected behavior

The model should be cached as it was previously.

### Logs

> INFO metabase.task.persist-refresh Error refreshing persisting model with card-id 273,org.postgresql.util.PSQLException: ERREUR: annulation de la requête à cause du délai écoulé pour l'exécution de l'instruction,	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725),	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412),	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371),	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502),	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419),	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194),	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:155),	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1502),	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__41953.invoke(jdbc.clj:1049),	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:860),	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776),	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789),	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776),	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1048),	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1042),	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1080),	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1060),	at clojure.java.jdbc$execute_BANG_$execute_helper__42027.invoke(jdbc.clj:1464),	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1466),	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1435),	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1456),	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1435),	at metabase.driver.sql.ddl$execute_BANG_.invokeStatic(ddl.clj:27),	at metabase.driver.sql.ddl$execute_BANG_.invoke(ddl.clj:24),	at metabase.driver.postgres.ddl$fn__85617$fn__85619$fn__85620.invoke(ddl.clj:49),	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807),	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776),	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789),	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776),	at metabase.driver.postgres.ddl$fn__85617$fn__85619.invoke(ddl.clj:46),	at metabase.driver.sql_jdbc.execute$fn__81291$fn__81292.invoke(execute.clj:397),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:337),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:320),	at metabase.driver.sql_jdbc.execute$fn__81291.invokeStatic(execute.clj:391),	at metabase.driver.sql_jdbc.execute$fn__81291.invoke(execute.clj:389),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.driver.postgres.ddl$fn__85617.invokeStatic(ddl.clj:41),	at metabase.driver.postgres.ddl$fn__85617.invoke(ddl.clj:38),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.task.persist_refresh$reify__86565.refresh_BANG_(persist_refresh.clj:53),	at metabase.task.persist_refresh$refresh_with_stats_BANG_$fn__86568.invoke(persist_refresh.clj:73),	at metabase.task.persist_refresh$refresh_with_stats_BANG_.invokeStatic(persist_refresh.clj:72),	at metabase.task.persist_refresh$refresh_with_stats_BANG_.invoke(persist_refresh.clj:57),	at clojure.lang.AFn.applyToHelper(AFn.java:165),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.core$apply.invokeStatic(core.clj:673),	at clojure.core$partial$fn__5914.doInvoke(core.clj:2660),	at clojure.lang.RestFn.invoke(RestFn.java:397),	at metabase.task.persist_refresh$save_task_history_BANG_$fn__86586.invoke(persist_refresh.clj:123),	at metabase.models.task_history$do_with_task_history.invokeStatic(task_history.clj:116),	at metabase.models.task_history$do_with_task_history.invoke(task_history.clj:105),	at metabase.task.persist_refresh$save_task_history_BANG_.invokeStatic(persist_refresh.clj:115),	at metabase.task.persist_refresh$save_task_history_BANG_.invoke(persist_refresh.clj:111),	at metabase.task.persist_refresh$refresh_individual_BANG_.invokeStatic(persist_refresh.clj:219),	at metabase.task.persist_refresh$refresh_individual_BANG_.invoke(persist_refresh.clj:211),	at metabase.task.persist_refresh$refresh_job_fn_BANG_.invokeStatic(persist_refresh.clj:235),	at metabase.task.persist_refresh$refresh_job_fn_BANG_.invoke(persist_refresh.clj:229),	at metabase.task.persist_refresh.PersistenceRefresh.execute(persist_refresh.clj:245),	at org.quartz.core.JobRunShell.run(JobRunShell.java:202),	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[d7ed4fe8-1eca-4698-9c79-6a1166322f22] 2024-07-05T16:11:19+02:00 INFO metabase.task.persist-refresh Finished updated model-id 273 from persisted-info 161.

### Information about your Metabase installation

```JSON
Metabase is installed on Windows Server 2016 and is configured for production mode with a MySQL 8 server. It is running version v0.50.8. The database that the model points to is PostgreSQL.
```

### Severity

I can't run my other reports that depend on this model

**Comment by vipera7** [comment]
I observed that if I disable the option to persist the model in the admin settings and then re-enable it, the models are correctly persisted. This might provide a clue.

**Comment by paoliniluis** [comment]
metabase version?

**Comment by vipera7** [comment]
Hello paoliniluis,

Here are the info of my Metabase:

```
{
  "browser-info": {
    "language": "fr-FR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "Cp1252",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.23+9",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.23",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.23+9",
    "os.name": "Windows Server 2016",
    "os.version": "10.0",
    "user.language": "fr",
    "user.timezone": "Europe/Paris"
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "mysql"
    ],
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.36"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-07-12",
      "tag": "v0.50.12",
      "hash": "86d4671"
    },
    "settings": {
      "report-timezone": "Europe/Paris"
    }
  }
}
```

**Comment by vipera7** [comment]
I wonder if the name of the last model is related to this issue: 

![Sans titre](https://github.com/user-attachments/assets/97a5b6de-2b6e-4bfe-bc0b-cce042808045)

**Comment by dragonsahead** [comment]
@vipera7 do you still see this?
