### ISSUE TITLE
yarn build fails with Metabase with 0.50.11

### ISSUE THREAD

**Issue by tumbler-x** [metabase/metabase#45339]
### Describe the bug

when run "yarn build" in the project dir, then print: 
root@iZf8zhs1taah6tauqg1dd1Z:~/metabase# yarn build
yarn run v1.22.22
$ yarn build:cljs && yarn build:js
$ yarn && yarn build-pure:cljs
$ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^2.2.3"
warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^2.2.3"
warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^1.0.1"
warning Resolution field "set-value@4.0.1" is incompatible with requested version "set-value@^2.0.0"
warning Resolution field "unset-value@2.0.1" is incompatible with requested version "unset-value@^1.0.0"
warning Resolution field "set-value@4.0.1" is incompatible with requested version "set-value@^2.0.1"
warning Resolution field "source-map-js@1.2.0" is incompatible with requested version "source-map-js@^0.6.2"
warning Resolution field "nth-check@2.0.1" is incompatible with requested version "nth-check@^1.0.2"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^1.0.2"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^6.0.1"
warning Resolution field "json5@2.2.2" is incompatible with requested version "json5@^2.2.3"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^6.0.1"
success Already up-to-date.
$ patch-package
patch-package 8.0.0
Applying patches...
@storybook/core-common@6.5.16 ✔
echarts@5.5.0 ✔
echarts@5.5.1-rc.1 ✔
$ husky install
fatal: not a git repository (or any of the parent directories): .git
$ yarn clean-dev:cljs && shadow-cljs compile app
$ rm -rf target/cljs_dev/*
shadow-cljs - config: /root/metabase/shadow-cljs.edn
shadow-cljs - starting via "clojure"
--- SHADOW-CLJS FAILED TO LOAD! ----------------------

This is most commonly caused by a dependency conflict.
When using deps.edn or project.clj you must ensure that all
required dependencies are provided with the correct version.

You are using shadow-cljs version: 2.27.5

The important dependencies are:

  org.clojure/clojure "1.11.1"
  org.clojure/clojurescript "1.11.132"
  com.google.javascript/closure-compiler-unshaded "v20230802"

Please verify that you are loading these versions.
You can find all required dependencies here:

  https://clojars.org/thheller/shadow-cljs/versions/2.27.5

Please refer to the Guide for more information:

  https://shadow-cljs.github.io/docs/UsersGuide.html#failed-to-load

-----------------------------------------------------

The error encountered was:

Syntax error macroexpanding at (shadow/cljs/util.clj:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7665)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6162)
	at clojure.core$load.invokeStatic(core.clj:6161)
	at clojure.core$load.doInvoke(core.clj:6145)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5934)
	at clojure.core$load_one.invoke(core.clj:5929)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5976)
	at clojure.core$load_lib.invokeStatic(core.clj:5975)
	at clojure.core$load_lib.doInvoke(core.clj:5954)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6017)
	at clojure.core$load_libs.doInvoke(core.clj:6001)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6039)
	at clojure.core$require.doInvoke(core.clj:6039)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at shadow.cljs.devtools.config$eval191$loading__6789__auto____192.invoke(config.clj:1)
	at shadow.cljs.devtools.config$eval191.invokeStatic(config.clj:1)
	at shadow.cljs.devtools.config$eval191.invoke(config.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6162)
	at clojure.core$load.invokeStatic(core.clj:6161)
	at clojure.core$load.doInvoke(core.clj:6145)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5934)
	at clojure.core$load_one.invoke(core.clj:5929)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5976)
	at clojure.core$load_lib.invokeStatic(core.clj:5975)
	at clojure.core$load_lib.doInvoke(core.clj:5954)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6017)
	at clojure.core$load_libs.doInvoke(core.clj:6001)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6039)
	at clojure.core$require.doInvoke(core.clj:6039)
	at clojure.lang.RestFn.invoke(RestFn.java:1289)
	at shadow.cljs.devtools.cli_actual$eval173$loading__6789__auto____174.invoke(cli_actual.clj:1)
	at shadow.cljs.devtools.cli_actual$eval173.invokeStatic(cli_actual.clj:1)
	at shadow.cljs.devtools.cli_actual$eval173.invoke(cli_actual.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6162)
	at clojure.core$load.invokeStatic(core.clj:6161)
	at clojure.core$load.doInvoke(core.clj:6145)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5934)
	at clojure.core$load_one.invoke(core.clj:5929)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5976)
	at clojure.core$load_lib.invokeStatic(core.clj:5975)
	at clojure.core$load_lib.doInvoke(core.clj:5954)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6017)
	at clojure.core$load_libs.doInvoke(core.clj:6001)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6039)
	at clojure.core$require.doInvoke(core.clj:6039)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$serialized_require.invokeStatic(core.clj:6115)
	at clojure.core$requiring_resolve.invokeStatic(core.clj:6124)
	at clojure.core$requiring_resolve.invoke(core.clj:6118)
	at shadow.cljs.devtools.cli$_main$fn__166.invoke(cli.clj:70)
	at shadow.cljs.devtools.cli$_main.invokeStatic(cli.clj:69)
	at shadow.cljs.devtools.cli$_main.doInvoke(cli.clj:67)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.main$main_opt.invokeStatic(main.clj:514)
	at clojure.main$main_opt.invoke(main.clj:510)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
Caused by: java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CompilerOptions has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2209)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2222)
	at cljs.externs$loading__6706__auto____1358.invoke(externs.clj:9)
	at cljs.externs__init.load(Unknown Source)
	at cljs.externs__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2209)
	at clojure.lang.RT.classForName(RT.java:2218)
	at clojure.lang.RT.loadClassForName(RT.java:2237)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6162)
	at clojure.core$load.invokeStatic(core.clj:6161)
	at clojure.core$load.doInvoke(core.clj:6145)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5934)
	at clojure.core$load_one.invoke(core.clj:5929)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5976)
	at clojure.core$load_lib.invokeStatic(core.clj:5975)
	at clojure.core$load_lib.doInvoke(core.clj:5954)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6017)
	at clojure.core$load_libs.doInvoke(core.clj:6001)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6039)
	at clojure.core$require.doInvoke(core.clj:6039)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at cljs.env$loading__6706__auto____754.invoke(env.cljc:9)
	at cljs.env__init.load(Unknown Source)
	at cljs.env__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2209)
	at clojure.lang.RT.classForName(RT.java:2218)
	at clojure.lang.RT.loadClassForName(RT.java:2237)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6162)
	at clojure.core$load.invokeStatic(core.clj:6161)
	at clojure.core$load.doInvoke(core.clj:6145)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5934)
	at clojure.core$load_one.invoke(core.clj:5929)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5976)
	at clojure.core$load_lib.invokeStatic(core.clj:5975)
	at clojure.core$load_lib.doInvoke(core.clj:5954)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6017)
	at clojure.core$load_libs.doInvoke(core.clj:6001)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6039)
	at clojure.core$require.doInvoke(core.clj:6039)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at cljs.analyzer$loading__6706__auto____645.invoke(analyzer.cljc:9)
	at cljs.analyzer__init.load(Unknown Source)
	at cljs.analyzer__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2209)
	at clojure.lang.RT.classForName(RT.java:2218)
	at clojure.lang.RT.loadClassForName(RT.java:2237)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6162)
	at clojure.core$load.invokeStatic(core.clj:6161)
	at clojure.core$load.doInvoke(core.clj:6145)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5934)
	at clojure.core$load_one.invoke(core.clj:5929)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5976)
	at clojure.core$load_lib.invokeStatic(core.clj:5975)
	at clojure.core$load_lib.doInvoke(core.clj:5954)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6017)
	at clojure.core$load_libs.doInvoke(core.clj:6001)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6039)
	at clojure.core$require.doInvoke(core.clj:6039)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at shadow.cljs.util$eval263$loading__6789__auto____264.invoke(util.clj:1)
	at shadow.cljs.util$eval263.invokeStatic(util.clj:1)
	at shadow.cljs.util$eval263.invoke(util.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	... 95 more
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Information about your Metabase installation

```JSON
OS:Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
java:java version "1.8.0_411"
  Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
  Java HotSpot(TM) 64-Bit Server VM (build 25.411-b09, mixed mode)
npm:v10.7.0
node: v20.15.0
yarn:v1.22.22
clj:Clojure 1.11.2
```

### Severity

entirely

**Comment by nemanjaglumac** [comment]
Please use the node version indicated in `.nvmrc`, which is `v.18.20.0`

**Comment by paoliniluis** [comment]
You’re using Java 8 which is no longer supported
