### ISSUE TITLE
Passing `?limit=` twice to a question URL returns a bare 500

### ISSUE THREAD

**Issue by romeovs** [metabase/metabase#45345]
### Describe the bug

When adding the `?limit=` url search parameter to a question twice, I get a bare unstyled 500 page. Even for questions that do not have a `limit` parameter defined at all.

<img width="1474" alt="Screenshot 2024-07-09 at 16 51 59" src="https://github.com/metabase/metabase/assets/1250185/1331d955-821d-49fd-b698-137655721d36">

### To Reproduce

1. Create any question and save it
2. Visit the question and add `?limit=1&limit=2` to the url
3. See the bare 500 page

### Expected behavior

Passing the limit url param twice is not supported, but we should either redirect to remove one of the limits, or render a more useful error page.

### Information about your Metabase installation

```JSON
On `master` at 6946a5d3dd122d4510cabbae407a44d1ab1e2d6b as well as on stats.
```

### Severity

P3

**Comment by piranha** [comment]
This could be a bit more than just a problem with `limit`, every query parameter is implicitly converted to a vector internally if it's supplied a few times.

**Comment by dpsutton** [comment]
My thinking is that we don't want to prevent the error in full generality (as @piranha says that sounds like an endless struggle) but we absolutely have to handle errors thrown at this point in the middleware.


<details>
<summary>Stactrace:</summary>

```
java.lang.IllegalArgumentException: Expected string, got clojure.lang.PersistentVector
	at clojure.core$parse_long.invokeStatic(core.clj:8165)
	at clojure.core$parse_long.invoke(core.clj:8158)
	at metabase.server.middleware.offset_paging$parse_paging_params.invokeStatic(offset_paging.clj:19)
	at metabase.server.middleware.offset_paging$parse_paging_params.invoke(offset_paging.clj:18)
	at metabase.server.middleware.offset_paging$handle_paging$fn__146009.invoke(offset_paging.clj:38)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__83890.invoke(json.clj:88)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__169538.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__169565.invoke(params.clj:77)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__121734.invoke(misc.clj:60)
.clj:568)t metabase.server.middleware.session$reset_session_timeout$fn__127307.invoke(session
	at metabase.server.middleware.session$bind_current_user$fn__127265$fn__127266.invoke(session.clj:462)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:441)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:424)
	at metabase.server.middleware.session$bind_current_user$fn__127265.invoke(session.clj:461)
	at metabase.server.middleware.session$wrap_current_user_info$fn__127238.invoke(session.clj:385)
	at metabase.server.middleware.session$wrap_session_id$fn__127210.invoke(session.clj:261)
	at metabase.server.middleware.auth$wrap_static_api_key$fn__145513.invoke(auth.clj:32)
	at ring.middleware.cookies$wrap_cookies$fn__169353.invoke(cookies.clj:200)
	at metabase.server.middleware.misc$add_content_type$fn__121716.invoke(misc.clj:28)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__121742.invoke(misc.clj:77)
	at ring.middleware.gzip$wrap_gzip$fn__169403.invoke(gzip.clj:86)
_id$wrap_request_id$fn__146024.invoke(request_id.clj:9)
	at metabase.server.middleware.misc$bind_request$fn__121745.invoke(misc.clj:94)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__146047.invoke(ssl.clj:41)
	at clojure.lang.Var.invoke(Var.java:395)
	at metabase.server$async_proxy_handler$fn__119058.invoke(server.clj:77)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
lipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-07-10 13:30:09,942 ERROR metabase.server :: Unexpected exception in endpoint
java.lang.IllegalArgumentException: Expected string, got clojure.lang.PersistentVector
	at clojure.core$parse_long.invokeStatic(core.clj:8165)
	at clojure.core$parse_long.invoke(core.clj:8158)
	at metabase.server.middleware.offset_paging$parse_paging_params.invokeStatic(offset_paging.clj:19)
	at metabase.server.middleware.offset_paging$parse_paging_params.invoke(offset_paging.clj:18)
	at metabase.server.middleware.offset_paging$handle_paging$fn__146009.invoke(offset_paging.clj:38)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__83890.invoke(json.clj:88)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__169538.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__169565.invoke(params.clj:77)
1734.invoke(misc.clj:60)er.middleware.misc$maybe_set_site_url$fn__12
	at metabase.server.middleware.session$reset_session_timeout$fn__127307.invoke(session.clj:568)
	at metabase.server.middleware.session$bind_current_user$fn__127265$fn__127266.invoke(session.clj:462)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:441)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:424)
	at metabase.server.middleware.session$bind_current_user$fn__127265.invoke(session.clj:461)
	at metabase.server.middleware.session$wrap_current_user_info$fn__127238.invoke(session.clj:385)
	at metabase.server.middleware.session$wrap_session_id$fn__127210.invoke(session.clj:261)
	at metabase.server.middleware.auth$wrap_static_api_key$fn__145513.invoke(auth.clj:32)
	at ring.middleware.cookies$wrap_cookies$fn__169353.invoke(cookies.clj:200)
	at metabase.server.middleware.misc$add_content_type$fn__121716.invoke(misc.clj:28)
j:77)	at metabase.server.middleware.misc$disable_streaming_buffering$fn__121742.invoke(misc.cl
	at ring.middleware.gzip$wrap_gzip$fn__169403.invoke(gzip.clj:86)
	at metabase.server.middleware.request_id$wrap_request_id$fn__146024.invoke(request_id.clj:9)
	at metabase.server.middleware.misc$bind_request$fn__121745.invoke(misc.clj:94)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__146047.invoke(ssl.clj:41)
	at clojure.lang.Var.invoke(Var.java:395)
	at metabase.server$async_proxy_handler$fn__119058.invoke(server.clj:77)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
tpChannel.java:501)pse.jetty.server.HttpChannel.handle(Ht
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
g.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
</details>

**Comment by piranha** [comment]
I've been thinking that maybe if we type `limit` with malli with could have a converter from a vector to a single value in such a case. So it could be almost a general solution (provided parameter is typed and not used raw).
