### ISSUE TITLE
Exception "Unknown type of ref" when using a division in Summarize of question

### ISSUE THREAD

**Issue by janfrederik** [metabase/metabase#45361]
### Describe the bug

When I execute a question (or metric) with a Custom Expression as Summarize like `Sum([MyField1]) / Sum([MyField2])`, the server logs show error: "Error saving query execution info", caused by exception "Unknown type of ref".

There is no error when just doing `Sum([MyField1])`or `Sum([MyField2])`.

`Sum([MyField2])` is non-zero.

### To Reproduce

1. Add the metabase internal database as database
2. New Question based on table `metabase_database`
3. Summarize: "Custom Expression": `Sum([id]) / Sum([id])`
4. Visualize

Result: the error appears in the log

![image](https://github.com/metabase/metabase/assets/18148910/4acc2a69-f81e-4fb2-b83c-69fa9d23139c)

### Logs

Browser log:
```
Cookie “_sp_root_domain_test_1720617153389” has been rejected for invalid domain. [index.module.js:496:17](webpack:///node_modules/@snowplow/browser-tracker-core/dist/index.module.js)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value\n {:lib/type :mbql/query,\n  :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n  :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value\n  {:lib/type :mbql/query,\n   :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n   :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value\n {:lib/type :mbql/query,\n  :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n  :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value\n  {:lib/type :mbql/query,\n   :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n   :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/mbql}], :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database],\n    :schema #object[Object [object Object]],\n    :value nil,\n    :type :malli.core/missing-key}\n   {:path [0 0 :stages 0 1 0 0 :mbql.stage/mbql],\n    :in [:stages 0], \n    :schema #object[Object [object Object]], \n    :value {:lib/type :mbql.stage/mbql}})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value {:lib/type :mbql/query, :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n" [core.cljs:4009:5](webpack:///target/cljs_release/cljs/core.cljs)
[metabase.lib.normalize] "Error normalizing pMBQL:\n{:value\n {:lib/type :mbql/query,\n  :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n  :lib/metadata #object[p [object Object]]},\n :schema #object[Object [object Object]],\n :explain\n {:schema #object[Object [object Object]],\n  :value\n  {:lib/type :mbql/query,\n   :stages [{:lib/type :mbql.stage/native, :template-tags {}, :native \"\"}],\n   :lib/metadata #object[p [object Object]]},\n  :errors\n  ({:path [0 0 :database],\n    :in [:database], \n    :schema #object[Object [object Object]], \n    :value nil, \n    :type :malli.core/missing-key})}}\n"
```

Server log:
```
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:35+02:00 DEBUG metabase.server.middleware.log GET /api/user/current 200 20.5 ms (10 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (2 idle, 0 queued) (99 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:35+02:00 DEBUG metabase.server.middleware.log GET /api/session/properties 200 20.4 ms (7 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (2 idle, 0 queued) (99 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:35+02:00 DEBUG metabase.server.middleware.log GET /api/collection/root 200 8.0 ms (2 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (2 idle, 0 queued) (99 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:35+02:00 DEBUG metabase.server.middleware.log GET /api/database 200 8.6 ms (1 DB calls) App DB connections: 0/15 Jetty threads: 8/50 (0 idle, 0 queued) (99 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:35+02:00 DEBUG metabase.server.middleware.log GET /api/bookmark 200 4.1 ms (1 DB calls) App DB connections: 1/15 Jetty threads: 8/50 (0 idle, 0 queued) (99 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:35+02:00 DEBUG metabase.server.middleware.log GET /api/collection/tree 200 24.3 ms (6 DB calls) App DB connections: 2/15 Jetty threads: 7/50 (1 idle, 0 queued) (100 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:35+02:00 DEBUG metabase.server.middleware.log GET /api/search 200 41.1 ms (5 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (1 idle, 0 queued) (100 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:36+02:00 DEBUG metabase.server.middleware.log GET /api/timeline 200 4.6 ms (3 DB calls) App DB connections: 2/15 Jetty threads: 7/50 (1 idle, 0 queued) (100 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:36+02:00 DEBUG metabase.server.middleware.log GET /api/search 200 59.5 ms (11 DB calls) App DB connections: 0/15 Jetty threads: 7/50 (1 idle, 0 queued) (100 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:36+02:00 DEBUG metabase.server.middleware.log POST /api/dataset/query_metadata 200 68.2 ms (18 DB calls) App DB connections: 1/15 Jetty threads: 6/50 (1 idle, 0 queued) (100 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:36+02:00 DEBUG metabase.server.middleware.log GET /api/dashboard/24 200 310.6 ms (57 DB calls) App DB connections: 0/15 Jetty threads: 6/50 (1 idle, 0 queued) (100 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:36+02:00 DEBUG metabase.server.middleware.log POST /api/dataset 202 [ASYNC: completed] 63.7 ms (16 DB calls) App DB connections: 1/15 Jetty threads: 4/50 (1 idle, 0 queued) (102 total active threads) Queries in flight: 0 (0 queued); postgres DB 3 connections: 0/2 (0 threads blocked) {:metabase-user-id 2}
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:36+02:00 ERROR metabase.query-processor.middleware.process-userland-query Error saving query execution info,clojure.lang.ExceptionInfo: Unknown type of ref {:ref [:sum {:lib/uuid "49484458-696c-4748-bc4c-3baac64dbb31"} [:field {:base-type :type/Integer, :lib/uuid "b99a66a0-e0c4-46ba-8233-207a7e7fedf9", :effective-type :type/Integer} 13884]]},	at metabase.lib.equality$find_matching_column.invokeStatic(equality.cljc:293),	at metabase.lib.equality$find_matching_column.invoke(equality.cljc:249),	at metabase.lib.equality$find_matching_column.invokeStatic(equality.cljc:274),	at metabase.lib.equality$find_matching_column.invoke(equality.cljc:249),	at metabase.lib.aggregation$aggregation_column.invokeStatic(aggregation.cljc:433),	at metabase.lib.aggregation$aggregation_column.invoke(aggregation.cljc:423),	at metabase.models.field_usage$aggregation__GT_field_usage.invokeStatic(field_usage.clj:38),	at metabase.models.field_usage$aggregation__GT_field_usage.invoke(field_usage.clj:36),	at metabase.models.field_usage$stage__GT_field_usages$fn__75606.invoke(field_usage.clj:77),	at clojure.core$keep$fn__8649.invoke(core.clj:7406),	at clojure.lang.LazySeq.sval(LazySeq.java:42),	at clojure.lang.LazySeq.seq(LazySeq.java:58),	at clojure.lang.RT.seq(RT.java:535),	at clojure.core$seq__5467.invokeStatic(core.clj:139),	at clojure.core$concat$cat__5560$fn__5561.invoke(core.clj:736),	at clojure.lang.LazySeq.sval(LazySeq.java:42),	at clojure.lang.LazySeq.seq(LazySeq.java:58),	at clojure.lang.RT.seq(RT.java:535),	at clojure.core$seq__5467.invokeStatic(core.clj:139),	at clojure.core$seq__5467.invoke(core.clj:139),	at metabase.query_processor.middleware.process_userland_query$save_execution_metadata_BANG__STAR_.invokeStatic(process_userland_query.clj:50),	at metabase.query_processor.middleware.process_userland_query$save_execution_metadata_BANG__STAR_.invoke(process_userland_query.clj:42),	at metabase.query_processor.middleware.process_userland_query$save_execution_metadata_BANG_$fn__75632.invoke(process_userland_query.clj:68),	at clojure.lang.AFn.run(AFn.java:22),	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source),	at java.base/java.util.concurrent.FutureTask.run(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source),	at java.base/java.lang.Thread.run(Unknown Source)
[5e2344d9-397b-49cb-9caa-9391fe864a5c] 2024-07-10T15:11:36+02:00 DEBUG metabase.server.middleware.log GET /api/database/3 200 11.0 ms (5 DB calls) App DB connections: 0/15 Jetty threads: 5/50 (1 idle, 0 queued) (102 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 2}
```

### Information about your Metabase installation

```
- Firefox 127.0.2
- Windows 11
- Postgres 14
- Metabase 0.50.11
- Metabase internal database: Postgres 14
```

### Severity

annoying

**Comment by mngr** [comment]
I'm unable to reproduce it when I just divide Sum([Id])/Sum(Id]) on the Accounts table.
So I guess the problem is either fixed or not in the division but rather something related to summing id's.
<img width="624" alt="Image" src="https://github.com/user-attachments/assets/137a7adb-9dcd-44fe-9b21-adca201d7664" />

**Comment by paoliniluis** [comment]
@janfrederik do you still see this in 52?

**Comment by janfrederik** [comment]
This has been resolved, indeed. Probably since the major changes in 52.
