### ISSUE TITLE
NormalModule.onModuleBuildFailed on v0.23.0

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#4541]
OS: macOS Sierra 10.12.3
Internal DB: MySQL
MB Version: 0.23.0

`yarn run dev` gives following error

```
$ yarn run dev
yarn run v0.21.3
$ yarn && concurrently --kill-others -p name -n 'backend,frontend' -c 'blue,green' 'lein ring server' 'yarn run build-hot' 
yarn install v0.21.3
$ ps -fp $PPID | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 2.79s.

yarn run v0.21.3

$ NODE_ENV=hot webpack --bail && NODE_ENV=hot webpack-dev-server --progress 
[frontend] webpack env: hot
[backend] 03-17 11:43:38 INFO metabase.util :: Loading Metabase...
[backend] 03-17 11:43:42 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
[frontend] Error
[frontend]     at NormalModule.onModuleBuildFailed (/Users/Vikram/Documents/code/metabase/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
[frontend]     at nextLoader (/Users/Vikram/Documents/code/metabase/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
[frontend]     at /Users/Vikram/Documents/code/metabase/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
[frontend]     at context.callback (/Users/Vikram/Documents/code/metabase/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
[frontend]     at /Users/Vikram/Documents/code/metabase/node_modules/babel-loader/lib/index.js:128:16
[frontend]     at /Users/Vikram/Documents/code/metabase/node_modules/babel-loader/lib/fs-cache.js:81:16
[frontend]     at ReadFileContext.callback (/Users/Vikram/Documents/code/metabase/node_modules/babel-loader/lib/fs-cache.js:15:14)
[frontend]     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:357:13)
[frontend] Error
[frontend]     at transpile (/Users/Vikram/Documents/code/metabase/node_modules/babel-loader/lib/index.js:61:13)
[frontend]     at /Users/Vikram/Documents/code/metabase/node_modules/babel-loader/lib/fs-cache.js:79:18
[frontend]     at ReadFileContext.callback (/Users/Vikram/Documents/code/metabase/node_modules/babel-loader/lib/fs-cache.js:15:14)
[frontend]     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:357:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[frontend] yarn run build-hot exited with code 1
--> Sending SIGTERM to other processes..
[backend] lein ring server exited with code null
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Already tried to no effect:
- https://github.com/kriasoft/react-starter-kit/issues/1100 - set `svgo:false` in webpack config

**Comment by VikramTiwari** [comment]
Still, present with the latest release.

**Comment by tlrobinson** [comment]
@VikramTiwari What version of Node are you using? And does `yarn run build` work?

**Comment by VikramTiwari** [comment]
@tlrobinson 
node: v7.7.3
npm: 4.1.2
yarn: v0.21.3
`yarn run build`: same error

**Comment by VikramTiwari** [comment]
Tried it on a debain based instance and still the same error, but some more insight, maybe. @tlrobinson Any idea what might be causing this?
![screen shot 2017-03-29 at 23 46 55](https://cloud.githubusercontent.com/assets/1330677/24491016/218f4f64-14da-11e7-8b75-20beca75520b.png)

**Comment by VikramTiwari** [comment]
Found the issue. During merge `frontend/src/metabase/admin/settings/selectors.js` file did not get merged properly. Closing.
