### ISSUE TITLE
Migrations fails during upgrade from 049.8 to 0.50.13

### ISSUE THREAD

**Issue by vterdunov** [metabase/metabase#45701]
### Describe the bug

Upgrade Metabase from 049.8  to 0.50.13 got the following error.

```
2024-07-17 06:29:16,168 INFO db.liquibase :: Running 55 migrations ...
2024-07-17 06:39:18,093 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v50.2024-02-26T22:15:54::noahmoss encountered an exception.
liquibase.exception.DatabaseException: An I/O error occurred while sending to the backend. [Failed SQL: (0) -- Insert table-level view-data permissions when necessary: when a group has
-- table-level data-access permissions, and some of the `no-self-service` rows
-- cannot be automatically migrated to `unrestricted` due to conflicts with
-- other groups
INSERT INTO
  data_permissions (
    group_id,
    perm_type,
    db_id,
    schema_name,
    table_id,
    perm_value
  )
SELECT
  dp.group_id,
  'perms/view-data' AS perm_type,
  dp.db_id,
  dp.schema_name,
  dp.table_id,
  CASE
    WHEN dp.perm_value = 'no-self-service'
    AND EXISTS (
      SELECT
        1
      FROM
        permissions_group_membership pgm
        JOIN (
          SELECT
            group_id,
            db_id,
            CAST(NULL AS INTEGER) AS table_id
          FROM
            connection_impersonations
          UNION
          SELECT
            group_id,
            db_id,
            CAST(NULL AS INTEGER) AS table_id
          FROM
            data_permissions
          WHERE
            perm_value = 'block'
            AND table_id IS NULL
          UNION
          SELECT
            group_id,
            CAST(NULL AS INTEGER) as db_id,
            table_id
          FROM
            sandboxes
        ) AS sp ON pgm.group_id = sp.group_id
      WHERE
        pgm.group_id <> dp.group_id
        AND (
          sp.db_id IS NULL
          OR sp.db_id = dp.db_id
        )
        AND (
          sp.table_id IS NULL
          OR sp.table_id = dp.table_id
        )
    ) THEN 'legacy-no-self-service'
    ELSE 'unrestricted'
  END AS perm_value
FROM
  data_permissions dp
WHERE
  dp.perm_type = 'perms/data-access'
  AND dp.table_id IS NOT NULL]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
        at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
        at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
        at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
        at liquibase.Scope.lambda$child$0(Scope.java:186)
        at liquibase.Scope.child(Scope.java:195)
        at liquibase.Scope.child(Scope.java:185)
        at liquibase.Scope.child(Scope.java:164)
        at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
        at liquibase.Scope.lambda$child$0(Scope.java:186)
        at liquibase.Scope.child(Scope.java:195)
        at liquibase.Scope.child(Scope.java:185)
        at liquibase.Scope.child(Scope.java:164)
        at liquibase.Scope.child(Scope.java:252)
        at liquibase.Scope.child(Scope.java:256)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
        at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)
        at liquibase.Scope.lambda$child$0(Scope.java:186)
        at liquibase.Scope.child(Scope.java:195)
        at liquibase.Scope.child(Scope.java:185)
        at liquibase.Scope.child(Scope.java:164)
        at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)
        at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
        at liquibase.command.CommandScope.execute(CommandScope.java:217)
        at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
        at liquibase.Scope.lambda$child$0(Scope.java:186)
        at liquibase.Scope.child(Scope.java:195)
        at liquibase.Scope.child(Scope.java:185)
        at liquibase.Scope.child(Scope.java:164)
        at liquibase.Liquibase.runInScope(Liquibase.java:1419)
        at liquibase.Liquibase.update(Liquibase.java:234)
        at liquibase.Liquibase.update(Liquibase.java:212)
        at liquibase.Liquibase.update(Liquibase.java:194)
        at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__44519.invoke(liquibase.clj:360)
        at metabase.db.liquibase$run_in_scope_locked$reify__44515.run(liquibase.clj:325)
        at liquibase.Scope.lambda$child$0(Scope.java:186)
        at liquibase.Scope.child(Scope.java:195)
        at liquibase.Scope.child(Scope.java:185)
        at liquibase.Scope.child(Scope.java:164)
        at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:318)
        at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:301)
        at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:349)
        at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:342)
        at metabase.db.setup$migrate_BANG_$fn__53455.invoke(setup.clj:84)
        at metabase.db.liquibase$do_with_liquibase$f_STAR___44456.invoke(liquibase.clj:140)
        at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:143)
        at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:131)
        at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)
        at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:149)
        at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:144)
        at metabase.db.setup$setup_db_BANG_$fn__53483$fn__53484.invoke(setup.clj:167)
        at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
        at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
        at metabase.db.setup$setup_db_BANG_$fn__53483.invoke(setup.clj:161)
        at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
        at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
        at metabase.db$setup_db_BANG_$fn__53508.invoke(db.clj:86)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:81)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:68)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:117)
        at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
        at metabase.core$init_BANG_.invokeStatic(core.clj:170)
        at metabase.core$init_BANG_.invoke(core.clj:165)
        at metabase.core$start_normally.invokeStatic(core.clj:182)
        at metabase.core$start_normally.invoke(core.clj:176)
        at metabase.core$entrypoint.invokeStatic(core.clj:215)
        at metabase.core$entrypoint.doInvoke(core.clj:209)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
        at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.bootstrap.main(Unknown Source)
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
        at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
        ... 86 more
Caused by: java.io.EOFException
        at org.postgresql.core.PGStream.receiveChar(PGStream.java:469)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2166)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
        ... 94 more

UPDATE SUMMARY
Run:                         55
Previously run:             295
Filtered out:                50
-------------------------------
Total change sets:          400


FILTERED CHANGE SETS SUMMARY
DBMS mismatch:               50

```

The `ERROR liquibase.changelog` error happened after 10 min migration stared. Probably timeout?

### To Reproduce

Change image in docker run command.

### Expected behavior

Migrations successfully finished

### Information about your Metabase installation

```JSON
- Metabase in docker on a VM
- Database Postgres 16.1 AWS RDS
```

### Severity

-

**Comment by noahmoss** [comment]
@vterdunov What's the size of your instance? Do you have a particularly large number of users, groups, DBs, or tables connected?

**Comment by vterdunov** [comment]
@noahmoss Hi I guess a small instance
VM -  2cpu 4GB Ram
AWS RDS Aurora Postgres 16.1 db.t4g.medium (4 vCPU 8GB RAM)
~73 users and 24 groups
35 Databases connected

**Comment by noahmoss** [comment]
@vterdunov Thanks. I'm trying to replicate...do you have an estimate of how many tables you have total in the DBs? You can run `select count(*) from metabase_database;` on your app DB to get an exact count, if you have access to it.

**Comment by vterdunov** [comment]
@noahmoss 
```
select count(*) from metabase_database;
```
35

**Comment by noahmoss** [comment]
@vterdunov Sorry, I mistyped. `select count(*) from metabase_table;` will return the total table count.

**Comment by vterdunov** [comment]
@noahmoss 17424

I guess can try another migration attempt if it's possible to increase the timeout. Probably for some reason VM or Postgres was on some load.

**Comment by noahmoss** [comment]
@vterdunov Can you give me a sense of what your permissions configuration looks like? I'm trying to replicate with a similar number of DBs & tables but I'm not seeing it timeout.

**Comment by vterdunov** [comment]
@noahmoss could you please clarify what kind of permissions do you mean? in terms of Postgres user?

**Comment by noahmoss** [comment]
@vterdunov No, your permissions configuration in Metabase. Assuming you're logged in as an admin, it's at `<site-url>/admin/permissions/data`

Is the "Create queries" permission set to the a single value for each DB in each group? Is it set to different values for different tables? Or a combination of both? Whatever details you could provide would be useful. It's possible that this migration has a hot spot that's triggered under specific circumstances but I haven't determined what those are yet.

**Comment by noahmoss** [comment]
Actually, think I might have just reproduced it.

**Comment by ilmarivikstrom** [comment]
Suffering from the same exact problem.

**Comment by noahmoss** [comment]
I believe there's a hot spot in the migration under specific circumstances (many tables with permissions set granularly) which can be mitigated with specific index. I have a fix which will be out in Metabase 50.14. 

If you want, you can apply these indexes manually and see if that fixes the timeouts:
```
CREATE INDEX idx_data_permissions_group_id_db_id_perm_value ON data_permissions(group_id, db_id, perm_value);
CREATE INDEX idx_data_permissions_group_id_db_id_table_id_perm_value ON data_permissions(group_id, db_id, table_id, perm_value);
```

If you try this, please let me know if you still see issues.

**Comment by vdubovets** [comment]
We had the same issue -> https://github.com/metabase/metabase/issues/45801

**Comment by noahmoss** [comment]
@vdubovets @ilmarivikstrom How many tables are on your instance? You can run `select count(*) from metabase_table;` to fetch the total count.

**Comment by vdubovets** [comment]
@noahmoss The table count is `77 247`

**Comment by GabrielBourget52** [comment]
I got a similar problem with my local setop, form 0.49 to 0.50.
I have 1 database

2024-07-19 14:39:04 liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v50.2024-01-10T03:27:29::noahmoss:
2024-07-19 14:39:04      Reason: liquibase.exception.DatabaseException: ERROR: constraint "fk_sandboxes_ref_permissions" of relation "sandboxes" does not exist [Failed SQL: (0) ALTER TABLE "public"."sandboxes" DROP CONSTRAINT "fk_sandboxes_ref_permissions"]

**Comment by noahmoss** [comment]
@GabrielBourget52 That's a separate issue which has already been fixed. Please upgrade to 0.50.13 instead of 0.50.0
