### ISSUE TITLE
java.lang.IllegalArgumentException: No implementation of method: :->temporal of protocol: #'metabase.sync.analyze.fingerprint.fingerprinters/ITemporalCoerceable found for class: java.lang.Boolean when fingerprinting mongodb

### ISSUE THREAD

**Issue by dragonsahead** [metabase/metabase#45722]
### Describe the bug

A very interesting log line in a mongodb fingerprint on our cloud

### To Reproduce

Check the ticket associated with this issue, you'll be able to see the log line exactly at 2024-07-17 13:30:13.748

### Expected behavior

We should not have any errors on the fingerprints

### Logs

```
2024-07-17 13:30:13.749	
	at java.base/java.lang.Thread.run(Unknown Source)



2024-07-17 13:30:13.749	
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2024-07-17 13:30:13.749	
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2024-07-17 13:30:13.749	
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2024-07-17 13:30:13.749	
	at clojure.lang.AFn.call(AFn.java:18)
2024-07-17 13:30:13.749	
	at clojure.lang.RestFn.invoke(RestFn.java:397)
2024-07-17 13:30:13.749	
	at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
2024-07-17 13:30:13.749	
	at clojure.core$apply.invokeStatic(core.clj:671)
2024-07-17 13:30:13.749	
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
2024-07-17 13:30:13.749	
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
2024-07-17 13:30:13.749	
	at clojure.lang.RestFn.invoke(RestFn.java:425)
2024-07-17 13:30:13.749	
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
2024-07-17 13:30:13.749	
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
2024-07-17 13:30:13.749	
	at clojure.core$apply.invokeStatic(core.clj:667)
2024-07-17 13:30:13.749	
	at clojure.lang.AFn.applyTo(AFn.java:144)
2024-07-17 13:30:13.749	
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
2024-07-17 13:30:13.749	
	at metabase.sync.concurrent$submit_task$fn__94647.invoke(concurrent.clj:23)
2024-07-17 13:30:13.749	
	at metabase.api.table$sync_unhidden_tables$fn__98932.invoke(table.clj:90)
2024-07-17 13:30:13.749	
	at metabase.sync$sync_table_BANG_.invoke(sync.clj:57)
2024-07-17 13:30:13.749	
	at metabase.sync$sync_table_BANG_.invokeStatic(sync.clj:61)
2024-07-17 13:30:13.749	
	at metabase.sync.analyze$analyze_table_BANG_.invoke(analyze.clj:76)
2024-07-17 13:30:13.749	
	at metabase.sync.analyze$analyze_table_BANG_.invokeStatic(analyze.clj:79)
2024-07-17 13:30:13.749	
	at metabase.sync.analyze.fingerprint$fingerprint_fields_BANG_.invoke(fingerprint.clj:194)
2024-07-17 13:30:13.749	
	at metabase.sync.analyze.fingerprint$fingerprint_fields_BANG_.invokeStatic(fingerprint.clj:200)
2024-07-17 13:30:13.749	
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:183)
2024-07-17 13:30:13.749	
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:190)
2024-07-17 13:30:13.749	
	at metabase.sync.analyze.fingerprint$fingerprint_fields_BANG_$fn__83413.invoke(fingerprint.clj:202)
2024-07-17 13:30:13.749	
	at metabase.sync.analyze.fingerprint$fingerprint_table_BANG_.invoke(fingerprint.clj:61)
2024-07-17 13:30:13.749	
	at metabase.sync.analyze.fingerprint$fingerprint_table_BANG_.invokeStatic(fingerprint.clj:84)
2024-07-17 13:30:13.749	
	at clojure.lang.MultiFn.invoke(MultiFn.java:252)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo$fn__123884.invoke(mongo.clj:337)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo$fn__123884.invokeStatic(mongo.clj:339)
2024-07-17 13:30:13.749	
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150)
2024-07-17 13:30:13.749	
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:158)
2024-07-17 13:30:13.749	
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150)
2024-07-17 13:30:13.749	
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:169)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo$fn__123884$fn__123885.invoke(mongo.clj:342)
2024-07-17 13:30:13.749	
	at metabase.db.metadata_queries$table_rows_sample.invoke(metadata_queries.clj:200)
2024-07-17 13:30:13.749	
	at metabase.db.metadata_queries$table_rows_sample.invokeStatic(metadata_queries.clj:218)
2024-07-17 13:30:13.749	
	at metabase.query_processor$process_query.invoke(query_processor.clj:291)
2024-07-17 13:30:13.749	
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:311)
2024-07-17 13:30:13.749	
	at clojure.lang.RestFn.invoke(RestFn.java:436)
2024-07-17 13:30:13.749	
	at metabase.query_processor.reducible$sync_qp$qp_STAR___63256.doInvoke(reducible.clj:153)
2024-07-17 13:30:13.749	
	at clojure.core$apply.invoke(core.clj:662)
2024-07-17 13:30:13.749	
	at clojure.core$apply.invokeStatic(core.clj:667)
2024-07-17 13:30:13.749	
	at clojure.lang.AFn.applyTo(AFn.java:144)
2024-07-17 13:30:13.749	
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
2024-07-17 13:30:13.749	
	at metabase.query_processor.reducible$async_qp$qp_STAR___63244.invoke(reducible.clj:132)
2024-07-17 13:30:13.749	
	at metabase.query_processor.reducible$async_qp$qp_STAR___63244$thunk__63246.invoke(reducible.clj:126)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__72540.invoke(enterprise.clj:103)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.enterprise$fn__72529$handle_audit_app_internal_queries__72530$fn__72532.invoke(enterprise.clj:96)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.normalize_query$normalize$fn__72894.invoke(normalize_query.clj:38)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_database$fn__72589.invoke(resolve_database_and_driver.clj:60)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.store$initialize_store$fn__67752.invoke(store.clj:13)
2024-07-17 13:30:13.749	
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150)
2024-07-17 13:30:13.749	
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:164)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.store$initialize_store$fn__67752$fn__67753.invoke(store.clj:14)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72592.invoke(resolve_database_and_driver.clj:76)
2024-07-17 13:30:13.749	
	at metabase.driver$do_with_driver.invoke(driver.clj:92)
2024-07-17 13:30:13.749	
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:97)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.resolve_database_and_driver$resolve_driver_and_database_local_values$fn__72592$fn__72596.invoke(resolve_database_and_driver.clj:77)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__67125.invoke(fetch_source_query.clj:303)
2024-07-17 13:30:13.749	
	at metabase.query_processor$fn__73849$combined_pre_process__73850$combined_pre_process_STAR___73851.invoke(query_processor.clj:259)
2024-07-17 13:30:13.749	
	at metabase.query_processor$fn__73849$combined_post_process__73854$combined_post_process_STAR___73855.invoke(query_processor.clj:262)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__71944.invoke(mbql_to_native.clj:24)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__72512.invoke(enterprise.clj:64)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.enterprise$check_download_permissions_middleware$fn__72502.invoke(enterprise.clj:51)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__67028.invoke(permissions.clj:140)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___72681.invoke(cache.clj:229)
2024-07-17 13:30:13.749	
	at metabase.query_processor.reducible$identity_qp.invoke(reducible.clj:36)
2024-07-17 13:30:13.749	
	at metabase.query_processor.reducible$identity_qp.invokeStatic(reducible.clj:39)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context$runf.invoke(context.clj:40)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context$runf.invokeStatic(context.clj:46)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context.default$default_runf.invoke(default.clj:42)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context.default$default_runf.invokeStatic(default.clj:44)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context$executef.invoke(context.clj:49)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context$executef.invokeStatic(context.clj:60)
2024-07-17 13:30:13.749	
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo$fn__123872.invoke(mongo.clj:318)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo$fn__123872.invokeStatic(mongo.clj:320)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo.connection$do_with_mongo_client.invoke(connection.clj:85)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo.connection$do_with_mongo_client.invokeStatic(connection.clj:89)
2024-07-17 13:30:13.749	
	at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154)
2024-07-17 13:30:13.749	
	at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:165)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo.connection$do_with_mongo_client$fn__120057.invoke(connection.clj:94)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo$fn__123872$f__120066__auto____123873.invoke(mongo.clj:321)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo.execute$execute_reducible_query.invoke(execute.clj:182)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo.execute$execute_reducible_query.invokeStatic(execute.clj:207)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo.execute$reduce_results.invoke(execute.clj:171)
2024-07-17 13:30:13.749	
	at metabase.driver.mongo.execute$reduce_results.invokeStatic(execute.clj:177)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context.default$default_runf$respond_STAR___50910.invoke(default.clj:45)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context$reducef.invoke(context.clj:63)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context$reducef.invokeStatic(context.clj:70)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context.default$default_reducef.invoke(default.clj:25)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context.default$default_reducef.invokeStatic(default.clj:33)
2024-07-17 13:30:13.749	
	at metabase.query_processor.context.default$default_reducef$fn__50906.invoke(default.clj:34)
2024-07-17 13:30:13.749	
	at clojure.core$transduce.invoke(core.clj:6934)
2024-07-17 13:30:13.749	
	at clojure.core$transduce.invokeStatic(core.clj:6943)
2024-07-17 13:30:13.749	
	at clojure.core$transduce.invokeStatic(core.clj:6947)
2024-07-17 13:30:13.749	
	at metabase.query_processor.reducible$reducible_rows$reify__63259.reduce(reducible.clj:177)
2024-07-17 13:30:13.749	
	at metabase.query_processor.middleware.add_rows_truncated$add_rows_truncated_xform$fn__71615.invoke(add_rows_truncated.clj:34)
2024-07-17 13:30:13.749	
	at clojure.core$take$fn__5974$fn__5975.invoke(core.clj:2894)
2024-07-17 13:30:13.749	
	at redux.core$post_complete$fn__62630.invoke(core.cljc:15)
2024-07-17 13:30:13.748	
	at metabase.sync.analyze.fingerprint.fingerprinters$col_wise$fn__62990.invoke(fingerprinters.clj:31)
2024-07-17 13:30:13.748	
	at clojure.core$mapv.invoke(core.clj:6971)
2024-07-17 13:30:13.748	
	at clojure.core$mapv.invokeStatic(core.clj:6971)
2024-07-17 13:30:13.748	
	at clojure.core$into.invokeStatic(core.clj:6959)
2024-07-17 13:30:13.748	
	at clojure.core$reduce.invokeStatic(core.clj:6887)
2024-07-17 13:30:13.748	
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
2024-07-17 13:30:13.748	
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
2024-07-17 13:30:13.748	
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
2024-07-17 13:30:13.748	
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
2024-07-17 13:30:13.748	
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
2024-07-17 13:30:13.748	
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
2024-07-17 13:30:13.748	
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:169)
2024-07-17 13:30:13.748	
	at clojure.core$next__5451.invokeStatic(core.clj:64)
2024-07-17 13:30:13.748	
	at clojure.lang.RT.next(RT.java:713)
2024-07-17 13:30:13.748	
	at clojure.lang.Cons.next(Cons.java:39)
2024-07-17 13:30:13.748	
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
2024-07-17 13:30:13.748	
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
2024-07-17 13:30:13.748	
	at clojure.core$map$fn__5942.invoke(core.clj:2783)
2024-07-17 13:30:13.748	
	at metabase.sync.analyze.fingerprint.fingerprinters$col_wise$fn__62990$fn__62995.invoke(fingerprinters.clj:34)
2024-07-17 13:30:13.748	
	at metabase.sync.analyze.fingerprint.fingerprinters$with_error_handling$fn__63027.invoke(fingerprinters.clj:84)
2024-07-17 13:30:13.748	
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:183)
2024-07-17 13:30:13.748	
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:190)
2024-07-17 13:30:13.748	
	at metabase.sync.analyze.fingerprint.fingerprinters$with_error_handling$fn__63027$fn__63032.invoke(fingerprinters.clj:84)
2024-07-17 13:30:13.748	
	at redux.core$post_complete$fn__62630.invoke(core.cljc:15)
2024-07-17 13:30:13.748	
	at redux.core$juxt$fn__62636.invoke(core.cljc:34)
2024-07-17 13:30:13.748	
	at clojure.core$mapv.invoke(core.clj:6971)
2024-07-17 13:30:13.748	
	at clojure.core$mapv.invokeStatic(core.clj:6971)
2024-07-17 13:30:13.748	
	at clojure.core$into.invokeStatic(core.clj:6959)
2024-07-17 13:30:13.748	
	at clojure.core$reduce.invokeStatic(core.clj:6887)
2024-07-17 13:30:13.748	
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
2024-07-17 13:30:13.748	
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
2024-07-17 13:30:13.748	
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
2024-07-17 13:30:13.748	
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
2024-07-17 13:30:13.748	
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
2024-07-17 13:30:13.748	
	at clojure.lang.RT.seq(RT.java:535)
2024-07-17 13:30:13.748	
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
2024-07-17 13:30:13.748	
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
2024-07-17 13:30:13.748	
	at clojure.core$map$fn__5939.invoke(core.clj:2777)
2024-07-17 13:30:13.748	
	at redux.core$juxt$fn__62636$fn__62641.invoke(core.cljc:37)
2024-07-17 13:30:13.748	
	at redux.core$post_complete$fn__62630.invoke(core.cljc:15)
2024-07-17 13:30:13.748	
	at clojure.core$map$fn__5931$fn__5932.invoke(core.clj:2759)
2024-07-17 13:30:13.748	
	at metabase.sync.analyze.fingerprint.fingerprinters$fn__63085$G__63080__63090.invoke(fingerprinters.clj:189)
2024-07-17 13:30:13.748	
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:576)
2024-07-17 13:30:13.748	
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:584)
2024-07-17 13:30:13.748	
java.lang.IllegalArgumentException: No implementation of method: :->temporal of protocol: #'metabase.sync.analyze.fingerprint.fingerprinters/ITemporalCoerceable found for class: java.lang.Boolean
2024-07-17 13:30:13.748	
2024-07-17 13:30:13,748 WARN sync.util :: Error generating fingerprint for Field 1062 ''lastSessionTime''
```

### Information about your Metabase installation

```JSON
v49
```

### Severity

P2

### Additional context

NA

**Comment by rileythomp** [comment]
@paoliniluis What's the ticket associated with the issue?

**Comment by rileythomp** [comment]
Likely related to https://github.com/metabase/metabase/issues/59942. Trying to reproduce with the same steps but using `{tricky: true}` instead of `{tricky: "I am long string"}` didn't cause fingerprinting to fail though, the boolean was interpreted as epoch 0
