### ISSUE TITLE
Migrations to v0.50.13 fail 

### ISSUE THREAD

**Issue by leopasta-enable** [metabase/metabase#45795]
### Describe the bug

When upgrading from  v0.50.7 to v0.50.13, metabase startup fails while applying Liquibase migration and continues in a loop.

### Logs

```
" 2024-07-18 08:23:29,272 INFO db.setup :: Running Database Migrations...

"
" 2024-07-18 08:23:29,272 INFO db.setup :: Setting up Liquibase...

"
" 2024-07-18 08:23:30,237 INFO db.setup :: Liquibase is ready.

"
" 2024-07-18 08:23:30,238 INFO db.liquibase :: Checking if Database has unrun migrations...

"
" 2024-07-18 08:23:32,580 INFO db.liquibase :: Database has unrun migrations. Checking if migration lock is taken...

"
" 2024-07-18 08:23:32,715 INFO db.liquibase :: No migration lock found.

"
" 2024-07-18 08:23:32,716 INFO db.liquibase :: Migration lock acquired.

"
" 2024-07-18 08:23:33,762 INFO db.liquibase :: Running 15 migrations ...

"
" 2024-07-18 08:23:35,283 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:07::calherries encountered an exception.

"
" liquibase.exception.DatabaseException: ERROR: syntax error at or near ""(""

"
"   Position: 87 [Failed SQL: (0) ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (

"
"   CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END

"
" ) STORED]

"
" 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)

"
" 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)

"
" 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)

"
" 	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)

"
" 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)

"
" 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)

"
" 	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)

"
" 	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)

"
" 	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)

"
" 	at liquibase.Scope.lambda$child$0(Scope.java:186)

"
" 	at liquibase.Scope.child(Scope.java:195)

"
" 	at liquibase.Scope.child(Scope.java:185)

"
" 	at liquibase.Scope.child(Scope.java:164)

"
" 	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)

"
" 	at liquibase.Scope.lambda$child$0(Scope.java:186)

"
" 	at liquibase.Scope.child(Scope.java:195)

"
" 	at liquibase.Scope.child(Scope.java:185)

"
" 	at liquibase.Scope.child(Scope.java:164)

"
" 	at liquibase.Scope.child(Scope.java:252)

"
" 	at liquibase.Scope.child(Scope.java:256)

"
" 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)

"
" 	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)

"
" 	at liquibase.Scope.lambda$child$0(Scope.java:186)

"
" 	at liquibase.Scope.child(Scope.java:195)

"
" 	at liquibase.Scope.child(Scope.java:185)

"
" 	at liquibase.Scope.child(Scope.java:164)

"
" 	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)

"
" 	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)

"
" 	at liquibase.command.CommandScope.execute(CommandScope.java:217)

"
" 	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)

"
" 	at liquibase.Scope.lambda$child$0(Scope.java:186)

"
" 	at liquibase.Scope.child(Scope.java:195)

"
" 	at liquibase.Scope.child(Scope.java:185)

"
" 	at liquibase.Scope.child(Scope.java:164)

"
" 	at liquibase.Liquibase.runInScope(Liquibase.java:1419)

"
" 	at liquibase.Liquibase.update(Liquibase.java:234)

"
" 	at liquibase.Liquibase.update(Liquibase.java:212)

"
" 	at liquibase.Liquibase.update(Liquibase.java:194)

"
" 	at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__44519.invoke(liquibase.clj:360)

"
" 	at metabase.db.liquibase$run_in_scope_locked$reify__44515.run(liquibase.clj:325)

"
" 	at liquibase.Scope.lambda$child$0(Scope.java:186)

"
" 	at liquibase.Scope.child(Scope.java:195)

"
" 	at liquibase.Scope.child(Scope.java:185)

"
" 	at liquibase.Scope.child(Scope.java:164)

"
" 	at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:318)

"
" 	at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:301)

"
" 	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:349)

"
" 	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:342)

"
" 	at metabase.db.setup$migrate_BANG_$fn__53455.invoke(setup.clj:84)

"
" 	at metabase.db.liquibase$do_with_liquibase$f_STAR___44456.invoke(liquibase.clj:140)

"
" 	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:143)

"
" 	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:131)

"
" 	at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)

"
" 	at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)

"
" 	at clojure.lang.RestFn.invoke(RestFn.java:425)

"
" 	at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:149)

"
" 	at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:144)

"
" 	at metabase.db.setup$setup_db_BANG_$fn__53483$fn__53484.invoke(setup.clj:167)

"
" 	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)

"
" 	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)

"
" 	at metabase.db.setup$setup_db_BANG_$fn__53483.invoke(setup.clj:161)

"
" 	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)

"
" 	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)

"
" 	at metabase.db$setup_db_BANG_$fn__53508.invoke(db.clj:86)

"
" 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:81)

"
" 	at metabase.db$setup_db_BANG_.doInvoke(db.clj:68)

"
" 	at clojure.lang.RestFn.invoke(RestFn.java:421)

"
" 	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:117)

"
" 	at metabase.core$init_BANG__STAR_.invoke(core.clj:98)

"
" 	at metabase.core$init_BANG_.invokeStatic(core.clj:170)

"
" 	at metabase.core$init_BANG_.invoke(core.clj:165)

"
" 	at metabase.core$start_normally.invokeStatic(core.clj:182)

"
" 	at metabase.core$start_normally.invoke(core.clj:176)

"
" 	at metabase.core$entrypoint.invokeStatic(core.clj:215)

"
" 	at metabase.core$entrypoint.doInvoke(core.clj:209)

"
" 	at clojure.lang.RestFn.invoke(RestFn.java:397)

"
" 	at clojure.lang.AFn.applyToHelper(AFn.java:152)

"
" 	at clojure.lang.RestFn.applyTo(RestFn.java:132)

"
" 	at clojure.lang.Var.applyTo(Var.java:705)

"
" 	at clojure.core$apply.invokeStatic(core.clj:667)

"
" 	at clojure.core$apply.invoke(core.clj:662)

"
" 	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)

"
" 	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)

"
" 	at clojure.lang.RestFn.invoke(RestFn.java:397)

"
" 	at clojure.lang.AFn.applyToHelper(AFn.java:152)

"
" 	at clojure.lang.RestFn.applyTo(RestFn.java:132)

"
" 	at metabase.bootstrap.main(Unknown Source)

"
" Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near ""(""

"
"   Position: 87

"
" 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)

"
" 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)

"
" 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)

"
" 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)

"
" 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)

"
" 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)

"
" 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)

"
" 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)

"
" 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)

"
" 	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)

"
" 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)

"
" 	... 86 more

"
" 

"
" UPDATE SUMMARY

"
" Run:                         15

"
" Previously run:             335

"
" Filtered out:                50

"
" -------------------------------

"
" Total change sets:          400

"
```

### Information about your Metabase installation

```JSON
PostgreSQL 11.22
Metabase: v0.50.13
Docker image: metabase/metabase:latest
```

### Severity

blocking your usage of Metabase entirely

**Comment by ilmarivikstrom** [comment]
Suffering from the same exact problem.

**Comment by qnkhuat** [comment]
Please upgrade to postgres 12 or above. We no longer support version 11 as it's already end of life
