### ISSUE TITLE
Redshift sync can return stale metadata for a short amount of time after tables are deleted, or can fail completely

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#45874]
See this Slack thread https://metaboat.slack.com/archives/C5XHN8GLW/p1721339724075889

Redshift `describe-database` seems to sometimes return tables that were recently deleted. This has been causing test flakes for a while, since we then attempt to sync that table that no longer exists and `describe-table` on it fails.

We had an old hack in the code prior to my test data loading PR #45268 that disabled table deletion in tests for Redshift. I took that out because it broke a lot of stuff now that we don't destroy and recreate the test data a dozen times in test runs. In #45873 I introduced a new hack to enable normal robust sync behavior so sync should still complete normally even if a specific `describe-table` call fails.

Neither the old hack nor the new hack really address the fundamental root issue tho which is that Redshift sync is returning stale metadata for some unknown reason. We should try to figure out why this is the case and see if we can prevent it from happening. Is the query getting cached upstream? 

This is a pretty low-priority issue since it's probably not a problem in real life since we use the robust sync behavior in prod and timing seems to have to be pretty tight between dropping a table and running sync, but we should still look into this issue and make sure we're not inadvertently enabling query caching for sync metadata queries or anything like that. And removing the hack from #45873 will be nice.

**Comment by camsaul** [comment]
It seems like Redshift sync can actually fail entirely sometimes -- `driver/describe-database` can fail if there are recently deleted tables, for some reason. For example

https://github.com/metabase/metabase/actions/runs/10038716376/job/27748689824#step:3:1431

```
[CLI-agent-send-off-pool-22] ERROR metabase.sync.fetch-metadata - Error while fetching metdata with 'db-metadata'
com.amazon.redshift.util.RedshiftException: ERROR: relation "2024_07_22_13d160b0_08a1_4a12_b85d_2c7348823961_schema.mwnpmfiotgmmwsjmldze" does not exist
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2648) ~[redshift-jdbc42-2.1.0.28.jar:?]
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2295) ~[redshift-jdbc42-2.1.0.28.jar:?]
	at com.amazon.redshift.core.v3.QueryExecutorImpl.access$000(QueryExecutorImpl.java:82) ~[redshift-jdbc42-2.1.0.28.jar:?]
	at com.amazon.redshift.core.v3.QueryExecutorImpl$RingBufferThread.run(QueryExecutorImpl.java:3128) ~[redshift-jdbc42-2.1.0.28.jar:?]
```

not clear where the rest of the stacktrace is, but it's definitely triggered by this code in `metabase.sync.fetch-metadata`

```clj
(mu/defn db-metadata :- i/DatabaseMetadata
  "Get basic Metadata about a `database` and its Tables. Doesn't include information about the Fields."
  [database :- i/DatabaseInstance]
  (log-if-error "db-metadata"
    (driver/describe-database (driver.u/database->driver database) database)))
```

**Comment by camsaul** [comment]
Here's a way to reliably reproduce Redshift sync failures

```clj
(ns metabase.driver.redshift-test ...)

...

;;; NOCOMMIT do not merge
(defn reproduce-redshift-sync-failures []
  (mt/test-driver :redshift
    ;; make sure test data is loaded
    (mt/db)
    ;; create a DIFFERENT schema than our unique-session-schema to fill with trash asynchronously
    (let [do-with-connection (fn [f]
                               (sql-jdbc.execute/do-with-connection-with-options
                                :redshift
                                (sql-jdbc.conn/connection-details->spec :redshift @redshift.test/db-connection-details)
                                {:write? true}
                                f))
          schema             (str (redshift.test/unique-session-schema) "_2")]
      (locking println (println "UNIQUE SESSION SCHEMA =" (redshift.test/unique-session-schema)))
      (try
        (do-with-connection
         (fn [^java.sql.Connection conn]
           (with-open [stmt (.createStatement conn)]
             (.execute stmt (format "CREATE SCHEMA IF NOT EXISTS \"%s\";" schema)))))
        ;; now asynchronously load a bunch of trash into the schema
        (let [fut (future
                    (do-with-connection
                     (fn [^java.sql.Connection conn]
                       (with-open [stmt (.createStatement conn)]
                         (dotimes [_ 100]
                           (let [table (u/lower-case-en (mt/random-name))]
                             (locking println (println "CREATING AND DROPPING" schema table))
                             (.execute stmt (format "CREATE TABLE \"%s\".\"%s\" (id INTEGER);" schema table))
                             (.execute stmt (format "DROP TABLE \"%s\".\"%s\";" schema table))))))))]
          (try
            ;; now run sync a bunch of times and make sure it completes ok.
            (dotimes [i 100]
              (locking println (println "Sync #" i))
              (let [sync-tables (:tables (driver/describe-database :redshift (mt/db)))]
                (doseq [{sync-table-name :name, :as synced-table} sync-tables]
                  (testing (format "\nsynced table: %s" (u/pprint-to-str synced-table))
                    (is (or (str/starts-with? sync-table-name "test_data_")
                            (= sync-table-name "extsales")
                            (#{"ioczvlzuryxmervumwrn" "umcwdqwjjaagvmrgrdhi"} sync-table-name)))))))
            (finally
              ;; cancel the async trash-loading future if it's still running.
              (future-cancel fut))))
        (finally
          ;; clean up after ourselves and drop the test schema.
          (do-with-connection
           (fn [^java.sql.Connection conn]
             (with-open [stmt (.createStatement conn)]
               (.execute stmt (format "DROP SCHEMA \"%s\";" schema))))))))))
```

**Comment by camsaul** [comment]
I don't know if there's a problem with the query used to power Redshift sync we added in https://github.com/metabase/metabase/pull/41068 or Redshift is just being terrible again.

Maybe we can update the Redshift sync code to use the schema inclusion and exclusion patterns in the query itself instead of fetching every single table in the DB and then filtering them out client-side and maybe that would improve things
