### ISSUE TITLE
`java.lang.NegativeArraySizeException` when running `migrate-query-executions` for 0.23.0

### ISSUE THREAD

**Issue by leomelzer** [metabase/metabase#4589]
- Your databases: Postgres
- Metabase version: 0.23.0
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

Hi all,
we just encountered an issue when upgrading from 0.22.0 to 0.23.0: Running the data migration [`migrate-query-executions`](https://github.com/metabase/metabase/blob/master/src/metabase/db/migrations.clj#L335) results in an `java.lang.NegativeArraySizeException`. I'm not sure whether this could be a problem with our setup or existing data. Can I somehow find offending entries in the `query_queryexecution` table myself? 

Log / Stacktrace:

```
03-22 21:12:03 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
03-22 21:12:04 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
03-22 21:12:04 INFO db.migrations :: Running data migration 'migrate-query-executions'...
java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.NegativeArraySizeException
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)
	at com.mchange.v2.c3p0.impl.NewPooledConnection.handleThrowable(NewPooledConnection.java:369)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:93)
	at clojure.java.jdbc$db_query_with_resultset$run_query_with_params__1893.invoke(jdbc.clj:831)
	at clojure.java.jdbc$db_query_with_resultset.invokeStatic(jdbc.clj:850)
	at clojure.java.jdbc$db_query_with_resultset.invoke(jdbc.clj:818)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:874)
	at clojure.java.jdbc$query.invoke(jdbc.clj:854)
	at toucan.db$query.invokeStatic(db.clj:237)
	at toucan.db$query.doInvoke(db.clj:233)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$simple_select.invokeStatic(db.clj:301)
	at toucan.db$simple_select.invoke(db.clj:290)
	at toucan.db$select.invokeStatic(db.clj:538)
	at toucan.db$select.doInvoke(db.clj:532)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at metabase.db.migrations$migrate_query_executions.invokeStatic(migrations.clj:365)
	at metabase.db.migrations$migrate_query_executions.invoke(migrations.clj:361)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:53)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:44)
	at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:72)
	at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:66)
	at clojure.lang.Var.invoke(Var.java:375)
	at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:355)
	at metabase.db$run_data_migrations_BANG_.invoke(db.clj:350)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:367)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:357)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:115)
	at metabase.core$init_BANG_.invoke(core.clj:95)
	at metabase.core$start_normally.invokeStatic(core.clj:198)
	at metabase.core$start_normally.invoke(core.clj:192)
	at metabase.core$_main.invokeStatic(core.clj:290)
	at metabase.core$_main.doInvoke(core.clj:285)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: java.lang.NegativeArraySizeException
	at org.postgresql.core.PGStream.ReceiveTupleV3(PGStream.java:372)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1895)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	... 35 more
03-22 21:12:54 ERROR metabase.core :: Metabase Initialization FAILED:  An SQLException was provoked by the following failure: java.lang.NegativeArraySizeException
03-22 21:12:54 INFO metabase.core :: Metabase Shutting Down ...
03-22 21:12:54 INFO metabase.core :: Metabase Shutdown COMPLETE
State changed from up to crashed
State changed from crashed to starting
```

Anyone else running in this issue? Can I somehow force it to output the actual query which was attempted?
Happy to provide more details if needed.
Thanks a lot!

Leo

**Comment by camsaul** [comment]
Yikes. No idea where this `NegativeArraySizeException` is coming from but it looks like it's happening when pulling rows from the `query_queryexecution` table. So there's probably some weird/invalid data in there 😳 

Not ideal but migrating the query execution log isn't critical so you could [`TRUNCATE`](https://www.postgresql.org/docs/9.6/static/sql-truncate.html) that table and re-launch Metabase to get things working again.

**Comment by leomelzer** [comment]
@camsaul Thanks for the fast reply, that did it. Thanks for making Metabase greater with every release!
