### ISSUE TITLE
Upgrade from 0.50.10 to 0.50.13 failed with failing migration

### ISSUE THREAD

**Issue by sanel** [metabase/metabase#45894]
### Describe the bug

After downloading the latest 0.50.13 version and tried to upgrade our 0.50.10 version, it failed with failing migration. 

### Expected behavior

1. Have 0.50.10 running
2. Download and install 0.50.13
3. Start it, it will fail with provided logs.

### Logs

```
 Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "("
   Position: 87
         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
         at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
         at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
         at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
         at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
         at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
         ... 86 more
 UPDATE SUMMARY
 Run:                          3
 Previously run:             347
 Filtered out:                50
 -------------------------------
 Total change sets:          400
 FILTERED CHANGE SETS SUMMARY
 DBMS mismatch:               50
 2024-07-20 08:48:43,688 ERROR metabase.core :: Metabase Initialization FAILED
 liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:07::calherries:
      Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "("
   Position: 87 [Failed SQL: (0) ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (
   CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END
 ) STORED]
         at liquibase.command.CommandScope.execute(CommandScope.java:253)
         at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
         at liquibase.Scope.lambda$child$0(Scope.java:186)
...

 Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:07::calherries:
      Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "("
   Position: 87 [Failed SQL: (0) ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (
   CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END
 ) STORED]
         at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:151)
         at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)
         at liquibase.Scope.lambda$child$0(Scope.java:186)
         at liquibase.Scope.child(Scope.java:195)
         at liquibase.Scope.child(Scope.java:185)
         at liquibase.Scope.child(Scope.java:164)
         at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)
         at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
         at liquibase.command.CommandScope.execute(CommandScope.java:217)
         ... 58 more
 Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:07::calherries:
      Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "("
   Position: 87 [Failed SQL: (0) ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (
   CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END
 ) STORED]
...
 Caused by: liquibase.exception.DatabaseException: ERROR: syntax error at or near "("
   Position: 87 [Failed SQL: (0) ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (
   CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END
 ) STORED]
         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
         at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
         at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
         at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
         at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
         at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
         ... 81 more
 Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "("
   Position: 87
         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
         at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
         at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
         at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
         at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
         at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
         ... 86 more
 2024-07-20 08:48:43,692 INFO metabase.core :: Metabase Shutting Down ...
 2024-07-20 08:48:43,693 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
 2024-07-20 08:48:43,701 WARN db.liquibase :: ()
 2024-07-20 08:48:43,702 INFO metabase.core :: Metabase Shutdown COMPLETE
 metabase.service: Main process exited, code=exited, status=1/FAILURE
 metabase.service: Unit entered failed state.
 metabase.service: Failed with result 'exit-code'.
```

### Information about your Metabase installation

```JSON
- Tested on 126.0.6478.182 (Official Build, ungoogled-chromium) (64-bit)
- JDK: 126.0.6478.182 (Official Build, ungoogled-chromium) (64-bit)
- Postgres 10.17-1.pgdg16.04+1
- Ubuntu 16.04.7 LTS
```

### Severity

Unable to migrate to the latest version

### Additional context

Downgrade to 0.50.10 for now. Maybe a dumb question, is minimal required Postgres version changed? I saw psql errors like this when newer psql syntax was used on older Postgres version, but I might be wrong.

**Comment by perivamsi** [comment]
We support postgres 12 and above

https://endoflife.date/postgresql

**Comment by paoliniluis** [comment]
@sanel please move to postgres v12 at least or better, to v16

**Comment by sanel** [comment]
@perivamsi @paoliniluis thank you guys for your fast reply. I'll plan for migration and re-open this ticket if I get the same issue. Cheers!
