### ISSUE TITLE
If `driver/describe-database` throws an error, `sync/sync-database!` does not handle it correctly

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#45948]
So it looks like `metabase.sync.sync-metadata/sync-db-metadata!` can return either an instance of a `Throwable` or a map (this seems to be on purpose since `metabase.sync.util/do-with-error-handling` has that logic, however calling code assumes it always returns a map and triggers a different error that makes logs confusing

https://github.com/metabase/metabase/blob/89dc03f2c747f579dceda8e4624509b697d0339a/src/metabase/sync.clj#L52

you can see that happening in this test run https://github.com/metabase/metabase/actions/runs/10038716376/job/27748689824#step:3:1397

```
[main] ERROR metabase.test.data.impl.get-or-create - Failed to sync test database "diff-time-zones-cases": Invalid output: ["invalid type, got: #error {\n :cause \"class com.amazon.redshift.util.RedshiftException cannot be cast to class clojure.lang.Associative (com.amazon.redshift.util.RedshiftException and clojure.lang.Associative are in unnamed module of loader 'app')\"\n :via\n [{:type java.lang.ClassCastException\n   :message \"class com.amazon.redshift.util.RedshiftException cannot be cast to class clojure.lang.Associative (com.amazon.redshift.util.RedshiftException and clojure.lang.Associative are in unnamed module of loader 'app')\"\n   :at [clojure.lang.RT assoc \"RT.java\" 827]}]\n :trace\n [[clojure.lang.RT assoc \"RT.java\" 827]\n  [clojure.core$assoc__5481 invokeStatic \"core.clj\" 193]\n  [clojure.core$assoc__5481 invoke \"core.clj\" 192]\n  [metabase.sync$fn__117877$_AMPERSAND_f__117879$fn__117881 invoke \"sync.clj\" 52]\n  [metabase.sync.util$do_with_error_handling invokeStatic \"util.clj\" 188]\n  [metabase.sync.util$do_with_error_handling invoke \"util.clj\" 181]\n  [clojure.core$partial$fn__5910 invoke \"core.clj\" 2647]\n  [metabase.driver$eval76273$fn__76274 invoke \"driver.clj\" 884]\n  [clojure.lang.MultiFn invoke \"MultiFn.java\" 239]\n  [metabase.sync.util$sync_in_context$fn__82219 invoke \"util.clj\" 164]\n  [metabase.sync.util$with_db_logging_disabled$fn__82216 invoke \"util.clj\" 156]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \"util.clj\" 129]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \"util.clj\" 123]\n  [metabase.sync.util$with_start_and_finish_logging$fn__82203 invoke \"util.clj\" 141]\n  [metabase.sync.util$fn__82190$_AMPERSAND_f__82191$fn__82195 invoke \"util.clj\" 115]\n  [metabase.sync.util$with_duplicate_ops_prevented$fn__82180 invoke \"util.clj\" 87]\n  [metabase.sync.util$fn__82238$_AMPERSAND_f__82239 invoke \"util.clj\" 213]\n  [metabase.sync.util$fn__82238$fn__82241 invoke \"util.clj\" 207]\n  [metabase.sync$fn__117877$_AMPERSAND_f__117879 invoke \"sync.clj\" 51]\n  [metabase.sync$fn__117877$fn__117885 invoke \"sync.clj\" 37]\n  [metabase.test.data.impl.get_or_create$sync_newly_created_database_BANG_$fn__147190$fn__147194$fn__147195 invoke \"get_or_create.clj\" 137]\n  [metabase.test.data.impl.get_or_create$sync_newly_created_database_BANG_$fn__147190$fn__147194 invoke \"get_or_create.clj\" 136]\n  [metabase.test.data.impl.get_or_create$sync_newly_created_database_BANG_$fn__147190 invoke \"get_or_create.clj\" 128]\n  [clojure.core$binding_conveyor_fn$fn__5823 invoke \"core.clj\" 2047]\n  [clojure.lang.AFn call \"AFn.java\" 18]\n  [java.util.concurrent.FutureTask run \"FutureTask.java\" 264]\n  [java.util.concurrent.ThreadPoolExecutor runWorker \"ThreadPoolExecutor.java\" 1128]\n  [java.util.concurrent.ThreadPoolExecutor$Worker run \"ThreadPoolExecutor.java\" 628]\n  [java.lang.Thread run \"Thread.java\" 829]]}"]
clojure.lang.ExceptionInfo: Failed to sync test database "diff-time-zones-cases": Invalid output: ["invalid type, got: #error {\n :cause \"class com.amazon.redshift.util.RedshiftException cannot be cast to class clojure.lang.Associative (com.amazon.redshift.util.RedshiftException and clojure.lang.Associative are in unnamed module of loader 'app')\"\n :via\n [{:type java.lang.ClassCastException\n   :message \"class com.amazon.redshift.util.RedshiftException cannot be cast to class clojure.lang.Associative (com.amazon.redshift.util.RedshiftException and clojure.lang.Associative are in unnamed module of loader 'app')\"\n   :at [clojure.lang.RT assoc \"RT.java\" 827]}]\n :trace\n [[clojure.lang.RT assoc \"RT.java\" 827]\n  [clojure.core$assoc__5481 invokeStatic \"core.clj\" 193]\n  [clojure.core$assoc__5481 invoke \"core.clj\" 192]\n  [metabase.sync$fn__117877$_AMPERSAND_f__117879$fn__117881 invoke \"sync.clj\" 52]\n  [metabase.sync.util$do_with_error_handling invokeStatic \"util.clj\" 188]\n  [metabase.sync.util$do_with_error_handling invoke \"util.clj\" 181]\n  [clojure.core$partial$fn__5910 invoke \"core.clj\" 2647]\n  [metabase.driver$eval76273$fn__76274 invoke \"driver.clj\" 884]\n  [clojure.lang.MultiFn invoke \"MultiFn.java\" 239]\n  [metabase.sync.util$sync_in_context$fn__82219 invoke \"util.clj\" 164]\n  [metabase.sync.util$with_db_logging_disabled$fn__82216 invoke \"util.clj\" 156]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invokeStatic \"util.clj\" 129]\n  [metabase.sync.util$with_start_and_finish_logging_STAR_ invoke \"util.clj\" 123]\n  [metabase.sync.util$with_start_and_finish_logging$fn__82203 invoke \"util.clj\" 141]\n  [metabase.sync.util$fn__82190$_AMPERSAND_f__82191$fn__82195 invoke \"util.clj\" 115]\n  [metabase.sync.util$with_duplicate_ops_prevented$fn__82180 invoke \"util.clj\" 87]\n  [metabase.sync.util$fn__82238$_AMPERSAND_f__82239 invoke \"util.clj\" 213]\n  [metabase.sync.util$fn__82238$fn__82241 invoke \"util.clj\" 207]\n  [metabase.sync$fn__117877$_AMPERSAND_f__117879 invoke \"sync.clj\" 51]\n  [metabase.sync$fn__117877$fn__117885 invoke \"sync.clj\" 37]\n  [metabase.test.data.impl.get_or_create$sync_newly_created_database_BANG_$fn__147190$fn__147194$fn__147195 invoke \"get_or_create.clj\" 137]\n  [metabase.test.data.impl.get_or_create$sync_newly_created_database_BANG_$fn__147190$fn__147194 invoke \"get_or_create.clj\" 136]\n  [metabase.test.data.impl.get_or_create$sync_newly_created_database_BANG_$fn__147190 invoke \"get_or_create.clj\" 128]\n  [clojure.core$binding_conveyor_fn$fn__5823 invoke \"core.clj\" 2047]\n  [clojure.lang.AFn call \"AFn.java\" 18]\n  [java.util.concurrent.FutureTask run \"FutureTask.java\" 264]\n  [java.util.concurrent.ThreadPoolExecutor runWorker \"ThreadPoolExecutor.java\" 1128]\n  [java.util.concurrent.ThreadPoolExecutor$Worker run \"ThreadPoolExecutor.java\" 628]\n  [java.lang.Thread run \"Thread.java\" 829]]}"]
	at metabase.test.data.impl.get_or_create$sync_newly_created_database_BANG_.invokeStatic(get_or_create.clj:145) [?:?]
	at metabase.test.data.impl.get_or_create$sync_newly_created_database_BANG_.invoke(get_or_create.clj:120) [?:?]
	at metabase.test.data.impl.get_or_create$fn__147267$_AMPERSAND_f__147269.invoke(get_or_create.clj:265) [?:?]
	at metabase.test.data.impl.get_or_create$fn__147267$fn__147272.invoke(get_or_create.clj:253) [?:?]
	at metabase.test.data.impl.get_or_create$create_database_BANG_.invokeStatic(get_or_create.clj:276) [?:?]
	at metabase.test.data.impl.get_or_create$create_database_BANG_.invoke(get_or_create.clj:272) [?:?]
	at metabase.test.data.impl.get_or_create$create_database_with_bound_settings_BANG_$thunk__147280.invoke(get_or_create.clj:286) [?:?]
	at metabase.test.util$do_with_temporary_setting_value.invokeStatic(util.clj:450) [?:?]
	at metabase.test.util$do_with_temporary_setting_value.doInvoke(util.clj:406) [?:?]
	at clojure.lang.RestFn.invoke(RestFn.java:445) [clojure-1.11.2.jar:?]
	at clojure.lang.Var.invoke(Var.java:393) [clojure-1.11.2.jar:?]
	at metabase.test.data.impl.get_or_create$create_database_with_bound_settings_BANG_.invokeStatic(get_or_create.clj:292) [?:?]
	at metabase.test.data.impl.get_or_create$create_database_with_bound_settings_BANG_.invoke(get_or_create.clj:282) [?:?]
	at metabase.test.data.impl.get_or_create$create_and_sync_database_with_write_lock_BANG_.invokeStatic(get_or_create.clj:303) [?:?]
	at metabase.test.data.impl.get_or_create$create_and_sync_database_with_write_lock_BANG_.invoke(get_or_create.clj:297) [?:?]
	at metabase.test.data.impl.get_or_create$default_get_or_create_database_BANG_.invokeStatic(get_or_create.clj:343) [?:?]
	at metabase.test.data.impl.get_or_create$default_get_or_create_database_BANG_.invoke(get_or_create.clj:334) [?:?]
	at metabase.test.data.impl$eval147408$fn__147409.invoke(impl.clj:41) [?:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:234) [clojure-1.11.2.jar:?]
	at metabase.test.data.impl$do_with_dataset$fn__147594.invoke(impl.clj:377) [?:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) [clojure-1.11.2.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:667) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invoke(core.clj:662) [clojure-1.11.2.jar:?]
	at metabase.db$memoize_for_application_db$fn__74145.doInvoke(db.clj:104) [?:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:139) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:667) [clojure-1.11.2.jar:?]
	at clojure.core$memoize$fn__6946.doInvoke(core.clj:6389) [clojure-1.11.2.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:669) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invoke(core.clj:662) [clojure-1.11.2.jar:?]
	at metabase.db$memoize_for_application_db$fn__74147.doInvoke(db.clj:106) [?:?]
	at clojure.lang.RestFn.invoke(RestFn.java:408) [clojure-1.11.2.jar:?]
	at metabase.test.data.impl$do_with_dataset$db_fn__147596.invoke(impl.clj:381) [?:?]
	at metabase.test.data.impl$do_with_dataset$fn__147598.invoke(impl.clj:383) [?:?]
	at metabase.test.data.impl$fn__147426$_AMPERSAND_f__147427.invoke(impl.clj:89) [?:?]
	at metabase.test.data.impl$fn__147426$fn__147429.invoke(impl.clj:87) [?:?]
	at metabase.test.data$id.invokeStatic(data.clj:219) [?:?]
	at metabase.test.data$id.invoke(data.clj:214) [?:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:152) [clojure-1.11.2.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) [clojure-1.11.2.jar:?]
	at clojure.lang.Var.applyTo(Var.java:705) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:667) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invoke(core.clj:662) [clojure-1.11.2.jar:?]
	at metabase.test.data.mbql_query_impl$druid_id_fn.invokeStatic(mbql_query_impl.clj:19) [?:?]
	at metabase.test.data.mbql_query_impl$druid_id_fn.doInvoke(mbql_query_impl.clj:12) [?:?]
	at clojure.lang.RestFn.invoke(RestFn.java:397) [clojure-1.11.2.jar:?]
	at metabase.query_processor_test.date_time_zone_functions_test$fn__276350$fn__276389$fn__276390$diffs__276391.invoke(date_time_zone_functions_test.clj:1066) [?:?]
	at metabase.query_processor_test.date_time_zone_functions_test$run_datetime_diff_time_zone_tests_BANG_$fn__276291$fn__276292.invoke(date_time_zone_functions_test.clj:963) [?:?]
	at metabase.test.util$do_with_temporary_setting_value.invokeStatic(util.clj:450) [?:?]
	at metabase.test.util$do_with_temporary_setting_value.doInvoke(util.clj:406) [?:?]
	at clojure.lang.RestFn.invoke(RestFn.java:445) [clojure-1.11.2.jar:?]
	at metabase.query_processor_test.date_time_zone_functions_test$run_datetime_diff_time_zone_tests_BANG_$fn__276291.invoke(date_time_zone_functions_test.clj:961) [?:?]
	at metabase.query_processor_test.date_time_zone_functions_test$run_datetime_diff_time_zone_tests_BANG_.invokeStatic(date_time_zone_functions_test.clj:960) [?:?]
	at metabase.query_processor_test.date_time_zone_functions_test$run_datetime_diff_time_zone_tests_BANG_.invoke(date_time_zone_functions_test.clj:949) [?:?]
	at metabase.query_processor_test.date_time_zone_functions_test$fn__276350$fn__276389$fn__276390.invoke(date_time_zone_functions_test.clj:[1075](https://github.com/metabase/metabase/actions/runs/10038716376/job/27748689824#step:3:1089)) [?:?]
	at metabase.test.data.impl$do_with_dataset.invokeStatic(impl.clj:385) [?:?]
	at metabase.test.data.impl$do_with_dataset.invoke(impl.clj:371) [?:?]
	at metabase.query_processor_test.date_time_zone_functions_test$fn__276350$fn__276389.invoke(date_time_zone_functions_test.clj:1063) [?:?]
	at metabase.test.data.datasets$_test_driver$fn__146757.invoke(datasets.clj:29) [?:?]
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:105) [?:?]
	at metabase.driver$do_with_driver.invoke(driver.clj:100) [?:?]
	at metabase.test.data.datasets$_test_driver.invokeStatic(datasets.clj:28) [?:?]
	at metabase.test.data.datasets$_test_driver.invoke(datasets.clj:23) [?:?]
	at metabase.query_processor_test.date_time_zone_functions_test$fn__276350.invokeStatic(date_time_zone_functions_test.clj:1062) [?:?]
	at metabase.query_processor_test.date_time_zone_functions_test$fn__276350.invoke(date_time_zone_functions_test.clj:1061) [?:?]
	at clojure.test$test_var$fn__9856.invoke(test.clj:717) [clojure-1.11.2.jar:?]
	at clojure.test$test_var.invokeStatic(test.clj:717) [clojure-1.11.2.jar:?]
	at clojure.test$test_var.invoke(test.clj:708) [clojure-1.11.2.jar:?]
	at mb.hawk.core$run_test.invokeStatic(core.clj:151) [?:?]
	at mb.hawk.core$run_test.invoke(core.clj:142) [?:?]
	at eftest.runner$test_vars$fn__21553$fn__21557.invoke(runner.clj:106) [?:?]
	at clojure.test$default_fixture.invokeStatic(test.clj:687) [clojure-1.11.2.jar:?]
	at clojure.test$default_fixture.invoke(test.clj:683) [clojure-1.11.2.jar:?]
	at eftest.runner$test_vars$fn__21553.invoke(runner.clj:98) [?:?]
	at eftest.runner$wrap_test_with_timer$fn__21514.invoke(runner.clj:38) [?:?]
	at clojure.core$map$fn__5935.invoke(core.clj:2770) [clojure-1.11.2.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) [clojure-1.11.2.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) [clojure-1.11.2.jar:?]
	at clojure.lang.RT.seq(RT.java:535) [clojure-1.11.2.jar:?]
	at clojure.core$seq__5467.invokeStatic(core.clj:139) [clojure-1.11.2.jar:?]
	at clojure.core$dorun.invokeStatic(core.clj:3135) [clojure-1.11.2.jar:?]
	at clojure.core$dorun.invoke(core.clj:3135) [clojure-1.11.2.jar:?]
	at eftest.runner$test_vars$fn__21561.invoke(runner.clj:115) [?:?]
	at clojure.test$default_fixture.invokeStatic(test.clj:687) [clojure-1.11.2.jar:?]
	at clojure.test$default_fixture.invoke(test.clj:683) [clojure-1.11.2.jar:?]
	at eftest.runner$test_vars.invokeStatic(runner.clj:112) [?:?]
	at eftest.runner$test_vars.invoke(runner.clj:88) [?:?]
	at eftest.runner$test_ns.invokeStatic(runner.clj:125) [?:?]
	at eftest.runner$test_ns.invoke(runner.clj:121) [?:?]
	at eftest.runner$test_all$f__21575$fn__21577.invoke(runner.clj:140) [?:?]
	at clojure.core$map$fn__5935.invoke(core.clj:2772) [clojure-1.11.2.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) [clojure-1.11.2.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:51) [clojure-1.11.2.jar:?]
	at clojure.lang.Cons.next(Cons.java:39) [clojure-1.11.2.jar:?]
	at clojure.lang.RT.next(RT.java:713) [clojure-1.11.2.jar:?]
	at clojure.core$next__5451.invokeStatic(core.clj:64) [clojure-1.11.2.jar:?]
	at clojure.core$reduce1.invokeStatic(core.clj:946) [clojure-1.11.2.jar:?]
	at clojure.core$reduce1.invokeStatic(core.clj:936) [clojure-1.11.2.jar:?]
	at clojure.core$merge_with.invokeStatic(core.clj:3077) [clojure-1.11.2.jar:?]
	at clojure.core$merge_with.doInvoke(core.clj:3069) [clojure-1.11.2.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:139) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:669) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invoke(core.clj:662) [clojure-1.11.2.jar:?]
	at eftest.runner$test_all$f__21575.invoke(runner.clj:141) [?:?]
	at eftest.runner$test_all.invokeStatic(runner.clj:144) [?:?]
	at eftest.runner$test_all.invoke(runner.clj:129) [?:?]
	at eftest.runner$run_tests$fn__21621.invoke(runner.clj:215) [?:?]
	at eftest.runner$run_tests.invokeStatic(runner.clj:215) [?:?]
	at eftest.runner$run_tests.invoke(runner.clj:181) [?:?]
	at mb.hawk.core$run_tests$fn__22066.invoke(core.clj:197) [?:?]
	at clojure.core$with_redefs_fn.invokeStatic(core.clj:7583) [clojure-1.11.2.jar:?]
	at clojure.core$with_redefs_fn.invoke(core.clj:7567) [clojure-1.11.2.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.11.2.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:667) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invoke(core.clj:662) [clojure-1.11.2.jar:?]
	at metabase.test.redefs$new_with_redefs_fn.invokeStatic(redefs.clj:38) [?:?]
	at metabase.test.redefs$new_with_redefs_fn.doInvoke(redefs.clj:36) [?:?]
	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.11.2.jar:?]
	at mb.hawk.core$run_tests.invokeStatic(core.clj:194) [?:?]
	at mb.hawk.core$run_tests.invoke(core.clj:175) [?:?]
	at mb.hawk.core$find_and_run_tests_with_options$fn__22093.invoke(core.clj:233) [?:?]
	at mb.hawk.core$find_and_run_tests_with_options.invokeStatic(core.clj:230) [?:?]
	at mb.hawk.core$find_and_run_tests_with_options.invoke(core.clj:223) [?:?]
	at mb.hawk.core$find_and_run_tests_cli.invokeStatic(core.clj:266) [?:?]
	at mb.hawk.core$find_and_run_tests_cli.invoke(core.clj:258) [?:?]
	at metabase.test_runner$find_and_run_tests_cli.invokeStatic(test_runner.clj:104) [?:?]
	at metabase.test_runner$find_and_run_tests_cli.invoke(test_runner.clj:101) [?:?]
	at clojure.lang.Var.invoke(Var.java:384) [clojure-1.11.2.jar:?]
	at clojure.run.exec$exec.invokeStatic(exec.clj:89) [?:?]
	at clojure.run.exec$exec.invoke(exec.clj:78) [?:?]
	at clojure.run.exec$_main$fn__20820.invoke(exec.clj:216) [?:?]
	at clojure.run.exec$_main.invokeStatic(exec.clj:212) [?:?]
	at clojure.run.exec$_main.doInvoke(exec.clj:180) [?:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.11.2.jar:?]
	at clojure.lang.Var.applyTo(Var.java:705) [clojure-1.11.2.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:667) [clojure-1.11.2.jar:?]
	at clojure.main$main_opt.invokeStatic(main.clj:514) [clojure-1.11.2.jar:?]
	at clojure.main$main_opt.invoke(main.clj:510) [clojure-1.11.2.jar:?]
	at clojure.main$main.invokeStatic(main.clj:664) [clojure-1.11.2.jar:?]
	at clojure.main$main.doInvoke(main.clj:616) [clojure-1.11.2.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [clojure-1.11.2.jar:?]
	at clojure.lang.Var.applyTo(Var.java:705) [clojure-1.11.2.jar:?]
	at clojure.main.main(main.java:40) [clojure-1.11.2.jar:?]
```

**Comment by camsaul** [comment]
ok so actually I guess the sync code is at least catching the `com.amazon.redshift.util.RedshiftException cannot be cast to class clojure.lang.Associative` error, so I guess maybe the actual problem is that `sync-database!` has a schema that says it returns a map when it can actually return a `Throwable` as well. Investigating further

**Comment by camsaul** [comment]
Here's a test to repro in `metabase.sync-test`

```clj
(driver/register! ::sync-database-error-test)

(defmethod driver/describe-database ::sync-database-error-test
  [_driver _database]
  (driver/describe-database :h2 (mt/with-driver :h2 (mt/db))))

(defmethod driver/describe-table ::sync-database-error-test
  [_driver _database table]
  (if (= (:name table) "ORDERS")
    (throw (ex-info "OOPS!" {}))
    (driver/describe-table :h2 (mt/with-driver :h2 (mt/db)) table)))

(deftest ^:parallel sync-database!-error-test
  (testing "Errors in sync should be caught, and sync should continue normally (#45848)"
    (mt/with-temp [Database db {:engine ::sync-database-error-test}]
      (binding [sync-util/*log-exceptions-and-continue?* false]
        (is (= :error
               (sync/sync-database! db)))))))
```
