### ISSUE TITLE
Memory issue during 'migrate-query-executions' migration

### ISSUE THREAD

**Issue by maliayas** [metabase/metabase#4601]
- Your operating system: Windows 8
- Your databases: MySQL
- Metabase version: 0.23.0
- Metabase hosting environment: Docker
- Metabase internal database: H2

During the update to v0.23.0, I repeatedly got the below error. I truncated the table `query_queryexecution` (there were 60849 rows) and issue was fixed. Maybe there should be some way to periodically cleand this table.

````
03-23 12:42:21 INFO db.migrations :: Running data migration 'migrate-query-executions'...
java.lang.OutOfMemoryError: Java heap space
        at java.io.BufferedReader.<init>(BufferedReader.java:105)
        at java.io.BufferedReader.<init>(BufferedReader.java:116)
        at org.h2.util.IOUtils.getBufferedReader(IOUtils.java:380)
        at org.h2.value.ValueLobDb.getReader(ValueLobDb.java:366)
        at org.h2.jdbc.JdbcClob.getCharacterStream(JdbcClob.java:111)
        at metabase.util$fn__7425.invokeStatic(util.clj:336)
        at metabase.util$fn__7425.invoke(util.clj:310)
        at metabase.util$fn__7403$G__7398__7408.invoke(util.clj:306)
        at toucan.models$apply_type_fns$iter__3132__3136$fn__3137.invoke(models.clj:278)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:688)
        at clojure.core$next__4341.invokeStatic(core.clj:64)
        at clojure.core.protocols$fn__6755.invokeStatic(protocols.clj:168)
03-23 12:46:53 ERROR metabase.core :: Metabase Initialization FAILED:  Java heap space
        at clojure.core.protocols$fn__6755.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6545)
        at clojure.core$into.invokeStatic(core.clj:6610)
        at clojure.core$into.invoke(core.clj:6604)
        at toucan.models$apply_type_fns.invokeStatic(models.clj:276)
        at toucan.models$apply_type_fns.invoke(models.clj:273)
        at toucan.models$do_post_select.invokeStatic(models.clj:323)
        at toucan.models$do_post_select.invoke(models.clj:318)
        at toucan.db$do_post_select$iter__3274__3278$fn__3279.invoke(db.clj:288)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
````

**Comment by maliayas** [comment]
I've just found this issue was already discussed in #4155. Sorry for bugging.
