### ISSUE TITLE
[Mongo] Failed to fingerprint table with PK of type "ObjectID"

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#46259]
### Describe the bug

It fails to fingerprint mongo tables with PK of type ObjectID, which is very common.
Mongo

### To Reproduce

1. Create a mongo DB with this collection
```
db.myCollection.insertMany([
  { name: "Eminem" }
]);
```
2. Sync it, observe log

### Expected behavior

Fingerprint succeed without errors

### Logs

```
2024-07-30 04:04:00,167 WARN sync.util :: Error fingerprinting Table 29 ''myCollection''
clojure.lang.ExceptionInfo: Error preprocessing query in #'metabase.query-processor.middleware.normalize-query/normalize-preprocessing-middleware: Error normalizing query: Error creating query from legacy query: Invalid output: {:stages [{:order-by [[nil nil ["an expression that can b
e compared with :> or :<, got: [:field {:lib/uuid \"88af652b-b169-4930-a34a-1c4dd9de5a22\", :metabase.lib.query/transformation-added-base-type true, :base-type :type/MongoBSONID, :effective-type :type/MongoBSONID} 355]"]]]}]} {:fn #'metabase.query-processor.middleware.normalize-query/
normalize-preprocessing-middleware, :query {:database 4, :type :query, :query {:source-table 29, :expressions {"substring199343" [:substring [:field 356 nil] 1 1234]}, :fields [[:expression "substring199343"]], :limit 500, :order-by [[:desc [:field 355 nil]]]}, :middleware {:format-ro
ws? false, :skip-results-metadata? true}}, :type :qp}
        at metabase.query_processor.preprocess$fn__109470$_AMPERSAND_f__109471$fn__109472$fn__109473.invoke(preprocess.clj:150)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$transduce.invokeStatic(core.clj:6947)
        at clojure.core$transduce.invoke(core.clj:6934)
        at metabase.query_processor.preprocess$fn__109470$_AMPERSAND_f__109471$fn__109472.invoke(preprocess.clj:124)
        at metabase.query_processor.setup$fn__109435$_AMPERSAND_f__109436.invoke(setup.clj:225)
        at metabase.query_processor.setup$fn__109435$fn__109440.invoke(setup.clj:216)
        at metabase.query_processor.preprocess$fn__109470$_AMPERSAND_f__109471.invoke(preprocess.clj:122)
        at metabase.query_processor.preprocess$fn__109470$fn__109485.invoke(preprocess.clj:118)
        at metabase.query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:46)
        at metabase.query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)
        at metabase.query_processor.middleware.enterprise$eval104531$handle_audit_app_internal_queries__104532$fn__104534.invoke(enterprise.clj:96)
        at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__104542.invoke(enterprise.clj:103)
        at metabase.query_processor.middleware.process_userland_query$fn__110355$_AMPERSAND_f__110356$_AMPERSAND_f__110357.invoke(process_userland_query.clj:182)
        at metabase.query_processor.middleware.process_userland_query$fn__110355$_AMPERSAND_f__110356$fn__110363.invoke(process_userland_query.clj:179)
        at metabase.query_processor.middleware.catch_exceptions$fn__110182$_AMPERSAND_f__110183$_AMPERSAND_f__110184.invoke(catch_exceptions.clj:121)
        at metabase.query_processor.middleware.catch_exceptions$fn__110182$_AMPERSAND_f__110183$fn__110196.invoke(catch_exceptions.clj:118)
        at metabase.query_processor$fn__110685$_AMPERSAND_f__110686$fn__110687.invoke(query_processor.clj:80)
        at metabase.query_processor.setup$fn__109427$_AMPERSAND_f__109428$fn__109429.invoke(setup.clj:189)
        at metabase.query_processor.setup$fn__109417$_AMPERSAND_f__109418$fn__109419.invoke(setup.clj:181)
        at metabase.query_processor.setup$fn__109407$_AMPERSAND_f__109408$fn__109409$fn__109410.invoke(setup.clj:166)
        at metabase.driver$do_with_driver.invokeStatic(driver.clj:106)
        at metabase.driver$do_with_driver.invoke(driver.clj:101)
        at metabase.query_processor.setup$fn__109407$_AMPERSAND_f__109408$fn__109409.invoke(setup.clj:165)
        at metabase.query_processor.setup$fn__109395$_AMPERSAND_f__109396$fn__109397.invoke(setup.clj:140)
        at metabase.query_processor.setup$fn__109377$_AMPERSAND_f__109378$_AMPERSAND_f__109379.invoke(setup.clj:128)
        at metabase.query_processor.setup$fn__109377$_AMPERSAND_f__109378$fn__109382.invoke(setup.clj:122)
        at metabase.query_processor.setup$fn__109435$_AMPERSAND_f__109436.invoke(setup.clj:232)
        at metabase.query_processor.setup$fn__109435$fn__109440.invoke(setup.clj:216)
        at metabase.query_processor$fn__110685$_AMPERSAND_f__110686.invoke(query_processor.clj:78)
        at metabase.query_processor$fn__110685$fn__110691.invoke(query_processor.clj:71)
        at metabase.db.metadata_queries$fn__196222$_AMPERSAND_f__196223.invoke(NO_SOURCE_FILE:219)
        at metabase.db.metadata_queries$fn__196222$fn__196225.invoke(NO_SOURCE_FILE:201)
        at metabase.driver.mongo$eval198870$fn__198871$fn__198872.invoke(NO_SOURCE_FILE:344)
        at metabase.query_processor.store$fn__96270$_AMPERSAND_f__96271.invoke(store.clj:166)
        at metabase.query_processor.store$fn__96270$fn__96274.invoke(store.clj:151)
        at metabase.driver.mongo$eval198870$fn__198871.invoke(NO_SOURCE_FILE:341)
        at clojure.lang.MultiFn.invoke(MultiFn.java:252)
        at metabase.sync.analyze.fingerprint$fn__198245$_AMPERSAND_f__198246.invoke(NO_SOURCE_FILE:88)
        at metabase.sync.analyze.fingerprint$fn__198245$fn__198259.invoke(NO_SOURCE_FILE:65)
        at metabase.sync.analyze.fingerprint$fn__139433$_AMPERSAND_f__139434$fn__139435.invoke(fingerprint.clj:206)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:189)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:182)
        at metabase.sync.analyze.fingerprint$fn__139433$_AMPERSAND_f__139434.invoke(fingerprint.clj:204)
        at metabase.sync.analyze.fingerprint$fn__139433$fn__139441.invoke(fingerprint.clj:198)
        at metabase.sync.analyze.fingerprint$fn__139444$_AMPERSAND_f__139445$fn__139446$fn__139447.invoke(fingerprint.clj:230)
        at clojure.core$completing$fn__8528.invoke(core.clj:6932)
        at clojure.core$map$fn__5931$fn__5932.invoke(core.clj:2759)
        at toucan2.pipeline$with_init$fn__58064.invoke(pipeline.clj:327)
        at clojure.core$completing$fn__8528.invoke(core.clj:6932)
        at clojure.core$map$fn__5931$fn__5932.invoke(core.clj:2759)
        at toucan2.jdbc.result_set$reduce_result_set.invokeStatic(result_set.clj:158)
        at toucan2.jdbc.result_set$reduce_result_set.invoke(result_set.clj:125)
        at toucan2.jdbc.query$reduce_jdbc_query.invokeStatic(query.clj:51)
        at toucan2.jdbc.query$reduce_jdbc_query.invoke(query.clj:22)
        at toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default.invokeStatic(pipeline.clj:19)
        at toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default.invoke(pipeline.clj:9)
        at clojure.lang.AFn.applyToHelper(AFn.java:178)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:675)
        at clojure.core$partial$fn__5908.doInvoke(core.clj:2639)
        at clojure.lang.RestFn.applyTo(RestFn.java:146)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at methodical.impl.combo.threaded$eval14962$fn__14963$fn__14964$fn__14971.invoke(threaded.clj:79)
        at methodical.impl.combo.threaded$reducer_fn$fn__14930$fn__14934.invoke(threaded.clj:23)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
        at clojure.core.protocols$fn__8244.invokeStatic(protocols.clj:136)
        at clojure.core.protocols$fn__8244.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6887)
        at clojure.core$reduce.invoke(core.clj:6869)
        at methodical.impl.combo.threaded$reducer_fn$fn__14930.invoke(threaded.clj:21)
        at clojure.core$comp$fn__5876.doInvoke(core.clj:2589)
        at clojure.lang.RestFn.applyTo(RestFn.java:146)
        at clojure.core$apply.invokeStatic(core.clj:675)
        at clojure.core$apply.doInvoke(core.clj:662)
        at clojure.lang.RestFn.invoke(RestFn.java:533)
        at methodical.impl.combo.threaded$combine_with_threader$fn__14940.doInvoke(threaded.clj:46)
        at clojure.lang.RestFn.applyTo(RestFn.java:151)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:675)
        at clojure.core$apply.doInvoke(core.clj:662)
        at clojure.lang.RestFn.invoke(RestFn.java:533)
        at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:65)
        at methodical.impl.standard$invoke_multifn.doInvoke(standard.clj:47)
        at clojure.lang.RestFn.invoke(RestFn.java:594)
        at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:199)
        at toucan2.pipeline$transduce_execute$with_connection_STAR___57962.invoke(pipeline.clj:78)
        at toucan2.connection$bind_current_connectable_fn$fn__57543.invoke(connection.clj:104)
        at toucan2.connection$bind_current_connectable_fn$fn__57543.invoke(connection.clj:104)
        at toucan2.connection$bind_current_connectable_fn$fn__57543.invoke(connection.clj:104)
        at toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource.invokeStatic(connection.clj:18)
        at toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource.invoke(connection.clj:15)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at clojure.core$partial$fn__5908.invoke(core.clj:2642)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at methodical.impl.combo.threaded$eval14962$fn__14963$fn__14964$fn__14965.invoke(threaded.clj:70)
        at methodical.impl.combo.threaded$reducer_fn$fn__14930$fn__14934.invoke(threaded.clj:23)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
        at clojure.core.protocols$fn__8244.invokeStatic(protocols.clj:136)
        at clojure.core.protocols$fn__8244.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6887)
        at clojure.core$reduce.invoke(core.clj:6869)
               at metabase.sync.analyze.fingerprint$fn__139444$_AMPERSAND_f__139445$fn__139446.invoke(fingerprint.clj:228)
        at metabase.query_processor.store$fn__96270$_AMPERSAND_f__96271.invoke(store.clj:171)
        at metabase.query_processor.store$fn__96270$fn__96274.invoke(store.clj:151)
        at metabase.query_processor.store$fn__96270$_AMPERSAND_f__96271.invoke(store.clj:160)
        at metabase.query_processor.store$fn__96270$fn__96274.invoke(store.clj:151)
        at metabase.sync.analyze.fingerprint$fn__139444$_AMPERSAND_f__139445.invoke(fingerprint.clj:224)
        at metabase.sync.analyze.fingerprint$fn__139444$fn__139451.invoke(fingerprint.clj:215)
        at metabase.sync.analyze.fingerprint$fn__139444$_AMPERSAND_f__139445.invoke(fingerprint.clj:219)
        at metabase.sync.analyze.fingerprint$fn__139444$fn__139451.invoke(fingerprint.clj:215)
        at metabase.sync.analyze.fingerprint$fn__139454$_AMPERSAND_f__139455.invoke(fingerprint.clj:242)
        at metabase.sync.analyze.fingerprint$fn__139454$fn__139457.invoke(fingerprint.clj:237)
        at metabase.sync.analyze$make_analyze_steps$fn__139583.invoke(analyze.clj:100)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$apply.invoke(core.clj:662)
        at metabase.sync.util$fn__98447$_AMPERSAND_f__98449$fn__98451$fn__98454.invoke(util.clj:490)
        at metabase.models.task_history$fn__98197$_AMPERSAND_f__98198.invoke(task_history.clj:116)
        at metabase.models.task_history$fn__98197$fn__98201.invoke(task_history.clj:105)
        at metabase.sync.util$fn__98447$_AMPERSAND_f__98449$fn__98451.doInvoke(util.clj:483)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:130)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:124)
        at metabase.sync.util$do_with_start_and_finish_debug_logging.invokeStatic(util.clj:148)
        at metabase.sync.util$do_with_start_and_finish_debug_logging.invoke(util.clj:144)
        at metabase.sync.util$fn__98447$_AMPERSAND_f__98449.invoke(util.clj:477)
        at metabase.sync.util$fn__98447$fn__98460.invoke(util.clj:472)
        at metabase.sync.util$fn__98506$_AMPERSAND_f__98507$fn__98508$fn__98516.invoke(util.clj:563)
        at metabase.sync.util$fn__98506$_AMPERSAND_f__98507$fn__98508.invoke(util.clj:561)
        at metabase.models.task_history$fn__98197$_AMPERSAND_f__98198.invoke(task_history.clj:116)
        at metabase.models.task_history$fn__98197$fn__98201.invoke(task_history.clj:105)
        at metabase.sync.util$fn__98506$_AMPERSAND_f__98507.invoke(util.clj:558)
        at metabase.sync.util$fn__98506$fn__98526.invoke(util.clj:553)
        at metabase.sync.analyze$fn__139590$_AMPERSAND_f__139591$fn__139592.invoke(analyze.clj:116)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:189)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:182)
        at clojure.core$partial$fn__5910.invoke(core.clj:2647)
        at metabase.driver.mongo$eval198412$fn__198413$f__126226__auto____198414.invoke(NO_SOURCE_FILE:104)
        at metabase.driver.mongo.connection$do_with_mongo_client$fn__126217.invoke(connection.clj:94)
        at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:165)
        at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154)
        at metabase.driver.mongo.connection$do_with_mongo_client.invokeStatic(connection.clj:89)
        at metabase.driver.mongo.connection$do_with_mongo_client.invoke(connection.clj:85)
        at metabase.driver.mongo$eval198412$fn__198413.invoke(NO_SOURCE_FILE:103)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at metabase.sync.util$sync_in_context$fn__98326.invoke(util.clj:165)
        at metabase.sync.util$with_db_logging_disabled$fn__98323.invoke(util.clj:157)
        at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:130)
```

### Information about your Metabase installation

```JSON
master
```

### Severity

Regressions that exist in 50

**Comment by qnkhuat** [comment]
It fails to get the table sample rows in https://github.com/metabase/metabase/blob/84651267d4e11606601e54c2facdccf2d34f1a1f/modules/drivers/mongo/src/metabase/driver/mongo.clj#L344

**Comment by qnkhuat** [comment]
I think it's a MLv2 issue because if I add `:type/MongoBSONID` to this [orderable-types](https://github.com/metabase/metabase/blob/d364df916e50153ebba64c477cfd161e7b4984a8/src/metabase/lib/schema/expression.cljc#L139) list then fingerprint works.
