### ISSUE TITLE
v0.50.19 can no longer start due to a SQL syntax error in a Liquibase migration

### ISSUE THREAD

**Issue by dkrylovsb** [metabase/metabase#46658]
### Describe the bug

After upgrading to v0.50.19, the app can no longer start:

```
2024-08-08T20:26:12.458161083Z 2024-08-08 20:26:12,457 INFO db.setup :: Running Database Migrations...
2024-08-08T20:26:12.458377439Z 2024-08-08 20:26:12,458 INFO db.setup :: Setting up Liquibase...
2024-08-08T20:26:12.716135150Z 2024-08-08 20:26:12,715 INFO db.setup :: Liquibase is ready.
2024-08-08T20:26:12.716447024Z 2024-08-08 20:26:12,716 INFO db.liquibase :: Checking if Database has unrun migrations...
2024-08-08T20:26:13.252124297Z 2024-08-08 20:26:13,251 INFO db.liquibase :: Database has unrun migrations. Checking if migration lock is taken...
2024-08-08T20:26:15.279696837Z 2024-08-08 20:26:15,279 WARN util.jvm :: [31mauto-retry metabase.db.liquibase$wait_for_migration_lock$fn__44398@142c8d98: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.[0m
2024-08-08T20:26:15.336285083Z 2024-08-08 20:26:15,335 WARN db.liquibase :: Migration lock was acquired after 1 retries.
2024-08-08T20:26:15.642619835Z 2024-08-08 20:26:15,631 INFO db.liquibase :: Running 10 migrations ...
2024-08-08T20:26:15.965540636Z 2024-08-08 20:26:15,958 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:07::calherries encountered an exception.
2024-08-08T20:26:15.965582334Z liquibase.exception.DatabaseException: ERROR: syntax error at or near "("
2024-08-08T20:26:15.965590389Z   Position: 87 [Failed SQL: (0) ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (
2024-08-08T20:26:15.965596801Z   CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END
2024-08-08T20:26:15.965603193Z ) STORED]
2024-08-08T20:26:15.965609154Z 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
2024-08-08T20:26:15.965617891Z 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
2024-08-08T20:26:15.965624693Z 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:179)
2024-08-08T20:26:15.965630855Z 	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
2024-08-08T20:26:15.965637116Z 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1285)
2024-08-08T20:26:15.965642927Z 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:755)
2024-08-08T20:26:15.965648829Z 	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
2024-08-08T20:26:15.965668295Z 	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
2024-08-08T20:26:15.965675268Z 	at liquibase.changelog.ChangeLogIterator$2.lambda$run$0(ChangeLogIterator.java:133)
2024-08-08T20:26:15.965681249Z 	at liquibase.Scope.lambda$child$0(Scope.java:186)
2024-08-08T20:26:15.965686940Z 	at liquibase.Scope.child(Scope.java:195)
2024-08-08T20:26:15.965692400Z 	at liquibase.Scope.child(Scope.java:185)
2024-08-08T20:26:15.965698151Z 	at liquibase.Scope.child(Scope.java:164)
2024-08-08T20:26:15.965704172Z 	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:122)
2024-08-08T20:26:15.965709863Z 	at liquibase.Scope.lambda$child$0(Scope.java:186)
2024-08-08T20:26:15.965715423Z 	at liquibase.Scope.child(Scope.java:195)
2024-08-08T20:26:15.965721124Z 	at liquibase.Scope.child(Scope.java:185)
2024-08-08T20:26:15.965726644Z 	at liquibase.Scope.child(Scope.java:164)
2024-08-08T20:26:15.965732245Z 	at liquibase.Scope.child(Scope.java:252)
2024-08-08T20:26:15.965737945Z 	at liquibase.Scope.child(Scope.java:256)
2024-08-08T20:26:15.965743967Z 	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
2024-08-08T20:26:15.965750098Z 	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:110)
2024-08-08T20:26:15.965756139Z 	at liquibase.Scope.lambda$child$0(Scope.java:186)
2024-08-08T20:26:15.965761710Z 	at liquibase.Scope.child(Scope.java:195)
2024-08-08T20:26:15.965767511Z 	at liquibase.Scope.child(Scope.java:185)
2024-08-08T20:26:15.965775045Z 	at liquibase.Scope.child(Scope.java:164)
2024-08-08T20:26:15.965781046Z 	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:108)
2024-08-08T20:26:15.965786707Z 	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
2024-08-08T20:26:15.965792888Z 	at liquibase.command.CommandScope.execute(CommandScope.java:217)
2024-08-08T20:26:15.965798409Z 	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
2024-08-08T20:26:15.965804069Z 	at liquibase.Scope.lambda$child$0(Scope.java:186)
2024-08-08T20:26:15.965809620Z 	at liquibase.Scope.child(Scope.java:195)
2024-08-08T20:26:15.965815140Z 	at liquibase.Scope.child(Scope.java:185)
2024-08-08T20:26:15.965820911Z 	at liquibase.Scope.child(Scope.java:164)
2024-08-08T20:26:15.965826391Z 	at liquibase.Liquibase.runInScope(Liquibase.java:1419)
2024-08-08T20:26:15.965832082Z 	at liquibase.Liquibase.update(Liquibase.java:234)
2024-08-08T20:26:15.965837832Z 	at liquibase.Liquibase.update(Liquibase.java:212)
2024-08-08T20:26:15.965843263Z 	at liquibase.Liquibase.update(Liquibase.java:194)
2024-08-08T20:26:15.965849044Z 	at metabase.db.liquibase$migrate_up_if_needed_BANG_$fn__44437.invoke(liquibase.clj:360)
2024-08-08T20:26:15.965867338Z 	at metabase.db.liquibase$run_in_scope_locked$reify__44433.run(liquibase.clj:325)
2024-08-08T20:26:15.965873299Z 	at liquibase.Scope.lambda$child$0(Scope.java:186)
2024-08-08T20:26:15.965878749Z 	at liquibase.Scope.child(Scope.java:195)
2024-08-08T20:26:15.965885662Z 	at liquibase.Scope.child(Scope.java:185)
2024-08-08T20:26:15.965891323Z 	at liquibase.Scope.child(Scope.java:164)
2024-08-08T20:26:15.965897394Z 	at metabase.db.liquibase$run_in_scope_locked.invokeStatic(liquibase.clj:318)
2024-08-08T20:26:15.965903856Z 	at metabase.db.liquibase$run_in_scope_locked.invoke(liquibase.clj:301)
2024-08-08T20:26:15.965910208Z 	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invokeStatic(liquibase.clj:349)
2024-08-08T20:26:15.965915809Z 	at metabase.db.liquibase$migrate_up_if_needed_BANG_.invoke(liquibase.clj:342)
2024-08-08T20:26:15.965922050Z 	at metabase.db.setup$migrate_BANG_$fn__53373.invoke(setup.clj:84)
2024-08-08T20:26:15.965928032Z 	at metabase.db.liquibase$do_with_liquibase$f_STAR___44374.invoke(liquibase.clj:140)
2024-08-08T20:26:15.965934063Z 	at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:143)
2024-08-08T20:26:15.965939984Z 	at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:131)
2024-08-08T20:26:15.965945835Z 	at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:73)
2024-08-08T20:26:15.965951445Z 	at metabase.db.setup$migrate_BANG_.doInvoke(setup.clj:55)
2024-08-08T20:26:15.965956735Z 	at clojure.lang.RestFn.invoke(RestFn.java:425)
2024-08-08T20:26:15.965961995Z 	at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:149)
2024-08-08T20:26:15.965967275Z 	at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:144)
2024-08-08T20:26:15.965973156Z 	at metabase.db.setup$setup_db_BANG_$fn__53401$fn__53402.invoke(setup.clj:167)
2024-08-08T20:26:15.965978466Z 	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
2024-08-08T20:26:15.965985078Z 	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
2024-08-08T20:26:15.965990549Z 	at metabase.db.setup$setup_db_BANG_$fn__53401.invoke(setup.clj:161)
2024-08-08T20:26:15.965995979Z 	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
2024-08-08T20:26:15.966001389Z 	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
2024-08-08T20:26:15.966006769Z 	at metabase.db$setup_db_BANG_$fn__53426.invoke(db.clj:86)
2024-08-08T20:26:15.966012289Z 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:81)
2024-08-08T20:26:15.966017699Z 	at metabase.db$setup_db_BANG_.doInvoke(db.clj:68)
2024-08-08T20:26:15.966022949Z 	at clojure.lang.RestFn.invoke(RestFn.java:421)
2024-08-08T20:26:15.966028219Z 	at metabase.core$init_BANG__STAR_.invokeStatic(core.clj:117)
2024-08-08T20:26:15.966046774Z 	at metabase.core$init_BANG__STAR_.invoke(core.clj:98)
2024-08-08T20:26:15.966052104Z 	at metabase.core$init_BANG_.invokeStatic(core.clj:170)
2024-08-08T20:26:15.966057414Z 	at metabase.core$init_BANG_.invoke(core.clj:165)
2024-08-08T20:26:15.966062664Z 	at metabase.core$start_normally.invokeStatic(core.clj:182)
2024-08-08T20:26:15.966067934Z 	at metabase.core$start_normally.invoke(core.clj:176)
2024-08-08T20:26:15.966073133Z 	at metabase.core$entrypoint.invokeStatic(core.clj:215)
2024-08-08T20:26:15.966079054Z 	at metabase.core$entrypoint.doInvoke(core.clj:209)
2024-08-08T20:26:15.966085256Z 	at clojure.lang.RestFn.invoke(RestFn.java:397)
2024-08-08T20:26:15.966091538Z 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
2024-08-08T20:26:15.966097359Z 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
2024-08-08T20:26:15.966103310Z 	at clojure.lang.Var.applyTo(Var.java:705)
2024-08-08T20:26:15.966108930Z 	at clojure.core$apply.invokeStatic(core.clj:667)
2024-08-08T20:26:15.966114851Z 	at clojure.core$apply.invoke(core.clj:662)
2024-08-08T20:26:15.966120903Z 	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
2024-08-08T20:26:15.966126924Z 	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
2024-08-08T20:26:15.966132805Z 	at clojure.lang.RestFn.invoke(RestFn.java:397)
2024-08-08T20:26:15.966138656Z 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
2024-08-08T20:26:15.966144687Z 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
2024-08-08T20:26:15.966150518Z 	at metabase.bootstrap.main(Unknown Source)
2024-08-08T20:26:15.966156079Z Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "("
2024-08-08T20:26:15.966162360Z   Position: 87
2024-08-08T20:26:15.966168191Z 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
2024-08-08T20:26:15.966174133Z 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
2024-08-08T20:26:15.966180004Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
2024-08-08T20:26:15.966186075Z 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
2024-08-08T20:26:15.966193449Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
2024-08-08T20:26:15.966199570Z 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:341)
2024-08-08T20:26:15.966205531Z 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:326)
2024-08-08T20:26:15.966211663Z 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:302)
2024-08-08T20:26:15.966217714Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:297)
2024-08-08T20:26:15.966223565Z 	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
2024-08-08T20:26:15.966236650Z 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:464)
2024-08-08T20:26:15.966243162Z 	... 86 more
2024-08-08T20:26:15.989398062Z
2024-08-08T20:26:15.989434230Z UPDATE SUMMARY
2024-08-08T20:26:15.989454287Z Run:                         10
2024-08-08T20:26:15.989460910Z Previously run:             342
2024-08-08T20:26:15.989467251Z Filtered out:                50
2024-08-08T20:26:15.989473493Z -------------------------------
2024-08-08T20:26:15.989479695Z Total change sets:          402
2024-08-08T20:26:15.989485446Z
2024-08-08T20:26:15.989491187Z
2024-08-08T20:26:15.989497147Z FILTERED CHANGE SETS SUMMARY
2024-08-08T20:26:15.989503059Z DBMS mismatch:               50
2024-08-08T20:26:15.989509130Z
2024-08-08T20:26:16.068351942Z 2024-08-08 20:26:16,066 ERROR metabase.core :: Metabase Initialization FAILED
```

### To Reproduce

Upgrade to latest

### Information about your Metabase installation

```JSON
Metabase v0.50.19 (0b97bf8) via Docker
```

### Severity

Critical

**Comment by dpsutton** [comment]
@dkrylovsb can you tell me what version you were upgrading from and what version of postgres you are using as your application db?

**Comment by dkrylovsb** [comment]
Hi @dpsutton I am upgrading from `metabase/metabase:v0.50.7`. It is Postgres 11 in Azure.

**Comment by dpsutton** [comment]
thanks @dkrylovsb 

I've run 0.50.7 and then 0.50.19 right after (only difference upping the liquibase log level) and seeing this on startup 

```
2024-08-08 15:53:12,644 INFO db.liquibase :: Running 17 migrations ...
...
2024-08-08 15:53:12,885 INFO liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:06::calherries ran successfully in 2ms
2024-08-08 15:53:12,894 INFO liquibase.changelog :: Custom SQL executed
2024-08-08 15:53:12,896 INFO liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:07::calherries ran successfully in 10ms
2024-08-08 15:53:12,901 INFO liquibase.changelog :: Unique constraint added to metabase_field(name, table_id, unique_field_helper)
2024-08-08 15:53:12,901 INFO liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:08::calherries ran successfully in 3ms
2024-08-08 15:53:12,906 INFO liquibase.changelog :: Custom SQL executed
...
```

The substance of `v49.2024-06-27T00:00:07` is

```sql
ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (
  CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END
) STORED;
```

This works for me locally with postgres 14. Let me investigate.

**Comment by dpsutton** [comment]
Ok. I can recreate:

```
❯ docker run -it -e POSTGRES_PASSWORD=password -d -p 5433:5432 postgres:11
❯ psql -p "5433" -h "0.0.0.0" -U postgres
postgres=# create database no_upgrade;
CREATE DATABASE
postgres=#
```

Then 

note my logging info in the jar has been changed to
```
<Logger name="liquibase" level="INFO"/>
```

```
MB_DB_CONNECTION_URI="postgres://postgres:password@0.0.0.0:5433/no_upgrade" MB_JETTY_PORT=3050 java -jar 0.50.19.jar

...
2024-08-08 16:10:30,587 ERROR liquibase.changelog :: ChangeSet migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:07::calherries encountered an exception.
liquibase.exception.DatabaseException: ERROR: syntax error at or near "("
  Position: 87 [Failed SQL: (0) ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (
  CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END
) STORED]
...
2024-08-08 16:10:30,639 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset migrations/001_update_migrations.yaml::v49.2024-06-27T00:00:07::calherries:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "("
  Position: 87 [Failed SQL: (0) ALTER TABLE metabase_field ADD COLUMN unique_field_helper INTEGER GENERATED ALWAYS AS (
  CASE WHEN is_defective_duplicate = TRUE THEN NULL ELSE (CASE WHEN parent_id IS NULL THEN 0 ELSE parent_id END) END
) STORED]
	at liquibase.command.CommandScope.execute(CommandScope.java:253)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:245)
	at liquibase.Scope.lambda$child$0(Scope.java:186)
...
2024-08-08 16:10:30,641 INFO metabase.core :: Metabase Shutting Down ...
2024-08-08 16:10:30,641 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2024-08-08 16:10:30,646 WARN db.liquibase :: ()
2024-08-08 16:10:30,646 INFO metabase.core :: Metabase Shutdown COMPLETE
```

**Comment by notrom** [comment]
Same as #45367 maybe? Postresql version requirement has been quietly bumped.

**Comment by dkrylovsb** [comment]
Since we are using Postgres 11, are we out of luck with getting a fix for this one? 🙏

**Comment by dpsutton** [comment]
Unfortunately so. Postgres 11 is [no longer supported](https://www.postgresql.org/support/versioning/) and we remove it from our test matrix.
