### ISSUE TITLE
Connection to Spark SQL fails with exception java.lang.NoSuchMethodError in logs

### ISSUE THREAD

**Issue by Interpro-Ahmad** [metabase/metabase#46793]
### Describe the bug

Trying to connect to an apache spark cluster on my local network, and it fails with `'void org.apache.thrift.transport.THttpClient.<init>(java.lang.String, org.apache.http.client.HttpClient)'`.

### To Reproduce

1. Go to '/admin/databases'
2. Click on 'Add database'
3. Fill in required information for connection
4. Press 'Save'
5. 'Save' button changes to 'Failed' and error message appears below

### Expected behavior

Successfully connect to Spark SQL source as it did in 0.47.13.

### Logs

[7fb73f6e-13ed-4d6d-b105-d1f04164d725] 2024-08-13T13:56:51-06:00 ERROR metabase.driver.util Failed to connect to Database,java.lang.NoSuchMethodError: 'void org.apache.thrift.transport.THttpClient.<init>(java.lang.String, org.apache.http.client.HttpClient)',	at org.apache.hive.jdbc.HiveConnection.createHttpTransport(HiveConnection.java:372),	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:341),	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:228),	at metabase.driver.hive_like.fixed_hive_connection.proxy$org.apache.hive.jdbc.HiveConnection$ff19274a.<init>(Unknown Source),	at metabase.driver.hive_like.fixed_hive_connection$fixed_hive_connection.invokeStatic(fixed_hive_connection.clj:9),	at metabase.driver.hive_like.fixed_hive_connection$fixed_hive_connection.invoke(fixed_hive_connection.clj:9),	at metabase.driver.sparksql.SparkSQLDataSource.getConnection(sparksql.clj:96),	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:372),	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274),	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111),	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093),	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182),	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160),	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:349),	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:346),	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_$fn__81580.invoke(connection.clj:358),	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection$fn__81562.invoke(connection.clj:334),	at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:165),	at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154),	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:329),	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:325),	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:357),	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:353),	at metabase.driver.sql_jdbc$fn__109733.invokeStatic(sql_jdbc.clj:49),	at metabase.driver.sql_jdbc$fn__109733.invoke(sql_jdbc.clj:47),	at clojure.lang.MultiFn.invoke(MultiFn.java:234),	at metabase.driver.util$can_connect_with_details_QMARK_$fn__56078.invoke(util.clj:167),	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047),	at clojure.lang.AFn.call(AFn.java:18),	at java.base/java.util.concurrent.FutureTask.run(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source),	at java.base/java.lang.Thread.run(Unknown Source)
[7fb73f6e-13ed-4d6d-b105-d1f04164d725] 2024-08-13T13:56:51-06:00 ERROR metabase.api.database Cannot connect to Database,clojure.lang.ExceptionInfo: 'void org.apache.thrift.transport.THttpClient.<init>(java.lang.String, org.apache.http.client.HttpClient)' {:message "'void org.apache.thrift.transport.THttpClient.<init>(java.lang.String, org.apache.http.client.HttpClient)'"},	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:184),	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:155),	at clojure.lang.RestFn.invoke(RestFn.java:442),	at metabase.api.database$test_database_connection.invokeStatic(database.clj:728),	at metabase.api.database$test_database_connection.doInvoke(database.clj:718),	at clojure.lang.RestFn.invoke(RestFn.java:425),	at metabase.api.database$test_connection_details.invokeStatic(database.clj:782),	at metabase.api.database$test_connection_details.invoke(database.clj:762),	at metabase.api.database$fn__100719.invokeStatic(database.clj:803),	at metabase.api.database$fn__100719.invoke(database.clj:786),	at compojure.core$wrap_response$fn__52905.invoke(core.clj:160),	at compojure.core$wrap_route_middleware$fn__52889.invoke(core.clj:132),	at compojure.core$wrap_route_info$fn__52894.invoke(core.clj:139),	at compojure.core$wrap_route_matches$fn__52898.invoke(core.clj:151),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__52898.invoke(core.clj:152),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917.invoke(core.clj:200),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at metabase.server.middleware.auth$enforce_authentication$fn__97044.invoke(auth.clj:18),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917.invoke(core.clj:200),	at compojure.core$make_context$handler__52945.invoke(core.clj:290),	at compojure.core$make_context$fn__52949.invoke(core.clj:300),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$make_context$fn__52949.invoke(core.clj:301),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$make_context$fn__52949.invoke(core.clj:301),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$make_context$fn__52949.invoke(core.clj:301),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$make_context$fn__52949.invoke(core.clj:301),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$make_context$fn__52949.invoke(core.clj:301),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$make_context$fn__52949.invoke(core.clj:301),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$make_context$fn__52949.invoke(core.clj:301),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$make_context$fn__52949.invoke(core.clj:301),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$make_context$fn__52949.invoke(core.clj:301),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__52898.invoke(core.clj:153),	at clojure.lang.Var.invoke(Var.java:393),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at metabase.api.routes$fn__104631$fn__104634.invoke(routes.clj:73),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917.invoke(core.clj:200),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.core$apply.invokeStatic(core.clj:667),	at clojure.core$apply.invoke(core.clj:662),	at metabase.server.routes$fn__104911$fn__104912.doInvoke(routes.clj:73),	at clojure.lang.RestFn.invoke(RestFn.java:436),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917.invoke(core.clj:200),	at compojure.core$make_context$handler__52945.invoke(core.clj:290),	at compojure.core$make_context$fn__52949.invoke(core.clj:300),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__52898.invoke(core.clj:153),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__52898.invoke(core.clj:153),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__52898.invoke(core.clj:153),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at compojure.core$wrap_route_matches$fn__52898.invoke(core.clj:153),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917$f__52918$respond_SINGLEQUOTE___52919.invoke(core.clj:197),	at metabase.server.routes$fn__104894$fn__104896.invoke(routes.clj:47),	at compojure.core$routes$fn__52917$f__52918.invoke(core.clj:198),	at compojure.core$routes$fn__52917.invoke(core.clj:200),	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__101025.invoke(exceptions.clj:107),	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__101022.invoke(exceptions.clj:96),	at metabase.server.middleware.log$log_api_call$fn__105191$fn__105192$fn__105193.invoke(log.clj:236),	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18),	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12),	at metabase.server.middleware.log$log_api_call$fn__105191$fn__105192.invoke(log.clj:227),	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112),	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103),	at metabase.server.middleware.log$log_api_call$fn__105191.invoke(log.clj:226),	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__108461.invoke(browser_cookie.clj:40),	at metabase.server.middleware.security$add_security_headers$fn__100981.invoke(security.clj:240),	at ring.middleware.json$wrap_json_body$fn__108720.invoke(json.clj:64),	at metabase.server.middleware.offset_paging$handle_paging$fn__87236.invoke(offset_paging.clj:43),	at metabase.server.middleware.json$wrap_streamed_json_response$fn__54437.invoke(json.clj:83),	at ring.middleware.keyword_params$wrap_keyword_params$fn__108809.invoke(keyword_params.clj:55),	at ring.middleware.params$wrap_params$fn__108828.invoke(params.clj:77),	at metabase.server.middleware.misc$maybe_set_site_url$fn__70382.invoke(misc.clj:60),	at metabase.server.middleware.session$reset_session_timeout$fn__77502.invoke(session.clj:552),	at metabase.server.middleware.session$bind_current_user$fn__77468$fn__77469.invoke(session.clj:446),	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:425),	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:408),	at metabase.server.middleware.session$bind_current_user$fn__77468.invoke(session.clj:445),	at metabase.server.middleware.session$wrap_current_user_info$fn__77447.invoke(session.clj:383),	at metabase.server.middleware.session$wrap_session_id$fn__77419.invoke(session.clj:259),	at metabase.server.middleware.auth$wrap_static_api_key$fn__97052.invoke(auth.clj:32),	at ring.middleware.cookies$wrap_cookies$fn__108648.invoke(cookies.clj:200),	at metabase.server.middleware.misc$add_content_type$fn__70364.invoke(misc.clj:28),	at metabase.server.middleware.misc$disable_streaming_buffering$fn__70390.invoke(misc.clj:77),	at ring.middleware.gzip$wrap_gzip$fn__108690.invoke(gzip.clj:86),	at metabase.server.middleware.misc$bind_request$fn__70393.invoke(misc.clj:94),	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__108477.invoke(ssl.clj:41),	at metabase.server$async_proxy_handler$fn__70728.invoke(server.clj:77),	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source),	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173),	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122),	at org.eclipse.jetty.server.Server.handle(Server.java:563),	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598),	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753),	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501),	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287),	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314),	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100),	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277),	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199),	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411),	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969),	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194),	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149),	at java.base/java.lang.Thread.run(Unknown Source),Caused by: java.lang.NoSuchMethodError: 'void org.apache.thrift.transport.THttpClient.<init>(java.lang.String, org.apache.http.client.HttpClient)',	at org.apache.hive.jdbc.HiveConnection.createHttpTransport(HiveConnection.java:372),	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:341),	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:228),	at metabase.driver.hive_like.fixed_hive_connection.proxy$org.apache.hive.jdbc.HiveConnection$ff19274a.<init>(Unknown Source),	at metabase.driver.hive_like.fixed_hive_connection$fixed_hive_connection.invokeStatic(fixed_hive_connection.clj:9),	at metabase.driver.hive_like.fixed_hive_connection$fixed_hive_connection.invoke(fixed_hive_connection.clj:9),	at metabase.driver.sparksql.SparkSQLDataSource.getConnection(sparksql.clj:96),	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:372),	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274),	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111),	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093),	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182),	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160),	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:349),	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:346),	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_$fn__81580.invoke(connection.clj:358),	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection$fn__81562.invoke(connection.clj:334),	at metabase.util.ssh$do_with_ssh_tunnel.invokeStatic(ssh.clj:165),	at metabase.util.ssh$do_with_ssh_tunnel.invoke(ssh.clj:154),	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:329),	at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:325),	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:357),	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:353),	at metabase.driver.sql_jdbc$fn__109733.invokeStatic(sql_jdbc.clj:49),	at metabase.driver.sql_jdbc$fn__109733.invoke(sql_jdbc.clj:47),	at clojure.lang.MultiFn.invoke(MultiFn.java:234),	at metabase.driver.util$can_connect_with_details_QMARK_$fn__56078.invoke(util.clj:167),	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047),	at clojure.lang.AFn.call(AFn.java:18),	at java.base/java.util.concurrent.FutureTask.run(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source),	... 1 more
[7fb73f6e-13ed-4d6d-b105-d1f04164d725] 2024-08-13T13:56:51-06:00 DEBUG metabase.server.middleware.log POST /api/database 400 1.0 s (1 DB calls) {:metabase-user-id 1} 
{:message "'void org.apache.thrift.transport.THttpClient.<init>(java.lang.String, org.apache.http.client.HttpClient)'"}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.15.153.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.7"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    },
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-08-06",
      "tag": "v0.50.19",
      "hash": "0b97bf8"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

### Severity

blocking an upgrade

### Additional context

Screenshot including error at bottom:
![image](https://github.com/user-attachments/assets/48d0941b-3038-4313-9301-433c15121188)

**Comment by crisptrutski** [comment]
I don't believe that we've updated our hive version since 47, but passing on to our drivers team to follow up.

**Comment by lbrdnk** [comment]
1. This specific error is shown with `transportMode=http` option set.
2. Properties passed to `HiveConnection` (see the `metabase.driver.hive-like.fixed-hive-connection` ns) seems to contain kv pairs used by Metabase, not mean for the connection connection (eg. `advanced-options`).

```
{"let-user-control-scheduling" "false", "password" "asdf", "advanced-options" "true", "dbname" "xix", "tunnel-enabled" "false", "engine" "sparksql", "user" "xix"}
```

**Comment by Charonxin** [comment]
I met the same problem just now, when will this problem been fixed? Before the problem has been fixed, is there any other way to connect to apache hive using metabase?

**Comment by guicailiao** [comment]
we mee the same issue: https://github.com/metabase/metabase/issues/46793

**Comment by guicailiao** [comment]
Tried `transportMode=binary`, it did unblock us for using sparksql.

**Comment by EVRAZ-ahmad** [comment]
Still interested in a resolution to this issue.  replacing transportMode=http with transportMode=binary as @guicailiao suggested on my installation changes my error from the nondescript 'void org.apache.thrift.transport.THttpClient.<init>(java.lang.String, org.apache.http.client.HttpClient)' to "Could not open client transport with JDBC Uri: jdbc:hive2://<ip address>/default;transportMode=binary;httpPath=lakehouse/process-data: Invalid status 72", while the connection with the original parameters still works on metabase v0.47.13
