### ISSUE TITLE
Combined card fails on scheduled subscription (not on the "send now" test)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#46892]
### Describe the bug

Combining 2 cards make the subscription to fail, but only if the subscription is scheduled, not when you click the "send now" button

### To Reproduce

1) create 2 questions: sum of total per month and sum of subtotal per month
2) combine those on the dashboard
3) create a subscription, but schedule it, don't send it with the send now button

### Expected behavior

It should work both on the send now and the scheduled subscription

### Logs

```
2024-08-15 15:00:00,080 ERROR pulse.render :: Pulse card render error
clojure.lang.ExceptionInfo: You don't have permissions to do that. {:status-code 403}
	at metabase.api.common$check_one.invokeStatic(common.clj:106)
	at metabase.api.common$check_one.invoke(common.clj:100)
	at metabase.api.common$check.invokeStatic(common.clj:136)
	at metabase.api.common$check.doInvoke(common.clj:109)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at metabase.api.common$check_403.invokeStatic(common.clj:238)
	at metabase.api.common$check_403.invoke(common.clj:235)
	at metabase.api.common$read_check$fn__53247.invoke(common.clj:461)
	at metabase.api.common$read_check.invokeStatic(common.clj:460)
	at metabase.api.common$read_check.invoke(common.clj:453)
	at metabase.api.common$read_check.invokeStatic(common.clj:470)
	at metabase.api.common$read_check.invoke(common.clj:453)
	at metabase.query_processor.dashboard$process_query_for_dashcard.invokeStatic(dashboard.clj:180)
	at metabase.query_processor.dashboard$process_query_for_dashcard.doInvoke(dashboard.clj:163)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at metabase.pulse.util$execute_dashboard_subscription_card$result_fn__102112.invoke(util.clj:76)
	at clojure.core$comp$fn__5876.invoke(core.clj:2586)
	at clojure.core$map$fn__5935.invoke(core.clj:2770)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$map$fn__5935.invoke(core.clj:2763)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$map$fn__5935.invoke(core.clj:2763)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.lang.RT.nthFrom(RT.java:982)
	at clojure.lang.RT.nth(RT.java:940)
	at medley.core$distinct_by$step__10981$fn__10982$fn__10984.invoke(core.cljc:294)
	at medley.core$distinct_by$step__10981$fn__10982.invoke(core.cljc:294)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:713)
	at clojure.core$next__5451.invokeStatic(core.clj:64)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:169)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6887)
	at clojure.core$reduce.invoke(core.clj:6869)
	at cheshire.generate$generate.invokeStatic(generate.clj:133)
	at cheshire.generate$generate.invoke(generate.clj:119)
	at cheshire.core$generate_string.invokeStatic(core.clj:74)
	at cheshire.core$generate_string.invoke(core.clj:49)
	at cheshire.core$generate_string.invokeStatic(core.clj:55)
	at cheshire.core$generate_string.invoke(core.clj:49)
	at metabase.pulse.render.js_svg$javascript_visualization.invokeStatic(js_svg.clj:152)
	at metabase.pulse.render.js_svg$javascript_visualization.invoke(js_svg.clj:148)
	at metabase.pulse.render.body$fn__74253$_AMPERSAND_f__74254.invoke(body.clj:555)
	at metabase.pulse.render.body$fn__74253$fn__74261.invoke(body.clj:545)
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
	at metabase.pulse.render$render_pulse_card_body.invokeStatic(render.clj:144)
	at metabase.pulse.render$render_pulse_card_body.invoke(render.clj:130)
	at metabase.pulse.render$render_pulse_card.invokeStatic(render.clj:171)
	at metabase.pulse.render$render_pulse_card.invoke(render.clj:154)
	at metabase.pulse.render$render_pulse_section$fn__74649.invoke(render.clj:207)
	at metabase.pulse.render$render_pulse_section.invokeStatic(render.clj:205)
	at metabase.pulse.render$render_pulse_section.invoke(render.clj:201)
	at metabase.email.messages$render_part.invokeStatic(messages.clj:442)
	at metabase.email.messages$render_part.invoke(messages.clj:438)
	at metabase.email.messages$render_message_body$fn__75617$fn__75618.invoke(messages.clj:495)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6980)
	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6887)
	at clojure.core$mapv.invokeStatic(core.clj:6971)
	at clojure.core$mapv.invoke(core.clj:6971)
	at metabase.email.messages$render_message_body$fn__75617.invoke(messages.clj:495)
	at metabase.email.messages$render_message_body.invokeStatic(messages.clj:494)
	at metabase.email.messages$render_message_body.invoke(messages.clj:492)
	at metabase.email.messages$render_pulse_email.invokeStatic(messages.clj:521)
	at metabase.email.messages$render_pulse_email.invoke(messages.clj:518)
	at metabase.pulse$fn__102307.invokeStatic(pulse.clj:414)
	at metabase.pulse$fn__102307.invoke(pulse.clj:403)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.pulse$parts__GT_notifications$iter__102382__102386$fn__102387$fn__102388.invoke(pulse.clj:485)
	at metabase.pulse$parts__GT_notifications$iter__102382__102386$fn__102387.invoke(pulse.clj:483)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core$seq__5467.invoke(core.clj:139)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:538)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:537)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:566)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:546)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at metabase.task.send_pulses$send_pulse_BANG_$fn__111696.invoke(send_pulses.clj:57)
	at metabase.models.task_history$do_with_task_history.invokeStatic(task_history.clj:116)
	at metabase.models.task_history$do_with_task_history.invoke(task_history.clj:105)
	at metabase.task.send_pulses$send_pulse_BANG_.invokeStatic(send_pulses.clj:52)
	at metabase.task.send_pulses$send_pulse_BANG_.invoke(send_pulses.clj:49)
	at metabase.task.send_pulses$send_pulse_BANG__STAR_.invokeStatic(send_pulses.clj:125)
	at metabase.task.send_pulses$send_pulse_BANG__STAR_.invoke(send_pulses.clj:116)
	at metabase.task.send_pulses.SendPulse.execute(send_pulses.clj:147)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

### Information about your Metabase installation

```JSON
v50.19
```

### Severity

P1

### Additional context

Regression maybe?

**Comment by qnkhuat** [comment]
Regression introduced in https://github.com/metabase/metabase/pull/43428
