### ISSUE TITLE
JDBC connection setup on startup, but fail to run SQL with overflow call to c3p0 checkoutResource

### ISSUE THREAD

**Issue by jovezhong** [metabase/metabase#47207]
### Describe the bug

Hi there, I am developing/updating a custom driver https://github.com/timeplus-io/metabase-proton-driver. The https://github.com/timeplus-io/metabase-proton-driver/releases/tag/v0.50.4 works with metabase 0.50.x but doesn't work with our latest database. After I upgraded the database jar file, I got overflow of `BasicResourcePool.checkoutResource`
```
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594) ~[metabase.jar:?]
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594) ~[metabase.jar:?]
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594) ~[metabase.jar:?]
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594) ~[metabase.jar:?]
```
However, if I define a database connection, restart the metabase server, from the server log, I can tell the JDBC connection was setup
```
2024-08-25 12:00:53,664 [main] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.5 [built 11-December-2019 22:18:33 -0800; debug? true; trace: 10]
2024-08-25 12:00:57,555 [main] INFO metabase.core - Starting Metabase version v0.50.21 (ec9f5d7) ...
2024-08-25 12:00:57,558 [main] INFO metabase.core - System info:
 {"file.encoding" "UTF-8",
 "java.runtime.name" "OpenJDK Runtime Environment",
 "java.runtime.version" "17.0.12+7",
 "java.vendor" "Eclipse Adoptium",
 "java.vendor.url" "https://adoptium.net/",
 "java.version" "17.0.12",
 "java.vm.name" "OpenJDK 64-Bit Server VM",
 "java.vm.version" "17.0.12+7",
 "os.name" "Mac OS X",
 "os.version" "14.6.1",
 "user.language" "en",
 "user.timezone" "America/Vancouver"}
2024-08-25 12:00:57,988 [main] DEBUGcom.mchange.v2.resourcepool.BasicResourcePool - acquire test -- pool size: 0; target_pool_size: 1; desired target? 1
2024-08-25 12:00:57,988 [main] DEBUGcom.mchange.v2.resourcepool.BasicResourcePool - awaitAvailable(): [unknown]
2024-08-25 12:00:57,997 [C3P0PooledConnectionPoolManager[identityToken->z8kfltb512jk5qxyxbuky|75332dcf, dataSourceName->metabase-h2-app-db]-HelperThread-#0] DEBUGcom.timeplus.proton.jdbc.ProtonDriver - Proton Driver 0.7.1.0(JDBC: 4.2.0.0) registered
2024-08-25 12:00:59,238 [clojure-agent-send-off-pool-1] INFO metabase.driver.impl - [33mInitializing driver :proton...[0m
2024-08-25 12:00:59,238 [clojure-agent-send-off-pool-1] INFO metabase.plugins.classloader - Added URL file:/Users/jove/Dev/metabase_0.50.21/plugins/proton-driver-0.50.5.jar to classpath
2024-08-25 12:00:59,433 [clojure-agent-send-off-pool-1] TRACEmetabase.driver.proton - connection-details->spec* called with details: {:host localhost, :port 8123}
2024-08-25 12:00:59,439 [clojure-agent-send-off-pool-1] DEBUGcom.timeplus.proton.jdbc.internal.ProtonConnectionImpl - Creating a new connection to jdbc:proton:http://localhost:8123/default
2024-08-25 12:00:59,451 [clojure-agent-send-off-pool-1] DEBUGcom.timeplus.proton.client.AbstractClient - Connection established: com.timeplus.proton.client.http.HttpUrlConnectionImpl@6056d88b
```

But when I run a query say `select 95` with this data source in metabase, I got a lot of stack traces, keeping calling `BasicResourcePool.checkoutResource`

```
2024-08-25 12:01:32,422 [streaming-response-thread-pool-1] DEBUGcom.timeplus.proton.client.AbstractClient - Connecting to: ProtonNode(addr=http:localhost/<unresolved>:8123, db=default)@394117274
2024-08-25 12:01:32,423 [streaming-response-thread-pool-1] DEBUGcom.timeplus.proton.client.AbstractClient - Connection established: com.timeplus.proton.client.http.HttpUrlConnectionImpl@7fdd053e
2024-08-25 12:01:32,423 [streaming-response-thread-pool-1] DEBUGcom.mchange.v2.resourcepool.BasicResourcePool - A resource could not be refurbished for checkout. [com.mchange.v2.c3p0.impl.NewPooledConnection@62113eb]
java.sql.SQLException: Connection is invalid
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:573) ~[metabase.jar:?]
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:464) ~[metabase.jar:?]
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishResourceOnCheckout(C3P0PooledConnectionPool.java:339) ~[metabase.jar:?]
	at com.mchange.v2.resourcepool.BasicResourcePool.attemptRefurbishResourceOnCheckout(BasicResourcePool.java:1771) [metabase.jar:?]
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:558) [metabase.jar:?]
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758) [metabase.jar:?]
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685) [metabase.jar:?]
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:336) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:320) [metabase.jar:?]
	at metabase.driver.proton$eval1448$fn__1450.invoke(proton.clj:78) [?:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:244) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:707) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:704) [metabase.jar:?]
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:693) [metabase.jar:?]
	at metabase.driver.sql_jdbc$fn__110077.invokeStatic(sql_jdbc.clj:78) [metabase.jar:?]
	at metabase.driver.sql_jdbc$fn__110077.invoke(sql_jdbc.clj:76) [metabase.jar:?]
	at clojure.lang.MultiFn.invoke(MultiFn.java:244) [metabase.jar:?]
	at metabase.query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47) [metabase.jar:?]
	at metabase.query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34) [metabase.jar:?]
	at metabase.query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97) [metabase.jar:?]
	at metabase.query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90) [metabase.jar:?]
	at metabase.query_processor.execute$run.invokeStatic(execute.clj:60) [metabase.jar:?]
	at metabase.query_processor.execute$run.invoke(execute.clj:54) [metabase.jar:?]
	at metabase.query_processor.middleware.update_used_cards$update_used_cards_BANG_$fn__70549.invoke(update_used_cards.clj:58) [metabase.jar:?]
	at metabase.query_processor.execute$add_native_form_to_result_metadata$fn__70564.invoke(execute.clj:23) [metabase.jar:?]
	at metabase.query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__70569.invoke(execute.clj:34) [metabase.jar:?]
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___70522.invoke(cache.clj:242) [metabase.jar:?]
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__64370.invoke(permissions.clj:119) [metabase.jar:?]
	at metabase.query_processor.middleware.enterprise$check_download_permissions_middleware$fn__64980.invoke(enterprise.clj:51) [metabase.jar:?]
	at metabase.query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__64990.invoke(enterprise.clj:64) [metabase.jar:?]
	at metabase.query_processor.execute$execute$fn__70596.invoke(execute.clj:92) [metabase.jar:?]
	at metabase.query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:225) [metabase.jar:?]
	at metabase.query_processor.setup$do_with_qp_setup.invoke(setup.clj:216) [metabase.jar:?]
	at metabase.query_processor.execute$execute.invokeStatic(execute.clj:91) [metabase.jar:?]
	at metabase.query_processor.execute$execute.invoke(execute.clj:87) [metabase.jar:?]
	at metabase.query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47) [metabase.jar:?]
	at metabase.query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:43) [metabase.jar:?]
	at metabase.query_processor.middleware.enterprise$fn__65007$handle_audit_app_internal_queries__65008$fn__65010.invoke(enterprise.clj:96) [metabase.jar:?]
	at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__65018.invoke(enterprise.clj:103) [metabase.jar:?]
	at metabase.query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__76360.invoke(process_userland_query.clj:202) [metabase.jar:?]
	at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__76429.invoke(catch_exceptions.clj:128) [metabase.jar:?]
	at metabase.query_processor$process_query$fn__76466.invoke(query_processor.clj:78) [metabase.jar:?]
	at metabase.query_processor.setup$do_with_canceled_chan$fn__65422.invoke(setup.clj:189) [metabase.jar:?]
	at metabase.query_processor.setup$do_with_database_local_settings$fn__65417.invoke(setup.clj:181) [metabase.jar:?]
	at metabase.query_processor.setup$do_with_driver$fn__65412$fn__65413.invoke(setup.clj:166) [metabase.jar:?]
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:105) [metabase.jar:?]
	at metabase.driver$do_with_driver.invoke(driver.clj:100) [metabase.jar:?]
	at metabase.query_processor.setup$do_with_driver$fn__65412.invoke(setup.clj:165) [metabase.jar:?]
	at metabase.query_processor.setup$do_with_metadata_provider$fn__65405$fn__65408.invoke(setup.clj:151) [metabase.jar:?]
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:171) [metabase.jar:?]
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:151) [metabase.jar:?]
	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:160) [metabase.jar:?]
	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:151) [metabase.jar:?]
	at metabase.query_processor.setup$do_with_metadata_provider$fn__65405.invoke(setup.clj:150) [metabase.jar:?]
	at metabase.query_processor.setup$do_with_resolved_database$fn__65399.invoke(setup.clj:128) [metabase.jar:?]
	at metabase.query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232) [metabase.jar:?]
	at metabase.query_processor.setup$do_with_qp_setup.invoke(setup.clj:216) [metabase.jar:?]
	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:76) [metabase.jar:?]
	at metabase.query_processor$process_query.invoke(query_processor.clj:69) [metabase.jar:?]
	at metabase.api.dataset$run_streaming_query$fn__97277.invoke(dataset.clj:84) [metabase.jar:?]
	at metabase.query_processor.streaming$_streaming_response$fn__68924$fn__68925$fn__68926.invoke(streaming.clj:175) [metabase.jar:?]
	at metabase.query_processor.streaming$_streaming_response$fn__68924$fn__68925.invoke(streaming.clj:174) [metabase.jar:?]
	at metabase.query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165) [metabase.jar:?]
	at metabase.query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152) [metabase.jar:?]
	at metabase.query_processor.streaming$_streaming_response$fn__68924.invoke(streaming.clj:171) [metabase.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) [metabase.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) [metabase.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:667) [metabase.jar:?]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990) [metabase.jar:?]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990) [metabase.jar:?]
	at clojure.lang.RestFn.applyTo(RestFn.java:142) [metabase.jar:?]
	at clojure.core$apply.invokeStatic(core.clj:671) [metabase.jar:?]
	at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020) [metabase.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:421) [metabase.jar:?]
	at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:68) [metabase.jar:?]
	at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:66) [metabase.jar:?]
	at metabase.async.streaming_response$do_f_async$task__52241.invoke(streaming_response.clj:87) [metabase.jar:?]
	at clojure.lang.AFn.run(AFn.java:22) [metabase.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```

### To Reproduce

1. have 0.50.21 metabase.jar in a folder
2. put the `proton-driver-0.50.5.jar` and `proton-jdbc-0.7.1-shaded.jar` in the plugins folder
3. set the log4j2.xml as following

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
  <Appenders>
    <Console name="STDOUT" target="SYSTEM_OUT" follow="true">
      <PatternLayout pattern="%date %level %logger{2} :: %message%n%throwable">
        <replace regex=":basic-auth \\[.*\\]" replacement=":basic-auth [redacted]"/>
      </PatternLayout>
    </Console>

    <!-- This file appender is provided as an example -->
    <RollingFile name="FILE" fileName="${logfile.path}/metabase.log" filePattern="${logfile.path}/metabase.log.%i">
      <Policies>
        <SizeBasedTriggeringPolicy size="500 MB"/>
      </Policies>
      <DefaultRolloverStrategy max="2"/>
      <PatternLayout pattern="%d [%t] %-5p %c - %m%n">
        <replace regex=":basic-auth \\[.*\\]" replacement=":basic-auth [redacted]"/>
      </PatternLayout>
    </RollingFile>
  </Appenders>

  <Loggers>
    <Logger name="com.mchange" level="INFO"/>
    <Logger name="liquibase" level="ERROR"/>
    <Logger name="metabase" level="INFO"/>
    <Logger name="metabase-enterprise" level="INFO"/>
    <Logger name="metabase.metabot" level="DEBUG"/>
    <Logger name="metabase.plugins" level="DEBUG"/>

    <Logger name="metabase.driver.sql" level="TRACE"/>
    <Logger name="metabase.driver.sql-jdbc" level="TRACE"/>
    <Logger name="metabase.driver.sql_jdbc" level="TRACE"/>
    <Logger name="metabase.driver.proton" level="TRACE"/>
    <Logger name="metabase.driver.proton_introspection" level="TRACE"/>
    <Logger name="metabase.driver.proton_qp" level="TRACE"/>
    <Logger name="metabase.driver.proton_version" level="TRACE"/>
    <Logger name="com.timeplus.proton" level="TRACE"/>
    <Logger name="com.mchange.v2.resourcepool.BasicResourcePool" level="DEBUG"/>

    <Logger name="sun.net.www.protocol.http" level="ERROR"/>

    <Logger name="metabase.query-processor.async" level="DEBUG"/>
    <Logger name="metabase.server.middleware" level="DEBUG"/>
    <Logger name="org.quartz" level="INFO"/>
    <Logger name="net.snowflake.client.jdbc.SnowflakeConnectString" level="ERROR"/>

    <Root level="WARN">
      <AppenderRef ref="STDOUT"/>
      <AppenderRef ref="FILE"/>
    </Root>
  </Loggers>
</Configuration>

```

Get the Timeplus proton via `https://install.timeplus.com/oss | sh`, run it with `./proton server`

### Expected behavior

Able to run SQL

### Logs

[metabase.log](https://github.com/user-attachments/files/16741665/metabase.log)

### Information about your Metabase installation

```JSON
c3p0-0.9.5.5
Metabase v0.50.21 (ec9f5d7)
JDK 17.0.12+7
[Timeplus Proton 1.5.16](https://github.com/timeplus-io/proton)
```

### Severity

Medium

**Comment by jovezhong** [comment]
The related c3p0 code is https://github.com/swaldman/c3p0/blob/5640dcc2e3e216953325c9ed7059626e735e5032/src/java/com/mchange/v2/c3p0/impl/C3P0PooledConnectionPool.java#L758 I am not sure what the reason behind `Connection is invalid`

**Comment by paoliniluis** [comment]
Hi @jovezhong, first of all I wanted to thank you for developing a driver for Metabase. A few things that come to my mind:
1) please remember to always use Java 11, as we don't support Java 17 yet and you might run into some issues
2) c3p0 performs a check on every connection checkout. I'm seeing that you're doing "SELECT count(*) > 0 FROM system.databases WHERE name = ?" on your driver, does that query returns something? https://github.com/timeplus-io/metabase-proton-driver/blob/b007cb3c0bde6ae7d19bb4f341f66e50b83a0333/src/metabase/driver/proton.clj#L145

**Comment by jovezhong** [comment]
Hi @paoliniluis , thanks for the comment.  I did switch to JDK 11 (`sdk use java 11.0.24-tem`) But I hit the same issue.

According to the log, this `(defmethod driver/can-connect? :proton` is not called. I don't see either `can-connect` tracing message or the SQL statement.

I am attaching the log, at line 1857, the Proton JDBC connection established, but then C3P0PooledConnectionPool failed to test the connection on CHECKOUT
```
2024-08-26 20:33:42,011 [streaming-response-thread-pool-1] DEBUG com.timeplus.proton.client.AbstractClient - Connection established: com.timeplus.proton.client.http.HttpUrlConnectionImpl@1488b00e
2024-08-26 20:33:42,012 [streaming-response-thread-pool-1] DEBUG com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool - Test of PooledConnection [com.mchange.v2.c3p0.impl.NewPooledConnection@798dd782] on CHECKOUT has FAILED.
java.sql.SQLException: Connection is invalid
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:573) ~[metabase.jar:?]
```
[metabase5.log.zip](https://github.com/user-attachments/files/16756148/metabase5.log.zip)

**Comment by snoe** [comment]
Hi @jovezhong, it looks like you're using `sql-jdbc.execute/do-with-connection-with-options` in your `can-connect?` implementation. Unfortunately that functions requires an already established connection pool, and so you're seeing these repeated calls and failures.

[You can see](https://github.com/metabase/metabase/blob/master/src/metabase/driver/sql_jdbc/connection.clj#L356) that `sql-jdbc/can-connect?` uses `sql-jdbc.conn/with-connection-spec-for-testing-connection` which gives you a connection that is not pooled for this purpose..

**Comment by jovezhong** [comment]
Hi @snoe , thanks for looking into this. Really appreciate your help.

In this commit https://github.com/timeplus-io/metabase-proton-driver/commit/fee9ebe2ef7351cfe32e1108bb563a7381de5d08 I changed `sql-jdbc.execute/do-with-connection-with-options` to `sql-jdbc.conn/do-with-connection-spec-for-testing-connection` but still got similar error.

Not sure whether I should update `(defmethod sql-jdbc.execute/do-with-connection-with-options :proton` to avoid using `sql-jdbc.execute/do-with-resolved-connection`

Error Log

> 2024-09-11 18:16:54,713 [C3P0PooledConnectionPoolManager[identityToken->z8kfltb51r7dnwb11x0ops|560a04ca, dataSourceName->db-2-proton-null]-HelperThread-#2] TRACE com.mchange.v2.c3p0.impl.NewPooledConnection - com.mchange.v2.c3p0.impl.NewPooledConnection@5a769501 closed by a client.
> java.lang.Exception: DEBUG -- CLOSE BY CLIENT STACK TRACE
> 	at com.mchange.v2.c3p0.impl.NewPooledConnection.close(NewPooledConnection.java:659) [metabase.jar:?]
> 	at com.mchange.v2.c3p0.impl.NewPooledConnection.closeMaybeCheckedOut(NewPooledConnection.java:255) [metabase.jar:?]
> 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.destroyResource(C3P0PooledConnectionPool.java:622) [metabase.jar:?]
> 	at com.mchange.v2.resourcepool.BasicResourcePool$1DestroyResourceTask.run(BasicResourcePool.java:1114) [metabase.jar:?]
> 	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696) [metabase.jar:?]
> 2024-09-11 18:16:54,692 [streaming-response-thread-pool-1] DEBUG com.mchange.v2.resourcepool.BasicResourcePool - A resource could not be refurbished for checkout. [com.mchange.v2.c3p0.impl.NewPooledConnection@53c95052]
> java.sql.SQLException: Connection is invalid
> 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.finerLoggingTestPooledConnection(C3P0PooledConnectionPool.java:458) ~[metabase.jar:?]
> 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.finerLoggingTestPooledConnection(C3P0PooledConnectionPool.java:444) ~[metabase.jar:?]
> 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishResourceOnCheckout(C3P0PooledConnectionPool.java:337) ~[metabase.jar:?]
> 	at com.mchange.v2.resourcepool.BasicResourcePool.attemptRefurbishResourceOnCheckout(BasicResourcePool.java:1771) [metabase.jar:?]
> 	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:558)
> 	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594) [metabase.jar:?]
> 	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594) [metabase.jar:?]
> 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758) [metabase.jar:?]
> 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685) [metabase.jar:?]
> 	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140) [metabase.jar:?]
> 	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:336) [metabase.jar:?]
> 	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:320) [metabase.jar:?]
> 	at metabase.driver.proton$eval1956$fn__1958.invoke(proton.clj:78) [?:?]

**Comment by jovezhong** [comment]
Here is the first 1000 lines of log [head1000.log](https://github.com/user-attachments/files/16972149/head1000.log) for your reference.

There are a quite a few SQL have been executed when the server started(I created the data source last startup) But when I ran a `select now()` testing query in the sql editor, it failed to validate the connection

> 2024-09-11 18:33:48,682 [clojure-agent-send-off-pool-1] DEBUG com.timeplus.proton.client.http.ProtonHttpClient - Query: select current_user(), timezone(), version(), if_null((select to_uint8(value) from system.settings where name='readonly'), 0) AS readonly FORMAT RowBinaryWithNamesAndTypes
> 
> 2024-09-11 18:33:48,711 [clojure-agent-send-off-pool-1] DEBUG com.timeplus.proton.client.http.ProtonHttpClient - Query: SELECT value='1' FROM system.settings WHERE name='cloud_mode'
> 
> 2024-09-11 18:33:48,719 [clojure-agent-send-off-pool-1] DEBUG com.timeplus.proton.client.http.ProtonHttpClient - Query: select current_user(), timezone(), version(), if_null((select to_uint8(value) from system.settings where name='readonly'), 0) AS readonly FORMAT RowBinaryWithNamesAndTypes
> 
> 2024-09-11 18:33:48,721 [clojure-agent-send-off-pool-1] DEBUG com.timeplus.proton.client.http.ProtonHttpClient - Query: WITH s AS (SELECT version() AS ver, split_by_char('.', ver) AS verSplit) SELECT s.ver, to_int32(verSplit[1]), to_int32(verSplit[2]) FROM s
> 
> 2024-09-11 18:33:48,729 [clojure-agent-send-off-pool-1] DEBUG com.timeplus.proton.client.http.ProtonHttpClient - Query: SELECT value='1' FROM system.settings WHERE name='cloud_mode'
> 
> 2024-09-11 18:33:48,733 [clojure-agent-send-off-pool-1] DEBUG com.timeplus.proton.client.http.ProtonHttpClient - Query: WITH s AS (SELECT version() AS ver, split_by_char('.', ver) AS verSplit) SELECT s.ver, to_int32(verSplit[1]), to_int32(verSplit[2]) FROM s

**Comment by paoliniluis** [comment]
Can you check again in 52.5?

**Comment by jovezhong** [comment]
Thanks for the comment, we plan to try to use latest metabase later this month

**Comment by jovezhong** [comment]
Hi @luizarakaki , thanks for reporting this.

Today I spent some time updating our metabase driver. Since our upstream is https://github.com/ClickHouse/metabase-clickhouse-driver and their latest version is based on `METABASE_VERSION=v0.51.1.2`, so I am using their codebase to support our system, basically a set of function and data type renaming. You can refer to https://github.com/timeplus-io/metabase-proton-driver/blob/mb.51/RELEASE.md, or check the change history in the `mb.51` branch.

It passed the `lein check` static check. I setup a local metabase with the compiled plugin and start it. After login and go to the admin page to create a data. I chose Proton and set the host/username/password. Click on the Save button will hit the connection pool issue again:

>  at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:594)

**Comment by jovezhong** [comment]
Here is the log file(4.5MB after compression, 280MB raw)

[metabase.log.zip](https://github.com/user-attachments/files/18384278/metabase.log.zip)

Line 291, I sent a query `select 1`

Line 317

> 2025-01-11 04:47:34,917 [streaming-response-thread-pool-1] DEBUG com.timeplus.proton.client.AbstractClient - Connection established: com.timeplus.proton.client.http.HttpUrlConnectionImpl@1bd56092

But in the next few lines

> 2025-01-11 04:47:34,918 [streaming-response-thread-pool-1] DEBUG com.mchange.v2.resourcepool.BasicResourcePool - A resource could not be refurbished for checkout. [com.mchange.v2.c3p0.impl.NewPooledConnection@31d6ddd5]
java.sql.SQLException: Connection is invalid
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:573) ~[metabase.jar:?]

then keep repeating the process: Connection established -> A resource could not be refurbished for checkout -> Connection is invalid

Please help. Many thanks.

**Comment by dragonsahead** [comment]
@jovezhong do you still see this?
