### ISSUE TITLE
Error During Migration from H2 to PostgreSQL: “Unable to connect to Metabase H2 DB”

### ISSUE THREAD

**Issue by nb1907** [metabase/metabase#47760]
**Context**
Migration issues from H2 to PostgreSQL.

Hello Team,

Following the official documentation, I’m attempting to migrate my Metabase setup from H2 to PostgreSQL. I was using a Docker container for this process and took a backup of my H2 database before starting the migration.

When I run the migration command:
java -jar metabase.jar load-from-h2 /path/to/metabase.db

I encounter the following error:
clojure.lang.ExceptionInfo: ERROR Set up h2 source database and run migrations...: Unable to connect to Metabase h2 DB. {}
at metabase.cmd.copy$do_step$fn__100134.invoke(copy.clj:34)
at metabase.cmd.copy$do_step.invokeStatic(copy.clj:30)
at metabase.cmd.copy$do_step.invoke(copy.clj:28)
at metabase.cmd.copy$copy_BANG_.invokeStatic(copy.clj:393)
at metabase.cmd.copy$copy_BANG_.invoke(copy.clj:383)
at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:35)
at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:25)
at clojure.lang.Var.invoke(Var.java:384)
at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:74)
at metabase.cmd$load_from_h2.invoke(cmd.clj:68)
at clojure.lang.AFn.applyToHelper(AFn.java:154)
at clojure.lang.AFn.applyTo(AFn.java:144)
at clojure.core$apply.invokeStatic(core.clj:667)
at clojure.core$apply.invoke(core.clj:662)
at metabase.cmd$run_cmd$fn__107764.invoke(cmd.clj:313)
at metabase.cmd$run_cmd.invokeStatic(cmd.clj:310)
at metabase.cmd$run_cmd.invoke(cmd.clj:300)
at clojure.lang.Var.invoke(Var.java:393)
at metabase.core$run_cmd.invokeStatic(core.clj:193)
at metabase.core$run_cmd.invoke(core.clj:191)
at metabase.core$entrypoint.invokeStatic(core.clj:215)
at metabase.core$entrypoint.doInvoke(core.clj:210)
at clojure.lang.RestFn.applyTo(RestFn.java:137)
at clojure.lang.Var.applyTo(Var.java:705)
at clojure.core$apply.invokeStatic(core.clj:667)
at clojure.core$apply.invoke(core.clj:662)
at metabase.bootstrap$<em>main.invokeStatic(bootstrap.clj:31)
at metabase.bootstrap$<em>main.doInvoke(bootstrap.clj:28)
at clojure.lang.RestFn.applyTo(RestFn.java:137)
at metabase.bootstrap.main(Unknown Source)
Caused by: clojure.lang.ExceptionInfo: Unable to connect to Metabase h2 DB. {}
at metabase.db.setup$verify_db_connection$fn__53455.invoke(setup.clj:117)
at metabase.db.setup$verify_db_connection.invokeStatic(setup.clj:115)
at metabase.db.setup$verify_db_connection.invoke(setup.clj:107)
at metabase.db.setup$setup_db_BANG</em>$fn__53475$fn__53476.invoke(setup.clj:165)
at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
at metabase.db.setup$setup_db_BANG</em>$fn__53475.invoke(setup.clj:161)
at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
at metabase.cmd.copy$copy_BANG_$fn__100326.invoke(copy.clj:394)
at metabase.cmd.copy$do_step$fn__100134.invoke(copy.clj:31)
... 29 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database "/home/metabase/metabase.db" not found, and IFEXISTS=true, so we cant auto-create it [90146-214]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
at org.h2.message.DbException.get(DbException.java:223)
at org.h2.message.DbException.get(DbException.java:199)
at org.h2.engine.Engine.throwNotFound(Engine.java:186)
at org.h2.engine.Engine.openSession(Engine.java:72)
at org.h2.engine.Engine.openSession(Engine.java:222)
at org.h2.engine.Engine.createSession(Engine.java:201)
at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
at org.h2.jdbc.JdbcConnection.(JdbcConnection.java:122)
at org.h2.Driver.connect(Driver.java:59)
at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
at metabase.db.data_source.DataSource.getConnection(data_source.clj:79)
at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:372)
at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:349)
at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:346)
at clojure.lang.Var.invoke(Var.java:384)
at metabase.db.setup$verify_db_connection$fn__53455.invoke(setup.clj:115)
... 39 more
Command failed with exception: ERROR Set up h2 source database and run migrations...: Unable to connect to Metabase h2 DB.

It appears that Metabase cannot locate the H2 database file. I've confirmed that the file exists at the specified path and that Docker volumes are correctly set up. Despite this, the error persists.

Has anyone else encountered this issue or have any insights into what might be going wrong? I’d appreciate any guidance or solutions you might have!

Thank you!

**Comment by paoliniluis** [comment]
99% of the times this happened it was due to permissions, what's the file permissions?

**Comment by nb1907** [comment]
These are the file permissions that I have and also tried after changing it even though faced the same error. 


ls -l /home/nitin/Downloads/metabase2.db/metabase2.db/metabase.db.mv.db
-rw-r--r-- 1 nitin nitin 251797504 Sep  3 13:50 /home/nitin/Downloads/metabase2.db/metabase2.db/metabase.db.mv.db


ls -l /home/nitin/Downloads/metabase2.db/metabase2.db
-rw-r--r-- 1 nitin nitin 251797504 Sep  3 13:50 metabase.db.mv.db
-rw-r--r-- 1 nitin nitin    271295 Sep  5 11:27 metabase.db.trace.db

**Comment by paoliniluis** [comment]
well... the logs say that we're looking for /home/metabase/metabase.db and you sent some paths that are different from that

**Comment by nb1907** [comment]
Yes, you're right! but I tried with the right path and also created a separate folder for it even though I faced the similar error here is the complete information of the new folder from which I tried to migrate.

Commands which I run for db_connection: 
export MB_DB_TYPE=postgres
export MB_DB_CONNECTION_URI="jdbc:postgresql://<host>:5432/metabase?user=<username>&password=<password>"

Commands for migration which I run after successful db_connection:
java -jar metabase.jar load-from-h2 /path/to/metabase.db 

java -jar metabase.jar load-from-h2 /home/nitin/metabase-data                   
2024-09-10 10:55:46,512 INFO metabase.util :: Maximum memory available to JVM: 3.7 GB
2024-09-10 10:55:49,262 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
 For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
2024-09-10 10:55:55,254 INFO driver.impl :: Registered abstract driver :sql  🚚
2024-09-10 10:55:55,280 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
2024-09-10 10:55:55,286 INFO metabase.util :: Load driver :sql-jdbc took 10.5 ms
2024-09-10 10:55:55,286 INFO driver.impl :: Registered driver :h2 (parents: [:sql-jdbc]) 🚚
2024-09-10 10:55:55,567 INFO driver.impl :: Registered driver :mysql (parents: [:sql-jdbc]) 🚚
2024-09-10 10:55:55,609 INFO driver.impl :: Registered driver :postgres (parents: [:sql-jdbc]) 🚚
2024-09-10 10:55:57,234 INFO metabase.core :: 
Metabase v0.50.23 (7040ff1) 

Copyright © 2024 Metabase, Inc. 

Metabase Enterprise Edition extensions are NOT PRESENT.
2024-09-10 10:55:57,290 INFO driver.impl :: Registered abstract driver :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set  🚚
2024-09-10 10:55:57,295 INFO driver.impl :: Registered abstract driver :metabase.driver.sql.query-processor.empty-string-is-null/empty-string-is-null  🚚
2024-09-10 10:55:57,597 INFO cmd.copy :: Set up h2 source database and run migrations... 
2024-09-10 10:55:57,598 INFO db.setup :: Verifying h2 Database Connection ...
2024-09-10 10:55:57,635 ERROR cmd.copy :: [FAIL]

clojure.lang.ExceptionInfo: ERROR Set up h2 source database and run migrations...: Unable to connect to Metabase h2 DB. {}
	at metabase.cmd.copy$do_step$fn__100127.invoke(copy.clj:34)
	at metabase.cmd.copy$do_step.invokeStatic(copy.clj:30)
	at metabase.cmd.copy$do_step.invoke(copy.clj:28)
	at metabase.cmd.copy$copy_BANG_.invokeStatic(copy.clj:392)
	at metabase.cmd.copy$copy_BANG_.invoke(copy.clj:382)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:35)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:25)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:74)
	at metabase.cmd$load_from_h2.invoke(cmd.clj:68)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__107778.invoke(cmd.clj:313)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:310)
	at metabase.cmd$run_cmd.invoke(cmd.clj:300)
	at clojure.lang.Var.invoke(Var.java:393)
	at metabase.core$run_cmd.invokeStatic(core.clj:193)
	at metabase.core$run_cmd.invoke(core.clj:191)
	at metabase.core$entrypoint.invokeStatic(core.clj:215)
	at metabase.core$entrypoint.doInvoke(core.clj:210)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
Caused by: clojure.lang.ExceptionInfo: Unable to connect to Metabase h2 DB. {}
	at metabase.db.setup$verify_db_connection$fn__53175.invoke(setup.clj:117)
	at metabase.db.setup$verify_db_connection.invokeStatic(setup.clj:115)
	at metabase.db.setup$verify_db_connection.invoke(setup.clj:107)
	at metabase.db.setup$setup_db_BANG_$fn__53195$fn__53196.invoke(setup.clj:165)
	at metabase.util.jvm$do_with_us_locale.invokeStatic(jvm.clj:239)
	at metabase.util.jvm$do_with_us_locale.invoke(jvm.clj:225)
	at metabase.db.setup$setup_db_BANG_$fn__53195.invoke(setup.clj:161)
	at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:160)
	at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:153)
	at metabase.cmd.copy$copy_BANG_$fn__100319.invoke(copy.clj:393)
	at metabase.cmd.copy$do_step$fn__100127.invoke(copy.clj:31)
	... 29 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database "/home/nitin/metabase-data" not found, and IFEXISTS=true, so we cant auto-create it [90146-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.engine.Engine.throwNotFound(Engine.java:186)
	at org.h2.engine.Engine.openSession(Engine.java:72)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at metabase.db.data_source.DataSource.getConnection(data_source.clj:79)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:372)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:348)
	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:345)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.db.setup$verify_db_connection$fn__53175.invoke(setup.clj:115)
	... 39 more
Command failed with exception: ERROR Set up h2 source database and run migrations...: Unable to connect to Metabase h2 DB.






I got a similar error and here I mentioned the permissions I have with these files and the location of the files where it exist already.

ls /home/nitin/metabase-data
metabase.db.mv.db  metabase.db.trace.db


ls -l /home/nitin/metabase-data
-rw-r--r-- 1 nitin nitin 251797504 Sep  3 16:07 metabase.db.mv.db
-rw-r--r-- 1 nitin nitin    266619 Sep  3 16:07 metabase.db.trace.db


ls -l /home/nitin/metabase-data/metabase.db.mv.db 
-rw-r--r-- 1 nitin nitin 251797504 Sep  3 16:07 /home/nitin/metabase-data/metabase.db.mv.db


ls -l /home/nitin/metabase-data/metabase.db.trace.db 
-rw-r--r-- 1 nitin nitin 266619 Sep  3 16:07 /home/nitin/metabase-data/metabase.db.trace.db

**Comment by KyleRampGrowth** [comment]
@nb1907 Just posting this here as the solution. I had exactly the same issue and after a terrible support experience, I finally solved it.

The DB backup literally needs to be called "metabase.db.mv.db" and when you reference it in your migration script, it needs to be referenced as "metabase.db.mv.db". Even if what you are provided is "backup.mv.db" you need to rename it to "metabase.db.mv.db".

Even though the error message states that the db I pointed to "wasn't found" the error is actually "Your db backup is found, it's just named EXACTLY how we want it to be".
It's NOT a file permission issue; it's just a bad error message.

**Comment by paoliniluis** [comment]
> [@nb1907](https://github.com/nb1907) Just posting this here as the solution. I had exactly the same issue and after a terrible support experience, I finally solved it.
> 
> The DB backup literally needs to be called "metabase.db.mv.db" and when you reference it in your migration script, it needs to be referenced as "metabase.db.mv.db". Even if what you are provided is "backup.mv.db" you need to rename it to "metabase.db.mv.db".
> 
> Even though the error message states that the db I pointed to "wasn't found" the error is actually "Your db backup is found, it's just named EXACTLY how we want it to be". It's NOT a file permission issue; it's just a bad error message.

Hi Kyle, it's sad that you say that you had a terrible support experience considering that we sent you the files you needed and the documentaton. Specifically, the docs that we sent you says that very explicitly https://www.metabase.com/docs/latest/troubleshooting-guide/loading-from-h2#are-you-trying-to-migrate-the-application-database-from-h2-to-something-else

**Comment by KyleRampGrowth** [comment]
I don't think there is an engineer in the world that would agree that receiving an error stating "db could not be found" is synonymous with "your DB backup is incorrectly named".

Some pointers:
 - If I'm able to just rename a file extension (like is required) then why not have you guys simply provide a download link that gives the correct file name?. (I even asked about this in my email and it was ignored)
 - Simple state in the docs "Please ensure your filename matches metabase.db.mv.db eaxctly as that is what our tool is expecting you to name it, any other filenames are invalid".
- Replace the error message to indicate that the filename is incorrect.

**Comment by KyleRampGrowth** [comment]
Even in this thread, when @nb1907 showed you the output of the `ls` command which clearly showed his db file was incorrect, you just pointed out that his example snippet was wrong rather than saying: "Oh hey, yeah it's usually a file permission issue or you need to rename the file to match metabase.db.mv.db exactly or it won't work".

So yeah, lots to do better.

**Comment by paoliniluis** [comment]
In case anyone ends up here, please read the docs :)

**Comment by wasimb-atica** [comment]
@paoliniluis Can you please share the doc link? I am too stuck here for migration purpose.
