### ISSUE TITLE
Can not migrate from h2.db to aurora postgres

### ISSUE THREAD

**Issue by ivanrezic** [metabase/metabase#47900]
### Describe the bug

I was following the [migration guide](https://www.metabase.com/docs/latest/installation-and-operation/migrating-from-h2#jar-how-to-migrate-from-h2-to-your-production-application-database) to move from h2.db to aurora postgres but got this error: `org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"`

### To Reproduce

1.  I attached to the metabase pod running in our EKS
2. copied recursively h2.db
3. downloaded h2.db dir from metabase pod
4. contents of downloaded dir
```
h2.db
├── h2.db.mv.db
├── h2.db.trace.db
└── h2.db.v1-backup.mv.db
```
5. ran `java -jar metabase.jar load-from-h2 h2.db/h2.d`
6. got the error from the log below.

### Expected behavior

Migration script should run successfully. 

### Logs

```
2024-09-12 21:04:25,960 INFO cmd.copy :: Copying instances of Field...
2024-09-12 21:04:32,614 ERROR cmd.copy :: BatchUpdateException:
 Message: Batch entry 19 INSERT INTO metabase_field ( "description", "database_type", "semantic_type", "table_id", "coercion_strategy", "database_indexed", "name", "fingerprint_version", "has_field_values", "settings", "caveats", "fk_target_field_id", "updated_at", "custom_position", "effective_type", "active", "nfc_path", "parent_id", "id", "last_analyzed", "database_partitioned", "database_is_auto_increment", "json_unfolding", "position", "visibility_type", "preview_display", "display_name", "database_position", "database_required", "fingerprint", "created_at", "base_type", "points_of_interest" ) VALUES ( (NULL), ('java.lang.String'), ('type/Category'), ('55'::int4), (NULL), (NULL), ('type'), ('5'::int4), ('auto-list'), (NULL), (NULL), (NULL), ('2023-10-02 18:09:12.323317+00'::timestamp with time zone), ('0'::int4), ('type/Text'), ('TRUE'::boolean), (NULL), (NULL), ('3789'::int4), ('2023-03-22 10:34:51.986+00'::timestamp with time zone), (NULL), ('FALSE'::boolean), ('FALSE'::boolean), ('4'::int4), ('normal'), ('TRUE'::boolean), ('Type'), ('4'::int4), ('FALSE'::boolean), ('{"global":{"distinct-count":2,"nil%":0.9961046188091263},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":0.07011686143572621}}}'), ('2023-03-22 10:26:38.37+00'::timestamp with time zone), ('type/Text'), (NULL) ) was aborted: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(55, type) already exists.  Call getNextException to see other errors in the batch.
 SQLState: 23505
 Error Code: 0
PSQLException:
 Message: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(55, type) already exists.
 SQLState: 23505
 Error Code: 0

2024-09-12 21:04:32,621 INFO cmd.copy :: Re-enabling DB constraints...
2024-09-12 21:04:32,623 INFO cmd.copy :: [OK]
clojure.lang.ExceptionInfo: Error copying instances of Field {:model "Field"}
	at metabase.cmd.copy$copy_data_BANG_$fn__99746$fn__99747.invoke(copy.clj:196)
	at metabase.cmd.copy$copy_data_BANG_$fn__99746.invoke(copy.clj:193)
	at clojure.core$partition_all$fn__8625$fn__8626.invoke(core.clj:7333)
	at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1205)
	at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1197)
	at clojure.java.jdbc$reducible_result_set_STAR_$reify__41980.reduce(jdbc.clj:1227)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6869)
	at clojure.java.jdbc$query_reducer$fn__41986$fn__41989.invoke(jdbc.clj:1262)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1091)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1106)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$reducible_query$reify__42003.reduce(jdbc.clj:1357)
	at clojure.core$transduce.invokeStatic(core.clj:6947)
	at clojure.core$transduce.invoke(core.clj:6934)
	at metabase.cmd.copy$copy_data_BANG_.invokeStatic(copy.clj:180)
	at metabase.cmd.copy$copy_data_BANG_.invoke(copy.clj:174)
	at metabase.cmd.copy$copy_BANG_$fn__99881$fn__99882$fn__99883.invoke(copy.clj:411)
	at metabase.cmd.copy$do_with_disabled_db_constraints.invokeStatic(copy.clj:275)
	at metabase.cmd.copy$do_with_disabled_db_constraints.invoke(copy.clj:271)
	at metabase.cmd.copy$copy_BANG_$fn__99881$fn__99882.invoke(copy.clj:410)
	at metabase.cmd.copy$do_with_connection_rollback_only.invokeStatic(copy.clj:217)
	at metabase.cmd.copy$do_with_connection_rollback_only.invoke(copy.clj:215)
	at metabase.cmd.copy$copy_BANG_$fn__99881.invoke(copy.clj:408)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)
	at metabase.cmd.copy$copy_BANG_.invokeStatic(copy.clj:405)
	at metabase.cmd.copy$copy_BANG_.invoke(copy.clj:380)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:35)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:25)
	at clojure.lang.Var.invoke(Var.java:384)
	at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:74)
	at metabase.cmd$load_from_h2.invoke(cmd.clj:68)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.cmd$run_cmd$fn__106482.invoke(cmd.clj:301)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:300)
	at metabase.cmd$run_cmd.invoke(cmd.clj:290)
	at clojure.lang.Var.invoke(Var.java:388)
	at metabase.core$run_cmd.invokeStatic(core.clj:192)
	at metabase.core$run_cmd.invoke(core.clj:190)
	at metabase.core$entrypoint.invokeStatic(core.clj:214)
	at metabase.core$entrypoint.doInvoke(core.clj:209)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.bootstrap$_main.invokeStatic(bootstrap.clj:31)
	at metabase.bootstrap$_main.doInvoke(bootstrap.clj:28)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.bootstrap.main(Unknown Source)
Caused by: java.sql.BatchUpdateException: Batch entry 19 INSERT INTO metabase_field ( "description", "database_type", "semantic_type", "table_id", "coercion_strategy", "database_indexed", "name", "fingerprint_version", "has_field_values", "settings", "caveats", "fk_target_field_id", "updated_at", "custom_position", "effective_type", "active", "nfc_path", "parent_id", "id", "last_analyzed", "database_partitioned", "database_is_auto_increment", "json_unfolding", "position", "visibility_type", "preview_display", "display_name", "database_position", "database_required", "fingerprint", "created_at", "base_type", "points_of_interest" ) VALUES ( (NULL), ('java.lang.String'), ('type/Category'), ('55'::int4), (NULL), (NULL), ('type'), ('5'::int4), ('auto-list'), (NULL), (NULL), (NULL), ('2023-10-02 18:09:12.323317+00'::timestamp with time zone), ('0'::int4), ('type/Text'), ('TRUE'::boolean), (NULL), (NULL), ('3789'::int4), ('2023-03-22 10:34:51.986+00'::timestamp with time zone), (NULL), ('FALSE'::boolean), ('FALSE'::boolean), ('4'::int4), ('normal'), ('TRUE'::boolean), ('Type'), ('4'::int4), ('FALSE'::boolean), ('{"global":{"distinct-count":2,"nil%":0.9961046188091263},"type":{"type/Text":{"percent-json":0.0,"percent-url":0.0,"percent-email":0.0,"percent-state":0.0,"average-length":0.07011686143572621}}}'), ('2023-03-22 10:26:38.37+00'::timestamp with time zone), ('type/Text'), (NULL) ) was aborted: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(55, type) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2413)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:579)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:912)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:936)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1733)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2544)
	at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:591)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1058)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1042)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1080)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1060)
	at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1594)
	at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1585)
	at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1653)
	at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1619)
	at metabase.cmd.copy$insert_chunk_BANG_.invokeStatic(copy.clj:129)
	at metabase.cmd.copy$insert_chunk_BANG_.invoke(copy.clj:123)
	at metabase.cmd.copy$copy_data_BANG_$fn__99746$fn__99747.invoke(copy.clj:194)
	... 57 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idx_uniq_field_table_id_parent_id_name_2col"
  Detail: Key (table_id, name)=(55, type) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	... 75 more
Command failed with exception: Error copying instances of Field
```

### Information about your Metabase installation

```JSON
- metabase version  v0.50.2
- metabase.jar version v0.50.2
- internal database: h2.db -> H2 2.1.214 (2022-06-13) got from the logs
- destination db, aurora postgres 15.5
```

### Severity

Annoying, blocking us to implement usage tracking

**Comment by paoliniluis** [comment]
Check https://github.com/metabase/metabase/issues/45885
