### ISSUE TITLE
.xlsx Download Error - 504 Gateway Time-out - Client closed connection prematurely

### ISSUE THREAD

**Issue by fmercurio** [metabase/metabase#48177]
**Describe the bug**
I cannot download .xlsx datasets.

**Logs**
``` Docker Logs
2024-09-27 22:00:04,117 INFO cache.impl :: Results are too large to cache. 😫
2024-09-27 22:00:05,113 INFO middleware.cache :: Query 4a273c7b took 1.0 mins to run; minimum for cache eligibility is 1000.0 ms; eligible
2024-09-27 22:00:05,113 INFO middleware.cache :: Caching results for next time for query with hash "4a273c7b". 💾
2024-09-27 22:00:05,446 ERROR query-processor.streaming :: Client closed connection prematurely
org.eclipse.jetty.io.EofException: Closed
        at org.eclipse.jetty.server.HttpOutput.checkWritable(HttpOutput.java:756)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:780)
        at java.base/java.util.zip.GZIPOutputStream.finish(Unknown Source)
        at java.base/java.util.zip.DeflaterOutputStream.close(Unknown Source)
        at metabase.async.streaming_response$delay_output_stream$fn__52041.invoke(streaming_response.clj:130)
        at metabase.async.streaming_response.proxy$java.io.OutputStream$ff19274a.close(Unknown Source)
        at metabase.query_processor.streaming.xlsx$fn$reify__70019.finish_BANG_(xlsx.clj:685)
        at metabase.query_processor.streaming$streaming_result_fn$result__70115$fn__70116.invoke(streaming.clj:144)
        at metabase.query_processor.streaming$streaming_result_fn$result__70115.invoke(streaming.clj:143)
        at metabase.query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:81)
        at metabase.query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:49)
        at metabase.query_processor.middleware.cache$run_query_with_cache$reduce_SINGLEQUOTE___71530$fn__71531.invoke(cache.clj:211)
        at metabase.query_processor.middleware.cache.impl$do_with_serialization.invokeStatic(impl.clj:83)
        at metabase.query_processor.middleware.cache.impl$do_with_serialization.invoke(impl.clj:54)
        at metabase.query_processor.middleware.cache.impl$do_with_serialization.invokeStatic(impl.clj:73)
        at metabase.query_processor.middleware.cache.impl$do_with_serialization.invoke(impl.clj:54)
        at metabase.query_processor.middleware.cache$run_query_with_cache$reduce_SINGLEQUOTE___71530.invoke(cache.clj:207)
        at metabase.query_processor.pipeline$_STAR_run_STAR_$respond__56960.invoke(pipeline.clj:95)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__82465.invoke(execute.clj:725)
        at metabase.driver.sql_jdbc.execute$fn__82269$fn__82270.invoke(execute.clj:398)
        at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:338)
        at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:321)
        at metabase.driver.sql_jdbc.execute$fn__82269.invokeStatic(execute.clj:392)
        at metabase.driver.sql_jdbc.execute$fn__82269.invoke(execute.clj:390)
        at clojure.lang.MultiFn.invoke(MultiFn.java:244)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:708)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:705)
        at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)
        at metabase.driver.sql_jdbc$fn__108283.invokeStatic(sql_jdbc.clj:78)
        at metabase.driver.sql_jdbc$fn__108283.invoke(sql_jdbc.clj:76)
        at clojure.lang.MultiFn.invoke(MultiFn.java:244)
        at metabase.query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)
        at metabase.query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)
        at metabase.query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)
        at metabase.query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)
        at metabase.query_processor.execute$run.invokeStatic(execute.clj:60)
        at metabase.query_processor.execute$run.invoke(execute.clj:54)
        at metabase.query_processor.middleware.update_used_cards$update_used_cards_BANG_$fn__71571.invoke(update_used_cards.clj:60)
        at metabase.query_processor.execute$add_native_form_to_result_metadata$fn__71586.invoke(execute.clj:23)
        at metabase.query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__71591.invoke(execute.clj:34)
        at metabase.query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:212)
        at metabase.query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:185)
        at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___71544.invoke(cache.clj:238)
        at metabase.query_processor.middleware.permissions$check_query_permissions$fn__66185.invoke(permissions.clj:147)
        at metabase.query_processor.middleware.enterprise$check_download_permissions_middleware$fn__66797.invoke(enterprise.clj:51)
        at metabase.query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__66807.invoke(enterprise.clj:64)
        at metabase.query_processor.execute$execute$fn__71618.invoke(execute.clj:92)
        at metabase.query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:225)
        at metabase.query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)
        at metabase.query_processor.execute$execute.invokeStatic(execute.clj:91)
        at metabase.query_processor.execute$execute.invoke(execute.clj:87)
        at metabase.query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47)
        at metabase.query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:43)
        at metabase.query_processor.middleware.enterprise$fn__66824$handle_audit_app_internal_queries__66825$fn__66827.invoke(enterprise.clj:96)
        at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__66835.invoke(enterprise.clj:103)
        at metabase.query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__76807.invoke(process_userland_query.clj:198)
        at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__76876.invoke(catch_exceptions.clj:128)
        at metabase.query_processor$process_query$fn__76913.invoke(query_processor.clj:78)
        at metabase.query_processor.setup$do_with_canceled_chan$fn__67239.invoke(setup.clj:187)
        at metabase.query_processor.setup$do_with_database_local_settings$fn__67234.invoke(setup.clj:181)
        at metabase.query_processor.setup$do_with_driver$fn__67229$fn__67230.invoke(setup.clj:166)
        at metabase.driver$do_with_driver.invokeStatic(driver.clj:104)
        at metabase.driver$do_with_driver.invoke(driver.clj:99)
        at metabase.query_processor.setup$do_with_driver$fn__67229.invoke(setup.clj:165)
        at metabase.query_processor.setup$do_with_metadata_provider$fn__67222$fn__67225.invoke(setup.clj:151)
        at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:170)
        at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150)
        at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:159)
        at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150)
        at metabase.query_processor.setup$do_with_metadata_provider$fn__67222.invoke(setup.clj:150)
        at metabase.query_processor.setup$do_with_resolved_database$fn__67216.invoke(setup.clj:128)
        at metabase.query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232)
        at metabase.query_processor.setup$do_with_qp_setup.invoke(setup.clj:216)
        at metabase.query_processor$process_query.invokeStatic(query_processor.clj:76)
        at metabase.query_processor$process_query.invoke(query_processor.clj:69)
        at metabase.query_processor.card$process_query_for_card_default_qp.invokeStatic(card.clj:170)
        at metabase.query_processor.card$process_query_for_card_default_qp.invoke(card.clj:166)
        at metabase.query_processor.card$process_query_for_card_default_run_fn$fn__82654$fn__82655.invoke(card.clj:177)
        at metabase.query_processor.streaming$_streaming_response$fn__70127$fn__70128$fn__70129.invoke(streaming.clj:176)
        at metabase.query_processor.streaming$_streaming_response$fn__70127$fn__70128.invoke(streaming.clj:174)
        at metabase.query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165)
        at metabase.query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152)
        at metabase.query_processor.streaming$_streaming_response$fn__70127.invoke(streaming.clj:171)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)
        at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76)
        at metabase.async.streaming_response$do_f_async$task__52026.invoke(streaming_response.clj:97)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2024-09-27 22:00:05,447 INFO cache.impl :: Results are too large to cache. 😫
2024-09-27 22:00:05,447 INFO cache.impl :: Results are too large to cache. 😫
```

``` Metabase Troubleshoot Logs
[32ca2cef-c797-450f-8cd0-2b9676e037d1] 2024-09-27T19:00:04-03:00 INFO metabase.query-processor.middleware.cache.impl Results are too large to cache. 😫
[32ca2cef-c797-450f-8cd0-2b9676e037d1] 2024-09-27T19:00:05-03:00 INFO metabase.query-processor.middleware.cache Caching results for next time for query with hash "4a273c7b". 💾
[32ca2cef-c797-450f-8cd0-2b9676e037d1] 2024-09-27T19:00:05-03:00 INFO metabase.query-processor.middleware.cache Query 4a273c7b took 1.0 mins to run; minimum for cache eligibility is 1000.0 ms; eligible
[32ca2cef-c797-450f-8cd0-2b9676e037d1] 2024-09-27T19:00:05-03:00 ERROR metabase.query-processor.streaming Client closed connection prematurely,org.eclipse.jetty.io.EofException: Closed,	at org.eclipse.jetty.server.HttpOutput.checkWritable(HttpOutput.java:756),	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:780),	at java.base/java.util.zip.GZIPOutputStream.finish(Unknown Source),	at java.base/java.util.zip.DeflaterOutputStream.close(Unknown Source),	at metabase.async.streaming_response$delay_output_stream$fn__52041.invoke(streaming_response.clj:130),	at metabase.async.streaming_response.proxy$java.io.OutputStream$ff19274a.close(Unknown Source),	at metabase.query_processor.streaming.xlsx$fn$reify__70019.finish_BANG_(xlsx.clj:685),	at metabase.query_processor.streaming$streaming_result_fn$result__70115$fn__70116.invoke(streaming.clj:144),	at metabase.query_processor.streaming$streaming_result_fn$result__70115.invoke(streaming.clj:143),	at metabase.query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:81),	at metabase.query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:49),	at metabase.query_processor.middleware.cache$run_query_with_cache$reduce_SINGLEQUOTE___71530$fn__71531.invoke(cache.clj:211),	at metabase.query_processor.middleware.cache.impl$do_with_serialization.invokeStatic(impl.clj:83),	at metabase.query_processor.middleware.cache.impl$do_with_serialization.invoke(impl.clj:54),	at metabase.query_processor.middleware.cache.impl$do_with_serialization.invokeStatic(impl.clj:73),	at metabase.query_processor.middleware.cache.impl$do_with_serialization.invoke(impl.clj:54),	at metabase.query_processor.middleware.cache$run_query_with_cache$reduce_SINGLEQUOTE___71530.invoke(cache.clj:207),	at metabase.query_processor.pipeline$_STAR_run_STAR_$respond__56960.invoke(pipeline.clj:95),	at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__82465.invoke(execute.clj:725),	at metabase.driver.sql_jdbc.execute$fn__82269$fn__82270.invoke(execute.clj:398),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:338),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:321),	at metabase.driver.sql_jdbc.execute$fn__82269.invokeStatic(execute.clj:392),	at metabase.driver.sql_jdbc.execute$fn__82269.invoke(execute.clj:390),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:708),	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694),	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:705),	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694),	at metabase.driver.sql_jdbc$fn__108283.invokeStatic(sql_jdbc.clj:78),	at metabase.driver.sql_jdbc$fn__108283.invoke(sql_jdbc.clj:76),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47),	at metabase.query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34),	at metabase.query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97),	at metabase.query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90),	at metabase.query_processor.execute$run.invokeStatic(execute.clj:60),	at metabase.query_processor.execute$run.invoke(execute.clj:54),	at metabase.query_processor.middleware.update_used_cards$update_used_cards_BANG_$fn__71571.invoke(update_used_cards.clj:60),	at metabase.query_processor.execute$add_native_form_to_result_metadata$fn__71586.invoke(execute.clj:23),	at metabase.query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__71591.invoke(execute.clj:34),	at metabase.query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:212),	at metabase.query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:185),	at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___71544.invoke(cache.clj:238),	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__66185.invoke(permissions.clj:147),	at metabase.query_processor.middleware.enterprise$check_download_permissions_middleware$fn__66797.invoke(enterprise.clj:51),	at metabase.query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__66807.invoke(enterprise.clj:64),	at metabase.query_processor.execute$execute$fn__71618.invoke(execute.clj:92),	at metabase.query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:225),	at metabase.query_processor.setup$do_with_qp_setup.invoke(setup.clj:216),	at metabase.query_processor.execute$execute.invokeStatic(execute.clj:91),	at metabase.query_processor.execute$execute.invoke(execute.clj:87),	at metabase.query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:47),	at metabase.query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:43),	at metabase.query_processor.middleware.enterprise$fn__66824$handle_audit_app_internal_queries__66825$fn__66827.invoke(enterprise.clj:96),	at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__66835.invoke(enterprise.clj:103),	at metabase.query_processor.middleware.process_userland_query$process_userland_query_middleware$fn__76807.invoke(process_userland_query.clj:198),	at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__76876.invoke(catch_exceptions.clj:128),	at metabase.query_processor$process_query$fn__76913.invoke(query_processor.clj:78),	at metabase.query_processor.setup$do_with_canceled_chan$fn__67239.invoke(setup.clj:187),	at metabase.query_processor.setup$do_with_database_local_settings$fn__67234.invoke(setup.clj:181),	at metabase.query_processor.setup$do_with_driver$fn__67229$fn__67230.invoke(setup.clj:166),	at metabase.driver$do_with_driver.invokeStatic(driver.clj:104),	at metabase.driver$do_with_driver.invoke(driver.clj:99),	at metabase.query_processor.setup$do_with_driver$fn__67229.invoke(setup.clj:165),	at metabase.query_processor.setup$do_with_metadata_provider$fn__67222$fn__67225.invoke(setup.clj:151),	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:170),	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150),	at metabase.query_processor.store$do_with_metadata_provider.invokeStatic(store.clj:159),	at metabase.query_processor.store$do_with_metadata_provider.invoke(store.clj:150),	at metabase.query_processor.setup$do_with_metadata_provider$fn__67222.invoke(setup.clj:150),	at metabase.query_processor.setup$do_with_resolved_database$fn__67216.invoke(setup.clj:128),	at metabase.query_processor.setup$do_with_qp_setup.invokeStatic(setup.clj:232),	at metabase.query_processor.setup$do_with_qp_setup.invoke(setup.clj:216),	at metabase.query_processor$process_query.invokeStatic(query_processor.clj:76),	at metabase.query_processor$process_query.invoke(query_processor.clj:69),	at metabase.query_processor.card$process_query_for_card_default_qp.invokeStatic(card.clj:170),	at metabase.query_processor.card$process_query_for_card_default_qp.invoke(card.clj:166),	at metabase.query_processor.card$process_query_for_card_default_run_fn$fn__82654$fn__82655.invoke(card.clj:177),	at metabase.query_processor.streaming$_streaming_response$fn__70127$fn__70128$fn__70129.invoke(streaming.clj:176),	at metabase.query_processor.streaming$_streaming_response$fn__70127$fn__70128.invoke(streaming.clj:174),	at metabase.query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:165),	at metabase.query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:152),	at metabase.query_processor.streaming$_streaming_response$fn__70127.invoke(streaming.clj:171),	at clojure.lang.AFn.applyToHelper(AFn.java:156),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.core$apply.invokeStatic(core.clj:667),	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990),	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990),	at clojure.lang.RestFn.applyTo(RestFn.java:142),	at clojure.core$apply.invokeStatic(core.clj:671),	at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020),	at clojure.lang.RestFn.invoke(RestFn.java:421),	at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78),	at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76),	at metabase.async.streaming_response$do_f_async$task__52026.invoke(streaming_response.clj:97),	at clojure.lang.AFn.run(AFn.java:22),	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source),	at java.base/java.util.concurrent.FutureTask.run(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source),	at java.base/java.lang.Thread.run(Unknown Source)
[32ca2cef-c797-450f-8cd0-2b9676e037d1] 2024-09-27T19:00:05-03:00 INFO metabase.query-processor.middleware.cache.impl Results are too large to cache. 😫
```

**To Reproduce**
1. Open a big Metabase `question`;
2. Click on `Download` icon;
3. Choose `.xlsx`
4. Wait for the `can't download message`

**Expected behavior**
Download the dataset on a .xlsx file.

**Screenshots**
![image](https://github.com/user-attachments/assets/91144692-2001-4bd7-b48f-090f2d468e8e)

![image](https://github.com/user-attachments/assets/264fbe2e-a963-46a6-980a-487404a60521)

**Severity**
The download functionality is one of the most wanted tool to of my user`s company.

**Additional context**
I try to download with CSV and I got another error.

**Metabase Diagnostic Info**

```json
{
  "browser-info": {
    "language": "pt-BR",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-09-16",
      "tag": "v0.50.26",
      "hash": "5a65f46"
    },
    "settings": {
      "report-timezone": "America/Sao_Paulo"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "6.8.0-45-generic",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

**Comment by paoliniluis** [comment]
your reverse proxy is cutting the connection, please increase the proxy time or make the queries run faster
