### ISSUE TITLE
error message of "Your question took too long"

### ISSUE THREAD

**Issue by reddy2018** [metabase/metabase#48296]
### Describe the bug

I am facing the issue. when i ran the sql query from metabase, its giving timeout after 20mins, still i have added the
jetty:
ASYNC_RESPONSE_TIMEOUT: "3600000"

also the ingress level time out - nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"

### Information about your Metabase installation

i am using the chrome to access the metabase

### Severity

high

**Comment by crisptrutski** [comment]
Can you please provide more information, for example around the query and the database in question?

**Comment by reddy2018** [comment]
clojure.lang.ExceptionInfo: Timed out after 20.0 mins. {:status :timed-out, :type :timed-out}
	at metabase.query_processor.context.default$default_timeoutf.invokeStatic(default.clj:90)
	at metabase.query_processor.context.default$default_timeoutf.invoke(default.clj:86)
	at metabase.query_processor.context$timeoutf.invokeStatic(context.clj:85)
	at metabase.query_processor.context$timeoutf.invoke(context.clj:80)
	at metabase.query_processor.reducible$wire_up_context_channels_BANG_$fn__66755$state_machine__36873__auto____66764$fn__66766.invoke(reducible.clj:63)
	at metabase.query_processor.reducible$wire_up_context_channels_BANG_$fn__66755$state_machine__36873__auto____66764.invoke(reducible.clj:57)
	at clojure.core.async.impl.runtime$run_state_machine.invokeStatic(runtime.clj:62)
	at clojure.core.async.impl.runtime$run_state_machine.invoke(runtime.clj:61)
	at clojure.core.async.impl.runtime$run_state_machine_wrapped.invokeStatic(runtime.clj:66)
	at clojure.core.async.impl.runtime$run_state_machine_wrapped.invoke(runtime.clj:64)
	at clojure.core.async$ioc_alts_BANG_$fn__33198.invoke(async.clj:423)
	at clojure.core.async$do_alts$fn__33137$fn__33140.invoke(async.clj:290)
	at clojure.core.async.impl.channels.ManyToManyChannel$fn__32957.invoke(channels.clj:269)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__32795$fn__32796.invoke(concurrent.clj:29)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Tony-metabase** [comment]
How long does it take to run when you run it directly on your DB? and can you share the diagnostic information as well.

Also it would be more productive for both of us if this kind of issues are flagged in https://discourse.metabase.com/ cause this is not a bug and other users might experience the same problem and provide support

**Comment by reddy2018** [comment]
when i ran directly in the db, it took almost 40mins.

**Comment by reddy2018** [comment]
it seems some where in the metabase needs to change the timeout setting to run the query more than 20 mins.

If anyone faced the same problem please share the solution

**Comment by Tony-metabase** [comment]
I think you need to increase both the [MB_JETTY_ASYNC_RESPONSE_TIMEOUT](https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_jetty_async_response_timeout) and the [MB_DB_QUERY_TIMEOUT_MINUTES](https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_db_query_timeout_minutes)

Nonetheless please don't open Bugs for things related to configuration, you can get better support on Discourse  https://discourse.metabase.com/ 

Also if a query takes around 40mins to run, you need to perform some optimization around that. Imagine having a dashboard with 5 questions that take around 40 min each to run. That means a user has to wait 40 min to see the results.

**Comment by reddy2018** [comment]
is this the correct way to setup [MB_DB_QUERY_TIMEOUT_MINUTES]

extraEnv:
  - name: MB_DB_QUERY_TIMEOUT_MINUTES
    value: "60"
#  - name: MB_DB_QUERY_TIMEOUT_SEC
#    value: "3600"
  - name: metabase.query-processor.query-timeout-ms
    value: "3600000"
  - name: MB_DB_CONNECTION_TIMEOUT_MS
    value: "3600000"

**Comment by reddy2018** [comment]
@Tony-metabase can you please check my env varaible is correct or not
