### ISSUE TITLE
You can't operate on a closed ResultSet!!! (master)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#48310]
### Describe the bug

Just tried moving an old 50 I had to master and got:
```
2024-10-03 17:36:51,152 INFO task.sweep-query-analysis :: Recalculating potentially stale analysis
2024-10-03 17:36:51,154 ERROR task.analyze-queries :: Unhandled error when attempting to analyse the next card in the queue
clojure.lang.ExceptionInfo: You can't operate on a closed ResultSet!!! {:toucan2/context-trace [["read column" {:thunk #object[toucan2.jdbc.read$read_column_thunk_primary_method_default$default_read_column_thunk__26091 0x5c82ced5 "toucan2.jdbc.read$read_column_thunk_primary_method_default$default_read_column_thunk__26091@5c82ced5"], :model :model/Card}]]}
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getObject(NewProxyResultSet.java:171)
	at toucan2.jdbc.read$read_column_thunk_primary_method_default$default_read_column_thunk__26091.invoke(read.clj:73)
	at toucan2.jdbc.read$read_column_thunk_after_method_default$fn__26103.invoke(read.clj:79)
	at toucan2.jdbc.read$make_column_thunk$column_thunk__26136.invoke(read.clj:136)
	at toucan2.jdbc.read$make_cached_row_num__GT_i__GT_thunk$row_num__GT_i__GT_thunk_STAR___26145$i__GT_thunk_STAR___26146$cached_column_thunk__26147.invoke(read.clj:180)
	at toucan2.jdbc.row$fetch_column_with_name.invokeStatic(row.clj:36)
	at toucan2.jdbc.row$fetch_column_with_name.invoke(row.clj:26)
	at toucan2.jdbc.row.TransientRow.valAt(row.clj:211)
	at toucan2.jdbc.row.TransientRow.valAt(row.clj:192)
	at clojure.lang.KeywordLookupSite$1.get(KeywordLookupSite.java:45)
	at metabase.util$id.invokeStatic(util.cljc:452)
	at metabase.util$id.invoke(util.cljc:443)
	at metabase.util$the_id.invokeStatic(util.cljc:462)
	at metabase.util$the_id.invoke(util.cljc:455)
	at metabase.task.analyze_queries$analyzer_loop_STAR_.invokeStatic(analyze_queries.clj:44)
	at metabase.task.analyze_queries$analyzer_loop_STAR_.invoke(analyze_queries.clj:40)
	at metabase.task.analyze_queries$analyzer_loop_BANG_.invokeStatic(analyze_queries.clj:72)
	at metabase.task.analyze_queries$analyzer_loop_BANG_.invoke(analyze_queries.clj:68)
	at metabase.task.analyze_queries$analyzer_loop_BANG_.invokeStatic(analyze_queries.clj:70)
	at metabase.task.analyze_queries$analyzer_loop_BANG_.invoke(analyze_queries.clj:68)
	at metabase.task.analyze_queries.QueryAnalyzer.execute(analyze_queries.clj:81)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.sql.SQLException: You can't operate on a closed ResultSet!!!
	... 25 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.getObject(int)" because "this.inner" is null
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getObject(NewProxyResultSet.java:165)
	... 22 more

```

### To Reproduce

move to master?

### Expected behavior

Don't hit the error

### Logs

Above

### Information about your Metabase installation

master

### Severity

P1

**Comment by crisptrutski** [comment]
Did a quick scan of the logs on Stats, and don't see it happening there.

I also have seen it locally where I've shifted between 50 and master a few times per day.

Failures in the analyzer background process should not interfere with the app in any way, can you confirm that the instance is otherwise responsive?

The originating exception above seems to come the connection pool management, so perhaps there are other symptoms?

**Comment by crisptrutski** [comment]
Do you recall precisely which version of 50 you switched from

**Comment by paoliniluis** [comment]
I went from 50.11 to master. The instance worked, yes

**Comment by crisptrutski** [comment]
@paoliniluis can you confirm whether the task throws the same exceptions on subsequent runs?

**Comment by paoliniluis** [comment]
Sorry @crisptrutski , I dumped the environment 🤦‍♂️

**Comment by armgong** [comment]
Maybe is not a upgrading problem.
Test master build today  on windows , where started a new instance with new default h2 database, the error still show
windows 10 
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)
~~~
2024-10-08 17:33:03,955 INFO task.sweep-query-analysis :: Calculating analysis for cards without any
2024-10-08 17:33:04,021 INFO channel.core :: Loading channel namespace: metabase.channel.http
2024-10-08 17:33:04,037 INFO channel.core :: Loading channel namespace: metabase.channel.shared
2024-10-08 17:33:04,040 INFO channel.core :: Loading channel namespace: metabase.channel.slack
2024-10-08 17:33:04,050 INFO metabase.core :: Metabase Initialization COMPLETE in 43.3 s
2024-10-08 17:33:05,381 INFO task.sweep-query-analysis :: Recalculating potentially stale analysis
2024-10-08 17:33:05,381 ERROR task.analyze-queries :: Unhandled error when attempting to analyse the next card in the queue
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:223)
        at org.h2.message.DbException.get(DbException.java:199)
        at org.h2.message.DbException.get(DbException.java:188)
        at org.h2.jdbc.JdbcResultSet.checkClosed(JdbcResultSet.java:3536)
        at org.h2.jdbc.JdbcResultSet.getMetaData(JdbcResultSet.java:141)
        at com.mchange.v2.c3p0.impl.NewProxyResultSet.getMetaData(NewProxyResultSet.java:987)
        at toucan2.jdbc.read$make_column_thunk$column_thunk__26136.invoke(read.clj:134)
        at toucan2.jdbc.read$make_cached_row_num__GT_i__GT_thunk$row_num__GT_i__GT_thunk_STAR___26145$i__GT_thunk_STAR___26146$cached_column_thunk__26147.invoke(read.clj:180)

        at toucan2.jdbc.row$fetch_column_with_name.invokeStatic(row.clj:36)
        at toucan2.jdbc.row$fetch_column_with_name.invoke(row.clj:26)
        at toucan2.jdbc.row.TransientRow.valAt(row.clj:211)
        at toucan2.jdbc.row.TransientRow.valAt(row.clj:192)
        at clojure.lang.KeywordLookupSite$1.get(KeywordLookupSite.java:45)
        at metabase.util$id.invokeStatic(util.cljc:452)
        at metabase.util$id.invoke(util.cljc:443)
        at metabase.util$the_id.invokeStatic(util.cljc:462)
        at metabase.util$the_id.invoke(util.cljc:455)
        at metabase.task.analyze_queries$analyzer_loop_STAR_.invokeStatic(analyze_queries.clj:44)
        at metabase.task.analyze_queries$analyzer_loop_STAR_.invoke(analyze_queries.clj:40)
        at metabase.task.analyze_queries$analyzer_loop_BANG_.invokeStatic(analyze_queries.clj:72)
        at metabase.task.analyze_queries$analyzer_loop_BANG_.invoke(analyze_queries.clj:68)
        at metabase.task.analyze_queries$analyzer_loop_BANG_.invokeStatic(analyze_queries.clj:70)
        at metabase.task.analyze_queries$analyzer_loop_BANG_.invoke(analyze_queries.clj:68)
        at metabase.task.analyze_queries.QueryAnalyzer.execute(analyze_queries.clj:81)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2024-10-08 17:33:11,439 INFO jdbcjobstore.JobStoreTX :: ClusterManager: detected 2 failed or restarted instances.
2024-10-08 17:33:11,439 INFO jdbcjobstore.JobStoreTX :: ClusterManager: Scanning for instance "win10-hyperv1728379970952"'s failed in-progress jobs.
2024-10-08 17:33:11,440 INFO jdbcjobstore.JobStoreTX :: ClusterManager: Scanning for instance "win10-hyperv1728379976053"'s failed in-progress jobs.
~~~

**Comment by crisptrutski** [comment]
Have a plausible theory, cut a PR.

**Comment by crisptrutski** [comment]
Resolving as the only report I've seen since was for the beta preceding the related PR.
