### ISSUE TITLE
Hiding columns in InteractiveQuestion in the sdk throws a JavaScript error

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#48789]
Hiding columns in InteractiveQuestion throws a JavaScript error in the embedding sdk.

### Screenshot

When clicking on "Hide Column"

<img src="https://github.com/user-attachments/assets/2a92794c-cf71-4eb7-be80-13bb3754b223" width="200">

JavaScript error is thrown

```tsx
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'query')
    at visualization-settings.js:36:58
    at Object.dispatch (redux-thunk.mjs:5:14)
    at dispatch (page.bundle.js:6:7424)
    at pR (action.js:12:7)
    at ClickActionsPopover.tsx:56:26
    at onClick (ClickActionsView.tsx:52:32)
    at o10 (ClickActionControl.tsx:53:15)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
```

<img src="https://github.com/user-attachments/assets/f7d86524-c2ab-4daf-8f84-447e628302c3" width="400">

**Comment by heypoom** [comment]
This is caused by the click actions popover referencing `getQuestion` to get question from the Redux store, which the SDK does not have.

```ts
const question = getQuestion(getState());
```
