### ISSUE TITLE
Error connecting to Athena Database from Metabase

### ISSUE THREAD

**Issue by jackton1** [metabase/metabase#48835]
### Describe the bug

I previously used two VPCs. One had an MSK cluster and an msk-athena-connector, and the second was for Metabase running on ECS. I set up an Athena database in Metabase, which connected to Athena to query my MSK Kafka topic. However, when I changed my setup and used a single VPC, I got this error when I synced my Athena database.

### To Reproduce

1. Setup MSK Cluster with a VPC
2. Setup Metabase on ECS with the same VPC
3. Create a Kafka topic and publish messages to it
4. Create a schema in AWS Glue using (AthenaFederatedQuery)
5. Query the topic in AWS Athena to verify
6. Configure the Athena Database in Metabase
7. Sync the database 
8. View the error below

### Expected behavior

It shouldn't fail to sync with Athena

### Logs

```log

Oct 17 06:48:38.072 DEBUG 33 com.simba.athena.athena.api.AJClient.fetchSchemasWithProxyApi: Aws::Athena - AthenaClient - GetNameSpaces ----- exit -----
--
Oct 17 06:48:38.074 ERROR 33 com.simba.athena.exceptions.ExceptionConverter.toSQLException: [Simba][AthenaJDBC](100131) An error has been thrown from the AWS SDK client. Unable to execute HTTP request: The target server failed to respond [Execution ID not available]
java.sql.SQLException: [Simba][AthenaJDBC](100131) An error has been thrown from the AWS SDK client. Unable to execute HTTP request: The target server failed to respond [Execution ID not available]
at com.simba.athena.athena.api.AJClient.checkAndThrowException(Unknown Source)
at com.simba.athena.athena.api.AJClient.fetchSchemasWithProxyApi(Unknown Source)
at com.simba.athena.athena.api.AJClient.getSchemas(Unknown Source)
at com.simba.athena.athena.utilities.AJMetadataHelperUtilities.getSchemasWithCatalogCheck(Unknown Source)
at com.simba.athena.athena.dataengine.metadata.AJCatalogSchemaOnlyMetadataSource.<init>(Unknown Source)
at com.simba.athena.athena.dataengine.AJDataEngine.makeNewMetadataSource(Unknown Source)
at com.simba.athena.dsi.dataengine.impl.DSIDataEngine.makeNewMetadataResult(Unknown Source)
at com.simba.athena.athena.dataengine.AJDataEngine.makeNewMetadataResult(Unknown Source)
at com.simba.athena.jdbc.jdbc42.S42DatabaseMetaData.createMetaDataResult(Unknown Source)
at com.simba.athena.jdbc.common.BaseDatabaseMetaData.getSchemas(Unknown Source)
at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getSchemas(NewProxyDatabaseMetaData.java:2990)
at metabase.driver.athena$fast_active_tables.invokeStatic(athena.clj:427)
at metabase.driver.athena$fast_active_tables.invoke(athena.clj:416)
at metabase.driver.athena$fn__121290$fn__121292.invoke(athena.clj:455)
at metabase.driver.sql_jdbc.execute$fn__82322$fn__82323.invoke(execute.clj:398)
at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:338)
at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:321)
at metabase.driver.sql_jdbc.execute$fn__82322.invokeStatic(execute.clj:392)
at metabase.driver.sql_jdbc.execute$fn__82322.invoke(execute.clj:390)
at clojure.lang.MultiFn.invoke(MultiFn.java:244)
at metabase.driver.athena$fn__121290.invokeStatic(athena.clj:449)
at metabase.driver.athena$fn__121290.invoke(athena.clj:447)
at clojure.lang.MultiFn.invoke(MultiFn.java:234)
at metabase.sync.fetch_metadata$db_metadata.invokeStatic(fetch_metadata.clj:30)
at metabase.sync.fetch_metadata$db_metadata.invoke(fetch_metadata.clj:26)
at metabase.sync.sync_metadata$sync_db_metadata_BANG_$fn__86091.invoke(sync_metadata.clj:69)
at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:189)
at metabase.sync.util$do_with_error_handling.invoke(util.clj:182)
at clojure.core$partial$fn__5910.invoke(core.clj:2647)
at metabase.driver$fn__55334.invokeStatic(driver.clj:826)
at metabase.driver$fn__55334.invoke(driver.clj:826)
at clojure.lang.MultiFn.invoke(MultiFn.java:239)
at metabase.sync.util$sync_in_context$fn__57781.invoke(util.clj:165)
at metabase.sync.util$with_db_logging_disabled$fn__57778.invoke(util.clj:157)
at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:130)
at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:124)
at metabase.sync.util$with_start_and_finish_logging$fn__57765.invoke(util.clj:142)
at metabase.sync.util$with_sync_events$fn__57760.invoke(util.clj:116)
at metabase.sync.util$with_duplicate_ops_prevented$fn__57747.invoke(util.clj:88)
at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:214)
at metabase.sync.util$do_sync_operation.invoke(util.clj:208)
at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invokeStatic(sync_metadata.clj:68)
at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invoke(sync_metadata.clj:65)
at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invokeStatic(sync_databases.clj:88)
at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invoke(sync_databases.clj:71)
at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:107)
at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:95)
at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:112)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
Caused by: com.simba.athena.support.exceptions.GeneralException: [Simba][AthenaJDBC](100131) An error has been thrown from the AWS SDK client. Unable to execute HTTP request: The target server failed to respond [Execution ID not available]
... 49 more
Caused by: com.simba.athena.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond
at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1219)
at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1165)
at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
at com.simba.athena.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
at com.simba.athena.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.doInvoke(AmazonAthenaClient.java:2570)
at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.invoke(AmazonAthenaClient.java:2537)
at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.invoke(AmazonAthenaClient.java:2526)
at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.executeListDatabases(AmazonAthenaClient.java:1542)
at com.simba.athena.amazonaws.services.athena.AmazonAthenaClient.listDatabases(AmazonAthenaClient.java:1511)
at com.simba.athena.athena.api.AJClient.fetchSchemasWithProxyApi(Unknown Source)
at com.simba.athena.athena.api.AJClient.getSchemas(Unknown Source)
at com.simba.athena.athena.utilities.AJMetadataHelperUtilities.getSchemasWithCatalogCheck(Unknown Source)
at com.simba.athena.athena.dataengine.metadata.AJCatalogSchemaOnlyMetadataSource.<init>(Unknown Source)
at com.simba.athena.athena.dataengine.AJDataEngine.makeNewMetadataSource(Unknown Source)
at com.simba.athena.dsi.dataengine.impl.DSIDataEngine.makeNewMetadataResult(Unknown Source)
at com.simba.athena.athena.dataengine.AJDataEngine.makeNewMetadataResult(Unknown Source)
at com.simba.athena.jdbc.jdbc42.S42DatabaseMetaData.createMetaDataResult(Unknown Source)
at com.simba.athena.jdbc.common.BaseDatabaseMetaData.getSchemas(Unknown Source)
at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getSchemas(NewProxyDatabaseMetaData.java:2990)
at metabase.driver.athena$fast_active_tables.invokeStatic(athena.clj:427)
at metabase.driver.athena$fast_active_tables.invoke(athena.clj:416)
at metabase.driver.athena$fn__121290$fn__121292.invoke(athena.clj:455)
at metabase.driver.sql_jdbc.execute$fn__82322$fn__82323.invoke(execute.clj:398)
at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:338)
at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:321)
at metabase.driver.sql_jdbc.execute$fn__82322.invokeStatic(execute.clj:392)
at metabase.driver.sql_jdbc.execute$fn__82322.invoke(execute.clj:390)
at clojure.lang.MultiFn.invoke(MultiFn.java:244)
at metabase.driver.athena$fn__121290.invokeStatic(athena.clj:449)
at metabase.driver.athena$fn__121290.invoke(athena.clj:447)
at clojure.lang.MultiFn.invoke(MultiFn.java:234)
at metabase.sync.fetch_metadata$db_metadata.invokeStatic(fetch_metadata.clj:30)
at metabase.sync.fetch_metadata$db_metadata.invoke(fetch_metadata.clj:26)
at metabase.sync.sync_metadata$sync_db_metadata_BANG_$fn__86091.invoke(sync_metadata.clj:69)
at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:189)
at metabase.sync.util$do_with_error_handling.invoke(util.clj:182)
at clojure.core$partial$fn__5910.invoke(core.clj:2647)
at metabase.driver$fn__55334.invokeStatic(driver.clj:826)
at metabase.driver$fn__55334.invoke(driver.clj:826)
at clojure.lang.MultiFn.invoke(MultiFn.java:239)
at metabase.sync.util$sync_in_context$fn__57781.invoke(util.clj:165)
at metabase.sync.util$with_db_logging_disabled$fn__57778.invoke(util.clj:157)
at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:130)
at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:124)
at metabase.sync.util$with_start_and_finish_logging$fn__57765.invoke(util.clj:142)
at metabase.sync.util$with_sync_events$fn__57760.invoke(util.clj:116)
at metabase.sync.util$with_duplicate_ops_prevented$fn__57747.invoke(util.clj:88)
at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:214)
at metabase.sync.util$do_sync_operation.invoke(util.clj:208)
at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invokeStatic(sync_metadata.clj:68)
at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invoke(sync_metadata.clj:65)
at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invokeStatic(sync_databases.clj:88)
at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invoke(sync_databases.clj:71)
at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:107)
at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:95)
at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:112)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
at com.simba.athena.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at com.simba.athena.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
at com.simba.athena.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
... 61 more
Oct 17 06:48:38.076 TRACE 33 com.simba.athena.jdbc.common.SConnection.getAutoCommit(): +++++ enter +++++
Oct 17 06:48:38.076 TRACE 33 com.simba.athena.dsi.core.impl.DSIConnection.getProperty(19): +++++ enter +++++
Oct 17 06:48:38.083 TRACE 69 com.simba.athena.jdbc.common.SConnection.clearWarnings(): +++++ enter +++++
Oct 17 06:48:38.083 TRACE 69 com.simba.athena.jdbc.common.SConnection.getAutoCommit(): +++++ enter +++++
Oct 17 06:48:38.083 TRACE 69 com.simba.athena.dsi.core.impl.DSIConnection.getProperty(19): +++++ enter +++++
2024-10-17 06:48:38,083 ERROR sync.fetch-metadata :: Error while fetching metdata with 'db-metadata'
java.sql.SQLException: [Simba][AthenaJDBC](100131) An error has been thrown from the AWS SDK client. Unable to execute HTTP request: The target server failed to respond [Execution ID not available]
at com.simba.athena.athena.api.AJClient.checkAndThrowException(Unknown Source)
at com.simba.athena.athena.api.AJClient.fetchSchemasWithProxyApi(Unknown Source)
at com.simba.athena.athena.api.AJClient.getSchemas(Unknown Source)
at com.simba.athena.athena.utilities.AJMetadataHelperUtilities.getSchemasWithCatalogCheck(Unknown Source)
at com.simba.athena.athena.dataengine.metadata.AJCatalogSchemaOnlyMetadataSource.<init>(Unknown Source)
at com.simba.athena.athena.dataengine.AJDataEngine.makeNewMetadataSource(Unknown Source)
at com.simba.athena.dsi.dataengine.impl.DSIDataEngine.makeNewMetadataResult(Unknown Source)
at com.simba.athena.athena.dataengine.AJDataEngine.makeNewMetadataResult(Unknown Source)
at com.simba.athena.jdbc.jdbc42.S42DatabaseMetaData.createMetaDataResult(Unknown Source)
at com.simba.athena.jdbc.common.BaseDatabaseMetaData.getSchemas(Unknown Source)
at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getSchemas(NewProxyDatabaseMetaData.java:2990)
at metabase.driver.athena$fast_active_tables.invokeStatic(athena.clj:427)
at metabase.driver.athena$fast_active_tables.invoke(athena.clj:416)
at metabase.driver.athena$fn__121290$fn__121292.invoke(athena.clj:455)
at metabase.driver.sql_jdbc.execute$fn__82322$fn__82323.invoke(execute.clj:398)
at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:338)
at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:321)
at metabase.driver.sql_jdbc.execute$fn__82322.invokeStatic(execute.clj:392)
at metabase.driver.sql_jdbc.execute$fn__82322.invoke(execute.clj:390)
at clojure.lang.MultiFn.invoke(MultiFn.java:244)
at metabase.driver.athena$fn__121290.invokeStatic(athena.clj:449)
at metabase.driver.athena$fn__121290.invoke(athena.clj:447)
at clojure.lang.MultiFn.invoke(MultiFn.java:234)
at metabase.sync.fetch_metadata$db_metadata.invokeStatic(fetch_metadata.clj:30)
at metabase.sync.fetch_metadata$db_metadata.invoke(fetch_metadata.clj:26)
at metabase.sync.sync_metadata$sync_db_metadata_BANG_$fn__86091.invoke(sync_metadata.clj:69)
at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:189)
at metabase.sync.util$do_with_error_handling.invoke(util.clj:182)
at clojure.core$partial$fn__5910.invoke(core.clj:2647)
at metabase.driver$fn__55334.invokeStatic(driver.clj:826)
at metabase.driver$fn__55334.invoke(driver.clj:826)
at clojure.lang.MultiFn.invoke(MultiFn.java:239)
at metabase.sync.util$sync_in_context$fn__57781.invoke(util.clj:165)
at metabase.sync.util$with_db_logging_disabled$fn__57778.invoke(util.clj:157)
at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:130)
at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:124)
at metabase.sync.util$with_start_and_finish_logging$fn__57765.invoke(util.clj:142)
at metabase.sync.util$with_sync_events$fn__57760.invoke(util.clj:116)
at metabase.sync.util$with_duplicate_ops_prevented$fn__57747.invoke(util.clj:88)
at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:214)
at metabase.sync.util$do_sync_operation.invoke(util.clj:208)
at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invokeStatic(sync_metadata.clj:68)
at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invoke(sync_metadata.clj:65)
at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invokeStatic(sync_databases.clj:88)
at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invoke(sync_databases.clj:71)
at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:107)
at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:95)
at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:112)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)


```

### Information about your Metabase installation

```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "athena",
      "postgres"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-10-02",
      "tag": "v0.50.28",
      "hash": "3179ef2"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "14.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.10.226-214.879.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  }
}
```

### Severity

Blocking usage of Metabase entirely

**Comment by paoliniluis** [comment]
Can you check if the vpc can accept traffic from outside to the msk cluster?

**Comment by jackton1** [comment]
Yes, it can. I decided to use 2 VPCs and set up VPC peering.
