### ISSUE TITLE
Snowflake vector column causes sync to fail

### ISSUE THREAD

**Issue by sicarul** [metabase/metabase#49388]
### Describe the bug

When running Metabase sync with a vector column on Snowflake, it fails the entire sync (not only the affected table) with this error:
An SQLException was provoked by the following failure: java.lang.IllegalArgumentException: No enum constant net.snowflake.client.jdbc.SnowflakeType.VECTOR

Probably upgrading the Snowflake driver is enough to fix this?

### To Reproduce

Create a Snowflake table with a VECTOR column and sync it

### Expected behavior

Vector columns should not break the sync

### Logs

[ed9270f8-d33d-4d8b-9633-740eab0a7390] 2024-10-31T10:37:45-03:00 ERROR metabase.sync.fetch-metadata Error while fetching metdata with 'table-fields-metadata',java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.IllegalArgumentException: No enum constant net.snowflake.client.jdbc.SnowflakeType.VECTOR,	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118),	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77),	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74),	at com.mchange.v2.c3p0.impl.NewPooledConnection.handleThrowable(NewPooledConnection.java:505),	at com.mchange.v2.c3p0.impl.NewProxyResultSet.next(NewProxyResultSet.java:699),	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__84551$fn__84552.invoke(common.clj:43),	at clojure.core$repeatedly$fn__6531.invoke(core.clj:5175),	at clojure.lang.LazySeq.sval(LazySeq.java:42),	at clojure.lang.LazySeq.seq(LazySeq.java:51),	at clojure.lang.Cons.next(Cons.java:39),	at clojure.lang.RT.next(RT.java:713),	at clojure.core$next__5451.invokeStatic(core.clj:64),	at clojure.core.protocols$fn__8249.invokeStatic(protocols.clj:169),	at clojure.core.protocols$fn__8249.invoke(protocols.clj:124),	at clojure.core.protocols$fn__8204$G__8199__8213.invoke(protocols.clj:19),	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31),	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75),	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75),	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13),	at clojure.core$reduce.invokeStatic(core.clj:6887),	at clojure.core$reduce.invoke(core.clj:6869),	at metabase.driver.sql_jdbc.sync.common$reducible_results$reify__84551.reduce(common.clj:39),	at clojure.core$transduce.invokeStatic(core.clj:6947),	at clojure.core.Eduction.reduce(core.clj:7751),	at clojure.core$reduce.invokeStatic(core.clj:6886),	at clojure.core$cat$fn__8851.invoke(core.clj:7694),	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343),	at clojure.core$reduce.invokeStatic(core.clj:6886),	at clojure.core$reduce.invoke(core.clj:6869),	at metabase.driver.sql_jdbc.sync.describe_table$fields_metadata$reify__84602.reduce(describe_table.clj:168),	at clojure.core$transduce.invokeStatic(core.clj:6947),	at clojure.core$into.invokeStatic(core.clj:6963),	at clojure.core$into.invoke(core.clj:6951),	at metabase.driver.sql_jdbc.sync.describe_table$fn__84623.invokeStatic(describe_table.clj:214),	at metabase.driver.sql_jdbc.sync.describe_table$fn__84623.invoke(describe_table.clj:212),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.driver.snowflake$fn__115407$fn__115409.invoke(snowflake.clj:562),	at metabase.driver.sql_jdbc.execute$fn__82321$fn__82322.invoke(execute.clj:398),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:338),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:321),	at metabase.driver.sql_jdbc.execute$fn__82321.invokeStatic(execute.clj:392),	at metabase.driver.sql_jdbc.execute$fn__82321.invoke(execute.clj:390),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.driver.snowflake$fn__115407.invokeStatic(snowflake.clj:556),	at metabase.driver.snowflake$fn__115407.invoke(snowflake.clj:554),	at clojure.lang.MultiFn.invoke(MultiFn.java:239),	at metabase.sync.fetch_metadata$table_fields_metadata.invokeStatic(fetch_metadata.clj:45),	at metabase.sync.fetch_metadata$table_fields_metadata.invoke(fetch_metadata.clj:32),	at metabase.sync.fetch_metadata$describe_fields_using_describe_table$fn__85536.invoke(fetch_metadata.clj:60),	at clojure.core$map$fn__5931$fn__5932.invoke(core.clj:2759),	at clojure.core$completing$fn__8528.invoke(core.clj:6932),	at clojure.core$map$fn__5931$fn__5932.invoke(core.clj:2759),	at toucan2.pipeline$with_init$fn__21680.invoke(pipeline.clj:327),	at clojure.core$completing$fn__8528.invoke(core.clj:6932),	at clojure.core$map$fn__5931$fn__5932.invoke(core.clj:2759),	at toucan2.jdbc.result_set$reduce_result_set.invokeStatic(result_set.clj:158),	at toucan2.jdbc.result_set$reduce_result_set.invoke(result_set.clj:125),	at toucan2.jdbc.query$reduce_jdbc_query.invokeStatic(query.clj:51),	at toucan2.jdbc.query$reduce_jdbc_query.invoke(query.clj:22),	at toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default.invokeStatic(pipeline.clj:19),	at toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default.invoke(pipeline.clj:9),	at methodical.impl.combo.common$partial_STAR_$fn__18182.invoke(common.clj:15),	at methodical.impl.combo.threaded$combine_methods_thread_last$fn__18492$combined_method_thread_last__18493.invoke(threaded.clj:64),	at methodical.util.FnWithMeta.invoke(util.clj:46),	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:65),	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47),	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:216),	at toucan2.pipeline$transduce_execute$with_connection_STAR___21600.invoke(pipeline.clj:78),	at toucan2.connection$bind_current_connectable_fn$fn__21277.invoke(connection.clj:104),	at toucan2.connection$bind_current_connectable_fn$fn__21277.invoke(connection.clj:104),	at toucan2.connection$bind_current_connectable_fn$fn__21277.invoke(connection.clj:104),	at toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource.invokeStatic(connection.clj:18),	at toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource.invoke(connection.clj:15),	at methodical.impl.combo.common$partial_STAR_$fn__18182.invoke(common.clj:12),	at methodical.util.FnWithMeta.invoke(util.clj:46),	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118),	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106),	at methodical.impl.combo.common$partial_STAR_$fn__18182.invoke(common.clj:12),	at methodical.util.FnWithMeta.invoke(util.clj:46),	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55),	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47),	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210),	at metabase.db.connection$do_with_connection_primary_method_default.invokeStatic(connection.clj:132),	at metabase.db.connection$do_with_connection_primary_method_default.invoke(connection.clj:130),	at methodical.impl.combo.common$partial_STAR_$fn__18182.invoke(common.clj:12),	at methodical.util.FnWithMeta.invoke(util.clj:46),	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118),	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106),	at methodical.impl.combo.common$partial_STAR_$fn__18182.invoke(common.clj:12),	at methodical.util.FnWithMeta.invoke(util.clj:46),	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55),	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47),	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210),	at toucan2.connection$do_with_connection_primary_method_.invokeStatic(connection.clj:204),	at toucan2.connection$do_with_connection_primary_method_.invoke(connection.clj:194),	at methodical.impl.combo.common$partial_STAR_$fn__18182.invoke(common.clj:12),	at methodical.util.FnWithMeta.invoke(util.clj:46),	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118),	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106),	at methodical.impl.combo.common$partial_STAR_$fn__18182.invoke(common.clj:12),	at methodical.util.FnWithMeta.invoke(util.clj:46),	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55),	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47),	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210),	at toucan2.pipeline$transduce_execute.invokeStatic(pipeline.clj:77),	at toucan2.pipeline$transduce_execute.invoke(pipeline.clj:64),	at clojure.lang.Var.invoke(Var.java:399),	at toucan2.pipeline$transduce_compiled_query.invokeStatic(pipeline.clj:244),	at toucan2.pipeline$transduce_compiled_query.invoke(pipeline.clj:240),	at toucan2.pipeline$transduce_built_query.invokeStatic(pipeline.clj:252),	at toucan2.pipeline$transduce_built_query.invoke(pipeline.clj:246),	at toucan2.pipeline$transduce_query_primary_method_default.invokeStatic(pipeline.clj:272),	at toucan2.pipeline$transduce_query_primary_method_default.invoke(pipeline.clj:269),	at methodical.impl.combo.common$partial_STAR_$fn__18182.invoke(common.clj:15),	at methodical.impl.combo.threaded$combine_methods_thread_last$fn__18492$combined_method_thread_last__18493.invoke(threaded.clj:64),	at methodical.util.FnWithMeta.invoke(util.clj:46),	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:65),	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47),	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:216),	at toucan2.pipeline$transduce_query_STAR_.invokeStatic(pipeline.clj:278),	at toucan2.pipeline$transduce_query_STAR_.invoke(pipeline.clj:274),	at toucan2.pipeline$transduce_with_model.invokeStatic(pipeline.clj:293),	at toucan2.pipeline$transduce_with_model.invoke(pipeline.clj:280),	at toucan2.pipeline$transduce_parsed.invokeStatic(pipeline.clj:309),	at toucan2.pipeline$transduce_parsed.invoke(pipeline.clj:295),	at toucan2.pipeline$transduce_unparsed.invokeStatic(pipeline.clj:317),	at toucan2.pipeline$transduce_unparsed.invoke(pipeline.clj:311),	at clojure.lang.AFn.applyToHelper(AFn.java:160),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.core$apply.invokeStatic(core.clj:669),	at clojure.core$apply.invoke(core.clj:662),	at toucan2.pipeline$reducible_fn$reify__21700.reduce(pipeline.clj:386),	at clojure.core$transduce.invokeStatic(core.clj:6947),	at clojure.core.Eduction.reduce(core.clj:7751),	at clojure.core$transduce.invokeStatic(core.clj:6947),	at clojure.core.Eduction.reduce(core.clj:7751),	at clojure.core$transduce.invokeStatic(core.clj:6947),	at clojure.core$transduce.invoke(core.clj:6934),	at metabase.sync.sync_metadata.fields$sync_fields_BANG_$fn__85598.invoke(fields.clj:82),	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:189),	at metabase.sync.util$do_with_error_handling.invoke(util.clj:182),	at metabase.sync.sync_metadata.fields$sync_fields_BANG_.invokeStatic(fields.clj:76),	at metabase.sync.sync_metadata.fields$sync_fields_BANG_.invoke(fields.clj:71),	at clojure.lang.AFn.applyToHelper(AFn.java:154),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.core$apply.invokeStatic(core.clj:669),	at clojure.core$apply.invoke(core.clj:662),	at metabase.sync.util$run_step_with_metadata$fn__57869$fn__57872.invoke(util.clj:488),	at metabase.models.task_history$do_with_task_history.invokeStatic(task_history.clj:115),	at metabase.models.task_history$do_with_task_history.invoke(task_history.clj:104),	at metabase.sync.util$run_step_with_metadata$fn__57869.doInvoke(util.clj:482),	at clojure.lang.RestFn.invoke(RestFn.java:397),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:130),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:124),	at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:148),	at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:144),	at metabase.sync.util$run_step_with_metadata.invokeStatic(util.clj:477),	at metabase.sync.util$run_step_with_metadata.invoke(util.clj:472),	at metabase.sync.util$run_sync_operation$fn__57911$fn__57919.invoke(util.clj:561),	at metabase.sync.util$run_sync_operation$fn__57911.invoke(util.clj:559),	at metabase.models.task_history$do_with_task_history.invokeStatic(task_history.clj:115),	at metabase.models.task_history$do_with_task_history.invoke(task_history.clj:104),	at metabase.sync.util$run_sync_operation.invokeStatic(util.clj:556),	at metabase.sync.util$run_sync_operation.invoke(util.clj:551),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_$fn__86090.invoke(sync_metadata.clj:70),	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:189),	at metabase.sync.util$do_with_error_handling.invoke(util.clj:182),	at clojure.core$partial$fn__5910.invoke(core.clj:2647),	at metabase.driver$fn__55334.invokeStatic(driver.clj:826),	at metabase.driver$fn__55334.invoke(driver.clj:826),	at clojure.lang.MultiFn.invoke(MultiFn.java:239),	at metabase.sync.util$sync_in_context$fn__57780.invoke(util.clj:165),	at metabase.sync.util$with_db_logging_disabled$fn__57777.invoke(util.clj:157),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:130),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:124),	at metabase.sync.util$with_start_and_finish_logging$fn__57764.invoke(util.clj:142),	at metabase.sync.util$with_sync_events$fn__57759.invoke(util.clj:116),	at metabase.sync.util$with_duplicate_ops_prevented$fn__57746.invoke(util.clj:88),	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:214),	at metabase.sync.util$do_sync_operation.invoke(util.clj:208),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invokeStatic(sync_metadata.clj:68),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invoke(sync_metadata.clj:65),	at metabase.api.database$fn__99281$fn__99286.invoke(database.clj:1021),	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047),	at clojure.lang.AFn.call(AFn.java:18),	at java.base/java.util.concurrent.FutureTask.run(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source),	at java.base/java.lang.Thread.run(Unknown Source),Caused by: java.lang.IllegalArgumentException: No enum constant net.snowflake.client.jdbc.SnowflakeType.VECTOR,	at java.base/java.lang.Enum.valueOf(Unknown Source),	at net.snowflake.client.jdbc.SnowflakeType.valueOf(SnowflakeType.java:23),	at net.snowflake.client.jdbc.SnowflakeType.fromString(SnowflakeType.java:53),	at net.snowflake.client.jdbc.SnowflakeUtil.getSnowflakeType(SnowflakeUtil.java:217),	at net.snowflake.client.jdbc.SnowflakeUtil.extractColumnMetadata(SnowflakeUtil.java:184),	at net.snowflake.client.jdbc.SnowflakeDatabaseMetaData$4.next(SnowflakeDatabaseMetaData.java:1795),	at com.mchange.v2.c3p0.impl.NewProxyResultSet.next(NewProxyResultSet.java:685),	... 184 more

### Information about your Metabase installation

{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "redshift",
      "snowflake"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-10-03",
      "tag": "v0.50.28",
      "hash": "556ae49"
    },
    "settings": {
      "report-timezone": "America/Los_Angeles"
    },
    "hosting-env": "unknown",
    "application-database": "mysql",
    "application-database-details": {
      "database": {
        "name": "MySQL",
        "version": "8.0.28"
      },
      "jdbc-driver": {
        "name": "MariaDB Connector/J",
        "version": "2.7.10"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.10.226-214.879.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}

### Severity

Quite annoying, i had to remove the vector column which is used to detect similar tickets

**Comment by bshepherdson** [comment]
Might not be P1, since it only affects a particular database and only if you're using VECTOR columns.

**Comment by sicarul** [comment]
If it helps in any way, i see support was added on 3.16: https://docs.snowflake.com/en/release-notes/clients-drivers/jdbc-2024#version-3-16-0-april-29-2024

And metabase is currently using 3.12.7 (If i understand correctly):
https://github.com/metabase/metabase/blob/5879f90bfa601fe3a35db153d86cac4d0c1dcc58/modules/drivers/snowflake/resources/metabase-plugin.yaml#L3
That version is from June 2020, we might gain other benefits from upgrading?

**Comment by paoliniluis** [comment]
just merged the dep bump, but I don't think it will make a difference

**Comment by perivamsi** [comment]
I don't think this should be a P1, bumping down to a P2. We can make it a P1 if we have more info.

**Comment by rileythomp** [comment]
@sicarul Is this still occurring for you? I wasn't able to recreate with the current version of the Snowflake JDBC driver

**Comment by sicarul** [comment]
It works now! It doesn't map but it doesn't break the sync now


```
2025-04-10T23:48:43-03:00 WARN metabase.driver.sql-jdbc.sync.describe-table Don't know how to map column type 'VECTOR' to a Field base_type, falling back to :type/*.
```
