### ISSUE TITLE
MongoDB - Can’t connect to database if it doesn’t contain a collection

### ISSUE THREAD

**Issue by FilmonK** [metabase/metabase#49438]
### Describe the bug

You can't connect to a MongoDB instance if the database doesn't have at least a single collection.<br>Normally this isn't an issue but we have customer who is heavily using the API to generate connections as part of their automation. Often there will not be a default collection until a later point.<br>Their goal is to be able implement their automation logic without having to create a "dummy" collection, which is a workaround at the moment.

Tested this in 1.51.1 and 1.50.30.

### To Reproduce

1. Create a Mongo instance using a command like the following:

`docker run --name mongodb -p 27017:27017  -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=password -d mongo:8`

Or YAML

```
version: '3.8'

services:
  mongodb:
    image: mongo:latest 
    container_name: mongodb-container
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  
      MONGO_INITDB_ROOT_PASSWORD: password  
    volumes:
      - ./mongo-data:/data/db 

volumes:
  mongo-data:
    driver: local
```

2. Confirm you're able to connect from Metabase using a connection string like the following:<br>`mongodb://root:password@localhost:27017/admin`
3. If browse the container, you’ll see the following databases and collections created by default and the reason you're able to connect with the string above.

> **show dbs**<br>Databases:<br>admin<br>config<br>local
>
> **show collections**<br>Collections:<br>system.users<br>system.version

4. Now, create a new database, new user, and grant permissions

```
use newdb

db.createUser({
  user: "appUser",
  pwd: "password",
  roles: [ { role: "readWrite", db: "newdb" } ]
});
```

5. Confirm you can connect to this database using the newly created account directly.

```
docker exec -it <Docker container> /bin/bash

mongosh --username appUser --password password --authenticationDatabase newdb
```

6. Try to connect within Metabase using a connection string like the following and won't be able. I've posted the logs below.

```
mongodb://appUser:password@localhost:27017/newdb
or
mongodb://appUser:password@localhost:27017/newdb?authSource=newdb
```

7. Create a collection in the newdb database. You should be able to connect from within Metabase.

```
use newdb
db.sampleCollection.insertOne({ name: "testDocument", value: 123 });
```

### Expected behavior

For a user to be able to connect to an empty database in the same way you can with something like postgres.

### Logs

2024-11-01 10:20:15,009 DEBUG mongo.connection :: Opened new MongoClient.<br>2024-11-01 10:20:15,072 DEBUG mongo.connection :: Closed MongoClient.<br>2024-11-01 10:20:15,072 ERROR driver.util :: Failed to connect to Database<br>java.lang.Exception: Failed to connect to Database<br>	at metabase.driver.util$can_connect_with_details_QMARK\_$fn__56584.invoke(util.clj:167)<br>	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)<br>	at clojure.lang.AFn.call(AFn.java:18)<br>	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br>	at java.base/java.lang.Thread.run(Thread.java:829)<br>2024-11-01 10:20:15,075 DEBUG mongo.connection :: Opened new MongoClient.<br>2024-11-01 10:20:15,109 DEBUG mongo.connection :: Closed MongoClient.<br>2024-11-01 10:20:15,109 ERROR driver.util :: Failed to connect to Database<br>java.lang.Exception: Failed to connect to Database<br>	at metabase.driver.util$can_connect_with_details_QMARK\_$fn__56584.invoke(util.clj:167)<br>	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)<br>	at clojure.lang.AFn.call(AFn.java:18)<br>	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br>	at java.base/java.lang.Thread.run(Thread.java:829)<br>2024-11-01 10:20:15,110 ERROR api.database :: Cannot connect to Database<br>clojure.lang.ExceptionInfo: Failed to connect to Database {:message "Failed to connect to Database"}<br>	at metabase.driver.util$can_connect_with_details_QMARK\_.invokeStatic(util.clj:184)<br>	at metabase.driver.util$can_connect_with_details_QMARK\_.doInvoke(util.clj:155)<br>	at clojure.lang.RestFn.invoke(RestFn.java:442)<br>	at metabase.api.database$test_database_connection.invokeStatic(database.clj:730)<br>	at metabase.api.database$test_database_connection.doInvoke(database.clj:720)<br>	at clojure.lang.RestFn.invoke(RestFn.java:425)<br>	at metabase.api.database$test_connection_details.invokeStatic(database.clj:784)<br>	at metabase.api.database$test_connection_details.invoke(database.clj:764)<br>	at metabase.api.database$fn__100408.invokeStatic(database.clj:805)<br>	at metabase.api.database$fn__100408.invoke(database.clj:788)<br>	at compojure.core$wrap_response$fn__52791.invoke(core.clj:160)<br>	at compojure.core$wrap_route_middleware$fn__52775.invoke(core.clj:132)<br>	at compojure.core$wrap_route_info$fn__52780.invoke(core.clj:139)<br>	at compojure.core$wrap_route_matches$fn__52784.invoke(core.clj:151)<br>	at clojure.lang.Var.invoke(Var.java:393)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$wrap_route_matches$fn__52784.invoke(core.clj:152)<br>	at clojure.lang.Var.invoke(Var.java:393)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803.invoke(core.clj:200)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at metabase.server.middleware.auth$enforce_authentication$fn__98681.invoke(auth.clj:18)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803.invoke(core.clj:200)<br>	at compojure.core$make_context$handler__52831.invoke(core.clj:290)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:300)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$wrap_route_matches$fn__52784.invoke(core.clj:153)<br>	at clojure.lang.Var.invoke(Var.java:393)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:199)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:199)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803.invoke(core.clj:200)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:199)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803.invoke(core.clj:200)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803.invoke(core.clj:200)<br>	at metabase.api.routes$fn__104362$fn__104363.invoke(routes.clj:70)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803.invoke(core.clj:200)<br>	at clojure.lang.AFn.applyToHelper(AFn.java:160)<br>	at clojure.lang.AFn.applyTo(AFn.java:144)<br>	at clojure.core$apply.invokeStatic(core.clj:667)<br>	at clojure.core$apply.invoke(core.clj:662)<br>	at metabase.server.routes$fn__104642$fn__104643.doInvoke(routes.clj:73)<br>	at clojure.lang.RestFn.invoke(RestFn.java:436)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803.invoke(core.clj:200)<br>	at compojure.core$make_context$handler__52831.invoke(core.clj:290)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:300)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$wrap_route_matches$fn__52784.invoke(core.clj:153)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$wrap_route_matches$fn__52784.invoke(core.clj:153)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$wrap_route_matches$fn__52784.invoke(core.clj:153)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$wrap_route_matches$fn__52784.invoke(core.clj:153)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:199)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:199)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:199)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803.invoke(core.clj:200)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803.invoke(core.clj:200)<br>	at compojure.core$make_context$handler__52831.invoke(core.clj:290)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:300)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803$f__52804$respond_SINGLEQUOTE___52805.invoke(core.clj:197)<br>	at compojure.core$make_context$fn__52835.invoke(core.clj:301)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803.invoke(core.clj:200)<br>	at compojure.core$routes$fn__52803$f__52804.invoke(core.clj:198)<br>	at compojure.core$routes$fn__52803.invoke(core.clj:200)<br>	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__100715.invoke(exceptions.clj:107)<br>	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__100712.invoke(exceptions.clj:96)<br>	at metabase.server.middleware.log$log_api_call$fn__106990$fn__106991$fn__106992.invoke(log.clj:233)<br>	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:18)<br>	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12)<br>	at metabase.server.middleware.log$log_api_call$fn__106990$fn__106991.invoke(log.clj:224)<br>	at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112)<br>	at toucan2.execute$do_with_call_counts.invoke(execute.clj:103)<br>	at metabase.server.middleware.log$log_api_call$fn__106990.invoke(log.clj:223)<br>	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__113194.invoke(browser_cookie.clj:40)<br>	at metabase.server.middleware.security$add_security_headers$fn__100671.invoke(security.clj:246)<br>	at ring.middleware.json$wrap_json_body$fn__113453.invoke(json.clj:64)<br>	at metabase.server.middleware.offset_paging$handle_paging$fn__89034.invoke(offset_paging.clj:43)<br>	at metabase.server.middleware.json$wrap_streamed_json_response$fn__54419.invoke(json.clj:83)<br>	at ring.middleware.keyword_params$wrap_keyword_params$fn__113542.invoke(keyword_params.clj:55)<br>	at ring.middleware.params$wrap_params$fn__113561.invoke(params.clj:77)<br>	at metabase.server.middleware.misc$maybe_set_site_url$fn__64764.invoke(misc.clj:59)<br>	at metabase.server.middleware.session$reset_session_timeout$fn__66317.invoke(session.clj:549)<br>	at metabase.server.middleware.session$bind_current_user$fn__66283$fn__66284.invoke(session.clj:443)<br>	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:422)<br>	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:405)<br>	at metabase.server.middleware.session$bind_current_user$fn__66283.invoke(session.clj:442)<br>	at metabase.server.middleware.session$wrap_current_user_info$fn__66264.invoke(session.clj:381)<br>	at metabase.server.middleware.session$wrap_session_id$fn__66236.invoke(session.clj:259)<br>	at metabase.server.middleware.auth$wrap_static_api_key$fn__98689.invoke(auth.clj:32)<br>	at ring.middleware.cookies$wrap_cookies$fn__113381.invoke(cookies.clj:200)<br>	at metabase.server.middleware.misc$add_content_type$fn__64746.invoke(misc.clj:28)<br>	at metabase.server.middleware.misc$disable_streaming_buffering$fn__64772.invoke(misc.clj:75)<br>	at ring.middleware.gzip$wrap_gzip$fn__113423.invoke(gzip.clj:86)<br>	at metabase.server.middleware.misc$bind_request$fn__64775.invoke(misc.clj:91)<br>	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__113210.invoke(ssl.clj:41)<br>	at metabase.server$async_proxy_handler$fn__72520.invoke(server.clj:77)<br>	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)<br>	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)<br>	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)<br>	at org.eclipse.jetty.server.Server.handle(Server.java:563)<br>	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)<br>	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)<br>	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)<br>	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)<br>	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)<br>	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)<br>	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)<br>	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)<br>	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)<br>	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)<br>	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)<br>	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)<br>	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)<br>	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)<br>	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)<br>	at java.base/java.lang.Thread.run(Thread.java:829)<br>Caused by: java.lang.Exception: Failed to connect to Database<br>	at metabase.driver.util$can_connect_with_details_QMARK\_$fn__56584.invoke(util.clj:167)<br>	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)<br>	at clojure.lang.AFn.call(AFn.java:18)<br>	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br>	... 1 more<br>2024-11-01 10:20:15,117 DEBUG middleware.log :: POST /api/database 400 121.2 ms (1 DB calls) {:metabase-user-id 1} <br>{:message "Failed to connect to Database"}

### Information about your Metabase installation

{<br>  "browser-info": {<br>    "language": "en-US",<br>    "platform": "MacIntel",<br>    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",<br>    "vendor": "Google Inc."<br>  },<br>  "metabase-info": {<br>    "databases": \[<br>      "h2",<br>      "postgres"<br>    \],<br>    "run-mode": "prod",<br>    "plan-alias": "enterprise-self-hosted",<br>    "version": {<br>      "date": "2024-10-23",<br>      "tag": "v1.51.1",<br>      "hash": "b8178a8"<br>    },<br>    "settings": {<br>      "report-timezone": null<br>    },<br>    "hosting-env": "unknown",<br>    "application-database": "postgres",<br>    "application-database-details": {<br>      "database": {<br>        "name": "PostgreSQL",<br>        "version": "15.3"<br>      },<br>      "jdbc-driver": {<br>        "name": "PostgreSQL JDBC Driver",<br>        "version": "42.7.3"<br>      }<br>    }<br>  },<br>  "system-info": {<br>    "file.encoding": "UTF-8",<br>    "[java.runtime.name](<http://java.runtime.name>)": "OpenJDK Runtime Environment",<br>    "java.runtime.version": "11.0.22+7",<br>    "java.vendor": "Eclipse Adoptium",<br>    "java.vendor.url": "[https://adoptium.net/](<https://adoptium.net/>)",<br>    "java.version": "11.0.22",<br>    "[java.vm.name](<http://java.vm.name>)": "OpenJDK 64-Bit Server VM",<br>    "java.vm.version": "11.0.22+7",<br>    "[os.name](<http://os.name>)": "Mac OS X",<br>    "os.version": "14.5",<br>    "user.language": "en",<br>    "user.timezone": "America/Chicago"<br>  }<br>}

### Severity

P2

### Additional context

*No response*

**Comment by rileythomp** [comment]
Can reproduce with the steps provided
