### ISSUE TITLE
Exporting pivots to XLSX with "Keep Data Pivoted" selected can Crash Metabase (Heap memory error) and pegs CPU

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#49977]
### Describe the bug

Exporting Pivots to XLSX can eat memory and can cause the JVM to crash. 

### To Reproduce

1. Set up v51.1 locally with 1GB RAM
2. Create a pivot with accounts and invoices that has a handful of breakouts (Loom recording below)
3. Export to XLSX with "Keep Data Pivoted" selected
4. Metabase crashed with OOM error

https://www.loom.com/share/9446d6efe8af4bba8ebc23b322c8d3e6

### Expected behavior

We [recommend deploying with 1G](https://www.metabase.com/learn/metabase-basics/administration/administration-and-operation/metabase-in-production#metabase-application-server-size) for every 20 concurrent users so I wouldn't expect to to hit heap memory in this case. The pivot table wasn't very large:

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2",
      "postgres",
      "sqlserver",
      "mysql",
      "oracle",
      "databricks"
    ],
    "run-mode": "prod",
    "plan-alias": "enterprise-self-hosted",
    "version": {
      "date": "2024-10-23",
      "tag": "v1.51.1",
      "hash": "b8178a8"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.1 (Debian 15.1-1.pgdg110+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.24+8",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "11.0.24",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.24+8",
    "os.name": "Linux",
    "os.version": "5.15.153.1-microsoft-standard-WSL2",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

blocking upgrade

### Additional context

Customer that initially reported this is running on 2GB and sees their instances crash intermittently with pivot exports. They want to upgrade to the next minor release to see some other patches but they're concerned about moving to a version where exporting these files pivoted is the default behavior given these crashes.

**Comment by Tony-metabase** [comment]
Note that this is also impacting the CPU ...When i try to download this pivot now  [question on stats](https://stats.metabase.com/question/20344-large-pivots-break-download-tony)
It seems I am able to bring stats down


![Image](https://github.com/user-attachments/assets/7fcda101-92f0-45d8-b8c2-e5ca9ad120fb)

This was me pressing that download pivot button (Keep Formatting) .... I guess we reached the CPU limit and kubernetes was killing the pod.

**Comment by sgarbesi** [comment]
running into the same issue on the latest version of Metabase.
anytime we try to export a CSV with a pivot and formatting, the server memory jumps to 8GB and crashes.
using the latest version of Metabase.

@ixipixi did you ever come up with a resolution to this?

**Comment by paoliniluis** [comment]
@sgarbesi what's the "latest version" for you?

**Comment by sgarbesi** [comment]
@paoliniluis 0.51.6.1

**Comment by paoliniluis** [comment]
@sgarbesi try with 51.7

**Comment by pmcmanaman** [comment]
@paoliniluis We've updated to v0.52.1.3 and still see the same issue

**Comment by sgarbesi** [comment]
@paoliniluis anything we can provide that may help?

**Comment by paoliniluis** [comment]
@sgarbesi @pmcmanaman please send us:
- sizing of the container (also how much memory the process gets on start)
- logs
- environment variables used (we're interested in the ones that modify the api response and the downloads)
- the size of the data and the pivot table (how massive is the query)

**Comment by pmcmanaman** [comment]
@paoliniluis 
- The container gets at least 3CPU and 8GB of memory with limits of 4CPU and 16GB.
- logs below
- no environment variables, so just default

```
2024-12-26 15:09:21,354 ERROR middleware.process-userland-query :: Error saving field usages
clojure.lang.ExceptionInfo: Unknown type of ref {:ref [:contains {:case-sensitive false, :effective-type :type/Boolean, :lib/uuid "ff904e48-203f-4d62-a7f9-a5a8c5588ad5"} [:field {:base-type :type/Text, :lib/uuid "90052ad0-f81e-4564-a128-41eb19671b00"} "subscription_plan_name"] [:value {:effective_type :type/Text, :base-type :type/Text, :effective-type :type/Text, :lib/uuid "aefa5b8a-ff9f-43f4-af1e-ea92f9c3f4bb"} "gold"]]}
	at metabase.lib.equality$find_matching_column31939__31942.invokeStatic(equality.cljc:308)
	at metabase.lib.equality$find_matching_column31939__31942.invoke(equality.cljc:264)
	at metabase.lib.equality$find_matching_column31939__31942.invokeStatic(equality.cljc:321)
	at metabase.lib.equality$find_matching_column31939__31942.invoke(equality.cljc:264)
	at metabase.lib.equality$find_matching_column31939__31942.invokeStatic(equality.cljc:311)
	at metabase.lib.equality$find_matching_column31939__31942.invoke(equality.cljc:264)
	at metabase.lib.filter$filter_parts32794__32795.invokeStatic(filter.cljc:552)
	at metabase.lib.filter$filter_parts32794__32795.invoke(filter.cljc:540)
	at metabase.models.field_usage$filter__GT_field_usage.invokeStatic(field_usage.clj:29)
	at metabase.models.field_usage$filter__GT_field_usage.invoke(field_usage.clj:27)
	at metabase.models.field_usage$stage__GT_field_usages$fn__78326.invoke(field_usage.clj:76)
	at clojure.core$keep$fn__8691.invoke(core.clj:7529)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.realize(LazySeq.java:89)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.RT.seq(RT.java:555)
	at clojure.core$seq__5486.invokeStatic(core.clj:139)
	at clojure.core$concat$fn__5577.invoke(core.clj:727)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.realize(LazySeq.java:89)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.RT.seq(RT.java:555)
	at clojure.core$seq__5486.invokeStatic(core.clj:139)
	at clojure.core$concat$cat__5579$fn__5580.invoke(core.clj:736)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.lockAndForce(LazySeq.java:60)
	at clojure.lang.LazySeq.sval(LazySeq.java:69)
	at clojure.lang.LazySeq.unwrap(LazySeq.java:77)
	at clojure.lang.LazySeq.realize(LazySeq.java:93)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.RT.seq(RT.java:555)
	at clojure.core$seq__5486.invokeStatic(core.clj:139)
	at clojure.core$map$fn__5954.invoke(core.clj:2763)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.realize(LazySeq.java:89)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.RT.seq(RT.java:555)
	at clojure.core$seq__5486.invokeStatic(core.clj:139)
	at clojure.core$concat$cat__5579$fn__5580.invoke(core.clj:736)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.lockAndForce(LazySeq.java:60)
	at clojure.lang.LazySeq.sval(LazySeq.java:69)
	at clojure.lang.LazySeq.unwrap(LazySeq.java:77)
	at clojure.lang.LazySeq.realize(LazySeq.java:93)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.RT.seq(RT.java:555)
	at clojure.core$seq__5486.invokeStatic(core.clj:139)
	at clojure.core$map$fn__5954.invoke(core.clj:2763)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.realize(LazySeq.java:89)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.RT.seq(RT.java:555)
	at clojure.core$seq__5486.invokeStatic(core.clj:139)
	at clojure.core$dorun.invokeStatic(core.clj:3141)
	at clojure.core$doall.invokeStatic(core.clj:3156)
	at clojure.walk$walk.invokeStatic(walk.clj:47)
	at clojure.walk$prewalk.invokeStatic(walk.clj:65)
	at clojure.walk$prewalk.invoke(walk.clj:61)
	at clojure.core$partial$fn__5927.invoke(core.clj:2641)
	at clojure.core$map$fn__5954.invoke(core.clj:2772)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.realize(LazySeq.java:89)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.Cons.next(Cons.java:41)
	at clojure.lang.RT.next(RT.java:733)
	at clojure.core$next__5470.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3150)
	at clojure.core$doall.invokeStatic(core.clj:3156)
	at clojure.walk$walk.invokeStatic(walk.clj:47)
	at clojure.walk$prewalk.invokeStatic(walk.clj:65)
	at clojure.walk$prewalk.invoke(walk.clj:61)
	at clojure.core$partial$fn__5927.invoke(core.clj:2641)
	at clojure.walk$walk.invokeStatic(walk.clj:46)
	at clojure.walk$prewalk.invokeStatic(walk.clj:65)
	at clojure.walk$prewalk.invoke(walk.clj:61)
	at clojure.core$partial$fn__5927.invoke(core.clj:2641)
	at clojure.core$map$fn__5954.invoke(core.clj:2772)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.realize(LazySeq.java:89)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.Cons.next(Cons.java:41)
	at clojure.lang.RT.next(RT.java:733)
	at clojure.core$next__5470.invokeStatic(core.clj:64)
	at clojure.core.protocols$fn__8275.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8275.invoke(protocols.clj:123)
	at clojure.core.protocols$fn__8229$G__8224__8238.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8262.invokeStatic(protocols.clj:74)
	at clojure.core.protocols$fn__8262.invoke(protocols.clj:74)
	at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6965)
	at clojure.core$into.invokeStatic(core.clj:7038)
	at clojure.walk$walk.invokeStatic(walk.clj:50)
	at clojure.walk$prewalk.invokeStatic(walk.clj:65)
	at clojure.walk$prewalk.invoke(walk.clj:61)
	at clojure.core$partial$fn__5927.invoke(core.clj:2641)
	at clojure.core$map$fn__5954.invoke(core.clj:2770)
	at clojure.lang.LazySeq.force(LazySeq.java:50)
	at clojure.lang.LazySeq.realize(LazySeq.java:89)
	at clojure.lang.LazySeq.seq(LazySeq.java:106)
	at clojure.lang.RT.seq(RT.java:555)
	at clojure.core$seq__5486.invokeStatic(core.clj:139)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__8262.invokeStatic(protocols.clj:74)
	at clojure.core.protocols$fn__8262.invoke(protocols.clj:74)
	at clojure.core.protocols$fn__8203$G__8198__8216.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6965)
	at clojure.core$into.invokeStatic(core.clj:7038)
	at clojure.walk$walk.invokeStatic(walk.clj:50)
	at clojure.walk$prewalk.invokeStatic(walk.clj:65)
	at clojure.walk$prewalk.invoke(walk.clj:61)
	at toucan2.util$add_context_to_ex_data$fn__22416.invoke(util.clj:53)
	at clojure.core$update.invokeStatic(core.clj:6259)
	at clojure.core$update.invoke(core.clj:6251)
	at toucan2.util$add_context_to_ex_data.invokeStatic(util.clj:51)
	at toucan2.util$add_context_to_ex_data.invoke(util.clj:50)
	at toucan2.util$fn__22422.invokeStatic(util.clj:78)
	at toucan2.util$fn__22422.invoke(util.clj:72)
	at toucan2.util$fn__22402$G__22397__22409.invoke(util.clj:47)
	at toucan2.query$parse_args_with_spec.invokeStatic(query.clj:69)
	at toucan2.query$parse_args_with_spec.invoke(query.clj:66)
	at toucan2.insert$parse_args_primary_method_toucan_query_type_insert__STAR_.invokeStatic(insert.clj:35)
	at toucan2.insert$parse_args_primary_method_toucan_query_type_insert__STAR_.invoke(insert.clj:32)
	at methodical.impl.combo.common$partial_STAR_$fn__19388.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210)
	at toucan2.pipeline$transduce_unparsed.invokeStatic(pipeline.clj:315)
	at toucan2.pipeline$transduce_unparsed.invoke(pipeline.clj:311)
	at toucan2.pipeline$transduce_unparsed_with_default_rf.invokeStatic(pipeline.clj:374)
	at toucan2.pipeline$transduce_unparsed_with_default_rf.invoke(pipeline.clj:368)
	at toucan2.insert$insert_BANG_.invokeStatic(insert.clj:124)
	at toucan2.insert$insert_BANG_.doInvoke(insert.clj:74)
	at clojure.lang.RestFn.invoke(RestFn.java:424)
	at metabase.query_processor.middleware.process_userland_query$fn__78349$fn__78350$fn__78351.invoke(process_userland_query.clj:43)
	at grouper.core$body_fn$fn__62202.invoke(core.clj:72)
	at grouper.core$start_BANG_$thread__62245.invoke(core.clj:135)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Tony-metabase** [comment]
@pmcmanaman one important factor missing there. What about the size of the data and the pivot table (how massive is the query)

**Comment by pmcmanaman** [comment]
@Tony-metabase 
1 pivot rows
8 pivot columns
31920 rows

**Comment by paoliniluis** [comment]
@pmcmanaman if you're using the defaults then there's a problem, since Metabase will use just 1/4 of the RAM of the server and if it goes above a certain threshold the CPU will start doing garbage collection aggresively. Have you seen https://www.metabase.com/docs/latest/troubleshooting-guide/running#allocating-more-memory-to-the-jvm?

**Comment by pmcmanaman** [comment]
@paoliniluis This happens when the JVM has a large amount of RAM

2024-12-27 18:18:14,606 INFO metabase.util :: Maximum memory available to JVM: 8.0 GB

**Comment by paoliniluis** [comment]
@pmcmanaman just reproduced, we need to fix this ASAP

**Comment by dpsutton** [comment]
In profiling, I found the CSV export did an enormous amount of work in `metabase.query-processor.pivot.postprocess/build-pivot-output`.

**Comment by alexander-yakushev** [comment]
Oh no, not pivot again:).
