### ISSUE TITLE
an exception occurred while mb syncs table structure everyday , 2 dbs and 2 same table names with different structure

### ISSUE THREAD

**Issue by feng-dreaming** [metabase/metabase#50382]
### Describe the bug

![Image](https://github.com/user-attachments/assets/ae728ab8-8189-40c7-9a5c-f46e68750778)
an exception occurred while mb syncs table structure everyday
more details:
1. mb version is 0.51.3
2. source db is mysql 5.7.28 , one instace
3. most important , mysql instance has 2 dbs ,  both have same table 't_nursing_record' ,  and they have 5 same fields , 3 are different , I think this is the reason

I guess adding database filter to where clause will fix the problem

one other suggestion : in general one MySQL instance has more then one db , change database field from required to optional where there will be reduce db connections in adding database page , espically in big data applications there will benefit from this change

### To Reproduce

1. Go to 'database'
2. Click on 'hgs'
3. Scroll down to 't_nursing_record' table, click on it
![Image](https://github.com/user-attachments/assets/7436f180-5c0c-4cb5-88c3-8719535e9a04)

### Expected behavior

no exception

### Logs

2024-11-22 10:17:07,233 WARN sync.util :: Error fingerprinting Table 211 ''t_nursing_record''
clojure.lang.ExceptionInfo: 执行查询时出错：(conn=14917287) Unknown column 't_nursing_record.memo' in 'field list' {:driver :mysql, :sql ["-- Metabase" "SELECT" "  SUBSTRING(`t_nursing_record`.`memo`, 1, 1234) AS `substring107908`" "FROM" "  `t_nursing_record`" "LIMIT" "  10000"], :params nil, :type :invalid-query}
	at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__87286$fn__87287.invoke(execute.clj:717)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__87286.invoke(execute.clj:714)
	at metabase.driver.sql_jdbc.execute$fn__87090$fn__87091.invoke(execute.clj:398)
	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection87060__87061.invokeStatic(execute.clj:338)
	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection87060__87061.invoke(execute.clj:321)
	at metabase.driver.sql_jdbc.execute$fn__87090.invokeStatic(execute.clj:392)
	at metabase.driver.sql_jdbc.execute$fn__87090.invoke(execute.clj:390)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:708)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:705)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694)
	at metabase.driver.sql_jdbc$fn__113432.invokeStatic(sql_jdbc.clj:79)
	at metabase.driver.sql_jdbc$fn__113432.invoke(sql_jdbc.clj:77)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at metabase.query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:47)
	at metabase.query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:34)
	at metabase.query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:97)
	at metabase.query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:90)
	at metabase.query_processor.execute$run.invokeStatic(execute.clj:62)
	at metabase.query_processor.execute$run.invoke(execute.clj:56)
	at metabase.query_processor.middleware.update_used_cards$update_used_cards_BANG_76957__76958$fn__76959.invoke(update_used_cards.clj:60)
	at metabase.query_processor.execute$add_native_form_to_result_metadata$fn__76974.invoke(execute.clj:25)
	at metabase.query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__76980.invoke(execute.clj:36)
	at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___76930.invoke(cache.clj:241)
	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__73967.invoke(permissions.clj:147)
	at metabase.query_processor.middleware.enterprise$check_download_permissions_middleware$fn__74678.invoke(enterprise.clj:51)
	at metabase.query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__74688.invoke(enterprise.clj:64)
	at metabase.query_processor.execute$execute77007__77008$fn__77009.invoke(execute.clj:94)
	at metabase.query_processor.setup$do_with_qp_setup75203__75204.invokeStatic(setup.clj:225)
	at metabase.query_processor.setup$do_with_qp_setup75203__75204.invoke(setup.clj:216)
	at metabase.query_processor.execute$execute77007__77008.invokeStatic(execute.clj:93)
	at metabase.query_processor.execute$execute77007__77008.invoke(execute.clj:89)
	at metabase.query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49)
	at metabase.query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44)
	at metabase.query_processor.middleware.enterprise$fn__74705$handle_audit_app_internal_queries__74706$fn__74708.invoke(enterprise.clj:96)
	at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__74716.invoke(enterprise.clj:103)
	at metabase.query_processor.middleware.process_userland_query$process_userland_query_middleware77863__77864$fn__77865.invoke(process_userland_query.clj:191)
	at metabase.query_processor.middleware.catch_exceptions$catch_exceptions77928__77929$fn__77930.invoke(catch_exceptions.clj:125)
	at metabase.query_processor$process_query77969__77970$fn__77971.invoke(query_processor.clj:80)
	at metabase.query_processor.setup$do_with_canceled_chan75198__75199$fn__75200.invoke(setup.clj:189)
	at metabase.query_processor.setup$do_with_database_local_settings75191__75192$fn__75193.invoke(setup.clj:181)
	at metabase.query_processor.setup$do_with_driver75184__75185$fn__75186$fn__75187.invoke(setup.clj:166)
	at metabase.driver$do_with_driver.invokeStatic(driver.clj:106)
	at metabase.driver$do_with_driver.invoke(driver.clj:101)
	at metabase.query_processor.setup$do_with_driver75184__75185$fn__75186.invoke(setup.clj:165)
	at metabase.query_processor.setup$do_with_metadata_provider75175__75176$fn__75177.invoke(setup.clj:140)
	at metabase.query_processor.setup$do_with_resolved_database75165__75166$fn__75167.invoke(setup.clj:128)
	at metabase.query_processor.setup$do_with_qp_setup75203__75204.invokeStatic(setup.clj:232)
	at metabase.query_processor.setup$do_with_qp_setup75203__75204.invoke(setup.clj:216)
	at metabase.query_processor$process_query77969__77970.invokeStatic(query_processor.clj:78)
	at metabase.query_processor$process_query77969__77970.invoke(query_processor.clj:71)
	at metabase.db.metadata_queries$table_rows_sample80859__80860.invokeStatic(metadata_queries.clj:181)
	at metabase.db.metadata_queries$table_rows_sample80859__80860.invoke(metadata_queries.clj:164)
	at metabase.db.metadata_queries$fn__80862.invokeStatic(metadata_queries.clj:185)
	at metabase.db.metadata_queries$fn__80862.invoke(metadata_queries.clj:183)
	at clojure.lang.MultiFn.invoke(MultiFn.java:252)
	at metabase.sync.analyze.fingerprint$fingerprint_table_BANG_90769__90770.invokeStatic(fingerprint.clj:88)
	at metabase.sync.analyze.fingerprint$fingerprint_table_BANG_90769__90770.invoke(fingerprint.clj:65)
	at metabase.sync.analyze.fingerprint$fingerprint_fields_BANG_90818__90819$fn__90820.invoke(fingerprint.clj:206)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:191)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:184)
	at metabase.sync.analyze.fingerprint$fingerprint_fields_BANG_90818__90819.invokeStatic(fingerprint.clj:204)
	at metabase.sync.analyze.fingerprint$fingerprint_fields_BANG_90818__90819.invoke(fingerprint.clj:198)
	at metabase.sync.analyze.fingerprint$fingerprint_fields_for_db_BANG__STAR_90826__90827$fn__90828$fn__90829.invoke(fingerprint.clj:230)
	at clojure.core$completing$fn__8558.invoke(core.clj:7010)
	at clojure.core$map$fn__5950$fn__5951.invoke(core.clj:2759)
	at toucan2.pipeline$with_init$fn__22812.invoke(pipeline.clj:327)
	at clojure.core$completing$fn__8558.invoke(core.clj:7010)
	at clojure.core$map$fn__5950$fn__5951.invoke(core.clj:2759)
	at toucan2.jdbc.result_set$reduce_result_set.invokeStatic(result_set.clj:156)
	at toucan2.jdbc.result_set$reduce_result_set.invoke(result_set.clj:125)
	at toucan2.jdbc.query$reduce_jdbc_query.invokeStatic(query.clj:51)
	at toucan2.jdbc.query$reduce_jdbc_query.invoke(query.clj:22)
	at toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default.invokeStatic(pipeline.clj:19)
	at toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default.invoke(pipeline.clj:9)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:15)
	at methodical.impl.combo.threaded$combine_methods_thread_last$fn__19646$combined_method_thread_last__19647.invoke(threaded.clj:64)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:65)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:216)
	at toucan2.pipeline$transduce_execute$with_connection_STAR___22732.invoke(pipeline.clj:78)
	at toucan2.connection$bind_current_connectable_fn$fn__22409.invoke(connection.clj:104)
	at toucan2.connection$bind_current_connectable_fn$fn__22409.invoke(connection.clj:104)
	at toucan2.connection$bind_current_connectable_fn$fn__22409.invoke(connection.clj:104)
	at toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource.invokeStatic(connection.clj:18)
	at toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource.invoke(connection.clj:15)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210)
	at metabase.db.connection$do_with_connection_primary_method_default.invokeStatic(connection.clj:132)
	at metabase.db.connection$do_with_connection_primary_method_default.invoke(connection.clj:130)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210)
	at toucan2.connection$do_with_connection_primary_method_.invokeStatic(connection.clj:204)
	at toucan2.connection$do_with_connection_primary_method_.invoke(connection.clj:194)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210)
	at toucan2.pipeline$transduce_execute.invokeStatic(pipeline.clj:77)
	at toucan2.pipeline$transduce_execute.invoke(pipeline.clj:64)
	at clojure.lang.Var.invoke(Var.java:401)
	at toucan2.pipeline$transduce_compiled_query.invokeStatic(pipeline.clj:244)
	at toucan2.pipeline$transduce_compiled_query.invoke(pipeline.clj:240)
	at toucan2.pipeline$transduce_built_query.invokeStatic(pipeline.clj:252)
	at toucan2.pipeline$transduce_built_query.invoke(pipeline.clj:246)
	at toucan2.pipeline$transduce_query_primary_method_default.invokeStatic(pipeline.clj:272)
	at toucan2.pipeline$transduce_query_primary_method_default.invoke(pipeline.clj:269)
	at methodical.impl.combo.common$partial_STAR_$fn__19336.invoke(common.clj:15)
	at methodical.impl.combo.threaded$combine_methods_thread_last$fn__19646$combined_method_thread_last__19647.invoke(threaded.clj:64)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:65)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:216)
	at toucan2.pipeline$transduce_query_STAR_.invokeStatic(pipeline.clj:278)
	at toucan2.pipeline$transduce_query_STAR_.invoke(pipeline.clj:274)
	at toucan2.pipeline$transduce_with_model.invokeStatic(pipeline.clj:293)
	at toucan2.pipeline$transduce_with_model.invoke(pipeline.clj:280)
	at toucan2.pipeline$transduce_parsed.invokeStatic(pipeline.clj:309)
	at toucan2.pipeline$transduce_parsed.invoke(pipeline.clj:295)
	at toucan2.pipeline$transduce_unparsed.invokeStatic(pipeline.clj:317)
	at toucan2.pipeline$transduce_unparsed.invoke(pipeline.clj:311)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at toucan2.pipeline$reducible_fn$reify__22832.reduce(pipeline.clj:386)
	at clojure.core$transduce.invokeStatic(core.clj:7025)
	at clojure.core.Eduction.reduce(core.clj:7874)
	at clojure.core$reduce.invokeStatic(core.clj:6964)
	at clojure.core$reduce.invoke(core.clj:6947)
	at metabase.sync.analyze.fingerprint$fingerprint_fields_for_db_BANG__STAR_90826__90827$fn__90828.invoke(fingerprint.clj:228)
	at metabase.query_processor.store$do_with_metadata_provider58710__58711.invokeStatic(store.clj:170)
	at metabase.query_processor.store$do_with_metadata_provider58710__58711.invoke(store.clj:150)
	at metabase.query_processor.store$do_with_metadata_provider58710__58711.invokeStatic(store.clj:159)
	at metabase.query_processor.store$do_with_metadata_provider58710__58711.invoke(store.clj:150)
	at metabase.sync.analyze.fingerprint$fingerprint_fields_for_db_BANG__STAR_90826__90827.invokeStatic(fingerprint.clj:224)
	at metabase.sync.analyze.fingerprint$fingerprint_fields_for_db_BANG__STAR_90826__90827.invoke(fingerprint.clj:215)
	at metabase.sync.analyze.fingerprint$fingerprint_fields_for_db_BANG__STAR_90826__90827.invokeStatic(fingerprint.clj:219)
	at metabase.sync.analyze.fingerprint$fingerprint_fields_for_db_BANG__STAR_90826__90827.invoke(fingerprint.clj:215)
	at metabase.sync.analyze.fingerprint$fingerprint_fields_for_db_BANG_90833__90834.invokeStatic(fingerprint.clj:242)
	at metabase.sync.analyze.fingerprint$fingerprint_fields_for_db_BANG_90833__90834.invoke(fingerprint.clj:237)
	at metabase.sync.analyze$make_analyze_steps$fn__90984.invoke(analyze.clj:100)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$run_step_with_metadata65871__65873$fn__65875$fn__65878.invoke(util.clj:495)
	at metabase.models.task_history$do_with_task_history65708__65709.invokeStatic(task_history.clj:121)
	at metabase.models.task_history$do_with_task_history65708__65709.invoke(task_history.clj:109)
	at metabase.sync.util$run_step_with_metadata65871__65873$fn__65875.doInvoke(util.clj:488)
	at clojure.lang.RestFn.invoke(RestFn.java:400)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:132)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:126)
	at metabase.sync.util$do_with_start_and_finish_debug_logging.invokeStatic(util.clj:150)
	at metabase.sync.util$do_with_start_and_finish_debug_logging.invoke(util.clj:146)
	at metabase.sync.util$run_step_with_metadata65871__65873.invokeStatic(util.clj:482)
	at metabase.sync.util$run_step_with_metadata65871__65873.invoke(util.clj:477)
	at metabase.sync.util$run_sync_operation65921__65922$fn__65923$fn__65931.invoke(util.clj:568)
	at metabase.sync.util$run_sync_operation65921__65922$fn__65923.invoke(util.clj:566)
	at metabase.models.task_history$do_with_task_history65708__65709.invokeStatic(task_history.clj:121)
	at metabase.models.task_history$do_with_task_history65708__65709.invoke(task_history.clj:109)
	at metabase.sync.util$run_sync_operation65921__65922.invokeStatic(util.clj:563)
	at metabase.sync.util$run_sync_operation65921__65922.invoke(util.clj:558)
	at metabase.sync.analyze$analyze_db_BANG_90991__90992$fn__90993.invoke(analyze.clj:116)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:191)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:184)
	at clojure.core$partial$fn__5929.invoke(core.clj:2647)
	at metabase.driver$fn__58386.invokeStatic(driver.clj:892)
	at metabase.driver$fn__58386.invoke(driver.clj:892)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__65780.invoke(util.clj:167)
	at metabase.sync.util$with_db_logging_disabled$fn__65777.invoke(util.clj:159)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:132)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging$fn__65764.invoke(util.clj:144)
	at metabase.sync.util$with_sync_events65754__65755$fn__65759.invoke(util.clj:118)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__65744.invoke(util.clj:90)
	at metabase.sync.util$do_sync_operation65795__65796.invokeStatic(util.clj:216)
	at metabase.sync.util$do_sync_operation65795__65796.invoke(util.clj:210)
	at metabase.sync.analyze$analyze_db_BANG_90991__90992.invokeStatic(analyze.clj:114)
	at metabase.sync.analyze$analyze_db_BANG_90991__90992.invoke(analyze.clj:109)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invokeStatic(sync_databases.clj:91)
	at metabase.task.sync_databases$sync_and_analyze_database_STAR__BANG_.invoke(sync_databases.clj:71)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invokeStatic(sync_databases.clj:107)
	at metabase.task.sync_databases$sync_and_analyze_database_BANG_.invoke(sync_databases.clj:95)
	at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:112)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.sql.SQLSyntaxErrorException: (conn=14917287) Unknown column 't_nursing_record.memo' in 'field list'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:362)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:500)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
	at metabase.driver.sql_jdbc.execute$fn__87216.invokeStatic(execute.clj:570)
	at metabase.driver.sql_jdbc.execute$fn__87216.invoke(execute.clj:568)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invokeStatic(execute.clj:578)
	at metabase.driver.sql_jdbc.execute$execute_statement_or_prepared_statement_BANG_.invoke(execute.clj:575)
	at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__87286$fn__87287.invoke(execute.clj:715)
	... 208 more
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Unknown column 't_nursing_record.memo' in 'field list'
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:195)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:263)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356)
	... 216 more
Caused by: java.sql.SQLException: Unknown column 't_nursing_record.memo' in 'field list'
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1693)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1555)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1518)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:257)
	... 217 more

### Information about your Metabase installation

```JSON
1.chrome 131.0.6778.69
2.jar file deployed 
3.centos 7.6
```

### Severity

blocking users

**Comment by perivamsi** [comment]
This is fixed in 51.4 by this PR https://github.com/metabase/metabase/pull/50091
