### ISSUE TITLE
sync-fields task failed - class java.lang.ClassCastException

### ISSUE THREAD

**Issue by dorsegal** [metabase/metabase#50930]
### Describe the bug

added new database and Metabase can't get columns data.
![Image](https://github.com/user-attachments/assets/a6c78b51-cc95-4cc4-9b70-059a6d249ec2)

I tried running "Sync database schema now" and noticed an error in logs.
`{"status":"failed","exception":"class java.lang.ClassCastException","message":null,"stacktrace":[null],"ex-data":null,"original-info":null}`

Please note my database is Starrocks and it is compatible with mysql.
I already have databased and tables working with it. This is a new issue and I don't know if it is metabase side or Starrocks.
![Image](https://github.com/user-attachments/assets/a34f8f53-e46c-4731-8ff8-1f7f6375041c)

### To Reproduce

1. Add new Mysql database
2. Got to Admin  > Table Metadata > check id columns where identified.

### Logs

```
2024-12-05 13:10:56,802 DEBUG middleware.log :: GET /api/health 200 228.7 µs (0 DB calls) App DB connections: 0/7 Jetty threads: 8/50 (2 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id nil}
2024-12-05 13:10:59,647 WARN driver.mysql ::

********************************************************************************
WARNING: Metabase only officially supports MySQL 5.7/MariaDB 10.2 and above.
All Metabase features may not work properly when using an unsupported version.
********************************************************************************

2024-12-05 13:10:59,648 DEBUG sync.util :: Sync operations in flight: {:sync-metadata #{36}}
2024-12-05 13:10:59,648 DEBUG middleware.log :: POST /api/database/36/sync_schema 200 20.0 ms (1 DB calls) App DB connections: 0/7 Jetty threads: 8/50 (2 idle, 0 queued) (43 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
2024-12-05 13:10:59,648 INFO sync.util :: STARTING: Sync metadata for mysql Database 36 ''Test''
2024-12-05 13:10:59,704 INFO sync.util :: STARTING: step ''sync-dbms-version'' for mysql Database 36 ''Test''
2024-12-05 13:10:59,711 INFO sync.util :: FINISHED: step ''sync-dbms-version'' for mysql Database 36 ''Test'' (7.1 ms)
2024-12-05 13:10:59,712 INFO sync.util :: STARTING: step ''sync-timezone'' for mysql Database 36 ''Test''
2024-12-05 13:10:59,719 WARN sync.util :: Error running step ''sync-timezone'' for mysql Database 36 ''Test''
java.sql.SQLTransientConnectionException: (conn=884) Getting analyzing error from line 1, column 73 to line 1, column 173. Detail message: No matching function with signature: time_format(TIME, varchar).
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1113)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
	at metabase.driver.mysql$fn__113067.invokeStatic(mysql.clj:239)
	at metabase.driver.mysql$fn__113067.invoke(mysql.clj:229)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.sql_jdbc$fn__115544.invokeStatic(sql_jdbc.clj:73)
	at metabase.driver.sql_jdbc$fn__115544.invoke(sql_jdbc.clj:68)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.sync.sync_metadata.sync_timezone$sync_timezone_BANG_91670__91671.invokeStatic(sync_timezone.clj:41)
	at metabase.sync.sync_metadata.sync_timezone$sync_timezone_BANG_91670__91671.invoke(sync_timezone.clj:36)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.sync.util$run_step_with_metadata63542__63544$fn__63546$fn__63549.invoke(util.clj:495)
	at metabase.models.task_history$do_with_task_history63379__63380.invokeStatic(task_history.clj:121)
	at metabase.models.task_history$do_with_task_history63379__63380.invoke(task_history.clj:109)
	at metabase.sync.util$run_step_with_metadata63542__63544$fn__63546.doInvoke(util.clj:488)
	at clojure.lang.RestFn.invoke(RestFn.java:400)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:132)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:126)
	at metabase.sync.util$do_with_start_and_finish_debug_logging.invokeStatic(util.clj:150)
	at metabase.sync.util$do_with_start_and_finish_debug_logging.invoke(util.clj:146)
	at metabase.sync.util$run_step_with_metadata63542__63544.invokeStatic(util.clj:482)
	at metabase.sync.util$run_step_with_metadata63542__63544.invoke(util.clj:477)
	at metabase.sync.util$run_sync_operation63592__63593$fn__63594$fn__63602.invoke(util.clj:568)
	at metabase.sync.util$run_sync_operation63592__63593$fn__63594.invoke(util.clj:566)
	at metabase.models.task_history$do_with_task_history63379__63380.invokeStatic(task_history.clj:121)
	at metabase.models.task_history$do_with_task_history63379__63380.invoke(task_history.clj:109)
	at metabase.sync.util$run_sync_operation63592__63593.invokeStatic(util.clj:563)
	at metabase.sync.util$run_sync_operation63592__63593.invoke(util.clj:558)
	at metabase.sync.sync_metadata$sync_db_metadata_BANG_93843__93844$fn__93845.invoke(sync_metadata.clj:70)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:191)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:184)
	at clojure.core$partial$fn__5929.invoke(core.clj:2647)
	at metabase.driver$fn__59430.invokeStatic(driver.clj:892)
	at metabase.driver$fn__59430.invoke(driver.clj:892)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.sync.util$sync_in_context$fn__63451.invoke(util.clj:167)
	at metabase.sync.util$with_db_logging_disabled$fn__63448.invoke(util.clj:159)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:132)
	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:126)
	at metabase.sync.util$with_start_and_finish_logging$fn__63435.invoke(util.clj:144)
	at metabase.sync.util$with_sync_events63425__63426$fn__63430.invoke(util.clj:118)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__63415.invoke(util.clj:90)
	at metabase.sync.util$do_sync_operation63466__63467.invokeStatic(util.clj:216)
	at metabase.sync.util$do_sync_operation63466__63467.invoke(util.clj:210)
	at metabase.sync.sync_metadata$sync_db_metadata_BANG_93843__93844.invokeStatic(sync_metadata.clj:68)
	at metabase.sync.sync_metadata$sync_db_metadata_BANG_93843__93844.invoke(sync_metadata.clj:65)
	at metabase.api.database$fn__106321$fn__106326.invoke(database.clj:1017)
	at clojure.core$binding_conveyor_fn$fn__5842.invoke(core.clj:2047)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Getting analyzing error from line 1, column 73 to line 1, column 173. Detail message: No matching function with signature: time_format(TIME, varchar).
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:195)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:178)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:322)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 65 more
Caused by: java.sql.SQLException: Getting analyzing error from line 1, column 73 to line 1, column 173. Detail message: No matching function with signature: time_format(TIME, varchar).
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1693)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1555)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1518)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:319)
	... 66 more
2024-12-05 13:10:59,720 INFO sync.util :: FINISHED: step ''sync-timezone'' for mysql Database 36 ''Test'' (8.2 ms)
2024-12-05 13:10:59,720 INFO sync.util :: STARTING: step ''sync-tables'' for mysql Database 36 ''Test''
2024-12-05 13:10:59,724 INFO sync-metadata.tables :: Found new table: Table  ''data''
2024-12-05 13:10:59,736 INFO sync-metadata.tables :: Marking tables as inactive: (Table  ''records'' Table  ''cells'')
2024-12-05 13:10:59,742 INFO sync-metadata.tables :: Updating table metadata for Table 93 ''data''
2024-12-05 13:10:59,745 INFO sync.util :: FINISHED: step ''sync-tables'' for mysql Database 36 ''Test'' (24.4 ms)
2024-12-05 13:10:59,745 INFO sync.util :: STARTING: step ''sync-fields'' for mysql Database 36 ''Test''
2024-12-05 13:10:59,762 WARN sync.util :: Error syncing Fields for Database ''mysql Database 36 ''Test''''
java.lang.ClassCastException
2024-12-05 13:10:59,764 WARN sync.util :: Error running step ''sync-fields'' for mysql Database 36 ''Test''
java.lang.ClassCastException
2024-12-05 13:10:59,764 INFO sync.util :: FINISHED: step ''sync-fields'' for mysql Database 36 ''Test'' (19.5 ms)
2024-12-05 13:10:59,764 INFO sync.util :: STARTING: step ''sync-fks'' for mysql Database 36 ''Test''
2024-12-05 13:10:59,813 INFO sync.util :: FINISHED: step ''sync-fks'' for mysql Database 36 ''Test'' (48.8 ms)
2024-12-05 13:10:59,814 INFO sync.util :: STARTING: step ''sync-indexes'' for mysql Database 36 ''Test''
2024-12-05 13:10:59,836 INFO sync.util :: FINISHED: step ''sync-indexes'' for mysql Database 36 ''Test'' (22.7 ms)
2024-12-05 13:10:59,837 INFO sync.util :: STARTING: step ''sync-metabase-metadata'' for mysql Database 36 ''Test''
2024-12-05 13:10:59,841 INFO sync.util :: FINISHED: step ''sync-metabase-metadata'' for mysql Database 36 ''Test'' (4.7 ms)
2024-12-05 13:10:59,842 INFO sync.util :: STARTING: step ''sync-table-privileges'' for mysql Database 36 ''Test''
2024-12-05 13:10:59,846 INFO sync.util :: FINISHED: step ''sync-table-privileges'' for mysql Database 36 ''Test'' (4.9 ms)
2024-12-05 13:10:59,847 DEBUG sync.util ::
#################################################################
# Completed sync on Test
# Start: 2024-12-05T13:10:59.704699333Z
# End: 2024-12-05T13:10:59.847092029Z
# Duration: 142.4 ms
# ---------------------------------------------------------------
# Completed step ''sync-dbms-version''
# Start: 2024-12-05T13:10:59.704711258Z
# End: 2024-12-05T13:10:59.712030093Z
# Duration: 7.3 ms
# Found DBMS version 5.1.0
# ---------------------------------------------------------------
# Completed step ''sync-timezone''
# Start: 2024-12-05T13:10:59.712048241Z
# End: 2024-12-05T13:10:59.720399892Z
# Duration: 8.4 ms
# Found timezone id null
# ---------------------------------------------------------------
# Completed step ''sync-tables''
# Start: 2024-12-05T13:10:59.720466629Z
# End: 2024-12-05T13:10:59.745160088Z
# Duration: 24.7 ms
# Total number of tables sync''d 2, number of tables updated 3
# ---------------------------------------------------------------
# Completed step ''sync-fields''
# Start: 2024-12-05T13:10:59.745180072Z
# End: 2024-12-05T13:10:59.764832306Z
# Duration: 19.7 ms
# Total number of fields sync''d null, number of fields updated null
# ---------------------------------------------------------------
# Completed step ''sync-fks''
# Start: 2024-12-05T13:10:59.764920806Z
# End: 2024-12-05T13:10:59.814078998Z
# Duration: 49.2 ms
# Total number of foreign keys sync''d 0, 0 updated and 0 tables failed to update
# ---------------------------------------------------------------
# Completed step ''sync-indexes''
# Start: 2024-12-05T13:10:59.814102431Z
# End: 2024-12-05T13:10:59.837030075Z
# Duration: 22.9 ms
# Total number of indexes sync''d 0, 0 added and 0 removed
# ---------------------------------------------------------------
# Completed step ''sync-metabase-metadata''
# Start: 2024-12-05T13:10:59.837052657Z
# End: 2024-12-05T13:10:59.841995605Z
# Duration: 4.9 ms
# ---------------------------------------------------------------
# Completed step ''sync-table-privileges''
# Start: 2024-12-05T13:10:59.842015202Z
# End: 2024-12-05T13:10:59.847082573Z
# Duration: 5.1 ms
#################################################################

2024-12-05 13:10:59,850 INFO sync.util :: FINISHED: Sync metadata for mysql Database 36 ''Test'' (201.3 ms)
2024-12-05 13:10:59,850 DEBUG sync.util :: Sync operations in flight: {:analyze #{36}}
2024-12-05 13:10:59,850 INFO sync.util :: STARTING: Analyze data for mysql Database 36 ''Test''
2024-12-05 13:10:59,854 INFO sync.util :: STARTING: step ''fingerprint-fields'' for mysql Database 36 ''Test''
2024-12-05 13:10:59,859 INFO sync.analyze :: fingerprint-fields Analyzed [************······································] 😒   25% Table 93 ''data''
2024-12-05 13:10:59,862 INFO sync.util :: FINISHED: step ''fingerprint-fields'' for mysql Database 36 ''Test'' (8.6 ms)
2024-12-05 13:10:59,863 INFO sync.util :: STARTING: step ''classify-fields'' for mysql Database 36 ''Test''
2024-12-05 13:10:59,867 INFO sync.analyze :: classify-fields Analyzed [*************************·························] 😬   50% Table 93 ''data''
2024-12-05 13:10:59,869 INFO sync.util :: FINISHED: step ''classify-fields'' for mysql Database 36 ''Test'' (6.3 ms)
2024-12-05 13:10:59,869 INFO sync.util :: STARTING: step ''classify-tables'' for mysql Database 36 ''Test''
2024-12-05 13:10:59,874 DEBUG analyze.classify :: Based on classification, updating these values of Table 93 ''data'': {:entity_type :entity/GenericTable}
2024-12-05 13:10:59,876 INFO sync.analyze :: classify-tables Analyzed [*************************************·············] 😋   75% Table 93 ''data''
2024-12-05 13:10:59,879 INFO sync.util :: FINISHED: step ''classify-tables'' for mysql Database 36 ''Test'' (9.6 ms)
2024-12-05 13:10:59,879 DEBUG sync.util ::
#################################################################
# Completed analyze on Test
# Start: 2024-12-05T13:10:59.854171769Z
# End: 2024-12-05T13:10:59.879344325Z
# Duration: 25.2 ms
# ---------------------------------------------------------------
# Completed step ''fingerprint-fields''
# Start: 2024-12-05T13:10:59.8541806Z
# End: 2024-12-05T13:10:59.862980148Z
# Duration: 8.8 ms
# Fingerprint updates attempted 0, updated 0, no data found 0, failed 0
# ---------------------------------------------------------------
# Completed step ''classify-fields''
# Start: 2024-12-05T13:10:59.862991364Z
# End: 2024-12-05T13:10:59.869513767Z
# Duration: 6.5 ms
# Total number of fields classified 0, 0 failed
# ---------------------------------------------------------------
# Completed step ''classify-tables''
# Start: 2024-12-05T13:10:59.869524562Z
# End: 2024-12-05T13:10:59.879332182Z
# Duration: 9.8 ms
# Total number of tables classified 1, 1 updated
#################################################################

2024-12-05 13:10:59,883 INFO sync.util :: FINISHED: Analyze data for mysql Database 36 ''Test'' (32.4 ms)
```

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-12-04",
      "tag": "v0.52.1",
      "hash": "5bc320b"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "2.1.214 (2022-06-13)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "2.1.214 (2022-06-13)"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.5+11-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.5+11-LTS",
    "os.name": "Linux",
    "os.version": "6.1.115",
    "user.language": "en",
    "user.timezone": "UTC"
  }
}
```

### Severity

blocking

### Additional context

Ignore sync-timezone errors.

**Comment by dpsutton** [comment]
> Please note my database is Starrocks and it is compatible with mysql.

> Caused by: java.sql.SQLException: Getting analyzing error from line 1, column 73 to line 1, column 173. Detail message: No matching function with signature: time_format(TIME, varchar).

We attempt to get the timezone of the db with this: https://github.com/metabase/metabase/blob/master/src/metabase/driver/mysql.clj#L233 which runs the query

```sql
SELECT @@GLOBAL.time_zone AS global_tz, 
       @@system_time_zone AS system_tz,
       time_format(  
          timediff(
            now(), convert_tz(now(), @@GLOBAL.time_zone, '+00:00')
          ),
         '%H:%i' ) AS 'offset';
```

The complaint seems to be about this.

**Comment by paoliniluis** [comment]
we don't support Starrocks: https://github.com/metabase/metabase/issues/28081

**Comment by stdpain** [comment]
supported in https://github.com/StarRocks/starrocks/pull/53724

**Comment by aruizhong** [comment]
> supported in [StarRocks/starrocks#53724](https://github.com/StarRocks/starrocks/pull/53724)
Hi, Can this merge directly to solve this problem, I tried a custom function time_format, although not an error can't find time_format function, but will still have a warning log Java. Lang. ClassCastException, The fields are not synchronized

**Comment by dorsegal** [comment]
@dpsutton could you have a look again? Starrocks implemented a fix for time_format function. 

`sync-timezone` step passes with no errors but my original `sync-fields` error remains.

<img width="993" alt="Image" src="https://github.com/user-attachments/assets/eaa098ce-ef49-473e-bc81-8384160360a2" />

**Comment by dorsegal** [comment]
Looks like adding `tinyInt1isBit=false` in additional JDBC connection string options works.

**Comment by ScalaFirst** [comment]
> Looks like adding `tinyInt1isBit=false` in additional JDBC connection string options works.

its good for me
