### ISSUE TITLE
The Metabase server terminated unexpectedly at Sierra 10.12.4

### ISSUE THREAD

**Issue by CarolHsu** [metabase/metabase#5126]
Metabase version 0.24.0.1

I've gotten the same issue with the closed issue [#4246](https://github.com/metabase/metabase/issues/4246), my OS X versions is Sierra 10.12.4.

I know it's happened and been solved before, I tried the solution but it's not working for me. (And it's older version so I move back to the latest one)

<img width="653" alt="screen shot 2017-05-17 at 11 22 00 am" src="https://cloud.githubusercontent.com/assets/1646695/26137255/ae5f646c-3af3-11e7-8cec-1d5d79fa55f2.png">

**Comment by salsakran** [comment]
What else is in the logs? Can you pull our the actual server logs via the "Logs" menu item in the upper right corner of the applicaiton?

**Comment by camsaul** [comment]
This is actually the same issue as the one we're discussing in #6068, so I'm going to close this as a duplicate. @CarolHsu check out #6068, I posted a link to a new build of 0.26.1 that I think should resolve the issues you're seeing.

**Comment by fandomfilms** [comment]
I just updated metabase on mac and got this

The Metabase server terminated unexpectedly.

Messages:
WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__21120@3b2a5402: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__21120@3b2a5402: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__21120@3b2a5402: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
java.lang.Exception: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.at metabase.db$wait_for_migration_lock_to_be_cleared$fn__21120.invoke(db.clj:148)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:713)
at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:717)
at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:717)
at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:717)
at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:717)at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:717)
at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.db$wait_for_migration_lock_to_be_cleared.invokeStatic(db.clj:146)
at metabase.db$wait_for_migration_lock_to_be_cleared.invoke(db.clj:142)
at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:161)
at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:151)
at metabase.db$migrate_BANG_$fn__21163.invoke(db.clj:247)
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:740)
at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
at metabase.db$migrate_BANG_.invokeStatic(db.clj:235)
at metabase.db$migrate_BANG_.invoke(db.clj:218)
at
