### ISSUE TITLE
Deadlock on the app db (52)

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#51316]
### Describe the bug

Got a deadlock on the app db, I think this was when I was deleting an DB, but I may be wrong. EDIT: it's when analyzing a card

### To Reproduce

I really don't know how to repro, got it while a script that I run to initialize instances. It seems to be happening when Metabase analyzes the cards

### Expected behavior

We shouldn't cause any deadlocks

### Logs

```
2024-12-15 21:01:41,045 INFO task.sweep-query-analysis :: Recalculating potentially stale analysis
2024-12-15 21:01:42,052 ERROR task.analyze-queries :: Error analysing and updating query for Card 37
clojure.lang.ExceptionInfo: ERROR: deadlock detected
  Detail: Process 59 waits for ShareLock on transaction 2093; blocked by process 57.
Process 57 waits for ShareLock on transaction 2091; blocked by process 59.
  Hint: See server log for query details.
  Where: while locking tuple (3,6) in relation "metabase_field"
SQL statement "SELECT 1 FROM ONLY "public"."metabase_field" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x" {:toucan2/context-trace [["execute SQL with class com.mchange.v2.c3p0.impl.NewProxyConnection" {:toucan2.jdbc.query/sql-args ["INSERT INTO \"query_field\" (\"card_id\", \"analysis_id\", \"schema\", \"table\", \"column\", \"table_id\", \"field_id\", \"explicit_reference\") VALUES (?, ?, NULL, ?, ?, ?, ?, TRUE), (?, ?, NULL, ?, ?, ?, ?, TRUE), (?, ?, NULL, ?, ?, ?, ?, TRUE)" 37 118 "ORDERS" "PRODUCT_ID" 2 14 37 118 "ORDERS" "CREATED_AT" 2 13 37 118 "ORDERS" "QUANTITY" 2 2]}] ["resolve connection" {:toucan2.connection/connectable org.postgresql.jdbc.PgConnection}] ["resolve connection" {:toucan2.connection/connectable nil}] {:toucan2.pipeline/rf #object[clojure.core$completing$fn__8558 0x12136d20 "clojure.core$completing$fn__8558@12136d20"]} ["with compiled query" {:toucan2.pipeline/compiled-query ["INSERT INTO \"query_field\" (\"card_id\", \"analysis_id\", \"schema\", \"table\", \"column\", \"table_id\", \"field_id\", \"explicit_reference\") VALUES (?, ?, NULL, ?, ?, ?, ?, TRUE), (?, ?, NULL, ?, ?, ?, ?, TRUE), (?, ?, NULL, ?, ?, ?, ?, TRUE)" 37 118 "ORDERS" "PRODUCT_ID" 2 14 37 118 "ORDERS" "CREATED_AT" 2 13 37 118 "ORDERS" "QUANTITY" 2 2]}] ["with built query" {:toucan2.pipeline/built-query {:insert-into [:query_field], :values ((toucan2.instance/instance :model/QueryField {:card_id 37, :analysis_id 118, :schema nil, :table "ORDERS", :column "PRODUCT_ID", :table_id 2, :field_id 14, :explicit_reference true}) (toucan2.instance/instance :model/QueryField {:card_id 37, :analysis_id 118, :schema nil, :table "ORDERS", :column "CREATED_AT", :table_id 2, :field_id 13, :explicit_reference true}) (toucan2.instance/instance :model/QueryField {:card_id 37, :analysis_id 118, :schema nil, :table "ORDERS", :column "QUANTITY", :table_id 2, :field_id 2, :explicit_reference true}))}}] ["with resolved query" {:toucan2.pipeline/resolved-query {}}] ["with parsed args" {:toucan2.pipeline/query-type :toucan.query-type/insert.update-count, :toucan2.pipeline/parsed-args {:rows [{:card_id 37, :analysis_id 118, :schema nil, :table "ORDERS", :column "PRODUCT_ID", :table_id 2, :field_id 14, :explicit_reference true} {:card_id 37, :analysis_id 118, :schema nil, :table "ORDERS", :column "CREATED_AT", :table_id 2, :field_id 13, :explicit_reference true} {:card_id 37, :analysis_id 118, :schema nil, :table "ORDERS", :column "QUANTITY", :table_id 2, :field_id 2, :explicit_reference true}]}}] ["with model" {:toucan2.pipeline/model :model/QueryField}] ["with unparsed args" {:toucan2.pipeline/query-type :toucan.query-type/insert.update-count, :toucan2.pipeline/unparsed-args (:model/QueryField ({:card_id 37, :analysis_id 118, :schema nil, :table "ORDERS", :column "PRODUCT_ID", :table_id 2, :field_id 14, :explicit_reference true} {:card_id 37, :analysis_id 118, :schema nil, :table "ORDERS", :column "CREATED_AT", :table_id 2, :field_id 13, :explicit_reference true} {:card_id 37, :analysis_id 118, :schema nil, :table "ORDERS", :column "QUANTITY", :table_id 2, :field_id 2, :explicit_reference true}))}] ["resolve connection" {:toucan2.connection/connectable metabase.db.connection.ApplicationDB}] ["resolve connection" {:toucan2.connection/connectable :default}] ["resolve connection" {:toucan2.connection/connectable nil}]]}
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:180)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:67)
	at toucan2.jdbc.query$reduce_jdbc_query.invokeStatic(query.clj:40)
	at toucan2.jdbc.query$reduce_jdbc_query.invoke(query.clj:22)
	at toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default.invokeStatic(pipeline.clj:19)
	at toucan2.jdbc.pipeline$transduce_execute_with_connection_primary_method_java_sql_Connection_default_default.invoke(pipeline.clj:9)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:15)
	at methodical.impl.combo.threaded$combine_methods_thread_last$fn__19702$combined_method_thread_last__19703.invoke(threaded.clj:64)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:65)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:216)
	at toucan2.pipeline$transduce_execute$with_connection_STAR___22784$with_transaction_STAR___22785.invoke(pipeline.clj:75)
	at toucan2.connection$bind_current_connectable_fn$fn__22465.invoke(connection.clj:104)
	at metabase.db.connection$do_with_transaction_primary_method_java_sql_Connection.invokeStatic(connection.clj:180)
	at metabase.db.connection$do_with_transaction_primary_method_java_sql_Connection.invoke(connection.clj:162)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:13)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_transaction_around_method_toucan2_connection_default.invokeStatic(connection.clj:249)
	at toucan2.connection$do_with_transaction_around_method_toucan2_connection_default.invoke(connection.clj:245)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:13)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:58)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:212)
	at toucan2.pipeline$transduce_execute$with_connection_STAR___22784.invoke(pipeline.clj:74)
	at toucan2.connection$bind_current_connectable_fn$fn__22465.invoke(connection.clj:104)
	at toucan2.connection$bind_current_connectable_fn$fn__22465.invoke(connection.clj:104)
	at toucan2.jdbc.connection$do_with_connection_primary_method_java_sql_Connection.invokeStatic(connection.clj:13)
	at toucan2.jdbc.connection$do_with_connection_primary_method_java_sql_Connection.invoke(connection.clj:11)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210)
	at toucan2.connection$do_with_connection_primary_method_.invokeStatic(connection.clj:204)
	at toucan2.connection$do_with_connection_primary_method_.invoke(connection.clj:194)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210)
	at toucan2.pipeline$transduce_execute.invokeStatic(pipeline.clj:74)
	at toucan2.pipeline$transduce_execute.invoke(pipeline.clj:64)
	at clojure.lang.Var.invoke(Var.java:401)
	at toucan2.pipeline$transduce_compiled_query.invokeStatic(pipeline.clj:244)
	at toucan2.pipeline$transduce_compiled_query.invoke(pipeline.clj:240)
	at toucan2.pipeline$transduce_built_query.invokeStatic(pipeline.clj:252)
	at toucan2.pipeline$transduce_built_query.invoke(pipeline.clj:246)
	at toucan2.pipeline$transduce_query_primary_method_default.invokeStatic(pipeline.clj:272)
	at toucan2.pipeline$transduce_query_primary_method_default.invoke(pipeline.clj:269)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:15)
	at methodical.impl.combo.threaded$combine_methods_thread_last$fn__19702$combined_method_thread_last__19703.invoke(threaded.clj:64)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:65)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:216)
	at toucan2.pipeline$transduce_query_STAR_.invokeStatic(pipeline.clj:278)
	at toucan2.pipeline$transduce_query_STAR_.invoke(pipeline.clj:274)
	at toucan2.pipeline$transduce_with_model.invokeStatic(pipeline.clj:293)
	at toucan2.pipeline$transduce_with_model.invoke(pipeline.clj:280)
	at toucan2.pipeline$transduce_parsed.invokeStatic(pipeline.clj:309)
	at toucan2.pipeline$transduce_parsed.invoke(pipeline.clj:295)
	at toucan2.pipeline$transduce_unparsed.invokeStatic(pipeline.clj:317)
	at toucan2.pipeline$transduce_unparsed.invoke(pipeline.clj:311)
	at toucan2.pipeline$transduce_unparsed_with_default_rf.invokeStatic(pipeline.clj:374)
	at toucan2.pipeline$transduce_unparsed_with_default_rf.invoke(pipeline.clj:368)
	at toucan2.insert$insert_BANG_.invokeStatic(insert.clj:124)
	at toucan2.insert$insert_BANG_.doInvoke(insert.clj:74)
	at clojure.lang.RestFn.invoke(RestFn.java:424)
	at metabase.query_analysis$update_query_analysis_for_card_BANG_$with_connection_STAR___75567$with_transaction_STAR___75568.invoke(query_analysis.clj:157)
	at toucan2.connection$bind_current_connectable_fn$fn__22465.invoke(connection.clj:104)
	at metabase.db.connection$do_transaction$thunk__43610.invoke(connection.clj:140)
	at metabase.db.connection$do_transaction.invokeStatic(connection.clj:152)
	at metabase.db.connection$do_transaction.invoke(connection.clj:136)
	at metabase.db.connection$do_with_transaction_primary_method_java_sql_Connection.invokeStatic(connection.clj:189)
	at metabase.db.connection$do_with_transaction_primary_method_java_sql_Connection.invoke(connection.clj:162)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:13)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_transaction_around_method_toucan2_connection_default.invokeStatic(connection.clj:249)
	at toucan2.connection$do_with_transaction_around_method_toucan2_connection_default.invoke(connection.clj:245)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:13)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:58)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:212)
	at metabase.query_analysis$update_query_analysis_for_card_BANG_$with_connection_STAR___75567.invoke(query_analysis.clj:132)
	at toucan2.connection$bind_current_connectable_fn$fn__22465.invoke(connection.clj:104)
	at toucan2.connection$bind_current_connectable_fn$fn__22465.invoke(connection.clj:104)
	at toucan2.connection$bind_current_connectable_fn$fn__22465.invoke(connection.clj:104)
	at toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource.invokeStatic(connection.clj:18)
	at toucan2.jdbc.connection$do_with_connection_primary_method_javax_sql_DataSource.invoke(connection.clj:15)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210)
	at metabase.db.connection$do_with_connection_primary_method_default.invokeStatic(connection.clj:132)
	at metabase.db.connection$do_with_connection_primary_method_default.invoke(connection.clj:130)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210)
	at toucan2.connection$do_with_connection_primary_method_.invokeStatic(connection.clj:204)
	at toucan2.connection$do_with_connection_primary_method_.invoke(connection.clj:194)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invokeStatic(connection.clj:118)
	at toucan2.connection$do_with_connection_around_method_toucan2_connection_default.invoke(connection.clj:106)
	at methodical.impl.combo.common$partial_STAR_$fn__19392.invoke(common.clj:12)
	at methodical.util.FnWithMeta.invoke(util.clj:46)
	at methodical.impl.standard$invoke_multifn.invokeStatic(standard.clj:55)
	at methodical.impl.standard$invoke_multifn.invoke(standard.clj:47)
	at methodical.impl.standard.StandardMultiFn.invoke(standard.clj:210)
	at metabase.query_analysis$update_query_analysis_for_card_BANG_.invokeStatic(query_analysis.clj:132)
	at metabase.query_analysis$update_query_analysis_for_card_BANG_.invoke(query_analysis.clj:124)
	at metabase.query_analysis$analyze_BANG__STAR_.invokeStatic(query_analysis.clj:239)
	at metabase.query_analysis$analyze_BANG__STAR_.invoke(query_analysis.clj:228)
	at metabase.task.analyze_queries$analyzer_loop_STAR_$fn__117936.invoke(analyze_queries.clj:51)
	at metabase.task.analyze_queries$analyzer_loop_STAR_.invokeStatic(analyze_queries.clj:50)
	at metabase.task.analyze_queries$analyzer_loop_STAR_.invoke(analyze_queries.clj:40)
	at metabase.task.analyze_queries$analyzer_loop_BANG_.invokeStatic(analyze_queries.clj:73)
	at metabase.task.analyze_queries$analyzer_loop_BANG_.invoke(analyze_queries.clj:69)
	at metabase.task.analyze_queries$analyzer_loop_BANG_.invokeStatic(analyze_queries.clj:71)
	at metabase.task.analyze_queries$analyzer_loop_BANG_.invoke(analyze_queries.clj:69)
	at metabase.task.analyze_queries.QueryAnalyzer.execute(analyze_queries.clj:82)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 59 waits for ShareLock on transaction 2093; blocked by process 57.
Process 57 waits for ShareLock on transaction 2091; blocked by process 59.
  Hint: See server log for query details.
  Where: while locking tuple (3,6) in relation "metabase_field"
SQL statement "SELECT 1 FROM ONLY "public"."metabase_field" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
	... 151 more
2024-12-15 21:01:42,076 DEBUG middleware.log :: DELETE /api/database/1 204 1111ms (149 DB calls) App DB connections: 1/7 Jetty threads: 6/50 (1 idle, 0 queued) (52 total active threads) Queries in flight: 0 (0 queued) {:metabase-user-id 1}
```

### Information about your Metabase installation

```JSON
v52.2.6
```

### Severity

P1

### Additional context

This is the lab
https://github.com/paoliniluis/metabase-serialization

**Comment by paoliniluis** [comment]
EDIT: does not happen in 51

**Comment by crisptrutski** [comment]
This is pretty strange, as the transaction should be write-only. Toucan must be inserting that select for some reason, but at first glance it's unclear why as there are no hooks defined on the relevant model.

**Comment by crisptrutski** [comment]
Using toucan monitor to examine the queries issued from a local instance with PostgreSQL, this blocking SELECT 1 is not being issued.

```
"INSERT INTO ""QUERY_ANALYSIS"" (""CARD_ID"", ""STATUS"") VALUES (?, ?)","[1 ""running""]",0.383833
"SELECT ""ID"", ""ENGINE"", ""NAME"", ""DBMS_VERSION"", ""SETTINGS"", ""IS_AUDIT"", ""DETAILS"", ""TIMEZONE"" FROM ""METABASE_DATABASE"" WHERE ""ID"" = ?",[1],2.763125
"SELECT ""T"".""ID"" AS ""TABLE-ID"", ""T"".""NAME"" AS ""TABLE"", ""T"".""SCHEMA"" AS ""SCHEMA"" FROM ""METABASE_TABLE"" AS ""T"" WHERE (""T"".""DB_ID"" = ?) AND ((LOWER(""T"".""NAME"") = ?) OR (LOWER(""T"".""NAME"") = ?))","[1 ""18be3cc2_84cf_44e6_87a7_306cba70a89812955651_e2c4_48ed_afcd_53cda43b116e598ea6f8_f158_49e1_95f0_4b6d06145dde94a9f996_7390_4813_b4a3_855aacd91c28373021c6_2334_48fd_b456_6ef3fe392daad5922ead_f76a_4f1d_94f3_05d1202dfca14c3ef6cf_8981_4647_a3c5_a86c5052712eb17831cf_5968_45bc_a5fd_f005c3cc4d2b6d1afa0c_7f86_415e_b691_d635809293e5a67a5d46_bae3_41f4_9074_43cc5e2cc5f6"" ""t""]",0.54225
"SELECT ""F"".""ID"" AS ""FIELD-ID"", ""F"".""NAME"" AS ""COLUMN"", ""T"".""ID"" AS ""TABLE-ID"", ""T"".""NAME"" AS ""TABLE"", ""T"".""SCHEMA"" AS ""SCHEMA"" FROM ""METABASE_TABLE"" AS ""T"" LEFT JOIN ""METABASE_FIELD"" AS ""F"" ON ""F"".""TABLE_ID"" = ""T"".""ID"" WHERE (""T"".""DB_ID"" = ?) AND ((((""F"".""ID"" IS NULL) OR (LOWER(""F"".""NAME"") = ?)) AND ((LOWER(""T"".""NAME"") = ?) OR (LOWER(""T"".""NAME"") = ?))) OR (((""F"".""ID"" IS NULL) OR (LOWER(""F"".""NAME"") = ?)) AND ((LOWER(""T"".""NAME"") = ?) OR (LOWER(""T"".""NAME"") = ?))))","[1 ""d40496bd_8a48_4973_b8c9_ac721c83d725eb9694c9_26ff_4764_8224_80856706cd850eebb22a_8796_4b32_b9d3_877616fc824d456b750b_4f29_48d6_a517_81644d01e719e1be74de_4f91_45d4_ba8b_46d108cd92c7c076178b_1a55_4bc3_89c0_accceb4df3ac8339d9f1_8916_4682_b4ec_a7a6ab2710b86e2c28e7_ba2b_4abc_85fd_cf6953059cfc51af7971_e971_40f8_b0c1_6e731be05f19526f7f1d_790b_4742_818c_b54766015c03"" ""18be3cc2_84cf_44e6_87a7_306cba70a89812955651_e2c4_48ed_afcd_53cda43b116e598ea6f8_f158_49e1_95f0_4b6d06145dde94a9f996_7390_4813_b4a3_855aacd91c28373021c6_2334_48fd_b456_6ef3fe392daad5922ead_f76a_4f1d_94f3_05d1202dfca14c3ef6cf_8981_4647_a3c5_a86c5052712eb17831cf_5968_45bc_a5fd_f005c3cc4d2b6d1afa0c_7f86_415e_b691_d635809293e5a67a5d46_bae3_41f4_9074_43cc5e2cc5f6"" ""t"" ""c"" ""18be3cc2_84cf_44e6_87a7_306cba70a89812955651_e2c4_48ed_afcd_53cda43b116e598ea6f8_f158_49e1_95f0_4b6d06145dde94a9f996_7390_4813_b4a3_855aacd91c28373021c6_2334_48fd_b456_6ef3fe392daad5922ead_f76a_4f1d_94f3_05d1202dfca14c3ef6cf_8981_4647_a3c5_a86c5052712eb17831cf_5968_45bc_a5fd_f005c3cc4d2b6d1afa0c_7f86_415e_b691_d635809293e5a67a5d46_bae3_41f4_9074_43cc5e2cc5f6"" ""t""]",0.58575
"INSERT INTO ""QUERY_FIELD"" (""CARD_ID"", ""ANALYSIS_ID"", ""SCHEMA"", ""TABLE"", ""COLUMN"", ""TABLE_ID"", ""FIELD_ID"", ""EXPLICIT_REFERENCE"") VALUES (?, ?, NULL, NULL, ?, NULL, NULL, TRUE), (?, ?, NULL, NULL, ?, NULL, NULL, TRUE)","[1 1 ""d40496bd_8a48_4973_b8c9_ac721c83d725eb9694c9_26ff_4764_8224_80856706cd850eebb22a_8796_4b32_b9d3_877616fc824d456b750b_4f29_48d6_a517_81644d01e719e1be74de_4f91_45d4_ba8b_46d108cd92c7c076178b_1a55_4bc3_89c0_accceb4df3ac8339d9f1_8916_4682_b4ec_a7a6ab2710b86e"" 1 1 ""c""]",0.227792
"INSERT INTO ""QUERY_TABLE"" (""CARD_ID"", ""ANALYSIS_ID"", ""SCHEMA"", ""TABLE"", ""TABLE_ID"") VALUES (?, ?, NULL, ?, NULL), (?, ?, NULL, ?, NULL)","[1 1 ""t"" 1 1 ""18be3cc2_84cf_44e6_87a7_306cba70a89812955651_e2c4_48ed_afcd_53cda43b116e598ea6f8_f158_49e1_95f0_4b6d06145dde94a9f996_7390_4813_b4a3_855aacd91c28373021c6_2334_48fd_b456_6ef3fe392daad5922ead_f76a_4f1d_94f3_05d1202dfca14c3ef6cf_8981_4647_a3c5_a86c5052712eb1""]",0.130791
"UPDATE ""QUERY_ANALYSIS"" SET ""STATUS"" = ? WHERE ""ID"" = ?","[""complete"" 1]",0.175375
"DELETE FROM ""QUERY_ANALYSIS"" WHERE (""CARD_ID"" = ?) AND (""ID"" <> ?)",[1 1],0.0485
```

**Comment by crisptrutski** [comment]
The deepest toucan logs (toucan2.jdbc.query:40) show that we're about to execute the INSERT query, but for some reason when we execute the statement it refers to this locking SELECT. I can't find any code in metabase or toucan2 that would generate this query either.

I enabled the logging for all Postgres queries locally, but do not see the SELECT 1 statement being run on my side.

**Comment by crisptrutski** [comment]
Ah, what I missed is that the exists query is on `metabase_field` *not* `query_field` (which we're inserting into). This must correspond to the implicit foreign key check on the `field_id` column. There is one other query to `metabase_field` in the transaction, which is earlier when we find the relevant entities to join to.

I don't understand how this creates a deadlock, especially not a non-deterministic one as we always do the same two queries. On the other hand, we don't actually need a transaction now that we use a `query_analysis` parent record to do a two phase commit.

Removing the transaction should resolve the issue, but its hard to be sure if we aren't able to reproduce.

**Comment by crisptrutski** [comment]
Lowering from P1 to P2 as this deadlock occurred on the async worker for populating query analysis, and would not cause direct impact.
