### ISSUE TITLE
`Cannot read properties of undefined (reading 'ReactCurrentDispatcher')` error in React SDK with React 19

### ISSUE THREAD

**Issue by umar-ahmed** [metabase/metabase#51435]
### Describe the bug

When using the latest React SDK in an app with `next@15.0.4` and `react@19.0.0` and `react-dom@19.0.0`, the following error is rendered in the DOM by the `<MetabaseProvider />` component:

```
Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher') 
  at 20244 (http://localhost:3000/_next/static/chunks/08b5e_%40metabase_embedding-sdk-react_dist_main_bundle_da8477.js:180879:85) 
  at __webpack_require__ (http://localhost:3000/_next/static/chunks/08b5e_%40metabase_embedding-sdk-react_dist_main_bundle_da8477.js:293027:39) 
  at 75897 (http://localhost:3000/_next/static/chunks/08b5e_%40metabase_embedding-sdk-react_dist_main_bundle_da8477.js:182770:17) 
  at __webpack_require__ (http://localhost:3000/_next/static/chunks/08b5e_%40metabase_embedding-sdk-react_dist_main_bundle_da8477.js:293027:39) 
  at http://localhost:3000/_next/static/chunks/08b5e_%40metabase_embedding-sdk-react_dist_main_bundle_da8477.js:401079:19 
  at http://localhost:3000/_next/static/chunks/08b5e_%40metabase_embedding-sdk-react_dist_main_bundle_da8477.js:433378:6 
  at [project]/node_modules/@metabase/embedding-sdk-react/dist/main.bundle.js [client] (ecmascript) (http://localhost:3000/_next/static/chunks/08b5e_%40metabase_embedding-sdk-react_dist_main_bundle_da8477.js:433379:2) 
  at http://localhost:3000/_next/static/chunks/pages__app_77de1d._.js:693:27 
  at runModuleExecutionHooks (http://localhost:3000/_next/static/chunks/pages__app_77de1d._.js:738:9) 
  at instantiateModule (http://localhost:3000/_next/static/chunks/pages__app_77de1d._.js:691:9) 
  at getOrInstantiateModuleFromParent (http://localhost:3000/_next/static/chunks/pages__app_77de1d._.js:624:12) 
  at esmImport (http://localhost:3000/_next/static/chunks/pages__app_77de1d._.js:142:20) 
  at [project]/apps/web/components/metabase/admin-metrics.tsx [client] (ecmascript) (http://localhost:3000/_next/static/chunks/components_metabase_admin-metrics_tsx_2cfdc7._.js:12:181) 
  at http://localhost:3000/_next/static/chunks/pages__app_77de1d._.js:693:27 
  at runModuleExecutionHooks (http://localhost:3000/_next/static/chunks/pages__app_77de1d._.js:738:9) at instantiateModule (http://localhost:3000/_next/static/chunks/pages__app_77de1d._.js:691:9) 
  at getOrInstantiateModuleFromParent (http://localhost:3000/_next/static/chunks/pages__app_77de1d._.js:624:12) 
  at esmImport (http://localhost:3000/_next/static/chunks/pages__app_77de1d._.js:142:20) 
  at http://localhost:3000/_next/static/chunks/%5Bproject%5D__4ef268._.js:16:16
```

### To Reproduce

1. Clone https://github.com/metabase/metabase-nextjs-sdk-embedding-sample/tree/main
2. Run `cd next-sample-pages-router`
3. Run `npm install`
4. Run `npm upgrade react@^19.0.0 react-dom@^19.0.0 @types/react@^19.0.0 @types/react-dom@^19.0.0 next@^15.0.0`
5. Follow the remaining steps in the readme to set up the connection to locally running Metabase instance with JWT SSO (as per the docs)

### Expected behavior

It should render the pages with embedded dashboards correctly

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "duckdb",
      "postgres",
      "mysql"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted",
    "version": {
      "date": "2024-12-09",
      "tag": "v1.52.2",
      "hash": "32effb1"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "heroku",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.5 (Ubuntu 15.5-1.pgdg22.04+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "19+36-2238",
    "java.vendor": "Oracle Corporation",
    "java.vendor.url": "https://java.oracle.com/",
    "java.version": "19",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "19+36-2238",
    "os.name": "Linux",
    "os.version": "6.1.0-25-cloud-amd64",
    "user.language": "en",
    "user.timezone": "Etc/UTC"
  }
}
```

### Severity

High - blocking usage of SDK

**Comment by albertoperdomo** [comment]
Hello @umar-ahmed ,

currently the SDK is only tested to work with Next.js 14 and React 18. Supporting React 19 is something we are tracking but haven't prioritized yet.

Since this is a known issue bug in favor of a feature request you can upvote and keep track of: https://github.com/metabase/metabase/issues/51442

In the meantime, my recommendation would be to use Next.js 14 and React 18 if that works for you, as this is known to work and is actively being tested.
