### ISSUE TITLE
Support encrypted RSA private key on Snowflake connection

### ISSUE THREAD

**Issue by vicmayrink** [metabase/metabase#51604]
**Is your feature request related to a problem? Please describe.**
Snowflake recommends to use encrypted RSA private keys, which is not yet supported. [Reference](https://docs.snowflake.com/en/user-guide/key-pair-auth)

**Describe the solution you'd like**
When creating a new database connection to snowflake, if the user provides **both** the RSA key file and a password, then metabase could automatically infer that the password is the private key pass phrase (as a benchmark, this is exactly what [Airflow](https://www.astronomer.io/docs/learn/connections/snowflake/) does, when adding a conection to snowflake). Alternatively, we could use an field `Private key pass phrase`.

**Describe alternatives you've considered**
N/A

**How important is this feature to you?**
I would guess this is not an urgent matter. I'm currently using non encrypted RSA keys. But I think it should be fine to support encrypted RSA keys at some point, since metabase uses JDBC driver, which already support it.

**Additional context**
Error message when uploading an encrypted RSA key file:

![Image](https://github.com/user-attachments/assets/11d13717-bf33-4015-86ea-bb503cd017b4)

**Comment by paoliniluis** [comment]
Check https://github.com/metabase/metabase/issues/51057

**Comment by radhe-kishan** [comment]
@paoliniluis I did not understand why it has been closed, #51057 does not mention anything about encrypted key.
Is there any specific reason for marking it as Not Planned?

I am getting below error - 

```
2025-04-23 12:57:07 2025-04-23 07:27:07,575 ERROR core.SessionUtilKeyPair :: Could not extract private key using standard JDK. Try setting the JVM argument: -Dnet.snowflake.jdbc.enableBouncyCastle=TRUE
2025-04-23 12:57:07 2025-04-23 07:27:07,580 ERROR driver.util :: Failed to connect to Database
2025-04-23 12:57:07 net.snowflake.client.jdbc.SnowflakeSQLLoggedException: Private key provided is invalid or not supported: java.security.InvalidKeyException: Unable to decode key
2025-04-23 12:57:07     at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initialize(DefaultSFConnectionHandler.java:136)
2025-04-23 12:57:07     at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initializeConnection(DefaultSFConnectionHandler.java:104)
2025-04-23 12:57:07     at net.snowflake.client.jdbc.SnowflakeConnectionV1.initConnectionWithImpl(SnowflakeConnectionV1.java:151)
2025-04-23 12:57:07     at net.snowflake.client.jdbc.SnowflakeConnectionV1.<init>(SnowflakeConnectionV1.java:128)
2025-04-23 12:57:07     at net.snowflake.client.jdbc.SnowflakeDriver.connect(SnowflakeDriver.java:227)
```

**Comment by iveselin-glooko** [comment]
Having an encrypted private key in a flow where we have to upload it somewhere is a must from our security practices. I would urge a reconsideration of this feature request.

**Comment by dragonsahead** [comment]
@radhe-kishan @iveselin-glooko just went again through this and we closed it as it's a duplicate of https://github.com/metabase/metabase/issues/43576

**Comment by dragonsahead** [comment]
But also there's a lot of information why we can't support this here https://github.com/metabase/metabase/issues/58847
