### ISSUE TITLE
Embedded dashboard with locked filters doesn't fill dropdown options

### ISSUE THREAD

**Issue by IsThisOriginalEnough** [metabase/metabase#51622]
Hello, 

We are experiencing issues that the dropdown filter doesn't get populated with data. This only happens in the embedded dashboards, on metabase itself the dropdowns do get populated.

On metabase:
![Image](https://github.com/user-attachments/assets/e3b0eea6-fa64-4077-a473-cfb879d98005)

Embedded:
![Image](https://github.com/user-attachments/assets/5a2a2dd3-da14-4166-8b29-3b73af356774)

The ContainerID is a locked filter, so we don't see it on the embedded dashboards, but when I change that to  be editable, then suddenly the dropdowns do get populated when embedded. 
Embedded with editable filter:
![Image](https://github.com/user-attachments/assets/3ced8d40-fe55-45e6-a948-f343d5a83233)

So to me it seems like the issue comes from the locked filter, which then somehow can't be used as a linked filter?

**Severity**
Some filter options are complex for the user to type out, so these can't be used at all now. This stops some of our users from using the dashboards at all.

Some info,
We have had this issue when we were running on version 41.2, but have also updated a few weeks ago to version 52.2, and still running against that same issue.

The container ID is a linked filter for the StandardProduct dropdown
All filters are field filters, from connected fields.

Edit on 15-1-2025, Possibly related log line after trying to get a dashboard with the locked filters:

`[817f1fdd-a289-45f2-b95d-9594dc8082a7] 2025-01-15T14:55:18+01:00 ERROR metabase.query-processor.streaming Client closed connection prematurely,org.eclipse.jetty.io.EofException,	at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:116),	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422),	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:275),	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:254),	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:386),	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:849),	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:243),	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224),	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:600),	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:1051),	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:1123),	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:270),	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:623),	at java.base/java.util.zip.DeflaterOutputStream.close(Unknown Source),	at metabase.async.streaming_response$delay_output_stream$fn__53454.invoke(streaming_response.clj:130),	at metabase.async.streaming_response.proxy$java.io.OutputStream$ff19274a.close(Unknown Source),	at java.base/sun.nio.cs.StreamEncoder.implClose(Unknown Source),	at java.base/sun.nio.cs.StreamEncoder.lockedClose(Unknown Source),	at java.base/sun.nio.cs.StreamEncoder.close(Unknown Source),	at java.base/java.io.OutputStreamWriter.close(Unknown Source),	at java.base/java.io.BufferedWriter.implClose(Unknown Source),	at java.base/java.io.BufferedWriter.close(Unknown Source),	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.close(WriterBasedJsonGenerator.java:1033),	at metabase.query_processor.streaming.json$fn$reify__82188.finish_BANG_(json.clj:154),	at metabase.query_processor.streaming$streaming_result_fn83083__83084$result__83085$fn__83086.invoke(streaming.clj:153),	at metabase.query_processor.streaming$streaming_result_fn83083__83084$result__83085.invoke(streaming.clj:152),	at clojure.core$comp$fn__5895.invoke(core.clj:2586),	at metabase.query_processor.pipeline$_STAR_reduce_STAR_.invokeStatic(pipeline.clj:86),	at metabase.query_processor.pipeline$_STAR_reduce_STAR_.invoke(pipeline.clj:54),	at metabase.query_processor.pipeline$_STAR_run_STAR_$respond__62619.invoke(pipeline.clj:100),	at metabase.driver.sql_jdbc.execute$execute_reducible_query$fn__87558.invoke(execute.clj:725),	at metabase.driver.sql_jdbc.execute$fn__87362$fn__87363.invoke(execute.clj:398),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection87332__87333.invokeStatic(execute.clj:338),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection87332__87333.invoke(execute.clj:321),	at metabase.driver.sql_jdbc.execute$fn__87362.invokeStatic(execute.clj:392),	at metabase.driver.sql_jdbc.execute$fn__87362.invoke(execute.clj:390),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:708),	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694),	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invokeStatic(execute.clj:705),	at metabase.driver.sql_jdbc.execute$execute_reducible_query.invoke(execute.clj:694),	at metabase.driver.sql_jdbc$fn__115586.invokeStatic(sql_jdbc.clj:79),	at metabase.driver.sql_jdbc$fn__115586.invoke(sql_jdbc.clj:77),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.query_processor.pipeline$_STAR_execute_STAR_.invokeStatic(pipeline.clj:52),	at metabase.query_processor.pipeline$_STAR_execute_STAR_.invoke(pipeline.clj:39),	at metabase.query_processor.pipeline$_STAR_run_STAR_.invokeStatic(pipeline.clj:102),	at metabase.query_processor.pipeline$_STAR_run_STAR_.invoke(pipeline.clj:95),	at metabase.query_processor.execute$run.invokeStatic(execute.clj:62),	at metabase.query_processor.execute$run.invoke(execute.clj:56),	at metabase.query_processor.middleware.update_used_cards$update_used_cards_BANG_75913__75914$fn__75915.invoke(update_used_cards.clj:60),	at metabase.query_processor.execute$add_native_form_to_result_metadata$fn__75930.invoke(execute.clj:25),	at metabase.query_processor.execute$add_preprocessed_query_to_result_metadata_for_userland_query$fn__75936.invoke(execute.clj:36),	at metabase.query_processor.middleware.cache$maybe_return_cached_results$maybe_return_cached_results_STAR___75886.invoke(cache.clj:241),	at metabase.query_processor.middleware.permissions$check_query_permissions$fn__72591.invoke(permissions.clj:148),	at metabase.query_processor.middleware.enterprise$check_download_permissions_middleware$fn__73312.invoke(enterprise.clj:51),	at metabase.query_processor.middleware.enterprise$maybe_apply_column_level_perms_check_middleware$fn__73322.invoke(enterprise.clj:64),	at metabase.query_processor.execute$execute75963__75964$fn__75965.invoke(execute.clj:94),	at metabase.query_processor.setup$do_with_qp_setup73837__73838.invokeStatic(setup.clj:225),	at metabase.query_processor.setup$do_with_qp_setup73837__73838.invoke(setup.clj:216),	at metabase.query_processor.execute$execute75963__75964.invokeStatic(execute.clj:93),	at metabase.query_processor.execute$execute75963__75964.invoke(execute.clj:89),	at metabase.query_processor$process_query_STAR__STAR_.invokeStatic(query_processor.clj:49),	at metabase.query_processor$process_query_STAR__STAR_.invoke(query_processor.clj:44),	at metabase.query_processor.middleware.enterprise$fn__73339$handle_audit_app_internal_queries__73340$fn__73342.invoke(enterprise.clj:96),	at metabase.query_processor.middleware.enterprise$handle_audit_app_internal_queries_middleware$fn__73350.invoke(enterprise.clj:103),	at metabase.query_processor.middleware.process_userland_query$process_userland_query_middleware78395__78396$fn__78397.invoke(process_userland_query.clj:204),	at metabase.query_processor.middleware.catch_exceptions$catch_exceptions78460__78461$fn__78462.invoke(catch_exceptions.clj:132),	at metabase.query_processor$process_query78501__78502$fn__78503.invoke(query_processor.clj:80),	at metabase.query_processor.setup$do_with_canceled_chan73832__73833$fn__73834.invoke(setup.clj:187),	at metabase.query_processor.setup$do_with_database_local_settings73825__73826$fn__73827.invoke(setup.clj:181),	at metabase.query_processor.setup$do_with_driver73818__73819$fn__73820$fn__73821.invoke(setup.clj:166),	at metabase.driver$do_with_driver.invokeStatic(driver.clj:106),	at metabase.driver$do_with_driver.invoke(driver.clj:101),	at metabase.query_processor.setup$do_with_driver73818__73819$fn__73820.invoke(setup.clj:165),	at metabase.query_processor.setup$do_with_metadata_provider73809__73810$fn__73811$fn__73814.invoke(setup.clj:151),	at metabase.query_processor.store$do_with_metadata_provider59778__59779.invokeStatic(store.clj:170),	at metabase.query_processor.store$do_with_metadata_provider59778__59779.invoke(store.clj:150),	at metabase.query_processor.store$do_with_metadata_provider59778__59779.invokeStatic(store.clj:159),	at metabase.query_processor.store$do_with_metadata_provider59778__59779.invoke(store.clj:150),	at metabase.query_processor.setup$do_with_metadata_provider73809__73810$fn__73811.invoke(setup.clj:150),	at metabase.query_processor.setup$do_with_resolved_database73799__73800$fn__73801.invoke(setup.clj:128),	at metabase.query_processor.setup$do_with_qp_setup73837__73838.invokeStatic(setup.clj:232),	at metabase.query_processor.setup$do_with_qp_setup73837__73838.invoke(setup.clj:216),	at metabase.query_processor$process_query78501__78502.invokeStatic(query_processor.clj:78),	at metabase.query_processor$process_query78501__78502.invoke(query_processor.clj:71),	at metabase.query_processor.card$process_query_for_card_default_qp89390__89391.invokeStatic(card.clj:233),	at metabase.query_processor.card$process_query_for_card_default_qp89390__89391.invoke(card.clj:229),	at metabase.api.public$process_query_for_card_with_id_run_fn$run__103345$fn__103346$fn__103347.invoke(public.clj:140),	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:438),	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:421),	at metabase.api.public$process_query_for_card_with_id_run_fn$run__103345$fn__103346.invoke(public.clj:139),	at metabase.query_processor.streaming$_streaming_response$fn__83097$fn__83098$fn__83099.invoke(streaming.clj:185),	at metabase.query_processor.streaming$_streaming_response$fn__83097$fn__83098.invoke(streaming.clj:183),	at metabase.query_processor.streaming$do_with_streaming_rff.invokeStatic(streaming.clj:174),	at metabase.query_processor.streaming$do_with_streaming_rff.invoke(streaming.clj:161),	at metabase.query_processor.streaming$_streaming_response$fn__83097.invoke(streaming.clj:180),	at clojure.lang.AFn.applyToHelper(AFn.java:156),	at clojure.lang.AFn.applyTo(AFn.java:144),	at clojure.core$apply.invokeStatic(core.clj:667),	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990),	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990),	at clojure.lang.RestFn.applyTo(RestFn.java:145),	at clojure.core$apply.invokeStatic(core.clj:671),	at clojure.core$bound_fn_STAR_$fn__5837.doInvoke(core.clj:2020),	at clojure.lang.RestFn.invoke(RestFn.java:424),	at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78),	at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:76),	at metabase.async.streaming_response$do_f_async$task__53439.invoke(streaming_response.clj:97),	at clojure.lang.AFn.run(AFn.java:22),	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source),	at java.base/java.util.concurrent.FutureTask.run(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source),	at java.base/java.lang.Thread.run(Unknown Source),Caused by: java.io.IOException: Broken pipe,	at java.base/sun.nio.ch.SocketDispatcher.writev0(Native Method),	at java.base/sun.nio.ch.SocketDispatcher.writev(Unknown Source),	at java.base/sun.nio.ch.IOUtil.write(Unknown Source),	at java.base/sun.nio.ch.IOUtil.write(Unknown Source),	at java.base/sun.nio.ch.SocketChannelImpl.write(Unknown Source),	at java.base/java.nio.channels.SocketChannel.write(Unknown Source),	at org.eclipse.jetty.io.SocketChannelEndPoint.flush(SocketChannelEndPoint.java:110),	... 114 more
`

Diagnostic info:
`{
  "browser-info": {
    "language": "en-US",
    "platform": "Win32",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "sqlserver"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2024-12-09",
      "tag": "v0.52.2",
      "hash": "32effb1"
    },
    "settings": {
      "report-timezone": "Europe/Amsterdam"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "12.20"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.3"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.5+11-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.5+11-LTS",
    "os.name": "Linux",
    "os.version": "5.15.0-1073-azure",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}`

**Comment by fer-batista** [comment]
I use embedded dashboards with hidden fields and I faced this issue.
In my case, I solved it by setting the field to "a list of all values".

Go to Admin -> Table Metadata -> Database -> Schema -> Table -> Find your field and click on the gear icon -> Change the "Filtering on this field" to "a list of all values".

You need to do this for all tables that use this field in your dashboard.

**Comment by IsThisOriginalEnough** [comment]
Thanks for the reply, it was "Search box" before, changed it to "A list of all values", rescanned the field but no luck sadly.

**Comment by fer-batista** [comment]
Confirm if you also changed the field filter in the dashboard to "Dropdown"?

**Comment by IsThisOriginalEnough** [comment]
Hmm it was already a dropdown there. So I've checked it when both are dropdown, and when both are search box just in case, but no luck.
I wouldn't think the issue is in the filter options, as the other dropdowns do get populated when I test my embedded dashboard when I make my hidden filter editable.

**Comment by IsThisOriginalEnough** [comment]
I have also made a post on the forum: https://discourse.metabase.com/t/embedded-dashboard-with-locked-filters-doesnt-fill-dropdown-options/197598 

But it seems like the behaviour was changed in sending filter options through the JWT. Now these filter options are automatically used as a linked filter for the other filter options, even though in the dashboard we don't specify it that way. Not sure if that is intended behaviour or not, but for us this breaks some filter options which are not necessarily linked to filters sent through the JWT.

**Comment by zierler** [comment]
I have the same issue on v0.53.1. Thanks for analyzing it, I can reproduce everything you said.

**Comment by zierler** [comment]
@IsThisOriginalEnough I have actually found a workaround for the moment. When you are inside the dashboard, in the filter settings (StandardProduct in your example), beside "Dropdown List" click on Edit and select "From another model or question".

There you can add a list which is not influenced by the remaining filters. Since you cannot select a table here, you will have to create a new Question which just returns the names of all StandardProduct elements. When then selecting this new "helper" question and column inside "From another model or question", the behavior should be the same as before inside metabase, and when embedding it works as well (at least for me).

I hope this helps you, although a bugfix from metabase would still be nice.

**Comment by paoliniluis** [comment]
@IsThisOriginalEnough can you test in 54.6? also, the error seems to indicate that there's something cutting the connection. Is there anything that you might see that's cutting the connection? could be your browser (any plugin), an anti virus, a WAF, the load balancer, etc

**Comment by perivamsi** [comment]
Closing this because of inactivity. Feel free to open it if there is more info.
