### ISSUE TITLE
Upgrading to 0.24.1 can't connect to internal Mysql DB [SOLVED]

### ISSUE THREAD

**Issue by that0n3guy** [metabase/metabase#5228]
### system information
- Metabase version: going to 0.24.1 from 0.23.1
- Metabase hosting environment: docker
- Metabase internal database: MySQL

### issue
I just tried upgrading from 0.23.1 to 0.24.1 with docker.   Simple docker pull and run (though I'm using rancher).

I've changed nothing in my environment variables but I get this error: 
```
5/30/2017 4:11:37 PM05-30 16:11:37 INFO metabase.util :: Loading Metabase...
5/30/2017 4:11:43 PM05-30 16:11:43 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
5/30/2017 4:11:50 PM05-30 16:11:50 INFO metabase.core :: Starting Metabase in STANDALONE mode
5/30/2017 4:11:50 PM05-30 16:11:50 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
5/30/2017 4:11:50 PM {:port 3000, :host "0.0.0.0"}
5/30/2017 4:11:50 PM
5/30/2017 4:11:50 PM05-30 16:11:50 INFO metabase.core :: Starting Metabase version v0.24.1 (480e4aaf release-0.24.1) ...
5/30/2017 4:11:50 PM05-30 16:11:50 INFO metabase.core :: System timezone is 'US/Central' ...
5/30/2017 4:11:50 PM05-30 16:11:50 DEBUG metabase.driver :: Registered driver :bigquery 🚚
5/30/2017 4:11:50 PM05-30 16:11:50 DEBUG metabase.driver :: Registered driver :crate 🚚
5/30/2017 4:11:50 PM05-30 16:11:50 DEBUG metabase.driver :: Registered driver :druid 🚚
5/30/2017 4:11:50 PM05-30 16:11:50 DEBUG metabase.driver :: Registered driver :googleanalytics 🚚
5/30/2017 4:11:50 PM05-30 16:11:50 DEBUG metabase.driver :: Registered driver :h2 🚚
5/30/2017 4:11:51 PM05-30 16:11:51 DEBUG metabase.driver :: Registered driver :mongo 🚚
5/30/2017 4:11:51 PM05-30 16:11:51 DEBUG metabase.driver :: Registered driver :mysql 🚚
5/30/2017 4:11:51 PM05-30 16:11:51 DEBUG metabase.driver :: Registered driver :postgres 🚚
5/30/2017 4:11:51 PM05-30 16:11:51 DEBUG metabase.driver :: Registered driver :presto 🚚
5/30/2017 4:11:51 PM05-30 16:11:51 DEBUG metabase.driver :: Registered driver :redshift 🚚
5/30/2017 4:11:51 PM05-30 16:11:51 DEBUG metabase.driver :: Registered driver :sqlite 🚚
5/30/2017 4:11:51 PM05-30 16:11:51 DEBUG metabase.driver :: Registered driver :sqlserver 🚚
5/30/2017 4:11:51 PM05-30 16:11:51 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
5/30/2017 4:11:51 PM05-30 16:11:51 INFO metabase.db :: Verifying mysql Database Connection ...
5/30/2017 4:11:51 PM05-30 16:11:51 ERROR metabase.driver :: Failed to connect to database: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
5/30/2017 4:11:51 PM
5/30/2017 4:11:51 PMThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
5/30/2017 4:11:51 PMjava.lang.AssertionError: Assert failed: Unable to connect to Metabase mysql DB.
5/30/2017 4:11:51 PM(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
5/30/2017 4:11:51 PM	at metabase.db$verify_db_connection.invokeStatic(db.clj:334)
5/30/2017 4:11:51 PM	at metabase.db$verify_db_connection.invoke(db.clj:327)
5/30/2017 4:11:51 PM	at metabase.db$verify_db_connection.invokeStatic(db.clj:330)
5/30/2017 4:11:51 PM	at metabase.db$verify_db_connection.invoke(db.clj:327)
5/30/2017 4:11:51 PM	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:382)
5/30/2017 4:11:51 PM	at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
5/30/2017 4:11:51 PM	at clojure.lang.RestFn.invoke(RestFn.java:421)
5/30/2017 4:11:51 PM	at metabase.core$init_BANG_.invokeStatic(core.clj:103)
5/30/2017 4:11:51 PM	at metabase.core$init_BANG_.invoke(core.clj:82)
5/30/2017 4:11:51 PM	at metabase.core$start_normally.invokeStatic(core.clj:187)
5/30/2017 4:11:51 PM	at metabase.core$start_normally.invoke(core.clj:181)
5/30/2017 4:11:51 PM	at metabase.core$_main.invokeStatic(core.clj:279)
5/30/2017 4:11:51 PM	at metabase.core$_main.doInvoke(core.clj:274)
5/30/2017 4:11:51 PM	at clojure.lang.RestFn.invoke(RestFn.java:397)
5/30/2017 4:11:51 PM	at clojure.lang.AFn.applyToHelper(AFn.java:152)
5/30/2017 4:11:51 PM	at clojure.lang.RestFn.applyTo(RestFn.java:132)
5/30/2017 4:11:51 PM	at metabase.core.main(Unknown Source)
5/30/2017 4:11:51 PM05-30 16:11:51 ERROR metabase.core :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase mysql DB.
5/30/2017 4:11:51 PM(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
5/30/2017 4:11:51 PM05-30 16:11:51 INFO metabase.core :: Metabase Shutting Down ...
5/30/2017 4:11:51 PM05-30 16:11:51 INFO metabase.core :: Metabase Shutdown COMPLETE
Disconnected
```

Yes, I'm sure my db is up and running and the docker container can connect to it.

Here are my env vars: 
![image](https://cloud.githubusercontent.com/assets/113870/26605881/5fed4530-4555-11e7-9ec3-a3fcbffd2b15.png)

**Comment by that0n3guy** [comment]
Well... I got this figured out.   Had to directly connect to mysql instead of using a docker alias `mysql`.   I wonder if something changed in the newer docker versions.   

I'm not seeing this issue with my other images... only with metabase.  Have you tested `external_links` with your container on a newer version of docker?

**Comment by salsakran** [comment]
Thanks for the heads up!

**Comment by camsaul** [comment]
Closing as solved
