### ISSUE TITLE
Karma fails on macOS Sierra

### ISSUE THREAD

**Issue by Varunram** [metabase/metabase#5263]
Looks like the test are not isolated to the backend (#5249), Karma seems to be failing too on macOS Sierra. @mazameli @camsaul Any pointers as to what version of OSX is stable for developing? Thanks!

Stacktrace for future reference:
```
Chrome 58.0.3029 (Mac OS X 10.12.5) LineAreaBarRenderer should display numeric year in X-axis and tooltip correctly FAILED
	Expected [ '2014', '2015', '2016' ] to equal [ '2015', '2016', '2017' ].
	    at onHoverChange (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:147:22)
	    at test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:60810:14
	    at SVGCircleElement.<anonymous> (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:59648:18)
	    at SVGCircleElement.__onmousemove (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:35366:19)
Chrome 58.0.3029 (Mac OS X 10.12.5): Executed 228 of 314 (1 FAILED) (skipped 4) (0 secs / 0.965 seChrome 58.0.3029 (Mac OS X 10.12.5) LineAreaBarRenderer should display hourly data (in Z timezone) in X axis and tooltip consistently FAILED
	Expected [ '7 PM - October 3, 2016', '8 PM - October 3, 2016', '9 PM - October 3, 2016' ] to equal [ '8 PM - October 3, 2016', '9 PM - October 3, 2016' ].
	    at onHoverChange (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:168:26)
	    at test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:60810:14
	    at SVGCircleElement.<anonymous> (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:59648:18)
	    at SVGCircleElement.__onmousemove (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:35366:19)
Chrome 58.0.3029 (Mac OS X 10.12.5): Executed 229 of 314 (2 FAILED) (skipped 4) (0 secs / 0.995 seChrome 58.0.3029 (Mac OS X 10.12.5) LineAreaBarRenderer should display hourly data (in -01:00 timezone) in X axis and tooltip consistently FAILED
	Expected [ '7 PM - October 3, 2016', '8 PM - October 3, 2016', '9 PM - October 3, 2016' ] to equal [ '8 PM - October 3, 2016', '9 PM - October 3, 2016' ].
	    at onHoverChange (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:168:26)
	    at test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:60810:14
	    at SVGCircleElement.<anonymous> (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:59648:18)
	    at SVGCircleElement.__onmousemove (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:35366:19)
Chrome 58.0.3029 (Mac OS X 10.12.5): Executed 230 of 314 (3 FAILED) (skipped 4) (0 secs / 1.009 seChrome 58.0.3029 (Mac OS X 10.12.5) LineAreaBarRenderer should display hourly data (in +00:00 timezone) in X axis and tooltip consistently FAILED
	Expected [ '7 PM - October 3, 2016', '8 PM - October 3, 2016', '9 PM - October 3, 2016' ] to equal [ '8 PM - October 3, 2016', '9 PM - October 3, 2016' ].
	    at onHoverChange (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:168:26)
	    at test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:60810:14
	    at SVGCircleElement.<anonymous> (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:59648:18)
	    at SVGCircleElement.__onmousemove (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:35366:19)
Chrome 58.0.3029 (Mac OS X 10.12.5): Executed 231 of 314 (4 FAILED) (skipped 4) (0 secs / 1.024 seChrome 58.0.3029 (Mac OS X 10.12.5) LineAreaBarRenderer should display hourly data (in +01:00 timezone) in X axis and tooltip consistently FAILED
	Expected [ '7 PM - October 3, 2016', '8 PM - October 3, 2016', '9 PM - October 3, 2016' ] to equal [ '8 PM - October 3, 2016', '9 PM - October 3, 2016' ].
	    at onHoverChange (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:168:26)
	    at test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:60810:14
	    at SVGCircleElement.<anonymous> (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:59648:18)
	    at SVGCircleElement.__onmousemove (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:35366:19)
Chrome 58.0.3029 (Mac OS X 10.12.5): Executed 232 of 314 (5 FAILED) (skipped 4) (0 secs / 1.038 seChrome 58.0.3029 (Mac OS X 10.12.5) LineAreaBarRenderer should display hourly data (in the browser's timezone) in X axis and tooltip consistently and correctly FAILED
	Expected [ '12 AM - January 1, 2016', '1 AM - January 1, 2016', '2 AM - January 1, 2016', '3 AM - January 1, 2016', '4 AM - January 1, 2016' ] to equal [ '1 AM - January 1, 2016', '2 AM - January 1, 2016', '3 AM - January 1, 2016', '4 AM - January 1, 2016' ].
	    at onHoverChange (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:187:22)
	    at test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:60810:14
	    at SVGCircleElement.<anonymous> (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:59648:18)
	    at SVGCircleElement.__onmousemove (test/unit/visualizations/lib/LineAreaBarRenderer.spec.js:35366:19)
Chrome 58.0.3029 (Mac OS X 10.12.5): Executed 233 of 314 (6 FAILED) (skipped 4) (0 secs / 1.055 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 234 of 314 (6 FAILED) (skipped 4) (0 secs / 1.081 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 235 of 314 (6 FAILED) (skipped 4) (0 secs / 1.098 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 236 of 314 (6 FAILED) (skipped 4) (0 secs / 1.143 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 237 of 314 (6 FAILED) (skipped 4) (0 secs / 1.156 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 238 of 314 (6 FAILED) (skipped 4) (0 secs / 1.162 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 239 of 314 (6 FAILED) (skipped 4) (0 secs / 1.178 seWARN: 'Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (http://localhost:9876/base/test/unit/visualizations/lib/LineAreaBarRenderer.spec.js?b40b11576743b7a29c2441b2e21de73b3cdb4bb9:5072:106)
    at configFromString (http://localhost:9876/base/test/unit/visualizations/lib/LineAreaBarRenderer.spec.js?b40b11576743b7a29c2441b2e21de73b3cdb4bb9:6802:33)
    at configFromInput (http://localhost:9876/base/test/unit/visualizations/lib/LineAreaBarRenderer.spec.js?b40b11576743b7a29c2441b2e21de73b3cdb4bb9:7162:14)
    at prepareConfig (http://localhost:9876/base/test/unit/visualizations/lib/LineAreaBarRenderer.spec.js?b40b11576743b7a29c2441b2e21de73b3cdb4bb9:7145:14)
    at createFromConfig (http://localhost:9876/base/test/unit/visualizations/lib/LineAreaBarRenderer.spec.js?b40b11576743b7a29c2441b2e21de73b3cdb4bb9:7112:45)
    at createLocalOrUTC (http://localhost:9876/base/test/unit/visualizations/lib/LineAreaBarRenderer.spec.js?b40b11576743b7a29c2441b2e21de73b3cdb4bb9:7199:17)
    at Function.create_utc__createUTC [as utc] (http://localhost:9876/base/test/unit/visualizations/lib/LineAreaBarRenderer.spec.js?b40b11576743b7a29c2441b2e21de73b3cdb4bb9:4864:17)
    at parseTimestamp (http://localhost:9876/base/test/unit/visualizations/lib/LineAreaBarRenderer.spec.js?b40b11576743b7a29c2441b2e21de73b3cdb4bb9:44415:34)
    at HACK_parseTimestamp (http://localhost:9876/base/test/unit/visualizations/lib/LineAreaBarRenderer.spec.js?b40b11576743b7a29c2441b2e21de73b3cdb4bb9:60251:43)
    at http://localhost:9876/base/test/unit/visualizations/lib/LineAreaBarRenderer.spec.js?b40b11576743b7a29c2441b2e21de73b3cdb4bb9:60409:57'
Chrome 58.0.3029 (Mac OS X 10.12.5): Executed 239 of 314 (6 FAILED) (skipped 4) (0 secs / 1.178 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 240 of 314 (6 FAILED) (skipped 4) (0 secs / 1.193 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 241 of 314 (6 FAILED) (skipped 4) (0 secs / 1.205 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 242 of 314 (6 FAILED) (skipped 4) (0 secs / 1.205 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 243 of 314 (6 FAILED) (skipped 4) (0 secs / 1.205 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 244 of 314 (6 FAILED) (skipped 4) (0 secs / 1.21 secChrome 58.0.3029 (Mac OS X 10.12.5): Executed 245 of 314 (6 FAILED) (skipped 4) (0 secs / 1.21 secChrome 58.0.3029 (Mac OS X 10.12.5): Executed 246 of 314 (6 FAILED) (skipped 4) (0 secs / 1.21 secChrome 58.0.3029 (Mac OS X 10.12.5): Executed 247 of 314 (6 FAILED) (skipped 4) (0 secs / 1.21 secChrome 58.0.3029 (Mac OS X 10.12.5): Executed 248 of 314 (6 FAILED) (skipped 4) (0 secs / 1.21 secChrome 58.0.3029 (Mac OS X 10.12.5): Executed 249 of 314 (6 FAILED) (skipped 4) (0 secs / 1.211 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 250 of 314 (6 FAILED) (skipped 4) (0 secs / 1.211 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 251 of 314 (6 FAILED) (skipped 4) (0 secs / 1.211 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 252 of 314 (6 FAILED) (skipped 4) (0 secs / 1.211 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 253 of 314 (6 FAILED) (skipped 4) (0 secs / 1.211 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 254 of 314 (6 FAILED) (skipped 4) (0 secs / 1.211 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 255 of 314 (6 FAILED) (skipped 4) (0 secs / 1.211 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 256 of 314 (6 FAILED) (skipped 4) (0 secs / 1.211 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 257 of 314 (6 FAILED) (skipped 4) (0 secs / 1.211 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 258 of 314 (6 FAILED) (skipped 4) (0 secs / 1.211 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 259 of 314 (6 FAILED) (skipped 4) (0 secs / 1.212 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 260 of 314 (6 FAILED) (skipped 4) (0 secs / 1.212 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 261 of 314 (6 FAILED) (skipped 4) (0 secs / 1.212 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 262 of 314 (6 FAILED) (skipped 4) (0 secs / 1.212 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 263 of 314 (6 FAILED) (skipped 4) (0 secs / 1.217 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 264 of 314 (6 FAILED) (skipped 4) (0 secs / 1.218 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 265 of 314 (6 FAILED) (skipped 4) (0 secs / 1.218 seERROR: 'Error getting setting', 'graph.x_axis._is_numeric', TypeError{}
Chrome 58.0.3029 (Mac OS X 10.12.5): Executed 265 of 314 (6 FAILED) (skipped 4) (0 secs / 1.218 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 266 of 314 (6 FAILED) (skipped 4) (0 secs / 1.224 seERROR: 'Error getting setting', 'graph.x_axis._is_numeric', TypeError{}
Chrome 58.0.3029 (Mac OS X 10.12.5): Executed 266 of 314 (6 FAILED) (skipped 4) (0 secs / 1.224 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 267 of 314 (6 FAILED) (skipped 4) (0 secs / 1.225 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 268 of 314 (6 FAILED) (skipped 4) (0 secs / 1.226 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 269 of 314 (6 FAILED) (skipped 4) (0 secs / 1.226 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 270 of 314 (6 FAILED) (skipped 4) (0 secs / 1.226 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 271 of 314 (6 FAILED) (skipped 4) (0 secs / 1.23 secChrome 58.0.3029 (Mac OS X 10.12.5): Executed 272 of 314 (6 FAILED) (skipped 4) (0 secs / 1.23 secChrome 58.0.3029 (Mac OS X 10.12.5): Executed 273 of 314 (6 FAILED) (skipped 4) (0 secs / 1.23 secChrome 58.0.3029 (Mac OS X 10.12.5): Executed 274 of 314 (6 FAILED) (skipped 4) (0 secs / 1.23 secChrome 58.0.3029 (Mac OS X 10.12.5): Executed 275 of 314 (6 FAILED) (skipped 4) (0 secs / 1.231 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 276 of 314 (6 FAILED) (skipped 4) (0 secs / 1.232 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 277 of 314 (6 FAILED) (skipped 4) (0 secs / 1.232 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 278 of 314 (6 FAILED) (skipped 4) (0 secs / 1.232 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 279 of 314 (6 FAILED) (skipped 4) (0 secs / 1.237 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 280 of 314 (6 FAILED) (skipped 4) (0 secs / 1.237 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 281 of 314 (6 FAILED) (skipped 4) (0 secs / 1.239 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 282 of 314 (6 FAILED) (skipped 4) (0 secs / 1.24 secChrome 58.0.3029 (Mac OS X 10.12.5): Executed 283 of 314 (6 FAILED) (skipped 4) (0 secs / 1.241 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 284 of 314 (6 FAILED) (skipped 4) (0 secs / 1.241 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 285 of 314 (6 FAILED) (skipped 4) (0 secs / 1.245 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 286 of 314 (6 FAILED) (skipped 4) (0 secs / 1.246 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 287 of 314 (6 FAILED) (skipped 4) (0 secs / 1.248 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 288 of 314 (6 FAILED) (skipped 4) (0 secs / 1.248 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 289 of 314 (6 FAILED) (skipped 4) (0 secs / 1.248 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 290 of 314 (6 FAILED) (skipped 4) (0 secs / 1.249 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 291 of 314 (6 FAILED) (skipped 4) (0 secs / 1.249 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 292 of 314 (6 FAILED) (skipped 4) (0 secs / 1.249 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 293 of 314 (6 FAILED) (skipped 4) (0 secs / 1.249 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 294 of 314 (6 FAILED) (skipped 4) (0 secs / 1.251 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 295 of 314 (6 FAILED) (skipped 4) (0 secs / 1.251 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 296 of 314 (6 FAILED) (skipped 4) (0 secs / 1.251 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 297 of 314 (6 FAILED) (skipped 4) (0 secs / 1.252 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 298 of 314 (6 FAILED) (skipped 4) (0 secs / 1.256 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 299 of 314 (6 FAILED) (skipped 4) (0 secs / 1.257 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 300 of 314 (6 FAILED) (skipped 4) (0 secs / 1.257 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 301 of 314 (6 FAILED) (skipped 4) (0 secs / 1.262 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 302 of 314 (6 FAILED) (skipped 4) (0 secs / 1.262 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 303 of 314 (6 FAILED) (skipped 4) (0 secs / 1.263 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 304 of 314 (6 FAILED) (skipped 4) (0 secs / 1.263 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 305 of 314 (6 FAILED) (skipped 4) (0 secs / 1.263 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 306 of 314 (6 FAILED) (skipped 4) (0 secs / 1.263 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 307 of 314 (6 FAILED) (skipped 4) (0 secs / 1.263 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 308 of 314 (6 FAILED) (skipped 4) (0 secs / 1.263 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 309 of 314 (6 FAILED) (skipped 4) (0 secs / 1.266 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 310 of 314 (6 FAILED) (skipped 4) (0 secs / 1.266 seChrome 58.0.3029 (Mac OS X 10.12.5): Executed 310 of 314 (6 FAILED) (skipped 4) (1.304 secs / 1.266 secs)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by camsaul** [comment]
@Varunram @tlrobinson or @attekei might know more about this

**Comment by Varunram** [comment]
Thanks for the pointer!

**Comment by kdoh** [comment]
Hey @Varunram. I just tried this again on latest master and was able to get a clean test run. Mind giving this another try and letting me know if you still run into issues when you're able?

```sh
Chrome 58.0.3029 (Mac OS X 10.12.5): Executed 310 of 314 (skipped 4) SUCCESS (1.336 secs / 1.296 secs)
✨  Done in 29.26s.
```

**Comment by Varunram** [comment]
Well @kdoh you're right. Current master does build properly. Is this somehow related to our CI builds which keep failing and passing at random intervals?

**Comment by kdoh** [comment]
Closing this since Karma tests are working fine now.
