### ISSUE TITLE
Metabase fails to start after upgrade to 0.24.x

### ISSUE THREAD

**Issue by kristian-elder** [metabase/metabase#5420]
- Metabase version: (e.x. 0.19.3)
Running 0.23.1, attempting to upgrade to 0.24.0
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Official Docker image, running in Google gloud under Kubernetes
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
MySQL

- *Repeatable steps to reproduce the issue*

After upgrading an existing MetaBase instance, from 0.23.1 to 0.24.0 (or .2), it fails to start with the following log output:

```
07-04 08:38:59 INFO metabase.util :: Loading Metabase...
07-04 08:39:10 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
07-04 08:39:23 INFO metabase.core :: Starting Metabase in STANDALONE mode
07-04 08:39:23 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 80, :host "metabase-deployment-115206140-8p2sb"}

07-04 08:39:23 WARN component.AbstractLifeCycle :: FAILED ServerConnector@5392c0a7{HTTP/1.1}{metabase-deployment-115206140-8p2sb:80}: java.net.SocketException: Permission denied
java.net.SocketException: Permission denied
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at ring.adapter.jetty$run_jetty.invokeStatic(jetty.clj:137)
        at ring.adapter.jetty$run_jetty.invoke(jetty.clj:100)
        at metabase.core$start_jetty_BANG_.invokeStatic(core.clj:167)
        at metabase.core$start_jetty_BANG_.invoke(core.clj:146)
        at metabase.core$start_normally.invokeStatic(core.clj:185)
        at metabase.core$start_normally.invoke(core.clj:181)
        at metabase.core$_main.invokeStatic(core.clj:279)
        at metabase.core$_main.doInvoke(core.clj:274)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
07-04 08:39:23 WARN component.AbstractLifeCycle :: FAILED org.eclipse.jetty.server.Server@5a349644: java.net.SocketException: Permission denied
java.net.SocketException: Permission denied
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at ring.adapter.jetty$run_jetty.invokeStatic(jetty.clj:137)
        at ring.adapter.jetty$run_jetty.invoke(jetty.clj:100)
        at metabase.core$start_jetty_BANG_.invokeStatic(core.clj:167)
        at metabase.core$start_jetty_BANG_.invoke(core.clj:146)
        at metabase.core$start_normally.invokeStatic(core.clj:185)
        at metabase.core$start_normally.invoke(core.clj:181)
        at metabase.core$_main.invokeStatic(core.clj:279)
        at metabase.core$_main.doInvoke(core.clj:274)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
java.net.SocketException: Permission denied
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at ring.adapter.jetty$run_jetty.invokeStatic(jetty.clj:137)
        at ring.adapter.jetty$run_jetty.invoke(jetty.clj:100)
        at metabase.core$start_jetty_BANG_.invokeStatic(core.clj:167)
        at metabase.core$start_jetty_BANG_.invoke(core.clj:146)
        at metabase.core$start_normally.invokeStatic(core.clj:185)
        at metabase.core$start_normally.invoke(core.clj:181)
        at metabase.core$_main.invokeStatic(core.clj:279)
        at metabase.core$_main.doInvoke(core.clj:274)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
07-04 08:39:23 ERROR metabase.core :: Metabase Initialization FAILED:  Permission denied
```

**Comment by miry** [comment]
@kristian-elder can you share the kubernetes config

**Comment by kristian-elder** [comment]
Sure, this is our kubernetes deployment file (with credentials removed):

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metabase-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:v0.23.1
        imagePullPolicy: Always
        env:
        - name: "MB_JETTY_PORT"
          value: "80"
        - name: "MB_DB_TYPE"
          value: "mysql"
        - name: "MB_DB_DBNAME"
          value: "<retracted>"
        - name: "MB_DB_PORT"
          value: "3306"
        - name: "MB_DB_USER"
          value: "<retracted>"
        - name: "MB_DB_PASS"
          value: "<retracted>"
        - name: "MB_DB_HOST"
          value: "<retracted>"
        - name: JAVA_TOOL_OPTIONS
          value: '-Xmx2g -Xms2g -Xmx2g -Xss1m -XX:+CMSClassUnloadingEnabled -XX:MaxMetaspaceSize=196m -XX:+CrashOnOutOfMemoryError'
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 3Gi
            cpu: 500m
          limits:
            memory: 3Gi
            cpu: 2
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 240
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          timeoutSeconds: 1
```

**Comment by miry** [comment]
@kristian-elder use default port from the docker, if i remember 3000. Because 80 port could be used only for `root`. And i assume in the docker done right and used user permissions. 

Depends on how do you want to expose the port, I assume you want to access by host port. I suggest to check https://kubernetes.io/docs/concepts/services-networking/service/ 

If you still want to use host port as 80, than you need to specify the `hostNetwork: true` and add priviligade mode

**Comment by kdoh** [comment]
@kristian-elder Did @miry's suggestion end up working for you?

**Comment by kristian-elder** [comment]
Changing the port to a non-privileged one did indeed fix it, thank you! I'm still curious to understand what changed as we've been running Metabase on port 80 across multiple previous versions without problems.
