### ISSUE TITLE
Upper Limit for Caching

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#5650]
Currently metabase offers lower limit for caching, that any questions have running time exceeding this limit will be cached.
However, I found that my users have some extremely heavy questions that run once  a week/month, that don't need to cache (because this will quickly make Metabase out of memory and crashed, as I observed)
So I suggest there is a way in metabase (such as upper limit for caching) to exclude such questions out of caching.
Thanks

**Comment by salsakran** [comment]
We ignore any questions with results larger than this setting 

![screen shot 2017-08-01 at 2 00 24 pm](https://user-images.githubusercontent.com/107439/28846844-c8d23a86-76c1-11e7-9bc1-9bc0a472ed47.png)


It's quite possible that what's happening is that the result size is overloading server memory in general. Can you run those queries with caching turned off or do they fail under that situation as well?

**Comment by thucnc** [comment]
Yeah, I'm not aware of this setting, so let me try it then to see any improvement.
On the other hand, we suffered unresponsive metabase (with cache enabled) when there was some heavy query running, even I killed the query progress from that postgres database

**Comment by thucnc** [comment]
Hello @salsakran , we are still suffering of Metabase unresponding issue very frequently when I found that Metabase consumed too much memory (above 100% of 5GB RAM that I allocated for Metabase via env variable) without many concurrent users. 
The current version of our Metabase is v0.25.1, running on a 4Cores 8GB RAM DigitalOcean Droplet.
Is there any way that I can find the root cause or simply get more debug information providing you?

**Comment by thucnc** [comment]
I found the stderr logs as below:

> Exception in thread "Timer-1" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at sun.misc.IOUtils.readFully(IOUtils.java:60)
	at java.util.jar.JarFile.getBytes(JarFile.java:425)
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193)
	at java.util.jar.JarFile.getManifest(JarFile.java:180)
	at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:944)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector.run(ThreadPoolAsynchronousRunner.java:831)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Exception in thread "Timer-0" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at sun.misc.IOUtils.readFully(IOUtils.java:60)
	at java.util.jar.JarFile.getBytes(JarFile.java:425)
	at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193)
	at java.util.jar.JarFile.getManifest(JarFile.java:180)
	at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:944)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector.run(ThreadPoolAsynchronousRunner.java:831)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Picked up JAVA_TOOL_OPTIONS: -Xmx5012m

**Comment by salsakran** [comment]
What OS and how much memory is on the instance where you run Metabase on?
Did you set a JVM memory limit or are you using the default?
How many questions do you have on your system?
What are your cache settings?

**Comment by thucnc** [comment]
Hi @salsakran,
I run Metabase docker on Ubuntu 16.x, with 4Cores and 8GB RAM of Digital Ocean.
The JVM Memory limit was set to 5GB RAM (as Xmx5012m).
I have around 2500 questions so far.
The cache settings are: MINIMUM QUERY DURATION = 90, CACHE TTL MULTIPLIER = 30, MAX CACHE ENTRY SIZE = 1000.
The incidents can happen anytime during peak/low usage period.

**Comment by thucnc** [comment]
Hi @salsakran,
I found some my incidents similar to https://github.com/metabase/metabase/issues/5187 , hence I added my comment in that issue.

**Comment by flamber** [comment]
There has been a lot of changes, since this issue was opened.
Better memory handling and streaming results are some of the things available in latest release 0.35.4
Please comment with details if you're still experiencing this issue.
