### ISSUE TITLE
Migration from H2 to MySQL fails with "Unknown column 'ldap_auth' in 'field list'"

### ISSUE THREAD

**Issue by zaiddabaeen** [metabase/metabase#5707]
After exporting type=mysql, port, host, password, user, and running:
```java -jar metabase.jar load-from-h2```

I got:
```
08-08 08:47:46 INFO metabase.util :: Loading Metabase...
08-08 08:47:52 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
08-08 08:47:56 INFO metabase.db :: Verifying mysql Database Connection ...
08-08 08:47:57 DEBUG metabase.driver :: Registered driver :mysql 🚚
08-08 08:47:57 INFO metabase.db :: Verify Database Connection ...  ✅
08-08 08:47:57 INFO metabase.db :: Running Database Migrations...
08-08 08:47:57 INFO metabase.db :: Setting up Liquibase...
08-08 08:47:57 INFO metabase.db :: Liquibase is ready.
08-08 08:47:57 INFO metabase.db :: Checking if Database has unrun migrations...
08-08 08:48:01 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
08-08 08:48:01 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
08-08 08:48:01 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
08-08 08:48:01 INFO metabase.db :: Migration lock is cleared. Running migrations...
08-08 08:48:01 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
08-08 08:48:01 WARN liquibase :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
08-08 08:48:36 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
Temporarily disabling DB constraints...
[OK]
Transfering 2 instances of Database....[OK]
Transfering 100 instances of RawTable....[OK]
Transfering 891 instances of RawColumn......[OK]
Transfering 9 instances of User....BatchUpdateException:
 Message: Unknown column 'ldap_auth' in 'field list'
 SQLState: 42S22
 Error Code: 1054
java.sql.BatchUpdateException: Unknown column 'ldap_auth' in 'field list'
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1166)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
	at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:426)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:419)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__10871.invoke(jdbc.clj:792)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:637)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:791)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:778)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:814)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:795)
	at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1069)
	at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1061)
	at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1110)
	at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1093)
	at metabase.cmd.load_from_h2$insert_entity_BANG_$fn__39408.invoke(load_from_h2.clj:131)
	at metabase.cmd.load_from_h2$insert_entity_BANG_.invokeStatic(load_from_h2.clj:130)
	at metabase.cmd.load_from_h2$insert_entity_BANG_.invoke(load_from_h2.clj:112)
	at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:146)
	at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:140)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__39488.invoke(load_from_h2.clj:215)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:613)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:629)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:212)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:205)
	at clojure.lang.Var.invoke(Var.java:379)
	at metabase.core$load_from_h2.invokeStatic(core.clj:210)
	at metabase.core$load_from_h2.invoke(core.clj:203)
	at metabase.core$load_from_h2.invokeStatic(core.clj:206)
	at metabase.core$load_from_h2.invoke(core.clj:203)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$run_cmd$fn__40258.invoke(core.clj:264)
	at metabase.core$run_cmd.invokeStatic(core.clj:264)
	at metabase.core$run_cmd.doInvoke(core.clj:263)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$_main.invokeStatic(core.clj:278)
	at metabase.core$_main.doInvoke(core.clj:274)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'ldap_auth' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751)
	... 52 more
Command failed with exception: Unknown column 'ldap_auth' in 'field list'
```
 
I do not use LDAP for authentication, only Google Sign-On.

- Your operating system: OSx Sierra
- Your databases: MySQL
- Metabase version: 0.25.0
- Metabase hosting environment: Jar on EC2
- Metabase internal database: H2, moving to MySQL

I will try now with 0.25.1,

**Comment by zaiddabaeen** [comment]
Might have been using wrong Metabase version after multiple updates and fixes to DB.
