### ISSUE TITLE
Exceptions mishandled for SQL backends

### ISSUE THREAD

**Issue by senior** [metabase/metabase#5761]
We have logic [here](https://github.com/metabase/metabase/blob/master/src/metabase/driver/generic_sql/query_processor.clj#L368) that mishandles the exception, hiding the original exception and throwing a separate/different exception that hides the original issue making it difficult to determine the real cause.

As an example, I was receiving an error from the SQLite JDBC driver that it was unable to parse  a timestamp. How this manifests in the application currently is the original exception is passed to [this function](https://github.com/clojure/java.jdbc/blob/master/src/main/clojure/clojure/java/jdbc.clj#L596) which writes to standard out (i.e. println) a summary without the stacktrace of the error:
```
SQLException:
 Message: Error parsing time stamp
 SQLState: null
 Error Code: 0
```
The result of that (nil) is what's [logged](https://github.com/metabase/metabase/blob/master/src/metabase/driver/generic_sql/query_processor.clj#L368) resulting in a log entry like:
```
ERROR generic-sql.query-processor :: nil
```
After that's been logged [this line](https://github.com/metabase/metabase/blob/master/src/metabase/driver/generic_sql/query_processor.clj#L369) creates a new exception and throws it, resulting in an entirely different stacktrace:
```
{:status :failed,
 :class java.lang.Exception,
 :error "Error parsing time stamp",
 :stacktrace
 ["driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:408)"
  "driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:403)"
  "driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:432)"
  "driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:428)"
  "driver$eval28056$fn__28057$G__28045__28064.invoke(driver.clj:47)"
  "query_processor$execute_query.invokeStatic(query_processor.clj:50)"
  "query_processor$execute_query.invoke(query_processor.clj:44)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__39141.invoke(mbql_to_native.clj:30)"
  "query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__37427.invoke(annotate_and_sort.clj:41)"
  "query_processor.middleware.limit$limit$fn__39080.invoke(limit.clj:14)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__38882.invoke(cumulative_aggregations.clj:46)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__38882.invoke(cumulative_aggregations.clj:46)"
  "query_processor.middleware.format_rows$format_rows$fn__39063.invoke(format_rows.clj:21)"
  "query_processor.middleware.binning$update_binning_strategy$fn__37512.invoke(binning.clj:164)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__40479.invoke(results_metadata.clj:88)"
  "query_processor.middleware.resolve$resolve_middleware$fn__37000.invoke(resolve.clj:349)"
  "query_processor.middleware.expand$expand_middleware$fn__38756.invoke(expand.clj:543)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__37094.invoke(add_row_count_and_status.clj:14)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__38918.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__40497.invoke(resolve_driver.clj:14)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__37619.invoke(cache.clj:146)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__38816.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:126)"
  "query_processor$process_query.invoke(query_processor.clj:122)"
  "test.data$eval59232$run_query_STAR___59237$fn__59238.invoke(data.clj:116)"
  "test.data$eval59232$run_query_STAR___59237.invoke(data.clj:110)"
  "query_processor_test.field_visibility_test$eval60629$actual__1810449112__60632.invoke(field_visibility_test.clj:63)"
  "test.data.datasets$do_with_engine.invokeStatic(datasets.clj:91)"
  "test.data.datasets$do_with_engine.invoke(datasets.clj:85)"
  "query_processor_test.field_visibility_test$eval60629$fn__60734$expect1537118210__60735$fn__60738.invoke(field_visibility_test.clj:41)"
  "query_processor_test.field_visibility_test$eval60629$fn__60734$expect1537118210__60735.invoke(field_visibility_test.clj:41)"],
 :query
 {:type :query,
  :query
  {:source-table 6,
   :order-by
   [{:direction :ascending,
     :field {:field-id 23, :fk-field-id nil, :datetime-unit :default, :remapped-from nil, :remapped-to nil, :field-display-name nil, :binnin$
-strategy nil, :binning-param nil}}]}},
 :expanded-query nil,
 :data {:native_form false, :cols (), :rows []}}
```
The original/real exception never appears in the log or standard out. I hacked in some code to print the real exception which is below:
```
java.sql.SQLException: Error parsing time stamp
        at org.sqlite.jdbc3.JDBC3ResultSet.getDate(JDBC3ResultSet.java:327)
        at com.mchange.v2.c3p0.impl.NewProxyResultSet.getDate(NewProxyResultSet.java:3264)
        at metabase.driver.generic_sql.query_processor$get_date$fn__53748.invoke(query_processor.clj:353)
        at metabase.driver.generic_sql.query_processor$read_columns_with_date_handling$fn__53759$fn__53762.invoke(query_processor.clj:385)
        at clojure.core$map$fn__4789.invoke(core.clj:2651)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:688)
        at clojure.core$next__4341.invokeStatic(core.clj:64)
        at clojure.core.protocols$fn__6755.invokeStatic(protocols.clj:168)
        at clojure.core.protocols$fn__6755.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6545)
        at clojure.core$into.invokeStatic(core.clj:6610)
        at clojure.core$mapv.invokeStatic(core.clj:6618)
        at clojure.core$mapv.invoke(core.clj:6618)
        at metabase.driver.generic_sql.query_processor$read_columns_with_date_handling$fn__53759.invoke(query_processor.clj:384)
        at clojure.java.jdbc$result_set_seq$row_values__2299.invoke(jdbc.clj:483)
        at clojure.java.jdbc$result_set_seq$thisfn__2305.invoke(jdbc.clj:496)
        at clojure.java.jdbc$result_set_seq.invokeStatic(jdbc.clj:498)
        at clojure.java.jdbc$result_set_seq.invoke(jdbc.clj:459)
        at clojure.java.jdbc$query$fn__2422.invoke(jdbc.clj:1011)
        at clojure.java.jdbc$db_query_with_resultset$run_query_with_params__2417.invoke(jdbc.clj:951)
        at clojure.java.jdbc$db_query_with_resultset.invokeStatic(jdbc.clj:966)
        at clojure.java.jdbc$db_query_with_resultset.invoke(jdbc.clj:936)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1004)
        at clojure.java.jdbc$query.invoke(jdbc.clj:973)
        at metabase.driver.generic_sql.query_processor$run_query.invokeStatic(query_processor.clj:392)
        at metabase.driver.generic_sql.query_processor$run_query.invoke(query_processor.clj:387)
        at clojure.core$partial$fn__4761.invoke(core.clj:2522)
        at clojure.core$partial$fn__4759.invoke(core.clj:2514)
        at metabase.driver.generic_sql.query_processor$do_with_auto_commit_disabled.invokeStatic(query_processor.clj:418)
        at metabase.driver.generic_sql.query_processor$do_with_auto_commit_disabled.invoke(query_processor.clj:410)
        at metabase.driver.generic_sql.query_processor$do_in_transaction$fn__53776.invoke(query_processor.clj:423)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:740)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
        at metabase.driver.generic_sql.query_processor$do_in_transaction.invokeStatic(query_processor.clj:422)
        at metabase.driver.generic_sql.query_processor$do_in_transaction.invoke(query_processor.clj:421)
        at metabase.driver.generic_sql.query_processor$run_query_without_timezone.invokeStatic(query_processor.clj:426)
        at metabase.driver.generic_sql.query_processor$run_query_without_timezone.invoke(query_processor.clj:425)
        at metabase.driver.generic_sql.query_processor$execute_query$fn__53782.invoke(query_processor.clj:435)
        at metabase.driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:404)
        at metabase.driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:403)
        at metabase.driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:432)
        at metabase.driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:428)
        at clojure.lang.Var.invoke(Var.java:383)
        at metabase.driver$eval28056$fn__28057$G__28045__28064.invoke(driver.clj:47)
        at metabase.query_processor$execute_query.invokeStatic(query_processor.clj:50)
        at metabase.query_processor$execute_query.invoke(query_processor.clj:44)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at metabase.query_processor.middleware.mbql_to_native$mbql__GT_native$fn__39141.invoke(mbql_to_native.clj:30)
        at metabase.query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__37427.invoke(annotate_and_sort.clj:41)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at metabase.query_processor.middleware.limit$limit$fn__39080.invoke(limit.clj:14)
        at metabase.query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__38882.invoke(cumulative_aggregations.clj:46
)
        at metabase.query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__38882.invoke(cumulative_aggregations.clj:46
)
at metabase.query_processor.middleware.format_rows$format_rows$fn__39063.invoke(format_rows.clj:21)
        at metabase.query_processor.middleware.binning$update_binning_strategy$fn__37512.invoke(binning.clj:164)
        at metabase.query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__40479.invoke(results_metadata.clj:88)
        at metabase.query_processor.middleware.resolve$resolve_middleware$fn__37000.invoke(resolve.clj:349)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at metabase.query_processor.middleware.expand$expand_middleware$fn__38756.invoke(expand.clj:543)
        at metabase.query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__37094.invoke(add_row_count_and_status.cl
j:14)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at metabase.query_processor.middleware.driver_specific$process_query_in_context$fn__38918.invoke(driver_specific.clj:12)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at metabase.query_processor.middleware.resolve_driver$resolve_driver$fn__40497.invoke(resolve_driver.clj:14)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at metabase.query_processor.middleware.cache$maybe_return_cached_results$fn__37619.invoke(cache.clj:146)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at metabase.query_processor.middleware.catch_exceptions$catch_exceptions$fn__38816.invoke(catch_exceptions.clj:58)
        at metabase.query_processor$process_query.invokeStatic(query_processor.clj:126)
        at metabase.query_processor$process_query.invoke(query_processor.clj:122)
        at metabase.test.data$eval59232$run_query_STAR___59237$fn__59238.invoke(data.clj:116)
        at metabase.test.data$eval59232$run_query_STAR___59237.invoke(data.clj:110)
        at metabase.query_processor_test.field_visibility_test$eval60629$actual__1810449112__60632.invoke(field_visibility_test.clj:63)
        at metabase.test.data.datasets$do_with_engine.invokeStatic(datasets.clj:91)
        at metabase.test.data.datasets$do_with_engine.invoke(datasets.clj:85)
        at metabase.query_processor_test.field_visibility_test$eval60629$fn__60734$expect1537118210__60735$fn__60738.invoke(field_visibility_
test.clj:41)
        at metabase.query_processor_test.field_visibility_test$eval60629$fn__60734$expect1537118210__60735.invoke(field_visibility_test.clj:4
1)
        at expectations$test_var$fn__164.invoke(expectations.cljc:229)
        at expectations$test_var.invokeStatic(expectations.cljc:225)
        at expectations$test_var.invoke(expectations.cljc:219)
        at expectations$test_vars$fn__199.invoke(expectations.cljc:264)
        at expectations$create_context.invokeStatic(expectations.cljc:244)
        at expectations$create_context.invoke(expectations.cljc:242)
        at expectations$test_vars.invokeStatic(expectations.cljc:264)
        at expectations$test_vars.invoke(expectations.cljc:250)
        at expectations$run_tests.invokeStatic(expectations.cljc:309)
        at expectations$run_tests.invoke(expectations.cljc:302)
        at expectations$run_all_tests.invokeStatic(expectations.cljc:315)
        at expectations$run_all_tests.invoke(expectations.cljc:314)
        at user$eval60783.invokeStatic(form-init3778586451690734743.clj:1)
        at user$eval60783.invoke(form-init3778586451690734743.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6916)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.text.ParseException: Unparseable date: "2014-04-01 08:30:00" does not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{
Nd}++)\Q:\E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q.\E(\p{Nd}++)
        at org.sqlite.date.FastDateParser.parse(FastDateParser.java:299)
        at org.sqlite.date.FastDateFormat.parse(FastDateFormat.java:490)
        at org.sqlite.jdbc3.JDBC3ResultSet.getDate(JDBC3ResultSet.java:324)
        ... 127 more
```
Which pretty clearly points the finger at the JDBC driver unfortunately hitting a [bug in the JDBC driver](https://github.com/xerial/sqlite-jdbc/issues/88).

There are a few issues that need to be fixed.
- We should only write to the log, not stdout
- We should log the original stacktrace with the error message
- The original exception should always be preserved (i.e. propagated or wrapped and rethrown)

A targeted fix in this area is ok as it's a pretty high traffic code path. Ultimately I think we'll want to have a top-level exception handler that "does the right thing" so we don't need to have this code sprinkled throughout the code.

**Comment by camsaul** [comment]
Are we using `jdbc/print-sql-exception-chain`? We could probably just wrap that in `with-out-str` so it gets passed to the logger as expected

**Comment by camsaul** [comment]
This was fixed a long time ago, going to go ahead and close this out
