### ISSUE TITLE
load-from-h2 fails

### ISSUE THREAD

**Issue by nkconnor** [metabase/metabase#5858]
- Metabase version: v0.25.2 (Latest)
- Metabase hosting environment: Ubuntu 16.04

I followed these instructions: http://www.metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres

It seems like the postgres driver never gets loaded?

```
java -jar metabase.jar load-from-h2 metabase.db.mv.db
08-31 10:35:38 INFO metabase.util :: Loading Metabase...
08-31 10:35:42 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
08-31 10:35:49 INFO metabase.db :: Verifying postgres Database Connection ...
08-31 10:35:49 ERROR metabase.driver :: Failed to connect to database: java.lang.IllegalArgumentException: No implementation of method: :can-connect? of protocol: #'metabase.driver/IDriver found for class: nil
java.lang.AssertionError: Assert failed: Unable to connect to Metabase postgres DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
	at metabase.db$verify_db_connection.invokeStatic(db.clj:334)
	at metabase.db$verify_db_connection.invoke(db.clj:327)
	at metabase.db$verify_db_connection.invokeStatic(db.clj:330)
	at metabase.db$verify_db_connection.invoke(db.clj:327)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:382)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:213)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:207)
	at clojure.lang.Var.invoke(Var.java:379)
	at metabase.core$load_from_h2.invokeStatic(core.clj:210)
	at metabase.core$load_from_h2.invoke(core.clj:203)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$run_cmd$fn__41408.invoke(core.clj:264)
	at metabase.core$run_cmd.invokeStatic(core.clj:264)
	at metabase.core$run_cmd.doInvoke(core.clj:263)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.core$_main.invokeStatic(core.clj:278)
	at metabase.core$_main.doInvoke(core.clj:274)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)
Command failed with exception: Assert failed: Unable to connect to Metabase postgres DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
```

**Comment by camsaul** [comment]
Sorry. Those instructions should be a little more clear. The path to the H2 DB shouldn't include the `.mv.db` part. It should look like `/path/to/metabase.db`. Actually I think you can leave that part out if you're just using the default filename (which it looks like you are)

**Comment by nkconnor** [comment]
`java -jar metabase.jar load-from-h2 /home/ubuntu/metabase.db` fails with the same error. Same with leaving the filename out

**Comment by camsaul** [comment]
Oh yeah. Looks like it can't find your postgres DB. 

```
 Unable to connect to Metabase postgres DB.
```

Postgres driver is loading just fine. Double-check your Postgres connection details

**Comment by nkconnor** [comment]
I must be overlooking some minor detail. I dbl checked the connection details several times and can connect via the psql shell 

```$ export PGPASSWORD=$MB_DB_PASS
$ psql -h $MB_DB_HOST -U $MB_DB_USER -d $MB_DB_DBNAME -p $MB_DB_PORT
psql (9.5.8, server 9.6.2)
WARNING: psql major version 9.5, server major version 9.6.
         Some psql features might not work.
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

metabase=> \q
```
```
$ java -jar metabase.jar load-from-h2
08-31 12:27:04 INFO metabase.util :: Loading Metabase...
08-31 12:27:09 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
08-31 12:27:16 INFO metabase.db :: Verifying postgres Database Connection ...
08-31 12:27:16 ERROR metabase.driver :: Failed to connect to database: java.lang.IllegalArgumentException:
```

**Comment by nkconnor** [comment]
also, if I just run the jar without `load-from-h2`, it seems to connect just fine to postgres

```
$ java -jar metabase.jar
08-31 12:39:01 INFO metabase.util :: Loading Metabase...
08-31 12:39:06 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
08-31 12:39:13 INFO metabase.core :: Starting Metabase in STANDALONE mode
08-31 12:39:13 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}
08-31 12:39:13 INFO metabase.core :: Starting Metabase version v0.25.0.RC2 (c8807ce release-0.25.0) ...
08-31 12:39:13 INFO metabase.core :: System timezone is 'America/Denver' ...
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :bigquery 🚚
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :crate 🚚
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :druid 🚚
08-31 12:39:13 WARN metabase.driver :: No -init-driver function found for 'metabase.driver.google'
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :googleanalytics 🚚
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :h2 🚚
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :mongo 🚚
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :mysql 🚚
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :postgres 🚚
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :presto 🚚
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :redshift 🚚
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :sqlite 🚚
08-31 12:39:13 DEBUG metabase.driver :: Registered driver :sqlserver 🚚
08-31 12:39:13 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
08-31 12:39:13 INFO metabase.db :: Verifying postgres Database Connection ...
08-31 12:39:14 INFO metabase.db :: Verify Database Connection ...  ✅
08-31 12:39:14 INFO metabase.db :: Running Database Migrations...
08-31 12:39:14 INFO metabase.db :: Setting up Liquibase...
08-31 12:39:14 INFO metabase.db :: Liquibase is ready.
08-31 12:39:14 INFO metabase.db :: Checking if Database has unrun migrations...
08-31 12:39:15 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
08-31 12:39:16 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
08-31 12:39:16 INFO db.migrations :: Finished running data migrations.
....
```

```
$ psql -h $MB_DB_HOST -U $MB_DB_USER -d $MB_DB_DBNAME
psql (9.5.8, server 9.6.2)
WARNING: psql major version 9.5, server major version 9.6.
         Some psql features might not work.
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

metabase=> \dt
                    List of relations
 Schema |             Name             | Type  |  Owner   
--------+------------------------------+-------+----------
 public | activity                     | table | nicholas
 public | card_label                   | table | nicholas
 public | collection                   | table | nicholas
 public | collection_revision          | table | nicholas
 public | core_session                 | table | nicholas
 public | core_user                    | table | nicholas
 public | dashboard_favorite           | table | nicholas
 public | dashboardcard_series         | table | nicholas
 public | data_migrations              | table | nicholas
 public | databasechangelog            | table | nicholas
 public | databasechangeloglock        | table | nicholas
 public | dependency                   | table | nicholas
 public | dimension                    | table | nicholas
```

**Comment by camsaul** [comment]
What version of Java are you using?

**Comment by nkconnor** [comment]
```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by camsaul** [comment]
ok. strange.

After looking at it a second time it seems like maybe the Postgres driver isn't loading after all. I'll try and reproduce this

**Comment by nkconnor** [comment]
ah, maybe the issue is on my end

You're on version v0.25.0.RC2
Built on 2017-07-20
Branch: release-0.25.0
Hash: c8807ce

downloading v0.25.2 now

**Comment by nkconnor** [comment]
It loads the driver correctly with v0.25.2, but..

I get a PK exception right away:

```
08-31 12:54:19 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
Temporarily disabling DB constraints...
[OK]
Transfering 3 instances of Database....BatchUpdateException:
 Message: Batch entry 0 INSERT INTO metabase_database ( "description", "name", "caveats", "is_full_sync", "updated_at", "details", "is_sample", "id", "engine", "created_at", "points_of_interest" ) VALUES ( NULL, 'Sample Dataset', NULL, '1', '2017-08-31 12:49:29.209000 -06:00:00', '{"db":"zip:/home/ubuntu/metabase.jar!/sample-dataset.db;USER=GUEST;PASSWORD=guest"}', '1', 1, 'h2', '2017-01-18 12:35:05.102000 -07:00:00', NULL ) was aborted.  Call getNextException to see the cause.
 SQLState: 23505
 Error Code: 0
PSQLException:
 Message: ERROR: duplicate key value violates unique constraint "pk_metabase_database"
  Detail: Key (id)=(1) already exists.
 SQLState: 23505
 Error Code: 0
```

I'll debug more and look for related issues

**Comment by camsaul** [comment]
yeah, that's because it started loading data when you started metabase without `load-from-h2`. `load-from-h2` needs an empty database. Drop your Metabase DB and re-create it and then try again

**Comment by nkconnor** [comment]
I ran

```
DROP DATABASE metabase;
CREATE DATABASE metabase;
```

**Comment by nkconnor** [comment]
ah, tricked myself somehow. not a postgres guy. after recreation the data is still there. must be some commit flag I'm not using

**Comment by nkconnor** [comment]
```
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
```
this did the trick. everything migrated now. sorry for the trouble!
