### ISSUE TITLE
Unable to sync tables in PostgreSQL that have a time field

### ISSUE THREAD

**Issue by senior** [metabase/metabase#5911]
The error is a bit hard to find due to #5761, but what shows in the log is:
```
09-06 15:50:54 ERROR generic-sql.query-processor :: Failed to set timezone:
 PSQLException:
 Message: ERROR: cannot cast type time without time zone to date
  Position: 213
 SQLState: 42846
 Error Code: 0
```
Digging a bit further, the real issue is related to incorrect casting of a time field in PostgreSQL:
```
org.postgresql.util.PSQLException: ERROR: cannot cast type time without time zone to date
  Position: 213
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
        at clojure.java.jdbc$db_query_with_resultset$run_query_with_params__5230.invoke(jdbc.clj:950)
        at clojure.java.jdbc$db_query_with_resultset.invokeStatic(jdbc.clj:966)
        at clojure.java.jdbc$db_query_with_resultset.invoke(jdbc.clj:936)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1004)
        at clojure.java.jdbc$query.invoke(jdbc.clj:973)
        at metabase.driver.generic_sql.query_processor$run_query.invokeStatic(query_processor.clj:429)
        at metabase.driver.generic_sql.query_processor$run_query.invoke(query_processor.clj:423)
        at metabase.driver.generic_sql.query_processor$run_query_with_timezone$fn__59677.invoke(query_processor.clj:479)
        at clojure.core$partial$fn__4759.invoke(core.clj:2514)
        at metabase.driver.generic_sql.query_processor$do_with_auto_commit_disabled.invokeStatic(query_processor.clj:455)
        at metabase.driver.generic_sql.query_processor$do_with_auto_commit_disabled.invoke(query_processor.clj:447)
        at metabase.driver.generic_sql.query_processor$do_in_transaction$fn__59669.invoke(query_processor.clj:460)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:740)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
        at metabase.driver.generic_sql.query_processor$do_in_transaction.invokeStatic(query_processor.clj:459)
        at metabase.driver.generic_sql.query_processor$do_in_transaction.invoke(query_processor.clj:458)
        at metabase.driver.generic_sql.query_processor$run_query_with_timezone.invokeStatic(query_processor.clj:477)
        at metabase.driver.generic_sql.query_processor$run_query_with_timezone.invoke(query_processor.clj:475)
        at metabase.driver.generic_sql.query_processor$execute_query$fn__59693.invoke(query_processor.clj:495)
        at metabase.driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:442)
        at metabase.driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:441)
        at metabase.driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:492)
        at metabase.driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:488)
        at clojure.lang.Var.invoke(Var.java:383)
        at metabase.driver$eval28312$fn__28313$G__28301__28320.invoke(driver.clj:34)
```
The SQL query used to cause that error is casting the time field as a date, i.e. 
```
SELECT ... CAST("public"."foo"."t" AS date) AS "t"...
```
This is somewhat related to #5563 as we're not distinguishing between date and time fields, but the difference here is this is taking place in the database and is preventing that query from running.

**Comment by camsaul** [comment]
Fixed by #5912
