### ISSUE TITLE
Bug on running compiled version -> java.lang.Exception: Unable to parse date string

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#6085]
Version v0.26.1.

Compiled from repo.

```bash
java.lang.Exception: Unable to parse date string '2017-10-02 17:25:02.315 BRT' for database engine 'h2'
	at metabase.driver$make_current_db_time_fn$fn__23257.invoke(driver.clj:305)
	at metabase.driver$fn__23137$G__22989__23144.invoke(driver.clj:34)
	at metabase.sync.sync_metadata.sync_timezone$fn__41317$sync_timezone_BANG___41322$fn__41323.invoke(sync_timezone.clj:20)
	at metabase.sync.sync_metadata.sync_timezone$fn__41317$sync_timezone_BANG___41322.invoke(sync_timezone.clj:13)
	at metabase.sync.sync_metadata$fn__41559$sync_db_metadata_BANG___41564$fn__41565$fn__41566.invoke(sync_metadata.clj:24)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:115)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:110)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:113)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:110)
	at clojure.core$partial$fn__4759.invoke(core.clj:2514)
	at metabase.driver$fn__23228.invokeStatic(driver.clj:209)
	at metabase.driver$fn__23228.invoke(driver.clj:209)
	at metabase.driver$fn__23202$G__22983__23211.invoke(driver.clj:34)
	at metabase.sync.util$sync_in_context$fn__38951.invoke(util.clj:106)
	at metabase.sync.util$with_db_logging_disabled$fn__38948.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_logging$fn__38943.invoke(util.clj:87)
	at metabase.sync.util$with_sync_events$fn__38940.invoke(util.clj:70)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__38931.invoke(util.clj:49)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:133)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:130)
	at metabase.sync.sync_metadata$fn__41559$sync_db_metadata_BANG___41564$fn__41565.invoke(sync_metadata.clj:23)
	at metabase.sync.sync_metadata$fn__41559$sync_db_metadata_BANG___41564.invoke(sync_metadata.clj:20)
	at metabase.sync$fn__41609$sync_database_BANG___41614$fn__41615$fn__41616.invoke(sync.clj:28)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:115)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:110)
	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:113)
	at metabase.sync.util$do_with_error_handling.invoke(util.clj:110)
	at clojure.core$partial$fn__4759.invoke(core.clj:2514)
	at metabase.driver$fn__23228.invokeStatic(driver.clj:209)
	at metabase.driver$fn__23228.invoke(driver.clj:209)
	at metabase.driver$fn__23202$G__22983__23211.invoke(driver.clj:34)
	at metabase.sync.util$sync_in_context$fn__38951.invoke(util.clj:106)
	at metabase.sync.util$with_db_logging_disabled$fn__38948.invoke(util.clj:98)
	at metabase.sync.util$with_start_and_finish_logging$fn__38943.invoke(util.clj:87)
	at metabase.sync.util$with_sync_events$fn__38940.invoke(util.clj:70)
	at metabase.sync.util$with_duplicate_ops_prevented$fn__38931.invoke(util.clj:49)
	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:133)
	at metabase.sync.util$do_sync_operation.invoke(util.clj:130)
	at metabase.sync$fn__41609$sync_database_BANG___41614$fn__41615.invoke(sync.clj:26)
	at metabase.sync$fn__41609$sync_database_BANG___41614.invoke(sync.clj:19)
	at metabase.sample_data$add_sample_dataset_BANG_.invokeStatic(sample_data.clj:30)
	at metabase.sample_data$add_sample_dataset_BANG_.invoke(sample_data.clj:24)
	at metabase.core$init_BANG_.invokeStatic(core.clj:129)
	at metabase.core$init_BANG_.invoke(core.clj:82)
	at metabase.core$start_normally.invokeStatic(core.clj:187)
	at metabase.core$start_normally.invoke(core.clj:181)
	at metabase.core$_main.invokeStatic(core.clj:285)
	at metabase.core$_main.doInvoke(core.clj:280)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Invalid format: "2017-10-02 17:25:02.315 BRT" is malformed at "BRT"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
	at clj_time.format$parse.invokeStatic(format.clj:160)
	at clj_time.format$parse.invoke(format.clj:156)
	at metabase.driver$make_current_db_time_fn$fn__23257.invoke(driver.clj:301)

```

**Comment by monitaure** [comment]
Got the same issue, it seems to be just a warning that will be fix in a future version, see https://github.com/metabase/metabase/issues/6080#issuecomment-333535615
