### ISSUE TITLE
Not able to start up docker container with metabase built from source code using the dockerfile found in root folder

### ISSUE THREAD

**Issue by BrijToSuccess** [metabase/metabase#6481]
Not able to start up docker container with metabase built from source code using the dockerfile found in root folder. Here are the logs.

11-27 23:38:32 INFO metabase.db :: Liquibase is ready.
11-27 23:38:32 INFO metabase.db :: Checking if Database has unrun migrations...
liquibase.exception.UnknownChangelogFormatException: Cannot find parser that supports liquibase.yaml
	at liquibase.parser.ChangeLogParserFactory.getParser(ChangeLogParserFactory.java:70)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:228)
	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1183)
	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1176)
	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1172)
	at metabase.db$has_unrun_migrations_QMARK_.invokeStatic(db.clj:135)
	at metabase.db$has_unrun_migrations_QMARK_.invoke(db.clj:129)
	at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:159)
	at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:151)
	at metabase.db$migrate_BANG_$fn__5690.invoke(db.clj:247)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:740)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
	at metabase.db$migrate_BANG_.invokeStatic(db.clj:235)
	at metabase.db$migrate_BANG_.invoke(db.clj:218)
	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:365)
	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:360)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:383)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:108)
	at metabase.core$init_BANG_.invoke(core.clj:87)
	at metabase.core$start_normally.invokeStatic(core.clj:194)
	at metabase.core$start_normally.invoke(core.clj:188)
	at metabase.core$_main.invokeStatic(core.clj:292)
	at metabase.core$_main.doInvoke(core.clj:287)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
11-27 23:38:32 ERROR metabase.core :: Metabase Initialization FAILED:  Cannot find parser that supports liquibase.yaml
11-27 23:38:32 INFO metabase.core :: Metabase Shutting Down ...
11-27 23:38:32 INFO metabase.core :: Metabase Shutdown COMPLETE

**Comment by BrijToSuccess** [comment]
Nevermind its working now
