### ISSUE TITLE
fk_report_card_ref_database_id CONSTRAINT when upgrading to 0.27.0

### ISSUE THREAD

**Issue by Poggen** [metabase/metabase#6489]
- Metabase version: 0.27.0
- Metabase hosting environment: 4.4.0-38-generic #57-Ubuntu
- Metabase internal database: MySQL

When upgrading to 0.27.0 we get the following crash:

```
11-28 20:01:36 INFO metabase.util :: Loading Metabase...
11-28 20:01:41 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance.
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
11-28 20:01:46 INFO metabase.core :: Starting Metabase in STANDALONE mode
11-28 20:01:46 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 80, :ssl? true, :ssl-port 443, :keystore "/root/ssl/crossroads.jks"}

11-28 20:01:46 INFO metabase.core :: Starting Metabase version v0.27.0 (00e2d3e release-0.27.0) ...
11-28 20:01:46 INFO metabase.core :: System timezone is 'Europe/Stockholm' ...
11-28 20:01:47 WARN metabase.driver :: No -init-driver function found for 'metabase.driver.google'
11-28 20:01:47 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
11-28 20:01:47 INFO metabase.db :: Verifying mysql Database Connection ...
11-28 20:01:47 INFO metabase.db :: Verify Database Connection ...
11-28 20:01:47 INFO metabase.db :: Running Database Migrations...
11-28 20:01:47 INFO metabase.db :: Setting up Liquibase...
11-28 20:01:47 INFO metabase.db :: Liquibase is ready.
11-28 20:01:47 INFO metabase.db :: Checking if Database has unrun migrations...
11-28 20:01:49 INFO metabase.db :: Database Migrations Current ...
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
11-28 20:01:49 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
11-28 20:01:49 INFO db.migrations :: Running data migration 'populate-card-database-id'...
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`metabase`.`report_card`, CONSTRAINT `fk_report_card_ref_database_id` FOREIGN KEY (`database_id`) REFERENCES `metabase_database` (`id`))
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__10886.invoke(jdbc.clj:901)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:900)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:894)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:932)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:912)
	at clojure.java.jdbc$execute_BANG_$execute_helper__10945.invoke(jdbc.clj:1161)
	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1165)
	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1145)
	at toucan.db$execute_BANG_.invokeStatic(db.clj:324)
	at toucan.db$execute_BANG_.doInvoke(db.clj:319)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$update_BANG_.invokeStatic(db.clj:378)
	at toucan.db$update_BANG_.invoke(db.clj:367)
	at toucan.db$update_where_BANG_.invokeStatic(db.clj:402)
	at toucan.db$update_where_BANG_.doInvoke(db.clj:392)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at metabase.db.migrations$populate_card_database_id.invokeStatic(migrations.clj:335)
	at metabase.db.migrations$populate_card_database_id.invoke(migrations.clj:332)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:49)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:40)
	at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:68)
	at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:62)
	at clojure.lang.Var.invoke(Var.java:375)
	at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:374)
	at metabase.db$run_data_migrations_BANG_.invoke(db.clj:369)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:385)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:108)
	at metabase.core$init_BANG_.invoke(core.clj:87)
	at metabase.core$start_normally.invokeStatic(core.clj:194)
	at metabase.core$start_normally.invoke(core.clj:188)
	at metabase.core$_main.invokeStatic(core.clj:292)
	at metabase.core$_main.doInvoke(core.clj:287)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
11-28 20:01:49 ERROR metabase.core :: Metabase Initialization FAILED:  Cannot add or update a child row: a foreign key constraint fails (`metabase`.`report_card`, CONSTRAINT `fk_report_card_ref_database_id` FOREIGN KEY (`database_id`) REFERENCES `metabase_database` (`id`))
11-28 20:01:49 INFO metabase.core :: Metabase Shutting Down ...
11-28 20:01:49 INFO metabase.core :: Metabase Shutdown COMPLETE
```

**Comment by camsaul** [comment]
@Poggen we've released a hotfix release, 0.27.1, which fixes this issue. You can download it here: https://www.metabase.com/start/

**Comment by robsonpeixoto** [comment]
The same problem here after upgrade from `metabase/metabase:v0.26.1` to `metabase/metabase:v0.27.1`
