### ISSUE TITLE
Mac - version 0.27.1.0 on MacOS High Sierra - 10.13.1  Crashing and not loading

### ISSUE THREAD

**Issue by fandomfilms** [metabase/metabase#6511]
I just updated and got this when I loaded the software.  

The Metabase server terminated unexpectedly.

Messages:
```
WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__21120@3b2a5402: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__21120@3b2a5402: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__21120@3b2a5402: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
java.lang.Exception: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.at metabase.db$wait_for_migration_lock_to_be_cleared$fn__21120.invoke(db.clj:148)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:713)
at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:717)
at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:717)
at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:717)
at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:717)at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:717)
at metabase.util$do_with_auto_retries.invoke(util.clj:705)
at metabase.db$wait_for_migration_lock_to_be_cleared.invokeStatic(db.clj:146)
at metabase.db$wait_for_migration_lock_to_be_cleared.invoke(db.clj:142)
at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:161)
at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:151)
at metabase.db$migrate_BANG_$fn__21163.invoke(db.clj:247)
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:740)
at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
at metabase.db$migrate_BANG_.invokeStatic(db.clj:235)
at metabase.db$migrate_BANG_.invoke(db.clj:218)
at 
```

**Comment by senior** [comment]
The error makes it look like you've already got a Metabase process running that is holding on to the H2 database lock. Can you check that? `jps` or `ps` works there. If you're sure there's not a process running  and you still get the same error, you can run the release locks command like the error describes to release it.

**Comment by camsaul** [comment]
@salsakran it doesn't sound like he's using the Mac App. Otherwise we probably wouldn't have this stacktrace here.

**Comment by mbvictoria** [comment]
Closing - old version, has been labeled need more info for over 2 years, not reported by other users.
