### ISSUE TITLE
App crashes on upgrade from 26 > 27.2

### ISSUE THREAD

**Issue by ericchernuka** [metabase/metabase#6513]
We were waiting on the lastest fix in 27.2 which just landed. Upon upgrading the app, it restarts but gets stuck on `Polishing tables...`.  Looking at the logs its throwing an exception parsing `liquibase.yaml`.

Restarting produces the following logs.

```
2017-11-30T17:44:00+00:00 app[heroku-postgres]: source=DATABASE sample#current_transaction=2212 sample#db_size=23157272bytes sample#tables=41 sample#active-connections=1 sample#waiting-connections=0 sample#index-cache-hit-rate=0.8147 sample#table-cache-hit-rate=0.88153 sample#load-avg-1m=0.025 sample#load-avg-5m=0.005 sample#load-avg-15m=0 sample#read-iops=0 sample#write-iops=0 sample#memory-total=4044964kB sample#memory-free=2743944kB sample#memory-cached=1136800kB sample#memory-postgres=13776kB
2017-11-30T17:44:15.849061+00:00 heroku[web.1]: State changed from crashed to starting
2017-11-30T17:44:23.091154+00:00 heroku[web.1]: Starting process with command `./bin/start`
2017-11-30T17:44:24.866249+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2017-11-30T17:44:24.915882+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -Dfile.encoding=UTF-8
2017-11-30T17:44:31.181759+00:00 app[web.1]: 11-30 17:44:31 INFO metabase.util :: Loading Metabase...
2017-11-30T17:44:41.926649+00:00 app[web.1]: 11-30 17:44:41 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
2017-11-30T17:44:41.926669+00:00 app[web.1]: See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
2017-11-30T17:44:51.525564+00:00 app[web.1]: 11-30 17:44:51 INFO metabase.core :: Starting Metabase in STANDALONE mode
2017-11-30T17:44:51.544496+00:00 app[web.1]: 11-30 17:44:51 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
2017-11-30T17:44:51.544498+00:00 app[web.1]:  {:port 14893}
2017-11-30T17:44:51.544499+00:00 app[web.1]:
2017-11-30T17:44:51.595698+00:00 app[web.1]: 11-30 17:44:51 INFO metabase.core :: Starting Metabase version v0.27.1 (055e448 release-0.27.0) ...
2017-11-30T17:44:51.596025+00:00 app[web.1]: 11-30 17:44:51 INFO metabase.core :: System timezone is 'Etc/UTC' ...
2017-11-30T17:44:51.742837+00:00 heroku[web.1]: State changed from starting to up
2017-11-30T17:44:54.475912+00:00 heroku[web.1]: Process running mem=553M(107.0%)
2017-11-30T17:44:54.476001+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-30T17:44:56.084314+00:00 app[web.1]: 11-30 17:44:56 WARN metabase.driver :: No -init-driver function found for 'metabase.driver.google'
2017-11-30T17:44:57.043382+00:00 app[web.1]: 11-30 17:44:57 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
2017-11-30T17:44:57.046740+00:00 app[web.1]: 11-30 17:44:57 INFO metabase.db :: Verifying postgres Database Connection ...
2017-11-30T17:44:57.224296+00:00 app[web.1]: 11-30 17:44:57 INFO metabase.db :: Verify Database Connection ...  ✅
2017-11-30T17:44:57.224620+00:00 app[web.1]: 11-30 17:44:57 INFO metabase.db :: Running Database Migrations...
2017-11-30T17:44:57.263081+00:00 app[web.1]: 11-30 17:44:57 INFO metabase.db :: Setting up Liquibase...
2017-11-30T17:44:57.366374+00:00 app[web.1]: 11-30 17:44:57 INFO metabase.db :: Liquibase is ready.
2017-11-30T17:44:57.366856+00:00 app[web.1]: 11-30 17:44:57 INFO metabase.db :: Checking if Database has unrun migrations...
2017-11-30T17:44:54+00:00 app[heroku-postgres]: source=DATABASE sample#current_transaction=2212 sample#db_size=23157272bytes sample#tables=41 sample#active-connections=1 sample#waiting-connections=0 sample#index-cache-hit-rate=0.8147 sample#table-cache-hit-rate=0.88153 sample#load-avg-1m=0.03 sample#load-avg-5m=0.01 sample#load-avg-15m=0 sample#read-iops=0 sample#write-iops=0 sample#memory-total=4044964kB sample#memory-free=2726884kB sample#memory-cached=1153188kB sample#memory-postgres=13776kB
2017-11-30T17:45:15.541765+00:00 heroku[web.1]: Process running mem=573M(111.7%)
2017-11-30T17:45:15.541900+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-30T17:45:16.046031+00:00 app[web.1]: liquibase.exception.ChangeLogParseException: Error parsing liquibase.yaml
2017-11-30T17:45:16.046285+00:00 app[web.1]: 	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:98)
2017-11-30T17:45:16.046338+00:00 app[web.1]: 	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:229)
2017-11-30T17:45:16.046386+00:00 app[web.1]: 	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1183)
2017-11-30T17:45:16.046442+00:00 app[web.1]: 	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1176)
2017-11-30T17:45:16.046519+00:00 app[web.1]: 	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1172)
2017-11-30T17:45:16.046552+00:00 app[web.1]: 	at metabase.db$has_unrun_migrations_QMARK_.invokeStatic(db.clj:135)
2017-11-30T17:45:16.046608+00:00 app[web.1]: 	at metabase.db$has_unrun_migrations_QMARK_.invoke(db.clj:129)
2017-11-30T17:45:16.046658+00:00 app[web.1]: 	at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:159)
2017-11-30T17:45:16.046706+00:00 app[web.1]: 	at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:151)
2017-11-30T17:45:16.046762+00:00 app[web.1]: 	at metabase.db$migrate_BANG_$fn__21163.invoke(db.clj:247)
2017-11-30T17:45:16.046843+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
2017-11-30T17:45:16.046879+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
2017-11-30T17:45:16.046956+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:740)
2017-11-30T17:45:16.047010+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
2017-11-30T17:45:16.047052+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
2017-11-30T17:45:16.047115+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
2017-11-30T17:45:16.047161+00:00 app[web.1]: 	at metabase.db$migrate_BANG_.invokeStatic(db.clj:235)
2017-11-30T17:45:16.047211+00:00 app[web.1]: 	at metabase.db$migrate_BANG_.invoke(db.clj:218)
2017-11-30T17:45:16.047265+00:00 app[web.1]: 	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:365)
2017-11-30T17:45:16.047317+00:00 app[web.1]: 	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:360)
2017-11-30T17:45:16.047370+00:00 app[web.1]: 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:383)
2017-11-30T17:45:16.047425+00:00 app[web.1]: 	at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
2017-11-30T17:45:16.047511+00:00 app[web.1]: 	at clojure.lang.RestFn.invoke(RestFn.java:421)
2017-11-30T17:45:16.047564+00:00 app[web.1]: 	at metabase.core$init_BANG_.invokeStatic(core.clj:108)
2017-11-30T17:45:16.047621+00:00 app[web.1]: 	at metabase.core$init_BANG_.invoke(core.clj:87)
2017-11-30T17:45:16.047691+00:00 app[web.1]: 	at metabase.core$start_normally.invokeStatic(core.clj:194)
2017-11-30T17:45:16.047736+00:00 app[web.1]: 	at metabase.core$start_normally.invoke(core.clj:188)
2017-11-30T17:45:16.047797+00:00 app[web.1]: 	at metabase.core$_main.invokeStatic(core.clj:292)
2017-11-30T17:45:16.047843+00:00 app[web.1]: 	at metabase.core$_main.doInvoke(core.clj:287)
2017-11-30T17:45:16.047892+00:00 app[web.1]: 	at clojure.lang.RestFn.invoke(RestFn.java:397)
2017-11-30T17:45:16.047966+00:00 app[web.1]: 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
2017-11-30T17:45:16.048016+00:00 app[web.1]: 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
2017-11-30T17:45:16.048078+00:00 app[web.1]: 	at metabase.core.main(Unknown Source)
2017-11-30T17:45:16.048321+00:00 app[web.1]: Caused by: liquibase.exception.SetupException: Error parsing migrations/000_migrations.yaml
2017-11-30T17:45:16.048367+00:00 app[web.1]: 	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:448)
2017-11-30T17:45:16.048416+00:00 app[web.1]: 	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:352)
2017-11-30T17:45:16.048502+00:00 app[web.1]: 	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:282)
2017-11-30T17:45:16.048503+00:00 app[web.1]: 	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:91)
2017-11-30T17:45:16.048564+00:00 app[web.1]: 	... 32 more
2017-11-30T17:45:16.048736+00:00 app[web.1]: Caused by: liquibase.exception.ChangeLogParseException: Error parsing migrations/000_migrations.yaml
2017-11-30T17:45:16.048785+00:00 app[web.1]: 	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:98)
2017-11-30T17:45:16.048857+00:00 app[web.1]: 	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:478)
2017-11-30T17:45:16.048907+00:00 app[web.1]: 	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:445)
2017-11-30T17:45:16.048956+00:00 app[web.1]: 	... 35 more
2017-11-30T17:45:16.049121+00:00 app[web.1]: Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
2017-11-30T17:45:16.049187+00:00 app[web.1]: 	at java.util.Hashtable.addEntry(Hashtable.java:435)
2017-11-30T17:45:16.049235+00:00 app[web.1]: 	at java.util.Hashtable.put(Hashtable.java:476)
2017-11-30T17:45:16.049293+00:00 app[web.1]: 	at sun.security.util.SignatureFileVerifier.updateSigners(SignatureFileVerifier.java:831)
2017-11-30T17:45:16.049362+00:00 app[web.1]: 	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:349)
2017-11-30T17:45:16.049407+00:00 app[web.1]: 	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:263)
2017-11-30T17:45:16.049537+00:00 app[web.1]: 	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:318)
2017-11-30T17:45:16.049588+00:00 app[web.1]: 	at java.util.jar.JarVerifier.update(JarVerifier.java:230)
2017-11-30T17:45:16.049643+00:00 app[web.1]: 	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
2017-11-30T17:45:16.049710+00:00 app[web.1]: 	at java.util.jar.JarFile.getInputStream(JarFile.java:450)
2017-11-30T17:45:16.049777+00:00 app[web.1]: 	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:162)
2017-11-30T17:45:16.049869+00:00 app[web.1]: 	at liquibase.resource.ClassLoaderResourceAccessor.getResourcesAsStream(ClassLoaderResourceAccessor.java:50)
2017-11-30T17:45:16.049926+00:00 app[web.1]: 	at liquibase.util.StreamUtil.singleInputStream(StreamUtil.java:186)
2017-11-30T17:45:16.049991+00:00 app[web.1]: 	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:26)
2017-11-30T17:45:16.050047+00:00 app[web.1]: 	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:478)
2017-11-30T17:45:16.050084+00:00 app[web.1]: 	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:445)
2017-11-30T17:45:16.050138+00:00 app[web.1]: 	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:352)
2017-11-30T17:45:16.050188+00:00 app[web.1]: 	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:282)
2017-11-30T17:45:16.050281+00:00 app[web.1]: 	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:91)
2017-11-30T17:45:16.050340+00:00 app[web.1]: 	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:229)
2017-11-30T17:45:16.050383+00:00 app[web.1]: 	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1183)
2017-11-30T17:45:16.050442+00:00 app[web.1]: 	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1176)
2017-11-30T17:45:16.050495+00:00 app[web.1]: 	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1172)
2017-11-30T17:45:16.050551+00:00 app[web.1]: 	at metabase.db$has_unrun_migrations_QMARK_.invokeStatic(db.clj:135)
2017-11-30T17:45:16.050603+00:00 app[web.1]: 	at metabase.db$has_unrun_migrations_QMARK_.invoke(db.clj:129)
2017-11-30T17:45:16.050660+00:00 app[web.1]: 	at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:159)
2017-11-30T17:45:16.050716+00:00 app[web.1]: 	at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:151)
2017-11-30T17:45:16.050782+00:00 app[web.1]: 	at metabase.db$migrate_BANG_$fn__21163.invoke(db.clj:247)
2017-11-30T17:45:16.050831+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
2017-11-30T17:45:16.050895+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
2017-11-30T17:45:16.050957+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:740)
2017-11-30T17:45:16.051009+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
2017-11-30T17:45:16.051055+00:00 app[web.1]: 	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
2017-11-30T17:45:16.052437+00:00 app[web.1]: 11-30 17:45:16 ERROR metabase.core :: Metabase Initialization FAILED:  Error parsing liquibase.yaml
2017-11-30T17:45:16.058409+00:00 app[web.1]: 11-30 17:45:16 INFO metabase.core :: Metabase Shutting Down ...
2017-11-30T17:45:16.058911+00:00 app[web.1]: 11-30 17:45:16 INFO metabase.core :: Metabase Shutdown COMPLETE
2017-11-30T17:45:16.554786+00:00 heroku[web.1]: Process exited with status 1
2017-11-30T17:45:16.570447+00:00 heroku[web.1]: State changed from up to crashed
2017-11-30T17:45:16.572889+00:00 heroku[web.1]: State changed from crashed to starting
2017-11-30T17:45:22.522491+00:00 heroku[web.1]: Starting process with command `./bin/start`
2017-11-30T17:45:25.462354+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2017-11-30T17:45:25.514965+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -Dfile.encoding=UTF-8
2017-11-30T17:45:41.678262+00:00 app[web.1]: 11-30 17:45:41 INFO metabase.util :: Loading Metabase...
```

**Comment by ericchernuka** [comment]
Apologies. This turned out to be because we forked the app on Heroku and it defaulted to a hobby dyno.  Moving the dyno to 2X fixed our memory issue.
