### ISSUE TITLE
Unable to migrate from h2 file to postgres

### ISSUE THREAD

**Issue by madhavc** [metabase/metabase#6582]
### Bugs
- Your browser and the version: **Chrome 52.1**
- Your operating system: **ubuntu**
- Your databases: **Postgres**
- Metabase version: **0.27.2**
- Metabase hosting environment: **jar file**
- Metabase internal database: **h2 file migrating to new ec2 with postgres**

- *Repeatable steps to reproduce the issue*
Run the command `java -jar metabase.jar load-from-h2` or `java -jar metabase.jar load-from-h2 ~/metabase.db.h2.db`

Gets errored out 

```
java -jar metabase.jar load-from-h2
12-14 23:45:43 INFO metabase.util :: Loading Metabase...
12-14 23:45:47 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
12-14 23:45:52 INFO metabase.db :: Verifying postgres Database Connection ...
12-14 23:45:52 INFO metabase.db :: Verify Database Connection ...  ✅
12-14 23:45:52 INFO metabase.db :: Running Database Migrations...
12-14 23:45:52 INFO metabase.db :: Setting up Liquibase...
12-14 23:45:53 INFO metabase.db :: Liquibase is ready.
12-14 23:45:53 INFO metabase.db :: Checking if Database has unrun migrations...
12-14 23:45:55 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
Temporarily disabling DB constraints...
[OK]
org.h2.jdbc.JdbcSQLException: Unsupported database file version or invalid file header in file "/home/ubuntu/metabase.db.h2.db" [90048-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.store.FileStore.init(FileStore.java:194)
	at org.h2.engine.Database.openFile(Database.java:558)
	at org.h2.store.PageStore.openExisting(PageStore.java:329)
	at org.h2.store.PageStore.open(PageStore.java:289)
	at org.h2.engine.Database.getPageStore(Database.java:2488)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
```
Thanks you please help as we are trying to migrate for production!
-------

**Comment by madhavc** [comment]
Issue was resolved by renaming the file to `metabase.db.mv.db`
