### ISSUE TITLE
can't start with docker 

### ISSUE THREAD

**Issue by BlankRain** [metabase/metabase#6602]
```
➜  ~ sudo docker run -d -p 3000:3000 --name metabase metabase/metabase
Unable to find image 'metabase/metabase:latest' locally
latest: Pulling from metabase/metabase
e110a4a17941: Pull complete 
5726fbb708f0: Pull complete 
7c322de39b42: Pull complete 
e00b172abb18: Pull complete 
f53440e31a7d: Pull complete 
e19a51f4a73a: Pull complete 
7e5d96b2f78f: Pull complete 
Digest: sha256:8a6351aa14202e1daec5cde3eb58b4571ee8835ec4cb009f65a196fb08212f17
Status: Downloaded newer image for metabase/metabase:latest
8724fe2f29e4ef257fd04a230542c1797d984b31d55de838f47783736cbdb16d

```
Then ,I can't connect to http://localhost:3000

```
➜  ~ sudo docker logs metabase 
12-20 02:46:26 INFO metabase.util :: Loading Metabase...
12-20 02:46:39 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓 
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
12-20 02:47:11 INFO metabase.core :: Starting Metabase in STANDALONE mode
12-20 02:47:11 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000, :host "0.0.0.0"}

12-20 02:47:12 INFO metabase.core :: Starting Metabase version v0.27.2 (35acf6e release-0.27.0) ...
12-20 02:47:12 INFO metabase.core :: System timezone is 'GMT' ...
12-20 02:47:30 WARN metabase.driver :: No -init-driver function found for 'metabase.driver.google'
12-20 02:47:34 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
12-20 02:47:34 INFO metabase.db :: Verifying h2 Database Connection ...
12-20 02:47:39 ERROR metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
12-20 02:47:39 ERROR metabase.core :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
12-20 02:47:39 INFO metabase.core :: Metabase Shutting Down ...
12-20 02:47:39 INFO metabase.core :: Metabase Shutdown COMPLETE
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
	at metabase.db$verify_db_connection.invokeStatic(db.clj:334)
	at metabase.db$verify_db_connection.invoke(db.clj:327)
	at metabase.db$verify_db_connection.invokeStatic(db.clj:330)
	at metabase.db$verify_db_connection.invoke(db.clj:327)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:382)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:108)
	at metabase.core$init_BANG_.invoke(core.clj:87)
	at metabase.core$start_normally.invokeStatic(core.clj:194)
	at metabase.core$start_normally.invoke(core.clj:188)
	at metabase.core$_main.invokeStatic(core.clj:292)
	at metabase.core$_main.doInvoke(core.clj:287)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
```

**Comment by salsakran** [comment]
This isn't an appropriate place to get support running Metabase. Please open a thread on our discussion forum (discourse.metabase.com) and/or check out our troubleshooting guides and documentation at metabase.com/docs

**Comment by BlankRain** [comment]
okay, I see
