### ISSUE TITLE
SQLite error java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V

### ISSUE THREAD

**Issue by avnerbarr** [metabase/metabase#6627]
I am running the server through the docker cli using this command

docker run -d -p 3000:3000 --name metabase metabase/metabase

I copied some SQLIte test data to the docker instance by doing:

docker cp data.db metabase:/home/data.db

I logged into the docker instance and indeed see that the file is copied there correctly:

```
bash-4.3# ls -lah /home
total 6038480
drwxr-xr-x    1 root     root        4.0K Dec 31 09:26 .
drwxr-xr-x    1 root     root        4.0K Dec 31 09:16 ..
-rw-r--r--    1 501      dialout     6.2M Dec 31 09:25 data.csv
-rw-r--r--    1 501      dialout     5.8G Dec 30 20:21 data.db
drwxr-sr-x    2 metabase metabase    4.0K Dec 31 09:16 metabase
```

When I try to configure the UI to use that path I get this error

> java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V

![databases_ _admin_ _metabase](https://user-images.githubusercontent.com/2404795/34460703-e7ae0604-ee1e-11e7-8a72-48dff6888399.png)

**Comment by salsakran** [comment]
I don't know a ton about how the sqllite driver works off the top of my head, but what happens if you place it in the directory with the metabase file and use a relative path? Eg, is it just not treating absolute paths properly, or is it not working at all in your situation?

**Comment by camsaul** [comment]
Sounds like the same issue as #3753.

This is an issue with the SQLite JDBC driver we use (see xerial/sqlite-jdbc#97). We first started seeing this a while back after upgrading to a newer version a little over a year ago, so we rolled back to an older version. From discussion in #3753 it sounds like upgrading to the newest version might fix everything for everybody. So we can try that out and if it ends up breaking more things than it fixes we can roll it back again.

**Comment by camsaul** [comment]
@avnerbarr do you think you could try #6632 and see if that fixes it for you?

**Comment by fcasco** [comment]
Hi, I'm having the same issue. How can I try #6632 running from Docker?

**Comment by jornh** [comment]
@fcasco there's an automated build at https://hub.docker.com/r/metabase/metabase-head/

**Comment by camsaul** [comment]
I'll have to merge the PR before it's available in the automated HEAD build. I'll go ahead and do that since it sounds like this fix should work. @avnerbarr please try it out and let me know and I can reopen this issue if you're still having problems

**Comment by ad-m** [comment]
Unfortunately, this doesn't help.

```
 $ docker pull metabase/metabase-head
Using default tag: latest
latest: Pulling from metabase/metabase-head
709515475419: Already exists 
38a1c0aaa6fd: Pull complete 
cd134db5e982: Pull complete 
525df8038313: Pull complete 
2fc92596958c: Pull complete 
f0ae9dd3ea75: Pull complete 
f431863c6614: Pull complete 
cc91377b9e36: Pull complete 
e1ea7c835cf0: Pull complete 
c00178261fcf: Pull complete 
98d0e6de9bc5: Pull complete 
Digest: sha256:ef0f66b258a744068f46e92ef103b5e1ed332f584d3fba9f6e990a5e33ae9bbb
Status: Downloaded newer image for metabase/metabase-head:latest
$ docker run -d -p 3000:3000 -v $PWD:/db/ --name metabase metabase/metabase-head:latest
2ae30d97a2433cc2fd9a19ce93abe6d61be8c275a177ac27f554d7df966ab1b5
$ docker logs -f metabase
...
03-24 01:51:44 ERROR metabase.driver :: Failed to connect to database: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
03-24 01:51:44 DEBUG metabase.middleware :: POST /api/setup/validate 400 (4 ms) (0 DB calls).
{:errors {:dbname "java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V"}}
....
```

**Comment by ad-m** [comment]
As mentioned in lmenezes/cerebro#121 there is permission issue in ```/tmp/``` directory. Chmod 777 /tmp & restart container fixed that IMO.

**Comment by temal-** [comment]
Problem still exists in `v0.28.6 (83e3c0d release-0.28.6)` and `v0.29.0-snapshot (dc63082 master)`.

> v0.28.6 (83e3c0d release-0.28.6)
```
Failed to load native library:sqlite-3.21.0.1-6304c9f0-be81-4e9a-8048-0b8b372fff62-libsqlitejdbc.so. osinfo: Linux/x86_64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.21.0.1-6304c9f0-be81-4e9a-8048-0b8b372fff62-libsqlitejdbc.so: Error relocating /tmp/sqlite-3.21.0.1-6304c9f0-be81-4e9a-8048-0b8b372fff62-libsqlitejdbc.so: __isnan: symbol not found
04-29 07:58:39 ERROR metabase.driver :: Failed to connect to database: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
04-29 07:58:39 DEBUG metabase.middleware :: POST /api/setup/validate 400 (286 ms) (0 DB calls).
{:errors {:dbname "java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V"}}
```

> v0.29.0-snapshot (dc63082 master)
```
Failed to load native library:sqlite-3.21.0.1-75a2bc7b-0cf8-4e4f-aba8-387a379333f2-libsqlitejdbc.so. osinfo: Linux/x86_64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.21.0.1-75a2bc7b-0cf8-4e4f-aba8-387a379333f2-libsqlitejdbc.so: Error relocating /tmp/sqlite-3.21.0.1-75a2bc7b-0cf8-4e4f-aba8-387a379333f2-libsqlitejdbc.so: __isnan: symbol not found
04-29 08:09:09 ERROR metabase.driver :: Failed to connect to database: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
04-29 08:09:09 DEBUG metabase.middleware :: POST /api/setup/validate 400 (94 ms) (0 DB calls).
{:errors {:dbname "java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V"}}
```

**Comment by daemianmack** [comment]
Also hitting this error. Is there perhaps an older Docker/build I can use instead?

**Comment by ad-m** [comment]
I added glibc via following Dockerfile:
```
$ git diff Dockerfile
diff --git a/Dockerfile b/Dockerfile
index 12313c8..3db27f0 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -2,7 +2,7 @@
 # images hosted on Docker Hub https://hub.docker.com/r/metabase/metabase/ which use the
 # Dockerfile located at ./bin/docker/Dockerfile
 
-FROM java:openjdk-8-jre-alpine
+FROM frolvlad/alpine-glibc:latest
 
 ENV JAVA_HOME=/usr/lib/jvm/default-jvm
 ENV PATH /usr/local/bin:$PATH
@@ -12,13 +12,13 @@ ENV FC_LANG en-US
 ENV LC_CTYPE en_US.UTF-8
 
 # install core build tools
-RUN apk add --update nodejs git wget bash python make g++ java-cacerts ttf-dejavu fontconfig && \
+RUN apk add --update nodejs git wget bash python make g++ java-cacerts ttf-dejavu fontconfig sqlite-dev openjdk7-jre && \
     npm install -g yarn && \
     ln -sf "${JAVA_HOME}/bin/"* "/usr/bin/"
 
 # fix broken cacerts
-RUN rm -f /usr/lib/jvm/default-jvm/jre/lib/security/cacerts && \
-    ln -s /etc/ssl/certs/java/cacerts /usr/lib/jvm/default-jvm/jre/lib/security/cacerts
+# RUN rm -f /usr/lib/jvm/default-jvm/jre/lib/security/cacerts && \
+#     ln -s /etc/ssl/certs/java/cacerts /usr/lib/jvm/default-jvm/jre/lib/security/cacerts
 
 # install lein
 ADD https://raw.github.com/technomancy/leiningen/stable/bin/lein /usr/local/bin/lein
```

It fails on last step of setup (but SQLite database added):
``` 
05-05 10:05:06 INFO sync.util :: FINISHED: Analyze data for h2 Database 1 'Sample Dataset' (11 s)
05-05 10:05:06 DEBUG sync.util :: Sync operations in flight: {:sync #{1}, :cache-field-values #{1}}
05-05 10:05:06 INFO sync.util :: STARTING: Cache field values in h2 Database 1 'Sample Dataset'
05-05 10:05:06 DEBUG sync.field-values :: Looking into updating FieldValues for Field 2 'RATING'
05-05 10:05:06 DEBUG sync.field-values :: Looking into updating FieldValues for Field 6 'CATEGORY'
05-05 10:05:06 DEBUG sync.field-values :: Looking into updating FieldValues for Field 14 'QUANTITY'
05-05 10:05:08 DEBUG sync.field-values :: Looking into updating FieldValues for Field 24 'SOURCE'
05-05 10:05:08 DEBUG sync.field-values :: Looking into updating FieldValues for Field 28 'STATE'
05-05 10:05:08 DEBUG sync.field-values :: Looking into updating FieldValues for Field 36 'RATING'
05-05 10:05:08 INFO sync.util :: FINISHED: Cache field values in h2 Database 1 'Sample Dataset' (2 s)
05-05 10:05:08 INFO sync.util :: FINISHED: Sync h2 Database 1 'Sample Dataset' (14 s)
05-05 10:05:08 INFO metabase.core :: Metabase Initialization COMPLETE
05-05 10:05:12 DEBUG metabase.middleware :: GET /api/session/properties 200 (9 ms) (1 DB calls). Jetty threads: 8/50 (4 busy, 4 idle, 0 queued)
05-05 10:05:12 DEBUG metabase.middleware :: GET /api/user/current 401 (6 ms) (0 DB calls).
"Unauthenticated"

Exception in thread "dirigiste-pool-controller-0" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at io.aleph.dirigiste.Stats$UniformLongReservoirMap.toMap(Stats.java:114)
	at io.aleph.dirigiste.Pool.updateStats(Pool.java:237)
	at io.aleph.dirigiste.Pool.startControlLoop(Pool.java:320)
	at io.aleph.dirigiste.Pool.access$500(Pool.java:8)
	at io.aleph.dirigiste.Pool$1.run(Pool.java:381)
	at java.lang.Thread.run(Thread.java:748)
05-05 10:05:56 DEBUG metabase.middleware :: POST /api/util/password_check 200 (4 ms) (0 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
05-05 10:06:13 DEBUG metabase.middleware :: POST /api/setup/validate 200 (204 ms) (0 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
05-05 10:06:15 INFO models.user :: Adding user 1 to All Users permissions group...
05-05 10:06:15 INFO models.user :: Adding user 1 to Admin permissions group...
05-05 10:06:15 DEBUG sync.util :: Sync operations in flight: {:sync #{2}}
05-05 10:06:15 INFO sync.util :: STARTING: Sync sqlite Database 2 'xxx'
05-05 10:06:15 DEBUG sync.util :: Sync operations in flight: {:sync #{2}, :sync-metadata #{2}}
05-05 10:06:15 INFO sync.util :: STARTING: Sync metadata for sqlite Database 2 'xxx'
05-05 10:06:15 DEBUG metabase.middleware :: POST /api/setup 200 (627 ms) (20 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
05-05 10:06:15 INFO sync-metadata.tables :: Found new tables: (Table  'invoice_items' Table  'genres' Table  'tracks' Table  'albums' Table  'playlists' Table  'customers' Table  'employees' Table  'invoices' Table  'media_types' Table  'artists' Table  'playlist_track')
05-05 10:06:16 INFO sync-metadata.fks :: Marking foreign key from Table 5 'invoice_items' Field 40 'TrackId' -> Table 7 'tracks' Field 49 'TrackId'
05-05 10:06:16 INFO sync-metadata.fks :: Marking foreign key from Table 5 'invoice_items' Field 41 'InvoiceId' -> Table 12 'invoices' Field 92 'InvoiceId'
05-05 10:06:16 INFO sync-metadata.fks :: Marking foreign key from Table 7 'tracks' Field 45 'AlbumId' -> Table 8 'albums' Field 53 'AlbumId'
05-05 10:06:16 INFO sync-metadata.fks :: Marking foreign key from Table 7 'tracks' Field 44 'MediaTypeId' -> Table 13 'media_types' Field 96 'MediaTypeId'
05-05 10:06:16 INFO sync-metadata.fks :: Marking foreign key from Table 7 'tracks' Field 47 'GenreId' -> Table 6 'genres' Field 42 'GenreId'
05-05 10:06:16 INFO sync-metadata.fks :: Marking foreign key from Table 8 'albums' Field 55 'ArtistId' -> Table 14 'artists' Field 97 'ArtistId'
05-05 10:06:16 INFO sync-metadata.fks :: Marking foreign key from Table 10 'customers' Field 63 'SupportRepId' -> Table 11 'employees' Field 71 'EmployeeId'
05-05 10:06:16 INFO sync-metadata.fks :: Marking foreign key from Table 11 'employees' Field 79 'ReportsTo' -> Table 11 'employees' Field 71 'EmployeeId'
05-05 10:06:16 INFO sync-metadata.fks :: Marking foreign key from Table 12 'invoices' Field 90 'CustomerId' -> Table 10 'customers' Field 62 'CustomerId'
05-05 10:06:16 INFO sync-metadata.fks :: Marking foreign key from Table 15 'playlist_track' Field 100 'TrackId' -> Table 7 'tracks' Field 49 'TrackId'
05-05 10:06:16 INFO sync-metadata.fks :: Marking foreign key from Table 15 'playlist_track' Field 99 'PlaylistId' -> Table 9 'playlists' Field 56 'PlaylistId'
05-05 10:06:16 INFO sync.util :: FINISHED: Sync metadata for sqlite Database 2 'xxx' (920 ms)
05-05 10:06:16 DEBUG sync.util :: Sync operations in flight: {:sync #{2}, :analyze #{2}}
05-05 10:06:16 INFO sync.util :: STARTING: Analyze data for sqlite Database 2 'xxx'
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000000a786, pid=1, tid=139638784359144
#
# JRE version: OpenJDK Runtime Environment (7.0_151-b01) (build 1.7.0_151-b01)
# Java VM: OpenJDK 64-Bit Server VM (24.151-b01 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.6.11
# Distribution: Custom build (Tue Nov 21 10:48:38 GMT 2017)
# Problematic frame:
# C  0x000000000000a786
#
# Core dump written. Default location: /app/source/core or core.1
#
# An error report file with more information is saved as:
# /app/source/hs_err_pid1.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
#
```

**Comment by fmendonca00** [comment]
The same error while adding database *.db in docker image Metabase 0.30.3 
ERROR metabase.driver :: Failed to connect to database: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
