### ISSUE TITLE
Unable to synchronize database

### ISSUE THREAD

**Issue by lucasm-iRonin** [metabase/metabase#6871]
Hi,
I'm getting errors when I try to synchronize Database schema.

Info:
- Database: PostgreSQL 9.2.20
- OS: Debian 8.9
- Metabase: 0.27.2
- Metabase hosting environment: VPS
- Metabase internal database: H2

Here is stack trace from logs:

```
02-06 08:31:53 WARN sync-metadata.sync-timezone :: Error syncing database timezone
java.lang.Exception: Unable to parse date string '2018-02-06 08:31:53.212 CET' for database engine 'postgres'
        at metabase.driver$make_current_db_time_fn$fn__24563.invoke(driver.clj:305)
        at metabase.driver$fn__24443$G__24295__24450.invoke(driver.clj:34)
        at metabase.sync.sync_metadata.sync_timezone$fn__35601$sync_timezone_BANG___35606$fn__35607.invoke(sync_timezone.clj:20)
        at metabase.sync.sync_metadata.sync_timezone$fn__35601$sync_timezone_BANG___35606.invoke(sync_timezone.clj:13)
        at metabase.sync.sync_metadata$fn__35843$sync_db_metadata_BANG___35848$fn__35849$fn__35850.invoke(sync_metadata.clj:24)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:115)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:110)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:113)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:110)
        at clojure.core$partial$fn__4759.invoke(core.clj:2514)
        at metabase.driver$fn__24534.invokeStatic(driver.clj:209)
        at metabase.driver$fn__24534.invoke(driver.clj:209)
        at metabase.driver$fn__24508$G__24289__24517.invoke(driver.clj:34)
        at metabase.sync.util$sync_in_context$fn__33235.invoke(util.clj:106)
        at metabase.sync.util$with_db_logging_disabled$fn__33232.invoke(util.clj:98)
        at metabase.sync.util$with_start_and_finish_logging$fn__33227.invoke(util.clj:87)
        at metabase.sync.util$with_sync_events$fn__33224.invoke(util.clj:70)
        at metabase.sync.util$with_duplicate_ops_prevented$fn__33215.invoke(util.clj:49)
        at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:133)
        at metabase.sync.util$do_sync_operation.invoke(util.clj:130)
        at metabase.sync.sync_metadata$fn__35843$sync_db_metadata_BANG___35848$fn__35849.invoke(sync_metadata.clj:23)
        at metabase.sync.sync_metadata$fn__35843$sync_db_metadata_BANG___35848.invoke(sync_metadata.clj:20)
        at metabase.api.database$fn__36486$fn__36487$fn__36488.invoke(database.clj:495)
        at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid format: "2018-02-06 08:31:53.212 CET" is malformed at "CET"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
        at clj_time.format$parse.invokeStatic(format.clj:160)
        at clj_time.format$parse.invoke(format.clj:156)
        at metabase.driver$make_current_db_time_fn$fn__24563.invoke(driver.clj:301)
        ... 28 more
02-06 08:31:53 WARN driver.generic-sql :: Don't know how to map column type '_text' to a Field base_type, falling back to :type/*.
02-06 08:31:53 WARN driver.generic-sql :: Don't know how to map column type '_int4' to a Field base_type, falling back to :type/*.
02-06 08:31:53 WARN driver.generic-sql :: Don't know how to map column type '_int4' to a Field base_type, falling back to :type/*.
02-06 08:31:53 WARN driver.generic-sql :: Don't know how to map column type '_text' to a Field base_type, falling back to :type/*.
02-06 08:31:53 WARN driver.generic-sql :: Don't know how to map column type 'hstore' to a Field base_type, falling back to :type/*.
02-06 08:31:54 WARN driver.generic-sql :: Don't know how to map column type '_text' to a Field base_type, falling back to :type/*.
02-06 08:31:54 WARN driver.generic-sql :: Don't know how to map column type '_varchar' to a Field base_type, falling back to :type/*.
02-06 08:31:54 WARN driver.generic-sql :: Don't know how to map column type 'candidate_status' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type '_text' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type '_varchar' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type 'hstore' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type 'training_states' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type 'hstore' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type 'hstore' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type 'hstore' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type '_hstore' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type '_hstore' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type '_hstore' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type 'hstore' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type '_text' to a Field base_type, falling back to :type/*.
02-06 08:31:55 WARN driver.generic-sql :: Don't know how to map column type '_varchar' to a Field base_type, falling back to :type/*.
02-06 08:31:57 INFO sync.util :: FINISHED: Sync metadata for postgres Database 2 'application' (4 s)
```

This error prevents me from running the Metabase questions because the column that Metabase remember is no longer available.

**Comment by senior** [comment]
Can you describe what problem you are seeing? The exception above is a warning only and should not cause issues with your running Metabase instance. The error occurs because Joda Time doesn't recognize the CET timezone, but the timezone information is used for debugging only and should have no affect (other than the message in the log). Newer versions of Metabase shouldn't show that error, we try to parse the timezone using Java's built-in date library if Joda Time doesn't work.

**Comment by lucasm-iRonin** [comment]
@senior thank you for your response. I've updated Metabase to the latest version (v0.28.1 at the time of writing this) and the warning disappeared. Unfortunately the initial problem (removed column from database are still visible in Metabase) remains. I believe the problem is related to #6146 , right?

**Comment by senior** [comment]
@lucasm-iRonin If you're having problems with Metabase referencing a column that no longer exists, I need some more info to be able to troubleshoot this.

- When you say the removed column is still visible in Metabase, where are you seeing it?
- What database has this column been removed from?
- If the column has been removed, has sync ran since it's been removed? You can trigger this manually via the admin panel and will run periodically (hourly) depending on how your Metabase instance is configured.

**Comment by lucasm-iRonin** [comment]
@senior as I mentioned in the previous update, updating to the latest version fixed problem for me.
