### ISSUE TITLE
Pulse Email Issue

### ISSUE THREAD

**Issue by sranes** [metabase/metabase#6935]
Hi Team,

Unable to send email using Pulse
Email is not being sent when "Send email now" is clicked.
The email ID specified in the "To" section also not getting saved.
When I look into the log screen, the only message I get related to this is "WARN metabase.email :: Failed to send email"

Metabase Version 0.28
DB: Metabase embedded database
Email Settings
SMTP Host: smtp.gmail.com
SMTP Port: 465
SMTP Security: SSL

**Comment by sranes** [comment]
Console error message:
2-11 11:11:54 [1mWARN metabase.email[0m :: Failed to send email
java.lang.NullPointerException
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1204)
        at postal.smtp$smtp_send_STAR_.invokeStatic(smtp.clj:36)
        at postal.smtp$smtp_send_STAR_.invoke(smtp.clj:29)
        at postal.smtp$smtp_send.invokeStatic(smtp.clj:58)
        at postal.smtp$smtp_send.doInvoke(smtp.clj:39)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at postal.core$send_message.invokeStatic(core.clj:35)
        at postal.core$send_message.invoke(core.clj:29)
        at metabase.email$fn__23155$send_message_or_throw_BANG___23160$fn__23164.invoke(email.clj:78)
        at metabase.email$fn__23155$send_message_or_throw_BANG___23160.invoke(email.clj:69)
        at metabase.email$send_message_BANG_.invokeStatic(email.clj:103)
        at metabase.email$send_message_BANG_.doInvoke(email.clj:88)
        at clojure.lang.RestFn.invoke(RestFn.java:619)
        at metabase.pulse$fn__32589.invokeStatic(pulse.clj:206)
        at metabase.pulse$fn__32589.invoke(pulse.clj:204)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:214)
        at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:212)
        at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:240)
        at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:231)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at metabase.api.pulse$fn__32755$fn__32758.invoke(pulse.clj:155)
        at metabase.api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:253)
        at metabase.api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:248)
        at metabase.api.pulse$fn__32755.invokeStatic(pulse.clj:147)
        at metabase.api.pulse$fn__32755.invoke(pulse.clj:147)
        at compojure.core$make_route$fn__1561.invoke(core.clj:135)
        at compojure.core$wrap_route_middleware$fn__1554.invoke(core.clj:122)
        at compojure.core$wrap_route_info$fn__1558.invoke(core.clj:126)
        at compojure.core$if_route$fn__1516.invoke(core.clj:45)
        at compojure.core$if_method$fn__1506.invoke(core.clj:27)
        at compojure.core$routing$fn__1568.invoke(core.clj:151)
        at clojure.core$some.invokeStatic(core.clj:2592)
        at clojure.core$some.invoke(core.clj:2583)
        at compojure.core$routing.invokeStatic(core.clj:151)
        at compojure.core$routing.doInvoke(core.clj:148)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at compojure.core$routes$fn__1572.invoke(core.clj:156)
        at metabase.middleware$enforce_authentication$fn__33151.invoke(middleware.clj:123)
        at compojure.core$routing$fn__1568.invoke(core.clj:151)
        at clojure.core$some.invokeStatic(core.clj:2592)
        at clojure.core$some.invoke(core.clj:2583)
        at compojure.core$routing.invokeStatic(core.clj:151)
        at compojure.core$routing.doInvoke(core.clj:148)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at metabase.api.routes$fn__46125.invokeStatic(routes.clj:80)
        at metabase.api.routes$fn__46125.invoke(routes.clj:80)
        at compojure.core$if_context$fn__1590.invoke(core.clj:220)
        at compojure.core$routing$fn__1568.invoke(core.clj:151)
        at clojure.core$some.invokeStatic(core.clj:2592)
        at clojure.core$some.invoke(core.clj:2583)
        at compojure.core$routing.invokeStatic(core.clj:151)
        at compojure.core$routing.doInvoke(core.clj:148)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at compojure.core$routes$fn__1572.invoke(core.clj:156)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$apply.invoke(core.clj:641)
        at metabase.routes$fn__46855$fn__46856.doInvoke(routes.clj:106)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at compojure.core$routing$fn__1568.invoke(core.clj:151)
        at clojure.core$some.invokeStatic(core.clj:2592)
        at clojure.core$some.invoke(core.clj:2583)
        at compojure.core$routing.invokeStatic(core.clj:151)
        at compojure.core$routing.doInvoke(core.clj:148)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at metabase.routes$fn__46855.invokeStatic(routes.clj:101)
        at metabase.routes$fn__46855.invoke(routes.clj:101)
        at compojure.core$if_context$fn__1590.invoke(core.clj:220)
        at compojure.core$routing$fn__1568.invoke(core.clj:151)
        at clojure.core$some.invokeStatic(core.clj:2592)
        at clojure.core$some.invoke(core.clj:2583)
        at compojure.core$routing.invokeStatic(core.clj:151)
        at compojure.core$routing.doInvoke(core.clj:148)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at compojure.core$routes$fn__1572.invoke(core.clj:156)
        at clojure.lang.Var.invoke(Var.java:379)
        at metabase.middleware$log_api_call$fn__33250$fn__33252.invoke(middleware.clj:342)
        at toucan.db$_do_with_call_counting.invokeStatic(db.clj:205)
        at toucan.db$_do_with_call_counting.invoke(db.clj:198)
        at metabase.middleware$log_api_call$fn__33250.invoke(middleware.clj:341)
        at metabase.middleware$add_security_headers$fn__33200.invoke(middleware.clj:255)
        at ring.middleware.json$wrap_json_body$fn__47453.invoke(json.clj:44)
        at metabase.core$wrap_streamed_json_response$fn__47650.invoke(core.clj:66)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__47498.invoke(keyword_params.clj:36)
        at ring.middleware.params$wrap_params$fn__47546.invoke(params.clj:67)
        at metabase.middleware$bind_current_user$fn__33155.invoke(middleware.clj:144)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at metabase.middleware$maybe_set_site_url$fn__33204.invoke(middleware.clj:279)
        at puppetlabs.i18n.core$locale_negotiator$fn__124.invoke(core.clj:357)
        at ring.middleware.cookies$wrap_cookies$fn__47396.invoke(cookies.clj:175)
        at ring.middleware.session$wrap_session$fn__47637.invoke(session.clj:108)
        at ring.middleware.gzip$wrap_gzip$fn__47427.invoke(gzip.clj:65)
        at ring.adapter.jetty$proxy_handler$fn__47273.invoke(jetty.clj:25)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)

**Comment by sranes** [comment]
Same issue with Metabase V0.28.1

**Comment by jornh** [comment]
Just googled this up on smtp access to GMail: https://www.lifewire.com/unlock-gmail-for-a-new-email-program-or-service-1171974

Maybe useful?

Do you get any notifications inside your google account?

**Comment by sranes** [comment]
There is no issue with email configuration as the same configuration works for older version of Metabase (v.26x). 

The root cause seems to be the email IDs specified in the "To" field are not getting saved/passed.

Is this functionality working for others in V.28?

**Comment by salsakran** [comment]
This seems very strange. We haven't made any changes to the code that sends emails in a long time, and it's fairly well tested.

This seems like it's almost certainly a problem with either your credentials, white listing ips or sending accounts, etc. Does 0.26 work on the same machine?

**Comment by mikeclarke** [comment]
If @sranes hit the same issue I did, the confusion is in the UX for sending a test pulse.

![image](https://user-images.githubusercontent.com/245199/36614732-7cadfafa-1892-11e8-8378-94186dab9a31.png)

If I hit send with my email address in the text box, I'll hit the same NPE exception as suggested above. However, if I select the corresponding user account from the dropdown *then* click "Send email now", I get the test pulse in my inbox. I think the expectation is that if the text input has a valid email, it would go out to that address when you click "Send email now". I'm assuming this isn't an issue once you schedule pulses to go out to an address because it's being persisted properly after saving.

**Comment by sranes** [comment]
@mikeclarke is right, when a registered user is selected in the email "To" field, it all works fine, but when an email id directly specified in the "To" filed, NPE is thrown.

@salsakran is this something expected or needs to be addressed?

**Comment by sranes** [comment]
If the expectation is only registered users are to be selected for "Send email now", then this issue can be closed.

**Comment by salsakran** [comment]
you should be able to send emails to people who don't have user accounts, and we do so regularly.  Let me try to reproduce this.

**Comment by salsakran** [comment]
reproduced. =(

**Comment by senior** [comment]
I can reproduce this issue locally. It looks like the UI is not including non-user recipients in the POST. If I include only a email address, no recipients are included in the POST. If I have a MB user and an email address, only the MB user is included in the recipient list.

**Comment by tlrobinson** [comment]
I believe this was just due to some UX confusion where the recipient picker didn't "commit" the email address unless you hit tab or enter. I've fixed that in #7879 If that's not the case please let me know.
