### ISSUE TITLE
Running two instances against same database when migrating fails one for Postgres.

### ISSUE THREAD

**Issue by viblo** [metabase/metabase#6951]
I just installed the new 0.28.1 version of metabase (previously running 0.27). I have two instances running against the same metadata database which is a postgres db.

One instance failed to start up because of a PSQLException. It seems like it does wait for the migration lock to clear, but then try to migrate even when the other instance already completed the migration.

(Note that as a workaround restarting the instance fixes the problem, so this bug is not super critical)

The log from the instance that failed:
```
D:\home\site\wwwroot>"D:\Program Files\Java\jdk1.8.0_73\bin\java.exe" -Djava.net.preferIPv4Stack=true -jar ./metabase-0.28.1.jar 
02-14 09:38:58 [1mINFO metabase.util[0m :: Loading Metabase...
02-14 09:39:14 [1mINFO util.encryption[0m :: DB details encryption is DISABLED for this Metabase instance.  
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
02-14 09:39:38 [1mINFO metabase.core[0m :: Starting Metabase in STANDALONE mode
02-14 09:39:39 [1mINFO metabase.core[0m :: Launching Embedded Jetty Webserver with config:
 {:port 4227}

02-14 09:39:39 [1mINFO metabase.core[0m :: Starting Metabase version v0.28.1 (fe0c411 release-0.28.1) ...
02-14 09:39:39 [1mINFO metabase.core[0m :: System timezone is 'GMT' ...
02-14 09:39:39 [1mERROR metabase.middleware[0m :: GET /api/setup/admin_checklist 503 (8 ms) (0 DB calls)
"Metabase is still initializing. Please sit tight..."

02-14 09:39:39 [1mERROR metabase.middleware[0m :: GET /api/activity/recent_views 503 (10 ms) (0 DB calls)
"Metabase is still initializing. Please sit tight..."

02-14 09:39:42 [1mINFO metabase.core[0m :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
02-14 09:39:42 [1mINFO metabase.db[0m :: Verifying postgres Database Connection ...
02-14 09:39:43 [1mINFO metabase.db[0m :: Verify Database Connection ...  
02-14 09:39:43 [1mINFO metabase.db[0m :: Running Database Migrations...
02-14 09:39:44 [1mINFO metabase.db[0m :: Setting up Liquibase...
02-14 09:39:49 [1mINFO metabase.db[0m :: Liquibase is ready.
02-14 09:39:49 [1mINFO metabase.db[0m :: Checking if Database has unrun migrations...
02-14 09:39:54 [1mINFO metabase.db[0m :: Database has unrun migrations. Waiting for migration lock to be cleared...
02-14 09:39:54 [1mINFO metabase.db[0m :: Migration lock is cleared. Running migrations...
org.postgresql.util.PSQLException: ERROR: column "database_type" of relation "metabase_field" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__10897.invoke(jdbc.clj:952)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:784)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:724)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:951)
	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:945)
	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:983)
	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:963)
	at clojure.java.jdbc$execute_BANG_$execute_helper__10968.invoke(jdbc.clj:1364)
	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1366)
	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1337)
	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1356)
	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1337)
	at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:169)
	at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:155)
	at metabase.db$migrate_BANG_$fn__20229.invoke(db.clj:258)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:741)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:724)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at metabase.db$migrate_BANG_.invokeStatic(db.clj:246)
	at metabase.db$migrate_BANG_.invoke(db.clj:227)
	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:381)
	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:376)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:399)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:392)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:140)
	at metabase.core$init_BANG_.invoke(core.clj:119)
	at metabase.core$start_normally.invokeStatic(core.clj:248)
	at metabase.core$start_normally.invoke(core.clj:241)
	at metabase.core$_main.invokeStatic(core.clj:269)
	at metabase.core$_main.doInvoke(core.clj:264)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
02-14 09:39:59 [1mERROR metabase.core[0m :: Metabase Initialization FAILED:  ERROR: column "database_type" of relation "metabase_field" already exists
02-14 09:39:59 [1mINFO metabase.core[0m :: Metabase Shutting Down ...
02-14 09:39:59 [1mINFO metabase.core[0m :: Metabase Shutdown COMPLETE
```

An the one that succeeded looks like this:
```
D:\home\site\wwwroot>"D:\Program Files\Java\jdk1.8.0_73\bin\java.exe" -Djava.net.preferIPv4Stack=true -jar ./metabase-0.28.1.jar 
02-14 09:38:57 [1mINFO metabase.util[0m :: Loading Metabase...
02-14 09:39:12 [1mINFO util.encryption[0m :: DB details encryption is DISABLED for this Metabase instance.  
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
02-14 09:39:35 [1mINFO metabase.core[0m :: Starting Metabase in STANDALONE mode
02-14 09:39:35 [1mINFO metabase.core[0m :: Launching Embedded Jetty Webserver with config:
 {:port 4227}

02-14 09:39:35 [1mINFO metabase.core[0m :: Starting Metabase version v0.28.1 (fe0c411 release-0.28.1) ...
02-14 09:39:35 [1mINFO metabase.core[0m :: System timezone is 'GMT' ...
02-14 09:39:36 [1mERROR metabase.middleware[0m :: GET /api/activity 503 (9 ms) (0 DB calls)
"Metabase is still initializing. Please sit tight..."

02-14 09:39:39 [1mINFO metabase.core[0m :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
02-14 09:39:39 [1mINFO metabase.db[0m :: Verifying postgres Database Connection ...
02-14 09:39:40 [1mINFO metabase.db[0m :: Verify Database Connection ...  
02-14 09:39:40 [1mINFO metabase.db[0m :: Running Database Migrations...
02-14 09:39:41 [1mINFO metabase.db[0m :: Setting up Liquibase...
02-14 09:39:43 [1mINFO metabase.db[0m :: Liquibase is ready.
02-14 09:39:43 [1mINFO metabase.db[0m :: Checking if Database has unrun migrations...
02-14 09:39:50 [1mINFO metabase.db[0m :: Database has unrun migrations. Waiting for migration lock to be cleared...
02-14 09:39:50 [1mINFO metabase.db[0m :: Migration lock is cleared. Running migrations...
02-14 09:40:00 [1mINFO metabase.db[0m :: Database Migrations Current ...  
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
02-14 09:40:01 [1mINFO db.migrations[0m :: Running all necessary data migrations, this may take a minute.
02-14 09:40:03 [1mINFO db.migrations[0m :: Running data migration 'migrate-humanization-setting'...
02-14 09:40:03 [1mINFO db.migrations[0m :: Finished running data migrations.
```

**Comment by jornh** [comment]
>  I have two instances running against the same metadata database which is a postgres db.

Don't do that! Because Metabase isn't built for that ...
(or said in a slightly more polite way, why would you need to do that?)

I think this issue is basically a duplicate of the existing feature request in #2754

**Comment by viblo** [comment]
Yes, you are right. I didnt find it when I checked for existing problems and just assumed it would normally work. I will close this issue and add my usage to the other one.
