### ISSUE TITLE
Mac Version Latest update crashing

### ISSUE THREAD

**Issue by fandomfilms** [metabase/metabase#7004]
The last three version have caused issues for me.  I updated to 0.28.1.0 and when I attempt to open the software I get the following message:

The Metabase server terminated unexpectedly.

Messages:
WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__20186@1dc2211f: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__20186@1dc2211f: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
WARN metabase.util :: auto-retry metabase.db$wait_for_migration_lock_to_be_cleared$fn__20186@1dc2211f: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.
java.lang.Exception: Database has migration lock; cannot run migrations. You can force-release these locks by running `java -jar metabase.jar migrate release-locks`.at metabase.db$wait_for_migration_lock_to_be_cleared$fn__20186.invoke(db.clj:152)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:726)
at metabase.util$do_with_auto_retries.invoke(util.clj:718)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:730)
at metabase.util$do_with_auto_retries.invoke(util.clj:718)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:730)
at metabase.util$do_with_auto_retries.invoke(util.clj:718)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:730)
at metabase.util$do_with_auto_retries.invoke(util.clj:718)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:730)
at metabase.util$do_with_auto_retries.invoke(util.clj:718)
at metabase.util$do_with_auto_retries.invokeStatic(util.clj:730)
at metabase.util$do_with_auto_retries.invoke(util.clj:718)
at metabase.db$wait_for_migration_lock_to_be_cleared.invokeStatic(db.clj:149)
at metabase.db$wait_for_migration_lock_to_be_cleared.invoke(db.clj:145)
at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:166)
at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:155)
at metabase.db$migrate_BANG_$fn__20229.invoke(db.clj:258)
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:741)
at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:776)
at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:724)
at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
at metabase.db$migrate_BANG_.invokeStatic(db.clj:246)

**Comment by salsakran** [comment]
at the risk of being glib -- the problem and the solution are in the logs you copy/pasted

```Database has migration lock; cannot run migrations. You can force-release these locks by running java -jar metabase.jar migrate release-locks.
```

When we attempted to migrate to a new version, the database file was locked. You can unlock it by running `java -jar metabase.jar migrate release-locks.`

**Comment by mbvictoria** [comment]
Closing - solved.
