### ISSUE TITLE
databases with invalid credentials - sync should stop

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#7183]
During sync, if auth errors are generated, catch them, and mark the database so that it can't be synced. Some notification in the databases page would also help.

Here are some sample auth errors for BigQuery and GA.

```
03-22 16:50:05 INFO sync.util :: STARTING: Sync metadata for googleanalytics Database 102 'Google Analytics'
 Mar 22, 2018 4:50:05 PM com.google.api.client.auth.oauth2.Credential handleResponse
 SEVERE: unable to refresh token
 com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
 {
   "error" : "invalid_grant"
 }
        at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
        at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
        at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
        at com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:570)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:372)
        at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
        at com.google.api.client.auth.oauth2.Credential.handleResponse(Credential.java:272)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1015)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at metabase.driver.google$execute_no_auto_retry.invokeStatic(google.clj:32)
        at metabase.driver.google$execute_no_auto_retry.invoke(google.clj:28)
        at metabase.driver.google$execute$fn__45855.invoke(google.clj:46)
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:726)
        at metabase.util$do_with_auto_retries.invoke(util.clj:717)
        at metabase.driver.google$execute.invokeStatic(google.clj:45)
        at metabase.driver.google$execute.invoke(google.clj:39)
        at metabase.driver.googleanalytics$fetch_properties.invokeStatic(googleanalytics.clj:33)
        at metabase.driver.googleanalytics$fetch_properties.invoke(googleanalytics.clj:31)
        at metabase.driver.googleanalytics$properties_PLUS_profiles.invokeStatic(googleanalytics.clj:43)
        at metabase.driver.googleanalytics$properties_PLUS_profiles.invoke(googleanalytics.clj:39)
        at metabase.driver.googleanalytics$profile_ids.invokeStatic(googleanalytics.clj:50)
        at metabase.driver.googleanalytics$profile_ids.invoke(googleanalytics.clj:47)
        at metabase.driver.googleanalytics$describe_database.invokeStatic(googleanalytics.clj:55)
        at metabase.driver.googleanalytics$describe_database.invoke(googleanalytics.clj:53)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$apply.invoke(core.clj:641)
        at clojure.core$partial$fn__4759.invoke(core.clj:2515)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2461)
        at metabase.driver$fn__26394$G__26330__26401.invoke(driver.clj:51)
        at metabase.sync.fetch_metadata$fn__35055$db_metadata__35060$fn__35061.invoke(fetch_metadata.clj:13)
        at metabase.sync.fetch_metadata$fn__35055$db_metadata__35060.invoke(fetch_metadata.clj:10)
        at metabase.sync.sync_metadata.tables$fn__36185$db_metadata__36190$fn__36191.invoke(tables.clj:127)
        at metabase.sync.sync_metadata.tables$fn__36185$db_metadata__36190.invoke(tables.clj:124)
        at metabase.sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250$fn__36251.invoke(tables.clj:144)
        at metabase.sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250.invoke(tables.clj:139)
        at metabase.sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281$fn__36282.invoke(sync_metadata.clj:26)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:124)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:119)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:122)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:119)
        at clojure.core$partial$fn__4759.invoke(core.clj:2514)
        at metabase.driver$fn__26576.invokeStatic(driver.clj:235)
        at metabase.driver$fn__26576.invoke(driver.clj:235)
        at metabase.driver$fn__26511$G__26318__26520.invoke(driver.clj:51)
        at metabase.sync.util$sync_in_context$fn__33539.invoke(util.clj:115)
        at metabase.sync.util$with_db_logging_disabled$fn__33536.invoke(util.clj:106)
        at metabase.sync.util$with_start_and_finish_logging$fn__33531.invoke(util.clj:92)
        at metabase.sync.util$with_sync_events$fn__33528.invoke(util.clj:75)
        at metabase.sync.util$with_duplicate_ops_prevented$fn__33519.invoke(util.clj:54)
        at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:142)
        at metabase.sync.util$do_sync_operation.invoke(util.clj:139)
        at metabase.sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281.invoke(sync_metadata.clj:23)
        at metabase.sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280.invoke(sync_metadata.clj:20)
        at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:36)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
 
 03-22 16:50:05 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__45855@6f2792c5: Invalid Credentials
 03-22 16:50:05 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__45855@6f2792c5: 400 Bad Request
 {
   "error" : "invalid_grant"
 }
 03-22 16:50:06 ERROR sync.util :: Error running sync step: 400 Bad Request
 {
   "error" : "invalid_grant"
 }
 ("driver.google$execute_no_auto_retry.invokeStatic(google.clj:32)"
  "driver.google$execute_no_auto_retry.invoke(google.clj:28)"
  "driver.google$execute$fn__45855.invoke(google.clj:46)"
  "util$do_with_auto_retries.invokeStatic(util.clj:725)"
  "util$do_with_auto_retries.invoke(util.clj:717)"
  "util$do_with_auto_retries.invokeStatic(util.clj:729)"
  "util$do_with_auto_retries.invoke(util.clj:717)"
  "util$do_with_auto_retries.invokeStatic(util.clj:729)"
  "util$do_with_auto_retries.invoke(util.clj:717)"
  "driver.google$execute.invokeStatic(google.clj:45)"
  "driver.google$execute.invoke(google.clj:39)"
  "driver.googleanalytics$fetch_properties.invokeStatic(googleanalytics.clj:33)"
  "driver.googleanalytics$fetch_properties.invoke(googleanalytics.clj:31)"
  "driver.googleanalytics$properties_PLUS_profiles.invokeStatic(googleanalytics.clj:43)"
  "driver.googleanalytics$properties_PLUS_profiles.invoke(googleanalytics.clj:39)"
  "driver.googleanalytics$profile_ids.invokeStatic(googleanalytics.clj:50)"
  "driver.googleanalytics$profile_ids.invoke(googleanalytics.clj:47)"
  "driver.googleanalytics$describe_database.invokeStatic(googleanalytics.clj:55)"
  "driver.googleanalytics$describe_database.invoke(googleanalytics.clj:53)"
  "driver$fn__26394$G__26330__26401.invoke(driver.clj:51)"
  "sync.fetch_metadata$fn__35055$db_metadata__35060$fn__35061.invoke(fetch_metadata.clj:13)"
  "sync.fetch_metadata$fn__35055$db_metadata__35060.invoke(fetch_metadata.clj:10)"
  "sync.sync_metadata.tables$fn__36185$db_metadata__36190$fn__36191.invoke(tables.clj:127)"
  "sync.sync_metadata.tables$fn__36185$db_metadata__36190.invoke(tables.clj:124)"
  "sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250$fn__36251.invoke(tables.clj:144)"
  "sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250.invoke(tables.clj:139)"
  "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281$fn__36282.invoke(sync_metadata.clj:26)"
  "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
  "sync.util$do_with_error_handling.invoke(util.clj:119)"
  "sync.util$do_with_error_handling.invokeStatic(util.clj:122)"
  "sync.util$do_with_error_handling.invoke(util.clj:119)"
  "driver$fn__26576.invokeStatic(driver.clj:235)"
  "driver$fn__26576.invoke(driver.clj:235)"
  "driver$fn__26511$G__26318__26520.invoke(driver.clj:51)"
  "sync.util$sync_in_context$fn__33539.invoke(util.clj:115)"
  "sync.util$with_db_logging_disabled$fn__33536.invoke(util.clj:106)"
  "sync.util$with_start_and_finish_logging$fn__33531.invoke(util.clj:92)"
  "sync.util$with_sync_events$fn__33528.invoke(util.clj:75)"
  "sync.util$with_duplicate_ops_prevented$fn__33519.invoke(util.clj:54)"
  "sync.util$do_sync_operation.invokeStatic(util.clj:142)"
  "sync.util$do_sync_operation.invoke(util.clj:139)"
  "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281.invoke(sync_metadata.clj:23)"
  "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280.invoke(sync_metadata.clj:20)"
  "task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:36)")
```

```
03-22 16:50:13 INFO sync.util :: STARTING: Sync metadata for googleanalytics Database 107 'Google Analytics'
 03-22 16:50:13 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__45855@3dc678ce: User does not have sufficient permissions for this account.
 03-22 16:50:14 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__45855@3dc678ce: User does not have sufficient permissions for this account.
 03-22 16:50:14 ERROR sync.util :: Error running sync step: User does not have sufficient permissions for this account.
 ("driver.google$execute_no_auto_retry.invokeStatic(google.clj:35)"
  "driver.google$execute_no_auto_retry.invoke(google.clj:28)"
  "driver.google$execute$fn__45855.invoke(google.clj:46)"
  "util$do_with_auto_retries.invokeStatic(util.clj:725)"
  "util$do_with_auto_retries.invoke(util.clj:717)"
  "util$do_with_auto_retries.invokeStatic(util.clj:729)"
  "util$do_with_auto_retries.invoke(util.clj:717)"
  "util$do_with_auto_retries.invokeStatic(util.clj:729)"
  "util$do_with_auto_retries.invoke(util.clj:717)"
  "driver.google$execute.invokeStatic(google.clj:45)"
  "driver.google$execute.invoke(google.clj:39)"
  "driver.googleanalytics$fetch_properties.invokeStatic(googleanalytics.clj:33)"
  "driver.googleanalytics$fetch_properties.invoke(googleanalytics.clj:31)"
  "driver.googleanalytics$properties_PLUS_profiles.invokeStatic(googleanalytics.clj:43)"
  "driver.googleanalytics$properties_PLUS_profiles.invoke(googleanalytics.clj:39)"
  "driver.googleanalytics$profile_ids.invokeStatic(googleanalytics.clj:50)"
  "driver.googleanalytics$profile_ids.invoke(googleanalytics.clj:47)"
  "driver.googleanalytics$describe_database.invokeStatic(googleanalytics.clj:55)"
  "driver.googleanalytics$describe_database.invoke(googleanalytics.clj:53)"
  "driver$fn__26394$G__26330__26401.invoke(driver.clj:51)"
  "sync.fetch_metadata$fn__35055$db_metadata__35060$fn__35061.invoke(fetch_metadata.clj:13)"
  "sync.fetch_metadata$fn__35055$db_metadata__35060.invoke(fetch_metadata.clj:10)"
  "sync.sync_metadata.tables$fn__36185$db_metadata__36190$fn__36191.invoke(tables.clj:127)"
  "sync.sync_metadata.tables$fn__36185$db_metadata__36190.invoke(tables.clj:124)"
  "sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250$fn__36251.invoke(tables.clj:144)"
  "sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250.invoke(tables.clj:139)"
  "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281$fn__36282.invoke(sync_metadata.clj:26)"
  "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
  "sync.util$do_with_error_handling.invoke(util.clj:119)"
  "sync.util$do_with_error_handling.invokeStatic(util.clj:122)"
  "sync.util$do_with_error_handling.invoke(util.clj:119)"
  "driver$fn__26576.invokeStatic(driver.clj:235)"
  "driver$fn__26576.invoke(driver.clj:235)"
  "driver$fn__26511$G__26318__26520.invoke(driver.clj:51)"
  "sync.util$sync_in_context$fn__33539.invoke(util.clj:115)"
  "sync.util$with_db_logging_disabled$fn__33536.invoke(util.clj:106)"
  "sync.util$with_start_and_finish_logging$fn__33531.invoke(util.clj:92)"
  "sync.util$with_sync_events$fn__33528.invoke(util.clj:75)"
  "sync.util$with_duplicate_ops_prevented$fn__33519.invoke(util.clj:54)"
  "sync.util$do_sync_operation.invokeStatic(util.clj:142)"
  "sync.util$do_sync_operation.invoke(util.clj:139)"
  "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281.invoke(sync_metadata.clj:23)"
  "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280.invoke(sync_metadata.clj:20)"
  "task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:36)")
```

```
Mar 22, 2018 4:05:24 PM com.google.api.client.auth.oauth2.Credential handleResponse
SEVERE: unable to refresh token
com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
{
  "error" : "invalid_grant",
  "error_description" : "Account has been deleted"
}
        at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
        at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
        at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
        at com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:570)
        at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:372)
        at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
        at com.google.api.client.auth.oauth2.Credential.handleResponse(Credential.java:272)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1015)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at metabase.driver.google$execute_no_auto_retry.invokeStatic(google.clj:32)
        at metabase.driver.google$execute_no_auto_retry.invoke(google.clj:28)
        at metabase.driver.google$execute$fn__45855.invoke(google.clj:46)
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:726)
        at metabase.util$do_with_auto_retries.invoke(util.clj:717)
        at metabase.driver.google$execute.invokeStatic(google.clj:45)
        at metabase.driver.google$execute.invoke(google.clj:39)
        at metabase.driver.googleanalytics$fetch_properties.invokeStatic(googleanalytics.clj:33)
        at metabase.driver.googleanalytics$fetch_properties.invoke(googleanalytics.clj:31)
        at metabase.driver.googleanalytics$properties_PLUS_profiles.invokeStatic(googleanalytics.clj:43)
 "driver.googleanalytics$describe_database.invoke(googleanalytics.clj:53)"
        at metabase.driver.googleanalytics$properties_PLUS_profiles.invoke(googleanalytics.clj:39)
        at metabase.driver.googleanalytics$profile_ids.invokeStatic(googleanalytics.clj:50)
        at metabase.driver.googleanalytics$profile_ids.invoke(googleanalytics.clj:47)
        at metabase.driver.googleanalytics$describe_database.invokeStatic(googleanalytics.clj:55)
        at metabase.driver.googleanalytics$describe_database.invoke(googleanalytics.clj:53)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$apply.invoke(core.clj:641)
        at clojure.core$partial$fn__4759.invoke(core.clj:2515)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2461)
        at metabase.driver$fn__26394$G__26330__26401.invoke(driver.clj:51)
        at metabase.sync.fetch_metadata$fn__35055$db_metadata__35060$fn__35061.invoke(fetch_metadata.clj:13)
        at metabase.sync.fetch_metadata$fn__35055$db_metadata__35060.invoke(fetch_metadata.clj:10)
        at metabase.sync.sync_metadata.tables$fn__36185$db_metadata__36190$fn__36191.invoke(tables.clj:127)
        at metabase.sync.sync_metadata.tables$fn__36185$db_metadata__36190.invoke(tables.clj:124)
        at metabase.sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250$fn__36251.invoke(tables.clj:144)
        at metabase.sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250.invoke(tables.clj:139)
        at metabase.sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281$fn__36282.invoke(sync_metadata.clj:26)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:124)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:119)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:122)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:119)
        at clojure.core$partial$fn__4759.invoke(core.clj:2514)
        at metabase.driver$fn__26576.invokeStatic(driver.clj:235)
        at metabase.driver$fn__26576.invoke(driver.clj:235)
        at metabase.driver$fn__26511$G__26318__26520.invoke(driver.clj:51)
        at metabase.sync.util$sync_in_context$fn__33539.invoke(util.clj:115)
        at metabase.sync.util$with_db_logging_disabled$fn__33536.invoke(util.clj:106)
        at metabase.sync.util$with_start_and_finish_logging$fn__33531.invoke(util.clj:92)
        at metabase.sync.util$with_sync_events$fn__33528.invoke(util.clj:75)
        at metabase.sync.util$with_duplicate_ops_prevented$fn__33519.invoke(util.clj:54)
        at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:142)
        at metabase.sync.util$do_sync_operation.invoke(util.clj:139)
        at metabase.sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281.invoke(sync_metadata.clj:23)
        at metabase.sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280.invoke(sync_metadata.clj:20)
        at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:36)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)

03-22 16:05:24 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__45855@15361f11: Invalid Credentials
03-22 16:05:24 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__45855@15361f11: 400 Bad Request
{
  "error" : "invalid_grant",
  "error_description" : "Account has been deleted"
}
03-22 16:05:24 ERROR sync.util :: Error running sync step: 400 Bad Request
{
  "error" : "invalid_grant",
  "error_description" : "Account has been deleted"
}
("driver.google$execute_no_auto_retry.invokeStatic(google.clj:32)"
 "driver.google$execute_no_auto_retry.invoke(google.clj:28)"
 "driver.google$execute$fn__45855.invoke(google.clj:46)"
 "util$do_with_auto_retries.invokeStatic(util.clj:725)"
 "util$do_with_auto_retries.invoke(util.clj:717)"
 "util$do_with_auto_retries.invokeStatic(util.clj:729)"
 "util$do_with_auto_retries.invoke(util.clj:717)"
 "util$do_with_auto_retries.invokeStatic(util.clj:729)"
 "util$do_with_auto_retries.invoke(util.clj:717)"
 "driver.google$execute.invokeStatic(google.clj:45)"
 "driver.google$execute.invoke(google.clj:39)"
 "driver.googleanalytics$fetch_properties.invokeStatic(googleanalytics.clj:33)"
 "driver.googleanalytics$fetch_properties.invoke(googleanalytics.clj:31)"
 "driver.googleanalytics$properties_PLUS_profiles.invokeStatic(googleanalytics.clj:43)"
 "driver.googleanalytics$properties_PLUS_profiles.invoke(googleanalytics.clj:39)"
 "driver.googleanalytics$profile_ids.invokeStatic(googleanalytics.clj:50)"
 "driver.googleanalytics$profile_ids.invoke(googleanalytics.clj:47)"
 "driver.googleanalytics$describe_database.invokeStatic(googleanalytics.clj:55)"
 "driver.googleanalytics$describe_database.invoke(googleanalytics.clj:53)"
 "driver$fn__26394$G__26330__26401.invoke(driver.clj:51)"
 "sync.fetch_metadata$fn__35055$db_metadata__35060$fn__35061.invoke(fetch_metadata.clj:13)"
 "sync.fetch_metadata$fn__35055$db_metadata__35060.invoke(fetch_metadata.clj:10)"
 "sync.sync_metadata.tables$fn__36185$db_metadata__36190$fn__36191.invoke(tables.clj:127)"
 "sync.sync_metadata.tables$fn__36185$db_metadata__36190.invoke(tables.clj:124)"
 "sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250$fn__36251.invoke(tables.clj:144)"
 "sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250.invoke(tables.clj:139)"
 "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281$fn__36282.invoke(sync_metadata.clj:26)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:122)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "driver$fn__26576.invokeStatic(driver.clj:235)"
 "driver$fn__26576.invoke(driver.clj:235)"
 "driver$fn__26511$G__26318__26520.invoke(driver.clj:51)"
 "sync.util$sync_in_context$fn__33539.invoke(util.clj:115)"
 "sync.util$with_db_logging_disabled$fn__33536.invoke(util.clj:106)"
 "sync.util$with_start_and_finish_logging$fn__33531.invoke(util.clj:92)"
 "sync.util$with_sync_events$fn__33528.invoke(util.clj:75)"
 "sync.util$with_duplicate_ops_prevented$fn__33519.invoke(util.clj:54)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:142)"
 "sync.util$do_sync_operation.invoke(util.clj:139)"
 "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281.invoke(sync_metadata.clj:23)"
 "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280.invoke(sync_metadata.clj:20)"
 "task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:36)")
```

```
03-22 16:00:03 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__45855@a7c57b0: User does not have sufficient permissions for this account.
03-22 16:00:03 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__45855@a7c57b0: User does not have sufficient permissions for this account.
03-22 16:00:03 ERROR sync.util :: Error running sync step: User does not have sufficient permissions for this account.
("driver.google$execute_no_auto_retry.invokeStatic(google.clj:35)"
 "driver.google$execute_no_auto_retry.invoke(google.clj:28)"
 "driver.google$execute$fn__45855.invoke(google.clj:46)"
 "util$do_with_auto_retries.invokeStatic(util.clj:725)"
 "util$do_with_auto_retries.invoke(util.clj:717)"
 "util$do_with_auto_retries.invokeStatic(util.clj:729)"
 "util$do_with_auto_retries.invoke(util.clj:717)"
 "util$do_with_auto_retries.invokeStatic(util.clj:729)"
 "util$do_with_auto_retries.invoke(util.clj:717)"
 "driver.google$execute.invokeStatic(google.clj:45)"
 "driver.google$execute.invoke(google.clj:39)"
 "driver.googleanalytics$fetch_properties.invokeStatic(googleanalytics.clj:33)"
 "driver.googleanalytics$fetch_properties.invoke(googleanalytics.clj:31)"
 "driver.googleanalytics$properties_PLUS_profiles.invokeStatic(googleanalytics.clj:43)"
 "driver.googleanalytics$properties_PLUS_profiles.invoke(googleanalytics.clj:39)"
 "driver.googleanalytics$profile_ids.invokeStatic(googleanalytics.clj:50)"
 "driver.googleanalytics$profile_ids.invoke(googleanalytics.clj:47)"
 "driver.googleanalytics$describe_database.invokeStatic(googleanalytics.clj:55)"
 "driver.googleanalytics$describe_database.invoke(googleanalytics.clj:53)"
 "driver$fn__26394$G__26330__26401.invoke(driver.clj:51)"
 "sync.fetch_metadata$fn__35055$db_metadata__35060$fn__35061.invoke(fetch_metadata.clj:13)"
 "sync.fetch_metadata$fn__35055$db_metadata__35060.invoke(fetch_metadata.clj:10)"
 "sync.sync_metadata.tables$fn__36185$db_metadata__36190$fn__36191.invoke(tables.clj:127)"
 "sync.sync_metadata.tables$fn__36185$db_metadata__36190.invoke(tables.clj:124)"
 "sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250$fn__36251.invoke(tables.clj:144)"
 "sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250.invoke(tables.clj:139)"
 "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281$fn__36282.invoke(sync_metadata.clj:26)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:122)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "driver$fn__26576.invokeStatic(driver.clj:235)"
 "driver$fn__26576.invoke(driver.clj:235)"
 "driver$fn__26511$G__26318__26520.invoke(driver.clj:51)"
 "sync.util$sync_in_context$fn__33539.invoke(util.clj:115)"
 "sync.util$with_db_logging_disabled$fn__33536.invoke(util.clj:106)"
 "sync.util$with_start_and_finish_logging$fn__33531.invoke(util.clj:92)"
 "sync.util$with_sync_events$fn__33528.invoke(util.clj:75)"
 "sync.util$with_duplicate_ops_prevented$fn__33519.invoke(util.clj:54)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:142)"
 "sync.util$do_sync_operation.invoke(util.clj:139)"
 "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281.invoke(sync_metadata.clj:23)"
 "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280.invoke(sync_metadata.clj:20)"
 "task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:36)")
```

```
03-22 15:51:29 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__45855@3ad6ba61: Not found: Dataset a.b
03-22 15:51:29 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__45855@3ad6ba61: Not found: Dataset a.b
03-22 15:51:30 ERROR sync.util :: Error running sync step: Not found: Dataset a.b
("driver.google$execute_no_auto_retry.invokeStatic(google.clj:35)"
 "driver.google$execute_no_auto_retry.invoke(google.clj:28)"
 "driver.google$execute$fn__45855.invoke(google.clj:46)"
 "util$do_with_auto_retries.invokeStatic(util.clj:725)"
 "util$do_with_auto_retries.invoke(util.clj:717)"
 "util$do_with_auto_retries.invokeStatic(util.clj:729)"
 "util$do_with_auto_retries.invoke(util.clj:717)"
 "util$do_with_auto_retries.invokeStatic(util.clj:729)"
 "util$do_with_auto_retries.invoke(util.clj:717)"
 "driver.google$execute.invokeStatic(google.clj:45)"
 "driver.google$execute.invoke(google.clj:39)"
 "driver.bigquery$list_tables.invokeStatic(bigquery.clj:71)"
 "driver.bigquery$list_tables.invoke(bigquery.clj:59)"
 "driver.bigquery$list_tables.invokeStatic(bigquery.clj:67)"
 "driver.bigquery$list_tables.invoke(bigquery.clj:59)"
 "driver.bigquery$list_tables.invokeStatic(bigquery.clj:64)"
 "driver.bigquery$list_tables.invoke(bigquery.clj:59)"
 "driver.bigquery$describe_database$fn__45897.invoke(bigquery.clj:77)"
 "driver.bigquery$describe_database.invokeStatic(bigquery.clj:77)"
 "driver.bigquery$describe_database.invoke(bigquery.clj:74)"
 "driver$fn__26394$G__26330__26401.invoke(driver.clj:51)"
 "sync.fetch_metadata$fn__35055$db_metadata__35060$fn__35061.invoke(fetch_metadata.clj:13)"
 "sync.fetch_metadata$fn__35055$db_metadata__35060.invoke(fetch_metadata.clj:10)"
 "sync.sync_metadata.tables$fn__36185$db_metadata__36190$fn__36191.invoke(tables.clj:127)"
 "sync.sync_metadata.tables$fn__36185$db_metadata__36190.invoke(tables.clj:124)"
 "sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250$fn__36251.invoke(tables.clj:144)"
 "sync.sync_metadata.tables$fn__36245$sync_tables_BANG___36250.invoke(tables.clj:139)"
 "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281$fn__36282.invoke(sync_metadata.clj:26)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:122)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "driver$fn__26576.invokeStatic(driver.clj:235)"
 "driver$fn__26576.invoke(driver.clj:235)"
 "driver$fn__26511$G__26318__26520.invoke(driver.clj:51)"
 "sync.util$sync_in_context$fn__33539.invoke(util.clj:115)"
 "sync.util$with_db_logging_disabled$fn__33536.invoke(util.clj:106)"
 "sync.util$with_start_and_finish_logging$fn__33531.invoke(util.clj:92)"
 "sync.util$with_sync_events$fn__33528.invoke(util.clj:75)"
 "sync.util$with_duplicate_ops_prevented$fn__33519.invoke(util.clj:54)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:142)"
 "sync.util$do_sync_operation.invoke(util.clj:139)"
 "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280$fn__36281.invoke(sync_metadata.clj:23)"
 "sync.sync_metadata$fn__36275$sync_db_metadata_BANG___36280.invoke(sync_metadata.clj:20)"
 "task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:36)")
```

**Comment by dpsutton** [comment]
this might be similar to this issue: https://github.com/metabase/metabase/issues/7526

**Comment by camsaul** [comment]
@robdaemon was this fixed by the sync fixes you did recently?

**Comment by robdaemon** [comment]
@camsaul unfortunately my fix won't help this one since it's not a jdbc datasource :(

We would need to extend the fix to have driver-specific functions (mentioned in a TODO in the fix)

**Comment by thebiglabasky** [comment]
Linking to [SEM-415](https://linear.app/metabase/issue/SEM-415/deleting-a-db-will-not-stop-the-sync-process-if-its-running) since that could likely be handled the same way
