### ISSUE TITLE
java out of memory issues

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#7197]
- Your databases: bigquery
- Metabase version: 0.28.2
- Metabase internal database: MySQL

- *Repeatable steps to reproduce the issue*
Logs:
```
03-25 01:43:38 WARN metabase.query-processor :: {:status :failed,
 :class java.lang.OutOfMemoryError,
 :error "Java heap space",
 :stacktrace
 ["query_processor.middleware.parameters.sql$fn__31832$expand_query_params__31837$fn__31841.invoke(sql.clj:493)"
  "query_processor.middleware.parameters.sql$fn__31832$expand_query_params__31837.invoke(sql.clj:489)"],
 :query
 {:type "native",
  :native
  {:query
   "___SOME_BIGQUERY_BASED_QUERY___",
   :template_tags {}},
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :parameters [],
  :cache_ttl nil,
  :info
  {:executed-by 1,
   :context :question,
   :card-id 7231,
   :dashboard-id nil,
   :query-hash [44, 53, -7, 38, 63, 126, 19, -31, 47, 56, -80, -41, 48, -24, -81, -111, 67, -90, 119, 109, 19, 24, 98, 87, -2, -31, 73, -125, -25, -128, -29, -73],
   :query-type "native"}},
 :expanded-query nil}

03-25 01:43:46 WARN metabase.query-processor :: Query failure: Java heap space
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:209)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:202)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:242)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
 "query_processor$fn__32020$process_query_and_save_execution_BANG___32025$fn__32026.invoke(query_processor.clj:281)"
 "query_processor$fn__32020$process_query_and_save_execution_BANG___32025.invoke(query_processor.clj:267)"
 "api.card$run_query_for_card.invokeStatic(card.clj:607)"
 "api.card$run_query_for_card.doInvoke(card.clj:593)"
 "api.card$fn__48654$fn__48657$fn__48658.invoke(card.clj:614)"
 "api.card$fn__48654$fn__48657.invoke(card.clj:613)"
 "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
 "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
 "api.card$fn__48654.invokeStatic(card.clj:609)"
 "api.card$fn__48654.invoke(card.clj:609)"
 "middleware$enforce_authentication$fn__23041.invoke(middleware.clj:117)"
 "api.routes$fn__52336.invokeStatic(routes.clj:62)"
 "api.routes$fn__52336.invoke(routes.clj:62)"
 "routes$fn__52431$fn__52432.doInvoke(routes.clj:106)"
 "routes$fn__52431.invokeStatic(routes.clj:101)"
 "routes$fn__52431.invoke(routes.clj:101)"
 "middleware$log_api_call$fn__23140$fn__23142.invoke(middleware.clj:353)"
 "middleware$log_api_call$fn__23140.invoke(middleware.clj:352)"
 "middleware$add_security_headers$fn__23090.invoke(middleware.clj:255)"
 "core$wrap_streamed_json_response$fn__52887.invoke(core.clj:67)"
 "middleware$bind_current_user$fn__23045.invoke(middleware.clj:138)"
 "middleware$maybe_set_site_url$fn__23094.invoke(middleware.clj:279)"]
```

**Comment by key88sf** [comment]
Getting these too, ever since upgrading to 0.28.x from 0.27.x.

Also seeing Metabase become unresponsive every 4 hours or so (have to reboot beanstalk app server).

@salsakran ^  Any other reports of this?

**Comment by key88sf** [comment]
@salsakran When running a large query, even though Metabase appears to say it took too long in the UI, the query appears to still run behind the scenes. When large amounts of data are returned, the entire Metabase app is crashing and unable to recover:

```
Exception in thread "com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1" Exception in thread "MetabaseScheduler_QuartzSchedulerThread" java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3332)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
    at java.lang.StringBuilder.append(StringBuilder.java:136)
    at org.postgresql.jdbc.PgDatabaseMetaData.getTables(PgDatabaseMetaData.java:1233)
    at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnectionNoQuery(DefaultConnectionTester.java:185)
    at com.mchange.v2.c3p0.impl.DefaultConnectionTester.activeCheckConnection(DefaultConnectionTester.java:62)
    at com.mchange.v2.c3p0.AbstractConnectionTester.activeCheckConnection(AbstractConnectionTester.java:67)
    at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.testPooledConnection(C3P0PooledConnectionPool.java:368)
    at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.refurbishIdleResource(C3P0PooledConnectionPool.java:310)
    at com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask.run(BasicResourcePool.java:1999)
    at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
java.lang.OutOfMemoryError: Java heap space
03-27 10:17:46 WARN thread.QueuedThreadPool :: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@258a3143 in qtp2049672449{STARTED,8<=20<=50,i=0,q=11}
Exception in thread "qtp2049672449-73" java.lang.OutOfMemoryError: Java heap space
```

**Comment by VikramTiwari** [comment]
@salsakran Please note that even the Metabase app (0.28.2.0) is crashing because of all these memory issues. Will open a new issue with the errors I am seeing there as well.

**Comment by salsakran** [comment]
What kind of server are you running this on, how much memory is available and did you explicitly set a jvm heap size?

**Comment by VikramTiwari** [comment]
Since it's happening on my Mac app too, I don't think it's related to server capacities. Yet, on an instance that I am running it, it's a standard machine type with 1 virtual CPU and 3.75 GB of memory. Running as a Docker container without any explicit limits.

**Comment by VikramTiwari** [comment]
@camsaul Do you think you will have time to take a look into this too before 0.28.4 goes out? This is making the Mac app totally useless along with servers just crashing randomly.

**Comment by senior** [comment]
@key88sf @VikramTiwari From the stacktraces posted here, it looks to be like you are issuing a query, where the results are too large to fit into memory. I would expect that kind of failure to be consistent between the Mac App and a Metabase instance deployed on a server, it makes sense that you're seeing it in both places.

- @VikramTiwari Did this query work in previous versions of Metabase but now gives you Out of Memory Errors? If so, what version?
- What are some rough stats on this query, how many rows does it return, how many columns, are there any unusually large columns etc
- What is your max heap? If you are not setting one, how much memory does your Metabase instance have available.

It would also be useful to get a heap dump of your Metabase instance when it runs out of memory. This would help me know how the memory is being allocated and then where I can focus on reducing it. The JDK will dump the heap automatically when it runs out of memory if you include the right system properties. I wrote up some instructions on setting that in our [troubleshooting guide](https://metabase.com/docs/latest/troubleshooting-guide/running.html) under the _Diagnosing memory issues causing OutOfMemoryErrors_ heading. These files can be big. Once you have a heap dump, you can email me and I'll send you a non-public place to upload the file. My email is my first name at metabase.com.

**Comment by VikramTiwari** [comment]
@senior I think it's more than just the result sizes.
Last it was working fine is on 0.27.2. I haven't reproduced it on a single query but a dashboard. All the queries on that dashboard come from the same BigQuery database, are native and have less than 50 rows and less than 15 columns and data is time-series.

The unique thing about these queries is that they use a lot of joins and are not properly formatted. The queries are correct however and work totally fine in 0.27.2.

I am running it on an instance that is a standard machine type with 1 virtual CPU and 3.75 GB of memory. Running as a Docker container without any explicit limits.

I will take a look at generating the heap dump and sending to you by EOD today.

**Comment by key88sf** [comment]
Same here -- works fine on 0.27.2 but crash on 0.28.x

**Comment by VikramTiwari** [comment]
@senior Could you confirm that I am generating the dump properly.

I added 
```
JAVA_OPTS="$JAVA_OPTS -Xmx2g -XX:+HeapDumpOnOutOfMemoryError"
JAVA_OPTS="$JAVA_OPTS -XX:HeapDumpPath=/Users/Vikram/Documents/code/metabase/error_dump"
```
in bin/start

On running `yarn run dev` and navigating to the affected dashboard/query, I see following logs:
```
[backend] 03-29 11:38:56 DEBUG metabase.middleware :: GET /api/dashboard/1043 200 (2 s) (15 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
[backend] 03-29 11:38:56 INFO middleware.cache :: Using query processor cache backend: :db 💾
[backend] 03-29 11:38:56 INFO middleware.cache :: Using query processor cache backend: :db 💾
[backend] 03-29 11:38:56 INFO middleware.cache :: Using query processor cache backend: :db 💾
[backend] 03-29 11:38:56 INFO middleware.cache :: Using query processor cache backend: :db 💾
[backend] 03-29 11:38:56 INFO middleware.cache :: Using query processor cache backend: :db 💾
[backend] Thu Mar 29 11:38:57 PDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[backend] Thu Mar 29 11:38:57 PDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[backend] Thu Mar 29 11:38:57 PDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[backend] 03-29 11:38:58 DEBUG metabase.middleware :: GET /api/database/478/metadata 200 (2 s) (7 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
[backend] 03-29 11:38:59 WARN metabase.query-processor :: Query failure: No var named 'instance' found in namespace metabase.query-processor.middleware.cache-backend.db
[backend] ["query_processor.middleware.cache$get_backend_instance_in_namespace.invokeStatic(cache.clj:47)"
[backend]  "query_processor.middleware.cache$get_backend_instance_in_namespace.invoke(cache.clj:36)"
[backend]  "query_processor.middleware.cache$get_backend_instance_in_namespace.invokeStatic(cache.clj:43)"
[backend]  "query_processor.middleware.cache$get_backend_instance_in_namespace.invoke(cache.clj:36)"
[backend]  "query_processor.middleware.cache$set_backend_BANG_.invokeStatic(cache.clj:64)"
[backend]  "query_processor.middleware.cache$set_backend_BANG_.invoke(cache.clj:53)"
[backend]  "query_processor.middleware.cache$set_backend_BANG_.invokeStatic(cache.clj:59)"
[backend]  "query_processor.middleware.cache$set_backend_BANG_.invoke(cache.clj:53)"
[backend]  "query_processor.middleware.cache$maybe_return_cached_results.invokeStatic(cache.clj:142)"
[backend]  "query_processor.middleware.cache$maybe_return_cached_results.invoke(cache.clj:127)"
[backend]  "query_processor$qp_pipeline.invokeStatic(query_processor.clj:86)"
[backend]  "query_processor$qp_pipeline.invoke(query_processor.clj:73)"
[backend]  "query_processor$process_query.invokeStatic(query_processor.clj:130)"
[backend]  "query_processor$process_query.invoke(query_processor.clj:126)"
[backend]  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:241)"
[backend]  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:235)"
[backend]  "query_processor$eval42782$process_query_and_save_execution_BANG___42787$fn__42788.invoke(query_processor.clj:281)"
[backend]  "query_processor$eval42782$process_query_and_save_execution_BANG___42787.invoke(query_processor.clj:267)"
[backend]  "api.card$run_query_for_card.invokeStatic(card.clj:607)"
[backend]  "api.card$run_query_for_card.doInvoke(card.clj:593)"
[backend]  "api.card$fn__46040$fn__46043$fn__46044.invoke(card.clj:614)"
[backend]  "api.card$fn__46040$fn__46043.invoke(card.clj:613)"
[backend]  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
[backend]  "api.common.internal$do_with_caught_api_exception
[backend] s.invoke(internal.clj:249)"
[backend]  "api.card$fn__46040.invokeStatic(card.clj:609)"
[backend]  "api.card$fn__46040.invoke(card.clj:609)"
[backend]  "middleware$enforce_authentication$fn__44351.invoke(middleware.clj:117)"
[backend]  "api.routes$fn__54467.invokeStatic(routes.clj:62)"
[backend]  "api.routes$fn__54467.invoke(routes.clj:62)"
[backend]  "routes$fn__54564$fn__54565.doInvoke(routes.clj:106)"
[backend]  "routes$fn__54564.invokeStatic(routes.clj:101)"
[backend]  "routes$fn__54564.invoke(routes.clj:101)"
[backend]  "middleware$log_api_call$fn__44464$fn__44466.invoke(middleware.clj:353)"
[backend]  "middleware$log_api_call$fn__44464.invoke(middleware.clj:352)"
[backend]  "middleware$add_security_headers$fn__44400.invoke(middleware.clj:255)"
[backend]  "core$wrap_streamed_json_response$fn__55381.invoke(core.clj:67)"
[backend]  "middleware$bind_current_user$fn__44355.invoke(middleware.clj:138)"
[backend]  "middleware$maybe_set_site_url$fn__44404.invoke(middleware.clj:279)"]
[backend] 
[backend] 03-29 11:38:59 DEBUG metabase.middleware :: POST /api/card/7216/query 200 (3 s) (6 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
[backend] 03-29 11:39:05 DEBUG metabase.middleware :: POST /api/card/7212/query 200 (9 s) (10 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
[backend] 03-29 11:39:05 DEBUG metabase.middleware :: POST /api/card/7211/query 200 (9 s) (10 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
```

Out of 9 queries that went out, only 3 show `200`. Two of those 3 questions plot properly in the UI and one gives an error message `There was a problem displaying this chart.`. Rest of them are `Still Waiting... This is usually pretty fast, but seems to be taking awhile right now.`

The system is hung up now and java is using 1.32 GB of Memory and all of the available CPU (~80-95%). Will send you dump via email as soon as it's ready.

**Comment by VikramTiwari** [comment]
Yes, I was launching on my local with `yarn run dev` which runs `lein ring server` to launch the backend. Trying again with `project.clj` based options.

**Comment by VikramTiwari** [comment]
I have been trying to crash it since to no result. It will hang-up, but not crash. My java process is using 2.34 GB of memory and full CPU, yet not crashing. I tried running syncs in the backgrounds as well by scheduling them more often, yet no crash.

The server is hung up to the point where it isn't even accepting any requests, but it wouldn't crash. Any suggestions to make it happen. Maybe setting a lower memory size. I don't wanna dirty up the test though. 

I will keep trying.

**Comment by senior** [comment]
There might be two issues here, memory and the process hanging and we can debug them separately. If you have the CPU at 100% and the process seems hung something really useful is a thread dump. It will say what each thread in the JVM is doing at that moment in time. You just need to run `jstack PID > my-thread-dump.txt` where PID is your Java process ID. You can find all of your java process ids with `jps`. Note that you probably have two process ids related to Metabase if you're launching this with Leiningen. You'll have Leiningen's process ID and Metabase's process id. Metabase's process id will be a higher number than Leiningen's. If you want to attach that thread dump here or email it to me, I could go through it and separate out the interesting parts (there tends to be a decent amount of noise in thread dumps).

The thread dump doesn't tell us how much CPU is being spent in each of the threads (or methods), just what code is being executed by each thread. It's a good first step. Depending on how that goes it might be good to screenshare with you and get some CPU sampling going with VisualVM which goes one level deeper.

**Comment by salsakran** [comment]
btw @VikramTiwari , while we needed to kick out 0.28.4 to fix embedded dashboards, we're taking this issue very seriously, and it's a blocker on 0.29 going out.

**Comment by VikramTiwari** [comment]
Thanks, guys! Trying with `jstack` now.

**Comment by VikramTiwari** [comment]
Tried for both Metabase and Leiningen's processes, no result. Tried with sudo as well.

```
$ jstack 7319 metabase_project_dump.txt
Attaching to core metabase_project_dump.txt from executable 7319, please wait...
ERROR: can't open core file
Error attaching to core file: Can't attach to the core file
sun.jvm.hotspot.debugger.DebuggerException: Can't attach to the core file
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach0(Native Method)
	at sun.jvm.hotspot.debugger.bsd.BsdDebuggerLocal.attach(BsdDebuggerLocal.java:295)
	at sun.jvm.hotspot.HotSpotAgent.attachDebugger(HotSpotAgent.java:673)
	at sun.jvm.hotspot.HotSpotAgent.setupDebuggerDarwin(HotSpotAgent.java:659)
	at sun.jvm.hotspot.HotSpotAgent.setupDebugger(HotSpotAgent.java:341)
	at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:304)
	at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:156)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:191)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
	at sun.tools.jstack.JStack.main(JStack.java:106)
```

**Comment by salsakran** [comment]
@VikramTiwari you need to use the pipe in 
`jstack 7319 > metabase_project_dump.txt` not `jstack 7319 metabase_project_dump.txt`

**Comment by VikramTiwari** [comment]
To provide an update, @senior has found the issue and a fix is in the works.

**Comment by senior** [comment]
@VikramTiwari I just opened PR #7257 that should fix this. If you have some time would be great to get confirmation that it fixes your issue.

**Comment by VikramTiwari** [comment]
@senior That worked like a charm!

@salsakran Could we push this out in 0.28.5? 0.28.x is totally unusable without it.

**Comment by drorwr** [comment]
Just ran into this on 0.29.3. Restarting fixed the problem, at least for now. 
Running Metabase using a remote Posgres database using built-in Jetty. 
One question that I don't see answered above: in production are there any JVM flags that need to be set ?
We're just following https://metabase.com/docs/latest/operations-guide/running-the-metabase-jar-file.html and running 
java -jar metabase.jar

**Comment by swatisinghi** [comment]
I am also consistently facing out of memory issue. Any help will be highly appreciated.
I have given a lot of memory (14gb) to the process. 
`java -Xms14336m -Xmx14336m -jar metabase/metabase.jar`

Stack trace
```
Exception in thread "qtp156797912-1379" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at sun.misc.IOUtils.readFully(IOUtils.java:60)
        at java.util.jar.JarFile.getBytes(JarFile.java:425)
        at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193)
        at java.util.jar.JarFile.getManifest(JarFile.java:180)
        at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:981)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
```
