### ISSUE TITLE
email failing cause it cant resolve hostname of container

### ISSUE THREAD

**Issue by mr-devop** [metabase/metabase#7258]
when using AWS fargate it looks like the java mail library tries to confirm the hostname of the container and promptly fails. this prevents us from being able to send any e-mail.

```
04-03 17:59:18 [1mWARN metabase.email[0m :: Failed to send email
java.net.UnknownHostException: f19f771fc20f: f19f771fc20f: Name does not resolve
at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
at postal.support$hostname.invokeStatic(support.clj:73)
at postal.support$hostname.invoke(support.clj:73)
at postal.support$message_id.invokeStatic(support.clj:78)
at postal.support$message_id.invoke(support.clj:76)
at postal.message$make_jmessage$fn__23212.invoke(message.clj:175)
at postal.message.proxy$javax.mail.internet.MimeMessage$ff19274a.updateMessageID(Unknown Source)
at javax.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2200)
at postal.message.proxy$javax.mail.internet.MimeMessage$ff19274a.updateHeaders(Unknown Source)
at javax.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2159)
at postal.message.proxy$javax.mail.internet.MimeMessage$ff19274a.saveChanges(Unknown Source)
at postal.message$make_jmessage.invokeStatic(message.clj:176)
at postal.message$make_jmessage.invoke(message.clj:156)
at postal.smtp$smtp_send_STAR_$fn__23246.invoke(smtp.clj:34)
at clojure.core$map$fn__4785.invoke(core.clj:2646)
at clojure.lang.LazySeq.sval(LazySeq.java:40)
at clojure.lang.LazySeq.seq(LazySeq.java:49)
at clojure.lang.RT.seq(RT.java:521)
at clojure.core$seq__4357.invokeStatic(core.clj:137)
at clojure.core$seq__4357.invoke(core.clj:137)
at postal.smtp$smtp_send_STAR_.invokeStatic(smtp.clj:35)
at postal.smtp$smtp_send_STAR_.invoke(smtp.clj:29)
at postal.smtp$smtp_send.invokeStatic(smtp.clj:58)
at postal.smtp$smtp_send.doInvoke(smtp.clj:39)
at clojure.lang.RestFn.invoke(RestFn.java:423)
at postal.core$send_message.invokeStatic(core.clj:35)
at postal.core$send_message.invoke(core.clj:29)
at metabase.email$fn__23329$send_message_or_throw_BANG___23334$fn__23338.invoke(email.clj:78)
at metabase.email$fn__23329$send_message_or_throw_BANG___23334.invoke(email.clj:69)
at metabase.email$send_message_BANG_.invokeStatic(email.clj:103)
at metabase.email$send_message_BANG_.doInvoke(email.clj:88)
at clojure.lang.RestFn.invoke(RestFn.java:619)
at metabase.api.email$fn__39674$fn__39675.invoke(email.clj:97)
at metabase.api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)
at metabase.api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)
at metabase.api.email$fn__39674.invokeStatic(email.clj:93)
at metabase.api.email$fn__39674.invoke(email.clj:93)
at compojure.core$make_route$fn__13295.invoke(core.clj:135)
at compojure.core$wrap_route_middleware$fn__13288.invoke(core.clj:122)
at compojure.core$wrap_route_info$fn__13292.invoke(core.clj:126)
at compojure.core$if_route$fn__13250.invoke(core.clj:45)
at compojure.core$if_method$fn__13240.invoke(core.clj:27)
at compojure.core$routing$fn__13302.invoke(core.clj:151)
at clojure.core$some.invokeStatic(core.clj:2592)
at clojure.core$some.invoke(core.clj:2583)
at compojure.core$routing.invokeStatic(core.clj:151)
at compojure.core$routing.doInvoke(core.clj:148)
at clojure.lang.RestFn.applyTo(RestFn.java:139)
at clojure.core$apply.invokeStatic(core.clj:648)
at clojure.core$apply.invoke(core.clj:641)
at compojure.core$routes$fn__13306.invoke(core.clj:156)
at metabase.middleware$enforce_authentication$fn__37770.invoke(middleware.clj:117)
at compojure.core$routing$fn__13302.invoke(core.clj:151)
at clojure.core$some.invokeStatic(core.clj:2592)
at clojure.core$some.invoke(core.clj:2583)
at compojure.core$routing.invokeStatic(core.clj:151)
at compojure.core$routing.doInvoke(core.clj:148)
at clojure.lang.RestFn.invoke(RestFn.java:423)
at metabase.api.routes$fn__46872.invokeStatic(routes.clj:67)
at metabase.api.routes$fn__46872.invoke(routes.clj:67)
at compojure.core$if_context$fn__13324.invoke(core.clj:220)
at compojure.core$routing$fn__13302.invoke(core.clj:151)
at clojure.core$some.invokeStatic(core.clj:2592)
at clojure.core$some.invoke(core.clj:2583)
at compojure.core$routing.invokeStatic(core.clj:151)
at compojure.core$routing.doInvoke(core.clj:148)
at clojure.lang.RestFn.applyTo(RestFn.java:139)
at clojure.core$apply.invokeStatic(core.clj:648)
at clojure.core$apply.invoke(core.clj:641)
at compojure.core$routes$fn__13306.invoke(core.clj:156)
at clojure.lang.AFn.applyToHelper(AFn.java:154)
at clojure.lang.AFn.applyTo(AFn.java:144)
at clojure.core$apply.invokeStatic(core.clj:646)
at clojure.core$apply.invoke(core.clj:641)
at metabase.routes$fn__46957$fn__46958.doInvoke(routes.clj:106)
at clojure.lang.RestFn.invoke(RestFn.java:408)
at compojure.core$routing$fn__13302.invoke(core.clj:151)
at clojure.core$some.invokeStatic(core.clj:2592)
at clojure.core$some.invoke(core.clj:2583)
at compojure.core$routing.invokeStatic(core.clj:151)
at compojure.core$routing.doInvoke(core.clj:148)
at clojure.lang.RestFn.invoke(RestFn.java:423)
at metabase.routes$fn__46957.invokeStatic(routes.clj:101)
at metabase.routes$fn__46957.invoke(routes.clj:101)
at compojure.core$if_context$fn__13324.invoke(core.clj:220)
at compojure.core$routing$fn__13302.invoke(core.clj:151)
at clojure.core$some.invokeStatic(core.clj:2592)
at clojure.core$some.invoke(core.clj:2583)
at compojure.core$routing.invokeStatic(core.clj:151)
at compojure.core$routing.doInvoke(core.clj:148)
at clojure.lang.RestFn.applyTo(RestFn.java:139)
at clojure.core$apply.invokeStatic(core.clj:648)
at clojure.core$apply.invoke(core.clj:641)
at compojure.core$routes$fn__13306.invoke(core.clj:156)
at clojure.lang.Var.invoke(Var.java:379)
at metabase.middleware$log_api_call$fn__37869$fn__37871.invoke(middleware.clj:347)
at toucan.db$_do_with_call_counting.invokeStatic(db.clj:205)
at toucan.db$_do_with_call_counting.invoke(db.clj:198)
at metabase.middleware$log_api_call$fn__37869.invoke(middleware.clj:346)
at metabase.middleware$add_security_headers$fn__37819.invoke(middleware.clj:249)
at ring.middleware.json$wrap_json_body$fn__51945.invoke(json.clj:44)
at metabase.core$wrap_streamed_json_response$fn__52142.invoke(core.clj:67)
at ring.middleware.keyword_params$wrap_keyword_params$fn__51990.invoke(keyword_params.clj:36)
at ring.middleware.params$wrap_params$fn__52038.invoke(params.clj:67)
at metabase.middleware$bind_current_user$fn__37774.invoke(middleware.clj:138)
at clojure.core$comp$fn__4727.invoke(core.clj:2460)
at clojure.core$comp$fn__4727.invoke(core.clj:2460)
at clojure.core$comp$fn__4727.invoke(core.clj:2460)
at metabase.middleware$maybe_set_site_url$fn__37823.invoke(middleware.clj:273)
at puppetlabs.i18n.core$locale_negotiator$fn__124.invoke(core.clj:357)
at ring.middleware.cookies$wrap_cookies$fn__51888.invoke(cookies.clj:175)
at ring.middleware.session$wrap_session$fn__52129.invoke(session.clj:108)
at ring.middleware.gzip$wrap_gzip$fn__51919.invoke(gzip.clj:65)
at ring.adapter.jetty$proxy_handler$fn__51765.invoke(jetty.clj:25)
at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:499)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: f19f771fc20f: Name does not resolve
at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
... 122 more
04-03 17:59:18 [1mWARN api.email[0m :: Problem connecting to mail server: f19f771fc20f: f19f771fc20f: Name does not resolve
```
pretty sure `f19f771fc20f` is the name of the container/container host running metabase in aws fargate as our actual smtp host is set to gmail.

**Comment by mmollick** [comment]
I had this same issue trying to send a test email from an EC2 instance, I tried several different ESPs before realizing the issue was with the system's [hostname](http://deploymentzone.com/2014/01/06/aws-instances-and-java-net-unknownhostexception/). Adding the instance's hostname to `/etc/hosts` should resolve this issue.

**Comment by jwitrick** [comment]
I ran into this same issue. I was finally able to implement a work around by Creating  shell script: hostsHack


    #!/usr/bin/env bash

    HOSTNAME=$(hostname)
    export old=$(echo "localhost" | sed -e 's/[]$.*[\^]/\\&/g' )
    sed -e "s/${old}/localhost $HOSTNAME/g" /etc/hosts > /etc/hosts2

    echo "Value of hostname is: $HOSTNAME"
    echo "Value of /etc/hosts before:"
    cat /etc/hosts

    cat /etc/hosts2 > /etc/hosts

    echo "Value of /etc/hosts after:"
    cat /etc/hosts

    /app/run_metabase.sh


And creating my own image (based upon the metabase container). My docker file:



    FROM metabase/metabase

    COPY hostsHack /usr/local/bin/hostsHack 
    USER root

    ENTRYPOINT ["/usr/local/bin/hostsHack"]



And now when my container starts up it adds the hostname of the running container to the /etc/hosts file on line 127.0.0.1.

**Comment by alex-benoit** [comment]
+1

**Comment by flamber** [comment]
Closing in favor of #8373, which has more more information about possible workarounds.
