### ISSUE TITLE
Returned closed issue: #6104

### ISSUE THREAD

**Issue by toddheslin** [metabase/metabase#7304]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your databases: Postgres, Google Analytics
- Metabase version: 0.28.5
- Metabase hosting environment: Tested Elastic Beanstalk and Heroku
- Metabase internal database: Postgres

---

I upgraded from 0.28.0 to 0.28.5 on AWS Elastic Beanstalk and found the app to be continually crashing. This wasn't quite obvious and I thought it was an EBS problem however when I deployed on Heroku, I found the same issue.

Specifically this one: https://github.com/metabase/metabase/issues/6104 which should have been fixed in https://github.com/metabase/metabase/pull/6818

The error I'm getting is:
```
java.lang.Exception: Not something with an ID: gaid::-9
	at metabase.util$get_id.invokeStatic(util.clj:768)
	at metabase.util$get_id.invoke(util.clj:759)
	at metabase.query_processor.middleware.expand_macros$segment_parse_filter_subclause.invokeStatic(expand_macros.clj:45)
	at metabase.query_processor.middleware.expand_macros$segment_parse_filter_subclause.invoke(expand_macros.clj:41)
	at metabase.query_processor.middleware.expand_macros$segment_parse_filter.invokeStatic(expand_macros.clj:54)
	at metabase.query_processor.middleware.expand_macros$segment_parse_filter.invoke(expand_macros.clj:47)
	at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__6750.invokeStatic(protocols.clj:136)
	at clojure.core.protocols$fn__6750.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__6736.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__6736.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6545)
	at clojure.core$mapv.invokeStatic(core.clj:6618)
	at clojure.core$mapv.invoke(core.clj:6618)
	at metabase.query_processor.middleware.expand_macros$segment_parse_filter.invokeStatic(expand_macros.clj:52)
	at metabase.query_processor.middleware.expand_macros$segment_parse_filter.invoke(expand_macros.clj:47)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$update_in.invokeStatic(core.clj:5950)
	at clojure.core$update_in.doInvoke(core.clj:5939)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:652)
	at clojure.core$update_in.invokeStatic(core.clj:5949)
	at clojure.core$update_in.doInvoke(core.clj:5939)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at metabase.query_processor.middleware.expand_macros$expand_segments.invokeStatic(expand_macros.clj:59)
	at metabase.query_processor.middleware.expand_macros$expand_segments.invoke(expand_macros.clj:56)
	at metabase.query_processor.middleware.expand_macros$expand_metrics_and_segments.invokeStatic(expand_macros.clj:152)
	at metabase.query_processor.middleware.expand_macros$expand_metrics_and_segments.invoke(expand_macros.clj:150)
	at metabase.query_processor.middleware.expand_macros$expand_macros_STAR_.invokeStatic(expand_macros.clj:160)
	at metabase.query_processor.middleware.expand_macros$expand_macros_STAR_.invoke(expand_macros.clj:157)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at metabase.models.card$mbql_permissions_path_set.invokeStatic(card.clj:174)
	at metabase.models.card$mbql_permissions_path_set.doInvoke(card.clj:137)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at metabase.models.card$query_perms_set.invokeStatic(card.clj:200)
	at metabase.models.card$query_perms_set.doInvoke(card.clj:191)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at metabase.models.card$maybe_update_read_permissions.invokeStatic(card.clj:315)
	at metabase.models.card$maybe_update_read_permissions.invoke(card.clj:302)
	at metabase.models.card$pre_update.invokeStatic(card.clj:351)
	at metabase.models.card$pre_update.invoke(card.clj:349)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at toucan.models$fn__3985$G__3904__3990.invoke(models.clj:178)
	at toucan.models$do_pre_update.invokeStatic(models.clj:330)
	at toucan.models$do_pre_update.invoke(models.clj:325)
	at toucan.db$update_BANG_.invokeStatic(db.clj:479)
	at toucan.db$update_BANG_.invoke(db.clj:462)
	at metabase.db.migrations$repopulate_card_read_permissions$fn__32982.invoke(migrations.clj:396)
	at clojure.core$run_BANG_$fn__7276.invoke(core.clj:7393)
	at clojure.core$completing$fn__6948.invoke(core.clj:6585)
	at clojure.core$map$fn__4781$fn__4782.invoke(core.clj:2633)
	at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1120)
	at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1112)
	at clojure.java.jdbc$reducible_result_set_STAR_$reify__1874.reduce(jdbc.clj:1142)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$reduce.invoke(core.clj:6527)
	at clojure.java.jdbc$query_reducer$fn__1880$fn__1883.invoke(jdbc.clj:1177)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:994)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:987)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1016)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:996)
	at clojure.java.jdbc$reducible_query$reify__1895.reduce(jdbc.clj:1272)
	at clojure.core$transduce.invokeStatic(core.clj:6600)
	at clojure.core.Eduction.reduce(core.clj:7360)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$run_BANG_.invokeStatic(core.clj:7388)
	at clojure.core$run_BANG_.invoke(core.clj:7388)
	at metabase.db.migrations$repopulate_card_read_permissions.invokeStatic(migrations.clj:394)
	at metabase.db.migrations$repopulate_card_read_permissions.invoke(migrations.clj:393)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:50)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:41)
	at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:70)
	at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:64)
	at clojure.lang.Var.invoke(Var.java:375)
	at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:390)
	at metabase.db$run_data_migrations_BANG_.invoke(db.clj:385)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:401)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:392)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:154)
	at metabase.core$init_BANG_.invoke(core.clj:133)
	at metabase.core$start_normally.invokeStatic(core.clj:258)
	at metabase.core$start_normally.invoke(core.clj:251)
	at metabase.core$_main.invokeStatic(core.clj:279)
	at metabase.core$_main.doInvoke(core.clj:274)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
04-09 23:13:25 [1mERROR metabase.core[0m :: Metabase Initialization FAILED:  Not something with an ID: gaid::-9
04-09 23:13:25 [1mINFO metabase.core[0m :: Metabase Shutting Down ...
04-09 23:13:25 [1mINFO metabase.core[0m :: Metabase Shutdown COMPLETE
```
The server subsequently shuts down. On EBS it will restart automatically and repeat this process, however on Heroku it would crash and wait, allowing me to see that this was indeed the problem.

In both cases, I'm using a snapshot of a database that was running perfectly fine on 0.28.0.

I created a fresh environment on AWS EBS using the 0.28.0 docker file and everything restored as expected. This seems to be a bug introduced in the past few patches.

**Comment by toddheslin** [comment]
Fantastic, thanks @camsaul 

Hopefully, anyone who finds this issue can know why EBS is falling over.
