### ISSUE TITLE
Error on boot after updating from v0.28.1 to v0.28.6

### ISSUE THREAD

**Issue by jonahwh** [metabase/metabase#7365]
PSQL databases, Running in AWS in EBS using provided package

After upgrading my metabase instance from v.0.28.1 to v.0.28.6, I receive this error and stack trace on boot, and Metabase fails to load.

<details>
<summary>Stack Trace</summary>

```
Apr 17 20:03:35 0a486103457a-stdouterr.log: java.lang.IllegalArgumentException: No implementation of method: :parse-value of protocol: #'metabase.query-processor.middleware.resolve/IParseValueForField found for class: metabase.query_processor.interface.FieldPlaceholder
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:560)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.query_processor.middleware.resolve$fn__27986$G__27981__27993.invoke(resolve.clj:218)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.query_processor.middleware.resolve$value_ph_resolve_field.invokeStatic(resolve.clj:276)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.query_processor.middleware.resolve$value_ph_resolve_field.invoke(resolve.clj:270)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.query_processor.middleware.resolve$fn__27894$G__27876__27901.invoke(resolve.clj:83)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.AFn.applyToHelper(AFn.java:156)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.AFn.applyTo(AFn.java:144)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$apply.invokeStatic(core.clj:646)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$apply.invoke(core.clj:641)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.util$rpartial$fn__2828.doInvoke(util.clj:463)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RestFn.invoke(RestFn.java:408)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk.invokeStatic(walk.clj:48)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invokeStatic(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invoke(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$map$fn__4785.invoke(core.clj:2644)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.sval(LazySeq.java:40)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.seq(LazySeq.java:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RT.seq(RT.java:521)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$vec.invokeStatic(core.clj:377)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk.invokeStatic(walk.clj:45)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invokeStatic(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invoke(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk$fn__7806.invoke(walk.clj:48)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6742.invokeStatic(protocols.clj:75)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6742.invoke(protocols.clj:75)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$reduce.invokeStatic(core.clj:6545)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk.invokeStatic(walk.clj:48)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invokeStatic(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invoke(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$map$fn__4785.invoke(core.clj:2644)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.sval(LazySeq.java:40)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.seq(LazySeq.java:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RT.seq(RT.java:521)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$seq__4357.invokeStatic(core.clj:137)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$reduce.invokeStatic(core.clj:6545)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$into.invokeStatic(core.clj:6610)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk.invokeStatic(walk.clj:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invokeStatic(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invoke(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$map$fn__4785.invoke(core.clj:2644)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.sval(LazySeq.java:40)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.seq(LazySeq.java:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RT.seq(RT.java:521)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$vec.invokeStatic(core.clj:377)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk.invokeStatic(walk.clj:45)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invokeStatic(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invoke(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk$fn__7806.invoke(walk.clj:48)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6742.invokeStatic(protocols.clj:75)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6742.invoke(protocols.clj:75)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$reduce.invokeStatic(core.clj:6545)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk.invokeStatic(walk.clj:48)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invokeStatic(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invoke(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$map$fn__4785.invoke(core.clj:2644)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.sval(LazySeq.java:40)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.seq(LazySeq.java:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RT.seq(RT.java:521)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$vec.invokeStatic(core.clj:377)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk.invokeStatic(walk.clj:45)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invokeStatic(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invoke(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$map$fn__4785.invoke(core.clj:2646)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.sval(LazySeq.java:40)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.seq(LazySeq.java:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.Cons.next(Cons.java:39)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RT.next(RT.java:688)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$next__4341.invokeStatic(core.clj:64)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6755.invokeStatic(protocols.clj:168)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6755.invoke(protocols.clj:124)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$reduce.invokeStatic(core.clj:6545)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$into.invokeStatic(core.clj:6610)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk.invokeStatic(walk.clj:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invokeStatic(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invoke(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$map$fn__4785.invoke(core.clj:2644)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.sval(LazySeq.java:40)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.seq(LazySeq.java:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RT.seq(RT.java:521)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazilyPersistentVector.create(LazilyPersistentVector.java:44)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$vec.invokeStatic(core.clj:377)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk.invokeStatic(walk.clj:45)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invokeStatic(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invoke(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$partial$fn__4759.invoke(core.clj:2515)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$map$fn__4785.invoke(core.clj:2646)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.sval(LazySeq.java:40)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.LazySeq.seq(LazySeq.java:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.Cons.next(Cons.java:39)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RT.next(RT.java:688)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$next__4341.invokeStatic(core.clj:64)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6755.invokeStatic(protocols.clj:168)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6755.invoke(protocols.clj:124)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$reduce.invokeStatic(core.clj:6545)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$into.invokeStatic(core.clj:6610)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$walk.invokeStatic(walk.clj:49)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invokeStatic(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.walk$postwalk.invoke(walk.clj:52)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.query_processor.middleware.resolve$resolve_fields.invokeStatic(resolve.clj:342)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.query_processor.middleware.resolve$resolve_fields.invoke(resolve.clj:325)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.query_processor.middleware.resolve$resolve.invokeStatic(resolve.clj:411)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.query_processor.middleware.resolve$resolve.invoke(resolve.clj:408)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.query_processor.middleware.resolve$resolve_middleware$fn__28069.invoke(resolve.clj:422)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.query_processor.middleware.expand$expand_middleware$fn__29769.invoke(expand.clj:601)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.models.card$mbql_permissions_path_set.invokeStatic(card.clj:174)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.models.card$mbql_permissions_path_set.doInvoke(card.clj:137)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RestFn.invoke(RestFn.java:464)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.models.card$query_perms_set.invokeStatic(card.clj:200)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.models.card$query_perms_set.doInvoke(card.clj:191)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RestFn.invoke(RestFn.java:464)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.models.card$maybe_update_read_permissions.invokeStatic(card.clj:315)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.models.card$maybe_update_read_permissions.invoke(card.clj:302)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.models.card$pre_update.invokeStatic(card.clj:351)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.models.card$pre_update.invoke(card.clj:349)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at toucan.models$fn__3985$G__3904__3990.invoke(models.clj:178)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at toucan.models$do_pre_update.invokeStatic(models.clj:330)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at toucan.models$do_pre_update.invoke(models.clj:325)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at toucan.db$update_BANG_.invokeStatic(db.clj:479)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at toucan.db$update_BANG_.invoke(db.clj:462)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.db.migrations$repopulate_card_read_permissions$fn__32984.invoke(migrations.clj:396)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$run_BANG_$fn__7276.invoke(core.clj:7393)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$completing$fn__6948.invoke(core.clj:6585)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$map$fn__4781$fn__4782.invoke(core.clj:2633)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1120)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1112)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.java.jdbc$reducible_result_set_STAR_$reify__1874.reduce(jdbc.clj:1142)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$reduce.invokeStatic(core.clj:6544)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$reduce.invoke(core.clj:6527)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.java.jdbc$query_reducer$fn__1880$fn__1883.invoke(jdbc.clj:1177)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:994)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:987)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1016)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:996)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.java.jdbc$reducible_query$reify__1895.reduce(jdbc.clj:1272)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$transduce.invokeStatic(core.clj:6600)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core.Eduction.reduce(core.clj:7360)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$reduce.invokeStatic(core.clj:6544)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$run_BANG_.invokeStatic(core.clj:7388)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.core$run_BANG_.invoke(core.clj:7388)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.db.migrations$repopulate_card_read_permissions.invokeStatic(migrations.clj:394)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.db.migrations$repopulate_card_read_permissions.invoke(migrations.clj:393)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:50)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:41)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:70)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:64)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.Var.invoke(Var.java:375)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:390)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.db$run_data_migrations_BANG_.invoke(db.clj:385)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:401)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.db$setup_db_BANG_.doInvoke(db.clj:392)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RestFn.invoke(RestFn.java:421)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.core$init_BANG_.invokeStatic(core.clj:154)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.core$init_BANG_.invoke(core.clj:133)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.core$start_normally.invokeStatic(core.clj:258)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.core$start_normally.invoke(core.clj:251)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.core$_main.invokeStatic(core.clj:279)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.core$_main.doInvoke(core.clj:274)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RestFn.invoke(RestFn.java:397)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
Apr 17 20:03:35 zen-aws-metabase 0a486103457a-stdouterr.log: 	at metabase.core.main(Unknown Source)
Apr 17 20:03:35 0a486103457a-stdouterr.log: 04-18 03:03:32 ERROR metabase.core :: Metabase Initialization FAILED:  No implementation of method: :parse-value of protocol: #'metabase.query-processor.middleware.resolve/IParseValueForField found for class: metabase.query_processor.interface.FieldPlaceholder
```

</details>

I was successfully able to revert to v.0.28.1, but it seems I am blocked from upgrading

**Comment by camsaul** [comment]
@jonahwh this is fixed by #7313 which is shipping as part of our upcoming 0.29.0 release
