### ISSUE TITLE
Issue on updating from v0.28.1 to v0.28.6

### ISSUE THREAD

**Issue by mancio-ingenuity** [metabase/metabase#7367]
- Databases: Postgres
- Metabase version: v.0.28.1
- Metabase hosting environment: Ubuntu 14.04.2 LTS, (GNU/Linux 3.13.0-24-generic x86_64); Microsoft Azure;
- Metabase internal database: Postgres

Tried upgrading my metabase instance from v.0.28.1 to v.0.28.6, I received this error shown below and Metabase fails to load. Reverted back to v.0.28.1 just to have Metabase running back again. Thoughts on how to resolve the issue so as I can already update to the latest version? Thanks!

```04-18 07:59:47 INFO metabase.util :: Loading Metabase...
04-18 08:00:06 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance.  
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
04-18 08:00:43 INFO metabase.core :: Starting Metabase in STANDALONE mode
04-18 08:00:43 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3001, :host "0.0.0.0"}

04-18 08:00:43 INFO metabase.core :: Starting Metabase version v0.28.6 (83e3c0d release-0.28.6) ...
04-18 08:00:43 INFO metabase.core :: System timezone is 'Etc/UTC' ...
04-18 08:00:48 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
04-18 08:00:48 INFO metabase.db :: Verifying postgres Database Connection ...
04-18 08:00:48 INFO metabase.db :: Verify Database Connection ...  
04-18 08:00:48 INFO metabase.db :: Running Database Migrations...
04-18 08:00:49 INFO metabase.db :: Setting up Liquibase...
04-18 08:00:49 INFO metabase.db :: Liquibase is ready.
04-18 08:00:49 INFO metabase.db :: Checking if Database has unrun migrations...
04-18 08:00:56 INFO metabase.db :: Database Migrations Current ...  
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
04-18 08:00:56 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
04-18 08:00:56 INFO db.migrations :: Running data migration 'repopulate-card-read-permissions'...
clojure.lang.ExceptionInfo: Input to aggregation does not match schema: 

	   [nil (named [(not ("Valid map" nil)) (not ("Valid map" nil))] ag-or-ags)]  

 {:type :schema.core/error, :schema [#schema.core.One{:schema Any, :optional? false, :name query} #schema.core.One{:schema (maybe (cond-pre (pred "Valid map") [(pred "Valid map")])), :optional? false, :name ag-or-ags}], :value [{:source-table 88} (nil nil)], :error [nil (named [(not ("Valid map" nil)) (not ("Valid map" nil))] ag-or-ags)]}
	at metabase.query_processor.middleware.expand$fn__29055$aggregation__29068.invoke(expand.clj:193)
	at metabase.query_processor.middleware.expand$fn__29055$aggregation__29068$fn__29088.invoke(expand.clj:218)
	at metabase.query_processor.middleware.expand$fn__29055$aggregation__29068.doInvoke(expand.clj:193)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.lang.Var.invoke(Var.java:388)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.query_processor.middleware.expand$fn__29743$expand_inner__29748$fn__29749.invoke(expand.clj:574)
	at metabase.query_processor.middleware.expand$fn__29743$expand_inner__29748.invoke(expand.clj:565)
	at clojure.core$update.invokeStatic(core.clj:5960)
	at clojure.core$update.invoke(core.clj:5952)
	at metabase.query_processor.middleware.expand$expand.invokeStatic(expand.clj:595)
	at metabase.query_processor.middleware.expand$expand.invoke(expand.clj:580)
	at metabase.query_processor.middleware.expand$expand_middleware$fn__29769.invoke(expand.clj:602)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at metabase.models.card$mbql_permissions_path_set.invokeStatic(card.clj:174)
	at metabase.models.card$mbql_permissions_path_set.doInvoke(card.clj:137)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at metabase.models.card$query_perms_set.invokeStatic(card.clj:200)
	at metabase.models.card$query_perms_set.doInvoke(card.clj:191)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at metabase.models.card$maybe_update_read_permissions.invokeStatic(card.clj:315)
	at metabase.models.card$maybe_update_read_permissions.invoke(card.clj:302)
	at metabase.models.card$pre_update.invokeStatic(card.clj:351)
	at metabase.models.card$pre_update.invoke(card.clj:349)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at toucan.models$fn__3985$G__3904__3990.invoke(models.clj:178)
	at toucan.models$do_pre_update.invokeStatic(models.clj:330)
	at toucan.models$do_pre_update.invoke(models.clj:325)
	at toucan.db$update_BANG_.invokeStatic(db.clj:479)
	at toucan.db$update_BANG_.invoke(db.clj:462)
	at metabase.db.migrations$repopulate_card_read_permissions$fn__32984.invoke(migrations.clj:396)
	at clojure.core$run_BANG_$fn__7276.invoke(core.clj:7393)
	at clojure.core$completing$fn__6948.invoke(core.clj:6585)
	at clojure.core$map$fn__4781$fn__4782.invoke(core.clj:2633)
	at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1120)
	at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1112)
	at clojure.java.jdbc$reducible_result_set_STAR_$reify__1874.reduce(jdbc.clj:1142)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$reduce.invoke(core.clj:6527)
	at clojure.java.jdbc$query_reducer$fn__1880$fn__1883.invoke(jdbc.clj:1177)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:994)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:987)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1016)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:996)
	at clojure.java.jdbc$reducible_query$reify__1895.reduce(jdbc.clj:1272)
	at clojure.core$transduce.invokeStatic(core.clj:6600)
	at clojure.core.Eduction.reduce(core.clj:7360)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$run_BANG_.invokeStatic(core.clj:7388)
	at clojure.core$run_BANG_.invoke(core.clj:7388)
	at metabase.db.migrations$repopulate_card_read_permissions.invokeStatic(migrations.clj:394)
	at metabase.db.migrations$repopulate_card_read_permissions.invoke(migrations.clj:393)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:50)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:41)
	at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:70)
	at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:64)
	at clojure.lang.Var.invoke(Var.java:375)
	at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:390)
	at metabase.db$run_data_migrations_BANG_.invoke(db.clj:385)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:401)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:392)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:154)
	at metabase.core$init_BANG_.invoke(core.clj:133)
	at metabase.core$start_normally.invokeStatic(core.clj:258)
	at metabase.core$start_normally.invoke(core.clj:251)
	at metabase.core$_main.invokeStatic(core.clj:279)
	at metabase.core$_main.doInvoke(core.clj:274)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
04-18 08:00:57 ERROR metabase.core :: Metabase Initialization FAILED:  Input to aggregation does not match schema: 

	   [nil (named [(not ("Valid map" nil)) (not ("Valid map" nil))] ag-or-ags)]  


04-18 08:00:57 INFO metabase.core :: Metabase Shutting Down ...
04-18 08:00:57 INFO metabase.core :: Metabase Shutdown COMPLETE
```

**Comment by camsaul** [comment]
Fixed by #7313
