### ISSUE TITLE
Method "text" is only meant to be run on a single node

### ISSUE THREAD

**Issue by senior** [metabase/metabase#7394]
This is a common transient frontend test failure that can cause CI to fail when there is no real issue (we think).

```
 FAIL  frontend/test/public/public.integ.spec.js (12.305s)
  ● public/embedded › dashboards › as an anonymous user › should handle parameters in public Dashboards correctly

    Method “text” is only meant to be run on a single node. 0 found instead.
      
      at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1419:17)
      at ReactWrapper.text (node_modules/enzyme/build/ReactWrapper.js:706:21)
      at getValueOfCard (frontend/test/public/public.integ.spec.js:529:23)
      at getValueOfMbqlCard (frontend/test/public/public.integ.spec.js:532:78)
      at _callee11$ (frontend/test/public/public.integ.spec.js:568:26)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (frontend/test/public/public.integ.spec.js:79:4016)
      at frontend/test/public/public.integ.spec.js:79:4176
          at <anonymous>
```

**Comment by tlrobinson** [comment]
Generally this is due to a race condition causing the expected UI to not be present.

We could probably eliminate this sort of problem with some better abstractions. e.x. instead of 

```javascript
expect(app.find("whatever").text()).toEqual("foo")
```

maybe something like

```javascript
await eventually(() => expect(app.find("whatever").text()).toEqual("foo"))
```

which would run that anonymous function periodically for a few seconds, and if it's still failing after a timeout then the test fails. If it doesn't pass on the first try but does eventually we could log instead of failing.

**Comment by senior** [comment]
This has been fixed in master
