### ISSUE TITLE
Can't update Metabase to 0.28.6 : java.lang.Exception: Cannot calculate permissions due to circular references.

### ISSUE THREAD

**Issue by benjR** [metabase/metabase#7478]
Hi there,

Just tried to update metabase from 0.28.1 to latest 0.28.6 and had the critical message below.
I can't run the latest version but I can relaunch the previous one (0.28.1), any clue on what can cause this ? The message is not very clear, and I don't know where to search (permissions? browse through all questions?), is there a command I can run to tell me which questions are at fault ?

Thanks

```
Status: Downloaded newer image for metabase/metabase:latest
04-27 06:57:04 INFO metabase.util :: Loading Metabase...
04-27 06:57:11 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓 
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
04-27 06:57:21 INFO metabase.core :: Starting Metabase in STANDALONE mode
04-27 06:57:21 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000, :host "0.0.0.0"}

04-27 06:57:21 INFO metabase.core :: Starting Metabase version v0.28.6 (83e3c0d release-0.28.6) ...
04-27 06:57:21 INFO metabase.core :: System timezone is 'GMT' ...
04-27 06:57:24 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
04-27 06:57:24 INFO metabase.db :: Verifying h2 Database Connection ...
04-27 06:57:25 INFO metabase.db :: Verify Database Connection ...  ✅
04-27 06:57:25 INFO metabase.db :: Running Database Migrations...
04-27 06:57:25 INFO metabase.db :: Setting up Liquibase...
04-27 06:57:25 INFO metabase.db :: Liquibase is ready.
04-27 06:57:25 INFO metabase.db :: Checking if Database has unrun migrations...
04-27 06:57:30 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
04-27 06:57:30 INFO metabase.db :: Migration lock is cleared. Running migrations...
04-27 06:57:42 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
04-27 06:57:42 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
04-27 06:57:42 INFO db.migrations :: Running data migration 'populate-card-read-permissions'...
04-27 06:57:42 INFO db.migrations :: Not running migration `populate-card-read-permissions` as it has been replaced by a subsequent migration 
04-27 06:57:42 INFO db.migrations :: Running data migration 'repopulate-card-read-permissions'...
04-27 06:57:43 WARN middleware.expand :: The syntax for datetime-field has changed in MBQL '98. [:datetime-field <field> :as <unit>] is deprecated. Prefer [:datetime-field <field> <unit>] instead.
04-27 06:57:43 WARN middleware.expand :: You shouldn't specify an :and filter with only one subclause.
04-27 06:57:43 WARN middleware.expand :: You shouldn't specify an :and filter with only one subclause.
04-27 06:57:43 WARN middleware.expand :: You shouldn't specify an :and filter with only one subclause.
04-27 06:57:43 WARN middleware.expand :: The syntax for order-by has changed in MBQL '98. [<field> :ascending/:descending] is deprecated. Prefer [:asc/:desc <field>] instead.
04-27 06:57:43 WARN middleware.expand :: You shouldn't specify an :and filter with only one subclause.
04-27 06:57:44 WARN middleware.expand :: You shouldn't specify an :and filter with only one subclause.
04-27 06:57:44 WARN middleware.expand :: You shouldn't specify an :and filter with only one subclause.
04-27 06:57:44 WARN middleware.expand :: The syntax for datetime-field has changed in MBQL '98. [:datetime-field <field> :as <unit>] is deprecated. Prefer [:datetime-field <field> <unit>] instead.
java.lang.Exception: Cannot calculate permissions due to circular references. This means a question is either using itself as a source or one or more questions are using each other as sources.
	at metabase.models.card$mbql_permissions_path_set.invokeStatic(card.clj:166)
	at metabase.models.card$mbql_permissions_path_set.doInvoke(card.clj:137)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at metabase.models.card$query_perms_set.invokeStatic(card.clj:200)
	at metabase.models.card$query_perms_set.doInvoke(card.clj:191)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at metabase.models.card$maybe_update_read_permissions.invokeStatic(card.clj:315)
	at metabase.models.card$maybe_update_read_permissions.invoke(card.clj:302)
	at metabase.models.card$pre_update.invokeStatic(card.clj:351)
	at metabase.models.card$pre_update.invoke(card.clj:349)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at toucan.models$fn__3985$G__3904__3990.invoke(models.clj:178)
	at toucan.models$do_pre_update.invokeStatic(models.clj:330)
	at toucan.models$do_pre_update.invoke(models.clj:325)
	at toucan.db$update_BANG_.invokeStatic(db.clj:479)
	at toucan.db$update_BANG_.invoke(db.clj:462)
	at metabase.db.migrations$repopulate_card_read_permissions$fn__32984.invoke(migrations.clj:396)
	at clojure.core$run_BANG_$fn__7276.invoke(core.clj:7393)
	at clojure.core$completing$fn__6948.invoke(core.clj:6585)
	at clojure.core$map$fn__4781$fn__4782.invoke(core.clj:2633)
	at clojure.java.jdbc$init_reduce_rs.invokeStatic(jdbc.clj:1120)
	at clojure.java.jdbc$init_reduce_rs.invoke(jdbc.clj:1112)
	at clojure.java.jdbc$reducible_result_set_STAR_$reify__1874.reduce(jdbc.clj:1142)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$reduce.invoke(core.clj:6527)
	at clojure.java.jdbc$query_reducer$fn__1880$fn__1883.invoke(jdbc.clj:1177)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:994)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:987)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1016)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:996)
	at clojure.java.jdbc$reducible_query$reify__1895.reduce(jdbc.clj:1272)
	at clojure.core$transduce.invokeStatic(core.clj:6600)
	at clojure.core.Eduction.reduce(core.clj:7360)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$run_BANG_.invokeStatic(core.clj:7388)
	at clojure.core$run_BANG_.invoke(core.clj:7388)
	at metabase.db.migrations$repopulate_card_read_permissions.invokeStatic(migrations.clj:394)
	at metabase.db.migrations$repopulate_card_read_permissions.invoke(migrations.clj:393)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:50)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:41)
	at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:70)
	at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:64)
	at clojure.lang.Var.invoke(Var.java:375)
	at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:390)
	at metabase.db$run_data_migrations_BANG_.invoke(db.clj:385)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:401)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:392)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:154)
	at metabase.core$init_BANG_.invoke(core.clj:133)
	at metabase.core$start_normally.invokeStatic(core.clj:258)
	at metabase.core$start_normally.invoke(core.clj:251)
	at metabase.core$_main.invokeStatic(core.clj:279)
	at metabase.core$_main.doInvoke(core.clj:274)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
04-27 06:57:44 ERROR metabase.core :: Metabase Initialization FAILED:  Cannot calculate permissions due to circular references. This means a question is either using itself as a source or one or more questions are using each other as sources.
04-27 06:57:44 INFO metabase.core :: Metabase Shutting Down ...
04-27 06:57:44 INFO metabase.core :: Metabase Shutdown COMPLETE
```

### Bugs

- Your databases: Mysql (MariaDB)
- Metabase version: 0.28.1 to 0.28.6
- Metabase hosting environment: Docker on Ubuntu host
- Metabase internal database: Default

**Comment by benjR** [comment]
Any clue? I'm kind of stuck with 0.28.1 version for now I guess?

**Comment by camsaul** [comment]
@salsakran @benjR this was fixed by #7313 and shipped with our 0.29 release.

**Comment by benjR** [comment]
Thanks I'll give it a try right now ;)

**Comment by benjR** [comment]
Working great, thanks guys!
