### ISSUE TITLE
Transient integ test failure with embedded questions

### ISSUE THREAD

**Issue by senior** [metabase/metabase#7491]
Seen in CircleCI
```
Summary of all failing tests
 FAIL  frontend/test/public/public.integ.spec.js (20.786s)
  ● public/embedded › questions › as an anonymous user › should allow seeing an embedded question

    All these actions were not dispatched within 8000ms:
    metabase/metadata/ADD_PARAM_VALUES
    
    Dispatched actions since the last call of `waitForActions`:
    07:52:23.597 metabase/user/REFRESH_CURRENT_USER
    07:52:23.597 metabase/user/LOAD_CURRENT_USER
    07:52:23.598 metabase/settings/REFRESH_SITE_SETTINGS
    07:52:23.598 integrated-tests/BROWSER_HISTORY_PUSH
    07:52:23.642 metabase/app/SET_ERROR_PAGE
    
    Dispatched actions since the initialization of test suite:
    07:52:23.597 metabase/user/REFRESH_CURRENT_USER
    07:52:23.597 metabase/user/LOAD_CURRENT_USER
    07:52:23.598 metabase/settings/REFRESH_SITE_SETTINGS
    07:52:23.598 integrated-tests/BROWSER_HISTORY_PUSH
    07:52:23.642 metabase/app/SET_ERROR_PAGE
      
      at frontend/test/__support__/integrated_tests.js:535:233
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:475:11)
      at tryOnTimeout (timers.js:310:5)
      at Timer.listOnTimeout (timers.js:270:5)

```

**Comment by senior** [comment]
This has been fix on master
