### ISSUE TITLE
Database structure not support default percona xtradb cluster

### ISSUE THREAD

**Issue by wanghanlin** [metabase/metabase#7561]
This is not a bug, but more a feature request to support pxc (percona xtradb cluster), which is a popular mysql variant (clustering solution) that support master-master replication.

By default pxc have global mysql status pxc_strict_mode=ENFORCING to avoid potential issue during the replication, which forbid DML operations on tables without a primary key.

Unfortunately metabase.DATABASECHANGELOG table is one of them, so when startup metabase docker image with pxc, it will throw error `Percona-XtraDB-Cluster prohibits use of DML command on a table (metabase.DATABASECHANGELOG) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER`.

Although pxc use can disable strict mode by `SET pxc_strict_mode=PERMISSIVE;` but it will bring a little risk. so I'd purpose we make `ID` primary key since it wouldn't bring much problem on metabase side.

Thanks for this amazing project!

**Comment by camsaul** [comment]
That table is created automatically by [Liquibase](http://www.liquibase.org/), the library we're using for DB migrations. They actually do allow multiple migrations with the same ID, in case two different developers are adding migrations at the same time. So ID itself wouldn't work as a primary key. 

Either way, changing that Table would be more of an upstream thing for Liquibase instead of something we'd do as part of Metabase, so it could be a good idea to lobby the people behind that project for the proposed change :)

**Comment by wanghanlin** [comment]
@camsaul Thanks for your fast response.

Here is a possible workaround provided by liquibase, if we plan to add support, maybe we can check if that is helpful or not. https://liquibase.jira.com/browse/CORE-1909?focusedCommentId=25000&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25000

Also liquibase github repo don't accept issues, but there already same issue have been created on their JIRA, reference:
https://liquibase.jira.com/browse/CORE-2924
https://liquibase.jira.com/browse/CORE-2086

And based on CORE-2924 from liquibase, I believe mariadb galera cluster with `innodb_force_primary_key=1` enabled will fail too, but i'm not sure if it's by default set to `1`.

**Comment by robertoschwald** [comment]
Percona Cluster is also affected.

**Comment by wanghanlin** [comment]
@robertoschwald you posted two same link :)

**Comment by devurandom** [comment]
According to https://liquibase.jira.com/browse/CORE-2086 this was fixed in version 4.0.0. The latest release is 4.3.5, metabase uses 3.6.3. Can someone please try to upgrade the dependency for metabase and see whether the problem is resolved?

**Comment by devurandom** [comment]
> According to https://liquibase.jira.com/browse/CORE-2086 this was fixed in version 4.0.0. The latest release is 4.3.5, metabase uses 3.6.3. Can someone please try to upgrade the dependency for metabase and see whether the problem is resolved?

I created https://github.com/metabase/metabase/pull/16086 for the update to 4.3.5 (please review thoroughly, as this is my first contact with both Liquibase and the Metabase source code).

Sadly it does not resolve this issue. Contrary to what "fix versions: 4.0.0" in https://liquibase.jira.com/browse/CORE-2086 suggests the problem persists (upstream has been notified via that JIRA issue):

```
May 14, 2021 8:21:54 PM liquibase.changelog                                                                                                                                                                                                                                                                                                                                 
INFO: Reading resource: migrations/000_migrations.yaml                                                                                                                                                                                                                                                                                                                      
May 14, 2021 8:21:55 PM liquibase.changelog                                                                                                                                                                                                                                                                                                                                 
INFO: Creating database history table with name: metabase.DATABASECHANGELOG                                                                                                                                                                                                                                                                                                 
May 14, 2021 8:21:56 PM liquibase.changelog                                                                                                                                                                                                                                                                                                                                 
INFO: Creating database history table with name: metabase.DATABASECHANGELOG                                                                                                                                                                                                                                                                                                 
2021-05-14 20:21:56,617 ERROR metabase.core :: Metabase Initialization FAILED                                                                                                                                                                                                                                                                                               
liquibase.exception.DatabaseException: (conn=486973) Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting. [Failed SQL: (3750) CREATE TABLE metabase.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35) NULL, `DESCRIPTION` VARCHAR(255) NULL, COMMENTS VARCHAR(255) NULL, TAG VARCHAR(255) NULL, LIQUIBASE VARCHAR(20) NULL, CONTEXTS VARCHAR(255) NULL, LABELS VARCHAR(255) NULL, DEPLOYMENT_ID VARCHAR(10) NULL) ENGINE InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)                                                                                                                                                                                                                                                                
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)                                                                                                                                                                                                                                                                                                
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150)                                                                                                                                                                                                                                                                                               
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:134)                                                                                                                                                                                                                                                                                               
        at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:281)                                                                                                                                                                                                                                                               
        at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1878)                                                                                                                                                                                                                                                                                                    
        at liquibase.Liquibase.listLocks(Liquibase.java:1899)                                                                                                                                                                                                                                                                                                               
        at metabase.db.liquibase$migration_lock_exists_QMARK_.invokeStatic(liquibase.clj:98)                                                                                                                                                                                                                                                                                
        at metabase.db.liquibase$migration_lock_exists_QMARK_.invoke(liquibase.clj:95)                                                                                                                                                                                                                                                                                      
        at metabase.db.liquibase$release_lock_if_needed_BANG_.invokeStatic(liquibase.clj:188)                                                                                                                                                                                                                                                                               
        at metabase.db.liquibase$release_lock_if_needed_BANG_.invoke(liquibase.clj:184)                                                                                                                                                                                                                                                                                     
        at metabase.db.setup$migrate_BANG_$fn__35108$fn__35109.invoke(setup.clj:91)                                                                                                                                                                                                                                                                                         
        at metabase.db.liquibase$do_with_liquibase.invokeStatic(liquibase.clj:38)                                                                                                                                                                                                                                                                                           
        at metabase.db.liquibase$do_with_liquibase.invoke(liquibase.clj:30)                                                                                                                                                                                                                                                                                                 
        at metabase.db.setup$migrate_BANG_$fn__35108.invoke(setup.clj:63)                                                                                                                                                                                                                                                                                                   
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:807)                                                                                                                                                                                                                                                                                                
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)                                                                                                                                                                                                                                                                                                      
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:852)                                                                                                                                                                                                                                                                                                
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)                                                                                                                                                                                                                                                                                                      
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:789)                                                                                                                                                                                                                                                                                                
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:776)                                                                                                                                                                                                                                                                                                      
        at metabase.db.setup$migrate_BANG_.invokeStatic(setup.clj:54)                                                                                                                                                                                                                                                                                                       
        at metabase.db.setup$migrate_BANG_.invoke(setup.clj:40)                                                                                                                                                                                                                                                                                                             
        at metabase.db.setup$run_schema_migrations_BANG_.invokeStatic(setup.clj:119)                                                                                                                                                                                                                                                                                        
        at metabase.db.setup$run_schema_migrations_BANG_.invoke(setup.clj:115)                                                                                                                                                                                                                                                                                              
        at metabase.db.setup$setup_db_BANG_$fn__35159$fn__35160.invoke(setup.clj:143)                                                                                                                                                                                                                                                                                       
        at metabase.util$do_with_us_locale.invokeStatic(util.clj:687)                                                                                                                                                                                                                                                                                                       
        at metabase.util$do_with_us_locale.invoke(util.clj:673)                                                                                                                                                                                                                                                                                                             
        at metabase.db.setup$setup_db_BANG_$fn__35159.invoke(setup.clj:141)                                                                                                                                                                                                                                                                                                 
        at metabase.db.setup$setup_db_BANG_.invokeStatic(setup.clj:140)                                                                                                                                                                                                                                                                                                     
        at metabase.db.setup$setup_db_BANG_.invoke(setup.clj:136)                                                                                                                                                                                                                                                                                                           
        at metabase.db$setup_db_BANG_$fn__35173.invoke(db.clj:61)                                                                                                                                                                                                                                                                                                           
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:56)                                                                                                                                                                                                                                                                                                               
        at metabase.db$setup_db_BANG_.invoke(db.clj:51)
        at metabase.core$init_BANG_.invokeStatic(core.clj:95)
        at metabase.core$init_BANG_.invoke(core.clj:74)
        at metabase.core$start_normally.invokeStatic(core.clj:139)
        at metabase.core$_main.doInvoke(core.clj:166)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
Caused by: java.sql.SQLTransientConnectionException: (conn=486973) Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363)
        at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:501)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389)
        ... 43 more
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
        at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:262)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357)
        ... 45 more
Caused by: java.sql.SQLException: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1688)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1550)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1513)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:256)
        ... 46 more
```

**Comment by devurandom** [comment]
> > According to https://liquibase.jira.com/browse/CORE-2086 this was fixed in version 4.0.0. The latest release is 4.3.5, metabase uses 3.6.3. Can someone please try to upgrade the dependency for metabase and see whether the problem is resolved?
> 
> I created #16086 for the update to 4.3.5.
> 
> Sadly it does not resolve this issue. Contrary to what "fix versions: 4.0.0" in https://liquibase.jira.com/browse/CORE-2086 suggests the problem persists (upstream has been notified via that JIRA issue): [...]

I tried again using metabase 0.43.0 (which uses liquibase 4.8.0), just in case my own attempt at the upgrade was the cause for the error still happening. Sadly the error persists with that version:
```
liquibase.exception.DatabaseException: (conn=1155862) Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting. [Failed SQL: (3750) CREATE TABLE metabase.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35) NULL, `DESCRIPTION` VARCHAR(255) NULL, COMMENTS VARCHAR(255) NULL, TAG VARCHAR(255) NULL, LIQUIBASE VARCHAR(20) NULL, CONTEXTS VARCHAR(255) NULL, LABELS VARCHAR(255) NULL, DEPLOYMENT_ID VARCHAR(10) NULL) ENGINE InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;]
```
