### ISSUE TITLE
Why after making a backup from H2 DB file and moving it to another host gives exception?

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#7562]
I copied the `.db` file from a host to another host in order to move all questions and dashboards into the new host. Now unfortunately when I run the Metabase it gives the error of:

```
05-07 07:28:39 INFO metabase.db :: Verifying h2 Database Connection ...
05-07 07:28:44 ERROR metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
	at metabase.db$verify_db_connection.invokeStatic(db.clj:349)
	at metabase.db$verify_db_connection.invoke(db.clj:342)
	at metabase.db$verify_db_connection.invokeStatic(db.clj:345)
	at metabase.db$verify_db_connection.invoke(db.clj:342)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:398)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:392)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:154)
	at metabase.core$init_BANG_.invoke(core.clj:133)
	at metabase.core$start_normally.invokeStatic(core.clj:258)
	at metabase.core$start_normally.invoke(core.clj:251)
	at metabase.core$_main.invokeStatic(core.clj:279)
	at metabase.core$_main.doInvoke(core.clj:274)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
05-07 07:28:44 ERROR metabase.core :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
```

When Metabase is run without any existing DB, it gets up and running successfully.

Why `Metabase` does not have an easy procedure to export dashboards, questions?
Is there any workaround for this problem?

**Comment by kip-13** [comment]
Hi, do you can post how you start metabase and other info like the version, docker version(?).... ?

**Comment by salsakran** [comment]
That message means we can't connect to the database file. It's hard to debug in the abstract, but can be due to the database file being corrupted or just not in a directory the application can find. 

Please refer to https://www.metabase.com/docs/latest/troubleshooting-guide/application-database.html for troubleshooting info.

**Comment by alirezastack** [comment]
I did a migration from `H2` to `MySQL`. We're all OK now.
