### ISSUE TITLE
 `lein ring server` fails when setting up dev environment on macos

### ISSUE THREAD

**Issue by jeffreyyoung** [metabase/metabase#7570]
When setting up a dev environment on macos, after running `lein ring server` I see the following output:

```jeyoung-OSX:metabase jeyoung$ lein ring server
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
05-07 00:21:46 INFO metabase.util :: Loading Metabase...
05-07 00:21:54 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/jeyoung/.m2/repository/io/netty/netty-common/4.1.17.Final/netty-common-4.1.17.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
05-07 00:22:08 WARN common.internal :: We don't have a nice error message for schema: (pred clojure.core$comp/fn--4727) Consider wrapping it in `su/with-api-error-message`.
05-07 00:22:08 WARN common.internal :: We don't have a nice error message for schema: (pred clojure.core$comp/fn--4727) Consider wrapping it in `su/with-api-error-message`.
05-07 00:22:08 WARN common.internal :: We don't have a nice error message for schema: (pred clojure.core$comp/fn--4727) Consider wrapping it in `su/with-api-error-message`.
05-07 00:22:08 WARN common.internal :: We don't have a nice error message for schema: (pred clojure.core$comp/fn--4727) Consider wrapping it in `su/with-api-error-message`.
05-07 00:22:08 WARN common.internal :: We don't have a nice error message for schema: (pred clojure.core$comp/fn--4727) Consider wrapping it in `su/with-api-error-message`.
05-07 00:22:09 WARN common.internal :: We don't have a nice error message for schema: (maybe Any) Consider wrapping it in `su/with-api-error-message`.
05-07 00:31:59 INFO metabase.core :: Starting Metabase version v0.29.0-snapshot (96ab8c1 HEAD) ...
05-07 00:31:59 INFO metabase.core :: System timezone is 'America/Denver' ...
05-07 00:32:07 WARN metabase.driver :: No -init-driver function found for 'metabase.driver.sparksql'
05-07 00:32:08 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
05-07 00:32:08 INFO metabase.db :: Verifying h2 Database Connection ...
05-07 00:32:08 INFO metabase.db :: Verify Database Connection ...  ✅
05-07 00:32:08 INFO metabase.db :: Running Database Migrations...
05-07 00:32:08 INFO metabase.db :: Setting up Liquibase...
05-07 00:32:08 INFO metabase.db :: Liquibase is ready.
05-07 00:32:08 INFO metabase.db :: Checking if Database has unrun migrations...
Exception in thread "main" liquibase.exception.ChangeLogParseException: Error parsing liquibase.yaml, compiling:(/private/var/folders/76/gf_kcsds4g168ffysbkkl3bw0000gn/T/form-init4581770143518446706.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)```

**Comment by camsaul** [comment]
Hi @jeffreyyoung, what branch are you on?

**Comment by jeffreyyoung** [comment]
master

**Comment by camsaul** [comment]
try pulling the latest it looks like commit `96ab8c1` is from almost a month ago

**Comment by jeffreyyoung** [comment]
oops looks like i was on java 9 rather than java 8. I'm going to go ahead and close
