### ISSUE TITLE
Migrating from h2 file to Postgres: Command failed with exception: Table "COMPUTATION_JOB" not found

### ISSUE THREAD

**Issue by seantcanavan** [metabase/metabase#7853]
Operating system: Ubuntu 18.04
Databases: Migrating from local `.h2` to cloud `postgres` 9.6.6 hosted in RDS
Metabase version: 0.29
Hosting environment: Elastic Beanstalk w/ RDS backing

1. Export `.h2` file from previous database
2. Follow the installation and setup here: https://www.metabase.com/docs/v0.29.0/operations-guide/running-metabase-on-elastic-beanstalk.html
3. navigate to `{beanstalkurl}/setup` and configure initial email / password and database credentials
4. Follow the migration guide here: https://www.metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres
5. Received significant errors importing - ran the following to correct:

`alter table metabase_field alter column database_type drop not null;`

`TRUNCATE metabase_field CASCADE; TRUNCATE setting CASCADE; TRUNCATE core_user CASCADE; TRUNCATE metabase_database CASCADE; TRUNCATE permissions_group CASCADE;`

After getting through all the PK constraints after truncating I received 

`Command failed with exception: Table "COMPUTATION_JOB" not found; SQL statement:
SELECT * FROM computation_job [42102-194]`

**Comment by seantcanavan** [comment]
Did some more investigation. I've logged into the RDS instance and verified that the table exists:

`ebdb=> \d computation_job
                                        Table "public.computation_job"
   Column   |            Type             | Collation | Nullable |                   Default                   
------------+-----------------------------+-----------+----------+---------------------------------------------
 id         | integer                     |           | not null | nextval('computation_job_id_seq'::regclass)
 creator_id | integer                     |           |          | 
 created_at | timestamp without time zone |           | not null | 
 updated_at | timestamp without time zone |           | not null | 
 type       | character varying(254)      |           | not null | 
 status     | character varying(254)      |           | not null | 
 context    | text                        |           |          | 
 ended_at   | timestamp without time zone |           |          | 
Indexes:
    "pk_computation_job" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "fk_computation_job_ref_user_id" FOREIGN KEY (creator_id) REFERENCES core_user(id)
Referenced by:
    TABLE "computation_job_result" CONSTRAINT "fk_computation_result_ref_job_id" FOREIGN KEY (job_id) REFERENCES computation_job(id)
`

And here's the full stacktrace:

`
Tue Jun 12 11:12 AM Downloads: ./import_metabase.sh 
06-12 11:12:36 INFO metabase.util :: Loading Metabase...
06-12 11:12:38 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓 
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
06-12 11:12:42 INFO metabase.db :: Verifying postgres Database Connection ...
06-12 11:12:42 INFO metabase.db :: Verify Database Connection ...  ✅
06-12 11:12:42 INFO metabase.db :: Running Database Migrations...
06-12 11:12:43 INFO metabase.db :: Setting up Liquibase...
06-12 11:12:44 INFO metabase.db :: Liquibase is ready.
06-12 11:12:44 INFO metabase.db :: Checking if Database has unrun migrations...
06-12 11:12:46 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
Temporarily disabling DB constraints...
[OK]
Transfering 5 instances of Database....[OK]
Transfering 3 instances of User....[OK]
Transfering 17 instances of Setting....[OK]
Transfering 165 instances of Table....[OK]
Transfering 2196 instances of Field...........[OK]
Transfering 365 instances of FieldValues.....[OK]
Transfering 222 instances of Revision....[OK]
Transfering 2329 instances of ViewLog...........[OK]
Transfering 107 instances of Session....[OK]
Transfering 3 instances of Dashboard....[OK]
Transfering 61 instances of Card....[OK]
Transfering 41 instances of DashboardCard....[OK]
Transfering 285 instances of Activity....[OK]
Transfering 1 instances of Pulse....[OK]
Transfering 3 instances of PulseCard....[OK]
Transfering 1 instances of PulseChannel....[OK]
Transfering 2 instances of PulseChannelRecipient....[OK]
Transfering 5 instances of PermissionsGroup....[OK]
Transfering 6 instances of PermissionsGroupMembership....[OK]
Transfering 15 instances of Permissions....[OK]
Transfering 7 instances of PermissionsRevision....[OK]
Transfering 4 instances of Collection....[OK]
Transfering 3 instances of CollectionRevision....[OK]
org.h2.jdbc.JdbcSQLException: Table "COMPUTATION_JOB" not found; SQL statement:
SELECT * FROM computation_job [42102-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5465)
	at org.h2.command.Parser.readTableFilter(Parser.java:1259)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1934)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2083)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1928)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1746)
	at org.h2.command.Parser.parseSelect(Parser.java:1734)
	at org.h2.command.Parser.parsePrepared(Parser.java:447)
	at org.h2.command.Parser.parse(Parser.java:319)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.prepareCommand(Parser.java:256)
	at org.h2.engine.Session.prepareLocal(Session.java:564)
	at org.h2.engine.Session.prepareCommand(Session.java:505)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at clojure.java.jdbc$prepare_statement.invokeStatic(jdbc.clj:614)
	at clojure.java.jdbc$prepare_statement.invoke(jdbc.clj:561)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1008)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:996)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1090)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1047)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1063)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1047)
	at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:147)
	at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:144)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__36793.invoke(load_from_h2.clj:225)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:741)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:776)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:724)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:711)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:222)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:215)
	at clojure.lang.Var.invoke(Var.java:379)
	at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:36)
	at metabase.cmd$load_from_h2.invoke(cmd.clj:29)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at metabase.cmd$run_cmd$fn__38501.invoke(cmd.clj:132)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:132)
	at metabase.cmd$run_cmd.invoke(cmd.clj:128)
	at clojure.lang.Var.invoke(Var.java:383)
	at metabase.core$run_cmd.invokeStatic(core.clj:269)
	at metabase.core$run_cmd.invoke(core.clj:267)
	at metabase.core$_main.invokeStatic(core.clj:278)
	at metabase.core$_main.doInvoke(core.clj:274)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)
Command failed with exception: Table "COMPUTATION_JOB" not found; SQL statement:
SELECT * FROM computation_job [42102-194]
`

**Comment by sbelak** [comment]
Computation jobs were a part of infrastructure of the initial version of xrays which we retired in .29. Apparently we didn't account properly for all migration paths.

**Comment by seantcanavan** [comment]
@sbelak any ideas on a workaround? should I deploy `0.28` instead? I'm working on migrating a production database within a specified time frame so any workaround to get metabase up and running would be hugely appreciated.

**Comment by seantcanavan** [comment]
Confirming that switching out the `metabase.jar` to `0.28.6` and deploying `0.28.6` to beanstalk didn't fix the issue. Will continue working back through releases to see if that helps. I don't know what version the `.h2` file was originally exported from.

**Comment by seantcanavan** [comment]
I've successfully performed the migration to version `0.25.2`. I'm wondering if it's going to be safe to upgrade to `.0.29.3` however?

**Comment by JAC2703** [comment]
Is this the same cause as #7952?

**Comment by camsaul** [comment]
This was fixed by #7862
