### ISSUE TITLE
[BUG] PostgreSQL Error sync database timezone

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#7933]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Chrome 67.0.3396.62 (64-bits)
- Your operating system: Linux/Ubuntu
- Your databases: Postgres
- Metabase version: v0.29.3
- Metabase hosting environment: Linux/Debian
- Metabase internal database: Postgres

Debugging error I found this:

```bash
06-25 10:00:44 WARN sync-metadata.sync-timezone :: Error syncing database timezone                                     
java.lang.Exception: Unable to parse date string '2018-06-25 10:00:44.046 -03' for database engine 'postgres'          
        at metabase.driver$make_current_db_time_fn$fn__25961.invoke(driver.clj:371)                                    
        at metabase.driver$fn__25780$G__25632__25787.invoke(driver.clj:61)                                             
        at metabase.sync.sync_metadata.sync_timezone$fn__35243$sync_timezone_BANG___35248$fn__35249.invoke(sync_timezone.clj:20)                                                                                                              
        at metabase.sync.sync_metadata.sync_timezone$fn__35243$sync_timezone_BANG___35248.invoke(sync_timezone.clj:13) 
        at metabase.sync.sync_metadata$fn__35485$sync_db_metadata_BANG___35490$fn__35491$fn__35492.invoke(sync_metadata.clj:24)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:124)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:119)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:122)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:119)
        at clojure.core$partial$fn__4759.invoke(core.clj:2514)
        at metabase.driver$fn__25884.invokeStatic(driver.clj:245)
        at metabase.driver$fn__25884.invoke(driver.clj:245)
        at metabase.driver$fn__25819$G__25626__25828.invoke(driver.clj:61)
        at metabase.sync.util$sync_in_context$fn__32553.invoke(util.clj:115)
        at metabase.sync.util$with_db_logging_disabled$fn__32550.invoke(util.clj:106)
        at metabase.sync.util$with_start_and_finish_logging$fn__32545.invoke(util.clj:92)
        at metabase.sync.util$with_sync_events$fn__32542.invoke(util.clj:75)
        at metabase.sync.util$with_duplicate_ops_prevented$fn__32533.invoke(util.clj:54)
        at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:142)
        at metabase.sync.util$do_sync_operation.invoke(util.clj:139)
        at metabase.sync.sync_metadata$fn__35485$sync_db_metadata_BANG___35490$fn__35491.invoke(sync_metadata.clj:23)
        at metabase.sync.sync_metadata$fn__35485$sync_db_metadata_BANG___35490.invoke(sync_metadata.clj:20)
        at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:36)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.text.ParseException: Unparseable date: "2018-06-25 10:00:44.046 -03"
        at java.text.DateFormat.parse(DateFormat.java:366)
        at metabase.driver.ThreadSafeSimpleDateFormat.parse(driver.clj:329)
        at metabase.driver$first_successful_parse.invokeStatic(driver.clj:346)
        at metabase.driver$first_successful_parse.invoke(driver.clj:340)
        at metabase.driver$make_current_db_time_fn$fn__25961.invoke(driver.clj:367)
        ... 24 more
06-25 10:03:43 INFO sync.util :: FINISHED: Sync metadata for postgres Database 2 'dw' (3 mins)
```

**Comment by senior** [comment]
That is only a warning and won't impact the system in any way. This is a query that is issued to try and determine what timezone the database is in to store for debugging purposes. It can be safely ignored.

**Comment by thomasLeclaire** [comment]
Hello, 
still such warning occurs a lot with last versions. 
If it doesn't impact the system it should not be a warning but only a DEBUG item.
