### ISSUE TITLE
Metabase & Postgres (Instead of H2)

### ISSUE THREAD

**Issue by cwbeck** [metabase/metabase#7934]
This is causing some headaches for us. We want to connect and use SSL...

docker run -d -p 80:3000 \
  -e "MB_DB_TYPE=postgres" \
  -e "METABASE_DB_CONNECTION_URI=postgres://admin:<pass-removed>@<server-removed>.dblayer.com:<port-removed>/metabase?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory" \
  --name metabase metabase/metabase

Connecting via PSQL on the command line is fine, using the above fails with the following...

```
# docker logs metabase
06-25 13:59:47 INFO metabase.util :: Loading Metabase...
06-25 13:59:56 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓 
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
root@ip-10-0-1-145:/home/ubuntu# docker logs metabase
06-25 13:59:47 INFO metabase.util :: Loading Metabase...
06-25 13:59:56 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓 
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
06-25 14:00:08 INFO metabase.core :: Starting Metabase in STANDALONE mode
06-25 14:00:08 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000, :host "0.0.0.0"}

06-25 14:00:08 INFO metabase.core :: Starting Metabase version v0.29.3 (0de4585 release-0.29.3) ...
06-25 14:00:08 INFO metabase.core :: System timezone is 'GMT' ...
06-25 14:00:12 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
06-25 14:00:12 INFO metabase.db :: Verifying postgres Database Connection ...
Jun 25, 2018 2:00:12 PM org.postgresql.Driver connect
SEVERE: Error in url: jdbc:postgresql://:/?OpenSourceSubProtocolOverride=true
06-25 14:00:12 ERROR metabase.driver :: Failed to connect to database: java.sql.SQLException: No suitable driver found for jdbc:postgresql://:/?OpenSourceSubProtocolOverride=true
java.lang.AssertionError: Assert failed: Unable to connect to Metabase postgres DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
	at metabase.db$verify_db_connection.invokeStatic(db.clj:349)
	at metabase.db$verify_db_connection.invoke(db.clj:342)
	at metabase.db$verify_db_connection.invokeStatic(db.clj:345)
	at metabase.db$verify_db_connection.invoke(db.clj:342)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:398)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:392)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:154)
	at metabase.core$init_BANG_.invoke(core.clj:133)
	at metabase.core$start_normally.invokeStatic(core.clj:258)
	at metabase.core$start_normally.invoke(core.clj:251)
	at metabase.core$_main.invokeStatic(core.clj:279)
	at metabase.core$_main.doInvoke(core.clj:274)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
06-25 14:00:12 ERROR metabase.core :: Metabase Initialization FAILED:  Assert failed: Unable to connect to Metabase postgres DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
06-25 14:00:12 INFO metabase.core :: Metabase Shutting Down ...
06-25 14:00:12 INFO metabase.core :: Metabase Shutdown COMPLETE
```

I referenced an old issue #3296, but no luck on this one...

**Comment by cwbeck** [comment]
MB_DB_CONNECTION_URI not METABASE_DB_CONNECTION_URI
