### ISSUE TITLE
SyntaxError: frontend/src/metabase/containers/UndoListing.jsx

### ISSUE THREAD

**Issue by joebordes** [metabase/metabase#7966]
### Bug

- operating system: linux mint 18.3
- Metabase version: git d69a4050677026665e478bbd142566b0a7c916a6

Launch
```
bin/i18n/update-translations
```
and I get this error message:

```
SyntaxError: frontend/src/metabase/containers/UndoListing.jsx: Can not translate '${ capitalize(verb) } ${ count } ${ inflect(subject, count) }'
Error: Can not translate '${ capitalize(verb) } ${ count } ${ inflect(subject, count) }'
    at logAction (/space/reps/metabase/node_modules/babel-plugin-c-3po/dist/context.js:52:19)
    at C3poContext.validationFailureAction (/space/reps/metabase/node_modules/babel-plugin-c-3po/dist/context.js:188:13)
    at extractOrResolve (/space/reps/metabase/node_modules/babel-plugin-c-3po/dist/plugin.js:62:29)
    at PluginPass.<anonymous> (/space/reps/metabase/node_modules/babel-plugin-c-3po/dist/plugin.js:20:13)
    at newFn (/space/reps/metabase/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/space/reps/metabase/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/space/reps/metabase/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/space/reps/metabase/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/space/reps/metabase/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/space/reps/metabase/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/space/reps/metabase/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/space/reps/metabase/node_modules/babel-traverse/lib/index.js:114:17)
  36 |   <div>
  37 |     {count > 1
> 38 |       ? t`${capitalize(verb)} ${count} ${inflect(subject, count)}`
     |         ^
  39 |       : t`${capitalize(verb)} ${subject}`}
  40 |   </div>
  41 | );
```

**Comment by mauricio-sonegatti** [comment]
Related #7957
