### ISSUE TITLE
Unable to update to v0.30.0: UnsupportedClassVersionError: org/postgresql/util/PGobject

### ISSUE THREAD

**Issue by zaiddabaeen** [metabase/metabase#8257]
I was on v0.28.6, tried to get to v0.30.0, but it failed with the error below.

Updated to v0.29.0, then to v0.29.3 to make sure it is not migrations related. But still upgrading from v0.29.3 to v0.30.0 fails with the same error.

I remained on v0.29.3.

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/postgresql/util/PGobject : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at metabase.util__init.__init0(Unknown Source)
	at metabase.util__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.RT.loadClassForName(RT.java:2232)
	at clojure.lang.RT.load(RT.java:450)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5929)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at metabase.db$loading__6434__auto____2668.invoke(db.clj:1)
	at metabase.db__init.load(Unknown Source)
	at metabase.db__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.RT.loadClassForName(RT.java:2232)
	at clojure.lang.RT.load(RT.java:450)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5929)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:1289)
	at metabase.core$loading__6434__auto____59536.invoke(core.clj:2)
	at metabase.core__init.load(Unknown Source)
	at metabase.core__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at clojure.lang.RT.classForName(RT.java:2204)
	at clojure.lang.RT.classForName(RT.java:2213)
	at clojure.lang.RT.loadClassForName(RT.java:2232)
	at clojure.lang.RT.load(RT.java:450)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:381)
	at clojure.lang.Util.loadWithClass(Util.java:250)
	at metabase.core.<clinit>(Unknown Source)

```

- Your operating system: Ubuntu 16.4 LTS
- Your databases: MySQL - Aurora
- Metabase version: 0.29.3
- Metabase hosting environment: Ubuntu - JAR
- Metabase internal database: MySQL - MySQL

**Comment by eddsmith8** [comment]
I have the same issue using the metabase-deploy repository with Heroku.

- Your databases: Postgres V9.6.8
- Metabase version: 0.29.3
- Metabase hosting environment: Heroku cedar-14
- Metabase internal database: Postgres V9.6.6

Same exception as above

**Comment by charleswcole** [comment]
Need 1.8 for the new version

**Comment by zaiddabaeen** [comment]
The deprecated version

DEPRECATION WARNING: You are currently running JDK '1.7.0_131'.

**Comment by senior** [comment]
@charleswcole Correct, as of 0.30.0. We show an error message on startup if we detect JDK 1.7 or older. Not sure if the `UnsupportedClassVersionError` is preventing our error message from showing or maybe it was just earlier in the log.

**Comment by zaiddabaeen** [comment]
Got it, thanks!

**Comment by zaiddabaeen** [comment]
Yes it is preventing the message from showing. The error is the only thing that shows.

**Comment by zaiddabaeen** [comment]
I can confirm that updating to JDK 1.8 has solved the issue.

**Comment by douglaspetrin** [comment]
I have  Metabase 0.29.3 and it's saying is the latest version on the Updates session. Which is false. Alright.

I tried to deploy MB via Heroku and what I have is:

> -----> Clojure (Leiningen 2) app detected
> 
> -----> **Installing JDK 1.8... done**
> 
> -----> Installing Leiningen
> 
>        Downloading: leiningen-2.7.1-standalone.jar
> 
>        Writing: lein script
> 
> -----> Building with Leiningen
> 
>        Found bin/build; running it instead of default lein invocation.
> 
>        Running: bin/build
> 
>        fatal: Not a git repository (or any parent up to mount point /tmp)
> 
>        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> 
>        fatal: Not a git repository (or any parent up to mount point /tmp)
> 
>        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> 
>        fatal: Not a git repository (or any parent up to mount point /tmp)
> 
>        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> 
>        Tagging uberjar with version 'v0.30.1   '...
> 
>        Running './bin/i18n/build-translation-resources' to build translation resources...
> 
>        internal/modules/cjs/loader.js:583
> 
>            throw err;
> 
>            ^
> 
>        
> 
>        Error: Cannot find module 'gettext-parser'
> 
>            at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
> 
>            at Function.Module._load (internal/modules/cjs/loader.js:507:25)
> 
>            at Module.require (internal/modules/cjs/loader.js:637:17)
> 
>            at require (internal/modules/cjs/helpers.js:20:18)
> 
>            at Object.<anonymous> (/tmp/build_88a4b2ed06b06276244b628ba7c7d097/bin/i18n/build-translation-frontend-resource:8:17)
> 
>            at Module._compile (internal/modules/cjs/loader.js:689:30)
> 
>            at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> 
>            at Module.load (internal/modules/cjs/loader.js:599:32)
> 
>            at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> 
>            at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> 
>        Building translation resources failed, please install 'gettext', or build without translations by running './bin/build no-translations'.
> 
>  !     **Failed to build.**
> 
>  !     Push rejected, failed to compile Clojure (Leiningen 2) app.
> 
>  !     Push failed

as @zaiddabaeen had success with updating JDK to 1.8, it seems for me is not the solution. 

I didnt want to create a new issue, but it seems it's. 

Anyone having the same problem?

**Comment by zaiddabaeen** [comment]
I think you should create another ticket, your problem is not related to mine.
