### ISSUE TITLE
java.lang.NumberFormatException: For input string: "9-internal"

### ISSUE THREAD

**Issue by noctorus** [metabase/metabase#8282]
Hi everyone.
I try update my metabase.jar today from version 0.29.2 to 0.30 but I received this error message:

> ubuntu:~/metabase$ sudo java -jar metabase.jar
08-10 11:48:36 INFO metabase.util :: Loading Metabase...
08-10 11:48:43 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. ? 
For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
08-10 11:48:58 INFO metabase.core :: Starting Metabase in STANDALONE mode
08-10 11:48:58 INFO metabase.core :: Launching Embedded Jetty Webserver with config: 
 {:port 3000}
08-10 11:48:58 INFO metabase.core :: Starting Metabase version v0.30.0 (04836dc release-0.30.0) ...
08-10 11:48:58 INFO metabase.core :: System timezone is 'Etc/UTC' ...
08-10 11:48:58 ERROR metabase.core :: Metabase Initialization FAILED
java.lang.NumberFormatException: For input string: "9-internal"
 at java.lang.NumberFormatException.forInputString(java.base@9-internal/NumberFormatException.java:65)
 at java.lang.Integer.parseInt(java.base@9-internal/Integer.java:695)
 at java.lang.Integer.parseInt(java.base@9-internal/Integer.java:813)
 at metabase.util$is_java_9_or_higher_QMARK_.invokeStatic(util.clj:553)
 at metabase.util$is_java_9_or_higher_QMARK_.invoke(util.clj:550)
 at metabase.plugins$load_plugins_BANG_.invokeStatic(plugins.clj:77)
 at metabase.plugins$load_plugins_BANG_.invoke(plugins.clj:73)
 at metabase.core$init_BANG_.invokeStatic(core.clj:150)
 at metabase.core$init_BANG_.invoke(core.clj:138)
 at metabase.core$start_normally.invokeStatic(core.clj:245)
 at metabase.core$start_normally.invoke(core.clj:239)
 at metabase.core$_main.invokeStatic(core.clj:265)
 at metabase.core$_main.doInvoke(core.clj:260)
 at clojure.lang.RestFn.invoke(RestFn.java:397)
 at clojure.lang.AFn.applyToHelper(AFn.java:152)
 at clojure.lang.RestFn.applyTo(RestFn.java:132)
 at metabase.core.main(Unknown Source)
08-10 11:48:58 INFO metabase.core :: Metabase Shutting Down ...
08-10 11:48:58 INFO metabase.core :: Metabase Shutdown COMPLETE

I will back to last version e works fine ...

**Comment by noctorus** [comment]
My java version is:
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

**Comment by camsaul** [comment]
Hey everyone,I fixed this in #8305 which we'll ship as part of our 0.30.1 bugfix release in the next few days.
