### ISSUE TITLE
java.lang.IllegalStateException: File corrupted - Cannot save some of native questions

### ISSUE THREAD

**Issue by lwqcz** [metabase/metabase#8331]
- Your browser and the version: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.52
- Your operating system: Win10
- Your databases: Postgres 9.5.12
- Metabase version: 0.30.0
- Metabase hosting environment: Linux/Ubuntu *.jar file
- Metabase internal database: H2

- Custom Questions are working as well as simple native questions.

- Question saving dialog:

![metabase_save_question_error](https://user-images.githubusercontent.com/39486334/44148707-b34b6fae-a099-11e8-9ec6-03b4e9c7e958.jpg)

- LOG output:

```
08-15 14:38:31 ERROR metabase.middleware :: POST /api/card 500 (2 s) (4 DB calls).
{:message
 "General error: \"java.lang.IllegalStateException: File corrupted in chunk 31169, expected page length 4..192, got 0 [1.4.197/6]\"; SQL statement:\nINSERT INTO \"REPORT_CARD\" (\"DESCRIPTION\", \"COLLECTION_POSITION\", \"TABLE_ID\", \"RESULT_METADATA\", \"DATABASE_ID\", \"COLLECTION_ID\", \"QUERY_TYPE\", \"NAME\", \"CREATOR_ID\", \"UPDATED_AT\", \"DATASET_QUERY\", \"DISPLAY\", \"VISUALIZATION_SETTINGS\", \"CREATED_AT\") VALUES (?, NULL, NULL, NULL, 2, 34, ?, ?, 7, ?, ?, ?, ?, ?) [50000-197]",
 :type org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["api.card$fn__45900$fn__45903.invoke(card.clj:242)"
  "api.card$fn__45900.invokeStatic(card.clj:238)"
  "api.card$fn__45900.invoke(card.clj:210)"
  "middleware$enforce_authentication$fn__55104.invoke(middleware.clj:116)"
  "api.routes$fn__55244.invokeStatic(routes.clj:61)"
  "api.routes$fn__55244.invoke(routes.clj:61)"
  "routes$fn__55331$fn__55332.doInvoke(routes.clj:108)"
  "routes$fn__55331.invokeStatic(routes.clj:103)"
  "routes$fn__55331.invoke(routes.clj:103)"
  "middleware$catch_api_exceptions$fn__55233.invoke(middleware.clj:424)"
  "middleware$log_api_call$fn__55210$fn__55212.invoke(middleware.clj:351)"
  "middleware$log_api_call$fn__55210.invoke(middleware.clj:350)"
  "middleware$add_security_headers$fn__55158.invoke(middleware.clj:253)"
  "core$wrap_streamed_json_response$fn__60519.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__55109.invoke(middleware.clj:140)"
  "middleware$maybe_set_site_url$fn__55162.invoke(middleware.clj:277)"],
 :sql-exception-chain
 ["JdbcSQLException:"
  "Message: General error: \"java.lang.IllegalStateException: File corrupted in chunk 31169, expected page length 4..192, got 0 [1.4.197/6]\"; SQL statement:"
  "INSERT INTO \"REPORT_CARD\" (\"DESCRIPTION\", \"COLLECTION_POSITION\", \"TABLE_ID\", \"RESULT_METADATA\", \"DATABASE_ID\", \"COLLECTION_ID\", \"QUERY_TYPE\", \"NAME\", \"CREATOR_ID\", \"UPDATED_AT\", \"DATASET_QUERY\", \"DISPLAY\", \"VISUALIZATION_SETTINGS\", \"CREATED_AT\") VALUES (?, NULL, NULL, NULL, 2, 34, ?, ?, 7, ?, ?, ?, ?, ?) [50000-197]"
  "SQLState: HY000"
  "Error Code: 50000"]}.
```
- When I tried to save it again without diacritics:

```
08-15 14:53:01 ERROR metabase.middleware :: POST /api/card 500 (1 s) (4 DB calls).
{:message
 "The object is already closed; SQL statement:\nINSERT INTO \"REPORT_CARD\" (\"DESCRIPTION\", \"COLLECTION_POSITION\", \"TABLE_ID\", \"RESULT_METADATA\", \"DATABASE_ID\", \"COLLECTION_ID\", \"QUERY_TYPE\", \"NAME\", \"CREATOR_ID\", \"UPDATED_AT\", \"DATASET_QUERY\", \"DISPLAY\", \"VISUALIZATION_SETTINGS\", \"CREATED_AT\") VALUES (?, NULL, NULL, NULL, 2, 34, ?, ?, 7, ?, ?, ?, ?, ?) [90007-197]",
 :type org.h2.jdbc.JdbcSQLException,
 :stacktrace
 ["api.card$fn__45900$fn__45903.invoke(card.clj:242)"
  "api.card$fn__45900.invokeStatic(card.clj:238)"
  "api.card$fn__45900.invoke(card.clj:210)"
  "middleware$enforce_authentication$fn__55104.invoke(middleware.clj:116)"
  "api.routes$fn__55244.invokeStatic(routes.clj:61)"
  "api.routes$fn__55244.invoke(routes.clj:61)"
  "routes$fn__55331$fn__55332.doInvoke(routes.clj:108)"
  "routes$fn__55331.invokeStatic(routes.clj:103)"
  "routes$fn__55331.invoke(routes.clj:103)"
  "middleware$catch_api_exceptions$fn__55233.invoke(middleware.clj:424)"
  "middleware$log_api_call$fn__55210$fn__55212.invoke(middleware.clj:351)"
  "middleware$log_api_call$fn__55210.invoke(middleware.clj:350)"
  "middleware$add_security_headers$fn__55158.invoke(middleware.clj:253)"
  "core$wrap_streamed_json_response$fn__60519.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__55109.invoke(middleware.clj:140)"
  "middleware$maybe_set_site_url$fn__55162.invoke(middleware.clj:277)"],
 :sql-exception-chain
 ["JdbcSQLException:"
  "Message: The object is already closed; SQL statement:"
  "INSERT INTO \"REPORT_CARD\" (\"DESCRIPTION\", \"COLLECTION_POSITION\", \"TABLE_ID\", \"RESULT_METADATA\", \"DATABASE_ID\", \"COLLECTION_ID\", \"QUERY_TYPE\", \"NAME\", \"CREATOR_ID\", \"UPDATED_AT\", \"DATASET_QUERY\", \"DISPLAY\", \"VISUALIZATION_SETTINGS\", \"CREATED_AT\") VALUES (?, NULL, NULL, NULL, 2, 34, ?, ?, 7, ?, ?, ?, ?, ?) [90007-197]"
  "SQLState: 90007"
  "Error Code: 90007"]}
```

_**Can you please analyze-out what I've screwed up?**_ 🤕 

**EDIT**: I think that this issue is not my fault as the logs says:
```
"INSERT INTO \"REPORT_CARD\" (\"DESCRIPTION\", \"COLLECTION_POSITION\", \"TABLE_ID\", \"RESULT_METADATA\", \"DATABASE_ID\", \"COLLECTION_ID\", \"QUERY_TYPE\", \"NAME\", \"CREATOR_ID\", \"UPDATED_AT\", \"DATASET_QUERY\", \"DISPLAY\", \"VISUALIZATION_SETTINGS\", \"CREATED_AT\") VALUES (?, NULL, NULL, NULL, 2, 34, ?, ?, 7, ?, ?, ?, ?, ?) [90007-197]"
```
... so there are a lot of missing values including important ones like DATASET_QUERY, NAME, QUERY_TYPE or TABLE_ID. Or am I wrong with my assumption and these values are not important for native question?

**EDIT2**: I am quite in hurry so I try workaround like "save a simple native SQL question and then update code for complex one". But no luck as seen below:

![metabase_save_question_update_error](https://user-images.githubusercontent.com/39486334/44150877-25cc8ca0-a0a1-11e8-85ef-e517f3300e1e.jpg)

**Comment by lwqcz** [comment]
Unfortunately I've just found where problem is (anyway I am not aware way it happends...) - H2 database file seems to be corrupted.

As this Metabase instance is just for testing purposes and there weren't nearly no valuable content, this issue will not present any significant problem, but I'll try to recover it as documentation says.

Now I'm waiting for some response from @salsakran @tlrobinson @camsaul or anyone other - otherwise I will do recovery procedure tommorow.

But anyway - what I'm interested about is how this corruption happend and how to prevent it? Beside the backup strategy for metabase.db file which I will start right away (after it'll be running OK again).

**Thanks a lot for any input!**

```
08-15 15:52:14 INFO metabase.core :: Starting Metabase version v0.30.0 (04836dc release-0.30.0) ...
08-15 15:52:14 INFO metabase.core :: System timezone is 'Europe/Prague' ...
2018-08-15T15:52:14.970+0200: [GC (Allocation Failure) 2018-08-15T15:52:14.970+0200: [DefNew: 147299K->17215K(155520K), 0.0908113 secs] 287633K->191454K(500932K), 0.0910483 secs] [Times: user=0.09 sys=0.00, real=0.09 secs] 
2018-08-15T15:52:15.494+0200: [GC (Allocation Failure) 2018-08-15T15:52:15.494+0200: [DefNew: 155519K->10979K(155520K), 0.0376187 secs] 329758K->191094K(500932K), 0.0378362 secs] [Times: user=0.03 sys=0.00, real=0.04 secs] 
2018-08-15T15:52:17.062+0200: [GC (Allocation Failure) 2018-08-15T15:52:17.062+0200: [DefNew: 149283K->17215K(155520K), 0.0470087 secs] 329398K->220011K(500932K), 0.0472549 secs] [Times: user=0.04 sys=0.01, real=0.05 secs] 
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
08-15 15:52:17 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
08-15 15:52:17 INFO metabase.db :: Verifying h2 Database Connection ...
08-15 15:52:18 ERROR metabase.driver :: Failed to connect to database: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: File corrupted in chunk 31169, expected page length 4..192, got 16777216 [1.4.197/6]" [50000-197]
08-15 15:52:18 ERROR metabase.core :: Metabase Initialization FAILED
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
        at metabase.db$verify_db_connection.invokeStatic(db.clj:365)
        at metabase.db$verify_db_connection.invoke(db.clj:358)
        at metabase.db$verify_db_connection.invokeStatic(db.clj:361)
        at metabase.db$verify_db_connection.invoke(db.clj:358)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:427)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:161)
        at metabase.core$init_BANG_.invoke(core.clj:138)
        at metabase.core$start_normally.invokeStatic(core.clj:245)
        at metabase.core$start_normally.invoke(core.clj:239)
        at metabase.core$_main.invokeStatic(core.clj:265)
        at metabase.core$_main.doInvoke(core.clj:260)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
08-15 15:52:18 INFO metabase.core :: Metabase Shutting Down ...
08-15 15:52:18 INFO metabase.core :: Metabase Shutdown COMPLETE
Heap
 def new generation   total 155520K, used 73068K [0x00000000c0000000, 0x00000000ca8b0000, 0x00000000d5550000)
  eden space 138304K,  40% used [0x00000000c0000000, 0x00000000c368b020, 0x00000000c8710000)
  from space 17216K,  99% used [0x00000000c97e0000, 0x00000000ca8afff0, 0x00000000ca8b0000)
  to   space 17216K,   0% used [0x00000000c8710000, 0x00000000c8710000, 0x00000000c97e0000)
 tenured generation   total 345412K, used 202795K [0x00000000d5550000, 0x00000000ea6a1000, 0x0000000100000000)
   the space 345412K,  58% used [0x00000000d5550000, 0x00000000e1b5af30, 0x00000000e1b5b000, 0x00000000ea6a1000)
 Metaspace       used 99588K, capacity 100090K, committed 100352K, reserved 1128448K
  class space    used 21248K, capacity 21494K, committed 21504K, reserved 1048576K
```

**Comment by salsakran** [comment]
@lwqcz If you're using H2, you should be really careful regarding how stable your filesystem is. While it doesn't corrupt all that often, we do hear about it happening every now and then.

Very wise to keep backups. In general, we recommend people use MySQL or PostgreSQL as a backing application database if at all possible. 

Closing as there's not much we can do to help uncorrupt that DB.
