### ISSUE TITLE
Build error: Exception in thread "BasicRepositoryConnector-dl.bintray.com-2-1" 

### ISSUE THREAD

**Issue by ghost** [metabase/metabase#8403]
------
Hello! I'm not sure is it trouble with me or code in metabase, but i can't build it. I'm Russian speaker so I decided to have a build with ru.po exported from POEditor (i contributed there a bit). I got environment set, installed latest Oracle Java 8 SE, yarn, leiningen (apt-get install leiningen), npm 8. Also i had to install OpenJDK8 because lein pointed me that there is no openjdk JVM (obviously), but i didn't found a way to configure it to work with Oracle Java. I tried to search an issue about this, but it seems like there is no such. 
-----

- OS: Ubuntu Server 18.04
- Metabase version: 0.30.1
- Metabase hosting environment: (Docker (Ubuntu 18.04 host) )

- *Repeatable steps to reproduce the issue*
./bin/build and thus ./bin/docker/build_image.sh (i had to launch npm install first because update-translations failed without it. Doesn't seem like a related problem, but every detail is needed)

log:
```
Running 'lein uberjar'...
Exception in thread "BasicRepositoryConnector-dl.bintray.com-2-1" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.http.client.utils.URLEncodedUtils.urlDecode(URLEncodedUtils.java:590)
        at org.apache.http.client.utils.URLEncodedUtils.decodeFormFields(URLEncodedUtils.java:619)
        at org.apache.http.client.utils.URLEncodedUtils.parse(URLEncodedUtils.java:316)
        at org.apache.http.client.utils.URLEncodedUtils.parse(URLEncodedUtils.java:249)
        at org.apache.http.client.utils.URIBuilder.parseQuery(URIBuilder.java:110)
        at org.apache.http.client.utils.URIBuilder.digestURI(URIBuilder.java:200)
        at org.apache.http.client.utils.URIBuilder.<init>(URIBuilder.java:90)
        at org.apache.http.impl.client.DefaultRedirectStrategy.createLocationURI(DefaultRedirectStrategy.java:189)
        at org.apache.http.impl.client.DefaultRedirectStrategy.getLocationURI(DefaultRedirectStrategy.java:148)
        at org.apache.http.impl.client.DefaultRedirectStrategy.getRedirect(DefaultRedirectStrategy.java:221)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:121)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:825)
        at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:986)
        at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:963)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:126)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:567)
        at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:435)
        at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:412)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:453)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:360)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.http.client.utils.URLEncodedUtils.urlDecode(URLEncodedUtils.java:590)
        at org.apache.http.client.utils.URLEncodedUtils.decodeFormFields(URLEncodedUtils.java:619)
        at org.apache.http.client.utils.URLEncodedUtils.parse(URLEncodedUtils.java:316)
        at org.apache.http.client.utils.URLEncodedUtils.parse(URLEncodedUtils.java:249)
        at org.apache.http.client.utils.URIBuilder.parseQuery(URIBuilder.java:110)
        at org.apache.http.client.utils.URIBuilder.digestURI(URIBuilder.java:200)
        at org.apache.http.client.utils.URIBuilder.<init>(URIBuilder.java:90)
        at org.apache.http.impl.client.DefaultRedirectStrategy.createLocationURI(DefaultRedirectStrategy.java:189)
        at org.apache.http.impl.client.DefaultRedirectStrategy.getLocationURI(DefaultRedirectStrategy.java:148)
        at org.apache.http.impl.client.DefaultRedirectStrategy.getRedirect(DefaultRedirectStrategy.java:221)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:121)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:825)
        at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:986)
        at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:963)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:126)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:567)
        at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:435)
        at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:412)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:453)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:360)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by MarkRx** [comment]
Something you are using was compiled for java 9. Java 9 had a breaking change on Buffer.flip changing the return object from a Buffer (Java 8) to a ByteBuffer (Java 9). Double check your java version you are building with.

It works for me with the following environment:
```
> java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
> npm -version
5.5.1
> node --version
v8.9.0
> lein --version
Leiningen 2.8.1 on Java 1.8.0_111 Java HotSpot(TM) 64-Bit Server VM
> yarn --version
1.3.2
```


https://docs.oracle.com/javase/8/docs/api/java/nio/Buffer.html#flip--
https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#flip--

**Comment by PavelLJ** [comment]
```
#java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
# npm -version
5.6.0
# node --version
v8.11.4
# lein --version
Leiningen 2.8.1 on Java 1.8.0_181 OpenJDK 64-Bit Server VM
# yarn --version
1.9.4
root@Ubuntu-1804-bionic-64-minimal ~ # 

```
My guess it's a problem with Lein as i had to install OpenJDK  to make it at least launch. How did you set up leiningen to work with Oracle Java?

**Comment by jornh** [comment]
> I know it's not a metabase question anymore (if that's the problem), but how did you set up leiningen to work with Oracle Java?

@PavelLJ I have my Ubuntu 16.04 based setup running with Leiningen installed not through `apt` but using "the lein script method": https://leiningen.org/#install. As far as I know the Leiningen apt apckage was only recently brought up to snuff: https://clojuresync.com/elana-hashman/ So when I started looking at Metabase it was lacking behind and I ended up installing to my `~/bin` as mention above. Maybe the `apt` package is still a bit rough around the edges regarding tolerating OpenJDK/Oracle JDK? I'm sure it will mature pretty soon though ...

In addition I have *also* been fighting a bit back and forth with OpenJDK and Oracle JDK as well. Recently after an `apt update && apt upgrade` it left me with a non-working `$ java` in bash. To get to a setting where I could both use `java` and `lein` again I ended up using `$ sudo update-alternatives --config java`. Below a dump of the Java/Clojure related side of my config:

```
jornh@Workstation:~$ which lein
/home/jornh/bin/lein
jornh@Workstation:~$ ls bin/lein
bin/lein
jhe@W60494:~$ sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-8-oracle/jre/bin/java          1081      auto mode
  1            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
  2            /usr/lib/jvm/java-8-oracle/jre/bin/java          1081      manual mode

Press <enter> to keep the current choice[*], or type selection number:
jornh@Workstation:~$ lein -v
Leiningen 2.8.1 on Java 1.8.0_181 Java HotSpot(TM) 64-Bit Server VM
jornh@Workstation:~$ java -version
java version "1.8.0_181"
```

Failing the above - and seeing you use Docker you might also try `docker build -t metabase_from_docker_build .` on the root of your metabase git clone for building Metabase because then you have a known-good tool chain.

Hope some of the info above will help you get to a working solution!

**Comment by flamber** [comment]
Closing, since Java 9 is EOL
