### ISSUE TITLE
Metabase H2 Row not found when trying to delete from index

### ISSUE THREAD

**Issue by mahenn** [metabase/metabase#8680]
Hi,

Today all of sudden our metabase instance went off. While re-running it showed Row not found when trying to delete from index
````
java -jar metabase.jar migrate release-locks
````
````10-12 10:59:48 INFO metabase.util :: Loading Metabase...
10-12 10:59:53 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
org.h2.jdbc.JdbcSQLException: Row not found when trying to delete from index """"".I37: ( /* key:770682 */ X'b287ce882a714b6fe7b84ac49ca794f8af99e655225d7aa7c02c7cffc0946c7b', 906)" [90112-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
````

post research on google and forums I run following commands.

````java -cp metabase.jar org.h2.tools.Recover
mv metabase.db.h2.db metabase.old.db
touch metabase.db.h2.db
````
Sql file was generated successfully. 

when I run 
````
java -cp metabase.jar org.h2.tools.RunScript -script metabase.db.h2.sql -url jdbc:h2:/path/to/metabase.db;MV_STORE=FALSE
````
````
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:

-- page 59459: b-tree leaf (last) parent: 62001 index: 9 entries: 143
-- page 59460: data leaf (last) parent: 0 table: 40 entries: 3 columns: 6
INSERT INTO O_40 VALUES(1, 'XXX AD collection', 'et_XXXX_collection', NULL, '#f9d45c', FALSE) [21002-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
````	

I found insert statement with diff columns. Few had 2 columns and other had two.

Since we had upgraded from 0.19 to 0.24, it looked like there were two structures of data and create statement was created using old data.

Finally I downloaded H2 tool and run the command
````
java -cp h2*.jar org.h2.tools.RunScript -url "jdbc:h2:~/mahen/metabase.db.h2.db.new2;MV_STORE=FALSE"  -continueOnError -user "sa" -script "~/mahen/metabase.db.h2.sql"
````
It had given me all errors
````INSERT INTO O_317 VALUES(1, 1, 1) [21002-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)

-- page 59459: b-tree leaf (last) parent: 62001 index: 9 entries: 143
-- page 59460: data leaf (last) parent: 0 table: 40 entries: 3 columns: 6
INSERT INTO O_40 VALUES(1, 'ET media FBAD collection', 'et_media_fbad_collection', NULL, '#f9d45c', FALSE) [21002-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)

LTER TABLE PUBLIC.PERMISSIONS_GROUP_MEMBERSHIP ADD CONSTRAINT PUBLIC.FK_PERMISSIONS_GROUP_GROUP_ID FOREIGN KEY(GROUP_ID) INDEX PUBLIC.FK_PERMISSIONS_GROUP_GROUP_ID_INDEX_A REFERENCES PUBLIC.PERMISSIONS_GROUP(ID) NOCHECK [23505-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)

ALTER TABLE PUBLIC.PERMISSIONS ADD CONSTRAINT PUBLIC.FK_PERMISSIONS_GROUP_ID FOREIGN KEY(GROUP_ID) INDEX PUBLIC.FK_PERMISSIONS_GROUP_ID_INDEX_C REFERENCES PUBLIC.PERMISSIONS_GROUP(ID) NOCHECK [23505-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
```

I had commented few queries and rerun the above command.
```
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_5E ON PUBLIC.PERMISSIONS_GROUP(ID) [23505-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:101)
	at org.h2.index.PageBtree.find(PageBtree.java:120)
	at org.h2.index.PageBtreeLeaf.addRow(PageBtreeL

ALTER TABLE PUBLIC.PERMISSIONS_GROUP ADD CONSTRAINT PUBLIC.PK_PERMISSIONS_GROUP PRIMARY KEY(ID) INDEX PUBLIC.PRIMARY_KEY_5E [23505-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)

ALTER TABLE PUBLIC.PERMISSIONS_GROUP_MEMBERSHIP ADD CONSTRAINT PUBLIC.FK_PERMISSIONS_GROUP_GROUP_ID FOREIGN KEY(GROUP_ID) INDEX PUBLIC.FK_PERMISSIONS_GROUP_GROUP_ID_INDEX_A REFERENCES PUBLIC.PERMISSIONS_GROUP(ID) NOCHECK [23505-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)

ALTER TABLE PUBLIC.PERMISSIONS ADD CONSTRAINT PUBLIC.FK_PERMISSIONS_GROUP_ID FOREIGN KEY(GROUP_ID) INDEX PUBLIC.FK_PERMISSIONS_GROUP_ID_INDEX_C REFERENCES PUBLIC.PERMISSIONS_GROUP(ID) NOCHECK [23505-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
````
Though metabase is working fine now. I don't know how do i rectify above errors. 

Please advice

**Comment by salsakran** [comment]
Do you have backups? It sounds like a migration got half-applied. 

Depending on how active the instance is, it might be best to just start up a fresh instance and programatically re-create the artifacts and users via our API.

**Comment by salsakran** [comment]
closing this since there's been no activity for over a month. Sorry your DB got corrupted. Happy to re-open if you're still having issues
