### ISSUE TITLE
Failed upgrade to v0.31.0 (Verifying h2 Database Connection)

### ISSUE THREAD

**Issue by jbrooksuk** [metabase/metabase#8901]
I've gone to upgrade from v0.30.3 to v0.31.0 this morning and I'm having issues.

We're running Metabase through the Linux Docker image.

Output of error:

```
11-09 08:46:11 INFO metabase.util :: Loading Metabase...
 11-09 08:46:23 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
  For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
 11-09 08:46:46 INFO metabase.core :: Starting Metabase in STANDALONE mode
 11-09 08:46:46 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
  {:port 3000, :host "0.0.0.0"}

 11-09 08:46:46 INFO metabase.core :: Starting Metabase version v0.31.0 (adf9a89 release-0.31.0) ...
 11-09 08:46:46 INFO metabase.core :: System timezone is 'GMT' ...
 WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
 11-09 08:46:52 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
 11-09 08:46:52 INFO metabase.db :: Verifying h2 Database Connection ...
 11-09 08:46:57 ERROR metabase.driver :: Failed to connect to database: Timed out after 5000 milliseconds.
 11-09 08:46:57 ERROR metabase.core :: Metabase Initialization FAILED
 java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
 (binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
 	at metabase.db$verify_db_connection.invokeStatic(db.clj:390)
 	at metabase.db$verify_db_connection.invoke(db.clj:383)
 	at metabase.db$verify_db_connection.invokeStatic(db.clj:386)
 	at metabase.db$verify_db_connection.invoke(db.clj:383)
 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:452)
 	at metabase.db$setup_db_BANG_.doInvoke(db.clj:446)
 	at clojure.lang.RestFn.invoke(RestFn.java:421)
 	at metabase.core$init_BANG_.invokeStatic(core.clj:162)
 	at metabase.core$init_BANG_.invoke(core.clj:139)
 	at metabase.core$start_normally.invokeStatic(core.clj:246)
 	at metabase.core$start_normally.invoke(core.clj:240)
 	at metabase.core$_main.invokeStatic(core.clj:266)
 	at metabase.core$_main.doInvoke(core.clj:261)
 	at clojure.lang.RestFn.invoke(RestFn.java:397)
 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
 	at metabase.core.main(Unknown Source)
 11-09 08:46:57 INFO metabase.core :: Metabase Shutting Down ...
 11-09 08:46:57 INFO metabase.core :: Metabase Shutdown COMPLETE
```

How do I go about fixing the upgrade?

**Comment by jbrooksuk** [comment]
I've now migrated to MySQL and it's okay.

**Comment by senior** [comment]
@jbrooksuk it looks like maybe H2 didn't startup, maybe it couldn't find the database file? Migrating from H2 to MySQL or PostgreSQL is a good idea in general, so it sounds like you aren't seeing this issue anymore. Is there any followup on this issue or should it be closed?

**Comment by jbrooksuk** [comment]
@senior I started the Docker image as I have done for the last few upgrades, so there shouldn’t have been an issue with that. 

Nope, all good for me.
