### ISSUE TITLE
Failed upgrade 0.31.0 (No implementation of method: :form-encode*)

### ISSUE THREAD

**Issue by MikeRoetgers** [metabase/metabase#8905]
Hi, I tried to update from 0.30.4 to 0.31.0 this morning. I know there is a similar ticket open, but it revolves around h2, so I'm guessing it is not the same underlying issue.

* official docker image
* Internal Metabase DB is Postgres 9.6
* Error: `auto-retry metabase.db$run_schema_migrations_BANG_$fn__15456@17c60995: No implementation of method: :form-encode* of protocol: #'ring.util.codec/FormEncodeable found for class: nil`

The full boot process including stack trace:

```
11-09 08:55:23 INFO metabase.util :: Loading Metabase...
11-09 08:55:32 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
 For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
11-09 08:55:49 INFO metabase.core :: Starting Metabase in STANDALONE mode
11-09 08:55:49 INFO metabase.core :: Launching Embedded Jetty Webserver with config: 
 {:port 3000, :host "0.0.0.0"}

11-09 08:55:49 INFO metabase.core :: Starting Metabase version v0.31.0 (adf9a89 release-0.31.0) ...
11-09 08:55:49 INFO metabase.core :: System timezone is 'GMT' ...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
11-09 08:55:52 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
11-09 08:55:52 INFO metabase.db :: Verifying postgres Database Connection ...
11-09 08:55:53 INFO metabase.db :: Verify Database Connection ...  ✅
11-09 08:55:53 INFO metabase.db :: Running Database Migrations...
11-09 08:55:53 WARN metabase.util :: auto-retry metabase.db$run_schema_migrations_BANG_$fn__15456@17c60995: No implementation of method: :form-encode* of protocol: #'ring.util.codec/FormEncodeable found for class: nil
11-09 08:55:53 ERROR metabase.core :: Metabase Initialization FAILED
java.lang.IllegalArgumentException: No implementation of method: :form-encode* of protocol: #'ring.util.codec/FormEncodeable found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at ring.util.codec$fn__1583$G__1578__1590.invoke(codec.clj:81)
	at ring.util.codec$fn__1599$encode__1600.invoke(codec.clj:90)
	at ring.util.codec$fn__1599$encode_param__1603.invoke(codec.clj:91)
	at ring.util.codec$fn__1599$fn__1609.invoke(codec.clj:97)
	at clojure.core$map$fn__5587.invoke(core.clj:2747)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1785)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$mapcat.invokeStatic(core.clj:2775)
	at clojure.core$mapcat.doInvoke(core.clj:2775)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at ring.util.codec$fn__1599.invokeStatic(codec.clj:93)
	at ring.util.codec$fn__1599.invoke(codec.clj:84)
	at ring.util.codec$fn__1583$G__1578__1590.invoke(codec.clj:81)
	at ring.util.codec$form_encode.invokeStatic(codec.clj:108)
	at ring.util.codec$form_encode.doInvoke(codec.clj:103)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.db.spec$make_subname.invokeStatic(spec.clj:25)
	at metabase.db.spec$make_subname.invoke(spec.clj:24)
	at metabase.db.spec$postgres.invokeStatic(spec.clj:41)
	at metabase.db.spec$postgres.invoke(spec.clj:29)
	at metabase.db$jdbc_details.invokeStatic(db.clj:111)
	at metabase.db$jdbc_details.invoke(db.clj:101)
	at metabase.db$migrate_BANG_.invokeStatic(db.clj:276)
	at metabase.db$migrate_BANG_.invoke(db.clj:257)
	at metabase.db$run_schema_migrations_BANG_$fn__15456.invoke(db.clj:435)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:410)
	at metabase.util$do_with_auto_retries.invoke(util.clj:402)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:414)
	at metabase.util$do_with_auto_retries.invoke(util.clj:402)
	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:434)
	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:417)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:453)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:446)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:162)
	at metabase.core$init_BANG_.invoke(core.clj:139)
	at metabase.core$start_normally.invokeStatic(core.clj:246)
	at metabase.core$start_normally.invoke(core.clj:240)
	at metabase.core$_main.invokeStatic(core.clj:266)
	at metabase.core$_main.doInvoke(core.clj:261)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
11-09 08:55:53 INFO metabase.core :: Metabase Shutting Down ...
11-09 08:55:53 INFO metabase.core :: Metabase Shutdown COMPLETE
```

Any idea how to proceed?

**Comment by senior** [comment]
@MikeRoetgers Can you include how you are specifying your application database connection information? Are you using an `MB_DB_CONNECTION_URI`? If so can you include the connection string (with sensitive information omitted of course).

**Comment by senior** [comment]
I'm able to reproduce your issue and I know what's wrong now. You are not correctly specifying the database name. In your config above you are using `MB_DB_NAME` but to configure the database name, you should be using `MB_DB_DBNAME`. The code is assuming `MB_DB_DBNAME` is present and so some code downstream is having an issue with there being a null value there. We should change Metabase to be tolerant of that configuration issue, but as a workaround, specifying the correct variable for the database name will fix your issue.

Your Metabase instance was running fine before because your Metabase database user is `metabase` which will default to connecting to the `metabase` database. We take the `MB_DB_DBNAME` parameter and default it to `""` when its used to connect, but that null database name is slipping through in another place.

**Comment by MikeRoetgers** [comment]
Oh wow, would have never catched that myself. Thank you for the support @senior
