### ISSUE TITLE
error when starting: org.postgresql.util.PSQLException: SSL error: sun.security.validator.ValidatorException

### ISSUE THREAD

**Issue by cwbeck** [metabase/metabase#8908]
```docker run -d -p 80:3000   -e "MB_DB_TYPE=postgres"   -e "MB_DB_CONNECTION_URI=postgres://<username>:<password>@aws-eu-west-1-portal.......:19.../metabase?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory"   --name metabase metabase/metabase:v0.31.0```

It goes a bit like this...

```
Nov 09, 2018 10:49:01 AM org.postgresql.Driver connect
SEVERE: Connection error: 
org.postgresql.util.PSQLException: SSL error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:67)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:389)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:160)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:62)
	... 15 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	... 23 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 29 more
```

**Comment by jbrooksuk** [comment]
https://discourse.metabase.com/t/upgrading-to-v0-31-0/4770

I'm having the same issue with the H2 driver.

**Comment by senior** [comment]
@cwbeck The error message looks like it's trying verify the SSL certificate that it is getting from your PostgreSQL instance. Can you provide some more information about your SSL setup on AWS? I'm not sure why you would be seeing this after the upgrade. One change that we did make for this release is we moved from a deprecated OpenJDK docker image `java:openjdk-8-jdk-alpine` to `openjdk:8-jdk-alpine`. That move also would have made a minor upgrade to the OpenJDK 8 (1.8.0_111 vs 1.8.0_171).

Minor JDK upgrades like that don't tend to cause problems, so I wouldn't suspect that as an issue. Also I'm not sure if it matters, but the old docker container we used had more cerfificates in the keystore than the new one does. Looking at the difference, it looks like they just removed expired ones, so it is probably not relevant here.

**Comment by cwbeck** [comment]
@senior, I came to a similar conclusion. We used to have issues with self-signed certs, we had to add them manually via ```keytool```, but these are valid certs. We use IBM's compose.com, I know it's an AWS endpoint but this is abstracted away from us. We run docker ```8-jre``` and ```11-jre``` for our setups connecting to this server too (Scala). We've not encountered any issues. I spun the old image back up (30.4) and it connected without any issues. It seems likely that it is somehow releated to this new base image. Perhaps ```org.postgresql.ssl.NonValidatingFactory``` is unsupported? The SSL cert is valid and tried without ```&sslfactory=org.postgresql.ssl.NonValidatingFactory``` but still no joy.

**Comment by eladeyal-intel** [comment]
I see the same thing here, trying to upgrade from 0.29.3 . 

My value of MB_DB_CONNECTION_URI  is `postgres://USERNAME:PASSWORD@HOSNAME:5433/lusus_metabase_app_database?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory`

connects well with 0.29.3

I had a problem upgrading from 0.29 to 0.30 so I stopped then (can't find the issue. will search again). I think someone created a JAR with the older jdk and it did not help.

I am in enterprise environment, not AWS. I can help debug, run private JAR or docker - I'm really exceited about all the new versions.

My PostgreSQL  version: `PostgreSQL 9.5.0 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-55), 64-bit`

**Comment by eladeyal-intel** [comment]
@cwbeck I had the same problem and I fixed it ! by adding ```&sslmode=require``` to the connection string

MB_DB_CONNECTION_URI before ```postgres://uuuu:pppp@host:5433/xxxxxxx?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&sslmode=require``` gave me the same error as described here.

after: ```postgres://uuuu:pppp@host:5433/xxxxxxx?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&sslmode=require``` works ok with v0.31.0.

**Comment by cwbeck** [comment]
@eladeyal-intel you sir are a legend!

**Comment by hawaiik** [comment]
Thank you so much, this just saved my day! :)

**Comment by camsaul** [comment]
Not sure if we should be adding that parameter automatically in this case or not (I'm worried that doing so could break things for other people). At the very least we should add this to the documentation somewhere

**Comment by camsaul** [comment]
Resolved by #9045

**Comment by magwas** [comment]
Please note that using nonvalidating ssl factory means that the server certificate is not checked.
Based on your environment it may or may not mean a security vulnerability.
Before doing this, ask yourself whether you are absolutely sure that you connect to the right server: both the networking path and - if you use symbolic names - the DNS is protected against tampering and man-in-the-middle attacks?

**Comment by magwas** [comment]
The right solution is to add the server certificate to the list of trusted certificate, as documented at https://jdbc.postgresql.org/documentation/head/ssl-client.html

**Comment by PrajwalSD** [comment]
> &sslmode=require

This fixed my issue too! Thank you!

**Comment by praveenbaliga** [comment]
@eladeyal-intel , thanks so much .. it worked like a charm :)

**Comment by praveenbaliga** [comment]
> @cwbeck I had the same problem and I fixed it ! by adding `&sslmode=require` to the connection string
> 
> MB_DB_CONNECTION_URI before
> 
> ```
> postgres://uuuu:pppp@host:5433/xxxxxxx?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&sslmode=require
> ```
> 
> gave me the same error as described here.
> 
> after:
> 
> ```
> postgres://uuuu:pppp@host:5433/xxxxxxx?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&sslmode=require
> ```
> 
> works ok with v0.31.0.

@eladeyal-intel , thanks so much .. it worked like a charm :)

**Comment by raimiyashiro** [comment]
> @cwbeck I had the same problem and I fixed it ! by adding `&sslmode=require` to the connection string
> 
> MB_DB_CONNECTION_URI before
> 
> ```
> postgres://uuuu:pppp@host:5433/xxxxxxx?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
> ```
> 
> gave me the same error as described here.
> 
> after:
> 
> ```
> postgres://uuuu:pppp@host:5433/xxxxxxx?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&sslmode=require
> ```
> 
> works ok with v0.31.0.

Thank you, lad!
