### ISSUE TITLE
Migration issue when upgrading from 0.30.0 to 0.31.0

### ISSUE THREAD

**Issue by lukaszkorecki** [metabase/metabase#8909]
Hi 👋 

While upgrade to 0.30.0 was super smooth, looks like we've run into an issue with migrations when moving to 0.31.0:

```
11-09 12:29:28 INFO metabase.core :: System timezone is 'GMT' ...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replac
ed by: #'monger.collection/any?                                                                  
11-09 12:29:32 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this 
may take a minute...                                                                             
11-09 12:29:32 INFO metabase.db :: Verifying postgres Database Connection ...
11-09 12:29:33 INFO metabase.db :: Verify Database Connection ...  ✅
11-09 12:29:33 INFO metabase.db :: Running Database Migrations...
11-09 12:29:33 INFO metabase.db :: Setting up Liquibase...
11-09 12:29:33 INFO metabase.db :: Liquibase is ready.
11-09 12:29:33 INFO metabase.db :: Checking if Database has unrun migrations...
11-09 12:29:39 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be
 cleared...                                                                                      
11-09 12:29:39 INFO metabase.db :: Migration lock is cleared. Running migrations...
11-09 12:29:49 WARN metabase.util :: auto-retry metabase.db$run_schema_migrations_BANG_$fn__15456@
68a06679: ERROR: could not create unique index "idx_databasechangelog_id_author_filename"        
  Detail: Key (id, author, filename)=(60, camsaul, migrations/000_migrations.yaml) is duplicated.
11-09 12:29:49 INFO metabase.db :: Setting up Liquibase...
11-09 12:29:49 INFO metabase.db :: Liquibase is ready.
11-09 12:29:49 INFO metabase.db :: Checking if Database has unrun migrations...
11-09 12:29:51 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be
 cleared...                                                                                      
11-09 12:29:51 INFO metabase.db :: Migration lock is cleared. Running migrations...
11-09 12:30:00 ERROR metabase.core :: Metabase Initialization FAILED
org.postgresql.util.PSQLException: ERROR: could not create unique index "idx_databasechangelog_id_
author_filename"                                                                                 
  Detail: Key (id, author, filename)=(6, agilliland, migrations/000_migrations.yaml) is duplicated
.                                                                                                
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:24
33)                                                                                              
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
        at clojure.java.jdbc$db_do_execute_prepared_statement$fn__11200.invoke(jdbc.clj:961)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:790)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:730)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:960)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:954)
        at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:992)
        at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:972)
        at clojure.java.jdbc$execute_BANG_$execute_helper__11279.invoke(jdbc.clj:1386)
        at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1388)
        at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1359)
        at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1378)
        at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1359)
        at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:186)

```

Environment: Linux + Docker
Databases connected: Postgres, Big Query
Metabase is storing its config in Postgres

**Comment by jbrooksuk** [comment]
I'm having this issue with H2; https://discourse.metabase.com/t/upgrading-to-v0-31-0/4770

**Comment by lukaszkorecki** [comment]
@senior sure thing, here's the csv output, as exported from metabase:

```csv
id,author,filename,dateexecuted,orderexecuted,exectype,md5sum,description,comments,tag,liquibase,contexts,labels,deployment_id
6,agilliland,migrations/000_migrations.yaml,2018-01-16T12:28:53.451Z,5,EXECUTED,8:2d2f5d1756ecb81da7c09ccfb9b1565a,"dropNotNullConstraint columnName=organization_id, tableName=metabase_database; dropForeignKeyConstraint baseTableName=metabase_database, constraintName=fk_database_ref_organization_id; dropNotNullConstraint columnName=organization_id, tableName=re...",,,3.5.3,,,6105643921
6,agilliland,migrations/000_migrations.yaml,2018-04-23T14:02:35.597+01:00,5,EXECUTED,8:2d2f5d1756ecb81da7c09ccfb9b1565a,"dropNotNullConstraint columnName=organization_id, tableName=metabase_database; dropForeignKeyConstraint baseTableName=metabase_database, constraintName=fk_database_ref_organization_id; dropNotNullConstraint columnName=organization_id, tableName=re...",,,3.5.3,,,4492057146
60,camsaul,migrations/000_migrations.yaml,2018-04-23T14:02:35.597+01:00,59,EXECUTED,8:4f997b2cd3309882e900493892381f38,addColumn tableName=metabase_database,Added 0.26.0,,3.5.3,,,4492057146
60,camsaul,migrations/000_migrations.yaml,2018-01-16T12:28:53.451Z,59,EXECUTED,8:4f997b2cd3309882e900493892381f38,addColumn tableName=metabase_database,Added 0.26.0,,3.5.3,,,6105643921
```

**Comment by senior** [comment]
@lukaszkorecki Having two entries for those ids is definitely the issue. I'll look into what would cause that. Manually removing the duplicate entries would resolve the issue, but it would be good to know how or why it happened.

**Comment by blender50** [comment]
I have the same issue here. Looking at the databasechangelog table ordered by 'id' shows that there are a ton of duplicate records going back as far as March 2017. It would seem that trying to create an index as a part of the new migration is what is the show stopper here.

**Comment by camsaul** [comment]
Hey everyone, I'm taking a look at this issue and hope to have a fix later today.

**Comment by mohit091** [comment]
Any update on this

**Comment by lukaszkorecki** [comment]
@camsaul Thank you! I see that it got pushed to release-0.31.1 tag - will test it as soon as it's available in the Docker registry
