### ISSUE TITLE
Java error java.lang.OutOfMemoryError in v0.31.0 jar file on Windows

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#8921]
Edit: I've just found https://metabase.com/docs/latest/troubleshooting-guide/running.html which gives some details on how to handle this so I have a work around. I'll leave the issue open though as there may be something worth following up on your end. 

Starting from just the v0.31.0 jar file, using only the built in H2 databases, I get a ```java.lang.OutOfMemoryError``` error when running db migrations.

- Your operating system: Windows 7, 64-bit, Java 1.8.0_101-b13
- Your databases: H2
- Metabase version: 0.31.0
- Metabase hosting environment: local jar file
- Metabase internal database: H2

**Repeatable steps to reproduce the issue**
- Using the new v0.31.0 jar file in an otherwise empty folder, no Metabase environment variables setup
- Run the jar file
- java.lang.OutOfMemoryError error reported and Metabase does not start
- using the v0.30.4 jar file still works fine
- Physical memory on the machine seems fine, no shortage available
- Log below

```
java -jar metabase.jar
11-12 16:45:29 ←[1mINFO metabase.util←[0m :: Loading Metabase...
11-12 16:45:36 ←[1mINFO util.encryption←[0m :: Saved credentials encryption is D
ISABLED for this Metabase instance.
 For more information, see https://www.metabase.com/docs/latest/operations-guide
/start.html#encrypting-your-database-connection-details-at-rest
11-12 16:46:11 ←[1mINFO metabase.core←[0m :: Starting Metabase in STANDALONE mod
e
11-12 16:46:11 ←[1mINFO metabase.core←[0m :: Launching Embedded Jetty Webserver
with config:
 {:port 3000}

11-12 16:46:11 ←[1mINFO metabase.core←[0m :: Starting Metabase version v0.31.0 (
adf9a89 release-0.31.0) ...
11-12 16:46:11 ←[1mINFO metabase.core←[0m :: System timezone is 'Pacific/Aucklan
d' ...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collec
tion, being replaced by: #'monger.collection/any?
11-12 16:46:16 ←[1mINFO metabase.core←[0m :: Setting up and migrating Metabase D
B. Please sit tight, this may take a minute...
11-12 16:46:16 ←[1mINFO metabase.db←[0m :: Verifying h2 Database Connection ...
11-12 16:46:16 ←[1mINFO metabase.db←[0m :: Verify Database Connection ...
11-12 16:46:16 ←[1mINFO metabase.db←[0m :: Running Database Migrations...
11-12 16:46:16 ←[1mINFO metabase.db←[0m :: Setting up Liquibase...
11-12 16:46:16 ←[1mINFO metabase.db←[0m :: Liquibase is ready.
11-12 16:46:16 ←[1mINFO metabase.db←[0m :: Checking if Database has unrun migrat
ions...
11-12 16:46:33 ←[1mWARN metabase.util←[0m :: auto-retry metabase.db$run_schema_m
igrations_BANG_$fn__15456@9d5a5a: Java heap space
11-12 16:46:33 ←[1mINFO metabase.db←[0m :: Setting up Liquibase...
11-12 16:46:33 ←[1mINFO metabase.db←[0m :: Liquibase is ready.
11-12 16:46:33 ←[1mINFO metabase.db←[0m :: Checking if Database has unrun migrat
ions...
11-12 16:46:47 ←[1mERROR metabase.core←[0m :: Metabase Initialization FAILED
java.lang.OutOfMemoryError: Java heap space
        at java.util.Hashtable.rehash(Unknown Source)
        at java.util.Hashtable.addEntry(Unknown Source)
        at java.util.Hashtable.put(Unknown Source)
        at sun.security.util.SignatureFileVerifier.updateSigners(Unknown Source)

        at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
        at sun.security.util.SignatureFileVerifier.process(Unknown Source)
        at java.util.jar.JarVerifier.processEntry(Unknown Source)
        at java.util.jar.JarVerifier.update(Unknown Source)
        at java.util.jar.JarFile.initializeVerifier(Unknown Source)
        at java.util.jar.JarFile.getInputStream(Unknown Source)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Sour
ce)
        at liquibase.resource.ClassLoaderResourceAccessor.getResourcesAsStream(C
lassLoaderResourceAccessor.java:53)
        at liquibase.util.StreamUtil.singleInputStream(StreamUtil.java:186)
        at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogPar
ser.java:27)
        at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:
525)
        at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.ja
va:490)
        at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeL
og.java:368)
        at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:293
)
        at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogPar
ser.java:78)
        at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:217)
        at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1281)
        at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1274)
        at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:1270)
        at metabase.db$has_unrun_migrations_QMARK_.invokeStatic(db.clj:147)
        at metabase.db$has_unrun_migrations_QMARK_.invoke(db.clj:140)
        at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:177)
        at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:168)
        at metabase.db$migrate_BANG_$fn__15423.invoke(db.clj:288)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:747)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
11-12 16:46:47 ←[1mINFO metabase.core←[0m :: Metabase Shutting Down ...
11-12 16:46:47 ←[1mINFO metabase.core←[0m :: Metabase Shutdown COMPLETE
```

Thanks

**Comment by notrom** [comment]
Further info, just tried the jar for **v0.31 RC1** in exactly the same environment and I'm **not getting the memory error**.

Thanks

**Comment by camsaul** [comment]
Hi @notrom try telling the JVM how much memory it can use with the `-Xmx` flag.

e.g.

```
java -Xmx2g -jar metabase.jar
```

**Comment by notrom** [comment]
Thanks @camsaul, I did try that and it ran, I edited the issue a few days ago to reflect that.

Found https://metabase.com/docs/latest/troubleshooting-guide/running.html which gives some details on how to handle this so I have a work around. I'll leave the issue open though as there may be something worth following up on your end.

The -Xmx wasn't (and still isn't needed) in v0.31 RC1 or v0.30.4 in my environment.

**Comment by camsaul** [comment]
Hi @notrom, Metabase 0.31.1 reduces memory usage a bit, so you might want to try that. 

Going to go ahead and close this issue since using the `-Xmx` flag seems to have resolved the issue for you

**Comment by pull6** [comment]
> Hi [@notrom](https://github.com/notrom), Metabase 0.31.1 reduces memory usage a bit, so you might want to try that.
> 
> Going to go ahead and close this issue since using the `-Xmx` flag seems to have resolved the issue for you





https://chaperone562.github.io/kFi-8KZfTaKzEUGmnlI99R2SkHZ_IATyDvi5_LsvOB2VxyG5uOM35FfYU_b9wXQYAy_hvER_klHuIw/
