### ISSUE TITLE
Failed 0.31.0 jar file local installation

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#8923]
Metabase: 0.31.0 (previously 0.30.4)
Host: Localhost:3000
OS: Microsoft Windows [Version 6.0.6002]
Browser: Firefox 52.9.0

Tsk, tsk, the curse of the early adopters. Judging from various and sundry open issues it would seem v0.31.0 isn't quite ready for primetime in every environment... Back to v0.30.4, it works dandy, looking forward to v0.31.1

<code>
Microsoft Windows [Version 6.0.6002]
Copyright (c) 2006 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd c:\Program Files\Metabase

c:\Program Files\Metabase>java -jar metabase.jar
11-11 21:23:29 ←[1mINFO metabase.util←[0m :: Loading Metabase...
11-11 21:23:52 ←[1mINFO util.encryption←[0m :: Saved credentials encryption is D
ISABLED for this Metabase instance.
 For more information, see https://www.metabase.com/docs/latest/operations-guide
/start.html#encrypting-your-database-connection-details-at-rest
11-11 21:25:50 ←[1mINFO metabase.core←[0m :: Starting Metabase in STANDALONE mod
e
11-11 21:25:50 ←[1mINFO metabase.core←[0m :: Launching Embedded Jetty Webserver
with config:
 {:port 3000}

11-11 21:25:50 ←[1mERROR metabase.core←[0m :: Metabase Initialization FAILED
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConn
ector.java:331)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:29
9)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNet
workConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java
:235)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:398)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:68)
        at ring.adapter.jetty$run_jetty.invokeStatic(jetty.clj:154)
        at ring.adapter.jetty$run_jetty.invoke(jetty.clj:114)
        at metabase.core$start_jetty_BANG_.invokeStatic(core.clj:226)
        at metabase.core$start_jetty_BANG_.invoke(core.clj:203)
        at metabase.core$start_normally.invokeStatic(core.clj:244)
        at metabase.core$start_normally.invoke(core.clj:240)
        at metabase.core$_main.invokeStatic(core.clj:266)
        at metabase.core$_main.doInvoke(core.clj:261)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)

c:\Program Files\Metabase>
</code>

**Comment by MarcGJA** [comment]
CLOSE this issue.  Copied the wrong error message into the original post.  This is a <a href="https://metabase.com/docs/latest/troubleshooting-guide/running.html">known Heap Space issue</a>.  Apologies for re-posting rather than editing the original post, GitHub recently updated it's website beyond the capabilities of the most advanced browsers my current OS allows and the editing feature is among those no longer supported.  Rather than monkeying around with install parameters I'll just stick to v0.30.4 locally for the time being.

<code>
Microsoft Windows [Version 6.0.6002]
Copyright (c) 2006 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd c:\Program Files\Metabase

c:\Program Files\Metabase>java -jar metabase.jar
11-12 10:05:26 ←[1mINFO metabase.util←[0m :: Loading Metabase...
11-12 10:05:39 ←[1mINFO util.encryption←[0m :: Saved credentials encryption is D
ISABLED for this Metabase instance.
 For more information, see https://www.metabase.com/docs/latest/operations-guide
/start.html#encrypting-your-database-connection-details-at-rest
11-12 10:06:47 ←[1mINFO metabase.core←[0m :: Starting Metabase in STANDALONE mod
e
11-12 10:06:47 ←[1mINFO metabase.core←[0m :: Launching Embedded Jetty Webserver
with config:
 {:port 3000}

11-12 10:06:47 ←[1mINFO metabase.core←[0m :: Starting Metabase version v0.31.0 (
adf9a89 release-0.31.0) ...
11-12 10:06:47 ←[1mINFO metabase.core←[0m :: System timezone is 'America/Los_Ang
eles' ...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collec
tion, being replaced by: #'monger.collection/any?
11-12 10:06:59 ←[1mINFO metabase.core←[0m :: Setting up and migrating Metabase D
B. Please sit tight, this may take a minute...
11-12 10:06:59 ←[1mINFO metabase.db←[0m :: Verifying h2 Database Connection ...
11-12 10:07:01 ←[1mINFO metabase.db←[0m :: Verify Database Connection ...
11-12 10:07:01 ←[1mINFO metabase.db←[0m :: Running Database Migrations...
11-12 10:07:01 ←[1mINFO metabase.db←[0m :: Setting up Liquibase...
11-12 10:07:01 ←[1mINFO metabase.db←[0m :: Liquibase is ready.
11-12 10:07:01 ←[1mINFO metabase.db←[0m :: Checking if Database has unrun migrat
ions...
11-12 10:08:14 ←[1mWARN metabase.util←[0m :: auto-retry metabase.db$run_schema_m
igrations_BANG_$fn__15456@1a53992: Java heap space
11-12 10:08:14 ←[1mINFO metabase.db←[0m :: Setting up Liquibase...
11-12 10:08:14 ←[1mINFO metabase.db←[0m :: Liquibase is ready.
11-12 10:08:14 ←[1mINFO metabase.db←[0m :: Checking if Database has unrun migrat
ions...
11-12 10:08:52 ←[1mERROR metabase.core←[0m :: Metabase Initialization FAILED
java.lang.OutOfMemoryError: Java heap space
11-12 10:08:52 ←[1mINFO metabase.core←[0m :: Metabase Shutting Down ...
11-12 10:08:52 ←[1mINFO metabase.core←[0m :: Metabase Shutdown COMPLETE

c:\Program Files\Metabase>
</code>

**Comment by camsaul** [comment]
> CLOSE this issue.

@MarcGJA just a reminder, GitHub lets you close your own issues. You don't need to wait for us to do it
