### ISSUE TITLE
Metabase 0.31 upgrade fails 

### ISSUE THREAD

**Issue by AvnerCohen** [metabase/metabase#8924]
Using the elasticbeanstalk solution, upgrade using standard workflow.
getting the following to loop forever:

11-12 07:41:11 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
11-12 07:41:11 INFO db.migrations :: Running data migration 'add-legacy-sql-directive-to-bigquery-sql-cards'...
11-12 07:41:11 ERROR metabase.core :: Metabase Initialization FAILED
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at clojure.core$re_matcher.invokeStatic(core.clj:4796)
	at clojure.core$re_find.invokeStatic(core.clj:4838)
	at clojure.core$re_find.invoke(core.clj:4838)
	at metabase.db.migrations$add_legacy_sql_directive_to_bigquery_sql_cards.invokeStatic(migrations.clj:286)
	at metabase.db.migrations$add_legacy_sql_directive_to_bigquery_sql_cards.invoke(migrations.clj:277)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:52)
	at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:43)
	at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:72)
	at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:66)
	at clojure.lang.Var.invoke(Var.java:377)
	at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:444)
	at metabase.db$run_data_migrations_BANG_.invoke(db.clj:439)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:455)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:446)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:162)
	at metabase.core$init_BANG_.invoke(core.clj:139)
	at metabase.core$start_normally.invokeStatic(core.clj:246)
	at metabase.core$start_normally.invoke(core.clj:240)
	at metabase.core$_main.invokeStatic(core.clj:266)
	at metabase.core$_main.doInvoke(core.clj:261)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)

**Comment by Microsheep** [comment]
Seems to get a similar problem here.

**Comment by camsaul** [comment]
Fixed by #8980
