### ISSUE TITLE
ERROR in task-history-cleanup

### ISSUE THREAD

**Issue by wccropper** [metabase/metabase#8941]
- Metabase version: 0.30.4
- Metabase hosting environment: Docker on CentOS 7
- Metabase internal database: MySQL

Pulses have stopped sending out and we noticed this error about every 4 minutes in the docker log for the metabase container.

11-14 15:05:26 ERROR jdbcjobstore.JobStoreTX :: MisfireHandler: Error handling misfires: Couldn't store trigger 'DEFAULT.metabase.task.task-history-cleanup.trigger' for 'DEFAULT.metabase.task.task-history-cleanup.job' job:Could not locate metabase/task/task_history_cleanup__init.class or metabase/task/task_history_cleanup.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
org.quartz.JobPersistenceException: Couldn't store trigger 'DEFAULT.metabase.task.task-history-cleanup.trigger' for 'DEFAULT.metabase.task.task-history-cleanup.job' job:Could not locate metabase/task/task_history_cleanup__init.class or metabase/task/task_history_cleanup.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name. [See nested exception: java.io.FileNotFoundException: Could not locate metabase/task/task_history_cleanup__init.class or metabase/task/task_history_cleanup.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1212)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1026)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:975)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3174)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3934)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3955)
Caused by: java.io.FileNotFoundException: Could not locate metabase/task/task_history_cleanup__init.class or metabase/task/task_history_cleanup.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6548.invoke(core.clj:6046)
	at clojure.core$load.invokeStatic(core.clj:6045)
	at clojure.core$load.doInvoke(core.clj:6029)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5848)
	at clojure.core$load_one.invoke(core.clj:5843)
	at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
	at clojure.core$load_lib.invokeStatic(core.clj:5887)
	at clojure.core$load_lib.doInvoke(core.clj:5868)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5925)
	at clojure.core$load_libs.doInvoke(core.clj:5909)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5947)
	at clojure.core$require.doInvoke(core.clj:5947)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at metabase.task.DynamicClassLoadHelper$require_task_namespace.invokeStatic(DynamicClassLoadHelper.clj:36)
	at metabase.task.DynamicClassLoadHelper$require_task_namespace.invoke(DynamicClassLoadHelper.clj:29)
	at metabase.task.DynamicClassLoadHelper$_loadClass.invokeStatic(DynamicClassLoadHelper.clj:46)
	at metabase.task.DynamicClassLoadHelper$_loadClass.invoke(DynamicClassLoadHelper.clj:38)
	at metabase.task.DynamicClassLoadHelper.loadClass(Unknown Source)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:873)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1194)
	... 5 more

**Comment by camsaul** [comment]
I'm not sure what's causing this but it doesn't seem to cause any problems

**Comment by camsaul** [comment]
@wccropper what Java version are you using? Are you still seeing this on Metabase 0.31.1?

**Comment by camsaul** [comment]
@wccropper I think I figured this out. Did you upgrade to Metabase 0.31.x and then downgrade back to Metabase 0.30.4?

**Comment by wccropper** [comment]
Yes we upgraded to 0.31.0 but had SSL issues from here #8912 . We have now completed the upgrade to 0.31.1. I still see issues though. These seem more related to #5961 

11-28 21:00:00 ERROR core.JobRunShell :: Job DEFAULT.metabase.task.task-history-cleanup.job threw an unhandled Exception:
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 3,597,877 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
	at sun.reflect.GeneratedConstructorAccessor85.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3559)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:353)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1002)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:996)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1025)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1005)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1099)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1056)
	at toucan.db$query.invokeStatic(db.clj:275)
	at toucan.db$query.doInvoke(db.clj:271)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$simple_select.invokeStatic(db.clj:379)
	at toucan.db$simple_select.invoke(db.clj:368)
	at toucan.db$simple_select_one.invokeStatic(db.clj:405)
	at toucan.db$simple_select_one.invoke(db.clj:394)
	at toucan.db$select_one.invokeStatic(db.clj:606)
	at toucan.db$select_one.doInvoke(db.clj:599)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at toucan.db$select_one_field.invokeStatic(db.clj:615)
	at toucan.db$select_one_field.doInvoke(db.clj:608)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.models.task_history$cleanup_task_history_BANG_.invokeStatic(task_history.clj:21)
	at metabase.models.task_history$cleanup_task_history_BANG_.invoke(task_history.clj:12)
	at metabase.task.task_history_cleanup$task_history_cleanup_BANG_.invokeStatic(task_history_cleanup.clj:29)
	at metabase.task.task_history_cleanup$task_history_cleanup_BANG_.invoke(task_history_cleanup.clj:25)
	at metabase.task.task_history_cleanup.TaskHistoryCleanup.execute(task_history_cleanup.clj:41)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469)
	... 36 more
11-28 21:00:00 ERROR core.ErrorLogger :: Job (DEFAULT.metabase.task.task-history-cleanup.job threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 3,597,877 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 3,597,877 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
	at sun.reflect.GeneratedConstructorAccessor85.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3559)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:353)
	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1002)
	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:996)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1025)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1005)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1099)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1056)
	at toucan.db$query.invokeStatic(db.clj:275)
	at toucan.db$query.doInvoke(db.clj:271)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at toucan.db$simple_select.invokeStatic(db.clj:379)
	at toucan.db$simple_select.invoke(db.clj:368)
	at toucan.db$simple_select_one.invokeStatic(db.clj:405)
	at toucan.db$simple_select_one.invoke(db.clj:394)
	at toucan.db$select_one.invokeStatic(db.clj:606)
	at toucan.db$select_one.doInvoke(db.clj:599)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at toucan.db$select_one_field.invokeStatic(db.clj:615)
	at toucan.db$select_one_field.doInvoke(db.clj:608)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at metabase.models.task_history$cleanup_task_history_BANG_.invokeStatic(task_history.clj:21)
	at metabase.models.task_history$cleanup_task_history_BANG_.invoke(task_history.clj:12)
	at metabase.task.task_history_cleanup$task_history_cleanup_BANG_.invokeStatic(task_history_cleanup.clj:29)
	at metabase.task.task_history_cleanup$task_history_cleanup_BANG_.invoke(task_history_cleanup.clj:25)
	at metabase.task.task_history_cleanup.TaskHistoryCleanup.execute(task_history_cleanup.clj:41)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	... 1 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469)
	... 36 more

**Comment by camsaul** [comment]
Fixed by #9671
