### ISSUE TITLE
Can't loginafter changing language to Turkish

### ISSUE THREAD

**Issue by smddzcy** [metabase/metabase#9011]
### Bugs

I changed my email from the team panel, and after changing my language as well, I can't login to Metabase. I get the error `Assert failed: (integer? (:id user))`.

- Your browser and the version: Chrome 70.0.3538.102 (Official Build) (64-bit)
- Your operating system: OS X 10.14.1
- Your databases: MongoDB
- Metabase version: 0.31.1
- Metabase hosting environment: Mac app
- Metabase internal database: H2

Steps to reproduce the bug:
- Log in to Metabase.
- Change your email address from admin panel.
- Change your language (in case it might be related to the language; change it to Turkish). You'll be automatically signed off.
- Try to log in again, you should get an error like this:

![image](https://user-images.githubusercontent.com/13895224/48944212-dd9b1200-ef36-11e8-8a55-804bc3dac45f.png)

**Comment by camsaul** [comment]
Hi @smddzcy do you have a stacktrace? You can look at the API response in the browser console. If you're using the Mac App you can click the link button in the top right corner to get a link to the page and open that in a browser

**Comment by camsaul** [comment]
@smddzcy are you changing the language of your entire computer?

**Comment by camsaul** [comment]
@smddzcy I'm guessing maybe what happened when you changed the language of the entire computer it did that sort of soft restart it does and closed Metabase before it got a chance to save the database file with the updated email address. Try logging in with the original email address, I have a feeling that will work.

**Comment by smddzcy** [comment]
@camsaul I'm just changing the language of Metabase, not my entire computer. I don't have a stack trace but you can easily reproduce the bug with the steps above.

I tried logging in with the old and new emails; old email gives wrong password, and the new email gives the error aboev.

**Comment by EckiA** [comment]
Same issue here. I am also using  v0.31.1. I have changed the language of Metabase in the admin section for testing (I am not 100% sure but I think I choosed Turkish language). This action caused an immediate logoff. When trying to login again I receive the same error as described above in the initial thread by @smddzcy. I would be very grateful for any suggestions.

**Comment by tlrobinson** [comment]
I've reproduced this. It only happens with Turkish, which is odd. Looks like it has something to do with this string:

```
12-05 00:42:18 ERROR util.i18n :: Unable to translate string 'User lookup filter, the placeholder '{login}' will be replaced by the user supplied login.'
java.lang.IllegalArgumentException: can't parse argument number: login
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1429)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
	at java.text.MessageFormat.<init>(MessageFormat.java:380)
	at puppetlabs.i18n.core$fmt.invoke(core.clj:250)
	at puppetlabs.i18n.core$translate.doInvoke(core.clj:257)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:663)
	at clojure.core$apply.invoke(core.clj:652)
	at metabase.util.i18n$translate.invokeStatic(i18n.clj:27)
	at metabase.util.i18n$translate.invoke(i18n.clj:20)
	at metabase.util.i18n.UserLocalizedString.toString(i18n.clj:37)
	at clojure.core$str.invokeStatic(core.clj:553)
	at clojure.core$str.invoke(core.clj:544)
	at metabase.models.setting$user_facing_info.invokeStatic(setting.clj:620)
	at metabase.models.setting$user_facing_info.invoke(setting.clj:610)
	at metabase.models.setting$all$iter__17084__17088$fn__17089.invoke(setting.clj:630)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:706)
	at clojure.core$next__5108.invokeStatic(core.clj:64)
	at clojure.core$next__5108.invoke(core.clj:64)
	at cheshire.generate$generate.invokeStatic(generate.clj:132)
	at cheshire.generate$generate.invoke(generate.clj:116)
	at cheshire.core$generate_stream.invokeStatic(core.clj:105)
	at cheshire.core$generate_stream.invoke(core.clj:80)
	at metabase.core$streamed_json_response$fn__62582.invoke(core.clj:55)
	at ring.util.io$piped_input_stream$fn__14844.invoke(io.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: For input string: "login"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1427)
	... 35 more
```

**Comment by tlrobinson** [comment]
Normally our translations use numbered arguments like `{0}` in translations so maybe it's getting confused by the `{login}` which is not intended to be an argument, though I'm not sure why it only happens for Turkish. We probably just need to escape it somehow.

```
#: src/metabase/integrations/ldap.clj
msgid "User lookup filter, the placeholder '{login}' will be replaced by the user supplied login."
msgstr "Kullanıcı arama filtresi, '{login}' yer tutucu, kullanıcı tarafından sağlanan girişle değiştirilecektir."
```

**Comment by tlrobinson** [comment]
It looks like `clj-i18n` uses https://docs.oracle.com/javase/8/docs/api/java/text/MessageFormat.html which says

> Within a String, a pair of single quotes can be used to quote any arbitrary characters except single quotes. For example, pattern string "'{0}'" represents string "{0}", not a FormatElement.

But that string already has single quotes around the `{login}` so I'm not sure what's going on:

```
  (tru "User lookup filter, the placeholder '{login}' will be replaced by the user supplied login.")
```

Worst case, we could change it to something like 

```
  (tru "User lookup filter, the placeholder '{0}' will be replaced by the user supplied login." "{login}")
```

which also has the advantage of no risk of translators translating `{login}` (which shouldn't be translated)

**Comment by walterl** [comment]
Turned out to be a bug in `clojure.java.jdbc`, which promptly [got fixed](https://github.com/clojure/java.jdbc/commit/1f1ff8144b4a9a4447b2a2fbb9e592f90ccd2659).

While that fix is not yet released, we'll use a workaround in [Toucan](https://github.com/metabase/toucan/pull/59).

I'll leave this open until Metabase's dependencies were updated to include a fix.
