### ISSUE TITLE
Sending pulse to slack no longer works after upgrade to 0.31(.1)

### ISSUE THREAD

**Issue by tschut** [metabase/metabase#9016]
- Your browser and the version: latest chrome
- Your operating system: win10
- Your databases: MongoDB
- Metabase version: latest
- Metabase hosting environment: Heroku
- Metabase internal database: Whatever is the default with a Heroku installation

After upgrading to 0.31 pulses are no longer sent to slack. Upgrading to 0.31.1 did not resolve the issue. Things I've tried:
* Setting heroku dyno size to x2 (more RAM) - no change
* Recreating the question and pulse - no change
* Recreating the slackbot - no change

Sending the pulse through e-mail works. The preview also renders fine. Sending the pulse through slack doesn't. Worse, it completely borks the metabase instance and I have to restart the Heroku dyno to get it running again.

Heroku log:
`2018-11-26T07:58:48.712378+00:00 heroku[router]: at=info method=POST path="/api/pulse/test" host=luiwammes-metabase.herokuapp.com request_id=48109bd4-c8cf-445d-97ce-01d276b64051 fwd="94.210.202.26" dyno=web.1 connect=0ms service=5630ms status=200 bytes=999 protocol=https
2018-11-26T07:58:48.709932+00:00 app[web.1]: 11-26 08:58:48 [1mERROR metabase.pulse[0m :: Error sending notification!
2018-11-26T07:58:48.709946+00:00 app[web.1]: java.lang.OutOfMemoryError: Metaspace
2018-11-26T07:58:48.709948+00:00 app[web.1]: 	at metabase.pulse.render$render_to_png.invokeStatic(render.clj:311)
2018-11-26T07:58:48.709949+00:00 app[web.1]: 	at metabase.pulse.render$render_to_png.invoke(render.clj:301)
2018-11-26T07:58:48.709951+00:00 app[web.1]: 	at metabase.pulse.render$fn__25996$render_html_to_png__26001$fn__26005.invoke(render.clj:336)
2018-11-26T07:58:48.709952+00:00 app[web.1]: 	at metabase.pulse.render$fn__25996$render_html_to_png__26001.invoke(render.clj:328)
2018-11-26T07:58:48.709954+00:00 app[web.1]: 	at metabase.pulse.render$render_pulse_card_to_png.invokeStatic(render.clj:839)
2018-11-26T07:58:48.709955+00:00 app[web.1]: 	at metabase.pulse.render$render_pulse_card_to_png.invoke(render.clj:836)
2018-11-26T07:58:48.709957+00:00 app[web.1]: 	at metabase.pulse$create_slack_attachment_data$iter__40312__40316$fn__40317$fn__40318$fn__40321.invoke(pulse.clj:69)
2018-11-26T07:58:48.709958+00:00 app[web.1]: 	at metabase.pulse$create_and_upload_slack_attachments_BANG_$iter__40335__40339$fn__40340$fn__40341.invoke(pulse.clj:80)
2018-11-26T07:58:48.709960+00:00 app[web.1]: 	at metabase.pulse$create_and_upload_slack_attachments_BANG_$iter__40335__40339$fn__40340.invoke(pulse.clj:79)
2018-11-26T07:58:48.709961+00:00 app[web.1]: 	at clojure.lang.LazySeq.sval(LazySeq.java:40)
2018-11-26T07:58:48.709962+00:00 app[web.1]: 	at clojure.lang.LazySeq.seq(LazySeq.java:49)
2018-11-26T07:58:48.709964+00:00 app[web.1]: 	at clojure.lang.RT.seq(RT.java:528)
2018-11-26T07:58:48.709965+00:00 app[web.1]: 	at clojure.core$seq__5124.invokeStatic(core.clj:137)
2018-11-26T07:58:48.709967+00:00 app[web.1]: 	at clojure.core$dorun.invokeStatic(core.clj:3125)
2018-11-26T07:58:48.709968+00:00 app[web.1]: 	at clojure.core$doall.invokeStatic(core.clj:3140)
2018-11-26T07:58:48.709969+00:00 app[web.1]: 	at clojure.core$doall.invoke(core.clj:3140)
2018-11-26T07:58:48.709971+00:00 app[web.1]: 	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:78)
2018-11-26T07:58:48.709972+00:00 app[web.1]: 	at metabase.pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:75)
2018-11-26T07:58:48.709973+00:00 app[web.1]: 	at metabase.pulse$fn__40423.invokeStatic(pulse.clj:201)
2018-11-26T07:58:48.709975+00:00 app[web.1]: 	at metabase.pulse$fn__40423.invoke(pulse.clj:199)
2018-11-26T07:58:48.709976+00:00 app[web.1]: 	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
2018-11-26T07:58:48.709978+00:00 app[web.1]: 	at metabase.pulse$send_notifications_BANG_$fn__40434.invoke(pulse.clj:217)
2018-11-26T07:58:48.709979+00:00 app[web.1]: 	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:216)
2018-11-26T07:58:48.709980+00:00 app[web.1]: 	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:212)
2018-11-26T07:58:48.709982+00:00 app[web.1]: 	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:245)
2018-11-26T07:58:48.709983+00:00 app[web.1]: 	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:236)
2018-11-26T07:58:48.709984+00:00 app[web.1]: 	at clojure.lang.RestFn.invoke(RestFn.java:410)
2018-11-26T07:58:48.709985+00:00 app[web.1]: 	at metabase.api.pulse$fn__55052.invokeStatic(pulse.clj:191)
2018-11-26T07:58:48.709987+00:00 app[web.1]: 	at metabase.api.pulse$fn__55052.invoke(pulse.clj:181)
2018-11-26T07:58:48.709988+00:00 app[web.1]: 	at compojure.core$make_route$fn__16243.invoke(core.clj:135)
2018-11-26T07:58:48.709989+00:00 app[web.1]: 	at compojure.core$wrap_route_middleware$fn__16236.invoke(core.clj:122)
2018-11-26T07:58:48.709990+00:00 app[web.1]: 	at compojure.core$wrap_route_info$fn__16240.invoke(core.clj:126)
2018-11-26T07:58:48.711161+00:00 app[web.1]: 11-26 08:58:48 [1mDEBUG metabase.middleware[0m :: [32mPOST /api/pulse/test 200 (6 s) (27 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)[0m`

It seems memory usage has increased greatly with .31? Is there any way to downgrade a Heroku install to 0.30.x?

The next bigger dyno on Heroku costs 10x as much so not really looking forward to scaling further.

**Comment by tlrobinson** [comment]
Possibly duplicate of #8967

**Comment by tschut** [comment]
> Possibly duplicate of #8967

Possibly. I didn't see the error that's reported in that issue though and the preview rendered fine.

**Comment by tlrobinson** [comment]
We think this change to `bin/start` should fix this: https://github.com/metabase/metabase-deploy/commit/c8147a7af6d135e72f00e4c4ed7d34193d4829a4

You can redeploy from scratch or modify the `bin/start` in your Heroku app

**Comment by tschut** [comment]
This fixes it for me, awesome! Thanks for the fast reply 💯 👍
