### ISSUE TITLE
Metabase does not start on a machine with Turkish locale

### ISSUE THREAD

**Issue by yagabey** [metabase/metabase#9075]
When I try to run Metabase on a Windows 10 machine with Turkish locale and display language, Metabase does not start with the floowing error output:

java -jar metabase.jar

> 12-05 16:59:50 [1mINFO metabase.util[0m :: Metataban? ynkleniyor ...
> 12-05 16:59:50 [1mINFO metabase.util[0m :: Maximum memory available to JVM: 494,9 MB
> 12-05 17:00:03 [1mINFO util.encryption[0m :: Kay?tl? kimlik bilgileri ?ifreleme, bu Metataban? ÷rne?i itin DEVRE DI?I.
>  For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
> 12-05 17:00:20 [1mINFO metabase.core[0m :: STANDALONE modunda Metataban?n? ba?latma
> 12-05 17:00:20 [1mINFO metabase.core[0m :: Config ile Embedded Jetty Web sunucusu ba?lat?l?yor:
>  {:port 3000}
> 
> 12-05 17:00:21 [1mINFO metabase.core[0m :: Metataban? snrnmn v0.31.1 (04829a7 release-0.31.1) ba?lat?l?yor ...
> 12-05 17:00:21 [1mINFO metabase.core[0m :: Sistem saat dilimi ' Europe/London ' ...
> WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
> 12-05 17:00:27 [1mINFO metabase.core[0m :: Metataban? DByi kurma ve ta??ma. Lntfen bekleyin, Bu bir dakika snrebilir ..
> 12-05 17:00:27 [1mINFO metabase.db[0m :: h2 Veritaban? Ba?lant?s? Do?rulan?yor ...
> 12-05 17:00:28 [1mINFO metabase.db[0m :: Veritaban? Ba?lant?s?n? Do?rulay?n.
> 12-05 17:00:28 [1mINFO metabase.db[0m :: Veritaban? Geti?lerini ¦al??t?rma ...
> 12-05 17:00:28 [1mINFO metabase.db[0m :: Liquibase kurulumu ...
> 12-05 17:00:29 [1mINFO metabase.db[0m :: Liquibase haz?rd?r.
> 12-05 17:00:29 [1mINFO metabase.db[0m :: Veritaban?n?n geti?leri kald?r?l?p kald?r?lmad???n? kontrol etme ...
> 12-05 17:00:39 [1mINFO metabase.db[0m :: Veritaban? Geti?leri
> 12-05 17:00:40 [1mINFO db.migrations[0m :: Running all necessary data migrations, this may take a minute.
> 12-05 17:00:40 [1mINFO db.migrations[0m :: Running data migration 'add-users-to-default-permissions-groups'...
> 12-05 17:00:40 [1mERROR metabase.core[0m :: Metataban? Ba?latma Ba?ar?s?z
> org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_A6 ON PUBLIC.DATA_MIGRATIONS(ID) VALUES ('add-users-to-default-permissions-groups', 1)"; SQL statement:
> INSERT INTO "DATA_MIGRATIONS" ("ID", "TIMESTAMP") VALUES (?, ?) [23505-197]
>         at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
>         at org.h2.message.DbException.get(DbException.java:179)
>         at org.h2.message.DbException.get(DbException.java:155)
>         at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:101)
>         at org.h2.mvstore.db.MVSecondaryIndex.requireUnique(MVSecondaryIndex.java:236)
>         at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:202)
>         at org.h2.mvstore.db.MVTable.addRow(MVTable.java:732)
>         at org.h2.command.dml.Insert.insertRows(Insert.java:182)
>         at org.h2.command.dml.Insert.update(Insert.java:134)
>         at org.h2.command.CommandContainer.update(CommandContainer.java:102)
>         at org.h2.command.Command.executeUpdate(Command.java:261)
>         at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
>         at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
>         at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)
>         at clojure.java.jdbc$db_do_execute_prepared_return_keys$exec_and_return_keys__4667.invoke(jdbc.clj:897)
>         at clojure.java.jdbc$db_do_execute_prepared_return_keys.invokeStatic(jdbc.clj:919)
>         at clojure.java.jdbc$db_do_execute_prepared_return_keys.invoke(jdbc.clj:884)
>         at clojure.java.jdbc$db_do_prepared_return_keys.invokeStatic(jdbc.clj:950)
>         at clojure.java.jdbc$db_do_prepared_return_keys.invoke(jdbc.clj:927)
>         at clojure.java.jdbc$db_do_prepared_return_keys.invokeStatic(jdbc.clj:952)
>         at clojure.java.jdbc$db_do_prepared_return_keys.invoke(jdbc.clj:927)
>         at toucan.db$simple_insert_many_BANG_$iter__6382__6386$fn__6387$fn__6388.invoke(db.clj:541)
>         at toucan.db$simple_insert_many_BANG_$iter__6382__6386$fn__6387.invoke(db.clj:539)
>         at clojure.lang.LazySeq.sval(LazySeq.java:40)
>         at clojure.lang.LazySeq.seq(LazySeq.java:49)
>         at clojure.lang.RT.seq(RT.java:528)
>         at clojure.core$seq__5124.invokeStatic(core.clj:137)
>         at clojure.core$dorun.invokeStatic(core.clj:3125)
>         at clojure.core$doall.invokeStatic(core.clj:3140)
>         at clojure.core$doall.invoke(core.clj:3140)
>         at toucan.db$simple_insert_many_BANG_.invokeStatic(db.clj:538)
>         at toucan.db$simple_insert_many_BANG_.invoke(db.clj:525)
>         at toucan.db$simple_insert_BANG_.invokeStatic(db.clj:571)
>         at toucan.db$simple_insert_BANG_.invoke(db.clj:560)
>         at toucan.db$insert_BANG_.invokeStatic(db.clj:588)
>         at toucan.db$insert_BANG_.invoke(db.clj:575)
>         at toucan.db$insert_BANG_.invokeStatic(db.clj:591)
>         at toucan.db$insert_BANG_.doInvoke(db.clj:575)
>         at clojure.lang.RestFn.invoke(RestFn.java:494)
>         at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:53)
>         at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:43)
>         at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:72)
>         at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:66)
>         at clojure.lang.Var.invoke(Var.java:377)
>         at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:445)
>         at metabase.db$run_data_migrations_BANG_.invoke(db.clj:440)
>         at metabase.db$setup_db_BANG_.invokeStatic(db.clj:456)
>         at metabase.db$setup_db_BANG_.doInvoke(db.clj:447)
>         at clojure.lang.RestFn.invoke(RestFn.java:421)
>         at metabase.core$init_BANG_.invokeStatic(core.clj:162)
>         at metabase.core$init_BANG_.invoke(core.clj:139)
>         at metabase.core$start_normally.invokeStatic(core.clj:246)
>         at metabase.core$start_normally.invoke(core.clj:240)
>         at metabase.core$_main.invokeStatic(core.clj:266)
>         at metabase.core$_main.doInvoke(core.clj:261)
>         at clojure.lang.RestFn.invoke(RestFn.java:397)
>         at clojure.lang.AFn.applyToHelper(AFn.java:152)
>         at clojure.lang.RestFn.applyTo(RestFn.java:132)
>         at metabase.core.main(Unknown Source)
> 

I didn't have these issue on systems with english locale.

**Comment by flamber** [comment]
Looks like you're not the only one: issue #9073

**Comment by yagabey** [comment]
> Looks like you're not the only one: issue #9073

Yes it seems so :)

**Comment by tlrobinson** [comment]
Related to / duplicate of #9011
