### ISSUE TITLE
Lock and close connection to internal database and cannot access GUI.

### ISSUE THREAD

**Issue by KosukeTsumura** [metabase/metabase#9332]
# Bugs

Metabase is unstable in my environment.
For example, After one month launching metabase, we cannot access web UI.
But looks like open port 443 for https.
It's not first experience. It already happened in our dev environment. The specification of dev and production is almost same.
If the issue is already exists and report resolution, please let me know...

I guess metabase cannot access internal database and then we cannot open GUI. 

I described information as follows,
```
- Your browser and the version: Any
- Your operating system: windows/ mac os
- Your databases: postgresql
- Metabase version: 0.31.1
- Metabase hosting environment: Ubuntu 16.04.5
- Metabase internal database: H2 
```

### Logs

```bash
01-22 11:15:42 [1mINFO api.common[0m :: [33mconnection closed, canceling request[0m
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:286)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:323)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:804)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:538)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:795)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:846)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:240)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:216)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:398)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
	at metabase.api.common$fn__23150$fn__23151.invoke(common.clj:396)
	at metabase.api.common$fn__23150.invokeStatic(common.clj:394)
	at metabase.api.common$fn__23150.invoke(common.clj:385)
	at ring.core.protocols$fn__23042$G__23037__23051.invoke(protocols.clj:8)
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:106)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.util.servlet$update_servlet_response.invokeStatic(servlet.clj:95)
	at ring.util.servlet$update_servlet_response.invoke(servlet.clj:91)
	at ring.adapter.jetty$proxy_handler$fn__62177.invoke(jetty.clj:26)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:266)
	... 36 more
01-22 11:15:47 [1mDEBUG metabase.middleware[0m :: [32mGET /api/database/2/autocomplete_suggestions 200 (70 ms) (6 DB calls). Jetty threads: 8/50 (5 busy, 2 idle, 0 queued)[0m
01-22 11:15:48 [1mWARN metabase.query-processor[0m :: [31mQuery failure: The object is already closed; SQL statement:
INSERT INTO "QUERY" ("QUERY", "QUERY_HASH", "AVERAGE_EXECUTION_TIME") VALUES (?, ?, 13011) [90007-197]
("org.h2.message.DbException.getJdbcSQLException(DbException.java:357)"
 "org.h2.message.DbException.get(DbException.java:168)"
 "org.h2.store.LobStorageMap.createClob(LobStorageMap.java:204)"
 "org.h2.value.ValueLobDb.copy(ValueLobDb.java:254)"
 "org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:105)"
 "org.h2.mvstore.db.MVTable.addRow(MVTable.java:732)"
 "org.h2.command.dml.Insert.insertRows(Insert.java:182)"
 "org.h2.command.dml.Insert.update(Insert.java:134)"
 "org.h2.command.CommandContainer.update(CommandContainer.java:102)"
 "org.h2.command.Command.executeUpdate(Command.java:261)"
 "org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)"
 "org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)"
 "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)"
 "clojure.java.jdbc$db_do_execute_prepared_return_keys$exec_and_return_keys__4667.invoke(jdbc.clj:897)"
 "clojure.java.jdbc$db_do_execute_prepared_return_keys.invokeStatic(jdbc.clj:919)"
 "clojure.java.jdbc$db_do_execute_prepared_return_keys.invoke(jdbc.clj:884)"
 "clojure.java.jdbc$db_do_prepared_return_keys.invokeStatic(jdbc.clj:950)"
 "clojure.java.jdbc$db_do_prepared_return_keys.invoke(jdbc.clj:927)"
 "clojure.java.jdbc$db_do_prepared_return_keys.invokeStatic(jdbc.clj:952)"
 "clojure.java.jdbc$db_do_prepared_return_keys.invoke(jdbc.clj:927)"
 "toucan.db$simple_insert_many_BANG_$iter__6382__6386$fn__6387$fn__6388.invoke(db.clj:541)"
 "toucan.db$simple_insert_many_BANG_$iter__6382__6386$fn__6387.invoke(db.clj:539)"
 "clojure.lang.LazySeq.sval(LazySeq.java:40)"
 "clojure.lang.LazySeq.seq(LazySeq.java:49)"
 "clojure.lang.RT.seq(RT.java:528)"
 "clojure.core$seq__5124.invokeStatic(core.clj:137)"
 "clojure.core$dorun.invokeStatic(core.clj:3125)"
 "clojure.core$doall.invokeStatic(core.clj:3140)"
 "clojure.core$doall.invoke(core.clj:3140)"
 "toucan.db$simple_insert_many_BANG_.invokeStatic(db.clj:538)"
 "toucan.db$simple_insert_many_BANG_.invoke(db.clj:525)"
 "toucan.db$simple_insert_BANG_.invokeStatic(db.clj:571)"
 "toucan.db$simple_insert_BANG_.invoke(db.clj:560)"
 "toucan.db$insert_BANG_.invokeStatic(db.clj:588)"
 "toucan.db$insert_BANG_.invoke(db.clj:575)"
 "toucan.db$insert_BANG_.invokeStatic(db.clj:591)"
 "toucan.db$insert_BANG_.doInvoke(db.clj:575)"
 "clojure.lang.RestFn.invoke(RestFn.java:573)"
 "--> models.query$record_new_query_entry_BANG_.invokeStatic(query.clj:61)"
 "models.query$record_new_query_entry_BANG_.invoke(query.clj:57)"
 "models.query$save_query_and_update_average_execution_time_BANG_.invokeStatic(query.clj:75)"
 "models.query$save_query_and_update_average_execution_time_BANG_.invoke(query.clj:66)"
 "query_processor$save_query_execution_BANG_.invokeStatic(query_processor.clj:231)"
 "query_processor$save_query_execution_BANG_.invoke(query_processor.clj:227)"
 "query_processor$save_and_return_successful_query_BANG_.invokeStatic(query_processor.clj:268)"
 "query_processor$save_and_return_successful_query_BANG_.invoke(query_processor.clj:257)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:324)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
 "query_processor$fn__37661$process_query_and_save_execution_BANG___37666$fn__37667.invoke(query_processor.clj:354)"
 "query_processor$fn__37661$process_query_and_save_execution_BANG___37666.invoke(query_processor.clj:340)"
 "query_processor$fn__37685$process_query_and_save_with_max_BANG___37690$fn__37691.invoke(query_processor.clj:373)"
 "query_processor$fn__37685$process_query_and_save_with_max_BANG___37690.invoke(query_processor.clj:369)"
 "api.dataset$fn__44186$fn__44189.invoke(dataset.clj:45)"
 "api.common$fn__23166$invoke_thunk_with_keepalive__23171$fn__23172$fn__23173.invoke(common.clj:435)")
[0m
01-22 11:15:49 [1mERROR jdbcjobstore.JobStoreTX[0m :: Couldn't rollback jdbc connection. The database has been closed [90098-197]
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1686)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1696)
	at org.h2.engine.Session.setSavepoint(Session.java:859)
	at org.h2.command.Command.executeUpdate(Command.java:255)
	at org.h2.jdbc.JdbcConnection.rollbackInternal(JdbcConnection.java:1558)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:518)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:1033)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
	at com.sun.proxy.$Proxy12.rollback(Unknown Source)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.rollbackConnection(JobStoreSupport.java:3639)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3264)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3857)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3894)
01-22 11:15:49 [1mWARN jdbcjobstore.AttributeRestoringConnectionInvocationHandler[0m :: Failed restore connection's original auto commit setting.
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Session.getTransaction(Session.java:1686)
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1696)
	at org.h2.engine.Session.setSavepoint(Session.java:859)
	at org.h2.command.Command.executeUpdate(Command.java:255)
	at org.h2.jdbc.JdbcConnection.commit(JdbcConnection.java:497)
	at org.h2.jdbc.JdbcConnection.setAutoCommit(JdbcConnection.java:457)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.setAutoCommit(NewProxyConnection.java:1059)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.restoreOriginalAtributes(AttributeRestoringConnectionInvocationHandler.java:141)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.cleanupConnection(JobStoreSupport.java:3589)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3273)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3857)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3894)
01-22 11:15:49 [1mERROR jdbcjobstore.JobStoreTX[0m :: ClusterManager: Error managing cluster: Failure identifying failed instances when checking-in: The database has been closed [90098-197]
org.quartz.JobPersistenceException: Failure identifying failed instances when checking-in: The database has been closed [90098-197] [See nested exception: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.findFailedInstances(JobStoreSupport.java:3330)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.clusterCheckIn(JobStoreSupport.java:3380)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3240)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3857)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3894)
Caused by: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Database.checkPowerOff(Database.java:536)
	at org.h2.command.Command.executeQuery(Command.java:228)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:353)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectSchedulerStateRecords(StdJDBCDelegate.java:2949)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.findFailedInstances(JobStoreSupport.java:3294)
	... 4 more
```

**Comment by flamber** [comment]
Hi @KosukeTsumura 
Without being an expert in H2, those errors looks like something is crashing the database - maybe a corruption. Are those the only error logs you see - there's nothing a little earlier?
I would highly recommend that you use Postgres or MySQL as internal database, since H2 is not meant to run in production and is prone to corruption.
https://www.metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres

**Comment by KosukeTsumura** [comment]
Hi @flamber 
Thank you for your comment.
I understand if running as production, have to use postgres or mysql for internal database.

I found another logs before above error log as follows,

```bash
01-22 11:01:35 [1mWARN metabase.query-processor[0m :: [31m{:status :failed,
 :class java.util.concurrent.ExecutionException,
 :error "org.postgresql.util.PSQLException: ERROR: column o.id does not exist\n  Hint: Perhaps you meant to reference the column \"s.id\" or the column \"b.id\".\n  Position: 559",
 :stacktrace
 ("java.util.concurrent.FutureTask.report(FutureTask.java:122)"
  "java.util.concurrent.FutureTask.get(FutureTask.java:192)"
  "clojure.core$deref_future.invokeStatic(core.clj:2292)"
  "clojure.core$future_call$reify__8097.deref(core.clj:6894)"
  "clojure.core$deref.invokeStatic(core.clj:2312)"
  "clojure.core$deref.invoke(core.clj:2298)"
  "--> driver.generic_sql.query_processor$cancellable_run_query.invokeStatic(query_processor.clj:620)"
  "driver.generic_sql.query_processor$cancellable_run_query.invoke(query_processor.clj:612)"
  "driver.generic_sql.query_processor$run_query.invokeStatic(query_processor.clj:637)"
  "driver.generic_sql.query_processor$run_query.invoke(query_processor.clj:632)"
  "driver.generic_sql.query_processor$do_with_auto_commit_disabled.invokeStatic(query_processor.clj:675)"
  "driver.generic_sql.query_processor$do_with_auto_commit_disabled.invoke(query_processor.clj:664)"
  "driver.generic_sql.query_processor$do_in_transaction$fn__57831.invoke(query_processor.clj:680)"
  "driver.generic_sql.query_processor$do_in_transaction.invokeStatic(query_processor.clj:679)"
  "driver.generic_sql.query_processor$do_in_transaction.invoke(query_processor.clj:678)"
  "driver.generic_sql.query_processor$run_query_without_timezone.invokeStatic(query_processor.clj:696)"
  "driver.generic_sql.query_processor$run_query_without_timezone.invoke(query_processor.clj:695)"
  "driver.generic_sql.query_processor$execute_query$fn__57855.invoke(query_processor.clj:723)"
  "driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:659)"
  "driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:654)"
  "driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:720)"
  "driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:716)"
  "driver$fn__29952$G__29759__29959.invoke(driver.clj:106)"
  "query_processor$execute_query.invokeStatic(query_processor.clj:66)"
  "query_processor$execute_query.invoke(query_processor.clj:60)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__32452.invoke(mbql_to_native.clj:36)"
  "query_processor.middleware.annotate$add_column_info$fn__31207.invoke(annotate.clj:300)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__31914.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.limit$limit$fn__32405.invoke(limit.clj:17)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__37481.invoke(results_metadata.clj:87)"
  "query_processor.middleware.format_rows$format_rows$fn__32395.invoke(format_rows.clj:26)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__30551.invoke(add_dimension_projections.clj:234)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__30839.invoke(add_row_count_and_status.clj:15)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__32156.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__35279.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31351$fn__31352.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31351.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__37496$fn__37497.invoke(store.clj:11)"
  "query_processor.store$do_with_new_store.invokeStatic(store.clj:34)"
  "query_processor.store$do_with_new_store.invoke(store.clj:30)"
  "query_processor.middleware.store$initialize_store$fn__37496.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__31773.invoke(cache.clj:127)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__31821.invoke(catch_exceptions.clj:64)"
  "query_processor$process_query.invokeStatic(query_processor.clj:213)"
  "query_processor$process_query.invoke(query_processor.clj:209)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:322)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
  "query_processor$fn__37661$process_query_and_save_execution_BANG___37666$fn__37667.invoke(query_processor.clj:354)"
  "query_processor$fn__37661$process_query_and_save_execution_BANG___37666.invoke(query_processor.clj:340)"
  "query_processor$fn__37685$process_query_and_save_with_max_BANG___37690$fn__37691.invoke(query_processor.clj:373)"
  "query_processor$fn__37685$process_query_and_save_with_max_BANG___37690.invoke(query_processor.clj:369)"
  "api.dataset$fn__44186$fn__44189.invoke(dataset.clj:45)"
  "api.common$fn__23166$invoke_thunk_with_keepalive__23171$fn__23172$fn__23173.invoke(common.clj:435)"),
 :query
 {:type "native",
  :native
  {:query
   "SELECT COUNT(*)\nFROM orders o\n    JOIN services s ON s.initial_order = o.order_id\n    JOIN customers c ON o.customer = customer_id\n    JOIN buildings b ON s.primary_location = b.id\n    JOIN data_centers dc ON b.data_center = dc.id\n    JOIN service_defs sd ON s.service_def = sd.id\n    JOIN service_def_sub_categories sdsc ON sd.sub_category = sdsc.id\n    JOIN service_def_categories sdc ON sdsc.category = sdc.id\nWHERE sdc.id = 33\nGROUP BY o.id;\n",
   :template-tags {}},
  :parameters [],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 2,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [52, -66, 33, -54, -69, 23, 24, -66, 126, 127, 20, 8, 80, 85, -103, 5, -77, -93, -47, -71, -24, -116, 52, 87, -103, 121, -83, 27, 20, 30, 17, -12],
   :query-type "native"}}}
[0m
01-22 11:01:35 [1mWARN metabase.query-processor[0m :: [31mQuery failure: org.postgresql.util.PSQLException: ERROR: column o.id does not exist
  Hint: Perhaps you meant to reference the column "s.id" or the column "b.id".
  Position: 559
("clojure.core$ex_info.invokeStatic(core.clj:4739)"
 "clojure.core$ex_info.invoke(core.clj:4739)"
 "--> query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:285)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:277)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:323)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
 "query_processor$fn__37661$process_query_and_save_execution_BANG___37666$fn__37667.invoke(query_processor.clj:354)"
 "query_processor$fn__37661$process_query_and_save_execution_BANG___37666.invoke(query_processor.clj:340)"
 "query_processor$fn__37685$process_query_and_save_with_max_BANG___37690$fn__37691.invoke(query_processor.clj:373)"
 "query_processor$fn__37685$process_query_and_save_with_max_BANG___37690.invoke(query_processor.clj:369)"
 "api.dataset$fn__44186$fn__44189.invoke(dataset.clj:45)"
 "api.common$fn__23166$invoke_thunk_with_keepalive__23171$fn__23172$fn__23173.invoke(common.clj:435)")
[0m
01-22 11:01:35 [1mDEBUG metabase.middleware[0m :: [32mPOST /api/dataset 200 (166 ms) (9 DB calls). Jetty threads: 8/50 (5 busy, 2 idle, 0 queued)[0m
01-22 11:02:18 [1mWARN metabase.query-processor[0m :: [31m{:status :failed,
 :class java.util.concurrent.ExecutionException,
 :error "org.postgresql.util.PSQLException: ERROR: column o.id does not exist\n  Hint: Perhaps you meant to reference the column \"s.id\".\n  Position: 410",
 :stacktrace
 ("java.util.concurrent.FutureTask.report(FutureTask.java:122)"
  "java.util.concurrent.FutureTask.get(FutureTask.java:192)"
  "clojure.core$deref_future.invokeStatic(core.clj:2292)"
  "clojure.core$future_call$reify__8097.deref(core.clj:6894)"
  "clojure.core$deref.invokeStatic(core.clj:2312)"
  "clojure.core$deref.invoke(core.clj:2298)"
  "--> driver.generic_sql.query_processor$cancellable_run_query.invokeStatic(query_processor.clj:620)"
  "driver.generic_sql.query_processor$cancellable_run_query.invoke(query_processor.clj:612)"
  "driver.generic_sql.query_processor$run_query.invokeStatic(query_processor.clj:637)"
  "driver.generic_sql.query_processor$run_query.invoke(query_processor.clj:632)"
  "driver.generic_sql.query_processor$do_with_auto_commit_disabled.invokeStatic(query_processor.clj:675)"
  "driver.generic_sql.query_processor$do_with_auto_commit_disabled.invoke(query_processor.clj:664)"
  "driver.generic_sql.query_processor$do_in_transaction$fn__57831.invoke(query_processor.clj:680)"
  "driver.generic_sql.query_processor$do_in_transaction.invokeStatic(query_processor.clj:679)"
  "driver.generic_sql.query_processor$do_in_transaction.invoke(query_processor.clj:678)"
  "driver.generic_sql.query_processor$run_query_without_timezone.invokeStatic(query_processor.clj:696)"
  "driver.generic_sql.query_processor$run_query_without_timezone.invoke(query_processor.clj:695)"
  "driver.generic_sql.query_processor$execute_query$fn__57855.invoke(query_processor.clj:723)"
  "driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:659)"
  "driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:654)"
  "driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:720)"
  "driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:716)"
  "driver$fn__29952$G__29759__29959.invoke(driver.clj:106)"
  "query_processor$execute_query.invokeStatic(query_processor.clj:66)"
  "query_processor$execute_query.invoke(query_processor.clj:60)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__32452.invoke(mbql_to_native.clj:36)"
  "query_processor.middleware.annotate$add_column_info$fn__31207.invoke(annotate.clj:300)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__31914.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.limit$limit$fn__32405.invoke(limit.clj:17)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__37481.invoke(results_metadata.clj:87)"
  "query_processor.middleware.format_rows$format_rows$fn__32395.invoke(format_rows.clj:26)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__30551.invoke(add_dimension_projections.clj:234)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__30839.invoke(add_row_count_and_status.clj:15)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__32156.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__35279.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31351$fn__31352.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31351.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__37496$fn__37497.invoke(store.clj:11)"
  "query_processor.store$do_with_new_store.invokeStatic(store.clj:34)"
  "query_processor.store$do_with_new_store.invoke(store.clj:30)"
  "query_processor.middleware.store$initialize_store$fn__37496.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__31773.invoke(cache.clj:127)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__31821.invoke(catch_exceptions.clj:64)"
  "query_processor$process_query.invokeStatic(query_processor.clj:213)"
  "query_processor$process_query.invoke(query_processor.clj:209)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:322)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
  "query_processor$fn__37661$process_query_and_save_execution_BANG___37666$fn__37667.invoke(query_processor.clj:354)"
  "query_processor$fn__37661$process_query_and_save_execution_BANG___37666.invoke(query_processor.clj:340)"
  "query_processor$fn__37685$process_query_and_save_with_max_BANG___37690$fn__37691.invoke(query_processor.clj:373)"
  "query_processor$fn__37685$process_query_and_save_with_max_BANG___37690.invoke(query_processor.clj:369)"
  "api.dataset$fn__44186$fn__44189.invoke(dataset.clj:45)"
  "api.common$fn__23166$invoke_thunk_with_keepalive__23171$fn__23172$fn__23173.invoke(common.clj:435)"),
 :query
 {:type "native",
  :native
  {:query
   "SELECT COUNT(*)\nFROM orders o\n    JOIN services s ON s.initial_order = o.order_id\n    JOIN service_defs sd ON s.service_def = sd.id\n    JOIN service_def_sub_categories sdsc ON sd.sub_category = sdsc.id\n    JOIN service_def_categories sdc ON sdsc.category = sdc.id\nWHERE sdc.id = 33\nGROUP BY o.id;",
   :template-tags {}},
  :parameters [],
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 2,
   :context :ad-hoc,
   :card-id nil,
   :nested? false,
   :query-hash [3, 102, -5, 99, 39, -71, -40, 24, 97, 0, -110, 56, 96, 41, -24, 9, 30, -53, 16, 16, 20, 25, -106, -74, -108, -22, -19, -114, 9, 49, 114, 52],
   :query-type "native"}}}
[0m
01-22 11:02:18 [1mWARN metabase.query-processor[0m :: [31mQuery failure: org.postgresql.util.PSQLException: ERROR: column o.id does not exist
  Hint: Perhaps you meant to reference the column "s.id".
  Position: 410
("clojure.core$ex_info.invokeStatic(core.clj:4739)"
 "clojure.core$ex_info.invoke(core.clj:4739)"
 "--> query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:285)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:277)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:323)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
 "query_processor$fn__37661$process_query_and_save_execution_BANG___37666$fn__37667.invoke(query_processor.clj:354)"
 "query_processor$fn__37661$process_query_and_save_execution_BANG___37666.invoke(query_processor.clj:340)"
 "query_processor$fn__37685$process_query_and_save_with_max_BANG___37690$fn__37691.invoke(query_processor.clj:373)"
 "query_processor$fn__37685$process_query_and_save_with_max_BANG___37690.invoke(query_processor.clj:369)"
 "api.dataset$fn__44186$fn__44189.invoke(dataset.clj:45)"
 "api.common$fn__23166$invoke_thunk_with_keepalive__23171$fn__23172$fn__23173.invoke(common.clj:435)")
[0m
```

**Comment by salsakran** [comment]
@KosukeTsumura it looks like the filesystem is misbehaving.

What kind of server are you running this on?

**Comment by camsaul** [comment]
Closing since we never got requested information and this stuff was reworked and improved in 0.32.x
