### ISSUE TITLE
Metabase Initialization FAILED: metabase.core$jetty_ssl_config

### ISSUE THREAD

**Issue by RMMSecurity** [metabase/metabase#9333]
- Your browser and the version: Chrome (71.0.3578.98), Firefox (64.0)
- Your operating system: Windows 10
- Your databases: MySQL, MSSQL
- Metabase version: master (v0.32.0-snapshot)
- Metabase hosting environment: Windows Server 2012, Windows Server 2016 (JAR), Windows 10 WSL
- Metabase internal database: MySQL

#9308 - Commit: 954e8fe5ee1856dd165a06ac9154afed3fa3d761 introduced a bug that occurs when I start it with SSL:

```

01-28 02:54:40 [1mINFO metabase.core[0m :: Starting Metabase in STANDALONE mode
01-28 02:54:40 [1mERROR metabase.core[0m :: Metabase Initialization FAILED
java.lang.IllegalArgumentException: Don't know how to create ISeq from: metabase.core$jetty_ssl_config
	at clojure.lang.RT.seqFrom(RT.java:553)
	at clojure.lang.RT.seq(RT.java:533)
	at clojure.lang.APersistentMap.cons(APersistentMap.java:40)
	at clojure.lang.RT.conj(RT.java:673)
	at clojure.core$conj__5375.invokeStatic(core.clj:85)
	at clojure.core$merge$fn__5943.invoke(core.clj:3049)
	at clojure.core$reduce1.invokeStatic(core.clj:944)
	at clojure.core$reduce1.invokeStatic(core.clj:934)
	at clojure.core$merge.invokeStatic(core.clj:3048)
	at clojure.core$merge.doInvoke(core.clj:3041)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$jetty_config.invokeStatic(core.clj:217)
	at metabase.core$jetty_config.invoke(core.clj:208)
	at metabase.core$start_jetty_BANG_.invokeStatic(core.clj:224)
	at metabase.core$start_jetty_BANG_.invoke(core.clj:219)
	at metabase.core$start_normally.invokeStatic(core.clj:248)
	at metabase.core$start_normally.invoke(core.clj:244)
	at metabase.core$_main.invokeStatic(core.clj:270)
	at metabase.core$_main.doInvoke(core.clj:265)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)

```

Reverting the commit for 954e8fe5ee1856dd165a06ac9154afed3fa3d761 then looking at the logs on startup shows:

```
01-28 04:43:59 [1mINFO metabase.core[0m :: Starting Metabase in STANDALONE mode
01-28 04:43:59 [1mINFO metabase.core[0m :: Launching Embedded Jetty Webserver with config: 
 {:port 3000, :host "0.0.0.0", :ssl? true, :ssl-port 8443, :keystore "C:\\[Sensitive-Info-Removed].jks"}

01-28 04:44:00 [1mWARN SslContextFactory.config[0m :: No Client EndPointIdentificationAlgorithm configured for SslContextFactory@450897d[provider=null,keyStore=file:///C:/[Sensitive-Info-Removed].jks,trustStore=null]
01-28 04:44:00 [1mINFO metabase.core[0m :: Starting Metabase version v0.32.0-snapshot (344b694 master) ...
01-28 04:44:00 [1mINFO metabase.core[0m :: System timezone is 'America/New_York' ...
```

Followed by a successful startup. Now we never needed the truststore filled out before and I only ran into this behavior when I was testing this in staging.  

@camsaul just a heads up!

**Comment by camsaul** [comment]
Oops, sorry about that. I’ll fix it

**Comment by sumiodz** [comment]
Hello
I am using jetty ssl in metabase compilation its working on ssl but connect is not secure i am having this warning  No Client EndPointIdentificationAlgorithm configured for SslContextFactory@7decdae9[provider=null,keyStore=file:///var/www/html/metabase/sfdcsec.ks,trustStore=null]

Please let me know how i can solve this

**Comment by RMMSecurity** [comment]
Create a separate issue and ask there as this one is closed. Be sure to fill out all the info it asks for so they can better help you.
