### ISSUE TITLE
Metabase hangs with unknown reason, CPU usage full, saying "The database(H2) has been closed"

### ISSUE THREAD

**Issue by wxiaoguang** [metabase/metabase#9465]
- Your databases: (e.x. MariaDB)
- Metabase version: (e.x. 0.31.2)
- Metabase hosting environment: (e.x. Debian 9)
- Metabase internal database: (e.x. H2)

- *Repeatable steps to reproduce the issue*

After long time run, the metabase hangs and CPU is full (400% at a 4 core cpu)

`kill` doesn't work and I have to do `kill -9` to force terminating. Sorry I forgot to do `jstack`.

```
02-21 08:02:32 DEBUG sync.util :: STARTING: step 'sync-fks' for mysql Database 2 'xxxxxxx'
02-21 08:43:12 DEBUG metabase.middleware :: GET /api/user/current 200 (29 mins) (2 DB calls). Jetty threads: 8/50 (34 busy, 2 idle, 0 queued)
02-21 08:43:27 ERROR jdbcjobstore.JobStoreTX :: Couldn't rollback jdbc connection. The database has been closed [90098-197]
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.message.DbException.get(DbException.java:144)
        at org.h2.engine.Session.getTransaction(Session.java:1686)
        at org.h2.engine.Session.getStatementSavepoint(Session.java:1696)
        at org.h2.engine.Session.setSavepoint(Session.java:859)
        at org.h2.command.Command.executeUpdate(Command.java:255)
        at org.h2.jdbc.JdbcConnection.rollbackInternal(JdbcConnection.java:1558)
        at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:518)
        at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:1033)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
        at com.sun.proxy.$Proxy12.rollback(Unknown Source)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.rollbackConnection(JobStoreSupport.java:3639)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3264)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3857)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3894)
02-21 08:43:31 WARN server.HttpChannel :: /api/collection/root
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]                                                                                                                          [665/1998]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.message.DbException.get(DbException.java:144)
        at org.h2.engine.Database.checkPowerOff(Database.java:536)
        at org.h2.command.Command.executeQuery(Command.java:228)
        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:353)
        at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1002)
        at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:996)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1025)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1005)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1099)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1056)
        at toucan.db$query.invokeStatic(db.clj:275)
        at toucan.db$query.doInvoke(db.clj:271)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at toucan.db$simple_select.invokeStatic(db.clj:379)
        at toucan.db$simple_select.invoke(db.clj:368)
        at toucan.db$simple_select_one.invokeStatic(db.clj:405)
        at toucan.db$simple_select_one.invoke(db.clj:394)
        at toucan.db$select_one.invokeStatic(db.clj:606)
        at toucan.db$select_one.doInvoke(db.clj:599)
        at clojure.lang.RestFn.invoke(RestFn.java:516)
        at metabase.middleware$session_with_id.invokeStatic(middleware.clj:73)
        at metabase.middleware$session_with_id.invoke(middleware.clj:70)
        at metabase.middleware$current_user_info_for_session.invokeStatic(middleware.clj:94)
        at metabase.middleware$current_user_info_for_session.invoke(middleware.clj:90)
        at metabase.middleware$add_current_user_info.invokeStatic(middleware.clj:100)
        at metabase.middleware$add_current_user_info.invoke(middleware.clj:99)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at metabase.middleware$maybe_set_site_url$fn__56239.invoke(middleware.clj:290)
        at puppetlabs.i18n.core$locale_negotiator$fn__124.invoke(core.clj:357)
        at ring.middleware.cookies$wrap_cookies$fn__62401.invoke(cookies.clj:175)
        at ring.middleware.session$wrap_session$fn__62658.invoke(session.clj:108)
        at metabase.middleware$add_content_type$fn__56232.invoke(middleware.clj:262)
        at ring.middleware.gzip$wrap_gzip$fn__62432.invoke(gzip.clj:65)
        at ring.adapter.jetty$proxy_handler$fn__62260.invoke(jetty.clj:25)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)                                                                                                      [623/1998]
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.lang.Thread.run(Thread.java:748)
02-21 08:43:41 ERROR jdbcjobstore.JobStoreTX :: Couldn't rollback jdbc connection. The database has been closed [90098-197]
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.message.DbException.get(DbException.java:144)
        at org.h2.engine.Session.getTransaction(Session.java:1686)
        at org.h2.engine.Session.getStatementSavepoint(Session.java:1696)
        at org.h2.engine.Session.setSavepoint(Session.java:859)
        at org.h2.command.Command.executeUpdate(Command.java:255)
        at org.h2.jdbc.JdbcConnection.rollbackInternal(JdbcConnection.java:1558)
        at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:518)
        at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:1033)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
        at com.sun.proxy.$Proxy12.rollback(Unknown Source)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.rollbackConnection(JobStoreSupport.java:3639)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3183)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3934)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3955)
02-21 08:43:41 WARN server.HttpChannel :: /api/dashboard/1
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.message.DbException.get(DbException.java:144)
        at org.h2.engine.Database.checkPowerOff(Database.java:536)
        at org.h2.command.Command.executeQuery(Command.java:228)
        at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:353)
        at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1002)
        at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:996)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1025)                                                                                                          [578/1998]
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1005)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1099)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1056)
        at toucan.db$query.invokeStatic(db.clj:275)
        at toucan.db$query.doInvoke(db.clj:271)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at toucan.db$simple_select.invokeStatic(db.clj:379)
        at toucan.db$simple_select.invoke(db.clj:368)
        at toucan.db$simple_select_one.invokeStatic(db.clj:405)
        at toucan.db$simple_select_one.invoke(db.clj:394)
        at toucan.db$select_one.invokeStatic(db.clj:606)
        at toucan.db$select_one.doInvoke(db.clj:599)
        at clojure.lang.RestFn.invoke(RestFn.java:516)
        at metabase.middleware$session_with_id.invokeStatic(middleware.clj:73)
        at metabase.middleware$session_with_id.invoke(middleware.clj:70)
        at metabase.middleware$current_user_info_for_session.invokeStatic(middleware.clj:94)
        at metabase.middleware$current_user_info_for_session.invoke(middleware.clj:90)
        at metabase.middleware$add_current_user_info.invokeStatic(middleware.clj:100)
        at metabase.middleware$add_current_user_info.invoke(middleware.clj:99)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at clojure.core$comp$fn__5529.invoke(core.clj:2561)
        at metabase.middleware$maybe_set_site_url$fn__56239.invoke(middleware.clj:290)
        at puppetlabs.i18n.core$locale_negotiator$fn__124.invoke(core.clj:357)
        at ring.middleware.cookies$wrap_cookies$fn__62401.invoke(cookies.clj:175)
        at ring.middleware.session$wrap_session$fn__62658.invoke(session.clj:108)
        at metabase.middleware$add_content_type$fn__56232.invoke(middleware.clj:262)
        at ring.middleware.gzip$wrap_gzip$fn__62432.invoke(gzip.clj:65)
        at ring.adapter.jetty$proxy_handler$fn__62260.invoke(jetty.clj:25)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by salsakran** [comment]
this looks like there are too many long running queries running that are saturating the threadpool.

we moved to an async model in 0.32, and I'd suggest upgrading as that should solve this entire class of stability problems.

**Comment by salsakran** [comment]
closing since I'm 99% sure this specific failure mode no longer exists, but if it happens with 0.32, please chime in and I'll re-open.
