### ISSUE TITLE
`java.lang.AssertionError: Assert failed: (isa? type-keyword :type/*)` when deploying Jar to Cloud Foundry

### ISSUE THREAD

**Issue by zilkey** [metabase/metabase#9526]
I'm deploying the metabase jar (downloaded from https://metabase.com/start/jar.html -  v0.31.2) to Cloud Foundry on IBM Bluemix.  I realize this isn't a place to find support for Cloud Foundry-related issues, but this appears to be a bug since it runs fine in Docker and locally.

When I try to start the app, I get the following error:

```
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 03-07 06:09:20 ERROR metabase.core :: Metabase Initialization FAILED
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT java.lang.AssertionError: Assert failed: (isa? type-keyword :type/*)
```

The line it appears to be failing on is https://github.com/metabase/metabase/blob/67c79e6d334f531b59c3de41c988c0ed903f6c17/src/metabase/db/migrations.clj#L267

I created the app like so:

```
export APP_NAME=my-metabase-app
cf create-service compose-for-postgresql Standard metabase-db
cf push "$APP_NAME" -p metabase.jar -b https://github.com/cloudfoundry/java-buildpack.git --no-start -m 1GB
cf set-env "$APP_NAME" MB_DB_TYPE postgres
cf set-env "$APP_NAME" MB_DB_DBNAME compose
cf set-env "$APP_NAME" MB_DB_PORT 12345
cf set-env "$APP_NAME" MB_DB_USER admin
cf set-env "$APP_NAME" MB_DB_PASS password
cf set-env "$APP_NAME" MB_DB_HOST host.dblayer.com
cf set-env "$APP_NAME" MB_ENCRYPTION_SECRET_KEY `openssl rand -base64 32`
cf set-env "$APP_NAME" MB_JETTY_PORT 8080
cf start "$APP_NAME"
```

The full stack trace looks like this:

```
2019-03-07T00:09:11.68-0600 [APP/PROC/WEB/0] OUT 03-07 06:09:11 INFO metabase.db :: Verify Database Connection ...  ✅
   2019-03-07T00:09:11.68-0600 [APP/PROC/WEB/0] OUT 03-07 06:09:11 INFO metabase.db :: Running Database Migrations...
   2019-03-07T00:09:11.71-0600 [APP/PROC/WEB/0] OUT 03-07 06:09:11 INFO metabase.db :: Setting up Liquibase...
   2019-03-07T00:09:12.12-0600 [APP/PROC/WEB/0] OUT 03-07 06:09:12 INFO metabase.db :: Liquibase is ready.
   2019-03-07T00:09:12.12-0600 [APP/PROC/WEB/0] OUT 03-07 06:09:12 INFO metabase.db :: Checking if Database has unrun migrations...
   2019-03-07T00:09:19.59-0600 [APP/PROC/WEB/0] OUT 03-07 06:09:19 INFO metabase.db :: Database Migrations Current ...  ✅
   2019-03-07T00:09:20.46-0600 [APP/PROC/WEB/0] OUT 03-07 06:09:20 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
   2019-03-07T00:09:20.94-0600 [APP/PROC/WEB/0] OUT 03-07 06:09:20 INFO db.migrations :: Running data migration 'mark-category-fields-as-list'...
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 03-07 06:09:20 ERROR metabase.core :: Metabase Initialization FAILED
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT java.lang.AssertionError: Assert failed: (isa? type-keyword :type/*)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db$type_keyword__GT_descendants.invokeStatic(db.clj:490)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db$type_keyword__GT_descendants.invoke(db.clj:490)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db$isa.invokeStatic(db.clj:516)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db$isa.invoke(db.clj:502)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db.migrations$mark_category_fields_as_list.invokeStatic(migrations.clj:267)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db.migrations$mark_category_fields_as_list.invoke(migrations.clj:265)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:52)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:43)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:72)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:66)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at clojure.lang.Var.invoke(Var.java:377)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:456)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db$run_data_migrations_BANG_.invoke(db.clj:451)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:467)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.db$setup_db_BANG_.doInvoke(db.clj:458)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at clojure.lang.RestFn.invoke(RestFn.java:421)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.core$init_BANG_.invokeStatic(core.clj:162)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.core$init_BANG_.invoke(core.clj:139)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.core$start_normally.invokeStatic(core.clj:246)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.core$start_normally.invoke(core.clj:240)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.core$_main.invokeStatic(core.clj:266)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.core$_main.doInvoke(core.clj:261)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at clojure.lang.RestFn.invoke(RestFn.java:397)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
   2019-03-07T00:09:20.96-0600 [APP/PROC/WEB/0] OUT 	at metabase.core.main(Unknown Source)
   2019-03-07T00:09:21.02-0600 [APP/PROC/WEB/0] OUT 03-07 06:09:20 INFO metabase.core :: Metabase Shutting Down ...
   2019-0
```

Does this look like a bug?  If it's a misconfiguration I can move this over to discourse.

**Comment by flamber** [comment]
Hi @zilkey 
If it works with the Docker/Kubernetes image, but not the direct JAR-file, then it's probably something to do with the Java version used in Cloud Foundry.
Looking at the forum, it seems like a couple of people are using CF, so you can try asking there.

**Comment by zilkey** [comment]
I'll close this issue.  Just for anyone who might arrive here from a search engine, here's what I learned:

The Cloud Foundry Java Buildpack explodes the jar, and then runs its own start command.  That start command sets a classpath, and the classpath does not include all the classes necessary to run the initial migrations.

So the workaround I found was to update the start command to download the jar, then alter the run command to run `java -jar metabase.jar`.  This is an odd solution in the sense that it fully ignores whatever you push, but the command I ended up with looks like this:

```
export START_CMD='curl -s --retry 3 -o "$PWD/metabase.jar" -L "http://downloads.metabase.com/v0.31.2/metabase.jar" && JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.16.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR -XX:ActiveProcessorCount=$(nproc) -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" && CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.13.0_RELEASE -totMemory=$MEMORY_LIMIT -loadedClasses=32215 -poolType=metaspace -stackThreads=250 -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS $CALCULATED_MEMORY" && MALLOC_ARENA_MAX=2 eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -jar $PWD/metabase.jar'

cf push "$APP_NAME" -p any-valid-jar.jar -b https://github.com/cloudfoundry/java-buildpack.git -m 1GB -c "$START_CMD" -u port
```

So I suppose this could be considered a feature request to allow Metabase to be run with the Java buildpack, but since a lot of CF installations support docker now, I'm not sure how valuable that would be.
