### ISSUE TITLE
Migration from H2 to Postgres&MySql fails with TASK_HISTORY not found exception

### ISSUE THREAD

**Issue by h2ri** [metabase/metabase#9537]
### Bug

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: Ubuntu 16.04.5 LTS
- Your databases: H2 and Postgres
- Metabase version: 0.30.3
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

`docker run --name metabase-migration -v /home/report/metabase:/metabase-data -e "MB_DB_FILE=/metabase-data/metabase.db" -e "MB_DB_TYPE=postgres" -e "MB_DB_DBNAME=metabase" -e "MB_DB_PORT=5432" -e "MB_DB_USER=<USERNAME>" -e 'MB_DB_PASS=<PASSWORD>' -e "MB_DB_HOST=<HOSTNAME>" metabase/metabase load-from-h2`

`03-11 15:16:14 INFO metabase.util :: Loading Metabase...
03-11 15:16:14 INFO metabase.util :: Maximum memory available to JVM: 833.3 MB
03-11 15:16:22 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
03-11 15:16:35 INFO metabase.db :: Verifying postgres Database Connection ...
03-11 15:16:38 INFO metabase.db :: Verify Database Connection ...  ✅
03-11 15:16:38 INFO metabase.db :: Running Database Migrations...
03-11 15:16:39 INFO metabase.db :: Setting up Liquibase...
03-11 15:16:40 INFO metabase.db :: Liquibase is ready.
03-11 15:16:40 INFO metabase.db :: Checking if Database has unrun migrations...
03-11 15:16:45 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
03-11 15:16:45 INFO metabase.db :: Migration lock is cleared. Running migrations...
03-11 15:18:07 INFO metabase.db :: Database Migrations Current ...  ✅
Temporarily disabling DB constraints...
[OK]
Transfering 3 instances of Database....[OK]
Transfering 22 instances of User....[OK]
Transfering 13 instances of Setting....[OK]
Transfering 218 instances of Table....[OK]
Transfering 2021 instances of Field..........[OK]
Transfering 700 instances of FieldValues......[OK]
Transfering 539 instances of Revision.....[OK]
Transfering 1951 instances of ViewLog..........[OK]
Transfering 138 instances of Session....[OK]
Transfering 15 instances of Dashboard....[OK]
Transfering 109 instances of Card....[OK]
Transfering 41 instances of DashboardCard....[OK]
Transfering 563 instances of Activity.....[OK]
Transfering 4 instances of Pulse....[OK]
Transfering 15 instances of PulseCard....[OK]
Transfering 4 instances of PulseChannel....[OK]
Transfering 15 instances of PulseChannelRecipient....[OK]
Transfering 7 instances of PermissionsGroup....[OK]
Transfering 44 instances of PermissionsGroupMembership....[OK]
Transfering 20 instances of Permissions....[OK]
Transfering 9 instances of PermissionsRevision....[OK]
Transfering 27 instances of Collection....[OK]
Transfering 1 instances of CollectionRevision....[OK]
org.h2.jdbc.JdbcSQLException: Table "TASK_HISTORY" not found; SQL statement:
SELECT * FROM task_history [42102-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5920)
	at org.h2.command.Parser.readTableFilter(Parser.java:1430)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2138)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2287)
	at org.h2.command.Parser.parseSelectSub(Parser.java:2133)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1946)
	at org.h2.command.Parser.parseSelect(Parser.java:1919)
	at org.h2.command.Parser.parsePrepared(Parser.java:463)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:304)
	at clojure.java.jdbc$prepare_statement.invokeStatic(jdbc.clj:620)
	at clojure.java.jdbc$prepare_statement.invoke(jdbc.clj:567)Command failed with exception: Table "TASK_HISTORY" not found; SQL statement:
SELECT * FROM task_history [42102-197]

	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1017)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1005)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1099)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1056)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1072)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1056)
	at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:141)
	at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:138)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__44049.invoke(load_from_h2.clj:219)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:747)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:730)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:216)
	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:209)
	at clojure.lang.Var.invoke(Var.java:381)
	at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:37)
	at metabase.cmd$load_from_h2.invoke(cmd.clj:30)
	at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:33)
	at metabase.cmd$load_from_h2.invoke(cmd.clj:30)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at metabase.cmd$run_cmd$fn__44225.invoke(cmd.clj:133)
	at metabase.cmd$run_cmd.invokeStatic(cmd.clj:133)
	at metabase.cmd$run_cmd.invoke(cmd.clj:129)
	at clojure.lang.Var.invoke(Var.java:385)
	at metabase.core$run_cmd.invokeStatic(core.clj:256)
	at metabase.core$run_cmd.invoke(core.clj:254)
	at metabase.core$_main.invokeStatic(core.clj:265)
	at metabase.core$_main.doInvoke(core.clj:261)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at metabase.core.main(Unknown Source)`

**Comment by flamber** [comment]
Hi @h2ri 
Are upgrading from 0.30.3 to 0.31.2, while also doing the migration? I would recommend that you do it in two steps, first migrate, then upgrade.
The table `task_history` was added in 0.31.0: https://github.com/metabase/metabase/blob/master/resources/migrations/000_migrations.yaml

**Comment by h2ri** [comment]
Hi @flamber 

It worked
Thank you for the resolution.

**Comment by flamber** [comment]
@h2ri Great! Please close this issue then :+1:

**Comment by camsaul** [comment]
Closing because issue was resolved
