### ISSUE TITLE
socksProxyHost authentication fails

### ISSUE THREAD

**Issue by soorur** [metabase/metabase#9567]
I deployed Metabase to Heroku and I am using quotaGuard Static for Static IP. It offers socks5 proxy. When adding JAVA_TOOL_OPTIONS to Heroku env variable (-DsocksProxyHost=xxx -Djava.net.socks.username="abc" -Djava.net.socks.password="123" ) then authentication still fails.

> 2019-03-14T20:17:26.008574+00:00 app[web.1]: java.net.SocketException: SOCKS : authentication failed
2019-03-14T20:17:26.008576+00:00 app[web.1]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:473)
2019-03-14T20:17:26.008577+00:00 app[web.1]: 	at java.net.Socket.connect(Socket.java:589)
2019-03-14T20:17:26.008579+00:00 app[web.1]: 	at org.postgresql.core.PGStream.<init>(PGStream.java:69)
2019-03-14T20:17:26.008580+00:00 app[web.1]: 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
2019-03-14T20:17:26.008582+00:00 app[web.1]: 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
2019-03-14T20:17:26.008583+00:00 app[web.1]: 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
2019-03-14T20:17:26.008585+00:00 app[web.1]: 	at org.postgresql.Driver.makeConnection(Driver.java:452)
2019-03-14T20:17:26.008586+00:00 app[web.1]: 	at org.postgresql.Driver.connect(Driver.java:254)
2019-03-14T20:17:26.008587+00:00 app[web.1]: 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
2019-03-14T20:17:26.008589+00:00 app[web.1]: 	at java.sql.DriverManager.getConnection(DriverManager.java:208)
2019-03-14T20:17:26.008590+00:00 app[web.1]: 	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:370)
2019-03-14T20:17:26.008591+00:00 app[web.1]: 	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:229)
2019-03-14T20:17:26.008592+00:00 app[web.1]: 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1023)
2019-03-14T20:17:26.008594+00:00 app[web.1]: 	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1005)
2019-03-14T20:17:26.008595+00:00 app[web.1]: 	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1099)
2019-03-14T20:17:26.008596+00:00 app[web.1]: 	at clojure.java.jdbc$query.invoke(jdbc.clj:1056)
2019-03-14T20:17:26.008598+00:00 app[web.1]: 	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1072)
2019-03-14T20:17:26.008599+00:00 app[web.1]: 	at clojure.java.jdbc$query.invoke(jdbc.clj:1056)
2019-03-14T20:17:26.008600+00:00 app[web.1]: 	at metabase.driver.generic_sql$can_connect_QMARK_.invokeStatic(generic_sql.clj:206)
2019-03-14T20:17:26.008601+00:00 app[web.1]: 	at metabase.driver.generic_sql$can_connect_QMARK_.invoke(generic_sql.clj:203)
2019-03-14T20:17:26.008603+00:00 app[web.1]: 	at metabase.driver$fn__29969$G__29722__29976.invoke(driver.clj:106)
2019-03-14T20:17:26.008604+00:00 app[web.1]: 	at metabase.driver$can_connect_with_details_QMARK_$fn__30102.invoke(driver.clj:523)
2019-03-14T20:17:26.008605+00:00 app[web.1]: 	at clojure.core$binding_conveyor_fn$fn__5476.invoke(core.clj:2022)
2019-03-14T20:17:26.008607+00:00 app[web.1]: 	at clojure.lang.AFn.call(AFn.java:18)
2019-03-14T20:17:26.008608+00:00 app[web.1]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-03-14T20:17:26.008609+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-03-14T20:17:26.008611+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-03-14T20:17:26.008612+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:748)

Recommendations?

**Comment by salsakran** [comment]
this sort of question is better asked on our user forum http://discourse.metabase.com
given the number of variables involved, we can't know if it's an actual issue with Metabase or not.

Giving you personalized support for a network issue is beyond the scope of what we can do. 

If you discover that Metabase itself is doing something dumb with this, please chime in and we'll re-open the issue.
