### ISSUE TITLE
Java Exception after upgrade to 0.32.x

### ISSUE THREAD

**Issue by kelsen** [metabase/metabase#9666]
- Metabase version: 0.32.0 or 0.32.1
- Metabase hosting environment: Ubuntu 16.04.6 LTS
- Metabase internal database: MySQL Server version: 5.7.25-0ubuntu0.16.04.2
```
java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

```

After upgrading to 0.32.0 or 0.32.1 metabase won't start, console show this java exception.

Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.core$fn__8478.invokeStatic(core.clj:7060)
        at clojure.core$fn__8478.invoke(core.clj:7055)
        at clojure.core__init.load(Unknown Source)
        at clojure.core__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(java.base@9-internal/Native Method)
        at java.lang.Class.forName(java.base@9-internal/Class.java:378)
        at clojure.lang.RT.classForName(RT.java:2207)
        at clojure.lang.RT.classForName(RT.java:2216)
        at clojure.lang.RT.loadClassForName(RT.java:2235)
        at clojure.lang.RT.load(RT.java:453)
        at clojure.lang.RT.load(RT.java:428)
        at clojure.lang.RT.doInit(RT.java:471)
        at clojure.lang.RT.<clinit>(RT.java:338)
        at clojure.lang.Namespace.<init>(Namespace.java:34)
        at clojure.lang.Namespace.findOrCreate(Namespace.java:176)
        at clojure.lang.Var.internPrivate(Var.java:156)
        at metabase.core.<clinit>(Unknown Source)
Caused by: java.lang.NoSuchMethodException: no such method: java.lang.reflect.Method.canAccess(Object)boolean/invokeVirtual
        at java.lang.invoke.MemberName.makeAccessException(java.base@9-internal/MemberName.java:929)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(java.base@9-internal/MemberName.java:1046)
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(java.base@9-internal/MethodHandles.java:1683)
        at java.lang.invoke.MethodHandles$Lookup.findVirtual(java.base@9-internal/MethodHandles.java:939)
        at clojure.lang.Reflector.<clinit>(Reflector.java:38)
        ... 17 more
Caused by: java.lang.NoSuchMethodError: java.lang.reflect.Method.canAccess(Ljava/lang/Object;)Z
        at java.lang.invoke.MethodHandleNatives.resolve(java.base@9-internal/Native Method)
        at java.lang.invoke.MemberName$Factory.resolve(java.base@9-internal/MemberName.java:1018)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(java.base@9-internal/MemberName.java:1043)
        ... 20 more

**Comment by camsaul** [comment]
Hey @kelsen Java 9 was EOL'ed over a year ago. I run Metabase every day with OpenJDK 11 and don't have any issues so I'd recommend giving that a try instead.

**Comment by kelsen** [comment]
The issue was resolved after upgrading to Java 11.
Thank you @camsaul
