### ISSUE TITLE
JDBC connection URI when migrating H2 to MySQL

### ISSUE THREAD

**Issue by Microsheep** [metabase/metabase#9748]
In the documents for [Configuring the Metabase Application Database](https://metabase.com/docs/latest/operations-guide/start.html#configuring-the-metabase-application-database) there is an option to use a full JDBC connection URI to setup the database connection.

But when migrating from H2 database to MySQL Database by the [Migrating from using the H2 database to MySQL or Postgres](https://metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres) it does not state that using a full JDBC connection URI is possible.

I tried using a full JDBC connection URI like the following
```
MB_DB_CONNECTION_URI="mysql://XXX.XXX.XXX.XXX:3306/metabase?user=<username>&password=<password>" java -jar metabase.jar load-from-h2 /.../metabase.db
```

Metabase Version: 0.31.2

It will produce the following errors
```
Transfering 10 instances of Database...java.lang.IllegalArgumentException: No matching clause: :h2
        at metabase.cmd.load_from_h2$insert_entity_BANG_.invokeStatic(load_from_h2.clj:115)
        at metabase.cmd.load_from_h2$insert_entity_BANG_.invoke(load_from_h2.clj:108)
        at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:144)
        at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:138)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__44049.invoke(load_from_h2.clj:219)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:747)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:730)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:717)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:216)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:209)
        at clojure.lang.Var.invoke(Var.java:381)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:37)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:30)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.core$apply.invoke(core.clj:652)
        at metabase.cmd$run_cmd$fn__44225.invoke(cmd.clj:133)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:133)
        at metabase.cmd$run_cmd.invoke(cmd.clj:129)
        at clojure.lang.Var.invoke(Var.java:385)
        at metabase.core$run_cmd.invokeStatic(core.clj:256)
        at metabase.core$run_cmd.invoke(core.clj:254)
        at metabase.core$_main.invokeStatic(core.clj:265)
        at metabase.core$_main.doInvoke(core.clj:261)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Command failed with exception: No matching clause: :h2
```

This issue is bypassed if I define all the variables
```
MB_DB_TYPE=mysql
MB_DB_DBNAME=metabase
MB_DB_PORT=3306
MB_DB_USER=XXX
MB_DB_PASS=XXX
MB_DB_HOST=XXX
java -jar metabase.jar load-from-h2 /.../metabase.db
```

After searching on the web I found some other users had similar problems when migrating.
- https://discourse.metabase.com/t/0-30-0-done-error-migrating-from-h2-to-mysql/1599/8
- https://github.com/metabase/metabase/issues/9234
- https://www.cnblogs.com/Dy1an/p/10623086.html

So I think I will also add this issue here.

**Comment by camsaul** [comment]
Not 100% sure why that wouldn't work. After looking at the source code for the old version I can't see a reason why it shouldn't off the top of my head.

I made some fixes to code related to this functionality as part of 0.32.x so I'd be interested to see if trying this on Metabase 0.32.3+ fixes the problem

**Comment by Microsheep** [comment]
@camsaul Confirmed that after upgrading to 0.32.4 will fix this.
