### ISSUE TITLE
metabase with proxysql don't Initializing driver mysql 

### ISSUE THREAD

**Issue by SilentNess** [metabase/metabase#9774]
Hi! 
I use metabase with proxysql database.

Now, I try to update from version v0.31.0 to v0.32.4 and have the problem. 
I hope you will help to solve the problem.

LOG: 
 export MB_DB_TYPE=mysql
 export MB_DB_DBNAME=metabase
 export MB_DB_USER=metabase
 export MB_DB_PASS=****pass****
 export MB_DB_PORT=6033
 export MB_DB_HOST=127.0.0.1
 export MB_DB_SSL="false"
 export MB_JETTY_PORT=3001
 export MB_JETTY_HOST=10.**.64.**
 export MB_EMOJI_IN_LOGS="false"
 export MB_PLUGINS_DIR="/usr/local/metabase/plugins/"

 java -jar /usr/local/metabase/metabase.jar
log4j:ERROR Could not find value for key log4j.appender.metabase
log4j:ERROR Could not instantiate appender named "metabase".
04-12 15:14:52 INFO metabase.util :: Loading Metabase...
04-12 15:14:52 INFO metabase.util :: Maximum memory available to JVM: 3.5 GB
04-12 15:14:55 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance.
 For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
04-12 15:14:57 INFO metabase.driver :: Registered abstract driver :sql
04-12 15:15:01 INFO metabase.core :: Starting Metabase in STANDALONE mode
04-12 15:15:02 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
 {:port 3001, :host "10.**.64.**"}

04-12 15:15:02 INFO metabase.core :: Starting Metabase version v0.32.4 (f4dc152 release-0.32.0) ...
04-12 15:15:02 INFO metabase.core :: System timezone is 'Europe/Moscow' ...
04-12 15:15:02 INFO metabase.plugins :: Loading plugins in /usr/local/metabase/plugins...
04-12 15:15:02 DEBUG plugins.classloader :: Setting current thread context classloader to NEWLY CREATED classloader clojure.lang.DynamicClassLoader@4c499190...
04-12 15:15:02 INFO plugins.classloader :: Added URL file:/usr/local/metabase/plugins/ojdbc8.jar to classpath
04-12 15:15:02 INFO plugins.classloader :: Added URL file:/usr/local/metabase/plugins/metabase-sparksql-deps-1.2.1.spark2-standalone.jar to classpath
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
04-12 15:15:03 INFO metabase.driver :: Registered abstract driver :sql-jdbc (parents: :sql)
Load driver :sql-jdbc took 61 ms
04-12 15:15:03 INFO metabase.driver :: Registered driver :sqlite (parents: #{:sql-jdbc})
04-12 15:15:03 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? true
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :oracle...
04-12 15:15:03 INFO metabase.driver :: Registered driver :oracle (parents: #{:sql-jdbc})
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
04-12 15:15:03 INFO metabase.driver :: Registered driver :druid
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
04-12 15:15:03 INFO metabase.driver :: Registered driver :postgres (parents: :sql-jdbc)
Load driver :postgres took 32 ms
04-12 15:15:03 INFO metabase.driver :: Registered driver :redshift (parents: #{:postgres})
04-12 15:15:03 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

04-12 15:15:03 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
04-12 15:15:03 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver"]
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
04-12 15:15:03 INFO metabase.driver :: Registered abstract driver :hive-like (parents: #{:sql-jdbc})
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
04-12 15:15:03 INFO metabase.driver :: Registered driver :sparksql (parents: #{:hive-like})
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :presto...
04-12 15:15:03 INFO metabase.driver :: Registered driver :presto (parents: #{:sql})
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :google...
04-12 15:15:03 INFO metabase.driver :: Registered abstract driver :google
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
04-12 15:15:03 INFO metabase.driver :: Registered driver :sqlserver (parents: #{:sql-jdbc})
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
04-12 15:15:03 INFO metabase.driver :: Registered driver :snowflake (parents: #{:sql-jdbc})
04-12 15:15:03 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
04-12 15:15:03 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery...
04-12 15:15:03 INFO metabase.driver :: Registered driver :bigquery (parents: #{:sql :google})
04-12 15:15:03 INFO plugins.dependencies :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
04-12 15:15:03 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
04-12 15:15:03 INFO metabase.driver :: Registered driver :googleanalytics (parents: #{:google})
04-12 15:15:03 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
04-12 15:15:03 INFO metabase.driver :: Registered driver :mongo
04-12 15:15:04 INFO metabase.driver :: Registered driver :mysql (parents: :sql-jdbc)
Load driver :mysql took 22 ms
04-12 15:15:04 INFO metabase.driver :: Registered driver :h2 (parents: :sql-jdbc)
Load driver :h2 took 17 ms
04-12 15:15:04 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
04-12 15:15:04 INFO metabase.db :: Verifying mysql Database Connection ...
04-12 15:15:04 INFO metabase.driver :: Initializing driver :sql...
04-12 15:15:04 INFO metabase.driver :: Initializing driver :sql-jdbc...
04-12 15:15:04 INFO metabase.driver :: Initializing driver :mysql...
04-12 15:15:04 ERROR metabase.core :: Metabase Initialization FAILED
java.lang.Exception: java.sql.SQLNonTransientConnectionException: unexpected end of stream, read 0 bytes from 7 (socket was closed by server)
        at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:34)
        at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:18)
        at clojure.lang.RestFn.invoke(RestFn.java:442)
        at clojure.lang.Var.invoke(Var.java:393)
        at metabase.db$verify_db_connection$fn__14460.invoke(db.clj:403)
        at metabase.db$verify_db_connection.invokeStatic(db.clj:401)
        at metabase.db$verify_db_connection.invoke(db.clj:394)
        at metabase.db$verify_db_connection.invokeStatic(db.clj:397)
        at metabase.db$verify_db_connection.invoke(db.clj:394)
        at metabase.db$setup_db_BANG_$fn__14477.invoke(db.clj:467)
        at metabase.util$do_with_us_locale.invokeStatic(util.clj:683)
        at metabase.util$do_with_us_locale.invoke(util.clj:669)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:466)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:460)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:72)
        at metabase.core$init_BANG_.invoke(core.clj:51)
        at metabase.core$start_normally.invokeStatic(core.clj:118)
        at metabase.core$start_normally.invoke(core.clj:112)
        at metabase.core$_main.invokeStatic(core.clj:138)
        at metabase.core$_main.doInvoke(core.clj:133)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.sql.SQLNonTransientConnectionException: unexpected end of stream, read 0 bytes from 7 (socket was closed by server)
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at clojure.core$deref_future.invokeStatic(core.clj:2302)
        at clojure.core$future_call$reify__8439.deref(core.clj:6974)
        at clojure.core$deref.invokeStatic(core.clj:2324)
        at clojure.core$deref.invoke(core.clj:2306)
        at metabase.util$deref_with_timeout.invokeStatic(util.clj:326)
        at metabase.util$deref_with_timeout.invoke(util.clj:323)
        at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:29)
        ... 24 more
Caused by: java.sql.SQLNonTransientConnectionException: unexpected end of stream, read 0 bytes from 7 (socket was closed by server)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:234)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1199)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:560)
        at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:174)
        at org.mariadb.jdbc.Driver.connect(Driver.java:92)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
        at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1093)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1142)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:123)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:118)
        at metabase.driver.sql_jdbc$fn__61786.invokeStatic(sql_jdbc.clj:39)
        at metabase.driver.sql_jdbc$fn__61786.invoke(sql_jdbc.clj:38)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.driver.util$can_connect_with_details_QMARK_$fn__16675.invoke(util.clj:30)
        at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: unexpected end of stream, read 0 bytes from 7 (socket was closed by server)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.handleIoException(AbstractQueryProtocol.java:1888)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1429)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1407)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.readPipelineAdditionalData(AbstractConnectProtocol.java:657)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:535)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1195)
        ... 27 more
Caused by: java.io.EOFException: unexpected end of stream, read 0 bytes from 7 (socket was closed by server)
        at org.mariadb.jdbc.internal.io.input.DecompressPacketInputStream.readBlocking(DecompressPacketInputStream.java:195)
        at org.mariadb.jdbc.internal.io.input.DecompressPacketInputStream.getPacketArray(DecompressPacketInputStream.java:117)
        at org.mariadb.jdbc.internal.io.input.DecompressPacketInputStream.getPacket(DecompressPacketInputStream.java:97)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1427)
        ... 31 more
04-12 15:15:04 INFO metabase.core :: Metabase Shutting Down ...
04-12 15:15:04 INFO metabase.core :: Metabase Shutdown COMPLETE

**Comment by flamber** [comment]
Hi @SilentNess 
Which version of ProxySQL?
It says `socket was closed by server`, so could you also check the logs on ProxySQL and real database?
It looks like there's some issues between ProxySQL and MariaDB Connector/J:
https://github.com/sysown/proxysql/issues?q=is%3Aissue+is%3Aopen+jdbc+mariadb

**Comment by SilentNess** [comment]
ProxySQL version 1.4.14-28-g0f6701c, codename Truls

**Comment by SilentNess** [comment]
I did a test and added to "Additional JDBC connection string options" in web-interface of metabase parameters "usePipelineAuth=false" and it works through proxysql.

Is there any way to pass this parameter to system config for example:

Like: 
export MB_DB_DBNAME=metabase
export MB_DB_USER=metabase
export MB_DB_JDBC_PARAMETERS="usePipelineAuth=false"

Or maybe it can be set as the default connection parameter for the system database?

**Comment by flamber** [comment]
@SilentNess 
Yes, by using the `MB_DB_CONNECTION_URI` instead of separated envvars.
https://metabase.com/docs/latest/operations-guide/start.html#mysql
And please close this issue, if that fixes it for you :+1:

**Comment by SilentNess** [comment]
In version v0.32.0 application has started. But there is the problem with Initializing task:
SyncDatabases
CheckForNewVersions
SendAnonymousUsageStats
SendAbandomentEmails
SendPulses
SendFollowUpEmails
TaskHistoryCleanup

What you can find in "log_file_ v0.32.0_with_Initializing task error.txt"

I updated Metabase to v0.32.4 and this problem was fixed.
Thanks for the help!
[log_file_ v0.32.0_with_Initializing task error.txt](https://github.com/metabase/metabase/files/3083976/log_file_.v0.32.0_with_Initializing.task.error.txt)
