### ISSUE TITLE
Unable to migrate from H2 to Mysql

### ISSUE THREAD

**Issue by Shra25** [metabase/metabase#9786]
Message: (conn=222) Incorrect string value: '\xE2\x86\x94 "]' for column 'values' at row 1
 SQLState: HY000
 Error Code: 1366
java.sql.BatchUpdateException: (conn=222) Incorrect string value: '\xE2\x86\x94 "]' for column 'values' at row 1
        at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:289)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeBatch(MariaDbPreparedStatementClient.java:306)
        at clojure.java.jdbc$execute_batch.invokeStatic(jdbc.clj:591)
        at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:584)
        at clojure.java.jdbc$db_do_execute_prepared_statement$fn__12510.invoke(jdbc.clj:1039)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:842)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:1038)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:1024)
        at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:1062)
        at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:1042)
        at clojure.java.jdbc$insert_cols_BANG_.invokeStatic(jdbc.clj:1576)
        at clojure.java.jdbc$insert_cols_BANG_.invoke(jdbc.clj:1567)
        at clojure.java.jdbc$insert_multi_BANG_.invokeStatic(jdbc.clj:1633)
        at clojure.java.jdbc$insert_multi_BANG_.invoke(jdbc.clj:1601)
        at metabase.cmd.load_from_h2$insert_entity_BANG_$fn__47368.invoke(load_from_h2.clj:141)
        at metabase.cmd.load_from_h2$insert_entity_BANG_.invokeStatic(load_from_h2.clj:140)
        at metabase.cmd.load_from_h2$insert_entity_BANG_.invoke(load_from_h2.clj:123)
        at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:154)
        at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:148)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__47488.invoke(load_from_h2.clj:235)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:228)
        at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:220)
        at clojure.lang.Var.invoke(Var.java:384)
        at metabase.cmd$load_from_h2.invokeStatic(cmd.clj:37)
        at metabase.cmd$load_from_h2.invoke(cmd.clj:30)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.cmd$run_cmd$fn__53180.invoke(cmd.clj:140)
        at metabase.cmd$run_cmd.invokeStatic(cmd.clj:140)
        at metabase.cmd$run_cmd.invoke(cmd.clj:136)
        at clojure.lang.Var.invoke(Var.java:388)
        at metabase.core$run_cmd.invokeStatic(core.clj:128)
        at metabase.core$run_cmd.invoke(core.clj:126)
        at metabase.core$_main.invokeStatic(core.clj:137)
        at metabase.core$_main.doInvoke(core.clj:133)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at metabase.core.main(Unknown Source)
Caused by: java.sql.SQLException: (conn=222) Incorrect string value: '\xE2\x86\x94 "]' for column 'values' at row 1
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:255)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
        at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:286)
        ... 47 more
Caused by: java.sql.SQLException: Incorrect string value: '\xE2\x86\x94 "]' for column 'values' at row 1
Query is: INSERT INTO metabase_fieldvalues ( `id`, `created_at`, `updated_at`, `values`, `human_readable_values`, `field_id` ) VALUES ( 1513, '2018-10-09 18:09:47.375', '2018-11-16 18:23:24.457', '["Constant ↔ "]', <null>, 4656 )
java thread: MariaDb-bulk-4
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:126)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol$1.handleResultException(AbstractQueryProtocol.java:625)
        at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:142)
        at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:66)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Command failed with exception: (conn=222) Incorrect string value: '\xE2\x86\x94 "]' for column 'values' at row 1

**Comment by exabrial** [comment]
possible duplicate: https://github.com/metabase/metabase/issues/9741

**Comment by camsaul** [comment]
Hi, could you fill out the bug questionnaire so we can get a little more info so we can diagnose this issue?

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

**Comment by AntonTsaberyaby** [comment]
@Shra25 Hello,
I had the same issue

I run mysql server with 
`mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci`

It helped me

**Comment by camsaul** [comment]
Combining this issue into #10691
