### ISSUE TITLE
There are no errors in compiling Metabase 0.32.0 in the same environment, but the following errors occur in compiling 0.32.7

### ISSUE THREAD

**Issue by lttzsk** [metabase/metabase#9941]
Build: sparksql
Checksum has changed.
Verifying sparksql driver...
Checking whether resources/modules/sparksql.metabase-driver.jar exists....
File does not exist. Driver verification failed.
No existing build, or existing build is invalid. (Re)building driver.
Deleting old versions of sparksql driver...
metabase-core already installed to local Maven repo.
Metabase uberjar already built.
Building parent drivers (if needed)...
Building sparksql driver...
WARNING: You have $CLASSPATH set, probably by accident.
It is strongly recommended to unset this before proceeding.
WARNING: You have $CLASSPATH set, probably by accident.
It is strongly recommended to unset this before proceeding.
Leiningen's classpath: .:/usr/java/jdk1.8.0_131/lib:/usr/java/jdk1.8.0_131/jre/lib::/root/.lein/self-installs/leiningen-2.9.1-standalone.jar
Applying task uberjar to []
Could not find artifact jdk.tools:jdk.tools:jar:1.8 at specified path /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-7.b13.el7.x86_64/jre/../lib/tools.jar
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
clojure.lang.ExceptionInfo: Could not resolve dependencies {:suppress-msg true, :exit-code 1}
        at leiningen.core.classpath$get_dependencies_STAR_.invokeStatic(classpath.clj:312)
        at leiningen.core.classpath$get_dependencies_STAR_.invoke(classpath.clj:266)
        at clojure.lang.AFn.applyToHelper(AFn.java:165)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$memoize$fn__6862.doInvoke(core.clj:6353)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at leiningen.core.classpath$get_dependencies$fn__6105.invoke(classpath.clj:333)
        at leiningen.core.classpath$get_dependencies.invokeStatic(classpath.clj:331)
        at leiningen.core.classpath$get_dependencies.doInvoke(classpath.clj:325)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$apply.invoke(core.clj:660)
        at leiningen.core.classpath$resolve_managed_dependencies.invokeStatic(classpath.clj:444)
        at leiningen.core.classpath$resolve_managed_dependencies.doInvoke(classpath.clj:431)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at leiningen.core.eval$prep.invokeStatic(eval.clj:85)
        at leiningen.core.eval$prep.invoke(eval.clj:73)
        at leiningen.jar$build_jar.invokeStatic(jar.clj:286)
        at leiningen.jar$build_jar.invoke(jar.clj:283)
        at leiningen.jar$main_jar.invokeStatic(jar.clj:295)
        at leiningen.jar$main_jar.invoke(jar.clj:291)
        at leiningen.jar$jar.invokeStatic(jar.clj:346)
        at leiningen.jar$jar.invoke(jar.clj:328)
        at leiningen.uberjar$uberjar$fn__10301.invoke(uberjar.clj:167)
        at leiningen.uberjar$uberjar.invokeStatic(uberjar.clj:167)
        at leiningen.uberjar$uberjar.invoke(uberjar.clj:143)
        at leiningen.uberjar$uberjar.invokeStatic(uberjar.clj:187)
        at leiningen.uberjar$uberjar.invoke(uberjar.clj:143)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at leiningen.core.main$partial_task$fn__6592.doInvoke(main.clj:284)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:660)
        at leiningen.core.main$apply_task.invokeStatic(main.clj:334)
        at leiningen.core.main$apply_task.invoke(main.clj:320)
        at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:343)
        at leiningen.core.main$resolve_and_apply.invoke(main.clj:336)
        at leiningen.core.main$_main$fn__6681.invoke(main.clj:452)
        at leiningen.core.main$_main.invokeStatic(main.clj:442)
        at leiningen.core.main$_main.doInvoke(main.clj:439)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.main$main_opt.invokeStatic(main.clj:491)
        at clojure.main$main_opt.invoke(main.clj:487)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact jdk.tools:jdk.tools:jar:1.8 at specified path /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-7.b13.el7.x86_64/jre/../lib/tools.jar
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:355)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102)
        at cemerick.pomegranate.aether$resolve_dependencies_STAR_.invokeStatic(aether.clj:806)
        at cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke(aether.clj:707)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at cemerick.pomegranate.aether$resolve_dependencies.invokeStatic(aether.clj:815)
        at cemerick.pomegranate.aether$resolve_dependencies.doInvoke(aether.clj:809)
        at clojure.lang.RestFn.invoke(RestFn.java:2793)
        at leiningen.core.classpath$get_dependencies_STAR_.invokeStatic(classpath.clj:274)
        ... 60 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact jdk.tools:jdk.tools:jar:1.8 at specified path /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-7.b13.el7.x86_64/jre/../lib/tools.jar
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:338)
        ... 75 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact jdk.tools:jdk.tools:jar:1.8 at specified path /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-7.b13.el7.x86_64/jre/../lib/tools.jar
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:264)
        ... 77 more
Uberjar aborting because jar failed: Could not resolve dependencies
Error: could not find /opt/metabase-0.32.7/modules/drivers/sparksql/target/uberjar/sparksql.metabase-driver.jar. Build failed.
./bin/build-driver.sh: 第 157 行:return: -3: 无效选项
return: 用法:return [n]

**Comment by flamber** [comment]
This has been discussed in a very long thread in the forum - was probably because not using OracleJDK:
https://discourse.metabase.com/t/logon-authentication-and-support-for-multiple-users/6284
